### ISSUE TITLE
Move workflow archival from ReqMgr2 CherryPy to MSRuleCleaner

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10018]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
Once we have the MSRuleCleaner developed It will be the service to take care  of the final workflow status transition to `{normal, aborted, rejected}-archived`, which means we will need to remove the logic from the CherryPy thread which is currently dealing with that. The place where the change should happen is here  [1].

[1]
https://github.com/dmwm/WMCore/blob/5961d2229b1e548e58259c06af154f33bce36c68/src/python/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py#L101
 

**Describe the solution you'd like**
Let MSRuleCleaner take care of this status transition. and remove the code from StatusChangeTasks.py

**Describe alternatives you've considered**
No allternative

**Additional context**
No

**Comment by haozturk** [comment]
Hello @todor-ivanov @amaltaro I see that this issue is closed, but I have something to add here:
In Unified, we have [this issue](https://github.com/CMSCompOps/WmAgentScripts/issues/704) to address the output cleanup for aborted/rejected workflows. Last week in P&R Dev meeting, we thought that this WMCore issue could be the correct place to address this feature. What do you think about it?

**Comment by amaltaro** [comment]
@haozturk Hasan, I think that Unified issue can be closed then. MSRuleCleaner has already been deployed in production and it's deleting all the rucio rules found for the output datasets, made under the rucio account used by WMAgents `wma_prod`.
It does not use what you called as "rucio erase" though, MSRuleCleaner simply deletes a given rule id from Rucio.

**Comment by haozturk** [comment]
@amaltaro thanks for your comment. One question to be on the same page: Does MSRuleCleaner invalidate outputs at DBS and deletes the rules at Rucio for workflows that are rejected/aborted in a state before the archival? So, for instance, does it cover the case where the workflow is rejected after the `announced` state?

**Comment by todor-ivanov** [comment]
Hi @haozturk, the immediate answer is No. I know we had the long discussion in the P&R dev meeting a week ago about this use case and the eventual race condition that we may face in case we want to invalidate also datasets which already have rules on tape, but we somehow missed to reflect that at least with a comment in the current issue (it is my fault I would say).  But anyway, this one just went through and is already in testbed. So we should consider a dedicated issue just for those workflows which meet the conditions:
   * They follow the path `announced` -> `rejected`
   * They already have rules for datasets on tape which needs to be invalidated

I would say even though we missed to put that exact check in the current version of the service, we are still safe since the path `announced` -> `rejected` itself is one that should be triggered by a manual intervention and it should not be that often, hence the person who is triggering it could also (for the time being) make the proper check for rules on tape.     

Upon a second thought, we may even have an issue which is covering also this use case and is the next one to work on [1].
Maybe just a comment there giving some details will be enough too.

[1]
https://github.com/dmwm/WMCore/issues/10027
