### ISSUE TITLE
Investigate ReproducibleSeeding PSet tweaking

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10019]
**Impact of the bug**
PSet for ReproducibleSeeding random seed service might not be working as expected.

**Describe the bug**
Unless I'm missing something, it looks like ReproducibleSeeding, when chosen... doesn't pick the initialSeed from the jobBag object, but rather from the original Pset itself (meaning no change).

**How to reproduce it**
Not sure, as this has only looked at in the code. Run a Relval with this option, perhaps?

**Expected behavior**
I think the jobBag object should have the initial seed parameters, which we are supposed to put in the Pset tweak object.

**Additional context and error message**
This issue was raised by Davil Lange via email

This line here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L311

to me it looks like it should be this:
```
randService = self.jobBag.process.RandomNumberGeneratorService
```
I couldn't find any workflow running using `ReproducibleSeeding` though, all of them seemed to use `AutomaticSeeding` instead. Apparently, this could be used in RelVal. 
Any comments on this?
Are we missing something when reading the code, or is this a bug that needs to be fixed as above?

**Comment by khurtado** [comment]
When `ReproducibleSeeding` is set manually, the code fails with:

```
'Service' object is not iterableDetails:
  File "/tmpscratch/users/khurtado/work/job-unpacked/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 109, in <module>
  File "/tmpscratch/users/khurtado/work/job-unpacked/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 80, in invoke
  File "/tmpscratch/users/khurtado/work/job-unpacked/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 806, in __call__
    self.handleSeeding()
  File "/tmpscratch/users/khurtado/work/job-unpacked/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 314, in handleSeeding
    for x in randService:


        Stderr: None
```

I think this makes sense, because it seems the original Pset RandomNumberGeneratorService is not iterable, but the one coming from the jobBag, which is created via this DataStruct job method is.

So, I am in favor of using the proposed change:

````
randService = self.jobBag.process.RandomNumberGeneratorService
```
for the new implementation instead.

**Comment by amaltaro** [comment]
@khurtado Kenyi, just so we have reference for the future, could you please say a few words here on what was the agreement we had concerning this feature?
