### ISSUE TITLE
Account for Tape Rule Status in MSRuleCleaner

### ISSUE THREAD

**Issue by klannon** [dmwm/WMCore#10027]
**Impact of the new feature**
Currently MSRuleCleaner removes rules without consideration of the status of tape rules made in MSOutput.  Here I request MSRuleCleaner pay attention to tape rule status to avoid deleting the source of unapproved tape rules.

**Is your feature request related to a problem? Please describe.**
Yes!  If MSRuleCleaner deletes a disk rule that is the only protection for source data for a tape rule that hasn't been approved yet, then Rucio may delete that data before the rule gets approved.

**Describe the solution you'd like**
In the Rucio Transition meeting, we discussed the possibilty of using Rucio's "child rule" mechanism to link the disk and tape rule.  Alternatively if we had a way to query or remember the tape rules made for this dataset, we could check manually.  Either solution would be fine.

**Describe alternatives you've considered**
We could ignore the possibility of accidental deletion of tape rule source data and just hope that tape rules always get approved before the data disappears.  We could also lobby the Rucio development team to change the behavior so that unapproved tape rules still have some kind of data protection.  This has its own can of worms though.

**Additional context**
We also discussed the possibility of trying to catch rejected tape rules here, but I don't think we should get hung up on that.

**Comment by amaltaro** [comment]
Thanks for creating this issue Kevin.

We could have one special case here where the output dataset didn't get a Tape rule created, from the unified configuration (tiers_with_no_custodial):
https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L213

so my question is, what should we do if there are no tape rules locking/archiving a given output dataset? Should we still delete all the rules created by WMAgent (block-level and the dual container level), thus relying only on the - possible - Disk rule created by MSOutput? Or perhaps we should revise that list of tiers without Tape subscription and make sure all the production output datasets have a correspondent Tape data placement (but RelVals)?

Maybe @nsmith- has a strong opinion here too.

**Comment by nsmith-** [comment]
Personally I think that if no MSOutput rules cover the dataset, there was a mistake in the workflow creation to have that data tier written out. We have seen such issues in the past. For RelVal, this is expected but as I understand the MSOutput rule for RelVal would have a lifetime >>30d right? We should discuss what that lifetime is, but RelVal is assumed to be removed from disk after a reasonable time and doesn't need tape archiving.

**Comment by amaltaro** [comment]
> Personally I think that if no MSOutput rules cover the dataset, there was a mistake in the workflow creation to have that data tier written out.

Okay, it means then that if there is no tape rule, we can still delete those rules created by WMAgent.

> For RelVal, this is expected but as I understand the MSOutput rule for RelVal would have a lifetime >>30d right?

That's incorrect. We do not have a different lifetime setting for RelVal output disk rules created by MSOutput.
If we need to have that, please clarify what the lifetime should be and we can implement it for the upgrade in the next week.

**Comment by nsmith-** [comment]
We should eventually make all the MSOutput rules configurable via campaign (or even workflow) as discussed in #9639
In the meantime, based on http://dynamo.mit.edu/data/detox/policy?cycle=37788 I think 12 months is the current default for RelVal. @dr-stringfellow may have some input.

**Comment by amaltaro** [comment]
@nsmith- @dr-stringfellow let me suggest to follow up this lifetime discussion here: https://github.com/dmwm/WMCore/issues/10039
Thanks!

**Comment by todor-ivanov** [comment]
Just a side note while looking deeper into this. I just made a snapshot of all the tape rules created by `wmcore_output` account and the by status and site: [1]. So the possible statuses we should consider are: 
```
{REPLICATING, STUCK, SUSPENDED, WAITING_APPROVAL}
```
Thinking of all those statuses as transient and leaving status `OK` aside.

Maybe @amaltaro or @nsmith- my correct me here, before I run into the wrong direction. 

[1]
```
      1 ACCOUNT     STATE    RSE_EXPRESSION
       ------------- ------------------------- -------------------------------------------
   1593 wmcore_output OK  T0_CH_CERN_Tape
    825 wmcore_output OK  T1_DE_KIT_Tape
    121 wmcore_output OK  T1_ES_PIC_Tape
    658 wmcore_output OK  T1_FR_CCIN2P3_Tape
    966 wmcore_output OK  T1_IT_CNAF_Tape
    307 wmcore_output OK  T1_RU_JINR_Tape
    226 wmcore_output OK  T1_UK_RAL_Tape
   2483 wmcore_output OK  T1_US_FNAL_Tape
    412 wmcore_output REPLICATING  T0_CH_CERN_Tape
      8 wmcore_output REPLICATING  T1_DE_KIT_Tape
      2 wmcore_output REPLICATING  T1_ES_PIC_Tape
     40 wmcore_output REPLICATING  T1_FR_CCIN2P3_Tape
     30 wmcore_output REPLICATING  T1_IT_CNAF_Tape
     12 wmcore_output REPLICATING  T1_RU_JINR_Tape
      1 wmcore_output REPLICATING  T1_UK_RAL_Tape
    391 wmcore_output REPLICATING  T1_US_FNAL_Tape
     70 wmcore_output STUCK  T0_CH_CERN_Tape
     12 wmcore_output STUCK  T1_DE_KIT_Tape
      9 wmcore_output STUCK  T1_FR_CCIN2P3_Tape
     16 wmcore_output STUCK  T1_IT_CNAF_Tape
      2 wmcore_output STUCK  T1_RU_JINR_Tape
     13 wmcore_output STUCK  T1_US_FNAL_Tape
      2 wmcore_output SUSPENDED  T0_CH_CERN_Tape
      1 wmcore_output SUSPENDED  T1_DE_KIT_Tape
      2 wmcore_output SUSPENDED  T1_FR_CCIN2P3_Tape
      3 wmcore_output SUSPENDED  T1_IT_CNAF_Tape
      5 wmcore_output SUSPENDED  T1_US_FNAL_Tape
      2 wmcore_output WAITING_APPROVAL  T1_DE_KIT_Tape
    324 wmcore_output WAITING_APPROVAL  T1_US_FNAL_Tape
```

**Comment by amaltaro** [comment]
Todor, for this issue I would say that we check the status of the tape rule only without caring too much whether the same thing is repetitive or not.
If the rule state is different than `OK`, then we do not delete any rules for that given container; and create a proper log record with the workflow name, container name and rule state.
If the tape rule state is `OK`, then we proceed with the normal output rules cleanup.

Perhaps we could create another issue to create an alert if a tape rule is found in a given state, or in a given state for more than X days? We better consult the DM team first to see if this is really needed though.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro, I am pretty sure you may be right here. But just to be 100% sure, I'd need a confirmation (maybe from somebody from DM team), which of those statuses are 'terminal' and which are 'transient'. The ones I am mostly concerned are:

* `STUCK`
* `SUSPENDED`

Because I wouldn't be very happy to rely only on an alarm, triggered after a period of lack of a state change (which all by itself would be difficult to measure since the MSRulecleaner is stateless), when it is obvious from the very beginning that this won't move anywhere and the proper decision should be taken right once the state is spotted. 
Moreover, if we keep such workflows uncleaned for a period of time longer than the time while the workflow is visible in the centralDB we may end up with workflows uncleaned and not archived. And so those rules in Rucio would needs to be taken care of by some other means in combination with all the regular rules left behind from the same vanishing workflow, which would be already very difficult to find/track.

**Comment by nsmith-** [comment]
`STUCK` rules will be periodically retried by rucio. `SUSPENDED` is a terminal state unless manual intervention move the rule back to `STUCK` (where it will again start to periodically retry). All rules have a `updated_at` field that lets you know how long they have been in a given state. DM ops should be querying for the rules you identified that are suspended and do some intervention as necessary. I don't think its a WM responsibility to alert for such cases. The queries are straightforward:
```python
In [1]: from rucio.client import Client

In [2]: client = Client()

In [3]: suspended_rules = list(client.list_replication_rules(filters={"account": "wmcore_output", "state": "U"}))

In [4]: import pandas as pd

In [5]: pd.json_normalize(suspended_rules).groupby("rse_expression").size()
Out[5]:
rse_expression
T0_CH_CERN_Tape       2
T1_DE_KIT_Tape        1
T1_FR_CCIN2P3_Tape    2
T1_IT_CNAF_Tape       3
T1_US_FNAL_Tape       5
dtype: int64

In [6]: import datetime

In [7]: from rucio.common.utils import date_to_str

In [8]: old_stuck_rules = list(client.list_replication_rules(filters={"account": "wmcore_output", "state": "S", "updated_before": date_to_str(datetime.datetime.utcnow() - datetime.timedelta(days=14))}))

In [9]: pd.json_normalize(old_stuck_rules)
Out[9]:
Empty DataFrame
Columns: []
Index: []
```

**Comment by FernandoGarzon** [comment]
Hello

These are the suspended rules. Their status will be changed to stuck and in 24 hours I'll check how they are going.

226F8D370C214F0B8C446C3961F12E7A
8B583E42D25D4888A9B4825624F52792
8FD38DF46B1B4B599582C6F93E3CA5ED
DA0EC46BD7954DF7A2F7C7334BFAEDFD
41B870CDEDC6464B843D1614C7B474C0
FF61CB3E79364449A2F90300A9B758EF
52E2D4427F2A453E9BFAB4C01119CD49
1EDC7ED85D1047879E35B526D4A4BC3A
717D05C0D8274F20827ACFAE5411DEBE
293FFA43CD594767AD3F659C2FF00E21
DBF9B02DEF264C2B8595719E713637C8
4625049F45D049A284B3185A9CE5BF72
65F57E9CA19C49749C32BFDAF6979CE9

Thanks.

**Comment by todor-ivanov** [comment]
Thanks @nsmith- for the very detailed feedback. I am looking at all those this morning. I'd like to try few stuff so I can properly add this into the MSRulecleaner logic. 
and thanks @FernandoGarzon  for taking care of the already suspended rules. 
@amaltaro  Do you have it on top of your head what is the longest period of time a workflow is still visible through reqmgr in the statuses we  are querying for from MSRulecleaner?

**Comment by amaltaro** [comment]
MSRuleCleaner is already responsible for archiving workflows, so I believe the workflow will be visible to this MS as long as it's needed.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro

**Comment by todor-ivanov** [comment]
Hi @nsmith-  @amaltaro 

> Personally I think that if no MSOutput rules cover the dataset, there was a mistake in the workflow creation to have that data tier written out. We have seen such issues in the past.

Just for the record, the workflows having output not covered by tape rules are not only RelVals. The reason for lack of tape rule may also be a unified configuration. While working on the issue I just stumbled on several of them. Here [1] is one.

[1]
```
021-03-23 02:43:42,530:INFO:MSOutput: Workflow: pdmvserv_task_EXO-RunIISummer16NanoAODv7-10471__v1_T_210318_040432_5662, total output size: 0.0 GB, against RSE: T1_DE_KIT_Tape
2021-03-23 02:43:42,531:WARNING:MSOutput: Skipping tape data placement for dataset: /VBF_Zprime_tau_tau_M_1500_gl_0_gh_1_kv_0p1_TuneCUETP8M1_madgraph-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM because Unified configuration sets it not to go to tape.
2021-03-23 02:43:42,531:INFO:MSOutput: All the tape requests succeeded for: pdmvserv_task_EXO-RunIISummer16NanoAODv7-10471__v1_T_210318_040432_5662. Marking it as 'done'
2021-03-23 02:43:42,533:INFO:MSOutput: MSOutputConsumer: PipelineNonRelVal: Processed 'msOutDoc' with '_id': pdmvserv_task_EXO-RunIISummer16NanoAODv7-10471__v1_T_210318_040432_5662.
2021-03-23 02:43:42,534:DEBUG:MSOutput: {u'Campaign': u'RunIISummer16NanoAODv7',
 u'CreationTime': 1616462092,
 u'IsRelVal': False,
 u'LastUpdate': 1616463822,
 u'OutputDatasets': [u'/VBF_Zprime_tau_tau_M_1500_gl_0_gh_1_kv_0p1_TuneCUETP8M1_madgraph-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM'],
 u'OutputMap': [{u'Campaign': u'RunIISummer16NanoAODv7',
                 u'Copies': 1,
                 u'Dataset': u'/VBF_Zprime_tau_tau_M_1500_gl_0_gh_1_kv_0p1_TuneCUETP8M1_madgraph-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM',
                 u'DatasetSize': 225792356,
                 u'DiskDestination': u'(tier=2|tier=1)&cms_type=real&rse_type=DISK',
                 u'DiskRuleID': u'2ed551f748f3439ba90af96aeba83b35',
                 u'TapeDestination': u'',
                 u'TapeRuleID': u''}],
 u'RequestName': u'pdmvserv_task_EXO-RunIISummer16NanoAODv7-10471__v1_T_210318_040432_5662',
 u'RequestType': u'TaskChain',
 u'TransferStatus': u'done',
 u'_id': u'pdmvserv_task_EXO-RunIISummer16NanoAODv7-10471__v1_T_210318_040432_5662'}
```

**Comment by nsmith-** [comment]
I think the current plan of keeping workflows unarchived until the tape rules are OK is good, as it provides an extra safety layer on top of Rucio. But in theory, once a rule is past `waiting for approval` (and `inject`) rucio can guarantee that the needed source replicas will not be lost. The full enumeration of rule states is at https://github.com/rucio/rucio/blob/9b37362ccdd12da8b55446170be524f9d5ea69a1/lib/rucio/db/sqla/constants.py#L177-L183

If later we decide that waiting for OK is too much coupling between WM and DM, we can reduce the requirement from "O" to "not W or I`
