### ISSUE TITLE
Disable reqmon cherrypy threads in testbed

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10049]
**Impact of the new feature**
Have a singleton for reqmon cherrypy thread tasks

**Is your feature request related to a problem? Please describe.**
CherryPy tasks can't run in both VMs and K8s

**Describe the solution you'd like**
Disable reqmon-tasks from testbed VMs, so we have have in in k8s

**Additional context**
https://github.com/dmwm/deployment/issues/973

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/deployment/pull/975
