### ISSUE TITLE
Disable t0reqmon cherrypy threads in testbed

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10048]
**Impact of the new feature**
Have a singleton for t0reqmon cherrypy thread tasks

**Is your feature request related to a problem? Please describe.**
CherryPy tasks can't run in both VMs and K8s

**Describe the solution you'd like**
Disable t0reqmon-tasks from testbed VMs, so we have have in in k8s

**Additional context**
https://github.com/dmwm/deployment/issues/974

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/deployment/pull/976
