### ISSUE TITLE
Migrate reqmgr2 to k8s testbed

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10058]
Work with Imran to move reqmgr2 to k8s testbed, perform simple validation of the service and scan logs for any errors

**Comment by amaltaro** [comment]
Here are the relevant changes for the backends mapping:
https://github.com/dmwm/deployment/pull/981

@goughes once you have had a quick look at the k8s-testbed reqmgr2 logs, I think this issue could be marked as resolved/closed.

**Comment by goughes** [comment]
Reqmgr2 has been verified to be working properly in testbed.
