### ISSUE TITLE
Change dbs-client PyPI project name to dbs3-client

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10062]
The dbs3 client is currently packaged in PyPI under the name "dbs-client", change the name to dbs3-client to match what is produced via the RPM build process. dbs-client is an old package that was recently removed from the cmsdist spec repo.

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, I know you had a summer student working on the dbs3-client and its packaging this summer. Could you please confirm what is the package name used in PyPi and/or whether this WMCore issue makes any sense?

**Comment by amaltaro** [comment]
Indeed not longer relevant! Yuyi has started uploading `dbs3-client` package to PyPi, see: https://pypi.org/project/dbs3-client/

Closing.
