### ISSUE TITLE
Create more interactive workflow tests (taskChain done, need to add stepChain and maybe T0 related examples)

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10069]
https://gitlab.cern.ch/khurtado/psettweakmigration/-/issues/1

**Comment by amaltaro** [comment]
@khurtado I moved it to the Q1 project. If it's a work in progress, you might want to move it to the correct column.

**Comment by khurtado** [comment]
Closing this issue (we got stepChain, taskChain ReReco, DqmHarvesting) in: https://gitlab.cern.ch/khurtado/psettweakmigration
