### ISSUE TITLE
[py2py3] Remove/replace dependency on restkit library

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10076]
**Impact of the new feature**

WMCore in general, and perhaps other services depending on it.

**Is your feature request related to a problem? Please describe.**

Some packages built from dmwm/WMCore depend on `restkit` ( [pypi](https://pypi.org/project/restkit/), [specfile](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-restkit.spec) ), which only supports python2. 

List of dmwm/WMCore packages depending on `restkit`

* [WMagent](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagent.spec).  `restkit` is imported by [couchapp](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchapp.spec), which is imported by [couchdb15](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchdb15.spec).
* [ReqMgr2](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/reqmgr2.spec).  `restkit` is imported by [couchapp](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchapp.spec), which is imported by [couchdb15](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchdb15.spec).
* [Workqueue](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/workqueue.spec).`restkit` is imported by [couchapp](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchapp.spec), which is imported by [couchdb15](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchdb15.spec).
* [ACDCServer](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/acdcserver.spec). `restkit` is imported by [couchapp](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchapp.spec), which is imported by [couchdb15](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchdb15.spec).

**Describe the solution you'd like**

The issue about support for python3 in `restkit` is still [open](https://github.com/benoitc/restkit/issues/47) after 9 years. It seems unlikely that this changes soon.

I am not sure what the solution may be, I may need some help from other members of the team.

**Comment by amaltaro** [comment]
@mapellidario as we discussed in the past week, I'm setting this issue free such that others can pick it, if they want.

**Comment by amaltaro** [comment]
This cmsdist PR: https://github.com/cms-sw/cmsdist/pull/6892
deprecates the `restkit` and `couchapp` spec files, bringing in a new dependency on `CMSCouchapp` (which internally depends on the `requests` library).

It's been tested and Couchapps and jenkins are happy with the new package (I'm still working on another version to make it less DEBUG verbose though, to be fixed in the couchapp issue).

Having said that, I consider this issue done and it can be closed.
