### ISSUE TITLE
Move acdcserver to k8s testbed

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10090]
Work with Imran to move acdcserver to k8s testbed and validate it is are working properly.

**Comment by goughes** [comment]
Evaluated how this service looks on my VM. There is no "acdcserver" process that runs, the acdcserver is just some couchapps that are pushed to couchdb at deployment time: https://github.com/dmwm/deployment/blob/master/acdcserver/deploy

**Comment by goughes** [comment]
This was resolved awhile back via #10216 and #10303.

**Comment by amaltaro** [comment]
And just to complement, the ACDCServer is actually a couchapp only. So it runs wherever couchdb is running.
