### ISSUE TITLE
Problems in RelVal Output Data Placement

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10106]
**Impact of the bug**
RelVal Output Data Placement

**Describe the bug**
MSOutput handles the output data placement of RelVal output datasets with the same logic that Unified applied before [1]. There are more than one problem with this logic:
1. Output datasets whose data tier is `ALCARECO` are skipped and they are not placed anywhere.
2. The conditionals are redundant - i.e. it selects `T2_CH_CERN` as a destination if the data tier is not `RECO` and `ALCARECO`, then it checks if the data tier is `GEN-SIM`, which is totally redundant. `GEN-SIM` is already placed to `T2_CH_CERN` in the first conditional.
3. As this is a very old logic, I do not see any justification behind this. For instance, why do the datasets go to `T2_CH_CERN` if they are not `RECO` and `ALCARECO`?

[1] https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/MSOutput.py#L638-L659

**How to reproduce it**
An example from the log:
```
2020-11-21 00:44:02,517:WARNING:MSOutput: RelVal dataset: /RelValZpTT_1500_14/CMSSW_11_2_0_pre9-TkAlUpsilonMuMu-112X_mcRun3_2021_realistic_v11-v1/ALCARECO without any destination
```

**Expected behavior**
A new policy should be prepared for RelVal output data placement. Firstly, `ALCARECO` datasets are not placed anywhere for months and therefore they are not used by anyone for months. This makes me think that maybe they are not necessary and we should stop producing it?

**Additional context and error message**
@amaltaro @todor-ivanov @nsmith- FYI

**Comment by amaltaro** [comment]
Thanks for creating this issue, Hasan.
I suggest we first have that broader discussion that we have been talking about, come up with policies and update this github issue with what we have decided to have implemented.

**Comment by haozturk** [comment]
I agree Alan. We will discuss this with PdmV at the latest at 11.01.2021 - 2pm CERN time. I hope we can come up with policies, then. Please let me know if you have questions to PdmV regarding issue and I can bring them up. Or we can attach our questions to the existing e-mail thread `RelVal output data placement - Up-to-date requirements needed`

**Comment by chayanit** [comment]
@haozturk , let's include this topic in the discussion next month. I have pinged AlCa who supposed to be the users of ALCARECO to get more details.

**Comment by haozturk** [comment]
@chayanit thanks, that sounds good to me. @amaltaro  please let me know if you think we should include another person/group for this discussion.

**Comment by amaltaro** [comment]
Hasan, I'm not sure what are all the relevant groups. In short, anyone that does any sort of validation with RelVal output datasets :-)

**Comment by chayanit** [comment]
Hello @haozturk  @haozturk , to close the loop. Here is the policy of RelVal output data placement we would like to propose. 

- `GEN-SIM` to be stored at the production sites (either `T2_CH_CERN` or `FNAL`) in which they are needed as input datasets for PU workflows in RelVal production of every single *pre-release* 
- `ALCARECO` to be kept at `T2_CH_CERN` due to DPGs (detector subsystems) will be able to have access to them locally through lxplus and check the detector performance during data-taking. They were not touched recently because we do not have data-taking since a while
- RelVals lifetime can be categorised to 
1. All Relvals dataset for *pre-release* to be kept for 3 months 
2. All Relvals dataset for *production release* to be kept for 12 months 
Note : It would be nice if we have rights on RelVals deletion to clean up the storage from time to time as MC production. Let's discuss about this in the next PdmV/PnR meeting :)

Best
Chayanit for PdmV

**Comment by haozturk** [comment]
@chayanit  can you please elaborate what you mean by _pre-release_ and _production-release_?

**Comment by chayanit** [comment]
@haozturk I have explained in my message above

**Comment by haozturk** [comment]
Thanks for the edit, Chayanit, so we should make a string matching for the `pre` pattern in the `CMSSWVersion` parameter of the request. Correct me if I'm wrong.

**Comment by chayanit** [comment]
I would say so. You can make a string matching for RelVal workflows which contain _pre_ in the _CMSSWVersion_ to have shorter lifetime of 3 months than the one without _pre_ word.

**Comment by nsmith-** [comment]
A small note, currently rucio has the following rule-generating subscription:
```
transfer_ops: RelValNanoAOD UPDATED
  priority: 3
  filter: {"project": ["RelVal"], "pattern": "^/.*/NANOAOD(|SIM)$", "account": ["wma_prod"], "did_type": "CONTAINER", "scope": ["cms"]}
  rules: [{"rse_expression": "T2_CH_CERN", "activity": "Production Output", "copies": 1, "grouping": "ALL"}]
  comments: Controls the distribution of RelVal output NanoAOD
```
Is this still needed? Or is MSOutput producing appropriate rules?

**Comment by haozturk** [comment]
> GEN-SIM to be stored at the production sites (either T2_CH_CERN or FNAL) in which they are needed as input datasets for PU workflows in RelVal production of every single pre-release

@chayanit one question for GEN-SIM outputs: Currently, based on `SubRequestType`, `RelVal` workflows are running at FNAL and `HIRelVal` workflows are running at CERN. I'm not sure about if GEN-SIM is used as input for both of them or only one. If it's used as input for only one of type of RelVal workflow, it might help us deciding the destination of GEN-SIM outputs. Can you please let me know about this?

**Comment by haozturk** [comment]
@chayanit  one more request: could you please check the current destination logic and see if it makes sense to keep or remove some rules? https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L643-L654 These are pretty old rules and this is a good opportunity to update them: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L643-L654 
e.g. if processingString contains `TkAlMinBias`, place it to CERN?

**Comment by chayanit** [comment]
> > GEN-SIM to be stored at the production sites (either T2_CH_CERN or FNAL) in which they are needed as input datasets for PU workflows in RelVal production of every single pre-release
> 
> @chayanit one question for GEN-SIM outputs: Currently, based on `SubRequestType`, `RelVal` workflows are running at FNAL and `HIRelVal` workflows are running at CERN. I'm not sure about if GEN-SIM is used as input for both of them or only one. If it's used as input for only one of type of RelVal workflow, it might help us deciding the destination of GEN-SIM outputs. Can you please let me know about this?

Hello @haozturk we usually use GEN-SIM to be input for both RelVal and HIRelVal. I will try to check the rules soon.

**Comment by chayanit** [comment]
> @chayanit one more request: could you please check the current destination logic and see if it makes sense to keep or remove some rules? https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L643-L654 These are pretty old rules and this is a good opportunity to update them: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L643-L654
> e.g. if processingString contains `TkAlMinBias`, place it to CERN?

Hello @haozturk , I think the current destination logic still makes sense. BTW, have we fixed the policy of GENSIM and GEN-SIM-DIGI-RAW not placed on disk?

**Comment by haozturk** [comment]
Himm, really? @chayanit What's reason for placing a dataset whose processing string includes `TkAlMinBias`at CERN but not FNAL for instance? 

> have we fixed the policy of GENSIM and GEN-SIM-DIGI-RAW not placed on disk?

It's in progress, I was also waiting for your response to the question above before finalizing things. There is also not a definite roadmap for placing other datatiers. Alan proposed checking the transfer overhead of these relval outputs and if the transfer overhead is reasonably small, then, there is no need to concern about what to choose between CERN and FNAL. Here is a recent example for a relval output: 
`/RelValVHToHtt_NLO_Pow_13TeV_py8/CMSSW_12_0_0_pre3-120X_mcRun2_asymptotic_v1-v1/GEN-SIM`
@flgomezc can you please check what's transfer overhead for transferring this dataset from CERN to FNAL and the other way around? @chayanit  if this is not a good indicator for an average relval output, can you please give us one example?

**Comment by chayanit** [comment]
> Himm, really? @chayanit What's reason for placing a dataset whose processing string includes `TkAlMinBias`at CERN but not FNAL for instance?

This is a good question but I think maybe @mmusich can clarify better than me whether we need RelVals `ALCARECO` datatier with `TkAlMinBias` to be placed at T2_CERN. PdmV do not use this datatier.

> 
> > have we fixed the policy of GENSIM and GEN-SIM-DIGI-RAW not placed on disk?
> 
> It's in progress, I was also waiting for your response to the question above before finalizing things. There is also not a definite roadmap for placing other datatiers. Alan proposed checking the transfer overhead of these relval outputs and if the transfer overhead is reasonably small, then, there is no need to concern about what to choose between CERN and FNAL. Here is a recent example for a relval output:
> `/RelValVHToHtt_NLO_Pow_13TeV_py8/CMSSW_12_0_0_pre3-120X_mcRun2_asymptotic_v1-v1/GEN-SIM`
> @flgomezc can you please check what's transfer overhead for transferring this dataset from CERN to FNAL and the other way around? @chayanit if this is not a good indicator for an average relval output, can you please give us one example?

I would suggest to use this RelVal dataset for the indicator instead. 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_12_0_0_pre3__fullsim_noPU_2021_14TeV-TTbar_14TeV-00001

**Comment by mmusich** [comment]
> This is a good question but I think maybe @mmusich can clarify better than me whether we need RelVals ALCARECO datatier with TkAlMinBias to be placed at T2_CERN. PdmV do not use this datatier.

@chayanit I think this has been agreed in the distant past, because the special high memory machines in the CAF pool needed for Tracker Alignment work are only available at CERN.

**Comment by haozturk** [comment]
thanks @mmusich do you know if this is still necessary?

@chayanit  in order to finalize the development, can you please also comment on the other old requirements, which are
1. If processingString includes `SiStripCalMinBias` place to CERN.
2. if `GEN-SIM-RECO`, place to FNAL,
3. if `GEN-SIM-DIGI-RAW`, place to FNAL
do we have any reasonable justification for these old rules? We do not want to keep any invalid old rule.

**Comment by chayanit** [comment]
Sure @haozturk and sorry for some delay. I went offline for two weeks.

Before I can summarise new requirement, could you confirm that now all RelVals will be running at FNAL and HIRelVals at CERN? As soon as you confirm then I can set new requirement based on this setup.

**Comment by mmusich** [comment]
@haozturk 

> thanks @mmusich do you know if this is still necessary?

yes, nothing has changed in this respect.

**Comment by haozturk** [comment]
> could you confirm that now all RelVals will be running at FNAL and HIRelVals at CERN? As soon as you confirm then I can set new requirement based on this assumption.

yes @chayanit  this is the policy for months

**Comment by chayanit** [comment]
OK thanks. I need to be confirmed because things keep changing without notifying. 

Here is new requirement we want to update to

`if dataTier != "RECO" and dataTier != "GEN-SIM-RECO" and dataTier != "ALCARECO":` (we do not need to keep these 3 datatiers on disks and they can be deleted but some further requirement for ALCARECO below. Does it mean other datatiers will be stored at FNAL disk?)
                    destination.add('T1_US_FNAL_Disk')
`if dataTier == "GEN-SIM":`   (but as you said `RelVal` is running at FNAL while `HIRelVal` is running at CERN, then we need ccorresponding GEN-SIM to be stored at the site producing it. Could you modify the requirement accordingly?) 
                   `destination.add('T1_US_FNAL_Disk')`
`if dataTier == "GEN-SIM-DIGI-RAW":`
                    `destination.add('T1_US_FNAL_Disk')`
`if "RelValTTBar" in dsn and "TkAlMinBias" in procString and dataTier != "ALCARECO":`
                    `destination.add('T2_CH_CERN')`
`if "MinimumBias" in dsn and "SiStripCalMinBias" in procString and dataTier != "ALCARECO":
                    destination.add('T2_CH_CERN')

**Comment by amaltaro** [comment]
@haozturk @chayanit Hi, I wonder if we managed to converge to a final RelVal output data placement policy? If so, this would be a good moment to get a new implementation in place and deployed to production in the next week. Otherwise, we will have to wait for October to get any of these into production.

**Comment by amaltaro** [comment]
In that case, I read that T2_CH_CERN is actually the default option for RelVal output data placement, so having a schema like:
```
"relval_output_destinations": {
   "GEN-SIM": ["T1_US_FNAL_Disk"],
   "Tier_blah1": ["T1_US_FNAL_Disk", "T2_CH_CERN"],
   ...
   "default": ["T2_CH_CERN"]
}
```
is likely a better option, since it will guarantee that RelVal output always get a final data placement.
Of course, if we do produce datatiers that shouldn't be stored on Disk(?), or shouldn't be stored for more than a few days, then my suggestion won't work.

**Comment by bbilin** [comment]
Hi @amaltaro , the problem is currently we are running our validation jobs at CERN, and they need the GEN-SIM to be stored at disk here for several weeks at least to be used in sequential validations. For the moment we propose to keep the T2_CH_CERN as the default option, and we will come back with an exact list in the upcoming days.

Thanks and sorry for latency in response.

**Comment by amaltaro** [comment]
Sorry for a belated follow-up. Considering @bbilin feedback, the final schema would be then:
```
"relval_output_destinations": {
   "GEN-SIM": ["T1_US_FNAL_Disk", "T2_CH_CERN"],
   "Tier_blah1": ["T1_US_FNAL_Disk", "T2_CH_CERN"],
   ...
   "default": ["T2_CH_CERN"]
}
```

@haozturk what do you think? Would anyone have any other update to the RelVal output data placement logic/policy? If not, then we should definitely consider it and get this feature deployed.

**Comment by haozturk** [comment]
Hi @amaltaro  sounds reasonable to me. We can move forward w/ this logic, IMO.
