### ISSUE TITLE
Automatic PU deletion once its campaign is closed

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10107]
**Impact of the new feature**
Disk space of CMS sites

**Is your feature request related to a problem? Please describe.**
When a campaign is not used anymore, it is archived - i.e. PnR removes the campaign from the campaign configuration file and updates the CouchDB. In such cases, the PU of the campaign keeps occupying space on disk, although it is not used anymore. The deletion of these PUs require manual intervention, which might be time consuming.

**Describe the solution you'd like**
Once a campaign is archived, its PU/PUs should be deleted from disk automatically only if they are not used by any active campaign. 

**Describe alternatives you've considered**
In order to add an additional layer of check, we might want to develop the automation such that it asks for an approval. 

**Additional context**
@nsmith- @amaltaro @todor-ivanov FYI

**Comment by amaltaro** [comment]
Thanks for creating this issue, Hasan. The more I think about Pileup management within WMCore, the more I'm convinced that we need one specific microservice/thread to deal with them in an unified way. Sort of what I started discussing here:
https://github.com/dmwm/WMCore/issues/9779

**Comment by amaltaro** [comment]
I believe this issue has actually been addressed with the recent developments in MSPileup, especially tracked in this GH issue: https://github.com/dmwm/WMCore/issues/11426

@haozturk I am closing this issue out. But please reopen it in case I am missing anything. Thanks
