### ISSUE TITLE
Add python3 code compatibility checks to DMWM WMCore jenkins

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10120]
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
As we port our WMCore code to be compatible with both python2 and python3, we need to increase our degree of confidence with more automated checks and tests.

**Describe the solution you'd like**
Run a static analysis of the WMCore code and check for incompatibilities with python3. The `DMWM-WMCore-pylint3` jenkins project already has this check, but it only runs against the baseline WMCore, using this script:
https://gitlab.cern.ch/CMSDOCKS/dmwm/-/blob/master/wmcore_tests/TestScripts/pylint3WMCore.sh

So, my suggestion is to run the same `pylint --py3k` check, but in a PR basis. Other details are:
* I'm inclined to say that such tests shouldn't fail the PR (yet)
* it should run only on the python files that changed within the PR
* its output should be part of the final `PullRequestReport.html` report, which is fed back to the GH pull request

**Describe alternatives you've considered**
none that comes to my mind

**Additional context**
none

**Comment by amaltaro** [comment]
@mapellidario @todor-ivanov please let me know if I'm missing anything important on this description. I'm all ears if you have anything to suggest as well.

**Comment by mapellidario** [comment]
Thanks Alan! This would be very nice indeed!

I have one comment, but it may be naive. I suppose that the py2 pylint is run with [pylintWMCore.sh](https://gitlab.cern.ch/CMSDOCKS/dmwm/-/blob/master/wmcore_tests/TestScripts/pylintWMCore.sh#L14) . Should we add a `.pylintrc_py3` specific for py3, containing for example all the rules in [dmwm/WMCore/standards/.pylintrc](https://github.com/dmwm/WMCore/blob/master/standards/.pylintrc) and adding `-d w1618`, and place it in `dmwm/WMCore/standards` as well?

**Comment by amaltaro** [comment]
If those pylintrc files have no differences (besides this w1618), then I think we can keep using the same file for either python2 or python3. Honestly speaking, I have no clue on how different they are supposed to be.

**Comment by mapellidario** [comment]
I got a wrong idea of `pylint --py3k` yesterday. It [seems](https://portingguide.readthedocs.io/en/latest/tools.html#automated-checker-pylint-py3k) that `--py3k` is an option of python2 version of `pylint` and it checks for incompatibilities with python3 _only_. 
What if we include also a report from `python3 -m pylint` ? It is not given that compatibility with python3 and linting assuming python3 interpreter are the same thing. does this make sense to you?

**Comment by amaltaro** [comment]
Just updating this issue, from the discussion Dario and I had today, it seems there is value in providing a `pylint --py3k` report, which is very compacted; in addition to that, we are planning to enable a full report from futurize as well, instead of the current `stage1` fixers which is in place.

Both reports should be done only for new files and or files that have changed within the PR.
