### ISSUE TITLE
[doc] Select the format for WMCore docstrings

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10161]
**Impact of the new feature**

This may impact all WMCore docstrings.

**Is your feature request related to a problem? Please describe.**

We can likely converge on one convention of docstrings, then update the WMCore contributor guidelines. We need to answer

* Is there any specific format to be followed (NumPy, Google, reStructuredText, etc)? 
* Is there anything we must avoid?
* Any best practices?

**Describe the solution you'd like**

We should reuse what we already have as much as possible. From the Sphinx configuration in [dmwm/WMCore/doc](https://github.com/dmwm/WMCore/tree/master/doc) I have been able to build [this webpage](https://cms-dmwm-wmcore-sphinx.docs.cern.ch/index.html) with no tweaking to WMCore configuration. It was enough to tweak the procedure used to deploy mkdocs to cern's openshift, replacing mkdocs build with sphinx build. 

Since the current configuration of WMCore/doc uses [sphinx.ext.autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), by default it uses reStructuredText. This looks like a good option for me.

Some notable examples are
* [WMCore.ReqMgr.DataStructs.ReqMgrConfigDataCache](https://cms-dmwm-wmcore-sphinx.docs.cern.ch/WMCore.ReqMgr.DataStructs.ReqMgrConfigDataCache.html): looks good to me
* [WMCore.Services.LogDB.LogDBReport](https://cms-dmwm-wmcore-sphinx.docs.cern.ch/WMCore.Services.LogDB.LogDBReport.html) The intro was likely written with NumPy style in mind
* [WMCore.MicroService.Unified.MSOutputStreamer](https://cms-dmwm-wmcore-sphinx.docs.cern.ch/WMCore.MicroService.Unified.MSOutputStreamer.html): looks good to me, [source](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/MSOutputStreamer.py)
* [WMCore.MicroService.Unified.MSOutput](https://cms-dmwm-wmcore-sphinx.docs.cern.ch/WMCore.MicroService.Unified.MSOutput.html): surprisingly empty, to be investigated,  [source](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/MSOutput.py)

**Describe alternatives you've considered**

If you do not like it, we can change the style to NumPy or Google with [sphinx.ext.napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) .

**Additional context**

The s2i builder image used to deploy the website is available at [gitlab.cern.ch](https://gitlab.cern.ch/cms-dmwm-test/s2i-sphinx-container/). Right now the documentation website is automatically rebuilt every time I push to mapellidario/WMCore (github triggers the release event by contacting a webhook provided by CERN's Openshift). This is experimental and we can change the settings so that both the triggers and the code used to build the docs are from dmwm/WMCore.

**Comment by mapellidario** [comment]
I will remove myself from the assignee, i didn't really have the time to properly investigate this further. Sorry!

**Comment by amaltaro** [comment]
Trying to adopt a compact and already fairly used style, Sphinx. If we resume the activity of building automatic document, Sphinx would be able to parse it. PR proposing it is linked above.
