### ISSUE TITLE
[py2py3] investigate effect of `hash()` differences between py2 and py3

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10160]
**Impact of the new feature**

WMCore in general, and perhaps other services depending on it.

**Is your feature request related to a problem? Please describe.**

In dmwm/WMCore we rely on the standard `hash()` function, but its behavior has changed in py3. While in python2 the `hash()` of an object is guaranteed to be the always the same (if an object does not change) even after the python interpreter itself is restarted, this is not the case anymore in python3. The python3 `hash()` doc states

> By default, the __hash__() values of str and bytes objects are “salted” with an unpredictable random value. Although they remain constant within an individual Python process, they are not predictable between repeated invocations of Python.

We need to investigate if this can cause some errors. For example, if we store on a database the hash of an object obtained with `hash()` to check if it is the same across different python interpreters, then we need to refactor our code.

Quick links to `hash()` documentation
- [py2 hash doc](https://docs.python.org/2/reference/datamodel.html#object.__hash__): 
- [py2 hash doc](https://docs.python.org/3/reference/datamodel.html#object.__hash__)

Quick links to the use of `hash()` in `dmwm/WMCore/*`

* [src/python/WMCore/DataStructs/Run.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/DataStructs/Run.py#L135)
* [src/python/WMCore/DataStructs/WorkUnit.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/DataStructs/WorkUnit.py#L75)
* [src/python/WMCore/Services/Service.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/Services/Service.py#L107)
* [src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py#L38)
* [src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py#L106)

Same process comparison, should not cause any problem:
* [test/python/WMCore_t/DataStructs_t/WorkUnit_t.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/test/python/WMCore_t/DataStructs_t/WorkUnit_t.py#L99)

How to reproduce:

```bash
# should print always the same value
docker run python:2 python -c 'print(hash(frozenset({"hello": "world"}.items())))'

# should print a different value every time
docker run python:3 python -c 'print(hash(frozenset({"hello": "world"}.items())))'
```

**Describe the solution you'd like**

Investigate usage of `hash()` in WMCore and establish if the hashes are used to compare objects outside the boundaries of a python interpreter, for example between two concurrent interpreters or saving a hash on a database and using it at a later time.

**Describe alternatives you've considered**

The solution would require to use consistent hashing functions, such as the ones provided by `hashlib`, as it is already done in the following examples

* [src/python/WMCore/Services/LogDB/LogDBBackend.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMCore/Services/LogDB/LogDBBackend.py#L24)
* [src/python/WMQuality/WebTools/RESTClientAPI.py](https://github.com/dmwm/WMCore/blob/2b1af3e52c033f101880459556a6bac624f6ff89/src/python/WMQuality/WebTools/RESTClientAPI.py#L96)

Reproduce: how to get consistent hash

```bash
# py2
docker run python:2 python -c 'import hashlib;print(hashlib.sha256(unicode({"hello": "world"}).encode("utf-8")).hexdigest())'
> 08b8bdfc96c88412e3e4c9ce471899037be4f44b4d737fbdb85407bb3e66a331
# py3
docker run python:3 python -c 'import hashlib;print(hashlib.sha256(bytes(str({"hello": "world"}), "utf-8")).hexdigest())'
> 08b8bdfc96c88412e3e4c9ce471899037be4f44b4d737fbdb85407bb3e66a331
```

**Additional context**

Original discussion in [PR 10012](https://github.com/dmwm/WMCore/pull/10012#issuecomment-731164254).

**Comment by amaltaro** [comment]
As discussed with Dario over slack, and after reading this well written GH issue, we discovered that even if we disable the random seeding in python3 (with `export PYTHONHASHSEED=0`), it still yields different results between python2 and python3. The same happens if we set the initial seed to an specific integer.

I believe - to be confirmed - we use the built-in `hash` function just to have a reproducible way of identifying objects. If that's the case, we could then migrate to one of the `hashlib` algorithms, something that is consistent between different python interpreters and that's cheap CPU-wise (like sha1). I'm starting to change the Mock modules to `sha1`, and we shall see how it goes.

@mapellidario please let me know if you have a different suggestion or any other thought.

**Comment by mapellidario** [comment]
Your proposed solution sounds perfect!

I was about to suggest using some function from `random` fixing the seed to have reproducible results, but as they changed the algorithm underlying `hash()`, they can as well change the algo under `random`. I would stick to your solution, then.

I am sorry for having delegated this boring task! Thanks again for the help debugging #10543 !

**Comment by amaltaro** [comment]
As largely discussed in this PR comment: https://github.com/dmwm/WMCore/pull/10605#discussion_r654225846 (hopefully it won't vanish), the `hash()` builtin function was replaced by `hashlib.sha1()`, which gives us the same results regardless which python version is used.

There are some tricks though, such as:
* it requires a bytes-like input object (encoded unicode objects)
* it does not work with objects more complex, like list/set/frozenset (reports error on "buffer API required")
* the defined `__hash__` method enforces an integer to be returned (something internally enforced by its super class?)
* there can be easily an integer overflow (in PY2) when converting the `myhash.hexdigest()` value to integer. So we need to actually use an slice of the string hexdigest value. It's probably related on the hardware architecture/platform - and maybe python version - but both my docker container and laptop have this maximum integer value supported:
```
> python -c 'import sys; print(sys.maxint)'
9223372036854775807
```
thus, the `hexdigest()` slice to be used has to be - at most - 15 chars:
```
> int(15 * "f", base=16)
1152921504606846975
```

Hopefully there are no other catches that we are still missing here :-)
