### ISSUE TITLE
Build a minimal PyPI based Docker image for reqmgr2

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10178]
**Impact of the new feature**
Overhaul the Dockerfile for ReqMgr2 to be as small as possible. Container will use PyPI packages instead of the current RPM based deployment method.

**Is your feature request related to a problem? Please describe.**
ReqMgr2 container is currently very large, which is not ideal for k8s.

**Describe the solution you'd like**
Build a minimal Docker image using ReqMgr2 from PyPI

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vkuznet** [comment]
I provided initial Dockerfile to build docker image and it was successfully build, see details in https://github.com/dmwm/WMCore/issues/11310.

**Comment by amaltaro** [comment]
@vkuznet can you please provide a PR that is fixing each of these issues that you updated with the comment above? Feel free to provide it all in a single PR, then in the PR you can reference GH issues like "Fixes #blah\nFixes #blahblah" and so on.

You might want to become an assignee and also move them under the WIP column. Thanks

**Comment by vkuznet** [comment]
CMSKubernetes repo commits for WMCore Dockefiles:
- https://github.com/dmwm/CMSKubernetes/commit/fa223eea3bb05ef45b93499aa14f04630a60330a
- https://github.com/dmwm/CMSKubernetes/commit/942145b863dc62d5108525b7a223dd96b1073375
- https://github.com/dmwm/CMSKubernetes/commit/092523fc55fdc171558080ad6d99bea1487c8671
- https://github.com/dmwm/CMSKubernetes/commit/f67f20b2999a731bc742d861ce49ffce22bbd918
- https://github.com/dmwm/CMSKubernetes/commit/64bbe4eb9d24a879b32194d93594ae4b8de7e074
- https://github.com/dmwm/CMSKubernetes/commit/99d65ad733ea3adf970fc49602d8ba193e0047a5
- https://github.com/dmwm/CMSKubernetes/commit/6e025ba0f9641284f4a4d3e087264126c760c590

**Comment by amaltaro** [comment]
Thanks for the pointers.

Nonetheless, let me stress it once again, in the future, can you please adopt a feature-branch model such that we can have discussions and review **before** changes are actually merged? 

With direct push to a repository, we lose any possible explanation and historical data (other than the commit message itself!).

**Comment by amaltaro** [comment]
Can you please also add a section to this wiki:
https://github.com/dmwm/WMCore/wiki/Managing-WMCore-services-in-CMSWEB-kubernetes

explaining these different dockerfiles:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2/Dockerfile
vs
https://github.com/dmwm/CMSKubernetes/blob/master/docker/reqmgr2/Dockerfile
?
Questions like which one is used in (pre-)prod, main differences, do they have any automated build workflow, etc?

**Comment by vkuznet** [comment]
And, once again, different project, different rules. If WMCore model of issues/PRs will be adopted in CMSKubernetes there will be (at least) significant delay on making progress on k8s. The PRs model is good when you do programming, while direct commits on stuff which is in R&D mode and there is no clear path forward and there is no a-prior knowledge. We can debate about it, but I just want to make it clear why it is like that.

**Comment by amaltaro** [comment]
I am not asking for this adoption in the wide CMSKubernetes repository, but only on what is directly related to the services that the WMCore team is responsible for. If you say that those Dockerfiles are under the responsibility of someone else (HTTP group, your, etc), then yes, I agree, whatever is the most productive to you.

**Comment by vkuznet** [comment]
I'll add update on wiki, but difference is simple:
- docker/xxx is currently used Dockerfiles to build RPM based images for WMCore xxx package
- docker/pypy/xxx is new Dockerfile based on pypy approach
During transition period we need both, therefore I made different area for pypi.

**Comment by vkuznet** [comment]
Wiki is updated: https://github.com/dmwm/WMCore/wiki/Managing-WMCore-services-in-CMSWEB-kubernetes#wmcore-dockefiles

**Comment by vkuznet** [comment]
The new pypi based image is available:

- docker files: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi
- docker images: https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2

@amaltaro , should we close the ticket?

**Comment by amaltaro** [comment]
Basic functionality of these PyPi-based services - both reqmgr2 and reqmgr2-tasks - have been tested with docker image label: `pypi-20221215-base`

In addition to the changes already linked above, the following was required as well:
Mount rucio-secrets and rename the docker image name for microservices, global workqueue and t0_reqmon:
https://github.com/dmwm/CMSKubernetes/pull/1261
https://github.com/dmwm/CMSKubernetes/pull/1283
https://github.com/dmwm/CMSKubernetes/pull/1287

Fix to the run.sh script in the dmwm-base image:
https://github.com/dmwm/CMSKubernetes/pull/1288

@vkuznet from my side we can close this out and follow up with a more detailed validation in https://github.com/dmwm/WMCore/issues/11354. What do you think?

**Comment by vkuznet** [comment]
yes, let's close this ticket.
