### ISSUE TITLE
Determine appropriate k8s deployment method for acdcserver

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10183]
**Impact of the new feature**
We need to determine and implement an appropriate method for handling acdcserver in the k8s environment.

**Is your feature request related to a problem? Please describe.**
Acdcserver is not a service, so it really does not "run" anywhere. It is just a couple commands that run to push couchapps to couchdb via the acdcserver deployment script. 

**Describe the solution you'd like**
Up for discussion

**Describe alternatives you've considered**
- Handle acdcserver updates alongside couchdb in VM environment
- Have a k8s pod deploy acdcserver updates and exit
- Ask Valentin for alternate suggestions 

**Additional context**
Related Issue: https://github.com/dmwm/WMCore/issues/10090

**Comment by goughes** [comment]
Remote push to couchdb is possible via adding an external host to `allowed_hosts` config option: https://github.com/dmwm/deployment/blob/1a251c24519af3a8daa6f026ebbe1f9364b9db9a/couchdb/local.ini#L7
Validated this with lxplus and my VM.

Pods communication to the outside likely goes through the IP of whatever host it gets scheduled on. Would require limiting acdcserver to certain hosts or allowing a range of addresses from all k8s hosts.

**Comment by amaltaro** [comment]
That's great news, Erik. I don't know how safe, robust and straight forward it would be to allow "random" minions running from within kubernetes to push those couchapps. I have the feeling that we will need to change how ACDCServer gets deployed as well. AFAIK, we don't even run it as an application/backend, it's simply a layer on top of CouchDB, then couchDB does all the hard work.

Your research will be extremely useful for reqmon/reqmgr2/workqueue though. I guess there are other specific issue(s) for those services, no?

**Comment by goughes** [comment]
This was resolved awhile back via #10216 and #10303.
