### ISSUE TITLE
Create migration plan for ms-output mongodb contents

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10239]
**Impact of the new feature**
Need to determine a plan for migrating documents from the prod/testbed VM mongodb instances to k8s instances.

**Is your feature request related to a problem? Please describe.**
Mongodb contents (expecially prod ones) will need to be migrated before starting the mongodb and ms-output service in k8s
 
**Describe the solution you'd like**
Determine the best method for getting these docs migrated and implement the solution

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by goughes** [comment]
Step 1: Turn off reqmgr2ms in VM
Step 2: Run https://github.com/amaltaro/ProductionTools/blob/master/mongoDocsToJson.py
Step 3: Copy the json to the k8s mongodb pod
Step 4: Run https://github.com/goughes/ProductionTools/blob/b6df8c1c43b348c4e130f3c97d4de91902ccd542/mongoJsonToDB.py
Step 5: Turn on reqmgr2ms-output in k8s

**Comment by amaltaro** [comment]
I believe you mistakenly closed this issue, so I'm reopening it. Erik, close it once again if it wasn't a mistake ;)

**Comment by goughes** [comment]
Export for prod VM:
- wget this script: https://raw.githubusercontent.com/amaltaro/ProductionTools/master/mongoDocsToJson.py
- Run it to export DB contents which creates two json files in /data/user: `msOutNonRelValColl.json` and `msOutRelValColl.json`

Import for prod k8s:
- Make sure the ms-output pod is not running in prod k8s
- Start the ms-output-mongo pod
- Get a shell on any of the reqmgr2ms k8s productions pods. We need to source the reqmgr2ms env to run the import script.
- `mkdir -p /data/user/import`
- scp the exported json files to the import dir
- Download the import script: https://raw.githubusercontent.com/goughes/ProductionTools/b096e4265d2491259f5301b193d0c13cb10db1bd/mongoJsonToDB.py
- source the reqmgr2ms env: `source /data/srv/current/sw/slc7_amd64_gcc630/cms/reqmgr2ms/<version>/etc/profile.d/init.sh`
- Run the script `python mongoJsonToDB.py`
- Theoretically the mongo db will be empty when you run the import script. If not, any duplicates entries will be skipped and logged.

**Comment by amaltaro** [comment]
@goughes these instructions look good to me, thanks for preparing this!

I still have a couple of comments and questions.
* when we start the `ms-output-mongo` pod, can we start only that pod without starting the `reqmgr2ms-output` service one?  If not, then it could be that `reqmgr2ms-output` will try to insert a few fresh documents before we manage to import docs from the other instance. It's probably not a big deal though, it should fail to insert those documents with "_id already exists" or something like that.
* maybe we could add a final check to ensure that this importing process went fine, something like comparing the amount of documents in the different mongo instances:
```
> db.msOutRelValColl.count()
and
> db.msOutNonRelValColl.count()
```

**Comment by goughes** [comment]
@amaltaro Imran can start the mongo pod without starting the ms-output pod. So we should be good there.

The script should output the count of the documents that were uploaded, similar to how yours outputs the count of what was exported. Is it possible to query the VM mongodb from the k8s infrastructure? Wondering if there are any firewalls in the way.

**Comment by goughes** [comment]
ms-output and mongodb were migrated to prod k8s Jan. 27. Closing this issue.
