### ISSUE TITLE
[py2py3] pycurl_manager - better handling of curl.setopts() input arguments

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10249]
**Impact of the new feature**

WMCore.Services.pycurl_manager

**Is your feature request related to a problem? Please describe.**

When modernizing `pycurl_manager` in #9818 , I overlooked the pycurl API documentation and relied only on the unit tests.

While investigating `pycurl_manager` for https://github.com/dmwm/CRABServer/issues/6374 I realized that the input of `curl.setopts()` should be a bytes string, while we are not passing a unicode string. It is not a problem until we only pass URLs that do not contain non-ascii characters, as stated in the [pycurl docs](http://pycurl.io/docs/7.43.0.3/curlobject.html?highlight=setopt#pycurl.Curl.setopt), but this is not the optimal long term solution. 

**Describe the solution you'd like**

We should not use `curl.setopts(..., str(url))` in py3 (never) and in py2 (only when importing `from builtins import str`, which is our current case). We should make sure that url is passed as a bytes encoded string. Maybe we can add the inverse of https://github.com/dmwm/WMCore/blob/ebfc5159d0245ad41be1701be450b106425cfcc1/src/python/Utils/Utilities.py#L195 to Utils/Utilities.py and call it `encodeUnicodeToBytes` and use it here.

**Describe alternatives you've considered**

We can run with our current code and hope that our URLs will never contain non-ascii characters (a bit risky)

**Additional context**

[This discussion](https://github.com/dmwm/CRABServer/issues/6374) may contain some more information.

**Comment by vkuznet** [comment]
Just for reference, DBS will needs full validation if you'll change anything in pycurl_manager as it heavily relies on it. I suggest you put @yuyiguo in a loop for every change you'll make with it.

**Comment by belforte** [comment]
FWIW CRAB is *not* passing non-ASCII characters. The problem in https://github.com/dmwm/CRABServer/issues/6374 comes from using WMCore's own build of python and future with the pycurl available in the system python and can be reproduced e.g. on lxplus [1].
I agree that mixing python stuff from here and there is not good and we should find a better solution for this particular CRAB use case. But indeed there does seem to be no need to touch things inside WMCore so far, since when we use a consistent build of pycurl, things work.

[1]
following lines are "just after login on lxplus" I added some comments
```
* Please read LXPLUS Privacy Notice in http://cern.ch/go/TpV7
* ********************************************************************
# use WMCore's pythong
belforte@lxplus712/~> source  /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/etc/profile.d/init.sh
# and its py2-future 
belforte@lxplus712/~> source  /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/py2-future/0.18.2/etc/profile.d/init.sh 
# add system libs for pycurl
belforte@lxplus712/~> export PYTHONPATH=$PYTHONPATH:/usr/lib64/python2.7/site-packages/
belforte@lxplus712/~> python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> curl=pycurl.Curl()
>>> from builtins import str
>>> url="something"
>>> type(url)
<type 'str'>
>>> curl.setopt(pycurl.URL, url)
>>> # that worked finely, now turn url into a future string
>>> furl=str(url)
>>> type(furl)
<class 'future.types.newstr.newstr'>
>>> print(furl)
something
>>> curl.setopt(pycurl.URL, furl)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid arguments to setopt
>>> 

```

**Comment by mapellidario** [comment]
Ok, now I see. My very few experience with our environments hit again. The system pycurl (which is the one provided by cc7) is `7.19.0`, which is from 2013 and for which there is not even documentation on the official website. I assume it does not have the auto-encoding of unicode strings in `setopt`. Meanwhile, I run unit tests with wmcore-devtools docker, which uses [a more modern pycurl}(https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-pycurl.spec) that hid my error under the carpet

**Comment by mapellidario** [comment]
#10250 should have restored the pre - #9818 behavior, and should be compatible with both old version of pycurl in py2 and py3
