### ISSUE TITLE
make it easier to reuse (parts of ) submit.sh in CRAB

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10257]
**Impact of the new feature**
WMAgent 

**Is your feature request related to a problem? Please describe.**
At this moment I have copy/pasted these two fragments of `submit.sh`, from indicated lines until the comment
which ends the action (thanks for such a well readable script) into CRAB job wrapper, replacing old code which we had for same goal.
https://github.com/dmwm/WMCore/blob/6362413ccbaeed76f9d09e33e11b5dab24a13eef/etc/submit.sh#L96
https://github.com/dmwm/WMCore/blob/6362413ccbaeed76f9d09e33e11b5dab24a13eef/etc/submit.sh#L119

This works now, but will requires constantly repeating this every time there's a significant change
Looking at future changes (CC8, PowerPC, exotic archs...), can we find a better way then me spying on this file and keeping copy pasting ? 

**Describe the solution you'd like**
Maybe put those functions in two separate, scripts which are sourced ? An overkill given how short and neat `submit.sh is`, but only to improve reuse. I presume there will be a way for CRAB TaskWorker to use spec files to add those files from a tagged WMCore release.

Argument passing via HTCondor, sandbox handling and other few things are too different in WMA and CRAB to make it possible for me to use full `submit.sh` as is.

**Describe alternatives you've considered**
Until/unless we do that, please keep me posted in case of relevant changes here. 

**Additional context**

**Comment by belforte** [comment]
@amaltaro  @khurtado One year later. I think it is not unpolite to ping.
E.g. CRAB is currently missing this great improvement:
https://github.com/dmwm/WMCore/commit/86bb82b1273b5265471dd0ea358802e71bd95b71

I can volunteer for a PullRequest, but not before we have an agreement on what to do.

This also relates to https://github.com/dmwm/WMCore/wiki/Notes-about-environment-variables-passed-to-the-Scram-environment-or-modified-when-running-the-CMSSW-executable  : how confident can we be that clearing $PYTHONPATH is enough to make sure that there is no interference between COMP and CMSSW environment ? The setup in `submit.sh` also adds things to `#LD_LIBRARY_PATH` and `$PATH`.

@mapellidario FYI

**Comment by khurtado** [comment]
Closing, following up on this issue instead: https://github.com/dmwm/WMCore/issues/11104
