### ISSUE TITLE
set required py2-future version in submit.sh where python is setup

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10258]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
 it costed me a some wasted time when I copied from submit.sh into CRAB wrapper,
since the python dependency is listed in an unexpected place. Makes cose harder
to read IMHO, Also you may want to be free to use different py2-future releases
for different archs at lines 121-126

**Describe the solution you'd like**
move these lines
https://github.com/dmwm/WMCore/blob/6362413ccbaeed76f9d09e33e11b5dab24a13eef/etc/submit.sh#L51-L52
to the place where python is bootstrapped ? Currently Line 120 and below.

**Describe alternatives you've considered**
leaving it like this. Which increases chances of mistakes in the future.

**Additional context**

**Comment by amaltaro** [comment]
Stefano, just to make sure I understand what you requested here:
* move the `PY_FUTURE_VERSION` (constant) variable closer to where the python logic is. Basically inside the block "WMAgent COMP Python bootstrap starting";
* and an auto-discovery logic for the latest py2-future version?

If so, my comments are:
* `PY_FUTURE_VERSION` is defined where the other constants and command line parameters are
* before we change the py2-future version, I hope we can actually stop depending on it.

**Comment by belforte** [comment]
I was only suggesting the first bulled. Was not suggesting any autodiscovery logic. We clearly disagree on what is the best place for such constant, but if you have in mind to stop depending on this.. who cares. This request was mostly triggered by the desire to put all of the "env. bootstrap" into a separate script which I can source in CRAB.

**Comment by belforte** [comment]
I guess we discussed enough, and came to conclusion that it is better not to change things
