### ISSUE TITLE
wrong errror message/exit code

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10259]
**Impact of the bug**
WMA

**Describe the bug**
**RATS** I put wrong link to code in initial posting. EDITING IT NOW.
misleading/unclear error message from
https://github.com/dmwm/WMCore/blob/6362413ccbaeed76f9d09e33e11b5dab24a13eef/etc/submit.sh#L140-L142
this message is printed when the previous code could not decide if to use $VO_CMS_SW_DIR or
$OSG_APP or $CVMFS. Which to begin with should never happen, i.e. a failures would have been caught by previous code. And if it would happen "job environment does not contain init.sh" it likely useless and misleading. Bootstrap failures are only triggered when a job happens to run a on a broken machine (CVMFS mount failures e.g.) and unless they are very specific and we print attempted commands and full stdout/stderr, they are usually useless for finding/fixing the actual problem.

**How to reproduce it**
Need to run a job on a broken WN to trigger this. 

**Expected behavior**
IMHO the full `else` clause should be removed.
The code which actually intializes python looks good to me.
Maybe the part which source cmsset_default.sh, which now only prints
```
======== WMAgent CMS environment load starting at Thu Feb  4 00:06:37 GMT 2021 ========
WMAgent bootstrap: WMAgent thinks it found the correct CMSSW setup script
======== WMAgent CMS environment load finished at Thu Feb  4 00:06:37 GMT 2021 ========
```
could also say WHERE it found CMSSW ($VO_CMS_SW_DIR|$OSG_APP|$CVMFS)

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by amaltaro** [comment]
It should take me 30min to get these fixes in, so let me get over with this sooner than later.
