### ISSUE TITLE
make it easy to run WMCore REST in debug mode

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10266]
**Impact of the new feature**
every develops who uses WMCore REST will benefit

**Is your feature request related to a problem? Please describe.**
At times I really need to run CRABServer (i.e. a REST application based on WCORE/REST) in the foreground, in single thread mode, with all messages coming to console and with full `pdb` access.
Maybe WMCore devbelopers already have a trick to do this ? If so, please point me to it !
Otherwise... keep reading.

**Describe the solution you'd like**
we have a recipe to do this which works since years, which simply requires commenting out severl lines,
but it is annoying to edit code all of the times:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#To_run_the_crabserver_in_debug_m

So I propose to add an ENV variable switch inside Main.py to skip code as needed.
It should be pretty simple and safe. I can provide a tested PR if you like the idea.

**Describe alternatives you've considered**
having a "ready to swap MainForDbg.py" at hand, but I need to create it again every time Main,py is changed
Also, to avoid copying in/out of the container all of the times, I should likely hide a script inside CRABServer build which accomplishes this on demand. Ugly to say the least !!!

**Comment by belforte** [comment]
@amaltaro As agreed in the chat, I'll provide a tested PR at some point. you can assign to me to help me keep track

**Comment by amaltaro** [comment]
Thank you, Stefano.
