### ISSUE TITLE
Enforce SiteBlacklist to be applied to all the tasks within a workflow

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10270]
**Impact of the bug**
Several components most probably. To be determined later.

**Describe the bug**
During a debugging triggered by the following Jira ticket: [1], we found out several things we consider not ideal in the Site blacklisting logic in WMCore.
   * When we have more than a single CPU resource mapped to the same Disk resource due to the PSN to PNN mapping (taken from CRIC) we fail to blacklist only one of the CPU resources. 
   * We cannot blacklist sites on a campaign level (different tasks from one and the same workflow may be members of different campaigns). This is a parameter (`siteBlacklist` from the campaign configuration) propagated to the workflow description, but taken into account only in the context of data placement rather than for job creation. 
   * When creating a blacklist we may take it into account in the job creation phase only for the first (top level task), so even if it is put in on the workflow level a blacklist would apply in full only for a whole StepChain request, while for a Task chain it will be enforced only for `Task1` and for the rest a PSN to PNN mapping would take precedence.   

[1]
https://its.cern.ch/jira/browse/CMSCOMPPR-18198

**How to reproduce it**
Try to create a TaskChain submitted to more than one CPU resources mapped to the same Disk resource (eventually with AAA enabled) and having PUs in the two different steps assigned to different campaigns, then try to blacklist one of the CPU resources in both:

   * For the whole workflow
   * For one of the campaigns (i.e. try to apply the blacklist only for a single task but not for the whole workflow)

Example:
`T2_CH_CERN`
`T2_CH_CERN_HLT`   

**Expected behavior**

To be able to set block sites and put them in the proper blocking list at the following 3 levels:
   * At the campaign level through the campaign configuration
   * At a task/ttep level through the workflow configuration
   * At workflow level (top level configuration) through the workflow description, which parameter should be propagated down the whole chain of tasks for a TaskChain workflow.

This configuration needs to take precedence over the mapping of PSN to PNN.   
 
**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by amaltaro** [comment]
@todor-ivanov let me clarify a few of your comments here to avoid misinterpretations of what gets reported here.

> When we have more than a single CPU resource mapped to the same Disk resource due to the PSN to PNN mapping (taken from CRIC) we fail to blacklist only one of the CPU resources.

This is not very accurate. The ban of PSNs based on the SiteBlacklist does work as expected in ALL workflow spec types. There is only one difference on how it works in TaskChain workflows - which are meant to contain many tasks chained - where the ban is only applied to the top level task (Task1).

> We cannot blacklist sites on a campaign level (different tasks from one and the same workflow may be members of different campaigns). This is a parameter (siteBlacklist from the campaign configuration) propagated to the workflow description, but taken into account only in the context of data placement rather than for job creation.

Job creation depends on the workflow assignment parameters. Given that WMCore does not own the workflow assignment, I'd say this is an invalid comment.

> Expected behavior
> To have all those 3 different levels of site blacklisting implemented properly

This has to be made very explicit, what are the goals and deliverables expected from this GH issue?

Having made these comments, I would definitely not call it a bug, but instead, it's a feature change to propagate the SiteBlacklist through all the tasks in a TaskChain. Which, by the way, can potentially fail jobs performing fallback stage out to a disk location that maps only to blacklisted PSNs...

**Comment by nsmith-** [comment]
> WMCore does not own the workflow assignment

Can you help me understand who owns this? Is it eventually in WMCore via MSAssignor project?

**Comment by todor-ivanov** [comment]
@nsmith- Depending on when we are about to start working on it. I suspect this one can easily get into the scope of MSAssignor. We for sure must consider this logic while developing MSAssignor.

**Comment by klannon** [comment]
Our development effort is sufficiently stretched that we need to understand where this fits in, including how urgent a problem this issue is and whether solving it can be handled as a longer term development or requires an immediate patch.  For sure, I think we should try to avoid solutions that will need to be redone after the transition to MSAssignor.  Can someone clarify the following?
* Is this a common/current/ongoing problem, or was it trigger by a special case that we don't expect to occur anytime soon?
* Is there any viable operational workaround that we can use before a fix is implemented?
* Do the solution strategies change once we've migrated to MSAssignor?  (If so, it would be best to schedule this for after that change.)
* Is there any benefit from applying a quick but simple patch ASAP, and then fixing more deliberately on a longer time scale (e.g. after the MSAssignor transition)?

**Comment by todor-ivanov** [comment]
Hi @klannon , I will try to address your questions briefly, to the best of my knowledge:

> Is this a common/current/ongoing problem, or was it trigger by a special case that we don't expect to occur anytime soon?

I would say, this is not something which just popped up last week. This behavior is present for long and now and then we hear  inquiries from P&R about clarifying this logic. We simply discussed this in the context of a concrete usecase last week, and me personally had to rediscover the logic based on a long process of try and fail attempts we made together with @haozturk (BTW thanks Hasan for the hard work)

>  Is there any viable operational workaround that we can use before a fix is implemented?

Yes there is one. Blacklisting both resources when all together is doing the job so far. In this case the root problem was the fact that HLT cannot read the Pilup remotely, which combined with all the `if`s and `then`s needed in order to hit the exact workflow configuration so that this behavior is triggered, reduces the number of workflows that suffer the issue to a limited number (I'd need someone from P&R to put the exact number here, but anyway it is not for all the workflows in the system that's for sure.

> Do the solution strategies change once we've migrated to MSAssignor? (If so, it would be best to schedule this for after that change.)

I think so. Because, at least by my understanding, part of the configuration parameters called `SiteBlacklist` (more precisely those coming from the campaign configuration), are never referred by WMCore but are only used by Unified. @amaltaro  please correct me here if I am wrong. So I would say it should be a design/coding along and in parallel with the MSAsaignor.

>  Is there any benefit from applying a quick but simple patch ASAP, and then fixing more deliberately on a longer time scale (e.g. after the MSAssignor transition)?

My opinion is that from a quick patch we wouldn't gain that much, but we would rather put extra effort in something which in really near future we would come to redesign  it yet again.

**Comment by nsmith-** [comment]
I agree with Todor's assessment. There is no urgent operational issue that needs to be resolved, and the workaround, though limiting the available resources for certain workflows, is not too onerous.
On the eventual redesign, I mention in passing this interesting RFC: https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by haozturk** [comment]
I forgot to add my comment last week: I would agree that there is no urgent operational issue and we finally understood how the current logic works. Just let me add that I believe the current implementation is not intuitive at all and our trial and errors w/ Todor in a 2 week period supports this argument. It was not clear at the first place how to proceed and this might lead to other confusions in the future unless it's changed.

**Comment by amaltaro** [comment]
Priority updated according to Hasan's input on the Q3 planning (6/10)

**Comment by haozturk** [comment]
I think, we should either re-structure this issue or create a new one w/ the name: 
```
Decouple T2_CH_CERN and T2_CH_CERN_HLT such that CERN jobs aren't redirected to HLT
```
What do you think? From ops perspective, this is what matters. This was discussed this week's CompOps meeting and people agreed upon the importance of the fix of this issue.

**Comment by amaltaro** [comment]
Moved from 2023 Q3 to Q4, as we plan to finish it in the coming days.
