### ISSUE TITLE
Test PSet tweaking on a patched agent submitting to the ITB 

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10286]
**Impact of the new feature**
This will test a patched agent with (yet to be updated with latest changes) PR #10179, submitting different workflow types.

**Is your feature request related to a problem? Please describe.**
PSet tweaking python2/3 changes

**Additional context**
- Testbed central services are broken, so I need to re-deploy my own central services to test this first

**Comment by amaltaro** [comment]
@khurtado Hi Kenyi, sorry for not getting back to you sooner. If you are still trying to run those tests, please ping me on slack and I will help you with them.

**Comment by amaltaro** [comment]
@khurtado I think this work has been completed as well, right? If so, can you please close it? Thanks

**Comment by amaltaro** [comment]
As just chatted with Kenyi, this issue has been worked on. Closing.
