### ISSUE TITLE
Add spec creation validation for the SubRequestType parameter

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10282]
**Impact of the new feature**
ReqMgr2

**Is your feature request related to a problem? Please describe.**
Given that we started using this field to take decisions in different parts of the system (mostly microservices as far as I remember), we better add some validation and make sure the data type and the value is as expected.

Here is its definition: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1035

**Describe the solution you'd like**
Add a validation function for the `SubRequestType` field. It needs to be evaluated during request creation, and request creation should fail if the provided value does not pass the validate function.

The supported values for this parameter are (still discussing with Justinas/PdmV the last bits):
```
["MC", "ReDigi", "Pilot", "RelVal", "HIRelVal", "ReReco"]
``` 
if value is not provided, it should default to an empty string.

**Describe alternatives you've considered**
Not add this validation and suffer the consequences in the future.

**Additional context**
none

**Comment by amaltaro** [comment]
@justinasr Hi Justinas, it looks like another development will depend on this field, so I think right now is the best moment to get this validation in place (to be deployed in production in the next week). Could you please review the list of allowed values above? @jordan-martins and @haozturk might have some input as well.

**Comment by justinasr** [comment]
Hi @amaltaro,

Looks good to me, McM uses "MC", "ReDigi" and "Pilot", RelVals use "RelVal" and fingers crossed for "ReReco" TaskChain becoming a thing.

**Comment by amaltaro** [comment]
Great! Thanks for the prompt confirmation, Justinas! We seem to have everything in place and ready to deploy in testbed today.
