### ISSUE TITLE
Validate #10179 in ITB against different workflow types

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10347]
**Impact of the new feature**
This will validate the new PSet tweaking methods against different workflows.

**Is your feature request related to a problem? Please describe.**
This is related to the PSet Tweaking for python2/3 migration

**Describe the solution you'd like**

**Comment by khurtado** [comment]
Update: At present, Alan is injecting workflows in his Central Services and I'm doing the validation of the results.

**Comment by amaltaro** [comment]
This has been validated against ITB and it's already in use by the RelVal agent for a month or so:
https://github.com/dmwm/WMCore/pull/10179

There are still some issues with the T0 runtime tweak, but those are being handled in other GH issues.

@khurtado I'm going to close this issue, but feel free to reopen it if I missed anything. Thanks
