### ISSUE TITLE
Jenkins - run futurize (all stages) to files changed in PRs

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10343]
**Impact of the new feature**

Jenkins report

**Is your feature request related to a problem? Please describe.**

If we want to be sure we do not add regressions in our code by using py2-only-compatible idioms, one of the tools that can be helpful would be to run `futurize` (all stages) on the files that are modified in a PR.

**Describe the solution you'd like**

We already run `futurize` stage 1 fixers and we add it to the "Python3 compatibility checks"/"Summary of python3 compatibility repor" section of the report. We could run all `futurize` stages and add the results in that very same spot.

What I have in mind is something like changing [this line in pyfutureTest.sh](https://github.com/dmwm/Docker/blob/29e330fcbe774cdd0c05b597792c7c5f0e430e67/wmcore_base/ContainerScripts/pyfutureTest.sh#L29) as follows

```bash
- futurize -1 $name >> test.patch
+ futurize $name >> test.patch
```
And maybe we should also change [this header](https://github.com/dmwm/Docker/blob/29e330fcbe774cdd0c05b597792c7c5f0e430e67/jenkins_python/templates/pyfutureSummary.jinja#L13) to something like "Futurize makes the following suggestions. You should ignore them only if you are sure these are false positives.".

**Describe alternatives you've considered**

We already have `pylint --py3k` report in place, this new addition would make our automated reports more complete.

**Comment by amaltaro** [comment]
@mapellidario Hi Dario, I have just noticed that this ticket and https://github.com/dmwm/WMCore/issues/10519 actually have the opposite requirements. 

I'm about to completely drop this "Python3 compatibility" checks via futurize, in favor of py2 pylint, py3 pylint and py pytlint --py3k. Do you think we should maintain these futurize checks?

**Comment by mapellidario** [comment]
After a private discussion with Alan, we agreed upon that pylint in both py2 and py3, `pylint --py3k` and unittest in py3 should be enough to catch all the py3 shortcomings. Running `futurize` became redundant and we can discard this suggestion from my past-self.

Thanks @amaltaro for improving the Jenkins report!

(closing with this comment)
