### ISSUE TITLE
Reorganize microservices packages and modules within their own package

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10356]
**Impact of the new feature**
Microservices

**Is your feature request related to a problem? Please describe.**
With all the microservices already created, and still others already planned to be created, I think we should better organize those packages/modules under WMCore/MicroService to properly reflect the code and service provided.

**Describe the solution you'd like**
Still trying to make the whole picture in my mind, but the obvious re-organization is that each microservice should live inside its own package (named after the microservice).

TODO: update this description once other things are more clear.

**Describe alternatives you've considered**
Keep things as they are.

**Additional context**
none

**Comment by todor-ivanov** [comment]
Well done @amaltaro! I like this  reorganization pretty much. It is in perfect coherence with my practice of running the micro services standalone. And I like to have everything from a module at a single place.
