### ISSUE TITLE
[py2py3] test str use in src/python/WMCore/ReqMgr/Service/RequestAdditionalInfo.py

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10376]
**Impact of the bug**
It involves `src/python/WMCore/ReqMgr/Service/RequestAdditionalInfo.py` and all the users of `RequestAdditionalInfo.WorkloadConfig.get()`.

**Describe the bug**

 We have not observed any bug at the moment, but this is likely to create some problems.

In we use `str()` in python2 in
 
```python
class WorkloadConfig(RESTEntity):
 ...
@restcall(formats=[('text/plain', PrettyJSONFormat()), ('application/json', JSONFormat())])
@tools.expires(secs=-1)
def get(self, name):
     helper = WMWorkloadHelper()
      ...
      return str(helper.data)
```
Which is directly used in `src/python/WMCore/ReqMgr/Service/RestApiHub.py`, which is not clear to me how it  works. It is possible that we need to return bytes at all costs here, we have to check this.

**Expected behavior**
These are supposed to behave the same in py2 and py3 as he previous lines, but there is a somewhat high probability that they will not. We should make sure that these lines behave properly when we have a py3 environment.

**Comment by amaltaro** [comment]
Honestly, I had never explicitly used this API `workload_config`. Looking at a couple requests (old and new):
https://cmsweb-testbed.cern.ch/reqmgr2/data/workload_config/amaltaro_SC_ReDigi_Harvest_Agent136_Val_200814_105846_7752
https://cmsweb-testbed.cern.ch/reqmgr2/data/workload_config/amaltaro_TC_PY3_TTbarPU_HG2107_ValPY3_210630_230315_3410

everything looks fine to me - even though we do not have the old version available to have some better comparisons.

I'd suggest to close this issue. If a problem is spotted in the future, we can always reopen it or create a new issue. @mapellidario what do you think?

**Comment by mapellidario** [comment]
If it looks good to you, then I would suggest closing this! Thanks for checking Alan! :) (I leave to you the pleasure of closing, you did the check after all!)

**Comment by amaltaro** [comment]
No problems have been spotted so far, so closing this issue.
