### ISSUE TITLE
Elimate difference between "component" and "standalone" webapps

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#1037]
The current code can give rise to simple errors in the configuration stopping the app from running. Removing the distinction between the two styles of app would simplify matters. I don't really remember the reason for the "component" style - is it just to get the same logger/database pool?

With Deploy/manage scripts I think making everything a standalone application wouldn't be a bad idea. You get the added bonus of the things being separate processes, with their own logging and database connections (which means you could have different levels of access for different tasks).

**Comment by ticoann** [comment]
Closing this
