### ISSUE TITLE
Perform RelVal tests using changes in PR#10179

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10387]
**Impact of the new feature**
Check PSet tweaking changes work okay with RelVal validation tests

**Is your feature request related to a problem? Please describe.**
This is related to the Decoupling WMCore/CMSSW PSet tweaking topic

**Describe the solution you'd like**
Either add an agent and team in production where we can inject RelVal workflows, or use ITB + Alan Central Services for the tests.

**Describe alternatives you've considered**

**Additional context**
This is related to validating the changes in: https://github.com/dmwm/WMCore/pull/10179

**Comment by amaltaro** [comment]
This has already been tested and a production RelVal agent has been deployed a month ago.
@khurtado if I missed anything, please reopen this issue.
