### ISSUE TITLE
Tests PSet changes PR #10179 against T0

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10386]
**Impact of the new feature**
Decouple WMCore /CMMSW Pset tweaking, including for T0

**Is your feature request related to a problem? Please describe.**
We need to make sure changes integrate with T0. 

**Describe the solution you'd like**
Any changes needed? Where? We need to test.

**Additional context**
This is a subtask of validating https://github.com/dmwm/WMCore/pull/10179

**Comment by amaltaro** [comment]
This ticket is more than 1.5 years old. So I assume it has already been extensively tested (even in production :D). Closing this out, but feel free to reopen it in case I missed anything. @khurtado
