### ISSUE TITLE
Core slot incompatibility between sites and jobs: Handle the issue better and make error code more meaningful

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10385]
**Impact of the new feature**
Debugging the issues in case of core slot incompatibility between sites and jobs

**Is your feature request related to a problem? Please describe.**
This is discussed in SI meeting: Recently, we have seen that many prod jobs were failed at T2_TR_METU site due to:
```
JobKilled (Exit code: 71305)
The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Pending.
``` 
In fact, the problem was that the jobs were multicore while the site only has single slots and therefore jobs could not find slots to run. It took really days to figure out the issue. If the error code and its explanation were more meaningful, we would have spotted the issue much earlier.

An example: https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_task_B2G-RunIISummer16NanoAODv7-03193__v1_T_210120_171738_2342 

**Describe the solution you'd like**
I see two steps to move forward:
1. Those jobs should fail immediately instead of failing with timeouts. Or better we should redirect those jobs to more suitable sites.
2. Make the error code more meaningful, so that people can understand the problem right away and act accordingly.

**Describe alternatives you've considered**
None

**Additional context**
Any comment is much appreciated

**Comment by amaltaro** [comment]
Hasan, if I understand your request correctly, you're basically asking WMAgents to be aware of which kind of resources are provided in a given site, and which kind of pilots is it set to use.

Even though it's a good idea, I'm against of adding resource awareness logic inside WMAgent, changing the behaviour of job creation and submission. I'd rather rely on a proper workflow assignment, and avoid having such complexity in the agent.
This also means the system cannot give you a more meaningful error message.

As discussed in that private thread with Antonio and others, there is a push to move the final T2 sites to 8-core pilots. With that in place, there wouldn't be too much value with this feature as well.

Does it make sense?

**Comment by haozturk** [comment]
Hi Alan, sure, I'm aware that this introduces a new complexity in the agent and I am also aware that this is not needed with the new improvements on the T2 sites. My point was to improve the system such that it has better error handling in case somehow this happens. If you think that what we will gain with this feature is not worthwhile compared to the necessary effort needed to provide it, it's totally fine with me to cancel this feature request.

**Comment by amaltaro** [comment]
Hasan, I'm afraid I have to say the effort of such feature (and maintenance) isn't going to pay off. Especially because there are efforts from other groups to avoid this from happening again.

**Comment by haozturk** [comment]
Hi Alan, that's perfectly reasonable. Yesterday, in the SI meeting, we agreed to check if this is possible. Good to have a understanding on the necessary effort for this feature. Feel free to close the issue.

**Comment by amaltaro** [comment]
Thanks Hasan, closing this issue then.
