### ISSUE TITLE
JobAccountant crashing with over encoded byte strings in 1.4.7.pre6

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10381]
**Impact of the bug**
WMAgent

**Describe the bug**
This is the latest WMAgent pre-release, 1.4.7.pre6, and JobAccountant crashes while looking for a storage name in the `wmbs_pnns` table. From the traceback [1], one can see that the same string has been encoded to bytes over and over.

 I don't think the problem comes from the modernization of JobAccountant/AccountantWorker modules, but probably somewhere during runtime (e.g., when filling in the job report)

**How to reproduce it**
Still to be debugged and understood

**Expected behavior**
PNN should be a byte string (not sure if an unicode string would cause DB problems though) and the component should be functional and stable. 

**Additional context and error message**
Traceback from my test VM vocms0261
```
2021-03-24 17:34:46,338:140442208630528:INFO:AccountantWorker:Handling /data/srv/wmagent/v1.4.7.pre6/install/wmagent/JobCreator/JobCache/amaltaro_TaskChain_ProdMinBias_Mar2021_Val_210324_165533_4353/ProdMinBias/JobCollection_1_0/job_60/Re
port.0.pkl
2021-03-24 17:34:46,343:140442208630528:INFO:AccountantWorker:Job 60 , handle successful job
2021-03-24 17:34:46,347:140442208630528:ERROR:AccountantWorker:PNN doesn't exist in wmbs_pnns table: b'b'b'b'T2_CH_CERN'''' (investigate)
2021-03-24 17:34:46,474:140442208630528:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobAccountant.JobAccountantPoller.JobAccountantPoller object at 0x7fbb4a505e10> b'<@========== WMException Start ==========@>
Exception Class: AccountantWorkerException
Message: PNN doesn't exist in wmbs_pnns table: b'b'b'b'T2_CH_CERN'''' (investigate)
        ModuleName : WMComponent.JobAccountant.AccountantWorker
        MethodName : handleWMBSFiles
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py
        ClassName : None
        LineNumber : 814
        ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>'  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 183, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMCore/Database/DBExceptionHandler.py", line 40, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/Utils/Timers.py", line 26, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 70, in algorithm
    self.accountantWorker(jobsSlice)
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 249, in __call__
    self.handleWMBSFiles(self.wmbsFilesToBuild, self.parentageBinds)
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 814, in handleWMBSFiles
    raise AccountantWorkerException(msg)
```

**Comment by amaltaro** [comment]
Yes, indeed the FJR seems to be messy. Here is how to reproduce a similar problem (not exactly the same initially reported, but still a problem to be fixed):
```
>>> from WMCore.FwkJobReport.Report import Report
>>> from pprint import pprint
>>> jobReport = Report()
>>> jobReport.load('/data/srv/wmagent/v1.4.7.pre6/install/wmagent/JobCreator/JobCache/amaltaro_TaskChain_ProdMinBias_Mar2021_Val_210324_165533_4353/ProdMinBias/JobCollection_1_0/job_60/Report.0.pkl')
>>>
>>> from WMCore.JobStateMachine import SummaryDB
>>> wmbsJob = {}
>>> wmbsJob["fwjr"] = jobReport
>>> SummaryDB.fwjr_parser(wmbsJob)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.4.7.pre6/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.pre6/lib/python2.7/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 86, in fwjr_parser
    pdict['totalJobCPU'] += float(perf['cpu']['TotalJobCPU'])
ValueError: could not convert string to float: b'b'b'b'335.676''''
```

**Comment by mapellidario** [comment]
Is it possible that the culprit is the module that write the pickle file, and not the parser?
Alan, could you send me your pickle (or a recipe to reproduce it if it's not too complicated)?

(I will move the issue back in To-Do)

**Comment by amaltaro** [comment]
> Is it possible that the culprit is the module that write the pickle file, and not the parser?

I guess we cannot discard this possibility yet.

> Alan, could you send me your pickle (or a recipe to reproduce it if it's not too complicated)?

Producing the WMAgent FJR is likely tricky. I need to dive into the code and see how that's done. Let's see if I can get back to you by the end of the day.

PS.: I moved it back to Work in progress because it's the next item in my todo list (it's a blocker for releasing a new WMAgent production version).

**Comment by amaltaro** [comment]
Dario, I finally managed to reproduce this problem and it looks like you are right, the problem is parsing the pickle file somehow, I still have to digest this all though.

The steps to reproduce it are sort of convoluted, but here we go.
1. first we need to copy the CERN site-local-config.xml to either a WMAgent node or your laptop where you can run WMCore code, something like this:
```
amaltaro@lxplus775:~ $ cp /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml /afs/cern.ch/work/a/amaltaro/www/forAlan/
```
2. Copy this site-local-config file to under src/python in your WMCore project
3. Set your pythonpath (or source the agent init.sh), something like:
```
export PYTHONPATH="${PYTHONPATH}:/Users/amaltaro/Pycharm/WMCore/src/python/"
``` 
4. Create this script `loadSite.py` with the following content:
```
#!/usr/bin/env python
import logging
import sys
import WMCore.WMRuntime.Bootstrap as Bootstrap
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

job = dict(id=1234, name="alan_test", task="/alan_test/taskOne")
reportName = "alan_report.pkl"
logging.info("Creating initial report")
Bootstrap.createInitialReport(job=job, reportName=reportName)
logging.info("Done creating initial report")
```
5. Modify the SiteLocalConfig.py module to point to your disk instead of CVMFS, something like:
```
--- a/src/python/WMCore/Storage/SiteLocalConfig.py
+++ b/src/python/WMCore/Storage/SiteLocalConfig.py
@@ -39,7 +39,8 @@ def loadSiteLocalConfig():
             msg = "%s env. var. provided but not pointing to an existing file, ignoring." % overVarName
             logging.log(logging.ERROR, msg)
 
-    defaultPath = "$CMS_PATH/SITECONF/local/JobConfig/site-local-config.xml"
+    os.environ["CMS_PATH"] = "/Users/amaltaro/Pycharm/WMCore/src/python"
+    defaultPath = "$CMS_PATH/site-local-config.xml"
     actualPath = os.path.expandvars(defaultPath)
```
6. then execute `python loadSite.py `, which should produce an output similar to [^]
7. If it succeeds, it will create a new pkl file in the upper directory. Copy it to pwd, something like:
```
cp ../alan_report.pkl .
```
8. Finally, open a python interpreter prompt and reproduce the final details with:
```
from WMCore.FwkJobReport.Report import Report
from pprint import pprint
jobReport = Report()
jobReport.load("/Users/amaltaro/Pycharm/WMCore/src/python/alan_report.pkl")
### and now the BIG surprise
In [5]: jobReport.getSiteName()
Out[5]: b"b'T2_CH_CERN'"
```

There we go with double encoding of the site name. I guess we have a problem on how byte strings (preceded by b') are persisted in a pickle object (or how they are loaded into python object)... Still to be discovered...

[^]
```
INFO:root:Creating initial report
AMR value before: [] and type: <type 'list'>
INFO:root:AMR log value before: [] and type: <type 'list'>
AMR value before: Unknown and type: <type 'str'>
INFO:root:AMR log value before: Unknown and type: <type 'str'>
AMR value before: 1234 and type: <type 'int'>
INFO:root:AMR log value before: 1234 and type: <type 'int'>
AMR value before: alan_test and type: <type 'str'>
INFO:root:AMR log value before: alan_test and type: <type 'str'>
AMR value before: T2_CH_CERN and type: <class 'future.types.newstr.newstr'>
INFO:root:AMR log value before: T2_CH_CERN and type: <class 'future.types.newstr.newstr'>
AMR value after: b'T2_CH_CERN' and type: <class 'future.types.newbytes.newbytes'>
INFO:root:AMR log value after: b'T2_CH_CERN' and type: <class 'future.types.newbytes.newbytes'>
AMR value before: T2_CH_CERN and type: <class 'future.types.newstr.newstr'>
INFO:root:AMR log value before: T2_CH_CERN and type: <class 'future.types.newstr.newstr'>
AMR value after: b'T2_CH_CERN' and type: <class 'future.types.newbytes.newbytes'>
INFO:root:AMR log value after: b'T2_CH_CERN' and type: <class 'future.types.newbytes.newbytes'>
AMR value before: alannewmacpro.home and type: <type 'str'>
INFO:root:AMR log value before: alannewmacpro.home and type: <type 'str'>
AMR value before: alannewmacpro.home and type: <type 'str'>
INFO:root:AMR log value before: alannewmacpro.home and type: <type 'str'>
AMR value before: {} and type: <type 'dict'>
INFO:root:AMR log value before: {} and type: <type 'dict'>
AMR value before: {} and type: <type 'dict'>
INFO:root:AMR log value before: {} and type: <type 'dict'>
AMR value before: False and type: <type 'bool'>
INFO:root:AMR log value before: False and type: <type 'bool'>
AMR value before: /alan_test/taskOne and type: <type 'str'>
INFO:root:AMR log value before: /alan_test/taskOne and type: <type 'str'>
INFO:root:Done creating initial report
```

**Comment by amaltaro** [comment]
@mapellidario don't even waste time reading the previous comment. Here's an smarter way to reproduce that problem:
```
In [1]: import pickle

In [2]: from builtins import str as newstr, bytes

In [3]: ddd = dict(bytes=bytes('alan'), string=newstr('mid_name'), unicode=u'last_name')

In [4]: ddd
Out[4]: {'bytes': b'alan', 'string': 'mid_name', 'unicode': u'last_name'}

In [5]: pickle.dumps(ddd)
Out[5]: '(dp0\nS\'bytes\'\np1\nccopy_reg\n_reconstructor\np2\n(cfuture.types.newbytes\nnewbytes\np3\nc__builtin__\nstr\np4\nS"b\'alan\'"\np5\ntp6\nRp7\nsS\'string\'\np8\ng2\n(cfuture.types.newstr\nnewstr\np9\nc__builtin__\nunicode\np10\nVmid_name\np11\ntp12\nRp13\nsS\'unicode\'\np14\nVlast_name\np15\ns.'

In [6]: pklObj = pickle.dumps(ddd)

In [7]: pickle.loads(pklObj)
Out[7]: {'bytes': b"b'alan'", 'string': 'mid_name', 'unicode': u'last_name'}
```

**Comment by mapellidario** [comment]
I continued the investigation a bit, but I did not make too much progress.

I had an epiphany this afternoon. In python2 there should not be any type that is represented (with `__repr__` or `__str__`) with `b"my string"` and the only possibility is converting a string (unicode or btyes) to the class `future.types.newbytes.newbytes`, which is the one imported with `from builtins import bytes`. This means that if we use `bytes` from `builtins` to check a string type and then if it is unicode then we encode it, the result should be a python2 `str` which is not represented with the `b""`. We would have something that has the `b""` only if we use `bytes(mystring)`.  See the example below.

I created a new branch in https://github.com/mapellidario/WMCore/tree/10381-fix with a possible fix, in which I replace the conversion to bytes string using `bytes()` to ones using `unicode.encode()`. I tested it with the recipe that you provide me earlier and it does not solve this problem :sob: . I did some bisecting and the problem appears from `1.4.7.pre4`. If I have to bet, now that I have to go back to drawing board I restart investigating slice 17.

There is a catch and, as almost always, I am very puzzled: I am not sure why this line

https://github.com/dmwm/WMCore/blob/dd63a901a9b929d83cbe83e9a2f9004e0901a90c/src/python/WMCore/Configuration.py#L145

should return a string that is represented with `b""`. I will continue to have a look around.

Maybe we will have to look somewhere else, I will keep you posted.

#### example

I run this in `dmwm/WMCore` after sourcing the dev environment:

```python
from __future__ import print_function
from builtins import str as newstr, bytes as newbytes

import pickle
import pprint

from Utils.Utilities import encodeUnicodeToBytes

lll = [
    newbytes('dario newbytes'),
    bytes('dario py2-bytes'),
    bytes(u'dario py2-bytes'),
    encodeUnicodeToBytes(u'dario unicode, encoded'),
    newstr('dario newstr'), 
    u'dario unicode'
]

pprint.pprint(pickle.loads(pickle.dumps(lll)))
```

whose result is

```plaintext
[b"b'dario newbytes'",
 'dario py2-bytes',
 'dario py2-bytes',
 'dario unicode, encoded',
 'dario newstr',
 u'dario unicode']
```

**Comment by amaltaro** [comment]
Thanks Dario. All my attempts to get it fixed have failed so far, including the conversion of byte to unicode strings in that __setattr__ method, it breaks job submission and SimpleCondorPlugin (at least!).
I will try a new variation based on your first paragraph above.
