### ISSUE TITLE
[py2py3] test str/bytes use in src/python/WMCore/ReqMgr/Web/*

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10382]
**Impact of the bug**

It should affect `src/python/WMCore/ReqMgr/Web/*` only.

**Describe the bug**
 We have not observed any bug at the moment, but this is somewhat likely to create some problems.

We make a lot of string juggling in `src/python/WMCore/ReqMgr/Web/*`, in particular with data coming from cherrypy. We should really make sure that the modernization in #10379 is compatible with bot py2 and py3.

**Expected behavior**
Nothing should break (I know, not very informative. we will update this description while investigating)

**Comment by amaltaro** [comment]
ReqMgr2 Web GUI has been tested during the HG2107 validation phase, a bug fix has been made against for the time library, and it seems to be working properly.
So, I take the opportunity to close it.
