### ISSUE TITLE
[py2py3] check the use of division

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10397]
**Impact of the bug**

WMCore in general

**Describe the bug**
We have not observed any bug at the moment, but it is possible that this will create some problems.

During the modernization campaign, we made such changes:

```python
 from __future__ import division
...
                infoSSB[site]['slotsCPU'] *= self.t1SitesCores / 100
                infoSSB[site]['slotsIO'] *= self.t1SitesCores / 100
                infoSSB[site]['slotsCPU'] *= self.t1SitesCores // 100
                infoSSB[site]['slotsIO'] *= self.t1SitesCores // 100
```

While we tried to be as transparennt as possible, there is a non-zero possibility that this breaks some interfaces. We should check at least

- [ ] `src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py`
- [ ] `src/python/WMComponent/JobArchiver/JobArchiverPoller.py`

**How to reproduce it**

**Expected behavior**
We should make sure that the changes to how py3 deals with division are as transparent as expected.

**Comment by amaltaro** [comment]
I assume this has been well tested with Py3 WMAgent 1.5.2. Closing this issue as well.
