### ISSUE TITLE
Propagate workflow GPU parameters to the job specification/classads

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10393]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Once this issue is addressed: https://github.com/dmwm/WMCore/issues/10388
the next step is to propagate the workflow level GPU parameters all the way down to the job creation, job submission and job classad.

**Describe the solution you'd like**
In short, we need to propagate the workflow GPU configuration all the way to JobCreator, to be picked up by JobSubmitter and finally passed to the SimpleCondorPlugin, which should properly fill the condor job classad (and expressions where needed).

Trying to expand on the job classads (still needs further discussion with the SI team):
* workflow/task/step `RequiresGPU` mapped to job classad `RequiresGPU`, with one of the possible 3 string values:
  * `forbidden`: must not use GPUs (**default**)
  * `optional`: can use GPU, if possible
  * `required`: must use GPUs
* workflow/task/step `GPUMemoryMB` mapped to job classad `GPUMemoryMB`, string type (just as OriginalMemory is), default value to 0.
* workflow/task/step `CUDACapabilities` mapped to job classad `CUDACapabilities`, a comma separated string (just as DESIRED_Sites is), default value to empty string (should default value be `undefined` instead?);
* workflow/task/step `CUDARuntime` mapped to job classad `CUDARuntime`, string type, default to empty string (should default be `undefined` instead?)

The job matchmaking logic would be something like:
* if (`RequestGPU` == "forbidden") || (`RequestGPU` == "optional"), then forget GPUs in the matchmaking
* if `RequestGPU` == "required", then:
  * job's `GPUMemoryMB` <= node's `GPUMemoryMB`
  * at least one job's `CUDACapabilities` in the node's `CUDACapabilities`
  * job's `CUDARuntime` among those in the node's `CUDACompatibleRuntimes`

This description might be updated as we discuss it further with the SI team and converge on the best classad naming convention and data type.

**Describe alternatives you've considered**
This issue considers only the **required** parameters. In the future, we can also explore supporting the 3 optional spec parameters at job description level.

**Additional context**
 Major discussion happened here: cms-sw/cmssw#33057

**Comment by rcaspart** [comment]
One comment, and maybe I am simply misunderstanding the scope here. In that case feel free to discard this point.

Is there a specific reasoning for calling the classAd `RequestGPU` instead of e.g. `RequiresGPU`. At first glance to me this seems very close to the HTCondor native classAd `RequestGPUs` for declaring the requested number of GPUs for a job and could potentially lead to confusions when not paying close attention.

**Comment by amaltaro** [comment]
Hi Rene
> Is there a specific reasoning for calling the classAd RequestGPU instead of e.g. RequiresGPU

That's a good question and `RequiresGPU` would be my preference as well. However, I see that in our plugin we are already specifying different slots with the Request* pattern, such as: `Requestioslots` and `RequestRepackslots`.

If SI folks agree, I'm happy to update it from RequestGPU to RequiresGPU.

**Comment by srimanob** [comment]
As I try to update the PR, one thing which is unclear to me is that these parameters/attributes should be defined globally or in task/step that needs GPU of the workflow.

I am putting this comment also in https://github.com/cms-sw/cmssw/pull/33057

**Comment by amaltaro** [comment]
@srimanob Phat, I think our use case requires it to be flexible at the task and step level as well, right? This is how we are planning to implement at TaskChain and StepChain:
https://github.com/dmwm/WMCore/issues/10400
https://github.com/dmwm/WMCore/issues/10401

In short, it will be as flexible as other job requirements (Multicore, Memory, etc). Please let us know though in case you have a different view and/or use cases for this.

**Comment by srimanob** [comment]
Hi @amaltaro 
Yeah, I think in a similar way too. I will need to simplify how the code will look like for runTheMatrix, because other parameters (memory, cores), are cloned from global parameters.

Note that, this is on CMSSW runTheMatrix coding only. Not for PdmV relvals, McM machines where each step can be configured separately easily. @justinasr

**Comment by srimanob** [comment]
OK, I have updated the PR for runTheMatrix as we discussed. When `--RequiresGPU == 2`, and taskname/stepname contains "GPU" string, it will add GPU params to the task/step. It is unclear how `--RequiresGPU == 1` will be, need to converge.

`runTheMatrix.py --what upgrade -l 11650.502 --RequiresGPU 2 --wm init`

Here is how the workflow looks like:
```
{'AcquisitionEra': 'CMSSW_11_3_X_2021-04-15-2300',
 'CMSSWVersion': 'CMSSW_11_3_X_2021-04-15-2300',
 'Campaign': 'CMSSW_11_3_X_2021-04-15-2300',
 'ConfigCacheUrl': 'https://cmsweb.cern.ch/couchdb',
 'DQMConfigCacheID': 1041,
 'DQMUploadUrl': 'https://cmsweb.cern.ch/dqm/relval',
 'DbsUrl': 'https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader',
 'EnableHarvesting': 'True',
 'GlobalTag': u'113X_mcRun3_2021_realistic_v9',
 'Group': 'ppd',
 'Memory': 3000,
 'Multicore': 1,
 'PrepID': 'CMSSW_11_3_X_2021-04-15-2300__1618560038-ZMM_14',
 'ProcessingString': u'113X_mcRun3_2021_realistic_v9',
 'ProcessingVersion': 1,
 'RequestPriority': 500000,
 'RequestString': 'RVCMSSW_11_3_X_2021-04-15-2300ZMM_14',
 'RequestType': 'TaskChain',
 'Requestor': 'srimanob',
 'ScramArch': 'slc7_amd64_gcc900',
 'SizePerEvent': 1234,
 'SubRequestType': 'RelVal',
 'Task1': {'AcquisitionEra': 'CMSSW_11_3_X_2021-04-15-2300',
           'ConfigCacheID': 1043,
           'EventStreams': 0,
           'EventsPerJob': 100,
           'EventsPerLumi': 100,
           'GlobalTag': u'113X_mcRun3_2021_realistic_v9',
           'KeepOutput': True,
           'Memory': 3000,
           'Multicore': 1,
           'PrimaryDataset': 'RelValZMM_14',
           'ProcessingString': u'113X_mcRun3_2021_realistic_v9',
           'RequestNumEvents': 18000,
           'Seeding': 'AutomaticSeeding',
           'SplittingAlgo': 'EventBased',
           'TaskName': 'ZMM_14TeV_TuneCP5_2021_GenSim'},
 'Task2': {'AcquisitionEra': 'CMSSW_11_3_X_2021-04-15-2300',
           'ConfigCacheID': 1044,
           'EventStreams': 0,
           'GPUParams': set([None]),
           'GlobalTag': u'113X_mcRun3_2021_realistic_v9',
           'InputFromOutputModule': u'FEVTDEBUGoutput',
           'InputTask': 'ZMM_14TeV_TuneCP5_2021_GenSim',
           'KeepOutput': True,
           'LumisPerJob': 10,
           'Memory': 3000,
           'Multicore': 1,
           'ProcessingString': u'113X_mcRun3_2021_realistic_v9',
           'RequiresGPU': 0,
           'SplittingAlgo': 'LumiBased',
           'TaskName': 'Digi_2021'},
 'Task3': {'AcquisitionEra': 'CMSSW_11_3_X_2021-04-15-2300',
           'ConfigCacheID': 1042,
           'EventStreams': 0,
           'GPUParams': {'CUDACapabilities': ['7.5'],
                         'CUDADriverVersion': '',
                         'CUDARuntime': '11.2',
                         'CUDARuntimeVersion': '',
                         'GPUMemory': '8000',
                         'GPUName': ''},
           'GlobalTag': u'113X_mcRun3_2021_realistic_v9',
           'InputFromOutputModule': u'FEVTDEBUGHLToutput',
           'InputTask': 'Digi_2021',
           'KeepOutput': True,
           'LumisPerJob': 10,
           'Memory': 3000,
           'Multicore': 1,
           'ProcessingString': u'113X_mcRun3_2021_realistic_v9',
           'RequiresGPU': 2,
           'SplittingAlgo': 'LumiBased',
           'TaskName': 'Reco_Patatrack_PixelOnlyGPU_2021'},
 'TaskChain': 3,
 'TimePerEvent': 10}
```

**Comment by fwyzard** [comment]
@srimanob if I can make a suggestion: `--RequiresGPU 1` or `--RequiresGPU 2` seems very confusing... reading the command line I would guess it to mean "require 1 gpu" or "require 2 gpus".
Is there any chance to change it to something like `'none'`, `'optional'`, `'required'` ?

**Comment by amaltaro** [comment]
@srimanob  and @fwyzard just a note, if we decide that we should support only two cases: GPUs required, GPUs not required; I would then suggest to make `RequiresGPU` a boolean. This would be the cleanest setup IMO.

Anyhow, I guess this discussion is happening in the next week, then we can continue with implementation once all the requirements have been defined.

**Comment by amaltaro** [comment]
As an outcome of the GPU discussion we had today, I have just updated the initial description of this PR, where `RequiresGPU` is now going to be of a string type.

**Comment by srimanob** [comment]
PR for runTheMatrix is updated, here is how it looks like to step/task that runs GPU.

```
'Task3': {'AcquisitionEra': 'CMSSW_11_3_X_2021-04-26-2300',
           'ConfigCacheID': 1042,
           'EventStreams': 0,
           'GPUParams': {'CUDACapabilities': ['7.5'],
                         'CUDADriverVersion': '',
                         'CUDARuntime': '11.2',
                         'CUDARuntimeVersion': '',
                         'GPUMemory': '8000',
                         'GPUName': ''},
           'GlobalTag': u'113X_mcRun3_2021_realistic_v10',
           'InputFromOutputModule': u'FEVTDEBUGHLToutput',
           'InputTask': 'Digi_2021',
           'KeepOutput': True,
           'LumisPerJob': 10,
           'Memory': 3000,
           'Multicore': 1,
           'ProcessingString': u'113X_mcRun3_2021_realistic_v10',
           'RequiresGPU': 'required',
           'SplittingAlgo': 'LumiBased',
           'TaskName': 'Reco_Patatrack_PixelOnlyGPU_2021'},
```

**Comment by amaltaro** [comment]
Hi @srimanob , given that we are talking about Workflow level description, shall we move your comment and this discussion to https://github.com/dmwm/WMCore/issues/10388? I have the impression your `GPUParams` isn't properly constructed as specified in the issue above.

**Comment by srimanob** [comment]
> Hi @srimanob , given that we are talking about Workflow level description, shall we move your comment and this discussion to #10388? I have the impression your `GPUParams` isn't properly constructed as specified in the issue above.

Sure.
