### ISSUE TITLE
Build a minimal PyPI based Docker image for MSRuleCleaner

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10408]
**Impact of the new feature**
Overhaul the Dockerfile for reqmgr2ms, splitting out into separate containers for each microservice. Containers should be as small as possible. Container will use PyPI packages instead of the current RPM based deployment method.

**Is your feature request related to a problem? Please describe.**
reqmgr2ms container is currently very large and is used for multiple microservices, which is not ideal for k8s.

**Describe the solution you'd like**
Build a minimal Docker image using the MSRuleCleaner package from PyPI

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vkuznet** [comment]
I provided initial Dockerfile to build docker image and it was successfully build, see details in https://github.com/dmwm/WMCore/issues/11310.

**Comment by amaltaro** [comment]
Basic functionality of these PyPi-based services have been tested with docker image label: `2.1.6rc3`.
Workflows are getting their input rules evaluated and moving to `staged` status!

In addition to the changes already linked above, the following was required as well:
Mount rucio-secrets and rename the docker image name for microservices, global workqueue and t0_reqmon:
https://github.com/dmwm/CMSKubernetes/pull/1261
https://github.com/dmwm/CMSKubernetes/pull/1283
https://github.com/dmwm/CMSKubernetes/pull/1287

Fix to the run.sh script in the dmwm-base image:
https://github.com/dmwm/CMSKubernetes/pull/1288

A more in depth validation is still required and will be tracked through: https://github.com/dmwm/WMCore/issues/11354

Closing this one out.
