### ISSUE TITLE
Build a minimal PyPI based Docker image for MSMonitor

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10409]
**Impact of the new feature**
Overhaul the Dockerfile for reqmgr2ms, splitting out into separate containers for each microservice. Containers should be as small as possible. Container will use PyPI packages instead of the current RPM based deployment method.

**Is your feature request related to a problem? Please describe.**
reqmgr2ms container is currently very large and is used for multiple microservices, which is not ideal for k8s.

**Describe the solution you'd like**
Build a minimal Docker image using the MSMonitor package from PyPI

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vkuznet** [comment]
I provided initial Dockerfile to build docker image and it was successfully build, see details in https://github.com/dmwm/WMCore/issues/11310.

**Comment by vkuznet** [comment]
CMSKubernetes repo commits for WMCore Dockefiles:
- https://github.com/dmwm/CMSKubernetes/commit/fa223eea3bb05ef45b93499aa14f04630a60330a
- https://github.com/dmwm/CMSKubernetes/commit/942145b863dc62d5108525b7a223dd96b1073375
- https://github.com/dmwm/CMSKubernetes/commit/092523fc55fdc171558080ad6d99bea1487c8671
- https://github.com/dmwm/CMSKubernetes/commit/f67f20b2999a731bc742d861ce49ffce22bbd918
- https://github.com/dmwm/CMSKubernetes/commit/64bbe4eb9d24a879b32194d93594ae4b8de7e074
- https://github.com/dmwm/CMSKubernetes/commit/99d65ad733ea3adf970fc49602d8ba193e0047a5
- https://github.com/dmwm/CMSKubernetes/commit/6e025ba0f9641284f4a4d3e087264126c760c590

**Comment by vkuznet** [comment]
The new pypi based image is available:

- docker files: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi
- docker images: https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-output

@amaltaro , should we close the ticket?

**Comment by amaltaro** [comment]
Basic functionality of these PyPi-based services have been tested with docker image label: `2.1.6rc3`.
Workflows are getting their input rules evaluated and moving to `staged` status!

In addition to the changes already linked above, the following was required as well:
Mount rucio-secrets and rename the docker image name for microservices, global workqueue and t0_reqmon:
https://github.com/dmwm/CMSKubernetes/pull/1261
https://github.com/dmwm/CMSKubernetes/pull/1283
https://github.com/dmwm/CMSKubernetes/pull/1287

Fix to the run.sh script in the dmwm-base image:
https://github.com/dmwm/CMSKubernetes/pull/1288

I think we can close this ticket out and follow up with a more detailed validation in https://github.com/dmwm/WMCore/issues/11354.
