### ISSUE TITLE
Build a minimal PyPI based Docker image for workqueue

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10404]
**Impact of the new feature**
Overhaul the Dockerfile for Workqueue to be as small as possible. Container will use PyPI packages instead of the current RPM based deployment method.

**Is your feature request related to a problem? Please describe.**
Workqueue container is currently very large, which is not ideal for k8s.

**Describe the solution you'd like**
Build a minimal Docker image using Workqueue from PyPI

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vkuznet** [comment]
I provided initial Dockerfile to build docker image and it was successfully build, see details in https://github.com/dmwm/WMCore/issues/11310. The individual dockerfiles can be found over here https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi

The [workqueue](https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi/workqueue) Dockerfile and run.sh are avaiable.

**Comment by vkuznet** [comment]
The new pypi based image is available:

- docker files: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi
- docker images: https://registry.cern.ch/harbor/projects/1771/repositories/workqueue

@amaltaro , should we close the ticket?

**Comment by vkuznet** [comment]
yes, let's close this ticket.
