### ISSUE TITLE
Build and upload PyPI packages with each WMCore release

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10403]
**Impact of the new feature**
Associated with all packages built from WMCore. 
PyPI packaging is a manual process currently. This feature would automatically upload versions of WMCore packages (reqmgr2, workqueue, etc.) to PyPI when a new release/ is created. Will help us build containers without relying on CERN RPM repos.

**Is your feature request related to a problem? Please describe.**
RPM based deployment of python applications will/should go away in the future.

**Describe the solution you'd like**
When a new release is created, automatically upload new versions of packages to PyPI.

Maybe something like this:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by amaltaro** [comment]
@khurtado should we close it with the PR that you created: https://github.com/dmwm/WMCore/pull/11318
?

**Comment by khurtado** [comment]
@amaltaro Yes! Agree
