### ISSUE TITLE
Investigate possible incompatibilities between Oracle 11c and 19c

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10413]
**Impact of the new feature**
WMAgent (and T0)

**Is your feature request related to a problem? Please describe.**
Oracle 11c is no longer supported. Kate is coordinating/helping groups to migrate to the latest LTS Oracle version, 19c.

**Describe the solution you'd like**
This is just a high level issue to collect possible breaking changes between both oracle versions; list possible SQL syntax changes; and perhaps even list new features/functionalities that can boost the overall performance.

**Describe alternatives you've considered**
Not document anything, and blindly try the migration.

**Additional context**
Deadline for completing this migration is mid of June. So we should target beginning of June such that new agents can be deployed with new Oracle.
Further information in: https://indico.cern.ch/event/1002018/#7-additional-topics

**Comment by amaltaro** [comment]
From the unit tests outcome, provided in https://github.com/dmwm/WMCore/issues/10416, this issue can likely be closed. However, let me run some real quick tests with this new oracle version as well before we close it.

**Comment by amaltaro** [comment]
@goughes I executed many workflows with 1.5.4.pre2 (thus, oracle client 19) and couldn't spot any issues. Workflow completion is 100% and everything seems to be fully functional.
IMO, we can now consider this issue as done and it can be closed. Thanks

**Comment by goughes** [comment]
Great! Closing this out.
