### ISSUE TITLE
Setup Jenkins unit tests with Oracle backend

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10416]
**Impact of the new feature**
WMAgent / Jenkins unit tests

**Is your feature request related to a problem? Please describe.**
We already need to have this ability to run a complete set of unit tests against Oracle backend (instead of MariaDB), however, it will become even more important for the migration to Oracle 19c.

**Describe the solution you'd like**
Current jenkins unit tests are based on MariaDB backend, where each VM (slice) runs its own MariaDB backend in localhost (with a total of 11 slices).

We should implement a jenkins project to run all the WMCore unit tests against Oracle backend, even if that does not run against pull requests, but only twice a day on top of the baseline tag. It will likely have to be a single slice, because unit tests usually "destroy" the database between unit tests.

We already have a INT2R integration account allocated for this (well, we need to coordinate it with Dario :-D), so it's a matter of securely shipping the oracle credentials to our dmwm jenkins node(s). Shahzad is the expert to contact on this matter.

**Describe alternatives you've considered**
none, it really has to happen at some point.

**Additional context**
Better to be done before https://github.com/dmwm/WMCore/issues/10414

**Comment by amaltaro** [comment]
As discussed over slack, Erik will have a look at it and ping Kenyi/myself if help is needed. We will definitely need help from Shahzad for the secrets though.

**Comment by goughes** [comment]
Unit tests using an Oracle backend and python3 were configured and can be seen here: https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-TestOracle/

Tests that consistently fail with the Oracle backend:

```
WMComponent_t.ErrorHandler_t.ErrorHandler_t.ErrorHandlerTest.testA_Create
WMCore_t.JobStateMachine_t.ChangeState_t.TestChangeState.testIndexConflict
WMCore_t.ReqMgr_t.Service_t.ReqMgr_t.ReqMgrTest.testRequestSimpleCycle
WMCore_t.WMBS_t.Job_t.JobTest.testSaveTransaction
WMCore_t.WMBS_t.Workflow_t.WorkflowTest.testWorkflowInjectMarking
WMCore_t.WMBS_t.WorkUnit_t.WMBSWorkUnitTest.testCreateDeleteExists
WMCore_t.WMBS_t.WorkUnit_t.WMBSWorkUnitTest.testCreateTransaction
WMCore_t.WMBS_t.WorkUnit_t.WMBSWorkUnitTest.testDeleteTransaction
WMCore_t.WMBS_t.WorkUnit_t.WMBSWorkUnitTest.testGetInfo
WMCore_t.WMBS_t.WorkUnit_t.WMBSWorkUnitTest.testLoad
WMCore_t.WMInit_t.WMInit_t.testMySQLDatabase
WMCore_t.WMSpec_t.Steps_t.Executors_t.CMSSW_t.CMSSW_t.testB_ExecuteNonZeroExit
WMCore_t.WMSpec_t.Steps_t.Executors_t.CMSSW_t.CMSSW_t.testC_ExecuteSegfault
WMCore_t.WMSpec_t.Steps_t.Executors_t.CMSSW_t.CMSSW_t.testD_ExecuteNoOutput
WMQuality_t.Emulators_t.DBSClient_t.MockDbsApi_t.MockDbsApiTest.testDBSApiMembers
```

More info of which unit tests are failing with respect to the database backend can be found here: https://docs.google.com/spreadsheets/d/1D_VUgjooXFzn-bOWw_mB405jGT8sd2FTDYO017QB_xg/edit?usp=sharing

**Comment by goughes** [comment]
These tests are now running with 1.5.4.pre1, which includes the Oracle 19 client. The tests showed some new failures after the change, but all were related to 404 errors for missing phedex APIs. Similar phedex related errors were seen for the standard WMCore py3 unittests. I think we can say the new client did not have a negative impact the results of the Oracle tests.

**Comment by amaltaro** [comment]
@goughes Erik, could you please open a new GH issue providing the list of unit tests above, such that we can in the near future get those fixed (which is unrelated to the oracle upgrade, as mentioned above)?
In addition to that, if there is any other relevant information to be shared within this issue, could you please post it here?

Once this is done, I think we can close this issue. Thanks!

**Comment by goughes** [comment]
Final thoughts on this issue.

Jenkins+Oracle tests can be found here: https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-TestOracle/
Description of the tests is under `DMWM-WMCore-TestOracle` section of the Jenkins wiki: https://github.com/dmwm/WMCore/wiki/Understanding-Jenkins#headmaster-tasks

 Marking closed.

**Comment by amaltaro** [comment]
Thanks, Erik! We missed a GH issue to address the failing unit tests, but here we go: https://github.com/dmwm/WMCore/issues/10851
