### ISSUE TITLE
MSUnmerged: add job tracking and post job processing logic

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10412]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
It concerns a new microservice to carry out further cleanup of the sites' unmerged area (removal of files that are no longer needed/locked in the system).

**Describe the solution you'd like**
FIXME - UPDATE: this description still needs to be worked on and a few items clarified.

Once we have the ability to submit jobs remotely, we should try to track the outcome of such jobs. The basic functionalities that come to my mind are:
* every X minutes/hours, get a snapshot of the jobs in that schedd grouped by DESIRED_Sites (FIXME: not sure how to accomplish it)
* retrieve the job logs, parse it and find out whether the job succeeded or not; check how many files it managed to delete, or how many files it failed to delete.

**Describe alternatives you've considered**
Another alternative would be to embed a call from the job (in the worker node) back to the microservice, where the job summary would be provided. I dislike very much this option, but considering a very low weekly cleanup activity (< 10k jobs in total?), it looks safe enough.

Yet another alternative is to just assume that cleanup jobs are succeeding, and make sure that the number of unmerged files to be deleted are eventually decreasing (from one week to another).
 
**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10411

**Comment by amaltaro** [comment]
Setting it as medium priority and for Q2, but I somehow think this one could be pushed to Q3 if needed.

**Comment by todor-ivanov** [comment]
Closing this one too. We decided to go with the remote deletion method. It may be reopened if needed.
