### ISSUE TITLE
Update oracle-client spec file to 19c

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10414]
**Impact of the new feature**
Any DMWM service depending on the oracle.spec file

**Is your feature request related to a problem? Please describe.**
Oracle 11c is no longer supported. Kate is coordinating/helping groups to migrate to the latest LTS Oracle version, 19c.

**Describe the solution you'd like**
Oracle instant-client is one of the third-party dependencies that WMAgent (and T0 agent) has.
Communication between the client and server will be encrypted, and the current 11c client does not support it, thus we need to update this cmsdist spec:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/oracle.spec

to the latest production 19c client.

Further information has been provided by Kate on April 1st, see this link: https://cern.service-now.com/service-portal?sys_kb_id=d6b318f1dbcbe740a1cda4f84b961989&id=kb_article_view&sysparm_rank=1&sysparm_tsqueryId=55b8d4621bc6e8107a841f81bb4bcb50

NOTE that this activity needs to be properly communicated with all the other projects depending on the oracle.spec file, especially T0/DBS/CRAB.

**Describe alternatives you've considered**
Another alternative is to create a new spec file for the new oracle version (if we are still relying on RPMs...). This way we do not need to discuss those changes with any other DMWM groups.
 
**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10413

**Comment by amaltaro** [comment]
Update on this issue as well, after having the opportunity of talking to Kate today.
Our current cmsdist instant client 11.x version should still work with oracle 19 servers (besides a possible problem with old fashion passwds). The only problem will be once the data encryption is enabled on the server, which is not planned for June but more for September or so. Before that happens, we need to ensure our systems are using client 19.

@smuzaffar Shahzad, maybe we can join efforts here, in case you are planning to update the oracle client in CMSSW to version 19 in the coming weeks/months. The large different of gcc version might be a problem, but we could certainly based our work in something that has been built for CMSSW :-D

**Comment by smuzaffar** [comment]
@amaltaro , I am not planning to update oracle-client for CMSSW. We are already using `12.1.0.2.0` version which supports the new encryption. 
One reason to not to move to latest oracle-client is that they have not yet provided OCCI library build for C++ ABI C++11. This is a blocker for cmssw as we link to occi shared library. This might not be the issue for computing tools as I think you are not using  occi

**Comment by amaltaro** [comment]
Note to ourselves: https://github.com/cms-sw/cmsdist/pull/6958

**Comment by belforte** [comment]
cool. Looking forward to test this on int2r before they update cmsr to oracle19

**Comment by amaltaro** [comment]
Fixed by https://github.com/cms-sw/cmsdist/pull/7292
Thanks, Erik!
