### ISSUE TITLE
MSUnmerged: expose basic cleanup stats via REST API

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10417]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
It concerns a new microservice to carry out further cleanup of the sites' unmerged area (removal of files that are no longer needed/locked in the system).

**Describe the solution you'd like**
Since we are now having the remote deletions through `gfal` implemented,  we would like to have some statistics exposed per  RSE about the cleaning process. We are currently bound to the pooling cycle of the RucioConmon service, which is once per week, so the information and results of the consecutive reruns of our MSUnmerged service would be accumulated through out this period in the background database (MongoDB) and displayed  through appropriate REST APIs developed to the service. 

In order to retrieve data for a given RSE, we need to call the `info` REST API and provide the RSE name via `rse=RSE_name` query string. If `detail=true` is provided, then it also returns directory related information (what is protected, what is deleted, etc). Detailed information is disabled by default.

**Describe alternatives you've considered**
Create the desired Methods and APIs to translate the supported REST calls to the correct MongoDB queries and display the information through the `info` and `status` interfaces to the service. 

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10411

**Comment by todor-ivanov** [comment]
All of the above logic needs to be reevaluated now, and a new plan to be created. I will do it once I see the service deployed in prod for the first time.

**Comment by amaltaro** [comment]
Basic information is now available through the `status` and `info` REST APIs.

So, with this issue, we should now expose some RSE-based statistic numbers as well. In terms of REST endpoint, I would suggest to use the `info` API, and add support to a new query string named `rse_name`, which will have an RSE name as value. 

The expected behaviour is that the microservice would then fetch stats for that given RSE in its memory/state/database, and return it back to the user.

**Comment by todor-ivanov** [comment]
This issue should now better follow the resolution of this one: #10797. It would be much easier once we have the database and make the service 'memorize' the RSE state. The alternative to the database design would be to generate (on every poling cycle) a huge report instead of just collecting the counters (as it is right now), and then parse it on demand with a given RSE as key to the REST interface. That would take quite an effort to implement and the final result would be low performant and in my opinion clumsy.  
@amaltaro What do you think?
