### ISSUE TITLE
MSUnmerged: implement job creation and submission logic

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10411]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
It concerns a new microservice to carry out further cleanup of the sites' unmerged area (removal of files that are no longer needed/locked in the system).

**Describe the solution you'd like**
Considering that the service already has the list of protected LFNs and the list of unmerged files in a given RSE, we need to:
* implement the logic to find the final list of unmerged files to be deleted
* distribute those unmerged files in batches of 1000 (or whatever is more sound), and assign each batch to a new cleanup job;
* create a standard central production job JDL and make a remote condor submission (we will have to allocate one specific schedd for this activity); bulk condor submission is preferred, of course.
* deal with condor submission failures (perhaps retry a couple of times after waiting for 10 and 30 seconds?); or something like that..
* persist a JSON file in the `state` area that X jobs were created for RSE name XXX at the timestamp YYY, for a total number of files ZZZ; I don't see a need for adding a database technology dependency here.

For the moment, it does not matter if the jobs will succeed or not. Job tracking and post processing will be done in a different GH issue.

**Describe alternatives you've considered**
none

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10410

**Comment by amaltaro** [comment]
I've been provided with the following link, with regards to how unmerged cleanup is currently performed by Dynamo:
http://t3serv001.mit.edu/~bmaier/ddm/consistency_config.json

especial attention to: `IgnoreDirectories` and `ListDeletable, expanding here just in case that link goes away:
```
  "IgnoreDirectories": [
    "SAM",
    "HCTest",
    "HCtest",
    "GenericTTbar",
    "EWKWPlus2Jets_WToLNu_M-50_14TeV-madgraph-pythia8",
    "VBFToHHTo4B_SM_14TeV-madgraph-pythia8",
    "WToLNu_1J_14TeV-madgraphMLM-pythia8",
    "WZTo3LNu_1Jets_14TeV-madgraphMLM-pythia8",
    "TTGamma_SingleLeptFromTbar_TuneCUETP8M1_14TeV-madgraph-pythia8",
    "WGToLNuG_PtG-40_TuneCUETP8M1_14TeV-madgraphMLM-pythia8",
    "TA_Tleptonic_kappa_aut_LO_madspin-pythia8",
    "/RAW",
    "TOTEM",
    "Totem"
  ],
  "ListDeletable": {
    "LFN_TO_CLEAN": "/store/unmerged",
    "UNMERGED_DIR_LOCATION": "/store/unmerged",
    "WHICH_LIST": "files",
    "DELETION_FILE": "_unmerged.txt",
    "DIRS_TO_AVOID": ["logs", "tier0_harvest", "express", "data", "hidata"],
    "MIN_AGE": 2419200
  },
```

so, something that we must consider when creating the file selection algorithm.

**Comment by todor-ivanov** [comment]
We have decided to go with Remote deletions  so far. And this Issue is no longer need. I am closing it now. and in case we decide to come back to the this scenario we  may reopen it. I am going to copy the useful information from  Alann's @amaltaro comment above in the common issue.
