### ISSUE TITLE
MSUnmerged: create get methods for fetching unmerged files from the CC tool

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10410]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
It concerns a new microservice to carry out further cleanup of the sites' unmerged area (removal of files that are no longer needed/locked in the system).

**Describe the solution you'd like**
The expected solution from this issue is to implement the MSUnmerged logic for:
* retrieving a summary for all RSEs from the Consistency Check tool. That summary contains the number of unmerged files, empty directories, and others. The URL to be used is: https://cmsweb.cern.ch/rucioconmon/WM/stats
* retrieve a gzip file with a list of all unmerged files in a given RSE. AFAIK it contains one LFN entry per line. The URL to be used is (replacing the RSE name accordingly): https://cmsweb.cern.ch/rucioconmon/WM/files?rse=T2_US_UCSD
* last but not least, also add the necessary functionality to retrieve a list of all active output LFNs from WMStats (note that it will include the merged and unmerged LFNs, so we should filter it out and keep only the relevant information in memory). Reference for this API can be found in: https://github.com/dmwm/WMCore/wiki/wmstatsserver-api#retrieving-a-list-of-protected-lfns

**Describe alternatives you've considered**
none

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10402

Some more info from an already closed issue that would be needed here:
https://github.com/dmwm/WMCore/issues/10411#issuecomment-845809843
 
I've been provided with the following link, with regards to how unmerged cleanup is currently performed by Dynamo:
http://t3serv001.mit.edu/~bmaier/ddm/consistency_config.json

especial attention to: IgnoreDirectories and `ListDeletable, expanding here just in case that link goes away:
```
  "IgnoreDirectories": [
    "SAM",
    "HCTest",
    "HCtest",
    "GenericTTbar",
    "EWKWPlus2Jets_WToLNu_M-50_14TeV-madgraph-pythia8",
    "VBFToHHTo4B_SM_14TeV-madgraph-pythia8",
    "WToLNu_1J_14TeV-madgraphMLM-pythia8",
    "WZTo3LNu_1Jets_14TeV-madgraphMLM-pythia8",
    "TTGamma_SingleLeptFromTbar_TuneCUETP8M1_14TeV-madgraph-pythia8",
    "WGToLNuG_PtG-40_TuneCUETP8M1_14TeV-madgraphMLM-pythia8",
    "TA_Tleptonic_kappa_aut_LO_madspin-pythia8",
    "/RAW",
    "TOTEM",
    "Totem"
  ],
  "ListDeletable": {
    "LFN_TO_CLEAN": "/store/unmerged",
    "UNMERGED_DIR_LOCATION": "/store/unmerged",
    "WHICH_LIST": "files",
    "DELETION_FILE": "_unmerged.txt",
    "DIRS_TO_AVOID": ["logs", "tier0_harvest", "express", "data", "hidata"],
    "MIN_AGE": 2419200
  },
```
so, something that we must consider when creating the file selection algorithm.

**Comment by todor-ivanov** [comment]
Just a note, for an idea to be expanded on while working on this issue:
https://github.com/dmwm/WMCore/pull/10621#discussion_r658849987
