### ISSUE TITLE
 [py2py3] pre-production test of WMStats with the py3 environment #10423 

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10425]
**Impact of the new feature**

This should involve mainly WMStats and its dependencies.

**Is your feature request related to a problem? Please describe.**

After making sure that the whole WMCore passes unit tests in py3, we should run some pre-productions tests to check if WMStats is compatible with py3 in a production-like environment.

**Describe the solution you'd like**

We should deploy WMStats to testbed, run some workflows and see how it behaves. (please feel free to correct me or expand this section of the issue with more details!)

**Describe alternatives you've considered**
There is not much else that we can do. 

**Additional context**
I would tackle this after we have completed 
- [ ] #10422

**Comment by amaltaro** [comment]
Python3 WMStats seems to be fully functional starting with WMCore 1.5.0.pre6, which is currently available in cmsweb-testbed and will be deployed to production tomorrow.
Closing this ticket.
