### ISSUE TITLE
Migrate production VM couchapps to new deployment method

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10433]
**Impact of the new feature**
Production Couchdb VMs would no longer rely on couchapps code packaged in the reqmgr2, workqueue, reqmon, acdcserver RPMs. The couchapps would be provided via a new deployment method tracked in issue #10216 

**Is your feature request related to a problem? Please describe.**
Couchapp deployment is not fully functioning in k8s. For example, in the VM based deployment method, reqmgr2 and couchdb were installed on the same node and reqmgr2 couchapps could be pushed via localhost. This is not the case in k8s as reqmgr2 no longer resides on couchdb VMs. 

**Describe the solution you'd like**
Make required changes to couchdb deploy/manage scripts to pull couchapps code from WMCore and push the couchapps.

**Describe alternatives you've considered**
Some documented here: #10216 

**Additional context**
The Couchapp package, used to deploy couchapps does not support python3 #10303

**Comment by amaltaro** [comment]
Planned to be deployed in production tomorrow.

**Comment by amaltaro** [comment]
New couchapps deployment method has been deployed to the production system today and everything looks okay. Thanks for working on this, Erik. Closing this issue.
