### ISSUE TITLE
Setup a testbed WMAgent for PowerPC tests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10435]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Not a bug, but people are trying to start testing heterogeneous resources/architecture, and Daniele S. would like to have some production (test) workflows targeting those resources in Italy.

**Describe the solution you'd like**
Setup a testbed agent such as:
* connected to cmsweb-testbed services;
* team to be determined
* release needs to be the same as the latest production release
* in theory no further tweaks are needed.

And provide the right coordinates - and a MC from scratch spec template - to Daniele and others interested in testing PPC resources.

**Describe alternatives you've considered**
Any follow up work and possible bug fix need to be addressed (and properly prioritized) in different GH issues.

**Additional context**
See thread "Exchange about Capability to send RelVals to PPC Resources"

**Comment by spigad** [comment]
Hi 
 the plan is to use manual glidein launched at site. We'll keep using an already existing FrontEnd entry which is mapped to this site name "T3_IT_Opportunistic_dodas". This site doesn't exist in CRIC because we don't need/want glideinwms . 
 The storage we'll use is the storage of T1_IT_CNAF .  

Just to give you the full picture, a second step ( once/if things will work ) we will reproduce the setup we already did the past year with Marconi A2. At that point we will have a site extension of T1_IT_CNAF ( so we will target T1_IT_CNAF as a site ) 

cheers Daniele

**Comment by amaltaro** [comment]
Thanks for this information, @spigad .

We will add the following information to the local database (resource-control):
```
--site-name=T3_IT_Opportunistic_dodas --pnn=T1_IT_CNAF_Disk
```

such that the agent acquires work assigned to `T3_IT_Opportunistic_dodas` (so this is what your test workflows should target).  Given that it will be associated to the T1_IT_CNAF_Disk storage endpoint, further tasks of the workflow (including merge/logcollect/cleanup) will likely be submitted to condor with DESIRED_Sites="T1_IT_CNAF,T3_IT_Opportunistic_dodas".

A couple more questions. Can the schedd be connected to the ITB pool? Or you need it on the global pool?
Last but not least, will by any chance Federica F. help you with these tests? Just asking because she knows how to create and assign test workflows (and she has all the required permissions for that).
Thanks

**Comment by spigad** [comment]
Thanks Alan, 
  allright and thanks a lot. 
 
  We will go via ITB pool at the beginning and finally yes the Plan is that Federica will put some effort here as she already experienced as you said. However I think you should enable ( in terms of permissions ) both Tommaso Boccali and myself. 
THanks a lot! 

Danele

**Comment by tommasoboccali** [comment]
btw, the ITB + manual glideins has already worked for M100 in December, for CRAB jobs (you can see the report @ https://indico.cern.ch/event/994476/

So we do not really expect problems there ... I *think* my DN should already be enabled in the ITB since then, but my memory might fail me...


ciao ciao and thanks!

**Comment by spigad** [comment]
@tommasoboccali  I meant about permissions at agent level. Those matters and @amaltaro  should evaluate what must be done to grant us access and allow workflow injection - 
  
cheers Daniele

**Comment by amaltaro** [comment]
Okay, I have deployed an agent on vocms0263. Some important details are:
* team name: testbed-vocms0263
* connected to cmsweb-testbed services (and Rucio Int)
* connected to the ITB pool
* job retry set to 3
* resource control only with `T1_IT_CNAF` and `T3_IT_Opportunistic_dodas`. Furthe details in [1]

Regarding permissions, I have just added Daniele to the ReqMgr/DataManager CRIC group. Tom, I will send you a private email with a question regarding your account(s).

Daniele, let us (Todor/myself) know if you need any help and/or if anything gets broken with this agent. Better via mattermost DMWM channel.

[1]
```
$manage execute-agent wmagent-resource-control --plugin=SimpleCondorPlugin --pending-slots=200 --running-slots=200 --add-one-site T1_IT_CNAF
and
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --cms-name=T3_IT_Opportunistic_dodas --ce-name=T3_IT_Opportunistic_dodas --pnn=T1_IT_CNAF_Disk --plugin=SimpleCondorPlugin  --pending-slots=200 --running-slots=200
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Processing --pending-slots=2000 --running-slots=2000
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Production --pending-slots=2000 --running-slots=2000
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Merge --pending-slots=0 --running-slots=0
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=LogCollect --pending-slots=0 --running-slots=0
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Cleanup --pending-slots=0 --running-slots=0
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Skim --pending-slots=0 --running-slots=0
$manage execute-agent wmagent-resource-control --site-name=T3_IT_Opportunistic_dodas --task-type=Harvesting --pending-slots=0 --running-slots=0
```

**Comment by amaltaro** [comment]
@spigad Daniele, please let me know if any extra information is needed at this stage. Otherwise I would suggest to close this issue.

**Comment by spigad** [comment]
@amaltaro  first of all thanks a lot. 
 I think the ball is on our court at the moment and we'll have a checkpoint internally soon after the O&C week so that we  start to play with the system.  I'm sure we'll end-up with few questions but for the moment I think we can surely close the issue! We'll ask questions via Mattermost I guess
   Thanks again

**Comment by amaltaro** [comment]
Thanks Daniele! I'm closing this ticket then.
Don't hesitate to reach out to us via DMWM mattermost channel with any questions you might have.
