### ISSUE TITLE
Commission new CERN hardware allocated to WMAgent - stress test

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10436]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
We are trying to move to bigger and more powerful nodes at CERN, such that each agent can handle a larger number of running jobs (goal is to reach capabilities similar to the FNAL schedds)

**Describe the solution you'd like**
The VOC created vocms0243 (r2.3xlarge, 32VCPU/128GB, 750GB io2); the SI team have already connected it to the global/production pool. 
Once the node is fully operational, we should deploy the latest production WMAgent - connected  to the production central services - and run around 100k jobs in total  as we stress that node and see how far we can get (in terms of running jobs in Condor).

We should probably test how much it scales in steps of 5k, starting with (condor_schedd configuration):
* 25k running jobs
* then 30k running jobs
* last but not least, 35k jobs

Note: the VOC (Germano) is still sorting some final issues with that node.

**Describe alternatives you've considered**
We might as well synchronise these tests with the P&R team such that we can actually run some real work in the system (preferentially single core workflows).

**Additional context**
We can adapt this GH issue description as we give more thought to the final testing setup and metodology.

**Comment by amaltaro** [comment]
Even though it wasn't originally planned for Q3, I'm taking this issue now with the WMAgent upgrade campaign (to Py3 1.5.2).

**Comment by amaltaro** [comment]
Updating this ticket with some important information collected during the scale tests, which peaked around a week or two ago:
* Running jobs: peak at 48k jobs, more information in this snapshot: [schedd_running_jobs](https://monit-grafana.cern.ch/dashboard/snapshot/feOai06DeFDL4gjjzFu6unzVW2aoPU1o?orgId=11)
* CPU: was all the time below 25%
* Memory: peak at 73GB of memory use, more information in this snapshot: [host_memory](https://monit-grafana.cern.ch/dashboard/snapshot/N8ByjuSvrT7vKmdGJBqIG3A8BoxcCGrV?orgId=11)
* ramdisk (for the condor spool directory): below 70%, as can be seen in this snapshot: [host_disk](https://monit-grafana.cern.ch/dashboard/snapshot/0lGBwy2x1VTYO0usPrgK9UvxPlJUdO0y?orgId=11)
* Overall: services were running smoothly and no instabilities have been spotted.

Alan's conclusion: we should recycle all of our current WMAgent nodes and allocate new nodes that are worthy it a total of 200k jobs. Assuming each agent can scale up to 50k jobs, that means we need 4 new nodes (actually twice this number to properly deal with upgrade campaigns), plus one extra node as a contingency plan.
In addition to that, I would relax the specs and allocate something like 24/96GB, 750GB io2, instead of the current configuration of vocms0243, used for these tests.

Any comments are very welcomed.

**Comment by amaltaro** [comment]
Cross-reference: https://its.cern.ch/jira/browse/CMSVOC-288

**Comment by Germano0** [comment]
Hello, this is my Github account, in case you may want to tag me

**Comment by amaltaro** [comment]
The 3 remaining nodes - vocms0250, vocms0251 and vocms0280 - have just been requested to be deleted.
Oracle accounts from prod14 through prod22 have been deleted as well.

This task is now fully done. Closing this ticket.
