### ISSUE TITLE
 [py2py3] pre-production test of WMAgent with the py3 environment 

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10431]
**Impact of the new feature**

This should involve mainly WMAgent and its dependencies.

**Is your feature request related to a problem? Please describe.**

After making sure that the whole WMCore passes unit tests in py3, we should run some pre-productions tests to check if WMAgent is compatible with py3 in a production-like environment.

**Describe the solution you'd like**

We should deploy WMAgent to pre-production, run some workflows and see how it behaves. (please feel free to correct me or expand this section of the issue with more details!)

**Describe alternatives you've considered**
There is not much else that we can do. 

**Additional context**
I would tackle this after we have completed 
- [ ] #10422

**Comment by amaltaro** [comment]
I am starting this task with Py3 WMAgent `1.5.2.pre3`

**Comment by amaltaro** [comment]
Python3 WMAgent has been fully validated and we started deploying `1.5.2` release into production. Closing this issue.
