### ISSUE TITLE
[py2py3] Check that looping over dictionary is safe when in doubt

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10446]
**Impact of the bug**
WMCore in general, and perhaps other services depending on it.

**Describe the bug**

 We have not observed any bug at the moment, but this is likely to create some problems.

During the modernization of dmwm/WMCore we had to update how dictionaries are looped over. While this should be mostly safe, there are instances in which the dictionaries are changed during the loop, which can cause runtime errors if the iterator updates dynamically. We tried to be as cautious as possible, but we should manually check the following changes

- [ ] `/home/dario/docs/dmwm/github.com/WMCore/src/python/WMCore/JobStateMachine/SummaryDB.py` #10116 

**Expected behavior**
We should not experience runtime errors when using the aforementioned functions

**Comment by amaltaro** [comment]
Validation from Py3 WMAgent 1.5.2.pre3 is looking good.

We might want to check the outcome of a Py2 replay in the coming days.

**Comment by amaltaro** [comment]
The T0 team is migrating the T0 agent to python3, and since this has been fully validated in Python3, I'm closing this issue (we can always reopen it if a new issue is found in this module).
