### ISSUE TITLE
Validate PSet changes in python2 and python3 environment with different workflows

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10456]
**Impact of the new feature**
Re-Validate changes in PR #10179 with:
- Full battery of DMWM/Integration tests. DONE
- DQM, stepChain, taskChain workflows. DONE
- T0 Replays: In validation stage
- RelVal Tests with python3 environment. DONE

**Is your feature request related to a problem? Please describe.**
This is related to the decoupling of CMSSW and WMCore python versions 

**Describe the solution you'd like**
Solution is using the changes in PR #10179 

**Additional context**
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime

**Comment by khurtado** [comment]
Current status: PYTHONPATH environment fix introduced a bug in StepChain workflows. This has been fixed in the PR. There is a new error in one Taskchain workflow (PUMCRecyc) that I'm investigating, related to `--skip_pileup_events`

**Comment by khurtado** [comment]
@amaltaro Thanks! I updated the description to reflect the current status of these validations.

**Comment by amaltaro** [comment]
This issue is likely depending on this one to be sorted first: https://github.com/dmwm/WMCore/issues/10642

**Comment by amaltaro** [comment]
Jhonatan confirms things are working (even though a new issue might be created). Closing
