### ISSUE TITLE
Investigate and adapt CouchDB Prometheus alerts

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10450]
**Impact of the bug**
CouchDB

**Describe the bug**
For the last 4 or 5 days, I've been getting around 10 daily alerts:
```
 alertname = CouchDB service is down
```

for CouchDB in vocms0744. This instance contains the T0 databases, so the load should be pretty small these days.

I think the couchdb exporter is scraping data through the `_stats` API, in a frequency of every 30seconds.
 
**How to reproduce it**
none

**Expected behavior**
Investigate if CouchDB is really becoming unavailable, even for a short period of time (few seconds). This is the expression evaluated to trigger or not an alert (provided by Valentin back in March 18):
```
     expr: avg_over_time(couchdb_httpd_up[5m]) < .9
```

as I understand it, scenarios like:
* 2 queries failed out of 10
* 1 query failed out of 9, and the 10th query took too many seconds to be served, thus landing in a different 5m time range.
that would trigger it.

If those are transient, then we need to remake this expressions to stop creating false alarms.

**Additional context and error message**
none

**Comment by amaltaro** [comment]
Those alerts keep coming, around 10 or more every day... time to look into it.

**Comment by amaltaro** [comment]
Couchdb exporter logs were in a strange state in vocms0744. The couchdb_exporter log was dating back from yesterday, and there was no node_exporter logs at all.

I contacted Imran and he restarted `couchdb_exporter` on that node. Let's see if that was the actual problem.

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please remind me where we define the interval for scraping CouchDB stats? Is it using this global interval of 15 seconds
https://github.com/dmwm/CMSKubernetes/blob/4676d57e85b4f5a1945e75cd59d1a0ef7371ce04/kubernetes/cmsweb/monitoring/prometheus/services/prometheus.yaml#L2
?

I had a look at the couchdb log in vocms0744, but I fail to find any instabilities. I also had an attempt to make couchdb_exporter more verbose through either `-verbosity=2` or `-stderrthreshold=0`, but nothing changes in the exporter log and there is no useful information there. In short, I do not know if these prometheus monitoring calls are:
1) timing out
2) failing to be served (http code >= 400)
3) or if couchdb really says it's down
?

If you prefer not to share some of this data here, feel free to ping me on mattermost or via email please.

**Comment by amaltaro** [comment]
I guess I was looking at the wrong place... Is this the correct place with that configuration:
https://gitlab.cern.ch/cmsmonitoring/cmsmon-configs/-/blob/master/prometheus/prometheus.yaml#L167-172
?

And this is where the couchdb rules are defined (conditions to trigger alerts in AM):
https://gitlab.cern.ch/cmsmonitoring/cmsmon-configs/-/blob/master/prometheus/couchdb.rules

I still would like to look at the stats information pushed to AM, to verify which of the 3 conditions above we are hitting. Please provide further details on how to look at them.

**Comment by vkuznet** [comment]
@amaltaro , this is correct place. In gitlab we keep all configuration files. Each service have json file which contains targets (e.g. VMs:ports to scrape), the rules file which defines records and alert rules and test file which defines unit tests for all rules. You can inspect any rule and write associated unit test for it, e.g. for couchdb we have couchdb.rules and couchdb.test. I can test them as following:
```
# check rules
/cvmfs/cms.cern.ch/cmsmon/promtool check rules couchdb.rules

# run unit test
/cvmfs/cms.cern.ch/cmsmon/promtool test rules couchdb.test
```
Please note, that I found that on AFS promtool may fail at initialization step, therefore I usually use local file system for testing, e.g. /tmp area of the node. I suggest that you inspect test file and adjust it accordingly to initiate the failure. For instance, if you change anything labesl or annotations, e.g. change summary string of unit test then you can see how it fails.

I'm not sure what do you mean by looking stats information pushed to AM. It does not work this way. All info are in prometheus where you can see ANY metric, e.g. `couchdb_httpd_up`. The Prometheus itself takes the AM rules and check them against the metrics. So, if you need to see your metrics I suggest that you visit prometheus itself at
https://cms-monitoring.cern.ch/prometheus/graph
here you can type your metric (and it will help you with pop-ups to find it) and plot it. You can view it as table values or graph. Then you can visit alert section at
https://cms-monitoring.cern.ch/prometheus/alerts
and see all alerts definitions.

Bottom line, you should invest some of your time to learn new monitoring tools, they are very powerful and versatile. I doubt that there is anything wrong with rules syntax itself. What you need is to know your metric values and properly setup alerts. We monitor now hundreds of systems/services and if something will fail in prometheus we'll notice it in other places. I doubt there is anything specific about the couch. Said that ,I can look at exporter itself if you'll tell me the node and grant me access to it. Usually you can query exporter via simple HTTP call, e.g.
```
curl http://localhost:port/metrics
```
and see what it returns. The couchdb exporter uses port 15984, so go to your node and make a plain curl call to see what it returns. The metrics returned in plain ascii row format, e.g. HELP string followed by TYPE string followed by metrics value pair.

**Comment by amaltaro** [comment]
@vkuznet thanks for this information, Valentin.

Yes, I wanted to check the metrics in Prometheus, not in AM. Checking the `couchdb_httpd_up` metric, I see it's been always 1 here:
https://cms-monitoring.cern.ch/prometheus/graph?g0.expr=couchdb_httpd_up&g0.tab=0&g0.stacked=0&g0.range_input=15m&g0.end_input=2021-04-22%2012%3A26%3A04&g0.moment_input=2021-04-22%2012%3A26%3A04
and in the couchdb grafana dashboard:
https://monit-grafana.cern.ch/d/S8rTdLRZz/couchdb?from=1619092473985&orgId=11&refresh=1m&to=1619096073985&var-env=prod&var-node_name=master&var-method=All&var-db_name=All&var-instance=vocms0744:15984&var-hostname=All&var-view_name=All

even though we had an alert this afternoon at 2:26pm CERN time:
```
 action = Please check CouchDB service on vocms0744:XXXXX and restart if necessary
```

Perhaps it would be easier if we could chat over slack or mattermost; or even a zoom call such that I can share my screen and have a more productive and clear chat. Please let me know if you would be available for 5 or 10min this afternoon.

**Comment by vkuznet** [comment]
Alan,
how about 19:00 CERN time, before that I'm busy with other meetings/stuff.
Let's try zoom to share the screens.
V.

**Comment by amaltaro** [comment]
Perfect! See you in the usual WMCore zoom room.

**Comment by amaltaro** [comment]
This issue has been discussed with Valentin (thank you very much!) and it's also being tracked in a JIRA ticket: https://its.cern.ch/jira/browse/CMSMONIT-378

**Comment by vkuznet** [comment]
the issue is gone after restart of Prometheus.

**Comment by amaltaro** [comment]
Indeed, I haven't got any alerts since then. Thanks for fixing it, Valentin. 
I'm closing this ticket as there is nothing else to be done, neither a change to the alert expression.
