### ISSUE TITLE
Create a docker image based on wmagentpy3-dev RPM

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10487]
**Impact of the new feature**
We need a new docker image to run unit tests with our py3 environment

**Is your feature request related to a problem? Please describe.**

We should create a new image to run unit tests with the py3 environment. It should be based on [wmagentpy3-dev](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagentpy3-dev.spec) RPM.  

**Describe the solution you'd like**

We can emulate how we create the current `gitlab-registry.cern.ch/cmsdocks/dmwm:wmcore_tests` image to run unit tests with the py2 environment (see https://gitlab.cern.ch/CMSDOCKS/dmwm), based on [wmagent-dev](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagent-dev.spec) RPM.

**Comment by amaltaro** [comment]
I agree! Closing.
This has been fixed with (and a bunch of other fixes): https://github.com/dmwm/Docker/pull/126
