### ISSUE TITLE
WMCore/Credentials/Proxy is not py3 compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10483]
while trying to make CRABClient work with python3, I hit the following errors

- [ ] WMCore/Credentials/Proxy
- [ ] https://github.com/dmwm/WMCore/issues/10483#issuecomment-836336540

##### WMCore/Credentials/Proxy - details

https://github.com/dmwm/WMCore/blob/fcca972e2fab220d65235a65940fe7a9f00e5cfc/src/python/WMCore/Credential/Proxy.py#L764-L780

problem is that `execute_command` at line 23
https://github.com/dmwm/WMCore/blob/fcca972e2fab220d65235a65940fe7a9f00e5cfc/src/python/WMCore/Credential/Proxy.py#L23
relies on `subprocess` which returns a list of bytes, not
a string, so the code above (and very likely many other similar case) raises a
```
TypeError: a bytes-like object is required, not 'str'
```
when hitting e.g.
```
return attribute.split('\n')[0]
```
where we try to use  the string `'\n'` to split the byte sequence `attribute` 

I have several instances of this in CRAB code as well and am currently working around cases like `suprocess.check_output)` by wrapping the call `str(subprocess.....)`. But have not found a solution yet for `subprocess.popen`[*].  It you know the way, please share.

[*] making `execute_command` above return `str(stdout), str(stderr)` causes numerical values to be returned as e.g. `"b'669143\\n'"` which breaks lines which try to perform arithmetic.

Even if I am going to stop using WMCore in CRABClient, I will  need a way to call suprocess in a py2/3 compatible way (w/o importing future !) so any idea on how to deal with those numbers reported a list of bytes will be welcome. I guess I can cast subprocess outputs to `int` or `str` depending on which command I execute, but.. well.. surley stinks. And does not look "pythonic" at all.

(apologies for having written srong statements before, I edited the text after a couple more tests)

**Comment by belforte** [comment]
By the way, the same happens with  `pycurl` output in https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/pycurl_manager.py
```
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 282, in request
    header = self.parse_header(hbuf.getvalue())
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 270, in parse_header
    return ResponseHeader(header)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 70, in __init__
    self.parse(response)
  File "/afs/cern.ch/user/b/belforte/WORK/CRAB3/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 78, in parse
    for row in response.split('\r'):
TypeError: a bytes-like object is required, not 'str'
ERROR 2021-05-07 22:24:22.883 UTC: 	 ERROR: TypeError: a bytes-like object is required, not 'str'
```

**Comment by belforte** [comment]
@mapellidario I defer to you whether you want to have a separate issue for pycurl_manager, or change the subject or leave as is. Of course there could be other cases, simply Credentials/Proxy and pycurl_manger are the "immediate" dependencies for CRABClient, so I hit them very soon in testing.

**Comment by mapellidario** [comment]
As mentioned by @goughes at https://github.com/dmwm/WMCore/issues/10529#issuecomment-856773434, #10577 should fix this issue

**Comment by belforte** [comment]
thanks @mapellidario for keeping me in the loop.
Indeed I had just came to same solution (`decode(encoding='UTF-8')`) for CRABClient.
Beware the case where subprocess returns `None` for out or err, I was getting and error there and had to use. Maybe you are protected by `if isinstance(value, str)`
```
out, err = proc.communicate()
stdout = out.decode(encoding='UTF-8') if out else ''
stderr = err.decode(encoding='UTF-8') if err else ''
```
in my tests this works also in python2, no need for the `if Py3` switch.

**Comment by goughes** [comment]
Closed via https://github.com/dmwm/WMCore/pull/10577
