### ISSUE TITLE
[py2py3] test WMCore/Configuration after modernization

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10488]
**Impact of the bug**
`WMCore/Configuration.py` and all its dependencies

**Describe the bug**
We have not seen any bug at the moment, but `WMCore/Configuration.py` is such a base module that any problem in this module can have multiple side effects on dmwm/WMCore.

This is issue is the follow-up of #9974 

**Expected behavior**
We should make sure that this module has no bugs. 

Keep in mind that these bugs can be difficult to trace back to Configuration.py, such as #10381.

**Comment by amaltaro** [comment]
I'm going to test it this week with a Py3 WMAgent node.
Tier0 folks are testing it with Py2 1.5.1.pre6 T0 agent as well.

**Comment by amaltaro** [comment]
It's working fine for Py3 central services and Py3 WMAgent >= 1.5.2.pre3.

**Comment by amaltaro** [comment]
The T0 team is migrating the T0 agent to python3, and since this has been fully validated in Python3, I'm closing this issue (we can always reopen it if a new issue is found in this module).
