### ISSUE TITLE
Validate new couchapps deployment methods on py2 and py3

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10493]
**Impact of the new feature**
This validation would test the two recent changes to the couchapps deployment process.
1. Creation of a py3 compatible `couchapp`: https://github.com/dmwm/WMCore/issues/10303
2. Switching couchapp deployment to couchdb instead of WMCore services: https://github.com/dmwm/WMCore/issues/10216

**Is your feature request related to a problem? Please describe.**
Couchapp deployment was not working in k8s or in python3

**Describe the solution you'd like**
Test the following scenarios with the updated `couchapp` and couchdb manage script
1. py2 - Deploy all central services that use couchapps (reqmon/t0_reqmon/reqmgr2/acdcserver/workqueue) on dev VM 
2. py3 - same as 1
3. py2 - Deploy wmagent
4. py3 - Deploy wmagent

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by goughes** [comment]
From the numbered list above:

1. py2 central services on VM - Works fine
2. py3 central services on VM - Cannot test yet
3. py2 wmagent - Works fine
4. py3 wmagent - Works fine

**Comment by todor-ivanov** [comment]
Hi @goughes. The following remark is not a deal breaker for your tests, but I just found one package version conflict in requirements_py3.txt, while trying to install all the packages with pip [1].

[1]
```
(WMCore.venv3) :WMCore$ pip install -r requirements_py3.txt
...
ERROR: Cannot install -r requirements_py3.txt (line 15) and -r requirements_py3.txt (line 34) because these package versions have conflicting dependencies.

The conflict is caused by:
    cmscouchapp 1.3.2 depends on requests==2.25.1
    rucio-clients 1.25.5 depends on requests<=2.25.0 and >=2.20.0

```

**Comment by amaltaro** [comment]
Hi @todor-ivanov , I saw this warning yesterday as well. I guess I will have to release a new `cmscouchapp` with a more relaxed `requests` requirement. When I built it, I had requests 2.25.1, that's why I set that in the cmscouchapp requirements, but I'm pretty sure it can work with other versions as well.

**Comment by todor-ivanov** [comment]
thanks @amaltaro I just worked around it somehow - like force downgrading `requests`, then manually installing `rucio-client`.  And upon that installing `cmscouchapp`... but I agree not the best way :)

**Comment by amaltaro** [comment]
When I had to manually install it a couple of days ago, `pip` sorted everything automatically:
```
Installing collected packages: requests, setuptools, rucio-clients
  Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
  Found existing installation: rucio-clients 1.24.2.post1
    Uninstalling rucio-clients-1.24.2.post1:
      Successfully uninstalled rucio-clients-1.24.2.post1
  Running setup.py install for rucio-clients ... done
Successfully installed requests-2.25.0 rucio-clients-1.25.5 setuptools-50.3.2
WARNING: You are using pip version 19.2.3, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Let me get a new version with this change in though.

**Comment by amaltaro** [comment]
This PR should fix this conflict: https://github.com/cms-sw/cmsdist/pull/6984

Thanks for reporting it, Todor.

**Comment by amaltaro** [comment]
This issue actually depends on: https://github.com/dmwm/WMCore/issues/10655

**Comment by amaltaro** [comment]
Likely dependent on https://github.com/dmwm/WMCore/issues/10655

**Comment by amaltaro** [comment]
The last piece that was missing has been fixed with: https://github.com/dmwm/deployment/pull/1089

CMSWEB upgrade happened this morning, I double-checked the CouchDB backends and I see that they are now using `py3-cmscouchapp` library to deploy the WMCore couchapps (py2-cmscouchapp is actually no longer installed on those backends).

@goughes in case I missed any other dependency, please feel free to reopen this. Thanks!
