### ISSUE TITLE
Improve REST Validation error reporting

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10498]
**Impact of the new feature**
all systems which use WMCore/REST
Inform which systems would be affected by this new feature. WMAgent? ReqMgr2? WorkQueue? WMStats? MicroServices? etc

**Is your feature request related to a problem? Please describe.**
When a client makes  REST call with an invalid parameter, the server log onlys reports the param name, not the value. E.g.
```
[20/May/2021:17:59:25]    InvalidParameter: InvalidParameter 87e4709cea7386b2865e745b4355173a [HTTP 400, APP 302, MSG 'Invalid input parameter', INFO "Incorrect 'activity' parameter", ERR None]
[20/May/2021:17:59:25] crabserver-77df9f796d-cbbmk 137.138.120.6 "PUT /crabserver/prod/workflow HTTP/1.1" 400 Bad Request [data: 2228 in 733 out 4193 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba" "" ] [ref: "" "CRABClient/3.3.1705.patch4" ]
```

One has to correlate with client logs to know which exact call was made. With distributed clients like CRABClient (and also when debugging new code) this is quite annoying and lead to much wasted time.  Printing the refused value in server log
would make things much faster. Remember that server log only has the base url, not the  data part of the query.

**Describe the solution you'd like**
Code should be change in
https://github.com/dmwm/WMCore/blob/e62fe1b309d6ff3bf8e5a167838933fac7026f80/src/python/WMCore/REST/Validation.py#L31-L53
so that in line 42 the invalid value is also printed, not only the parameter name

Same for other basic checks, although I have never seen  a REST call failing validation other than on a (u)string check.

**Describe alternatives you've considered**
There is no practical way to capture current exception higher up in REST code and re-raise with additional info, code is like
https://github.com/dmwm/CRABServer/blob/cbd0a86868d76c9c58fc641a1a32ab59a24738db/src/python/CRABInterface/RESTUserWorkflow.py#L331-L346
etc.

**Additional context**
I can not imagine any reason not to do this. Lack of imagination ?
In theory this could impact tools which automatically parse REST logs, but I do not think we have any. Also those could be smart enough to survive adding things to the log. Existing text does not need to change.

Let me know if you'd like me to test this in CRAB and submit a tested PR, but I will not do if you do not like the idea or know of reasons not to do it.

**Comment by todor-ivanov** [comment]
Hi @belforte, 

I just checked, and I can see the current version of the code actually does return the value itdelf in combination with the value name and type: https://github.com/dmwm/WMCore/blob/2d3f8d89137ef89ec46441ce16e5dc48dcd2c7e3/src/python/WMCore/REST/Validation.py#L48  At least when it comes to string values (as I understand from the initial description). I hope I am not missing something here. Can you confirm this is still needed? 

FYI @amaltaro

**Comment by belforte** [comment]
WOW
yes, it is exactly what I was asking for, looks like @mapellidario found it useful too https://github.com/dmwm/WMCore/commit/02da765bcb96f81739cd8092b6d6c146f722a219#diff-4777b993af8a3d85e3b3ae9c0a1581455964bdadbaaff4aa17b0cc216211e410
Thanks Todor 
Thanks Dario
This can be closed as obsolete.

**Comment by todor-ivanov** [comment]
thanks @belforte
