### ISSUE TITLE
[py2py3] Add variable Utils.Utilities.PY3

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10509]
**Impact of the new feature**
WMCore

**Is your feature request related to a problem? Please describe.**
We should provide an easily accessible boolean variable to determine if the runtime is py2 or py3. 

**Describe the solution you'd like**
Instead of importing from WMCore/Configuration, we can add this variable to Utils/Utilities.py

**Describe alternatives you've considered**
We can always use `import sys: if sys.version_info[0] == 3:` in every module, instead of importing it from Utils.Utilities.

This is a valid option, but can get a bit verbose, such as in 

https://github.com/dmwm/WMCore/blob/1a9ec04202c3db836d5a2dd555e686e5845dc214/test/python/Utils_t/MemoryCache_t.py#L32-L44

**Comment by amaltaro** [comment]
@mapellidario Dario, in the dup issue that I just opened & closed: https://github.com/dmwm/WMCore/issues/10511, I suggested a different location to put it (and we can adapt it further, of course). If you agree that it makes more sense than the Utilities module, then please go for it. Thanks
