### ISSUE TITLE
[py2py3] assertItemsEqual is not supported in Python3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10514]
**Impact of the bug**
Probably unit tests only, but it could be masking other real problems

**Describe the bug**
I've seen a few python3 unit tests failing with this error:
```
AttributeError: 'MyTestCase' object has no attribute 'assertItemsEqual'
```

quick google suggests this attribute is no longer supported in python3 (or it might have been replaced by something else).
 
**How to reproduce it**
```
nosetests test/python/WMCore_t/Services_t/WMStats_t/DataStructs_t/RequestInfoCollection_t.py
```

**Expected behavior**
We should find a way to consistently validate the unit tests in both python2 and python3, so finding an equivalent replacement for `assertItemsEqual`. If we cannot use a single function/attribute common in both python versions, then we might have to find specific python solutions.

**Additional context and error message**
Full error log
```
======================================================================
ERROR: some very basic unit tests for the RequestInfo class
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Services_t/WMStats_t/DataStructs_t/RequestInfoCollection_t.py", line 151, in testRequestInfo
    self.assertItemsEqual(reqInfoObj.getTasks(), {})
AttributeError: 'MyTestCase' object has no attribute 'assertItemsEqual'
```

**Comment by mapellidario** [comment]
I encountered this problem, for example in #10500. If possible I would use `assertListEqual` that is py2 and py3 compatibile, otherwise we have to add a switch to select between `assertItemsEqual` and `assertCountEqual` based on the python runtime, such as in `Utils/Utilities.py`. 

I would tackle this only after closing #10509 (which goes on top of my TDL of tomorrow morning).

**Comment by amaltaro** [comment]
@mapellidario Dario, would you mind taking over this issue from Kenyi? He's working on a different project for the next few days. And this is failing many many unit tests, so the sooner it's sorted the better.

**Comment by mapellidario** [comment]
@amaltaro For me it's not a problem taking this over, I will put it on top of my to do list
