### ISSUE TITLE
[py2py3] CouchFileset converts file "lfn" to bytes in py3

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10521]
#### Impact of the bug
At least ACDC/CouchFileset

#### Describe the bug
Since #10508 we noticed that when we retrieve a `WMCore.DataStructs.File` from a CouchFileset, the "lfn" parameter is converted to a bytes string.

For example, if we create the file

```python
{'lfn': 'd698d5ca-dfe7-4c2f-88f5-57f936c34ee3', 'size': 2333, 'events': 2650, 'checksums': {}, 'runs': set(), 'merged': False, 'last_event': 0, 'first_event': 0, 'locations': set(), 'parents': set()}
```

when we retrieve it, it is

```python
{'last_event': 0, 'first_event': 0, 'lfn': b'd698d5ca-dfe7-4c2f-88f5-57f936c34ee3', 'locations': [], 'id': None, 'checksums': {}, 'events': 2650, 'merged': False, 'size': 2333, 'runs': [], 'parents': []}

```

[EDIT] This seems to be a problem with couchdb. If we have a python dictionary with only unocde string here 

https://github.com/dmwm/WMCore/blob/affd0253c98972da0010e31cf44844e5dcd23149/src/python/WMCore/ACDC/CouchFileset.py#L157

when we retrieve it here 

https://github.com/dmwm/WMCore/blob/affd0253c98972da0010e31cf44844e5dcd23149/src/python/WMCore/ACDC/CouchFileset.py#L184

all the strings are bytes strings

##### Proposal
- identify all the places where we retrieve data from couchdb, like https://github.com/dmwm/WMCore/blob/affd0253c98972da0010e31cf44844e5dcd23149/src/python/WMCore/ACDC/CouchFileset.py#L184
- check if we are ion py3 with `from Utils.PythonVersion import PY3; if PY3`, then loop over the dictionary and if we find some bytes string, we convert it to unicode with `Utils.Utilities.decodeBytesToUnicode`
- hope that we actually never need to save a bytes string to couchdb

We can have a better look at this issue when we get to #10537, since in that case we are sure that everything underneath works as expected

#### How to reproduce it

```bash
nosetests test/python/WMCore_t/ACDC_t/CouchFileset_t.py:CouchFileset_t.testListFiles
```

#### Expected behavior
The unittests should not fail

#### Additional context and error message

nosetests test/python/WMCore_t/ACDC_t/CouchFileset_t.py:CouchFileset_t.testListFiles

**Comment by amaltaro** [comment]
I went back in the history and managed to identify the following PR:
https://github.com/dmwm/WMCore/pull/10522
which got this issue fixed. That's why it no longer fails in master/HEAD.

@mapellidario if I missed anything, feel free to reopen it.
