### ISSUE TITLE
[py2py3] unittest in EventAwareLumiByWork_t fails in py3

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10520]
**Impact of the bug**
Not clear to me at the moment

**Describe the bug**
The unittest `WMCore_t.JobSplitting_t.EventAwareLumiByWork_t.EventAwareLumiByWorkTest:testNoFileSplitNoHardLimit` is failing in py3 since merging #10506 

On my docker py3 env it does not fail all the times. It works from time to time. In py2 it works all the times.

UPDATE: there are two more python3 unstable unit tests in this module, and this issue should address them as well:
```
WMCore_t.WMBS_t.JobSplitting_t.EventAwareLumiByWork_t.EventAwareLumiByWorkTest:testHardLimitSplitting changed from success to failure
WMCore_t.WMBS_t.JobSplitting_t.EventAwareLumiByWork_t.EventAwareLumiByWorkTest:testNoFileSplitNoHardLimit changed from success to failure
```

**How to reproduce it**
run

```bash
nosetests test/python/WMCore_t/JobSplitting_t/EventAwareLumiByWork_t.py:EventAwareLumiByWorkTest.testNoFileSplitNoHardLimit
```

**Expected behavior**
Should work all the times, like in py2

**Additional context and error message**
Discussed in https://github.com/dmwm/WMCore/pull/10506#pullrequestreview-670088394, starting with a comment by Alan.

A traceback is available at this hidden comment: https://github.com/dmwm/WMCore/pull/10506#issuecomment-849576678

**Comment by mapellidario** [comment]
These unittests are not failing since [june 10](https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCorePy3-UnitTests/32/#showFailuresLink) and are not in the unstable [unittest list](https://github.com/dmwm/WMCore/blob/74bd93ca5ebd50c7b84e72223074ef7945dfce21/test/etc/UnstableTests.txt).

@amaltaro, am I missing anything or can we really close this?

**Comment by amaltaro** [comment]
Thanks, Dario and Erik. I'm closing it then.
