### ISSUE TITLE
Validation - WMSpec/Steps/Executor.py.Executor.setCondorChirpAttrDelayed

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10523]
**Impact of the new feature**
WMSpec/Steps/Executor.py

**Is your feature request related to a problem? Please describe.**
In #10500 we forced `Utils.Utilities.zipEncodedStr` to return bytes in py3, too. This may cause problems if we always expect to pass unicode strings around in py3.

The only use of this function that I found is in `src/python/WMCore/WMSpec/Steps/Executor.py.Executor.setCondorChirpAttrDelayed`. 

We should make sure that returning bytes from `zipEncodedStr` into `setCondorChirpAttrDelayed` does not cause problems.

**Describe the solution you'd like**
A quick validation of the changes in #10500 is needed (or at least would help with my sleep)

**Describe alternatives you've considered**
We can just hope this is not a problem, but that would be not so wise

**Comment by amaltaro** [comment]
Validation from Py3 WMAgent 1.5.2.pre3 went well and I see StepChains providing key/values such as:
```
    "Chirp_WMCore_cmsRun1_ExitCode": 0,
    "Chirp_WMCore_cmsRun2_ExitCode": 0,
    "ChirpCMSSW_cmsRun2_WriteTimeMsecs": 2211,
    "ChirpCMSSW_cmsRun2_Elapsed": 1909,
...
```

checked on Kibana, e.g.: https://es-cms.cern.ch/kibana/goto/b59aba39632d3c4f01c8925721128427

**Comment by amaltaro** [comment]
The T0 team is migrating the T0 agent to python3, and since this has been fully validated in Python3, I'm closing this issue (we can always reopen it if a new issue is found in this module).
