### ISSUE TITLE
Ramp up Rucio Client in py3 requirements 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10566]
**Impact of the bug**
Not exactly a bug

**Describe the bug**
In order to satisfy this issue we had to update the Rucio Client version of the rpm we deploy in our py3 env. So we need to update that version in the py3 requirements file too  

**How to reproduce it**

**Expected behavior**

**Additional context and error message**
This one is related to: https://github.com/dmwm/WMCore/issues/10525#issuecomment-852965546

**Comment by amaltaro** [comment]
@todor-ivanov just an observation, I think we could have done that in the already opened issue: #10525, with no need to open this new one. It's not a big deal though.

What I wanted to say is, there is no hard requirement that we need 1 GH issue for 1 PR.
