### ISSUE TITLE
WorkQueue_t.py failing after fixing unittests in slice 8

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10586]
**Impact of the bug**
The following unittests are failing in py2

```plaintext
test/python/WMCore_t/WorkQueue_t/WorkQueue_t.py:WorkQueueTest.testGlobalDatasetSplitting
test/python/WMCore_t/WorkQueue_t/WorkQueue_t.py:WorkQueueTest.testParentProcessing
```

**Describe the bug**
We introduced two new unittest failures in py2 with #10580. The cause has been the need to update `test/data/Mock/DBSMockData.json`

**How to reproduce it**
run the unittests above in your py2 env

**Expected behavior**
no unittests should fail

**Additional context and error message**
have a look at the following comments
- https://github.com/dmwm/WMCore/pull/10580#issuecomment-858528103
- https://github.com/dmwm/WMCore/pull/10580#issuecomment-858557522

**Comment by amaltaro** [comment]
Thanks for creating this issue, Dario.
First test seems to be legit to me and it should indeed be updated.

Second test - testParentProcessing - indeed fails because it has a unicode in the dictionary key signature:
```
root: ERROR: testParentProcessing, [u'/Cosmics/ComissioningHI-PromptReco-v1/RECO#2587a5c4-0ca9-11e1-b764-003048caaace']: 
failed to retrieve data from DBS/PhEDEx in LQ: 
u"DBS mock API could not return data for method listFileArray, args=(), and kwargs={'logical_file_name': [u'/store/data/ComissioningHI/Cosmics/RAW/v1/000/181/171/3A382506-600B-E111-BB30-003048F11C58.root'], 'detail': True} (URL https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader) (Signature: listFileArray:[('detail', True), ('logical_file_name', [u'/store/data/ComissioningHI/Cosmics/RAW/v1/000/181/171/3A382506-600B-E111-BB30-003048F11C58.root'])])"
```
which fail when looking up that data in the DBS mock data.
