### ISSUE TITLE
MSUnmerged: Create scalable configuration K8 deployment 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10599]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
In the initial implementation we are going to create `MSUnmerged` service stateless - no background database, no bookkeeping ... etc. In order to be able to scale it as simple as possible e want to have a small function called "GranularityParser" (or similar) to run first in every pod, which should read per pod limits (amount of work to be done by a single pod) from a common MSUnmerged configuration file. This piece of code should decide on which subset of Tiers and Sites(RSEs) the current pod is about to run, without overlapping work with other pods [see the attached file].

There are two possible solutions:

a) Create some communication channel between the pods - either by a shared filesystem or a bookkeeping system with a background database.

b) In case we have a unique identifier per pod (which does not change upon restart) - we may put a hardwired configuration for all the pods directly into the config telling them - pod1 is going to work on T1s, pod2 on T2s(subset 1), pod3 on T2s(subset 2) etc. .. But for that we would need to have that  unique and non volatile identifier per pod in advance.

So our preference is to go with option b) for the time being.

**Describe the solution you'd like**

The method suggested by Valentin is to develop `MSUnmerged` in such a way that it would be able to start with the proper set of input parameters, e.g as `--tiers` && `--rseSubset`. And then we should create a dedicated `*.yaml` [1] file per every flavor (combination of `--tiers` && `--rseSubset`) of pods we want to have, so that we may run the full set of pods needed to serve the full list of RSEs we have in the system.
![WMCore_MSUnmerged](https://user-images.githubusercontent.com/8182807/122068594-35533e80-cdfd-11eb-998b-6260b8fa59ef.png)
 
[1]
https://github.com/dmwm/CMSKubernetes/blob/d4e4f2d2a5aada091ed7399a4ab1c0b277b7eab8/kubernetes/cmsweb/services/reqmgr2ms-unmerged.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by todor-ivanov** [comment]
Following our chat with @amaltaro earlier today, I need to make few notes here, so that we do not forget what decisions were taken.

The long story short: the way how we configure the distribution of the total amount of work should be expressed as a set of limits defined in the common MSConfig file, then every pod should identify itself based on the identifier/index given to it in the relevant `.yaml` file. From there on, the function in question, should be able to split the full set of RSEs obtained by CRIC, based on a splitting criteria provided also in the MSConfig, and determine on which subset the current pod would run. 

The set of splitting criteria are as follow:
 * By Country
 * By Tier
 
The set of limits to be defined are:
 * limit by number of RSEs per pod instance
 * limit to a given subset of Tiers per pod instance
 * limit by number of files to be deleted per pod instance in a polling cycle - would give a good estimation of the service running time but a little bit of non homogeneous load distribution - WE DECIDED TO GO THAT WAY for the time being 
 * limit by number of files to be deleted per RSE in a polling cycle - would give better load distribution, but poorly estimated service running time - WE DECIDED TO AVOID IT for the time being.   

We also decided that we should consider an RSE as an atomic unit for the polling cycle to iterate on, and as such we would never break/interrupt a run until we finish with the amount of work estimated to be done on a given RSE. Meaning that even if we need to spare a full polling cycle (or even several cycles in the case when the amount of files to be deleted on the current RSE exceeds the limit of files per cycle) just on a single big RSE, we would do so. Therefor in order to not getting the pod stuck on a single broken or heavily loaded RSE for countless of cycles, we need to randomize the finally estimated subset of RSEs at the beginning  of every polling cycle.

**Comment by amaltaro** [comment]
Thanks for persisting this information here, Todor.

I have a couple of comments to complement it.

> The set of splitting criteria are as follow:
> * By Country
> * By Tier

These could probably be either OR'ed or AND'ed. Whatever gives less immediate work and is robust enough.

> limit by number of RSEs per pod instance

This could be dangerous if our RSE slice turns to be bigger than this limit. So, I think I would simply drop this limit and rely on the RSE slicing to be done for every POD.

**Comment by todor-ivanov** [comment]
In the diagram above and in all the comments in the current issue we silently presumed that CRIC should be used as a source of the the initial RSE List. And the API we were foreseeing for the purpose was: [1]. The equivalent one is the standard and pretty easy to use call to `rucio.list_rses`. And in general the former API should not provide any superset of the later or vise versa. Instead they should be exactly equal. So, as we just shortly discussed with @amaltaro,  in order to minimize the dependencies on other clients, we will stick to the `Rucio` one for the time being. 

[1]
https://cms-cric.cern.ch/api/cms/site/query/list/?json&preset=data-processing
