### ISSUE TITLE
MSUnmerged: Deploy with GRID tools

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10613]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
We decided to clear all the unneeded files from the CMS unmerged namespace through remote deletions This means we will have to issue the deletion requests from the micro service itself, regardless if it would run on a VM or a K8 pod, and the later would most probably be the solution we are implementing right now. For that to happen wee will need to have the minimal set of GRID middleware software stack, mostly for authentication and deletion tools to be used once the proper deletion protocol for a given site have been established. The easiest way of having those is to have the `cvmfs` + `ceph volume` mounted on a K8 pod.   

**Describe the solution you'd like**
Having the ability to start k8 pods with `cvmfs` + `ceph volume` mounts.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by todor-ivanov** [comment]
During the rucio transition meeting yesterday we  mentioned there is an alternative to the external filesystem mount. There exists some  `gfal` bindings packages [1] both C and python which we may include directly into our micro services stack. 

[1]
https://gitlab.cern.ch/dmc/gfal2-bindings
https://github.com/cern-fts/gfal2-python
https://pypi.org/project/gfal2-python/

**Comment by todor-ivanov** [comment]
Here is the full list of direct dependencies of `gfal2-python3` :
```
yum install -y \
    gfal2-python3 \
    gfal2-plugin-file \
    gfal2-plugin-gridftp \
    gfal2-plugin-http \
    gfal2-plugin-srm \
    gfal2-plugin-xrootd \
    xrootd-client
```
Then it comes with few more ``` yum install cmake glib2 boost gcc-c++ ```, that are needed in order for it's shared library to be compiled (it is mandatory to be with the python version it is about to be used). But those they will be requested as dependencies of the above. 

And we will need this to be deployed in the docker container which will run the service. So I'd like to ask @vkuznet and @muhammadimranfarooqi how would be the best to proceed here. Should I continue relying on the old `rpm` based structure expressed in the cmsdit repository  - and in this case is it a must to create a separate `*.spec` file for every one of those depending packages. Or should we just do something similar to how @ericvaandering  builds the Rucio containers: 

https://github.com/rucio/containers/blob/aaae2516ac3d98c5fb4b22d16f71e9a4834092bf/daemons/Dockerfile#L39-L51

p.s. we'd like to follow the short(est)cut here :).

**Comment by vkuznet** [comment]
@todor-ivanov the best approach is to create a base image (or multiple base images) for your services which will encapsulate all your required dependencies. For instance, we have `cmsweb-base` image which is used to build cmsweb services. You may have `dmwm-base` image which will contain all dependencies dmwm services need. This approach has many advantages. For instance, today we use RPMs, tomorrow we may switch to another package management, e.g. install manually or through pypi or through anaconda. Think of your base image as your OS where you can run your service. Then you'll only need to adjust your base image to provide you full set of dependencies, while your service image will only contain your service codebase (WMCore). This approach allows to optimize base image, e.g. reduce its size, re-use it with other services, use different package management, etc.

**Comment by todor-ivanov** [comment]
Thanks @vkuznet  this is a great suggestion. And I agree. In this case though it is a little bit different. This dependency is introduced because of the need of `MSUnmerged` to interact with GRID services directly. And the package we are talking here about is not particularly well packaged in pip. This is something which we already realized while debugging its installation. It builds a shared library on the fly and exposes a python3 interface to the outer world etc. .... it did not break my expectations at all. So the bottom line is - I'd like to keep it as down the chain as possible close to the docker image of the service actually needs it. And that's  why I just created this commit [1], putting it as a dependency only for the `reqmgr2ms` container and avoid having it in a base image. And Thanks for the prompt reaction and the good advice again! 

[1]
https://github.com/dmwm/CMSKubernetes/pull/612/commits/764f09c51f79cde8350030bb0c66bb72f8a10a0e

**Comment by vkuznet** [comment]
@todor-ivanov once again, use layers, `dmwm-base -> dmwm-base-gfal -> reqmgr2ms-unmerged`. Doing this way you can again have separate images for individual parts, which can be reused.

**Comment by todor-ivanov** [comment]
And just for my personal log:

If one builds a virtual environment and the possibility of the command:`pip intall gfal2-pythono3` inside the virtual environment to fail is quite big. So the work around is to follow the regular deployment process from the OS packaging (being it `rpm`, `deb` etc.) and then the so installed shared library needs to be linked through the `$PYTHONPATH` variable for the virtual environment. 
Here is the dump of the information one needs to do the above:
```
[... WMCoreDev.d]$ rpm -ql gfal2-python3
/usr/lib64/python3.6/site-packages/gfal2.so

[... WMCoreDev.d]$ echo $PYTHONPATH
/usr/lib64/python3.6/site-packages/:/afs/cern.ch/work...
```  

And once the virtual environment is started the result should be:

```
(WMCore.venv3) [... WMCoreDev.d]$ ipython
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import gfal2
In [2]: 
```

**Comment by ericvaandering** [comment]
Definitely use layers. The one thing that I can see where there is room for improvement is this:

"Then it comes with few more yum install cmake glib2 boost gcc-c++, that are needed in order for it's shared library to be compiled (it is mandatory to be with the python version it is about to be used). But those they will be requested as dependencies of the above."

Those are temporary RPMs needed just to build something else and they are quite heavy. The most efficient way to handle this is, as Valentin would point out, to use a multi-source docker build so you build the libraries and bindings in one image and just copy them into the image you ultimately run. 

But a "poor mans" substitute could be to, in a single Dockerfile step run an install script which deletes these development RPMs at the end. That way your resulting image is smaller. You can see a simpler version of that here: 

https://github.com/dmwm/CMSKubernetes/blob/master/docker/rucio-server/install_mail_templates.sh

where I need to go through a whole bunch of hoops just to get access to a few small files.

**Comment by todor-ivanov** [comment]
Thanks @ericvaandering  @vkuznet  let me process this:
```
dmwm-base -> dmwm-base-gfal -> reqmgr2ms-unmerged
```
I was thinking that  what I am currently doing is kind of similar and looks something like this: 

```
dmwm-base -> reqmgr2ms + added dependency from gfal2
```

Which is almost the same only that this way `gfal` would be installed on every micro service not only `MSUnmerged`, but this was a side affect I convinced myself to live with, because of the lack of time to rebuild the whole construction of all the microservices image builds right now.

**Comment by ericvaandering** [comment]
I have not thought about it enough to know which order or layers you should have, just that in general, they are something you want.

**Comment by vkuznet** [comment]
@todor-ivanov , with my recent observation on a number of vulnerabilities which I posted in this ticket https://github.com/dmwm/WMCore/issues/10623 and to [hypernews](https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1788.html) I strongly advise that you evaluate a risk of having monolithic image which may contains lots of vulnerabilities from different dependency chains. Instead, making smaller and independent images ensures better security model.

Please also note, that `cmsweb` base image was our initial attempt to do the migration from VM based procedure to k8s one. But it is not the best approach! It contains our RPM based procedure which we used in VM which is not required in k8s. You may end-up with much smaller image if you **will not start** from cmsweb, but rather from small CC/Debian image and only build layers which you need to run your service. Of course `cmsweb` provides a way to build all cmsweb images but it has its downside, as I posted above we discovery plenty of vulnerabilties which comes from different software stack within an image and it will take us a while to fix them. This is why I strongly advice to start migrating to pypi based installation which you can control number of dependencies you put into image. At the end to run a dmwm python based app you **only** need python and few dependencies, but you **don't need per-se** RPMs. Of course, I understand that it may not be feasible right now to get away from RPM based procedure, but I want to make sure that you'll not freeze your mind that you'll always use it and will always depend on `cmsweb` image.

Said that, the better approach for you would be to start thinking about which layers you need. I think you have the following chain: `python -> dependencies -> dmwm/wmcore -> microservices -> additional dependencies -> specialized microservice(s)`. Therefore, the images you need would be `base image, e.g. CC/Debian`, `dmwm-deps`, `dmwm`, `microservice`, etc. Using layered approach you may build your dependencies as you like and then only copy necessary pieces to your final image. This will increase your image security, reduce its size, make layers independent and re-usable, etc.

Meanwhile, you need to evaluate what is in `cmsweb` image before you should use it. May be you only need `cmsweb-base` image to start with. Open up Dockerfile for each to see what they provide, and start from appropriate one. As I said you may first create your own `dmwm-base` image with only software you need and nothing else.

**Comment by todor-ivanov** [comment]
Hi @vkuznet  thanks!  this is all extremely helpful and a good suggestion. I am afraid I do not have the time to experiment  with anything beyond the already tested base image of `cmsweb` being it huge and `rpm` dependent. I doubt you may find anybody who would like to step away from `rpm`s more than I do. But unfortunately now is not the time. we have more urgent issues to face. So that's why I am about to give it a first try as @amaltaro  suggested to the Pr iteself:

`cmserb -> reqmgr2ms ->reqmgr2ms-unmerged + gfal2 dependencies from mainstream rpms (non cmsdist defined)`
I know this is not the best dependency sequence, this it the most I can afford experimenting with right now.

**Comment by klannon** [comment]
@vkuznet: It's urgent that *something* be deployed by next week.  Would a reasonable compromise be that we deploy what @todor-ivanov has, even though you have identified some flaws, and then we create one or more issues as needed that will be included in the Q3 to-do list, assigned to @todor-ivanov, to address those flaws?

**Comment by vkuznet** [comment]
@klannon , @todor-ivanov , I provided advice here based on best practices and experience we have now, but I'm not against what you suggested, and you can go ahead with proposed changes.

**Comment by klannon** [comment]
@vkuznet:  And I appreciate that advice.  @todor-ivanov: Please open one or more (as needed) issues to implement the advice from @vkuznet (and @ericvaandering) as an improvement on the initial version that we deploy next week.

**Comment by todor-ivanov** [comment]
Thanks @klannon I am creating the issues to track this activity on a later stage . @vkuznet  please  take a look at my try to implement the minimal effort image linking chain here [1] in case I totally messed up things - please let me know so that I revert this commit ad we go with the previous ASAP. Thanks you!

[1]
https://github.com/dmwm/CMSKubernetes/pull/615/commits/a1fecf4540234042296c798947a82a535b76e557

**Comment by todor-ivanov** [comment]
And just to keep track of it -  Here [1] is the newly created issue for the Docker images reorganization  based on a properly leayered system of image dependencies.

[1]
https://github.com/dmwm/WMCore/issues/10624
