### ISSUE TITLE
Provide some useful information from ReqMgr to Monit

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10618]
**Impact of the new feature**
Better monitoring

**Is your feature request related to a problem? Please describe.**
Recently, we wanted to get some plots about cpu efficiency to compare taskchain/stepchain requests as well as the classical mixing/premix requests. Although, this data is present in ReqMgr (or in databases that ReqMgr uses), it's not provided to monit, that's why we cannot get plots over kibana/grafana. The best that we could do was the following dashboard that Ceyhun and I generated with regex over request names which is a pretty dirty trick: https://monit-grafana.cern.ch/d/HbdOtARnk/user-hozturk-pnr-ops?orgId=11 

There is also the following issue related to this problem: https://github.com/dmwm/WMCore/issues/10604 

Apologies in advanced if I missed this information in monitoring. Both @todor-ivanov  and I checked this, but failed to find something useful.

**Describe the solution you'd like**
I think we should take this opportunity to identify all the useful information that we have in our databases and provide that information to monit. `RequestType`, `MCPileup` are the example fields that I have in my mind, but I think this can be extended.  

**Describe alternatives you've considered**
None

**Additional context**
@z4027163 @nsmith- FYI

**Comment by amaltaro** [comment]
@haozturk this looks like a reasonable request to me. The list of required pileups is already provided via `DESIRED_CMSPileups` job classad, which is supposed to be a comma separated string of pileup dataset names.

The `RequestType` is not yet available in the job classads, and we can look into providing it at job description level.

**Comment by haozturk** [comment]
Thanks a lot Alan. I managed to use `DESIRED_CMSPileups` for our monitoring: https://monit-grafana.cern.ch/d/HbdOtARnk/user-hozturk-pnr-ops?viewPanel=14&orgId=11&from=now-1y&to=now 

If this request is reasonable to you, I can check some other information which is missing in kibana and we can add them to our list as well. Will update the issue.

**Comment by amaltaro** [comment]
Priority updated according to Hasan's input on the Q3 planning (6/10)

**Comment by amaltaro** [comment]
@haozturk Hasan, as we quickly discussed during the WMCore chat today, I'm planning to make this GH specific to "providing the RequestType via job classads", I hope that's okay with you?

Then we have many other GH issues for providing further workflow/job information via job classads, such as:
https://github.com/dmwm/WMCore/issues/10604 (task name convention)
https://github.com/dmwm/WMCore/issues/9728 (link to the job log in CERN EOS)
https://github.com/dmwm/WMCore/issues/9487 (prep_id provided in the job classad)
https://github.com/dmwm/WMCore/issues/8958 (primary/secondary location)
https://github.com/dmwm/WMCore/issues/7413 (output datasets in the job classads)
https://github.com/dmwm/WMCore/issues/9455 (aggregation of all the interesting clasads, from the SI point of view)

If it's okay with you, I will then rename it.

**Comment by amaltaro** [comment]
@haozturk Hasan, if you can confirm my message above, then we should be able to cover it this quarter. Please let us know what your thoughts are.

**Comment by haozturk** [comment]
Hi Alan, I was also planning to ask to provide campaign information in task/step level. For instance, the following request is a stepchain and one of the steps runs w/ campaign `RunIISummer20UL16DIGIPremixAPV`, but it's not visible in monitoring [2] We only provide the campaign name of task/step 1. But, probably it's better to decouple such feature requests in different issues and implement one by one. Thus, I agree w/ your suggestion above. Perhaps, I can come up w/ PRs for my requests with the help of the PR that you'll create for this PR. How does that sound?

[1] https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210612_132502_1869 
[2] [Link to kibana](https://monit-kibana.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-12M,to:now))&_a=(columns:!(data.WMAgent_SubTaskName,data.ScheddName,data.WMAgent_JobID,data.CMS_JobType,data.CMS_CampaignType,data.Campaign),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b66f4510-cd98-11ea-9887-713cbbe6612f,key:data.WMAgent_RequestName,negate:!f,params:(query:haozturk_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210612_132502_1869),type:phrase,value:haozturk_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210612_132502_1869),query:(match:(data.WMAgent_RequestName:(query:haozturk_task_BPH-RunIISummer20UL16GENAPV-00054__v1_T_210612_132502_1869,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b66f4510-cd98-11ea-9887-713cbbe6612f,key:data.Campaign,negate:!f,params:(query:RunIISummer20UL16DIGIPremixAPV),type:phrase,value:RunIISummer20UL16DIGIPremixAPV),query:(match:(data.Campaign:(query:RunIISummer20UL16DIGIPremixAPV,type:phrase))))),index:b66f4510-cd98-11ea-9887-713cbbe6612f,interval:auto,query:(language:lucene,query:''),sort:!(metadata.timestamp,desc)))

**Comment by amaltaro** [comment]
@haozturk I need to check whether we have all the necessary information already available for filling up a campaign job classad. It might be a bit tricky for StepChains though - with multiple campaigns - and in that case we will likely have a comma separated string, e.g.: "Camp1,Camp2,Camp3"

Sure, I will tag you on my future PR providing this RequestType classad. Thanks
