### ISSUE TITLE
Broken unittests in WMCore_t/WMBS_t/JobSplitting_t/ in py3

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10627]
**Impact of the bug**
Some unittests in `WMCore_t/WMBS_t/JobSplitting_t` are failing in py3 and not in py2.

**Describe the bug**
The following unittests are failing in py3 only and this may mean a regression caused by our modernization

- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/EventBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/ParentlessMergeBySize_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/RunBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/SplitFileBased_t.py`
- [ ] `test/python/WMCore_t/WMBS_t/JobSplitting_t/WMBSMergeBySize_t.py`

**How to reproduce it**
run the unittests

**Expected behavior**
the unittests should pass

**Additional context and error message**

Check the failing unittests in py3 at [this webpage from jenkins](https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCorePy3-UnitTests/lastBuild/)

**Comment by amaltaro** [comment]
@goughes Erik, I do not know what the problem is here. But in case it's related to the order of items in a given python object, you might want to consider something similar to (if not too expensive):
https://github.com/dmwm/WMCore/pull/10583
