### ISSUE TITLE
MSUnmerged: Create unmerged files fitering logic

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10657]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
In the process of creating the MSUnmerged micro service, we figured out we cannot benefit from python set operations in the filtering out the protected LFNs (fetched from wmstats) fromf the list of unmerged LFNs fetched from the Rucio Consistency Monitor per RSE. The reason is the different depth in the LFN tree at which the two services keep information:

WMStats:
```
/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2
```

Rucio Consistency Monitor:
```
/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140000/388E3DEF-9F15-D04C-B582-7DD036D9DD33.root
```

 So we will have to iterate through the whole list item by item.

**Describe the solution you'd like**
A simple but fast enough method to search through those lists. In preference with the smallest memory footprint possible, because of the enormous amount of information we are about to manipulate. Just for reference: The records for the unmerged present only at one site -  T2_US_Wisconsin:
```
$ ll -h MSUnmerged.log.T2_US_Wisconsin
28M Jul  2 11:00 MSUnmerged.log.T2_US_Wisconsin
 
$ wc -l MSUnmerged.log.T2_US_Wisconsin
143283 MSUnmerged.log.T2_US_Wisconsin
```
`*` There is some minor % of these records coming from script debugging information but it is far less than 1% 

**Describe alternatives you've considered**

**Additional context**

**Comment by todor-ivanov** [comment]
While trying few stuff in this regard, I already reached the conclusion (and I already briefely discussed this with @amaltaro too) that the best way for us to proceed here is to try to delete recursively on a directory basis, starting from the deepest level where the protected list from `WMStats` tree reaches. Meaning in our case, for all files/paths of the kind:
```
/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140000/388E3DEF-9F15-D04C-B582-7DD036D9DD33.root
...
/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140001/BB2EA672-D1AA-C64B-A42B-B7FAF3D711E9.root
```

We will always search for a protected directory in WMStats which goes to the following level the deepest:
```
/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/
```

And in case we do not find it in the protected list the deletion command we are about to execute will be to purge recursively everything below it in one go, i.e:

```
$ gfal-rm -r gsiftp://cms-lvs-gridftp.hep.wisc.edu:2811/hdfs/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2
``` 

(Ignoring the file level granularity provided by Rucio Consistency Monitoring)

So I am already implementing the background machinery for having those lists filtered with the smallest possible memory footprint, but it would be great if we have the green light also from Data management and others who may have spot a drawback in this approach @nsmith-  @ericvaandering

**Comment by amaltaro** [comment]
Thanks for explaning this, Todor.

As we discussed yesterday, this will improve the overall unmerged deletion process (storage/network/microservice/time). 

Recursively deletions are extremely dangerous by nature, but you mention that there will be a safeguard to ensure that the path/directory to be deleted matches a regular expression like r'/store/unmerged/etcetc', so from my side, this plan is sound.

**Comment by nsmith-** [comment]
Have you confirmed that the `gfal-rm -r` command works at all sites? I would be suspicious of it because we do not use it anywhere else and it may not be well-tested. I also agree with Alan that recursive removal is very dangerous.. a leading space in the path for example could have dire consequences.

**Comment by todor-ivanov** [comment]
Hi @nsmith- Thanks for the feedback. I haven't tested the recursive command so far. I am surprised to hear there is any chance that it is not working, honestly I was not expecting it. So what would be the alternative you suggest. 

> a leading space in the path for example could have dire consequences

One of the reasons why whatever the final result after the path manipulation is it is always checked against the following regExp:
`^/store/unmerged/.*$"` before it enters the list for deletions. If it doesn't match this path is simply considered out of the service scope and is not touched at all.
