### ISSUE TITLE
Possible pickle incompatibility with SLC5 workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10652]
**Impact of the bug**
WMCore

**Describe the bug**
It hasn't been fully understood yet, but I wanted to file this ticket such that we can track it and eventually investigate to either fix or close it.

I have created a ReReco slc5 workflows, still with a Python2 ReqMgr2 service (1.4.9), then created an ACDC with Python3 ReqMgr2 service (1.5.0). I see that all the jobs have failed during runtime with error:
```
SCRAMScriptFailure (Exit Code: 50513)
```

and here is the traceback [1].

**How to reproduce it**
See above

**Expected behavior**
I believe we can still have SLC5 workflows in the system (even though there are none right now), so we should investigate this issue and fix whatever incompatibilities it has.

Before trying to fix anything though, we could:
* create an SLC5 workflow in Python3 ReqMgr2
* then make an ACDC for it (using the same ReqMgr2 version, of course)
* and see whether the jobs will succeed or not. Maybe having the workflow spec created with python3 and the ACDC with python3 as well, will work out of the box.

**Additional context and error message**
[1]
```
2021-06-30 20:20:43,243:INFO:SetupCMSSWPset:Executing SetupCMSSWPSet...
2021-06-30 20:21:03,967:INFO:WMTweak:Not resizing job
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun1
withe Script module: SetupCMSSWPset
'\x00'Details:
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 776, in __call__
    taskTweak = makeTaskTweak(self.step.data)
  File "/srv/job/PSetTweaks/WMTweak.py", line 392, in makeTaskTweak
    args = pickle.loads(stepSection.application.configuration.pickledarguments)
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/pickle.py", line 1374, in loads
    return Unpickler(file).load()
  File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/pickle.py", line 858, in load
    dispatch[key](self)
```

**Comment by khurtado** [comment]
As far as I remember, even without this bug, we don't have [cmssw-wmt-tools](https://github.com/cms-sw/cmssw-wm-tools/) available on scl5 scram architectures, so the SetupCMSSWPSet won't work.

**Comment by amaltaro** [comment]
@khurtado Kenyi, could you please try to confirm this with David/Shahzad? I do not know the CVMFS path, otherwise I could check it myself. If indeed it's not there, and there are no plans to have it, then I'd suggest to close this issue and we simply no longer support SLC5 workflows.

**Comment by khurtado** [comment]
@amaltaro
It is currently not present for slc5 (see below).

EL7 
```
$ echo $CMSSW_VERSION
CMSSW_11_3_0_pre2
[khurtado@earth ~/releases/el7/CMSSW_11_3_0_pre2]$ which edm_pset_tweak.py
/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py
```
EL5:
```
$ echo $SCRAM_ARCH
slc5_amd64_gcc462
$ echo $CMSSW_VERSION
CMSSW_5_3_0

$ which edm_pset_tweak.py
/usr/bin/which: no edm_pset_tweak.py in (/afs/crc.nd.edu/user/k/khurtado/releases/el5/CMSSW_5_3_0/bin/slc5_amd64_gcc462:/afs/crc.nd.edu/user/k/khurtado/releases/el5/CMSSW_5_3_0/external/slc5_amd64_gcc462/bin:/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_0/bin/slc5_amd64_gcc462:/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_0/external/slc5_amd64_gcc462/bin:/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/gcc/4.6.2/bin:/afs/crc.nd.edu/user/k/khurtado/.linuxbrew/bin:/afs/crc.nd.edu/group/ccl/software/x86_64/redhat6/cctools/lobster-167-0e914feb-cvmfs-70dfa0d6/bin:/afs/crc.nd.edu/x86_64_linux/Modules/4.5.0/bin:/opt/crc/usr/local/bin:/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.57/el7-x86_64/usr/bin:/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.57/el7-x86_64/usr/sbin:/cvmfs/cms.cern.ch/common:/opt/condor/RedHat7/sbin:/opt/condor/RedHat7/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin)
```

As far as central production workflows requiring slc5, answer was: there is no relevant/active production release cycle requiring slc5 since about 5 years. Mattermost link:

https://mattermost.web.cern.ch/cms-o-and-c/pl/4uncm9mdityk3yz61csu1gxkga

**Comment by amaltaro** [comment]
Haa, I would have never found it, thanks, Kenyi.
I see that Jordan said they have run a couple of slc5 MC workflows over the last 2 years, but then David replied saying those should be fully supported by slc6 releases.

I think it's safe to say: WMCore no longer supports SLC5 workflows and we close this issue with this in mind.
Thank you very much!
