### ISSUE TITLE
MSUnmerged: Imlplement the actual deletion logic for unmerged files

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10660]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
Once we have the proper set of unmerged files per RSE established - issue: #10657, we should implement the execution of the actual deletion command per RSE. 

**Describe the solution you'd like**
This deletion should be implemented in 3 steps:
 * Fetch the default deletion interface for the RSE from Rucio and fill it in the `MSUnmergedRSE['delInterface']` field
```
In [1]: from rucio.client import Client

In [2]: rcl = Client()

In [3]: rcl.lfns2pfns(rse='T2_US_Wisconsin',
   ...:               lfns=['cms://store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140000/388E3DEF-9F15-D04C-B582-7DD036D9DD33.root'],
   ...:               scheme='gsiftp',
   ...:               operation='delete')
Out[3]: {'cms://store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140000/388E3DEF-9F15-D04C-B582-7DD036D9DD33.root': 'gsiftp://cms-lvs-gridftp.hep.wisc.edu:2811/hdfs/store/unmerged/Run2016B/JetHT/MINIAOD/ver2_HIPM_UL2016_MiniAODv2-v2/140000/388E3DEF-9F15-D04C-B582-7DD036D9DD33.root'}

```
 * Try to aggregate as much as possible files in a single deletion execution 
 * Execute the deletions and collect counters      

**Describe alternatives you've considered**

**Additional context**

A really good example for parsing a pfn is given into the code of the Rucio client itself:
https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/rse/protocols/gfal.py#L66-L187

And also for proper working with `gfal` too:
https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/rse/protocols/gfal.py#L189-L205
https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/rse/protocols/gfal.py#L273-L293

Here is the gfal2-python documentation:
https://dmc-docs.web.cern.ch/dmc-docs/gfal2-python.html
https://dmc-docs.web.cern.ch/dmc-docs/versions/docs/gfal2-python-epel/html/

A repository with examples:
https://gitlab.cern.ch/dmc/gfal2-bindings/-/tree/develop/example/python

And the most solid one:
https://github.com/cern-fts/gfal2-util/blob/master/src/gfal2_util/rm.py

**Comment by todor-ivanov** [comment]
While working on the previous Issue #10657 #10666, I figured out a possibly risky situation regarding the information coming from Rucio Consistency Monitor about some sites in `error` state. I am putting the information here, so that I may follow in this issue and still merge the previous one.

I was trying to fetch list of unmerged files for `T2_DE_DESY` but the result was `0`. If checked at `https://cmsweb.cern.ch/rucioconmon/unmerged/stats`  the RSE is in error. There is already some protection in the code regarding RSE status [1], but currently it is relying on the RSEs `status` filed to be set explicitly to `error`, while in the case with T2_DE_DESY the RSE status is set to done:

```
In [24]: rseStats['T2_DE_DESY']
Out[24]: 
{'scanner': {'type': 'xrootd', 'version': '1.3'},
 'server_root': '/store/',
 'server': 't2-cms-xrootd01.desy.de:1094',
 'start_time': 1625134570.7156065,
 'end_time': 1625134571.356299,
 'status': 'done',
 'error': 'status: 54 [ERROR] Server responded with an error: [3011] Unable to locate /store/unmerged; no such file or directory',
 'root_failed': True,
 'failed_subdirectories': 0,
 'files': 0,
 'directories': 0,
 'empty_directories': 0}
```
So the logical question is: Which is the full set of markers/flags we need to check in the `unmerged/stats` interface, so that we may consider the information coming from `unmerged/files` interface as reliable?

[1]
https://github.com/dmwm/WMCore/blob/d66237302581b8d6b6a41295d82bb64c95a5296c/src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py#L229-L231

**Comment by klannon** [comment]
But is this really a concern?  If MSUmmerged receives an empty list from the consistency checking, it won't clean anything up, right?  That won't cause any issue in the short term. It's much better than cleaning up a file that's actively in use. I think we should rely on the consistency checking service and monitoring of that service to detect and correct it's own error condition. MSUnmerged can just focus on cleaning whatever files it gets sent. What do you think?

**Comment by todor-ivanov** [comment]
Hi  @klannon Thanks. 
Well, looking things that way, yes they do sound logical, but there are few more use cases I need to cover. 
 * First - the checks about data reliability I do in a very early step so I can avoid even proceeding such RSEs, because we want to save CPU cycles and redundant calls to external systems for sure, but also 
 * Second - because if we ignore the case of an RSE with 0 file counter and broken status and do not evacuate it from the functional pipeline early, then at the end of the line it's counter would be checked and this RSE would be considered clean. This is how it will enter the service counters in the report. And this is already a well hidden error, about which we will forget and in a month from now some of us will have to go answer the question "Why a broken RSE was not reported in the logs" and start counting RSE by RSE until we (eventually) find the problematic one.
