### ISSUE TITLE
MSUnmerged: Improve accounting of deletions

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10686]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
In the process of testing the service we've got to realize that we are accounting mostly for successful deletions and not logging the failed ones. We also may try to find  way to measure the volume to be released on every iteration, by an additional series of gfal calls to the RSE, once we have the lists for deletions built. 

**Describe the solution you'd like**
 * Account not only for successful, but also for failed deletions on a per directory basis
 * implement a series of `gfal-ls`-like calls to the RSE once the lists of files to be deleted are build or in the process of deletion  (but beware not to consume the file generators too early) so that we may have meaningful assessment of the volume released on the RSE

**Describe alternatives you've considered**
None

**Additional context**
Non

**Comment by todor-ivanov** [comment]
This one would benefit from #10797 too.

**Comment by amaltaro** [comment]
@todor-ivanov Todor, do you think this is trivial enough and we could get it done in this last 2021 quarter? If so, then we should add it to the Q4 project board.

**Comment by amaltaro** [comment]
Thanks, @todor-ivanov . Can you please make sure its status in the board is correct (ToDo? In Progress?)

**Comment by haozturk** [comment]
We need another kind of accounting to judge what kind of workflows are responsible for protecting unmerged directories and if these are really correct. I think the ideal case would be to know the list of workflows which protects the unmerged files in a given RSE and corresponding statistics such as:

RSE: T2_US_Florida
| Workflow  | Number of protected unmerged files  | Total size of the protected unmerged files (GB)  | List of protected LFNs  | List of protected unmerged files  |
|---|---|---|---|---|
| Workflow-1  | 16  | 43  | Link to the list of corresponding protected LFNs  | Link to the list of corresponding unmerged  files  |
| ...  | ...  | ...  | ...  | ...  |

This might be too good to be true, but I wanted to set this as the idea goal. It can be brake down into smaller issues and worked out, perhaps. Any comments?
@z4027163 @jenimal  FYI

**Comment by todor-ivanov** [comment]
Hi @haozturk  this is tricky to fetch all that information. One field I can say for sure is impossible to get as of now, this is the Total size. Unfortunately,  the way how the service is constructed right now, we see no volume information when it comes to any data present at the `/store/unmerged`  branch of the tree. The price for fetching that  info remotely would be thousands of calls to the RSE in order to calculate the size of each file. 

The rest is possibly achievable, but creating this would involve doing the reverse mapping of `lfn at /store/unmerged` -> `workflow Name`. This reverse mapping would involve calls to several other services like DBS and RequestManager. So again collecting this information for every workflow present at the site at any time, would also has its price. What I was thinking of, when we shortly discussed the issue, was something more like another REST API to the Unmerged service, which would do that reverse mapping on a per call basis. Something like: 

https://cmsweb-testbed.cern.ch/ms-unmerged/data/info?rse=T2_US_Florida&lfn=/store/unmerged/RunIISummer20UL16NanoAODv9/QCD_HT300to500_TuneCP5_PSWeights_13TeV-madgraphMLM-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1&detail=True

and the result should be a workflow name.

@amaltaro  please give your thoughts. I will create a new issue to follow there.

**Comment by amaltaro** [comment]
This is a very good discussion and definitely something that would be useful to many people. However, we need to make sure that we are not reimplementing work that others have already considered (for instance, unmerged volume is something that I thought it would be implemented in the Consistency Monitoring service).

I would suggest to create a new GH issue with these ideas, where we can keep discussing and defining what the final requirements and expected behavior is. However, I'd suggest not to spend too much investigating possibilities of what the system would support or not. I'd rather first make sure that an unmerged cleanup service is fully functional for all the production RSEs in the system. Then we start looking into enhancements and expanding on new features.
