### ISSUE TITLE
MSUnmerged: Implement data/status and data/info interfaces to the service

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10692]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
In the process of implementing the MSUnmeged service we did follow the old ways of creating reports as it was done in all other micro services. Meaning one single report per service. In this case, unfortunately, this approach is not going to work since we are having three different instances of the service but they all get their own names and deployment cycles. They share only a common MSConfig. So the links bellow simply won't work:

https://cmsweb.cern.ch/ms-unmerged/data/info 
https://cmsweb.cern.ch/ms-unmerged/data/status

And this was also the reason why we had to disable the `livenessprobe` check during the Kubernetes deployment in production - https://github.com/dmwm/WMCore/issues/10682#issuecomment-884897414 .

We need  to develop a proper way to expose those interfaces for the 3 different instances of the service with the proper counters and reports. The links to them should be:

https://cmsweb.cern.ch/ms-unmerged-t1/data/info 
https://cmsweb.cern.ch/ms-unmerged-t1/data/status

https://cmsweb.cern.ch/ms-unmerged-t2-t3/data/info 
https://cmsweb.cern.ch/ms-unmerged-t2-t3/data/status

https://cmsweb.cern.ch/ms-unmerged-t2-t3-us/data/info 
https://cmsweb.cern.ch/ms-unmerged-t2-t3-us/data/status

Or alternatively having one report f all three in a single page. Which in my opinion would be the best but since those are independent services that would be quite difficult to synchronize.

It would  be great if we can also report some counters on a per RSE base.

**Describe the solution you'd like**
Develop the proper interfaces to every instance of the service with the full set of reports.  And also reflect all of them in the full K8 setup of the service. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
Todor, let me update this thread from what we have been discussing today.

Endpoints are going to be the same between all those MSUnmerged instances, so:
https://cmsweb.cern.ch/ms-unmerged/data/info
https://cmsweb.cern.ch/ms-unmerged/data/status

is - if everything works as expected - the way to query this service.

In addition to that, we need to support a query string named `rses`, for the `info` API. Its expected values are meant to be:
1) `t2-t3-us`
2) `t2-t3`
3) `t1`
and these will decide which MSUnmerged replica is going to serve this REST request.

The `status` API is meant to support a `detail` query string, but I think that one is already implemented as part of the other microservices.

**Comment by amaltaro** [comment]
@todor-ivanov as discussed over slack, I'm taking this issue to myself and will provide some basic service stats through the `status` API. I suggest to make more specific requirements in a separate GH issue.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro
