### ISSUE TITLE
[py2py3] pickle load/dump should always read bytes

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10732]
**Impact of the bug**
WMCore in general

**Describe the bug**
`pickle.dump(object, file)` and `pickle.load(file)` require `file` to be  of type bytes and we do not enforce it everywhere in our code yet. The list of potential problematic usage of pickle is at [1]

**How to reproduce it**
We have not any specific bugs, i just looked for `pickle` in our code and tried to spot problematic uses.

**Expected behavior**
We should always pass bytes to pickle.

**Additional context and error message**

[1]

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/PSetTweaks/PSetTweak.py#L370-L371

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/PSetTweaks/PSetTweak.py#L399-L400

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/WMCore/BossAir/Plugins/MockPlugin.py#L40-L42

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/WMCore/BossAir/Plugins/MockPlugin.py#L167-L173

Here we should also fix how we interface with `base64`, since `base64.encodestring()` `base64.decodestring()` are not available in py3
https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/WMCore/ThreadPool/ThreadPool.py#L147-L149

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/src/python/WMCore/ThreadPool/ThreadSlave.py#L176

https://github.com/dmwm/WMCore/blob/2b41a0cc1fc635c71ce790b6d2433d3b31da7304/test/python/WMCore_t/BossAir_t/BossAir_t.py#L318-L319

https://github.com/dmwm/WMCore/blob/74bd93ca5ebd50c7b84e72223074ef7945dfce21/test/python/WMCore_t/Misc_t/WMAgent_t.py#L448-L450

**Comment by amaltaro** [comment]
This is a good issue, Dario.
What do you think about providing a pull request fixing those? Maybe it will even clear a few more failing unit tests.

Side note, whenever you find something like:
```
f = open(jobFile, 'r') 
 job = pickle.load(f) 
 f.close() 
```

please convert it to use a context manager, thus to something like:
```
with open(jobFile, 'r') as f:
    job = pickle.load(f) 
```
this ensures the file is closed, no matter what happens during its execution.
