### ISSUE TITLE
beware non-ASCII characters in FrameworkJobReport.xml

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10782]
**Impact of the bug**
code which relies on CMSSW FJR

**Describe the bug**
if there's a non-ASCII char in the report, parser throws an exception.
See: https://github.com/dmwm/CRABServer/issues/6640#issuecomment-909362639

**How to reproduce it**
run cmsRun indicating a non existing file as input

A crude solution is e.g.
https://github.com/dmwm/CRABServer/blob/f3eea115e849872ba6d4abd11d94d7c92a2e39b9/scripts/CMSRunAnalysis.py#L850-L854
but it shuld be possible and better to handle this cleanly in WMCore/Algorithms/ParseXML.py

**Comment by amaltaro** [comment]
@belforte Stefano, if you have such bad FJR, could you please share it in this issue?

**Comment by belforte** [comment]
here it is in zip format (Github will not let me attach it in xml)
[BadFjr.zip](https://github.com/dmwm/WMCore/files/7091699/BadFjr.zip)
the way to reproduce the problem is at the bottom of https://github.com/dmwm/CRABServer/issues/6640#issuecomment-909362639
(different filename, sorry)

**Comment by belforte** [comment]
@amaltaro what puzzles me is that you seems not to have this this so far. I presume WMA is running with CMSSW_12_x, is it ? In my tests every time file open fails (which always happen every now and then) the non-ascii `^@` is inserted

**Comment by amaltaro** [comment]
>@amaltaro what puzzles me is that you seems not to have this this so far. I presume WMA is running with CMSSW_12_x, is it ?

@belforte Sorry Stefano, I couldn't follow this up yet. But yes, we do have a few test templates using 12_0_0_pre6, but I believe we have only tested those in a python3 WMAgent (even though I believe the python version wouldn't mind...).

**Comment by belforte** [comment]
the original problem came from XROOT and xroot developers have now fixed it so that they do not send this stupid non-ascii character any more.

**Comment by amaltaro** [comment]
Thank you for following this up, Stefano.
