### ISSUE TITLE
MSUnmerged: MongoDB structure

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10798]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
As suggested in #10797, we need to define the structure of the MongoDB database.

**Describe the solution you'd like**
It seems to me the best approach to this would be to upload the RSE object we create at the beginning of the main loop of the service as it is. More precisely:

```
           {"name": rseName,
            "pfnPrefix": None,
            "isClean": False,
            "counters": {"totalNumFiles": 0,
                         "dirsToDeleteAll": 0,
                         "dirsToDelete": 0,
                         "filesToDelete": 0,
                         "deletedSuccess": 0,
                         "deletedFail": 0},
            "files": {"allUnmerged": [],
                      "toDelete": {},
                      "protected": {},
                      "deletedSuccess": [],
                      "deletedFail": []},
            "dirs": {"allUnmerged": set(),
                     "toDelete": set(),
                     "protected": set(),
                     "empty": []}}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by todor-ivanov** [comment]
FYI @amaltaro

**Comment by amaltaro** [comment]
Thank you, Todor. Can you please edit the initial description and elaborate on the definition and data type allowed for each of those key names (including possible default values, if meaningful)? @todor-ivanov

**Comment by amaltaro** [comment]
Todor, given that we delete everything under a candidate directory, maybe we could store only a list of directories that are eligible for deletion. In short, I'm not sure whether we should store everything on our side. It's not clear to me how useful and important that information is, and in the long run it might become quite a lot of data as well.

Without thinking too hard, I'd be inclined to say that this would be the important information to store:
```
           {"name": rseName,
            "pfnPrefix": None,
            "isClean": False,
            "counters": {"totalUnmergedFiles": 0,
                         "totalDirsToDelete": 0,
                         "totalFilesToDelete": 0,
                         "totalFilesDeleted": 0,
                         "totalFilesFailDeletion": 0},
            "dirs": {"toDelete": set(),
                      "deletedSuccess": [],
                      "deletedFail": []},
```

**Comment by todor-ivanov** [comment]
Hi @amaltaro, 

That is indeed the right approach. This  way we would leave behind all the fine grained information about files to be deleted and the generators with that. This would achieve two things:
 * Reducing the size of the documents preserved in the database and 
 * Avoiding the need to store any non-JSON objects (like the file filter generators themselves). We still need to generate those on every poling cycle and lose some memory and CPU tough, but that's unavoidable, anyway. 
 
 The only thing I am trying to add to this construction is a way to apply the already preserved counters from previous runs, so that we try to delete only files/directories that are leftovers from previous runs. This way we would also gradually accumulate those counters run by run until we reach a sufficient percentage of "deleted success" and announce a clean state for an RSE. This ( the RSE clean status) currently is hard to estimate, because of the many retries to delete already missing files, which  prevents an RSE to ever reach a fully cleaned state, unless it have not been reached on a single push during the first polling cycle of MSUnmerged.

**Comment by todor-ivanov** [comment]
Just for logging purposes: what I am fighting here is yet another `pythonic` object which does not fit into the MongoDB data model:

```
InvalidDocument: cannot encode object: set(), of type: <class 'set'>
``

**Comment by vkuznet** [comment]
@todor-ivanov , it is yet another example that you should always use proper data-format when you yield and consume data in application. JSON is fine for that, while python objects are not. With communication to Mongo please always serialize data via `json.dump(s)` which will always provide proper JSON data-format.

**Comment by todor-ivanov** [comment]
Hi @vkuznet I agree with you. And the problem is not that we cannot serialize the object. we definitely can. and we can also try to benefit from some of the MongoDB indexing capabilities to speedup some stuff... plenty of things can be done, I agree. The current problem I have is, because the already constructed code relies on some set operations like: [1], which are crucial for the service. So I cannot avoid them. Now the fight I am talking about is to minimize the CPU cycles needed in order to get the data format prepared for inbound and outbound comincation with MongoDB. Ye... at the end it might turn out we should go for the most straightforward and less optimal solution to convert those sets both ways up and down the database stream.   

[1]
https://github.com/dmwm/WMCore/blob/67dfd645e31988de44846817d9d28d1ca0ac3b89/src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py#L491-L492

**Comment by vkuznet** [comment]
@todor-ivanov , why not to do `list(set())` in your data? This will keep your optimal data sets but will provide standard JSON object (list).

**Comment by todor-ivanov** [comment]
Hi @vkuznet , Yes,agreed. This is exactly what I am about to do. But the sets are nested one level bellow the top level MongoDB projection I am configuring. But I think it is still doable though.
