### ISSUE TITLE
Tier0 is not able to find physics_skims using the agent 1.5.2

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/WMCore#10806]
**Impact of the bug**
Tier0 agent. Tier0Feeder is down due that is not able to find physics_skims for prompt-reco. Not able to lunch promt-reco and replay fails.

**Describe the bug**
With the T0 agent based on WMCore 1.5.2, the Tier0Feeder component is not able to find physics skims for promt-reco. If the dataset doesn't have physics_skims in the configuration as follows:
```
DATASETS = ["Cosmics"]
 
for dataset in DATASETS:
    addDataset(tier0Config, dataset,
               do_reco=True,
               write_reco=False,
               write_aod=True,
               write_miniaod=False,
               write_dqm=True,
               alca_producers=["SiStripCalCosmics","SiPixelCalCosmics","TkAlCosmics0T","MuAlGlobalCosmics"],
               #physics_skims=["CosmicSP", "CosmicTP", "LogError", "LogErrorMonitor"],
               timePerEvent=0.5,
               sizePerEvent=155,
               scenario=cosmicsScenario)
```
Tier0 is able to run prompt-reco but if physics_skims appear in the configuration the T0 agent is down and none of the promtreco workflows will run
**How to reproduce it**
Deploy T0 agent (3.0.0) based on WMCore 1.5.2

**Expected behavior**
Promptreco workflows should be able to run including the physics_skims parameter

**Additional context and error message**
Error message from the Componentlog is as follows:
`ERROR:StdBase:About to raise exception Can't find physics skim LogError in CMSSW_12_0_0`

**Comment by amaltaro** [comment]
@jhonatanamado Jhonatan, thanks fort creating this issue. Do you need our help to work on this issue? Or do you already have some work in progress and we should get this issue actually assigned to you?
