### ISSUE TITLE
Adapt WMCore/Jenkins code to setup/create/drop MariaDB databases for the latest version 10.6.x

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10836]
**Impact of the new feature**
WMAgent and Jenkins

**Is your feature request related to a problem? Please describe.**
Sub-task of https://github.com/dmwm/WMCore/issues/9241

During the Summer project, we found breaking changes on how the database/users are set up, and possibly how databases are created and dropped from within the Jenkins tests.

**Describe the solution you'd like**
We should adapt:
* the WMCore code to make sure that initial MariaDB setup works and that components can properly access and use it
* the Jenkins code, when we deploy WMCore+WMAgent to run the unittests
* possibly the dmwm/Docker scripts as well, used for creating the WMAgent Docker images

The goal is that a `$manage start-services` would set everything up and the relational database would be accessible and functional for the components.

**Describe alternatives you've considered**
Initial changes are here: https://github.com/dmwm/deployment/pull/1088
but it's quite possible that we will need more changes and/or some of those configuration files might not even be needed.

**Additional context**
Sub-task of https://github.com/dmwm/WMCore/issues/9241

**Comment by goughes** [comment]
Jenkins tests are configured here: https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMAgentMariaDB10.6.5-TestAll/

These tests use my private `sw.egough` rpm repo and deployment GH repo.

I did find a consistent failure today that is not present in the unittests that use mariadb 10.1.2:
https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMAgentMariaDB10.6.5-TestAll/SLICE=7,label=cms-dmwm-cc7/7/testReport/junit/WMComponent_t.JobSubmitter_t.JobSubmitter_t/JobSubmitterTest/testB_thresholdTest/

I verified that this test always succeeds on 10.1.2 and always fails on 10.6.5 on my test VM.

**Comment by amaltaro** [comment]
Last python3 build (412) worked just fine, without any changes: https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCorePy3-UnitTests/lastBuild/

the same for our python2 master/head tests, there are no required changes to get it working.

@goughes shall we close it?

**Comment by goughes** [comment]
Sounds good. Closing this one.
