### ISSUE TITLE
Update current CouchDB databases to the new schema supported in v.2.3.x

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10831]
**Impact of the new feature**
WMCore in general (including cmsweb databases)

**Is your feature request related to a problem? Please describe.**
This is a sub-task of https://github.com/dmwm/WMCore/issues/8853
Yes, we cannot upgrade CouchDB to version 3.1.1 and keep the same database schema/files in the CMSWEB backends. The current schema is not compatible with CouchDB 3.1.1

**Describe the solution you'd like**
Before we can upgrade CouchDB to version 3.1.1, we must upgrade the database schema in CMSWEB. This will likely require an outage of the CouchDB instances.
Max - the summer student who worked on this - came up with a docker-based procedure to update our databases/documents to the compatible schema. So we will have to perform that procedure before CouchDB can be upgraded.

**Describe alternatives you've considered**
To be discussed

**Additional context**
Sub-task of https://github.com/dmwm/WMCore/issues/8853

**Comment by vkuznet** [comment]
@amaltaro can you provide details of what schema/files are not compatible? The CouchDB is schema-less database, meaning any valid JSON can be injected into it. Therefore, I don't understand the statement that schema is not compatible. Which schema/files you're taking about? May be you referring that internal CouchDB files which keep the data has different data-format, but in this case I would expect that simple replication can bring data from one couch to another, i.e. we just need to re-inject the data.

**Comment by amaltaro** [comment]
@vkuznet Hi Valentin, right. It's not the schema of our documents that get written to CouchDB, but actually its internal mechanism on how this data is compressed/stored in the file system.

**Comment by amaltaro** [comment]
For the record, here is where it's documented that we cannot upgrade directly from CouchDB 1.x to 3.x:
https://docs.couchdb.org/en/stable/whatsnew/3.0.html#upgrade-notes

also pasting that text here:
"""
Due to code changes in [#2324](https://github.com/apache/couchdb/issues/2324), it is not possible to upgrade transparently from CouchDB 1.x to 3.x. In addition, the couchup utility has been removed from CouchDB 3.0 by [#2399](https://github.com/apache/couchdb/issues/2399). If you are upgrading from CouchDB 1.x, you must first upgrade to CouchDB 2.3.1 to convert your database and indexes, using couchup if desired. You can then upgrade to CouchDB 3.0. Or, you can start a new CouchDB 3.0 installation and replicate directly from 1.x to 3.0.
"""

**Comment by amaltaro** [comment]
We have upgraded all the databases to the new format, but for the acdcserver. See more details here: https://github.com/dmwm/WMCore/issues/10833#issuecomment-1184479717

In short, the procedure was:
* setup another CouchDB node (vocms0745) with 3+
* replicate databases from CMSWEB to this new node
* upgrade CMSWEB VMs to the new CouchDB version
* move all the database shards (and _dbs and _users databases) to the VMs running the new version.

This ticket can be closed once the last database - acdcserver - is fully available in CMSWEB production.

**Comment by amaltaro** [comment]
And the acdcserver database has been updated as well. Further details can be found in this post:
https://github.com/dmwm/WMCore/issues/10833#issuecomment-1185485925

closing this out.
