### ISSUE TITLE
Build and create the necessary configuration files for MariaDB 10.6.x

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10835]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
This is a sub-task of https://github.com/dmwm/WMCore/issues/9241

**Describe the solution you'd like**
Build/package/upload the latest stable MariaDB version, which is 10.6.3 at the moment this issue was updated.
A list of actions required for that is:
* either create a new spec file for this latest MariaDB version; or update the current one
* come up with a reasonable default configuration file

**Describe alternatives you've considered**
Most of this is already available at https://github.com/cms-sw/cmsdist/pull/7205
and configuration changes are in https://github.com/dmwm/deployment/pull/1087

**Additional context**
Sub-task of https://github.com/dmwm/WMCore/issues/9241

**Comment by amaltaro** [comment]
MariaDB 10.6.5 has been made available through:
https://github.com/dmwm/deployment/pull/1116
and 
https://github.com/cms-sw/cmsdist/pull/7205

shall we close it? @goughes

**Comment by goughes** [comment]
Let's close this one out. Thanks @amaltaro!
