### ISSUE TITLE
Tier0 support for NanoAOD in PromtReco workflows

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#10845]
**Impact of the new feature**
Inform which systems would be affected by this new feature. WMAgent? ReqMgr2? WorkQueue? WMStats? MicroServices? etc

**Is your feature request related to a problem? Please describe.**
We have been asked to deliver NanoAOD data for Run3 data. To include this in Tier0 workflows, this should be added as an extra output of Prompt Reco, alongside MiniAOD. Work involves dmwm/T0 and CMSSW to enable the creation a such a configuration but it may likely also involve dmwm/WMCore. Therefore we opened this issue.

**Describe the solution you'd like**
We will need the ability to generate a workload including NanoAOD as one of the WriteTiers. Of course we also need the output data to be properly added to Rucio and create the associated block and container rules

**Comment by germanfgv** [comment]
This was open by mistake. Will move it to another issue.

**Comment by amaltaro** [comment]
@germanfgv German, this has been developed in WMCore in the 2nd semester of 2022, and a bug-fix has just been implemented (not yet deployed in production) to avoid workflows to transition to completed prematurely.

I also understand - from our chat in the recent days - that Tier0 managed to commission this in the T0 machinery and it's soon going to production.

Said that, I am closing this issue out. But please reopen it in case there are issues yet to be resolved and/or discussed. Thanks
