### ISSUE TITLE
WMAgent: Add oportunistic resources during agent deployment

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10877]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
While iterating through the agents during our latest agents upgrade campaign, we have missed to add the T3 US opportunistic resources (basically the US HPC sites).     

**Describe the solution you'd like**
There are two possible solutions to this:
 * Adding an additional step/option in the deployment procedure/script so that we do not forget it in the future. This  is good enough for the time being, but it still involves manual actions, which are still as error prone as manually executing the  command to add those resource to the agent's resource control.
 * Create a proper description for those resources in CRIC, so the regular and automated procedure for adding them to the agents is followed. This one would require more work and would be more tricky since those resources are expected to be present only at the FNAL agents.  

**Describe alternatives you've considered**
Just add a reminder in the wmagent deployment wiki [1] and continue executing the command by hand upon agent deployment only for the FNAL agents.

**Additional context**

[1] https://github.com/dmwm/WMCore/wiki/WMAgent-deployment#deployment-of-a-new-agent-in-production

**Comment by amaltaro** [comment]
I have missed this GH issue, but it should have been fixed by: https://github.com/dmwm/WMCore/pull/11047

Todor, if there is anything left in here, please reopen this issue.
