### ISSUE TITLE
Validate the Go-based DBSReader instance

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10883]
**Impact of the new feature**
WMCore central services AND WMAgent

**Is your feature request related to a problem? Please describe.**
Once the Go-based DBS Server and the stakeholders applications are ready (meaning, they are already using the compatible dbs3-client library), we plan to swap the cmsweb-testbed backend from the Python-based to the Go-based DBS Server. In other words, the endpoint and REST URI/URLs will be the same, but requests will be processed and served by the new Go server.

**Describe the solution you'd like**
Prerequisites for this are:
* having cmsweb-testbed central services using the upcoming dbs3-client (version TBD) release that is compatible with both DBS servers
* having testbed WMAgents using the same upcoming dbs3-client

Tests that need to be performed are:
* check of the global workqueue logs
* ensure that workflows are processing the correct blocks/files/lumis (and parent files)
* run all the DMWM/Integration test templates and check the lumi completion and parentage for top level outputs with input dataset
* check the ReqMgr2 StepChainParentage cherrypy thread and make sure it's working properly
* anything else that I might have missed (?)

**Describe alternatives you've considered**
Before diving into this large scale validation, we might want to run a quick test using the specific endpoint for the DBS2Go testbed server and point one of our WMAgents to it. All of the above is still required though, this is just to avoid bad surprises at the very beginning.

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10884

**Comment by amaltaro** [comment]
I have been testing this with WMCore 1.5.7.pre1 (dbs3-client 4.0.4) and central services seem to be working fine. 
WMAgent, on the other hand, had issues with WorkQueueManager while trying to reach `listFileArray` POST API, which the follow redirect change is apparently unable to workaround, since the next request it sends is actually using the GET method (thus Method Not Allowed).

This issue https://github.com/dmwm/DBSClient/issues/55 reports a previous problem, and this POST error is also mentioned in the proposed bugfix.

PS.: I will keep updating this comment as new issues arise.

**Comment by amaltaro** [comment]
I have executed many of our DMWM/Integration test workflows with WMAgent `1.5.7.pre4`, which comes with dbs3-client 4.0.5 and dbs3-pycurl 3.17.7 and everything seems to be working fine, including the StepChain parentage fix thread.

It could be that we still didn't manage to spot some uncommon use case, but I believe it has been tested enough for now. Closing this.

**Comment by vkuznet** [comment]
@amaltaro could you please confirm your WMAgent configuration, my understanding that you tested WMAgent with default cmsweb testebed urls for DBS, e.g. `/dbs/int/global/DBSReader` and `/dbs/int/global/DBSWriter`. If so, your report confirms that DBSReader (Go-based) and DBSWriter (Python-based) backends work fine, right?

**Comment by amaltaro** [comment]
@vkuznet that's right! Setup was:
* central services pointing to testbed `dbs/int/global/DBSReader`
* wmagent reading from testbed `dbs/int/global/DBSReader`
* wmagent writing to testbed `dbs/int/global/DBSReader`
