### ISSUE TITLE
Validate the Go-based DBSWriter instance

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10885]
**Impact of the new feature**
Mostly WMAgent (but also StepChainParentage ReqMgr2 thread)

**Is your feature request related to a problem? Please describe.**
Another major step towards the DBS2Go migration. This assumes that all our WMCore stack will be already fully integrated and functional with the dbs3-client that can talk to both Python and Go-based DBS server.

This process is planned to be carried on through a swap of the cmsweb-testbed backend from the Python-based to the Go-based DBS Server (at this point, DBSReader should already be using the Go server). In other words, the endpoint and REST URI/URLs will be the same, but requests will be processed and served by the new Go server.

**Describe the solution you'd like**
Prerequisites for this are: central services and WMAgent should be using the latest stable dbs3-client library (compatible with Python and Go server)

Tests that need to be performed are:
* run all the DMWM/Integration test templates and check many things, such as:
  * output dataset/block/file name
  * output file and dataset parentage
  * lumi sections and events within a lumi
  * meta data, like: acquisition era, processing string, prep_id, campaign, CMSSW release, origin site, etc
* ensure that the StepChainParentage CherryPy thread is behaving properly AND that the file parentage - for StepChain workflows - is correct
* anything else that I might have missed

**Describe alternatives you've considered**
 Before diving into this large scale validation, we might want to run a quick test using the specific endpoint for the DBS2Go testbed server and point one of our WMAgents to it. All of the above is still required though, this is just to avoid bad surprises at the very beginning.

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/10884 and somehow on https://github.com/dmwm/WMCore/issues/10883

**Comment by amaltaro** [comment]
@vkuznet Valentin, could you please clarify what the timeline is to deploying Go-based DBSWriter in cmsweb (and testbed)? Thanks

**Comment by vkuznet** [comment]
there is no specific date, and it is already deployed and available under cmsweb-testbed.cern.ch/dbs2go-writer, therefore you can use and test it at any time.. Said that, according to our DBS migration plan we'll make a swap for `/dbs/int/global/DBSWriter` to Go based server after we finish migration of DBSReader (sometimes in Q1-Q2). Once we validate it on testbed, then we'll upgrade it on cmsweb.

**Comment by amaltaro** [comment]
Okay, then we might leave it in standby for Q2. Thanks Valentin.

**Comment by amaltaro** [comment]
Just replicating this issue with StepChain parentage fix:
https://github.com/dmwm/dbs2go/issues/35

here, which affects both DBSReader and DBSWriter instances in Go.

**Comment by vkuznet** [comment]
The actual issue with insertFileParents DBS API was resolved in https://github.com/dmwm/dbs2go/issues/36

**Comment by vkuznet** [comment]
The swap of DBSWriter to Go-based server is scheduled on May 17th.

**Comment by amaltaro** [comment]
I just had yet another check at the StepChain parentage thread and it seems to be all right.

@vkuznet Valentin, now that we fixed all the known issues, deployed this to production, and made sure everything is behaving properly, shall we close this ticket?

**Comment by vkuznet** [comment]
yes, we can close this ticket.
