### ISSUE TITLE
Integrate Go/Python-server compatible dbs3-client in the WMCore stack

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10884]
**Impact of the new feature**
WMCore

**Is your feature request related to a problem? Please describe.**
This is part of the DBS2Go migration, where WMCore services need to be running with a dbs3-client library that is compatible with both the Python and the Go-based DBS servers (which also includes data aggregation on the client side).
 
**Describe the solution you'd like**
The required changes to make dbs3-client compatible in currently in progress.
Once a new release is made, we need to integrate it into our WMCore stack (cmsdist changes) and run some basic python-based server tests.

These changes need to be performed taking into consideration our production deployment cycles though, both for central services and for WMAgent.

NOTE: we should also update our requirements_py3.txt file accordingly.

**Describe alternatives you've considered**
None

**Additional context**
Note that python3 dbs3-client is already coming from the new DBSClient repository:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py3-dbs3-client.spec

so it will be just a matter of changing the package version.

**Comment by todor-ivanov** [comment]
And here is the related Pr in cmsdist:  https://github.com/cms-sw/cmsdist/pull/7493

Need to add some additional info here. The package comming from pypi does not have the usual `setup.py` as required by `pip install` command. Instead it has a file named `setupPypi.py` which makes the installation through standard pip to fail with the following error:

```
$ pip install dbs3-client==4.0.1
Using pip 21.3.1 from /afs/cern.ch/user/t/tivanov/WMCoreDev.d/WMCore.venv3/lib64/python3.6/site-packages/pip (python 3.6)
Collecting dbs3-client==4.0.1
  Downloading dbs3-client-4.0.1.tar.gz (24 kB)
ERROR: dbs3-client==4.0.1 from https://files.pythonhosted.org/packages/ff/d4/f7ab682fc1a7a89276b31977b3eea64685475567aaa83b90ca52fc392363/dbs3-client-4.0.1.tar.gz#sha256=117dcddca9168198e86fcae670b3cd526fccbd2fd415fe18540a0a50cab243b4 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

```  

But if one download and untar, the package can be successfully installed by running:
```
$ wget https://files.pythonhosted.org/packages/ff/d4/f7ab682fc1a7a89276b31977b3eea64685475567aaa83b90ca52fc392363/dbs3-client-4.0.1.tar.gz
$ tar -xzvf dbs3-client-4.0.1.tar.gz
$ python dbs3-client-4.0.1/python setupPypi.py install
...
```

And this is the reason why we have to rename the setup executable in cmsdist with this line:
https://github.com/cms-sw/cmsdist/blob/d82d97ae2f0045d01cb7290b330fb5d886742cc4/py3-dbs3-client.spec#L6

**Comment by belforte** [comment]
@todor-ivanov why can't DBS package in pypi be modified to be installable via `pip install` instead of the above hack ?

**Comment by todor-ivanov** [comment]
I think this is not something impossible to be solved. I have created the relevant issue in DBSClient repository: [1]

[1]
https://github.com/dmwm/DBSClient/issues/53

**Comment by todor-ivanov** [comment]
And just to mention it here too - the problem with the standard pip install procedure has been resolved. Thanks @vkuznet  @yuyiguo
 
FYI @belforte

**Comment by amaltaro** [comment]
This has been tested and the final setup is:
* py3-dbs3-pycurl: 3.17.7
* py3-dbs3-client:  4.0.5

provided by:
https://github.com/cms-sw/cmsdist/pull/7508
and
https://github.com/cms-sw/cmsdist/pull/7524

Any WMCore service that we build and package will now come with these new versions. Closing this
