### ISSUE TITLE
MSUnmerged: Apply the general directory exclusion list 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10900]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
Not exactly a problem. This is a followup on https://github.com/dmwm/WMCore/issues/10718. Since we  are about to close that issue, because no problems have been observed so far with the current exclusion list. The only change that needs to be done is to move from the more restrictive log directory list, which points to logs only for 2021 [1], to a more general one, which should exclude any logs [2]. This needs to happen as a last issue for the service, upon resolving all the rest.

[1]
```
data.dirFilterExcl = ['/store/unmerged/data/logs/prod/2021',
                      '/store/unmerged/hidata/logs/prod/2021',
                      '/store/unmerged/logs/prod/2021',
                      '/store/unmerged/express/logs/prod/2021']

```

[2]
```
data.dirFilterExcl = ['/store/unmerged/data/logs/prod/',
                      '/store/unmerged/hidata/logs/prod/',
                      '/store/unmerged/logs/prod/',
                      '/store/unmerged/express/logs/prod/']
```  

**Describe the solution you'd like**
Once we have all MSUnmerged issues resolved, swap the two directory exclusion lists.
 
**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
@todor-ivanov in order to protect 2022 logs, I think we should merge and deploy this configuration change (`prod` branch only): https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/124

then once we are in 2022 and properly cleaning logs, when can then adapt this list of exclusion directories such that old logs (<=2020) can be deleted. What do you think?

**Comment by todor-ivanov** [comment]
Hi @amaltaro, Yes this plan looks good to me. Thanks for making the service config change!

**Comment by amaltaro** [comment]
Configuration changes provided in https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/124 have been deployed to MSUnmerged production on Dec 21st.

**Comment by todor-ivanov** [comment]
This configuration is in production for a while now. I do not see a reason to keep this issue open. Closing it.
