### ISSUE TITLE
Credential/Proxy is not fully py3 compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10912]
TypeError: Unicode-objects must be encoded before hashing
in

https://github.com/dmwm/WMCore/blob/15067b9916fbd01b6599d5329aa6825940654bf6/src/python/WMCore/Credential/Proxy.py#L263-L264

**Comment by belforte** [comment]
@mapellidario FYI,  this already second glitch we found in current WMCore, shall we start out own branch and merge when @amaltaro is back ? Or i @todor-ivanov comfortable with merging such fixes in current master ?

**Comment by todor-ivanov** [comment]
Hi @belforte , Thanks  for reporting this! 

I'll take a look into this ASAP. I feel comfortable enough merging a fix of the sort, the only problem is this is not going to make it for the December release, which is about to be deployed tomorrow. 

Do you have a fix already in place or should I work on it myself? 

p.s. Just one more thing which is worth keeping in the issue would be a dump of an exception or an error message (in case you have one at hand).

**Comment by belforte** [comment]
don't worry @todor-ivanov it is a trivial change. It is simply a matter of our branch vs. your master vs. your tag etc. You should leave it to @mapellidario to make PR's

**Comment by todor-ivanov** [comment]
ok @belforte, waiting for the proper PR then. Thanks!
