### ISSUE TITLE
Soft error while creating MariaDB user in 10.6.5 during deployment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10926]
**Impact of the bug**
WMAgent

**Describe the bug**
In the first real exercise with this new mariadb version (10.6.5) integrated into the WMCore stack, there is a soft error during the agent deployment while creating a mariadb user [1]. From the logs, I think this error happens because two users (root and cmsdataops, the unix user used to deploy these services) have already been created when MariaDB is installed

**How to reproduce it**
Deploy WMAgent Py3 tag 1.5.7.pre1 with MariaDB backend (using deployment tag HG2201b).

**Expected behavior**
If that local user is already properly created and have all the necessary priveleges, then we could likely remove these lines from the manage script:
https://github.com/dmwm/deployment/blob/master/wmagentpy3/manage#L290-L292

but further debugging is still necessary.

**Additional context and error message**
[1] Logs from the agent deployment
```
starting mysqld_safe...
Checking MySQL Socket file exists...
Socket file exists: /storage/local/data1/cmsdataops/srv/wmagent/v1.5.7.pre1/install/mysql/logs/mysql.sock
MySQL has not been initialised... running post initialisation
Installing the mysql schema...
Socket file exists, proceeding with schema install...
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'cmsdataops'@'localhost'
Installing WMAgent Database: wmagent
Checking Server connection...
Connection OK
Done!
```

**Comment by goughes** [comment]
More details on this issue can be found at https://github.com/dmwm/WMCore/issues/10837#issuecomment-996082271

**Comment by amaltaro** [comment]
Thanks Erik! This has been fixed with: https://github.com/dmwm/deployment/pull/1117#event-5794211825
and will be available in the tag HG2101d. Closing

**Comment by amaltaro** [comment]
With this fix, a new issue popped up while creating the py2/py3 agent container in gitlab. Log for wmagentpy3 can be found at:
https://gitlab.cern.ch/CMSDOCKS/dmwm/-/jobs/18457054/raw

And it's using this script to deploy WMAgent for unittests:
https://github.com/dmwm/WMCore/blob/master/test/deploy/deploy_unittest.sh

I will check things tomorrow morning, reopening it.

**Comment by amaltaro** [comment]
Still failing... if I get the error message from:
https://gitlab.cern.ch/CMSDOCKS/dmwm/-/jobs/18470726/raw

I think the problem comes from the fact that we try a mysql operation with the `root` user, but we are not logged in as root.
Changing it to the current unix user should suffice, since it is automatically created and has all the necessary privileges.

**Comment by amaltaro** [comment]
Just a summary of all the required changes to get to properly use MariaDB 10.6.5 without mariadb user password protected (just using localhost access).

Deployment changes (mostly wmagent py2/py3 manage scripts:
https://github.com/dmwm/deployment/pull/1117
https://github.com/dmwm/deployment/pull/1119
https://github.com/dmwm/deployment/pull/1120

WMCore changes:
https://github.com/dmwm/WMCore/pull/10932
https://github.com/dmwm/WMCore/pull/10934

and also these cms-bot changes (used within our jenkins setup):
https://github.com/cms-sw/cms-bot/pull/1682

last but not least, I also sent an email to Shahzad to update our environment variables/secrets (MYSQL_USER) to actually use the current unix user (cmsbld) instead of the one previously defined in the file. Once this change is made, I have to remove a sed/replace command from the jenkins job configuration.

One of the reason for all these changes is the different setup we have for:
* docker image with the dev/test setup
* RPM deployment in jenkins
* different unittest variables (env.sh) between docker and jenkins setup.

When running services only locally, like MariaDB and CouchDB, we should start converging into a single set of environment/secrets. It will make debugging and maintenance easier.

Now this issue can be closed for good!
