### ISSUE TITLE
In python 3.9 the sys.setcheckinterval is removed

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#10925]
**Impact of the bug**
Starting Python 3.9 the sys.setcheckinterval is removed. This function is used by [REST/Main.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Main.py#L220) and all code to start web services will  break.

The actual bug description can be found in [Python/ssue37392](https://bugs.python.org/issue37392)

**Describe the bug**
According to https://bugs.python.org/issue37392 the usage of sys.setcheckinterval was deprecated since Python 3.2.

**How to reproduce it**
```
python3
Python 3.9.9 (main, Nov 16 2021, 07:33:57)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> help(sys.setcheckinterval)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute 'setcheckinterval'
```

**Expected behavior**
The logic of REST/Main.py should be fixed to remove this obsolete function call.

**Additional context and error message**
Related to https://github.com/dmwm/WMCore/pull/10911, https://github.com/dmwm/WMCore/issues/10921

**Comment by amaltaro** [comment]
@vkuznet Valentin, thanks for creating this issue. I would suggest to leave the `Assignees` field empty until someone is about to work on this issue, that allows more people to be able to see and assign themselves to these issues.

**Comment by amaltaro** [comment]
Even though there is a couple of comments in the Main.py module making reference to `sys.setcheckinterval`, this has already been fixed by Valentin with this PR: https://github.com/dmwm/WMCore/pull/11432

So I am closing this issue out. Thanks!
