### ISSUE TITLE
Improve WMCore framework metrics

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#10936]
**Impact of the new feature**
To setup better monitoring of WMCore service process it is desired to improve its metrics. This may include but not limited to the following items:
- total HTTP request time
- time spend on DB
- process metrics like cpu/mem, etc.

**Is your feature request related to a problem? Please describe.**
It will provide better way to monitor WMCore processes

**Describe the solution you'd like**
Improve metrics in WMCore logging and feed them to monitoring infrastructure

**Describe alternatives you've considered**

**Additional context**

**Comment by vkuznet** [comment]
Yes, we may close this issue.

**Comment by amaltaro** [comment]
Closed by https://github.com/dmwm/WMCore/pull/9940. Thanks!
