### ISSUE TITLE
Refactor MSUnmerged frontend rules (rse_type)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10942]
**Impact of the new feature**
CMSWEB redirection rules

**Is your feature request related to a problem? Please describe.**
When MSUnmerged was commissioned in CMSWEB, we needed to have a mechanism to reach specific ms-unmerged replicas, since their status and RSE data was only available in the instance memory itself. Some relevant deployment changes can be seen in:
https://github.com/dmwm/deployment/pull/1075
https://github.com/dmwm/deployment/pull/1078

Now that the service has been made stateless, using MongoDB as a backend, we can remove those query string tweaks from the backends map, and simple let nginx decide which `ms-unmerged` replica will serve a client request.

**Describe the solution you'd like**
Now that there is a MongoDB database behind MSUnmerged, we can change the logic between frontends and backends, like:
* completely remove the `rse_type` query string from the url matchmaking (in the backends txt file)
* discuss with Imran if and how we can have a random/round-robin mechanism to have any of the MSUnmerged k8s replicas to be chosen to serve a request made by a client. 

**Describe alternatives you've considered**
Not change anything and keep the current behavior, which is:
* in testbed: the query string decides which replica serves a given request
* in production: there is a hard-wired k8s replica to serve any client requests.

**Additional context**
None

**Comment by todor-ivanov** [comment]
This issue has been solved by this PR:
https://github.com/dmwm/deployment/pull/1129

I am closing this one here.
