### ISSUE TITLE
Adjust build_pypi_packages.sh and requirements.txt to handle py3 stack

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#10955]
**Impact of the bug**
With migration to python3 we need to adjust [build_pypi_packages.sh](https://github.com/dmwm/WMCore/blob/master/tools/build_pypi_packages.sh) and its usage of `requirements.txt`  to satisfy py3 dependencies. There are two files in WMCore repo, `requirements.txt` and `requirements_py3.txt`, and `build_pypi_packages.sh` uses the former one.

**Describe the bug**
In order to use `build_pypy_packages.sh` in CI/CD builds we need to fix its usage of `requirements.txt` . I don't know which dependencies (`requirements.txt` or `requirements_py3.txt`) is a proper set and I suggest to leave now only one file. Moreover, I suggest to remove explicit versions of packages, the `==` condition, and/or replace it with `>=` ones. For example, replace `mock==4.0.3` to `mock` or `mock>=4.0.3`. This is required to resolve potential conflicts of dependency packages during pip install.

**How to reproduce it**
There is no way to reproduce it since I only point out to two different files `requirements.txt` and `requirements_py3.txt`, and ask to converge them to a single one. But, someone can use pip command to see dependency conflicts, e.g.
```
# setup python env
python3 -m venv venv

# source env
source venv/bin/activate

# update pip
pip install --upgrade pip

# install dependencies
pip install -r requirements_py3.txt
...
Collecting pycurl==7.43.0.3
  Using cached pycurl-7.43.0.3.tar.gz (215 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /data/users/vk/tmp/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py'"'"'; __file__='"'"'/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/valya/pip-pip-egg-info-jy14zk6u
       cwd: /tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py", line 229, in configure_unix
      stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py", line 944, in <module>
      ext = get_extension(sys.argv, split_extension_source=split_extension_source)
    File "/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py", line 606, in get_extension
      ext_config = ExtensionConfiguration(argv)
    File "/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py", line 101, in __init__
      self.configure()
    File "/tmp/valya/pip-install-54dkfn3w/pycurl_b64a8d6a1b074e97a09c5a871124b7e7/setup.py", line 233, in configure_unix
      raise ConfigurationError(msg)
  __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz#sha256=6f08330c5cf79fa8ef68b9912b9901db7ffd34b63e225dce74db56bb21deda8e (from https://pypi.org/simple/pycurl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pycurl==7.43.0.3 (from versions: 7.18.2, 7.19.0, 7.19.0.1, 7.19.0.2, 7.19.0.3, 7.19.3, 7.19.3.1, 7.19.5, 7.19.5.1, 7.19.5.2, 7.19.5.3, 7.21.5, 7.43.0, 7.43.0.1, 7.43.0.2, 7.43.0.3, 7.43.0.4, 7.43.0.5, 7.43.0.6, 7.44.0, 7.44.1)
ERROR: No matching distribution found for pycurl==7.43.0.3

```

Here, we got dependency conflicts due to strict versions in `requirements_py3.txt`

**Expected behavior**
`pip install -r requirements.txt` command should work, where `requirements.txt` should be common set of dependencies (most likely for py3 we need content of `requirements_py3.txt` file).

**Additional context and error message**
Related to https://github.com/dmwm/WMCore/issues/10922,  https://github.com/dmwm/WMCore/issues/10921

**Comment by vkuznet** [comment]
@goughes since you suggested to use build_pypi_packages.sh in CI/CD pipeline I suggest that you look at this issue and propose resolution of requirements.txt and requirements_py3.txt files. I suggest to merge them now into requirements.txt single file and resolve dependency conflicts.

@amaltaro I think you are the best person to know which versions of dependency packages should be used.

**Comment by amaltaro** [comment]
Given that we have decided to stop supporting Python2 within WMCore, shall we start with the removal of this requirements.txt file? Or even better, replace it by the *_py3.txt one.
Adding this one to this quarter plan as well.

**Comment by vkuznet** [comment]
I think the `requirements_py3.txt` should replace `requirements.txt` but its content should be verified and dependency conflict should be resolved. As I reported so far it does not work.

**Comment by goughes** [comment]
@vkuznet I got confused for a second because the error you posted in this issue is a preliminary error one would get if they do not have the package that provides `curl-config`. But, then I did see this when I tried to reproduce on my machine.

```
ERROR: Cannot install -r requirements_py3.txt (line 35) and pycurl==7.43.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pycurl==7.43.0.3
    dbs3-pycurl 3.17.7 depends on pycurl==7.43.0.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

So it looks like someone should update the dbs3-pycurl requirements as well. Does dbs3-pycurl require that specific version of pycurl or can we also specify `>=` there?

**Comment by vkuznet** [comment]
This outlines precisely the issue, if we take somebody else package and in that package there is a fixed version used, then it may lead to conflicts. Sure, we should fix dbs3-pycurl to use `>=` clause, but this step will trigger the new version of dbs3-client, etc. What a nightmare. We have the following chain:
- WMCore requires dbs3-client and uses `==` clauses in requirements.txt
- dbs3-client requires dbs3-pycurl and uses `==` clauses in requirements.txt
- dbs3-pycurl requires pycurl and uses `==` clauses in requirements.txt

Therefore, the fix should be
- fix dbs3-pycurl (dmwm/PycurlClient) to use `pycurl>=7.43.0.6` instead of `pycurl==7.43.0.6`
- fix dbs3-client to use `pycurl>=7.43.0.6` and  `dbs3-pycurl>=3.17.7` instead of `pycurl==7.43.0.6` and `dbs3-pycurl==3.17.7`
- finally, fix WMCore requirements to use `>=` everywhere in requirements.txt

As such, we need new release of dbs3-pycurl, dbs3-client and only after that we can have new release in WMCore.

**Comment by vkuznet** [comment]
Here is relevant PRs: https://github.com/dmwm/PycurlClient/pull/10 and https://github.com/dmwm/DBSClient/pull/65, and I put Alan as reviewer.

**Comment by goughes** [comment]
Do you think we put ourselves in danger by using `>=` instead of `~=`? There could be a case where we grab a breaking change from a major version update, although it might not be that common.

**Comment by vkuznet** [comment]
It took me a while to find out exec specs for operators, next time please post explicit references. Here they are:
- https://pip.pypa.io/en/stable/cli/pip_install/
- https://www.python.org/dev/peps/pep-0440/#version-specifiers
- https://www.python.org/dev/peps/pep-0440/#compatible-release

So, if I read the last two correctly the "compatible release" is probably best match for our case, i.e. it guarantees that we'll pick up minor upgrades, but do not change major version of the package.

I think we need to get consensus which operator to use, and from my reading I would agree with you Erik. @amaltaro please provide your feedback, and if we agree I can adjust dbs PRs accordingly.

**Comment by amaltaro** [comment]
Sorry for joining this discussion late.

From what I read, I think we all converged to the compatible release specifier, as described here:
https://www.python.org/dev/peps/pep-0440/#id52

so yes, I would suggest to stick with `~=` in our requirements.txt file (which is what Erik is already proposing in the PR, thanks!)
