### ISSUE TITLE
Use of DBS filelumis RESTful API needs to be made compatible

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10956]
**Impact of the new feature**
MSTransferor, but there could be other parts of the code (including DBS3Reader)

**Is your feature request related to a problem? Please describe.**
While debugging why our LumiList-based templates don't manage to pass the `assigned` request status, I noticed that MSTransferor is actually failing to run the lumi list comparison. The reason for that is that Go and the Python implementation of the `filelumis` RESTful API yield data in different format.

I believe this is only a problem because we make a direct call to the REST endpoint, without using the dbs3-client. Nonetheless, it needs to be verified as well.

In MSTransferor, this line is actually raising an exception:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSTransferor/RequestInfo.py#L409

as one can interactive check with:
```
>>> fileMask = LumiList(runsAndLumis={'123': 333})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.5.7/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.7/lib/python3.8/site-packages/WMCore/DataStructs/LumiList.py", line 96, in __init__
    for lumi in sorted(int(l) for l in lumiList):
TypeError: 'int' object is not iterable
```

**Describe the solution you'd like**
The MSTransferor code needs to be updated such that it can deal with both response formats, allowing for a transparent migration of the DBS server. Here is the location calling `filelumis`:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Tools/Common.py#L247

we still need to investigate whether this very same DBS API is called in different places, and we need to ensure that our code will behave properly, regardless of the DBSServer flavor.

In addition to that, we should also investigate whether any changes are required for the `DBS3Reader` module.

**Describe alternatives you've considered**

**Additional context**
The python-based server does an aggregation of the lumis grouped by run+lfn, example:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filelumis?validFileOnly=1&block_name=/DoubleMuon/Run2018D-v1/RAW%23590119e4-3060-4c9b-9b38-2b16f6844bab

while the Go implementation yields a row for each lfn+run+lumi information:
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/filelumis?validFileOnly=1&block_name=/DoubleMuon/Run2018D-v1/RAW%23590119e4-3060-4c9b-9b38-2b16f6844bab

**Comment by vkuznet** [comment]
@amaltaro I scan WMCore repo and there are only two modules where code calls `mult_getdata` (I used rust grep tool to scan the repo and it reports line numbers for matched patterns):
```
rg multi_getdata
src/python/WMCore/Services/DBS/DBS3Reader.py
29:# from WMCore.Services.pycurl_manager import getdata as multi_getdata
799:    #     data = multi_getdata(urls, ckey(), cert())

src/python/WMCore/MicroService/MSMonitor/MSMonitor.py
146:        # FIXME: create concurrent rucio calls using multi_getdata

src/python/WMCore/MicroService/Tools/PycurlRucio.py
25:from WMCore.Services.pycurl_manager import getdata as multi_getdata
130:    data = multi_getdata(urls, ckey(), cert(), headers=headers)
180:    data = multi_getdata(urls, ckey(), cert(), headers=headers)
265:    data = multi_getdata(urls, ckey(), cert(), headers=headers)
325:    data = multi_getdata(urls, ckey(), cert(), headers=headers)
360:    data = multi_getdata(urls, ckey(), cert(), headers=headers)
404:    data = multi_getdata(urls, ckey(), cert(), headers=headers)

src/python/WMCore/MicroService/Tools/Common.py
26:from WMCore.Services.pycurl_manager import getdata as multi_getdata
62:    data = multi_getdata(urls, ckey(), cert())
99:    data = multi_getdata(urls, ckey(), cert())
144:    data = multi_getdata(urls, ckey(), cert())
196:    data = multi_getdata(urls, ckey(), cert())
231:    data = multi_getdata(urls, ckey(), cert())
260:    data = multi_getdata(urls, ckey(), cert(), num_conn=10)
287:    data = multi_getdata(urls, ckey(), cert())
322:    data = multi_getdata(urls, ckey(), cert())
366:    data = multi_getdata(urls, ckey(), cert())
584:    data = multi_getdata(urls, ckey(), cert())
```

Since `multi_getdata` calls in parallel given url list via direct REST API you need to make a decision how to handle aggregated data. There are two ways:
- add `multi_getdata` to DBSClient and provide flag to aggregate data
- handle results in place where code calls `multi_getdata`

Either way, it will require coding to handle aggregated data, and my understanding it may delay transition to Go server. Do you need this codebase for WMAs?

**Comment by amaltaro** [comment]
Thanks for looking into this, Valentin.

I did further greps and it actually affects only MSTransferor, which is heavily relying on those concurrent HTTP calls supported by the pycurl_manager module.

I think I would not change the `multi_getdata` API itself, but instead I would deal with data aggregation on the client side (in this case, the Common module). Another argument is that data aggregation would be especific to the service/API we are calling, so we better not touch pycurl_manager at all.

In addition to that, on L264:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Tools/Common.py#L264
we check for a possible None as result (in case there are no matches on the server side). I know that you have made it consistent such that it actually returns an empty list `[]` instead. If you want to work on this issue, can you please consider this change as well?

PS.: If you do work on it, don't forget to a) assign this issue to yourself; and b) move it to the "In progress" column in Q1/2022 project board. Feel free to ping me on slack if you have any questions as well.

**Comment by amaltaro** [comment]
I forgot to mention that we do not need it for WMAgent - that we are about to release in the coming days - but we do need to push this in in CMSWEB before we actually swap DBSServer in production as well. Honestly speaking, the sooner we have it in testbed the better.

**Comment by vkuznet** [comment]
I'll work on it and provide proper fix.
