### ISSUE TITLE
Pileup input data placement: Create input rules for every secondary location defined in the campaign

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10975]
**Impact of the bug**
Central production. Related: https://github.com/dmwm/WMCore/issues/10061  

**Describe the bug**
P&R defines secondary location(s) for every pileup secondary in the campaign configuration. In some cases, MSTransferor creates input rule for only one RSE from the campaign configuration whereas we expect it to create rules for every secondary location. However, I also remember cases where it acted properly and created rules for every RSE. I suspect it's related to how secondary locations are defined in the campaigns. There are multiple ways to do it which might be the reason for this inconsistency. Some examples:
1. https://cmsweb.cern.ch/reqmgr2/data/campaignconfig/RunIIAutumn18FSPremix
2. https://cmsweb.cern.ch/reqmgr2/data/campaignconfig/RunIISummer20UL16DIGIPremix
3. https://cmsweb.cern.ch/reqmgr2/data/campaignconfig/RunIISummer20UL17pp5TeVDR

**How to reproduce it**
When MSTransferor doesn't create rules for every RSE, we talk to DM team and ask them to create rules for missing RSEs. That's why I couldn't find an existing campaign to demonstrate the problem. If a new campaign w/ PU comes in, I'll update the issue.

**Expected behavior**
Ideally we should get rid of this inconsistent campaign definitions and agree on a single way to define locations to avoid confusions. However, it requires more work and simply we cannot find time to do it. Related issue: https://github.com/dmwm/WMCore/issues/10061 

What I suggest short term is to make MSTransferor create input rules for every RSE no matter how the location is defined in the campaign.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@haozturk thanks for creating this issue.
Can you please confirm whether we have pileup datasets defined with an empty list in the campaigns? If so, what would be the expected behavior in such cases?

PS.: you created this issue using the "Bug" template, but it's actually a "Feature request/change" ticket. Please consider it for the upcoming tickets because they provide you with slightly different fields.

**Comment by haozturk** [comment]
> Can you please confirm whether we have pileup datasets defined with an empty list in the campaigns?

We don't

> If so, what would be the expected behavior in such cases?

An intelligent RSE selection could be an option, but let's leave this to #10061 and assume that there will not be such cases while fixing this issue.

> PS.: you created this issue using the "Bug" template, but it's actually a "Feature request/change" ticket. Please consider it for the upcoming tickets because they provide you with slightly different fields.

It depends on the initial requirements, IMO. If the requirement when MSTransferor was developed was to create rules for every RSE, then it's a bug as it doesn't meet the requirement. O/w it's a feature request. I don't know the initial requirements, though :)

**Comment by amaltaro** [comment]
Thanks for the confirmation, Hasan. I think we can add a check in the code and keep the workflow in the same state in case we find a pileup with an empty list, just as a safety mechanism.

Fair comment on the issue creation! ;)

**Comment by haozturk** [comment]
> I think we can add a check in the code and keep the workflow in the same state in case we find a pileup with an empty list, just as a safety mechanism.

Sounds good!
