### ISSUE TITLE
MSUnmerged: Broken MongodB related unittests 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10978]
**Impact of the bug**
MSUnmerged

**Describe the bug**
Not exactly a bug. Until now we were having a quite unstable setup of MongoDB related unit tests for both `MSUnmerged` and `MSOutput` as well. Since we now know that the `mogomock` library [1] is doing the job of simulating a real database connection quite well [2] we need to fix these [3] tests too.  

[1]
https://github.com/mongomock/mongomock

[2]
https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12755/artifact/artifacts/PullRequestReport.html

[3]
https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12754/testReport/junit/MSUnmerged_t/MSUnmergedTest/testCutPath/

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12754/testReport/junit/MSUnmerged_t/MSUnmergedTest/testFilterInclExclDirectories/

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12754/testReport/junit/MSUnmerged_t/MSUnmergedTest/testFilterExclDirectories/

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12754/testReport/junit/MSUnmerged_t/MSUnmergedTest/testFilterInclDirectories/

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-WMCore-PR-test/12754/testReport/junit/MSUnmerged_t/MSUnmergedTest/testPlineUnmerged/

**How to reproduce it**
All MongoDB related unit tests for MSUnmerged are failing due to lack of MongoDB server at the nodes executing the tests.

**Expected behavior**
Have a decently constructed MongoDB emulation so that  all the tests pass.

**Additional context and error message**
N/A

**Comment by d-ylee** [comment]
Our Jenkins wmcore-dev image doesn't use RPMs, so we need to add `mongomock` to our WMCore requirements.txt.
