### ISSUE TITLE
Revisit environment variables that need to be passed from job wrapper to the CMSSW environment

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10970]
**Impact of the new feature**
Improve documentation ( and perhaps define a dictionary in the vode) of environment variables that need to be passed from job wrapper to the CMSSW environment. 

**Is your feature request related to a problem? Please describe.**
This was originally requested by CRAB, and it would be useful to any package depending on WMCore for this.

**Describe the solution you'd like**
Provide better documentation in the wiki and explore if a dictionary with all environment would be useful for the methods

**Comment by khurtado** [comment]
Done:
https://github.com/dmwm/WMCore/wiki/Notes-about-environment-variables-passed-to-the-Scram-environment-or-modified-when-running-the-CMSSW-executable

**Comment by amaltaro** [comment]
Thanks Kenyi! This documentation looks fantastic!
Could you please link this new wiki under the broader PSet tweak wiki that you created last year:
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime
? Perhaps under the `Job runtime details` section?

@belforte FYI, further information on the job runtime has been provided with this ticket

**Comment by belforte** [comment]
thanks @khurtado and @amaltaro 
I will read and study carefully.
Of course CRAB does not directy use the WMCore CMSSW executor :-)
So I may have to endup writing another small writeup which points to yours and explain our side,
to help future developers to keep things in sync.

BTW, I did not see immediately how you pass X509_USER_PROXY to cmsRun.
Nor the  XrdSecGSISRVNAMES needed by RAL https://github.com/dmwm/CRABServer/issues/6953

**Comment by khurtado** [comment]
Hi @belforte , since `cmsRun` is executed through a subprocess call and not Scram(), those variables are not lost

**Comment by belforte** [comment]
I tried to reply from phone, but it looks that it did not work.
Thanks @khurtado , I think I understand now.
I will follow up in ad-hoc issue.

**Comment by khurtado** [comment]
> Thanks Kenyi! This documentation looks fantastic! Could you please link this new wiki under the broader PSet tweak wiki that you created last year: https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime ? Perhaps under the `Job runtime details` section?
> 
> @belforte FYI, further information on the job runtime has been provided with this ticket

You got it! I just added this documentation in that wiki section.
