### ISSUE TITLE
MSUnmerged: Wrong input filters applied when reading from MongoDB 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10981]
**Impact of the bug**
MSUnmeged

**Describe the bug**
Not exactly a bug since we are already running quite safe with the current code, which already has a workaround for this. 
When reading from MongoDB we cannot apply filters of the sort:
```
mongoProjection = {
    "_id": False,
    "name": True,
    ...
    "files": False
}
``` 

Because we are getting this result: 
```
In [3]: from WMCore.MicroService.MSUnmerged.MSUnmergedRSE import MSUnmergedRSE

In [4]: rse = MSUnmergedRSE('T2_US_Wisconsin')

In [5]: rse.readRSEFromMongoDB(msUnmergedColl, useProjection=True)
---------------------------------------------------------------------------
OperationFailure                          Traceback (most recent call last)
<ipython-input-5-52e7cdc3e352> in <module>
----> 1 rse.readRSEFromMongoDB(msUnmergedColl, useProjection=True)

~/WMCoreDev.d/WMCore/src/python/WMCore/MicroService/MSUnmerged/MSUnmergedRSE.py in readRSEFromMongoDB(self, collection, useProjection)
     99         if useProjection:
    100             mongoProjection = self.buildMongoProjection()
--> 101             mongoRecord = collection.find_one(self.mongoFilter, projection=mongoProjection)
    102         else:
    103             mongoRecord = collection.find_one(self.mongoFilter)

...

~/WMCoreDev.d/WMCore.venv3/lib64/python3.6/site-packages/pymongo/helpers.py in _check_command_response(response, msg, allowable_errors, parse_write_concern_error)
    157 
    158             msg = msg or "%s"
--> 159             raise OperationFailure(msg % errmsg, code, response)
    160 
    161 

OperationFailure: Cannot do exclusion on field files in inclusion projection

```

And the reason is because we are hitting some MongoDB functionality constraints here. It simply does not allow to have `exclusion` fields inside `inclusion` filters. In those cases the only field we are allowed to exclude is `_id`, which is basically what we need to exclude for sure. While if we want to skip some of the rest, they simply must not be present into the filter. Here is some discussion on the topic from the MongoDb comunity with some more  details [1]

[1]
https://www.mongodb.com/community/forums/t/projection-does-not-allow-exclusion-inclusion-together/31756
 

**How to reproduce it**
Just execute the steps from the code snippet above, trying to read from MongoDB with a complex `inclusion` filter which is having more than a single `exclusion` at the `_id` field. 

**Expected behavior**
Create the mongoDB filter properly so it could be applied at read and write operations with equivalent result without failing any of them. 

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@todor-ivanov to provide the full picture, can you please link the PR that injected this bug as well (to the initial description).
And what is not clear to me as well is whether this is a bug in production? Or is it only in testbed? Or both? Thanks

**Comment by todor-ivanov** [comment]
Hi @amaltaro Thank you for taking a look. I really do not remember the PR introducing it. I think it should have been one of the initial MongoDB related ones. And this is not exactly a bug currently reviling itself neither in `Prod` nor in `PreProd`, since we never hit it inside the code because we do not query read with filters [1],  while for the write operations we go through the fields one at a time [2].  But it is good to be fixed anyway, because we may spare some CPU cycles and also to avoid hitting it by chance in the future. I happened to discover it while writing the unit tests yesterday. I remember having to deal with that for write operations and we also have it mentioned in our discussions, but somehow we missed the read with filters operation. 
 
[1]
https://github.com/dmwm/WMCore/blob/d728fc69e712e1e0ba50c7247065badf41eb56c9/src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py#L828

[2]
https://github.com/dmwm/WMCore/blob/d728fc69e712e1e0ba50c7247065badf41eb56c9/src/python/WMCore/MicroService/MSUnmerged/MSUnmergedRSE.py#L144

**Comment by todor-ivanov** [comment]
And the fix should be relatively simple. It may go away with a single iteration at the top in the `buildMongoProjection` method while creating the filter:
https://github.com/dmwm/WMCore/blob/d728fc69e712e1e0ba50c7247065badf41eb56c9/src/python/WMCore/MicroService/MSUnmerged/MSUnmergedRSE.py#L71

I can work on that later today.
