### ISSUE TITLE
MSUnmerged: Create a REST API for all RSEs' state

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10995]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
While monitoring the overall work performed by the service tracked in the following issue [1], we've found that the single database query used for extracting the error counters for all the RSEs is quite useful. Provided this is a single call, It is quite logical to have it implemented as a REST API to the service, so that the information is easily exposed.

**Describe the solution you'd like**
Implement the following REST API:
https://cmsweb.cern.ch/ms-unmerged/data/info?rse=ALL_DOCS

Which should provide the output from the following query to MongoDB:
```
In [47]: filter = {}

In [48]: projection = {
    ...:     "_id": False,
    ...:     "name": True,
    ...:     "isClean": True,
    ...:     "counters": {
    ...:         "gfalErrors": True,
    ...:         "dirsToDelete": True,
    ...:         "dirsDeletedSuccess": True,
    ...:         "dirsDeletedFail": True}}

In [49]: list(msUnmergedCollProd.find(filter, projection))
Out[49]: 
[{'name': 'T1_US_FNAL_Disk',
  'isClean': True,
  'counters': {'dirsToDelete': 37,
   'dirsDeletedSuccess': 37,
   'dirsDeletedFail': 0,
   'gfalErrors': {}}},
   ...
   {'name': 'T2_ES_CIEMAT',
  'isClean': False,
  'counters': {'dirsToDelete': 514,
   'dirsDeletedSuccess': 512,
   'dirsDeletedFail': 2,
   'gfalErrors': {'No such file or directory': 2586}}}]
```

**Describe alternatives you've considered**
Using the query only from python for debugging. 

**Additional context**
None

**Comment by amaltaro** [comment]
That's the way to go, Todor. I didn't mean to use the same implementation of ReqMgr Aux module, but only the same convention to retrieve all the documents (from the user point of view).

**Comment by todor-ivanov** [comment]
Got it. Thanks Alan! A PR is on its way already.
