### ISSUE TITLE
JobStatusLite not able to remove jobs in condor - FNAL schedds only

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11000]
**Impact of the bug**
WMAgent

**Describe the bug**
Even though it's not a problem with WMCore itself, I'm creating this ticket such that we can keep track of this problem, effect and resolution.

This problem is happening only on the agents running at Fermilab. There seems to be an authz problem, which makes our condor_rm commands to fail (both interactively and via python bindings). This means that we cannot kill jobs pending or running for too long - from JobStatusLite.

As I give this issue further thought, it could be that we fail to kill jobs for workflows that are aborted as well.

**How to reproduce it**
condor_rm one of the jobs in the schedd

**Expected behavior**
There is nothing for us - WMCore - to do here. The FNAL team is already aware of this issue, through this elog:
https://cms-logbook.cern.ch/elog/GlideInWMS/7922

and the action needs to be taken from their side.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
Quick update: it looks like job removal works fine from WorkQueueManager. This is what I see in the ComponentLog:
```
2022-02-01 01:57:06,078:140199661131520:INFO:WMBSHelper:Killing 2813 jobs for workflow: cmsunified_task_HIG-RunIISummer20UL16wmLHEGEN-00571__v1_T_210713_205431_7586
2022-02-01 01:57:07,825:140199661131520:INFO:SimpleCondorPlugin:Going to remove all the jobs for workflow cmsunified_task_HIG-RunIISummer20UL16wmLHEGEN-00571__v1_T_210713_205431_7586
...
2022-02-01 01:58:10,910:140199661131520:INFO:WorkQueue:Killing workflow in WMBS: cmsunified_task_HIG-RunIISummer20UL16wmLHEGEN-00571__v1_T_210713_205431_7586
2022-02-01 01:58:29,698:140199661131520:INFO:WMBSHelper:Killing 0 jobs for workflow: cmsunified_task_HIG-RunIISummer20UL16wmLHEGEN-00571__v1_T_210713_205431_7586
```

which means that it correctly removed all the jobs in the first attempt. For the record, here is the code that removes jobs for a given workflow:
```
            schedd.act(htcondor.JobAction.Remove, "WMAgent_RequestName == %s" % classad.quote(str(workflow)))
```

**Comment by mapsacosta** [comment]
@amaltaro Updating here, we found the root cause:

Permissions on /tmp got messed up and the folder was owned by cmsdatops:

drwxr-xr-x.  14 cmsdataops us_cms 4.0K Feb 16 15:17 tmp

This made HTCondor confused because it could not talk to its local daemons, thus all local commands were logged as unauthenticated and were immediately denied. Definitely not a bug or fault on the WMCore end.

**Comment by amaltaro** [comment]
Awesome! Thanks for getting this fixed, @mapsacosta .
I guess we can close this ticket now.
