### ISSUE TITLE
WMAgents are unable to spot some existing input blocks w/o the `--deep` flag in Rucio

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11013]
**Impact of the bug**
WMAgents & Rucio

**Describe the bug**
WMAgents are unable to spot some existing input blocks w/o `--deep` flag in Rucio, since Rucio sometimes provides different information with and without `--deep` flag. The one w/ the `--deep` flag is always true and sometimes query w/o `--deep` returns False info.

**How to reproduce it**

The following workflow is stuck because of this issue: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016H-SingleMuon-21Feb2020_UL2016_WMass-00002 

```
$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_EE_Estonia      |       0 |     500 |
| T2_US_UCSD         |       0 |     500 |
| T2_ES_CIEMAT       |       0 |     500 |
| T2_FR_IPHC         |       0 |     500 |
| T2_IT_Rome         |       0 |     500 |
| T1_FR_CCIN2P3_Tape |     500 |     500 |
| T2_US_MIT          |       0 |     500 |
| T2_IT_Legnaro      |       0 |     500 |
| T2_US_Florida      |       0 |     500 |
| T0_CH_CERN_Tape    |     500 |     500 |
| T2_UK_SGrid_RALPP  |       0 |     500 |
| T2_US_Vanderbilt   |       0 |     500 |
| T1_US_FNAL_Disk    |       0 |     500 |
+--------------------+---------+---------+
```

w/ `-deep`
```
$ rucio list-dataset-replicas cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228 --deep

DATASET: cms:/SingleMuon/Run2016H-v1/RAW#b84ebcce-9e28-11e6-9951-001e67abf228
+--------------------+---------+---------+
| RSE                |   FOUND |   TOTAL |
|--------------------+---------+---------|
| T2_CN_Beijing      |     500 |     500 |
| T1_FR_CCIN2P3_Tape |     500 |     500 |
| T0_CH_CERN_Tape    |     500 |     500 |
+--------------------+---------+---------+
```

**Expected behavior**
Either:
- Rucio should always return the true information w/o the `--deep` flag

or 
- WMAgents should always use `--deep` flag, which might not be very efficient in terms of performance as far as I understand.

**Additional context and error message**
None

**Comment by ericvaandering** [comment]
As I've said in the meeting today and elsewhere, I believe. I think you should use --deep since you really need the right answer.

**Comment by todor-ivanov** [comment]
Thanks @ericvaandering  and @haozturk a similar situation has already been addressed for T0 with the following PR https://github.com/dmwm/WMCore/pull/10902 I think this could be just a matter of a configuration change now for enabling this for production agents too. We are also looking into the code to see if any other code change is needed, though.

**Comment by amaltaro** [comment]
Okay, so re-setting the flag for all our input data location it is. I still have to evaluate whether it will affect any possible bulk requests that we make against Rucio these days. Unless there is a blocker, we should have this change in the upcoming production deployment in a week'ish from now.

**Comment by amaltaro** [comment]
I have a quick update on this issue.

None of the microservices depend on the "list dataset replicas" client/rest APIs. 
Regarding WorkQueue, it relies on this code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py#L1106-L1164

to perform the data location+availability, which internally relies on the following Rucio python client APIs:
* list_replication_rules; and
* get_dataset_locks

and none of those have the `deep` option. I suspect the output of `get_dataset_locks` API somehow depends on the replica-based information, similar to the deep list dataset replicas thing(?)

@ericvaandering would you have any suggestion on how to proceed here? Otherwise, I fail to see what can be done from the WMCore side to reliably fetch data location/availability.

**Comment by klannon** [comment]
Would it make sense to ask (i.e. on the "support" channel in the Rucio slack whether those APIs would be impacted by the lack of a `deep` option, and if the answer is "yes," then we could create issues for implementing the deep option which could potentially be picked up by CMS folks contributing to core Rucio?

**Comment by ericvaandering** [comment]
Yes, that would make sense. I had to read this a few times to understand what you were saying.

**Comment by amaltaro** [comment]
Right! I will be more mindful on my future messages. I guess many of those times I write messages targeting myself, sorry!

**Comment by amaltaro** [comment]
For the record, this issue is being followed up here: https://github.com/dmwm/CMSRucio/issues/257

**Comment by amaltaro** [comment]
Moving it under the Waiting column as we wait for another case to be spotted in the production system. If it doesn't happen for a couple of extra months, we might consider closing it.

**Comment by amaltaro** [comment]
Given that it's been almost 3 months that we don't have any updates to this ticket and/or we are not aware of such data location problems without the `--deep` flag, shall we close this issue out as nothing to be done? Or is there anything that might have to be implemented on the Rucio side? @ericvaandering @haozturk

**Comment by amaltaro** [comment]
Given the lack of activity in this issue, I assume things are in a better shape now and it hasn't reoccurred.
I am closing this one out, but please reopen it if I am mistaken and further follow up is required. Thanks to everyone who contributed debugging this issue!
