### ISSUE TITLE
MSUnmerged: NotMasterError renamed to NotPrimaryError

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11012]
**Impact of the bug**
MSUnmerged

**Describe the bug**
This is a future bug. Currently we do not experience it, because we are still using old enough version of MongoDB such that the breaking change has not been introduced yet.

While working on some manual imports of few WMCore modules deployed with `pypi` I've stumbled on the following error: [1]. This is a change in behavior introduced  with `pymongo` version 4.0. The pymongo error `NotMasterError` has been deprecated and the new one to be used should be `NotPrimaryError` as recommended at [2]. This is a non-backward compatible change on pymongo side about which we need to pay attention, once we upgrade to `pymongo` version 4.0 and above. We are currently using  version 3.10.1: [3]. One thing needs to be mentioned though, as long as we are using the RPM based deployment we are  safe, but once we move to `pypi` packaging and deployment we need to have it fixed, because at 
https://github.com/dmwm/WMCore/blob/8a6a17e54470cdae5be75209cd9ac3b94c6dbdbb/requirements.txt#L37 
 we are already using `~=` as a requirement string, this immediately places us at the latest available version (currently 4.0.1) because it has no conflicts with any other module deployed.  
  

[1]
```
In [1]: from WMCore.Micrrom WMCore.MicroService.MSUnmerged.MSUnmergedRSE import MSUnmergedRSE
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-1-9daca6c75ccf> in <module>
----> 1 from WMCore.MicroService.MSUnmerged.MSUnmergedRSE import MSUnmergedRSE

~/WMCoreDev.d/WMCoreTest.venv3/lib64/python3.6/site-packages/WMCore/MicroService/MSUnmerged/MSUnmergedRSE.py in <module>
      4 """
      5 
----> 6 from pymongo.errors  import NotMasterError
      7 # from pymongo.results import results as MongoResults
      8 

ImportError: cannot import name 'NotMasterError'
```

[2]
https://pymongo.readthedocs.io/en/stable/changelog.html?highlight=3.10#breaking-changes-in-4-0
```
 * Removed pymongo.errors.NotMasterError. Use [pymongo.errors.NotPrimaryError](https://pymongo.readthedocs.io/en/stable/api/pymongo/errors.html#pymongo.errors.NotPrimaryError) instead.
```

[3]
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py3-pymongo.spec

**How to reproduce it**
```
In [1]: pymongo.version
Out[1]: '4.0.1'

In [2]: from WMCore.Micrrom WMCore.MicroService.MSUnmerged.MSUnmergedRSE import MSUnmergedRSE 
```

**Expected behavior**
Safe import of modules depending on pymongo.

**Additional context and error message**
None

**Comment by todor-ivanov** [comment]
With the additional tests did today, I have figured out that we need to upgrade both the client and the server version both together. So the resolution of this issue needs  to be in coordination with whom ever is about to be upgrading the MongoDB as a service instance.  
FYI @amaltaro @muhammadimranfarooqi @Panos512

**Comment by todor-ivanov** [comment]
Some  more findings. As confirmed also by Panos the database version on the server is already 5.03: [1]. So it seems the new  version is compatible with the old clients. I am about to proceed now with upgrading the client only. 

[1] 
```
In [4]: msUnmergedDB.command({'buildInfo':1})['version']
Out[4]: '5.0.3'
```

**Comment by amaltaro** [comment]
Todor, we might have to check other things as well, because our current MongoDB setup is somehow hybrid, like:
* ms-output: uses MongoDB deployed with k8s in the CMSWEB cluster (which version?)
* ms-unmerged: uses MongoDB AaS (according to Panos/you, on version 5.0.3
* microservices in dev mode (our VMs): uses MongoDB built in cmsdist (current version is 3.2.10)

Given that we have not yet fully deprecated the VM-based tests, I think we should make sure that these changes will work for all of these 3 setups.

**Comment by todor-ivanov** [comment]
Hi @amaltaro Thanks for looking into is. 
I am feeling pretty safe when it comes to those 3:
> * ms-output: uses MongoDB deployed with k8s in the CMSWEB cluster (which version?)

Yes, and those they still need to be migrated to MongoDB as a service. The Exception changed with the current issue  relates only to MongoDB as a service, because it has been deployed in a replicaset instead as a monolithic single database instance. So it is really unlikely to affect ms-output in any way.

> *  ms-unmerged: uses MongoDB AaS (according to Panos/you, on version 5.0.3

Yes, and this one has been tested and the client v.s server versions do match in both ways (old pymongo client in combination with the latest server  && new pymongo client with the latest server) and are backwards compatible. It is only the change of the exception handling on the client side which is not. 

> * microservices in dev mode (our VMs): uses MongoDB built in cmsdist (current version is 3.2.10)

Yes, again, it does require mongo 3.2.10 for our dev VM deployments, but honestly I do not see a use case where it can be a blocker, because it is a matter of a MSConfig change to make it use the MongoDB as a service instance and do not care about what is configured as a dependency in the rpm based deployment.

**Comment by amaltaro** [comment]
> Yes, again, it does require mongo 3.2.10 for our dev VM deployments, but honestly I do not see a use case where it can be a blocker, because it is a matter of a MSConfig change to make it use the MongoDB as a service instance and do not care about what is configured as a dependency in the rpm based deployment.

Yes, it's definitely not a blocker, but something that we must cover not to leave broken pieces around.

Given that we have not yet completely deprecated the VM setup - even if it's not the most productive work - we should ensure that VM setup will manage to access MongoDB AaS and ensure that such tests don't affect our production services stability. With this change, we should also consider the testX cmsweb clusters as well.

For the record, this `pymongo` client no longer supports MongoDB 3.2, see:
https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-4-0

**Comment by todor-ivanov** [comment]
> For the record, this pymongo client no longer supports MongoDB 3.2, see:

Yes this is correct. And this would break MSOutput in the VM based setup unless any of those happens: 
   * We upgrade mongodb version of the rpm here:   https://github.com/cms-sw/cmsdist/blob/comp_gcc630/mongo.spec (but this would affect every other service/package depending on it)
   * We just set the default config for ms-output VM deployment to use MongoDB as a Service instead. Here:  https://github.com/dmwm/deployment/blob/master/reqmgr2ms/config-output.py 

As I said before I'd bet for the later option, but looking at this file it has no Mongodb configuration parameters at all, unlike the K8 configs though: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/reqmgr2ms-output/config-output.py#L107-108 . It seems we have already abandoned this configuration file since a while now.

**Comment by todor-ivanov** [comment]
And as I started working on it I've found few more things need to be added and tested to MSOutput so that it could be redirected to MongoDB as a service. Like adding a username and password for the MongoDB as a service to `Reqmgr2msSecrets` and also adding the replicaset for the configuration similar to [1]. Here is a separate issue for his [2]. 

@amaltaro  lets merge this one and follow the MSOutput related changes in the dedicated issue.



[1]
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/reqmgr2ms-unmerged/config-unmerged.py#L98-102
```
data.mongoDBUrl = 'mongodb://%s:%s@%s' % (MONGODB_USER, MONGODB_PASSWORD, MONGODB_SERVER)
data.mongoDBPort = MONGODB_PORT
data.mongoDB = 'msUnmergedDBPreProd'
data.mongoDBReplicaset = 'cms-db'
data.mongoDBRetryCount = 3
```

[2]
https://github.com/dmwm/WMCore/issues/11020
