### ISSUE TITLE
Stand-alone setup for MariaDB deployment

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11026]
**Impact of the new feature**
It would be useful to setup fully independent stand-alone deployment for MariaDB. This can be used during CI/CD, dev environments, etc.

**Is your feature request related to a problem? Please describe.**
We are moving towards unified approach to deploy WMCore services in different environments, dev env, k8s, etc. The use case has beed described here: https://github.com/dmwm/WMCore/issues/10979

**Describe the solution you'd like**
We need stand-alone deployment of MariaDB, including:
- download recent version
- separate configuration for MariaDB
- schema upload and validation in MariaDB
- add deployment and setup into venv script

**Describe alternatives you've considered**
Currently, we're based on RPM based procedure and will keep it for time being.

**Additional context**
Here are the relevant tickets: https://github.com/dmwm/WMCore/issues/10979, https://github.com/dmwm/WMCore/issues/10921,  https://github.com/dmwm/WMCore/issues/10935, https://github.com/dmwm/WMCore/pull/10911

**Comment by amaltaro** [comment]
@vkuznet Valentin, now with the migration to Alma9 and docker for WMAgent, I understand that the behavior requested has been accomplished. If so, can you please then close this ticket out?
