### ISSUE TITLE
Run3 Nano production while data taking

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#11048]
**Impact of the new feature**
WMAgent, ReqMgr2(?), WorkQueue(?)

**Is your feature request related to a problem? Please describe.**
T0 is not able generate NanoAOD as part of PromptReco workflows. Adding that feature would involve several time consuming developments. Instead of that, we are considering the possibility of having production workflows that generate NanoAOD during data taking.

**Describe the solution you'd like**
T0 creates MiniAOD datasets and continually adds blocks to them during data taking. We want to have running production workflows that will create NanoAOD out of the growing MiniAOD datasets. A more detailed description of the feature can be found in Jira: [CMSTZ-969](https://its.cern.ch/jira/browse/CMSTZ-969)

**Describe alternatives you've considered**
The alternative would be to modify PromptReco spec to generate the NanoAOD in T0. This has the complication that T0 currently cannot handle flat N-tuples files.

**Additional context**
CMS-T0 Jira discussion: [CMSTZ-969](https://its.cern.ch/jira/browse/CMSTZ-969)

**Comment by amaltaro** [comment]
As discussed during our chat, this issue actually requires two actions at different timelines:
* first half of April: we must assess whether `OpenRunningTimeout` request option is still functional and whether newly created blocks would make it into new chunks of work. In short, evaluate how much effort is required to have this feature fully functional.
* by the end of May: this feature must be fully functional and tested, such that T0/Central Production can start relying on it at the beginning of data taking (June 2022).

**Comment by amaltaro** [comment]
Once we confirm this workflow can be supported by central production, we can likely close this issue out: https://github.com/dmwm/WMCore/issues/10845

**Comment by amaltaro** [comment]
I  managed to get some initial results with this test workflow:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ReReco_RunBlockWhite_Agent202_Val_220413_175017_2462

defined with `OpenRunningTimeout=20000`, thus watching for new input blocks for 20k seconds.

It looks like it only works if the workflow remains in status `running-open`. This test had a single input block, which was immediately pulled down by an agent, triggering a status transition from `running-open` to `running-closed`. Once it's in `running-closed`, global workqueue no longer tries to further split this workflow.

TODO: What should be investigated next is to see how much effort it is to limit status transition from `running-open` to `running-closed` to also consider the request level `OpenRunningTimeout` parameter.

**Comment by amaltaro** [comment]
Reopening because there are 2 sub-issues - #11129 and #11130 - to be worked on before we can complete this feature throughout WMCore services.

**Comment by amaltaro** [comment]
And this issue can now be closed, with all the sub-tasks that have been created and worked on, such as:
* Global Workqueue with the removal of legacy open blocks from DBS: https://github.com/dmwm/WMCore/issues/11120
* Global Workqueue required changes: https://github.com/dmwm/WMCore/pull/11119
* Global WorkQueue with incremental statistics: https://github.com/dmwm/WMCore/issues/11129
* MSTransferor required changes: https://github.com/dmwm/WMCore/issues/11130

I don't think it requires a new WMAgent version to support this feature, but I could be wrong. Closing it.
