### ISSUE TITLE
Add support to RHEL8 workflows/jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11051]
**Impact of the new feature**
ReqMgr2 / WMAgent

**Is your feature request related to a problem? Please describe.**
Following an email exchange with Shahzad, they would like to start running tests with RHEL8 production workflows as soon as possible.

**Describe the solution you'd like**
In short, WMCore systems should support workflow creation and assignment as well as job creation and execution under RHEL8 OS (or variations of it, like EL8, Alma8, CS8, etc).

A **non-exhaustive** list of places that we need to verify and/or update if required, is:
1. submit_py3.sh job wrapper
2. the Scram.py module, which should have a map of ScramArch to OSes
3. SimpleCondorPlugin

UPDATE: as provided by Shahzad below, the list of new archs to be supported is:
```
(el|cc|cs|alma)N_(amd64|ppc64le|aarch64)_gccV
```
(where N>=8 and V>=10).

**Describe alternatives you've considered**
None

**Additional context**
In order to properly test it, we need to identify:
* which CMSSW release we could use for this test. Apparently CMSSW_12_3_0_preX releases under `cs8_amd64_gcc10`
* which ScramArch are we going to use for such workflows? Is it going to be only `slc8_*`, or should we consider the other variations?
* and whether there are RHEL8 pilot containers that we could use (thus, being able to run such workflows anywhere)

**Comment by smuzaffar** [comment]
@amaltaro , currently we have cs8_amd64_gcc10 releases available for tests. Soon we will build alma8_amd64_gcc10 release too.
Starting with EL8, we are not using `slc` for operating system name string. New archs are `(cc|cs|alma)N_(amd64|ppc64le|aarch64)_gccV`  (where N>=8 and V>=10). There is already singularity container `rhel8` (just like rhel7 and rhel6) available on cvmfs.

**Comment by amaltaro** [comment]
update: initial description updated to reflect the required changes.

**Comment by smuzaffar** [comment]
thanks @amaltaro for adding the support. I noticed [here](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Tools/Scram.py#L41) that you have `aarch64` and `ppc64le` mentioned. Does this mean we can now properly handle requests for these archs too?

**Comment by amaltaro** [comment]
Yes, but that architecture mapping only affects the job description and target grid resources for executing the payload.

To complete the loop, I think we would need to have some libraries (including python and python future) in CVMFS, such that the job wrapper can use libraries built in/for those architectures. @smuzaffar
