### ISSUE TITLE
Support ARM64 architecture at the job description and runtime

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11063]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Given that we have CMSSW builds for ARM64 architecture, we should make sure this architecture would be supported in central production workflows as well.

**Describe the solution you'd like**
We need to ensure that `aarch64` architecture is supported at the job description AND job runtime. This involves:
* the submit_py3.sh job wrapper
* required libraries need to be available in CVMFS (even if it doesn't come from our COMP stack). We must have at least `python3` (3.8 would be the best) and `future` python library.
* SimpleCondorPlugin need to properly define the `Target` architecture

and any other place that I might be still missing.

**Describe alternatives you've considered**
None

**Additional context**
Some discussions with Shahzad started in this PR: https://github.com/dmwm/WMCore/issues/11051

**Comment by smuzaffar** [comment]
`uname -m` for arm64 is `aarch64` and yes it is exact same string used in ScramArch

**Comment by hufnagel** [comment]
+1 on this since we'll be trying to commission an ARM based HPC in the US ~soonish

**Comment by khurtado** [comment]
@amaltaro Do we need to support ARM64 under slc6?

**Comment by smuzaffar** [comment]
No, slc6/ARM or slc6/power support is not needed, we do not have any cmssw release for these archs.

**Comment by amaltaro** [comment]
Kenyi, I understand that there is no required work to be done and that the last changes provided with this PR:
https://github.com/dmwm/WMCore/pull/11077

completed the support to this architectured (and PowerPC). Is that correct? If so, shall we close it?

Just a note regarding your comment on the BasePlugin, it looks like you just identified the place that we need to change (plus SimpleCondorPlugin) in order to address this ticket: https://github.com/dmwm/WMCore/issues/10674
