### ISSUE TITLE
Put `T3_ES_PIC_BSC` in production: Update CERN & FNAL resource control accordingly

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11072]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
We decided to start testing T3_ES_PIC_BSC for production using regular production agents and we want our agents to work with this site.

**Describe the solution you'd like**
Update existing and incoming CERN & FNAL agents to include this site in their resource control.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by aperezca** [comment]
Thanks, Hasan!

I'd like to add that the typical scale at which we would like to operate BSC is 5k CPU cores. (=about 2.5 times that of PIC).

As files produced by jobs running at BSC will be merged at PIC, we might need to rescale merge limits for PIC as well. What is the current total limit of merge for T1_ES_PIC?

**Comment by amaltaro** [comment]
@aperezca Hi Antonio, current limits for T1_ES_PIC are (pending slots vary according to the number of agents up and running with the same team name):
```
T1_ES_PIC - 106 running, 680 pending, 4820 running slots total, 723 pending slots total, Site is Normal:
  Merge - 0 running, 1 pending, 120 max running, 25 max pending, priority 4
```

so, 4.8k jobs in total and up to 120+25 merge jobs.

Regarding `T3_ES_PIC_BSC`, I have just added it to vocms0252 such that tests can proceed. It's set with 3k running and 2k pending jobs (a total of up to 5k jobs).

A permanent or better solution is still to be implemented.

Antonio, are these BSC resources going to be available for a somehow long period?

**Comment by aperezca** [comment]
Hi Alan,

On PIC, thanks for the info, we might need to increase the amount of merge jobs, let's see as we advance in our expertise running PIC+BSC combined (all merge is done at PIC)

On BSC, thanks for adding it to the covms0252 agent and schedd. Yes, I already see some jobs in queue for T3_ES_PIC_BSC. And 5k jobs should be sufficient.

"A permanent or better solution is still to be implemented." => We have been discussing this with Stephan (see [ticket)](https://ggus.eu/index.php?mode=ticket_info&ticket_id=156291). He pointed me to the Site Capacity data, which I have already edited for BSC: https://cmssst.web.cern.ch/cgi-bin/set/SiteCapacity/T3_ES_PIC_BSC

I hope this is the permanent solution we need, as indeed BSC CPU resources are expected to become part of the future pledge of our Tier1 at PIC. We already have a collaboration agreement signed so we, from PIC, can use BSC to run our LHC VOs tasks (ATLAS, CMS and LHCb). This allows us to request and get assigned some CPU fraction regularly at BSC.

**Comment by amaltaro** [comment]
I don't know why I haven't thought about this over the past 4 years(!!), but we should simply add another command line option in this script:
https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control

such that we can add opportunistic resources with a single command line without the CRIC dependency.
