### ISSUE TITLE
Jenkins PR unit tests checks failing to create a new baseline

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11089]
**Impact of the bug**
Jenkins

**Describe the bug**
It's been weeks that I see PR jenkins reports like:
```
Python3 Unit tests: succeeded
* 7 tests added
```

however, those 7 new unit tests have been added by a PR that has been merged many weeks ago.
So, something in our PR vs baseline unit test setup is not persisting the new unit tests, and it keeps considering those as new over and over.

**How to reproduce it**
Not sure

**Expected behavior**
There are 2 baseline jenkins releases created every day. So, whenever a PR gets merged, the unit tests that it adds should be persisted in the next baseline jenkins release, and those should stop being reported as new tests.

**Additional context and error message**
None

**Comment by goughes** [comment]
The 7 unit tests added for MSUnmerged were failing in the Jenkins job `DMWM-WMAgentPy3-TestAll` due to the following openssl RuntimeError.

```
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
```

Resolved by setting this environment variable in the Jenkins tests (which was already set for the PR tests).
```
export CRYPTOGRAPHY_ALLOW_OPENSSL_102=1
```

Now PR tests are coming back with proper counts for added tests.

```
Jenkins results:

Python3 Unit tests: succeeded
 * 1 changes in unstable tests
```

**Comment by amaltaro** [comment]
Wonderful! Thank you very much for pin-pointing this problem and getting it fixed!
