### ISSUE TITLE
Ensure that the GridFTP service deprecation has no impact in the WMCore services

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11087]
**Impact of the new feature**
Likely WMAgent and perhaps MSUnmerged

**Is your feature request related to a problem? Please describe.**
Support to GridFTP will be over by end of May 2022, so we should make sure that this won't have any impact on the WMCore services.

For context, WMAgent does the stage out using a few plugins stored under WMCore/Storage/Backend, which includes stage in for the logArchive tarballs.
MSUnmerged access (and deletes) unmerged data with gfal2 utils and a map from Rucio.

**Describe the solution you'd like**
Talk to the SS team (or Stephan L.) and understand whether the end-of-life of the GridFTPs can have any impact on how WMAgent and/or MSUnmerged perform file access/copy/deletion. I'm inclined to say it has no impact, but we better make sure of that not to be caught by surprise.

If there is any work to be done in WMCore, the sooner we know it the better.

**Describe alternatives you've considered**
Wait for things to break :)

**Additional context**
None

**Comment by amaltaro** [comment]
@goughes Erik, what do you think about working on this issue this or in the coming week?

**Comment by goughes** [comment]
Sounds good @amaltaro, assigned myself.

**Comment by goughes** [comment]
After taking a look at this, I don't see any place in WMCore that would be impacted by this. There is no place where we explicitly use gridftp. Rucio calls from MSUnmerged use whatever the default Rucio protocol is for the site. Jobs would use the local siteconf. LogArchive/Collect transfers to EOS are hard coded to use `xrdcp`.
