### ISSUE TITLE
Workflows stuck in announced status for a year

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11094]
**Impact of the bug**
Likely MSRuleCleaner

**Describe the bug**
While scanning the system for very old workflows, I found a small set of workflows from 2020 that have been sitting in `announced` status for many months, maybe even for a year or more. Here is the list [1].

**How to reproduce it**
None

**Expected behavior**
Workflow archival should be done at the MSRuleCleaner microservice, so we should investigate its logs in production and try to understand why these workflows are still in announced. There could be some implemented constraints which are keeping these workflows in this state, but we should understand what those are and make sure there are no subtle issues with the workflow archival.

**Additional context and error message**
[1]
```
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00399__v1_T_201217_220835_930
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00420__v1_T_201217_223216_3726
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00427__v1_T_201217_215709_6988
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00453__v1_T_201217_224624_965
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00458__v1_T_201217_214406_3495
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00475__v1_T_201217_225614_2162
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00488__v1_T_201217_222701_445
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00056__v1_T_201210_105536_8824
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00058__v1_T_201210_110637_9543
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00065__v1_T_201221_155242_4539
cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00037__v1_T_201207_122800_6254
cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00057__v1_T_201206_222426_2907
```

**Comment by amaltaro** [comment]
@todor-ivanov Todor, do you think you could have a look at these today/tomorrow?

**Comment by todor-ivanov** [comment]
@amaltaro looking into it

**Comment by todor-ivanov** [comment]
All seems to be working normally as it comes to MSRulecleaner. There are some unsatisfied `Tape` rules for those workflows:

```
2022-04-15 07:32:28,229:DEBUG:MSRuleCleaner: Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395
2022-04-15 07:32:28,317:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "GET /rules/8d11f0c3bec04b2ca11e81ec3fc63bef HTTP/1.1" 200 941
2022-04-15 07:32:28,318:INFO:MSRuleCleaner: Tape rule: 8d11f0c3bec04b2ca11e81ec3fc63bef in non final state: REPLICATING for workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395
2022-04-15 07:32:28,335:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "GET /rules/f2cc29c94fc84f17a6e5364d705b624b HTTP/1.1" 200 935
2022-04-15 07:32:28,336:INFO:MSRuleCleaner: Tape rule: f2cc29c94fc84f17a6e5364d705b624b in non final state: REPLICATING for workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395
2022-04-15 07:32:28,336:INFO:MSRuleCleaner: Skipping workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395 - tape transfers are not yet completed. Will retry again in the next cycle.
2022-04-15 07:32:28,337:DEBUG:MSRuleCleaner: TargetStatus: normal-archived
```

And here follows the list of `Tape` rules per workflow and relative rule status:

```
Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395     
Tape rule: 8d11f0c3bec04b2ca11e81ec3fc63bef in non final state: REPLICATING
Tape rule: f2cc29c94fc84f17a6e5364d705b624b in non final state: REPLICATING

Dispatching workflow: cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00057__v1_T_201206_222426_2907     
Tape rule: 29d06f2e58ae4fc09d49cd1069beb8d9 in non final state: SUSPENDED
Tape rule: e9d31cf740d540acbef623c578019ab2 in final state: OK

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00399__v1_T_201217_220835_930     
Tape rule: 8dfbc8d69ba94901b64ede47cee9ba48 in non final state: REPLICATING
Tape rule: 5d7a7edd55074702b69a3a20a58170b8 in non final state: REPLICATING

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00453__v1_T_201217_224624_965     
Tape rule: b65edfbb975b4e77a710f7642fbeb08e in final state: OK
Tape rule: 72af3b7029fa4fa59c74e60d50fe7b43 in non final state: REPLICATING

Dispatching workflow: cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00037__v1_T_201207_122800_6254     
Tape rule: dc007d76230f44ae9b9cc40a6743a200 in non final state: SUSPENDED
Tape rule: 9f7f90b183cf42a881be092c6bdd5ee1 in final state: OK

Dispatching workflow: cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00058__v1_T_201210_110637_9543     
Tape rule: 3bd18620f1394587aa951d72d03edaf3 in non final state: REPLICATING
Tape rule: c202de280dfb45fd8c57defe111814f0 in non final state: REPLICATING

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00475__v1_T_201217_225614_2162     
Tape rule: 6316c61ff9bf48549c09af8feac2c9ba in non final state: REPLICATING
Tape rule: d55a5af164c541e0a9169f92b7388e2e in non final state: REPLICATING

Dispatching workflow: cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00065__v1_T_201221_155242_4539     
Tape rule: 81a7da392bcf44b89a1f59a1e53ee92a in final state: OK
Tape rule: 346b711ca11e49898a862f3be76be7f8 in non final state: REPLICATING

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00488__v1_T_201217_222701_445     
Tape rule: d3f9a183a85741418a1d2c154ad0a650 in final state: OK
Tape rule: ae862ebc42814ca9a82d5919405de851 in non final state: SUSPENDED

Dispatching workflow: cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00056__v1_T_201210_105536_8824     
Tape rule: a7a79ce9bb774fb19a10b5f2a57afcc6 in non final state: REPLICATING
Tape rule: c84f26ee738642e1bba263c037e78b2b in non final state: REPLICATING

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00458__v1_T_201217_214406_3495     
Tape rule: d66ec20afcf54e66a738e686f31d65ba in final state: OK
Tape rule: 4fd0aa002f5147f68f229573dacb75b0 in non final state: SUSPENDED

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00427__v1_T_201217_215709_6988     
Tape rule: ce8bf19f432642d2ba847cacb49bfcbf in non final state: REPLICATING
Tape rule: c62e8a6f69654fa18acef9452a0cf662 in non final state: REPLICATING

Dispatching workflow: cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00420__v1_T_201217_223216_3726     
Tape rule: 6f92a3aac858447fb0fd03c036633da0 in final state: OK
Tape rule: 9a7c536f50184e8e8d2f0330ad62cbb1 in non final state: SUSPENDED
```

I think this should be forwarded to Data Management to cross check why those rules are stuck for so long.

FYI @amaltaro

**Comment by amaltaro** [comment]
Yes, please do so.
We should try to understand if there is any process in place to avoid it in the future as well. Having our workflows stuck for a year or more because a rucio rule isn't satisfied isn't reasonable IMO. We might even have a grace period in our component - like 1 month - and archive workflows going beyond that. But in the end, DM team needs to be aware of such stuck rules.

**Comment by todor-ivanov** [comment]
May be an alarm for such workflows including also the rules in question is a feasible approach in this case.

**Comment by FernandoGarzon** [comment]
Agreed. We have a dashboard in the queue that needs to be deployed, that would give us stuck rules for more than x period of time. I'll see to it getting ready. Regarding these rules, I have boosted them and restarted their transfer requests as a quick way to get things moving again. I'll check them again next week and try to get them in OK state.

**Comment by todor-ivanov** [comment]
Thank you @FernandoGarzon

**Comment by FernandoGarzon** [comment]
Quick rule's state update:

State:                      REPLICATING
State:                      REPLICATING
State:                      STUCK
State:                      OK
State:                      OK
State:                      REPLICATING
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      STUCK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      STUCK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK
State:                      OK

Checking on the few stuck rules. 

F.

**Comment by todor-ivanov** [comment]
Thanks a lot @FernandoGarzon it seems a good success rate for those rules . I do see two of them `STUCK` though. How should we proceed ? Could we somehow rescue them?

**Comment by FernandoGarzon** [comment]
All rules are ok now. Will get the dashboard done to avoid this happening again.

Cheers.

**Comment by amaltaro** [comment]
Just a follow up on this issue. I'd suggest to implement a prometheus alert in the microservice itself as follows:
* workflows stuck for one month (configurable), should trigger an email/slack notification
* notification expiration should be set to 24h, such that we only get one notification per workflow for each day (this is likely something that won't be able to be resolved within a couple of hours).
* should we add someone from the DM team to the list of recipients?

**Comment by todor-ivanov** [comment]
as it comes to the set of workflows @amaltaro lists in the issue description they are all normal-archived already:
```
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00399__v1_T_201217_220835_930:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00417__v1_T_201217_222725_8395:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00420__v1_T_201217_223216_3726:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00427__v1_T_201217_215709_6988:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00453__v1_T_201217_224624_965:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00458__v1_T_201217_214406_3495:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00475__v1_T_201217_225614_2162:normal-archived
cmsunified_task_B2G-RunIISummer20UL17wmLHEGEN-00488__v1_T_201217_222701_445:normal-archived
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00056__v1_T_201210_105536_8824:normal-archived
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00058__v1_T_201210_110637_9543:normal-archived
cmsunified_task_TOP-RunIISummer20UL17wmLHEGEN-00065__v1_T_201221_155242_4539:normal-archived
cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00037__v1_T_201207_122800_6254:normal-archived
cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00057__v1_T_201206_222426_2907:normal-archived
```
I am checking what needs to be done in regards to those alarms/notifications.

**Comment by todor-ivanov** [comment]
hi @amaltaro @vkuznet 
And here is the new issue: https://github.com/dmwm/WMCore/issues/11396
