### ISSUE TITLE
Remove legacy concept of open blocks from DBS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11120]
**Impact of the new feature**
WMCore in general (and likely T0 and CRAB)

**Is your feature request related to a problem? Please describe.**
Back in the DBS2 era, we used to have open blocks available in the DBS Server and files were added to them until a given point (until that block was closed). With the DBS3 service, that concept was removed and we can only inject closed blocks in the server.

It turns out that this feature is still supported in WMCore, which makes the Global WorkQueue logic unnecessarily complex. 

**Describe the solution you'd like**
I suggest we remove this functionality from WMCore, which affects (at least):
* DBS3Reader, which should no longer check for open blocks and we should remove the `open_for_writing|OpenForWriting` attributes
* (Global) WorkQueue, removing the same OpenForWriting logic; which affects `OpenForNewData`

Regarding `OpenRunningTimeout`, it's being repurposed with this GH issue: https://github.com/dmwm/WMCore/issues/11048, such that we use this attribute to decide whether we need to look up for new blocks in the input dataset (instead of looking for new files in an open block).

**Describe alternatives you've considered**
This change is not really necessary, but code becomes cleaner and more maintainable without it.

**Additional context**
For now, the 3rd and 4th commit in this PR https://github.com/dmwm/WMCore/pull/11119 contains most of the necessary changes

**Comment by belforte** [comment]
thanks Alan, I will look at impact on CRAB. None is expected at first sight :-)
