### ISSUE TITLE
New rule for RelVal EOS disk space

### ISSUE THREAD

**Issue by kskovpen** [dmwm/WMCore#11124]
We (PPD) would like to request an implementation of a new rule for EOS area for RelVals workflow outputs. The current implementation corresponds to the preservation of all RelVals at EOS for the duration of one year. We would like to ask to update this rule to keep RelVals produced in CMSSW pre-releases for the duration of 3 months, while the full release outputs can be kept for one year, as is done now. Thanks a lot in advance.

**Comment by haozturk** [comment]
Thanks @kskovpen Can you let us know how we can discriminate pre-releases from full releases?

**Comment by kskovpen** [comment]
Thanks Hasan. In case of pre releases, there is a "pre" postfix, such as in "CMSSW_12_4_0_pre2". The full releases are e.g. "CMSSW_12_3_0", "CMSSW_12_3_1", etc.

**Comment by haozturk** [comment]
Thanks Kirill, let's see what Alan and Todor think about it. The current lifetime is already configurable: https://github.com/dmwm/deployment/blob/master/reqmgr2ms/config-output.py#L27 but there is no pre-release, full-release distinction in the existing code.

**Comment by amaltaro** [comment]
AFAICT, RelVal output dataset always have the same convention, where:
```
/PrimaryDataset/AcquisitionEra-ProcessingString-vX/Datatier
```

where `AcquisitionEra` is ALWAYS the CMSSW release used to produce that dataset. If that's true and will likely remain true for the years to come, then I think we could have a check before making the rucio rule, such that we know whether it's a pre-release or not (like a final, patch, special release).

The service configuration could be changed from a single integer to a dictionary as well, e.g.:
```
RULE_LIFETIME_RELVAL = {"pre": 3 * 30 * 24 * 60 * 60, "default": 12 * 30 * 24 * 60 * 60 }
```
with 3 months for pre-releases, and anything else getting a 12 months expiration. What do you think?

**Comment by haozturk** [comment]
whether `AcquisitionEra` is ALWAYS the CMSSW release or not requires confirmation from @kskovpen. Other than that, your dictionary solution looks good to me.

**Comment by kskovpen** [comment]
Thanks @haozturk and @amaltaro - I confirm that this is the case.

**Comment by kskovpen** [comment]
Hello, sorry to spam, just to touch the base - is the updated rule already in place?

**Comment by amaltaro** [comment]
@kskovpen Hi Kirill, unless it's critical for this quarter, it would have to follow our quarterly activities plan, meaning it would be addressed only in the next quarter. However, this seems to be a straight forward change and we can likely make the necessary changes to get it deployed in production in the next week.

**Comment by kskovpen** [comment]
Thanks @amaltaro !
