### ISSUE TITLE
Repurpose Tier0 workflow output data placement to deal with rucio rules.

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/WMCore#11145]
**Impact of the bug**
Tier-0 Agent

**Describe the bug**
Related to #9639. Tier-0 wants to modify/eliminate some of the workflow output data placement due that the information that needs to be used for the rucio rules is not meaningful

The current arguments for the 3 different types of wfs that Tier0 assign with `wmSpec.setSubscriptionInformation(**subscription)` are at follows:
```
Repack wfs
{
 'custodialSites': ['T0_CH_CERN_MSS', 'T1_US_FNAL_MSS'], 
 'custodialSubType': 'Replica', 
 'custodialGroup': 'DataOps', 
 'nonCustodialSites': ['T1_US_FNAL_Disk'],
 'nonCustodialSubType': 'Replica',
 'nonCustodialGroup': 'AnalysisOps', 
 'autoApproveSites': ['T0_CH_CERN_MSS', 'T1_US_FNAL_Disk'], 
 'priority': 'high', 
 'primaryDataset': 'AlCaPhiSym', 
 'deleteFromSource': True, 
 'dataTier': 'RAW', 
 'datasetLifetime': 7776000
}
Express wfs
{
 'custodialSites': [], 
 'custodialSubType': 'Replica', 
 'custodialGroup': 'DataOps', 
 'nonCustodialSites': ['T2_CH_CERN'], 
 'nonCustodialSubType': 'Replica', 
 'nonCustodialGroup': 'express', 
 'autoApproveSites': ['T2_CH_CERN'], 
 'priority': 'high', 
 'primaryDataset': 'StreamExpress', 
 'deleteFromSource': True, 
 'datasetLifetime': 7776000
}
Prompt wfs
{
 'custodialSites': ['T1_US_FNAL_MSS'], 
 'custodialSubType': 'Replica', 
 'custodialGroup': 'DataOps', 
 'nonCustodialSites': ['T1_US_FNAL_Disk'], 
 'nonCustodialSubType': 'Replica', 
 'nonCustodialGroup': 'AnalysisOps', 
 'autoApproveSites': ['T1_US_FNAL_Disk'], 
 'priority': 'high', 
 'primaryDataset': 'ZeroBias4', 
 'useSkim': True, 
 'isSkim': False, 
 'deleteFromSource': True, 
 'dataTier': 'MINIAOD', 
 'datasetLifetime': 7776000
}
``` 
Cross-checking with the arguments given to the dataset-level rules and block-level rules:
```
Dataset-level rules
{
 'ask_approval': False, 
 'activity': 'T0 Export', 
 'account': 'tier0_replay', 
 'grouping': 'ALL', 
 'comment': 'T0 WMAgent automatic container rule', 
 'meta': '{"agentHost": "vocms015.cern.ch", "userAgent": "WMAgent"}', 
 'lifetime': 172800, 
 'priority': 4
}
Block-level rules
{
 'activity': 'Production Output', 
 'account': 'tier0_replay', 
 'grouping': 'DATASET', 
 'comment': 'WMAgent automatic container rule', 
 'ignore_availability': True, 
 'meta': '{"agentHost": "vocms015.cern.ch", "userAgent": "WMAgent"}', 
 'lifetime': 172800
}
```
The proposal will be to modify the output data placement and the database schema as follows:
- Change `priority` from `string` to `integer` where the default value will be 3. (This is the default value when rucio rules are created). T0 will update this value to 4 when the wfs parameters are created. This changes will take place within the T0 code.
-  Add the `activity` column. This will be a string and the possible values during the wf output data placement will be the [activity shares](https://fts3-cms.cern.ch:8446/config/activity_shares)
- Add `ask_approval` column. The default will be `False` and will change to `True` if the rse needs approval by checking `rucio.requiresApproval(rseName)`
- Use `custodialSites` and `nonCustodialSites ` as a meta data information for dataset-level rules. This will give some information for operators in case they need to check where a full dataset replica should be present.
- Delete `custodialSubType`, `custodialGroup`, `nonCustodialSubType` , `autoApproveSites` and `nonCustodialGroup`

**How to reproduce it**

**Expected behavior**

**Additional context and error message**
Some arguments like `primaryDataset` and `deleteFromSource` not quite sure how those arguments works during the PhEDEx era and don't know how this information could be useful during the placement of dataset-level rules.

**Comment by amaltaro** [comment]
@jhonatanamado Jhonatan, thanks for providing all these details. 

> Change priority from string to integer where the default value will be 3. (This is the default value when rucio rules are created). T0 will update this value to 4 when the wfs parameters are created. This changes will take place within the T0 code.

Yes, I think it makes sense. However, the moment we make this modification, our data in CouchDB will no longer follow a single shcema. Meaning, new workflows will have `SubscriptionPriority` with an integer value, while past workflows will have a string. This is defined here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py
I have two suggestions/alternatives to this:
1. Keep the same schame for `SubscriptionPriority`, but in the agent map "low to 2", "medium to 3", "high to 4", where T0 would use "high" and central production either in "low" or "medium".
2. completely get rid of this attribute and instead define this priority in the `RucioInjector` component configuration.

> Add the activity column. This will be a string and the possible values during the wf output data placement will be the [activity shares](https://fts3-cms.cern.ch:8446/config/activity_shares)

I cannot access this link. But given that we have a small set of values and they are already pretty well defined in the RucioInjector component, I would not create a new column in the database neither a new workflow spec parameter.

> Add ask_approval column. The default will be False and will change to True if the rse needs approval by checking rucio.requiresApproval(rseName)

If we always create WMAgent rules without the `ask_approval` (meaning ask_approval=False), then I think I would not implement this as well. AFAIR, we only set `ask_approval=true` when the RSE (only Tape endpoints?) enforce it.

> Use custodialSites and nonCustodialSites as a meta data information for dataset-level rules. This will give some information for operators in case they need to check where a full dataset replica should be present.

I am not sure I understand this comment. In the PhEDEx era, `custodialSites` had a list of Tape endpoints while `nonCustodialSites` had a list of Disk endpoints. If we want to keep compatibility with what is already in the system, we keep using it the same way. However, in the agent side, I think we could easily merge these two lists altogether and have a single list of RSEs where we should create a container-level rule for.

> Delete custodialSubType, custodialGroup, nonCustodialSubType , autoApproveSites and nonCustodialGroup

Agreed! However, the `autoApproveSites` could be used as the `ask_approval` flag. I still think we shouldn't keep any of these around.

Now that I am done with my comments, I think it will be extremely hard to keep workflow description compatibility between this new model and what we used to have for PhEDEx.
We might want to have a broader discussion on this topic as well, possibly looping Eric V. in.

**Comment by jhonatanamado** [comment]
Thanks Alan and Eric for the comments
So the final proposal will be as follows:

- Completely drop `custodialSubType , custodialGroup, nonCustodialSubType, nonCustodialGroup, autoApproveSites `
- Keep `custodialSites` and `nonCustodialSites ` and use it as additional information for container subscriptions
- Map `SubscriptionPriority` in the agent from string to integer 

With that proposal the `wmSpec.setSubscriptionInformation(**subscription)` will be as follows:
```
{
 'custodialSites': ['T0_CH_CERN_MSS', 'T1_US_FNAL_MSS'], 
 'nonCustodialSites': ['T1_US_FNAL_Disk'],
 'priority': 'high', 
 'primaryDataset': 'AlCaPhiSym', 
 'deleteFromSource': True, 
 'dataTier': 'RAW', 
 'datasetLifetime': 7776000
}
```
And the container subscriptions will be
```
{
 'ask_approval': False | True, #depends on rucio.requiresApproval
 'activity': 'T0 Export' | 'T0 Tape' | 'Production Output ', 
 'account': 'tier0_account', 
 'grouping': 'ALL' | DATASET, 
 'comment': 'T0 WMAgent automatic container rule', 
 'meta': '{"agentHost": "vocms015.cern.ch", "userAgent": "WMAgent", "containerReplica":['T0_CH_CERN_MSS', 'T1_US_FNAL_MSS', 'T1_US_FNAL_Disk']}', 
 'lifetime': 172800, 
 'priority': 4 #following by the mapping in the agent
}
```
One last comment Alan,  During the PhEDEx era, what was `deleteFromSource` attribute used for?

**Comment by amaltaro** [comment]
Thanks for this summary, Jhonatan. It looks good to me.

Regarding the `deleteFromSource`, it's actually defined in the workflow spec files (and it's a boolean):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1082

This isn't going to be a small change, so when you start working on this, I'd suggest to split work in different commits, something like:
1) changes to WMSpec
2) changes to the DAOs and RucioInjector
3) unit tests

We will likely have to document these changes in a WMCore wiki as well, but that can come later when we are almost done with everything.

**Comment by amaltaro** [comment]
After our discussion and implementation, here is my understanding of the changes applied to the system:
* Delete: custodialSubType, custodialGroup, nonCustodialSubType , autoApproveSites and nonCustodialGroup
* Priority remains the same (string for low/medium/high) as done for PhEDEx, but the agent will map those to integer values for Rucio.
* CustodialSites and nonCustodialSites are still used for output data placement done by the agent, where the former is used for Tape-based placement
  and the later is overriden by a general "type=DISK" placement.
