### ISSUE TITLE
JINR Tape output rules in need of redistribution

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11156]
**Impact of the bug**
MSOutput (in partner with the P&R and DM team)

**Describe the bug**
The DM team reported that there are many output data placement rules - made by MSOutput - for JINR_Tape RSE, which have been stuck for many weeks (or even months). This has, at least, two negative consequences:
* workflows cannot get archived (they will remain in announced state until those Tape rules have been satisfied)
* and, there is no archival copy of those datasets, increasing chances of data loss

**How to reproduce it**
None

**Expected behavior**
What we discussed over slack (P&R, site-info channel) is the following:
1. the DM team has identified all the problematic containers
2. the DM team (Fernando?) will create new Tape rules for all those containers
3. the DM team will hand a list/json of container name and the new rule id over to the WMCore team
4. the WMCore team will find which workflows (only the original/first workflow) created those containers
5. the WMCore team will fetch those workflows MSOutput records, update the relevant Tape container rule by swapping it by the new rule id provided by the DM team, and finally updating that record in MongoDB

We better keep that list of workflow/containers/rule ids persisted somewhere, such that we can confirm that those workflows start moving to archived, as Tape rules started getting satisfied.

We might take the opportunity and provide a script to fetch and update those mongodb records. No need to make that too generic, but really more like a baseline for future similar actions.

**Additional context and error message**
None

**Comment by klannon** [comment]
I know that @todor-ivanov is following up on this but don't forget to update the issue here to say what specifically we're waiting on before we can move this forward.

**Comment by todor-ivanov** [comment]
Thanks @klannon  I am following this with Fernando and Data Management Team now.

**Comment by todor-ivanov** [comment]
I am uploading here the list of rules  as provided by DataManagement: 
[JINR_Tape_Relocation_Rules.txt](https://github.com/dmwm/WMCore/files/8976230/JINR_Tape_Relocation_Rules.txt)

**Comment by todor-ivanov** [comment]
And [here](https://github.com/dmwm/WMCore/pull/11221#issuecomment-1192377424) I link the comment from the PR pointing to the operational logs.

**Comment by amaltaro** [comment]
Closing this issue out as well. Further information at: https://github.com/dmwm/WMCore/pull/11221
Thanks Todor.
