### ISSUE TITLE
Validate MongoDB as a service on cmsweb-test clusters

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#11210]
**Impact of the new feature**
Allows us to run services that depend on MongoDB in the cmsweb-test k8s clusters

**Is your feature request related to a problem? Please describe.**
We need to stop using VM based development since some services no longer work in that setup, see https://github.com/dmwm/WMCore/issues/11085

**Describe the solution you'd like**
Deploy services that rely on MongoDB in cmsweb-test k8s clusters and verify that they are working properly.

**Describe alternatives you've considered**
None

**Additional context**
Prereq of #11085

**Comment by amaltaro** [comment]
@goughes @todor-ivanov I have the impression this is somehow a work in progress. If so, can you please update this ticket accordingly? Thanks

**Comment by todor-ivanov** [comment]
Hi @amaltaro, this issue needs to wait for this one: https://github.com/dmwm/WMCore/pull/11280 to be merged before it could be worked on.
