### ISSUE TITLE
Duplicate monitoring data from HeartBeatMonitor thread at RequestManager

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11252]
**Impact of the bug**
Monitoring system

**Describe the bug**
This ticket is a followup on https://its.cern.ch/jira/browse/CMSMONIT-490
Due to some change in the system, which happened suddenly at around 00:00 o'clock on 14.08.2022, we started to observe increased rate of sending monitoring data through StompAMQ. [1],  causing incorrect monitoring data when values are aggregated by timestamp. The document creator is a single one and it is `ReqMgr2`, which is a central service, even though the document's topic is `/topic/cms.jobmon.wmagent` *. This excludes the possibility of duplicate data originating from multiple producers. We are sure the thread responsible for sending the `ReqMgr2` monitoring data is `HeartBeatMonitor` and it is running inside the `reqmgr2_tasks` pod at K8 [2]. 

After a close look at the log messages timestamps  at [2] one sees that they are scrambled and unordered, even more they are mixed somehow by at least a day difference.  

 
[*] The single topic for both WMCore Central services and WMAgents is done, I believe, in order to have the all our monitoring under the same section. 

[1]
https://monit-kibana.cern.ch/kibana/goto/8a3130876e36ef441c6ddff4c8575a78

[2]
```
2022-08-17 00:01:37,826:INFO:HeartbeatMonitorBase:Checking Thread status...
2022-08-17 00:01:37,939:INFO:HeartbeatMonitor:Collecting ReqMgr2 statistics...
2022-08-17 00:01:39,997:INFO:HeartbeatMonitor:988 docs created to post to MonIT
2022-08-16 22:01:40,040:INFO:StompAMQ7:host and ports: [('cms-mb.cern.ch', 61313)]
2022-08-16 22:01:40,043:INFO:StompAMQ7:resolver: [('188.184.28.133', 61313), ('137.138.122.170', 61313), ('137.138.122.50', 61313), ('137.138.31.103', 61313), ('137.138.152.151', 61313), ('188.184.94.87', 61313)]
2022-08-16 22:01:40,111:INFO:HeartbeatMonitorBase:988 out of 988 documents successfully sent to AMQ
2022-08-16 22:01:40,297:INFO:HeartbeatMonitorBase:Uploaded to WMStats...
2022-08-17 00:03:35,543:INFO:CherryPyPeriodicTask:Setting CherryPy periodic task with the following config:
heartbeatMonitor.post_to_amq = True
heartbeatMonitor.wmstatsSvc_url = 'https://cmsweb.cern.ch/wmstatsserver'
heartbeatMonitor.object = 'WMCore.ReqMgr.CherryPyThreads.HeartbeatMonitor.HeartbeatMonitor'
heartbeatMonitor.log_reporter = 'reqmgr2'
heartbeatMonitor.heartbeatCheckDuration = 600
heartbeatMonitor.topic_amq = '/topic/cms.jobmon.wmagent'
heartbeatMonitor.log_file = '/data/srv/logs/reqmgr2/heartbeatMonitor-reqmgr2-tasks-749465758c-x45np-20220812.log'
...
```

**How to reproduce it**

**Expected behavior**

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by amaltaro** [comment]
This issue can now be closed as well. Further details have been provided in the last comments of this GH issue:
https://github.com/dmwm/WMCore/issues/11253

In short, the `reqmgr2-task` service was getting killed for exceeding memory consumption and the cherrypy threads were restarting all the time, thus uploading documents to AMQ much more often as well.

Thank you for your initial investigations, Todor.
