### ISSUE TITLE
Failed Parentage rosolution and workflows not progressing from closed-out to announced. 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11253]
**Impact of the bug**
Reqmgr

**Describe the bug**
This issue is a follow up on https://its.cern.ch/jira/browse/CMSCOMPPR-27653
This issue is closely related to https://github.com/dmwm/WMCore/issues/11252 

All our workflows are moved from `closed-out` status to `announced`  by Unified. One of the flags in the workflow description that is checked during this transition is `ParentageResolved = Trrue`. This flag is set either by default in case no resolution is needed or later by ReqMgr2. The CherryPy thread which  is doing the resolution is `StepChainParentageFixTask`, running on the `reqmgr-task` pod at K8. 

Looking into one such workflow: [cmsunified_task_HIG-RunIISummer20UL17wmLHEGEN-03833__v1_T_220608_152814_5551](https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_HIG-RunIISummer20UL17wmLHEGEN-03833__v1_T_220608_152814_5551)  we find the following related datasets from two different steps: 
```
    "Step5": {
      "ParentDset": null,
      "ChildDsets": [
        "/GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM"
      ]
    },
    "Step6": {
      "ParentDset": "/GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM",
      "ChildDsets": [
        "/GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v3/MINIAODSIM"
      ]
    }
```

Looking into the logs we see that parentage resolution is tried for the parent but not for the child dataset: 

```
022-08-19T16:32:17.900Z [INFO] StepChainParentageFixTask.py:72 Resolving parentage for dataset: /GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM 
2022-08-19T16:32:17.907Z [INFO] DBS3Reader.py:938 Parent datasets for /GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM are: [] 
2022-08-19T16:32:17.908Z [WARNING] DBS3Reader.py:943 No parent dataset found for child dataset /GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM 
2022-08-19T16:32:17.908Z [INFO] StepChainParentageFixTask.py:87 Parentage for '/GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM' successfully updated. Proc
essed 437 out of 1567 datasets. 
2022-08-19T16:32:17.908Z [INFO] StepChainParentageFixTask.py:90     spent 0.0078012943267822266 secs on this dataset: /GluGluToRadionToHHTo2G2WTo2G4Q_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM 

```

 
This leads to a big increase of workflows in status `closed-out`. The trend starts simultaneously with the one from issue https://github.com/dmwm/WMCore/issues/11252. See the attached image bellow:

![increased-closed-out](https://user-images.githubusercontent.com/8182807/186189772-96a39c2f-9694-4d29-bc31-0d7ca88c08af.png) 

Upon further investigation we've noticed the the thread actually never managed to complete during a single pooling cycle and also  logs that  we used to have separate have been merged into the general log.

before:
```
parentageFixTask-reqmgr2-tasks-749465758c-x45np-20220812.log
statusChangeTasks-reqmgr2-tasks-749465758c-x45np-20220812.log
```

after
```
-rw-r--r--. 1 1000 1000 302193121 Aug 19 01:59 reqmgr2-20220818-reqmgr2-tasks-749465758c-x45np.log
-rw-r--r--. 1 1000 1000 469074023 Aug 20 01:59 reqmgr2-20220819-reqmgr2-tasks-749465758c-x45np.log
-rw-r--r--. 1 1000 1000 572314327 Aug 21 01:59 reqmgr2-20220820-reqmgr2-tasks-749465758c-x45np.log
-rw-r--r--. 1 1000 1000 619256094 Aug 22 01:59 reqmgr2-20220821-reqmgr2-tasks-749465758c-x45np.log
-rw-r--r--. 1 1000 1000 455811482 Aug 22 15:50 reqmgr2-20220822-reqmgr2-tasks-749465758c-x45np.log
``` 

**How to reproduce it**

**Expected behavior**

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by amaltaro** [comment]
I feel like we have a major problem with the ReqMgr2 CherryPy threads service (called reqmgr2-tasks in k8s). We have problems affecting many of those threads:
* this one, concerning StepChain parentage fix
* the heartbeat monitoring and AMQ, see https://github.com/dmwm/WMCore/issues/11252
* and Hasan also reported two workflows completed with no output stats, apparently the workflows were completed while jobs were still running

Besides having messed up logs for those services (since ~Aug 13th), I had the impression that a new cherrypy thread gets started every few minutes, still unclear if it's the same cherrypy thread or a new one getting spawned.

**Comment by vkuznet** [comment]
@amaltaro , I already pointed @todor-ivanov to plots of reqmgr2 RAM usage, see at [plot](https://monit-grafana.cern.ch/d/cmsweb_reqmgr/reqmgr2?orgId=11&refresh=1m&from=now-14d&to=now&viewPanel=28). It shows both Reqmgr2 and ReqMgr2-tasks pods (which you can select by clicking on the pod name). Both show spikes up to 3GB of RAM which is resource limit in k8s and can cause pod's restart, Bottom line, the reqmgr2 had always such behavior, see from a plot but reqmgr2-tasks start getting it from around Aug 14th. I still doubt it is an issue with infrastructure. If we had issue with cherryypy thread then we will not have spikes in reqmgr2 before Aug 14th which is the case of reqmgr2-tasks. Have a look at [plot](https://monit-grafana.cern.ch/d/cmsweb_reqmgr/reqmgr2?orgId=11&refresh=1m&from=now-14d&to=now&viewPanel=28) to select your pods and dates.

**Comment by amaltaro** [comment]
I get a 500 Internal Server Error whenever I try to access the dashboard you shared. Is it "ReqMgr2" or the "CMSWEB timber k8s" dashboard?

If it was about resources, then I would expect the POD/replica to actually get killed and a new one started. This is not the behavior we see from the logs, the same POD (log) keeps reporting that it started a cherrypy thread.

**Comment by vkuznet** [comment]
plot is working fine for me, you can access it by visiting CMS monitoring dashboard, https://monit-grafana.cern.ch/d/000000530/cms-monitoring-project?orgId=11, then search for ReqMgr2 and view Memory usage by (node, pod) from kube-eagle plot.

**Comment by vkuznet** [comment]
from one of the [log](/cephfs/product/dmwm-logs/reqmgr2-20220826-reqmgr2-tasks-9b66dfb99-57r9d.log) what is the following exit code means:
```
WATCHDOG: server exited with exit code signal 9..
```

**Comment by amaltaro** [comment]
Which explains why I see cherrypy threads getting restarted all the time.
Imran joined a discussion over MM "Web Serv & Security" channel.

**Comment by vkuznet** [comment]
It is interesting to see now that after we traced down and changed RAM threshold that reqmgr2-tasks spike up to 4GB and requires 5mins to stay at 3-4GB level to process the data, then it release it. I'm attaching RAM plots before and after adjustment:

- before the pod limit adjustment (which cause pod restarts due to oom kill):
![Screen Shot 2022-08-26 at Aug 26, 2 11 45 PM](https://user-images.githubusercontent.com/125138/186985681-67a65f16-25ba-461a-a3fc-4c99980616ac.png)

- after adjustment
![Screen Shot 2022-08-26 at Aug 26, 4 28 32 PM](https://user-images.githubusercontent.com/125138/186985820-46b9aea4-cd0e-4691-9a62-2027585fbfe5.png)

**Comment by amaltaro** [comment]
Thanks Valentin. We might evaluate to actually separate those cherrypy threads in their own k8s service in the future.

Things are moving forward and I confirm that the StepChain parentage CP thread is back operational, here is a summary of its last cycle:
```
2022-08-26T20:23:08.721Z [INFO] StepChainParentageFixTask.py:102 A total of 1788 requests have been processed, where 10 will have to be retried in the next cycle. 
```

which started triggering workflow status transition from `closed-out` to `announced`.

**Comment by amaltaro** [comment]
I have created an extra issue to follow up on the WMCore resources requirements (to be worked on in the coming days):
https://github.com/dmwm/WMCore/issues/11259

and bumped up this issue related to k8s livenessprobe:
https://github.com/dmwm/WMCore/issues/10223

I think we can now close this issue out. Thanks to everyone that helped to investigate it.
Feel free to reopen it if I missed anything important still to be followed up in here.
