### ISSUE TITLE
Review and adjust liveness probe APIs for all WMCore services

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11262]
**Impact of the new feature**
To improve experience on k8s infrastructure we need to review liveness probe APIs for all WMCore services.

**Is your feature request related to a problem? Please describe.**
The liveness probe API is used by k8s infrastructure to decide the status of the service. All k8s manifest files we use have liveness probe API. By default we use `/data/info` API of WMCore services which is provided by WMCore REST framework. In reality each service should provide its own API to do this task.

**Describe the solution you'd like**
The liveness probe API should provide HTTP access point which should answer the question if service is doing ok or not. This API should return 200 OK HTTP response and internally perform any necessary action required to answer service liveness question. For instance, if (data|ms)-service talks to a database the liveness prove API may query DB to ensure that DB is accessible and moreover returns proper data.

For instance, in dbs2go the liveness probe talks to DBS DB and fetches data from smallest table, e.g. data-tiers. Then it checks if `RAW` data-tier is present in result. Finally it can either return 200 OK or 500 InternalServiceError HTTP code back to the caller.

In k8s the liveness probe API usually called `/healthz` and I suggest that we follow this convention for all services.

**Describe alternatives you've considered**
We can still use `/data/info` WMCore API but it may not be optimal.

**Additional context**
Related issues: https://github.com/dmwm/WMCore/issues/10223 , https://github.com/dmwm/WMCore/issues/11259

**Comment by amaltaro** [comment]
@vkuznet I don't understand why you created this issue if we were already discussing this in exactly the issue meant to track livenessprobe setup, thus: https://github.com/dmwm/WMCore/issues/10223

I am closing this one out as a dup of https://github.com/dmwm/WMCore/issues/10223
