### ISSUE TITLE
Missing stats w/ workflows which were successfully recovered by ACDCs

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11274]
**Impact of the bug**
Some production workflows

**Describe the bug**
We see some workflows which had failures originally. Later, we ACDC'd these requests and ACDCs went successful. However, we still see missing stats.

It's also possible that ACDCs don't cover every failed job in the original workflow. If it's the case, I cannot see how that can be possible.

**How to reproduce it**
Check the following requests:

1. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL16wmLHEGENAPV-02777 
2. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL16wmLHEGENAPV-02779 ​​
3. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL18wmLHEGEN-00211 
4. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL18wmLHEGEN-03972 
​5. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer20UL16wmLHEGEN-00654 

**Expected behavior**
We should have 100% output if all the jobs of a request is successful .

**Additional context and error message**
None

**Comment by todor-ivanov** [comment]
Looking into the agent's WorkQueue for one of those ACDCs:
```
2022-08-21 15:27:48,976:140171263747840:INFO:WorkQueue:Splitting /cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214623_6699/HIG-RunIISummer20UL16wmLHEGENAPV-02777_0 with policy name ResubmitBlock and policy params {'name': 'ResubmitBlock', 'args': {}}
2022-08-21 15:27:50,090:140171263747840:INFO:Rucio:Container: /Neutrino_E-10_gun/RunIISummer20ULPrePremix-UL16_106X_mcRun2_asymptotic_v13-v1/PREMIX with container-based location at: {'T2_CH_CERN', 'T1_US_FNAL_Disk'}
2022-08-21 15:27:51,170:140171263747840:INFO:WorkQueue:Work splitting completed with 1 units, 0 rejectedWork and 0 badWork
2022-08-21 15:27:51,170:140171263747840:INFO:WorkQueue:Queuing element c224f009a1cd4e3e3ea8e788d7f86b87 for /cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214623_6699/HIG-RunIISummer20UL16wmLHEGENAPV-02777_0 with policy ResubmitBlock, with 1 job(s) and 4 lumis on /acdc/cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214623_6699/:pdmvserv_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220511_181015_3806:HIG-RunIISummer20UL16wmLHEGENAPV-02777_0/0/1
```  
It basically gives us the id of one and only one Workqueu element: c224f009a1cd4e3e3ea8e788d7f86b87 and this is basically only one  block re-submission contianing only 4 lumis. Which went through I think ok as well. And we have a total of 2 ACDCs for this workflow. Similarly for the second one:
```
2022-08-21 15:27:51,531:140171263747840:INFO:WorkQueue:Splitting /cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214621_3062/HIG-RunIISummer20UL16DIGIPremixAPV-03346_0 with policy name ResubmitBlock and policy params {'name': 'ResubmitBlock', 'args': {}}
2022-08-21 15:27:51,991:140171263747840:INFO:Rucio:Container: /Neutrino_E-10_gun/RunIISummer20ULPrePremix-UL16_106X_mcRun2_asymptotic_v13-v1/PREMIX with container-based location at: {'T2_CH_CERN', 'T1_US_FNAL_Disk'}
2022-08-21 15:27:53,073:140171263747840:INFO:WorkQueue:Work splitting completed with 1 units, 0 rejectedWork and 0 badWork
2022-08-21 15:27:53,073:140171263747840:INFO:WorkQueue:Queuing element c7af71b4c6e0d48d311ad65ac6894c0e for /cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214621_3062/HIG-RunIISummer20UL16DIGIPremixAPV-03346_0 with policy ResubmitBlock, with 3 job(s) and 4 lumis on /acdc/cmsunified_ACDC0_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220821_214621_3062/:pdmvserv_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220511_181015_3806:HIG-RunIISummer20UL16wmLHEGENAPV-02777_0:HIG-RunIISummer20UL16SIMAPV-03367_0:HIG-RunIISummer20UL16DIGIPremixAPV-03346_0/0/2
```
Those ACDCs are covering only 4 lumis each. So I am sure with or without those ACDCs this workflow would not have made it to the full statistics requested. 

And if we look at  what those total of 10 blocks contain, we notice the events and lumis are spread of quite uneven though:
```
$ for block in `dasgoclient  -query="block dataset=/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM"` ; do echo -ne "$block:"; dasgoclient -query="summary block=$block";done
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#043521a5-9550-4228-8786-aa5f512be7d3:[{"file_size":187752201,"nblocks":1,"nevents":3000,"nfiles":1,"nlumis":3,"num_block":1,"num_event":3000,"num_file":1,"num_lumi":3}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#2cf763a4-6ad3-4bb8-829b-c780cfb564f8:[{"file_size":398730207,"nblocks":1,"nevents":7000,"nfiles":1,"nlumis":7,"num_block":1,"num_event":7000,"num_file":1,"num_lumi":7}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#33be2a49-7a4b-400e-92f5-e9814dbc234f:[{"file_size":239698777,"nblocks":1,"nevents":4000,"nfiles":1,"nlumis":4,"num_block":1,"num_event":4000,"num_file":1,"num_lumi":4}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#5ce76c0a-0245-46fa-bc9a-dcf91072a5e6:[{"file_size":79101803,"nblocks":1,"nevents":1000,"nfiles":1,"nlumis":1,"num_block":1,"num_event":1000,"num_file":1,"num_lumi":1}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#6653517f-9cd4-41a3-8a43-2610a611088e:[{"file_size":238794556,"nblocks":1,"nevents":4000,"nfiles":1,"nlumis":4,"num_block":1,"num_event":4000,"num_file":1,"num_lumi":4}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#6a88f4f1-24f0-4e75-aedb-3b79ca41a328:[{"file_size":613205188,"nblocks":1,"nevents":11000,"nfiles":1,"nlumis":11,"num_block":1,"num_event":11000,"num_file":1,"num_lumi":11}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#c982b797-0504-4d4d-ae73-4a70019c419d:[{"file_size":345926481,"nblocks":1,"nevents":6000,"nfiles":1,"nlumis":6,"num_block":1,"num_event":6000,"num_file":1,"num_lumi":6}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#e099b6e4-37ee-40d5-961c-bd06ddc7e5e1:[{"file_size":239561021,"nblocks":1,"nevents":4000,"nfiles":1,"nlumis":4,"num_block":1,"num_event":4000,"num_file":1,"num_lumi":4}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#f7a3ccdd-ef9c-47df-9f52-1bd08efe043e:[{"file_size":186227083,"nblocks":1,"nevents":3000,"nfiles":1,"nlumis":3,"num_block":1,"num_event":3000,"num_file":1,"num_lumi":3}]
/WminusH_HToZZTo4L_M250_TuneCP5_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM#f997fd72-f745-4d42-98f7-d2950f3f89d2:[{"file_size":80063203,"nblocks":1,"nevents":1000,"nfiles":1,"nlumis":1,"num_block":1,"num_event":1000,"num_file":1,"num_lumi":1}]
```
I do not find any issue with WMCore here, so far.

**Comment by haozturk** [comment]
Hi @todor-ivanov apologies for late reply and thanks a lot for your investigation. At this point, we should understand why these 2 ACDCs don't cover all the missing lumis. We did submit 2 ACDCs for the 2 failed tasks which are:
```
/pdmvserv_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220511_181015_3806/HIG-RunIISummer20UL16wmLHEGENAPV-02777_0
/pdmvserv_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220511_181015_3806/HIG-RunIISummer20UL16wmLHEGENAPV-02777_0/HIG-RunIISummer20UL16SIMAPV-03367_0/HIG-RunIISummer20UL16DIGIPremixAPV-03346_0
```
and AFAIK, [this document](https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_task_HIG-RunIISummer20UL16wmLHEGENAPV-02777__v1_T_220511_181015_3806%22&include_docs=true&reduce=false) is used during ACDC creation. I couldn't see anything wrong from the submission side. Is it possible that not all the documents for the recovery of all the missing lumis is provided in the ACDC server?

**Comment by todor-ivanov** [comment]
Hi @haozturk, Indeed these documents are a major place to look into for our debugging here. But this workflow have got announced in the meantime, so we have lost those documents. It would be quite helpful if you could point a finger to another workflow which is having the same issue and not been announced yet, so that  we can examine the if the full `file_set` created for the ACDC workflow covers what was expected for the original workflow.

**Comment by haozturk** [comment]
Hi @todor-ivanov we realized that there are other workflows getting affected by this issue. This is one: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2017G-LowEGJet-09Aug2019_UL2017-00002

**Comment by vkuznet** [comment]
@haozturk , again I'm new to this debugging things, but your workflows from https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2017G-LowEGJet-09Aug2019_UL2017-00002 have identical number of lumis for input/output datasets. So, what is the problem then?

**Comment by amaltaro** [comment]
@haozturk Hasan, given the information provided by Todor and Valentin, could you please check if there is anything else to be done with this ticket (other than follow up on the assistance workflows and ensure that they match the a) data invalidated during the lifetime of a workflow; b) same run/lumi tuple in multiple files). Thanks

**Comment by haozturk** [comment]
Hi all, I'm very sorry for my late reply. The last workflow that I've reported seems to be rejected by PDMV and the output seems to be invalidated. 

Please see this workflow [1] where the AODSIM output is fully produced while MINIAODSIM has missing lumis (38/500). The original request [2] had a failed task which was supposed to be recovered by this ACDC [3]. ACDC has 2 jobs and both are successful. At this point, we're clueless why there are missing events.

[1] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIIFall17wmLHEGS-06544 
[2] https://cmsweb.cern.ch/reqmgr2/fetch?rid=haozturk_task_EXO-RunIIFall17wmLHEGS-06544__v1_T_210816_185613_3745
[3] https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_ACDC0_task_EXO-RunIIFall17wmLHEGS-06544__v1_T_221216_013035_5506

**Comment by todor-ivanov** [comment]
Hi @haozturk,
We did look at this workflow with @amaltaro and what we've found is that actually the issue here has  nothing to do with the ACDC created. Those 2 failed jobs from the ACDC you mentioned, have no way to account for all those many missing lumi sections. In fact what we can see in WMStats is 14 merege jobs created for the MiniAOD, while the number of files at DBS for this datasets is just 6 - this to us is indeed a mystery - this could be related to some invalidations or rejected workflows but for sure the missing lumis have no way to be recovered only by the ACDC you point here.

Unfortunately there has been a huge gap in time between the original workflow completion and the ACDC creation, so the original workflow's logs has gone long ago (the agent working on this workflow was `submit6`, which was redeployed meanwhile). 

To us it is again not an issue with the ACDC machinery. This looks more likely to be an operational consequence. 
I am in favor of closing this issue now. If you have a workflow that has similar symptoms please feel free  to reopen it again.
