### ISSUE TITLE
Build a minimal PyPI based Docker image for MSUnmerged

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11308]
**Impact of the new feature**
Overhaul the Dockerfile for reqmgr2ms, splitting out into separate containers for each microservice. Containers should be as small as possible. Container will use PyPI packages instead of the current RPM based deployment method.

**Is your feature request related to a problem? Please describe.**
reqmgr2ms container is currently very large and is used for multiple microservices, which is not ideal for k8s.

**Describe the solution you'd like**
Build a minimal Docker image using the MSUnmerged package from PyPI

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vkuznet** [comment]
I provided initial Dockerfile to build docker image and it was successfully build, see details in https://github.com/dmwm/WMCore/issues/11310. The individual dockerfiles can be found over here https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi

This is the only image which fails so far to build. The main issue is lack of `gfal2-python` package on Debian. Therefore, the main work should be done on building this package in debian environment and deploying it to Pypi. Once it is available for non CC7 Linux OS then we can re-build `reqmgr2ms-unmerged` as any other `reqmgr2ms` images using existing Dockefiles.

**Comment by vkuznet** [comment]
The new pypi based image is available:
- docker files: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi
- docker images: https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-unmerged

@amaltaro , should we close the ticket?

**Comment by amaltaro** [comment]
Basic functionality of these PyPi-based services have been tested with docker image label: `2.1.6rc3`.
Workflows are getting their input rules evaluated and moving to `staged` status!

In addition to the changes already linked above, the following was required as well:
Mount rucio-secrets and rename the docker image name for microservices, global workqueue and t0_reqmon:
https://github.com/dmwm/CMSKubernetes/pull/1261
https://github.com/dmwm/CMSKubernetes/pull/1283
https://github.com/dmwm/CMSKubernetes/pull/1287

Fix to the run.sh script in the dmwm-base image:
https://github.com/dmwm/CMSKubernetes/pull/1288

Fix for the MongoDB credentials:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/185

Further and in depth validation can be tracked at https://github.com/dmwm/WMCore/issues/11354. Closing this one out.
