### ISSUE TITLE
Create a base Docker image for WMCore services

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11311]
**Impact of the new feature**
WMCore

**Is your feature request related to a problem? Please describe.**
Instead of relying on the beefy CMSWEB docker image, which brings in many things not needed by WMCore (hadoop, spark, etc), we should work in a new base image providing only what is necessary for WMCore and CMS/CMSWEB specific setup (dev utils should not be added here).

**Describe the solution you'd like**
As can be seen in the reqmgr2 Dockerfile:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/reqmgr2/Dockerfile#L1

it depends on a generic CMSWEB image.
With this ticket, we should build a new base image for WMCore services, and then make all the WMCore services to inherit from it. The base image should have only what is common among the services, and if possible nothing that is not relevant for a production environment.

**Describe alternatives you've considered**
Keep using the standard CMSWEB image and keep a high number of vulnerabilities.

**Additional context**
None

**Comment by vkuznet** [comment]
I do not know if we really need to target this for RPM based installation (as I hope we're going to replace it soon on k8s), but for pypi based images I already created/tested/deployed common dmwm-base image, see https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/Dockerfile The corresponding image can be found in registry: https://registry.cern.ch/harbor/projects/1771/repositories/dmwm-base/artifacts-tab

**Comment by amaltaro** [comment]
@vkuznet Valentin, thanks for looking into it. I have a few comments on this:
1) you might want to own this issue (assign yourself) and move it to work in progress, since you worked on this 5 days ago. If you don't do so, it can potentially be worked on by someone else;
2) I was afraid of the following line bringing in too many things
```
FROM registry.cern.ch/cmsweb/cmsweb-base as cmsweb-base
```
but I see that it's been made really light over the past weeks. So, it's pretty good now!
3) do you know what would be the additional image size if we install `less` in this image? I see it already has `vim`, thanks!
4) my initial goal was to make a base image for the WMCore services, hence I would suggest to use `wmcore-base` image name instead of `dmwm-base`. However, if other projects (e.g., CRAB, T0) decide to use it, then `dmwm-base` is indeed better.
5) I think we discussed about the directory structure in the past week and the idea would be to stick to the current organization (unless we hit a blocker). So, perhaps we could create those base directories in this image as well and avoid duplicating a bunch of lines in many Dockerfiles:
https://github.com/dmwm/WMCore/issues/11354#issuecomment-1323901243

**Comment by vkuznet** [comment]
Alan, I'll answer your question in order you placed them:
1. I assigned to myself, but it is unclear still if you want base image for RPM based image, in my view it is not worth it, but I'm ok if you will say we still need it
2. The line you refer is a side-car image, i.e. I declare it to copy some stuff from it but it is not used in the image. If you look at Dockefile you'll see that I copy from cmsweb-base image only certificates that's it.
3. `less` can be added without additional overhead in size of the image
4. I still in favor of `dmwm-base` since indeed it can be used by other, non WMCore services
5. I don't think we should add directory structure into the image. Base image install the minimum software stack, that's it. The directory structure comes from RPM based deployment procedure and it not required for pypi one, but so far due to our scripts and configs we need it. Therefore, in my view it should stay out of image itself. If you inspect pypi area and its docker files you rather may notice that run.sh script is common and I think it should be put into base image since we start all services identically. In fact, so far run.sh is identical across all pypi images. And, run.sh contains all necessary steps to setup proper directory structure. So, if you want unification I rather prefer to put run.sh script into base image. But I did not make it so far since I was not sure if all services will have identical start procedure (they seems to have it since all of them just call `wmc-httpd` daemon with proper config and log entries. I need your input on this though in order to move run.sh into base image. Please have a look at individual run.sh in pypi area.

**Comment by amaltaro** [comment]
@vkuznet this was sitting in the Q4 - 2022 ToDo column. I just moved it to "In progress", given that you started working on it 5 days ago.

**Comment by amaltaro** [comment]
>I assigned to myself, but it is unclear still if you want base image for RPM based image, in my view it is not worth it, but I'm ok if you will say we still need it

At this stage, I would not invest any time in the RPM-based packaging/deployment.

> less can be added without additional overhead in size of the image

please add it to the base image then.

> If you inspect pypi area and its docker files you rather may notice that run.sh script is common and I think it should be put into base image since we start all services identically. In fact, so far run.sh is identical across all pypi images.

I think most of them are the same. However, I am sure that microservices - and maybe MSUnmerged - are slightly different. Can you please compare them all to come with a final answer on this?

> And, run.sh contains all necessary steps to setup proper directory structure. So, if you want unification I rather prefer to put run.sh script into base image. 

yes, that looks good as well. I just want to avoid creating the same directory structure in 10 different places.

**Comment by vkuznet** [comment]
@amaltaro , I added `run.sh` script into base image, and I verified that so far it is the same file used in all services with the exception of the concrete config file to be used by the service. Therefore I made appropriate change with the image to deal with that problem, e.g. https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2ms-output/Dockerfile#L5 where `run.sh` comes from https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/Dockerfile#L10 and https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/run.sh

Now, we have single place for `run.sh` which uses `config.py` (https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/run.sh#L7), and each individual service may or may not overwrite it, e.g. reqmgr2ms-output overwrites this via this substitution: https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2ms-output/Dockerfile#L5

**Comment by amaltaro** [comment]
Thanks Valentin.

I still don't see `less` added to the `dmwm-base` image. Have I missed it?

Can you please clarify what the difference is between Dockerfile and Dockerfile.dist? It looks like that the *dist installs from the tarball and installs all of the requirements as an extra step.

I understand that with the GH action properly depending on the Pypi package - either the sdist or the wheel package - we will no longer need Dockerfile.dist, right?

**Comment by vkuznet** [comment]
@amaltaro , the `less` is last package on this line: https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/Dockerfile#L5

The `Dockerfile` uses pip to install out of existing package tag, while `Dockerfile.dist` uses a tarball which we may create before putting package to pypi. Therefore, the former requires package to be uploaded to pypi, while latter does not. As such, only the latter can be used with single workflows which build tarball, build image and upload tarball to pypi.

Our choice of how we organize CI/CD pipeline workflows will dictate which Docker file to use. If we decide to use package from pypi we may use `Dockerfile`, while if we'll build our images before or after we send tarball to pypi we should use `Dockerfile.dist`. And, if we use manual builds we can use either.

**Comment by amaltaro** [comment]
My take on this is that we should upload packages to PyPi, then use those packages from PyPi to create the Docker images.

**Comment by amaltaro** [comment]
Yes, I think the remaining work can be followed up in their respective tickets. Thank you very much, Valentin.
