### ISSUE TITLE
add WebDav errors to StageOut Exceptions

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#11329]
**Impact of the bug**
Reporting webdav errors with generic failure even when a proper reason is available, this makes troubleshooting and user support in CRAB (at least) un-necessarely painful

**Describe the bug**
`STAGEOUT_ERRORS` dictionary in `WMCore/WMExceptions.py` is a collections of regexp's which are used to parse error messages from FTS in order to assing one exit code to the job. The current version pre-dates WebDav and needs updating, there are a couple common use cases (at least) where current code reports `60324 - Other stageout exception. ` but we could set a more meaningful exit code instead.

**How to reproduce it**
no need to

**Expected behavior**
When WebDav report a useful message like "Permission refused" we should map into proper exit code.

**Additional context and error message**
Since we discover FTS messages as we operate and they are not standardized but can change, there will always be need to update the list of regexp which we match in here

**Comment by belforte** [comment]
this is addressed in PR #11328

**Comment by amaltaro** [comment]
@belforte thanks Stefano. Do we have these regex because the logs are too large and we want to provide a very short and simple error message whenever it happens?

**Comment by belforte** [comment]
@amaltaro  that code is simply about setting one exit code or another. What you say is exactly the role of exit codes. Also having numeric codes allows us to classify things e.g. in Grafana. All I am trying to do is to make a few more cases to a specific reason instead of "60324 - Other stageout exception." My bad not having made this more clear.

**Comment by belforte** [comment]
I updated description at top to point out that this is about setting job exit codes. Which indeed are short and simple !
