### ISSUE TITLE
Remove pylint py3k check from the Jenkins tests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11332]
**Impact of the new feature**
WMCore Jenkins

**Is your feature request related to a problem? Please describe.**
Now that code has been fully ported to python3 and python2 code is no longer supported - and that pylint is executed in a python3 environment - there is no more reason to keep the `Pylint py3k` tests, which is testing the compatibility of a python2 code with python3.

**Describe the solution you'd like**
A non-exhaustive list of actions is:
* remove the Jenkins job running `pylint --py3k` on top of every PR
* remove the Jenkins job running `pylint --py3k` on our baseline tests (if any)
* update the script aggregating test results to stop considering it (check with the CRAB team to ensure compatibility across projects)
* build a new WMCore docker image (used by jenkins), if required

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
@d-ylee AFAIU, this has been resolved together with the developments you were making in https://github.com/dmwm/WMCore/issues/11568. If that is correct, can you please close this out?

**Comment by d-ylee** [comment]
Yes, I believe we are not doing the py3k checks anymore in our new Jenkins setup. Closing.
