### ISSUE TITLE
JobAccountant trying to upload large documents to local CouchDB

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11342]
**Impact of the bug**
WMAgent

**Describe the bug**
While investigating an ErrorHandler issue in vocms0252, I noticed that JobAccountant log is barely usable, with a dump of a large document that failed to be inserted into local CouchDB for being too large, see part of the error here [1]. And I think this is the equivalent log record in the CouchDB server [2], where one can see that this operation failed with a 
```
413 - Request Entity Too Large
```

We don't override any of the relevant CouchDB document size configuration in:
https://github.com/dmwm/deployment/blob/master/wmagentpy3/local.ini
which means we are using the default values for:
"""
A document exceeds the configured [couchdb/max_document_size](https://docs.couchdb.org/en/3.2.2-docs/config/couchdb.html#couchdb/max_document_size) value or the entire request exceeds the [chttpd/max_http_request_size](https://docs.couchdb.org/en/3.2.2-docs/config/http.html#chttpd/max_http_request_size) value.
"""

From a quick look at the log and the document dump, I think the problem comes from a **very large**  list of LFNs provided under
```
process.mixData.input.
fileNames = cms.untracked.vstring([\\\\\\\'/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/120000/00456BD1-4A4E-6843-AA18-78B56D65EF38.root, ...
```

Traceback information is provided in [3]

**How to reproduce it**
Create a document in CouchDB larger than what it's configured for.

**Expected behavior**
JobAccountant does not crash when it fails to upload such large documents - and neither are these documents extremely important - so I think we do not need to change anything on this front.

Possible improvements that could be delivered with this issue are:
* whenever this http error `413` is hit, we should not dump the document content in the error message. Ideally, we could actually json serialize it and get its length to see how big the document was.
* update the CouchDB `local.ini` and define those parameters there. Either with the same default value, or with an slightly increase in its size (16MB?)
* (BONUS) maybe stop providing a list of secondary files in the FJR that gets uploaded to CouchDB (and likely ending up in central WMStats, through replication).

**Additional context and error message**
[1]
```
2022-10-12 12:51:36,051:140152399025920:ERROR:ChangeState:Error updating job in couch: NEW ERROR STATUS! UPDATE CMSCOUCH.PY!: 413
CouchError - reason: Request Entity Too Large, data: {'docs': [{'_id': '2490046-0', 'jobid': 2490046, 'jobtype': 'Cleanup', 'jobstate': 'jobfailed', 'retrycount': 0, 'archivestatus': 'skip', 'fwjr': {'WorkerNodeInfo': {'HostName': 'llrgrwn129.in2p3.fr', 'MachineFeatures': {}, 'JobFeatures': {}}, 'task': '/cmsunified_task_HIG-RunIISummer20UL17wmLHEGEN-04807__v1_T_220629_205933_5667/HIG-RunIISummer20UL17wmLHEGEN-04807_0/HIG-RunIISummer20UL17MiniAODv2-06491_0CleanupUnmergedMINIAODSIMoutput', 'steps': {'cleanupUnmergedMINIAODSIMoutput': {'st
...
le "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_pickler.py", line 39, in main\\\\n    code = compile(f.read(), args.input, \\\\\\\'exec\\\\\\\')\\\\n  File "/srv/job/WMTaskSpace/cmsRun3/PSet.py", line 84\\\\n    process.mixData.input.
fileNames = cms.untracked.vstring([\\\\\\\'/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/120000/00456BD1-4A4E-6843-AA18-78B56D65EF38.root\\\\\\\', \\\\\\\'/store/mc/RunIISummer20ULPrePremix
/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/120000/00C583B9-1C11-D640-8D2C-F27E2DB5D5E3.root\\\\\\\', \\\\\\\'/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/120000/00CB222A-
45EA-7C4C-A5B8-DA43C984CBE9.root\\\\\\\',
...

'status': 0, 'start': 1665240769, 'stop': 1665240778, 'performance': {'storage': {}, 'memory': {}, 'cpu': {}, 'multicore': {}}, 'output': {'logArchive': [{'prep_id': 'TAU-RunIISummer20UL16wmLHEGEN-00014', 'merged': False, 'pfn': 'gsiftp:/
/se.grid.vbc.ac.at:2811//eos/vbc/experiments/cms/store/unmerged/logs/prod/2022/10/8/cmsunified_task_TAU-RunIISummer20UL16wmLHEGEN-00014__v1_T_221007_220847_2422/TAU-RunIISummer20UL16wmLHEGEN-00014_0/0012/2/f515950a-ffc1-4680-a998-ab5951a9
d3fe-287-2-logArchive.tar.gz', 'checksums': {'adler32': '887ea5a0', 'cksum': '488771565'}, 'lfn': '/store/unmerged/logs/prod/2022/10/8/cmsunified_task_TAU-RunIISummer20UL16wmLHEGEN-00014__v1_T_221007_220847_2422/TAU-RunIISummer20UL16wmLHE
GEN-00014_0/0012/2/f515950a-ffc1-4680-a998-ab5951a9d3fe-287-2-logArchive.tar.gz', 'size': 0, 'events': 0, 'runs': {}, 'module_label': 'logArchive', 'location': 'T2_AT_Vienna'}], 'analysis': []}, 'input': {}, 'errors': [], 'cleanup': {}, '
parameters': {}, 'site': 'T2_AT_Vienna', 'analysis': {}, 'logs': {}}}, 'skippedFiles': [], 'fallbackFiles': ['/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/260028/B664263C-EE8E-FF4D-BF9A-E8
5E028BD93B.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/130008/F1CA2195-46DA-1044-9C20-4C0B6D212846.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mc
Run2_asymptotic_v13-v1/130021/D9A62292-3457-4948-8FDA-45FA3FAC3C10.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/120015/D9B18E38-59F5-E743-B12C-759C15EC9DD0.root', '/store/mc/RunIIS
ummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/260008/34DD277B-53F5-FD45-8F6F-35342D95975C.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/130023/E2F95
3B6-89DC-F84E-93AC-D9DDB01E958C.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/130018/2493A19D-B4A9-294A-80D6-87928C8FAF11.root', '/store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gu
n/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/260026/8C490B56-9D1E-EC4E-889A-4019D5C86820.root'], 'Campaign': 'RunIISummer20UL16wmLHEGEN', 'PrepID': 'TAU-RunIISummer20UL16wmLHEGEN-00014', 'EOSLogURL': ''}, 'type': 'fwjr', 'timestamp': 16652
41967}]} result: b'{"error":"document_too_large","reason":"2446275-2"}\n'
```

[2]
```
[notice] 2022-10-12T10:58:10.773692Z couchdb@127.0.0.1 <0.20732.2466> f0bbd8867d localhost:5984 127.0.0.1 user POST /wmagent_jobdump%2Ffwjrs/_bulk_docs/ 413 ok 404
```

[3]
```
2023-03-01 18:04:52,178:140522091906816:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 131, in makeRequest
    result, status, reason, cached = JSONRequests.makeRequest(
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 185, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 202, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 353, in request
    raise exc
http.client.HTTPException: url=http://localhost:5984/wmagent_jobdump%2Ffwjrs/_bulk_docs/, code=413, reason=Request Entity Too Large, headers={'Connection': 'close', 'Date': 'Wed, 01 Mar 2023 17:04:51 GMT', 'Server': 'CouchDB/3.2.2 (Erlang OTP/22)', 'Cache-Control': 'must-revalidate', 'Content-Length': '52', 'Content-Type': 'application/json', 'X-Couch-Request-ID': 'cbf54a0567', 'X-CouchDB-Body-Time': '19'}, result=b'{"error":"document_too_large","reason":"4799572-0"}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 178, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 359, in recordInCouch
    self.fwjrdatabase.queue(fwjrDocument, timestamp=True, callback=discardConflictingDocument)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 240, in queue
    self.commit(viewlist=viewlist, callback=callback)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 306, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 154, in post
    return self.makeRequest(uri, data, 'POST', incoming_headers,
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 135, in makeRequest
    self.checkForCouchError(getattr(e, "status", None),
  File "/data/srv/wmagent/v2.1.6.1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.6.1/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 178, in checkForCouchError
    raise CouchError(reason, data, result, status)
WMCore.Database.CMSCouch.CouchError: NEW ERROR STATUS! UPDATE CMSCOUCH.PY!: 413
```

**Comment by amaltaro** [comment]
This is now affecting vocms0255 as well, and it dumps a huge log in the component log (truncated here):
```
2023-03-01 17:49:09,408:140522091906816:INFO:AccountantWorker:Job 5188785 , handle successful job
2023-03-01 17:49:12,086:140522091906816:ERROR:ChangeState:Error updating job in couch: NEW ERROR STATUS! UPDATE CMSCOUCH.PY!: 413
CouchError - reason: Request Entity Too Large, data: {'docs': [{'_id': '4799659-0', 'jobid': 4799659, 'jobtype': 'Merge', 'jobstate': 'success', 'retrycount': 0, 'archivestatus': 'ready', 'fwjr': {'WorkerNodeInfo': {'HostName': 'tds285.pic.es', 'MachineFeatures': {'hs06': None, 'total_cpu': None}, 'JobFeatures': {'hs06_job': None, 'allocated_cpu': None}}, 'task': '/cmsunified_task_EXO-RunIISummer20UL17wmLHEGEN-03682__v1_T_230223_115953_446/EXO-RunIISummer20UL17wmLHEGEN-03682_0/EXO-RunII...
```

I am checking if this can have a simple enough fix that we can push in.

**Comment by amaltaro** [comment]
From the CouchDB logs, this is the log record we get whenever this 413 Couch error happens:
```
[notice] 2023-03-03T02:19:03.877738Z couchdb@127.0.0.1 <0.21074.504> 28e1aacce3 localhost:5984 127.0.0.1 cmsdataops POST /wmagent_jobdump%2Ffwjrs/_bulk_docs/ 413 ok 2667
```

where we can see that the size of that document is not logged.

In addition to that, I checked the agent replications and the replication to WMStats is actually defined as:
```
    "source": "http://localhost:5984/wmagent_summary/",
    "target": "https://cmsweb.cern.ch/couchdb/wmstats/",
```

so it could be that this FJR is not really useful other than to build documents to WMArchive. Further investigation is required though.

**Comment by vkuznet** [comment]
Alan, thanks for providing these details, it explain our issue with reporting to WMArchive. Said that, I think the main question is do we need to provide LFNs in a doc? Who use this info and why these lists should be presented in CouchDB. Overall it is a big issue with data growth. It slows CouchDB itself, we lack of proper monitoring, etc. I think the priority should be to drop LFNs if nobody is using this info. The point is that LFNs can be captured from DBS if we record datasets in FWJR. I do not see any reason for them in this report. Of course we need to find out limit for JSON doc to be successfully uploaded to CouchDB but it will only tell us the limit. So it is one time exercise I think. Can we drop LFNs from FWJR?

**Comment by amaltaro** [comment]
> Can we drop LFNs from FWJR?

I don't have this answer right now because we still need to see where exactly this information gets propagated to.
Not all LFNs can be discovered through DBS, much of the workflow data is transient and never shows up in DBS, so dropping list of LFNs here might handicap any error report. As I said, further investigation needs to happen though.

**Comment by vkuznet** [comment]
This issue clearly demonstrates necessity of schema discussion and its proper documentation. Said that we have other information in FWJR which can be significantly large, e.g. pfns, run/lumis pairs, fallback files. The actual problem here is that FJW is unstructured JSON (a single nested dict) whose size dynamically grows with size of underlying tasks. As such in general it can grow to infinity, e.g. if we start producing dataset with thousands of blocks/files (I've seen that in DBS we may have a dataset with 10K files in it) and therefore the size of FWJR will only grow up due to its underlying data-format. Instead, we should revisit structure of FWJR document and decide which information should be persistent and which should be intermittent. The later, in my opinion, is better to push into dedicated RDBMS rather CouchDB.

Said that, I fear that if we'll increase CouchDB max sizes and still have a potential conditions when we'll exceed it.

I also suggest to consider an alternative solution. Instead of increasing CouchDB max sizes and dropping LFNs (or any other attributes) we may consider zipping FJW and inject it as a blob of bytes with some relevant keys. This way we can significantly reduce document size in CouchDB, we'll preserve its structure and keep it around as is. This approach will require adding zip/unzip handler when we insert and fetch docs such that docs will flow to Couch in zipped form while in WMCore code base it will be unzipped.

As far as I recall we already dropped run/lumis in WMArchive docs since MONIT infrastructure also complained about large doc sizes it about 2-3 years ago, see
- https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/run.sh#L27
- https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L187
- https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L247

**Comment by amaltaro** [comment]
Moving this one as well from Q1 to Q2, as it is still a work in progress item.
