### ISSUE TITLE
Supprt bulk changing of request priorities

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#1134]
Says Oli:
this is what I would like to do:

- select all workflows with the sub string 110209_01
- change their priority to 20

I found that you can filter in "view" and I know that I can change the priority for every workflow individually. Is there a bulk thing?

**Comment by amaltaro** [comment]
People use scripts for this whole thing now (and it's possible to come in ReqMgr2...).
@ticoann can we close this one
