### ISSUE TITLE
Update python rucio-clients package to the latest version (1.29.8?)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11359]
**Impact of the bug**
WMCore in general

**Describe the bug**
The `rucio-clients` library parses the error sent back from the server, which means that eventually it might start yielding a different error message to the end user, in case we fall too much behind with the client version.

As of this moment, WMCore services use version `1.25.5`, which dates back to May 2021.

**How to reproduce it**
None

**Expected behavior**
Update the python `rucio-clients` library to the latest stable version, at this moment, that would be `1.29.8`.
Two pull requests need to be created:
1) a cmsdist PR updating the py3-rucio-clients.spec file
2) another updating the WMCore requirements.txt file

In order to properly test it, we need to first merge the cmsdist PR, such that a new RPM gets created for WMAgent jenkins tests.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@belforte @mapellidario I think you are also using the cmsdist/py3-rucio-clients package, right? I'll likely get this update done this week.

**Comment by belforte** [comment]
yes we do. Thanks for the heads up Alan. We'll pick it in next build. I expect no problems.

**Comment by amaltaro** [comment]
Self-reminder: to be done once the T0 team releases a new stable T0-WMAgent package.

**Comment by amaltaro** [comment]
We actually hit a blocker! Let's see if we can relax one of the dependencies in the `cmsmonitoring` package:
https://github.com/dmwm/CMSMonitoring/issues/178
