### ISSUE TITLE
MSRuleCleaner potentially not cleaning unlocked input dataset rules

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11367]
**Impact of the bug**
MSRuleCleaner

**Describe the bug**
A possible issue with MSRuleCleaner has been reported in the past week, where it leaves Rucio rules behind for some of the input datasets. Amanda initially provided these 3 RelVal input datasets (blocks):
```
/RelValZMM_14/CMSSW_12_5_0_pre3-124X_mcRun3_2022_realistic_v8-v2/GEN-SIM-DIGI-RAW#621aab39-d57d-4308-b38c-fa8bfeb65fdb
/RelValTTbar_14TeV/CMSSW_12_5_0_pre3-124X_mcRun4_realistic_v8_2026D88noPU-v1/GEN-SIM-DIGI-RAW#fef08bee-3d76-485d-b4b4-68ed0b181b70
/RelValTTbar_14TeV/CMSSW_12_5_0_pre3-124X_mcRun3_2022_realistic_v8-v2/GEN-SIM-DIGI-RAW#4c88cda3-eebb-4e7f-9860-ef201108d9d8
```

which are still locked under the account `wmcore_transferor`, even though all the relevant workflows processing it are no longer active in the system (they have been archived).

A non-relval input dataset example is:
https://cmsweb.cern.ch/reqmgr2/data/request?inputdataset=/BTohh_hToMuNu_BsBdMixture_modHadLifetime_TuneCP5_13TeV-pythia8-evtgen/RunIISummer20UL17RECO-106X_mc2017_realistic_v6-v3/AODSIM

which has been archived in December 2021, leaving these two rucio rules behind:
```
c55dcaa65f2b443b9824fff1983228e1
61fa02b8b4694f27b80f91adec4d1591
```

**How to reproduce it**
No clue

**Expected behavior**
From a quick debugging that I have done so far, MSRuleCleaner seem to be properly deleting rules for the input dataset. So there might be a specific scenario that triggers this ill behaviour.

On what concerns this issue, we should:
* improve logging, such that we can explicitly see whenever an input data is looked up, and under which classification (primary, parent or secondary);
* ensure that rules allowed for deletion are actually removed, especially for input dataset

**Additional context and error message**
None

**Comment by anehnis** [comment]
I have compiled a list of rules older than 100 days whose datasets have all request statuses showing as archived. The first file contains lots of information about the rules while the second contains only the rule id and name.
[rules.csv](https://github.com/dmwm/WMCore/files/10135919/rules.csv)

[ruleid_name.csv](https://github.com/dmwm/WMCore/files/10135921/ruleid_name.csv)

**Comment by amaltaro** [comment]
Now we should have enough information to debug this microservice, thanks @anehnis . We will have a careful look into this tomorrow or on Monday.

**Comment by todor-ivanov** [comment]
Hi @khurtado @anehnis do you have any progress on this? Do you need some help? What you have found here, may have manifested itself also in another way, through the recently enabled alarms from `MSRulecleaner`. It would be good to have this checked.

**Comment by anehnis** [comment]
Currently I am still getting set up in a test environment to run MSRuleCleaner. Once that is completed, any help would be appreciated in fixing this.

**Comment by anehnis** [comment]
It appears that aborted-completed workflows did not go through the MSTrCont and MSTrBlock pipelines; therefore any rules from wmcore_transferor for these input datasets were never deleted. I have made a change to the code to have these workflows go through all the pipelines instead of only Agent pipelines.
