### ISSUE TITLE
Update CMSSST Grafana metadata field

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11376]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
As reported by Stephan today in the CompOps meeting - and also via private email - the CERN MonIT team needs to change the organization of documents in HDFS, and the impact is that the `metadata.path` field in cmsssdt metrics is being phased out in favor of `metadata.monit_hdfs_path`.

**Describe the solution you'd like**
We need to update the Grafana module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/MonIT/Grafana.py#L111

and replace `metadata.path` by `metadata.monit_hdfs_path`. 

Given that this query is large and ugly, I would simply make these changes in the source code itself.

**Describe alternatives you've considered**
Make things configurable such that no source code changes are required next time.

**Additional context**
None

**Comment by amaltaro** [comment]
@germanfgv @jhonatanamado if this piece of code is used by the T0 machinery, we will have to patch those agents as well. I don't think it is, though.

**Comment by jhonatanamado** [comment]
Hi @amaltaro Indeed AFAIK is not used by our monitoring in Grafana.
