### ISSUE TITLE
Create WMCore images via CI/CD pipeline

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11374]
**Impact of the new feature**
Automate creation of WMCore images via CI/CD pipeline

**Is your feature request related to a problem? Please describe.**
It addresses part of https://github.com/dmwm/WMCore/issues/10921

**Describe the solution you'd like**
I used separate repository (https://github.com/vkuznet/wmcore-builds) to provide GH workflow files, please see
- https://github.com/vkuznet/wmcore-builds/actions/runs/3559490437/jobs/5978964198
- https://github.com/vkuznet/wmcore-builds/blob/main/.github/workflows/pypy_build_publish.yml-
- https://github.com/vkuznet/wmcore-builds/blob/main/.github/workflows/pypy_build_images_template.yml

The separate repository was required as GH Actions are working with main branch and in order to develop/validate/debug the CI/CD process the new repository was created. But because of that I used to add an additional step to clone WMCore into the build (see https://github.com/vkuznet/wmcore-builds/blob/main/.github/workflows/pypy_build_images_template.yml#L29) which is not required when we will merge workflows into WMCore repository. All other steps are done with the same templates and steps we used in current WMCore GH workflow files. The final step to upload images to registry will require setting up `CERN_LOGIN` and `CERN_TOKEN` secrets in WMCore repository. Finally, we need to make a decision if we'll incorporate this as part of pypi build workflow and run it separate.

**Describe alternatives you've considered**
None

**Additional context**
This issue can close https://github.com/dmwm/WMCore/pull/11339

**Comment by amaltaro** [comment]
@vkuznet Valentin, I can work on the registry setup once a PR has been created.

> Finally, we need to make a decision if we'll incorporate this as part of pypi build workflow and run it separate.

For what concerns the question above, ideally we should separate:
* pypi packaging and upload; vs
* docker image creation and upload.

This will make each of these workflows simpler and easier to maintain and debug. Of course, if it's not straight forward to implement this separation - or if their dependencies is complicated to be enforced - then we could look into one big GH action workflow for everything.

**Comment by vkuznet** [comment]
@amaltaro , in order to create an image we need to create tar ball. The later step is part of pypi packaging GH workflow. Therefore, if we want to separate docker images from pypi packacing it is trivial, but we'll duplicate part of pypi packaging (which creates tar ball) in docker image GH workflow.

**Comment by amaltaro** [comment]
If we have to duplicate code, then I would actually be in favor of having a single GH action for building/uploading to pypi, then building/uploading to registry.

Another option that just occurred to me is that maybe we could probe whether the package in a specific version is already available in Pypi or not, e.g.:
curl -I -L https://pypi.io/packages/source/r/reqmgr2/reqmgr2-2.1.5rc2.tar.gz | grep "^HTTP/2 2"

this would look ugly and annoying to maintain though. Let's just stick to a single GH action and make sure we use the `needs` syntax for the dependency between PyPi image and docker build

**Comment by amaltaro** [comment]
Closed by https://github.com/dmwm/WMCore/pull/11377
