### ISSUE TITLE
Growing NANOAOD workflows prematurely completing (not respecting OpenRunningTimeout)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11385]
**Impact of the bug**
WMCore

**Describe the bug**
Some workflows can stay open - keep performing input data discovery - for a given amount of time (defined by OpenRunningTimeout, during assignment). This is a special case for growing datasets processed "directly" from the T0 system (the MiniAOD to NanoAOD case).

It was a dark and stormy night, and what happened is that such workflows e.g.:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_Run2022G_MuonEG_PromptNanoAODv10_v1_221125_091920_5517

moved to `completed` before the timeout for the creation of new input blocks was reached.

It's very likely that this workflow was marked as completed as soon as all the WQE were in a final state (e.g. Done). Which should still obey to the OpenRunningTimeout.

**How to reproduce it**
See above

**Expected behavior**
Workflows should remain in running state (either open or closed) until the OpenRunningTimeOut is reached in global workqueue. In other words, if an input block showed up within the timeout, that timeout should be reseted.

**Additional context and error message**
Follow up of: https://github.com/dmwm/WMCore/issues/11048

**Comment by amaltaro** [comment]
Development on this hasn't even started, but moving this one as well from Q1 to Q2.

**Comment by vkuznet** [comment]
@amaltaro , I can work on this issue if you'll provide more technical input and pointers to code-base which is responsible for this. I had a look at `OpenRunningTimeout` and it appears in many different places like:
- ReqMgr
- MSTransferor
- WorkQueue
- WMSpec
And, I have no idea which part is responsible for this misbehavior.
