### ISSUE TITLE
pycurl_manager should properly parse HTTP/2 HTTP reponses

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11399]
**Impact of the bug**
Current version of pucurl only able to parse HTTP/1.1 responses, while HTTP standard support HTTP/1, HTTP/1.1, and HTTP/2

**Describe the bug**
pycurl_manager parses HTTP response via regexp, see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/pycurl_manager.py#L103-L105
and the following pattern is wrong:
```
>>> import re
>>> row="HTTP/2 200"
>>> startRegex = r"^HTTP/\d.\d \d{3}"
>>> re.search(startRegex, row)
```

**How to reproduce it**
```
>>> import re
>>> row="HTTP/2 200"
>>> startRegex = r"^HTTP/\d.\d \d{3}"
>>> re.search(startRegex, row)
```

**Expected behavior**
The fix should include ability to properly parse HTTP/1.1 and HTTP/2 HTTP responses, e.g.
```
>>> startRegex = r"^HTTP/(\d|\d.\d) \d{3}"
>>> re.search(startRegex, "HTTP/1.1 200")
<re.Match object; span=(0, 12), match='HTTP/1.1 200'>
>>> re.search(startRegex, "HTTP/2 200")
<re.Match object; span=(0, 10), match='HTTP/2 200'>
```

**Additional context and error message**
This is the reason why reqmgr2-tasks pod is failing on k8s using pypi deployment.

**Comment by todor-ivanov** [comment]
Thanks for spotting that  @vkuznet . Can you please label the isseue as a bug, and assign it to a project (Q4 still I believe)
