### ISSUE TITLE
Change Alert properties for Micro Services 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11396]
**Impact of the new feature**
MSRuleCleaner and most probably all other MicroServices' alerts  

**Is your feature request related to a problem? Please describe.**
Recently we started sending proper alerts with MSRuleCleaner for workflows passing some configurable threshold of time sitting in `unarchived`status. This did reveal some  OPS related issues and proved to be a good working alarm, but also had one drawback - we  get those alarms re-raised over and over every hour. The alarms we are talking about have the following signature:
```
Labels
alertname = ms-rulecleaner: Not archived workflow: cmsunified_task_HIG-RunIISummer20UL16wmLHEGEN-06297__v1_T_220609_124831_4910
service = ms-rulecleaner
severity = high
tag = wmcore
```

Possible reasons  are 
* We update the alarm with every new call to AlertManager and by that we keep pushing the alarm's 48 hours expiration time infinitely 
* The AlertManager  is configured that way - to continue triggering alarms on every 1 hour until the alarm is alive (this should be the same 48 hours alarm expiration time). And then immediately after that period we again reactivate the alarm because those workflows are still correctly waiting for some condition to be met and are indeed still valid alarms.

While the latest is not  a wrong behavior per se, it is at least not the expected one. Our needs are, to have this alarm raised only once during the alarm expiration time, and then to be re-raised, yet again just once, when the alarm gets renewed.    

**Describe the solution you'd like**
We need to figure out the proper options we  set the alarms with when making the call to the AlarmManager, such that we achieve the expected behavior as  explained above. 

In addition, we may think of rearranging the messages in those alarms to make them more human readable if the AlertManager allows such a text prettifying.

**Describe alternatives you've considered**
Not a good one - Stop sending intensive alarms and relying only on warning from service log messages.   

**Additional context**
A typical alarm we are talking about here:

```
subject: 
[FIRING:1] ms-rulecleaner: Not archived workflow: pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01457__v1_T_210428_132335_3967 (ms-rulecleaner high wmcore)

alarm content:


[1] Firing
--
Labels  alertname = ms-rulecleaner: Not archived workflow: pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01457__v1_T_210428_132335_3967  service = ms-rulecleaner  severity = high  tag = wmcore  Annotations  description = Found a workflow not archived since Tue Aug 10 14:33:59  2021. Workflow:  pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01457__v1_T_210428_132335_3967  Has exceeded the Status Advance Timeout of: 720 hours for its current  status: announced. Additional info: Not properly cleaned workflow:  pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01457__v1_T_210428_132335_3967  Actions need to be taken!  hostname = ms-rulecleaner-658c5d67d8-src5n  summary = [MSRuleCleaner] Found workflow:  pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01457__v1_T_210428_132335_3967  not archived since Tue Aug 10 14:33:59 2021.

```

**Comment by todor-ivanov** [comment]
Just for logging purposes:
During the break we have resieved tons of alarms from `MSRuleCleaner` about not archived workflows. This [[1]](https://cms-monitoring.cern.ch/alertmanager/#/alerts?receiver=dmwm-admins ) is the link where one can check all the alarms to be sent to the `dmwm-admins` . Strangely enough I can find no alarms related to this  service at the moment. 


[1]
https://cms-monitoring.cern.ch/alertmanager/#/alerts?receiver=dmwm-admins

**Comment by todor-ivanov** [comment]
Currently we are dealing with the missing `MongoDBAsAService` instance as  explained here [1]. This thing fails completely `MSOutput` and hence `MSRuleCleaner` is unable to fetch the transfer document for any workflow and is also failing on every polling cycle: [2]. 

And this is the explanation, why we do not see any alarms the last two days, as noted in my previous comment. 

FYI @amaltaro 

[1]
https://github.com/dmwm/WMCore/issues/11439

[2]
```
2023-01-12 19:40:16,060:DEBUG:MSRuleCleaner: Dispatching workflow: cmsunified_task_HIG-RunIISummer20UL18wmLHEGEN-04474__v1_T_220603_143259_2652
2023-01-12 19:40:16,080:ERROR:MSRuleCleaner: General exception while fetching TransferInfo from MSOutput for cmsunified_task_HIG-RunIISummer20UL18wmLHEGEN-04474__v1_T_220603_143259_2652. Error: url=https://cmsweb.cern.ch:8443/ms-output/data/info?request=cmsunified_task_HIG-RunIISummer20UL18wmLHEGEN-04474__v1_T_220603_143259_2652, code=502, reason=Bad Gateway, headers={'Date': 'Thu, 12 Jan 2023 19:40:16 GMT', 'Server': 'Apache', 'Set-Cookie': 'cms-auth=10bb69bed4899872c3a954f289e202cf923aa79fd48a4a0f6c4094c72715d82cddb41160305e4960;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT', 'Content-Type': 'text/html', 'Content-Length': '150', 'CMS-Server-Time': 'D=6099 t=1673552416076228'}, result=b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 624, in getMSOutputTransferInfo
    res = self.curlMgr.getdata(url, params=params, headers=headers, ckey=ckey(), cert=cert())
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 363, in getdata
    _, data = self.request(url=url, params=params, headers=headers, verb=verb,
  File "/usr/local/lib/python3.8/site-packages/Utils/PortForward.py", line 67, in portMangle
    return callFunc(callObj, newUrl, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 353, in request
    raise exc
http.client.HTTPException: url=https://cmsweb.cern.ch:8443/ms-output/data/info?request=cmsunified_task_HIG-RunIISummer20UL18wmLHEGEN-04474__v1_T_220603_143259_2652, code=502, reason=Bad Gateway, headers={'Date': 'Thu, 12 Jan 2023 19:40:16 GMT', 'Server': 'Apache', 'Set-Cookie': 'cms-auth=10bb69bed4899872c3a954f289e202cf923aa79fd48a4a0f6c4094c72715d82cddb41160305e4960;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT', 'Content-Type': 'text/html', 'Content-Length': '150', 'CMS-Server-Time': 'D=6099 t=1673552416076228'}, result=b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
2023-01-12 19:40:16,080:ERROR:MSRuleCleaner: Unknown exception while running MSRuleCleaner thread Error: local variable 'transferInfo' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 222, in execute
    totalNumRequests, cleanNumRequests, normalArchivedNumRequests, forceArchivedNumRequests = self._execute(requestRecords)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 263, in _execute
    self._dispatchWflow(wflow)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 296, in _dispatchWflow
    self.getMSOutputTransferInfo(wflow)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 632, in getMSOutputTransferInfo
    if transferInfo is None:
UnboundLocalError: local variable 'transferInfo' referenced before assignment
2023-01-12 19:40:16,081:INFO:MSManager: Total ruleCleaner execution time: 12 secs
```

**Comment by todor-ivanov** [comment]
I hate to say it, but it seems nothing needs to be done with those alarms. After fixing the broken micro services I left them run and continue filling our mails for a week or two and now I am absolutely sure. The alarms are renewed every 48 hours as expected by definition.  And we  receive a single mail per alarm per day. (Well the last bit maybe something where we may want to search for some optimizations, but I am not sure if it worth the effort. )

The more disturbing fact is the amount of alarms we receive. Currently **1157**. All of them seem to be legitimate. Meaning, all those are workflows not archived for more than 30 days. Here I upload a full list of workflows exceeding the threshold. 
[MSRuleCleanerAlarms.txt](https://github.com/dmwm/WMCore/files/10500056/MSRuleCleanerAlarms.txt)

All of them are not archived due to one reason:  ```Additional info: Not properly cleaned workflow:```

I am inclined to close that issue and start a new `Operational` one just to investigate the reasons why those  workflows are stuck in the system. 

FYI @amaltaro 

p.s. During the investigation of this issue with the help of Ceyhun, we did come up with an easy way to fetch all the alarms from monit in a json format, suitable for parsing etc.:
```
curl -o MSRulecleanerAlarms.json  http://cms-monitoring.cern.ch:30093/api/v2/alerts\?receiver=dmwm-admins\&service=ms-rulecleaner
```

**Comment by todor-ivanov** [comment]
Just a thought here (nothing proven yet), but the amount of workflows in status `announced` but not `archived`, may be related to this issue here as well:
https://github.com/dmwm/WMCore/issues/11367

**Comment by amaltaro** [comment]
@todor-ivanov do I understand it correct that your conclusion is that we do NOT re-raise the same alert unless the expiry time (set by MSUnmerged, to 2 days) has passed?

Concerning the curl call to fetch all the active alerts for a given query string, can you please update the documentation with this? I think it would go here: https://github.com/dmwm/WMCore/wiki/Monitoring-of-CMSWEB-services-with-Prometheus-AlertManager

About #11367 , my understand so far is that workflows are actually archived while existent rules are not properly cleaned up (in some very specific use case, because it's not happening to every single workflow).

**Comment by todor-ivanov** [comment]
Hi @amaltaro 
> do I understand it correct that your conclusion is that we do NOT re-raise the same alert unless the expiry time (set by MSUnmerged, to 2 days) has passed?

Yep, it seems to be the case. We do send an email every 24 hours though, but this is not a problem in my opinion.

Documentation has been updated.

> About https://github.com/dmwm/WMCore/issues/11367 , my understand so far is that workflows are actually archived while existent rules are not properly cleaned up (in some very specific use case, because it's not happening to every single workflow).

Well that's  a good point. I'll create  a separate OPS issue, just for tracking the investigation on those  unarchived workflows. And will close this one.

**Comment by todor-ivanov** [comment]
And here is the new one: https://github.com/dmwm/WMCore/issues/11456

**Comment by amaltaro** [comment]
>Yep, it seems to be the case. We do send an email every 24 hours though, but this is not a problem in my opinion.

do we understand why an email is re-created every 24h?
