### ISSUE TITLE
COMP environment: wrong py3-future setup for aarch64 architecture

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#11401]
**Impact of the bug**
Job wrapper on aarch64 architecure. SI tests for aarch64 architecure integration (using CRAB).

**Describe the bug**
CRAB is setting up the job wrapper environment using [this](https://github.com/dmwm/CRABServer/blob/master/scripts/submit_env.sh) script (see [here](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.sh#L27-L33) for example). The same command is done by WMAgent [here](https://github.com/dmwm/WMCore/blob/73fa2c90a019f17ebe300ad103415af2fbe4fc0e/etc/submit_py3.sh#L173-L174).

In this area `/cvmfs/cms.cern.ch/COMP/rhel8_aarch64/` the python version 3.8.2 is deployed, therefore the py3-future source script `/cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/py3-future/0.18.2/etc/profile.d/init.sh` is going to look for the `python3.8` directory here `/cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/lib/` which does not exist (only python3.9 is available).

**How to reproduce it**
```
ssh mmascher@lxplus8-arm.cern.ch
...
[mmascher@lxplus8s03 ~]$ apptainer exec --bind /cvmfs /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:aarch64 /bin/bash
Singularity> echo $PYTHONPATH

Singularity> source submit_env.sh #I wget the file here https://github.com/dmwm/CRABServer/blob/master/scripts/submit_env.sh
Singularity> export REQUIRED_OS=rhel8
Singularity> setup_cmsset
======== CMS environment load starting at Thu Dec 15 09:44:02 GMT 2022 ========
WN missing VO_CMS_SW_DIR/OSG_APP/CVMFS environment variable, forcing it to CVMFS=/cvmfs/cms.cern.ch
CRAB job bootstrap: thinks it found the correct CMSSW setup script
======== CMS environment load finished at Thu Dec 15 09:44:02 GMT 2022 ========

Singularity> setup_python_comp
======== python bootstrap for stageout at Thu Dec 15 09:44:06 GMT 2022 STARTING ========
Job requires OS: rhel8, thus setting ScramArch to: rhel8_aarch64
WMAgent bootstrap: COMP Python path is: /cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external
WMAgent bootstrap: latest python3 release is: 3.8.2
Sourcing python future library from: /cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/py3-future/0.18.2/etc/profile.d/init.sh
WMAgent bootstrap: found python3 at..
/cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/python3/3.8.2/bin/python3
======== python bootstrap for stageout at Thu Dec 15 09:44:07 GMT 2022 FINISHED ========
Singularity> echo $PYTHONPATH

Singularity> echo $PYTHON3_LIB_SITE_PACKAGES
lib/python3.8/site-packages
Singularity> ls /cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/lib/
python3.9
```

**Expected behavior**
py3-future should be sourced correctly. Mismatch between pytho3 version and used py-future version should be fixed in this area `/cvmfs/cms.cern.ch/COMP/rhel8_aarch64` (which is a symlink to cc8_aarch64_gcc9).

**Additional context and error message**
Example of CRAB job that run on arm resource: https://cmsweb.cern.ch:8443/scheddmon/069/mmascher/221205_131953:mmascher_crab_testITB_ARM_2/job_out.6.2.txt

**Comment by mmascher** [comment]
BTW: I strongly support the usage of a common job wrapper environment setup script for CRAB and WMAgent :)

**Comment by amaltaro** [comment]
@mmascher Marco, thanks for creating this issue.

Just making sure I understand the issue reported, the py3-future init.sh script under the COMP area:
```
amaltaro@lxplus735:~ $ tail -n3 /cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/py3-future/0.18.2/etc/profile.d/init.sh
[ ! -d /cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/bin ] || export PATH="/cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/bin${PATH:+:$PATH}";
[ ! -d /cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/${PYTHON3_LIB_SITE_PACKAGES} ] || export PYTHONPATH="/cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/${PYTHON3_LIB_SITE_PACKAGES}${PYTHONPATH:+:$PYTHONPATH}";
```

links to the non-COMP area, which provides multiple python3 versions:
```
amaltaro@lxplus735:~ $ ls -lt /cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/python3/
total 2
drwxr-xr-x. 6 cvmfs cvmfs 27 Apr  2  2022 3.8.2
drwxr-xr-x. 6 cvmfs cvmfs 27 Apr  2  2022 3.9.6
drwxr-xr-x. 6 cvmfs cvmfs 27 Apr  2  2022 3.9.6-08d3bbf663e5ec71dd2cc6e7be45d0b0
drwxr-xr-x. 6 cvmfs cvmfs 27 Apr  2  2022 3.9.6-a09d62661fc633558039b9e68140007e
```

which finally breaks in the py3-future library in the non-COMP area (which requires python3.9):
```
amaltaro@lxplus735:~ $ ls /cvmfs/cms.cern.ch/cc8_aarch64_gcc9/external/py3-future/0.18.2/lib/
python3.9
```

I feared that this issue would eventually pop up, and it comes from the fact that COMP cannot keep up with the Scram Archs provided by the CMSSW software. 
Reason why we - with the great help of @smuzaffar - started making symlinks from COMP areas to CMSSW software area.

I don't know how we can fix it without affecting - or imposing - too much work on the CMSSW folks. But one way would be to actually remove all the dependency of the `future` library from the WMCore runtime code. 

Please let me know if you see any other alternatives.

**Comment by smuzaffar** [comment]
There are few things which we can do here.
-  If Crab/WMCore works with python 3.9 then as a quick fix I can create /cvmfs/cms.cern.ch/COMP/cc8_aarch64_gcc9/external/python3/3.9.2 symlink so that https://github.com/dmwm/CRABServer/blob/master/scripts/submit_env.sh#L104 find the latest version `3.9.2` . This will fix PYTHONPATH for py3-future. 

- if crab/WMCore does not work with python3.9 then I can change py3-future to point to `/cvmfs/cms.cern.ch/cc8_aarch64_gcc8/external/py2-future/0.18.2/lib/python3.8/site-packages`  area

**Comment by amaltaro** [comment]
Thanks for proposing these alternatives, Shahzad.

It's pretty hard to say whether WMCore would work with python 3.9.2, especially on what comes to the third-party libraries. But looking into the release changes between Python 3.9 and 3.8:
https://docs.python.org/3/whatsnew/3.9.html#removed-in-python-39

I found at least 2 issues that we need to resolve in our codebase:
* "base64.encodestring() and base64.decodestring()"
* "The encoding parameter of json.loads() has been removed"

If it's not too much work and safe for CMSSW release, I would vote for updating py3-future to use python3.8 instead.

**Comment by smuzaffar** [comment]
@amaltaro @mmascher , I have updated `/cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/py3-future/0.18.2` area so that it uses `python3.8`  . [a] works for me now, please try again and let me know if this works fro you too
[a]
```
> source  /cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/python3/3.8.2/etc/profile.d/init.sh
> source /cvmfs/cms.cern.ch/COMP/rhel8_aarch64/external/py3-future/0.18.2/etc/profile.d/init.sh
> python3 -c 'import future'
```

**Comment by amaltaro** [comment]
Thanks @smuzaffar !

@mmascher Marco, would you be able to give it another test?

**Comment by mmascher** [comment]
@amaltaro I think it works, my CRAB jobs have been running since 8 hours. Still waiting for them to fail the stageout lol. @smuzaffar I am not sure where we can get the gfal rpm from in the CMS images, OSG is not building them for non x86_64, and I have not find them from other repos...

**Comment by amaltaro** [comment]
@mmascher thank you for checking this, Marco. I guess we can close this issue out then, but I will wait until tomorrow morning in case something else comes up with your tests. Thanks!

**Comment by amaltaro** [comment]
Shahzad, thank you again for making these changes! We are trying to deprecate the `future` library in the next WMAgent production release (or the one after it, ~May/2023).

Marco, if something comes up in your tests, feel free to report and reopen this issue. Based on your previous comment, I consider this to have been fixed, so I am closing this out. Thanks!
