### ISSUE TITLE
Pypi-based ReqMgr2 image failing to load the Web UI templates

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11405]
**Impact of the bug**
ReqMgr2 (Pypi image)

**Describe the bug**
ReqMgr2 based on version `2.1.6rc3` fails to load workflows through their web UI (also linked from WMStats). An example url is:
https://cmsweb-test9.cern.ch/reqmgr2/fetch?rid=amaltaro_TC_PY3_ProdPsi_Agent214_Val_221214_222102_4629

and the error in the browser is:
"Template main not known"

Traceback from the component log is available in [1]

**How to reproduce it**
Open any workflow link in ReqMgr2, using the PyPi-based image (e.g. 2.1.6rc3)

**Expected behavior**
Templates need to be shipped with the Pypi package and properly available where the configuration expects to find them (see reqmgr2 config.py file).

**Additional context and error message**
[1]
```
[16/Dec/2022:13:02:34] reqmgr2-554998ddb8-wsjxl xxxxxx "GET /reqmgr2/data/request?_nostale=true&name=amaltaro_TC_PY3_ProdPsi_Agent214_Val_221214_222102_4629 HTTP/1.1" 200 OK [data: 4603 in 2289 out 61693 us ] [auth: OK "xxx" "" ] [ref: "" "WMCore.Services.Requests/v002" ]
[16/Dec/2022:13:02:35] reqmgr2-554998ddb8-wsjxl xxxx "GET /reqmgr2/data/splitting/amaltaro_TC_PY3_ProdPsi_Agent214_Val_221214_222102_4629 HTTP/1.1" 200 OK [data: 4569 in 800 out 97790 us ] [auth: OK "xxxxxx" "" ] [ref: "" "WMCore.Services.Requests/v002" ]
[16/Dec/2022:13:02:35] TemplatedPage doc not found at /data/srv/current/apps/reqmgr2/data/html/ReqMgr/templates
[16/Dec/2022:13:02:35] TemplatedPage menu not found at /data/srv/current/apps/reqmgr2/data/html/ReqMgr/templates
[16/Dec/2022:13:02:35] TemplatedPage generic not found at /data/srv/current/apps/reqmgr2/data/html/ReqMgr/templates
[16/Dec/2022:13:02:35] TemplatedPage main not found at /data/srv/current/apps/reqmgr2/data/html/ReqMgr/templates
```

**Comment by vkuznet** [comment]
Where the fix should go? I see two routes here:
- adjust setup.py to supply required aux files within reqmgr2 package
- adjust Dockerfile to get required aux files to build image

Which one do you foresee to use in a fix?

**Comment by amaltaro** [comment]
I think the first option would be better, such that the Pypi package has all that we need to run this service.
I haven't started looking into this, but let me know if you plan to work on this such that we don't duplicate work.

**Comment by vkuznet** [comment]
@amaltaro , turns out the templates are in pypi image, e.g.
```
kbash dmwm reqmgr2-554998ddb8-wsjxl

_reqmgr2@reqmgr2-554998ddb8-wsjxl:/data$ ls /usr/local/data/html/ReqMgr/templates/
admin.tmpl    assign.tmpl   confirm.tmpl  error.tmpl        index.tmpl  menu.tmpl      validate.tmpl
apis.tmpl     batch.tmpl    create.tmpl   filter_sort.tmpl  json        requests.tmpl  workflow.tmpl
approve.tmpl  batches.tmpl  doc.tmpl      generic.tmpl      main.tmpl   search.tmpl
```
They are installed under /usr/local path instead of RPM based `/data/srv/current/apps/reqmgr2` area. Therefore, what is required is either:
- change config to use proper location of aux files, or
- adjust run.sh script to copy or link aux files from /usr/local to /data/srv/current/apps/reqmgr2

Which approach would you like to proceed.

**Comment by amaltaro** [comment]
Thanks for checking this, Valentin.

I was going to say to go with the second option (thus copying files over to /data/srv/current...) for backwards compatibility with the RPM model, but it's likely better to go with:

> change config to use proper location of aux files, or

such that we don't have to change things again in a month or two from now. What do you think?
If you agree, please provide merge requests to services_config under all the three branches: test, preprod and prod (even though we should merge only the test one right now).

**Comment by vkuznet** [comment]
In my view, if you want to test things together, i.e. side-by-side RPM deployment and pypi one, then you need both options since configs will only work one type of deployment, right now they are working for RPM based deployment but do not for pypi. If we change config to use /usr/local location then RPM based deployment will be broken.

So, I suggest to make a soft link in pypi deployment from /usr/local/data to /data/srv/current/data (or whatever) and keep config as they are. When we'll be ready to switch to pypi the config can be changed but it will not break RPM based deployment, and soft link is not a copy and we can keep it around after the switch just in case.

**Comment by amaltaro** [comment]
Sounds good to me. Please make sure there is a comment made together with these changes such that we can come back to this in the near future.

**Comment by vkuznet** [comment]
You may use this tag `pypi-20221219-base` which includes changes to `run.sh` for creating a link. I redeployed it on test9 and here is how reqmgr2 looks like in a browser now: 
![Screen Shot 2022-12-19 at Dec 19, 3 11 07 PM](https://user-images.githubusercontent.com/125138/208512744-391eefe9-b391-4be3-b854-a07a5c895c33.png)

So, I would assume the issue can be closed.

**Comment by amaltaro** [comment]
Can you please, as usual, provide the relevant changes required for this fix? I am going to check services in the test9 cluster.

**Comment by vkuznet** [comment]
The changes went to CMSKubernetes repo went into this https://github.com/dmwm/CMSKubernetes/commit/1c713b989bf6d8198453c9e7113d23e82b32b34a . Then, I rebuild the images, built new base tag, applied new base tag to all pypi based packages in this commit: https://github.com/dmwm/CMSKubernetes/commit/7a4ca2dc030b91ad66b8d61caead6094c53efdc6 and pushed all images to registry.

**Comment by amaltaro** [comment]
Thanks! I've done further tests and it seems to be all working fine now. With that, we can close this one out.
