### ISSUE TITLE
CDR: consolidation of GPU workflows in central production

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11410]
**Impact of the new feature**
WM in general

**Is your feature request related to a problem? Please describe.**
Even though GPU workflows have been supported by WMCore since the end of 2021, there are still areas that need enhancement and further integration with the WM system. For instance:
* support to GPU steps within a StepChain workflow
* workqueue and queue prioritization
* hybrid TaskChain workflows (only with a sub-set targeting GPUs)
* GPU resource discovery and management (including proper functional workflow description)
* is the current workflow and job description sufficient?

This R&D will also be important for constructing the Computing Conceptual Design Report (CDR).

**Describe the solution you'd like**
This issue is meant to provide us with possible policies, new - or to be changed - parameters used for the job and workflow description, system to be used as a resource catalog for GPUs, ideas of how to deal with some of the cases listed above.

It's expected to have a few more GH issues created as a follow up of this one, pointing us to concrete systems and required developments to be carried within the WM system (or to be communicated to other areas, if required) 

**Describe alternatives you've considered**
Note that GPU workflows are already supported by ReReco and TaskChain specs.

**Additional context**
None

**Comment by khurtado** [comment]
I will start writing down a document regarding GPUS (what's missing in the WM framework, in HTCondor -if anything-, fair share considerations, in the CMSSW framework, etc) in more detail

**Comment by khurtado** [comment]
Closing this ticket with [doc](https://docs.google.com/document/d/1dU7U14TgHOx15UJ8-Sy6JJPN-zw4S-Aj2gyVaQFSLL4)
