### ISSUE TITLE
[MS] Define MSPileup RESTful endpoint and actions for pileup data

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11425]
**Impact of the new feature**
 New WMCore microservice

**Is your feature request related to a problem? Please describe.**
Creation of a new microservice to make pileup management more efficient and easier.
Subtask of https://github.com/dmwm/WMCore/issues/9779

**Describe the solution you'd like**
In addition to the `status` and `info` standard REST APIs, we should provide a way to privileged users and systems to be able to create, read, update and delete pileup ids (CRUD operations).

My suggestion is to provide a new `pileups` endpoint, likely under `ms-pileup/data/pileups` and perform an action according to the HTTP method (and possibly data provided) executed, such as:
* GET: provided a pileup id, return its definition in the database (or empty dictionary if none).
* POST: provided an input json object, it creates a new pileup data structure. The structure needs to go under some validation; and the user need to have enough privileges for that.
* PUT: provided an input json object, it updates an already existent pileup data structure. Validation over the input data needs to be performed, and the user needs to have enough privileges for such operation as well. 
* DELETE: provided a single pileup id, it deletes that pileup structure from the database. User (or machine) needs to have super powers to execute it.

Sending and receiving data should be done with JSON objects (Content-Type: application/json).

On what concerns the validation, CRIC roles should be used for the moment. The service configuration file has to support a definition of group/roles and what actions they can perform.

**Describe alternatives you've considered**
The DELETE action should likely be done only by the system, after a grace period of inactivity has passed (after the pileup id has been active:False for some long period of time).

**Additional context**
None

**Comment by vkuznet** [comment]
In addition to outlined tasks, I suggest to add support for data-streaming via `application/ndjson` data-format. The data-streaming together with static data-structure, see https://github.com/dmwm/WMCore/issues/11424#issuecomment-1375569830, will allow to keep under bare minimum resource utilization (proven to be the case in DBS implementation), and achieve flexibility, e.g. client can fetch only portion of data (useful for data visualization, monitoring or even data processing in chunks).

**Comment by amaltaro** [comment]
After deploying services with 2.1.7rc3 in testbed, I see that most of the microservices fail to start up with an exception like:
```
[02/Feb/2023:19:47:54]  INFO: loading ui into /ms-transferor

FrontPage static content: /usr/local/lib/python3.8/data/
[02/Feb/2023:19:47:54]  INFO: loading data into /ms-transferor/data
[02/Feb/2023:19:47:54]  ERROR: terminating due to error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 441, in start_daemon
    self.run()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 502, in run
    self.install_application()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 279, in install_application
    module = __import__(module_name, globals(), locals(), [class_name])
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/RestApiHub.py", line 16, in <module>
    from WMCore.MicroService.Service.Data import Data
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/Data.py", line 55, in <module>
    from WMCore.MicroService.MSPileup.MSPileup import mspileupError
ModuleNotFoundError: No module named 'WMCore.MicroService.MSPileup'

[02/Feb/2023:19:47:54]  WATCHDOG: server exited with exit code 1
```

which seems to come from the Data.py module, that imports something from the MSPileup module. Problem is, MSPileup module is only available in the MSPileup microservice.

**Comment by vkuznet** [comment]
Alan, I remember that you asked me in your review to move `mspileupError` from `Data.py` to `MSPileup.py` module :) The fix should be trivial to put it back to `Data.py`. I can provide PR for this.
