### ISSUE TITLE
[MS] Create monitoring dashboard for MSPileup microservice

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11429]
**Impact of the new feature**
New WMCore microservice

**Is your feature request related to a problem? Please describe.**
Creation of a new microservice to make pileup management more efficient and easier.
Subtask of https://github.com/dmwm/WMCore/issues/9779

**Describe the solution you'd like**
This is a joint ticket between the WMCore and the CMS Monitoring team, such that we can define and provide a monitoring dashboard for the MSPileup. So, relevant JIRA ticket might have to be created to get the usual process monitoring, as we have for the other WMCore microservices.

**Describe alternatives you've considered**
We can eventually consider service specific metrics as well, but I'd call that to be an future enhancement and we can properly define that in the future.

**Additional context**
None

**Comment by vkuznet** [comment]
There are two types of monitoring:
- service monitoring metrics, e.g. CPU/RAM, etc. provided via Prometheus `process_exporter` which we start in `dmwm-base` image via `/data/monitor.sh` script. The corresponding dashboard can be found [here](https://monit-grafana.cern.ch/d/JIz-EqvVz/wmcore-ms-services?orgId=11&refresh=1m&var-env=k8s-test10&var-service=All&var-app=All) (please choose appropriate env, service, etc.). But at the moment it is not functional due to pending issue https://github.com/dmwm/WMCore/issues/11454. Once new images will start properly `/data/monitor.sh` script the data will automatically appear in that dashboard.
- and, ms-pileup data monitoring which should push data into MONIT infrastructure. The corresponding PR https://github.com/dmwm/WMCore/pull/11478 provides first draft for this service. I envision that we'll push pileup documents to MONIT such that we'll organize another data base dashboard (similar to WMArchive one) with relevant meta-data information. For that I need an additional input/feedback.

@amaltaro , please review both options and provide your feedback. The former one will be done automatically once we'll get new images with `/data/monitor.sh` script, see https://github.com/dmwm/WMCore/issues/11454. The second one is more complex as it requires a decision of what should be push to MONIT infrastructure, which index to apply and how to organize a dashboard with relevant information. This is based on meta-data schema, i.e we can push MSPileup docs as is, or we may perform intermediate aggregation in MSPileupe MongoDB backend and push it to MONIT. Therefore, an additional feedback is required from you to understand what kind of information will be required for that.

**Comment by amaltaro** [comment]
@vkuznet having the first monitoring - process based - is a must and I understand it will be covered as soon as we fix the outstanding issue with monitor.sh

The second one is optional, but having data in ES would indeed be helpful to build a construct some data visualization based on the actual MongoDB documents. I don't have anything solid in my mind, but I think we should:
1. upload the original pileup document to ES (only a few times a day, given that we should not expect more than a handful of pileup changes a day)
2. aggregate pileup size per campaign (do we need to pre-aggregate it on the client side, or we just do that in grafana?)
  * thus relying in the document `pileupSize`, `campaigns` and `active`
3. aggregate pileup size per expected RSE (do we need to pre-aggregate it on the client side, or we just do that in grafana?)
  * thus relying in the document `pileupSize`, `expectedRSEs` and `active`
4. aggregate pileup size per current RSE (do we need to pre-aggregate it on the client side, or we just do that in grafana?)
  * thus relying in the document `pileupSize`, `currentRSEs` and `active`

These are the 4 custom visualizations that I can think of right now. On what concerns RSEs, given that that is a list, we might have to do some pre-processing before posting it to AMQ.

**Comment by vkuznet** [comment]
Alan, thanks for provided use-case. I opened [CMSMONIT-529](https://its.cern.ch/jira/browse/CMSMONIT-529) ticket to proceed with ES setup. It will take some time on CMS Monitoring/MONIT sides and I foresee that this issue will not be completed within Q1/23 as it will require lots of coordination between groups.

Said that, the MSPileup service monitoring is already in place once I redeployed MS services on testbed with `2.2.0rc3` and you can see its dashboard over [here](https://monit-grafana.cern.ch/d/JIz-EqvVz/wmcore-ms-services?orgId=11&refresh=1m&var-env=k8s-preprod&var-service=process_exporter_ms_pileup&var-service=process_exporter_ms_pileup_tasks&var-app=All&from=now-30m&to=now)

**Comment by vkuznet** [comment]
I'm still working on this issue and need to follow with Monitoring group, once we'll get working dashboard I'll still need to ensure data flow to MONIT.

**Comment by vkuznet** [comment]
According to https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF2261450:
```
   Hi Valentin,

   The things seem better now and you can start sending data.
   Let me know once done, so that I can create the index pattern in
   Opensearch.
   Thank you and apologise for the many required actions from your side!

   Cheers,
   Nikolay
```
So, we can start feeding MSPileup data to MONIT. Said that, we still need a dashboard.

**Comment by vkuznet** [comment]
FTI @amaltaro , @todor-ivanov , I want to update everyone that now we have first draft of monitoring dashboard for MSPIleup, please find it [here](https://monit-grafana.cern.ch/d/EOb3BlLVz/dmwm-mspileup?orgId=11). Ceyhun and I finished integration with MONIT and he came up with this dashboard. I understand that we may need to change it further but the whole pipeline (MSPileup data are send to MONIT ES, MONIT queue/index is integrated into CMS Monitoring and grafance dashboard use new data-source) are in place and we can start using it for our needs.

I suggest that @amaltaro and @todor-ivanov will evaluate the dashboard and suggest the improvements. Then we can request them in [CMSMONIT-529](https://its.cern.ch/jira/browse/CMSMONIT-529) ticket.

Now, if you agree, we may close this ticket as integration part is done, and the rest (plots) will only require changes to CMS MONIT side. Please feel free to send MSPileup data on testbed and we should see them in new dashboard.

**Comment by amaltaro** [comment]
Valentin, I would prefer to close this once we:
1) have the required credentials available for preprod and prod (please provide the required services_config MR)
2) have the service configuration updated to use these credentials
3) agree on a basic preprod grafana dashboard (I have to suggest some improvements to the initial dashboard)
4) clone the preprod dashboard to production

I am going to update the services_config prod soon with the latest cluster MongoDB credentials, so make sure you rebase your changes properly.

**Comment by vkuznet** [comment]
fine with me

**Comment by amaltaro** [comment]
@vkuznet Valentin, I provided some feedback on the CMSMONIT ticket. Could you please try to follow that up this week such that we can close this issue out?

**Comment by amaltaro** [comment]
> have the required credentials available for preprod and prod (please provide the required services_config MR)

@vkuznet Valentin, do we need to request new credentials for the production service and set it up in AMQ/MonIT? If so, can you please get started with this?

**Comment by vkuznet** [comment]
The AMQ/MONIT credentials for testbed and prod are the same, we can just copy credentials from testbed branch to production branch.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I think the current `prod` secrets only provide the MongoDB credentials. Can you please then update it by passing the AMQ as well. I have already taken care of `preprod` in the past days/week.

**Comment by vkuznet** [comment]
Here they are: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/208

**Comment by vkuznet** [comment]
Alan, Ceyhun adjusted dashboard based on your feedback and we fixed credentials. I think everything is done on WMCore side and we may close this issue. If anything needs to be done in dashboard itself it is better to ask this directly on CMS Monitoring ticket https://its.cern.ch/jira/browse/CMSMONIT-529 and not here, and if any follow up needs to be done it is better to follow on their ticket directly.

**Comment by amaltaro** [comment]
@vkuznet Valentin, how about we ask Ceyhun to migrate that dashboard to production grafana, add a link to the frontpage of CMS Monitoring, consume production data, and then share that dashboard with others (e.g., P&R and DM teams)? This way we can collect further feedback and see what modifications Ceyhun is able to apply.

If you can follow the remaining activity in the CMSMONIT ticket, then I think this ticket can be closed. Thanks

**Comment by vkuznet** [comment]
that's fine by me.

**Comment by amaltaro** [comment]
Right then, let us close this issue! Thanks Valentin

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please reach out to the CMS Monitoring team and ask them to include the relevant `ms-pileup` pattern to the cmsweb-timber-k8s grafana dashboard? This is the dashboard:
https://monit-grafana.cern.ch/d/cmswebk8s-timber/cmsweb-timber-k8s?orgId=11&var-system=acdcserver&var-system=couchdb&var-system=ms-monitor&var-system=ms-output&var-system=ms-rulecleaner&var-system=ms-transferor&var-system=ms-unmerged&var-system=reqmgr2&var-system=reqmgr2ms&var-system=reqmon&var-system=wmstatsserver&var-system=workqueue&var-method=All&var-api=All&var-code=All&var-metadataType=All&var-Filters=data.code%7C%3E%7C99&var-dnFilter=.*&var-copy_of_system=All&var-dbs_deployment=All&var-dbs_instance=All&var-dbs_dbs=All&var-cluster=cmsweb&var-cluster=cmsweb-prod&var-env=All&var-port=All&var-Bin=1d&var-agent_name=All&var-agent_version=All&var-common_filter_var=NOT+data.code%3A%28401+OR+403%29&from=1680619566952&to=1683211566952

and right now we are not able to filter `ms-pileup` (or `ms-pileup-tasks`) HTTP requests.

**Comment by amaltaro** [comment]
@vkuznet nevermind! I found issues with some of those patterns, so I will report everything in a JIRA ticket.

**Comment by amaltaro** [comment]
One of the patterns was actually a false alarm, given that it lists both reqmon and wmstatsserver. Anyways, I put it all in this JIRA ticket: https://its.cern.ch/jira/browse/CMSMONIT-538
