### ISSUE TITLE
Convert Utils package to python3-only (remove future dependency)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11421]
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
Yes, the `src/python/Utils` package is dual stack (Py2 and Py3) and it depends on the `future` library.
Now that we no longer support Python2 in WMCore, we should start cleaning up the python2 compatibility layer and reduce our dependency stack.

**Describe the solution you'd like**
Update everything under the `src/python/Utils` package such that:
* they no longer depend on the `future` library to keep compatibility with Py2 and Py3
* it supports only python3 (our official release at this very moment is 3.8.2)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by anpicci** [comment]
test please
