### ISSUE TITLE
[MS] Create a new microservice skeleton called MSPileup

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11423]
**Impact of the new feature**
 New WMCore microservice

**Is your feature request related to a problem? Please describe.**
Creation of a new microservice to make pileup management more efficient and easier.
Subtask of https://github.com/dmwm/WMCore/issues/9779

**Describe the solution you'd like**
As part of a better pileup data management within the WM system, we need to create the foundations of a new microservice called MSPileup (or any other more meaningful name). This ticket does not require any service logic to be implemented at this moment, but we should provide:
* a new subpackage/module under WMCore/Microservices
* deployment scripts under the deployment and services_config repository
* dockerfile and yaml manifest under the CMSKubernetes
* create frontend/nginx rules
* definition of this new service under the setup_dependencies.py
* automatic build and upload of this new service (via GH actions)
* REST APIs for `status` and `info` should be functional (same behavior as for the other microservices)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vkuznet** [comment]
I suggest to add to aforementioned items the following:
- add metrics to the service to be used by monitoring
- add monitoring dashboards
  - pileup status metrics, e.g. number of tasks in open state, etc.
  - service metrics, e.g. CPU/RAM utilization

**Comment by amaltaro** [comment]
That's a good suggestion Valentin. I have created another ticket for that: https://github.com/dmwm/WMCore/issues/11429
