### ISSUE TITLE
Liveness probe on pypi images is no longer working

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11451]
**Impact of the bug**
Today, during my WM shift I discovered that ms-unmerged-t1 pod is no longer produce logs. Turns out that service itself was not running, even though the pod was in a Running state. Upon investigation I found that newly create pypi images no longer contain `cmsweb-ping` tool we use for liveness probe. Therefore, all pypi images/pods which we deployed to production k8s cluster no longer have working liveness probe due missing `cmsweb-ping` tool.

**Describe the bug**
If you log into any pypi image and check for `cmsweb-ping` it is no longer there, e.g
```
kbash dmwm ms-unmer-t2t3us-58548bd496-ph9kq
Defaulted container "ms-unmer-t2t3us" out of: ms-unmer-t2t3us, ms-unmer-t2t3us-filebeat
_reqmgr2ms@ms-unmer-t2t3us-58548bd496-ph9kq:/data$ type cmsweb-ping
bash: type: cmsweb-ping: not found
```
The `cmsweb-ping` tool is Go based tool provide in `http://github.com/vkuznet/cmsweb-exporters` repository which we use to perform HTTP calls with proper authz to the services. It is used in all cmsweb services as liveness probe tool. So far it was packaged as part of cmsweb, cmsweb-monit and exporters images. Since we moved away from cmsweb image we simple overlook to port this tool into pypi based images.

**How to reproduce it**
Log in into any pypi based pod and check for cmsweb-ping tool

**Expected behavior**
Put cmsweb-ping into pypi images. Since it is Go tool, and static executable, it can be simply copied from cmsweb, cmsweb-monit or exporter image to pypi image via `COPY` command and we'll need to make sure that it is available in default PATH.

**Additional context and error message**

**Comment by vkuznet** [comment]
FYI: @amaltaro , @todor-ivanov , @khurtado

**Comment by vkuznet** [comment]
This commit: https://github.com/dmwm/CMSKubernetes/commit/574e25c2335d812de357ca84ef8c8ed2bc8b0c51 adds `cmsweb-ping` to `dmwm-base` image such that it will be present in `/usr/bin` system path for all pypi images. The new dmwm-base image tag is `pypi-20230123`. Now, it is time to rebuild all pypi images with it.

**Comment by vkuznet** [comment]
And, here is corresponding PR for pypi images: https://github.com/dmwm/CMSKubernetes/pull/1298

**Comment by vkuznet** [comment]
@amaltaro , please review changes and schedule upgrade on k8s infrastructure with new image tags.

**Comment by vkuznet** [comment]
The bot closed this issue which is wrong as it is not yet resolved on production k8s cluster. I'm re-open it.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I don't have any strong preference here, but the options I see are:
1) keep it open until it gets deployed in production (in that case, we should set the issue status to `Waiting`)
2) or close it, but just keep in mind that it's getting deployed in the next production release.

Alternatively, we could as well have tag `2.1.6` deployed to testbed and production with this new image. But I am not sure it's worth it the extra effort.

**Comment by vkuznet** [comment]
Until the issue is resolved I prefer to keep tickets open, therefore I changed the status to Waiting.

**Comment by amaltaro** [comment]
@vkuznet Valentin, WMCore central services are now running on version `2.1.8rc2` (which is the same as 2.1.8).
I connected to one of the PODs and here is the output for cmsweb-ping:
```
_reqmgr2@reqmgr2-549c6bdbfc-2k6pv:/data$ type cmsweb-ping
cmsweb-ping is /usr/bin/cmsweb-ping
```

Shall we close this issue?

**Comment by vkuznet** [comment]
yes let's close this ticket.
