### ISSUE TITLE
Support ACDC for harvesting tasks

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11458]
**Impact of the new feature**
The component(s) responsible for creating ACDC for harvesting tasks (don't know what they are)

**Is your feature request related to a problem? Please describe.**
Several weeks ago Alan reported that P&R submitted an ACDC [1] for a harvesting task and it's not supported by the system. Thus, we couldn't recover that task.

[1] https://cmsweb.cern.ch/reqmgr2/fetch?rid=request-wangz_ACDC0_Run2022A_ZeroBias_10Dec2022_230104_163506_1872 

**Describe the solution you'd like**
The issue was discussed with PDMV in our previous meeting and they stated that this is a necessary feature. 

There has been only 1 request affected by this issue so far, thus its impact is low. I'll share this ticket w/ PDMV and hopefully they can evaluate the priority of this request.

**Describe alternatives you've considered**
Can't think of any

**Additional context**
None

**Comment by amaltaro** [comment]
Given that data location might make recovery of harvesting jobs useless, I am somehow against supporting ACDCs for Harvesting jobs. The best option IMO would be to start with a brand new DQMHarvest workflow, such that we ensure all the relevant lumis will be harvested by the same job, thus avoiding incomplete stats in the DQM Gui.

**Comment by amaltaro** [comment]
@haozturk Hi Hasan, if my previous answer isn't satisfying and/or you see a reason why a recovery workflow would be better than a fresh new DQMHarvest workflow, please reopen this issue.
At this moment, I don't see a single benefit of supporting it. It can actually even cause partial statistics to be uploaded to the DQM Gui.
