### ISSUE TITLE
Update HTcondor python bindings to 10.0.1

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11464]
**Impact of the new feature**
The following feature will update the version of condor we use to submit via python (the HTCondor python bindings0

**Is your feature request related to a problem? Please describe.**
This is related to #11402. The current version we use for the bindings (9.2.0) is compatible with the HTCondor schedd 10.0.2. However, we should move eventually to the current stable release v10.

**Describe the solution you'd like**
Update the cmsdist recipe with HTCondor 10.0.1
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condorpy3.spec

UPDATE: we should try to resolve the confusion with the htcondor specs under the cmsdist repository and converge to a single one.

**Describe alternatives you've considered**
Stay with 9.2.0

**Comment by amaltaro** [comment]
@khurtado Kenyi, can you please reach out to Farrukh and someone from CERN SI to understand if this upgrade has to be considered for this quarter?

**Comment by amaltaro** [comment]
Given the known bug (already fixed) in HTCondor reported in this message:
https://github.com/dmwm/WMCore/issues/11402#issuecomment-1553227571

I think we should consider this as high priority for the next quarter.

**Comment by amaltaro** [comment]
I just managed to build HTCondor - still via the RPM system - on version 10.2.3, see:
https://github.com/cms-sw/cmsdist/pull/8582

this version should fix the `ServerTime` attribute retrieved from the schedd, which makes debugging and some agent operations a bit harder. Still to be tested though.

**Comment by amaltaro** [comment]
HTCondor python bindings version `10.2.3` has been provided in
https://github.com/cms-sw/cmsdist/pull/8582

and basic tests were successful.

@germanfgv @LinaresToine once you start working on a new T0 agent release, make sure the t0 spec gets migrated to this py3-htcondor.spec spec (instead of the condorpy3 one).
