### ISSUE TITLE
Manage auth/authz rules for MS services

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11465]
**Impact of the new feature**
We need a proper implementation of authentication and authorization rules for MS services.

**Is your feature request related to a problem? Please describe.**
The Micro-services should manage their data according to user's rules, e.g. some user may have read access while others should be able to perform write operations. Since users will interact with MS services via HTTP we need to put in place a proper implementation, configuration and management of group/roles/rules for each individual MS service.

**Describe the solution you'd like**
Implement the following:
- define schema for authentication/authorization group/roles/rules
- define a proper place for all MS configuration files, e.g. `data.authorization_rules`
- implement internal logic how to read them
- delegate rules to MS services

**Describe alternatives you've considered**
Currently there is no common approach to authorization rules/groups/roles and each MS service handles them indepedently.

**Additional context**
Part of https://github.com/dmwm/WMCore/pull/11443, see https://github.com/dmwm/WMCore/pull/11443#discussion_r1092531576

Initial rules:
- Create: create a pileup object needs to be allowed for CRIC roles [1] and [2]
- Read: read a pileup object needs to be allowed to ANY CMS user
- Update: update a pileup object needs to be allowed for CRIC roles [1] and [2]
- Delete: delete a pileup object needs to be allowed for CRIC roles [1] and [2]
[1]
```
"admin": [
        "group:reqmgr"
```
[2]
```
"production-operator": [
        "group:dataops"
      ], 
```

**Comment by vkuznet** [comment]
Here is a proposal for generic auth/authz schema and implementation for MS services.

The auth/authz schema is defined in JSON data-format as list of records, e.g.
`[ record1, record2, ...]` where individual record has the following structure
```
{"entry": "entry-value",
 "type": "<user|group|node>",
 "attr": "<role|group|rule|ip>",
 "value": "value"}
```

For example,
- user defined records
```
# define user USER with dn DN
{"entry":"USER", "type": "user", "attr":"dn", "value":"DN-of-the-user"}

# give USER role super-role
{"entry:"USER", "type": "user", "attr":"role", "value":"super-role"}

# include USER into data-ops group
{"entry": "USER", "type": "user", "attr":"group", "value":"data-ops"}

# give USER writer rule
{"entry": "USER", "type":"user", "attr":"rule", "value":"writer"}
```

- group specific records
```
# define group GROUP by e-group
{"entry":"GROUP", "type;"group", "attr":"group", "value":"e-group"}

# assign GROUP to writer rule
{"entry;"GROUP", "type": "group", "attr":"rule", "value":"writer"}
```

- or, individual node
```
# define node NODE with specific IP
{"entry": "NODE", "type;"node", "attr":"ip", "value":"IP address"}

# give node NODE robot rule
{"entry": "NODE", "type;"node", "kind":"rule", "value":"writer"}
```

- or, even define a different WMAgents and their common rules 
```
# define WMAgent by IP addresses
{"entry":"CERN1", "type": "wmagent", "kind":"IP", "value":"CERN IP address"}
{"entry":"FNAL1", "type": "wmagent", "kind":"IP", "value":"FNAL IP address"}

# include CERN WMAgent to writer and reader rules
{"entry":"CERN1", "type": "wmagent", "kind":"rule", "value":"writer"}
{"entry":"CERN1", "type": "wmagent", "kind":"rule", "value":"reader"}

# but assign to FNAL WMAgent only reader rule
{"entry":"FNAL1", "type": "wmagent", "kind":"rule", "value":"reader"}

# include ROBOT in admin role
{"entry": "ROBOT", "type": "robot", "kind":"role", "value":"admin"}
```

Such schema will allow to provide flexible auth/authz rules for different use-cases, e.g.
- give certain user specific rules and roles
- assign specific role for a given e-group
- define a node with a specific role, e.g. robot or daemon or wmagent

Once we'll enforce such schema, then the MSAuth class will read it and provide common set of APIs, e.g.
- `getRule(entry, type=None)` return rule value for given entry type where type is optional, e.g. get rule for `CERN1` WMAgent
- `getRole(entry, type=None)` return role value for given entry type
- `getSchema()` return full schema
- `checkRule(rule, entry, type=None)` check that rule is valid for given entry type
- `checkRole(role, entry, type=None)` check that role is valid for given entry type

**Comment by vkuznet** [comment]
@amaltaro , could you please review the proposed approach (see above) and let me know if you are ok with its implmentation.

**Comment by amaltaro** [comment]
@vkuznet Valentin, even though this would provide a more flexible and finer-grain auth/authz layer, we would be charged with this extra user/roles management, on top of CRIC.

In my opinion, we should rely on CRIC for the group/role vs DN mapping, and use that to decide which actions an user can take or not within the WM system. Once we get to the token era, I think most of this will have to be refactored, and then we can start with a fresh and fine-grain authz mechanism.

For the record, before you put effort reinventing anything, please keep in mind that we have this specific REST/Auth module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Auth.py

to deal with auth/authz.

Last year we had to change ReqMgr2 to also evaluate which status transition each user (associated to a CRIC role/group) is allowed to performed. The service configuration can be found here:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2/config.py
I think - for MSPileup - we won't need anything beyond than:
* who can delete a pileup configuration (likely, only admin and P*R)
* who can update a pileup configuration (likely, only admin and P*R)
* who can create a pileup configuration(likely, only admin and P*R, in the future perpahs PPD)
* read pileup is allowed to any CMS user.

**Comment by vkuznet** [comment]
Alan, I do not want re-invent the wheel and of course everything should come from CRIC. The proposal here is to unify **how** we define auth rules in MS configuration files, that's it. The actual class will use (of course) REST/Auth.py module, e.g. use `authz_match` function https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSPileup/MSPileup.py#L96 I only want unification of how we define roles/groups/rules in MS configs.

**Comment by amaltaro** [comment]
@vkuznet given the 4 bullets I mentioned in my reply above, how would you define it in the configuration file?

For the user information, we get their CRIC roles/group in the HTTP request header, which we will then try to match against what is configured in the service.

**Comment by vkuznet** [comment]
Here is how portion of configuration file will look like (for clarity I"ll add comments):
```
[
# define what alan login (as it defined in CRIC) can do
  {"entry": "alan", "type": "login", "kind": "ms-pileup-role", "value": "delete"},
  {"entry": "alan", "type": "login", "kind": "ms-pileup-role", "value": "update"},
  {"entry": "alan", "type": "login", "kind": "ms-pileup-role", "value": "create"},

# default rule for everybody
   {"entry": "", "type": "login", "kind": "ms-pileup-role", "value": "read"},

# define what PnR group (assuming it is defined in CRIC which is not yet the case):
   {"entry": "group:pnr", "type": "roles", "kind": "ms-pileup-role", "value": "create"},
etc.
]
```
Here:
- entry and type define a match or pattern we use in CRIC
- kind defines MS role, in this case it only applies to MSPIleup, but we may define any other MSXXX role, e.g. `ms-output`
- value defines HTTP/API action this entry can do

The Auth class will use HTTP header (which is parsed and matched with REST/Auth module), extract proper CMS header, e.g. login name, and see which kind of action this user can do within MS service. In other words, the CRIC defines authentication of user in FE and each user carry CRIC define roles, bu there we define which CRIC attribute (e.g. user login or group) can do specific MS action, like create, etc.

Or, of course, we can, define new groups in CRIC, change appropriate user records, and only use `authz_match` function to match the group we like.

**Comment by amaltaro** [comment]
@vkuznet Valentin, as we discussed over Zoom, we can proceed with a similar baseline schema for the authorization layer.

Here is what we started discussing - and now it has a final list of rules - for MSPileup authz:
```
authz_rules = [{"role": "admin", "group": "reqmgr", "service": "ms-pileup", "action": "create", "method": ["POST"]},
               {"role": "production-operator", "group": "dataops", "service": "ms-pileup", "action": "create", "method": ["POST"]},

               {"role": "admin", "group": "reqmgr", "service": "ms-pileup", "action": "create", "method": ["DELETE"]},
               {"role": "production-operator", "group": "dataops", "service": "ms-pileup", "action": "create", "method": ["DELETE"]},

               {"role": "admin", "group": "reqmgr", "service": "ms-pileup", "action": "update", "method": ["PUT"]},
               {"role": "production-operator", "group": "dataops", "service": "ms-pileup", "action": "update", "method": ["PUT"]}]
```

Note that GET calls - reading-only data -, well and potentially POST too does not require any special CRIC roles/groups. Any CMS user should be allowed to see those documents.

NOTE that all of these CRIC roles/groups come from:
https://cms-cric.cern.ch/api/accounts/user/query/list/?json&preset=roles

**Comment by amaltaro** [comment]
@vkuznet feel free to add this to the initial description, but here is my opinion on the initial authz rules for MSPileup CRUD operations:
* Create: create a pileup object needs to be allowed for CRIC roles [1] and [2]
* Read: read a pileup object needs to be allowed to ANY CMS user
* Update: update a pileup object needs to be allowed for CRIC roles [1] and [2]
* Delete: delete a pileup object needs to be allowed for CRIC roles [1] and [2]

Please let me know if you need any other information on this.

[1]
```
"admin": [
        "group:reqmgr"
```

[2]
```
"production-operator": [
        "group:dataops"
      ], 
```

**Comment by amaltaro** [comment]
Given that the granularity and cases is pretty small, I would suggest to use the service configuration file.
If it ever gets to complicated, I understand that the current implementation would accept even a json file with the relevant rules. For now, let's just use the configuration file though.

BTW, given that you are changing some of those, you might want to provide these rules as well.

**Comment by amaltaro** [comment]
Reopening it, as the final integration of MSAuth module into MSPileup CRUD operations (REST endpoints) is still required.
Relevant configuration changes are still to be provided in services_config repository as well.
