### ISSUE TITLE
Make DBS objects `created_by` attribute configurable DBSUpload

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#11494]
**Impact of the new feature**
T0, WMAgent, DBS

**Is your feature request related to a problem? Please describe.**
Currently, there is no direct way to distinguish files created by T0, from files created by central production. Similarly, it is not possible to directly filter Replay generated files from production files. Thius is because the `created_by` field in DBS is always set to `WMAgent`, as can be seen here: [/WMComponent/DBS3Buffer/DBSBufferBlock.py#L70](https://github.com/dmwm/WMCore/blob/fea1de4119a9091233f3e6414f33f069971b5a74/src/python/WMComponent/DBS3Buffer/DBSBufferBlock.py#L70)

**Describe the solution you'd like**
Created a new DBSUpload parameter in the WMAgent configuration called `UploaderName`, that defaults to `WMAgent`, but can be configured to `T0Prod` or `T0Replay`. This attribute would be used to fill the `created_by` and `last_modified_by` fields on DBSUpload.

**Describe alternatives you've considered**
Other existing fields can be use to make to distinguish T0 and Central production files, like origin_site_name, as T0 uses T0_CH_CERN_Disk. Nonetheless, this correlation is circunstantial and cannot be guaranteed, specially when it comes to Replay data. Other combinations of filters can be used in specific situations, like keywords in dataset names or lfn, but we would like to have a direct disctinction at file level.

**Additional context**

**Comment by germanfgv** [comment]
@vkuznet @amaltaro what do you think about this? It should be a simple enough development, I'd take care of it, but I'd like to know your opinion.

**Comment by vkuznet** [comment]
+1 from my side, and I'm in favor of removing hardcoded value in https://github.com/dmwm/WMCore/blob/fea1de4119a9091233f3e6414f33f069971b5a74/src/python/WMComponent/DBS3Buffer/DBSBufferBlock.py#L70 and pass it as an input argument to this class with that default. Then, check who calls this class and adjust accordingly (in addition to proposed changes to DBSUpload)

**Comment by germanfgv** [comment]
I have a question @vkuznet checking a file info in DAS, I see 2 similar attributes: 'create_by' and `created_by`. Is this on purpose? I only see 'create_by' in WMCore code. 

They seem to show the same information:
https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fbackfill%2F1%2Fdata%2FTier0_REPLAY_2023%2FCosmics%2FRAW%2Fv23194233%2F000%2F363%2F818%2F00000%2Fca49d9c5-9836-4f85-b97d-38af91067fbe.root&instance=prod/global

Same thing happens with `last_modified_by` and `modified_by`.

**Comment by vkuznet** [comment]
@germanfgv , DAS is not authoritative source of information as it ask other providers about it, e.g. DBS, Phedex (in a past), Rucio, etc. As such it needs to collect data from multiple of them and those providers may not have common schema and naming convention. As such DAS re-map attributes from different providers to a common set. I do not recall out of my head about create attributes, but most likely they come from different systems. Said that, you should only care about primary source of information, in this case DBS and here is what its schema provides:
```
scurl -s "https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader/files?logical_file_name=$lfn&detail=true" | jq
[
  {
    "adler32": "fe9bd9d9",
    "auto_cross_section": 0,
    "block_id": 32181945,
    "block_name": "/Cosmics/Tier0_REPLAY_2023-v23194233/RAW#e5449eae-96e8-4450-83dd-4ed2fada6ecc",
    "branch_hash_id": null,
    "check_sum": "96126024",
    "create_by": "T0Replay",
    "creation_date": 1677179627,
    "dataset": "/Cosmics/Tier0_REPLAY_2023-v23194233/RAW",
    "dataset_id": 14643476,
    "event_count": 0,
    "file_id": 2754776317,
    "file_size": 125005,
    "file_type": "EDM",
    "file_type_id": 1,
    "is_file_valid": 1,
    "last_modification_date": 1677179627,
    "last_modified_by": "T0Replay",
    "logical_file_name": "/store/backfill/1/data/Tier0_REPLAY_2023/Cosmics/RAW/v23194233/000/363/818/00000/ca49d9c5-9836-4f85-b97d-38af91067fbe.root",
    "md5": null
  }
]
```
