### ISSUE TITLE
Setup proper mandatory/optional values for MSPileup document

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11498]
**Impact of the bug**
We got initial feedback from data-ops about MSPileup services and Alan summarized mandatory, optional and service attributes in MSPileup requirement [document](https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Pileup). We should incorporate them into MSPileupObj.py module.

**Describe the bug**
Current implementation of MSPileupObj.py have current defaults for some of the mandatory attributes, and we should revisit all defaults for optional ones and ensure proper values for services attributes.

**How to reproduce it**
Read [MSPileupObj.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py) code for data assingment.

**Expected behavior**
Have proper set of mandatory, optional and service attributes according to requirement [document](https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Pileup).

**Additional context and error message**

**Comment by vkuznet** [comment]
This issue is partially fixed in https://github.com/dmwm/WMCore/pull/11487 PR via this commit https://github.com/dmwm/WMCore/pull/11487/commits/4aa8611dc88610eda5068a91abead1b36e32b98a and

**Comment by vkuznet** [comment]
First round of changes went into this PR: https://github.com/dmwm/WMCore/pull/11497, and second one in this one: https://github.com/dmwm/WMCore/pull/11499

**Comment by vkuznet** [comment]
Since we merged this PR https://github.com/dmwm/WMCore/pull/11499 we may safely close this issue. @amaltaro if you agree please close it.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/11499
