### ISSUE TITLE
MSPileup configured to use the same port as Reqmon

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11490]
**Impact of the bug**
MSPileup

**Describe the bug**
While reviewing this PR:
https://github.com/dmwm/CMSKubernetes/pull/1314

Imran noticed that MSPileup has been configured to use the same port as reqmon (wmstatsserver).

**How to reproduce it**
Check their configurations in services config:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/reqmgr2ms-pileup/config.py#L36
and
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/reqmon/config.py#L27

**Expected behavior**
I believe the HTTP team has documented the services port allocation. So we should ask for that document, pick an available port and update it in all the relevant places. A non-exhaustive list is:
* `services_config` repository (both test and preprod branch)
* configurations in the `deployment` repository for frontend, redirect rules, monitoring
* `CMSKubernetes` manifests and anything else defined for ms-pileup with the explicit port
* ask the HTTP team to update their documentation as well. 

and anything else that I might have missed.

**Additional context and error message**
Complement for: https://github.com/dmwm/WMCore/issues/11423

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please look into this and communicate with the HTTP on whatever is needed? Thanks

**Comment by vkuznet** [comment]
The service is working now:
```
scurl https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/status
{"result": [
 {
  "wmcore_version": "2.1.7",
  "microservice_version": "2.1.7",
  "microservice": "MSManager",
  "status": "OK",
  "thread_id": "MSPileup",
  "start_time": "Fri, 17 Feb 2023 13:42:12 UTC",
  "end_time": "Fri, 17 Feb 2023 13:42:12 UTC",
  "execution_time": 0.000161,
  "error": "",
  "total_num_pileups": 0,
  "total_num_rules": 0
}]}
```
and we can even query the data:
```
scurl https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup?campaigns=test
{"result": [
 {
  "pileupName": "/sdkjfhsdkf/klsjdflksdj/PREMIX",
  "pileupType": "classic",
  "insertTime": 1675707397,
  "lastUpdateTime": 1675707397,
  "expectedRSEs": [],
  "currentRSEs": [],
  "fullReplicas": 1,
  "campaigns": [
    "test"
  ],
  "containerFraction": 0.5,
  "replicationGrouping": "ALL",
  "activatedOn": 1675707397,
  "deactivatedOn": 1675707397,
  "active": true,
  "pileupSize": 0,
  "ruleList": []
}]}
```

@amaltaro feel free to close the ticket.

**Comment by amaltaro** [comment]
Great, thank you for the prompt action, Valentin!
I moved this issue status to "In Progress" and I am closing this out now, as all the relevant changes have been made in different repositories.
