### ISSUE TITLE
[MS] Redefine MSPileup document deletion logic

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11514]
**Impact of the new feature**
MSPileup

**Is your feature request related to a problem? Please describe.**
While discussing about this service with Hasan and Todor today, we noticed that we cannot really trigger a document deletion upon a DELETE request. 

Reason for that is very simple - and overlooked - if a document is removed from the database backend, then there is nothing that the service can act on for that pileup. In other words, we would be potentially leaving Rucio rules behind and we would never be able to clean those up automatically. Hence, we need to redefine that logic, see below.
 
**Describe the solution you'd like**
Upon a DELETE HTTP request, MSPileup should not really delete the relevant pileup object. Instead, it should update the following pileup attributes:
* `deactivatedOn`: the server will define it according to the service documentation (thus an integer with the epoch time)
* `active`: False (boolean)

which will then allow MSPileup to fetch it in the next service polling cycle and properly delete any outstanding Rucio rule.
 
**Describe alternatives you've considered**
Remove the HTTP DELETE method, thus no longer support it, and enforce users to update the document accordingly (when a deletion is required).

**Additional context**
Related to: https://github.com/dmwm/WMCore/issues/11425

**Comment by vkuznet** [comment]
Alan, I doubt that your described procedure is complete. From my understanding we need to introduce a `state` attribute into the schema. The state should indicate transition states, e.g. active state, non-active state, when rules are deleted, and when document is ready for eviction. What you describe is only partially address this. For instance, when we'll delete Rucio rules we should account for failures. And, you do not want to to keep outdated documents in backend DB either. Therefore, I see that we need the following:
- introduce state attribute or re-use existing (combination) to clearly define state of transition, e.g. document is no longer in use but Rucio rules are not delete yet
- provide all possible states and define them accordingly
- define rules for MSPileup how to deal with certain state
- add new cleanup task which will wipe out docs which have certain state, e.g. when Rucio rules deletion is successful

Once all of these requirements will be in place we can decide how to implement them. But in my view, what you want is update of the documents and we need periodic cleanup task to delete docs which are fully processed and their Rucio rules are deleted.

**Comment by amaltaro** [comment]
@vkuznet we already have everything that we need in the current document schema, such as:
* `active`: will tell the current state of the pileup object
* `deactivatedOn`: will tell when it was last deactivated (we should probably have a protection for disabling an already disabled pileup, but can be done in the future, I guess)
* `ruleIds`: list of known rule ids
* `currentRSEs`: likely redundant with `ruleIds`, but will say where we currently have this pileup locked at.

Having said that, I see no need to have another parameter containing state transition.

On what concerns the archival of pileup objects, Hasan was considering to keep documents for a little while such that we/they can check some of the history as well. I do think that we will need a cleanup task though, and I would suggest to implement that in the future and with a separated GH issue.

**Comment by vkuznet** [comment]
Alan, as I wrote the state attribute may be optional, we can use whatever we have, but please clearly define conditions when we can clean-up document. What I need to know is which query to place using attributes above to fetch docs which we need to delete in clean-up thread.

Said that, please carefully evaluate use-case for DELETE API. I still think it will be useful since we may manually need to delete stuff. I'm not against to remove it from the code, but remember we may only change auth/authz rules and restrict delete to specific group of people which may be different from one who write to MSPileup. So, please evaluate this use-case as well and let me know how we should proceed.

**Comment by amaltaro** [comment]
> What I need to know is which query to place using attributes above to fetch docs which we need to delete in clean-up thread.

My opinion is that the DELETE functionality should be refactored according to the specification in the beginning of this issue, thus not deleting the document but only updating attributes. Perhaps we could consider passing a specific key/value pair that would force the document to be deleted right away. What do you think?

For the cleanup implementation, I do think we should address it in a different GH issue. Requirements will be simple though, something like:
* If document is `active=False`; and
* document has an empty `ruleIds` list; and
* document has an empty `currentRSEs`; and
* document has been deactivated for a while (`deactivatedOn=XXX`), to be configured in the service.
then we can delete the document.

**Comment by vkuznet** [comment]
The clean-up task is done in this PR https://github.com/dmwm/WMCore/pull/11517, and here is PR https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/194 for prod service_configs which includes authz role for non-existing group to disable DELETE API.

**Comment by vkuznet** [comment]
And, I updated [MSPileup wiki](https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Pileup) with this instructions:
```
# update MSPileup document, here we show how to set new active status for
# pileupName /abc/xyz/PREMIX workflow
curl -v -X PUT -H "Content-type: application/json" -d '{"pileupName":"/abc/xyz/PREMIX", "active":False}' \
        http://localhost:8249/ms-pileup/data/pileup
```
which explain exactly how to set new active status of specific MSPileup document.

**Comment by amaltaro** [comment]
Thank you Valentin. I am going to leave the configuration review in the MR itself.
About the documentation, I reorganized the APIs a bit and also replaced localhost:port by the actual cmsweb endpoint.
