### ISSUE TITLE
MSPileup: incomplete error message in the response; getPileup fetches all the docs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11511]
**Impact of the bug**
MSPileup

**Describe the bug**
Apologies for filing two different issues in the same GH issue, feel free to provide different commits fixing each of them.
 
Based on MSPileup 2.2.0rc1 - running in testbed - I could spot two basic functionality issues:
1) upon providing an ill pileup data structure through a POST request, the service provides a basic and standard error message [1]
2) after injecting pileup objects into the system, if you want to retrieve one of them, the service returns everything from the database [2]

**How to reproduce it**
See instructions in the extra comments

**Expected behavior**
For the validation issue, we should provide what in the document schema is wrong. In other words, which attribute fail to pass the validation, and if possible, we should also provide what that was expected to be.

For the GET call, the service should of course only return the pileup configuration for the requested pileup name.

**Additional context and error message**
[1]
```
cmst1@vocms0193:/data/srv/wmagent/current $ scurl -v -X POST -H "Content-type: application/json" -d '{"pileupName":"/Test/Test-Alan-v1/PREMIX", "pileupType": "wrong", "active": false, "expectedRSEs": ["T2_CH_CERN"]}' https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup
...
        <h2>400 Bad Request</h2>
        <p>MSPileupError: schema error, code: 7</p>
        <pre id="traceback"></pre>
```

[2]
```
cmst1@vocms0193:/data/srv/wmagent/current $ scurl -v -X GET -H "Content-type: application/json" -d '{"pileupName":"/Test/Test-Alan-v2/GEN-SIM"}' https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup
...
{"result": [
 {
  "pileupName": "/sdkjfhsdkf/klsjdflksdj/PREMIX",
...
  "pileupName": "/hasan-test-Neutrino_E-10_gun/Run3Summer21PrePremix-120X_mcRun3_2021_realistic_v6-v2/PREMIX",
...
  "pileupName": "/Test/Test-Alan-v1/PREMIX",
...
  "pileupName": "/Test/Test-Alan-v2/GEN-SIM",
```

**Comment by amaltaro** [comment]
@vkuznet Valentin, given that I will be offline for most of the day, could you please look into this?

**Comment by vkuznet** [comment]
Alan,
I'm not sure what do you mean by first item., i.e. _the service provides a basic and standard error message_. What do you expect? 

Regarding second issue you listed, it is a wrong query. Please refer to [MSPileup wiki](https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Pileup) for all details but here is the explanation:
- the HTTP GET only works for end-point parameter query, like
```
scurl -s -X GET "https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup?pileupName=/Test/Test-Alan-v2/GEN-SIM"
```, or
- if you want to provide query via POST request you should wrap it in `{"query": ...}` since POST is used for creation of documents and for querying them. so the correct way to query would be:
```
scurl -s -X POST -H "Content-type: application/json" -d '{"query" : {"pileupName":"/Test/Test-Alan-v2/GEN-SIM"}}' https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup
{"result": [
 {"pileupName": "/Test/Test-Alan-v2/GEN-SIM", "pileupType": "classic", "insertTime": 1678703665, "lastUpdateTime": 1678706514, "expectedRSEs": ["T2_CH_CERN"], "currentRSEs": [], "fullReplicas": 1, "campaigns": [], "containerFraction": 1.0, "replicationGrouping": "ALL", "activatedOn": 1678703665, "deactivatedOn": 1678703665, "active": false, "pileupSize": null, "ruleIds": []}
]}
```
In both case the service returns correct results.

Your example in fact mixed GET with POST request when you provided JSON payload and payload does not represent query one but rather a document for insertion.

So, the second item in your list is not an issue and rather incorrect usage of HTTP method/query.

**Comment by vkuznet** [comment]
For the first issue I provided a fix in this PR: https://github.com/dmwm/WMCore/pull/11512

**Comment by vkuznet** [comment]
And, a little bit of fun about your second request:
- me to ChatGPT: can I send json payload with GET HTTP request, does it allowed by HTTP standard?
- ChatGPT to me:
```
Technically, it is possible to send JSON payload with a GET HTTP request,
but it is not recommended and not commonly used. According to the 
HTTP standard, the GET request method is used to retrieve information 
from the server and it is meant to be a safe and idempotent operation.
This means that GET requests should not have any side effects on the
server or modify any data on the server.

In contrast, the HTTP standard suggests using the POST method
to send data to the server, which is meant for submitting data to be
processed by the server. POST requests are typically used to create,
update, or delete data on the server.

While sending a JSON payload with a GET request may work, 
it is not considered a good practice because it can violate 
the idempotency and safety of the GET request. Additionally, 
some web servers or proxies may have limitations on the length 
of the request URL, which could cause issues when sending large 
JSON payloads in a GET request.

So, it is recommended to use the POST method 
to send JSON payloads or any other data to the server.
```
which totally coincide with implementation I provided and my basic knowledge of HTTP. Therefore, even though it would be technically possible to implement GET with JSON payload it is not recommended by standard. And, current implementation uses POST HTTP with JSON payload like `{"query": ...}` to provide functionality you're looking for.

**Comment by vkuznet** [comment]
Alan, feel free to re-open this issue if you're not satisfied with second issue GET vs POST and we can discuss it further.

**Comment by amaltaro** [comment]
@vkuznet it's all good Valentin. I was testing a scenario that should not be expected and the wiki documents things well. Thanks
