### ISSUE TITLE
JSON Wrapper should also consistently wrap exceptions

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#1154]
The JSON Wrapper doesn't consistently wrap exceptions, and cjson raises an exception of a different type to the default json module. We should have our own encode/decode errors and raise these.

**Comment by amaltaro** [comment]
@vkuznet @ticoann should we close this one?

**Comment by ticoann** [comment]
Should we close this, Valentin?

**Comment by vkuznet** [comment]
yes
