### ISSUE TITLE
CDR: Finalize assumptions and projections on HL-LHC

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11554]
Impact of the new feature
WM in general

Is your feature request related to a problem? Please describe.
Parent issue: #11552

Describe the solution you'd like
Write all projections from HL-LHC era based on documents from:
- CMS Workflow Management Review
- CMS Phase-2 Computing Model: Update Document
- CDR: Summary of current status

Additional context
None

**Comment by amaltaro** [comment]
@khurtado Kenyi, I think we have collected all the relevant information requested in this ticket as well. A few HL-LHC metrics are changing in almost a monthly basis, but what we have collected so far should be a reasonable commitment.
Shall we close this ticket out as well?

**Comment by khurtado** [comment]
@amaltaro Yes, I agree. Let's close this ticket.
