### ISSUE TITLE
CDR: Define additional considerations regarding availability of types of resources and considerations on parameters related to pilot and job units.

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11555]
**Impact of the new feature**
WM in general

**Is your feature request related to a problem? Please describe.**
Parent issue:  #11552

**Describe the solution you'd like**
Describe different parameters/scenarios that impact WM system in terms of type of resources and job units. E.g.:

- GPUs
- Non-x86 resources
- Pilot lifetime
- Average number of cores per job
- Average number of resources 
- Disk/storage considerations
etc

**Additional context**
None

**Comment by amaltaro** [comment]
Even though it's hard to predict the future of GPUs and non-x86 resources in the experiment, I think the "Additional considerations" section properly covers these 2 items now. It's all described in the same document.

@khurtado Kenyi, can you please have a look at the latest changes and let me know what you think? We might as well have a discussion on this in the coming days.

From my side, we can declare this ticket as completed, but I will wait for your feedback.

**Comment by khurtado** [comment]
@amaltaro I agree with the GPUs and non-x86 resources part. I didn't want to close the ticket until the disk modeling part was completed though, since that part settles the Disk/storage considerations. What do you think?

**Comment by amaltaro** [comment]
I was going to say that that will naturally revisited once we deal with this ticket:
https://github.com/dmwm/WMCore/issues/11605

but looking into it carefully, it was a meta-issue with 5 tasks, which are all done by now. I think 11605 is the best place to track that, but we likely need to either a) update that ticket description to also have a deliverable - beyond the sub-tasks; or b) make another sub-task to create and collect information from the model. If we do so, then this ticket should be closed IMO.

**Comment by khurtado** [comment]
@amaltaro Very well, I have updated #11605 to include a deliverable based on the completed pending tasks.

**Comment by amaltaro** [comment]
Great! Thanks Kenyi!
