### ISSUE TITLE
Determine WMStats current limits

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11571]
**Impact of the new feature**
WM in general

**Is your feature request related to a problem? Please describe.**
This issue is part of https://github.com/dmwm/WMCore/issues/11408

**Describe the solution you'd like**
Quantify the limits of WMStats related to CouchDB load, features used that could be reduced change to extend some limits (e.g.: job failure records), number of workflows in the system, WQEs, etc.  

Describe alternatives you've considered
None

Additional context
None

**Comment by amaltaro** [comment]
In addition to evaluating the limits of the service, I think it's also important to characterize how wmstatsserver is currently used.
The CMSWEB monitoring required changes and those have been deployed in production today, see:
https://its.cern.ch/jira/browse/CMSKUBERNETES-253

Now we can see which REST APIs are accessed, how often, time to serve them, etc.

**Comment by amaltaro** [comment]
Not yet the moment to close this issue out.

I will start providing a summary here of findings, documents, fixes and so on:
* fix for the DataCacheUpdate interval configuration https://github.com/dmwm/WMCore/pull/11924
* refactor `jobdetail` REST API to make concurrent calls to CouchDB https://github.com/dmwm/WMCore/pull/11885
* documentation on the limits and some resource estimation TBD
