### ISSUE TITLE
Investigate integration HTCondor + WMAgent in a container setting

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11570]
**Impact of the new feature**
This is an R&D item to decide what the best way approach would be to integrate HTCondor with WMAgent in a containerized environment 

**Is your feature request related to a problem? Please describe.**
This is related to: #11314

**Describe the solution you'd like**
R&D in terms HTCondor + WMAgent communication.
If HTCondor is also deployed with WMAgent:
- Do we use an isolated network, or host based network? Are there any difference in limitations in terms of number of TCP connections? This would impact the number of shadows per schedd
- If HTCondor is provided somewhere else (e.g.: the regular schedds): How do we handle de authentication from the containers to the remote schedds? Do we keep 1 condor schedd per WMAgent? Do we need to handle a shared FS binded between the schedd and the container to handle the Sandbox working directories? I.e.: the condor working area that the schedd usually keeps somewhere in the schedd. We use a remote schedd, the files are written in some directory of the container, but the schedd wouldn’t have access to it unless it’s a shared FS (to verify).

**Comment by khurtado** [comment]
THis has been answered [here], hence closing this ticket.
 (https://docs.google.com/document/d/1KOLS2tJ9i8kl3PpBh5jy8YVtcp7KtIwOfhx3sYJri4o/edit#heading=h.a392kbqsgk49)

**Comment by todor-ivanov** [comment]
> THis has been answered [here], hence closing this ticket.
> (https://docs.google.com/document/d/1KOLS2tJ9i8kl3PpBh5jy8YVtcp7KtIwOfhx3sYJri4o/edit#heading=h.a392kbqsgk49)

Hi @khurtado this document is locked. Could you or @amaltaro share it at least as readable for everybody with the link? 

Thanks!
