### ISSUE TITLE
Get workflow lifetime statistics

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11607]
Impact of the new feature
WM in general

Is your feature request related to a problem? Please describe.
This issue is part of  #11605

Describe the solution you'd like
Use job index database used by monit grafana or Elastic search in order to get:
- Workflow lifetime (input vs non-input)
    - In addition to mean, min, max, get 10%, 25%, 90% distribution if possible
- Workflow lifetime for original vs recovery phase.
    - Policy for ACDC (RequestType=Resubmission)

Describe alternatives you've considered
None

Additional context
None

**Comment by amaltaro** [comment]
I created a jupyter notebook parsing workflows created in the system from `[2022,4,1]` through `[2023,4,1]`, which can be found here: https://github.com/amaltaro/WMAnalytics/blob/main/workflow_lifetime.ipynb

It provides at least the following information:
* break down of workflows that entered the system and which final state they reached (some are not yet in a final state)
* some stats for workflows that have been archived (normal-archived, aborted-archived, rejected-archived)
* some stats for normal-archived workflows that were ACDC vs non-ACDC
* some stats for normal-archived workflows for every single status from creation to archival
* more stats depending on the input data requirements
* plots with workflow distribution and percentile

Some of this information has been propagated to the document with the WM modeling metrics; and to the "CDR: Evaluation of the WM system for the HL-LHC scenario" google document as well.

I think this ticket can now be closed out, but I am happy to come back to this if further details are required.
