### ISSUE TITLE
Create a script to deploy WMAgen in a virtual env. replicating the Docker image runtime env.

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11617]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Yes, two in particular:
* T0 team are not planning to move to a docker based deployment, so we will have to provide a base similar to what we get through the Docker image inside a well defined environment, such that T0 team can continue from there on with building the rest of the deployment procedures related to the T0 code alone
* We need a flexible development setup that would allow us to test runtime code, which should also serve as a major part of  a complete debugging tool set. 

**Describe the solution you'd like**
A single script, which is supposed to
* Recreate the environment as set  in the [Dockerfile](https://github.com/dmwm/CMSKubernetes/blob/ef297b01cfc42efcc3e4d9d737e63367fb9ef69c/docker/pypi/wmagent/Dockerfile) file from the `CMSKubernetes` repository
* Run the [install.sh](https://github.com/dmwm/CMSKubernetes/blob/ef297b01cfc42efcc3e4d9d737e63367fb9ef69c/docker/pypi/wmagent/install.sh) script inside a previously created virtual environment, so that it is all preserved as set from above at  runtime as well
 
**Describe alternatives you've considered**
None. We better own this part of the deployment process and let  T0 team deal only with the part that concerns T0 code.  

**Additional context**
it is an extension to these tow issues:
https://github.com/dmwm/WMCore/issues/11564 
https://github.com/dmwm/WMCore/issues/8797
and may be considered as part of the bigger meta issue here as well:  
https://github.com/dmwm/WMCore/issues/11314

**Comment by todor-ivanov** [comment]
@germanfgv As we shortly discussed in our WMCore meeting, I added you as a co-assignee of this issue and reduced the QPrio from High to Medium. This way you or anybody from T0 may test it in your own pace so we do not exert any pressure. I have kept myself as still assigned to the issue, just in case, some quick bug fixing or minor  debugging/development is required from WMCore side.   

FYI: @klannon @amaltaro

**Comment by amaltaro** [comment]
@todor-ivanov Todor, given that this issue got demoted to medium priority this quarter and that there is no current effort in the proposed PR https://github.com/dmwm/WMCore/pull/11624, I am moving this back to the ToDo queue and unassigning you from this. Once this becomes a priority again, we can resume working on this. 

Please let me know if there is any reason not to do so and/or if I am missing anything important though.
