### ISSUE TITLE
MSUnmerged: Failing to retrieve correct RSE list for different site tiers.

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11637]
**Impact of the bug**
MSUnmerged

**Describe the bug**
While working on this issue https://github.com/dmwm/WMCore/issues/11548 to confirm the validity of a new robot certificate we are about to use in all WMCore service, we have figured out the different instances of MSUnmerged are not fetching the correct RSE list for their work. In the past we have chosen a static scalability model, where  we use one MSUnmerged instance per a set of RSEs, chosen by a mixed approach based the site's  tier level and geographical creteria. Meaning we are expected to have the following MSUnmerged instance to sites mapping:
* `msunmerged_t1` - all T1 level Disk RSEs
* `msunmerged_t2t3` - all T2 && T3 level Disk RSEs outside US
* `msunmerged_t2t3us` -  all T2 && T3 level Disk RSEs inside US

Currently in all three instances the service is running on every RSE returned by the generic RSE expression: `rse_type=DISK&cms_type=real'`. This causes repetitive actions on every site, delay in service run and maybe even preventing the service polling cycle for completing.   

**How to reproduce it**
Restarting one of the instance (e.g. `msunmerged_t1`) and looking at the initial lines of the logs for a single pooling cycle, gives us [1]. Which is not the expected RSE list for sure. 

**Expected behavior**
Every MSUnmerged instace to take care only of the set of RSEs it is supposed to work on. 

**Additional context and error message**
[1]
```
2023-07-03 13:34:14,180:INFO:MSUnmerged: Retrieved list of 89 RSEs: ['T3_IR_IPM',
 'T2_RU_ITEP',
 'T3_US_NERSC',
 'T3_US_Rutgers',
 'T2_US_Nebraska',
 'T3_KR_UOS',
 'T2_IT_Pisa',
 'T2_US_Wisconsin',
 'T3_HR_IRB',
 'T3_US_CMU',
 'T2_IN_TIFR',
 'T1_IT_CNAF_Disk',
 'T3_US_NotreDame',
 'T2_US_MIT_Buffer',
 'T3_CH_CERN_OpenData',
 'T3_IT_Trieste',
 'T3_US_Princeton_ICSE',
 'T2_RU_JINR',
 'T2_DE_DESY',
 'T2_TW_NCHC',
 'T3_US_OSU',
 'T3_TW_TIDC',
 'T3_CH_CERNBOX',
 'T3_US_UMiss',
 'T2_BR_UERJ',
 'T2_ES_IFCA',
 'T2_US_Purdue',
 'T1_RU_JINR_Disk',
 'T3_US_PuertoRico',
 'T1_UK_RAL_Disk',
 'T2_CH_CERN',
 'T0_CH_CERN_Disk',
 'T2_RU_INR',
 'T1_ES_PIC_Disk',
 'T2_RU_IHEP',
 'T3_BG_UNI_SOFIA',
 'T3_CY_UCY',
 'T2_IT_Bari',
 'T2_PT_NCG_Lisbon',
 'T3_FR_IPNL',
 'T2_PK_NCP',
 'T2_TR_METU',
...
 'T2_UK_London_Brunel',
 'T2_BE_IIHE'] Service set to process up to 200 RSEs per instance.
```

**Comment by todor-ivanov** [comment]
the things that mattered the most from the previous version of [run.sh](), were the exportation of the `$X509_USER_PROXY` variable and the substitution of the `rseExpr` inside the config file before running the service:

https://github.com/dmwm/CMSKubernetes/blob/9910d982b9b9b0f7ff57d80969b9560cacb315b1/docker/reqmgr2ms-unmerged/run.sh#L154

While the `rseExpr` itself was passed as an external parameter to the `run.sh` script:
https://github.com/dmwm/CMSKubernetes/blob/9910d982b9b9b0f7ff57d80969b9560cacb315b1/docker/reqmgr2ms-unmerged/run.sh#L34-L39

**Comment by todor-ivanov** [comment]
And here is the fix:
https://github.com/dmwm/CMSKubernetes/pull/1400 

@amaltaro Please go ahead and review the changes so we can deploy this tonight and then I can continue tomorrow with monitoring the errors and resolving https://github.com/dmwm/WMCore/issues/11658 as well

**Comment by todor-ivanov** [comment]
Thanks @amaltaro for building and deploying an image  based on the PR from here https://github.com/dmwm/CMSKubernetes/pull/1400 

And it solves both problems 
* The wrong RSE lists are fixed now. From the pod's log:
```
[13/Jul/2023:21:07:55]  MicroService entire configuration:
from WMCore.Configuration import Configuration
config = Configuration()
...
config.views.data.rseExpr = '(cms_type=real|cms_type=int)&rse_type=DISK&tier=1'
...

2023-07-13 21:07:56,276:INFO:MSUnmerged: Retrieved list of 1 RSEs: ['T1_US_FNAL_Disk'] Service set to process up to 200 RSEs per instance.
``` 
* And it also exports the proper variable for the proxy:
```
_reqmgr2ms@ms-unmer-t1-5bbf49574d-vfj87:/data$ ps auxf 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

_reqmgr+      10  0.0  0.0   5924  3372 ?        S    21:06   0:00 /bin/bash /data/run.sh -e (cms_type=real|cms_type=int)&rse_type=DISK&tier=1

_reqmgr+      71  0.0  0.0  36340 26532 ?        S    21:07   0:00 python3 /usr/local/bin/wmc-httpd -r -d /data/srv/state/reqmgr2ms -l |rotatelogs /data/srv/logs/reqmgr2ms/reqmgr2ms-%Y%m%d-m
_reqmgr+      76 70.8  0.9 2994364 281988 ?      Sl   21:07   0:11  \_ python3 /usr/local/bin/wmc-httpd -r -d /data/srv/state/reqmgr2ms -l |rotatelogs /data/srv/logs/reqmgr2ms/reqmgr2ms-%Y%m


_reqmgr2ms@ms-unmer-t1-5bbf49574d-vfj87:/data$ xargs -0 -L1 -a /proc/76/environ |grep 509
X509_USER_CERT=/data/srv/current/auth/reqmgr2ms/dmwm-service-cert.pem
X509_USER_KEY=/data/srv/current/auth/reqmgr2ms/dmwm-service-key.pem
X509_USER_PROXY=/etc/proxy/proxy
```

I think we are all good here and we can proceed with merging the PR in CMSkubernetes and deploying in production.

**Comment by amaltaro** [comment]
Thanks Todor.

As mentioned over Slack, I have rebuilt MSUnmerged with the very same latest tag `2.2.2`, the `docker push` overwrites the previous image.

In order to pull the new image though, the service yaml manifests had to be updated, the kubernetes `deployment` removed and then we could redeploy ms-unmerged with the very same `2.2.2` tag. Here is the relevant change made for the current deployment (thus, not persisted):
```
--- a/kubernetes/cmsweb/services/reqmgr2ms-unmerged-t2t3.yaml
+++ b/kubernetes/cmsweb/services/reqmgr2ms-unmerged-t2t3.yaml
@@ -85,6 +85,7 @@ spec:
       containers:
       - image: registry.cern.ch/cmsweb/reqmgr2ms-unmerged #imagetag
         name: ms-unmer-t2t3
+        imagePullPolicy: Always
         lifecycle:
           postStart:
             exec:
```

**Comment by todor-ivanov** [comment]
Thanks @amaltaro 

And just to confirm - All MSUnmerged instances in production are now correctly fetching their RSE lists:
* ms-unmerged-t1:
```
$ head -n 1000 reqmgr2ms-20230713-ms-unmer-t1-6b6886cf8f-86lqw.log |grep -A 7  "MSUnmerged: Retrieved list of"
2023-07-13 21:52:36,898:INFO:MSUnmerged: Retrieved list of 7 RSEs: ['T1_UK_RAL_Disk',
 'T1_IT_CNAF_Disk',
 'T1_FR_CCIN2P3_Disk',
 'T1_RU_JINR_Disk',
 'T1_DE_KIT_Disk',
 'T1_ES_PIC_Disk',
 'T1_US_FNAL_Disk'] Service set to process up to 200 RSEs per instance.
```
* ms-unmer-t2t3:
```
$ head -n 1000 reqmgr2ms-20230713-ms-unmer-t2t3-5d7d88f97c-mh2mc.log |grep -A 57  "MSUnmerged: Retrieved list of"
2023-07-13 21:52:32,925:INFO:MSUnmerged: Retrieved list of 57 RSEs: ['T2_IT_Legnaro',
 'T2_BE_IIHE',
 'T2_UK_SGrid_RALPP',
 'T3_KR_UOS',
 'T2_FR_GRIF_IRFU',
 'T3_BG_UNI_SOFIA',
 'T2_BR_SPRACE',
 'T2_RU_INR',
 'T2_FR_GRIF_LLR',
 'T2_FI_HIP',
 'T2_AT_Vienna',
 'T3_MX_Cinvestav',
 'T2_IT_Pisa',
 'T2_IT_Rome',
 'T2_FR_IPHC',
 'T2_EE_Estonia',
 'T2_CH_CERN',
 'T3_CH_PSI',
 'T2_TR_METU',
 'T2_CN_Beijing',
 'T3_IT_Trieste',
 'T3_FR_IPNL',
 'T2_PT_NCG_Lisbon',
 'T2_HU_Budapest',
 'T3_CH_CERNBOX',
 'T2_BE_UCL',
 'T3_HR_IRB',
 'T3_TW_NTU_HEP',
 'T2_UK_London_Brunel',
 'T2_UK_SGrid_Bristol',
 'T3_KR_KNU',
 'T3_IT_MIB',
 'T2_TW_NCHC',
 'T2_ES_IFCA',
 'T3_CH_CERN_OpenData',
 'T3_KR_KISTI',
 'T2_UA_KIPT',
 'T2_UK_London_IC',
 'T2_PK_NCP',
 'T2_ES_CIEMAT',
 'T3_CY_UCY',
 'T2_RU_IHEP',
 'T2_RU_JINR',
 'T3_IR_IPM',
 'T2_FR_GRIF',
 'T2_PL_Cyfronet',
 'T2_BR_UERJ',
 'T3_TW_NCU',
 'T2_DE_RWTH',
 'T2_RU_ITEP',
 'T2_PL_Swierk',
 'T2_CH_CSCS',
 'T2_DE_DESY',
 'T2_KR_KISTI',
 'T2_IN_TIFR',
 'T3_TW_TIDC',
 'T2_IT_Bari'] Service set to process up to 200 RSEs per instance.
```
* ms-unmer-t2t3us:
```
$ head -n 1000 reqmgr2ms-20230713-ms-unmer-t2t3us-7977bdc4ff-lggdw.log |grep -A 24  "MSUnmerged: Retrieved list of"
2023-07-13 21:52:32,907:INFO:MSUnmerged: Retrieved list of 24 RSEs: ['T3_US_MIT',
 'T3_US_NotreDame',
 'T3_US_NERSC',
 'T3_US_OSU',
 'T2_US_MIT',
 'T3_US_UMiss',
 'T2_US_Purdue',
 'T2_US_Vanderbilt',
 'T2_US_Caltech',
 'T3_US_PuertoRico',
 'T2_US_Nebraska',
 'T2_US_Florida',
 'T2_US_UCSD',
 'T3_US_Rutgers',
 'T3_US_UMD',
 'T3_US_Brown',
 'T3_US_FNALLPC',
 'T2_US_Wisconsin',
 'T3_US_Princeton_ICSE',
 'T3_US_Baylor',
 'T3_US_Colorado',
 'T3_US_Rice',
 'T2_US_MIT_Buffer',
 'T3_US_CMU'] Service set to process up to 200 RSEs per instance.
2023-07-13 21:52:32,907:INFO:MSUnmerged: RSE: T3_US_UMiss Reading rse data from MongoDB.

```
