### ISSUE TITLE
Propagate timestamp metrics from WMCore FWJR into WMArchive and MONIT

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11657]
**Impact of the new feature**
Propagate timestamp metrics from CMSSW WM job into CMS monitoring

**Is your feature request related to a problem? Please describe.**
At the moment there is no clear timestamp metrics describing total wall clock time of WM jobs in CMS monitoring. Therefore, such request was placed in #11604. Even though it addresses how metrics should be set up in WM jobs we need an additional step to propagate them through WMArchive documents into MONIT.

**Describe the solution you'd like**
Propagate timestamp metrics from FWJR into WMArchive and MONIT:
- Adjust metrics related module to include these metrics from FWJR into WMArchive document
- Adjust WMArchvie schema to accept new metrics
- Adjust ES/OpenSearch schema/index in MONIT infrastructure
- Use new metrics in CMS monitoring dashboard(s)

**Describe alternatives you've considered**
None, we can continue using WM system as is and do not rely on this metrics

**Additional context**
Part of #11604

**Comment by amaltaro** [comment]
@vkuznet Valentin, I am afraid I missed something from our discussion.

Points 1 and 2 should be part of this GH issue: https://github.com/dmwm/WMCore/issues/11604 (which is to collect the job timestamp information and to propagate it to WMArchive).

Point 3 is indeed what we discussed, which was that WMArchive (server) needs to be adapted - or the document schema adapted - to accept these metrics. I guess Point 4 should be part of this ticket as well. 

And the last point about monitoring dashboards can either be delegated to the CMS Monitoring team, or we wait for specific requests on those.

About point 3 and 4, shouldn't a ticket exist in the [WMArchive](https://github.com/dmwm/WMArchive) project as well? It is still not clear to me who is supposed to maintain WMArchive.
