### ISSUE TITLE
Adopt a different Rucio account in MSPileup: wmcore_pileup

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11668]
**Impact of the new feature**
MSPileup

**Is your feature request related to a problem? Please describe.**
CompOps/DM decided to change the Rucio account used for WM secondary data placement, such that it is easier to see what the secondary data contribution is to input data required by central production.

**Describe the solution you'd like**
Update the MSPileup configuration files to use Rucio account `wmcore_pileup` instead of `wmcore_transferor`. This needs to be done in the `services_config` repository for all the 3 environments/branches. Current prod configurations can be found in [1].

In addition, we should also update WMCore default accounts defined in a couple of python modules under:
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/MicroService/MSPileup

A requirement for deploying this new configuration is that the Rucio account x DN mapping will need to be updated accordingly as well, both for Rucio Prod and Rucio Int. I think that the same DNs that can access `wmcore_transferor` will need to have access to the `wmcore_pileup` account (basically CERN and FNAL agents, as well as CMSWEB).

**Describe alternatives you've considered**
None

**Additional context**
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2ms-pileup-tasks/config.py
and
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2ms-pileup/config.py

**Comment by vkuznet** [comment]
Here are the changes for services_config repo:
- preprod: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/223
- prod: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/224

**Comment by khurtado** [comment]
Here is the test branch PR:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/225

**Comment by khurtado** [comment]
@amaltaro So far, we have:
- WMCore changes in #11673 
- k8s services changes in [223](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/223), [224](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/224), [225](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/225)
- Rucio account x DN mapping done in Rucio and Rucio-int

Is there anything else needed before this can be deployed and tested in testbed?

**Comment by amaltaro** [comment]
I still have to test #11673, then we need to run a testbed validation with all the pieces in place. However, deployment won't be trivial and we need to create a plan for it tomorrow.

Nonetheless, there is still one blocker, which is that `wmcore_pileup` is still not able to create rules (probably lack of quota - or not an admin account). I am waiting for DM Ops to act on this JIRA ticket: https://its.cern.ch/jira/browse/CMSTRANSF-654

**Comment by khurtado** [comment]
@amaltaro The bot closed the issue once the PR was merged, but it was not entirely clear to me if the testbed validation was done already, should I reopen this issue?

**Comment by amaltaro** [comment]
We should be done with the validation by now, but we missed the quotas - which I didn't expect to need - and now testbed MongoDB cluster is broken. I am working on it and I am even considering in deploying the relevant changes to production before having this final bit in place. 

I guess we can keep it closed, and if it turns out to require too much effort, we reopen it. Thank you for checking in though!
