### ISSUE TITLE
Change Unified configuration url for AuxCacheUpdateTasks CherryPy thread

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11695]
**Impact of the new feature**
ReqMgr2

**Is your feature request related to a problem? Please describe.**
The P&R team have recently migrated unified source code from GitHub to Gitlab, which affects one of the ReqMgr2 CherryPy threads:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/CherryPyThreads/AuxCacheUpdateTasks.py#L40C44-L40C55

which means WM microservices might now be using an outdated version of the Unified configuration.

**Describe the solution you'd like**
Update the ReqMgr2 (reqmgr2-tasks) configuration to fetch the Unified configuration from this link:
https://gitlab.cern.ch/CMSProductionReprocessing/WmAgentScripts/-/blob/master/unifiedConfiguration.json

instead of
https://raw.githubusercontent.com/CMSCompOps/WmAgentScripts/master/unifiedConfiguration.json

Note that code changes might be required as well, depending on how the auth/authz process is performed with CERN GitLab. If that is the case, code to be updated is:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/CherryPyThreads/AuxCacheUpdateTasks.py#L40C44-L40C55

**Describe alternatives you've considered**
Not at this moment, but for the long run, we need to see which Unified parameters are consumed within WMCore and migrate those to the relevant WM microservices. The P&R team expressed interest in having these parameters easily configurable, so such mechanism should be provided as well.

**Additional context**
None

**Comment by hassan11196** [comment]
@amaltaro @vlimant 

It seems that WMCore is still using the Unified Config from the Github Repo. It needs to be updated to Gitlab, this jira issue here makes it more necessitous.

https://its.cern.ch/jira/browse/CMSTRANSF-724

@haozturk

**Comment by vkuznet** [comment]
one way to handle it is to use encryption of config and store it on github. Then, whoever who needs it need to decrypt it on upon downloading. The encryption tools (sops and age) are used by CMSWEB team to encrypt our secrets and can be easily added to any system (both are go tools which you can obtain as static executable).

**Comment by amaltaro** [comment]
After investigating the WMCore code, it looks like the Unified configuration is currently only consumed by MSOutput. The following parameters are used: `tiers_to_DDM`, `tiers_no_DDM`, `tiers_with_no_custodial`.

I am considering refactoring the current Unified configuration stored in central CouchDB, retrieved through:
https://cmsweb.cern.ch/reqmgr2/data/unifiedconfig/config

with only the relevant fields. Then we can add a validation function against the `unifiedconfig` API and let it be retrieved/updated through this REST API.

**Comment by amaltaro** [comment]
@haozturk @hassan11196 Hasan, Hassan, would it be reasonable if we actually stop fetching the Unified configuration from the repository and we adopt a push model, where you need to actually make the relevant changes through a REST call to ReqMgr2?

This is how a clean "Unified" configuration looks now:
https://cmsweb-testbed.cern.ch/reqmgr2/data/unifiedconfig/config

only with the parameters that are currently consumed by WMCore/Microservices.

**Comment by hassan11196** [comment]
Hi Alan, @haozturk and I agree, this is a good temporary solution.

**Comment by amaltaro** [comment]
Thanks @hassan11196 . Just so we are on the same page, what would be your long-term suggestion?

**Comment by haozturk** [comment]
It doesn't make sense to me to push all the configuration there while only 2 or 3 fields matter for WMCore. Meanwhile unified will keep reading from the JSON file. In a sense we're again creating two data sources like campaigns. If we forget to sync, it might create issues. Either we should keep everything in WMCore and read from there as well. Or we push only the relevant configs and keep the rest for us. WMCore has many microservices and they are configured in different ways. Some MSOutput configs are configured via Unified. Some via their own internal configuration. Perhaps we should merge these scattered configurations. In this sense, I still think that there is room for improvement.

**Comment by hassan11196** [comment]
Hello @amaltaro, This issue was closed but we are still unclear on how to update the Unified Configutation on the link you provided. 

https://cmsweb-testbed.cern.ch/reqmgr2/data/unifiedconfig/config

@haozturk

**Comment by hassan11196** [comment]
Thank you  for the update Alan. 

We will create new issue to figure out how should we proceed with moving to a more centralized unified config i.e in couchdb.

@haozturk
