### ISSUE TITLE
Does WM make any use of cmsRun ability to pass the python configuration code via command line arguments?

### ISSUE THREAD

**Issue by makortel** [dmwm/WMCore#11702]
Hi,

We recently (re-)discovered that one can pass the python configuration code to `cmsRun` via command line argument along
```
cmsRun "import FWCore.ParameterSet.Config as cms; process = cms.Process('Test'); process.source=cms.Source('EmptySource'); process.maxEvents.input=10"
```
(as part of review of https://github.com/cms-sw/cmssw/pull/42650). Digging from history this ability was apparently added in 2008 in https://github.com/cms-sw/cmssw/commit/38f99e026a9325f1be071568150e9ded5d6ffc40 by a WM person. In https://github.com/cms-sw/cmssw/pull/42650 we are considering of dropping this ability (or moving it to be explicitly be requested with `cmsRun -c <code>` option).

Before changing the behavior of `cmsRun`, especially given the history, I'd like to confirm if WM makes any use of this feature? Or is the configuration always given via a file?

Thanks,
Matti

(going with a GitHub issue in order to have a written record of the answer)

**Comment by amaltaro** [comment]
@makortel Hi Matti, as far as I can tell, central production always run CMSSW/cmsRun with an explicit configuration file. The command line argument would not scale as well with the amount of tweaks required to the job (lumis, primary/secondary lfns, etc). However, I would appreciate if Kenyi could confirm this as well. @khurtado 

In addition, I am also tagging German and Antonio such that we can confirm that the T0 agent does not rely either on this command line argument mechanism. @germanfgv @LinaresToine

**Comment by germanfgv** [comment]
I'm not aware of T0 using this at all. We don;t use it when running jobs manually, and I don't see how WMCore would use it, given that jobs are ran with [this hardcoded script](https://github.com/dmwm/WMCore/blob/de110ccf6fc63ef5589b4e871ef4d51d5bce7a25/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L405). I think it's safe to remove, from our side.

**Comment by makortel** [comment]
Thanks @amaltaro and @germanfgv.

> The command line argument would not scale as well with the amount of tweaks required to the job (lumis, primary/secondary lfns, etc). However, I would appreciate if Kenyi could confirm this as well. @khurtado

Gentle ping

**Comment by amaltaro** [comment]
@makortel feel free to go ahead with your plan. Thank you for cross-checking it with us.

**Comment by makortel** [comment]
Thanks!
