### ISSUE TITLE
Support campaign name for TaskChain workflows

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11705]
**Impact of the new feature**
Support the campaign names available in de workflow description for TaskChain workflows.

**Is your feature request related to a problem? Please describe.**
It is related to: #10914

**Describe the solution you'd like**
For a taskChain workflow, we have many tasks, each with a campaign name in the workflow description. We need need to add get/setters to set this as part of the WMTask object and then propagate this information at the job classad level. The job level propagation would use the same mechanism implemented in #11704. The difference with this is that RERECO only has 1 task/campaign name, while taskchain will have 1 campaign name per task.

**Describe alternatives you've considered**
Use current mechanism at monit level, which we want to change now.

**Additional context**
 #10914

**Comment by amaltaro** [comment]
Awesome! Thanks for testing this out, Kenyi.
