### ISSUE TITLE
Abandon storage.xml in favor of storage.json for stage-in and stage-out

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11703]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
The current issue is a follow up on the previous investigation done in: https://github.com/dmwm/WMCore/issues/11157

We are about to completely abandon the usage of `storage.xml` file for `stage-in` and `stage-out` in favor of `storage.json`. The above issue successfully proved that creating the proper parser for the new xml elements provided in `site-local-config` and properly linking them from 
[src/python/WMCore/Storage/SiteLocalConfig.py](https://github.com/dmwm/WMCore/pull/11440/files#diff-cf7d138386d079c23bf39b4ae5d348c95a93ec6274357c42dc3e1f2e6a5de97b) and [src/python/WMCore/Storage/TrivialFileCatalog.py](https://github.com/dmwm/WMCore/pull/11440/files#diff-a814d9ffe96c9a85e4518d37ef558ce7854d487a2241d2f8292813499f353de2)  accomplishes the goal. 

Just for completeness, I am about to paste bellow the same information from #11157 about what those new xml elements are:

-------------------------------------------------------------------------
 `site-local-config.xml` has new xml elements to support the storage.json structure. They are:
* `data-access`, equivalent to `event-data`
* `stage-out`, equivalent to `local-stage-out` (which also contains the fallback rules)  
-------------------------------------------------------------------------

**Describe the solution you'd like**
The PR https://github.com/dmwm/WMCore/pull/11440  which was used for the tests in https://github.com/dmwm/WMCore/issues/11157 is to be left in `open` state for the time being, and used as a guide line for the places of change that need to happen. The solution here is meant to achieve two main goals:
* To get rid of the additional switch `useTfc` as  developed in the previous PR 
* To stop dragging old logic for a backwards compatibility which we do not intend to exercise - meaning, we are to abandon completely the old code referring to `storage.xml`    

**Describe alternatives you've considered**
None - it a must do

**Additional context**
https://github.com/dmwm/WMCore/pull/11440

**Comment by amaltaro** [comment]
Moved from Q3/medium to Q4/high

**Comment by nhduongvn** [comment]
@todor-ivanov ,
I made a pull request for this issue. Could you take a look and launch the test workflow?
https://github.com/dmwm/WMCore/pull/11790

**Comment by todor-ivanov** [comment]
Thanks @nhduongvn , I'll try to come back to this later today.

BTW, could you please use the PR Description template in the future, and try to mark which is the issue to be resolved from the given PR by including the comment  `fixes: #....` at the top of the description.  Sorry for asking this, otherwise we will loose the link between Issues and PRs.

**Comment by nhduongvn** [comment]
Yes, I will follow the template.
To not to forget, in the end we need to test these scenarios: 
1. A workflow runs at a sub site, for example https://gitlab.cern.ch/SITECONF/T1_DE_KIT/-/tree/master/KIT-HOREKA?ref_type=heads
2. A stage out to a storage site which uses chained rules, for example:
https://gitlab.cern.ch/SITECONF/T1_DE_KIT/-/blob/master/storage.json?ref_type=heads
currently, I did not implement this feature yet (just for simplification first)
https://github.com/nhduongvn/WMCore/blob/2d6fd5699f6b25e5cbf1b89a6771aaa8ce67522f/src/python/WMCore/Storage/RucioFileCatalog.py#L185
Another question is that whether StageInMgr class is used somewhere? I guess this class is obsolete since there is no \<stage-in\> in the site-local-config.xml

**Comment by todor-ivanov** [comment]
hi @nhduongvn 
I finally managed  to patch an agent and submit two requests testing your changes: 

https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_RunBlockWhite_StageOutTest_v1_231120_184205_5680

https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_Run2022C_LumiMask_StageOutTest_v1_231120_184212_5881

You can watch them yourself as well. Once they are finished we can see what the results/errors were

**Comment by todor-ivanov** [comment]
hi @nhduongvn 

Here is the error from the `Storage` module: [1]

[1]
https://cmsweb-testbed.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/tivanov_ReReco_RunBlockWhite_StageOutTest_v1_231120_184205_5680 

```
 <@========== WMException Start ==========@>
Exception Class: MgrImplementationError
Message: Unable to load StageOut/Delete Impl: <@========== WMException Start ==========@>
Exception Class: StageOutInitError
Message: Unable to load Trivial File Catalog:
Local stage out will not be attempted
'SiteLocalConfig' object has no attribute 'trivialFileCatalog'
	ClassName : None
	ModuleName : WMCore.Storage.StageOutError
	MethodName : __init__
	ClassInstance : None
	FileName : /srv/job/WMCore.zip/WMCore/Storage/StageOutError.py
	LineNumber : 32
	ErrorNr : 0
	ErrorCode : 60315
	ErrorType : StageOutInitError

Traceback: 
  File "/srv/job/WMCore.zip/WMCore/Storage/StageInMgr.py", line 106, in initialiseSiteConf
    self.tfc = self.siteCfg.trivialFileCatalog()

<@---------- WMException End ----------@>
	ClassName : None
	ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
	MethodName : __init__
	ClassInstance : None
	FileName : /srv/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
	LineNumber : 18
	ErrorNr : 60312

Traceback: 
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/LogCollect.py", line 85, in execute
    stageInMgr = StageInMgr()

  File "/srv/job/WMCore.zip/WMCore/Storage/StageInMgr.py", line 70, in __init__
    self.initialiseSiteConf()

  File "/srv/job/WMCore.zip/WMCore/Storage/StageInMgr.py", line 113, in initialiseSiteConf
    raise StageOutInitError( msg )

<@---------- WMException End ----------@>
```

**Comment by todor-ivanov** [comment]
logging here as well, the two successfully completed workflows:

https://cmsweb-testbed.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/tivanov_ReReco_RunBlockWhite_StageOutTest_v3_231201_152641_7197

https://cmsweb-testbed.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/tivanov_ReReco_Run2022C_LumiMask_StageOutTest_v3_231201_152650_8459

**Comment by todor-ivanov** [comment]
[Stefano](@belforte),  You asked to keep you posted. I think now  is the moment to check the modules from WMCore this PR is touching to see how would CRAB be affected.

**Comment by belforte** [comment]
@belforte @novicecpp @mapellidario

**Comment by amaltaro** [comment]
After reviewing changes provided in the PR https://github.com/dmwm/WMCore/pull/11816 and talking to Todor, I think further testing - and specially large scale tests targeting many sites - is necessary.

I also only managed to review the relevant PR this week, post merge, where I left many questions/comments/suggestions that need to be followed up.

Apologies for reopening this, but given how intrusive these changes are, I think it's better to isolate this from master branch for the moment and work further on these developments.

**Comment by khurtado** [comment]
Just for reference, I have created a GGUS ticket regarding an error observed when submitting jobs to `T3_ES_PIC_BSC`. 

https://ggus.eu/index.php?mode=ticket_info&ticket_id=165390
