### ISSUE TITLE
Implement a physics task type for all workflow types in the system

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11712]
**Impact of the new feature**
This feature will replace the current logic to guess the physics task type of a job from monit: https://github.com/dmwm/cms-htcondor-es/blob/vm-legacy/src/htcondor_es/convert_to_json.py#L1019-L1059
to here, and will add support for stepChain (currently, it does not support all the physics types between a job, but only the last). This will rely on a different source for the logic: the cmsDriver comand line arguments, rather than the campaign, request/subtask names

**Is your feature request related to a problem? Please describe.**
This is related to:
https://github.com/dmwm/WMCore/issues/10604

**Describe the solution you'd like**
Based on the outcome of:
https://github.com/dmwm/WMCore/issues/11711

We need to implement this logic to ReReco, taskChain, StepChain workflows 
Such solution will require:
-  Modifying ReqMgr2 such that the job configuration is loaded in order to read the cmsDriver command line arguments and then map the task to a physics task type.
- Update the workload object, task and step objects, with the physics task type. This information will then be available in the configFile (and config cache in couchdb)
- Consume this information in JobCreatorPoller (when assembling the dict with all the info that goes into the pickle file we send for the job) and JobSubmitterPoller (when we create the job object that we pass to the condor submit plugin)
- Create a new condor classad in SimpleCondorPlugin, called `CMS_extendedTaskType`, which will display the physics task type for physics jobs, or just the standard `CMS_JobType` (e.g.: LogCollect, Merge, etc) for non-physics jobs. This is so that monit can simply grab this classad and report it, without any extra logic needed at that level. We could provide just a CMS_PhysicsTaskType but then some if conditionals would be required at the monit level to get the general job task types (a combination of CMS_PhysicsTaskType. and CMS_JobType).

**Describe alternatives you've considered**
Native cmssw support for this, which has been reflected here:
cmsDriver feature request:
https://github.com/cms-sw/cmssw/issues/42450

but could take many years to propagate anyway, so we need this solution as well.

**Additional context**
Parent issue:
https://github.com/dmwm/WMCore/issues/10604

**Comment by amaltaro** [comment]
@khurtado Kenyi, in the expected solution, I think we should be explicit with the following:
* modify ReqMgr2 such that the job configuration is loaded and mapped to physics task type
* update the workload object - and task and step objects - with the physics task type
* consume this information in JobSubmitter
* create a new condor classad carrying this information (please specify which field we are planning to adopt).

Have I missed anything?

**Comment by khurtado** [comment]
Yes, you are right! I will update the description with the above.

In addition to that, should we create a different one explaining the solution for stepChain specifically?

**Comment by amaltaro** [comment]
I think this comment https://github.com/dmwm/WMCore/issues/11711#issuecomment-1715908059 should answer this. But please let me know if you have different suggestions.
