### ISSUE TITLE
Correct WMTiming metrics to be collected at the job wrapper

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11718]
**Impact of the bug**
WMAgent

**Describe the bug**
This issue:
https://github.com/dmwm/WMCore/issues/11604
- initially conceived as a meta-issue style - requested timing metrics to be provided for the whole grid job. 

Changes have been added to the bash job wrapper, but they apply those new metrics against the wrong Report pickle file.

Said that, this issue is to track the remaining investigation AND resolution/implementation of that feature.

**How to reproduce it**
Needs to have a job going through the agent, then looking into the documents uploaded to WMArchive.

**Expected behavior**
Some investigation is still required to find out what is possible and the best approach to finish this implementation. It could either be:
a) that at the job wrapper, we can actually persist these metrics in the correct FJR/Report (which is then automatically consumed by one of the agent's components)
b) or, that we will have to consume an indirect Report file and push it to the document that gets persisted in local CouchDB
c) yet another alternative would be to use multiple data source in the ArchiveDataReporter, such that the final document uploaded to WMArchive is enriched with the WMTiming metrics.

Once we have a clear path ahead, we need to implement the final details and conclude this feature. All to be addressed with this ticket.

**Additional context and error message**
Follow up of ticket https://github.com/dmwm/WMCore/issues/11604

**Comment by amaltaro** [comment]
@vkuznet Valentin, I ran a workflow with further debug statements and it turns out we are actually failing to add the WMTiming section to the report (this error is supposed to be in the standard logging level):
```
======== WMAgent add timestamps metrics to FJR Report.0.pkl ========
AMR Adding timestamps to report file: /srv/job/Report.0.pkl
WARNING: failed to update FJR with timestamps metrics, status=2
======== WMAgent finished adding timestamps metrics to FJR ========
```

and the directory structure is (I removed lines that make no difference for this task):
```
WMAgent bootstrap: WMAgent finished the job, it's copying the pickled report
AMR upper directory content (/srv):
-rw-r--r-- 1 cmsgli us_cms   71858 Sep 16 12:18 JobPackage.pkl
-rw-r--r-- 1 cmsgli us_cms     637 Sep 16 12:18 Report.0.pkl
drwxr-xr-x 7 cmsgli us_cms    4096 Sep 16 12:18 job
-rw-r--r-- 1 cmsgli us_cms   31834 Sep 16 12:58 wmagentJob.log

AMR WMTaskSpace content (/srv/job/WMTaskSpace):
-rw-r--r-- 1 cmsgli us_cms 24131 Sep 16 12:58 Report.0.pkl
drwxr-xr-x 4 cmsgli us_cms  4096 Sep 16 12:44 cmsRun1
drwxr-xr-x 4 cmsgli us_cms  4096 Sep 16 12:50 cmsRun2
drwxr-xr-x 4 cmsgli us_cms  4096 Sep 16 12:58 cmsRun3
drwxr-xr-x 3 cmsgli us_cms  4096 Sep 16 12:58 logArch1
drwxr-xr-x 3 cmsgli us_cms  4096 Sep 16 12:58 stageOut1
-rw-r--r-- 1 cmsgli us_cms 24131 Sep 16 12:58 WMTaskSpace/Report.0.pkl

WMTaskSpace/cmsRun1:
-rw-r--r--  1 cmsgli us_cms     24363 Sep 16 12:43 FrameworkJobReport.xml
-rw-r--r--  1 cmsgli us_cms      5693 Sep 16 12:58 Report.pkl

WMTaskSpace/cmsRun2:
-rw-r--r--  1 cmsgli us_cms    307561 Sep 16 12:50 FrameworkJobReport.xml
-rw-r--r--  1 cmsgli us_cms      6268 Sep 16 12:58 Report.pkl

WMTaskSpace/cmsRun3:
-rw-r--r--  1 cmsgli us_cms   374092 Sep 16 12:58 FrameworkJobReport.xml
-rw-r--r--  1 cmsgli us_cms     9767 Sep 16 12:58 Report.pkl

WMTaskSpace/logArch1:
-rw-r--r-- 1 cmsgli us_cms    2199 Sep 16 12:58 Report.pkl

WMTaskSpace/stageOut1:
-rw-r--r-- 1 cmsgli us_cms 1407 Sep 16 12:58 Report.pkl
======== WMAgent bootstrap FINISH at Sat Sep 16 12:58:35 GMT 2023 ========
```

In summary:
* we need to understand why it fails to add the WMTiming section to the job report file
* report pickle files can be found in 3 different locations, such as:
/srv/job/Report.0.pkl
/srv/Report.0.pkl  # copied from WMTaskSpace/Report*.pkl at the end of the job wrapper
/srv/job/WMTaskSpace/Report.0.pkl
/srv/job/WMTaskSpace/STEP_NAME/Report.0.pkl  # like cmsRun1, cmsRun2, logArch1, stageOut1

Which makes me think that we should wait for the Report.0.pkl to be copied and then add the WMTiming to that file. OR, add the WMTiming to "/srv/job/WMTaskSpace/Report.0.pkl" before it gets copied to a different location.

In addition, the condor job definition is defined like:
```
  TransferOutput = "Report.0.pkl,wmagentJob.log"
```
that means what is returned to the agent/schedd is actually /srv/Report.0.pkl. I believe this file will contain the CMSSW metrics that we add in the worker node and WMTiming, once we fix the latter.

**Comment by vkuznet** [comment]
Alan, thanks for looking this during my absence. I'll proceed with this info further.

**Comment by amaltaro** [comment]
This has been fixed by https://github.com/dmwm/WMCore/pull/11726 (which was mistakenly mentioned to be fixing the old issue). Closing this one out now.
