### ISSUE TITLE
Remove wma_prod and wmcore_transferor rules once output rules are satisfied

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11725]
**Impact of the new feature**
CMS disk management & MSRuleCleaner

**Is your feature request related to a problem? Please describe.**
`wma_prod` is the account which locks the most space on CMS disks: [Monitoring](https://monit-grafana.cern.ch/d/WPDxqoL4z/rucioaccounts?viewPanel=2&from=now-7d&to=now&orgId=11&var-RSE=T0_CH_CERN_Disk&var-RSE=T1_DE_KIT_Disk&var-RSE=T1_ES_PIC_Disk&var-RSE=T1_FR_CCIN2P3_Disk&var-RSE=T1_IT_CNAF_Disk&var-RSE=T1_RU_JINR_Disk&var-RSE=T1_UK_RAL_Disk&var-RSE=T1_US_FNAL_Disk&var-RSE=T2_AT_Vienna&var-RSE=T2_BE_IIHE&var-RSE=T2_BE_UCL&var-RSE=T2_BR_SPRACE&var-RSE=T2_BR_UERJ&var-RSE=T2_CH_CERN&var-RSE=T2_CH_CSCS&var-RSE=T2_CN_Beijing&var-RSE=T2_DE_DESY&var-RSE=T2_DE_RWTH&var-RSE=T2_EE_Estonia&var-RSE=T2_ES_CIEMAT&var-RSE=T2_ES_IFCA&var-RSE=T2_FI_HIP&var-RSE=T2_FR_CCIN2P3&var-RSE=T2_FR_GRIF&var-RSE=T2_FR_GRIF_IRFU&var-RSE=T2_FR_GRIF_LLR&var-RSE=T2_FR_IPHC&var-RSE=T2_GR_Ioannina&var-RSE=T2_HU_Budapest&var-RSE=T2_IN_TIFR&var-RSE=T2_IT_Bari&var-RSE=T2_IT_Legnaro&var-RSE=T2_IT_Pisa&var-RSE=T2_IT_Rome&var-RSE=T2_KR_KISTI&var-RSE=T2_PK_NCP&var-RSE=T2_PL_Cyfronet&var-RSE=T2_PL_Swierk&var-RSE=T2_PL_Warsaw&var-RSE=T2_PT_NCG_Lisbon&var-RSE=T2_RU_IHEP&var-RSE=T2_RU_INR&var-RSE=T2_RU_ITEP&var-RSE=T2_TR_METU&var-RSE=T2_RU_JINR&var-RSE=T2_TW_NCHC&var-RSE=T2_UA_KIPT&var-RSE=T2_UK_London_Brunel&var-RSE=T2_UK_London_IC&var-RSE=T2_UK_SGrid_Bristol&var-RSE=T2_UK_SGrid_RALPP&var-RSE=T2_US_Caltech&var-RSE=T2_US_Caltech_Ceph&var-RSE=T2_US_Florida&var-RSE=T2_US_MIT&var-RSE=T2_US_Nebraska&var-RSE=T2_US_Purdue&var-RSE=T2_US_UCSD&var-RSE=T2_US_Vanderbilt&var-RSE=T2_US_Wisconsin&var-AccountType=All&var-AccountName=All&var-ArchivalAccount=All&var-diskserviceaccount=All) 

Currently, wma_prod and wmcore_transferor rules are deleted once the corresponding workflow moves from `announced` to `-archived` status. WM performs multiple checks during this transition and even if one of them fails workflow doesn't advance and disk locks remain as they are. Only meaningful check before deleting `wma_prod` and `wmcore_transferor` rules is checking whether corresponding `wmcore_output` rules are satisfied or not. All other checks, e.g. ParentageResolved on DBS, aren't relevant. Currently most of the workflows which cannot perform `announced` to `-archived` transition suffers from parentage issue and their wma_prod and wmcore_transferor rules cannot be unlocked, which corresponds to probably petabytes of locked space

**Describe the solution you'd like**
Delete `wma_prod` and `wmcore_transferor` rules once all `wmcore_output` rules are fully satisfied

**Describe alternatives you've considered**
The fact that we're managing data in dataset level restricts the level of granularity. In the proposal I had above, all wma_prod and wmcore_transferor rules will still stay locked even if there is 1 stuck file which couldn't make to tape. In that case, it doesn't make sense to keep files which made to tape locked on disk. How feasible do you think it is to start deletions in file or block level? e.g. let's say I have a dataset with 100 blocks where each block has 100 files and only 1 file got stuck to be archived into tape. I propose to either
- unlock 99 blocks which are fully locked at their final destinations
or
- unlock 9999 files which are fully locked at their final destinations

Probably first one is easier.

**Additional context**
@dynamic-entropy @panos512 @drkovalskyi  fyi

**Comment by amaltaro** [comment]
@d-ylee Hi Dennis, it looks like only the first link is correct. The second talks about `IncludeParents`, which talks about parent dataset in a different context (in the context of using a parent dataset in the processing jobs). I understand it can be misleading, but they are actually different things.

For testing it, do we have unit tests for this module? If not, then I would suggest you to make a PR and then we discuss how to properly test it. It could be that we can test it during the integration phase (in testbed).
