### ISSUE TITLE
Workflows with file mismatch (Especially after Aug 1)

### ISSUE THREAD

**Issue by jang00777** [dmwm/WMCore#11729]
**Impact of the bug**
WFs with this issue stuck in complete status

**Describe the bug**
There was the previous discussion [1] and the issue is still happening. (Most recent discussion here [2], meeting log of 20/09/2023).
The file mismatch is literally a mismatch of files in DBS and Rucio. Because of the issue, several WFs can't be announced. 

**How to reproduce it**
They are listed here [3] and, especially, MC WFs submitted after Aug 1 should be investigated:

[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00116](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00116)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00114](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00114)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GENAPV-00188](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GENAPV-00188)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22wmLHEGS-00232](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22wmLHEGS-00232)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00194](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00194)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00196](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00196)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00207](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00207)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TSG-Run3Winter23Digi-00240](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TSG-Run3Winter23Digi-00240)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00204](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00204)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer20UL17wmLHEGEN-00437](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer20UL17wmLHEGEN-00437)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer20UL18wmLHEGEN-00423](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer20UL18wmLHEGEN-00423)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22wmLHEGS-00219](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22wmLHEGS-00219)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00201](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00201)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00199](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL17GEN-00199)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GENAPV-00183](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GENAPV-00183)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GEN-00190](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GEN-00190)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GEN-00189](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer20UL16GEN-00189)
[https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00298](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_GEN-Run3Summer22EEwmLHEGS-00298)
https://[dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00084](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-Run3Summer22EEGS-00084)

**Expected behavior**

**Additional context and error message**

[1] https://github.com/dmwm/WMCore/issues/11556
[2] https://docs.google.com/document/d/1yORJd6rWZeMyxXMGPQsaovOWjbFnEegXwukVedlFy50/edit
[3] [https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?in_production=1&rsort=2](https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?in_production=1&rsort=2)

**Comment by amaltaro** [comment]
@jang00777 I am very sorry for the lack of follow up on this ticket. Given that these are operational problems reported back in Sept 2023, I assume them are no longer relevant.

Hence I am closing this ticket out, but please reopen it if there is material and/or new cases of file mismatch.
