### ISSUE TITLE
Update RSE expression for output rules to tape

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11723]
**Impact of the new feature**
MSOutput

**Is your feature request related to a problem? Please describe.**
Ops would like to be able to control the tape RSEs to which MSOutput sends outputs to. Currently, MSOutput uses this RSE expression for output rules to tape [1]. Ops needs to go through WM to update it. This is not optimal in case of urgencies

[1] https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/aa6f6a38ec85409f676d2a08f6fdbde50b27cfb1/reqmgr2ms-output/config-output.py#L83 

**Describe the solution you'd like**
Ops will define a new RSE attribute, whose name could be `wmcore_output_tape` and make it `wmcore_output_tape=True` for tape RSEs to which we want outputs to go. WMCore should provide `wmcore_output_tape=True` as an RSE expression instead of `rse_type=TAPE\(cms_type=test|rse=T1_RU_JINR_Tape)`. This way, 
- we'll not have to hack the expression whenever we need a change
- we'll be protected by syntax errors that we can make while changing the RSE expression.

**Describe alternatives you've considered**
I cannot think of a better solution

**Additional context**
We need to stop output transfers to T0_CH_CERN_Tape asap

@drkovalskyi @ahmedmu @llavezzo fyi

**Comment by amaltaro** [comment]
This has been fixed with: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/234
and also deployed to the production Kubernetes cluster, followed by a restart of MSOutput.
Thanks to Hasan for helping me to validate the new Tape RSE expression.

**Comment by amaltaro** [comment]
@haozturk you might want to create a GH ticket under the Rucio repository to make sure that this new RSE attribute gets properly considered whenever Rucio is upgraded and/or a new kubernetes cluster is created.

BTW, thank you for suggesting this neat change.

**Comment by haozturk** [comment]
@dynamic-entropy said that these attributes are stored in Rucio db and shouldn't be affected by any upgrade.
