### ISSUE TITLE
WMCore stage-out script improvement

### ISSUE THREAD

**Issue by stlammel** [dmwm/WMCore#11731]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
It is usually hard to debug stage out issues, as we don't have enough debugging information and it's complicated to execute stage out in an standalone mode.

**Describe the solution you'd like**
One of the requests is to gather more information whenever there is a stage out failure. Extra information could be:
* which authentication method was used by the job
* which library, command and version was used for the stage out

In addition to that, Stephan express interest in having the ability to run the stage out process in an standalone mode (interactively from a worker node). This potentially requires more intrusive changes to the codebase and it's likely better to be tracked in a new GH issue. But I am keeping it here for the moment.

**Describe alternatives you've considered**
None

**Additional context**
Old description of this issue, provided by Stephan, is below:
"""
The current stage-out scripts leave us pretty much in the dark in case of a failure. We should review review the current scripts and update them with appropriate error handling and information logging in case of a failure.
Especially with the transition to IAM-issued tokens we need to know in more details why a transfer failed and have to get out of the current guessing/rerun-by-expert mode.
(Opened as suggested by Alan.)
 - Stephan
"""

**Comment by stlammel** [comment]
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/GFAL2Impl.py
so i don't forget the location

**Comment by amaltaro** [comment]
After a short discussion with @stlammel , I updated the initial description with more specific requirements that I collected. Please let us know if you have any other specific requirements that have not been persisted in the initial issue description.

**Comment by stlammel** [comment]
Thanks Alan! Maybe one should also consider if WMcore is the right location of the stage-out scripts of if there is a better/more suitable location. This could also be part of a general WM organization review. Having smaller modules with well defined functionality and good interface documentation would make extra, non-WM-expert effort more effective.
Just a thought,
 - Stephan

**Comment by anpicci** [comment]
@amaltaro , here is a first attempt:
https://github.com/anpicci/WMCore/commit/eddad413b272d05db5b746830915fe3fa2018b49

**Comment by amaltaro** [comment]
@anpicci expanding the stage out command could definitely be an option.

However, what I had in mind was to further separate stage out from stage out debugging information. It will be hard to explain these in written text, but here I go. This place is where we actually execute the stage out command (see the retry logic as well):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/StageOutImpl.py#L215

we could further instrument this code such that, once it fails all retries, instead of raising an exception upstream, we could build a debug environment command - note that it will be specific to the command/protocol being used - and execute that, such that the logs would contain the needed information. In very short, a pseudo-code would look like:
```
command = self.createStageOutCommand(sourcePFN, targetPFN, options, checksums)

for retryCount in range(self.numRetries + 1):
            try:
                logging.info("Running the stage out...")
                self.executeCommand(command)
                break
            except StageOutError as ex:
                etc

# if command above fail, execute below
command = self.createDebuggingCommand(sourcePFN, targetPFN, options, checksums)
            try:
                logging.info("Running the stage out...")
                self.executeCommand(command)
                break
            except StageOutError as ex:
                etc
raise stage out error
```

**Comment by anpicci** [comment]
Ok, so in my understanding, the to-do list would be the following:

1. create the abstract method `createDebuggingCommand` in `StageOutImpl.py` for the base class `StageOutImpl`
2. modify `__call__` to make a full debugging report before raising the stageout error
3. in [GFAL2Impl.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/GFAL2Impl.py), provide the actual definition for `createDebuggingCommand`, replicating what is done in `createStageOutCommand` but with additional information about the command failing (similarly to what is done in my commit).

What do you think?

**Comment by amaltaro** [comment]
That is correct. However, the step 3 is supposed to have only debugging information. I believe we already print the actual stage out command upon failure, so we could simply print environment information, e.g.:
* proxy file being used and its details (DN, expiration, maybe voms attributes)
* command executed for stage out, location, version
* worker node name and container OS

I would suggest starting with something very simple, then we can iterate with Stephan and see what is missing.

**Comment by anpicci** [comment]
Indeed, I agree

**Comment by anpicci** [comment]
@amaltaro, I have just attached the first PR for this issue. Feel free to move forward during my vacation time, if needed.
