### ISSUE TITLE
Evaluate WM payload timing for StepChain workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11747]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
We have seen reports of CMS job inefficiencies, where it is said that WMAgent jobs can result in 2% of the overall inefficiency.
We should study production payload to have a better understanding of where time is actually spent and identify potential improvements.

**Describe the solution you'd like**
Study StepChain jobs - only Production/Processing jobs - and map steps executed by WMAgent, time spent in each and potentially identify areas of improvements.

The following setup needs to be evaluated:
* StepChain without input and pileup data
* StepChain with input data (single pileup)
* StepChain with input and pileup data 

**Describe alternatives you've considered**
Ideally we should use the latest WMAgent release (>= 2.2.4.x)

**Additional context**
None

**Comment by khurtado** [comment]
I have added a stepchain section in this wiki:

https://github.com/dmwm/WMCore/wiki/WM-payload-timings-on-different-workflow-types#stepchain-1

Marking issue as done.
