### ISSUE TITLE
R&D: Classification of job exit code vs architecture

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11740]
**Impact of the new feature**
Provide a Classification of job exit code vs architecture for R&D purposes

**Is your feature request related to a problem? Please describe.**
This is part of the TODO tasks for the Evaluation of the WM system for the HL-LHC scenario

**Describe the solution you'd like**
Modify the following grafana dashboard to provide this information
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11

**Describe alternatives you've considered**

**Additional context**

**Comment by khurtado** [comment]
There are 3 architectures available in the system in the last 13 months, so I added 3 different plots for easier comparisons.

X86:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11&from=1663517780072&to=1697645780072&viewPanel=120

PPC:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11&from=1663517790187&to=1697645790187&viewPanel=121

ARM:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11&from=1663517809692&to=1697645809692&viewPanel=130

Note ARM has only a small percentage of sucessful jobs.

**Comment by amaltaro** [comment]
@khurtado Kenyi, did you save these new panels? I am unable to find it in this dashboard:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring?orgId=11&from=1663524623447&to=1697652623448

**Comment by khurtado** [comment]
@amaltaro Dang, you are right! I re-did the dashboards and it should be saved now.

**Comment by amaltaro** [comment]
Thanks @khurtado, now I can see them. I would like to make a suggestion though. Those plots are somehow hard to read, perhaps the following would make it substantially cleaner:
* limit the legend to the top 10 (based on values) exit code
* and move the legend to the right side of the pie chart (we can potentially then have 2 plots in the same row)

What do you think? Could you please give it a try?

PS.: It is unrelated to this ticket, but I see that "Number of job starts per job" has the same layout, perhaps we could take this opportunity and improve that one as well.

**Comment by amaltaro** [comment]
@khurtado just a friendly ping before I forget it myself
