### ISSUE TITLE
Create dump of the WM runtime parameters for Process customization

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11743]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
This is a sub-task of https://github.com/dmwm/WMCore/issues/10819, where it is desired to have workflow, job and step information at job runtime such that CMSSW customizations can be applied to the job.

This is specially important for StepChain workflows, hence dumping step information as steps are created and executed.

**Describe the solution you'd like**
The idea is to dump workflow/node/job information into a JSON file as the job progress. For instance, before starting the processing of `cmsRun1`, we would collect information that is already available for us and dump it in a file. After the PSet tweak, a CMSSW customization function would be called and would parse this JSON dump, deciding whether to apply customizations or not.

Parameters that are apparently important for the job customization can be classified as (but this list can grow and/or require further tickets as well):
1) workflow: workflow type, number of cmsRun steps,
2) worker node: node architecture, node OS 
3) job/steps: input file(s), output file(s), output data tiers, whether output file is kept or not (has diff behavior between StepChain and TaskChain)

A potential data structure for this JSON could be:
```
{
"workflow_type: "Stepchain",  # string with the request type
"number_of_cmsRun": 2,  # an integer >= 0
"worker_arch": "X86_64",  # string with the architecture of the worker node
"worker_os": "rhel9",  # string with the OS of the worker node
"cmsRun_params": [{
    "step": "cmsRun1",  # string with the relevant step
    "input_files": [string of input LFNs or a single local file],
    "output_files": [ordered string of output local files],
    "output_datatiers": [ordered string of output local files datatiers],
    "output_saved": [ordered boolean saying whether output files are announced in the workflow or not]
    },
    {
    "step": "cmsRun2",  # string with the relevant step
    # and so on...
    },
    # any new step appends step data to this list
]
}
```

Note that this data structure needs to be created before we get to the point where the customization function will be called.

**Describe alternatives you've considered**
None

**Additional context**
Sub-task for meta-issue: https://github.com/dmwm/WMCore/issues/10819

**Comment by khurtado** [comment]
@amaltaro  Is this information in the pset per cmsRun step?
```
"output_saved": [ordered boolean saying whether output files are announced in the workflow or not]
```

**Comment by khurtado** [comment]
Thank you! Do you know if WMWorkload.pkl and JobPackage.pcl would be all the information that we need? Or do we need to get information from the PSets? E.g.: For the input/output files, I don't know if we are supposed to get this info from the pset after tweaking, etc.

If we do need to get things from the PSets, I would rather create 1 json per cmsRun step, because the Psets are tweaked sequentially (cmsRun1 -> tweak, then execute, cmsRun2->tweak, then execute, etc).

Otherwise, if everything we need is in WMWorkload.pkl and JobPackage.pcl, then yes, a single json would make the most sense.

**Comment by khurtado** [comment]
@amaltaro I created a PR with the JSON structure. I opten to keep both "keep_output' and 'transient' per cmsRun step because of #9013
