### ISSUE TITLE
WMAgent v2.2.7 Validation

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11751]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
By-monthly task

**Describe the solution you'd like**
We need to release a new WMAgent stable version in Jan/2024, so this issue is meant to keep track of the full validation activity to be carried out in the first weeks of January, once we have a final 2.2.7 tag.

In addition to the validation results, WMAgent release notes and the validation check-list twiki need to be created as well.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
Description updated and moved to Q1/2024

**Comment by amaltaro** [comment]
This release has been tested with 2.2.6rc8 and no more issues have been found. Given that this agent has a new component (WorkflowUpdater), I decided to make a middle version upgrade, hence jumping to version `2.3.0`. Release notes can be found at: https://github.com/dmwm/WMCore/releases/tag/2.3.0

Usual validation twiki at: https://twiki.cern.ch/twiki/bin/view/CMS/WMAgent230Validation (note that test workflows are under campaign "Agent227_Val").

WMAgent upgrade is ongoing and the old version agents (2.2.5) are soon going into drain. I am closing this issue as completed.
