### ISSUE TITLE
Test and deploy a MongoDB backup mechanism

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11756]
**Impact of the new feature**
WMCore microservices using MongoDB

**Is your feature request related to a problem? Please describe.**
The CMSWEB team has been evaluating technologies to backup the MongoDB databases stored in the MongDBAaS cluster.
Right now those databases lack of any backup mechanism and we would like to have automated backup to be able to recover from possible accidents.

This issue is tracked by the HTTP/CMSWEB team in this ticket: https://its.cern.ch/jira/browse/CMSKUBERNETES-242
In addition, https://its.cern.ch/jira/browse/CMSMONIT-583 ticket keeps track of changes for CMS Monitoring AlertManager which becomes primary source for alerts and will route them to two channels:
- `alerts-mongodb-k8s-cluster` MM channel
- and, `cms-service-webtools` e-group
Here is actual changes to CMS Monitoring Alert Manager configuration: https://gitlab.cern.ch/cmsmonitoring/cmsmon-configs/-/merge_requests/56/diffs

The corresponding WM wiki page can be found here: https://github.com/dmwm/WMCore/wiki/MongoDB-backup-and-restore-procedure

### Backup details
- database names: msPileupDBPreProd, msOutputDBPreProd and msUnmergedDBPreProd
- frequencies: 4 hour (production) and 12 hours for preproduction
- retention policy: 10 days
- EOS location: /eos/project-c/cmsweb-http/mongodb/backups/<preprod,prod>

**Describe the solution you'd like**
Together with the HTTP/CMSWEB team, decide which technology will best suit our needs (which are?) and the CMSWEB/Kubernetes infrastructure.

In addition to providing the CMSWEB team with our requirements for this backup, it will also involve testing things out whenever they are deployed, studying backup options, etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
@vkuznet Valentin, when self-assigning an issue that you are starting to work on, please remember to move its "Status" from ToDo to In Progress. I have just done so on this issue.

**Comment by vkuznet** [comment]
The implementation on CMSWEB is completed and all components are in place. Said that, I need input which routes to use for alerts. So far they will go to alerts-mongodb-k8s-cluster MM channel. Is it sufficient or do we need another MM channel and/or email/e-group. @amaltaro please provide your insight.

**Comment by amaltaro** [comment]
I think these alerts need to reach mainly 2 teams:
a) HTTP CMSWEB
b) WMCore

we can discuss potential egroups in mattermost.

**Comment by vkuznet** [comment]
Alan, please be specific which channel for WMCore team to use. I can ask for either one on MM< e.g. use WM Ops, etc. I can't guess just based on group name as I need to tell CMS Monitoring team concrete channel to add to AM configuration.

**Comment by vkuznet** [comment]
We finished technical implementation on CMSWEB side (https://its.cern.ch/jira/browse/CMSKUBERNETES-242) and I created an additional ticket on CMS Monitoring side (https://its.cern.ch/jira/browse/CMSMONIT-583) to add appropriate e-group (cms-service-webtools) into AlertManager. Once it will be configured we'll get alerts in alerts-mongodb-k8s-cluster MM channel and in this e-group.

**Comment by vkuznet** [comment]
@amaltaro , @klannon please review provided new description as we done with technical implementation. All work were done through https://its.cern.ch/jira/browse/CMSKUBERNETES-242 ticket and there is no dedicated PR on WM side (as it is not required). Also, the alerts configuration will be in hands of CMS Monitoring group and I updated description with corresponding entry about their ticket https://its.cern.ch/jira/browse/CMSMONIT-583. I can either close this issue or I will keep it open until CMS Monitoring group will add appropriate changes to AlertManager (add new e-group). Said that, the new image for MongoDB back exists and deployed on mongo test cluster. If you are ok with final proposal I'll ask @arooshap to deploy new image to cmsweb testbed and we'll start using it.

**Comment by vkuznet** [comment]
The changes to CMS Monitoring Alert Manager are done over here: https://gitlab.cern.ch/cmsmonitoring/cmsmon-configs/-/merge_requests/56/diffs and if we'll need to change/adjust them we should use https://its.cern.ch/jira/browse/CMSMONIT-583 ticket.

**Comment by vkuznet** [comment]
I think now everything is in place and we may close this ticket as resolved. The actual back up now in hands of CMSWEB group. @amaltaro , @klannon please provide your feedback and decide if we should close the issue or anything else should be done here. Alan, I updated wiki page and added failure section where I outlined how alerts will be routed.

**Comment by amaltaro** [comment]
Awesome! Thank you for proactively updating the documentation as well:
https://github.com/dmwm/WMCore/wiki/MongoDB-backup-and-restore-procedure

which summarizes policy and decisions that we have taken. I think we can indeed close this out now, here we go!
