### ISSUE TITLE
Investigate slowness of DBS3Upload component under heavy load

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11767]
**Impact of the new feature**
Improve throughput of DBS3Upload component.

**Is your feature request related to a problem? Please describe.**
Due to recent incident with [resource pool meltdown](https://indico.cern.ch/event/1331390/contributions/5623808/attachments/2732415/4750453/WMCore%20-%20Resource%20Pool%20Meltdown%20Report%20(1).pdf) we found slowness of DBS3Upload components in multiple agents.  In particular, one of the agents had 10K open blocks and individual block took 3-5 min to resolve while after restart of DBS3Upload component it processed such blocks in 3-5 sec. We should investigate the cause of this issue. So far preliminary suspects are the following:
- slowness of SQL queries
- network issue with upstream DBS server
etc.

**Describe the solution you'd like**
Understand and resolve slowness of DBS3Upload component

**Describe alternatives you've considered**
Do nothing and leave with it

**Additional context**

**Comment by vkuznet** [comment]
Some additional information. From submit3 agent using DBS3Upload/ComponentLog I see the following:
```
2023-10-08 20:25:40,210:140489754543872:INFO:DBSUploadPoller:Found 12432 open blocks.
2023-10-08 20:25:40,230:140489754543872:INFO:DBSUploadPoller:Loaded 0 blocks from the database.
2023-10-09 03:15:36,461:140489754543872:INFO:DBSUploadPoller:Queueing block for insertion: /ggH_Hto2Sto4B_MH-125-MS-40-cta
uS-10_PTH-80_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM#cd5
90279-b9f2-473a-9c82-6a5e27892ce2
2023-10-09 03:15:36,463:140489754543872:INFO:DBSUploadPoller:Queueing block for insertion: /ggH_Hto2Sto4B_MH-125-MS-55-cta
uS-0p1_PTH-80_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM#bfbd7c0f-5b
38-4046-810f-ea2ceae4fdc2
...
```
and then over the sudden we have the following conditions:
```
2023-10-10 11:29:05,933:140605748287232:INFO:DBSUploadPoller:Found 11651 open blocks.
2023-10-10 11:29:14,432:140605748287232:INFO:DBSUploadPoller:Loaded 11651 blocks from the database.
2023-10-10 11:34:00,798:140605748287232:INFO:DBSUploadPoller:Have 1 files for block /ggH_Hto2Sto4B_MH-125-MS-23-ctauS-10_P
TH-80_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM#63a59523-be7c-47f0-
9191-81cf60d743bc
2023-10-10 11:39:05,643:140605748287232:INFO:DBSUploadPoller:Have 4 files for block /JPsito2Mu_JPsiFilter_2MuFilter_TuneCP
5_13p6TeV_pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM#5c5dbdbe-978d-4da9-a8fd-25704
6beffc0
...
```

The obvious questions are:
- why do we have O(10K) open blocks in first case and loaded 0 blocks from database, while
- in second case we have approximately the same amount of open blocks but the same amount of loaded blocks from database
Which conditions trigger to load at particular cycle all blocks from database? Do we need to constrain this amount of blocks to smaller number? Interestedly, once we load O(10K) blocks from database (which one) then each block record takes about 405 minutes to process. Looking further into top profile I found that we
have node saturation:
```
KiB Mem : 11507057+total, 16029780 free, 37839524 used, 61201268 buff/cache
KiB Swap: 33553404 total, 31724356 free,  1829048 used. 76602824 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  10391 cmsdata+  20   0   12.3g   4.0g   7136 S 421.2  3.6  85706:24 mariadbd
  10083 cmsdata+  20   0 7878632 179524   4692 S 164.2  0.2  72918:24 beam.smp
...
```
where we have quite some load on MariaDB and non-negligible RAM utilization. It seems to me that MariaDB consumes lots of node resources and slows down the entire process.

**Comment by amaltaro** [comment]
Just an update to this issue - because it's easier to lose this content in mattermost. 

The FNAL agent submit5 was running only the DBS3Upload component yesterday (all the other components had been stopped) and it took around 15h to go through 10k blocks, as can be seen in this log snippet
```
2023-10-12 05:59:16,105:140059579315968:INFO:DBSUploadPoller:Starting the DBSUpload Polling Cycle
2023-10-12 05:59:40,377:140059579315968:INFO:DBSUploadPoller:Found 9656 open blocks.
2023-10-12 05:59:44,384:140059579315968:INFO:DBSUploadPoller:Loaded 9656 blocks from the database.
2023-10-12 05:59:49,409:140059579315968:INFO:DBSUploadPoller:Have 1 files for block /WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM#4f4b3037-e70b-4c30-84a9-d
aa1f714c01b
...
2023-10-12 14:39:34,487:140059579315968:INFO:DBSUploadPoller:Have 1 files for block /ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM#5c7e2a64-6047-4ccb-8cdd-69eb20484c64
2023-10-12 14:50:30,128:140059579315968:INFO:DBSUploadPoller:Queueing block for insertion: /WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM#4f4b3037-e70b-4c30
-84a9-daa1f714c01b
...
2023-10-12 14:51:16,744:140059763263296:INFO:DBSUploadPoller:About to call insert block for: /TTtoBsto2Tau_BsFilter_TauTauFilter_TuneCP5_13p6TeV_pythia8-evtgen/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM#d70e455e-7893-4cde-9e0b-8fbd4f4e3b32
2023-10-12 15:23:15,119:140059763263296:INFO:DBSUploadPoller:About to call insert block for: /ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM#8e01f1c1-42bc-4229-839e-fb97b2b8811f
...
2023-10-12 21:53:10,613:140059579315968:INFO:BaseWorkerThread:DBSUploadPoller took 57234.507 secs to execute
2023-10-12 21:54:51,853:140059579315968:INFO:DBSUploadPoller:Starting the DBSUpload Polling Cycle
2023-10-12 21:55:02,432:140059579315968:INFO:DBSUploadPoller:Found 13577 open blocks.
```

we can make a few observations from this log:
* the component takes < 30 secs to retrieve the open blocks from MariaDB
* it took around 8h40min to load files and associate them to the relevant blocks
* it takes around 10min to queue these blocks in a multiprocess call to insert them into DBS
* then in this multiprocess execution of the dbs insert calls, it staled the logs for 6h30min (waiting for DBS server to reply to all of the insert requests?)

In addition, after inserting them into DBS, they should have been marked as closed and be gone from the next cycle. Yet, the component says `Found 13577 open blocks`. I checked a couple of block names and it looks like those are actually new blocks (they are not listed in the previous cycle log).

**Comment by vkuznet** [comment]
Alan, thanks for update. If I take your numbers here is my observations:
- 10K blocks in 6h30min for multiprocess execution is equal 21630 seconds
- I have no idea what multiprocess execution means, i.e. I do not know if it is sequential process(es) or not, but if I divide total time to 10K blocks it gives us around 20sec on average to insert the block
- if I look at DBS writer logs from vocms0750, here is my observation (please scroll horizontally to see how DBS log entry looks like, at the end it shows time of the request):
```
rg POST /cephfs/product/dbs-logs/dbs2go-global-w-*.log-20231012 | grep bulkblocks | grep prodsrv | head

/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x82dd.log-20231012:[2023-10-12 13:32:12.407878011 +0000 UTC m=+222.670200331] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 1104 in 2 out] [remoteAddr: 10.100.130.128:59248] [X-Forwarded-For: 188.184.75.82] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 191.418241ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x82dd.log-20231012:[2023-10-12 13:32:18.205551097 +0000 UTC m=+228.467873417] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 42804 in 2 out] [remoteAddr: 10.100.130.128:59250] [X-Forwarded-For: 188.184.75.82] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 5.958781216s proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:50:47.900312536 +0000 UTC m=+18.839267176] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 836 in 2 out] [remoteAddr: 10.100.137.64:41138] [X-Forwarded-For: 188.185.89.202] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 144.312138ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:50:47.99190786 +0000 UTC m=+18.930862538] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 1184 in 2 out] [remoteAddr: 10.100.137.64:41140] [X-Forwarded-For: 188.185.89.202] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 233.80814ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:52:29.09537099 +0000 UTC m=+120.034325638] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 1041 in 2 out] [remoteAddr: 10.100.137.64:41146] [X-Forwarded-For: 188.185.89.202] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 115.061983ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:52:29.176204407 +0000 UTC m=+120.115159068] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 1093 in 2 out] [remoteAddr: 10.100.137.64:41144] [X-Forwarded-For: 188.185.89.202] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 195.894124ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:53:56.640501486 +0000 UTC m=+207.579456192] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 736 in 2 out] [remoteAddr: 10.100.106.64:48654] [X-Forwarded-For: 188.184.73.32] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 58.04745ms proxy-resp: 0]
/cephfs/product/dbs-logs/dbs2go-global-w-5c65bcc968-x6mmd.log-20231012:[2023-10-12 06:54:10.265695032 +0000 UTC m=+221.204649688] HTTP/1.1 200 POST /dbs/prod/global/DBSWriter/bulkblocks [data: 965 in 2 out] [remoteAddr: 10.100.137.64:41150] [X-Forwarded-For: 188.185.89.202] [X-Forwarded-Host: cmsweb-k8s-prodsrv.cern.ch] [auth: no-TLS cipher-none "/DC=ch/DC=cern/OU=computers/CN=tier0/vocms001.cern.ch" tier0@vocms001.cern.ch X509Proxy] [ref: "-" "DBSClient/Unknown/"] [req: 77.922276ms proxy-resp: 0]
```
Then, if I filter to extract request time which DBS measures, I see the following
```
rg POST /cephfs/product/dbs-logs/dbs2go-global-w-*.log-20231012 | grep bulkblocks | grep prodsrv | head | awk '{print $31}'
5.593826514s
187.177023ms
191.418241ms
5.958781216s
144.312138ms
233.80814ms
115.061983ms
195.894124ms
58.04745ms
77.922276ms
```
So, the `bulkblocks` DBS API is taking far less (from the above printout 9 out of 10 calls took less than a second) according to DBS log. Here I do not know which DN is used by WMAgent, I also assumes WMAgent talks to `cmsweb-k8s-prodsrv.cern.ch` backend which is behind `cmsweb-prod` frontend. Sai that:
- there is some discrepancy in terms of time spend in DBS request, according to WMA requests take on average 20sec while according to DBS log it only take less than a second (again out of first 5 entries)
- 20 sec is not that big either in terms of insert call since it really depends on complexity of underlying payload 
- therefore, 6h30min for DBS insertion for 10K blocks (or so) does not seem crazy.

But I have no idea what does it means that *it took around 8h40min to load files and associate them to the relevant blocks*. Where the files comes from, what this procedure looks like, how association is done?

**Comment by amaltaro** [comment]
As mentioned in this PR comment:
https://github.com/dmwm/WMCore/pull/11768#issuecomment-1763060939

most of the component latency is apparently coming from the RDMBS data update. It needs to be further analyzed in the future though and we might decide to make some larger refactoring of the component.

For now, we agreed to merge https://github.com/dmwm/WMCore/pull/11768, which is meant to improve the component logging and give us a better idea of critical sections of the component.
