### ISSUE TITLE
Failed Workflows due to Failure while creating WQE's

### ISSUE THREAD

**Issue by hassan11196** [dmwm/WMCore#11784]
Around 50 of these wfs failed after being staged\[1\] . Upon checking the WorkQueue Error logs for one request\[2\], it failed due to “input data has no locations”. However the data is transfered in Rucio and is in OK state\[3\].

The issue happened between staged to acquired transition, so as I understand the workflow wasn't able to get to a agent because no WQE was created, as the wf failed while creating the WQE.

The transferor ms however shows 57.38% transfer completion\[4\].

Workqueue logs:
```
INFO:reqmgrInteraction:Processing request pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349 at https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/spec
INFO:reqmgrInteraction:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/spec"
INFO:reqmgrInteraction:Executing processInboundWork with 1 inbound_work, throw: True and continuous: False
INFO:reqmgrInteraction:Splitting /pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/BTV-Run3Summer22NanoAODv12-00043_0 with policy name Dataset and policy params {'name': 'Dataset', 'args': {}}
ERROR:reqmgrInteraction:Terminal exception splitting WQE: {'Status': 'Negotiating', 'TeamName': 'production', 'WMBSUrl': None, 'WMSpec': <WMCore.WMSpec.WMWorkload.WMWorkloadHelper object at 0x7fe322af6e80>, 'RequestName': 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349', 'StartPolicy': {'policyName': 'Dataset', 'SliceType': 'NumberOfEvents', 'SplittingAlgo': 'EventAwareLumiBased', 'OpenRunningTimeout': 0, 'blowupFactor': 1, 'SliceSize': 84656}, 'EndPolicy': {'policyName': 'SingleShot'}, 'OpenForNewData': True, 'Inputs': {}, 'ProcessedInputs': [], 'RejectedInputs': [], 'PileupData': {}, 'ParentData': {}, 'ParentFlag': False, 'Jobs': 0, 'SiteWhitelist': [], 'SiteBlacklist': [], 'Dbs': None, 'Task': None, 'ParentQueueId': None, 'Priority': 0, 'SubscriptionId': None, 'EventsWritten': 0, 'FilesProcessed': 0, 'PercentComplete': 0, 'PercentSuccess': 0, 'TaskName': None, 'ACDC': {}, 'ChildQueueUrl': None, 'ParentQueueUrl': None, 'NumberOfLumis': 0, 'NumberOfEvents': 0, 'NumberOfFiles': 0, 'NumOfFilesAdded': 0, 'Mask': None, 'TimestampFoundNewData': 1698695884, 'NoInputUpdate': False, 'NoPileupUpdate': False, 'CreationTime': 1698695884}
ERROR:reqmgrInteraction:Failing workflow "pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349": Invalid WMSpec: 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349': Input data has no locations "/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM"
CRITICAL:reqmgrInteraction:Permanent failure processing request "pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349": Invalid WMSpec: 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349': Input data has no locations "/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM"
INFO:reqmgrInteraction:Marking request pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349 as failed in ReqMgr
```
\[1\] [https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=Run3Summer22NanoAODv12&ds\_pattern=JMENano12p5](https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=Run3Summer22NanoAODv12&ds_pattern=JMENano12p5)

\[2\] [https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv\_task\_BTV-Run3Summer22NanoAODv12-00043\_\_v1\_T\_231030\_153236\_8349](https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349)

\[3\] [https://cms-rucio-webui.cern.ch/rule?rule\_id=7c13f7a1b04c46f6bb4811cdf631b682#locks](https://cms-rucio-webui.cern.ch/rule?rule_id=7c13f7a1b04c46f6bb4811cdf631b682#locks)

\[4\] [https://cmsweb.cern.ch/ms-transferor/data/info?request=pdmvserv\_task\_BTV-Run3Summer22NanoAODv12-00043\_\_v1\_T\_231030\_153236\_8349](https://cmsweb.cern.ch/ms-transferor/data/info?request=pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349)

@amaltaro @haozturk

**Comment by vkuznet** [comment]
If I read the code right the exception happened at this line:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1073

The observations comes from missing log entry `Work splitting completed` after posted `Splitting ...`. Therefore, to understand the issue someone should clarify to me and others how WQ policy works. Since we're dealing with dataset I think  https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Dataset.py is used.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I didn't check the logs, but usually when we fail a workflow, this is the exception that we hit in global workqueue:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1162

To help with this debugging, I would suggest you to take 1 or 2 workflows and:
1. cross-check the time of workflow acquisition in global workqueue
2. compare it with what was knew to MSMonitor (check the logs)
3. check the status of transfers - might be a double check of the step above - using this API (note that you need to replace the workflow name): https://cmsweb.cern.ch/reqmgr2/data/transferinfo/pdmvserv_Run2023C_ZeroBias5_22Sep2023_v4_231019_184341_3923
4. as you already figured out, depending on the workflow construction, they can have different workqueue start policy. Meaning being: `Dataset`: the whole dataset is placed as a whole and needs to be available within the same location/RSE; `Block`: a full block is placed at a given location (but many blocks are likely placed for the same workflow).
5. IMO it will be important to know if the input data was being retrieved from another Disk endpoint or straight from Tape. For this you might have to contact the DM team.

I would like to connect you with @todor-ivanov and @khurtado as well to provide further assistance to this issue, in case I don't manage to follow this closely.

**Comment by vkuznet** [comment]
Alan, to start working on this I need to know the following:
- what is workqueue location of the logs, so far I assumed that it is under vocms0750:/cephfs/product/dmwm-logs/workqueue-2023*, is it correct or anything else
- I scan already logs in vocms0750:/cephfs/product/dmwm-logs//workqueue-2023111* and I can't find any failed workflow shown in original ticket description. Moreover, I can't find patterns, like "Terminal exception splitting WQE", or "Permanent failure processing request", am I looking into wrong logs or what is proper timestamp of the log I need to look at? We do have zipped old-logs archives but I need to know which date to use
- please specify where to check transfer status as I have no idea
- to contact DM team about disk/tape transfer which channel I should use (again I never did such activity before and therefore have no a-prior knowledge where to look at).

**Comment by vkuznet** [comment]
I checked old-logs and found listed exception. Upon further checks I see strange correlation in WQ logs, like this:
```
ERROR:reqmgrInteraction:Unknown error processing ahmedmu_ACDC1_Run2022E_ZeroBias_30May2023v2_230829_130657_7479
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 108, in queueNewRequests
    units = queue.queueWork(workLoadUrl, request=reqName, team=team)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 646, in queueWork
    work = self.processInboundWork(inbound, throw=True)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1133, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1073, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 161, in __call__
    self.split()
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 70, in split
    Jobs=ceil(float(block[self.args['SliceType']]) /
KeyError: 'NumberOfRuns'
INFO:reqmgrInteraction:Processing request pdmvserv_task_GEN-Run3Summer22NanoAODv12-00377__v1_T_231030_152553_9919 at https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_GEN-Run3Summer22NanoAODv12-00377__v1_T_231030_152553_9919/spec
INFO:reqmgrInteraction:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_GEN-Run3Summer22NanoAODv12-00377__v1_T_231030_152553_9919/spec"
INFO:reqmgrInteraction:Executing processInboundWork with 1 inbound_work, throw: True and continuous: False
INFO:reqmgrInteraction:Splitting /pdmvserv_task_GEN-Run3Summer22NanoAODv12-00377__v1_T_231030_152553_9919/GEN-Run3Summer22NanoAODv12-00377_0 with policy name Dataset and policy params {'name': 'Dataset', 'args': {}}
ERROR:reqmgrInteraction:Terminal exception splitting WQE: {'Status': 'Negotiating', 'TeamName': 'production', 'WMBSUrl': None, 'WMSpec': <WMCore.WMSpec.WMWorkload.WMWorkloadHelper object at 0x7fe2f4413d60>, 'RequestName': 'pdmvserv_task_GEN-Run3Summer22NanoAODv12-00377__v1_T_231030_152553_9919', 'StartPolicy': {'policyName': 'Dataset', 'SliceType': 'NumberOfEvents', 'SplittingAlgo': 'EventAwareLumiBased', 'OpenRunningTimeout': 0, 'blowupFactor': 1, 'SliceSize': 84656}, 'EndPolicy': {'policyName': 'SingleShot'}, 'OpenForNewData': True, 'Inputs': {}, 'ProcessedInputs': [], 'RejectedInputs': [], 'PileupData': {}, 'ParentData': {}, 'ParentFlag': False, 'Jobs': 0, 'SiteWhitelist': [], 'SiteBlacklist': [], 'Dbs': None, 'Task': None, 'ParentQueueId': None, 'Priority': 0, 'SubscriptionId': None, 'EventsWritten': 0, 'FilesProcessed': 0, 'PercentComplete': 0, 'PercentSuccess': 0, 'TaskName': None, 'ACDC': {}, 'ChildQueueUrl': None, 'ParentQueueUrl': None, 'NumberOfLumis': 0, 'NumberOfEvents': 0, 'NumberOfFiles': 0, 'NumOfFilesAdded': 0, 'Mask': None, 'TimestampFoundNewData': 1698691638, 'NoInputUpdate': False, 'NoPileupUpdate': False, 'CreationTime': 1698691638}
```
I checked couple of logs and such behavior is there. I wonder if thrown exception with `NumberOfRuns` may caused later an issue within the same thread. I do not want to spend too much time on shown exception unless I'll be told otherwise, but it happens over here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L70 and I have no idea how/where `NumberOfRuns` come from. @amaltaro please advise.

**Comment by amaltaro** [comment]
The error above is unrelated, see for further information: https://mattermost.web.cern.ch/cms-o-and-c/pl/d9fbh3anfidt5mxsogagocuksw

In addition, you are reporting an error for a workflow that is in `staged` status, while this ticket report problems with workflows in `failed` status.

**Comment by vkuznet** [comment]
Further digging through the code. The actual exception happen in here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py#L141 which asks spec for `Inputs` and see that there is no site. According to the log the spec indeed does not show any `inputs`. Therefore, we need to find out who provided the spec which does not have inputs and where it is constructed. @amaltaro any thoughts on this find?

Another observations:
- workqueue log does not record timestamps at all !!! Why is that? Why logs does not have any timestamp?
- who generate `reqmgrInteractionTask-workqueue` log? I found it when I scan for workflow name and it contains timestamp for this workflow 2023-10-30 19:58:05,113 which shows splitting error
- according to reqmgr2 json, the staged transition state happen at 2023-10-30 19:49:37 UTC
- while, failed status recorded at 2023-10-30 19:58:09 UTC
- therefore, if I'll take timestamp of reqmgrInteractionTask-workqueue we have window between 2023-10-30 19:49:37 UTC and 2023-10-30 19:58:05,113 during which wf failed. It is about 10 minutes and I don't know how to check DM side for it.

So, in order to proceed I need to know where `Inputs` in spec are generated as they were not provided for splitting and according to the code logic the proper exception was thrown.

**Comment by vkuznet** [comment]
I checked MSOutput and other MS services for appearance of `%2FQCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8%2FRun3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2%2FMINIAODSIM` dataset (it should be properly url encoded). And, I found that MSoutput does not have any entries about it, while ms-rulecleaner does, in latter case all requests to rucio were ok. I also checked DAS for dataset presence and it shows that it indeed fully present at T1_DE_KIT (both disk and tape), therefore I would conclude that transfer itself was fine. Said that, as I wrote about it looks like the dataset splitting fail due to missing `inputs` and so far I have no idea how this is done. @amaltaro any further suggestions?

**Comment by amaltaro** [comment]
Valentin, on your question about which log file to use, we need to check `reqmgrInteractionTask-workqueue-XXX.log`, which is the workqueue cherrypy thread responsible for acquiring work from ReqMgr2 and splitting it into workqueue elements. BTW, you will see it has timestamps.

There is nothing in MSOutput relevant for this debugging, the microservice that I mentioned above is MSMonitor. MSRuleCleaner is performing cleanup, which is irrelevant to this debugging as well.

Looking for data presence in DAS does not give us a good answer either, as it's simply checking data location regardless of who locked the data. For WM, we only care about data that is available under our own rules (locks).

The question that we need to answer is: when the workflow was acquired (or processed) in global workqueue, was the input data requested by the workflow fully available on Disk (under the WM-created rules)?

**Comment by vkuznet** [comment]
The MSMonitor uses slashes instead of escaped `%2F`, that's why I haven't see it. The entries for dataset in question is:
```
2023-10-30 19:46:15,666:DEBUG:MSMonitor: Rule ID: 7c13f7a1b04c46f6bb4811cdf631b682, DID: /QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM, state: REPLICATING, grouping: ALL, rse_expression: T2_US_Caltech|T2_RU_JINR|T2_EE_Estonia|T2_IT_Rome|T2_BR_SPRACE|T2_ES_IFCA|T1_IT_CNAF_Disk|T2_US_Florida|T2_UK_London_IC|T2_US_MIT|T2_FR_GRIF_IRFU|T2_US_Vanderbilt|T2_US_Wisconsin|T2_US_Nebraska|T1_RU_JINR_Disk|T2_BE_UCL|T2_IT_Pisa|T2_BR_UERJ|T2_FR_GRIF_LLR|T2_US_Purdue|T2_PL_Swierk|T2_CH_CSCS|T2_UK_SGrid_Bristol|T2_US_UCSD|T2_ES_CIEMAT|T2_BE_IIHE|T2_CH_CERN|T1_DE_KIT_Disk|T1_US_FNAL_Disk
```
which lists T1_DE_KIT site. And, matching ruleid I see that
```
2023-10-30 19:46:15,666:INFO:MSMonitor: Rule ID: 7c13f7a1b04c46f6bb4811cdf631b682 has a completion rate of: 57.831325301204814%
```
So, MSMonitor shows `57%` of completion. The timestamp is 3 min away from the one shown in  WQ logs. Does it mean that the dataset was not migrated?

**Comment by vkuznet** [comment]
I checked another wf: `pdmvserv_task_GEN-Run3Summer22NanoAODv12-00361__v1_T_231103_003952_2508` from Dima's list. This uses `/G-4Jets_HT-200to400_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Summer22NanoAODv12-JMENano12p5_132X_mcRun3_2022_realistic_v3-v1/NANOAODSIM`
 dataset and it is listed as stated in MSMonitori 
```
2023-11-03 06:16:06,434:DEBUG:MSMonitor: Checking transfers for: pdmvserv_task_GEN-Run3Summer22NanoAODv12-00361__v1_T_231103_003952_2508
2023-11-03 06:16:06,445:INFO:MSMonitor: pdmvserv_task_GEN-Run3Summer22NanoAODv12-00361__v1_T_231103_003952_2508 OK, all transfers completed or above threshold, move it on.
2023-11-03 06:16:06,675:INFO:ReqMgrAux: Update in-place: False for transfer doc: pdmvserv_task_GEN-Run3Summer22NanoAODv12-00361__v1_T_231103_003952_2508 was successful.
6179:2023-11-03 06:16:07,332:INFO:MSCore: MSMonitor updating pdmvserv_task_GEN-Run3Summer22NanoAODv12-00361__v1_T_231103_003952_2508 status to: staged
```
This is different from `pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349` workflow which shows 57% completion in MSMonitor.

**Comment by vkuznet** [comment]
and, yet another wf `pdmvserv_task_BTV-Run3Summer22NanoAODv12-00056__v1_T_231101_121341_3043`
```
2023-11-01 17:06:51,188:DEBUG:MSMonitor: Checking transfers for: pdmvserv_task_BTV-Run3Summer22NanoAODv12-00056__v1_T_231101_121341_3043
2023-11-01 17:06:54,068:INFO:MSMonitor: pdmvserv_task_BTV-Run3Summer22NanoAODv12-00056__v1_T_231101_121341_3043 OK, all transfers completed or above threshold, move it on.
2023-11-01 17:06:54,692:INFO:ReqMgrAux: Update in-place: False for transfer doc: pdmvserv_task_BTV-Run3Summer22NanoAODv12-00056__v1_T_231101_121341_3043 was successful.
2023-11-01 17:07:07,632:INFO:MSCore: MSMonitor updating pdmvserv_task_BTV-Run3Summer22NanoAODv12-00056__v1_T_231101_121341_3043 status to: staged
```
which is listed as staged in MSMonitor.

**Comment by vkuznet** [comment]
To proceed someone should explain to me how splitting algorithm works. At this point I don't see that for last two workflows we had any issues with Rucio, but yet the `Inputs` were empty and it caused the exception to terminate the workflows. This leads me only to one direction, to investigate the splitting algorithm. Can someone (@amaltaro  or @todor-ivanov ) explain what splitting means when we have single dataset, what it does or suppose to do, and which codebase is responsible for it.

**Comment by vkuznet** [comment]
I scan few more workflows and found very suspicious correlation, that lots of workflows were failed approximately at the same time, e.g.:
```
pdmvserv_task_PPD-Run3Summer22NanoAODv12-00007__v1_T_231030_173340_87
failed: 2023-10-30 19:59:34 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00042__v1_T_231030_173333_9435
failed: 2023-10-30 19:56:12 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00041__v1_T_231030_173325_3835
failed: 2023-10-30 19:55:17 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00040__v1_T_231030_173328_4644
failed: 2023-10-30 19:58:47 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00039__v1_T_231030_173319_1967
failed: 2023-10-30 19:56:58 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00038__v1_T_231030_173308_6228
failed: 2023-10-30 19:56:08 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00037__v1_T_231030_173314_7744
failed: 2023-10-30 19:56:53 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00036__v1_T_231030_173321_9101
failed: 2023-10-30 20:00:43 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_EGM-Run3Summer22NanoAODv12-00035__v1_T_231030_173301_4127
failed: 2023-10-30 19:58:51 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_BTV-Run3Summer22NanoAODv12-00064__v1_T_231030_173252_227
failed: 2023-10-30 19:59:20 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_BTV-Run3Summer22NanoAODv12-00063__v1_T_231030_173248_8080
failed: 2023-10-30 19:59:18 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_BTV-Run3Summer22NanoAODv12-00062__v1_T_231030_173224_1709
failed: 2023-10-30 19:55:43 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account

pdmvserv_task_BTV-Run3Summer22NanoAODv12-00061__v1_T_231030_173219_5947
failed: 2023-10-30 19:58:12 UTC DN: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=msunmer/CN=852819/CN=Robot: WmCore Service Account
```
So within couple of minutes lots of workflows failed which may implies that we had some issues with some service/network. I was trying to look at behavior of MS services at this timestamp in CMS Monitoring but turns out that MS service monitoring page https://monit-grafana.cern.ch/d/JIz-EqvVz/wmcore-ms-services?orgId=11&refresh=1m&from=now-7d&to=now does not have any metrics (new [CMSMONIT-584](https://its.cern.ch/jira/browse/CMSMONIT-584) issue which II file to CMSWEB/CMS Monitoring). I need more time to check logs for these workflows. Will update this comment once I get into them.

**Comment by todor-ivanov** [comment]
@vkuznet  Upon a long  review of the logic in WMCore, I do not see this  behavior here as a bug.  WMCore system is doing the right thing here - it simply fails the workflows without intersection between `SiteWhitelist` and the those having the  datasets (the start policy for those workflows is: `with policy name Dataset and policy params {'name': 'Dataset', 'args': {}}`) 
At the same time these workflows are having:  ` "TrustSitelists": false,`

**Comment by amaltaro** [comment]
I had a look at the very first workflow reported in this ticket, which is:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349

and here are my observations:
* it entered the `staged` status on `2023-10-30 19:49:37 UTC`; and `failed` ~10min later
* it has around 30 allowed sites and a list of 10 or so disallowed sites;
* it has TrustSitelists: false
* it has TrustPUSitelists: false, it has no pileup
* input dataset `/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM` has 35 blocks


Global WorkQueue logs (WorkQueueReqMgrInterface thread) are:
```
2023-10-30 19:58:04,707:INFO:WorkQueueReqMgrInterface:Processing request pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349 at https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/spec
2023-10-30 19:58:04,708:INFO:WorkQueue:queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/spec"
2023-10-30 19:58:04,990:INFO:WorkQueue:Executing processInboundWork with 1 inbound_work, throw: True and continuous: False
2023-10-30 19:58:05,113:INFO:WorkQueue:Splitting /pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349/BTV-Run3Summer22NanoAODv12-00043_0 with policy name Dataset and policy params {'name': 'Dataset', 'args': {}}
2023-10-30 19:58:07,275:ERROR:WorkQueue:Terminal exception splitting WQE: {'Status': 'Negotiating', 'TeamName': 'production', 'WMBSUrl': None, 'WMSpec': <WMCore.WMSpec.WMWorkload.WMWorkloadHelper object at 0x7fe322af6e80>, 'RequestName': 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349', 'StartPolicy': {'policyName': 'Dataset', 'SliceType': 'NumberOfEvents', 'SplittingAlgo': 'EventAwareLumiBased', 'OpenRunningTimeout': 0, 'blowupFactor': 1, 'SliceSize': 84656}, 'EndPolicy': {'policyName': 'SingleShot'}, 'OpenForNewData': True, 'Inputs': {}, 'ProcessedInputs': [], 'RejectedInputs': [], 'PileupData': {}, 'ParentData': {}, 'ParentFlag': False, 'Jobs': 0, 'SiteWhitelist': [], 'SiteBlacklist': [], 'Dbs': None, 'Task': None, 'ParentQueueId': None, 'Priority': 0, 'SubscriptionId': None, 'EventsWritten': 0, 'FilesProcessed': 0, 'PercentComplete': 0, 'PercentSuccess': 0, 'TaskName': None, 'ACDC': {}, 'ChildQueueUrl': None, 'ParentQueueUrl': None, 'NumberOfLumis': 0, 'NumberOfEvents': 0, 'NumberOfFiles': 0, 'NumOfFilesAdded': 0, 'Mask': None, 'TimestampFoundNewData': 1698695884, 'NoInputUpdate': False, 'NoPileupUpdate': False, 'CreationTime': 1698695884}
2023-10-30 19:58:07,349:ERROR:WorkQueue:Failing workflow "pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349": Invalid WMSpec: 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349': Input data has no locations "/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM"
2023-10-30 19:58:08,469:CRITICAL:WorkQueueReqMgrInterface:Permanent failure processing request "pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349": Invalid WMSpec: 'pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349': Input data has no locations "/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM"
2023-10-30 19:58:08,470:INFO:WorkQueueReqMgrInterface:Marking request pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349 as failed in ReqMgr
```

while MSMonitor logs are:
```
2023-10-30 19:46:15,658:DEBUG:MSMonitor: Checking transfers for: pdmvserv_task_BTV-Run3Summer22NanoAODv12-00043__v1_T_231030_153236_8349 
2023-10-30 19:46:15,665:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "GET /rules/7c13f7a1b04c46f6bb4811cdf631b682 HTTP/1.1" 200 1367
2023-10-30 19:46:15,666:INFO:MSMonitor: Rule ID: 7c13f7a1b04c46f6bb4811cdf631b682 has a completion rate of: 57.831325301204814%
2023-10-30 19:46:15,666:DEBUG:MSMonitor: Rule ID: 7c13f7a1b04c46f6bb4811cdf631b682, DID: /QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v2/MINIAODSIM, state: REPLICATING, grouping: ALL, rse_expression: T2_US_Caltech|T2_RU_JINR|T2_EE_Estonia|T2_IT_Rome|T2_BR_SPRACE|T2_ES_IFCA|T1_IT_CNAF_Disk|T2_US_Florida|T2_UK_London_IC|T2_US_MIT|T2_FR_GRIF_IRFU|T2_US_Vanderbilt|T2_US_Wisconsin|T2_US_Nebraska|T1_RU_JINR_Disk|T2_BE_UCL|T2_IT_Pisa|T2_BR_UERJ|T2_FR_GRIF_LLR|T2_US_Purdue|T2_PL_Swierk|T2_CH_CSCS|T2_UK_SGrid_Bristol|T2_US_UCSD|T2_ES_CIEMAT|T2_BE_IIHE|T2_CH_CERN|T1_DE_KIT_Disk|T1_US_FNAL_Disk
```

As stated above, this workflow did arrive in Global WorkQueue with data partially available on Disk.

**Comment by vkuznet** [comment]
The new WMCore tag with changes from #11810 is [2.2.4.7](https://github.com/dmwm/WMCore/tree/2.2.4.7), and it is deployed on testbed.
