### ISSUE TITLE
Crosscheck for duplicate lumis

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11796]
**Impact of the bug**
Operational issue 

**Describe the bug**
This is a followup issue of the Jira ticket created by P&R:  https://its.cern.ch/jira/browse/CMSPROD-85 

Here follows the so suggested plan by @amaltaro  for confirming or ruling out the WMcore's involvement and/or eventual bug in the lumisection duplication in the workflow's output. This was discussed in the regular WMCore weekly meeting:

* Are the workflows legit clones? Or has there been some override that went unnoticed?
* Is there any duplicate run/lumi on the input dataset?
* Has there been any **recent** file invalidation on the input dataset?
* Was there any operational mistake? If the workflows have no ACDC, we can rule this out. If they do, we need them to check whether the correct task has been recovered only **once**.
* Valentin’s [wflow-dbs](https://cmsweb-testbed.cern.ch/wflow-dbs/stats?workflow=pdmvserv_Run2022A_DoubleMuon_30May2023_230607_174045_359) tool can be used for finding out duplicate lumis, but use it with care because Alan thinks that there are issues with the codebase.

**How to reproduce it**
Unclear

**Expected behavior**
There should be no duplicated lumisections in the output 

**Additional context and error message**
There were few similar issues in the past, which we should dig out an list here.

**Comment by vkuznet** [comment]
@todor-ivanov , you can view the wflow-dbs codebase over here https://github.com/vkuznet/wflow-dbs and adjust if there are doubts about its logic.

**Comment by todor-ivanov** [comment]
thanks @vkuznet I'll double check the logic there.
