### ISSUE TITLE
No jobdetail information for workflows

### ISSUE THREAD

**Issue by lucalavezzo** [dmwm/WMCore#11820]
**Impact of the bug**
P&R ACDC databases need information regarding exitCodes to display information about failures across the system and submit ACDCs.

**Describe the bug**
The wmsstatsserver jobdetail endpoint appears empty for some workflows, some times.
[This ](https://gitlab.cern.ch/CMSProductionReprocessing/WmAgentScripts/-/blob/python3-migration/src/python/Services/WMStats/WMStatsReader.py#L56-68) is how we read it, but even navigating to it via browser shows an empty page, so I don't believe it's an issue of how we read it.

**How to reproduce it**
Some examples:

- https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/pdmvserv_task_BPH-RunIISummer20UL18GEN-00237__v1_T_230926_104347_8763
- https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/wangz_ACDC1_task_GEN-Run3Summer22EEwmLHEGS-00479__v1_T_231201_223414_5800
- https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/cmsunified_task_EXO-RunIIFall18GS-05548__v1_T_230915_125606_6488

**Expected behavior**
Here is some examples of something that I would expect

- https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/llavezzo_task_EXO-Run3Summer22MiniAODv4-00112__v1_T_231110_180302_2038
- https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/pdmvserv_task_GEN-Run3Summer22EEwmLHEGS-00361__v1_T_231012_195915_7504

**Comment by z4027163** [comment]
There is an extra issue which might be related. The Exit code isn't properly parsed so it leads to:
1. Error message without line changing
example: https://cms-unified.web.cern.ch/cms-unified/report/cmsunified_ACDC0_task_EXO-RunIIFall17GS-07823__v1_T_231115_005644_458 

2. No Exit code:
example: https://cms-unified.web.cern.ch/cms-unified/report/wangz_r-0-Run2017G_DoubleMuon_UL2017_MiniAODv2_BParking_240104_200314_2623

**Comment by z4027163** [comment]
Another example: https://cms-unified.web.cern.ch/cms-unified/report/wangz_ACDC1_Run2018D_EGamma_UL2018_MiniAODv2_BParking_240108_221907_5689 

No error report

**Comment by z4027163** [comment]
Another example with a special case, which may help resolve this problem. 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-Run3Summer22MiniAODv4-00153 
In this WF, ACDC2 and ACDC5 shows 8001 error with error "[a] Fatal Root Error: @SUB=TTreeCache::FillBuffer".
ACDC3 and ACDC4 don't have exit code.
It's the same error and somehow in ACDC3 and ACDC4 there is nothing returned.

**Comment by amaltaro** [comment]
@lucalavezzo @z4027163 after investigating this workflow

> No Exit code:
example: https://cms-unified.web.cern.ch/cms-unified/report/wangz_r-0-Run2017G_DoubleMuon_UL2017_MiniAODv2_BParking_240104_200314_2623

I can see from submit8 that we actually had the same issue as the one reported in:
https://github.com/dmwm/WMCore/issues/11771#issuecomment-1793165161

That issue has been resolved with a 2nd iteration fix, but it was not backported to the agents that we are currently swapping out of production (version 2.2.5).

The new agent that started getting rolled into production by the end of the past week - version 2.3.0 - should have this 2nd iteration fix and I do not expect to have job report data loss again.

For the moment, I would suggest to close this issue; and if we see lack of job details for workflows that started after Jan 20th, 2024, we should then reopen this issue.

For the workflows missing job details, unfortunately we cannot recover those details. So I would suggest to use the documents in the ACDC server for any followup workflow recovery.

Please let us know what you think and/or if you have any questions.

**Comment by lucalavezzo** [comment]
Hi Alan,

Thank you for the explanation!

However, I want to clarify something: the wmstatsserver pages for these workflows (linked in issue description) are completely empty, it's not that we don't see exitCodes, we don't see anything. Is that exactly the same issue as missing exitCodes?

We will monitor this in the next couple of weeks to see how it develops, as workflows that started on the 20th of Jan will begin to finish. Can we please keep the issue open until we can confirm that this is issue is really gone?

Thank youo,
Luca

**Comment by amaltaro** [comment]
@lucalavezzo Hi Luca, yes, it's the same problem, but triggered in a slightly later stage in the component logic. The impact is that those documents are not retried (they are larger than the limit of 8MB) and we don't even try to make them smaller.

With the latest fix, we will try to reduce the file, if possible, and upload it to couchdb.

**Comment by lucalavezzo** [comment]
@amaltaro Just so that we understand on our end, are there cases then in which no exitCodes are expected? (e.g. very large documents). We really depend on this information for some fundamental aspects in our databases, like the lists tasks in each workflow, so we need to understand whether we can expect that this will work 100% of the time, or we need to build systems to deal with the hopefully occasional issue that we would expect. FYI @z4027163

**Comment by amaltaro** [comment]
@lucalavezzo I reviewed the two PRs fixing this issue:
https://github.com/dmwm/WMCore/pull/11502/files
and
https://github.com/dmwm/WMCore/pull/11786/files

and I am almost sure that we will have something reported in WMStats (including the exit code). It's not impossible that I am mistaken and/or missing something as well. 

If you can identify error messages missing in WMStats, then we shall discover that in the coming weeks/months. What do you think?

**Comment by lucalavezzo** [comment]
Perfect, thank you very much for all your detailed responses :)
We will keep an eye on this issue and report back to you.

**Comment by hassan11196** [comment]
Hello @amaltaro,
This workflows Failure rate is 46% but no Logs for a workflow in wmstats.

![image](https://github.com/dmwm/WMCore/assets/33365802/00fd29d2-7a03-4072-9977-54f7fdb30e37)
![image](https://github.com/dmwm/WMCore/assets/33365802/11fcc5fb-11cf-46ce-90ed-6847cb2923c0)

[cmsunified_task_PPD-Run3Summer22wmLHEGS-Backfill-00016__v1_T_240125_170259_2990](https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_PPD-Run3Summer22wmLHEGS-Backfill-00016__v1_T_240125_170259_2990)

**Comment by anpicci** [comment]
Hi @hassan11196 ,
we restarted `AgentStatusWatcher` component for voms0281, and this makes the jobdetails log appear in WMStats.

Thanks,
Andrea

**Comment by lucalavezzo** [comment]
Ciao @anpicci, 

Thank you for your prompt response!
Does this mean that we can expect temporary 'outages' in the jobdetails from time to time?
Or is this a leftover issue that was fixed by the latest fix that Alan mentioned, which for some reason wasn't applied to this job/agent?
Again, we are just trying to understand how to set up our systems to best interplay with yours.

Best,
Luca

**Comment by amaltaro** [comment]
@lucalavezzo this is an unexpected issue with database replication. We can definitely not prevent it from happening in the future, or having one of the agent's components down. So yes, there could be a period of time where job documents don't get replicated to WMStats, but the system usually recovers itself before you can even spot those.

**Comment by lucalavezzo** [comment]
@amaltaro thank you very much for the information. If it's okay, we will keep this ticket open for another week or two just to be 100% sure, but I am glad this issue seems resolved.

**Comment by amaltaro** [comment]
@lucalavezzo we discussed this issue in today's WMCore meeting and Hassan thinks it can now be closed. I am going to close this out, but feel free to reopen it if this same problem occurs again. Thanks!

**Comment by lucalavezzo** [comment]
@amaltaro Thank you, sounds good to me.
