### ISSUE TITLE
Training: Standard WM debugging

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11849]
**Impact of the new feature**
WM in general

**Is your feature request related to a problem? Please describe.**
Sharing knowledge and empowering WM/Ops to understand and debug the system. Sub-task of https://github.com/dmwm/WMCore/issues/11837

**Describe the solution you'd like**
Topic of this ticket is: Standard WM debugging

For the expected solution, please refer to the meta-issue for further details (in short: documentation + recorded presentation).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by germanfgv** [comment]
Thanks for the efforts @amaltaro. Here I'll leave a few subjects that I think should be included in this training:
- Debugging on running components
  - Attaching debuggers to component processes
  - Safety considerations and best practices when working on production environments
- Reproducing issues on testing environments
- CouchDB logs and test queries

I would also like to see material on the following subjects, although I'm not sure they fall into the scope of this training (maybe useful for a future session):
- Setup development environment
- Applying patches in development env (and production?)
- Running tests

**Comment by amaltaro** [comment]
My opinion for a basic debugging is:
* workflow status based debugging (according to the status, where we need to look for information)
* heartbeat timeout debugging
* multi-thread WMAgent components investigation

**Comment by todor-ivanov** [comment]
I would actually not add anything new but I'd mostly like to second  @germanfgv 's suggestion. Thanks German! All of what you requested is falling perfectly under this session, and I'll be pretty happy to walk through those. If you want we  can even meet in advance and you let me know about any particular use case you may have already encountered.

**Comment by hassan11196** [comment]
I second @germanfgv suggestions, they are all highly useful topics that I would also be interested in.

If in scope, I would also like to add a topic on debugging WQEs, Why a certain WQE was picked or what the next WQEs a workflows will be picked by the agent next. I find this process of pulling work opaque and would like to know how to debug this in the agents.

Thank you.

**Comment by anpicci** [comment]
I'm closing the issue, since the training has been held successfully

**Comment by amaltaro** [comment]
@anpicci let me reopen it such that we do not forget the deliverables - as discussed in yesterday's meeting and post-meeting on MM - a page in wmcore-docs with those questions/answers that we addressed in the training, plus the others that we did not manage to cover.

I plan to have it done today, but in case I miss it, we have this open issue to remind me.

**Comment by mapellidario** [comment]
After discussing with alan, here is the new page in wmcore-docs.

- https://cms-wmcore.docs.cern.ch/training/workflow-troubleshoot/
- introduced with the merge request https://gitlab.cern.ch/dmwm/wmcore-docs/-/merge_requests/70

I think we can close this issue

**Comment by amaltaro** [comment]
Awesome, thank you very much, Dario. I am closing this ticket out as completed now. Thanks again everyone!
