### ISSUE TITLE
stage-out script maintenance/overhault/basic support

### ISSUE THREAD

**Issue by stlammel** [dmwm/WMCore#11864]
Re: R: Feedback request for WM Q1/2024 Planning
Alan Malta Rodrigues [alan.malta@cern.ch]
Sent: 	Tuesday, January 16, 2024 16:49
To: 	
[Stephan Lammel](https://outlook.office365.com/owa/?ae=Item&t=IPM.Note&id=RgAAAABj2mJknaEJT41TncfeJm4bBwBrJOO8KiuzRrfEMgv21HiZAAAAFs3UAACZDIVSBx4%2bQ5WdGpsCR7O1AAeV2LqpAAAJ#); [klannon@nd.edu](https://outlook.office365.com/owa/?ae=Item&t=IPM.Note&a=New&to=klannon%40nd.edu&nm=klannon%40nd.edu)
Hi Stephan,

apologies for the belated reply.

I feel like we are pretty much packed for this quarter. However, a better argument for postponing it a little longer would be to first get the storage.json
changes in place and get some experience with it in production.

With that in place, enhancing stage out code should be easier and more clear. AFAIR you want to have better logging for when stage out issues arise, right?
In addition, if we still don't have a WMCore issue to track that, would you mind creating a new "Feature request" ticket in WMCore:
[https://github.com/dmwm/WMCore/issues/new/choose](https://outlook.office365.com/owa/redir.aspx?REF=DkkbCD5YUbNV0RkDqP0nowwva0AOKkq1GReXghRTOwZYX0PQZBfcCAFodHRwczovL3VybGRlZmVuc2UucHJvb2Zwb2ludC5jb20vdjIvdXJsP3U9aHR0cHMtM0FfX2dpdGh1Yi5jb21fZG13bV9XTUNvcmVfaXNzdWVzX25ld19jaG9vc2UmZD1Ed01HYVEmYz1nUmdHakozQmtJc2I1eTZzNDlRcXNBJnI9Rl9Wb1RiWWxrWlJDMzdfeTNuVVkzUSZtPVV5UkFIZ2ZUOG93WVVjaG5kaTVsTXF1RnhKeWFVMlk1TjJnbDVCZ2tTbzh6NUluOVd3VFJ4TEJNUm1IODJpajAmcz1qc01JX0FzeWFMSHdxZDQ4bDRrNDExLUlVYkhpME5TU1pRMmZJc3ZFU0NrJmU9)
?

Thanks,
Alan.
From: Stephan Lammel <lammel@fnal.gov>
Sent: Thursday, January 11, 2024 4:38 PM
To: klannon@nd.edu <klannon@nd.edu>
Cc: Alan Malta Rodrigues <alan.malta@cern.ch>
Subject: RE: R: Feedback request for WM Q1/2024 Planning
 
Hallo Kevin,
   thanks for sharing the proposed WM Q1 plan. Would it be
possible to include the first step on upgrading the stage-out
scripts? I am willing to contribute to better stage-out scripts
but would need a little, less-than-an-hour, overview/guidance
as first step.
   Thanks,
           cheers,  Stephan

**Comment by nhduongvn** [comment]
@stlammel I might have time to contribute too, so please include me in the " less-than-an-hour, overview/guidance
as first step." as well.

**Comment by amaltaro** [comment]
This is an ill defined ticket and we already have this ticket:
https://github.com/dmwm/WMCore/issues/11731

that Stephan created some months ago. I suggest to adjust the description of the other ticket and carry with any follow up on that one. Closing this one out.

**Comment by stlammel** [comment]
Yes, i'll let you know once Alan/Tudor find time. From the WM work planning discussion in today's O&C meeting probably not for a couple of months, unfortunately.
 - Stephan
