### ISSUE TITLE
Unable to shutdown old agent in vocms0282 because of DBS blocks failing to be inserted

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11865]
**Impact of the bug**
WMCore

**Describe the bug**
WMAgent on vocms0282 is now going to be 3 releases behind - it is still running on 2.2.0.4 - as we are unable to completely drain it, given that there are still 2 blocks to be inserted into DBS, which keep failing for many months now.

This issue is meant to be debug on the DBS side, but given the impact on WMCore, here is a ticket for us as well.
This is also been tracked in this DBS ticket: https://github.com/dmwm/dbs2go/issues/98

**How to reproduce it**
None

**Expected behavior**
Understand why those blocks fail to be inserted into DBS and decide what to do:
a) fix the problem and inject the whole block
b) shrink that block and inject only what DBS is accepting
c) abort those workflows and run them from scratch
d) etc

**Additional context and error message**
None

**Comment by jenimal** [comment]
Workflow is in rejected-archived so we can move ahead with shutting down the agent and just forgetting these blocks.

**Comment by amaltaro** [comment]
Thank you Jen for figuring this out during the P&R meeting. The workflow has been rejected:
https://cmsweb.cern.ch/reqmgr2/data/request?outputdataset=/DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Reco-TRKRealistic_AlcaRecoRealisticTRK_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RECO

and we no longer care about its output data. Closing this one out as unplanned (even though it took some cycles from me and Dennis).
