### ISSUE TITLE
Review/update links and pointers to the GitHub wiki documentation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11876]
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
This is a sub-task of this meta issue: https://github.com/dmwm/WMCore/issues/11875

Towards the migration of WMCore GitHub documentation over to the CERN GitLab platform.

**Describe the solution you'd like**
Review documentation in the GitLab repository:
https://gitlab.cern.ch/dmwm/wmcore-docs
and update any reference to the (now) old GitHub WMCore wiki.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by d-ylee** [comment]
Resolved in https://gitlab.cern.ch/dmwm/wmcore-docs/-/merge_requests/22. Closing.
