### ISSUE TITLE
Create new documentation repository on CERN gitlab

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11871]
**Impact of the new feature**
Perform migration from github wiki (pages) to CERN gitlab will improve security, searching capabilities and overall organization of DMWM documentation

**Is your feature request related to a problem? Please describe.**
Posting security related info on DMWM documentation, e.g. training, node names, etc.

**Describe the solution you'd like**
Migrate existing github pages to CERN gitlab infrastructure. So far we have the following:
- New site: https://cms-wmcore.docs.cern.ch/ 
- New repo: https://gitlab.cern.ch/dmwm/wmcore-docs 

**Describe alternatives you've considered**
Do nothing and keep using github

**Additional context**
Use platform [used by CMSWeb](https://cms-http-group.docs.cern.ch/)
Cmsweb docs resides in [cmsweb-docs](https://gitlab.cern.ch/cmsweb/cmsweb-docs) or [cmsmont-docs](https://gitlab.cern.ch/cmsmonitoring/cmsmonit-docs) gitlab repositories
There are few pieces which are required:
- request/setup new domain, e.g. cms-dmwm.docs.cern.ch
- Either create new repo or copy-clone it from cmsweb-docs one
- Populate repo with WMCore wiki markdown pages, it can be done by cloning the WMCore.wiki repo:
```
git clone git@github.com:dmwm/WMCore.wiki.git
```
and copying all files into new repository
- Create [mkdocs.yml](https://gitlab.cern.ch/cmsweb/cmsweb-docs/-/blob/master/mkdocs.yml?ref_type=heads) with appropriate settings (the domain and new repo)
- Add [gitlab-ci.yml](https://gitlab.cern.ch/cmsweb/cmsweb-docs/-/blob/master/.gitlab-ci.yml?ref_type=heads) to make a build
- Add docs area and populate it from WMCore.wiki markdown files. At this step we may create a nice nested hierarchical structure, see how it is done with cmsweb and cmsmonit docs.

**Comment by vkuznet** [comment]
The new group has been created: https://gitlab.cern.ch/dmwm

**Comment by vkuznet** [comment]
And, now we have fully working https://cms-dmwm.docs.cern.ch/ documentation page. Here are instructions to add/edit pages in it:
- clone gitlab repo
```
git clone ssh://git@gitlab.cern.ch:7999/dmwm/dmwm-docs.git
```
- `cd dmwm-docs`
- add/edit individual page in docs area (so far it has wmcore sub-directory which I populated with all wmcore wiki pages)
- edit `mkdocs.yml` to add your new markdown with specific title
- commit your code
- check gitlab pipelne page to see if you build is passed
- visit again web page and you document will be there.

**Comment by vkuznet** [comment]
FYI: @amaltaro , @klannon

**Comment by vkuznet** [comment]
And here are some useful links:
- how to create gilba pages guide: https://how-to.docs.cern.ch/
- setting up custom domain: https://how-to.docs.cern.ch/gitlabpagessite/create_site/set_up_pages/
- Web services portal to create GiLab pages: https://webservices-portal.web.cern.ch/gps

**Comment by vkuznet** [comment]
@amaltaro please let me know if anything else needs to be done in this issue (description, or whatever). There is no PR for the issue and therefore we should iterate over here.

**Comment by amaltaro** [comment]
That's great, Valentin.

I might have a couple of suggestions before we call this, such as:
a) add a red-colored message to the top of the [WMCore wiki](https://github.com/dmwm/WMCore/wiki) saying that documentation is being migrated to a different platform. Also giving a link to the new gitlab repository.
b) add to the gitlab [README](https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/README.md?ref_type=heads) the instructions you provided in [this comment](https://github.com/dmwm/WMCore/issues/11871#issuecomment-1904520837)

For future work, and here I do believe that we need a meta-issue for, we could have the following tasks/tickets:
a) explore the CERN MkDocs [documentation](https://how-to.docs.cern.ch/) and see what we can integrate into our WMCore documentation, e.g. automatic revision date.
b) organize the gitlab documentation by service. Also provide specific RESTful section.
c) remove and/or flag legacy documentation
d) review/update the remaining documentation (this one is likely better to be done after we are done with the training sessions though).

**Comment by vkuznet** [comment]
- I added message to WMCore wiki.
- I updated README on gitlab server

Here are new issues:
- better structure, https://github.com/dmwm/WMCore/issues/11873
- clean-up issue: https://github.com/dmwm/WMCore/issues/11874

**Comment by amaltaro** [comment]
Valentin, it looks like I cannot push (or merge merge requests) in wmcore-docs repository. Can you please grant write access to all the WMCore core developers?

I have also created this meta-issue https://github.com/dmwm/WMCore/issues/11875 and linked all of the sub-tasks to it.
Once the authorization access to wmcore-docs has been sorted out, I would say we can close this issue.

**Comment by vkuznet** [comment]
Alan, by default members are assigned Developer role. I went to the following link of the group: https://gitlab.cern.ch/groups/dmwm/-/group_members?sort=last_joined and changed yours and Kevin's role to be the owner, while others I assigned as Maintainer. Feel free to visit group page and adjust further your settings.

**Comment by amaltaro** [comment]
Looks good to me, Valentin. We keep in touch in case further settings need to be adapted. Thanks
