### ISSUE TITLE
CleanupJobs fail due to xrdfs shared library version mismatch. 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11893]
**Impact of the bug**
Cleanup jobs

**Describe the bug**
Following a report from T0 team we checked and confirmed the presence of the following error [1] from cleanup jobs also for the production WMAgents.  The origin of the problem seem to be a shared library mismatch between the `xrdfs` executable  accessible through `cvmfs` and the runtime environment of the job. Possibly due to a job scram arch  mismatch or wrong `LD_LIBRARY_PATH` value at runtime. 
   

**How to reproduce it**
Not clear yet

**Expected behavior**
To not be able to use `xrdfs` from `cvmfs` at any moment.

**Additional context and error message**

Just for logging purposes, I add here a single command to run any of the singularity containers we run at runtime and available through `/cvmfs/`:
```
[user@lxplus988]$ "/cvmfs/oasis.opensciencegrid.org/mis/singularity/current/bin/singularity" -vvv -d  exec --home "/tmp/glide_bBZiCh":/srv --pwd /srv  --ipc --contain  --pid --bind "/cvmfs,/etc/hosts,/etc/localtime"  "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel8-itb" /bin/bash
``` 

[1]

```
2024-02-09 13:25:06,861:INFO:DeleteMgr:Local Stage Out Implementation to be used is:xrdcp
Local Stage Out PNN to be used is T2_CH_CERN
Local Stage Out Catalog to be used is trivialcatalog_file:/cvmfs/cms.cern.ch/SITECONF/T2_CH_CERN/PhEDEx/storage.xml?protocol=eos
Trivial File Catalog has been loaded:
        lfn-to-pfn: protocol=eos path-match-re=/+store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/(.*) result=root://eospps.cern.ch//eos/pps/mw-test/phedex/store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/$1
        lfn-to-pfn: protocol=eos path-match-re=/+store/(.*) result=root://eoscms.cern.ch//eos/cms/store/$1
        lfn-to-pfn: protocol=P5xrootd path-match-re=/+store/(.*) result=root://eoscmshlt.cern.ch//eos/cms/store/$1
        lfn-to-pfn: protocol=xrootd path-match-re=/+store/(.*) result=root://xrootd-cms.infn.it//store/$1
        lfn-to-pfn: protocol=srmv2 path-match-re=/+store/user/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/user/$1
        lfn-to-pfn: protocol=srmv2 path-match-re=/+store/group/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/group/$1
        pfn-to-lfn: protocol=eos path-match-re=root://eoscms.cern.ch//eos/cms/store/(.*) result=/store/$1
        pfn-to-lfn: protocol=P5xrootd path-match-re=root://eoscmshlt.cern.ch//eos/cms/store/(.*) result=/store/$1
        pfn-to-lfn: protocol=srmv2 path-match-re=.*\?SFN=/eos/cms(.*) result=$1

2024-02-09 13:25:06,861:INFO:DeleteMgr:==>Working on file: /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
2024-02-09 13:25:06,861:INFO:DeleteMgr:===> Attempting To Delete.
2024-02-09 13:25:06,862:INFO:DeleteMgr:LFN to PFN match made:
LFN: /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
PFN: root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root

2024-02-09 13:25:06,909:INFO:StageOutImpl:Command exited with status: 1
Output message: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)

2024-02-09 13:25:06,909:ERROR:StageOutImpl:Exception During Stage Out:
Command exited non-zero, ExitCode:1
Output: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)
 
2024-02-09 13:25:07,002:ERROR:DeleteMgr:Failed to delete file: root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
2024-02-09 13:25:07,003:ERROR:DeleteMgr:===> Local file deletion failure. Exception:
<@========== WMException Start ==========@>
Exception Class: StageOutError
Message: Command exited non-zero, ExitCode:1
Output: stdout: 
stderr: xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by xrdfs)
xrdfs: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)
 
        ClassName : None
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        ClassInstance : None
        FileName : /srv/job/WMCore.zip/WMCore/Storage/StageOutError.py
        LineNumber : 32
        ErrorNr : 0
        Command : xrdfs eoscms.cern.ch rm /eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        ExitCode : 1
        ErrorCode : 60311
        ErrorType : GeneralStageOutFailure
        Protocol : xrdcp
        LFN : /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        TargetPFN : root://eoscms.cern.ch//eos/cms/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root

Traceback: 

<@---------- WMException End ----------@>
2024-02-09 13:25:07,005:ERROR:DeleteFiles:General failure in StageOut for DeleteFiles. Error: <@========== WMException Start ==========@>
Exception Class: StageOutFailure
Message: Unable to delete file:
/store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        ClassName : None
        ModuleName : WMCore.Storage.StageOutError
        MethodName : __init__
        ClassInstance : None
        FileName : /srv/job/WMCore.zip/WMCore/Storage/StageOutError.py
        LineNumber : 32
        ErrorNr : 0
        LFN : /store/unmerged/Run3Winter24Reco/GluGlutoHHto4B_kl-2p45_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/AODSIM/133X_mcRun3_2024_realistic_v9-v3/2820000/27ec44a5-1e43-4073-b827-ca54c3d40e9e.root
        PFN : None
        PNN : T2_CH_CERN
        StageOutCommand : None
        ErrorCode : 60311
        ErrorType : GeneralStageOutFailure

Traceback: 

<@---------- WMException End ----------@>
```

**Comment by todor-ivanov** [comment]
Here is the workflow to which one of those failing jobs is related https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_TSG-Run3Winter24wmLHEGS-00056__v1_T_240205_152710_6290

**Comment by smuzaffar** [comment]
@todor-ivanov , first you do not need to have same cmssw os and comp os. So running cmssw/cmsRun under el8_amd64_gccNN and running the pilot under `rhel7_x86_64` is perfectly fine. 
I can re-produce this issue if I run [a] or [b] i.e. starting an el[8,9] container or login to lxplus[8,9] then setting up rhel7 python. This will not work. If your host env is el[8.9] then you should source python from `/cvmfs/cms.cern.ch/COMP/rhel[8,9]_x86_64/`

 
[a] starting el8 container
```
[muzaffar@lxplus702 ~]$ cmssw-el8 # OR cmssw-el9
Singularity> source /cvmfs/cms.cern.ch/COMP/rhel7_x86_64/external/python/2.7.13-comp/etc/profile.d/init.sh 
Singularity> xrdcp --version
xrdcp: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /lib64/libXrdCl.so.3)
```

[b] using lxplus8 or lxplus9 host
```
[muzaffar@lxplus702 ~]$ ssh lxplus9
[muzaffar@lxplus922 ~]$ source /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/etc/profile.d/init.sh 
[muzaffar@lxplus922 ~]$ xrdcp --version
xrdcp: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by xrdcp)
xrdcp: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by xrdcp)
```

**Comment by todor-ivanov** [comment]
Thank you @smuzaffar  for helping us here!

I still have to look up where exactly we set the env. for the cleanup jobs and why it defaults to rhel7 or slc7.  It looks like an overlooked case on this exact combination of pilot and job architecture. @amaltaro do you have  it on top of your head where the quick fix should go?

BTW. @smuzaffar is there a way we could compile `xrdcp` tools and similar with static libraries, before uploading it to `cvmfs`, or we do not control that bit?

**Comment by smuzaffar** [comment]
> BTW. @smuzaffar is there a way we could compile xrdcp tools and similar with static libraries, before uploading it to cvmfs, or we do not control that bit?

CMSSW already has `xrootd` for all the OS/archs but as you run `xrd` commands from outside the cmssw env that is why you picked up system `xrd` tools. I would suggest keep using system `xrd` tool as this way you can get latest version of these tools.

**Comment by todor-ivanov** [comment]
>  but as you run xrd commands from outside the cmssw env that is why you picked up system xrd tools
I think this could  be specific to the cleanup jobs. I am checking the details right now.

**Comment by smuzaffar** [comment]
> I still have to look up where exactly we set the env. for the cleanup jobs and why it defaults to rhel7 or slc7. 

it could be that job was run with [REQUIRED_OS=any](https://github.com/dmwm/WMCore/blob/master/etc/submit_py3.sh#L146) which sets [WMA_DEFAULT_OS=rhel7](https://github.com/dmwm/WMCore/blob/master/etc/submit_py3.sh#L61). I think in case of `REQUIRED_OS=any` you should use the current os ( e.g. if pilot was running in el8 then set `WMA_SCRAM_ARCH=rhel8_${THIS_ARCH}` instead of using `${WMA_DEFAULT_OS}_${THIS_ARCH}`)

**Comment by todor-ivanov** [comment]
hi @smuzaffar 
that's actually a good catch and this is exactly what is happening here - All cleanup jobs from WMCore come with `REQUIRED_OS = any` and the PR that actually turned on the setup to make such jobs refer to `WMA_DEFAULT_OS` is  this one:  https://github.com/dmwm/WMCore/pull/11077


@amaltaro  the way to fix that as I can see them are two. We either require the cleanup job to have the same specific OS requirement, or we try to find out on what pilot the job landed at  runtime.

**Comment by amaltaro** [comment]
Detecting the OS the job landed will definitely be the optimal fix.

**Comment by todor-ivanov** [comment]
And the exact event, which has triggered  the behavior was also found. Few weeks ago, SI have changed  the default OS to `rhel8` for containers with `REQUIRED_OS=any` .  It was actually properly announced here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/CompOpsMeetingSI?rev=19. Thanks @mmascher, for pointing us to the proper place.

**Comment by mmascher** [comment]
I did check WMAgent jobs but I did not find any with `REQUIRED_OS=any`, otherwise I would have sent you and Alan a private message as well. I am sorry about that.

BTW, IMHO building the COMP environment with the whole c++ standard library and the stageout binaries (`xrdcp: /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6`)  made sense a few years ago when there was no singularity. Nowadays we can just make sure the base image @smuzaffar provides has everything WMAgent and CRAB needs for the stageout.

That's what we are already doing for ARM and powerpc architectures: if I am not mistake we are not building COMP binaries for gcc for those architectures. Shazad simply installed the correct rpm in the image and the stageout just worked.

**Comment by todor-ivanov** [comment]
Thanks @mmascher , I'd let @amaltaro  express a more competent opinion than mine on that.

**Comment by amaltaro** [comment]
The current COMP stack is the last survivor of that CMSWEB model. We are no longer building anything in COMP, other than keeping up with the last services that still rely on it, while we put effort on moving them to a different - containerized - stack.

I would suggest to detect the OS at the job wrapper (submit_py3.py) and use the correct (OS + ARCH) libraries in the job.

**Comment by todor-ivanov** [comment]
Now, as of how I plan to resolve the issue at hand: 
Based on another idea that  came from @mmascher  we could use the following two environment variables at runtime so we can estimate on which OS the singularity image on which the job has landed have been based:

```
GWMS_SINGULARITY_IMAGE=/cvmfs/singularity.opensciencegrid.org/.images/df/50a8d9c96be04df958d7ae92bf883af33dbee7fa01251c2f093f20bfc4e4ed
GWMS_SINGULARITY_IMAGE_HUMAN=/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel8-x86_64
```

As we talked and I later confirmed one is a symlink to the other, and I was planning to use the link name so that I can estimate the proper release. @smuzaffar can we rely on this link to be always present and to  follow the same  naming convetion? Otherwise, we will have to follow it the actual singularity container at `cvmfs` and parse the contents of `/etc/redhat-release`, like:

```
cat  /cvmfs/singularity.opensciencegrid.org/.images/df/50a8d9c96be04df958d7ae92bf883af33dbee7fa01251c2f093f20bfc4e4ed/etc/redhat-release 
AlmaLinux release 8.8 (Sapphire Caracal)

```
, which would be error prone I think.
   

FYI @amaltaro

**Comment by smuzaffar** [comment]
@todor-ivanov , use the `GWMS_SINGULARITY_IMAGE_HUMAN` name might not always work. For example for ITB env the image name will have  `cmssw/cms:rhel8-itb-x86_64`.  Why not just run  the following to the the Os version
```
#lxplus7
> rpm --eval '%{rhel}'
7
#lxplus8
> rpm --eval '%{rhel}'
8
#lxplus9
> rpm --eval '%{rhel}'
9
```

**Comment by mmascher** [comment]
Possibly one quick solution to this specific issue is also having log collect jobs requires `REQUIRED_OS=rhel7` instead of `any` (even condor_q_edit ing existing jobs). I mean, in case the long term thing takes some time.

**Comment by klannon** [comment]
@todor-ivanov This also does not look like a high priority issue to me.  This looks like an Operations issue.  If that is correct, can you please set QPrio appropriately?

**Comment by todor-ivanov** [comment]
This was a bug, which was causing accumulation of big amounts of unmerged data. And the solution was not operations to my opinion. It required its own amount of work for producing the olution, even though not been classified as a new feature. The only operational part for this issue, was the process of patching the agents, which was less than 5% of the whole work done.

**Comment by amaltaro** [comment]
I think the "Category: Bug" looks okay, but "Q Prio: High" should probably have been marked as "Q Prio: Operations", as this was not a planned activity and it was actually exposed and affecting the central production. In other words, it was raised by the P&R team (or actually T0) and it needed attention right away, even if most of the effort is on the development area, we have been calling it as an "Operations" issue, through the "Q Prio" field. I have just updated it, but let me know if I missed anything please.
