### ISSUE TITLE
cmsRun logs are represented as byte literal

### ISSUE THREAD

**Issue by makortel** [dmwm/WMCore#11919]
**Impact of the bug**

Log files (at least `cmsRun` logs)

**Describe the bug**

Logs like `cmsRun1-stdout.log` (e.g. https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_RVCMSSW_14_0_0ZpToEE_m6000_14TeV__STD_2026D98_PU_240226_210724_9408/50660/RecoGlobalPU_2026D98PU/00b82ad5-0748-468a-942f-7b237ed79bec-10-1-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log) seem to contain now
```
b"Setting up Frontier log level\nBeginning CMSSW wrapper script\n ...
```

The newlines represented as two characters `\n` instead of a real newline is particularly annoying.

**How to reproduce it**

N/A

**Expected behavior**

Log file formatted as
```
Setting up Frontier log level
Beginning CMSSW wrapper script
...
```

**Additional context and error message**

N/A

**Comment by amaltaro** [comment]
This has been resolved through https://github.com/dmwm/WMCore/pull/11933
Which actually closed another ticket that was duplicating the issue reported in here. Thanks for opening this up though, Matti.

**Comment by makortel** [comment]
Thanks!
