### ISSUE TITLE
cmsRun logs not usable because of lack of decoding

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#11932]
**Impact of the bug**
WMAgent, T0 WMAgent

**Describe the bug**
CMSSW executor is writing standar output and error from `cmsRun` directly from `bytes` stream without decoding. The resultant logs are not practical to use in debugging problems with CMSSW.

**How to reproduce it**
Check the tarball of any CMSSW job for a T0 or production agent

**Expected behavior**
The Executor should decode the output and error streams before writing log files

**Comment by amaltaro** [comment]
@germanfgv can you please either provide an example or cross-check whether this problem is the same reported by Matti in this ticket: https://github.com/dmwm/WMCore/issues/11919

**Comment by germanfgv** [comment]
You are right Alan, this looks like a duplicate of #11919. This is an example of the `cmsRun1-stderr.log` we are getting:
```
b'WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.\nWARNING: There already exists /srv/job/WMTaskSpace/cmsRun1/CMSSW_14_0_1 area for SCRAM_ARCH el8_amd64_gcc12.\n'
```
You can see the `\n` sequence at the end, instead of an actual newline. Other examples can be found here
```
/afs/cern.ch/user/c/cmst0/public/PausedJobs/skims14_0_1/job_10079/job/WMTaskSpace/cmsRun1
```
