### ISSUE TITLE
Improve documentation on WM data acquisition

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11963]
**Impact of the new feature**
Improve existing documentation on WM data acquisition

**Is your feature request related to a problem? Please describe.**
During training session we found few issues with existing documentation.

**Describe the solution you'd like**
Here are the list of improvements:
- Fix letter `M` in request state transition diagram to be `McM`
- Add Close-out sub-section description
- Add full set of requirements for DBS Injection, like 500 files per block, CMSWEB threshold, etc.
- Add link to AgentStatusWatcher
- Add JobCreator before Work acquisition

**Describe alternatives you've considered**
None

**Additional context**

**Comment by amaltaro** [comment]
Valentin, as we briefly discussed over Mattermost, I would rather close this ticket as "Not Planned" and make the relevant updates still as part of the original ticket: https://github.com/dmwm/WMCore/issues/11846

Other than the DBS block closure documentation - which is somehow unrelated to this activity - everything has been covered in this MR https://gitlab.cern.ch/dmwm/wmcore-docs/-/merge_requests/28

I am closing this one, but please let me know if you have different thoughts.
