### ISSUE TITLE
Commission schedd production VO boxes on Alma 9

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11973]
**Impact of the new feature**
WMCore

**Is your feature request related to a problem? Please describe.**
We got to the point where more testbed nodes are needed to keep developments and validation of a containerized WMAgent.
We got 4 nodes in the last week, under the hostgroup `vocmssi/schedd_htcondor/si_test/itb`, but it turns out their setup is not fully functional and we cannot perform some basic actions on those nodes (some in team cannot even log in to those nodes)

**Describe the solution you'd like**
We need to create new nodes that will match the following requirements:
1) under the `CMS Production` openstack project
2) VM flavor `m2.large`, with 4 VCPUs, 8GB of RAM and 40GB of ephemeral disk
3) we will likely have to mount a CEPH volume of ~200GB
4) connected to the `qa` puppet environment (or other than master)
5) Running `Alma9` OS
6) With `Condor schedd` configured (ITB pool should be good enough)
7) With `Docker` installed and properly setup
8) With `cmst1` access (and access to everyone in the wmagent list) - potentially with root access too.

For the record, our current testbed/production nodes are connected to the hostgroup: `vocms/production/schedd`
 
**Describe alternatives you've considered**
Try to fix those provided by the SI group and work on those nodes for the next couple of weeks, until we can properly commission something closer to the production environment.

**Additional context**
More details on this in the "CompOps VMs to Alma9" mattermost channel.

**Comment by bockjoo** [comment]
It' ready for your review vocms265.

**Comment by amaltaro** [comment]
At this moment we have enough production agents on Alma9 for a WMAgent upgrade campaign. However, we still have a bunch of CC7 nodes at CERN that need to be reformatted into Alma9, which I am handling with Bockjoo.

**Comment by amaltaro** [comment]
Quick update: other than the CMS@Home testbed node, all the other testbed/development nodes have been migrated to Alma9.

We also still have around 4 production nodes that need to be migrated, likely to happen in the next week or two.

**Comment by amaltaro** [comment]
The remaining CERN SLC7 nodes have been migrated to Alma9 today and with that, we can declare this issue fully resolved now.
We wouldn't be able to complete this migration in time if it wasn't for the prompt assistance and collaboration from @bockjoo , thank you very much!

For the record, everything has been tracked in https://its.cern.ch/jira/browse/CMSVOC-558

Closing this one out.
