### ISSUE TITLE
Investigate alternatives to increase performance on containerized MariaDB service 

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11977]
**Impact of the new feature**
Look for ways to increase performance of MariaDB inside docker, with respect to host-based deployment.

**Is your feature request related to a problem? Please describe.**
The results from #11566 on the performance of MariaDB inside docker are not very promising for the online transaction processing tests.

See general remarks below:
https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/MariaDB-benchmark-tests.md#conclusions-on-oltp-benchmarks

**Describe the solution you'd like**
We should investigate why the degradation of performance in MariaDB. Results at the host vs container level with respect to File I/O, Memory or CPU were close enough, so there may be a way to increase the performance when running the MariaDB server application specifically.

**Describe alternatives you've considered**
Leave things as is, with the performance degradation noticed.

**Additional context**

**Comment by khurtado** [comment]
There seems to be at least one difference in the old deployment config vs the container one, so I will be looking into the performance differences with this

**Comment by amaltaro** [comment]
@anpicci I haven't looked into the extensive results yet, but from a discussion with Kenyi last Friday, I understand that the performance can be degraded between 25 and 75%. Maybe 25% would be acceptable and fairly unnoticeable, but going to 50% will definitely give us problems with production workload.

It looks like there are known parameters/setup that will increase this performance, and I'd suggest to research and integrate those in before we go to production.

**Comment by amaltaro** [comment]
@khurtado these are great news.

Please take this opportunity to also persist the new MariaDB settings via a pull request for CMSKubernetes. The file that you are likely going to change is https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/wmagent-mariadb/my.cnf

**Comment by anpicci** [comment]
@khurtado I can work on the documentation

**Comment by khurtado** [comment]
@anpicci Thank you!

@amaltaro I have created a PR with the changes

**Comment by anpicci** [comment]
@amaltaro @khurtado I have updated the [GitLab documentation](https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/databases/MariaDB-benchmark.md) with the new set of results

**Comment by amaltaro** [comment]
This issue has been fixed with https://github.com/dmwm/CMSKubernetes/pull/1475
