### ISSUE TITLE
WMAgent: Missing Reqmgr.tools package causing exception when loading Stdbase

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11981]
**Impact of the bug**
WMAgent

**Describe the bug**
While working on the T0 deployment issue https://github.com/dmwm/WMCore/issues/11890, we found out that loading  StdBase module leads to an exception caused by a missing include. Here is the line causing it: 
https://github.com/dmwm/WMCore/blob/e4628ce9ab25f5015b71197a42eb09d630286318/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L23

And here is the result of this import inside the agent environment:
```
In [2]: from WMCore.ReqMgr.Tools  import releases, architectures
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from WMCore.ReqMgr.Tools  import releases, architectures

ModuleNotFoundError: No module named 'WMCore.ReqMgr.Tools'
``` 

The module `WMCore.Reqmgr.Tools` is indeed missing as a dependency for the `wmagent` package, which we build and upload to Pypi:  https://github.com/dmwm/WMCore/blob/e4628ce9ab25f5015b71197a42eb09d630286318/setup_dependencies.py#L182-L189

But is actually present for `tier0-agent`: https://github.com/dmwm/WMCore/blob/e4628ce9ab25f5015b71197a42eb09d630286318/setup_dependencies.py#L271 
which package, I am not sure if we actually upload to pypi. 

What we should do is to either include the `WMCore.Reqmgr.Tools` module as a dependency in the default `wmagent` package (which is currently the default pypi packag deployed even for the T0 deployment model) or to switch somehow to deploying the `tier0-agent` package.   

**How to reproduce it**

Start a pypi deployed agent and try to load the `WMCore.Reqmgr.Tools` module inside it. 

You may deploy the agent any method you'd like being it docker or virtual environment, the error if you try to load the  the module would be the same. In case you'd like to have it deployed in the virtual env as for T0, here is the script to use: https://github.com/dmwm/WMCore/blob/master/deploy/deploy-wmagent-venv.sh
and an example deployment command would be:
```
./deploy-wmagent-venv.sh -t 2.3.3 -y 
``` 
**Expected behavior**
To be able to load the StdBase module standalone

**Additional context and error message**
The issue: https://github.com/dmwm/WMCore/issues/11890  depends on the resolution of the current one, which makes it a chained dependency for the WMAgent new deployment model meta-issue: https://github.com/dmwm/WMCore/issues/11314

**Comment by todor-ivanov** [comment]
Just for completeness, here is the full exception from the Tier0Feeder logs:
```
2024-05-13 15:31:32,103:140259373348416:ERROR:StdBase:About to raise exception <@========== WMException Start ==========@>
Exception Class: WMSpecFactoryException
Message: [Errno 2] No such file or directory: '/tmp/.wmcore_cache_vxk10uvl/cmssdt.cern.ch/-5258551530043697436_GET__SDT_cgi-bin_ReleasesXML_'
        ClassName : None
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : _validateArgFunction
        ClassInstance : None
        FileName : /data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/WMSpec/WMWorkloadTools.py
        LineNumber : 139
        ErrorNr : 0

Traceback: 
  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/WMSpec/WMWorkloadTools.py", line 130, in _validateArgFunction
    if not valFunction(value):

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/WMSpec/StdSpecs/StdBase.py", line 1034, in <lambda>
    "CMSSWVersion": {"validate": lambda x: x in releases(),

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/ReqMgr/Tools/cms.py", line 219, in releases
    return TC.releases(arch)

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/TagCollector/TagCollector.py", line 89, in releases
    for row in self.data():

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/TagCollector/TagCollector.py", line 81, in data
    data = self._getResult()

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/TagCollector/TagCollector.py", line 66, in _getResult
    f = self.refreshCache(cFile, callname, args, encoder=encoder, decoder=decodeBytesToUnicode,

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/Service.py", line 218, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType, binary=binary)

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/Service.py", line 362, in getData
    raise he

  File "/data/tier0/WMAgent.venv3-2.3.3-src/srv/WMCore/src/python/WMCore/Services/Service.py", line 341, in getData
    with open(cachefile, 'w', encoding='utf-8') as f:

<@---------- WMException End ----------@>

```

**Comment by todor-ivanov** [comment]
Just for the record: I cannot see us uploading `t0-agent` package at all. The list of packages we upload throughout our builds is:  https://pypi.org/user/cms-oc-dmwm/ :
* reqmgr2ms-rulecleaner
* wmagent-devtools
* reqmgr2ms-pileup
* reqmgr2ms-transferor
* wmcore
* reqmon
* wmagent
* reqmgr2
* reqmgr2ms-monitor
* reqmgr2ms-output
* reqmgr2ms-unmerged
* global-workqueue
* acdcserver
* dbs3-client
* dbs3-pycurl
* reqmgr2ms
* CMSCouchapp
* pycurl-client

**Comment by amaltaro** [comment]
@todor-ivanov this list above only contains the projects under the `dmwm` organization in PyPi.
The services we actually have defined in our CD pipeline is listed in these 2 lines:
https://github.com/dmwm/WMCore/blob/master/.github/workflows/pypi_build_and_images.yaml#L29-L30

**Comment by todor-ivanov** [comment]
hi @amaltaro thanks for pointing this list (exactly the configuration place I was looking for)  , so this confirms exactly what I meant: in order for us to get a `t0-agent` uploaded to Pypi, we need to add this package in this very list. The alternative would be to add `WMCore.ReqMgr+` as a dependence to the `wmagent` package. 

Let me know  which solution you'd prefer.

**Comment by todor-ivanov** [comment]
Hi @amaltaro  as we quickly discussed in a private chat the path chosen here should be adding the extra dependencies to the `wmagent` package instead of uploading a new one to Pypi and changing deployment scripts. 

In the PR for fixing the issue I did so, but I did not wipe out the whole `t0-agent` section from the `setup_dependency.py` script, because this system deployment is still needed for the rpm based deployment: https://github.com/cms-sw/cmsdist/blob/a5a0b8640d227a432388285b8c0a11dfd5c0706d/t0.spec#L37 

So we  will have to deprecate the whole `t0-agent` package only once we  completely finish the Alma9 migration.
