### ISSUE TITLE
HTCondor 10.2.3 Unavailable

### ISSUE THREAD

**Issue by d-ylee** [dmwm/WMCore#12001]
**Impact of the bug**
WMAgent, WMCore

**Describe the bug**
HTCondor 10.2.3 is now unavailable on PyPI

**How to reproduce it**
`pip3 install -r requirements.txt`

**Expected behavior**
`pip` Installs HTCondor.

**Additional context and error message**
```
ERROR: Could not find a version that satisfies the requirement htcondor~=10.2.3 (from versions: 9.0.17, 10.0.3, 10.0.4, 10.0.6, 10.0.7, 10.0.8, 10.0.9, 10.3.0, 10.5.0, 10.6.0, 10.7.0, 10.8.0, 10.9.0, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 23.0.4, 23.0.6, 23.0.8, 23.0.10, 23.1.0, 23.2.0, 23.3.0, 23.4.0, 23.5.2, 23.6.1, 23.7.2, 23.9.0a2)
ERROR: No matching distribution found for htcondor~=10.2.3
```

**Comment by amaltaro** [comment]
For the record, release notes for HTCondor can be found at https://htcondor.org/htcondor/release-highlights/
I didn't see anything that could be concerning, so I guess we are fine.
