### ISSUE TITLE
WFs return no error but missing an entire MINIAOD output 

### ISSUE THREAD

**Issue by z4027163** [dmwm/WMCore#12029]
**Impact of the bug**
We have several WFs return no error, but missing an entire MINIAOD output, while they 100% complete rate for AOD and NANOAOD.

**Describe the bug**
The middle data tier output is entirely missing, this is the first time we see such behavior.

**How to reproduce it**
This might be random case

**Expected behavior**
If no error is reported, all the output should be 100%. 

**Additional context and error message**
We want to know the reason for such behavior, if it is temporary due to the FNAL Alm9 agent issue, or this is because of the other reasons.

Here are a few examples:
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIISummer20UL16wmLHEGENAPV-03431
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIISummer20UL16wmLHEGENAPV-05566
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIISummer20UL16wmLHEGEN-05870

**Comment by amaltaro** [comment]
@z4027163 Hi Qier, did you check for data/dataset invalidation?

I had a quick look at the first workflow and I can see the MINIAODSIM dataset in DBS (when I ask for any status):
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets?dataset=/WplusH_HToSSTobbbb_WToLNu_MH-125_MS-15_ctauS-300_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v3/MINIAODSIM&dataset_access_type=*

and I can also see DBS stats for it:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries?dataset=/WplusH_HToSSTobbbb_WToLNu_MH-125_MS-15_ctauS-300_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v3/MINIAODSIM

Can you please go through this list to understand if there was actual a DM action that could have affected the output of such workflows?

**Comment by drkovalskyi** [comment]
I see nothing wrong with the first example. It misses NANOAODSIM, but it was not part of the request. Second and third have empty NANOAODSIM output.

**Comment by amaltaro** [comment]
MINIAODSIM datasets are in DBS for all 3 workflows reported above:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries?dataset=/TprimeBToTH_LH_M1200_decay30pct_tch_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v3/MINIAODSIM

and
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries?dataset=/PairVLQ_x53x53_tHtH_narrow_RH_MX1600_MH1000_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM

@z4027163 please let me know if things are alright on your side as well. If so, I will then close this out as "Closed as not planned" (or feel free to do so).

**Comment by z4027163** [comment]
Sorry for the noise, the ones I was talking about were fixed automatically and I accidentally sent the wrong WFs.

**Comment by amaltaro** [comment]
No worries, thanks Qier!
