### ISSUE TITLE
etc/rucio.cfg gets misconfigured upon WMAgent tag update

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#12034]
**Impact of the bug**
WMAgent

**Describe the bug**
I had already observed this issue in the past week or so, but today I could confirm that upgrading an agent from `2.3.4rc12` to `2.3.4` causes the `/etc/rucio.cfg` configuration file to be reverted to the factory configuration, hence with placeholders like:
```
rucio_host = RUCIO_HOST_OVERWRITE
auth_host = RUCIO_AUTH_OVERWRITE
```

At this moment, this operation is performed by the following script:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/wmagent/init.sh#L197

**How to reproduce it**
See above

**Expected behavior**
Ideally, we should not recreate `etc/rucio.cfg` upon agent upgrade within the same release cycle.
If we do, then it should overwrite the placeholder variables such that the file configuration is correct.

**Additional context and error message**
None

**Comment by todor-ivanov** [comment]
> Ideally, we should not recreate etc/rucio.cfg upon agent upgrade within the same release cycle.

Here  is where  this happens: https://github.com/dmwm/CMSKubernetes/blob/3b7b12bc7c2fe811d85990048353d894f30cfb8c/docker/pypi/wmagent/init.sh#L121

**Comment by amaltaro** [comment]
Thank you for the pointer, Todor.
I think copying etc/* together with the runtime is the right thing to do, as we might have modifications to the submit_py3.sh script as well. With that said, we need to ensure that whenever we copy the runtime package, we also reinitialize etc/rucio.cfg.

**Comment by todor-ivanov** [comment]
Good to know your opinion. I was wandering about which approach would be the better one here. Either
*  Isolating the rucio config during the copy of etc/* 
or
* Triggering a fresh initialization of the step on minor tag change

I'll make the relevant change in few minutes.
