### ISSUE TITLE
Clarify the job logging procedure

### ISSUE THREAD

**Issue by lucalavezzo** [dmwm/WMCore#12036]
Hi all,

I have a quick question about job logs. For each workflow, I see that there are logs stored in 

1. `/eos/cms//store/unmerged/logs/prod/<year>/<month>/<day>/<workflow>`
2.  `/eos/cms/store/logs/prod/recent/PRODUCTION/<workflow>`

The former are not reliably accessible or not present at all, or I'm looking under the wrong date? I am using the LFNs pulled from WMStats to find them for each workflow, but I very frequently am not able to access them for any workflow via eos or xrootd.

The latter appear to be a lot more reliable, but I think are only saved for recent workflows.

Since Unified has several important dependencies on these logs, we would like some clarification on what the WMCore procedure for storing workflow logs in either of these directories is, why some workflows appear in only one of the two, and what the differences between the logs in the two are. I have read https://cms-wmcore.docs.cern.ch/training/services_and_logs/#job-logs-at-eos but it does not seem to address my concerns.

Thanks in advance for your help,
Luca

**Comment by todor-ivanov** [comment]
hi @lucalavezzo 

Please, consider anything in `/store/unmerged` as a temporary content and never rely on it. And  do not hook any piece of  code to make conclusions based on the presence or absence of data in this area.

That said, I think the answer to your question is `2)`.

**Comment by todor-ivanov** [comment]
And if I need to be more precise, 

If you do not find whatever you search in the recent folder: 
* `/eos/cms/store/logs/prod/recent`

Please take a look at:
* `/eos/cms/store/logs/prod/<year>/<month>` 

As it is also mentioned in the documentation you refer. 

I think we may close that issue if @amaltaro has nothing more to add

@lucalavezzo if you still cannot find  what you search, please contact us in the `WMOps` at Mattermost. We  will try to look deeper, especially if it is related to some particular workflow.

**Comment by lucalavezzo** [comment]
Thanks a lot @todor-ivanov , this is good to clarify. We will use `/eos/cms/store/logs/prod/recent` and/or `/eos/cms/store/logs/prod/<year>/<month>`. Just one quick question though: is there any clear difference between these two? Is `recent` just a subset of `prod/year/month`?

Feel free to close the ticket though, I think I have enough on my side to proceed.
Thanks a lot.
