### ISSUE TITLE
Update workqueue elements upon workflow site list change

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#12038]
**Impact of the new feature**
Global WorkQueue (and ReqMgr2)

**Is your feature request related to a problem? Please describe.**
This is a sub-task of this meta-issue: https://github.com/dmwm/WMCore/issues/8323
Towards providing a feature that allows workflow site lists to be changed while workflows are active in the system.

**Describe the solution you'd like**
Whenever an user updates either the `SiteWhitelist` or the `SiteBlacklist` attributes of a workflow, ReqMg2 needs to:
* load the workflow GQE
* filter elements that are in status `Available`
* update the site lists for each element

Please double check whether the list of sites in WQE is actually a list of sites, and not locations (RSEs). If the latter, then we also need to remap sites to RSEs.

If a failure happens during this process, nothing should be persisted in the workflow spec and a clear error message needs to be returned to the end user.

**Describe alternatives you've considered**
None

**Additional context**
Depends on https://github.com/dmwm/WMCore/issues/12037

For GQE statuses, please refer to: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataStructs/WorkQueueElement.py

**Comment by todor-ivanov** [comment]
Reopening This issue, just to be fixed with the next PR, due to an overlooked breaking unit test from https://github.com/dmwm/WMCore/pull/12099 :

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/WMCore-PR-Report/228/artifact/artifacts/PullRequestReport.html
> WMCore_t.WMSpec_t.WMWorkload_t.WMWorkloadTest:testUpdateWorkloadArgs was added with status failure. Must be fixed

**Comment by todor-ivanov** [comment]
Here is the new status of the unit test:

https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/WMCore-PR-Report/231/artifact/artifacts/PullRequestReport.html#unittestspy3 

>  WMCore_t.WMSpec_t.WMWorkload_t.WMWorkloadTest:testUpdateWorkloadArgs changed from failure to success
