### ISSUE TITLE
WorkQueueManager acquiring the same WQE in multiple agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#12041]
**Impact of the bug**
WMAgents

**Describe the bug**
As reported in this comment: https://github.com/dmwm/WMCore/issues/11956#issuecomment-2224384239

we found out that some workflows are having duplicate run/lumis because the very same global workqueue element is actually acquired by multiple agents.

There are multiple workflows having this issue, but the one investigated in the issue 11956 is:
`cmsunified_task_EXO-RunIISummer20UL18wmLHEGEN-05236__v1_T_240606_163348_8728`

which had a single WQE, being acquired both by submit7 and vocms0252.
 
**How to reproduce it**
One could try running a workflow in a team name with multiple agents connected to, but I don't think it is easy to reproduce this problem.

**Expected behavior**
A global workqueue element must be pulled down by a single agent. There is a "Negotiating" protocol/status, which is supposed to ensure that each GQE is only acquired by a single agent.
We need to identify the actual flaw and make sure it NEVER happens again.

**Additional context and error message**
Further details in this comment (but not that relevant): https://github.com/dmwm/WMCore/issues/11956#issuecomment-2224367587

and this as well: https://github.com/dmwm/WMCore/issues/11956#issuecomment-2224384239

**Comment by anpicci** [comment]
@amaltaro @hassan11196 do you think we can have two backfill/testbed agents assigned to the same team, and try to assign a workflow to that team?

I'm afraid we would need to assign multiple workflows to such a team since it seems there is a component of randomness in this bug.

In addition, I was wondering if we could add some instrumentation to track the assignment of the WQE within WorkQueueManager.

**Comment by amaltaro** [comment]
I'd rather not, it's better to run such debugging workflows not in the production environment (cmsweb production, dbs prod, rucio prod, etc). We better seek the testbed environment for such tests.

> In addition, I was wondering if we could add some instrumentation to track the assignment of the WQE within WorkQueueManager.

I am not sure I understand this question. Can you please clarify?


Back to the debugging of that workflow. One thing does not make sense though! If the same GQE was pulled by 2 agents and the workflow had a single GQE, then I would expect to have almost twice stats in the output, instead what I have is:
```
Summary for: /WRtoNTautoTauTauJJ_WR3000_N400_TuneCP5_13TeV_madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
| metric    |   dataset level |   block level |   file level |
|-----------|-----------------|---------------|--------------|
| num_block |              27 |            27 |           27 |
| num_file  |              28 |            28 |           28 |
| num_event |          151917 |        151917 |       151917 |
| num_lumi  |             151 |           151 |          151 |

Summary for: /WRtoNTautoTauTauJJ_WR3000_N400_TuneCP5_13TeV_madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/NANOAODSIM
| metric    |   dataset level |   block level |   file level |
|-----------|-----------------|---------------|--------------|
| num_block |              27 |            27 |           27 |
| num_file  |              27 |            27 |           27 |
| num_event |          151917 |        151917 |            0 |
| num_lumi  |             151 |           151 |          151 |

Summary for: /WRtoNTautoTauTauJJ_WR3000_N400_TuneCP5_13TeV_madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM
| metric    |   dataset level |   block level |   file level |
|-----------|-----------------|---------------|--------------|
| num_block |              31 |            31 |           31 |
| num_file  |              42 |            42 |           42 |
| num_event |          181275 |        181275 |       181275 |
| num_lumi  |             151 |           180 |          180 |
```

which is basically matching:
```
  "TotalInputLumis": 151,
```
other than the AODSIM dataset.


On the other hand, there is another factor contributing to the double agent assignment. The workflow expected to create:
```
  "TotalEstimatedJobs": 151,
```
and WMStats reports almost double that number of jobs:
```
EXO-RunIISummer20UL18wmLHEGEN-05236_0	293
```

**Comment by anpicci** [comment]
> 

  >  In addition, I was wondering if we could add some instrumentation to track the assignment of the WQE within WorkQueueManager.

> I am not sure I understand this question. Can you please clarify?
I was wondering if we want to add some additional printouts to reverse-engineer the assignment of the WQE.

Regarding your additional investigations, is there any mechanism in place to block delivering files with duplicated lumis? Given that the same WQE is assigned to two different agents with a lag of 5 minutes, could it be that agents A and B processes the same lumi sections, and B can detect duplicated lumis only for the files already released from A (and vice-versa)?
I mean, if A and B produce events for the same lumi section almost simultaneously, and mostly at the same time they check one another if a lumi has being already processed by the other, either A or B might not catch the information that the same lumi was already processed by the other one.

In addition, MiniAOD and NanoAOD should be produced starting from AOD, right? Why the duplicated lumis are not propagated downstream from AOD to MiniAOD and NanoAOD?

**Comment by amaltaro** [comment]
Agents A and B work independently, so they would not know anything that is going on in the other agent.
Once an agent locks into a GQE, it updates the element `Status` and `ChildQueue` attribute. If another agent is trying to lock into the same document, CouchDB should return a document conflict and the second agent **should** skip that element acquisition (classic "should" though...). 

> In addition, MiniAOD and NanoAOD should be produced starting from AOD, right? Why the duplicated lumis are not propagated downstream from AOD to MiniAOD and NanoAOD?

Yes, stats should be ~double all all across the output datasets.

WMStats also reports jobs in `cooloff` for vocms0252, which means those jobs are not in a final state. Nonetheless, I double-checked the drain log and everything looked good back in June 27 (one more strange thing!):
```
*** WORKQUEUE: elements still marked as Available in LQ workqueue / workqueue_inbox.
Elements matching the criteria (Available, workqueue) are: 0
Elements matching the criteria (Available, workqueue_inbox) are: 0

*** WORKQUEUE: elements still marked as Negotiating in LQ workqueue / workqueue_inbox.
Elements matching the criteria (Negotiating, workqueue) are: 0
Elements matching the criteria (Negotiating, workqueue_inbox) are: 0

*** WORKQUEUE: elements still marked as Acquired in LQ workqueue / workqueue_inbox.
Elements matching the criteria (Acquired, workqueue) are: 0
Elements matching the criteria (Acquired, workqueue_inbox) are: 0

*** WORKQUEUE: elements still marked as Running in LQ workqueue / workqueue_inbox.
Elements matching the criteria (Running, workqueue) are: 0
Elements matching the criteria (Running, workqueue_inbox) are: 0

*** WORKQUEUE: elements still marked as Acquired in GQ workqueue.
Elements matching the criteria (Acquired, http://vocms0252.cern.ch:5984) are: 0

*** WORKQUEUE: elements still marked as Running in GQ workqueue.
Elements matching the criteria (Running, http://vocms0252.cern.ch:5984) are: 0

*** WORKFLOWS: there are 0 distinct workflows not completed.

*** WORKFLOWS: found 0 workflows not fully injected.

*** WMBS: amount of wmbs jobs in each status:
[{'name': 'cleanout', 'count': 1871031}]

*** SUBSCRIPTIONS: subscriptions not finished: 0

*** SUBSCRIPTIONS: found 0 files available in WMBS (waiting for job creation):
[]

*** SUBSCRIPTIONS: found 0 files acquired in WMBS (waiting for jobs to finish):
[]
```

**Comment by amaltaro** [comment]
I believe I have an answer to the questions above. As one can see grepp'ing the WorkQueueManager logs, submit7 completed that workflow more or less at the same time that jobs were getting created in vocms0252. That caused the WQEs to be deleted both in the submit7 and in global workqueue. Based on the deletion of those documents, vocms0252 decided to kill the workflow, hence running just a subset of the jobs and not moving into the MINI and NANO datatiers.

I have copied 3 days of logs from WorkQueueManager in each of those nodes (June 6-8) and placed them here:
https://amaltaro.web.cern.ch/forWMCore/Issue_12041/

Now I am more confident that this problem has been correctly identified. It would be of great help to reproduce it though, and I think the only way would be to have a WQE in `Available` status while 2 different agents iterate over them.

**Comment by anpicci** [comment]
Thank you @amaltaro for these investigations. So, IMU, there is no chance two agents can acquire the same WQE, unless the CouchDB document for the corresponding GQE is properly updated, right?
