### ISSUE TITLE
Fix typos in logging messages, possible leftover bug from #11765, and remove two unused functions in WMCore/Database

### ISSUE THREAD

**Issue by oljemark** [dmwm/WMCore#12051]
**Impact of the new feature**
While looking for typos in most of the python code (that's specifically printed out), I found a seemingly unfixed part of the PR #11765 , see https://github.com/dmwm/WMCore/pull/11765#discussion_r1369296362 which still seems to be there: https://github.com/dmwm/WMCore/compare/master...oljemark:WMCore:custom-typo
Should this be fixed, or was this a DB field that was created with a certain typo and now has to be kept as is?

I also found that WMCore/Database/CmsCouch.py had two seemingly totally unused functions, getPrevisousRevision() & non_rotating_commit(), that were suspected as such already in #6928 .

The log text typos I found are here: https://github.com/dmwm/WMCore/compare/master...oljemark:WMCore:typo and error message & handler watchword typos here https://github.com/dmwm/WMCore/compare/master...oljemark:WMCore:twiki-codes
In the latter case, can I assume WMCore/Agent/Flow/DefaultFlow.py is not used anywhere, but just an example to be filled in by the user?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
If you think any of these corrections could be acceptable, I could open up to three PR's based on the branches above, and https://github.com/dmwm/WMCore/compare/master...oljemark:WMCore:remove2old , one each.

**Describe alternatives you've considered**

**Additional context**

**Comment by amaltaro** [comment]
Hi @oljemark , the first typo is very much undesired and I would appreciate it if you could make a PR out of your development branch.
The other 2 changes would be nice to have as well (I think that revision function for CouchDB does not even work in CouchDB 3.x series). So feel free to open the relevant PRs at your convenience and link them to close this one ticket, please.
I will be sorting out Jenkins today, as now we will definitely need to see the outcome of the CI pipeline. You might be getting another GitHub email at some. Thanks

**Comment by amaltaro** [comment]
@oljemark you should have received an email to join "dmwm" GitHub organization. Can you please confirm once you have accepted that, such that I can re-trigger the CI pipeline?

**Comment by oljemark** [comment]
Hello @amaltaro . I didn't see any email now, but I had got an invitation Thursday which I thought I had accepted. Clicking it now only went to dmwm/WMCore webpage, but now when I went to github.com/dmwm I saw an invitation that I accepted.

**Comment by amaltaro** [comment]
Great, I think we are all set and I see Jenkins results for one of the PRs. We can follow up on those PRs now, if needed.
I guess you will not be able to see details inside the jenkins jobs, but I can help you out as needed.

Even though we have moved our documentation over to CERN Gitlab, this Jenkins documentation should be mostly up-to-date: https://github.com/dmwm/WMCore/wiki/Understanding-Jenkins, in case you want to learn more about what we test in each pull request. Thanks Fredrik!
