### ISSUE TITLE
Improve DBSClient installation inside WMCore docker images

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#12100]
**Impact of the new feature**

All the wmcore services that rely on dbsclient

**Is your feature request related to a problem? Please describe.**

This issue is a followup of https://github.com/dmwm/WMCore/issues/12097 .

The image build by Alan `registry.cern.ch/cmsweb/reqmgr2ms-output:2.3.6rc5`  and deployed to cmsweb-testbed contains the correct wmcore version (`2.3.6rc5`) [1] but the dbsclient version is not what we desire ( [4.0.19](https://github.com/dmwm/WMCore/blob/7ddd036d68d43f3018a6215ff63381fe098fd1fe/requirements.txt#L21) ) [2]

**Describe the solution you'd like**

We should be able to get into wmcore images the exact dbs-client version that we ask for. We should use the `==` operator in our requirements.txt instead of `~=`. 

We can always switch back to `~=`  if we see that pip can not deal with the fixed "patch" versions for dbs-client and needs some wiggle room

Moreover, we should install dbs-client without specifying the desired version, such as in [ms-unmerged](https://github.com/dmwm/CMSKubernetes/blob/edfcee87b9364062c365cf068a33fb70d72592e2/docker/pypi/reqmgr2ms-unmerged/Dockerfile#L17)

**Describe alternatives you've considered**

We could change the minor version of the dbsclient and continue to use `~=`, but since this is a bugfix and did not add any new feature, it would against the semantic versioning [rationale](https://semver.org/)

---

[1]

```plaintext
_reqmgr2ms@ms-output-6b776bb56c-nwfkk:/data$ cat /usr/local/lib/python3.8/site-packages/WMCore/__init__.py
[...]
__version__ = '2.3.6rc5'
```

[2] 

```plaintext
_reqmgr2ms@ms-output-6b776bb56c-nwfkk:/data$ ls /usr/local/lib/python3.8/site-packages/dbs*
[...]
/usr/local/lib/python3.8/site-packages/dbs3_client-4.0.12.dist-info:
```

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/12102
