### ISSUE TITLE
Jobs for ACDC wfs not being submitted to sites with RSEs ending with _Disk

### ISSUE THREAD

**Issue by hassan11196** [dmwm/WMCore#12101]
**Impact of the bug**
WMAgent, WorkQueue

**Describe the bug**
Jobs for ACDC workflow that reads Pileup locally i.e. TrustPUSitelists: false will not be submitted to the site if its phedex_name / Storage name ends with _Disk

Related to https://github.com/dmwm/WMCore/issues/12012
This issue is similar to the above-discussed issue which was recently fixed, [Pull Request](https://github.com/dmwm/WMCore/pull/12094)

Now this issue is limited to ACDC workflows. 

For Example:
This ACDC workflow was created after the fix was deployed to agents,
https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_ACDC0_task_TSG-Phase2Spring24wmLHEGS-00001__v1_T_240917_112116_3408

However its WorkQueue Pileup locations still includes the storage name for the site
![image](https://github.com/user-attachments/assets/02601708-4a59-454e-8793-2d109aa8d2c9)

**How to reproduce it**
1. Create an ACDC workflow with `TrustPUSitelists:false` only to a site whose storage element ends with `_Disk`
2. The Workflow will remain stuck in Acquired state and agents will not create jobs for it.

**Expected behavior**
Jobs to be properly submitted to all sites in the site whitelist even if the SE and CE names are different i.e "T1_US_FNAL_Disk",
"T1_US_FNAL". 
WorkQueue Pileup Locations to have computing site names instead of storage name for ACDC workflows.

**Additional context and error message**
These 2 non-ACDC workflows were created after the fix was deployed but also have incorrect WorkQueue Pileup Locations.

1. https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_TSG-Phase2Spring24wmLHEGS-00006__v1_T_240915_225306_5625
    - https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/aacf81c7e1652b3805cdb01bc38dfbcc 
    - ![image](https://github.com/user-attachments/assets/6d9ef734-783e-42eb-b5ab-dd31643977d8)
  

2. https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_TSG-Phase2Spring24wmLHEGS-00012__v1_T_240914_161424_8704
    - https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=cmsunified_task_TSG-Phase2Spring24wmLHEGS-00012__v1_T_240914_161424_8704
        - ![image](https://github.com/user-attachments/assets/56bad2a4-8342-43ed-ad8c-2f5290dcf6f8)

FYI @amaltaro @anpicci

**Comment by amaltaro** [comment]
Having another look into this, I just noticed that the bug-fix that Kenyi made 10 days ago:
https://github.com/dmwm/WMCore/pull/12094

was not deployed yet in production. This is the reason why we still don't site names defined for `PileupData` in the workqueue elements.

About ErrorHandler, here is how we deal with the file locations:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L206

and I don't think there is anything to be changed on this component, as it is indeed expected to be a list of locations/RSEs.

Sorry for the miscommunication on this, we applied the relevant fix to the agents, but not to central services.

I am moving it over to Waiting right now and we might end up closing this as "not planned" (not actually an issue).

**Comment by amaltaro** [comment]
@hassan11196 we have pushed in a hot-fix today for Global WorkQueue, version `2.3.5.1`.
I scanned all of the Resubmission workflows in `acquired` status in production, but none of them are using pileup data that is available at FNAL, so I could not cross-check this fix.

If you create more ACDC workflows and/or know any ACDC that is requiring pileup available at FNAL, can you please check that and/or let us know. Thanks

**Comment by hassan11196** [comment]
Hello @amaltaro 
Thank you for the hotfix. I can confirm that its working for ACDCs, 
I had created this ACDC request and its WorkQueue Pileup locations are as expected. 

<img width="765" alt="image" src="https://github.com/user-attachments/assets/e7634406-f884-4885-a1fb-37ab13e32bc0">

Thank you.

**Comment by amaltaro** [comment]
Awesome! Thank you for promptly looking and validating this.
With that, I am closing this issue as "Not Planned", as it has actually being fixed by another Issue/PR. Thanks again!
