### ISSUE TITLE
Create Alma9 WMCore-dev image to run unit tests, with CouchDB/MariaDB dependencies

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#12113]
**Impact of the new feature**
Create a development Alma9 image of WMAgent/WMCore that includes unittests and necessary dependencies to run unittests

**Is your feature request related to a problem? Please describe.**
While working on https://github.com/dmwm/WMCore/issues/11568 , if we want to run unittests in containers, we cannot use the production WMAgent image, since it does not contain unittests.

**Describe the solution you'd like**
Creating a new development image dedicated for WMCore/WMAgent unittests that includes necessary dependencies to run unittests.
Revisit current setup in cmsdocks and other locations and see if we can deprecate/remove older images.
Update documentation

**Describe alternatives you've considered**
Similar to the current image for unittests, running all 3 services together: CouchDB + MariaDB + WMAgent

**Additional context**
Spec from cmsdist for creating a unittest docker image:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmcorepy3-devtools.spec

services that we build and upload to PyPi:
https://github.com/dmwm/WMCore/blob/master/.github/workflows/pypi_build_and_images.yaml#L29C17-L30C117

and list of services that we build a docker image
https://github.com/dmwm/WMCore/blob/master/.github/workflows/pypi_build_and_images.yaml#L44

Repository that we build WMCore unit test image (and other images):
https://gitlab.cern.ch/CMSDOCKS/dmwm/-/tree/master?ref_type=heads

**Comment by khurtado** [comment]
We have created an image that is working in Jenkins. Therefore, I will be closing this issue.

**Comment by amaltaro** [comment]
@khurtado before closing this issue, I think we need to at least:
* have a commit/PR with the proposal for the new wmcore-dev image (where are we storing its Dockerfile? Are we pushing the image to CERN registry? How do we call it?
* and, we should definitely document it. Perhaps we can use the existing Jenkins related documentation and create a new section for Alma9?

Keep in mind that at some point, this setup for Jenkins will be recommended for private use as well (just like we do with CC7 docker image for running unit tests in a developers environment/machine).

**Comment by d-ylee** [comment]
We probably also want to try using the image for a few days/weeks. I can start with the documentation of how I could use it.

**Comment by d-ylee** [comment]
For reference, here is the main wmcore-dev image location:
https://github.com/dmwm/CMSKubernetes/pull/1549

It is still in a PR.

The image is in the CERN registry, pushed using this script:
https://github.com/dmwm/CMSKubernetes/blob/4815fabb47eb7e9b79835b581aa582c928dc48c0/docker/pypi/wmcore-dev/push.sh

**Comment by khurtado** [comment]
Closing this issue, after merging:
https://github.com/dmwm/CMSKubernetes/pull/1549
