### ISSUE TITLE
Configure T0 WMAgent to use ResourceControlUpdater

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#12121]
**Impact of the new feature**
T0 needs to enable `ResourceControlUpdater`. AFAIK this component updates RC tables according to sites CRIC status, preventing T0 from submitting jobs to draining sites. We want to understand the features of the component so we can use it properly and request new features if needed.

**Is your feature request related to a problem? Please describe.**
T0 WMAgents do not use the `ResourceControlUpdater` thread of AgentStatusWatcher. Tier-0 deployment procedure adds each site to `ResourceControl` individually [here](https://github.com/dmwm/T0/blob/7cc17bfbacb239fd9aa48772866061f219c34963/bin/00_pypi_resource_control.sh). Adding other sites `T1` requires manual intervention from operators. Now that T0 regularly uses several T1 sites, it is necessary that T0 agents can react to changes in the sites status. 

**Describe the solution you'd like**
Enable `ResourceControlUpdater` so it reacts to CRIC status for T1 sites, but still allow us to closely control available slots at T1_CH_CERN

**Describe alternatives you've considered**
Develop a separate service for T0, but this option seems wasteful.

**Comment by amaltaro** [comment]
@germanfgv @LinaresToine can you please clarify the following:
1) which resources would you like to have added in the T0 agent? All T1s? Any T2 other than CERN?
2) in addition, it looks like you also add the following: T0_CH_CERN_Disk, T2_CH_CERN, T2_CH_CERN_P5
3) please point me to the script you use to deploy the T0 agents and/or create these resources
4) are you manually disabling AgentStatusWatcher? Or do you change its [configuration](https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L362) to `False` in the deployment script?

Thanks!

**Comment by germanfgv** [comment]
> 1. which resources would you like to have added in the T0 agent? All T1s? Any T2 other than CERN?

We use T2_CH_CERN, T2_CH_CERN_P5 + selected T1 sites for preocessing. We use T0_CH_CERN_Disk as storage node.

> 2. in addition, it looks like you also add the following: T0_CH_CERN_Disk, T2_CH_CERN, T2_CH_CERN_P5

See previous answer.

> 3. please point me to the script you use to deploy the T0 agents and/or create these resources

That happen in 2 different places
- CERN sites:
  https://github.com/dmwm/T0/blob/master/bin/00_pypi_resource_control.sh
- T1 sites:
  https://github.com/dmwm/T0/blob/master/bin/t0#L134

> 4. are you manually disabling AgentStatusWatcher? Or do you change its [configuration](https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L362) to `False` in the deployment script?

We set that parameter to `False` in the default Tier0Anget config: 
https://github.com/dmwm/T0/blob/master/etc/Tier0Config.py
We merge this default config with the one you linked during deployment
