### ISSUE TITLE
Upgrade MariaDB to the latest 10.6.x release

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#12138]
**Impact of the new feature**
MariaDB

**Is your feature request related to a problem? Please describe.**
Right now we are using MariaDB 10.6.5, dating from Nov/2021, while 10.6.19 has been released in Aug/2024.

Given the issue reported in this ticket: https://github.com/dmwm/WMCore/issues/12136 , I think we should have a conservative upgrade of MariaDB ASAP, potentially for the upcoming WMAgent release. With time and in a different ticket, we can track a major upgrade of MariaDB to the 11.x series.

**Describe the solution you'd like**
Upgrade the MariaDB version used by WMAgent to the latest 10.6.x minor release - at the moment of this ticket, it is `10.6.19`.

**Describe alternatives you've considered**
We could wait for a major upgrade, but if this turns out to be real little effort, we would be running a more solid version of MariaDB.

**Additional context**
Release notes are: https://mariadb.com/kb/en/release-notes-mariadb-106-series/

**Comment by todor-ivanov** [comment]
BTW the latest stable version of MariaDB is: `11.4.3` and the whole `11.4` series  is supposed to be the long term support for MariaDB which should span at least until 2029, as mentioned to the release notes here: https://mariadb.com/kb/en/mariadb-11-4-3-release-notes/ 
So it would have been better if we could make the effort and push a little bit harder and upgrade to the latest version. I know it might seem a big jump, but we  should give it a try.  The change of aliases from `mysql-*` to `mariadb-*` should supposedly not be that big of a problem. There should be few places here and there, mostly in the CMSKuberenetes repository.

**Comment by amaltaro** [comment]
As discussed in our team meeting on Monday, I only wanted to have a minor upgrade of MariaDB, the reasons are:
a) so that we can use a release that will not be affected by that potential bug
b) a safe and effortlessly upgrade
c) and a task that can be done right away (as Operations task).

For the major MariaDB upgrade, it will have to go through more changes and we will have to evaluate its performance as well. To me, that has to be performed as a planned development activity.
