### ISSUE TITLE
agent deployment - improve scripts

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#12162]
**Impact of the new feature**

I would suggest a couple of improvements for the WMAgent deployment procedure:

- cronjobs should be installed as soon as initializing the agents
- we should enforce that we do not initialize an agent if the local couchdb is not empty

**Is your feature request related to a problem? Please describe.**

When deploying a new wmagent, in order to install the cronjobs inside the wmagent docker container, we need to run the script [wmagent-docker-run.sh](https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/wmagent/wmagent-docker-run.sh) twice, which makes little sense.

Last time Andrea and I deployed an agent, we forgot to wipe the local couchdb. Since we never want to start an agent with a non-empty local couch, we should enforce this check

**Describe the solution you'd like**

I will open the proper PR to make these changes

**Describe alternatives you've considered**

We could live as is, but it would be sub-optimal

**Comment by amaltaro** [comment]
@mapellidario haven't we resolved this issue with the following CMSKubernetes developments:
https://github.com/dmwm/CMSKubernetes/pull/1561
https://github.com/dmwm/CMSKubernetes/pull/1563
and
https://github.com/dmwm/CMSKubernetes/pull/1562
?

If so, then I think this issue can be closed out. In the future, please make a reference from the CMSKubernetes PR to the WMCore GH issue, this way we can easily keep track of these developments. Thanks

**Comment by mapellidario** [comment]
Ooooops yes we did, thanks alan for the bookkeeping :)
