### ISSUE TITLE
WMAgent - cronjobs spam

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#12184]
**Impact of the bug**
WMAgent

**Describe the bug**
Upon fixing #12166 A spam behavior was reported by people, notifying that the restart component cronjob is generating a lot of useless emails. The reason is that crontab's stdout gets emailed to the user `cmst1` and consequently anybody to whom its mailbox has been redirected as well. One of the cronjob records in question is as follows:

```
*/15 * * * * source /data/WMAgent.venv3/bin/activate > /dev/null &&  source /data/WMAgent.venv3/deploy/restartComponent.sh 2>&1 >> /data/WMAgent.venv3/srv/wmagent/2.3.7/logs/component-restart.log
```

The situation becomes even worse especially when a machine deployment goes wrong and the component restarts intensify. We happen to notice that in testbed only because with the virtualenv. setup we fixed the cronjobs mailing mechanism first. Once the solution of https://github.com/dmwm/WMCore/issues/12159 (through https://github.com/dmwm/CMSKubernetes/pull/1566) gets propagated to the Docker containers we run in production, we would have been hit by a e-mail storm much bigger than what we noticed in testbed from just a single agent. It would have been a single e-mail per every run of every cronjob from all of the Docker containers in production.

And things do not stop there. In one of those cronjobs, we have a hardwired absolute path not coupled to the environment and the deployment root: https://github.com/dmwm/WMCore/blob/90a14e513d8bce727388f6dcf6b7dac80b616fbd/deploy/restartComponent.sh#L15

Which additionally leads to constantly scanning wrong component logs for errors, especially when it comes to virtual env. setup, and causing indefinite restarts of perfectly healthy components. This path should be tied to the environment variable: `WMA_INSATLL_DIR`
 

 
**How to reproduce it**
Just run the crontabs  as currently generated at the agents 

**Expected behavior**

No e-mails to be generated by cronjobs' stdout.

**Additional context and error message**
None

**Comment by todor-ivanov** [comment]
ok ... I am reopening this issue because there were two problems reported by T0 team:
* They found out the component restarts failed due to a wrong component name identification - it is been there before, I just happened to miss it myself. At this line:  https://github.com/dmwm/WMCore/blob/83c08ffec544faa9c0ec62c7121dd0f5fda1632b/deploy/restartComponent.sh#L16 
```
(WMAgent.venv3) cmst0@vocms0502:~ $ comps=$(ls $WMA_INSTALL_DIR)
(WMAgent.venv3) cmst0@vocms0502:~ $ echo $comps 
AgentStatusWatcher/ AnalyticsDataCollector/ DBS3Upload/ ErrorHandler/ JobAccountant/ JobArchiver/ JobCreator/ JobStatusLite/ JobSubmitter/ JobTracker/ RetryManager/ RucioInjector/ TaskArchiver/ Tier0Feeder/
```
thanks @LinaresToine  for reporting this

* They have tested this mechanism in two of their production agents and turned out the so hardcoded grace period of 30min before considering a component for stale is far from enough, especially when it comes to HI runs: 
https://github.com/dmwm/WMCore/blob/83c08ffec544faa9c0ec62c7121dd0f5fda1632b/deploy/restartComponent.sh#L26 
The result is they noticed the mechanism triggered on every run of the cronjob command and only the formerly explained error about the component naming, saved them from entering a spiral of component restarts.  

**So this should be configurable!!!**

**Comment by todor-ivanov** [comment]
To add something I just noticed. I happened to miss the error reported about the bad component names resolution, simply because the T0 and Production agents behave differently.

* A T0 agent:
```
(WMAgent.venv3) cmst0@vocms0502:/data/tier0/WMAgent.venv3 $ ls $WMA_INSTALL_DIR/
AgentStatusWatcher/  AnalyticsDataCollector/  DBS3Upload/   ErrorHandler/  JobAccountant/  JobArchiver/  JobCreator/  JobStatusLite/  JobSubmitter/  JobTracker/  RetryManager/
RucioInjector/	     TaskArchiver/	      Tier0Feeder/

```

vs.
* A Production agent:
```
(WMAgent.venv3) cmst1@vocms0260:WMAgent.venv3 $ ls $WMA_INSTALL_DIR/
AgentStatusWatcher      ArchiveDataReporter  ErrorHandler   JobArchiver  JobStatusLite  JobTracker  RetryManager   TaskArchiver     WorkQueueManager
AnalyticsDataCollector  DBS3Upload           JobAccountant  JobCreator   JobSubmitter   JobUpdater  RucioInjector  WorkflowUpdater

```

So definitely not the optimal way of identifying the list of enabled components at the agent.

**Comment by amaltaro** [comment]
From this comment: https://github.com/dmwm/WMCore/issues/12184#issuecomment-2505469630

I think there is a misunderstanding on this functionality. This script will not restart a component that is running a long cycle (and/or under heavy load). It actually relies on modifications to the change log (stat command). Provided we are logging something to the component log within 30min, there should be no restart of the component (hence protecting slow components against slow execution).

About making restarts configurable, if we are really serious about such mechanism, then I think we need to take a step back and implement it properly. Either with another component or with an actual supervisor application.
Or even better, making components more resilient such that they (almost) never crash.

**Comment by amaltaro** [comment]
@todor-ivanov as mentioned in my previous comment and now also tested in an agent, indeed with the latest changes the script no longer looks into components that are down. Can you please follow this up? I am reopening this issue.
