### ISSUE TITLE
CouchDB summary pages in WMAgent

### ISSUE THREAD

**Issue by linacre** [dmwm/WMCore#1532]
When there are lots of failures these can take a long time to load. Would it be possible for the couchdb summaries to be automatically created periodically (e.g. 10mins), and have the output saved to an html file which could then load instantly? The couchdb link could then point to this file rather than having to recreate the summary each time (which presumably could also cause high server load with lots of users).

**Comment by amaltaro** [comment]
@ticoann I guess this even precedes WMStats and so I think we can close this issue.
