### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by evansde77** [dmwm/WMCore#1696]
Because we will have to at some point.

Proposal is to branch at some well defined release point (0.8.0?) and run 2to3 on the branch and assess the damage.

**Comment by vkuznet** [comment]
Here is a good reference of how to make transition: https://www.youtube.com/watch?v=KPzDX5TX5HE

**Comment by evansde77** [comment]
Im pretty disappointed that @sfoulkes hasnt done this yet.

**Comment by sfoulkes** [comment]
I'm all over this.

**Comment by vkuznet** [comment]
How nice that people still care

**Comment by PerilousApricot** [comment]
🙅🙅🙅🙅🙅🙅🙅🙅🙅
>
>

-- 
Sent from Gmail Mobile

**Comment by ericvaandering** [comment]
Crap. Cannot assign this to @sfoulkes .

**Comment by ericvaandering** [comment]
There is also this Wiki which probably doesn't contain anything new: https://github.com/dmwm/WMCore/wiki/python3-transition

**Comment by ericvaandering** [comment]
So let me comment on how I think we should go about this. Having looked at modernize vs. futures, I definitely prefer futurize to avoid polluting things with a whole bunch of dependencies on "six". We have no need to support 2.5 or earlier.

I would like to start with two things: Adding the "from future" boilerplate to all new files as he suggests. And running the futurize fixers one at a time. This second bit requires us to have Jenkins back up and running. I'm working on this, but am waiting for @PerilousApricot to give me a bit of information.

His talk spends a lot of time on binary vs. text, but hopefully this is a very limited problem in our case. Division may be a bit trickier, although I doubt we overload the __ operators often if at all.

Finally, this is not just a WMCore/Agent issue but something all of our python products have to deal with (DAS, DBS, CRAB, SiteDB and some smaller things).

**Comment by vkuznet** [comment]
+1

**Comment by ticoann** [comment]
Need to keep the progress. Link Adelina's report here

**Comment by vkuznet** [comment]
Adelina's report:
https://github.com/SaltumDis/DMWMPythonMigration/blob/master/resultsFinal.deps

**Comment by ticoann** [comment]
Thanks Valentin, @ericvaandering, Eric, Is there a option to mark project to retired or something. 
ProdCommon, DLSAPI, WMCore-legacy - Are these used anywhere?

**Comment by ericvaandering** [comment]
I don't know. I can check, but I doubt it. I already told @saltumdis that many of these are dead projects, so I hope she updates the list soon.

**Comment by vkuznet** [comment]
Seangchan, I don't think it's Adelina's work to identify our dead projects,
instead I said many times that we must start campaign to clean-up WMCore and
remove all obsolete code. Please make a separate ticket for that and assign
all relevant people to do the clean-up.

**Comment by ticoann** [comment]
Hi Valentin, I wasn't asking Aledia to idnetify the dead projects. I asked Eric. :smile:, For WMCore I can clean. But I see there are some project I think it is not used anymore. That is what I want to identify. 

i.e. I didn't create WMCore_legacy so I am not sure what was the purpose of that project and it is still used or not.
I am not sure who is the relevant people. I guess we can track down who last updated the code.

**Comment by SaltumDis** [comment]
I'm updating the list.  Moving dependencies of these projects to the bottom of the list as they are no longer used:
CRABServer
ProdCommon
CRAB2
WMCore-legacy
DBSAPI 
DLSAPI 
ContinuousIntegration
Cmssh
FileMover
DQIS
Sandbox

**Comment by amaltaro** [comment]
CRABServer is used

**Comment by ericvaandering** [comment]
@amaltaro is right. My bad. I was thinking of the old CRAB2 server, but that's in CRAB2, not its own repo.

**Comment by vkuznet** [comment]
I'm not sure why it is closed, did we migrated to Python3 already?

Meanwhile, here is a quite good read about new features of Python3.7 which may be beneficial in many areas of our code: https://realpython.com/python37-new-features/

**Comment by amaltaro** [comment]
And I think we can finally consider this issue done and ready to be closed. With WMCore version `1.5.2`, we completed the WMCore migration to Python3.

Production central services have already been running in python3 for a couple of months now (starting with `1.5.0`). WMAgents started being upgraded to Python3 WMCore `1.5.2` this week.

This migration was done with the `future` compatibility library, thus keeping WMCore in dual stack (+2.7 and +3.8) until other projects depending on it have fully migrated to python3.

Thanks to everyone that contributed to getting WMCore in python3, you're awesome!
