### ISSUE TITLE
Flush out bad tasks

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#1745]
Following up on the bad skims we had during Apr21 which blocked the queues a lot. We set the skim thresholds to zero but later had to let them fail out as we needed to run other skims.

Can we have the possibility to flush out bad tasks of workflows so that they don't continue to go into the workqueues and so that we also kill the jonbs of these tasks already inserted into the queues? We also should add these tasks to ACDC so that we can rerun them later with fixes.

Thanks,

OLI

**Comment by amaltaro** [comment]
@ticoann if we've lived without this since 2011, then I guess it'd not be very useful (?)
Sorry Oli, no hard feelings ;-)

**Comment by amaltaro** [comment]
It could be done. However, the right thing here would be to report the workflow back to the requestors, abort it and put a new request in place.
@ticoann shall we close this one?
