### ISSUE TITLE
Add workflow state "Flush"

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#1746]
Can we add a new state possibility for "running" workflows. We had problems with workflows that wouldn't finish because all files of some blocks were invalidated after assignment of the workflow and the agent couldn't find a valid location for these blocks and therefore was waiting indefinitely.

Can we have the possibility to move the workflow forward to the state "Flush" where no more processing jobs of the first step are sent but the rest is properly closed out and force merged.

Thanks,

OLI

**Comment by amaltaro** [comment]
@ticoann @gutsche I guess we can close this one since we have now force-complete. Agree?
