### ISSUE TITLE
Couchapp template application with standard bits used by all our couchapps

### ISSUE THREAD

**Issue by geneguvo** [dmwm/WMCore#1898]
Create a template (skeleton) couchapp with the commonly shared bits:
   * Yui;
   * Replication filter (to avoid replicating design documents);
   * jquery.couch* vendor java scripts with fixes to properly work when behind the frontend (when mounted under "/couchdb");
   * Other commonly used vendor files (json2.js, sha1.js, etc).
   * ... ?

It should not include unnecessary files/directories as those generated by the `couchapp generate` command.

**Comment by amaltaro** [comment]
@ticoann you are the master and will know by heart whether this standard template is in place or not :-)

**Comment by ticoann** [comment]
Diego did this already wrong time ago and we are using it.
