### ISSUE TITLE
CMSCouch shouldn't override the built in id function

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#1908]
id is used as an argument in a few API calls, should be replaced with doc_id and dependent code updated to reflect the change.

**Comment by amaltaro** [comment]
@ticoann any idea about this one?

**Comment by ticoann** [comment]
id is built in function in python but we are using id as parameter as well. (in some case file too). We shouldn't do that. I will move this issue to  "When proper compensation is paid by Eric" milestone.

**Comment by ticoann** [comment]
I am deleting this one. Whenever we get pylint warnings we can fix it gradually.
