### ISSUE TITLE
Update webtools to use cherypy 3.2.0

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#1937]
Says valentine:

{{{
Steve, the problem occurred because I use cherrypy 3.2.0 which has different response.status structure. The problem with WMCore code is 2 fold: it assumes certain structure with response.status (it does not check its type and use split), and there is a caught exception elsewhere which does not propagated to and totally hides the real error. The remedy to first problem is simple, here is patch

diff --git a/src/python/WMCore/WebTools/Root.py b/src/python/WMCore/WebTools/Root.py
index fae75fc..c8e0169 100644
--- a/src/python/WMCore/WebTools/Root.py
+++ b/src/python/WMCore/WebTools/Root.py
@@ -85,7 +85,7 @@ class WTLogger(LogManager):
              'H': self.host,
              'h': remote.name or remote.ip,
              'r': request.request_line,
-             's': response.status.split(" ", 1)[0],
+             's': str(response.status),
              'b': outheaders.get('Content-Length', '') or "-",
              'T': (time.time() - request.start_time)*1e6,
              'AS': inheaders.get("CMS-Auth-Status", "-"),

The caught exception is hard to find in a code. May be you know code better then I am. Anyway I can run my app now with change shown above.
}}}

**Comment by amaltaro** [comment]
Comp has moved to cherrypy 3.2.2, I guess we can close this one, @ticoann ?
