### ISSUE TITLE
Properly clean-up MySQL tables upon job abortion

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#2033]
From google T0test wave:

Regarding MySQL clean-up. The current manage script has a flow. It provides action clean-mysql, which simply remove all tables from wmagent database. But the start-agent action (which calls start_agent which by itself calls init_agent) checks first that .init files exists and therefore NEVER call init step for agent(s). Since that happens the re-creation of tables is NEVER occurred due to presence of .init files. Silly and in my mind it should be fixed. I would prefer another action which removed .init files. 

My comment: I would expect to modify this section of manage script

{{{
clean_mysql(){
    echo "cleaning MySQL DB...";
    if [ -e $INSTALL_MYSQL/logs/mysql.pid ]; then stop_mysql; fi;

```
/bin/rm -f $INSTALL_MYSQL/.init
/bin/rm -f $INSTALL_MYSQL/logs/mysql.sock
/bin/rm -f $INSTALL_MYSQL/logs/mysqld.pid
/bin/rm -rf $INSTALL_MYSQL/database/*
```

}

}}}

As you see it entire wipe out mysql which creates aforementioned problem. Instead it should do 
1. drop tables
2. re-create tables

but leave mysql intact.

**Comment by amaltaro** [comment]
Bump! AFAIK nobody cleans the local WMAgent database... But ok, let's fix this eventually
