### ISSUE TITLE
Information about PhEDEx subscriptions on Workload Summary

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#2119]
OPs would like a link to the subscription information in phedex for each dataset produced.  Easiest way to do this (I think) would be to add an update function to the workload summary.  Once the PhEDExInjector makes a subscription for a dataset it'll post the subscription ID to the workload summary.  Only problem is that PhEDExInjector would have to know the workload name, which it currently doesn't.

**Comment by amaltaro** [comment]
Seems interesting to have. @ticoann we could also add this information to reqmgr_workload_cache db, as well as subscription types and sites auto-approved

**Comment by amaltaro** [comment]
Addressing the same thing in #5793. close this one please
