### ISSUE TITLE
CMSCouch.loadList() raises exception in raising exception

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#2245]
Comments  say:
{{{
        """
        Load data from a list function. This returns data that hasn't been
        decoded, since a list can return data in any format. It is expected that
        the caller of this function knows what data is being returned and how to
        deal with it appropriately.
        """
}}}
which means retval is a string but 
{{{
        if ('error' in retval):
            raise RuntimeError ,\
                    "Error in CouchDB: viewError '%s' reason '%s'" %\
                        (retval['error'], retval['reason'])
}}}
assumes retval is a dict

**Comment by amaltaro** [comment]
@ericvaandering @ticoann is this issue still out there?

**Comment by ericvaandering** [comment]
Looks like loadList was cleaned up but loadView still has the same pattern referenced above. 

https://github.com/dmwm/WMCore/blob/477c33757e856b4d1c0c916fa7b3baabbf04f55b/src/python/WMCore/Database/CMSCouch.py#L437

Of course, I don't really know what problem I was finding 4.5 years ago.

**Comment by ticoann** [comment]
@ericvaandering, Do you want to keep this issue (If you remember :-))?
