### ISSUE TITLE
logging messages not appearing, TestInit.setLogging issue

### ISSUE THREAD

**Issue by zdenekmaxa** [dmwm/WMCore#2247]
Despite the level of sophistication, the !TestInit.setLogging() method returns immediately. It's impossible to get messages INFO, WARNING appearing when running tests manually.

Matt's solution
{{{
logging.basicConfig(level = logLevel)
}}}

makes log messages appear as desired.

**Comment by ticoann** [comment]
closing this issue. Not sure still valid.
