### ISSUE TITLE
Release tests

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#2275]
It would be nice to have a standard set of tests that we run (automated) as part of the release/build process. This would be in addition to the unit tests (though running them and some coverage analysis in the same build/release script would be good). This ticket is to define what tests are needed, new tests will result in additional tickets. Stu already has a tagging script - extending that into wmcore_release would be a good idea IMHO. I think the aim should be that the tests take <1 hour to complete, and certainly less than a working day, so long running integration tests that send things to the grid aren't part of it (though we should work on automating those in the future).

So please provide ideas for tests to run as part of the release. Things I'm thinking of are:
 * Some performance metrics (building on Marco's script)
 * Profiling information; MySQL and CouchDB performance, agent memory foot print
 * Unit tests and coverage - write report into the release

**Comment by ericvaandering** [comment]
@amaltaro can't we close this since you are actually doing this?

**Comment by amaltaro** [comment]
I have no idea what Marco's script is, but I would close this one :)
