### ISSUE TITLE
Don't use list functions to filter available work

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#2358]
It's inefficient and puts a lot of load on the CouchDB server if there's a lot of data filtered out. Instead use view slicing, emit multiple values for an element (e.g. add site into the key), use limit and offsets to page through data and sort/unique data in the client side. 

I think you could do this in two steps: 
1. tweak the view so the list does less work (emit site in the keys)
2. update the filtering client side

**Comment by amaltaro** [comment]
@ticoann is it feasible?

**Comment by ticoann** [comment]
Yes, but I think in terms of performance it is OK, since there won't be big data in WQ. (We cleaned up pretty diligently.  But it will be good to filtering in client side since we can propagate the log to LodDB now, so if workflow is not pulled in local queue. the reason can be reported.

**Comment by ticoann** [comment]
let's do this sooner than later. I will have better reporting as well.

**Comment by ticoann** [comment]
Not going to happen, unless we rewrite the WQ.
