### ISSUE TITLE
Check for valid data tiers during workflow injection

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#2531]
Hi,

can we introduce a check during workflow injection that only valid data tiers are used? 

I usually query for valid data tiers with:

dbsql "find tier"

Thanks,

OLI

**Comment by amaltaro** [comment]
How about this issue from 2011 @ericvaandering @ticoann ? Do we still plan to perform the datatier check during request creation?

**Comment by ericvaandering** [comment]
Doesn't DBS enforce this now? @yuyiguo

**Comment by yuyiguo** [comment]
WMAgent uses  bulk insert into DBS. If the tier is not already in DBS, DBS will insert one.   DBS does not know if the new tier is valid or not.

**Comment by ericvaandering** [comment]
We may want to revisit that. I'm not concerned about WMAgent really, but as I just commented on the slack user-data-review channel, don't we open up to every user defining any data tier they want this way?

**Comment by amaltaro** [comment]
Yep, I agree that only DBS admins (real admins) should be able to create new data-tier. Otherwise, having this check in WMAgent should properly protect DBS/datatiers (at least global instance).

**Comment by amaltaro** [comment]
Fixed by #6067
