### ISSUE TITLE
check for pileup module in config during workflow injection

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#2553]
Hi,

can we check during workflow injection of the Redigi type, that the configuration contains the pileup module? We should check this if the pileup sample field is not empty though.

Thanks,

OLI

**Comment by amaltaro** [comment]
Living with that for 4 years now :-) @ticoann @ericvaandering shall we close it?

**Comment by ericvaandering** [comment]
Only 3.5 years.....
