### ISSUE TITLE
Alarm red/green (column) for each output dataset if subscription has been made and approved in the close out page.

### ISSUE THREAD

**Issue by efajardo** [dmwm/WMCore#2659]
As an operator task of closing out the request it will be nice to have a column on the close out page in which stays green if the subscription for the each outputdataset has been made and approved and red on the contrary.

**Comment by amaltaro** [comment]
Things have changed in Ops now and people don't usually wait for the Data Managers to approve requests. In addition to that, phedex subscriptions are more flexible now (including Disk endpoints) and the agent can self approve it.
@ticoann if you agree we can close this one.
