### ISSUE TITLE
Plot of cooloffs per site/agent for the last 24 hours.

### ISSUE THREAD

**Issue by efajardo** [dmwm/WMCore#2660]
As sometimes is difficult to keep track of cooloffs it will be nice to have plots on the request mgr which shows cooloffs per site, per agent in the last 24 hours. Like the ones found here:

https://test-service-cmst1regmgrmonitor.web.cern.ch/test-service-CMST1RegMgrMonitor/cooloff.html

**Comment by amaltaro** [comment]
This seems to be interesting, however we do not have plots while the workflow is running. How about the available tables showing cooloff jobs with different exit codes and sites? I believe it's Ok for now :-)
@ticoann what do you think? If that's basically not feasible, then let's close this one.

**Comment by ticoann** [comment]
We have information in wmstats. We can plot it too. But I guess we will close this unless some one screams for it.
