### ISSUE TITLE
Add log archives pfn in the job details

### ISSUE THREAD

**Issue by spinoso** [dmwm/WMCore#2673]
We often use the "Log Archives" lfns in the job details for debugging purposes. 

To get the archives we:  

1. copy the <lfn>
2. read the <sitename> from the corresponding line in the "Errors" section immediately above
3. call PhEDEx lfn2pfn (for instance): https://cmsweb.cern.ch/phedex/datasvc/xml/prod/lfn2pfn?node=<sitename>&protocol=srmv2&lfn=<lfn>

Example: https://cmsweb.cern.ch/phedex/datasvc/xml/prod/lfn2pfn?node=T2_BR_SPRACE&protocol=srmv2&lfn=/store/unmerged/logs/prod/2011/10/14/cmsdataops_Backfill_111005_MCTest_T2_BR_SPRACE_111005_114953/Production/0000/1/5e6e95be-f205-11e0-ab8a-003048f0e38c-248-1-logArchive.tar.gz

4. make srm-get <pfn>

It would be fine to add a pfn to each lfn, or a link to the call in (3), so that we can directly copy/paste that pfn to execute 4. on a separate shell.

**Comment by amaltaro** [comment]
WMStats offers the PFN to the logArchive since some time by now. @ticoann can we close it?
