### ISSUE TITLE
inject-to-config-cache: use process validation library in Configuration/DataProcessing and printout

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#2702]
Can we use the (proposed) API to check a process object for validity at the first stages of the inject-to-config-cache script? If the check fails, the script should then not upload the config. Can we make it that f the library is not available in the release used, a warning is printed and the user has to acknowledge before continuing?

Also, can we have additional printout after the successful upload of the config which lists the output modules and data tier/filter names of the config that was just uploaded:

output module 1: data tier: GEN-SIM-RAW, filterName: <NONE>
output module 2: data tier: GEN-SIM-RAW, filterName: lessEvents

So that the requestor notices what his uploaded config will actually produce.

Thanks,

OLI

**Comment by amaltaro** [comment]
I think all these injections are quite stable by now. How about we close this one since nobody worked on it since 2011? @ticoann

**Comment by ericvaandering** [comment]
Closing
