### ISSUE TITLE
WMClient: request APIs and CMSSW release integration

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#2703]
Can we add the APIS from my scripts: makeRequest, approveRequest, assignRequest in a library integrated into the WMClient.

Can we also add APIs for each workflow type that returns as help all parameters and their explanation per type?

And in the end, can we package everything in rpms and hand over to release integration to be included in the CMSSW release?

Thanks,

OLI

**Comment by amaltaro** [comment]
@ticoann someone with more knowledge of wmclient can comment on it? or close :P

**Comment by ticoann** [comment]
I think we already do that with reqmgr.py
