### ISSUE TITLE
Add status 'hold'

### ISSUE THREAD

**Issue by spinoso** [dmwm/WMCore#2796]
During running a workflow it happens that we face a config problem, so the job submission relative to that workflow should be stopped and L3 guys warned to look into the problem; after solving, a new version of the workflow usually is made and submitted.
For those kind of situations a 'hold' status would be very useful. The WMA in that case should just stop submission. The L3 guys can select periodically filtering by status 'hold', correct the error and then set the workflow as aborted. 
Optionally, it would be interesting also to allow reverting hold to running, to handle mistakes.

**Comment by amaltaro** [comment]
This feature was added 2 or 3 years ago with the OpsClipboard - or something like that - and after a few tests we came up with a conclusion that it would be quite hard to manage such a thing.
Moreover, by the moment you select a 'hold', easily tens of thousands of jobs may be created already.
IMO we should close this issue. @ticoann
