### ISSUE TITLE
Error Handler plugin that switches site

### ISSUE THREAD

**Issue by evansde77** [dmwm/WMCore#2823]
Add an enchanced Error Handler plugin to support jobs that have a site whitelist. 

In the event of a failure, use a flat cooloff period and remove the previous execution site from the whitelist. 
In the event that the whitelist is exchausted move to normal cooloff approach.

Useless unless #2822 is completed

**Comment by amaltaro** [comment]
Isn't it part of the Smart retry 'project'? Should we close this one in favor of those PRs/issues that Dirk was working on?

**Comment by amaltaro** [comment]
@hufnagel can we close this one on behalf of your smart retry handling developments?

**Comment by hufnagel** [comment]
Yeah, closing this, doesn't make sense to have this independent from the smart retry handler. If we ever have a quiet moment I need to work our with @ticoann and @ericvaandering what to do about the smart retry handler. That one has a lot of things implemented, not all of which we might want to use immediately or at all. But there are some definitely useful things in there as well, just have to decide what we want and how to proceed.
