### ISSUE TITLE
LogCollect executor stages files to weird places.

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#2883]
LogCollect is staging out a bunch of files to locations like:

/store/tmp/scratch_0/glide_z30148/execute/dir_4137/job/WMTaskSpace/logCollect1/
8cccac16-1217-11e1-b609-00221959e775-0-0-logArchive.tar.gz

Which happens to be "/store/%s" % fileNameOfTarBallOnWorkerNode. The createArchive function in LogCollect passes up the location of the tarball, which the step executor uses as the PFN. There is an LFN set in tarInfo, but I think that's ignored by the (old) stageout code. The new stageout code (with accompanying 100% guarantee) will probably be smarter about that situation.

**Comment by amaltaro** [comment]
We no longer stageout to /store/tmp - from WMAgent code at least. @ticoann, please close this issue.
Andrew, don't get sad :-)
