### ISSUE TITLE
Support space token in Storage plugins

### ISSUE THREAD

**Issue by stuartw** [dmwm/WMCore#2933]
Once we settle on the new system we should suport space token usage in the same way phedex does. Currently sites have to specify a token in the options section which means it  needs to be specified twice.

**Comment by amaltaro** [comment]
I really don't know what this space token is. Since this issues has not been touched for 4 years now, should we close it @PerilousApricot @ticoann ?

**Comment by ticoann** [comment]
I don't know either. If we don't know, we will close it. Chances are we will probably never look at it.
