### ISSUE TITLE
Add support for multiple test paths

### ISSUE THREAD

**Issue by stuartw** [dmwm/WMCore#2937]
Allow the form: python setup.py test --testCertainPath=test/python/WMCore_t/Algorithms_t/BasicAlgos_t.py, test/python/WMCore_t/Algorithms_t/MathAlgos_t.py 

Needed for oracle tests where we will only test certain modules.

Currently passing in multiple paths gives errors.

Thoughts?

**Comment by ticoann** [comment]
this is fixed
