### ISSUE TITLE
Add support to specify job requirements

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#2958]
Hey all,

It would be really rad (but not critical .. well, maybe critical) to add support in WMSpec and BA to add requirements for jobs submitted to the cluster. There could be a common set of options like memory/disc/walltime/# cores requirements that would be translated into scheduler-specific directives (of course with some sort of sensible defaults so that specs without this information wouldn't be rejected).

Two goals:

1) For schedulers that keep track of resources and slay jobs that get too big, there needs to be some way to request more memory for some workflows (looking at you, HI processing jobs)

2) For schedulers that care about walltime, a lot of efficiency could be gained by specifying that some jobs (for instance, LogArchive/cleanup jobs) are going to require little walltime, then they can be backfilled before earlier jobs.

I'd be willing to knock in the changes to WMSpec and the schedulers I have access to, and someone else could fix the other schedulers later (if nothing happens with them, the behavior would be the same as now, so it wouldn't be a problem if other people never got on it)

**Comment by amaltaro** [comment]
I guess we can close it since we now specify in the job classAds the expected WallTime, Expected disk usage, number of cores, memory required, etc @hufnagel @ticoann , should we close it?

**Comment by amaltaro** [comment]
ping

**Comment by ticoann** [comment]
This still might be relevant. Since we are having meeting about MaxWallTimeMin in a couple of day. I can create the new issue after finding out what comes out from the meeting and reference this issue.

**Comment by amaltaro** [comment]
I don't remember what came out of that discussion, but we do specify several parameters now.
Shall we close it?
