### ISSUE TITLE
Keep a mapping of LFNs to log collect tarballs in the WL summary

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#2993]
Talked to Matt about this, it isn't straight forward to do.  Filing this ticket anyway.

**Comment by amaltaro** [comment]
I believe this will be part of the WMArchive. Also, the WL summary does not seem to be the best place to put a list of LFNs (not for very big workflows at least). @ticoann @yuyiguo should we close this one and defer it to WMArchive?
