### ISSUE TITLE
Retrieve cms site name from site-local-config

### ISSUE THREAD

**Issue by cinquo** [dmwm/WMCore#3014]
As discussed in #2817.
There is also the savannah (#savannah:125253) to have a test on sam for this (so we are sure that site will have this). I would suggest to wait this to be done before having WMCore using this.

**Comment by amaltaro** [comment]
probably no longer needed @ticoann can we close this one?

**Comment by ericvaandering** [comment]
This probably is some early version of what @alexanderrichards is doing now. Closing
