### ISSUE TITLE
error reporting in couchdb jobsummary for failed multicore jobs

### ISSUE THREAD

**Issue by hernand** [dmwm/WMCore#3019]
in case of multicore jobs, the description of the error in the jobsummary in couchdb is not very meaningful. For example:
http://vocms121.cern.ch:5984/wmagent_jobdump%2Fjobs/_design/JobDump/_show/jobSummary/409
When the error happens in one of the children, it is not reported in the cmsRun1-stderr.log file but in the log file of the corresponding child. It is also reported in the xml job report of the child. So, it would be useful to get it from the job report and dump it into the job summary in couchdb. 
Right now the only way to understand what the error was is to manually copy the logarchive and look into it.

**Comment by amaltaro** [comment]
4 years old issue, I would just close it and open a new one if we hit the same issue after years of multicore development @ticoann
