### ISSUE TITLE
pycurl_manager can't handle 201 etc. return codes

### ISSUE THREAD

**Issue by stuartw** [dmwm/WMCore#3043]
Just saw the code has:
{{{
if  header.status == 200:
..
else:
  raise..
}}}

Couchdb, probably as well as others, returns at least 201 codes. Suggest only throwing on >=400.

**Comment by amaltaro** [comment]
The code was not changed. I wonder whether WMAgent is using this wrapper and whether these changes are still wanted. @vkuznet since you developed it, you are the best person to help us here :-P

**Comment by vkuznet** [comment]
Here is the fix: https://github.com/dmwm/WMCore/pull/5790, regarding the usage of the module I can't say much. Let's ask Seangchan, @ticoann do you know?

**Comment by ticoann** [comment]
I think we are using pycurl in agent. But haven really check. closing the issue.
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/wmagent.spec#L8
