### ISSUE TITLE
Look into marking datasets as valid in DBS from the closeout page in ReqMgr

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#3195]
This isn't the easiest to do.  We'd have to add a REST service to the ReqMgr that did this.  The ReqMgr would also need a cert that had write access to DBS.

**Comment by amaltaro** [comment]
@ticoann I believe it's going to be part of ReqMgr2, right? How about we then close this one?

**Comment by ticoann** [comment]
We were not planning to to this in reqmgr2, but shouldn't this be when it gets announced?

**Comment by ticoann** [comment]
I will close this unless Steve want to do it. :smile:
