### ISSUE TITLE
Move parent/child links from dataset to file records on web UI

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#3250]
New set of dataset created by DMWM do not set up parentage. It should be done on file level. This will be the case of DBS3 too. So I need to remove Parent/Child from dataset web records into file ones. Basically I need to discard Parent/Child links from presentation map.

**Comment by amaltaro** [comment]
I don't quite understand this issue. Anyways it's too old and lots of things happened on this front :-) @ticoann @vkuznet can we close this one?
