### ISSUE TITLE
Generic Alert Poller for WMBS

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#3319]
Implement a generic poller for WMBS (basically a SQL query poller). Particular watched metrics:

* We should add an alarm that will pick up on files that have not gone through job splitting and turned into jobs in a reasonable amount of time (= if the number of files in the wmbs_sub_files_available table goes beyond a certain number, generate an alert)

* Implement so that further WMBS metrics are easy to add

**Comment by amaltaro** [comment]
It has been 3 years with not a single comment to this issue. @ticoann how about we close it?
