### ISSUE TITLE
HTML special characters not encoded when rendering job errors on the job summary page

### ISSUE THREAD

**Issue by pkonst** [dmwm/WMCore#3328]
Example: a job fails with a line in the scramOutput.log like:

{{{['/store/mc/Fall11/TTJets_TuneZ2_7TeV-madgraph-tauola/AODSIM/PU_S6_START42_V14B-v2/0000/0CD90D3B-850F-E111-8298-001A92971B8E.root'] is not a valid <class 'FWCore.ParameterSet.Types.string'>Details:}}}

The part {{{<class 'FWCore.ParameterSet.Types.string'>}}} is not seen in the browser but it could be important for understanding the reason for the failure.

**Comment by amaltaro** [comment]
It should be fixed by now. If it's not, people usually look directly into the couch doc.
@ticoann can we close it?
