### ISSUE TITLE
Use JSONParser in JobArchiver

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#3385]
This is spun off of #3274.  You should use the JSON code we have in WMCore/Services/JSONParser instead of importing the json module directly.

**Comment by amaltaro** [comment]
JobArchiver is still importing directly json. Should we keep it open or... just close it? @ticoann @ericvaandering

**Comment by ericvaandering** [comment]
Let me look @ this one.

**Comment by ericvaandering** [comment]
Closing. #4418 even says JSONParser is no longer needed which I can see from looking at the code. I'll open another issue to actually get rid of it.
