### ISSUE TITLE
Enable Multicore for other request types

### ISSUE THREAD

**Issue by evansde77** [dmwm/WMCore#3397]
At present only the DataProcessing Request type includes support for Multicore controls, exposing the "Multicore" parameter. 

This should be selectively enabled for other Request types that need to use this mode of operation as it is now supported in StdBase. 
This should just be a case of supporting the setting in the Request Type, the underlying code will then set up all processing steps as Multicore jobs with the setting provided. 

At present, we distiguish Processing from MultiProcessing in the Task type, so some adjustment may be needed.  (Eg would ReReco become MultiReReco etc)

Input needed on:
- Which Requests types to enable Multicore for
- Wether this impacts the task type for those Requests

**Comment by ericvaandering** [comment]
Irrelevant now

**Comment by evansde77** [comment]
One for Throwback Thursday...
