### ISSUE TITLE
Blacklisting sites in WMS mode by the WMAgent operator

### ISSUE THREAD

**Issue by pkonst** [dmwm/WMCore#3470]
We have tested WMAgent 'WMS mode' for both Condor and gLite plugins within a CRAB3 server setup. It works exactly as expected.

We have seen that in the case of (temporary) runtime problems at some site, e.g. stage-out, there is no way for the server operator to (temporary) block job submission to such a site. For this purpose it would be useful if the plugin removed the sites that have zero slots defined in Resource DB from the list of possible sites for the job given to the WMS.

Currently workflows succeed in such cases only because there is chance that failed job sent by the WMS to a different site on resubmission.

**Comment by amaltaro** [comment]
@ticoann , please close this one since WMS mode only adds sites that have available slots in resource control.

**Comment by amaltaro** [comment]
@ticoann ping
