### ISSUE TITLE
HTTP tests sometimes fail with Connection Refused

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#3536]
I tried to track this down, but I couldn't find any easy culprits. On jenkins HTTP stuff (connecting to a local couchpy) will fail with

{{{
Traceback (most recent call last):
  File "/jenkins/workspace/WMCore-UnitTests/jobSlice/4/label/wmcore-unit-test-slaves/deploy/0.8.35/sw/slc5_amd64_gcc461/external/python/2.6.4-comp3/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/jenkins/workspace/WMCore-UnitTests-try/jobSlice/4/label/wmcore-unit-test-slaves/code/test/python/WMCore_t/WebTools_t/REST_t.py", line 168, in testA
    response = makeRequest(url=self.urlbase + '/', values={'value':1234})
  File "/jenkins/install/lib/python2.6/site-packages/WMQuality/WebTools/RESTClientAPI.py", line 53, in makeRequest
    conn.connect()
  File "/jenkins/workspace/WMCore-UnitTests/jobSlice/4/label/wmcore-unit-test-slaves/deploy/0.8.35/sw/slc5_amd64_gcc461/external/python/2.6.4-comp3/lib/python2.6/httplib.py", line 704, in connect
    self.timeout)
  File "/jenkins/workspace/WMCore-UnitTests/jobSlice/4/label/wmcore-unit-test-slaves/deploy/0.8.35/sw/slc5_amd64_gcc461/external/python/2.6.4-comp3/lib/python2.6/socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 111] Connection refused
-------------------- >> begin captured stdout << ---------------------

THIS BETTER NOT BE A PRODUCTION SERVER

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: This is our config: from WMCore.Configuration import Configuration
config = Configuration()
config.component_('SecurityModule')
config.SecurityModule.dangerously_insecure = True
config.SecurityModule.componentDir = None
config.component_('Webtools')
config.Webtools.componentDir = None
config.Webtools.access_log_level = 30
config.Webtools.expires = 300
config.Webtools.environment = 'development'
config.Webtools.application = 'UnitTests'
config.Webtools.host = 'localhost'
config.Webtools.log_screen = False
config.Webtools.error_log_level = 30
config.Webtools.port = 8888
config.component_('UnitTests')
config.UnitTests.templates = '/tmp'
config.UnitTests.description = 'Dummy server for the running of unit tests'
config.UnitTests.componentDir = None
config.UnitTests.section_('views')
config.UnitTests.views.section_('active')
config.UnitTests.views.active.section_('rest')
config.UnitTests.views.active.rest.section_('database')
config.UnitTests.views.active.rest.database.connectUrl = 'sqlite://'
config.UnitTests.views.active.rest.object = 'WMCore.WebTools.RESTApi'
config.UnitTests.views.active.rest.application = 'UnitTestRESTApp'
config.UnitTests.views.active.rest.default_expires = 300
config.UnitTests.views.active.rest.section_('model')
config.UnitTests.views.active.rest.model.object = 'WMCore_t.WebTools_t.DummyRESTModel'
config.UnitTests.views.active.rest.section_('formatter')
config.UnitTests.views.active.rest.formatter.templates = '/tmp'
config.UnitTests.views.active.rest.formatter.object = 'WMCore.WebTools.RESTFormatter'
config.UnitTests.admin = 'UnitTestAdmin'
config.UnitTests.title = 'CMS WMCore/WebTools Unit Tests'

root: ERROR: Missing componentDir and General section in config
root: ERROR: Going to trust you to know what you're doing.
cherrypy.access: WARNING: You are using the NullAuth, I hope you know what you're doing
--------------------- >> end captured logging << ---------------------
}}}

Any ideas?

**Comment by amaltaro** [comment]
@ericvaandering since you started playing with jenkins, should we keep this one open?

**Comment by ericvaandering** [comment]
I think with whatever re-boot of Jenkins we have, all new issues are going to crop up. So yeah.
