### ISSUE TITLE
Agent component logging and shutdown sequence

### ISSUE THREAD

**Issue by zdenekmaxa** [dmwm/WMCore#3602]
Agent's Harness, from which components inherit, has rather messy behaviour in terms of logging. For example, no logging message appears from a component's constructor, but later on (preInitialization) it does. Plain print statements are not appearing in the stdout.log file. Not sure why logging is partially duplicated in the stderr.log file.

wmcoreD --shutdown leads to signal.SIGTERM, however, neither Harness, not components install any handler for this signal so there is no chance to trigger the shutdown sequence in the components.

**Comment by amaltaro** [comment]
If agent fails to start one component, then it stops there and reports an error. I guess it's good for now. @ticoann , shall we close this 3 years old issue?
