### ISSUE TITLE
Report output files not loaded from Report.pkl

### ISSUE THREAD

**Issue by cinquo** [dmwm/WMCore#3604]
We are facing an issue with jobs being sent with the configuration that I am attaching to this ticket (config-cache and configFile). All jobs sent with that configuration are failing. User pset contains:
{{{
process.out = cms.OutputModule("PoolOutputModule",
    outputCommands = cms.untracked.vstring('keep *_selectedPatPhotons*_*_*', 
        'keep *_selectedPatElectrons*_*_*', 
        'keep *_selectedPatMuons*_*_*', 
        'keep *_selectedPatTaus*_*_*', 
        'keep *_selectedPatJets*_*_*', 
        'drop *_selectedPatJets_pfCandidates_*', 
        'drop *_*PF_caloTowers_*', 
        'drop *_*JPT_pfCandidates_*', 
        'drop *_*Calo_pfCandidates_*', 
        'keep *_patMETs*_*_*', 
        'keep *_selectedPatPFParticles*_*_*', 
        'keep *_selectedPatTrackCands*_*_*', 
        'drop *_selectedPatJets*_genJets_*'),
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring('p')
    ),
    fileName = cms.string('PatEvent.root')
)
}}}

I tried to load the Report and the problem is that {{{StageOut.post}}} method doesn't find the [https://svnweb.cern.ch/trac/CMSDMWM/browser/WMCore/trunk/src/python/WMCore/WMSpec/Steps/Executors/StageOut.py#L279
 guid] in the output file
{{{
>>> files = stepReport.getAllFileRefsFromStep(step = 'cmsRun1')
>>> for file in files:
...   if not hasattr(file, 'lfn') or not hasattr(file, 'location') or not hasattr(file, 'guid'):
...     print 'failed'
... 
failed
>>> sfile = files[0]
<WMCore.Configuration.ConfigSection object at 0x1c840ad0>
>>> hasattr(sfile, 'lfn')
True
>>> hasattr(sfile, 'location')
True
>>> hasattr(sfile, 'guid')
}}}

Also Preslav noticed the stderr of the job has the error message from https://svnweb.cern.ch/trac/CMSDMWM/browser/WMCore/trunk/src/python/WMCore/FwkJobReport/Report.py#L719:
{{{
INFO:root:Retrieved following performance figures:
INFO:root:RSS: 835868;  VSize: 1180768; PCPU: 98.5; PMEM: 13.9
ERROR:root:Tried to divide by zero doing storage statistics report parsing.
ERROR:root:Either you aren't reading and writing data, or you aren't reporting 
it.
ERROR:root:Not adding any storage performance info to report.
ERROR:root:Asked to retrieve files from step cmsRun1 with no outputModules
INFO:root:Steps.Executors.CMSSW.post called
}}}

This is the output file dictionary:
{{{
>>> step1.analysis.files.file0.dictionary_()
{'acquisitionEra': '1334064363', 'OutputPFN': 'srm://srmb.ihepa.ufl.edu:8443/srm/v2/server?SFN=/cms/data/store/temp/user/buchmann/CRAB-Out/buchmann_crab_Ndreaalysis_NTupProd_LM2_Summer11_Apr10_120410_161300/output/NTupleProducer_42X_data_0001.root', 'globalTag': None, 'processingVer': 'v1', 'lfn': '/store/temp/user/buchmann/CRAB-Out/buchmann_crab_Ndreaalysis_NTupProd_LM2_Summer11_Apr10_120410_161300/output/NTupleProducer_42X_data_0001.root', 'configURL': 'http://vocms120.cern.ch:5984;;wmagent_configcache;;812fa6f928bd7a7f8edbe60b5c0c5be6', 'fileName': '/wntmp/execute/dir_20974/glide_R21006/execute/dir_31081/job/WMTaskSpace/cmsRun1/NTupleProducer_42X_data.root', 'Source': 'TFileService', 'location': 'srm.ihepa.ufl.edu', 'InputPFN': '/wntmp/execute/dir_20974/glide_R21006/execute/dir_31081/job/WMTaskSpace/cmsRun1/NTupleProducer_42X_data.root', 'validate': False, 'pfn': '/wntmp/execute/dir_20974/glide_R21006/execute/dir_31081/job/WMTaskSpace/cmsRun1/NTupleProducer_42X_data.root', 'inputPath': '/LM2_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/AODSIM', 'StageOutCommand': 'srmv2-lcg', 'validStatus': 'PRODUCTION'}
}}}

The report generated by the job is also attached to this ticket, with the associated fwjr document in couchdb (note the analysis under the output key in the cmsRun1 step).

**Comment by amaltaro** [comment]
Still from the svn era :-) I'm not aware of output reporting problems, so I guess we can close this one, @ticoann ?
