### ISSUE TITLE
Add CPU and disk space killing to performance monitoring

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#3605]
In the same way that we can kill jobs that take too much memory, we need to be able to set thresholds for CPU time used, wall time, and disk space used so that we kill jobs before the pilot or sites do.

**Comment by amaltaro** [comment]
Right now we have a memory monitoring (MaxRSS and MaxVSize) that is shipped along the job.
On the agent side, there is a "config.JobStatusLite.stateTimeouts" where we specify for how long jobs can be in the running/pending state (the action I believe to be a condor_rm or close to it).
For disk space, there is nothing monitoring it from the WMAgent side.

If we should implement it, then leave it open. @ticoann @ericvaandering ?

**Comment by ticoann** [comment]
@ericvaandering, Eric can we close this?
