### ISSUE TITLE
Specify splitting parameters for new requests

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#3665]
We need to figure out how to specify the splitting parameters for new requests in the ReqMgr.  Most workflows will take a parameter like the following:
  "StdJobSplitArgs": {"lumis_per_job": lumisperjob},

The ReqMgr doesn't like it when you pass it that though.  Need to figure out how to do this.

**Comment by amaltaro** [comment]
A few changes happened to job splitting and it's possible to pass them (and algo) during request creation. @ticoann I guess we can close this one.
