### ISSUE TITLE
Don't include run/lumi information in job objects

### ISSUE THREAD

**Issue by sfoulkes** [dmwm/WMCore#3946]
We're currently including the run and lumi information in the input files in job objects.  This is causing problems as for MonteCarlo jobs the run and lumi information can be massive.  This results in job packages that are so large (~200MB) that they can't be transfered by the glideins.

We need to strip the run and lumi information from input files after we create the job.  It shouldn't be needed at runtime.

**Comment by amaltaro** [comment]
Done since 2012. @ticoann please close it

**Comment by amaltaro** [comment]
@ticoann close plz
