### ISSUE TITLE
Job retry distribution in the Workflow Summary

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#3967]
Copying what I wrote in HN (https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/398.html):

Around 5 months ago, I contributed with a view, that shows the failure
distribution for a workflow, documented on this ticket (Steve commited
for me) :

https://svnweb.cern.ch/trac/CMSDMWM/ticket/3313

I hoped that it would go in into some release some time afterwards,
but if I look here :

 https://cmsweb.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/amaltaro_RVCMSSW_6_0_0_pre10MinBias_120725_230422_8052

For instance, I don't see that it was used.

It was agreed that this will be done in the priority WMCore gives it, so I'm creating this ticket so it gets moving.

**Comment by amaltaro** [comment]
Samir, it seems this information is available in the workloadSummary. Since nobody looks at the "human" workflow summary. I would close this issue.
@ticoann can we close it please
