### ISSUE TITLE
Handle expanding datasets in WorkQueue

### ISSUE THREAD

**Issue by stuartw** [dmwm/WMCore#3992]
There is no way to work out whether new blocks will appear for a dataset right? If so, then the workqueue can poll for new blocks for a set period. Or, we could look at having the workqueue monitor the request manager for the upstream request and continue polling until that request completes.

Add optional field in spec splitting parameters "NewWorkPollingLifetime", name subject to change.
Global workqueue  polls for "NewWorkPollingLifetime" time after request injection and creates elements for the new blocks.
Global returns false for wmbsInjection status until "NewWorkPollingLifetime" period is over - so that dqm etc stuff only happens at the end as now.

I'd rather not all requests had this, so we should add a field to reqmgr to set this - which defaults to 0.

Also, can we just check these requests aren't something which should go into a TaskChain type request?

**Comment by amaltaro** [comment]
this has been done @ticoann close it please
