### ISSUE TITLE
Have WMAgent check ulimit -v 

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#4000]
Another request from Dave Dykstra:

       "Before doing cmsRun, have wmagent check ulimit -v to make sure it
	is either unlimited or there is a reasonable minimum amount of
	virtual memory space (in kilobytes) allowed, and if not abort
	with a clear error message.  This is the problem that caused a
	significant amount of job failures a couple weeks ago at CERN
	(it was set to 1.5GB) and it was hard to diagnose.  In theory
	ulimit -m might also cause a problem, but everything I've seen
	indicates that it is not enforced by Linux so it should not be
	checked."

Steve and I discussed this. Yes, it could pick up some problems on WN in rare cases, but in general we just assume the WN is ready to go. E.g. we don't test whether partitions are mounted read-only, etc. 

We may want to roll this into SAM tests instead.

**Comment by amaltaro** [comment]
@ticoann I guess we should close it
