### ISSUE TITLE
get rid of cherrypySetup decorator

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4017]
That decorator doesn't properly handle tearing down cherrypy, and worse doesn't have exception handling to even try if the test case blows up.

**Comment by amaltaro** [comment]
This commit is also related:
https://github.com/dmwm/WMCore/commit/de452acc0a54ccd8a8f27366a0a52d66d2c4f4b3

maybe @ericvaandering has some input here. I still need to ramp up on unit tests stuff :(

**Comment by ericvaandering** [comment]
No idea. Probably leave it open for now.

**Comment by ticoann** [comment]
@ericvaandering, still wants to leave it open. :-)?

**Comment by ericvaandering** [comment]
Yeah. Maybe @amaltaro will fix this since he was just asking me about the "CherryPy still has 32 threads running" issue in the unit tests.

**Comment by ticoann** [comment]
OK set the milestone and assign to Alan. :-)

**Comment by ericvaandering** [comment]
Let's be honest. this is not going to be changed in the next month. No point in a close in milestone (or perhaps a milestone at all)

**Comment by ticoann** [comment]
If we don't set the milestone we tend to lose track. It is just a reminder. so someday we will fix it. Other wise it will show up next annual clean up. 😄
