### ISSUE TITLE
Update all cherrypy-based tests to clean up state

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4028]
Cherrypy has a bad problem with keeping state, tests like

test/python/WMCore_t/WebTools_t/Root_t.py

don't properly clean it, which breaks tests even in other classes, which is really hard to chase down. The tests have been disabled, so they should be fixed for completeness

**Comment by amaltaro** [comment]
I did not run any test yet, so I cannot say :-) @ticoann any comments on this?

**Comment by ticoann** [comment]
I think this is done. We will reopen the issue if not.
