### ISSUE TITLE
Gracefully handle services being down in testing

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4036]
Occasionally, tests like

WMCore_t/Services_t/PhEDEx_t/PhEDEx_t.py

will fail because cmsweb is down for maintenance, etc… We should trap 503 (service unavailable) and raise a nose.skipTest to keep jenkins from going crazy

**Comment by amaltaro** [comment]
@ericvaandering you may have input for this issue

**Comment by ericvaandering** [comment]
Let's keep this one open. It's just a generally good idea even if we don't do it anytime soon.
