### ISSUE TITLE
Extremely expensive SQL query in ListThresholdsForCreate

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#4044]
The unassignedSQL query in ListThresholdsForCreate is extremely expensive.  I've seen it take upward of 15 minutes to execute on vocms96.

Is it possible to cache just that query for a few minutes (to decrease the query rate) or simply remove it?

**Comment by amaltaro** [comment]
it seems it was an exceptional case with 500k jobs in the system.
Looking at the query.... wow, it's huge. Maybe @yuyiguo could try to improve this query?

**Comment by ticoann** [comment]
We will try to looking into rewrite the query

**Comment by ticoann** [comment]
This is rewritten. Should be faster.
