### ISSUE TITLE
Add functionality to set/check parameters in PSet

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4050]
If process/module.dataset.dataTier or process.output.dataset.filterName aren't set in a pset, the agent blows up spectacularly later. I've got code to twiddle the process to add sensible defaults to those fields, but I have to refactor it a sensible way from some private analysis code to ConfigCache (well, really psettweaks). Marco and Daniele were asking about this

**Comment by amaltaro** [comment]
PSet stuff, I guess we can close this one @ticoann

**Comment by ericvaandering** [comment]
This may be related to CRAB3-WMAgent.
