### ISSUE TITLE
Send dashboard reports from the agent in chunks

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4053]
Julia has reported that we are losing messages sent from the agents, it seems the problem is when the agent sends many messages at once (for example the JobCreator can create thousands of jobs in a cycle, or the ErrorHandler can fail hundreds as well).

The idea would be to split the messages in chunks, send in a separate thread and do a sleep between chunks to make sure we don't overflow. I think a risk may be not sending a complete set of reports before the next polling cycle, therefore creating multiple threads. I'll try to measure that first.

**Comment by amaltaro** [comment]
@ticoann should we close this one as well?
