### ISSUE TITLE
Missing JobState transitions in Couch

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4078]
In the busiest agents sometimes we encounter inconsistencies between the number of cooloff/queued/success/failed jobs (those whose information is obtained from couch instead of BossAir)  in the GM and WMBS. The problem is that we often get errors in ChangeState when trying to upload the transitions to couch, usual timeouts when couch is too busy or down. If I understand correctly WMStats would have the same problem as that information is uploaded to wmstats based on what the local couch says, is that right @ticoann?

One of the reasons is the default queue limit of 1000 when committing these documents which is just too much, that should help with the "couch is busy" part. I'll modify that one.

I was thinking that an option would be to make the AnalyticsCollector reconcile the job states in local couch and wmbs before uploading the information, that way even if couch was down before the information in WMStats would be always accurate. Thoughts?

**Comment by amaltaro** [comment]
May also be interesting to investigate it...
