### ISSUE TITLE
Add workflow job states listing to WMStats

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#4090]
This is rather simple and in principle all the information is there, should be "just" about linking it to the agent couchDB.

It is also an interesting feature for Edgar and Preslav, where we just want to have the usual links form the job counters in the page to pages like that :

```
http://vocms96.cern.ch:5984/wmagent_jobdump%2Fjobs/_design/JobDump/_list/runningJobs/statusByWorkflowName?startkey=[%22casarsa_EXO-Summer12-00878_168_v2__120907_195650_3018%22]&endkey=[%22casarsa_EXO-Summer12-00878_168_v2__120907_195650_3018%22%2C{}]&reduce=false&stale=ok
```
Preslav commented that an advantage of WMStats is that it aggregates by site too, so my suggestion is that if not there, another key field is added with the site, so, depending on the grouping when the view is called, one can decide to take the site into accounting or not.

Thanks,
Samir

**Comment by amaltaro** [comment]
WMstats does this job now @ticoann please close it
