### ISSUE TITLE
Input files in job document do not correspond to what has been actually processed

### ISSUE THREAD

**Issue by cinquo** [dmwm/WMCore#4091]
When using halt_job_on_file_boundaries=False it happens that a very same file (and lumis) is assigned to two consecutive jobs.
The problem seems related to the fact that here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/LumiBased.py#L221 lastLumi of the current job is also the firstLumi of the consecutive job.

**Comment by amaltaro** [comment]
It may be worth it to investigate whether this issue has been completely solved or not. But I'm not doing it right now :)

**Comment by ticoann** [comment]
@amaltaro, This want to investigate?

**Comment by amaltaro** [comment]
Nope and it seems to have been fixed long time ago :)
