### ISSUE TITLE
Add performance logging to database things

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4094]
I was thinking/musing that it would probably not be too difficult to hijack the DAO/CMSCouch interfaces, connect them to the alerts interface, then connect the alerts interface to something like Graphite or RRDTool to get some #s on where things need to be optimized. Extra credit for (once we update to a recent version of couch) tracking how long our couch instances spend updating views.

I have an (unfounded) hunch that we have some views that we spend a lot of time building and then never call enough to justify burning all the CPU on. Getting some metrics for that would be nice.

**Comment by amaltaro** [comment]
seems interesting, but I don't think we''ll ever work on it (3 years have past) :-)
@ticoann should we close this one?
