### ISSUE TITLE
setup test should throw if nose isn't installed

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4098]
Currently, running 'setup test' just makes a Command that has no arguments and does nothing if nose isn't installed. It should raise an exception in the arguments-parsing stuff to let the user know. Right now, it just complains because the command line arguments are missing, which is difficult to diagnose.

**Comment by amaltaro** [comment]
@ericvaandering @ticoann do you guys know if that's still the case?

**Comment by ericvaandering** [comment]
I dunno, but this is in my wheelhouse now.

**Comment by PerilousApricot** [comment]
It still is the case

>

-- 
Sent from Gmail Mobile

**Comment by ticoann** [comment]
@ericvaandering, Is this still the case?

**Comment by ericvaandering** [comment]
Nothing changed since 2015 on this.
