### ISSUE TITLE
Use maxInput events CMSSW feature to produce MonteCarlo events

### ISSUE THREAD

**Issue by efajardo** [dmwm/WMCore#4102]
The MonteCarlo request should ask for:

1. The Max Input events
2. The Flter Efficiency
3. Output Events

And use the CMSSW feature that asks for only 1,2 to produce the events

**Comment by amaltaro** [comment]
PdmV now calculates the expected output events, so no need to have this new field. @ticoann can we close it?

**Comment by amaltaro** [comment]
@ticoann can we close this one?
