### ISSUE TITLE
Implement state change on tier0_requests to complete

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#4113]
Title says it all, one of my initial thoughts is that it should be done by the TaskArchiver when it finishes it's job.

But I don't know what changes state for usual requests, so better look there first. Problem is that it won't be general, but something only for "tier0_requests"

**Comment by amaltaro** [comment]
@hufnagel any comments on this issue? Can we close it?

**Comment by hufnagel** [comment]
@ticoann or @lucacopa might know more. I think this is related to Tier0 wmstats and how the Tier0 defines requests, but I don't know much about how that is done in detail.

**Comment by lucacopa** [comment]
This shouldn't be an issue anymore. Request are moved to complete correctly according to:
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStats/_attachments/js/DataStruct/T0/WMStats.RunSummary.js#L47
Also, we are able to keep requests in complete status for as log as we configure it. Then they are moved to archived as any other kind of request. 
@ticoann you can close this
