### ISSUE TITLE
srmv2 stageout implementation fails for file paths containing consecutive slashes

### ISSUE THREAD

**Issue by pkonst** [dmwm/WMCore#4131]
The srm v2 stageout implementation determines the size of the written file by doing `srmls` on the remote PFN and then `grep` for the remote path (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/SRMV2Impl.py#L197). When the PFN and the path contain consecutive slashes, e.g. (*), this does not work because `srmls` returns the path with just a single slash and the `grep` does not match. This results in declaring perfectly successful stageouts as failed.

(*)
srm://lcgsedc01.jinr.ru:8443/srm/managerv2?SFN=/pnfs/jinr.ru/data/cms/store/temp/user/pkonst/logs///pkonst_crab_crab3test-PK-001_121003_101259/Analysis/0000/0/eb423dac-0d47-11e2-893f-003048f1c5ce-23-0-logArchive.tar.gz

**Comment by amaltaro** [comment]
Seems it got fixed. @ticoann please close
