### ISSUE TITLE
Abort workflows can leave jobs running

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4159]
If jobs are in "complete" state by the time the WorkQueue calls the Jobs.killWorkflow DAO, those jobs will escape the killing. If they are to succeed they will move to succeed and trigger merge jobs, creating a dataset on the aborted workflow. If they fail, they will stay in the agent, retry as normal, if eventually succeed then also trigger merge jobs and create a bad dataset.

I think complete state should be included among the jobs to be killed when aborting the workflow, otherwise it can waste resources and create unwanted data. I haven't looked well enough the abort code but I don't see why not, please correct me if I'm wrong.

The case when this actually happens is very rare anyway.

**Comment by amaltaro** [comment]
We have made several changes lately to this code and it should not happen anymore. Besides it's quite old :-) @ticoann close this one please
