### ISSUE TITLE
More generic multiprocessing scheduling

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#4162]
Glidein WMS guys are working on a better way to support multi-core scheduling. Rather than dedicated queues we would specify 

+GLIDEIN_Is_HTPC = True

right now that would get us 8-core slots, but in the future they will communicate back to us (ENV variable, I imagine) the actual number of cores the job should use.

This is a placeholder issue. I don't expect this will reach production until we have a multithreaded CMSSW, but it may be worth testing with before that.

**Comment by amaltaro** [comment]
We don't even set this GLIDEIN_Is_HTPC anymore. @ericvaandering should we close it?
