### ISSUE TITLE
Race condition on transition from Assigned to Rejected

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4178]
There seems to be a race condition when a request is in assigned, and it was already picked up by the ReqMgrInterface main loop in the GlobalWorkqueue and meanwhile it's splitting it an operator rejects the request.

Which leaves the state in the ReqMgr as rejected but the request keeps running because it actually created the elements in the workqueue, and the workqueue doesn't do anything on rejected requests it just doesn't pick them up for splitting but it was already split anyway.

Not sure of a good solution for this, my ideas is:

-> Do the same in rejected as in aborted if necessary (i.e. if there are elements for that request in the global WQ)

@stuartw what do you think? Here is the information I used for debugging:

https://cmslogbook.cern.ch/elog/Workflow+processing/4608
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=etorassa_EWK-Summer12_DR53X-00089_T1_IT_CNAF_MSS_batch77res_v1__121009_233442_92
https://cmsweb.cern.ch/couchdb/wmstats/etorassa_EWK-Summer12_DR53X-00089_T1_IT_CNAF_MSS_batch77res_v1__121009_233442_92

Btw, @ticoann Looking at WMStats the assigned transition was not registered but the teams and site_whitelist were so it must have been registered somehow. Any idea why?

**Comment by amaltaro** [comment]
assigned to rejected is not allowed anymore. @ticoann please close
