### ISSUE TITLE
Propagate the GridID to the Dashboard

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4183]
Moving stuff from my  to do list to the issues list to keep better track. Julia asked for this some time ago, it can help debugging problems.

Looking into it.

**Comment by amaltaro** [comment]
I see we send the jobID (don't know the difference for the gridID). If it's not done yet, then it's not needed :-) @ticoann should we close this one?

**Comment by ticoann** [comment]
I am not sure what is gridID either, is it worker node id?

**Comment by ericvaandering** [comment]
It's a concept from edg days: an id to uniquely is a job on the grid.
