### ISSUE TITLE
Changes on the Workflow Summary couchapp

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#4219]
Diego and I were talking and we think that we could improve the Workflow Summary page in order to have it more dinamic and useable.

2 Main needed features for now are : 

  * Expand and shrink tasks (you only look at the tasks you want
  * Make the histograms/plots on the client side, have data points on the server side (couch document)

That's all for now. We need to solve all tickets listed below before looking into this : 

https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowWMAgentFixesRequestSummary

**Comment by amaltaro** [comment]
It needs to go over a makeover #4483
@ticoann please close this one

**Comment by amaltaro** [comment]
ping
