### ISSUE TITLE
Add tool to fetch logarchs from finished workflows -- given LFN

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#4229]
This should be implemented as a map like :

{ key : LFN, task : taskName, Value : JobID, inputFiles: InputFilesList}

Which should go into the worloadsummary DB but under a different kind of document. should be called like ReqName-lfnmap-N

Each document can hold at most 1000 entries or X configurable.

Talking to Edgar and reviewing things myself, it seems that the easiest is to provide per LFN, job ID, task name, INPUT FILES. 

The last one, will be very useful if we get a merge job, but we want the processing job, so we iterate through the inputs on the same thing to get the processing jobs, and it can scale up to whatever number of tasks you have in the workflow.

Description of the implementation : 
https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/446.html

**Comment by amaltaro** [comment]
Same comment as in #4243.
I believe WMArchive is going to handle it. @ticoann shall we close it?

**Comment by ticoann** [comment]
WMStats has this information.

**Comment by amaltaro** [comment]
Can we close it then?
