### ISSUE TITLE
Allow jobSummaryDBName to use a different couchurl than chouchDBName

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#4235]
The JobStateMachine section of the configuration contains the following parameters:

```
config.section_('JobStateMachine')
config.JobStateMachine.couchurl = 'http://blahblah.cern.ch:5984'
config.JobStateMachine.jobSummaryDBName = 'wmagent_summary'
config.JobStateMachine.couchDBName = 'wmagent_jobdump'
```

so we are forced to use the same couch instance for both the jobdump and the jobsummary.

**Comment by amaltaro** [comment]
Probably no longer out there. @ticoann please close
