### ISSUE TITLE
Archival for LFN->Job map

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#4243]
There are some ideas, we will likely need to review it when #4229 is done, but for now :+1: 
- (Dirk) Archive it in Oracle

Easily querable afterwards, might have more cost on manpower to implement.
- (Steve/Samir) CASTOR

Not easy to access afterwards, shouldn't cost much to implement.

We have to take into account that this kind of debugging is needed every 1 or 2 months, but when we need, Ops say it's 2~4h until we get what we want.

**Comment by amaltaro** [comment]
I believe WMArchive is going to handle it. @ticoann shall we close it?

**Comment by ticoann** [comment]
Local couch has this in formation, yes this need to be implemented in WMArchive
