### ISSUE TITLE
JobTracker crashing when MySQL is under heavy load

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4248]
I have seen this happen quite often now, sometimes MySQL is under heavy load and the JobTracker tries to pass many jobs in a single transaction and gets a timeout on the lock.

OperationalError: (OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')

This bring downs the component which usually delays the agent operation since the agent sees many jobs as "running" in the batch system.

I think this can just try, except and retry. This would go on the ChangeState module as it is a general thing, to make it more robust.

**Comment by amaltaro** [comment]
Maybe we can also close this one and if that happens again, then we open a new one. @ticoann how about it?
