### ISSUE TITLE
WMStats monitoring raise LWQ alarms depending on workflow status

### ISSUE THREAD

**Issue by cinquo** [dmwm/WMCore#4257]
You can see here an example of the GUI page: https://dl.dropbox.com/u/4076401/debug/wmstats.lwq.alarms.png

In reality both the workflows have been pulled by the LWQ (queue injection 100%), but the workflow status is still acquired because the WQ did not report it yet to the ReqMgr. This ends up on showing some inconsistent information. Not big problem  thought.

**Comment by amaltaro** [comment]
@ticoann please close

**Comment by ticoann** [comment]
LogDB should handle this eventually
