### ISSUE TITLE
WMstats job summary report missing output tFiles 

### ISSUE THREAD

**Issue by cinquo** [dmwm/WMCore#4286]
Some jobs do not get the output files being recognized by the JobAccountant https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L284-L294 and then not propagated into wmstats, making impossible to track these files from the monitoring.
Looking at the report https://dl.dropbox.com/u/4076401/debug/Report.0-3.pkl I see these files being produced but written in 'analysis.files' section and not in 'output' as usual. This seems to be the root cause: these files cannot be retrieved with `jobReport.getAllFilesFromStep(step='cmsRun1')`.

This is the corresponding spec https://dl.dropbox.com/u/4076401/debug/tfile.spec
This is the config cache object https://dl.dropbox.com/u/4076401/debug/tfile.cc.json
While this is the config file https://dl.dropbox.com/u/4076401/debug/configfile.py provided by the user.

A patch would be to retrieve all the files with https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/Report.py#L933-L940, replacing the currently being used https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/Report.py#L714-L719. I just gave it a try and it seems to work fine (also for log files).

Here below you can find the snapshot from the configuration.

```
FrameworkJobReport.cmsRun1.section_('analysis')
FrameworkJobReport.cmsRun1.analysis.section_('files')
FrameworkJobReport.cmsRun1.analysis.files.section_('file0')
FrameworkJobReport.cmsRun1.analysis.files.file0.OutputPFN = 'srm://ganymede.hep.kbfi.ee:8888/srm/v2/server?SFN=/hdfs/cms/store/temp/user/pkonst/CRAB-Out/pkonst_crab_newMuonAna-01_121109_131535/output/histo_06Aug2012A_ReReco_0001.root'
FrameworkJobReport.cmsRun1.analysis.files.file0.globalTag = 'GR_R_53_V6C::All'
FrameworkJobReport.cmsRun1.analysis.files.file0.processingVer = None
FrameworkJobReport.cmsRun1.analysis.files.file0.custodialSite = None
FrameworkJobReport.cmsRun1.analysis.files.file0.lfn = '/store/temp/user/pkonst/CRAB-Out/pkonst_crab_newMuonAna-01_121109_131535/output/histo_06Aug2012A_ReReco_0001.root'
FrameworkJobReport.cmsRun1.analysis.files.file0.configURL = 'https://crab3-test/couchdb;;analysis_reqmgr_config_cache;;5f88e23427ae1d2f9832108c0c82698e'
FrameworkJobReport.cmsRun1.analysis.files.file0.validStatus = 'PRODUCTION'
FrameworkJobReport.cmsRun1.analysis.files.file0.fileName = '/home/cms078/home_creur_213164349/CREAM213164349/glide_k26109/execute/dir_28622/job/WMTaskSpace/cmsRun1/histo_06Aug2012A_ReReco.root'
FrameworkJobReport.cmsRun1.analysis.files.file0.Source = 'TFileService'
FrameworkJobReport.cmsRun1.analysis.files.file0.pfn = '/home/cms078/home_creur_213164349/CREAM213164349/glide_k26109/execute/dir_28622/job/WMTaskSpace/cmsRun1/histo_06Aug2012A_ReReco.root'
FrameworkJobReport.cmsRun1.analysis.files.file0.location = 'ganymede.hep.kbfi.ee'
FrameworkJobReport.cmsRun1.analysis.files.file0.InputPFN = '/home/cms078/home_creur_213164349/CREAM213164349/glide_k26109/execute/dir_28622/job/WMTaskSpace/cmsRun1/histo_06Aug2012A_ReReco.root'
FrameworkJobReport.cmsRun1.analysis.files.file0.validate = False
FrameworkJobReport.cmsRun1.analysis.files.file0.acquisitionEra = None
FrameworkJobReport.cmsRun1.analysis.files.file0.StageOutCommand = 'srmv2-lcg'
FrameworkJobReport.cmsRun1.analysis.files.file0.inputPath = '/SingleMu/Run2012A-recover-06Aug2012-v1/AOD'
FrameworkJobReport.cmsRun1.analysis.files.fileCount = 1
```

**Comment by amaltaro** [comment]
Most likely it's gone. @ticoann shall we close this one?

**Comment by ticoann** [comment]
Yes this is fixed
