### ISSUE TITLE
WorkerThreads test occasionally hangs

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4294]
In test/python/WMCore_t/WorkerThreads_t/WorkerThreads_t.py, the test with the docstring If a worker raises an exception terminate the entire component can hang, killing the test process. It should be fixed, marked integration or deleted

Thanks,
Andrew

**Comment by amaltaro** [comment]
@ticoann @ericvaandering you know if it's still the case.
Should I stop bugging you guys about these test issues?

**Comment by ericvaandering** [comment]
Also marked for future review. Of course @PerilousApricot 's suggestion is easy to implement.

**Comment by ticoann** [comment]
I think we can mark as integration. Unless someone prefer to investigate.

**Comment by amaltaro** [comment]
integration
