### ISSUE TITLE
JobCreator hit the Too many links limit when creating a jobCollection directory

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4331]
It can get really big the number of jobs in cases like LogCollect and hit the OS limit on the number of subdirectories allowed.

Most of the directories will be empty and can be removed, but that doesn't happen automatically. The JobArchiver could do that after archiving the last job in a JobCollection.

**Comment by amaltaro** [comment]
I'm not aware of this problem for quite some time now. If I'm not wrong the limits for ext4 filesystem are much bigger and thus this problem should not happen anymore.
Should we close this issue @ticoann ?
How about @alexanderrichards ' PR? Maybe we keep that opened but close this one?

**Comment by ticoann** [comment]
Yes Alex made a patch, we didn't put in since it didn't get tested. So open the pull request but close this one.
