### ISSUE TITLE
TaskArchiver subscription finishing logic "deadlocking" with multiple requests with the same input

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4341]
In an agent we have 2 request reading on the same input dataset on the first step (it's TaskChain), now both have finished processing everything but some subscriptions are not marked as finished and therefore the request is stuck at running.

This is because the second part of the query which checks for parentage in l. 57 of GetAndMarkFinishedSubscriptions, this was added to prevent deletion of parents when shared between requests due to race conditions.

It was just in the code for the PromptSkimming case with Tier1PromptReco, for now in the affected agent I am removing that portion of the query while we come up with something better.

**Comment by amaltaro** [comment]
@ticoann I guess this is related to the fix you are working on to decouple workflow completion, no?

**Comment by ticoann** [comment]
yes
