### ISSUE TITLE
EventAwareLumiBased and LumiBased rare bug causing duplicated events

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4383]
Disclaimer: I am creating the issue so that we are aware that this can happen but I'm not sure if we should fix since the fact that a lumi is fully contained in a file is a prerequisite.

If an input dataset has lumis split across files and these algorithms are set to process more than one file per job then it is possible that duplicated events are created. Here's the scenario:
- RAW File A has lumis 1 to 6
- RAW File B has lumis 1 to 3, 7 to 10

So we have split lumis which we shouldn't but we do. 

Now if Split files between jobs: False then the algorithm will fit more than one file per job if that helps reach the optimal event count. 

The algorithm is iterating and finds file A, and creates a job for it with a mask of lumis 1 to 5 (splitting is set for 5 lumis per job), but now it has only 1 more lumi to allocate, so it will find the next file in the list (B) and will see its lumis and create a mask from lumis 1 to 3 and lumi 7, and finally a third job with lumis 8 to 10.

So we have 3 jobs:

Job-1 : File A and lumi mask 1 to 5
Job-2 : File A and B and lumi mask 6, 1 to 3, 7
Job-3 : File B and lumi mask 8 to 10

So Job-2 will process lumis 1 to 3 of file B AND A, and we get duplicated events since Job-1 already processed lumis 1 to 3 of file A.

**Comment by amaltaro** [comment]
to medium prio it goes.
