### ISSUE TITLE
ReqMgr2 - Oracle to CouchDB data migration

### ISSUE THREAD

**Issue by zdenekmaxa** [dmwm/WMCore#4388]
Once #4380, write a script checking for all possible information items in Oracle and setting them correspondingly in CouchDB (on the currently null items which #4380 should fix on future requests). Or in an unlikely scenario even creating new fields on existing documents in CouchDB.

This is a grand ticket accumulating all notes and instructions for ReqMgr Oracle,CouchDB data consistency scrutinizing particular Oracle tables, columns and CouchDB document fields.

Close after ReqMgr2 becomes just ReqMgr and Oracle no longer exclusively contains anything of value, i.e. everything is in CouchDB.

**Comment by amaltaro** [comment]
It seems part of this discussion (way too long) is very fruitful. If we are getting rid of of oracle db in reqmgr2, should we keep this open @ticoann ?

**Comment by ticoann** [comment]
I will keep this one just for the check point. We can close it when we switch to reqmgr2
