### ISSUE TITLE
Dashboard task activity - Configurable

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4390]
Right now we have a dashboard activity type in the assign page, but this really doesn't do anything since that is only reported on request creation and not afterwards.

There is a request to make it configurable so we should do some changes at some point, not really a priority though.

**Comment by amaltaro** [comment]
We do have "Dashboard" parameter which is set during assignment.
So we can close this issue @ticoann

**Comment by amaltaro** [comment]
@ticoann please close this one
