### ISSUE TITLE
Fix sorting in WMStats to take into account 100% being the largest

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4394]
In WMStats, the job/injection/event/lumi completion percents are sorted lexicographically when you mess with the sorting buttons. this makes a weird thing where the table thinks 0% < 100% < 20%, when it should be 0% < 20% < 100%

**Comment by amaltaro** [comment]
I just reproduced this issue with "job progress" column, at least.

**Comment by ticoann** [comment]
This is fixed
