### ISSUE TITLE
TaskArchiver query is making DBs unhappy

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4405]
According to CERN-IT reports it is taking up to 5h on the Tier-0, and that is just the part before we check the list of files for parentage.

We do have 300 requests in a single agent (Tier-0) which probably aggravates the problem, but we certainly need to optimize it.

Also tied with #4341

**Comment by amaltaro** [comment]
I guess we can close this one as well. @ticoann if we find TaskArchiver "defeating" the DB, then we can open a new one

**Comment by ticoann** [comment]
this is fixed at least on the query getting finished workflow
