### ISSUE TITLE
LogCollect jobs shouldn't clean up

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4427]
It causes problems because you don't know if the job actually succeeded only with runtime information, there are other things that play a role there. Deleting the logArchives can lead to hopeless retries by subsequent jobs.

Discussed with @hufnagel, and a better idea would be to have a Cleanup subscription that takes care of the logs after these have been LogCollected and the jobs came back successfully.

**Comment by amaltaro** [comment]
If I looked at the right place
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py#L184

then the cleanup in logCollect jobs is still in place and we need to fix it, eventually :D
