### ISSUE TITLE
Add information about inputs processed to workload summaries

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4438]
The workload summary currently just outputs the number of outputted events per output dataset (i.e. the number of events written to disk). It would be nice to also get the number of input events and list of in/out run/lumis also added to the summary as well. @samircury has a SQL query for it, I just need to wrap it in a DAO and put it in the taskarchiver.

**Comment by amaltaro** [comment]
workload summary is going to be worked here #4483. @ticoann please close this one
