### ISSUE TITLE
how to create LSF job names in the LsfPlugin

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#4460]
At the moment the job name we set in LSF is constructed from the jobs cache_dir path and the job id. Since #3630 the jobs wmbs name is also available in the LsfPlugin. At the moment there isn't much advantage to use this, we would first have to make sure the job splitters define some reasonable names.

For the Tier0 use case this would mean including run and stream/dataset in the job name as we are interested in seeing this info in the LSF job name. Placeholder for now, what we have works for now and it's not clear if we are really staying with LSF submission longterm (might be all AgileInfrastructure post-LS1).

**Comment by amaltaro** [comment]
since we moved away of LSF submission, do we still want to spend time on this issue? @hufnagel @ticoann otherwise close it please
