### ISSUE TITLE
Use Replicator documents in WorkQueue replications and cleanup  _replicate code

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4462]
All WorkQueue replications use the old _replicate API, CouchDB recommends using replicator documents for all your replication needs.

**Comment by amaltaro** [comment]
We have migrated to _replicator db some time ago. Though I still see _replicate being mentioned in 2 files. Maybe we should clean them up? @ticoann

**Comment by ticoann** [comment]
I will clean them up. But after https://github.com/dmwm/WMCore/pull/5628
