### ISSUE TITLE
Tools to recover from a host failure

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4475]
Assuming total loss of a host, we need a tool that can identify what we lost (WorkQueue elements running in the agent), reset them and invalidate the already produced output from DBS. There is no requirement to recover the work already done with finer granularity.

Putting this in medium priority as an Ops request, no milestone or deadline but should be soon.

**Comment by amaltaro** [comment]
IF this ever happens, then such tools would indeed be very handy.
However, since we have plennnnty of things on our plate already, I would either close it or... don't know, maybe set a milestone to 2016 or something like that @ticoann
