### ISSUE TITLE
Create extended MonteCarlo from previous MonteCarlo

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4478]
Same as #4477 this is a convenience feature for ReqMgr to facilitate the creation of extended MonteCarlo requests using the FirstLumi/FirstEvent automatically using the spec information. Is like a cloning operation but the ReqMgr has to evaluate the FirstLumi/FirstEvent as appropiate.

Probably for ReqMgr1 we can put this in reqmgr.py, but ReqMgr2 could support this "natively".

**Comment by amaltaro** [comment]
MC extension is in production for quite some time. @ticoann please close
