### ISSUE TITLE
Workflow Summary Makeover

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4483]
In a nutshell, improve document structure, move visualization to WMStats and improve visualization.

The needed features are:
- User friendly performance histograms with API for retrieval
- Error display, organized by sites, exit codes. 
- Missing lumis per output dataset with API for JSON retrieval
- Input description (including run information)
- Output description
- DQMHarvest information, run list of what was harvested.

This needs also more discussion on what else is required by Ops.

This will include the following issues:
#3967 #4438 #4315 #4219

This covers all that is contained in:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowWMAgentFixesRequestSummary

Most of it is closed already anyway.

**Comment by ticoann** [comment]
Diego and I were talking and we think that we could improve the Workflow Summary page in order to have it more dinamic and useable.

2 Main needed features for now are :

    Expand and shrink tasks (you only look at the tasks you want
    Make the histograms/plots on the client side, have data points on the server side (couch document)

That's all for now. We need to solve all tickets listed below before looking into this :

https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowWMAgentFixesRequestSummary

**Comment by amaltaro** [comment]
@vlimant is Unified using the workloadsummary document from couch? If so, can you tell me which information you lookup and what's the use case?
@AndrewLevin can you also aswer these questions please?

**Comment by AndrewLevin** [comment]
sorry, can you give the link to the workload summary document?

I am not exactly sure what it is.

**Comment by amaltaro** [comment]
Example from testbed:
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?workloadsummary/amaltaro_ReDigi_cmsRun2_LumiMask_Agent107_Validation_DeterPU_v1_150618_165637_255

**Comment by AndrewLevin** [comment]
I don't use it for anything.

**Comment by vlimant** [comment]
Unified uses it to get the "errors" : for making a call on ACDC and to make the summary of why a lumi section is missing from an output file.
We might change to a better source of information if any, or adapt to the new schema.

**Comment by ticoann** [comment]
Unified shouldn't use this for that purpose. The problem with workload summary is that it only keeps one agent summary. Multiple agent generates for the same requests when requests runs in multiple agents. But the last uploaded one kept.

Workload summary was created when the requirement was one request is going to specific agent.

**Comment by vlimant** [comment]
the wmstats job details should be used instead ? I did not have that at the time.
will schedule the migration asap.

**Comment by amaltaro** [comment]
Which means, the workloadSummary has basically no usage anymore :-) We should consider that during this makeover and maybe make it really just a summary, and not a full detail document about the workflow

**Comment by vlimant** [comment]
While trying to use the /wmstatsserver/data/jobdetail/<wfn> to get the aggregated information I (re)notice two things

a- lumis = [] while it is displaying in wmstats. please add the full list

b- samples has only limited (like, 1) entry, therefore it's not possible to gather cause for loss for all missing lumis. #6858
