### ISSUE TITLE
Show the CE and Workernode in WMStats for jobs in failed and in cooloff

### ISSUE THREAD

**Issue by efajardo** [dmwm/WMCore#4490]
Hi,

During the O&C week it was requested we need the pilot jobs to pass the CE to the WMAgent job and then this one should do the following:

1. Report the correct CE to dashboard
2. For failed and cooloff jobs it should correctly show in wmstats the workernode where it ran aswell as the CE.

**Comment by amaltaro** [comment]
Two years have passed and this was not implemented nor bumped, I'd assume we don't really need it.
@ticoann shall we close this one?
