### ISSUE TITLE
Adding logfile dowload capability in WMStat

### ISSUE THREAD

**Issue by xjanssen** [dmwm/WMCore#4533]
Hi Seangchang et al.,

As we have from time to time to access the true logfile of a job and that imply seferal manipulation:

1) Get the lfn from the job output summary

   by example:
    logArchive
    lfn:    /store/unmerged/logs/prod/2013/4/4/jen_a_ACDC234Pro_Winter532012DMETParked_FNALPrio4_537p6_130403_042115_5913/DataProcessing/DataProcessingMergeRECOoutput/skim_2012D_METParked/0001/1/00710a8c-9c5e-11e2-9408-003048f02d38-1-1-logArchive.tar.gz

2) Find the pfn:

  by example by parsing the output of:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/lfn2pfn?node=T2_US_MIT&protocol=srmv2&lfn=/store/unmerged/logs/prod/2013/4/4/jen_a_ACDC234Pro_Winter532012DMETParked_FNALPrio4_537p6_130403_042115_5913/DataProcessing/DataProcessingMergeRECOoutput/skim_2012D_METParked/0001/1/00710a8c-9c5e-11e2-9408-003048f02d38-1-1-logArchive.tar.gz

3) Get a certificate and do a lcg-cp with that info

Would it be possible to implement a dowload button in WMStat that just use the holded certificate and make step 1,2&3 and give the logfile tarball to the user. It would speed-up debugging of problems.

Ofc, it would need to take care of case where the logs are already copied at CERN to serve them from there instead of fishing them from a specific site.

Cheers. Xavier.

**Comment by amaltaro** [comment]
@ticoann I guess this is going to be handled by WMArchive, no?

**Comment by ericvaandering** [comment]
I changed the title to be more generic. Will also assign to @yuyiguo on the assumption that it gets taken care of.

**Comment by ticoann** [comment]
In favor of #7724 closing this.
