### ISSUE TITLE
Make reqmgr creation/assign parameter consistent in units

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4541]
We have several entries that are measured in bytes:

BlockCloseMaxSize 
Memory 
maxRSS 
maxVSize 
SizePerEvent 
MinMergeSize
MaxMergeSize 

It would be more clear if they are all in the same scale.

**Comment by amaltaro** [comment]
@lucacopa BIG shame that you did not fix this yet :-P
Do you have time to work on this issue? Otherwise I'll try to handle it in the next days (seems to be simple)

**Comment by lucacopa** [comment]
@amaltaro I have forgot about this :-) Not this week, and I am leaving on vacation next one, so if you can work on it, go ahead
