### ISSUE TITLE
ReqMgr2 CouchDB update function restriction

### ISSUE THREAD

**Issue by zdenekmaxa** [dmwm/WMCore#4564]
ReqMgr2 update function can only be called directly from ReqMgr2 service, not e.g. via curl with exception of ReqMgr2 developers. Figure out correct restrictions.

**Comment by amaltaro** [comment]
@ticoann do you understand this issue?

**Comment by ticoann** [comment]
We can change reqmgr  couchdb 2 ways, going through reqmgr2 api and direct access to couchdb. There are more control over what it can be done with reqmgr2 api. (which permission is given to which function, etc). We should have the same control on direct couch access. But this might be hard to do that.
One thing we can do is restrict direct couch update access to local  and only allow reqmgr2 api access.
