### ISSUE TITLE
keep the current status of table in wmstats when it get refreshed

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#4569]

**Comment by amaltaro** [comment]
@ticoann this applies to number of entries and sorting basically, right?

**Comment by ticoann** [comment]
This one need to be done. WMStats automatically refresh page but if table is sorted different way than default it changed to default which shouldn't happen

**Comment by amaltaro** [comment]
And this was another source of discussions. From the discussions and personal experience, this is what should happen when page gets refreshed:
1. keep the same filters in the input text boxes (already in place)
2. keep the same "number of rows" selected (25, 50, 75, 10)
3. keep the same column sorting, if existent
4. (bonus) make a button that you can disable auto-refresh

Also bumping the priority :)

**Comment by amaltaro** [comment]
@ticoann seems to be fixed. Closing
