### ISSUE TITLE
Fix rpm-jenkins patching

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4613]
need to blow away /jenkins/deploy/current in the jenkins-rpm script when a deploy gets detected as failing

**Comment by amaltaro** [comment]
Sorry :-) @ericvaandering how about this one?

**Comment by ericvaandering** [comment]
Let's keep it.

**Comment by ticoann** [comment]
@ericvaandering, this is fixed isn't it?

**Comment by ericvaandering** [comment]
It's not causing problems anymore. We deploy from scratch.
