### ISSUE TITLE
Improve the WMAgent deployment

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4621]
Objective:
- Allow upgrading a WMAgent codebase without requiring a drain.

Requirements:
- Integration with cmsweb deployment scripts, mainly for couchdb and MySQL, however we are not setting up the WMAgents as cmsweb services, just trying to standardize the deployment.
- Code development must be backwards compatible with the database contents, and information out of main memory such as sandboxes, job packages in disk, and submitted jobs in the batch system.

**Comment by amaltaro** [comment]
We found out that couch and sql database clean up is needed in the end.
Deployment is quite straight forward now, though it does not follow cmsweb way (it's not a cmsweb service anyways xD).
@ticoann shall we close this one?

**Comment by ticoann** [comment]
Since Diego already did work and we just need to validate. I think we should keep this.
