### ISSUE TITLE
Add a rev limiter to the WorkQueue

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4644]
A typical workqueue element is around 60kb and 100kb, these are stored in main memory during the splitting before being stored in couchdb. Which means that we can only reasonably produce 10k of them before going overboard in memory and bringing down the host.

This is a reasonable limit for ReReco since there are not datasets as big as 10k blocks. For MC there is always the option of making several workflows with different starting points (i.e. FirstLumi).

**Comment by ticoann** [comment]
This is fixed. WQ won't create too many elements at once any more.
