### ISSUE TITLE
Monitoring fix for late binding

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4716]
If jobs fail out too fast after moving to running state the JobStatusLite component has no chance to updating the running site to the real site instead of the randomly selected one in submission. This causes problems in the monitoring since we get failures appointed to the wrong sites in WMStats and Dashboard.

Possible solution is to retrieve condor_history on "missing" jobs and making sure of the running site when declaring them as failed. It should be top priority.

**Comment by amaltaro** [comment]
I think it has been fixed in the last couple of months, so closing it.
