### ISSUE TITLE
Identifying workflows going through ACDC process

### ISSUE THREAD

**Issue by dballesteros7** [dmwm/WMCore#4735]
A current operational hassle is identifying which workflows in completed already have ACDC workflows running and which do not, we need to add a state to the ReqMgr state machine in order to identify this "recovering" status.

Additionally, we need monitoring, either in WMStats or through the ACDCServer couchapp about the Resubmission workflows and their parents.

**Comment by amaltaro** [comment]
So, the idea is good but this issue is now 3 years old. Unified seems to be doing a pretty good job at tracking ACDCs. How about we close it?

**Comment by ticoann** [comment]
Actually we already have the view for checking this one. whether all the acdc are finished from original workflows. I think we can may be add the column on marking this in wmstats. I will move to this month issue and check how hard to add this.

**Comment by amaltaro** [comment]
Which view is that? Does it report the acdc and their status or it returns either 1 or 0 for ALL acdcs finished or not?
About adding it to wmstats, maybe ask CompOps first, it may be that it would be used for 1 workflow in 1000, and if so, I'd say don't waste time on it.

**Comment by ticoann** [comment]
It just list all the acdc's created from original workflow. we need to additional query to check whether acdc is finished but extending (or creating) other view will be trivial.

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byoriginalrequest?key=%22alahiff_2013AMinimumBias_5323_141217_204535_7970%22

Yes I won't add anything without consulting ops, Maybe they don't need this.
However what are you doing on Friday night, stop posting and commenting. 😄

**Comment by amaltaro** [comment]
To medium prio it goes.

**Comment by ticoann** [comment]
I will close this one. We have a call to list all the workflows related to either output dataset or original workflow. That can be used instead of separate status.
