### ISSUE TITLE
checking for duplicate dataset names

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#4768]
Hi,

We would like to have some kind of check when wmagent adds to a dataset to see whether the dataset already exists. Usually, we would like to fail the workflow is the dataset already exists. But we also need an option to allow the workflow to write to an existing dataset.

Andrew

**Comment by ticoann** [comment]
@AndrewLevin, do you still need this feature. To do this,
1. check dbs when request is created, if the dataset is exist give the warning and make the user confirm
  (I am not sure how this will work if the script is used to create the workflow).
2. Or in the spec, we can add the flag 'ignore duplicate output dataset' so it can be controlled. (i.e. ACDC workflow will set this flag True).

**Comment by AndrewLevin** [comment]
Hi Seangchan,

Yes, we still need this feature.

Using only a DBS query when the workflow is created does not cover all cases. If two workflows which produce the same dataset are created at similar times, then this check will not catch this. (This happens relatively frequently in release validation.) Do you have an idea about how to catch that case?

Thanks.

Andrew

**Comment by AndrewLevin** [comment]
Hi,

I think Julian and I still need to discuss what exactly we want. Please hold off on working on this.

Andrew
