### ISSUE TITLE
catch wrong enabledqmharvest parameter in reqmgr

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#4798]
The workflow dictionary parameter enabledqmharvest recently changed to enableharvesting, but the request manager does not catch workflows where the old parameter is used, it simply ignores that parameter. Please implement a check that the correct parameter used and give a useful error message in case the wrong parameter is used.

Thanks.

Andrew

**Comment by amaltaro** [comment]
I guess we do not have any workflows using the old parameter anymore.
So instead of adding more code into WMCore, I would suggest to simply close this issue.
@ticoann what do you think?

**Comment by ticoann** [comment]
@AndrewLevin, Andrew, can we close this?

**Comment by AndrewLevin** [comment]
Can you make a list of allowed parameters and check all of the parameters against this list?

**Comment by ticoann** [comment]
Yes, we can. All the parameters are base parameters defined here.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L874

But specific parameters are defined for each spec
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/MonteCarloFromGEN.py#L98

We can check whether some parameter is passed which is not defined in there, through the validation error. Is that what you want?

**Comment by AndrewLevin** [comment]
Yes, that is what I want.

**Comment by amaltaro** [comment]
Hmm, I agree that we should only allow expected parameters.
However, we sometimes need to provide another parameter that is not expected and
I would like not to have requests failing during injection, e.g., RequestSubType, Comments (that I'm using in my battery of requests).

This issue is basically 2 years old, why would we care about enabledqmharvest that is no longer used?!

**Comment by AndrewLevin** [comment]
Hi Alan,

If you want to have Comments and RequestSubType, can't you just add them to the list?

Do you need to use so many new parameters that you can't add them to the list before you use them?

Andrew

**Comment by amaltaro** [comment]
StdBase has only mandatory arguments for all the requests. These parameters are not mandatory, especially "Comments".
I insist, do you see any harvesting problems for the last months due to this retired parameter?

**Comment by AndrewLevin** [comment]
No, I don't see any harvesting problems in the last months. But I still think we should check the workflow parameters. Are we doing any checking of the workflow parameters now?

**Comment by ticoann** [comment]
On May 9, 2015, at 3:29 PM, AndrewLevin <notifications@github.com<mailto:notifications@github.com>> wrote:


No, I don't see any harvesting problems in the last months. But I still think we should check the workflow parameters. Are we doing any checking of the workflow parameters now?

**Comment by ticoann** [comment]
All the parameters are validated (If it is not optional user should enter the value. If it is optional it will take the default value specified in case a user didn't specify the value) But we are not checking the values it is not defined. (Simply gets ignored). It is good to check whether parameter is defined or not. However, as Alan said if the parameter is newly defined between the deployment it will cause the problem. - Although I don't think you should add the parameters on the fly.

**Comment by AndrewLevin** [comment]
Yes, I think we should have a list of optional parameters and of required parameters, and we should check that all of the parameters that are received are in one of these lists. Alan, do you agree?

**Comment by amaltaro** [comment]
Provided we keep:
 - "SubRequestType" (for TaskChain only - optional)
 - "Comments" (for all workflows - optional)
It's fine with me. Even so, I'd mark it as low priority and/or improvement ...

**Comment by AndrewLevin** [comment]
Someone requested a workflow with EnableDQMHarvest again:

woodson_HLT_newconditions0_RelVal_245005_150529_211459_9221

Can you please change this issue to be high priority?

**Comment by AndrewLevin** [comment]
Just to clarify, this is for reqmgr2.

**Comment by AndrewLevin** [comment]
Hi Seangchan,

Now there is both a low priority label and a medium priority label. Can you please remove the low priority label?

Thanks.

Andrew

**Comment by amaltaro** [comment]
I'd remove the medium... it does not affect any operations, it's simply a mistake from PPD side!

**Comment by AndrewLevin** [comment]
It does affect operations.When they make this mistake we need to debug what happened and then rerun workflows. I really think you should add the medium priority label back.

**Comment by ticoann** [comment]
Hi Andrew, the level of priority relative and we had to coordinate with other requirement. Actually, if there is alternative solution to handle the situation if goes lower level. We have to evaluate the issues for this month to define the priority. I know we have bad consequences when ops make mistake, however since this need to be done after reqmgr2 fixes are in I think we can set low for now, and move up higher when this can be applied.  Besides, Alan is development priority manager, so convince him if you really need something. :smile:

**Comment by AndrewLevin** [comment]
OK, I agree this should have low priority until request manager 2 is in production.

**Comment by vlimant** [comment]
Where was the change of parameter name advertised to requesters ?

**Comment by AndrewLevin** [comment]
Hi Jean-Roch,

This happened so long ago I don't remember. Maybe Alan remembers.

Andrew

**Comment by amaltaro** [comment]
And this kind of problems won't happen again since we have a stricter argument validation now.
