### ISSUE TITLE
please fix the lumi calculation in wmstats

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#4799]
We are seeing many workflows in wmstats with more than 100% for the lumi progress in the D view:

/SingleMu/CMSSW_7_0_0_pre4-SiStripCalZeroBias-PRE_62_V8_RelVal_mu2012D-v1/ALCARECO: event: 0.0%, lumi: 99.2%
/SingleMu/CMSSW_7_0_0_pre4-TkAlMinBias-PRE_62_V8_RelVal_mu2012D-v1/ALCARECO: event: 99.2%, lumi: 106.3%
/SingleMu/CMSSW_7_0_0_pre4-PRE_62_V8_RelVal_mu2012D-v1/DQM: event: 99.2%, lumi: 101.0%
/SingleMu/CMSSW_7_0_0_pre4-SiStripCalMinBias-PRE_62_V8_RelVal_mu2012D-v1/ALCARECO: event: 0.0%, lumi: 99.2%
/SingleMu/CMSSW_7_0_0_pre4-PRE_P62_V8_RelVal_mu2012D-v1/RAW: event: 99.4%, lumi: 106.5%
/SingleMu/CMSSW_7_0_0_pre4-PRE_62_V8_RelVal_mu2012D-v1/RECO: event: 99.2%, lumi: 106.3%

Since the event progress is less than 100%, it looks definitely like there is a bug in the lumi progress calculation.

Can you please check?

Thanks.

Andrew

**Comment by amaltaro** [comment]
Seangchan, this was one of the discussions this week. I'm bumping its priority :)

**Comment by ticoann** [comment]
duplicate #5486
