### ISSUE TITLE
rewrite CondorPlugIn for Condor 8 or upper version

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#4837]
take advantage of python bindings provided by Condor 8.
Possibly improve the performance and reduce the memory usage.

**Comment by amaltaro** [comment]
@ticoann PyCondorPlugin is out there. Still not fully stable, but major work done. How about we close this one?

**Comment by amaltaro** [comment]
ping

**Comment by hufnagel** [comment]
Isn't that what PyCondorPlugin is supposed to be ?

**Comment by tsarangi** [comment]
yes, and can we close this one !
