### ISSUE TITLE
Need new GFAL2 Stageout Plugin

### ISSUE THREAD

**Issue by chwissing** [dmwm/WMCore#4880]
The lcg-utils (based on GFAL) are being phased out in 2014 and are replaced by utilities based on GFAL2. The names of the tools as well as the APIs will change. Therefore we need to offer a successor of the srmv2-lcg stageout plugin.

Find some details about the WLCG plans in a presentation given during the recent GDB meeting:
http://indico.cern.ch/getFile.py/access?contribId=13&sessionId=2&resId=1&materialId=slides&confId=251192

Christoph ("CW")

**Comment by juztas** [comment]
@ericvaandering can you reopen and assign it to me? I will test this next week on T2_CH_CERN with WmAgent and CRAB3. Thanks

**Comment by ticoann** [comment]
Thanks Justas, let me know.

**Comment by ericvaandering** [comment]
@tsarangi was going to help with this testing too, right?

**Comment by juztas** [comment]
If T2_US_Wisconsin have gfal2 installed we can also test on this site. For sure T2_CH_CERN has and we need to specify own site-local-config  for this.

**Comment by tsarangi** [comment]
yes, gfal2 is available for compute nodes at Wisconsin.

**Comment by juztas** [comment]
it is tested with production and analysis and merged to official repo. @ticoann you can close this. Thanks

**Comment by amaltaro** [comment]
ping

**Comment by juztas** [comment]
do we need to test it more ? tested on BR_SPRACE, T3_US_Princeton_ARM, and T2_CH_CERN

**Comment by amaltaro** [comment]
If CRAB3 and SAM tests move first to gfal2, then I guess we don't need to test it in WMCore.
Otherwise, I think we still need to commission this new plugin for production, here I mean running at a bunch of sites (~5) and transferring data around (maybe also simulating some stage out failures).

Anyways, the plugin has been developed, so I think we can close this one.
