### ISSUE TITLE
TaskArchiver performance data upload to Dashboard fails

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#4896]
Not only does it fail, it prevents the TaskArchiver from cleaning up anything.

2013-12-21 09:01:54,932:INFO:TaskArchiverPoller:PromptReco_Run211684_MinimumBias has interesting performance information, trying to publish to DashBoard
2013-12-21 09:01:55,069:ERROR:TaskArchiverPoller:Couldn't upload summary for workflow PromptReco_Run211684_MinimumBias, will try again next time
Nothing will be deleted until the summary is in couch
Exception message: urlopen error [Errno -2] Name or service not known

I did not override the dashboardUrl, but even if the hardcoded value in the code was bad, the code should never fail in a way that it prevents the rest of the TaskArchiver from working, it should just skip the upload and move on.

Independently of this, I also need the ability to not upload performance data at all in replays, some of them I simply don't want to do it. Therefor in #4895 I changed the URL default to None and make it skip the upload in this case.

@samircury , you might want to take a look.

**Comment by amaltaro** [comment]
Since this issue is from 2013 and I didn't hear any problems back, closing this issue.
