### ISSUE TITLE
Why do these have differing numbers of jobs?

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#4913]
So ops has been assuming that blocks being closed late is the cause for not all blocks being processed in many recent rereco workflows.  I tried to track this down on one request:

pdmvserv_SUS-Summer12DR53X-00096_T1_DE_KIT_MSS_00114_v0__131216_083514_9476

Which went into completed state having processed only 21% of its input data.  Seemingly only knowing about 8 of the 54 blocks in the dataset.  Looking at when blocks closed though in DBS it looks like they were all closed at least a week before this workflow was submitted, which I would think means the blocks were actually OK.  Not seeing evidence of blocks being closed too late in this case.

This brings me to backfill then -- where we're essentially running the same request repeatedly.  Like:

dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131209_142247_6326  ( 33103 jobs created)
dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131209_050917_6371  (32791 jobs created)
dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131208_150803_72      (32814 jobs created)
dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131227_182356_5128  (2892 jobs created)
dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131214_200623_5782  (1567 jobs created)
dmason_Fall53_2011B_SingleElectron_Run2011B-v1_Prio1_5312p1_131211_215235_8545  (5419 jobs created)

Some minor fluctuation in number of jobs I suppose I could believe -- but those last 3 had quite a bit fewer jobs than the first.  These were all clones of the same workflow, with the same input dataset.  All have reached the "completed" state, the older ones having been manually closed out once they reached this state.

But why is the # jobs fluctuating here?  I see the input data is indeed still staged on DISK at RAL, so its not a case of something getting flushed off disk that I can tell.  Am suspecting a reqmgr issue here and guessing this and the SUS request problem above are related...  But maybe first things first -- why are the created jobs different in the backfill?  Shouldn't they always be ~the same?

**Comment by amaltaro** [comment]
@ticoann @DAMason so, should we close this issue?

**Comment by amaltaro** [comment]
ping

**Comment by ticoann** [comment]
Alan, I think we can close this. We haven't seen this since. we will reopen it when it happens.
