### ISSUE TITLE
implement more categorized retry options

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#4933]
along side with #4756,

From @amaltaro  suggestion
could we change the following line so make more categorized policy

config.ErrorHandler.maxRetries = 3
to a better retry policy, like
config.ErrorHandler.maxRetries = {'default' : 3, 'Harvesting' : 2, 'Merge' : 4, 'LogCollect' : 1, 'Cleanup' : 2}

**Comment by amaltaro** [comment]
This is in place for quite some time now :-) @ticoann please close it.
