### ISSUE TITLE
Workflows with Duplicate Lumi's 

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#4938]
We have a number of Redigi Workflows that are not closing out due to duplicate Lumi's in the output datasets.  Julian checked, and double checked the input datasets and they are clear.  We did not run any sort of ACDC or recovery on these workflows.  I have run out of ideas as to what may have happened or what our best course of action for recovery is on these.  I need a developer to look at them and try to figure it out and give us advice as to what to do.

is the ful e-log thread on this issue.  
https://cmslogbook.cern.ch/elog/Workflow+processing/12485

alahiff_BTV-Fall13dr-00050_T1_US_FNAL_MSS_00026_v0__140110_000836_4460
alahiff_BTV-Fall13dr-00052_T1_US_FNAL_MSS_00026_v0__140110_000857_3821
alahiff_BTV-Fall13dr-00053_T1_US_FNAL_MSS_00026_v0__140110_000908_6644
alahiff_BTV-Fall13dr-00054_T1_US_FNAL_MSS_00026_v0__140110_000918_809
alahiff_BTV-Fall13dr-00057_T1_US_FNAL_MSS_00026_v0__140110_000942_6330
pdmvserv_BTV-Fall13dr-00200_T1_US_FNAL_MSS_00055_v0_castor_tsg_131220_142050_3915
pdmvserv_BTV-Fall13dr-00200_T1_US_FNAL_MSS_00055_v0_castor_tsg_131220_142050_3915
pdmvserv_HIG-Fall13dr-00050_T1_FR_CCIN2P3_MSS_00019_v0_tsg_131219_010343_3987
pdmvserv_L1T-Fall13dr-00038_T1_US_FNAL_MSS_00015_v1_tsg_131219_004921_2006

**Comment by amaltaro** [comment]
@ticoann I guess we can close this issue. I believe these issues happened when we had 2 instances of GQ running in cmsweb.
