### ISSUE TITLE
CleanUp all the dbs2 and dls related code.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#4949]
remove dbs3UploadOnly flag
remove the sql set by the flog
remove DBSUpload, DBSBuffer package.
need to be careful since some of code used outside those packages (i.e. PhEDExInjector)

**Comment by ericvaandering** [comment]
Ticket #5225 is related

**Comment by alexanderrichards** [comment]
> remove dbs3UploadOnly flag
> remove the sql set by the flog
> remove DBSUpload, DBSBuffer package.
> need to be careful since some of code used outside those packages (i.e. PhEDExInjector)

@ticoann unless I'm mistaken it looks like at least the first two of these have been done already in:
[ clean up dbs3 configuration code #6003 ](https://github.com/dmwm/WMCore/pull/6003)
Which is merged. Did I miss something?

**Comment by alexanderrichards** [comment]
also whilst attempting to remove the DBSUpload I see reference to it in:
[dbsFix.py line 13](https://github.com/dmwm/WMCore/blob/master/etc/dbsFix.py#L13)

```python
from WMComponent.DBSUpload import DBSInterface
<snip>
newFiles.append(DBSInterface.createDBSFileFromBufferFile(localFile, processed))
```

Given that the DBSUpload package is never used, Is this file ever used or can it too be removed?

**Comment by amaltaro** [comment]
Alex, I think it's safe to remove dbsFix.py, it was made in 2010 and apparently never used (possible used at some point for Ops or DBS transition only..).

**Comment by alexanderrichards** [comment]
ok here's an interesting one. There are two references to DBSUpload package in the DBS3Buffer Package:

[WMComponent.DBS3Buffer.Oracle.LoadBlocksByDAS](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/Oracle/LoadBlocksByDAS.py#L11)
[WMComponent/DBS3Buffer.Oracle.SetDatasetAlgo](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/Oracle/SetDatasetAlgo.py#L12)

Are these files used at all? I would have assumed that these files would have wrapped their DBS3Buffer.MySQL equivalents as with the other Oracle ones?

**Comment by amaltaro** [comment]
... and that's why we want to get this DBS stuff cleaned up, it's a mess! :-(

LoadBlocksByDAS seems to be using the wrong package in Oracle. Checking those two classes, they are a bit different w.r.t. to the amount of arguments basically. 

I suggest you investigate a bit further and maybe run a test or two to make sure we won't break stuff.

**Comment by hufnagel** [comment]
Yes, any DAO use from the wrong package should be fixed. I am also not really sure if all the DAO we have in the right package are even used at all.

**Comment by alexanderrichards** [comment]
This is another right?
[WMComponent.DBS3Buffer.DBSBufferFile](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/DBSBufferFile.py#L264)

```python
        uploadFactory = DAOFactory(package = "WMComponent.DBSUpload.Database",
                                   logger = self.logger,
                                   dbinterface = self.dbi)
        setDatasetAlgoAction = uploadFactory(classname = "SetDatasetAlgo")
```

presumably this should be
```python
        uploadFactory = DAOFactory(package = "WMComponent.DBS3Buffer",
                                   logger = self.logger,
                                   dbinterface = self.dbi)
        setDatasetAlgoAction = uploadFactory(classname = "SetDatasetAlgo")
```
right?

**Comment by alexanderrichards** [comment]
another:
[WMComponent/DBS3Buffer/Oracle/AlgoDatasetAssoc.py
](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/Oracle/AlgoDatasetAssoc.py#L8)
