### ISSUE TITLE
add DBS upload flag  and PhEDEx inject flag

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#4971]
Agents need to propagate dbs upload information to wmstats/reqmgr closed and uploaded as well as PhEDEx status.
First we need to define what kind of information needs to be propagated.
1. i.e just flag saying there is not uploaded block in DBSBuffer or how many blocks not uploaded from the given workflow.
2. the same for PhEDEx.
3. Need to consider multiple agent handling the same request
4. close out script need to change to use this information

**Comment by amaltaro** [comment]
Seangchan, instead of this flag, I think we should work on this issue instead https://github.com/dmwm/WMCore/issues/8148 and synchronize workflow completion with dbs/phedex injection.

I'm closing this issue, but feel free to reopen it.
