### ISSUE TITLE
in Service/DBS when reading DBS3 make sure to skip invalid files

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#4994]
in DBS2 invalid files were ignored by default by the API, but this is not the case in DBS3. Need to check is_file_valid flag for.

Cfr:
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/7269/1/1/1/2.html
https://github.com/dmwm/CRAB2/issues/1036

**Comment by ericvaandering** [comment]
@belforte I think we can close this issue here in WMCore?

**Comment by belforte** [comment]
CLose,  because this is handled in the client (CRAB).

**Comment by ticoann** [comment]
Hi Stefano, actually this is handled in WMCore/Services/DBS/DBS3Reader.py as well. (Yuyi, provided validFileOnly flag)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L455

**Comment by belforte** [comment]
thank @ticoann , sorry I forgot that CRAB3 talks to DBS via WMCore. But I think this all OK now.,
