### ISSUE TITLE
Make replica tape subscription at 80% completion with override

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5048]
This was requested of WMAgent during the Disk/tape section of https://indico.cern.ch/event/293016/other-view?view=standard#2014-03-24

**Comment by DAMason** [comment]
Not sure about the discussion there, but think this should be tied to a state change -- i.e. the move to Announced rather than an arbitrary complete fraction.  Doesn't make sense to commit to tape until the dataset is actually announced for example, and often not even then ;)
