### ISSUE TITLE
Add 'warnings' to wmstats agent info view

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5060]
AgentInfo view at wmstats is currently showing green (everything ok) and red (error) for agent state. We need to add a new state: yellow for 'warning'. The warnings should include:
- disk alarms
- when an agent is in drain mode
- ? when data is not updated (Data collect error)

@julianbadillo do you think we could add more cases to the warning list?

**Comment by amaltaro** [comment]
I don't think it's possible unless we parse lots of strings/regexp.
Otherwise, we got the yellow warning state for 2 months now.
