### ISSUE TITLE
Workflows with missing lumis and events.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5105]
From Jen's report

I have 6 WF's that have 100% success in ACDC but are not at 100%
2:21
pdmvserv_TOP-Summer11LegDR-00007_T1_DE_KIT_MSS_00009_v0__140321_221220_5773     https://cmslogbook.cern.ch/elog/Workflow+processing/14240 stuck at 91% input dataset not complete though
2:22
pdmvserv_EXO-Spring14dr-00064_T1_IT_CNAF_MSS_00005_v0__140411_184916_2777       acdc successful but dbs still at only 89% https://cmslogbook.cern.ch/elog/Workflow+processing/14138
pdmvserv_B2G-Spring14dr-00008_T1_IT_CNAF_MSS_00007_v0__140412_002635_4233       acdc3 was successful but still at 92% 
pdmvserv_EXO-Summer12DR53X-02709_T1_UK_RAL_MSS_00155_v0__140218_123535_9079     https://cmslogbook.cern.ch/elog/Workflow+processing/14299 data is at 93% even though ACDC was 100% successful
2:22 pdmvserv_TSG-Spring14dr-00004_T1_UK_RAL_MSS_00022_v0__140418_082010_5778        100% successes but output is not in place after several days https://cmslogbook.cern.ch/elog/Workflow+processing/14097

**Comment by amaltaro** [comment]
I would close this issue unless we see it again. It's from may 2014... @ticoann
