### ISSUE TITLE
AgentNanny component should watch for expired certs

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#5119]
Well I'm assuming  you guys are going with my name for the component here ;)

But one of the things we need this to watch for the agents is that the certs it uses are not soon to expire & alarm when they get within some settable time (~week) of expiration.

**Comment by amaltaro** [comment]
@BrunoCoimbra I just discussed this issue with Seangchan and it looks a good kick off for you :-)
@ericvaandering please point something else if you prefer

**Comment by amaltaro** [comment]
It watches for the proxy expiration. We need to extend it to the service cert located in the node.
Should be a simple change now that the proxy part is done.
