### ISSUE TITLE
Not have workflow "completed" depend on things you can't ACDC

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#5126]
One of the things we end up waiting on in closing out workflows are "end of request" tasks like logCollect jobs.  Workflows will not go into complete status until those jobs -- which sometimes can last days, especially with retries, complete.  Were they to fail its not clear we could recover them since we don't have the option to ACDC them.  Can we have workflows reach the "completed" state once all ACDC'able tasks are complete?  At which point any remaining jobs are left to the wind anyway...

**Comment by amaltaro** [comment]
Workflow completion is now (actually for quite a long time now) independent of logcollect/cleanup jobs. Thus closing this issue as fixed
