### ISSUE TITLE
Where possible do not split lumis across multiple jobs

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#5181]
When doing lumi-based splitting, we may split a single lumi across multiple jobs if the input dataset was not created correctly.

After jobs are created for a job group, we should have a second pass where we confirm that no single lumi is in two jobs.  If it is, we should make sure that the lumi is removed from one job and any files containing that lumi are processed by the other job.

As long as these two actions are done, we should be guaranteed each lumi section is processed by at most one job in a job group.

If there are multiple job groups, a lumi may still be split across multiple jobs; this is because the lumi might be in file A / job group 1 and in file B / job group 2 where files A and B are not both present at any one site.

Hence, anything using lumi-based splitting should still try to detect overlapping lumis in jobs and warn appropriately.  This is especially relevant if you are trying to do lumi algebra (i.e., take the lumis processed by failed job X and use them as a lumi mask for a recovery task).

For 2012 primary datasets, we believe up to 1% of lumis are split across files.  We hope this algorithm will greatly reduce the number of situations where a lumi is split across multiple jobs.

**Comment by ericvaandering** [comment]
We should close this. The pull request was merged and is used where needed.

**Comment by amaltaro** [comment]
Happy to do so.
