### ISSUE TITLE
Jenkins needs to be tidier

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#5242]
Need to change the testing script to delete logs and stop/start couch and mysql processes before each run. They end up filling the root disk which blows things up

**Comment by ticoann** [comment]
@ericvaandering, Eric is doing whole Jenkins make over. should we close this?

**Comment by ericvaandering** [comment]
I'm basing what I'm doing on @PerilousApricot 's scripts, so these are OK notations to have.
