### ISSUE TITLE
add OriginalRequestName in cloned and extention workflow

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5257]
This is needed to track the parent relations between workflows

**Comment by amaltaro** [comment]
This script also needs to be updated:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/resubmit.py

as Seangchan and I discussed, OriginalRequestName will be a list of parent workflow names.

**Comment by amaltaro** [comment]
Updated Ops script according to my discussion with Dima. We only want the direct parent, see
https://github.com/CMSCompOps/WmAgentScripts/pull/114

**Comment by amaltaro** [comment]
@ticoann please close this one

**Comment by ticoann** [comment]
Thanks, Alan
