### ISSUE TITLE
Record the worker node hostname somewhere 

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#5327]
Been several cases where we've tried to debug problems that having the worker node name that the job ran on would be useful -- i.e. for things like tracking down black hole nodes, seeing if workers or groups of workers were misconfigured, etc.  Doesn't seem to be a reliable place that this is recorded -- could we add a line or two to record `uname -a` somewhere like the FJR?

**Comment by amaltaro** [comment]
This is part of the meta-data sent to WMArchive. This information is also recorded in the condor logs. If you feel like it should be present somewhere else, please reopen this issue.
