### ISSUE TITLE
Use PNN form of listFileBlockLocation

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5339]
1. listFileBlockLocation: make phedexNode flag to True. 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L508 

2. need to find what breaks (there are 69 places it uses this call)
i.e.) 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L188

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataLocationMapper.py#L137

**Comment by alexanderrichards** [comment]
@ticoann PNN patch merged so this can be closed
