### ISSUE TITLE
Use WMCore/SiteDB PNN to PSN Api

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5341]
switch all the calls (including unittest), so we can check it is replaceable. 
phEDExNodetocmsName
to 
PNNtoPSN

**Comment by alexanderrichards** [comment]
patch superseded by  #5592

**Comment by alexanderrichards** [comment]
@ticoann PNN patch merged so this can be closed right?

**Comment by ericvaandering** [comment]
Go ahead and close all the PNN issues assuming your patch takes care of them. If not, I probably entered things that did not have to happen.

**Comment by ticoann** [comment]
Thanks Alex, yes please close all the issues your big patch covers.
