### ISSUE TITLE
Fill PNN in origin_site_name

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5346]

**Comment by belforte** [comment]
if this issue means :
write T2_CH_CERN in place of srm-eos.cern.ch as site_origin_name in DBS
this is not done yet in current WMA released used in production
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/943/1/1/1/1.html

**Comment by alexanderrichards** [comment]
@ticoann this can be closed now right?
