### ISSUE TITLE
more timestamps in stageout code

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5364]
Hi,

You can see here:

http://cms-project-relval.web.cern.ch/cms-project-relval/forELOG25Sep2014/

an example of a job that seems to have taken 15 hours to stage out its log file and its root file. However, 
there are not enough timestamps printed out in the stage out code to have any idea what the problem.

Can the developers please add more timestamps e.g. at least one here immediately before and after each stage out.

Thanks.

Andrew

**Comment by amaltaro** [comment]
The stage out code has much more timestamp now (since 2015). So I'm closing this issue
