### ISSUE TITLE
move to cmssw python?

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5372]
We found here

https://hypernews.cern.ch/HyperNews/CMS/get/relval/3158/2.html

that the setup of the CMSSW pset failed when importlib was used, because we are using python2.6 which does not have this library. Maybe we should consider moving to the CMSSW python version?

**Comment by hufnagel** [comment]
@tiocann, after my changes and than Alans revisions on top of these changes, this is done now, isn't it ?

**Comment by ticoann** [comment]
yes, thanks
