### ISSUE TITLE
tasks with multiple steps can ask for the wrong number of cores in jdl

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#5420]
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobCreator/JobCreatorPoller.py#L561

calls wmTask.steps(), which when you look at

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMTask.py#L177

returns the settings for the *top* step only. Which means if you have two CMSSW steps in your task and the first runs single core and the second multicore, you only request a single core job slot.

If you think that is hypothetical, it's the reason my Tier0 replay just failed with jobs running out of memory. Express runs in a two step process, first repacking (which can only use a single core) and then express reco, where we want multiple cores.

Now, we could say that in a multi-step tasks we assign all steps the same number of cores. After all, they have them anyways, whether they use them or not. It's the same payload on the grid/cloud/batch.

There might be steps though that simply cannot be run in multi-threaded mode or run slower in multi-threaded mode. If we want to support assigning different number of cores to different steps for multi-step tasks, we need to change this code in JobCreatorPoller to loop over all steps and use the highest number of cores.

**Comment by ericvaandering** [comment]
This is related to TaskChain that I think @amaltaro has some thoughts on too.

So I guess we need to expand this in two more flexible ways?

1) Multiple executions of CMSSW within the same job may need different #'s of cores (and it's a given we will be "wasting" resources if we do this)
2) Different jobs submitted from a TaskChain need the ability to have different #'s cores (to avoid wasting resources)

@ticoann we should prioritize this

**Comment by ericvaandering** [comment]
@hufnagel where is the hack that you used to get around this? I'll shortly have a simple patch that does what you want. I don't have a way to construct a workflow with steps with different core counts though. Maybe that's OK.

**Comment by amaltaro** [comment]
The only difference between Dirk's case (multi-step task/job) and TaskChain is that the latter creates a different job per task. In addition to what Eric said:
 a) for multi-step task, we could simply get max(cores) for the different steps
 b) for taskChain, use number of cores provided for each task (or read the one from the main dict)

**Comment by ericvaandering** [comment]
@amaltaro the task chain case (for RelVals at least) should be fixed by #5754

**Comment by hufnagel** [comment]
@ericvaandering , I added an optional parameter useMulticore

https://github.com/hufnagel/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L231

which can be overridden when constructing your tasks in the real specs by calling setupProcessingTask. Express/PrompReco override this for the AlcaSkim task for instance, which shouldn't use multicore, but goes through the setupProcessingTask.

If you look at what setupProcessingTask does, it creates processing task with one step. So you could use this to override that step. For a multi-step task you then anyways have to add the other steps yourself, you can do whatever you want then with the multicore settings.

PS: Two step Express (repack/reco) is actually not forcing repack to run singlecore. It effectively does of course, but that is because of the framework itself, not any settings we make. I said something else to the contrary a few times, but I remember now that I left it like this.
