### ISSUE TITLE
Handling very long Skims wfs in WMAgent (> 6 months)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5426]
Creating this issue so we can have some brainstorm on how to handle workflows that should stay running open in the system for several months (maybe even more than a year). For reference, the original thread started here
https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/5706.html

Summary of what they are asking for:
 - workflow that has as input dataset and output dset from Tier0, which means new blocks will be created basically every day during the whole year
 - this means the workflow *must* be in "running-open" for the whole year, or even more if they want to
 - this workflow should move to "running-closed" *only* when ppd/offline asks us to do so

What do we have right now to handle them:
 - "OpenRunningTimeout": finite value in seconds that the workflow should stay running-open.
 - when ppd wants to complete the workflow, we need to update the couchdb document in "workqueue_inbox" and change "OpenForNewData" to false. It'll make the wf to go to "running-close".

Things to be discussed:
 - (not super important) what if they set OpenRunningTimeout to a value smaller than they had foreseen? I guess we can update some other couch document/request spec file
 - the team name must be alive throughout the life of these requests, in principle we could set an agent with 2 names if we make changes in central production.
 - recovery workflows. Would we be able to run ACDC wfs while the original one is running?
 - redeployment of agents. How do we guarantee that a drained agent has run all the jobs belonging to that wf? Especially auxiliary jobs (merge, logcollect, etc) which depends on other triggers. We probably need a way to force these jobs to be created and run in a specific agent.

That's all that comes to my mind. Feel free to add more things in case I've forgotten.
BTW, please let's try to keep it as simple as possible. Thanks

**Comment by amaltaro** [comment]
I'd not mark it as high prio since it's not clear to me whether it's going to be handled by CompOps or T0 folks in the end. Maybe @hufnagel and @ericvaandering have something to add.

If I'm not wrong, @lucacopa was going to run a replay to test some changes that @vlimant would provide him, though I don't know the current status.

**Comment by ericvaandering** [comment]
Yes. @hufnagel and I were discussing this over pre-dinner drinks... I'd say it's still under discussion.

**Comment by ticoann** [comment]
Move the milestone to 1506 for now

**Comment by ticoann** [comment]
Alan, are we still doing this?

**Comment by amaltaro** [comment]
Tier0 is handling these long skim workflows, I guess we can close it.
