### ISSUE TITLE
The resource estimate bits in the jdl seems to be a really bad idea...

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#5431]
Does anybody understand why we ever did this?

https://github.com/dmwm/WMCore/commit/69430f8ff179dea01a66b7082f0d51a9e73a5a6b

The effect seems to be that these variables in the jdl are essentially random numbers, which we end up having to blur away to be able to match jobs -- today's example:

https://cms-logbook.cern.ch/elog/GlideInWMS/778

A very good description of what the effect of these are:

"WMAgent is setting the RequestDisk and MaxWallTimeMins at the KB and minute-level granularity, respectively.  This caused there to be about 3k auto-clusters.  Because none of the first 100-or-so jobs did not match, the negotiator ran out of time to talk to the schedd and moved on.  I suspect the reason 
cmsgwms-submit1.fnal.gov works at all is pure luck."

I.e. this very much seems to have been a fix for a problem that didn't actually exist that I could tell, and instead causes bigger ones.  We seem to discover this every year or so and hammer away through condor magic.  Can instead just not do this in the first place?

**Comment by amaltaro** [comment]
Resource estimates are in the system for a few months now. Should we close this ticket?
