### ISSUE TITLE
Report number of cores to dashboard

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5437]
In order to properly calculate the CPU efficiency for multicore jobs, WMAgent needs to report number of cores to dashboard (this information is not available in the FJR at the moment).
Here is the message from Antonio Perez
```
from Julia's answer in the other thread ( https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/647/1.html )
it seems WMAgent reports TotalJobTime and TotalJobCPU. To allow the dashboard to correctly
calculate the CPU efficiency, we would need to add the number of cores to the report and coordinate
the change in the dashboard side.  
```

**Comment by ericvaandering** [comment]
Per discussion in https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/647/1/1/2/1/2.html and the rest of the thread, add NCores to the packet as suggested by Julia. Don't require this number to be reported by CMSSW.
