### ISSUE TITLE
Tier0 WMStats pending features 

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5449]
Request for the new tier0 WMStats monitor - so far:
- Add Request Alert 'Check bookkeeping' for Runs that are standing in 'Active' status for more than 24 hours 
- Show total number of events (not average), for AlcaSkim jobs
- Make the 'search' tab to actually work
- Add an option to search WorkloadSummary by run number
- don't clean up old workflows once they go into complete. We want some kind of timeout, best would be to cleanup groups of requests by run. (#5563)

**Comment by ticoann** [comment]
@hufnagel, @lucacopa Can we close this issue?

**Comment by lucacopa** [comment]
@ticoann some of the features are still pending, I think we can keep:
- Add Request Alert 'Check bookkeeping' for Runs that are standing in 'Active' status for more than 24 hours
- search tab: Add an option to search by run number
