### ISSUE TITLE
Setting back workflow status from completed due to race conditions

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5451]
Some tier0 workflows status is changed from completed to a previous status. 
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?t0_request/PromptReco_Run228979_Cosmics
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?t0_request/Express_Run228911_StreamExpressCosmics
There might be a race condition, we could create a forward transition constraint so a workflow cannot come back from completed status

**Comment by ticoann** [comment]
Fixed
