### ISSUE TITLE
New workflow type for DQM aggregation

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5468]
This was discussed and promised in the PPD meeting today. Inputs would be DQM dataset to run over and a LumiList in JSON representation (probably easier than dealing with a list of runs which is the actual requirement).

The workflow would perhaps just submit a single job that added up all the DQM info for all those runs and then uploaded the results to the DQM server.

@ticoann @hufnagel correct me if I got anything wrong or incomplete.

**Comment by ericvaandering** [comment]
Any update here?

**Comment by ticoann** [comment]
It is in the testbed now but needs testing which requires agent update. We are doing other validation test currently which Alan found some bugs, so I don't think it will be validate on time. (I am expecting there will be bugs).

**Comment by amaltaro** [comment]
Fixed by #5911 . I think we can close this one
