### ISSUE TITLE
E-log entry for workflows

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5473]
Coming from the WMAgent review we agreed to provide a way to link from a workflow to a URL, presumably a link to an e-Log. We said WMStats, but maybe ReqMgr is the more appropriate place to store (if not display) it. 

What do we need to do to implement this?

**Comment by ericvaandering** [comment]
Isn't this superseded by LogDB? @ticoann @vkuznet

**Comment by vkuznet** [comment]
I think so, once LogDB in place they can start using it, but we need to discuss how they'll make updates (either in code or external client).
