### ISSUE TITLE
WFs in failed and running jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5487]
As reported in this elog
https://cms-logbook.cern.ch/elog/Workflow+processing/17855

that workflow was assigned, went into acquired status and the to failed. Even so, it had plenty of success jobs and etc. We should investigate what's causing this.

**Comment by vlimant** [comment]
adding

https://cms-logbook.cern.ch/elog/Workflow+processing/24392
https://cms-logbook.cern.ch/elog/Workflow+processing/24419

**Comment by amaltaro** [comment]
Issue fixed for almost half an year, I think
