### ISSUE TITLE
PyCondorPlugin error 

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5507]
Message: Unhandled exception while calling update method for plugin PyCondorPlugin
Failed to fetch ads from schedd

**Comment by tsarangi** [comment]
@ticoann 
Check these changes. Let me know if they look OK to you, especially whether you want to put these in error or debug messages !
https://github.com/tsarangi/WMCore/commit/6bc3c5b022707ba370d1d5ea0917c44fd8077c44

**Comment by tsarangi** [comment]
@ticoann 
Can you check this one please ? https://github.com/tsarangi/WMCore/commit/b6caccdc6eacab230e010a36e140a11c6d1c53d7
