### ISSUE TITLE
Error when moving a site to normal in resource control

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5518]
Before I forget, when setting a site status from "down" to "normal", I get this error:

```
[cmsdataops@cmssrv214 current]$ $manage execute-agent wmagent-resource-control --site-name=T3_US_NERSC --normal
Executing wmagent-resource-control --site-name=T3_US_NERSC --normal ...
Configuration Warning "/etc/condor/condor_config", Line 1291: obsolete use of ':' for parameter assignment at RunBenchmarks : (LastBenchmark == 0 ) || ($(BenchmarkTimer) >= (4 * $(HOUR)))
ERROR:root:Not able to find WMAgent jobs
[cmsdataops@cmssrv214 current]$ 
```

But actually the site status is changed in resource-control. There are several other issues related to resource control as well.

Please, don't get mad at me, I promise to create more patches/fixes than issues in 2015 :-)

**Comment by ericvaandering** [comment]
"Please, don't get mad at me, I promise to create more patches/fixes than issues in 2015 :-)" 

How do you think that's going? :-)

**Comment by amaltaro** [comment]
Just gave it a try in 1.0.9.pre9 and it still complains, though it's different now:
```
cmst1@vocms0224:/data/srv/wmagent/current $ $manage execute-agent wmagent-resource-control --site-name=T2_PL_Warsaw --down
Executing wmagent-resource-control --site-name=T2_PL_Warsaw --down ...
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method CondorPlugin.__del__ of <WMCore.BossAir.Plugins.CondorPlugin.CondorPlugin instance at 0x14e4290>> ignored
cmst1@vocms0224:/data/srv/wmagent/current $
```
I was hoping it would fix itself :-) I think I know more or less where it breaks. Feel free to assign it to me

**Comment by ticoann** [comment]
> "Please, don't get mad at me, I promise to create more patches/fixes than issues in 2015 :-)"
> 
> How do you think that's going? :-)

Alan closed more issues than what I closed past five years. :-)

**Comment by ericvaandering** [comment]
Yeah Alan, I wasn't asking about this issue, just came across it while searching.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Sep 3, 2015, at 16:38, ticoann <notifications@github.com<mailto:notifications@github.com>> wrote:


"Please, don't get mad at me, I promise to create more patches/fixes than issues in 2015 :-)"

How do you think that's going? :-)

Alan closed more issues than what I closed past five years. :-)

**Comment by amaltaro** [comment]
I may be "neutral" at this point, but that just because some issues I'm registering in my mind only :P
