### ISSUE TITLE
DB deadlock in PhEDExInjector

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5577]
Another DB deadlock (I may be wrong, but it seems it happens only in MariaDB) but now in another component (PhEDExInjector).

I'm pasting here the backtrace provided by Ian
```
[cmsdataops@cmssrv217 current]$ tail -100 
/data/srv/wmagent/current/install/wmagent/PhEDExInjector/ComponentLog
2015-01-20 05:07:47,467:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.PhEDExInjector.PhEDExInjectorPoller.PhEDExInjectorPoller instance at 0x3399878> 
(OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') 'UPDATE 
dbsbuffer_file SET in_phedex = %s WHERE lfn = %s' [(1, 
'/store/mc/Summer12/TT_weights_CT10_TuneCUETP8M1_8TeV-powheg-pythia8/GEN-SIM/START53_V7C-v1/20001/B46BB726-
8FA0-E411-A61B-002590747E14.root'), (1, '/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-
pythia8/GEN-SIM/BACKFILL-v77/20001/5276BD14-8EA0-E411-AA3D-002590747E28.root'), (1, 
'/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-pythia8/GEN-SIM/BACKFILL-v77/20001/7630DC35-
8EA0-E411-AD57-00259073E3D0.root'), (1, '/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-
pythia8/GEN-SIM/BACKFILL-v77/20001/C2D53B2A-8FA0-E411-9071-00259073E526.root'), (1, 
'/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-pythia8/GEN-SIM/BACKFILL-v77/20001/42F2772E-
8FA0-E411-8788-002590747E28.root'), (1, '/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-
pythia8/GEN-SIM/BACKFILL-v77/20001/02D2C9D7-8FA0-E411-AF92-002590747E28.root'), (1, 
'/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-pythia8/GEN-SIM/BACKFILL-v77/20001/0EA8BE07-
8EA0-E411-8BE9-002590747E14.root'), (1, '/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-
pythia8/GEN-SIM/BACKFILL-v77/20001/16925510-8EA0-E411-A532-00259073E526.root')]  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 172, in __call__
    self.algorithm(parameters)
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py", line 368, in algorithm
    self.injectFiles()
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py", line 246, in injectFiles
    transaction = myThread.transaction)
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMComponent/DBS3Buffer/MySQL/DBSBufferFiles/SetPhEDExStatus.py", line 25, in execute
    transaction = transaction)
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMCore/Database/MySQLCore.py", line 140, in executemanybinds
    returnCursor)
  File 
"/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch2/lib/python2.6/si
te-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1116, in 
_handle_dbapi_exception
    exc_info
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.0.0.patch2/sw.pre.amaltaro/slc6_amd64_gcc481/external/py2-
sqlalchemy/0.9.6/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 924, in _execute_context
    context)
```

@yuyiguo , can you help me setting up and debugging this issue as well? This one I have no idea
how to reproduce... :-(

**Comment by yuyiguo** [comment]
Alan:
cmssrv* are fnal nodes. What backend DB PhEDExInjector is using? Without properly setting the deadlock log system, I just don't know how to find anything useful to help the debug. -:(

**Comment by amaltaro** [comment]
That's why I asked you to help me to setup it :-)
It's MariaDB, I just asked Julian and Andrew and in principle we do not see this issue in oracle backends. I'm redeploying cmssrv113 agent right now to run the cmsweb-testbed usual validation, do you want to setup MariaDB debugging level there?

**Comment by yuyiguo** [comment]
Alan:
I am very busy on cmsweb Feb release. New bugs founded:-(.
I wrote how to setup Maria DB for the error log in the other deadlock issue. Anyone can follow it to setup. If everything goes well for me, I will have time Friday.

**Comment by amaltaro** [comment]
Ok, don't worry :-) I'll take a look at the other thread (for some reason I thought there was some piece missing there...). Thanks!

**Comment by amaltaro** [comment]
Luck that we had the previous my.cnf configuration there. Pasting the config changes here for future reference (applied to cmssrv113):
```
[cmsdataops@cmssrv113 current]$ diff -rup config/mysql/my.cnf{.bkp,}
--- config/mysql/my.cnf.bkp	2015-01-21 13:49:45.803188171 -0600
+++ config/mysql/my.cnf	2015-01-21 13:55:25.765711438 -0600
@@ -8,7 +8,6 @@ connect_timeout = 60
 innodb_log_file_size=512M
 innodb_log_buffer_size=8M
 innodb_buffer_pool_size=2G
-innodb_additional_mem_pool_size=50M
 #set-variable = transaction-isolation = READ-COMMITTED
 binlog_format=row
 
@@ -30,9 +29,8 @@ innodb_concurrency_tickets=10000
 innodb_commit_concurrency=0
 innodb_flush_method=O_DIRECT
 innodb_file_io_threads = 4
-innodb_checksums=0
 innodb_doublewrite=0
-innodb_locks_unsafe_for_binlog = true
+innodb_print_all_deadlocks=1
 
 max_heap_table_size=2048M
 tmp_table_size=2048M
@@ -43,6 +41,17 @@ innodb_sync_spin_loops=60
 innodb_force_recovery = 0
 innodb_lock_wait_timeout = 100
 
+# enabling deadlock debugging mode, innodb plugin
+ignore_builtin_innodb
+plugin-load=ha_innodb.so 
+#innodb_additional_mem_pool_size=50M
+#innodb_checksums=0
+innodb_checksum_algorithm=NONE
+#innodb_locks_unsafe_for_binlog = true
+transaction-isolation = READ-COMMITTED
+innodb_print_all_deadlocks=1
+autocommit=0
+
 [mysql.server]
 STRICT_TRANS_TABLES=1
 transaction-isolation = READ-COMMITTED
```

**Comment by amaltaro** [comment]
This has been happening more often now in FNAL nodes, so I have just enabled these configurations in submit1. I'll ping you in case this crash happens again.

**Comment by amaltaro** [comment]
@yuyiguo , we got another deadlock in submit1. Can you take a look at the MariaDB logs and try to find out something useful there? I'll ask the WF team not to restart that component until you give us the green light.

**Comment by yuyiguo** [comment]
Did you mean  node cmsgwms-submit1?

**Comment by yuyiguo** [comment]
Here is what I found regrading the deadlock on cmsgwms-submiut1:
1. This node had 4 or 5 same deadlocks since this morning to now (3:07pm).
2. The deadlock DMLs are:
 Tx1: UPDATE dbsbuffer_file SET in_phedex = 1 WHERE lfn = '/store/mc/RunIIFall14GSBackfill/MinBias_TuneCUETP8M1_13TeV-pythia8/GEN-SIM/BACKFILL-v20/10004/C0F7A333-70B0-E411-81A5-0025904E239C.root'
Tx2: UPDATE dbsbuffer_file SET status = 'InDBS'
             WHERE block_id = (SELECT id FROM dbsbuffer_block WHERE blockname = '/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIFall14GSBackfill-BACKFILL-v20/GEN-SIM#9a80c03e-b086-11e4-80e9-a0369f23d01e')
3. Tx tables were reset when the rollback happens. No info from there. MariaDB error log has most of info. However, this info did not really help either. Because MariaDB provided only 1st ~30 characters of an columns where a lock hold, but we have very similar lfn names in a deadlock. The only difference are the last part of the lfn.
4, The deadlock happened inside the same table. Tx1 updated 50 rows and Tx2 updated about 5 rows in the same table. Tx2 hold the X lock needed by Tx1 at the same time waiting for another lock.
5. in the log only 10 of the 50 binded varables print out. Could someone modify the code on cmsgwms-submiut1 to log every bind variables for these two DMLs. 
6. all the locks here are row lock. So schema looks OK.

**Comment by amaltaro** [comment]
Yuyi, I could not find where to print all the binded variables by just having a quick look at the code.
Do you really need to have it? There are several deadlocks happening with less than 10 files, so there you have the full logs and variables.

**Comment by yuyiguo** [comment]
Alan, We had so many deadlocks yesterday. All the ones I saw had more than 10 bind variables. Could you pointed out at which node, when and which component the deadlock had less than 10 bind variables?  

It looks to me MariaDB gets locks row by row when multiple binding variables provided. However, Oracle does one lock for all rows.

**Comment by amaltaro** [comment]
The component is PhEDExInjector in cmsgwms-submit1 node.
A few timestamps with less than 10 binded variables:
2015-02-10 04:26:42,704
2015-02-09 22:23:07,514
2015-02-09 14:33:06,913

In case you want to take a look at this component log, you'll find it here:
/data/srv/wmagent/current/install/wmagent/PhEDExInjector/ComponentLog

**Comment by amaltaro** [comment]
Since we've redeployed cmsgwms-submit1, I have just pushed these MariaDB changes to that node again and restarted services.

**Comment by amaltaro** [comment]
It seems we got rid of this issue with the refactoring made by Dirk to PhEDExInjector component.
Thus I'm closing this issue
