### ISSUE TITLE
[Testbed validation] Error during ACDC submission

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5583]
Hi @ticoann ,
I've just found an issue in cmsweb-testbed ReqMgr. I was trying to create an ACDC workflow and
when I hit "submit" button a pop-up comes out with this message:
{"exception": 400, "message": "Create request failed, 'ResubmissionWorkloadFactory' object has no attribute 'requestName'", "type": "HTTPError"}

It seems we've removed this attr in the later releases and I believe the error is in this line:
https://github.com/dmwm/WMCore/blob/61be1750aadabae7c14c14246e732d5ac5b74de4/src/python/WMCore/WMSpec/StdSpecs/Resubmission.py#L35

shouldn't it be originalRequestName?
Thanks

**Comment by ticoann** [comment]
Hi Alan, actually code in testbed is this one. 
https://github.com/dmwm/WMCore/blob/1.0.3.pre10/src/python/WMCore/WMSpec/StdSpecs/Resubmission.py

It seems the error is on the validation, it looks like validation code ran before request name is created. 
How do you create the ACDC? are you using wmstats interface or script?
Could you send me the command you are running to create ACDC?

**Comment by amaltaro** [comment]
I'm using WMStats, you can try creating ACDC for this one (testbed):
amaltaro_700_pre11_ZJetsLNu_LHE_v1_150121_162739_7178

**Comment by ticoann** [comment]
Hi Alan, I was able to test the fix. It seems it is at least creating the workflow. Thank you for all your help.
I will create the new tag and request the testbed update. Is there anything else need to be updated.
I set the latest version on https://reqmgr2-dev.cern.ch/
