### ISSUE TITLE
WMAgent creating jobs for invalid files

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5589]
Andrew Lahiff reported today that jobs are created for invalid/non-existent files in the pileup sample.
The example was for this file:
/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root

where we can see marked as invalid in DBS [1] and non-existent (probably deleted) in TMDB/PhEDEx [2].

We need to enforce WMAgent not to create jobs (both primary and secondary source) jobs for invalid files.

[1]
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?logical_file_name=/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root&detail=True

[2]
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/data?file=/store/mc/TP2023SHCALGS/MinBias_TuneZ2star_14TeV-pythia6/GEN-SIM/DES23_62_V1-v1/20000/4EA851D4-776C-E411-9D45-842B2B186684.root

**Comment by amaltaro** [comment]
@ticoann , I'm cooking something and I'll ask you to take a look at it soon this evening

**Comment by amaltaro** [comment]
I drafted this fix amaltaro@9570df4d4d4d . Then when listing files it only returns a list of valid ones.

**Comment by ticoann** [comment]
@yuyiguo, ccing Yuyi, I though by default dbs only returns valid files. (Is it only in dataset level). I wonder how we get invalid file at the first place.

**Comment by yuyiguo** [comment]
DBS returns all files. you can use detail=1 to check the is_file_valid= 1 or 0 if you want to know if the file is valid or not.

**Comment by ticoann** [comment]
Thanks Yuyi, so there is no api option to get only valid files? In that case, Alan, the patch looks good.
 src/python/WMComponent/DBSUpload/DBSInterface.py doesn't have to be updated though. We need to remove that package.

**Comment by amaltaro** [comment]
Ok, I'll roll back my changes in DBSInterface then.
I still need to test it though and maybe also update some unit tests. Will try to do so tomorrow :-)
