### ISSUE TITLE
Workflow creation and rejection rights

### ISSUE THREAD

**Issue by drkovalskyi** [dmwm/WMCore#5607]
Dear Developers,

it looks like currently people who can inject new workflows not always have rights to reject them. This leads to a situation that we need to clean up bad requests ourselves. It's better if the person who makes a mistake can fix it himself. It can be a potential issue if we want to remove a manual handshake between PPD and Computing.

Dima

**Comment by DAMason** [comment]
Provided the workflow has not been assigned, after which point control of the workflow has to change hands to ops.

**Comment by julianbadillo** [comment]
Adding to this discussion:
ReqMgr doesn't allow to create ACDC's when an user is registered to DATAOPS but not to PPD group.
In that case we get:
400 Bad Request
Create request failed, (400, 'Error in Request check-in: RequestCheckInError
Message: Error creating new request:
User mcremone is not a member of group ppd
User is associated to groups: ['DATAOPS']
\tModuleName : WMCore.RequestManager.RequestMaker.CheckIn
\tMethodName : checkIn
