### ISSUE TITLE
remove reqmgr dependency

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5619]
1. resubmission WMStats.Ajax.js "/reqmgr/reqMgr/request" need to be replaced.
2. replace WorkQueueReqMgrInterface to reqmgr call (get calls need to be replace to reqmgr2 call, put calls need more caution to support both reqmgr and reqmgr2)

**Comment by amaltaro** [comment]
@ticoann wasn't it done already? If so, please close the issue.
