### ISSUE TITLE
Erlang view for wmstats and reqmgr

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5626]
views under here can be converted to Erlang view.
https://github.com/dmwm/WMCore/tree/master/src/couchapps/ReqMgr/views
https://github.com/dmwm/WMCore/tree/master/src/couchapps/WMStats/views

Some of view are created
https://github.com/dmwm/WMCore/tree/master/src/couchapps/WMStatsErl/views

Some are removed for clean up. but replaced by request mgr view.  They might be directly used for ReqMgr/views 
https://github.com/dmwm/WMCore/pull/5609/files

WMStats view     ReqMgr view
requestByDate -> bydate
requestByInputDataset -> byinputdataset
requestByOutputDataset -> byoutputdataset
requestByPrepID -> byprepid

**Comment by vkuznet** [comment]
Seangchan,
I want to clarify the details. I see that on production node there are more
Erlang views then in master branch, e.g. requestByPrepID. Does it means that
those were removed completely. Here is what I see from current master branch:

ls src/couchapps/WMStats/views/
agentInfo            jobsByStatusWorkflow latestRequest        requestHistory
cooledoffRequests    latestAgentSite      requestAgentUrl      time

ls src/couchapps/WMStatsErl/views/
agentInfo      requestHistory

I would guess that I only need to take care of those views which are located
in WMSTats/views area and not present in WMStatsErl/views.


Best,
Valentin

**Comment by ticoann** [comment]
Hi Valentin,
Yes that is correct. Also some of the views removed are replaced by reqmgr 
https://github.com/dmwm/WMCore/tree/master/src/couchapps/ReqMgr/views
> requestByDate -> bydate
> requestByInputDataset -> byinputdataset
> requestByOutputDataset -> byoutputdataset
> requestByPrepID -> byprepid

Eventually, all the reqmgr view need to switch to Erlang. However, as I mentioned I am not sure how critical this is since we are using SSD and I am planing to add server side cache. So I will put this in minor priority and only work on when you have nothing else to do. Thanks,
