### ISSUE TITLE
redo abort and force complete procedure.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5631]
When workflow is aborted it calls killWorkflow call in WMBSHelper.py
This would take forever if a lot of jobs need to be killed.
There are 3 bottle necks.
1. It updates all the couch job status to killed but couch doesn't do bulk updates so for each job it creates new http call.
2. dashboard status do the same.
3. I am not sure why db status update occurs by job instead of bulk of jobs but it seems that way as well.

Solution is
1. we don't have to update couch status or dashboard status since this will be all cleanup eventually when workflow status changed to completed or aborted.
2. We need to treat differently for force complete and aborted status in terms of killing log collect jobs.
  (force complete -> don't kill log collect job, abort -> kill all the log collect job as well) - In both cases keep the cleanup job running.

**Comment by ticoann** [comment]
@amaltaro, @julianbadillo, Alan, Julian, what do you think?

**Comment by amaltaro** [comment]
That sounds right, though I still have a couple of comments:
 - both force-complete and abort will not kill clean up jobs. So these jobs may be created and run even after the workflow moves to complete and a workloadSummary doc is created, right?
 - for the force-complete case, I would say it would be interesting to also allow (and create) Harvesting jobs. However, we usually don't have automatic harvesting in the current production workflows, besides RelVal ones.
 - for force-complete, of course we would like to get a workloadSummary in the end.
 - for aborted, we really do NOT care about anything, we just need to kill the workflow. So workloadSummary and anything else is not wanted.

**Comment by julianbadillo** [comment]
Nothing to add, just second the point:
Aborted -> we don't care (kill everything but cleanups)
Force-completed -> we need it urgently (kill prod jobs, move to complete but logcollects and harvesting keep running)

**Comment by amaltaro** [comment]
the force-complete part has been done and pushed to production in the previous week.
the aborted transition already works as expected, no?

**Comment by ticoann** [comment]
Aborted still creates clean up log collect job.

**Comment by vlimant** [comment]
I am not sure we even need the logcollect when force-completing (at least for the remainder), as we usually do force-complete when we know it's good to go and we want it out.

that's another discussion on logcollect, we should keep the logs only of the failing jobs, and randomly picking 1% of the succeeding jobs : those are IMO the only use case for logs

**Comment by ticoann** [comment]
Closing this.  
first one is added. Couch updated will be skipped when there are more than 100 jobs are killed.

https://github.com/dmwm/WMCore/commit/626273f7ba6a52ab1ca231838ecd48cf7d8423b8#diff-af5cb316c0b66783a9f738da4bc8c83aR122

Second issue, we are not counting clean up  and log collect job in complete state transition any more
