### ISSUE TITLE
Remove calculation of checksums other than adler32

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5632]
If I understand the CompOps notes from today correctly, we are OK to do this from the site side. @hufnagel anything to add?

**Comment by ericvaandering** [comment]
Actually we are going to wait a month before putting this in production, but that doesn't mean we can't change the code now. @ticoann can you assign this and put it on the March work plan?

**Comment by ericvaandering** [comment]
OK, we are fully cleared to do this, just don't deploy it before May 1. I think that should not be an issue.

**Comment by hufnagel** [comment]
Is there actually code for this already ?

**Comment by ericvaandering** [comment]
No, I believe no one has started to work on this. If you want it, take the ticket.

**Comment by hufnagel** [comment]
Taking it, already running tests. Not completely trivial as some couchapp code is also affected.

**Comment by hufnagel** [comment]
Ok, since the CRC checksum is mandatory in DBS for now, I reviewed this again and I can calculate both CRC and Adler32 checksums in a single file read. Therefore closing this issue, super-seeded by #5855
