### ISSUE TITLE
Limit TaskName/StepName value length in the specs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5641]
As a follow up of this issue #5465 , we just had the RelVal agent complaining again about wmbs_job column lengths (cache_dir and fwjr_path).
AFAIR there is a hard limit for varchar2 - I guess for MariaDB/InnoDB only - where varchar2 cannot be bigger than 767, that means we have to fix this issue in another way.

My suggestion would be to limit TaskChain 'TaskName' fields, otherwise people add a bunch of metadata to it and things go awry, as you can see in the example below.

```
(DatabaseError) ORA-12899: value too large for column "CMS_WMBS_PROD7"."WMBS_JOB"."FWJR_PATH" (actual: 775, maximum: 767)
 'UPDATE wmbs_job SET fwjr_path = :fwjrpath WHERE id = :jobid' [{'fwjrpath': '/data/srv/wmagent/v1.0.0.patch4/install/wmagent/JobCreator/JobCache/boudoul_RVCMSSW_6_2_0_SLHC23_patch1MinBias_TuneZ2star_14TeV__UPG23SHNoExt_150226_112655_3647/MinBias_TuneZ2star_14TeV_pythia6_Extended2023SHCalNoTaperNoExtPix_GenSimHLBeamSpotFull/MinBias_TuneZ2star_14TeV_pythia6_Extended2023SHCalNoTaperNoExtPix_GenSimHLBeamSpotFullMergeFEVTDEBUGoutput/DigiFull_Extended2023SHCalNoTaperNoExtPix/DigiFull_Extended2023SHCalNoTaperNoExtPixMergeFEVTDEBUGHLToutput/RecoFull_Extended2023SHCalNoTaperNoExtPix/RecoFull_Extended2023SHCalNoTaperNoExtPixMergeDQMoutput/RecoFull_Extended2023SHCalNoTaperNoExtPixMergeDQMoutputEndOfRunDQMHarvestMerged/RecoFull_Extended2023SHCalNoTaperNoExtPixMergeDQMoutputMergedEndOfRunDQMHarvestLogCollect/JobCollection_38213_0/job_296819/Report.0.pkl', 'jobid': 296819}]
```

Comments or suggestions are welcomed :)

**Comment by amaltaro** [comment]
Andrew just reported the same issue again, and it's increasing 
```
2015-04-07 11:32:33,823:ERROR:JobCreatorPoller:Unknown exception while setting the bulk cache:
(DatabaseError) ORA-12899: value too large for column "CMS_WMBS_PROD7"."WMBS_JOB"."CACHE_DIR" (actual: 
790, maximum: 780)
 'UPDATE wmbs_job\n             SET cache_dir = :cacheDir\n             WHERE id = :jobid' {'cacheDir': 
'/data/srv/wmagent/v1.0.0.patch4/install/wmagent/JobCreator/JobCache/boudoul_RVCMSSW_6_2_0_SLHC25_patch3Mi
nBias_TuneZ2star_14TeV__UPGFastTime_150406_192859_1294/MinBias_TuneZ2star_14TeV_pythia6_Extended2023SHCalN
oTaperFast_GenSimHLBeamSpotfixFull/MinBias_TuneZ2star_14TeV_pythia6_Extended2023SHCalNoTaperFast_GenSimHLB
eamSpotfixFullMergeFEVTDEBUGoutput/DigiFullFastTimer_Extended2023SHCalNoTaperFast/DigiFullFastTimer_Extend
ed2023SHCalNoTaperFastMergeFEVTDEBUGHLToutput/RecoFullFastTimer_Extended2023SHCalNoTaperFast/RecoFullFastT
imer_Extended2023SHCalNoTaperFastMergeDQMoutput/RecoFullFastTimer_Extended2023SHCalNoTaperFastMergeDQMoutp
utEndOfRunDQMHarvestMerged/RecoFullFastTimer_Extended2023SHCalNoTaperFastMergeDQMoutputMergedEndOfRunDQMHa
rvestLogCollect/JobCollection_114330_0/job_760413', 'jobid': 760413}
```

I don't know if the best approach here would be to limit the 'TaskName' or whether we do some tricks with Oracle/MariaDB to allow larger strings ?

**Comment by AndrewLevin** [comment]
Hi,

We are going to start running TaskChain workflows outside of relval soon (actually we already have started this), so the workflows will likely go to both FNAL (mariaDB) and CERN (oracle) wmagents. Currently, since the relval wmagent is a CERN (oracle) wmagent, this issue is not a showstopper, but I guess it will become a showstopper once we start sending a lot of TaskChain workflows to both CERN and FNAL wmagents.

Andrew

**Comment by amaltaro** [comment]
Reopening this issue as a follow up of the problems seen in production, reported here:
https://github.com/dmwm/WMCore/issues/9239

As the number of tasks/steps and the amount of information put in the TaskName/StepName increases, we hit database limitations (and performance). 
In order to protect the system from the same problem in the future, I think it would be wise to enforce a schema/limit for those two fields: `TaskName` and `StepName`, and possibly also the amount of steps or tasks that one can add to a single workflow.

I see basically two options for those fields:
a) hardcode them to be consistent with the task/step number. So Task1 would have a TaskName=Task1, Task2 would be Task2, and so on.
b) limit those fields to X characteres (maybe 10). Production seems to be around 30 or 40 chars per task at the moment.

option a) has a bigger impact, people won't be able to quickly say what a Task is doing and it will also affect the job monitoring task logic. 

I foresee a similar limit to workflow length. Maybe we should limit a TaskChain/StepChain workflow not to have more than X (10?) tasks/steps?

Such change would also break any backwards compatibility, so we need to take into account what's already in the system, in case we decide to walk this path.

@bbockelm @vlimant any thoughts on this matter?

**Comment by amaltaro** [comment]
As discussed with @drkovalskyi  in the P&R meeting, we should proceed with some limitation on our side and validate request parameters during a workflow creation, failing creation if it does not respect the limits.

Numbers that came up are:
* limit taskchain to 10 tasks (UL are currently using 7 tasks, I hope we'll never reach 10 though)
* `TaskName` seems to be between 30 and 40 chars. So let's set it to 50 chars and be done with it.

Once we have this implemented and first tests performed, we should contact McM and make sure they are aware of the limitations that will be deployed to production.
