### ISSUE TITLE
Name for output root file for multiRun DQM harvesting

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5643]
I believe the definition of the root file created out of the harvesting jobs does not come from WMAgent, but from cmsDriver command itself used to create the configuration. Anyways recording it here so we can investigate it later on.

I noticed the file name in DQM Gui has only one run number even when we are running "multiRun" harvesting mode, meaning several runs will be present in the same output root file, example:
DQM_V0001_R000202209__JetHT__CMSSW_7_2_0-PRE_R_72_V10A_RelVal_jetHT2012c_TEST_HG1503_Validation_multiRun_v2-v1__DQMIO.root  

If it relies on WMAgent, then we should investigate a proper way to name it.

**Comment by amaltaro** [comment]
@rovere Marco, do you know what should be the expected name when we upload a single root file containing > 1 runs?

**Comment by rovere** [comment]
The file **must** contain one and only one run-number. Maybe you are referring to the case in which we run the so called multi-run harvesting? But, also in this case, the final ROOT file will have the full statistics of all runs merged into a "fake" run. The agreement w/ Federico and the DQM Team is to have this identified by 999999. @deguio should be able to comment further, in case it is needed.

Ciao,
--Marco.

**Comment by amaltaro** [comment]
Yes, it's about the multi-run harvesting.
> The agreement w/ Federico and the DQM Team is to have this identified by 999999. 

Perfect!!! That's what I needed to know ;) Thanks Marco!

**Comment by deguio** [comment]
I confirm. thanks to both,
F.

**Comment by amaltaro** [comment]
@rovere @deguio , I assume the way to force a run number to the root file is by:
process.dqmSaver = cms.EDAnalyzer("DQMFileSaver",
    forceRunNumber = cms.untracked.int32(999999),

Can you confirm it please?

**Comment by deguio** [comment]
I confirm.
ciao,
F.

**Comment by amaltaro** [comment]
@vanbesien @deguio , the implementation is working as expected in WMAgent and it creates the following file in my tests:
DQM_V0001_R000999999__MinimumBias__CMSSW_7_3_1_patch1-GR_R_73_V0A_RelVal_run2010A-v1__DQMIO.root

However, jobs with multiRun are still failing because the upload step fails to upload that file to the DQM Server. These are the two urls we are trying to upload:
    "DQMUploadUrl": "https://cmsweb-testbed.cern.ch/dqm/dev;https://cmsweb.cern.ch/dqm/relval-test",

Could you guys please take a look at the server logs and try to identify what the problem is?

**Comment by amaltaro** [comment]
BTW, it seems to be an issue with the run number, since we managed to upload tons of the same files with a difference in the run number only.

**Comment by amaltaro** [comment]
File is properly created but FJR points to a wrong output file (with the wrong run number).
I posted this issue in the framework HN, let's see what happens:
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3592.html

**Comment by amaltaro** [comment]
From the discussion we just had, here are the notes provided by Gianluca:
```
After some experience with multi-run harvesting for ALCA applications,
the convention slightly evolved as illustrated below:

* run number -> always use 999999
* run range (min, max run#) is added to the string of the dataset name

Resulting file name:

DQM_V0001_R000999999__StreamExpress__Run2016F-PromptCalibProdSiStripGains-Express-v1-278309-278310__ALCAPROMPT.root

Dataset: StreamExpress
Processing tag: Run2016F-PromptCalibProdSiStripGains-Express-v1-278309-278310
Datatier: ALCAPROMPT


This allows for:
* special treatment by DQM GUI indexing
* searchability of run range in GUI interface
* allows for unique names for multiple uploads for the same dataset in
different run ranges

This convention is already in use, see for example:
https://cmsweb.cern.ch/dqm/dev/
searching for run 9999
```

The timescale to start having such requests in production was said to be Oct/Nov.

Last but not least, the agreement is that this feature is going to be supported for CMSSW 80x.
