### ISSUE TITLE
Submitting jobs above the thresholds - too many pending jobs

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5647]
For the assignJobLocations method, JobSubmitterPoller goes trough a sorted site list. If the site has available slots to run more jobs, then it creates a cache with more jobs to be sent. For 'setting' where the job is supposed to run we pick a random site in the job possible site list:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L702
In MC jobs, this location is only used for filling the record in wmbs_jobs, the job can eventually run in other site and when it does run, BossAir will update the site. For calculating the available slots, the pending jobs are counted from wmbs_jobs (So this location will actually affect the internal pending counts the next cycle). Faking the location makes sense for MC jobs, but this can cause to submit jobs above the thresholds for other sites. i.e:
A mc job can run in 5 sites, 4 of them have their pending threshold full. Lets suppose that the remaining site is not running jobs because an issue - or running a lot fewer than expected in the site pledge (max running). JobSubmitterPoller will find available slots to run in that site and when it is assigning the location, it may pick up one of the remaining 4 full pending threshold sites. When we actually fill the pending threshold for the site running too few, it would have affected the pending internal counts for the remaining 4 sites. In this case, JobSubmitter will count 1/5 of the jobs it submits to the site not running jobs (random site, 1 out of 5). So we can actually send 4 times more jobs to the other sites. 
Let's say that site has 300 pending slots, then JobSubmitter will send 300 * 4 jobs above the pending thresholds. Now, think about MC workflows with 25 sites in the whitelist, it can submit a lot more... 300 * 24 = 7200

**Comment by lucacopa** [comment]
I think I found the problem, I added some debug statements to the JobSubmitterPoller in vocms0314.
You can find the debug logs at:
/afs/cern.ch/user/l/lcontrer/public/JobSubmitterDebugging/JobSubmitter.log

As you can see in the logs, I managed to have 25 pending slots for FNAL. The component started to assign locations in this while loop:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L616
It practically never stopped, for 25 available slots to fill in FNAL, it assigned 1829 jobs distributed as follow: 

Jobs assigned for internal count toT1_IT_CNAF:
268
Jobs assigned for internal count toT1_US_FNAL:
244
Jobs assigned for internal count toT1_ES_PIC:
274
Jobs assigned for internal count toT1_DE_KIT:
255
Jobs assigned for internal count toT1_RU_JINR:
233
Jobs assigned for internal count toT1_FR_CCIN2P3:
272
Jobs assigned for internal count toT1_UK_RAL:
283

There are 2 different problems:
- nJobsRequired is not affected at all for jobs that can run in multiple sites. IMO, we can just remove this condition:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L727
So we decrease the accounting always. AFAIK the reason for this condition to be there, is to be flexible with the accounting for jobs with multiple sites in the whitelist, but don’t account them at all is like assuming that submit as many as possible doesn’t matter. 
- for the 1829 jobs submitted, only 244 (13%) were accounted to FNAL. This only matters in the internal thresholds counting at:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ResourceControl/MySQL/ListThresholdsForSubmit.py
The problem is that we are adding a lot of jobs to other sites that in terms of thresholds are already full (in this case 1585). If we were running only MC agents, this could not be that important but as we are running site dependent jobs (processing, merge, cleanup, log collect jobs), adding jobs without a real control to a site can be blocking that site.
I think the solution can be to make the fake site assignment smarter:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L695
We can check what sites actually can receive more jobs in terms of internal accounting (self.currentRcThresholds) and assign the job randomly between the sites that have free slots in the accounting.

**Comment by lucacopa** [comment]
@bbockelm what is the purpose of these lines?
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L727-L728

**Comment by amaltaro** [comment]
Luis, the way I understand it is as follows:
 - only account this job IF it's assigned to a single site
 - if there is more than one site. JobSubmitter may submit more jobs than nJobsRequired (since it does not decrement)
On the other hand, if we *always* decrement that, we'll be accounting the same job against all its possible locations...

**Comment by lucacopa** [comment]
yes, but If we always decrement we will account the job only for one site only, to the one in fakeAssignedSiteName. This site will be picked randomly from the possible site list.

**Comment by amaltaro** [comment]
This should be fixed with https://github.com/dmwm/WMCore/pull/6409 and https://github.com/dmwm/WMCore/pull/6434

**Comment by bbockelm** [comment]
Note #6434 is not yet merged.

**Comment by amaltaro** [comment]
Fixed, ergo closing it.
