### ISSUE TITLE
Add validation for parent flag

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5670]
1. If input dataset is "RAW" tier, there is no parent files for input files so parent flag cannot be set true. 
2. If there is no input dataset (MC), parent flag cannot be set true.

**Comment by DAMason** [comment]
I guess I'm confused about what the parent flag does -- why does it cause bad things to happen if you set it to true and there is legitimately no parent?  Shouldn't it just shrug its shoulders and move on?

**Comment by ticoann** [comment]
AFIK, parent flag is set when request need to use parent files for processing the input files.
So it is two file processing one. I think it is not the correct approach when parent flag is set if the parent file is not exist just ignore. Why would set the parent flag to true if you don't need to use? Is there a case, parent files exist only for some files in the same dataset but not others?

**Comment by DAMason** [comment]
Ah -- so the flag means "two file input" OK then you are right.  It is a mistake on the part of the requestor to request two file input when the second input doesn't exist.

**Comment by amaltaro** [comment]
Seangchan, your approach sounds correct to me.
