### ISSUE TITLE
Problems reading condor logs with PyCondorPlugin

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5672]
Two parts of the code to fix:
- We have to read the condor logs from the last retry of the job. We should organize by creation date/timestamp rather than by condor job number. 
- Why a condor.x.x.log can be empty? probably some weird case? anyway, the plugin need to handle this.

**Comment by lucacopa** [comment]
@tsarangi I pushed this bandaid to my private repo ( So I can keep my large scale test running ) https://github.com/lucacopa/WMCore/commit/fae1a0345643b22211e76a780049ffe496ae8343
This is a temporary fix to the problem, but it is not really a solution. We need to sort in order of creation.

**Comment by tsarangi** [comment]
@lucacopa 
I will work on this today or tomorrow, and also for the problem where the len(condor_log) is zero!
