### ISSUE TITLE
Replace sendMessage from WorkQueueReqMgr interface

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5675]
This requires creating log db for reqmgr2 and put the error messages there. This db can be combined ops note. should prevent adding duplicate error messages over and over

**Comment by vkuznet** [comment]
Seangchan, I think I need a little bit more info on this subject. Please start explaining current system and give details where new DB should be created and what are access/retrieve patterns for messages. From RequestManager interface I see that message is created with given request, but I'm not sure which DB holds the data.

**Comment by ticoann** [comment]
Hi Valentin, I am not completely sure what to do with this either. That is why assigned to you. :smile: 
I was just thinking out some request related db which ops can comment as well as reporting request level (not job level) errors. We should discuss this sometime we can talk a little bit tomorrow meeting.
Thanks,

**Comment by vkuznet** [comment]
Seangchan, in order to design something I need to understand the requirements. Few initial questions: what is a volume of data, how it will be queried? Does messages will accompany every request? Will they be added at later time? Will data-ops search for messages/notes? How? Should messages/notes be kept forever?

**Comment by ticoann** [comment]
closing and create more general requirement #5705

**Comment by vkuznet** [comment]
@ticoann , Seangchan, this issue is still marked as open even though you're closing it a year ago. Can you have a look and close it properly.
