### ISSUE TITLE
add new summary page for given request in wmstats

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5681]
need to define what kind of information need to be displayed (i.e. workflow progress)

**Comment by drkovalskyi** [comment]
Can we either get a separate webpage or just a view in the DB that won't require to load all the data that WMStats reads? 
I think this image shows all that we need to know:
![screen shot 2015-03-13 at 13 39 09](https://cloud.githubusercontent.com/assets/4704624/6640564/8ae254fa-c998-11e4-9352-6f4f28ba2f22.png)
If some information is not trivial to achieve, here is the bare minimum:
- lumi progress
- event progress
- failure rate
- queue injection
- job progress
"Estimated completion" is very useful as well, but if it's hard to get, we can live without.
Thanks,
          Dima

**Comment by vlimant** [comment]
will go with an effort to renew the wm monitoring IMO
