### ISSUE TITLE
listDatasetFileDetails unexpected failures

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#5694]
After this commit https://github.com/dmwm/WMCore/commit/2afc01ae571390f5fa009dd258be757adac89c28 we got a KeyError (see https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/489.html) here:

```
Traceback (most recent call last):
  File "/afs/cern.ch/user/m/mmascher/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 78, in execute
    filedetails = dbs.listDatasetFileDetails(kwargs['task']['tm_input_dataset'], True)
  File "/afs/cern.ch/user/m/mmascher/repos/WMCore/src/python/WMCore/Services/DBS/DBS3Reader.py", line 258, in listDatasetFileDetails
    files[p['logical_file_name']]['Parents'].extend(p['parent_logical_file_name'])
KeyError: '/store/mc/Fall13dr/QCD_Pt-470to600_Tune4C_13TeV_pythia8/GEN-SIM-RAW/castor_tsg_PU40bx50_POSTLS162_V2-v1/00001/9E4CDF6D-539E-E311-BEB5-0025905A60DE.root'
Traceback (most recent call last):
  File "/afs/cern.ch/user/m/mmascher/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 111, in <module>
    fileset.execute(task={'tm_input_dataset':dataset, 'tm_taskname':'pippo1', 'tm_dbs_url': config.Services.DBSUrl})
  File "/afs/cern.ch/user/m/mmascher/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 83, in execute
    " and contact the experts if the error persists.\nError reason: %s" % str(ex)) #TODO addo the nodes phedex so the user can check themselves
```

The dataset was `/store/mc/Fall13dr/QCD_Pt-470to600_Tune4C_13TeV_pythia8/GEN-SIM-RAW/castor_tsg_PU40bx50_POSTLS162_V2-v1/00001/9E4CDF6D-539E-E311-BEB5-0025905A60DE.root` and the user used the `useParent` flag

**Comment by mmascher** [comment]
I will fix this

**Comment by ticoann** [comment]
Sorry Marco for the inconvenience. Was that the case following two calls returns different set of lfns?

files = self.dbs.listFileParents(block_name = fileBlockName)
fileDetails = self.listFilesInBlock(fileBlockName, lumis)

**Comment by mmascher** [comment]
No, these two calls returned a different set of files: `fileDetails = self.dbs.listFiles(dataset = datasetPath, validFileOnly = 1, detail=True)` and `self.dbs.listFileParents(block_name = fileBlockName)`

With `validFileOnly = 1` everything is fine.

**Comment by ticoann** [comment]
Ah, I see. Thanks,
