### ISSUE TITLE
Requirements for reqmgr2 from comp/data-ops

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#5696]
This ticket is placeholder for collection of requirements we got from C&O week and chatting with comp/data-ops:

From Andrew Lahiff
- ProcessingString by default should be what is already defined in the request (S)
   Is this mean, Processing String is defined when request is made but can be changed by ops when it gets assigned? Or it won't be changed?  

- AcquisitionEra by default should be set to the campaign name (although there is at least one exception to this rule because the campaign begins with a number) (S)
How do you want handle exception? Drop the first number in front and make that AccquisitionEra?

- ProcessingVersion by default should be 1, but if any of the output datasets of the workflow would conflict with any existing datasets in DBS and/or PhEDEx, this number should be incremented as necessary

(I set the default value to 1 for this release).
Do you want to automatically check out put dataset and increase the ProcessingVersion by one?
This would be a little tricky since we have to find what was the processing version from previous request.
It could be 1, 2, etc depending on howmany done. Also ACDC should be treated differently, correct?

- the LFNbase should be set appropriately, e.g. /store/data, /store/mc, /store/himc, ... (S)
You mean LFN base should be set automatically? Could you give a written rule for which goes which?

- for run-dependent MC ReDigi, the splitting should be changed automatically to event splitting and set such that at least 500 (PU_RD1) or 2000 (PU_RD2) jobs will be created (S)
I probably don't understand correctly on this.
The splitting parameter should be defined in the spec (EventPerJob) in this case, are you saying this should have different values for depending on the request type?

- even if there was just a simple default site as well (e.g. Tier-1 with input dataset 100% on disk), then this would be very useful (S)
I have to check whether PhEDEx gives location by dataset (not block). Default value should be only the 
100% on the disk?

Other comments:
- for redigi workflows, there should be a check that the pileup dataset is on disk at the site you want to assign the workflow to (S)
We check this one in WQ, but I guess that is too late for checking. (All the location check is done in WQ by block). If there is location check by dataset in PhEDEx, can do first check in reqmgr.)

- if the input dataset for a ReReco or ReDigi workflow is not PRODUCTION or VALID, then assignment should fail
This require on going inputdataset (data is still fed to that dataset) should be already set PRODUCTION or VALID. Can this precondition satisfied?

This covers most of what we have in the assignment script (there are some other things like changing timeouts, max merge events and/or memory limits based on the campaign but these are less important).

Original comments:
- fast turn around of workflow templates, this can be done via approach I
  propose (aka das maps upload), i.e. separation of templates/workflow
  parameters from release cycles (V)

I was thinking putting the template in couchdb and can be loaded periodically or triggered. But we can discuss in later.

- semi-automation of assignments/approval process by using data-ops scripts,
  this is what we discussed but didn't implemented yet (S) 
Need to talked to OPs about more concrete requirements.

- auto-assignment/suggestion of workflows to site, this is new requirement
  which we didn't address or discuss how to do. To do that we need to implement
  an algorithm/API to get "busyness" of the site and provide an interface for
  auto-assingment/semi-assignment, i.e. suggestion/manual-assignment (current
  design). (V)

Since all the request will have different conditions. Bulk assignments need to be carefully reviewed

**Comment by vkuznet** [comment]
For dynamic templates support please take PR: #5701

**Comment by amaltaro** [comment]
Now that reqmgr2 is basically into production, shall we close this issue?

**Comment by vkuznet** [comment]
I'll not object
