### ISSUE TITLE
 Can we do deterministic random number seeds?

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5697]
Ask @davidlange6 for details.

**Comment by amaltaro** [comment]
@ericvaandering is it about the deterministic pileup? If so, then I guess it was worked on on another ticket, right?

**Comment by ericvaandering** [comment]
No, this is totally different.

**Comment by davidlange6** [comment]
I’ll look for you tomorrow Alan..

**Comment by amaltaro** [comment]
Summarizing here what David and I discussed, so I don't forget :)
The idea is that 2 workflows exactly the same (the only difference being its CMSSW release) would use the same set of random seeds, e.g.:
 - wf1 job1 use the same set of random seeds than wf2 job1
 - wf1 job2 use the same set of random seeds than wf2 job2
etc
This way they can perform identity tests in RelVals.
David, feel free to correct me if I got something wrong.

**Comment by ericvaandering** [comment]
I thought the point of this was different, that it was for trying to recover exactly what a workflow would have done. E.g. on a resubmit. At least we talked about determinism in that case too.

Maybe the easiest way to do this is to require, in this comparison case, a master seed to be supplied by the user. Then we initialize the python random # generator for each job with (that seed) + 1.

**Comment by ericvaandering** [comment]
Ok, so this is different from #5534. This, from what I just gathered, is only needed by RelVal. @davidlange6 how would you like to prioritize this? Need-by date?

**Comment by AndrewLevin** [comment]
Hi Eric,

Well, I think that #5534 is a prerequisite for this issue. If retried jobs have different random seeds than the first job, then two wfs with the same random seed will still have different outputs, since there will be different jobs that are retried.

Andrew

**Comment by ericvaandering** [comment]
We may have another issue with this which is the new type of random number seed added to CMSSW by Lindsay here: https://github.com/cms-sw/cmssw/pull/13921

We'd need to verify that we set all those seeds correctly or make a deterministic version of RandomServiceHelper.py
