### ISSUE TITLE
xrdcp hardcode lxgate39 for createStageoutcommand

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#5703]
On one site I see failures for xrdcp for local stageout and it seems that it adds lxgate39.cern.ch and it becomes "root://lxgate39.cern.ch/root://grid02.physics.uoi.gr//store/unmerged/SAM/StageOutTest-21864-Wed-Feb-25-22_39_50-2015" which is not correct. I think any site which uses xrdcp for stageout should specify hostname like "root://grid02.physics.uoi.gr" and WMCore should not have hardcoded value. 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/XRDCPImpl.py#L47

Can we remove this hardcoding?

**Comment by ticoann** [comment]
I am not sure why there is hardcore host name there (Probably that was the only gateway before). I think we should remove it. Someone knows more about the code history should comment. @hufnagel, Dirk?
