### ISSUE TITLE
Create Log database

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5705]
There are ops requirement to have database which Ops can write the comments and check (search)
I think it is better to have separate db for this.
Here is the requirement I can think of.

1. Ops should be able to write the comments  and retrieve comments by request.
2. Agent should be able to right the status of request or warnings and errors to the db by request and agent.
   * In case of the error message it could be request specific message (currently agent specific issues propagated to wmstats but not in detail) 
   * Error message and warning should be overwritten for repeated errors.
   * Request status need to be propagated (i.e. request is aquired since there is no available site, blah, blah)
   * Message should be updated asynchronously especially for the WMAgent report since the components runs in parallel.
3. Search option should be provided only by (group of) request name(s) and agent. (If there need more search option please specify).
4. Log can be cleaned up once request is announced.

There is some framework Zdenek, which updates the agent status to 
https://cmsweb.cern.ch/couchdb/_utils/database.html?alertscollector

and code base is  (We can review to check whether anything is reusable for the purpose of this database)
https://github.com/dmwm/WMCore/tree/master/src/python/WMComponent/AlertGenerator
https://github.com/dmwm/WMCore/tree/master/src/python/WMComponent/AlertProcessor

**Comment by ticoann** [comment]
replace #5675

**Comment by vkuznet** [comment]
Seangchan, it is still far from clear what exactly ops need. Let me break it down for you. The Alert system as far as I can tell is an client-server architecture where server collects various alerts sent by clients. The clients collect them automatically from workflows. While the requirements you posted seems like do not need any automation. Data-ops will provide request/agent and manually insert comments about given request. I don't really see the need in client-server architecture here. A simple DB will work just fine. What we'll need a couple of APIs: write(request, comment|error), search(request). The doc structure can be simple json with request/agent names and couple of additional attributes such as comment, its content, date, type. All clients will talk directly to logdb which can be any database (couch,RDMS). The only question is do we need central DB or local ones? And, it would be helpful to provide couple of examples how/where/who will send the message to logdb (should it be done within WMAgent code, externally, etc.)

**Comment by ticoann** [comment]
Valentin, the reason it is not clear is because I don't have clear idea. :smile:
Actually it is not just data ops writing to the database, Agent should be able to right on that db which could be many parallel calls. I am more concerns about format of the doc rather than the architecture of how the message is conveyed.  Anyway, I will try to contact you on skype tomorrow if you have time.

**Comment by vkuznet** [comment]
I think we should organize content as following:

```
request | date | msg | type
```

here request is request name, date is full timestamp (probably better store
UNIX time), msg is a string blog and type should indicate type of the message,
e.g. comment or error.

If we'll use RDBMS, then the schema would be

```
AgentTable -> aid|AgentName
RequestTable -> rid|RequestName
TypeTable -> tid|TypeName
LogTable -> aid|rid|UnixTimeStamp|Text|tid
```

Then it would be easy to organize look-up by request name, comment type, date.

If on another hand we'll use document-oriented DB (e.g. CouchDB), then we still
can use JSON but it will have 

```
{'request':[{'date':bla, 'comment':bla, 'type', bla}, ...]}
```

But look-up will be more complicated.

The RDBMS approach here seems better. It will be quick since we can apply index
on request name, time, type.

I don't think it would be wise to allow text search, instead I'll suggest to
stick with request name/agent pair and optionally allow search for date and
type of comments.

I should be available today for chat.
Valentin.

**Comment by vkuznet** [comment]
I performed several tests with CouchDB. Here is the outcome of this R&D:
- CouchDB can't handle concurrent updates of single documents, if concurrent clients will catch the same revision value it will lead to document conflicts which needs to be resolved manually
- Therefore we need to use "flat" structure of documents, i.e. every entry in LogDB will be a new document. This document should have id generated by CouchDB and its own attributes.
- I suggest the following attributes: ts (time stamp), name (request name), agent (agent name), msg (message body) and type (message type, e.g. comment, error), status (status of request). The timestamp should carry microseconds to allow clients to sort entries and avoid overlap among concurrent clients.
- The LogDB with CouchDB back-end should provide a view with request name and optional agent name.
- We need extra component to clean-up old/obsolete entries. For old entries (to be defined as announced requests plus some delta in time) we can delete documents. The obsolete entries (error message overwrite previous error message) we may either have extra clean-up component or leave things as is.
- Special care should be taken with stale requests whose status will not change much over time but yet the requests will not acquire announced status. It is unclear how to define action on those.
- The compaction (deletion of old docs) should be done periodically over this DB
- We'll need two APIs, one for inserting new message into LogDB and another to fetch all docs corresponding to given request and agent name. Client will be responsible for sorting fetched docs (can be done based on ts attribute). The API metric should be the following: insert(requestname, agentname, msg, type) and fetch(requestname, agentname).

I used the following scripts to test concurrent read/write operation for LogDB with CouchDB backend:
- https://gist.github.com/vkuznet/495871cc16cd1a36a038
- https://gist.github.com/vkuznet/32074685e79418cd1d32

**Comment by vkuznet** [comment]
First implementation can be found here: https://github.com/dmwm/WMCore/pull/5743

**Comment by vkuznet** [comment]
After initial prototype we further discussed these requirements. Here is outcome of this discussion:
- we will have central LogDB which will collect information from local agent LogDBs as well as provide interface to add additional comments by external clients
- we will create local LogDB within an Agent, it scope will be record all log entries from all components. To solve concurrency problem within component threads we'll use timestamp (within a micro-second precision), i.e. each thread will generate its own message and log it into local LogDB.
- we'll add a summary method whose scope will be to local all entries for given request and perform clean-up. The output would be summary snapshot of log entries for given request which we'll push into central LogDB.
- every summary snapshot will have a unique key based on request and agent name
- each entry in LogDB will carry timestamp, message itself and its type
- we'll assign different types for agent entries and external clients. The agent types will have comment prefix, e.g. agent-comment, agent-error, agent-warning, while external clients will not have such prefix. Their types would be comment, error, warning.
- we'll allow external client to make comment for a single request without specifying agent value, in this case agent=all.
- we'll establish one-way replication from local LogDB's into central LogDB.

**Comment by vkuznet** [comment]
The initial implementation of LogDB can be found here: #5743. The required configuration

```
logdb = config.section_("logdb")
logdb.couch_url="http://localhost:5984"
logdb.central_couch_url="https://cmsweb.cern.ch/couchdb"
logdb.db_name="logdb"
```

The following APIs are provided:

```
def post(self, request, agent, msg, mtype="comment"):
    """Post new entry into LogDB for given request/agent pair"""
def get(self, request, agent, mtype="comment"):
    """Retrieve all entries from LogDB for given request/agent pair"""
def delete(self, request, agent):
    """Delete entry in LogDB for given request/agent pair"""
def summary(self, request, agent):
    """Generate summary document for given request/agent pair"""
def upload2central(self, request, agent):
    """
    Upload local LogDB docs corresponding to given request/agent
    into central LogDB database
    """
```
