### ISSUE TITLE
Move subscriptions to Disk for outputs

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#5706]
This is more of a placeholder based on a discussion Seangchan and I had -- and also discussions in the compops meeting today (Mar 23).  Ultimately we need to be able to leave a copy of output data on a disk instance somewhere while its also being sent to its custodial tape instance.  

For example ideally a "custodial subscription" should have two parts:

1.  Make a PhEDEx noncustodial move subscription to a T1 disk instance (with the option to auto approve)
2.  Make a PhEDEx custodial replication to MSS (NEVER auto approve)

instead of what is currently done, namely just a PhEDEx move to the MSS endpoint -- which has the end result of rendering the dataset at least partially inaccessible once the move to tape is complete.  This especially hits ops when producing GEN-SIM, then needing to turn around and reconstruct it.  Ideally we'd like to be able to preserve a copy on a disk instance, but right now even if one makes a separate replication to disk, depending on when requests are approved, the move to MSS can still leave data needing to be restaged.

Why make the move request?  Usually this is done for MC production to free up disk a the T2's the data is produced at.  The move request is supposed to clear out data once its produced at the T2 to prevent the T2 disk from filling up.  Thinking about this more #2 might also be optional -- miniaod's wouldn't have the tape component since we don't write those to tape.

Sounded like there was missing functionality in reqmgr -- like actually being able to make the move subscription to disk.

**Comment by amaltaro** [comment]
Thanks Dave!
@ticoann , here is my first attempt to fix it (together with #5403) amaltaro/WMCore@2c2e7478e
I still need to test it in my VM.

**Comment by ticoann** [comment]
Hi Alan, your temp patch looks good. I added one comment. There are a couple of part I think it needs to be added. RequestManager GUI should have the option to add this. And validation has to be changed. 
If you don't mind, I will use your patch and add those things. You don't have spend more time on this unless you have spare time. :smile:

**Comment by amaltaro** [comment]
I was hoping to fix it before you jump in, but in the end I was too late :-)
About the GUI, indeed I missed that part. If you want to take over this patch, be my guest, otherwise I will resume it tomorrow.
BTW, I just tested the current patch in my VM and I managed to assign a workflow (I still need to connect an agent to it though...)

**Comment by ticoann** [comment]
@DAMason, Dave, what should be default value for NonCustodialSubType?

**Comment by DAMason** [comment]
what are my options?  replica?  don't auto approve?  we're talking about general defaults that we override depending on the application right?

**Comment by ticoann** [comment]
Yes, general default you can overwrite. Basically what do you want to put here Move or Replica.
https://github.com/ticoann/WMCore/blob/phedex_subscription/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L952
https://github.com/ticoann/WMCore/blob/phedex_subscription/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L954

**Comment by DAMason** [comment]
I suppose the safe thing to do for a default for noncustodial subscriptions would be to make a replica.  That said when using it in association with MC production we'll almost all of the time be doing moves.

**Comment by ticoann** [comment]
I set the default for noncustodial subscription type to Replica. I think I will just let ops define explicitly on MC side.
