### ISSUE TITLE
Add ability change white list after workflow is assigned

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5711]
The purpose is
1. In case initial site white list is not available after workflow pulled down the agent, by changing site white list, it can redirect the jobs to new site. (This wouldn't involve condor_q edit for the pending job in condor)
2. Need to consider new white list doesn't have the data (use xrootd or PhEDEx subscription)

**Comment by amaltaro** [comment]
@ticoann certainly a good bug to be closed by the next upgrade. Actually, it could be a new feature to JobUpdater
