### ISSUE TITLE
WMExecutionFailure crashes

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5712]
Here

http://cms-project-relval.web.cern.ch/cms-project-relval/forGithubIssue25Mar2015/Job_502057.tar.bz2

you can see an example of a job where it seems that the wmcore code has crashed. It produces this message in the Report.*.pkl file:

 Adding last ten lines of CMSSW stdout:
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
WARNING: There already exists /storage/local/data1/condor/execute/dir_13460/glide_ZE1nDb/execute/dir_25457/job/WMTaskSpace/cmsRun1/CMSSW_7_4_0_pre9_ROOT6 area for SCRAM_ARCH slc6_amd64_gcc491.
CmsRunFailure
Message: Error running cmsRun
{'arguments': ['/bin/bash', '/storage/local/data1/condor/execute/dir_13460/glide_ZE1nDb/execute/dir_25457/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc491', 'scramv1', 'CMSSW', 'CMSSW_7_4_0_pre9_ROOT6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Return code: 1

```
ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
MethodName : __init__
ClassInstance : None
FileName : /storage/local/data1/condor/execute/dir_13460/glide_ZE1nDb/execute/dir_25457/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
ClassName : None
LineNumber : 18
ErrorNr : 1
```

Traceback:

**Comment by ticoann** [comment]
@AndrewLevin, Hi Andrew, could explain a little more what kind of behavior you want? I might misunderstood what you want in the meeting.

**Comment by AndrewLevin** [comment]
Hi Seangchan,

It says "Adding last ten lines of CMSSW stdout:" but it does not actually add the last ten lines of the CMSSW stdout (it adds some lines in the stdout of the wmcore code that is executing I guess). Having some of the CMSSW stdout is the behavior I want.

If you look at the condor.*.*.err files (eg Job_502057/condor.45477.15.err) in the link, you can see the lines below, which may or may not be related to the missing CMSSW stdout, but still look very bad to me.

Andrew

ERROR:root:'1_ExeWCTime'
ERROR:root:Traceback (most recent call last):
  File "/storage/local/data1/condor/execute/dir_7634/glide_Ss5cxB/execute/dir_12407/job/WMCore.zip/WMCore/WMRuntime/Monitors/DashboardMonitor.py", line 140, in stepEnd
    stepReport = stepReport)
  File "/storage/local/data1/condor/execute/dir_7634/glide_Ss5cxB/execute/dir_12407/job/WMCore.zip/WMCore/WMRuntime/DashboardInterface.py", line 328, in stepEnd
    self.WrapperWCTime += data['%d_ExeWCTime' % self.stepCount]
KeyError: '1_ExeWCTime'

...

Exception in thread Thread-1 (most likely raised during interpreter shutdown):

**Comment by ticoann** [comment]
Hi Andrew, so basically you want to have some useful information to propagate to wmstats not just last 10 line. (And you said it is not even do that).
Extracting useful messages from log is maybe a little harder. 
What I can think of is searching ERROR string and get the messages around that. 
In this particular example which message is useful for you in the log. Also could you point me CMSSW stdout and stdout log file (scramOutput.log). If you can think of pattens of useful log message, that will be good too.

**Comment by AndrewLevin** [comment]
Hi Seangchan,

Yes, I want to have useful information in wmstats. The last 10 lines would be fine in this case. Here are the CMSSW log files for this job:

http://cms-project-relval.web.cern.ch/cms-project-relval/forGithubIssue25Mar2015/719c9614-d22f-11e4-9f78-02163e00d7b3-0-3-logArchive.tar.gz

The information in WMStats in this case is about a WMCore crash. The problem for us (the CMSSW developers and the workflow team) is that CMSSW crashed, not that WMCore crashed. Having information about a WMCore crash where there should be information about a CMSSW crash is really not good.

Andrew

**Comment by amaltaro** [comment]
@ticoann was this fix added in #7933 ?

**Comment by ticoann** [comment]
I would say partially. Still need to see how the cmssw error propagate.

**Comment by amaltaro** [comment]
Demoting it since it has been high priority for 2 years :)
