### ISSUE TITLE
kill jobs immediately if the MaxWallTimeMins parameter is more than the softTimeout

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5727]
Hi,

As reported here

https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6466/1/1.html

we are seeing jobs get stuck in pending when they have the MaxWallTimeMins set longer than 48 hours. If a job has no chance of running we should just kill it immediately.

(Actually, there are two similar parameters

MaxWallTimeMins 
MaxWallTimeMins_RAW

and I am not sure which one is used to match the job to the glidein.)

Andrew

**Comment by AndrewLevin** [comment]
Actually, I think we should make it a configurable parameter when the MaxWallTimeMins is too long. This really depends on how long the longest glideins run. We know that the time per events are often set very roughly, and so I think requiring that the MaxWallTimeMins be always less than the softTimeout is too strict.

**Comment by amaltaro** [comment]
Andrew, I didn't see this issue and opened another one #5738. If you agree, we can close this one and follow up on the other one?

**Comment by AndrewLevin** [comment]
yes, we can close mine
