### ISSUE TITLE
Remove site-level pending limits

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#5745]
We had this occur a few months back, but I don't think we ever fixed it.  Feel free to close it if we in fact did this.

The way that production jobs are submitted with large whitelists means that sites can have many pending jobs - well over the site-wide limit.  This causes other types of workflows (merge, reprocessing) to no longer get new jobs.

Now that everything is HTCondor, there's no need for site-wide pending limits.  We just need to keep the per-site-per-type limits.  We should simply remove this code.

**Comment by ticoann** [comment]
Hi Brian, for the submitting the jobs,  WMAgent always checks per site and per type for its threshold.
For the large white lists, it simply add up the all the white listed sites' pending threshold minus jobs are  already pending for those sites. Is that what you were asking, should I close the issue?

**Comment by bbockelm** [comment]
Hi,

Possibly not - I'm not sure we're talking about the same thing.

I think we need to simply ignore the site-pending limits, as the per-site-per-type is sufficient.

Brian

**Comment by ticoann** [comment]
Hi Brian, I guess I misunderstood what you are asking for.
So you just need WMAgent not checking the overall site pending number when we submit the job, is that correct? (something like below - I have to check the code more in detail)
https://github.com/cms-sw/cmsdist/commit/35c4230fab722d787e163568821f4e75c2ec2514

I was just wondering whether there is any pending number restriction in HTCondor in relations to the running jobs and what has changed compare to before regarding your comment below? Sorry if I am asking you already explained before, I must haven't been paying attention.

> Now that everything is HTCondor, there's no need for site-wide pending limits.

Thanks,
Seangchan

**Comment by bbockelm** [comment]
Hi Seangchan,

Yes - that proposed fix looks appropriate.

When we were using gLite, there were two things we were trying to accomplish through the thresholds:
1.  Do not overload the number of pending jobs the CE can handle (site-wide limit).
2.  Do not overload the SE with a lot of high-IO job (per-site-per-task limit).

I guess there are some cases where sum(limits of type 2) were greater than 1, hence the need for a separate set of limits.

While HTCondor does have limits to the # of pending jobs, it is definitely not per-site.  It is large enough (somewhere between 250-500k jobs) that we don't have to worry about it right now - sum(limits of type 2) is going to be much smaller.  This is why we can get rid of (1) as you propose in your patch.

In the future, if we are successful in having HTCondor manage the limits of type 2, then we'll need to come up with a separate mechanism to prevent the queue from being overwhelmed with pending jobs.  This is good enough for now.

Brian

**Comment by ticoann** [comment]
Thanks Brian for the explanation.
