### ISSUE TITLE
Report job type to HTCondor

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#5748]
Long-term, HTCondor can apply global limits to number of running jobs for arbitrary sets of jobs (like "merge jobs per site").  These are global across the pool - something the independent agents can't actually do.

However, to apply these limits, we need more information from the agent in the HTCondor job.  Can we add an attribute for the "job type"?  Looking at the resource control, I see the following job types:
- Cleanup
- Merge
- LogCollect
- Harvesting
- Skim
- Processing
- MultiProduction (what is this?)
- Production
- MultiProcessing (what is this?)
- Analysis

Once the job types are in HTCondor, I believe that I can construct the limits via this and the DESIRED_Sites string.

**Comment by ericvaandering** [comment]
Make sense. Can either you or @jamesletts choose a class add variable that fits with the others we use and I'll add it. Makes sense to implement the same in CRAB, probably using at least Analysis, PrivateMC, and perhaps PrivateLHE.

MultiProduction/MultiProcessing are for multicore applications. Back in the day with forking these were quite different because of the built-in mini-merge. Now they are not and we are on a path to get rid of them, but currently they still signify multithreaded jobs.

**Comment by bbockelm** [comment]
I would propose "CMS_JobType" (in other places, we've used 'WMAGent_*" prefix - but it'd be nice to leave room for CRAB too).

**Comment by ericvaandering** [comment]
It looks like this code is almost correct to do what you want: https://github.com/dmwm/WMCore/blob/0ec011d746ee8e00e2278b772f4f9b2b7950dd8f/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L1053

Looks to me like it's just a bug that we don't have this already. The subTaskType string appears nowhere else in the WMAgent codebase.....

Any ideas @ticoann ?

**Comment by ticoann** [comment]
Eric, yes, that looks like a bug. it should be
```python
if job.get('taskType', None):
```

**Comment by ericvaandering** [comment]
Doing a bit of archaeology this code was introduced in https://github.com/ericvaandering/WMCore/commit/d4888b91a89c786fc18666e78dda3974f9cfa686 in its current form. @bbockelm is listed as an author. Before that commit subTaskType was not in the code base, after that patch, just in this one place. Sure looks like a bug. I'll change the code and use the variable Brian suggests so that CRAB can set the same.

**Comment by ticoann** [comment]
That sounds good, Thank you.

**Comment by PerilousApricot** [comment]
Can I add the ClassAd variable to make all my jobs run at max limits?

-- 
Sent from Gmail Mobile

**Comment by ericvaandering** [comment]
Sorry, that functionality is currently limited to holders of Ph.D.s only.

**Comment by ticoann** [comment]
But we will do anything for Andrew. How about CMS_VIP flag?

**Comment by bbockelm** [comment]
Thanks Eric!

At yesterday's HTCondor/CMS phone call, we outlined the general idea to the HTCondor team (using their "concurrency limits" to enforce these rules globally across the pool).  They identified a few items they'll need to improve in HTCondor to do this at scale.

So, it'll probably take a release cycle or two to get all the pieces in place.  However, with this change, the submit infra team can do the rest of the work.  At the least, we'll finally be able to plot global numbers for things like merge jobs.

Brian

**Comment by ericvaandering** [comment]
With the current lead time for every WMCore patch to make it into a running agent, I would say this patch may already be late. :-)

**Comment by bbockelm** [comment]
@ericvaandering @ticoann - is it possible to get Eric's PR merged for this?

**Comment by amaltaro** [comment]
Landing late to this discussion
> Long-term, HTCondor can apply global limits to number of running jobs for arbitrary sets of jobs (like "merge jobs per site"). These are global across the pool - something the independent agents can't actually do.

not sure I really understood it. Does it mean HTCondor would control the *total* number of jobs running for a specific task? How would it manage the number of merge thresholds for instance? What if we run much more merge jobs in 10 sites and exceed this thresholds, would other sites starve of merge jobs?

**Comment by bbockelm** [comment]
Hi Alan,

Not exactly - HTCondor would control the total number of jobs of a certain job-type running at a given site.

In other words, if you limit # of merge jobs at site Nebraska to 100 and are at that limit, then HTCondor would refuse to start additional merge jobs _only at Nebraska_ until one of the running jobs has finished.

This is similar to what WMAgent does now, except:
1. It is applied globally instead of per-agent.
2. It actually applies the limits to the running jobs instead of throttling submissions.  Currently in the agent, if you have merge threshold for Nebraska set to 100 running and 100 pending, then the worst case scenario is 200 running.  In this case, HTCondor would keep things to 100 running (globally) regardless of the number pending.

Anyhow, that's the concept.  This is just the first step.

Brian

**Comment by amaltaro** [comment]
Crystal clear now ;)
About 1), this setting is in an agent basis, not globally. Though one could say it's "global" since several agents contribute to the global limits (sum of all agents task/site thresholds).
