### ISSUE TITLE
wrong total lumi calculation in task chain.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5761]
Review the code below.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/MonteCarlo.py#L58

Following gives double total lumis than what it supposed to be.
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_TOP-RunIIWinter15wmLHE-00015__v1_T_150404_183555_8973

**Comment by amaltaro** [comment]
BTW, it's not reproducible. Julian found a ReDigi workflow today with dup stats
https://cms-logbook.cern.ch/elog/Workflow+processing/21376
and I did not manage to reproduce it neither in my VM nor in the current production services.
