### ISSUE TITLE
Implement shuffling of PU files

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5791]
As a follow up of discussions all around and this summary from @chwissing 
"in the last few weeks we have constantly trouble with processing
workflows, because each and every job opens the _same_ pileup file for
discovering the data products. That causes some issues at some sites."

we should shuffle the pileup files to avoid opening always the same one by each job.

Here is my understand of the code and how it works in WMAgent. WMAgent will create a list of PU files available at the site whitelisted (based only on *completed* blocks available there) and this list is then shipped together with the job (in a json file), which is then fed into the PSet.py configuration during runtime in the worker node (such to avoid DBS calls from the WN).
I guess @ericvaandering is taking over from here ;-)

**Comment by ericvaandering** [comment]
Thanks Alan. Yes, I can either find where this list is inserted into the PSet and shuffle it before. Or extract it and shuffle it. That should make each job different. If I recall correctly, the start position to actually read events from this list is also chosen randomly, so these two randoms should not make the whole process less random. :-)

Maybe @Dr15Jones has input here.

**Comment by ericvaandering** [comment]
Fix is trivial. CMSSW vstring is a python list that can be shuffled in place.

**Comment by Dr15Jones** [comment]
The framework right now just opens the first file in the list in order to find out what data is available and then it closes that file. However, when it comes time to actually get events for pileup, we randomly choose which file to start from and then randomly choose which event to start from within that file.

**Comment by ericvaandering** [comment]
OK, so my patch will have exactly the right effect. By randomizing the list on the WN, you effectively will have two random file opens.
