### ISSUE TITLE
SubscriptionInformation not in workload cache

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5793]
Also add ProcessingVersion as well

On @amaltaro suggestion:

neither of

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/jbadillo_TOP-Summer12-00335_00209_v0__150406_103823_3394

  nor

https://cmsweb.cern.ch/reqmgr2/data/request?name=jbadillo_TOP-Summer12-00335_00209_v0__150406_103823_3394

  has

'SubscriptionInformation':
{'/TTJets_MSDecays_JpsiFilter_1785_TuneZ2star_8TeV-madgraph-tauola/Summer12-START53_V7C-v2/GEN-SIM':
{'NonCustodialSites': [], 'CustodialSubType': 'Move', 'CustodialSites':
[], 'Priority': 'Low', 'AutoApproveSites': [], 'NonCustodialSubType':
'Replica'}}

  present in :

https://cmsweb.cern.ch/reqmgr/reqMgr/request?requestName=jbadillo_TOP-Summer12-00335_00209_v0__150406_103823_3394

**Comment by ticoann** [comment]
Hi Jean-Roch, is there any other information you want to include?

**Comment by vlimant** [comment]
is there any other information you need ? I just found SubscriptionInformation information useful and would be a shame to not have it anymore anywhere.

**Comment by ticoann** [comment]
> is there any other information you need ?

No, I just want to know is there any other information missing but you want to add since we are going to change that we can add it together.

**Comment by amaltaro** [comment]
To be honest, we could simplify it by just adding these info in couch docs (probably reqmgr workload)
"NonCustodialSites": [whatever]
"CustodialSites": [whatever]
etc etc etc.

In principle there is no need to replicate the output dataset there again. We could also drop the "SubscriptionInformation" key.
