### ISSUE TITLE
LumiList not added in the workload for TaskChain

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5798]
@ticoann , I need your help with this issue since I failed miserably while trying to fix it :-(

The problem is that LumiList does not get added to the workload.request.schema section, since we call this method with an empty dict
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L802

I applied a couple of changes in the TaskChain.py spec file, basically
 - calling self.workload.setLumiList() from inside setupTask(), when the code sees the lumiList provided
 - also added LumiList argument under getTaskArguments() (I believe this one is not needed)
but that didn't work.

BTW, in the current production reqmgr (and in my VM) I get this error in the ReqMgr logs
```
ERROR:root:Invalid Value: Complex Value type in sequence:<type 'list'>
for name: LumiList and value: {'160960': [[277, 287], [79, 85], [167, 177], [226, 232]]}
Added to WMAgent Configuration
```
Does it mean we cannot have this structure under the request workload section?

This is a problem because, since LumiList is not available in the spec file - under the request.schema section, cloning TaskChain requests is not a real clone since the new request won't have this info.

Thanks a lot!

**Comment by ticoann** [comment]
Hi Alan, so lumi mask need to be set differently by task in task chain? or it just need to be added in schema section?

**Comment by amaltaro** [comment]
The logic behing lumi mask for taskchain seems to be Ok (at least if someone sets it in the first task), e.g.
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/Integration/TaskChain_Data_LumiMask.json#L29

It's "just" a matter of adding it to the schema section :-)

**Comment by ticoann** [comment]
Why do you need to set the schema? To have json document? anyway, I will take the issue. Please don't spend time on it.

**Comment by amaltaro** [comment]
I'm not anymore :-P  Because then we have the whole information provided by the requestor in one place and inside the spec file
https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/amaltaro_TaskChain_Data_LumiMask_TEST_clone_LumiList_Alan_150417_091600_9167/spec

which then we use WMWorkloadHelper to go through these parameters and clone that request.

I noticed this information is already available in reqmgr_workload_cache, but that document gets much more information and it may be trick to use that as source for clones. 
Do you know another way we could reliable retrieve information provided by the requestor?

**Comment by amaltaro** [comment]
Here is how we load this info
https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py#L632

and then we read the spec with (in my version I actually use dictionary_whole_tree_())
https://github.com/CMSCompOps/WmAgentScripts/blob/master/resubmit.py#L45

**Comment by ericvaandering** [comment]
To answer the original question, we have an alternate way of specifying these lumi lists specifically to make it fit into two lists. I'm sure there are functions to convert them; if you cannot find it, let me know.

The representation for what you've got is something like

```
'160960','160960','160960','160960'
277, 287,79, 85, 167, 177, 226, 232
```

**Comment by amaltaro** [comment]
@ticoann also high prio.
