### ISSUE TITLE
Do not build ACDC docs for aborted workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5819]
This is an improvement and, since I will most likely forget it tomorrow, better to keep this record.
I guess the easiest way of doing so, would be by creating a new job state.

**Comment by ticoann** [comment]
Alan, this might be a little hard to do it, since document is pushed to acdc jobs failed not when status changes. So when workflow is aborted there are bunch of jobs already pushed to acdc.
Currently what we are doing is clean up after the fact. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/CherryPyThreads/CouchDBCleanup.py#L41

We can add "aborted" there. currently only "aborted-archived" is there.

**Comment by amaltaro** [comment]
I still did not investigate how it could be done, but the main reason for that is that ACDC building is a very very expensive operation for ErrorHandler, so if we could get rid of them in such cases, that would be a super improvement ;-) I will investigate it during this week ...

**Comment by ticoann** [comment]
I think the key is when would you know whether workflow will be aborted. If you know very early on it reflect that not to push files to acdc. But workflow is aborted after many jobs finished the data will be already in acdc db. You could change the code to update acdc after certain state "completed" But I think that will be quite a lot of change.

**Comment by amaltaro** [comment]
Actually, my concern is not whether there are ACDC documents or not. Instead, I would like just to avoid building acdc documents for those jobs that were aborted in the agents (that were pending or running).

**Comment by ticoann** [comment]
If you are just concern the jobs after aborted, I think it is pretty easy to add. I will take this issue. Don't spend time on this. :smile:

**Comment by amaltaro** [comment]
Exactly! Oh, that's great and you are the man!!! It's not urgent though, if you have more interesting things to work on, relax and go for that.

**Comment by ticoann** [comment]
Hi Alan, it seems actually we are doing that already. 
This is the place where files are uploaded to acdc server
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L194

and that is called by handleRetryDoneJobs
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L261

And the jobList is from
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L305

It only gets the job in retrydone status.  When workflow is aborted job status moved to "killed" and killed job doesn't move to "retrydone" status.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/Transitions.py#L27

So it shouldn't put the inputdataset when job is aborted unless I am missing something in the code.

**Comment by amaltaro** [comment]
Yes, you're right. According to this code aborted jobs should not go to the acdc server.
Maybe I aborted my tests yesterday just when a hundred of jobs were failing....
Closing this issue, thanks Seangchan!
