### ISSUE TITLE
outputDataset broken for TaskChains

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5847]
@vlimant just reported that both the ReqMgr API [1] and a couch view [2] is broken when:
 1. it's a TaskChain request with no AcquisitionEra (probably ProcessingString as well) in the main dict
 2. the request is still not assigned.

These views are being used to check whether there will be dataset collision (different requests creating the same output dataset).

It's quite important, but since today is the last day of validation and we've lived with that since ever, I would push it only for HG1506.

**Comment by amaltaro** [comment]
and these are the views/apis
https://cmsweb.cern.ch/reqmgr/reqMgr/outputDatasetsByRequestName/vlimant_task_B2G-RunIIWinter15wmLHE-00013__v1_T_150430_120421_6714

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byoutputdataset?key=%22/TprimeBToBW_M-1800_13TeV-madgraph/FAKE-v2/LHE%22

**Comment by vlimant** [comment]
the output curently is 
['/TprimeBToBW_M-1800_13TeV-madgraph/FAKE-v2/LHE', '/TprimeBToBW_M-1800_TuneCUETP8M1_13TeV-madgraph-pythia8/FAKE-v2/GEN-SIM']
and
{"total_rows":166842,"offset":146174,"rows":[
{"id":"vlimant_task_B2G-RunIIWinter15wmLHE-00013__v1_T_150430_120421_6714","key":"/TprimeBToBW_M-1800_13TeV-madgraph/FAKE-v2/LHE","value":null}
]}
that request might get assigned soon

**Comment by amaltaro** [comment]
@ticoann certainly a good bug to be closed by the next upgrade

**Comment by ticoann** [comment]
Hi Alan, Jean-Roch,  Sorry for the late reply. Second part of output dataset name B in /A/B/C, is constructed by combining Acquistion  Era and version,  so unless that is specified you won't have correct output dataset name. (Currently that is set when workflow is assigned).
So are you asking that acquisition era need to be set in request creation stage?

**Comment by amaltaro** [comment]
Seangchan, B should be
AcquisitionEra + "-" + ProcessingString + "-" + ProcessingVersion

for most of the workflows, these parameters are set during request creation.
Since it's broken only for TaskChain, I believe WMStats (or something else) is not picking these values from the inner dicts (Task1, Task2, etc)

**Comment by ticoann** [comment]
Alan, yes, you are right but ProcessingString is optional. 
what do you mean by "broken"? Is that acquisiton era is not picked up when task chain workflow is created but picked up when other workflow is created?  
One other question, can acquisition era be differ between the tasks in the same TaskChain?

**Comment by amaltaro** [comment]
> Alan, yes, you are right but ProcessingString is optional. 

Hmmm, I thought it was mandatory... Maybe it's mandatory only during assignment.

By broken I meant it gets the default value (FAKE) when there is no AcquisitionEra parameter defined in the main dict (during creation). It should get those from inside the tasks.

> One other question, can acquisition era be differ between the tasks in the same TaskChain?

Yes, that's possible. The same happens for ProcessingString, they can differ among different tasks.
