### ISSUE TITLE
DQMHarvest spec creates merge job instead of harvesting

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5849]
Everything with the new DQMHarvest spec "succeeds" until the job starts running on the worker node, where it fail with a segmentation fault or some kind.

The problems seems to be that this spec is creating a merge job instead, and so the PSet is missing the whole configuration basically.

**Comment by amaltaro** [comment]
I'm testing a possible fix in my VM (or at least something that will help me to understand it).
BTW, I put the PSet.py here:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/myPSet_GH5849.py

**Comment by ticoann** [comment]
In term of jobs need to be created, Shouldn't DQM spec create the merge job? I thought since input dataset is DQM dataset, we just need to merge those (with lumi filter).  I might be completely misunderstood the case. @hufnagel, Dirk, could you give me some advice on this?

**Comment by hufnagel** [comment]
Well, looking at the DQMHarvest spec, it creates a merge job because that's what you told it to do. That whole spec implements a merge workflow, not a harvesting workflow.

What are you trying to do here ? Have a DQM or DAQIO dataset as input and run a single harvesting job on it ? Or something more elaborate ?

**Comment by hufnagel** [comment]
https://github.com/hufnagel/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/DQMHarvest.py#L66

clearly tells it to create a merge configuration. The rest of the code setting up the task and steps also looks like more like merge than harvest.

**Comment by amaltaro** [comment]
What we want to do with this spec is:
 a) get an input dataset (it will be either a DQM or DQMIO datatier)
 b) harvest this input dataset
 b.1.) either a single job for the whole input dataset (in case of "multiRun" harvesting)
 b.2.) otherwise, one job per run (standard harvesting)

IMO that merge task is not necessary, we only want to create a "Harvesting" task and  logCollect/cleanup for it.

**Comment by hufnagel** [comment]
https://github.com/hufnagel/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L587

will show you how to set this up. The DQMHarvest spec needs to be changed accordingly.

**Comment by hufnagel** [comment]
The Harvest job splitter already supports a single (multirun) job per fileset or one job per run. You just need to figure out how to tell the workqueues that it needs to feed the whole dataset at once, not block by block.

**Comment by amaltaro** [comment]
Yep, I looked at this code in the past week, but it assumes the harvesting task will have a parentTask, which does not apply for this spec, since we want to directly create a harvesting job without any task dependencies.

**Comment by hufnagel** [comment]
Well, yes, that is different. Everything else is the same though.

**Comment by ticoann** [comment]
As far as I understood,
This is needed only for the case for the multi run harvesting job with some run lumi filter.
 1. original workflow creates DQM or DQMIO with multi run harvest.
 2. DQM spec uses those input with run lumi filter generates new DQM file specified run and lumi.

I thought input is DQM dataset we just need to merge that with the filter. But I guess I completely misunderstood.  (So we have turn the harvesting jobs over DQM input files, correct?)

**Comment by hufnagel** [comment]
The spec can support both a single multirun harvesting of a complete dataset or the standard one_job/one_run harvesting of a complete dataset. This should be selectable in the spec parameters.

Input is a DQM dataset, but there is no need to merge it, you just pass it directly to a DQM Harvesting task.
