### ISSUE TITLE
WMAgent still has DBS2 client as a dependency

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5856]
When installing WMAgent by RPM I see this:

Get:3 http://cmsrep.cern.ch cmssw/comp.pre/apt/slc6_amd64_gcc481/cms cms+dbs-client+DBS_2_1_9-comp6 1-1 [638kB]

No need for that anymore....

**Comment by alexanderrichards** [comment]
is the following sufficient?
https://github.com/alexanderrichards/cmsdist/pull/1/files

**Comment by alexanderrichards** [comment]
also I have some questions, please see the comments section of the PR:
https://github.com/alexanderrichards/cmsdist/pull/1

**Comment by ticoann** [comment]
Thanks Alex, updated this testbed.
https://github.com/cms-sw/cmsdist/pull/2110

**Comment by alexanderrichards** [comment]
This can be closed right now?
