### ISSUE TITLE
Need a new state in Request Manager

### ISSUE THREAD

**Issue by drkovalskyi** [dmwm/WMCore#5861]
Dear Developers,

we need a new state to indicate that a workflow is being worked on, but not ready to be assigned yet. In practice it means that we are transferring data or doing some other preparation. Since no production tools will have to act on this state, the change should be trivial and correspond to work done before a workflow is assigned.

To summarize, we would like to be able to the following state transitions:
assignment-approved -> staging -> assigned
instead of 
assignment-approved -> assigned

Thanks,
           Dima

**Comment by ticoann** [comment]
Hi Dima,
Is staging required for all workflows?
How does the state transition is made. Is there a script automatically change the transition?

**Comment by drkovalskyi** [comment]
Hi Seangchan,

this state will be used by auto-assignment tools for workflows that need some time-consuming procedure (in reality it's pretty much always data stage-in). This way we will have a clear split between workflows that no one acted on yet and need to be assigned and those that are not assigned because we are doing something.

Dima

**Comment by vlimant** [comment]
will go with unified integration with @vkuznet

**Comment by drkovalskyi** [comment]
Can you give more details on why it's closed? Is it implemented?

**Comment by vlimant** [comment]
it got closed in a "yearly" cleaning.
the communication was not optimal.

**Comment by drkovalskyi** [comment]
So it's not implemented? Can someone please clarify what will be done?

**Comment by amaltaro** [comment]
We're closing issues older than 2 years in order to do some house cleaning and make the project/issues more manageable.
As JR said, this is part of the unified into wmcore transition, but we can leave this open until we get the new request state implemented.

**Comment by amaltaro** [comment]
@drkovalskyi Dima, can we follow this up here: https://github.com/dmwm/WMCore/issues/9134
?

That issue was supposed to get implemented this month, but I just noticed we'll have to rethink it regarding the PU samples... Let me close this one.
