### ISSUE TITLE
Hybrid job-data-site matching for optimal use of T2-AAA-T1

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5864]
in between using the data location for making job-site matching criteria and ignoring any data location, there is the hybrid, which matches a good strategy of using T2 for digi-reco wihout having to have the input dataset locally (T2 dataops quota issue).
The essence is that job should have a white-list containing sites that hold the block being run over and sites that do not hold any of the blocks of the input dataset. that way we prevent accidental job inversion between sites holding blocks of input.
site A block 1
site B block 2
site C no blocks

jobs for 1 should white-list A and C.
jobs for 2 should white-list B and C.
never should a job for 1 be matching B.

it's a data-or-nodata matching scheme.

**Comment by hufnagel** [comment]
This currently can't be done in WMAgent. It can't be done at a very deep level because site overrides happen at data injection times. We lie to the system and tell it that all blocks are at A, B and C, there is no way the job to location matching can access the previous information.

We would have to switch to the "Tier0 style" site overrides also for WMAgent, which do the override at submission time. You then have the location of a jobs input and the sitewhitelist and can apply whatever algorithm you want (in principle).

**Comment by amaltaro** [comment]
If we manage to update the workqueue docs when it's been "Acquired" or "Running" by the agent (it already happens for Available docs), then we may implement a new feature in JobUpdater to read the local workqueue_inbox and update queued/pending jobs.
Though it's not a simple fix, but a new feature with major changes.

**Comment by hufnagel** [comment]
Wouldn't that still only update the whole workflow, not block by block ?

**Comment by amaltaro** [comment]
Ouch! I skipped this subtle detail, we would need to map a block (which maps to a fileset, if I correctly understand it) to all its created/pending jobs. Then the condor_qedit would need to be fired only against those specific jobIds (wait, do we have condor job id inside wmbs? if we don't, then game over)

**Comment by hufnagel** [comment]
That's painful and complicated. I would instead speed up the migration to the "Tier0 style" overrides as these apply the site overrides at the last possible moment, when the job is submitted.

We need to work out  a few problems these could cause in the job splitting logic. Job splitters would then see not all real+fake locations but only real locations.

**Comment by amaltaro** [comment]
From the last discussions in comp-ops egroup, this is what should be addressed in this GH issue:
> However, from the GH issue that you created, you want a model that
> would submit jobs to all the sites whitelisted (when the input block is
> not available on those sites) OR would submit jobs to the intersection
> of block location with the sites whitelisted.

nope : it's
"""
  to the union of sites not hosting any block for the workflow and site
hosting the block of the GQ.
"""

such that:
 i) blocks outside the whole site white list ==> submitted to all whitelisted sites
 ii) blocks present at least at one site white listed ==> union of the site hosting the block + all the other sites whitelisted NOT hosting any block.

**Comment by hufnagel** [comment]
Did anything happen on this ? Bringing this up again in email with Jean-Roch and planning to bring it up during Comp&Offl week, at the basic level we need a way to be able to assign workflows to sites where we both respect data location for some sites and ignore data location for other sites. Example:

sitewhitelist = [ "A", "B", "C" ]
trustsitewhitelist = [ "C" ]

Only C would be able to run all the jobs, A and B only would get jobs where the input is at A or B. You can even imagine a further tweak where you say that C is close (in network terms) to B but far to A. Hence C should only be able to run jobs where the input is at B. Example:

sitewhitelist = [ "A", "B", "C" ]
trustsitewhitelist = [ "C" :  { "B"} ]

Both of these are example syntax to show how this could work. I am not sure both syntax rules can be supported at the same time. Maybe we can just support the second syntax, but the downside is you always have to spell out all the sites, there is no default "I don't care" rule. Suggestions welcome to do this in an easier/smarter way.

The trustsitelist parameter would be deprecated with this (although we can keep it functional for now and only remove it later).
