### ISSUE TITLE
ReqMgr2 -> Assign workflows - assign button.

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#5876]
I followed these steps:
- Selected "Assign" option
- selected a workflow I just created (marking the checkbox on the left)
- then clicked on button "Assign"
This showed this error box: 
Invalid spec parameter value: '/store/data//TTToHplusBHminusB_csbar_M-90_7TeV-pythia6-tauola/GEN-SIM/SITE_TEST-v1' does not match regular expression /store/results/([a-zA-Z0-9\-_]+)/"

After that I cannot unmark the marked checkbox (I have to navigate back or refresh the page).

**Comment by ticoann** [comment]
Setting of Assignment field should only display the fields need to be added or modified. (And preserve previous set value) - Julian, could you specify which field need to be modified in assignment stage?

**Comment by vkuznet** [comment]
The fix for disabled attribute is here: https://github.com/dmwm/WMCore/pull/5895

**Comment by amaltaro** [comment]
The assignment validation part was fixed here (and in other PRs as well): https://github.com/dmwm/WMCore/pull/6648
