### ISSUE TITLE
move alan's deployment script under WMCore/bin/ and create the wiki for instruction

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5914]
Alan could you move your script to WMCore 
https://github.com/amaltaro/scripts/blob/master/deployProd.sh

**Comment by amaltaro** [comment]
I change it quite often (basically each time there is a new patch). Maybe twice per week. 
Are you sure? :-)

**Comment by ticoann** [comment]
Yes, this doesn't affect any thing for other code base and every one can use it. :smile: 
Also it doesn't have to change so often if we make patch apply optional? right? 
i.e. deployProd.sh -patch 5465,5342. something like that. :smile: 
But you don't have to change anything now. I just think this is useful to have in main repository. We can improve it later for different use cases.

**Comment by amaltaro** [comment]
... why I have never thought about this --patch 1234 .... ?!?! :-)
