### ISSUE TITLE
lfn check failed for existing logical_file_name

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMCore#5922]
Below existing logical_file_name cannot pass Lexicon.py and these are valid lfns. 
/store/Generators/2008/3/12/RelVal-tt3j-madgraph-1205358838/0000/069E0626-C9F0-DC11-8041-003048561854.root
/store/Generators/2008/3/29/RelVal-tt3j-madgraph-1206775163/0009/B87DC6FB-D5FD-DC11-8FDE-000423DD2F34.root

**Comment by yuyiguo** [comment]
another group of valid lfns cannot pass Lexicon:
/store/data/h2tb2007/testbeam_HCalEcalCombined/RAW/default_v1/h2.00015635.0008.edm.storageManager.0.0000.root

**Comment by hufnagel** [comment]
Tier0 LFNs don't work either anymore. Probably all related to #5905

**Comment by ticoann** [comment]
@yuyiguo, Hi Yuyi which call is failing? could you point me the error message.

**Comment by ticoann** [comment]
Tier0 is slightly cases, I had a bug in #5905 but not the lexicon problem. 
I looked that https://twiki.cern.ch/twiki/bin/viewauth/CMS/DMWMPG_Namespace
and the format provided for generator file is a little different. I guess we can support both but twiki page need to be updated as well. 
@belforte, Stefano, are you maintaining that twiki? Could you confirm the formats supported for generator file?
Thanks,

**Comment by ticoann** [comment]
Also if some one can confirm what each part maps in 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L24

/store/Generators/2008/3/12/RelVal-tt3j-madgraph-1205358838/0000/069E0626-C9F0-DC11-8041-003048561854.root

I guess '/2008/3/12/' date.

Is this some old style tier0?
/store/data/h2tb2007/testbeam_HCalEcalCombined/RAW/default_v1/h2.00015635.0008.edm.storageManager.0.0000.root

I can change the lexicon to pass these specific lfns but if some one can give a general rules. I will appreciate that. @ericvaandering, Eric?

**Comment by ericvaandering** [comment]
Why would we modify our current definition of what could be put into DBS to satisfy something put in in 2007 or 2008? Surely today we would have the first example go under /store/generator and the latter go into /store/group?

If needed, maybe we can have a "legacy" regex so we don't cause problems with data existing in DBS, but we don't actually want new data coming in with those patterns.

**Comment by hufnagel** [comment]
Aren't there already different checks for input validation and output validation ? We just need this to be a valif LFN for the former, not the latter.

**Comment by ticoann** [comment]
I think it is reading from dbs not putting to dbs? Yuyi, is dbs using the same lfn check for reading and writing as Dirk said? (FIY, We don't have validation /store/generator in lexicon currently - at least we can add that).

**Comment by yuyiguo** [comment]
DBS GET and POST are using different validation functions. However, for the POST calls that actually search the DB because one wants to supply DBS with a long list of lfns, lumis, or runs. We have no way to know it is a select or insert in validation level with current code.  

I  found another set of lfns that cannot pass lexicon.py.
'/store/data/h2tb2007/testbeam_HCalEcalCombined/RAW/default_v1/h2.00014493.0000.edm.storageManager.0.0000.root', '/store/data/h2tb2007/testbeam_HCalEcalCombined/RAW/default_v1/h2.00014494.0002.edm.storageManager.0.0000.root', '/store/data/h2tb2007/testbeam_HCalEcalCombined/RAW/default_v1/h2.00015535.0035.edm.storageManager.0.0000.root'

**Comment by ticoann** [comment]
I think we have to maintain 2 different validation for the post call as well (one for insert and one for select). Changing validation for 'insert' to read legacy data will cause wrong format to get inserted. 
Yuyi, could you point me the code where the validation occur for the POST call? If not possible to distinguish at the time of the validation occurs, can we revalidate before the insert call happens?

**Comment by yuyiguo** [comment]
This is where DBS call happends
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/utils/DBSInputValidation.py#L289

As I said that DBS has generic validation for POST and GET. But when POST is used for searching we have to use the POST validation.

I found there are a lot of existing lfns that could not past current Lexicon.lfn test.

**Comment by ticoann** [comment]
I was more talking about how the post calls the validation function not the validation function it self. Anyway, looking at the code, it doesn't seem to validate the same way for all post calls. (I might be wrong though)

i.e. for this post call instead of using the same validation you can use relaxed validation since it is reader option, isn't it?

https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/web/DBSReaderModel.py#L470

**Comment by belforte** [comment]
what exactly breaks if you do not change anything ? @yuyiguo  how did you find the LFN's in your initial posting ? Where they tripping something ?

**Comment by yuyiguo** [comment]
I was testing the limit on some of the DBS APIs to see what is the maximum lnfs I can have in a list and the API can be finished in reasonable time. So I just got random lfns in DBS, but when I used them for query, they could not pass input validation if the call was POST. This is because DBS POST call are using Lexicon.py. I will have to rewrite some part of the validation code not to use the Lexicon.py for searching the DBS. So far no one  compliainted so I guess these datasets I found was not popular ones.

**Comment by belforte** [comment]
indeed simulated datasets from 2008, or data imported from pre-Run1 test beam are very likely not to 
be searched for by anyone, especially not starting with a LFN fragment !
Anyhow using a relaxed regexp check when searching should be the best solution, IIRC we have this 
for dataset names already. Simply do not put too much effort into this and it is not worth any 
ad-hoc patching. By the way, user searches will start in DAS, usually, so need to make sure that if 
Lexicon has two regexp checks there, DAS uses the "correct" one.

**Comment by ticoann** [comment]
I discussed with Yuyi yesterday. We (WMCore side) won't change or maintain Lexicon for relaxed validation. DBS will handle for the search validation. Thanks, created the new issue https://github.com/dmwm/DBS/issues/475 Thanks
