### ISSUE TITLE
SiteState changes should not result in job kill

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5930]
well, not for all the cases. For example, if we want to set T2_CH_CERN_HLT to 'Down', but it has jobs "running" in a whitelist ['T2_CH_CERN','T2_CH_CERN','T2_CH_CERN_HLT'], the agent should not kill these jobs. From what I see here
https://github.com/dmwm/WMCore/blob/60dbd1d2626d41b5ad53923454f84ff8c9e3081b/src/python/WMCore/ResourceControl/ResourceControl.py#L63

jobs will always be killed.

**Comment by hufnagel** [comment]
Why do we want to set T2_CH_CERN_HLT to Down anyways. Is there a particular reason ? Seems a lot of operational overhead to me, isn't it better to make WMAgent work with the HLT as-is ?

**Comment by amaltaro** [comment]
HLT does not accept connections from outside CERN (actually there is a very specific network class).
So schedd (condor_shadow) at FNAL agents will always fail to connect to the pilots at HLT worker nodes.

**Comment by hufnagel** [comment]
I don't understand. If the agent can't submit to the HLT, setting the HLT to Down in the agent can't kill any jobs there. If the agent can submit jobs to the HLT, why would you want to set it to Down. I don't see the problem. One agent cannot see another agents jobs, can it ?

**Comment by hufnagel** [comment]
In any case, an agent should only kill jobs on setting a site A to Down if the jobs are actually running at that site A. Killing on whitelist is not useful at all under any circumstance.

**Comment by amaltaro** [comment]
Yes, you are almost right! The agent will only kill this job IF it's 1 and only 1 site in the Desired_Sites (which means, this is the location where the job is running)
https://github.com/dmwm/WMCore/blob/cb33dbb88f7844e8075de57c3168734f2ece7fad/src/python/WMCore/BossAir/Plugins/CondorPlugin.py#L747

The agent does not check the site the job is really running, only the DESIRED_Sites and ExtDESIRED_Sites.

**Comment by amaltaro** [comment]
BTW, closing this issue since it's not authentic.
