### ISSUE TITLE
Rewrite end of SetupCMSSWPSet with nested context manager

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5934]
In python 2.7 you can do with a, b and simplify this a lot.

**Comment by ericvaandering** [comment]
@hufnagel given #5579 and that WMCore is now on python 2.7, is it true that we will always run SetupCMSSWPSet with python 2.7? Or will be use 2.6 if we are running an old version of CMSSW?

**Comment by ericvaandering** [comment]
Code I want to simplify starts here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L745

**Comment by hufnagel** [comment]
We'll use 2.6 if we run an older version of CMSSW, but it would have to be really old. Not sure when exactly we switched, but it was a while ago.

**Comment by ericvaandering** [comment]
5_3 series for sure is still on 2.6. CMSSW 6_2 series I did not check. I don't think this is worth the risk.
