### ISSUE TITLE
Create task chain params for MaxRSS, etc

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5940]
similar to #5937

**Comment by AndrewLevin** [comment]
Hi Seangchan,

For release validation, it is not very useful to be able to set Memory per task if we cannot also set MaxRSS per task. I think you should make this issue high priority.

Andrew

**Comment by ticoann** [comment]
Hi Andrew, I will try to do this first then. Do you need this one on this production deployment?

**Comment by ericvaandering** [comment]
I don't understand the urgency. Are you not able to run somewhat inefficiently by just requesting too much memory?

**Comment by amaltaro** [comment]
Most likely there is a misunderstand here. With Memory being passed by task, we'll have the proper job matching and efficiently use of the CE queues. That's what is really important IMO.
MaxRSS is only used for job monitoring and, in the worst case a job will be killed by the batch system instead of WMAgent (in this case there is no logs back).

**Comment by AndrewLevin** [comment]
Yes, we are able to run the workflows inefficiently without maxrss per task.

**Comment by AndrewLevin** [comment]
No, Alan, the memory per task is useless unless we have also maxrss per task for release validation at least. We need wmagent to kill the jobs before they get killed by the site.

**Comment by ericvaandering** [comment]
Yes, up are correct.


> On Jun 2, 2015, at 10:07, Alan Malta Rodrigues <notifications@github.com> wrote:
> 
> Most likely there is a misunderstand here. 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>
