### ISSUE TITLE
PhEDExInjector stops silently

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#5942]
Once in a while PhEDExInjector stops working with the following symptoms:
- No new entries in the ComponentLog
- No error message in the ComponentLog either
- No error/warning in wmstats
- From outside the agent, there is no new file or subscription created on PhEDEX.
Usually shutting down and starting again the component is enough for solving the problem.
Though we need to be able to spot it from wmstats.

**Comment by julianbadillo** [comment]
A few examples from the last days:
https://cms-logbook.cern.ch/elog/Workflow+processing/20508
 https://cms-logbook.cern.ch/elog/Workflow+processing/20466
https://cms-logbook.cern.ch/elog/Workflow+processing/20307

**Comment by amaltaro** [comment]
It will most likely be fixed by #6538, we shall see...

**Comment by amaltaro** [comment]
Fixed by #6538
