### ISSUE TITLE
Reduce the amount of LogCollect jobs created

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5943]
Having seen frequently now that most of the tails in MC are created by logcollect, here is a suggestion.
send/create log collects to "jobs/blocks that failed" (whatever is the unit) and only send a small fraction of those with no error (ceiling of 1%), only if there are still production/merging on-going.

1% is too low, make it 5%, it should be far enough for the IMO non-existent usage of logs for successful jobs.

making it a parameter in the schema would allow to re-run a workflow with full logs, if ever need be.

**Comment by ticoann** [comment]
@vlimant, do you still need this or we can do as we discuss in the meeting? (separate state transition from log collect jobs and clean up jobs.)

**Comment by vlimant** [comment]
what you suggested sound very good.
I still think we could reduce the amount of logollect to create, but that's another discussion if they are not in the way of having the workflow announced

**Comment by amaltaro** [comment]
Seangchan, if we separate state transition from logCollect/Cleanup. Would we still update workloadSummary with the logCollect castor location after a workflow moves to completed?

**Comment by ticoann** [comment]
> Seangchan, if we separate state transition from logCollect/Cleanup. Would we still update workloadSummary with the logCollect castor location after a workflow moves to completed?

I think we have to make that way.

**Comment by ticoann** [comment]
> what you suggested sound very good.
> I still think we could reduce the amount of logollect to create, but that's another discussion if they are not in the way of having the workflow announced

The reason I asked, other people mentioned before that all the log collect are needed even though 95% of them won't be ever looked at. (We are even planning to implement meta data db which can search log location easily) I need to know whether this requirement is agreed on all the parties involved.

**Comment by ericvaandering** [comment]
We are not going to stop doing LogCollect jobs. Period. We are, in fact, trying to go the other direction and saving more data even from successful jobs since occasionally this is useful for physics debugging.

**Comment by vlimant** [comment]
you find me happy with Seangchan's proposal of making delivery time shorter

**Comment by ticoann** [comment]
Closing this and  new issue is created #5970
