### ISSUE TITLE
Inject Blocks in Phedex with group=DataOps

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5945]
If this https://github.com/dmwm/PHEDEX/issues/989 get solved, we should get the blocks injected to phedex under dataops group.

**Comment by amaltaro** [comment]
From what I see in the phedex discussion, injecting data with phedex group is a no go. @vlimant shall we close this issue?

**Comment by vlimant** [comment]
If one ask me : injecting data and leaving it un-own is a no go ; but I have no say.
There has been no objection it seems to inject and subscribe which @hufnagel said he could look at while changing PhedexInjector that would help leaving any dataops data own by dataops and accounted for.

**Comment by amaltaro** [comment]
Just thinking out loud... perhaps one way to keep these data/groups 'clean' would be by firing a move subscription when the workflow is *ready* to move to completed. So it would move all the produced files to a single place and clean up the 'working' sites.

**Comment by hufnagel** [comment]
Had no time to discuss this yet, but we should really close this issue as assigning ownership on injection is a no-go, but making a separate subscription might work.

**Comment by hufnagel** [comment]
We uses to work with move subscriptions, but they are not usable for all scenarios. Plus they still leave the block unassigned for some time (although admittedly that time would be short).

**Comment by vlimant** [comment]
@amaltaro : making a move when completed is one thing that would remove all the blocks left behind, but would also remove sources/routings for further dispatching of the dataset for analysis or further processing. data is still left un-owned at a site for some relevant amount of time, time at which a site admin willing to find space could remove un-owned data and badly interfere with production. We also have used those blocks leftbehind to allow more sites to participate in a single workflow and distribute the load.
There are no more moves ; only transfers and deletes.

@hufnagel : separate subscription is what I had in mind.

**Comment by amaltaro** [comment]
Then creating block subscriptions seems to be the better approach here, though something tells me creating hundreds or thousands of block subscriptions per day will cause problems somewhere to someone :-)

**Comment by vlimant** [comment]
I had the same worry, but it does not seem to be a problem for phedex (see the GH issue)

**Comment by vlimant** [comment]
this is very relevant, as the production blocks are only subscribed to dataops in an adhoc way these days.

**Comment by amaltaro** [comment]
Summarizing the discussion on that phedex ticket:
* the agent should make a block-level subscription after a block gets *injected* at that same site.

Question is, different datasets (data tiers) have different phedex groups, while WMCore only supports a single PhEDEx group for the whole workflow (actually one group for custodial and one for non-custodial). Unless we couple PhEDEx group to output dataset (or datatier), there isn't much that we can do here. Did I miss anything?

In addition to that, with the migration to Rucio, we might just decide that this issue is no longer relevant and close it (?)

**Comment by vlimant** [comment]
leaving things opened for long enough makes it eventually not relevant anymore indeed.
fingers crossed with Rucio.
