### ISSUE TITLE
Failed jobs report a wrong number of cores to dashboard

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5957]
only and only when the job fails. Here is an example [1] based on this template:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/Integration/TaskChain_Task_Multicore.json

So, we got 74 failures for RECODreHLT (8 cores), but the failures in dashboard appears under the 1 core bar. 

@ericvaandering I remember you mentioned somewhere that the # of cores was only reported in the end of the job. Do you think it's related here?

[1]
http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=&submissiontool=&application=&activity=integration&status=&check=submitted&tier=&date1=2015-05-29+10%3A01&date2=2015-06-02+10%3A01&sortby=cores&scale=linear&bars=20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=wmagent_amaltaro_TaskChain_Task_Multicore_HG1506c_Validation_v1_150529_151843_4246&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

**Comment by ericvaandering** [comment]
Shouldn't be. There was a patch in April https://github.com/dmwm/WMCore/commit/dfb0ebeca9a4fdf400470adf8c2a35ca0ac0de9c that should predict the number of cores. Are we running with it?

**Comment by amaltaro** [comment]
Ahaaa! I knew you had something up your sleeve. That must be it. This fix was not backported to 1.0.5.
I'll take care of it and close this issue if that gets fixed. Thanks

**Comment by ericvaandering** [comment]
I had to go look at the code history since I thought you were right. :-)

**Comment by amaltaro** [comment]
Probably that patch fixes another issue, I still see the wrong number of cores reported to dashboard.
I took a quick look, but I could not spot yet how to get the number of cores here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L485

If you don't pick this one, then I can investigate it in the next week :)
