### ISSUE TITLE
Missing TotalInputLumis from reqmgr_worklod_cache

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#5969]
Once in a while we get one or two workflows missing this parameters
TotalInputLumis, TotalInputFiles, TotalInputEvents and TotalEstimatedJobs
in the reqmgr_worload_cache page
Here is an example
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_EXO-RunIISpring15DR74-00093_00043_v0__150511_200312_3690

**Comment by julianbadillo** [comment]
Another more recent one:
https://cms-logbook.cern.ch/elog/Workflow+processing/20805

**Comment by julianbadillo** [comment]
Another one:
https://cms-logbook.cern.ch/elog/Workflow+processing/20807

**Comment by julianbadillo** [comment]
And one more:
https://cms-logbook.cern.ch/elog/Workflow+processing/20812

**Comment by julianbadillo** [comment]
Two more recent ones:
https://cms-logbook.cern.ch/elog/Workflow+processing/21071
https://cms-logbook.cern.ch/elog/Workflow+processing/21070

**Comment by vlimant** [comment]
more of those are observed.

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, this this just happen again? Could you point some of the examples?
TotalInputLumis, TotalInputFiles, TotalInputEvents and TotalEstimatedJobs are one time update (GQ is trying to update this one time not periodically, I wonder whether it is related to cmsweb unresponsive problem we had)

**Comment by vlimant** [comment]
related to #6258 6258

**Comment by vlimant** [comment]
TotalInputEvents is missing from the workload of pdmvserv_task_EXO-RunIISpring16reHLT80-01212__v1_T_160623_145751_1432 
 TotalInputEvents is missing from the workload of pdmvserv_task_EXO-RunIISpring16reHLT80-01434__v1_T_160623_161521_288 
 TotalInputEvents is missing from the workload of pdmvserv_task_B2G-RunIISpring16reHLT80-00894__v1_T_160623_001722_5648 
... and the list grows. It's all irrelevant for operation as a fallback is in place but might be a sign of something really bad happening
