### ISSUE TITLE
Make a state transition without waiting LogCollect and Cleanup job to finish.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5970]
discussed here: #5943.
Plan is 
For completion status - don't wait for logcollect and clean up job finished. So it can be closed-out and announced without those jobs finished.
For achieved-status, it will wait for the log collect job to finished.
Add API for logcollect and cleanup job status checking for give workflow (REST api)

Need to look carefully since this is related db clean up. (We might need to have parallel state tracking log collect and clean up jobs.)

**Comment by AndrewLevin** [comment]
Hi Seangchan,

For relval wmagent, I think disconnecting state transitions from logcollect jobs is not the right thing to do. There is a large rate of failures in relval workflows, and we need to provide log files when we announce the workflows. Would it be difficult to configure in the config.py file whether you want this feature to be on or off?

Thanks. 

Andrew

**Comment by ticoann** [comment]
Hi Andrew, 
Announce state is in ops control. It doesn't even have to be configured. How do you announce the workflow. Do you check certain conditions before announced.  The change should only affect completed status. For close-out and announced, it is currently controlled by ops. (Which eventually need to be moved in reqmgr), For now, you can add the condition whether logCollect jobs are finished or not before workflow gets announced.  I will try to provide simple api to check that. Is that sufficient compromise?

**Comment by AndrewLevin** [comment]
Hi Seangchan,

Yes, an API to check if the logcollect jobs are finished is a sufficient compromise. Thanks.

Andrew

**Comment by vlimant** [comment]
What is the milestone on this one ?

**Comment by amaltaro** [comment]
This has been done and is in production for a few months now.
