### ISSUE TITLE
Do we use 'Analysis' task type?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5979]
Just wondering whether we could clean up this part of the code (maybe it is from the era where CRAB3 would be using ReqMgr...).
@ticoann @ericvaandering

**Comment by ericvaandering** [comment]
It was from that era. Let's get confirmation from @mmascher that CRAB3 does not use this part of WMCore. They certainly use the WMSteps.

**Comment by mmascher** [comment]
No we do not use it, feel free to clean it up.

**Comment by amaltaro** [comment]
Fixed by #7436
