### ISSUE TITLE
handling threshold for taskchain

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5983]
to solve gracefully, as discussed during the workflow team meeting, an issue with operating taskchain with multiplication of number of jobs in TaskN(N>=2), it would be great if total estimated number of jobs for a taskchain were accounted for when comparing to site thresholds ( compared to current number of jobs, corrsponding to Task1, which can be very small). This would help in not having a site acquiring too many taskchains and ending up with an immense number of jobs to process for subsequent tasks, and be stuck.

**Comment by amaltaro** [comment]
Giving a second thought to this issue now, IMO it would be something extremely hard to be done.

Perhaps, a better/easier approach here would be, for each task1 job, do a round robin on the site whitelist and add only ~3 sites to the DESIRED_CMSSites. This could - maybe - be done via a flag during assignment. What do you think?

**Comment by vlimant** [comment]
Given the parameters of a taskchain, it is possible to get an rough estimation of how many jobs will spawn from one job of task1. We can work out this number together. Is that simpler then once we have that number ?
Picking n at random from the whitelist means that we can still overlay several taskchains on a site that won't be able to absorbed the many jobs of the subsequent tasks ; it might help but we'd have to estimate what would be the residual rate of stuck workflows.
How about #5982 ?

**Comment by amaltaro** [comment]
I don't think it can be done. It completely changes the way WMAgent works. It does not estimate number of jobs, it "simply" pulls down work from GQ and do the job splitting and create jobs. It has no track of the next task for the same workflow. 

Moreover, I could bet that if we develop what is asked here, people would start complaining that workflows are moving slower than normal, since it would probably run in a smaller site whitelist regarding the one provided during assignment.

> Picking n at random from the whitelist means that we can still overlay several taskchains on a site that won't be able to absorbed the many jobs of the subsequent tasks...

This would be the easier option that could be accomplished this still year. If you think a site cannot absorb the amount of work, why do you add it to the whitelist? Just don't.

**Comment by vlimant** [comment]
As discussed during the workflow meeting : not adding to the whitelist, means one has to calculate the total ammount of work the task is going to create, and do the site whitelist accordingly : i.e. do the site threshold matching above.
Furthermore, even though one estimate the amount of work and matches to site, this would probably not reduce the whitelist much (for the example we are talking about 1 task1-job pulling 500 task2-jobs, meaning we'd vetoe site with less than 500 slots) one would have to be carefull of not sitewhitelisting twice this site in a row otherwise we'd be back to square one.
It does sound like something for this threshold matching algorithm, but of course things can be done in a much more complicated way "outside" of the agent if we cannot have the appropriate technology inside.

How about #5982 ?

As for "people start complaining", if the matching is done using the work amount estimate, then it will go faster anyways than now were a T2 has taken all the first jobs of many taskchains and is left with thousands of subsequent jobs to go through.

**Comment by hufnagel** [comment]
Number of jobs is kind of irrelevant anyways. Number of jobs can be one to a gazillion, depending on how you set your job splitting parameters (independent of input sample). What matter is the amount of work a request will do (number of jobs x average time of a job). Only the requester knows this, the agent can't look into the configuration.

**Comment by vlimant** [comment]
Hi Dirk, from the information in the request there is a way to get the estimate of amount of job and work.
How does the threshold work ? In terms of workload or number of events ?
If one introduce a jobfactor parameter we can estimate (multiplication factor in number of jobs) then this can be used to check against thresholds and accounting, maybe

**Comment by hufnagel** [comment]
Thresholds are purely for number of jobs. It doesn't have any concept of looking inside a job, its for the number of jobs *right now*. It also can't distinguish between single and multicore jobs, which will make setting useful thresholds for the T0 and T1 tricky.
