### ISSUE TITLE
Add one case to the creation failures in the EventAwareLumiBased splitting algorithm 

### ISSUE THREAD

**Issue by lucacopa** [dmwm/WMCore#5985]
There is a bug in the EventAwareLumiBased splitting algorithm. When a job is going to process a file with a single lumi and the avgEvtsPerLumi > eventLimit (default 20k), we move it to CreationFailure, which is correct. The problem is that if the input file has more than 1 lumi and still avgEvtsPerLumi is higher than the limit, that job is not moved to CreationFailure. Only input files with a single lumi are affected by this condition:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L163
Consequence, in the tier0 we got reco jobs processing files with too many events, even using the maximum splitting. This results on a high expansion factor from the repacked data size, then the jobs are removed by condor because they are using too much disk.
We need to add a case where the input file has more than 1 lumi and the avgEvtsPerLumi is higher than the limit in the algorithm.

**Comment by hufnagel** [comment]
@lucacopa , we discussed this and this is actually the desired behavior. With multi-lumi input, even if the average per lumi is too high, some lumis could be ok. In order to recover them we need to run jobs on each lumi.

Can this be closed ?

**Comment by lucacopa** [comment]
Yes, this can be closed.
