### ISSUE TITLE
Populate the wmbs_location_senames table with PNN

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6004]
This is needed for Alex' patch to work. 
Eventually we need to rename wmbs_location_senames to wmbs_location_pnns, but for now don't change the schema. To make this compatible with old agent, we need to insert both pnn and se names in the table.

Following function need to return {cmsName: [pnns], ....}
https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control#L98
especially,
https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control#L109

What happen was when PNN is returned in FWJR. JobAccountant failed to update the file locations for output files since following call fails which is called by JobAccoutant.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py

**Comment by alexanderrichards** [comment]
@ticoann 
I have made the first change that you suggest, namely
> Following function need to return {cmsName: [pnns], ....}
> https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control#L98
> especially,
> https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control#L109

see https://github.com/dmwm/WMCore/commit/1c5d14c82bd9a9b31fe28a936ed5ff02b0bdba7b

---
However I have an issue with the second:
> What happen was when PNN is returned in FWJR. JobAccountant failed to update the file locations for output files since following call fails which is called by JobAccoutant.
> 
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py

So I looked at this file but se_name is set from the input locations as:
```sql
WHERE wls.se_name = :location
```
Here: https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobAccountant/AccountantWorker.py#L837

However searching that file for where ```self.fileLocation``` is set I only see the following:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobAccountant/AccountantWorker.py#L117
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobAccountant/AccountantWorker.py#L147

in both places it is set to None so my first question is this: "Is this ever not None?"

however if I look at the first argument (fileLocations) in: 
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobAccountant/AccountantWorker.py#L836

then I see this set to what I think will be the PNNs:
```python
fileLocations.append({'lfn': lfn, 'location': wmbsFile.getLocations()[0]})
```
Here: https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobAccountant/AccountantWorker.py#L802

This means that the lfn is a list and so the binds are taken from is as in:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py#L23

Therefore as far as I can tell this file doesn't need to be changed as the PNNs should already be coming in from the above AccountantWorker.py code.

**Comment by ticoann** [comment]
Hi Alex,

> see 1c5d14c
Thank you,

> 
> However I have an issue with the second:
> 
>     What happen was when PNN is returned in FWJR. JobAccountant failed to update the file locations for output files since following call fails which is called by JobAccoutant.
> 
>     https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py
> 

Sorry, there was misunderstanding. This is not second issue. I was trying to explain what happen since we are not putting pnn in wmbs_location_sename table. The there is one issue and it should solved by your patch.

I am sorry I think I only talked about second issue on the email. Not here. (let me find the email)

**Comment by ticoann** [comment]
Here is the second issue.

However, there might be more problem when log collect jobs come back. I don’t think it will set the file location correctly for the log collect job. 

InputDatasetLocations only set for initial input dataset is set when the jobs comes back and location is set from fwjr this will be empty. 

I just looked at the code again. I think getting location that way is wrong. 
First, we can't use dataset location for the jobs since there is not all the files in the same dataset  have the same location.
Secondly location is resolved when job is submitted not job is created.

I think you had to add these actually with the same reason wmbs_location_senames are not populated.
I would suggest revert all the code getting InputDatasetLocations and run the test again with 
https://github.com/dmwm/WMCore/commit/1c5d14c82bd9a9b31fe28a936ed5ff02b0bdba7b

**Comment by alexanderrichards** [comment]
@ticoann this can be closed now right?
