### ISSUE TITLE
subscribe any new block we inject from WMAgent to DataOps ?

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#6005]
Followup to #5945. Talked to Nicolo and this could work technically.

Basically, when the WMAgent creates a new block in PhEDEx, ie. when file injections create a new block, immediately make a block level subscription for that block to the site we inject it at under DataOps.

This would help with space accounting for DataOps. Not sure if it would break anything else.

**Comment by amaltaro** [comment]
Please no, it would create an insane amount of mails/subscriptions. It looks much more easy - for me at least - to allow phedex group for data injection, since when we are injecting a block against a specific site, we are also saying this data is available there...

**Comment by hufnagel** [comment]
You can make a subscription without mails...

**Comment by hufnagel** [comment]
Data groups at injection time is a absolute no-go because injection is a file level operation, which ownership is recorded at block level. You need separate calls for them.

**Comment by amaltaro** [comment]
Hm, anyways I wonder if there would be any impact handling big datasets with 2k different subscriptions, that looks ... not clean to me.
But don't we have 2 separate calls anyways? We need to inject either a block and its files into TMBD.

**Comment by hufnagel** [comment]
You inject FILES (and this might or might not create a new block). You subscribe BLOCKS. Very different things.

Nicole said the extra subscriptions should be manageable. They would be temporary anyways because most of the data DataOps produces is eventually moved somewhere else for aggregation purposes, right ? That would remove the individual block level subscriptions from the system.

**Comment by amaltaro** [comment]
How the block names get defined them? When the agent injects file, does it get back the block name to which the file was injected? Thinking how we then have the same block name between DBS and PhEDEx...

Lots of things have changed in operation and I'm not sure anymore whether there is a final move subscription to aggregate data. @vlimant for sure knows that.

**Comment by hufnagel** [comment]
Not sure myself about your first question. The agent somehow gets the block name, not sure if that's a return from the file injection, it creates it upfront or it specifically checks for it. These three things come to mind. @ticoann , any comments on this ?

**Comment by vlimant** [comment]
There is no "final move" for various practical reasons irrelevant to the question of whether should dataops own a block dataops inject

**Comment by hufnagel** [comment]
Without a final move this needs to be rethought. We cannot just leave blocks owned by DataOps scattered across the sites. At the very least all these subscriptions would need to be changed to be AnalysisOps. DataOps has limited space, we need to cleanup after ourselves.

**Comment by vlimant** [comment]
#5945 """There are no more moves ; only transfers and deletes"""

**Comment by hufnagel** [comment]
My statement stands, DataOps doesn't have enough space available to them to not cleanup (where cleanup can be delete or subscribing to a different group) data it produces. The DataOps space is designed to keep processing input samples and to temporarily store processing output. Not permanently store processing output.

**Comment by vlimant** [comment]
agreed, hence the deletes.

**Comment by ticoann** [comment]
duplicate issue #5945

**Comment by vlimant** [comment]
May we please re-open this and discuss this more ?
