### ISSUE TITLE
storage plugins have inconsistent signatures for doTransfer() 

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#6011]
from https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2363/2/2/1/4/1/3.html 

On 06/18/2015 12:09 PM, Andrea Sciaba' wrote:> 
> *** Discussion title: Computing Operations
> 
> Hi Justas,
> 
> there is a problem with the newest WMCore, the various storage plugins
> have inconsistent signatures for the doTransfer() method.
> I wanted to use the new interface for SAM but I cannot without hacking
> the WMCore code.
> 
> Cheers,
> 
>          Andrea
> 
> On 17-Jun-15 10:51, Justas wrote:
>>
>> *** Discussion title: Computing Operations
>>
>> Hi All,
>>
>> For SAM tests to use gfal2, they have to update to newest WMCore version
>> but newest WMCore does not have tag created yet with this fix and
>> without it it will not work:
>> https://github.com/dmwm/WMCore/commit/b9626711bc154ed20d40729429244e641b2cbf87
>>
>> Out of topic:
>>
>> For David`s case, this is the line which says to use srmv2-lcg plugin
>> from WMCore and which uses lcg-cp
>> https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1519
>> Direct stageout in CRAB3 does not read site-local-config.xml and uses
>> lcg-cp. So if this transition is starting now, we also have to change
>> CRAB3 code to use gfal2 and have fallback to lcg-cp.
>>
>> Cheers,
>> Justas
>>
>> -------------------------------------------------------------
>> Visit this CMS message (to reply or unsubscribe) at:
>> https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2363/2/2/1/4/1.html
>>
> 
> -------------------------------------------------------------
> Visit this CMS message (to reply or unsubscribe) at:
> https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2363/2/2/1/4/1/3.html
>

**Comment by hufnagel** [comment]
All the changed plugins are in the Plugins directory, which AFAIK no one is using anywhere. All sites use the Backends directory implementations.
