### ISSUE TITLE
AWS workflow (details to be determined)

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6051]
We need a GEN/SIM/DIGI/RECO/MiniAOD producing workflow spec that may need several cmsRun steps.  Exact details are still to be determined depending on what we can fold into a single cmsRun.

**Comment by amaltaro** [comment]
Hmm, that is going to be a nice challenge/development :-) It'll be basically a taskChain spec but mimicking the KeepOutput (actually drop) from ReDigi spec.
Eric, do we have a timescale for this one? I guess it's for September's cycle?

**Comment by ticoann** [comment]
I think we should start this as soon as possible since this would affects whole chain.
