### ISSUE TITLE
Review what's stored in couchdb wmagent_jobdump/fwjrs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6052]
Since this information is going to be stored in WMArchive in the near future, we should review (also based on users feedback) what we are storing in those documents and make sure we have important and useful information over there.

Looking at one example (not very good btw), I can see lots of fields that we could basically drop, as 'analysis', 'cleanup', 'performance' for logArch and stageOut steps, etc etc

**Comment by yuyiguo** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/1975/1/1/1/1.html. please refer this link for monitoring info that people like to see in WMArchive DB.

Also, we have some thing like below in W-FWJR:
'storage': {'readAveragekB': 5.1022841432000003,
                                                            'readCachePercentageOps': 0.0,
                                                            'readMBSec': 0.022085570792900001,
                                                            'readMaxMSec': 7262.9799999999996
                                                             ...
We need to round the decimal point numbers to a reasonable precision. I assume this will same some space for us because we get a lot for data.

**Comment by yuyiguo** [comment]
need to add below items into w-FWJR if they are not there: (comment from David Lange)
- the date/time the job ran (e.g., start,stop in UTC)
- the CMSSW version used (maybe this is acquisition era?)-
- information about the CPU (e.g., SystemCPU info in the FJR)
-Only LFN is needed, if LFN is not present then PFN can be used. W-FWJR currently have two lfn and pfn for each. PFN can be reconstructed from LFN.

**Comment by yuyiguo** [comment]
comments from Andrew Levin:
- Inserting to WMArchive DB has to be robust. Losing data is not acceptable.
- WMArchive must have a flexible schema to allow adding or removing fields.  
- retrieving histograms of time per event, rss, and total job time like what is now in the workflow summaries.
- retrieving number of jobs, number of failed jobs, and failed jobs organized by cause of failure in the format that wmstats currently has.
- retrieving the lfn of a log file for a failed job.
