### ISSUE TITLE
About the regular expression used to validate datasets

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#6054]
Hi,

I have a question, CRAB3 is using this regular expression to validate the input dataset provided by users:

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L78

I just noticed with @jmarra13 that things like `/Getlogout` matches (a user put that as input dataset), so I am wondering if this is the correct regular expression to use, and what is DBS is using to validate a dataset name.

Infact, DBS answer with `HTTPError: HTTP Error 400: Invalid Input Data /Getlogout...: Not Match Required Format` when we query it using the `listDatasets` API, which makes me think DBS is using a different regexp.

@yuyiguo , do you know what we should use?

**Comment by amaltaro** [comment]
Marco, what is the complete dataset name set by the user?
Looking at the PrimaryDataset only, I see no problem setting it to "Getlogout", most likely the error is coming from another part of the DS name.

**Comment by mmascher** [comment]
The user set up just `/Getlogout`. That's the complete dataset.

I would like to understand if `HTTPError: HTTP Error 400: Invalid Input Data /Getlogout...: Not Match Required Format` means that the dataset we pass to `listDatasets` is not mathing a regexp (and therefore which one DBS is using), or it means an error in a second step because no datasets were found (and in this case the validation is ok).

Depending on the answer we would either update and use the same regexp used by DBS, or catch this exception.

**Comment by belforte** [comment]
We should not accept a dataset name that does not have more slashes ! /A/B/C
How can /Getlogout pass ?

**Comment by belforte** [comment]
@mmascher are you confusing primaryDS with DS ? please, write down exactly which query fails, where... etc.

**Comment by mmascher** [comment]
Hi Stefano,

I am not confusing DS and primaryDS, I would like to know which regexp DBS is using to validate an input dataset since I suspect the one used by crab3 is wrong (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L78)

**Comment by yuyiguo** [comment]
DBS validation for dataset:
1. read
https://github.com/dmwm/DBS/blob/d58e4fe7be87a6f84da4f246523641c9988ba1ef/Server/Python/src/dbs/utils/DBSInputValidation.py#L18

2. writer
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L168

**Comment by mmascher** [comment]
Thanks yuyi!

**Comment by mmascher** [comment]
Reopening since I have one more question. Isn't this regex in Lexicon.py @yuyiguo ? Can we put it there?

**Comment by mmascher** [comment]
I found something similar: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L167 ? I did a pull to use that regexp. That's the one we use to validate what the user pass as inputDataset, the input dataset he wants to analyze. If that's corrrect maybe DBS can use it as well (and maybe modify the value of the regexp if necessary)

**Comment by yuyiguo** [comment]
The function ( https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L168) used in DBS uses  https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L167 . So DBS and crab are using the same thing.

**Comment by mmascher** [comment]
Closing, even though from the link @yuyiguo provided in her previus commenr (https://github.com/dmwm/WMCore/issues/6054#issuecomment-135475550 and https://github.com/dmwm/DBS/blob/d58e4fe7be87a6f84da4f246523641c9988ba1ef/Server/Python/src/dbs/utils/DBSInputValidation.py#L18) it seemed to me that DBS was using a different regexp (not importing the one from WMCore. But I trust her that now we are using the right thing.

**Comment by belforte** [comment]
Marco: DBS uses Lexicon to validate writes, but uses something different to validate reads, because it has to allow to read old datasets written years ago with horrible-names-which-were-not-following-any-rational-scheme

**Comment by yuyiguo** [comment]
Marco: DBS writer is using Lexicon.py for everything, but reader is using DBS special one for the exact the reason said by @belforte ,

**Comment by mmascher** [comment]
Thanks! More clear now
