### ISSUE TITLE
Combine workload summary from agent instead of replacing it.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6057]
When workload summary created it replaces the data instead of combining it. 
(I thought there is issue created before but I couldn't find it)

**Comment by amaltaro** [comment]
We have this issue created #4483. But maybe we can fix this issues first and then work on improvements. It's up to you ;-)

**Comment by ticoann** [comment]
Thanks Alan, I knew there was issue like that. :smile: But I think it is missing this part on that issue.
Anyway, we have think this with other issues you pointed.
