### ISSUE TITLE
possible finer grained job monitoring for WMStats

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#6061]
This is a place holder issue for potential finer grained job monitoring possible due to this CMSSW change

https://github.com/cms-sw/cmssw/pull/10056

This would allow the job tracking to not only get status information from jobs in HTCondor (pending, running, done), but also extract job progress information while it is running. We could extract this information in the job tracking and then update it in couch. I would not move on this unless there is a clear and compelling use case how operations would benefit from this additional information though.

@ticoann @ericvaandering , just FYI for now, please attach labels and milestones as you see fit.

**Comment by PerilousApricot** [comment]
If the attributes are there "anyway", bolting this to glidemon.cern.ch/gwmsmon.cern.ch would be rad.

**Comment by ericvaandering** [comment]
Glidemon is not going to be used by users for CRAB after September.

**Comment by PerilousApricot** [comment]
Oh that's a shame, I love that site to pieces :(

-- 
Sent from Gmail Mobile

**Comment by ericvaandering** [comment]
Apparently now dashboard can do all that it can. But it won't be turned off, exactly, so you may be able to use it.

**Comment by PerilousApricot** [comment]
Gotcha. Hopefully, future changes to the ads, etc.. will keep glidemon
functional for a long long time.
