### ISSUE TITLE
ReqMgr2 -> Prevent when a request tries to create an invalid data tier on DBS

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#6062]
With current ReqMgr:
- If a request comes with a non-existent datatier in DBS, it will run but the events won't be uploaded to DBS, hence creating errors inside DBS3Upload.
What we need:
- if a request comes with a non-existent datatier in DBS, it will be failed after being assinged (or after being created).
@vlimant

**Comment by amaltaro** [comment]
Fair enough! I'm cooking something that will fail assignment if the datatier is unknown by DBS.
