### ISSUE TITLE
Create a fine-grained permissions to ReqMgr2

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6072]
If I looked at the right file
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Auth.py

it seems the only permissions distinctions are for: creating a request (new), approving (assign-approved) and assigning it (assigned).

If someone wants to reject a request, then this person needs to have full privileges (ReqMgr: Admin).

My suggestion would be (for ReqMgr group):
- User: should be able to create, approve and reject workflows. nothing else.
- Operator: should be able to create requests and change their status to anything that is not *-archived
- Admin: full access.

@ticoann does it make sense?

**Comment by amaltaro** [comment]
And two more comments:
 1. We need to keep FacOps: web-service, since this one is used by cmsweb.
 2. The same distinctions/privileges should apply to couch docs, though I'm not sure how hard it is (do we need to create a validate-func to each design doc?).

**Comment by ticoann** [comment]
Hi Alan, Yes I agree what you said.
The plan was, make this configuable for now it is hard coded
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Auth.py 

Base logic are following.
1. Authentication group and roles are not hosted in reqmgr2 unlike reqmgr1. (It uses the groups and roles from sitedb).
2. permission is tied to group and roles as well as request type. (So we define permission for those combination) i.e. you set set specific group, and/or role to approve StoreResult request but that group won't have approve privilege for other types of request.  
(It doesn't have user level and individual request level control, (i.e. only user who create the request can reject request. - I don't think we need that level of control, but we can add it if it is absolutely necessary.)

**Comment by amaltaro** [comment]
Thanks Seangchan! Individual request level control is just too much in my opinion as well.

About permissions being tied to groups, did you mean physics group? If so, IMO we could skip it as well, currently there are only a few people creating workflows, I'd go for a single group, easier to manage.

**Comment by ticoann** [comment]
group and role here is just sitedb group and roles, I am not sure how groups and roles defined there. But it is pretty flexible to define groups and roles, right?

**Comment by vlimant** [comment]
good !

**Comment by ticoann** [comment]
@vlimant, Jean-Roch could you give me the list which one needs which permission to have.

Here is some examples

https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_auxiliary/PERMISSION_BY_REQUEST_TYPE

Permission can be controlled by request type. i.e. 
For StoreResult type.
If state transition not specified. DEFAULT_STATE permission will take over.

```
"StoreResult": {
       "assigned": {
           "group": [
               "reqmgr",
               "facops",
               "dataops"
           ],
           "role": [
               "developer",
               "admin",
               "data-manager",
               "production-operator",
               "web-service"
           ]
       },
       "new": {
           "group": [
               "reqmgr",
               "facops",
               "dataops"
           ],
           "role": [
               "developer",
               "admin",
               "data-manager",
               "production-operator",
               "web-service"
           ]
       },
       "assignment-approved": {
           "group": [
               "reqmgr",
               "facops",
               "dataops"
           ],
           "role": [
               "developer",
               "admin",
               "data-manager",
               "production-operator",
               "web-service"
           ]
       }
   },

```

**Comment by amaltaro** [comment]
Reopening this issue because this is something in our radar for some time now. Let's target it for March maybe

**Comment by amaltaro** [comment]
In face of: https://github.com/dmwm/WMCore/issues/11190, this now becomes higher priority and we need to make sure it's functional. We might want to review how that permission document gets created in reqmgr_auxiliary db, given that I see it only in CMSWEB production but not in testbed.
