### ISSUE TITLE
Avoid drain sites if SSB is unavailable (AgentStatusWatcher)

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#6075]
@amaltaro 
In past days we have an unavailability in SSB metrics, resulting in AgentStatusWatcher setting several sites in down, therefore failing several jobs.
The component logs were something like[1]
However the SSB status for the sites was not "down" or "drain", it was just empty.
It would be better that AgentStatusWatcher  avoids switching a site from "normal" to "down" on the agent unless it's explicit on SSB (and skip the site if the metric is empty).
This will impact in the site initialization (everything should be down by default?)

[1]
2015-07-22 12:09:02,222:INFO:ResourceControlUpdater:Only SSBsites, forcing site T2_UK_London_IC to Down
2015-07-22 12:09:07,826:INFO:CondorPlugin:Retrieved 22296 classAds

**Comment by amaltaro** [comment]
There is a configuration for that:
config.AgentStatusWatcher.onlySSB = False

this forces AgentStatusWatcher not to take any action when a site status is
not in SSB (aka, status won't change in the agent).

About site initialization, I believe all the sites are inserted into RC with state = Normal.
We could then force it to insert sites in Down state... (?)

**Comment by amaltaro** [comment]
Fixed by #6128
Julian or Seangchan, close this issue please.

**Comment by amaltaro** [comment]
Already fixed @ticoann please close it
