### ISSUE TITLE
Create a couch view for pileup datasets

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6083]
This will be needed for DDM (possible other "customers" as well) to properly manage DataOps space.

**Comment by vlimant** [comment]
Indeed a bymcpileup view would be very useful

**Comment by ticoann** [comment]
@vlimant, Hi Jean-Roch
The view already exist.
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byprepid?stale=ok&key=%22B2G-Fall13-00001%22&include_docs=true

If that is not what you want, could you specify the requirement for this view?
Thanks,

**Comment by vlimant** [comment]
the view should be on MCPileup member of the workflow

**Comment by ticoann** [comment]
Sorry I completely misread the issue.

**Comment by ticoann** [comment]
Hi Alan, Jean-Roch
It seems we are not recording this data in couch db now.
Before implementing this one I want to clarify a few things.

1. Is pile up dataset only depends on workflow (request)? It seems it set as property of steps but you can set for whole workflow. If this need to be defined by task/steps later on, please clarify.
2. pile up has 2 different cases mc and data. Should the view need to be distinguished by both?
3. What exactly need for the REST api.
    i.e.) 
   1. given pile up dataset get the workflow information (what kind?)
   2. list all the pile up dataset and workflow pair. (This won't be so practical unless it has some conditions, i.e. for certain state of the workflows - not archived)

**Comment by vlimant** [comment]
Hi, the view should work the same way byinputdataset works : i.e I give a dataset name and I get the list of workflows that use that dataset as MCPileup.
Further to this, it should also support TaskChain and StepChain where the MCPileup is embedded in the TaskX object.
