### ISSUE TITLE
When tweaking a CMSSW PSet, check that attributes exit (and are valid) before trying to modify them.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/WMCore#6095]
Related issue in CRABClient: https://github.com/dmwm/CRABClient/issues/4528

**Comment by belforte** [comment]
in other words:
if modification of the attribute fails, report clearly this fact and possibly point at the problem. e.g. the problem may only (or more easily) appear during the modification rather than during some earlier check.
