### ISSUE TITLE
Problem with ACDC to recover merge failures for TaskChain

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6098]
The issue is the following: we normally set AcqEra and ProcStr to a dict made of TaskName:Value. The problem assigning wfs with these settings is that we are not specifying the AcqEra/ProcStr for the merge task (since it's out of our control), and then merge jobs will create files with None AcqEra and ProcStr.

The workaround for this issue would be setting AcqEra and ProcStr to a simple string instead. However it won't work for all the cases and, one of these cases would be if we need to recover *merge* jobs for Task1, but the workflow has a Task2 that must have != AcqEra and/or ProcStr.

**Comment by ticoann** [comment]
Hi Alan, Is this for the task chain?
You can define AcqEra/ProcStr in the task field too. (I think I added that feature a few month back).

What will be the merge task AcqEra/ProcStr? Should it be the same as parent processing?
can we et the global (within the workflow) AcqEra/ProcStr, and make each task overwrite that so if some task (merge) doesn't define the AcqEra/ProcStr, it will take the default global value?

**Comment by amaltaro** [comment]
Julian, do you create ACDCs via wmstats or via script? This is a classic example where the ACDC did not work:
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/jbadillo_ACDC_task_B2G-RunIIWinter15wmLHE-00388__v1_T_150728_121136_4197

but I wonder whether AcquisitionEra: "None" comes from your script or wmstats itself.

**Comment by julianbadillo** [comment]
I created it via wmstats.
But the "None" appears after it's assigned.

**Comment by julianbadillo** [comment]
As I showed you, the script uses acEra and ProcStr as dictionaries, and works fine if the recovered task is a production or processing one, but fails if it's a merge one.

**Comment by ticoann** [comment]
Thanks Julian for the information. That helps.

**Comment by amaltaro** [comment]
> What will be the merge task AcqEra/ProcStr? Should it be the same as parent processing?

That's right, merge tasks must inherit their parents config (AcqEra, ProcStr and ProcVer).

If global value is defined but not the task one, then global should be used.
