### ISSUE TITLE
Allow file based splitting with LHE files

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6113]
@amaltaro this is the issue we discussed with Dima last month. The idea, as I recall it, is that they would fill the LHESource with the full list of XML files and we would pick one/job and run on that. I can handle all the PSet modifications. Just need to know what to do.

**Comment by amaltaro** [comment]
Yep, I think that's it. They will provide a full list of XML files and we should implement a "skipFiles" which will remove all the other XML files from the PSet (at runtime), thus leaving a single LHE file without the need of "jumping" among them
