### ISSUE TITLE
Get future as a dependency of WMCore 

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6131]
Hi,

Can we add the "future" package a dependency of the WMCore RPM? The first use will be for the futurize command line, but if we want to start on the stage2 fixes for futurize, then we will need to be able import this.

**Comment by ticoann** [comment]
Eric, you are talking about https://pypi.python.org/pypi/future package, right? I will add that for next wmagent tag.
Technically it is issue for https://github.com/cms-sw/cmsdist/ but keep it here for a while.

I will also add https://github.com/cms-sw/cmsdist/blob/comp_gcc481/py2-mongoengine.spec (just a reminder) in agent. @vkuznet, Valentin is this the right one for mongo client?

**Comment by ericvaandering** [comment]
That's the one. Thanks!

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Aug 14, 2015, at 11:41, ticoann <notifications@github.com<mailto:notifications@github.com>> wrote:


Eric, you are talking about https://pypi.python.org/pypi/future package, right? I will add that for next wmagent tag.
Technically it is issue for https://github.com/cms-sw/cmsdist/ but keep it here for a while.

I will also add https://github.com/cms-sw/cmsdist/blob/comp_gcc481/py2-mongoengine.spec (just a reminder) in agent. @vkuznet<https://github.com/vkuznet>, Valentin is this the right one for mongo client?

**Comment by amaltaro** [comment]
Seangchan, in which spec file are you planning to add the mongoengine dependency? Just wondering if we could keep it away of the wmagent one, since it's not required there (I guess it wil only by WMArchive, right?).

**Comment by ticoann** [comment]
Actually it is in WMAgent. When fwjr generated it need to upload data directly. 
Plan is 
1. add the dependency 
2. add the code and a flag to whether to report to WMArchive or not. (default is false - it will set True only for the test).

**Comment by vkuznet** [comment]
Seangchan,
the correct pymongo driver is py2-pymongo, see
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/py2-pymongo.spec

The py2-mongoengine is a different beast and we don't need it for WMArchive
project.

Valentin.

**Comment by ticoann** [comment]
Thanks,Valentin.
