### ISSUE TITLE
Possible bug with SRM (v2?) plugin

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6149]
It seems SRM plugin tries to stage out files before explicitly creating the target directory. At least this is what Justas reported about recent issues at Caltech when the stage out fallbacks to srm protocol.

**Comment by juztas** [comment]
it happens for nebraska also if fallback is used. Without full log files not easy to debug if local/fallback was used. And wmstats shows last N lines, which are already for fallback and we don`t see what happened with local stageout
