### ISSUE TITLE
Unittests fixes 

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6152]
List of the failed unittest
https://cmssdt.cern.ch/jenkins/view/DMWM/job/DMWM-WMCore-UnitTests/lastCompletedBuild/testReport/

Seangchan
- WMCore_t/WorkQueue_t
- WMCore_t/Services_t

Alex
- WMCore_t.ResourceControl_t.ResourceControl_t.ResourceControlTest.testInsertAllSEs2
- WMCore_t.WMSpec_t.Steps_t.Executors_t.LogArch_t.LogArchiveTest.testUnitTestBackendNew

**Comment by ericvaandering** [comment]
Eric: after fixing jenkins, I want to see why sometimes these unit tests that oscillate get one number and sometimes a different one.
