### ISSUE TITLE
Broken unit test

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6175]
Headed home for the day, but ....

@amaltaro , pull request #5860 seems to have broken unit test

test/python/WMComponent_t/ErrorHandler_t/ErrorHandler_t.py , ErrorHandlerTest.testA_Create 

The files now come back with -90 events to analyze. Any ideas?

**Comment by ericvaandering** [comment]
FYI, I love my first experience with git bisect.

**Comment by amaltaro** [comment]
-90 evts... interesting :-)
I'll take a look at that in the coming days :)

**Comment by ericvaandering** [comment]
So here's what I found in my poking around before I went to track down the commit that broke things.

Line 115 in src/python/WMCore/ACDC/CouchFileset.py doesn't check if mask[FirstEvent] is bigger than f[events], which it should. That's where the -90 comes from and fails this bit of the test: https://github.com/dmwm/WMCore/blob/master/test/python/WMComponent_t/ErrorHandler_t/ErrorHandler_t.py#L269 Of course line 275 is also going to fail.

So maybe the test is non-sensical and/or wrong and your patch fixed code and broke the test. In which case, please write a sensible test. But in any case, the # of events should not go negative no matter the inputs. :-)

**Comment by ericvaandering** [comment]
Did this get fixed?

**Comment by amaltaro** [comment]
Not yet. There are real bugs in front of this one :-)
