### ISSUE TITLE
Lumi calc breaks unit tests

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6177]
@ticoann this commit https://github.com/dmwm/WMCore/commit/064e0bae99420aa29fe128572c523805ae9e5d98 breaks two unit tests: WMCore_t.WorkQueue_t.Policy_t.Start_t.MonteCarlo_t.MonteCarloTestCase.testLHEProductionWorkload and WMCore_t.WorkQueue_t.Policy_t.Start_t.MonteCarlo_t.MonteCarloTestCase.testShiftedStartSplitting

It looks to me like you are dropping a lumi section from the output if I read the test correctly.

**Comment by ticoann** [comment]
Sorry, I thought I ran the at least relevant unit tests. Thank you for finding out. fixes updated. #6178

**Comment by ericvaandering** [comment]
Going back and looking at it, you had a patch. I asked you to do with with python3 division. When you added that, you added the future import in the wrong place and broke things. Alan fixed that with a subsequent patch.

So I suspect you tested it before adding the future division and we didn't see these tests as failing until after Alan's fix. Doesn't matter in the end, we found it. :-)

**Comment by ticoann** [comment]
FYI, Eric, I didn't  add int(ceil ...) - you commented before about Python2 and Python 3 differences on return type. - It seems the some of the code expect that one to return float. I guess we have to clean up eventually.
