### ISSUE TITLE
Stageout error

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6207]
Andrew reported following error which happened in cmsgwms-submit1.fnal.gov

Job Name: 54d5b90a-4fe5-11e5-97a7-a0369f23d01e Task:
/pdmvserv_BPH-RunIIWinter15GS-00027_00119_v1__150827_174136_2842/Production/ProductionCleanupUnmergedRAWSIMoutput

Errors:
cleanupUnmergedRAWSIMoutput
StageOutFailure (Exit Code: 1)

General failure in StageOut for DeleteFilesStageOutFailure
Message: Unable to delete file:

/store/unmerged/RunIIWinter15GS/InclusiveBtoJpsitoMuMu_JpsiPt3_TuneCUEP8M1_13TeV-pythia8-evtgen/GEN-SIM/MCRUN2_71_V1-v1/00039/A2F9B501-734D-E511-9E75-D4AE5264D254.root
ErrorCode : 60311
ModuleName : WMCore.Storage.StageOutError
MethodName : __init__
LFN :
/store/unmerged/RunIIWinter15GS/InclusiveBtoJpsitoMuMu_JpsiPt3_TuneCUEP8M1_13TeV-pythia8-evtgen/GEN-SIM/MCRUN2_71_V1-v1/00039/A2F9B501-734D-E511-9E75-D4AE5264D254.root
ClassInstance : None
FileName : /tmp/glide_VH2zKu/execute/dir_16540/job/WMCore.zip/WMCore/Storage/StageOutError.py
ClassName : None
SEName : se1.accre.vanderbilt.edu
ErrorType : GeneralStageOutFailure
LineNumber : 32
PFN : None
ErrorNr : 0
StageOutCommand : None

Traceback: 
File "/tmp/glide_VH2zKu/execute/dir_16540/job/WMCore.zip/WMCore/Storage/DeleteMgr.py", line
168, in __call__
fileToDelete['PFN'] = self.deleteLFN(lfn)

File "/tmp/glide_VH2zKu/execute/dir_16540/job/WMCore.zip/WMCore/Storage/DeleteMgr.py", line
234, in deleteLFN
return self.deletePFN(pfn, lfn, command)

File "/tmp/glide_VH2zKu/execute/dir_16540/job/WMCore.zip/WMCore/Storage/DeleteMgr.py", line
263, in deletePFN
LFN = lfn, TargetPFN = pfn)

**Comment by amaltaro** [comment]
This looks like an ordinary stage out error, unless I'm missing something here.
@ticoann I'm closing this issue because I cannot see anything wrong. Feel free to reopen if you feel like
