### ISSUE TITLE
Investigate RotatingDatabase_t.py:testArchive

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6212]
Maybe one of our couch experts @ticoann or @vkuznet can have a look at this test. I turned it off because in my own tests it oscillates between 20 and 25 documents. I tried waiting as well to see if this was Couch's eventual consistency and the 25th document never does show up.

**Comment by ericvaandering** [comment]
testCycle in the same module is also oscillating (already marked integration)

**Comment by ticoann** [comment]
I will take a look at this problem. Sometimes couchDB results flips due to the stale view. (Most of calls by default is gets stale view in WMCore). In the unittest using the stale view cause some problems. I am no sure this is related, though.

**Comment by vkuznet** [comment]
Ok, I'll leave it up to Seangchan then.
Valentin.
