### ISSUE TITLE
Support MCPileUp in MonteCarlo and MonteCarloFromGEN request types

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6219]
for fastsim workflows, one needs to use either type and should be able to provide MCPileup parameter and it should be treated properly. This would facilitate greatly central production.
This ticket should have been opened a few months ago already @srimanob

**Comment by amaltaro** [comment]
Any reason not to use TaskChain request type for such cases?

**Comment by vlimant** [comment]
that is the trick that is being used. what you suggest could be achieved but for the sake of consistency in this case it would probably mean that all workflows would then come in as taskchain regardless their types (which is known to work just fine) and we could drop all types but TaskChain.
Doing what you suggest demands quite a large amount of work on the injection side, if the amount of work to enable MCPileup as specified in this ticket is not too large I would suggest doing so, that would simplify things and let MonteCarlo and MonteCarloFromGEN fulfilling their purpose.

**Comment by amaltaro** [comment]
Ok. Then I believe the work on ppd/mcm side would be much bigger than what it _should_ take in WMCore. However, I don't think we can make it before November, at best. Is that ok?

**Comment by vlimant** [comment]
Fine by me. @srimanob

**Comment by srimanob** [comment]
Thanks @vlimant @amaltaro 
I think it's fine for November, we are just starting the FastSim campaigns.

**Comment by ericvaandering** [comment]
So we talked about this in the WMAgent meeting on Thursday and I too think WMAgent should be able to do this. We don't want to artificially push things into TaskChain or even into multiple steps on the same worker node that we don't have to.

The only reason I see for TaskChain is if things need to run different releases or with different #'s of cores or need to run on different sets of resources.

**Comment by amaltaro** [comment]
@vlimant @ericvaandering do you see the need for deterministic pileup as well (premixing)?

**Comment by vlimant** [comment]
It is actually primarily for premixing these days ; not sure it is actually used (switch on in the workload by requester) though

**Comment by vlimant** [comment]
Thanks https://github.com/cms-PdmV/wmcontrol/issues/21 and https://github.com/cms-PdmV/cmsPdmV/issues/790 needs working on the requester's end

**Comment by amaltaro** [comment]
@vlimant @srimanob this is in testbed now and the WMCore functionality seems to be Ok. However I do not have a working workflow/configuration to test the whole chain, if you do and want to test a real thing, please inject it in testbed (or share the config with me) and we can test it before next Tuesday.

**Comment by srimanob** [comment]
pdmvserv_HIG-RunIISpring15FSPremix-00002_00008_v1__151116_133903_473
