### ISSUE TITLE
fixing bystatusandtype

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6220]
could this view emit the status and type, and not the workflow name in addition ?

**Comment by vlimant** [comment]
in https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/_design/ReqMgr

**Comment by vlimant** [comment]
This view is going to be useful for injecting ReReco in Unified @amaltaro should be easy to fix.

**Comment by amaltaro** [comment]
it prints request name, request status and request type:
https://github.com/dmwm/WMCore/blob/master/src/couchapps/ReqMgr/views/bystatusandtype/map.js

what's the problem printing workflow name? Can't you simply drop it in your client?

**Comment by vlimant** [comment]
Hi, I'd like to search by status and type i.e key=assignment-approved,ReReco and get directly the workflow names. the view cannot be used as a search as it stands.

**Comment by ticoann** [comment]
Hi Jean-Roch, yes it makes more sense to have that way. Fixes #6352
However, I remember this was requested specifically this way. I think a lot of Ops script need to be changed to get the value correctly.  As well as McM script.
https://github.com/cms-PdmV/stats/blob/master/tools/statsMonitoring.py#L183

I will try to announce that if everyone agree we will merge the patch, if not we have create the new view.
