### ISSUE TITLE
JobArchiver/TaskArchiver unit tests broken

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6235]
@ticoann these two sets of unit tests are broken by the removal of the alert unit tests with errors like

    from WMComponent_t.AlertGenerator_t.Pollers_t import utils
ImportError: No module named AlertGenerator_t.Pollers_t

I suspect the fixes are trivial

**Comment by ticoann** [comment]
Sorry Eric, I didn't know Alert is tested outside the package. Removed Alert test in Job/TaskArchiver #6236
