### ISSUE TITLE
Increase byinputdataset for TaskChain/StepChain content

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6240]
the view is not returning the workflows that have InputDataset in the tasks considering TaskChain. Could this please be updated ?

Example https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_SUS-chain_RunIIWinter15pLHE_flowRunIISpring15FSPreMix-00002__v1_T_150910_101516_5960

#6083 would need the same trick

**Comment by vlimant** [comment]
sorry, nevermind, that seems to work actually

**Comment by vlimant** [comment]
lack of sleep : it is relevant 
pdmvserv_SUS-chain_RunIIWinter15pLHE_flowRunIISpring15FSPreMix-00002__v1_T_150910_101516_5960

 uses internally 

/SMS-T1bbbb_mGluino-600_mLSP-1to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIWinter15pLHE-MCRUN2_71_V1-v1/LHE

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byinputdataset?key=%22/SMS-T1bbbb_mGluino-600_mLSP-1to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIWinter15pLHE-MCRUN2_71_V1-v1/LHE%22&include_docs=true

return pdmvserv_SUS-RunIISpring15FSPremix-00002_00002_v0__150909_002951_3924 only

**Comment by vlimant** [comment]
This is impacting operation

**Comment by amaltaro** [comment]
Damnit! We just had a testbed deployment :( I'll fix it for the current testbed

**Comment by vlimant** [comment]
thanks
