### ISSUE TITLE
Inconsistent usage of max_list_len

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6241]
@yuyiguo @ticoann this is the issue I mentioned yesterday, which is hitting us in production right now.

It seems we have an inconsistent usage of this max_list_len (for lumi_list for instance) between dbs client and server.

In the dbsClient code, we check the length of the list regardless whether it's a plain or a nested list (cannot be bigger than 1000, otherwise we slice it):
https://github.com/dmwm/DBS/blob/d58e4fe7be87a6f84da4f246523641c9988ba1ef/Client/src/python/dbs/apis/dbsClient.py#L1009

on the server side, we first expand this lumi_list in a plain list and then AND only then we check it against
the max length
https://github.com/dmwm/DBS/blob/00f44b9b32cefd79888eb1ded0ab8e359ab47965/Server/Python/src/dbs/web/DBSReaderModel.py#L910

where the following nested list
[[248, 494], [534, 546], [638, 650], [794, 1313], [1327, 1339], [1353, 1482], [1496, 1573], [1652, 1664], [1743, 1755], [1860, 1872]]

has 1053 elements, thus DBSServer returns a Bad Request.

Before putting more effort on it, I'd like to know whether we should fix it on the DBS side
 a. checking their length before any expansion
 b. if passes previous test but it's bigger, either go ahead or slice on the client side
or fix it in WMCore
 a. always expand from range of lumis to a plain lumi list and make POST calls with this plain list.

**Comment by ticoann** [comment]
Hi Alan, it seem this should fixed in DBS side, it sounds like dbs client call slices the parameters assuming which should accept by server but DBS server rejects it due to Oracle constraint. Is that correct?
Since it is hitting production now, so we should have temporary patch in WMAgent side but I think it should be eventually fixed in DBS side. Otherwise, it will have the problem whatever application which uses the same client api. @yuyiguo, Yuyi, what do you think?

**Comment by amaltaro** [comment]
Almost :) It does not really reach oracle. In the client side we have a list of lists where its length is smaller than 1000, so no slicing is needed here. However, the first thing done on the server side is expanding this list of lists in a plain list, which goes beyond the 1000 limit. Since the server does not apply any slices, it simply raises an exception in this case:
https://github.com/dmwm/DBS/blob/00f44b9b32cefd79888eb1ded0ab8e359ab47965/Server/Python/src/dbs/web/DBSReaderModel.py#L929

I agree with you, it would be better to fix it in the DBS side. I'll create a temporary agent patch tomorrow.

**Comment by amaltaro** [comment]
Actually, there is no temporary fix nor workaround in WMAgent, since this problem involves only central services and GQ fails to acquire work (start policy).
Yuyi, do you think you can fix it by next Testbed? Otherwise I'll add something in WMCore...

**Comment by amaltaro** [comment]
Yuyi made the fix in the end of 2015 :-)
