### ISSUE TITLE
Total stats missing from workload cache doc

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6258]
This issue should have been fixed by #6144, however Jean-Roch found another case after the last cmsweb upgrade where stats are not available:
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_EXO-RunIIWinter15GS-01072_00123_v0__150907_161918_385

**Comment by vlimant** [comment]
could this be related to #5486 where two workload are concurrently being updated, one is updated twice (could expected lumi), the other none (missing members)

**Comment by ticoann** [comment]
It seems very weird, in any case it should have the field recorded with 0. Are there any more cases of this? Workflow shouldn't update this simultaneously. It is one time operation from GQ unless there is additional block is added given inputdataset

**Comment by vlimant** [comment]
Last time this was seen is on 05/10/2015
TotalInputEvents is missing from the workload of pdmvserv_task_EXO-RunIIWinter15wmLHE-01203__v1_T_151002_160434_6833
TotalInputEvents is missing from the workload of pdmvserv_EXO-RunIISpring15DR74-02710_00402_v0__151001_040448_1293

**Comment by vlimant** [comment]
new cases 
pdmvserv_HIN-pp502Fall15-00010_00005_v0__151123_175741_6681
vlimant_SUS-RunIISpring15DR74-00094_00503_v0__151127_125406_8726
vlimant_HIG-RunIISpring15DR74-00589_00498_v0__151127_125326_2767
...

**Comment by ticoann** [comment]
Hmm, That is discouraging. I will investigate

**Comment by amaltaro** [comment]
Since I'm not aware of new cases like this, it was probably fixed by Seangchan (I couldn't find the PR...)
Closing this issue and we reopen if needed

**Comment by vlimant** [comment]
unified is resilient to this absence. one could browse all active workflows for this missing member.

**Comment by vlimant** [comment]
TotalInputEvents is missing from the workload of pdmvserv_EXO-RunIISpring16MiniAODv2-00920_00145_v0__160605_123203_6166
TotalInputEvents is missing from the workload of pdmvserv_EXO-RunIISpring16MiniAODv2-00897_00145_v0__160605_122612_6474

**Comment by vlimant** [comment]
related to #5969
