### ISSUE TITLE
WebTools frontend should be deployable remotely

### ISSUE THREAD

**Issue by evansde77** [dmwm/WMCore#627]
If we have public Couch Instances the Frontend WebTools RPM needs to be deployed.

Couchapps require that couch is actually running to push a couchapp. Couchapps are pushed at Couch startup 

Depends on getting the WT Frontend into a deployable state.

**Comment by amaltaro** [comment]
@ticoann @ericvaandering I don't really understand this issue. Since it's opened for 4 years with no further comments, how about closing it?

**Comment by vkuznet** [comment]
Alan, I think we can safely close this ticket.
