### ISSUE TITLE
Job deleting files after a successful stage out

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6273]
As reported in this HN:
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2536.html

it seems the stage out plugin is firing an srmRm for files that failed the
first stage out attempt and succeeded in the second one (still in the same
job).

It happened at T2_IT_Pisa that uses srmv2 protocol. More info in the HN itself.
debugging...

**Comment by amaltaro** [comment]
For the record, from the list of tickets I got from the transfer team, these are the sites and their local stage-out list:
T2_US_Vanderbilt using "vandy" command, so VandyImpl
T2_FI_HIP using srmv2 command, so SRMV2Impl
and all the others (T2_IT_PISA, T1_IT_CNAF, T2_US_Caltech, T2_EE_Estonia, T2_BE_IIHE, T2_DE_RWTH, T2_FR_GRIF_LLR) using srmv2-lcg, so LCGImpl

**Comment by ericvaandering** [comment]
Does this have anything to do with this? https://ggus.eu/index.php?mode=ticket_info&ticket_id=118307

**Comment by amaltaro** [comment]
The transfer team claims to still see files missing from time to time, mainly at KIT. I asked them to get in touch with us in the last CompOps, if we don't hear anything by beginning of March, we shall close this annoying issue.

**Comment by amaltaro** [comment]
After more investigation and debugging with the KIT folks, we came to the conclusion that the Alarm signal is "responsible" for these missing files, since it leaves behind a subprocess still trying to stage out:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/StageOut.py#L219

 and we cannot kill that subprocess because - at this point - we have no idea what command/call we are running, we didn't build the stage out command nor we know which protocol to use.

However, if we move the Alarm handling to this code (2 layers below the previous one):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/StageOutImpl.py#L173

then we could use check_output from subprocess, get the PID and kill it in case the Alarm is raised.

A second option would be removing the Alarm handling from the StageOut.py, we already have a timeout option for srm and lcg (probably for gfal as well), thus we don't need to have two layers of timeout for the stage out code.

**Comment by hufnagel** [comment]
If you can actually reliably kill everything that was started by the stageout subprocess (it's multiple things within a shell after all), I would keep the alarms and just move it down and make sure we wipe everything. Only if that isn't possible would I remove the Alarm handler. There were valid reasons originally why we wanted an Alarm here that restricted the amount of time we wait for stageout to finish.

**Comment by amaltaro** [comment]
Yes, I also think the alarm is important to have, that's why I kept it in this PR: https://github.com/dmwm/WMCore/pull/6695

However, my idea was that the alarm does not kick in for stage out implementations that provide some timeout mechanism (especially SRM flavors). Otherwise, it will wait for 2h per retry.

**Comment by amaltaro** [comment]
Everything indicates it was fixed by #6695
