### ISSUE TITLE
Trusting whitelist breaks a unit test

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6278]
9ddcf54b1d991aeb9b2a41850eecab9aafcceda5 breaks

WMComponent_t/JobSubmitter_t/JobSubmitter_t.py:JobSubmitterTest.testD_WhiteListBlackList

Will investigate.

**Comment by ericvaandering** [comment]
Part of #5743

**Comment by ericvaandering** [comment]
Was wrong. Commit is 031bdcb488b405b7e17ae4de1d84868dc0c7c217 it seems.

**Comment by ericvaandering** [comment]
@hufnagel can you take a look at the unit test WMComponent_t/JobSubmitter_t/JobSubmitter_t.py:JobSubmitterTest.testD_WhiteListBlackList which is broken by the above PR. I can't tell if this is intentional, but what's happening is that at https://github.com/dmwm/WMCore/blob/master/test/python/WMComponent_t/JobSubmitter_t/JobSubmitter_t.py#L701 submitting jobs with a whitelist of T2_US_Namibia does not automatically fail those jobs.

**Comment by amaltaro** [comment]
I guess this test was either removed or turned into another test, since I can no longer find it in the JobSubmitter test class. Closing it.
