### ISSUE TITLE
performance kill for disk space usage

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6285]
Hi,

Can we have a performance kill and a dedicated exit code (similar to maxRSS) when there is too much disk space used?

Andrew

**Comment by ericvaandering** [comment]
I'm surprised we don't have this, but we appear not to. Killer would go here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py

There are methods in the new psutil we are using do monitor disk space. That may help.

**Comment by ticoann** [comment]
I guess there is the reason this is not implemented. I am not completely sure how we get the disk usage by process id. I looked at the psutil, pidstat, iotop but it seems we can get the write rate for io but not directly disk usage of the given process. I assume the process writing to one file and maybe there is a way to find the way and keep checking the files size. 

i.e - 2 step procedure to fine the information
1. find file name which a given process is writing. (not sure how to do this)
2. get the size of the given file.

@ericvaandering, @AndrewLevin, Eric, Andrew, do you know any command to 1? Or is there easier way to get this information (I couldn't find one in psutil)

**Comment by AndrewLevin** [comment]
doesn't condor report the disk space usage?

it is one of the things I see when I do condor_q -l

does wmcore not have access to the same information condor has?

**Comment by ericvaandering** [comment]
I don't know that unix itself can do disk space of a process. You can get I/O that a process has read/written, but if it writes something and deletes is.... 

I don't know off the top of my head if we can get this info from Condor on the worker node, but even if we could I'm not sure we'd want to implement it that way vs. using something like psutil to get it from the working directory. We already have monitoring (I believe) that works that way but not with psutil. What we don't have, as I recall, is a way to terminate the job based on that info.

**Comment by ticoann** [comment]
Hi Eric, What we are missing is not just the terminating job part. But we don't get the disk information from the command we use

we use following command to ge the information
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L60

**Comment by ticoann** [comment]
> doesn't condor report the disk space usage?
> 
> it is one of the things I see when I do condor_q -l

I see following in condor_q -l, is DiskUsage updated periodically does that what you want?
Do you know what are the differences between _RAW value and other values?

DiskUsage_RAW = 86370
DiskUsage = 75000
RequestDisk = 400000
RequestDisk_RAW = 370121

> 
> does wmcore not have access to the same information condor has?

It uses ps command to get other informaion RSS, VSIZE, etc, I don't know the  command to get disk usage by pid. There must be one if condor can get that information. I think condor command to get the information is tricky. Could we even use the same condor command in worker node?

**Comment by hufnagel** [comment]
Question, apart from the technical aspects, how would this actually be used, ie. what would be the value we kill on ? Keep in mind this value needs to make sense compared to the Condor kill value (if Condor kills before WMAgent we haven't gained anything).

**Comment by ericvaandering** [comment]
Very true. My bad, I was remembering existing code in https://github.com/dmwm/WMCore/blob/6f3570a741779d209f0f720647642d51b64845da/src/python/WMComponent/AlertGenerator/Pollers/System.py but that's the Agent not the WN.

**Comment by hufnagel** [comment]
Another question, do we want to stay with fixed disk space assignment per job slot (with the only adjustment being the number of cores assigned to a job) or do we eventually move towards scheduling disk space like we do memory for at least the multi-core pilots ? Technical discussions are all fine and well, but we should make sure we have a sensible policy and an idea if/how that policy will evolve before we make changes.

**Comment by hufnagel** [comment]
For instance, high IO job slots don't really fit into the fixed disk space per job slot assignment, they effectively over-commit on disk for multi-core pilots that use them.

**Comment by hufnagel** [comment]
IMO, I see killing on running out of disk being potentially useful for RelVal. I don't see it being all that useful for anything else.

**Comment by AndrewLevin** [comment]
Hi Dirk,

For me (release validation), the only important thing is that we set the wmcore disk space kill to be less than the condor/site/glidein kill value, which is the RequestDisk value I guess, which I see is normally set to something like 20 GB, although I am not sure where/how it is set.

Andrew

**Comment by AndrewLevin** [comment]
Yes, the main reason I want it is so that I can report back properly to the requestor why the job failed.

**Comment by hufnagel** [comment]
RelVal has very different requirements than normal production. You care about being able to tell requestors why something failed, even if the changes we make for you to do so slightly lower your chances that it will succeed in the first place.

For production the tradeoff is different. We don't debug individual jobs there to the same degree that we do RelVal, so implementing changes that lower the chances of a job to succeed are maybe not the best idea.

Keep in mind that while 20GB is the nominal disk per job slot we ask site to give us, many sites have much more.

**Comment by hufnagel** [comment]
Anyways, we do have Condor kill expressions on disk. All I am saying is that anything we deploy on the agent side isn't more aggressive than the Condor ones. How about

Agent kills on (nCores * 20GB) + 1GB
Condor kills on (nCores * 20GB) + 5GB

You could still get unlucky if all jobs on a node use their max disk at the same time and run out of disk on the node before these kills kick in, but the only way to avoid this would be kill *below* 20GB.

**Comment by AndrewLevin** [comment]
yes, that seems reasonable

(maybe wmagent can also parse the reason why condor killed the job, I think there is a condor kill logic expression that has several different parts to it)
