### ISSUE TITLE
ACDCs should inherit performance info and mergedLFNBase

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6298]
We should make ACDCs inherit some performance parameters, like:
maxRSS, maxVSize, softTimeout and hardTimeout.

**Comment by amaltaro** [comment]
Just updated because it should also contain mergedLFNBase from the original request.
@vlimant feel free to add anything else that you consider missing there.
Aiming at the next cmsweb cycle (this one is basically finished)

**Comment by vlimant** [comment]
Will this appear in the worklfow dictionnary even before assignment, for ACDC ?

**Comment by vlimant** [comment]
@amaltaro a lot of things should be hardwired in the ACDC making, leaving only very few things to the liberty of the operator to change. All outputs, lfn, and all should be already wired and unmutable

**Comment by amaltaro** [comment]
Probably not completely fixed yet (in ReqMgr2, won't happen for ReqMgr), but #7254 and #7241 should do the work

**Comment by amaltaro** [comment]
Possible fixed by #7676
