### ISSUE TITLE
Add a few other fields to workload_cache reqmgr2

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6299]
We should add the following fields (provided during assignment) to the reqmgr_workload_cache document, in reqmgr2:
dashboardActivity, maxRSS, maxVSize, softTimeout and hardTimeout.

**Comment by ticoann** [comment]
Hi Alan, those are already in the reqmgr_workload_cache. But with CamalCase except hardTimeout

**Comment by amaltaro** [comment]
I didn't find any of them here Seangchan
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/amaltaro_ReDigi_cmsRun2_PNN_Oracle_151008_114823_2481
maybe we are talking about different docs?

**Comment by ticoann** [comment]
Ah, this only works with reqmgr2 request.
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/amaltaro_StepChain_ReDigi3_ReqMgr2_Validation_151008_003414_7581

However, it seems hardTimeout is just softTimeout + gracePeriod.  I can add the field (HardTimeout) though.

**Comment by amaltaro** [comment]
Seangchan, it seems they are not available even for ReqMgr2 requests only, see
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/amaltaro_TaskChainPyquenZeemumuJets_PU_ReqMgr2_Validation_151008_003253_907

**Comment by amaltaro** [comment]
Sorry Seangchan, I picked a workflow that has not been assigned, that's why those fields are not there. This one was assigned:
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/amaltaro_TaskChainTTbar_ReqMgr2_Validation_151008_003315_396

maxRSS and maxVSize are there, but not the dashboardActivity. Can you make this change as well?

**Comment by ticoann** [comment]
Actually, the name is Dashboard instead of DashboardActivity. Not sure why we change the name in json doc.

**Comment by amaltaro** [comment]
All these fields are now available for reqmgr2.
