### ISSUE TITLE
Make change Priority work with ReqMgr2

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6310]
When changes the priority need to update workqueue priority as well. (check whether we can get the directly from reqmgr db instead of updating workqueue)

**Comment by amaltaro** [comment]
Hmm, I'm almost sure priority updates also get propagated to workqueue.
About your second comment, I don't really understand it. You mean get it from reqmgr couch db, right?

**Comment by ticoann** [comment]
yes. I think if we don't have to get it from wq but get it from reqmgr couch db it will be better but if it is too complicate to change it, we might not do that.
