### ISSUE TITLE
Stepchain: allow intermediate stage out 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6344]
As discussed in yesterday's meeting, we need to have the flexibility of saving intermediate outputs in Stepchain. Right now it only saves (stages out) the files produced by the last step (cmsRun).

**Comment by amaltaro** [comment]
This can't be completely done. Different than TaskChain, a StepChain workflow has a single task where we add a new step (cmsRun) for each StepX in the configuration. In the end, we create a new merge task for each parent task + output module. Here is the problem, we have only one parent task here, such that duplicate output module (does not matter whether it has the same datatier or not) cannot be created.

The only way forward here is the following:
 1. add a StepChain validation and check we don't want to stage out using the same output module.
 2. provided there are no dup output module, we can do whatever we want with the outputs.

@ericvaandering @ticoann any comments/suggestions?

**Comment by ericvaandering** [comment]
I think that should work. What's the definition of a duplicate output module? Just the CMSSW name for the output module? That should be OK as long as we have a way to stage out AOD in one step and mini-AOD in the 2nd. Or even AOD and miniAOD v1 in the first step and miniAOD v2 in the 2nd step. (No idea if anyone will ever want to do that, but if we neglect to add it we can be sure they will want it. :-)

**Comment by amaltaro** [comment]
The definition of a duplicate output module ... well, in this case it's a duplicate task{name} actually. For each output module we want to keep, we have to create a new merge task:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L539

however, they all fall into the same parentTask and, in case we use the same output module (e.g. RAWSIMoutput) in different steps, it would map to the same merge task name which fails to be added to the ConfigSectionTree downstream:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/ConfigSectionTree.py#L126

About AOD and MINIOAD, it seems there is a different output module for each of them (AOD{SIM}output and MINIAOD{SIM}output), so it will work.

Hmm, you just reminded me that I still have to handle different AcqEra, ProcStr and ProcVer for them :-D

**Comment by ericvaandering** [comment]
Different AcqEra? Are you sure about that one? The other two I agree. 

So it's not just a string but something defined in our code? In other words, why not MINIAODoutput and MINIAOD2output ?

**Comment by amaltaro** [comment]
I already tried "hacking" the outputModuleName as you suggested :-)
however, it (the one that comes with the pset) seems to be used in other places, like the file written to disk in the worker node... I didn't really debug my test, but all jobs failed to read a 
      [a] Input file ../cmsRun2/RAWSIMoutput.root could not be opened.

when it probably had output a RAWSIM2output.root file.

For the AcqEra, if we are producing a GEN-SIM, I'm almost sure someone would want to name it as GSBlah and make it different for AOD for instance.
