### ISSUE TITLE
Stepchain: support trident configurations

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6345]
Stepchain should support parameters like input step and input module such that we can chain the steps as we want. For instance, 
 - Step1 produces GEN-SIM-RECO
 - Step2 reads the GEN-SIM-RECO from Step1 and produces AODSIM
 - Step3 *also* reads the GEN-SIM-RECO from Step1 and produces AODSIM
Differences between Step2 and Step3 could be a != release, or GT or config or etc

**Comment by amaltaro** [comment]
Setting milestone to January, feel free to change it in case I'm wrong.

**Comment by ticoann** [comment]
This will allow each intermediate output to be stored, correct?

**Comment by ericvaandering** [comment]
That's a different, probably simpler, issue.

**Comment by amaltaro** [comment]
Fixed by #6589
