### ISSUE TITLE
Handle legacy se names from dbs

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6349]
We need to handle that DBS returns se names in 'origin_site_name'. Until dbs migrates the all the data to PNN after agent is upgrade, we need to handle this.

The following could return se or PNN
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L603
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L791

**Comment by ticoann** [comment]
within those method we need to make sure return value is PNNs (convert se to pnn if necessary from dbs 'origin_site_name'

**Comment by alexanderrichards** [comment]
@ericvaandering @ticoann I have a commit here that should address the legacy se situation but I have a couple of inline comments. Could you take a look at the commit above: a25af89d1eb6c1ac003672907db105a0d6b023ed

**Comment by ticoann** [comment]
Thanks Alex, patch looks good to me. Could you make the the pull request so all the unittest can be tested?
