### ISSUE TITLE
WorkQueue block location is set for  PNN or PSN

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6350]
I am not sure this is real issue. But looking at the code it seems sometime the location is set to PSN (when trusted site is set) other cases PNN.  I wonder why this doesn't cause the problem yet. (*)
I think all needs to change to PSN

(*)
PSN:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L44
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L185

I think following just have an error, shouldn't this return PNN not se names? (Although current dbs has se names so changing this might actually break things but we have to support both PNN, se)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L46
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L109
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L141
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L164

PNN: - this need to be convert to PSN
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L187

If element containing site as location followings need to be changed as well.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L400

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L421

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L440

**Comment by amaltaro** [comment]
Picking this case as example:
> I think following just have an error, shouldn't this return PNN not se names? (Although current dbs has se names so changing this might actually break things but we have to support both PNN, se)
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L46

indeed it seems it would fail, since the listBlockParents call (L42) returns PNNs and then we provide PNNs instead of SEs to the sitesFromStorageEelements call (L46), which of course will return an empty list. Instead, we should convert from PNN to PSN.

These would also fail with the same reason (providing PNN to a function expecting SE):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L109
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L141
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L164

About
> If element containing site as location followings need to be changed as well.

it *may* make sense to change to PSN as well, but honestly, I'm not sure. Before the migration it had se_names, so replacing them by PNNs looks the right thing to do. 
Going down the chain, the wmbs file registration is made against the data location instead of the processing sites (probably JobCreator and/or JobSubmitter is picking this data location and later on x-checking against the site white/black list)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WMBSHelper.py#L602
What could be done here is just renaming storageElements by pnn to be more clear.

> PNN: - this need to be convert to PSN
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L187

Agreed!

**Comment by ericvaandering** [comment]
No function in WMCore should expect an SE name, that's the whole point of this exercise. To banish them from WMCore forever. If, in the interim, we need to convert a few straggling SE names to PNNs, fine, but we should do that in the DBS layer since thats the only place they should still arrive, right?

**Comment by alexanderrichards** [comment]
> indeed it seems it would fail, since the listBlockParents call (L42) returns PNNs and then we provide PNNs instead of SEs to the sitesFromStorageEelements call (L46), which of course will return an empty list. Instead, we should convert from PNN to PSN.
> 
> These would also fail with the same reason (providing PNN to a function expecting SE):

@ticoann @amaltaro 
I am confused what the point of going through the code base and changing everything to work with PNN was if we then have to go back through and put PSNs back in? Isn't the answer to change the functions that expect PSN to expect PNNs?

**Comment by alexanderrichards** [comment]
@ericvaandering (SNAP :smile: ) sorry only just saw your post.

**Comment by amaltaro** [comment]
That's another comment I forgot to mention :) AFAIK we will NOT support both PNNs and SEs, PNNs are completing taking over SEs and as Eric just said, SEs are (should) be unsupported by WMCore from this point on.

@alexanderrichards my understanding is that we have to support PSNs and PNNs, in some places like closer to job submission we should talk only PSNs (where jobs run). Places like data location should handle PNNs. The whole point of this big change was to retire SEs by PSNxPNN (not only PNN). Let me know if I got you wrong :)

**Comment by ericvaandering** [comment]
Right, PSN is for job location, PNN is for data location. If we are sloppy in mixing these two, the goal should to stop being sloppy and do the conversion at the right place.

**Comment by alexanderrichards** [comment]
ok thats clearer to me. So as I said then I guess the right thing to do is to make these functions accept PNNs rather than expecting SEs.

**Comment by alexanderrichards** [comment]
> indeed it seems it would fail, since the listBlockParents call (L42) returns PNNs and then we provide PNNs instead of SEs to the sitesFromStorageEelements call (L46), which of course will return an empty list. Instead, we should convert from PNN to PSN.
> 
> These would also fail with the same reason (providing PNN to a function expecting SE):
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L109
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L141
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L164

@amaltaro presumably we can in fact get rid of this function altogether and simply use the mapping in wmbs?

**Comment by amaltaro** [comment]
Sorry Alex, I didn't express myself well :( Yeah, that's what I meant, we should get rid of sitesFromStorageEelements everywhere in the code. Since we don't expect to handle SEs anymore.

**Comment by alexanderrichards** [comment]
@amaltaro I have made a commit (not yet in a PR above). Can you take a look at it please. I think it does what we discussed but I might need some help with the DAOFactory instantiation (might have too few parameters).

**Comment by ticoann** [comment]
@alexanderrichards, Hi Alex I commented a couple of things in the commit.

Followings are what I concern

1. You can't use DAO for getting pnn to psn mapping. (GQ doesn't have access to it) so need direct call to SiteDB for that.
2. If the PNN, PSN mapping doesn't exist there is something wrong so should raise exception. 
3 If you could we have handle temporary network glitch to siteDB (but this wasn't the case before so we can skip it in this patch)
4. To make this patch work, #6349 has to be fixes as well. (As Eric mentioned those two method checks whether site is SE or PNN and convert to PNN if it is SE. SE is not saved in wmbs anymore so conversion need to use sitedb call. - This part need to be removed when DBS updates all SE names to PNN.
5. What about following codes. (Once this patch is updated the site record there is PSN not PNN (from https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L398, right?)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L400
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L421
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L440

**Comment by alexanderrichards** [comment]
@ticoann @amaltaro I have reworked the patches. Can you please check the three commits above, namely:
e717815662acbc88fca75180b17898304c819f8d
97741916e27f2e2866c8978e8da8815aaaa89d6c
281544f792a05eeeac7daf0e07687bb32222ea09

**Comment by ericvaandering** [comment]
Can you convert the nearly identical code in the last two commits into a shared function? Without knowing the code in question well, I would suggest Services/SiteDB, but maybe another location would be even better.

**Comment by alexanderrichards** [comment]
@ericvaandering in fact all the code was very similar and benefited from factoring out to a seperate function. It was just a case of knowing where to put it. Your suggestion of the SiteDBJSON.py looks good to me. see:
60c78abc060098a06707e9dc15b671b3823add04
5e44a1f64f8d50bda6dcfd40513e629331d5611e
9a11d0dc35702bd645ee280b9ad999698c21485d

**Comment by ticoann** [comment]
Thanks Alex, patch looks good. Could you make the pull request?
One thing I am concerning is following (match['Inputs'].values()[0])

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L398
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L421
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L437

Which comes from here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L335
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L477

Is that value really PhEDExNodeName not PSN?

**Comment by alexanderrichards** [comment]
> Is that value really PhEDExNodeName not PSN?

I'm not sure, maybe @amaltaro will know

**Comment by ticoann** [comment]
Looking at the code before PNN, PSN patch those (match['Inputs'].values()[0]) are site names not PNN,

https://github.com/dmwm/WMCore/blob/799ef0359712cc87c02f07dce97346472e25ae57/src/python/WMCore/WorkQueue/WorkQueue.py#L398

https://github.com/dmwm/WMCore/blob/799ef0359712cc87c02f07dce97346472e25ae57/src/python/WMCore/WorkQueue/WorkQueue.py#L415

So I think we need to convert back that to PSN
so pnn is not actually pnn but psn (from below), we need to convert that to psn before call is returned
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L421

**Comment by amaltaro** [comment]
It seems you guys sorted everything out, right?

**Comment by alexanderrichards** [comment]
Yes all the things that seangchan notices, plus a couple of others should have been sorted with that patch.
