### ISSUE TITLE
Filter MSS, Buffer and Export endpoints?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6371]
I see several messages like
2015-10-30 17:25:08,682 WARNING  SiteDB: No PSNs for PNN: T1_ES_PIC_Buffer
2015-10-30 17:25:08,690 WARNING  SiteDB: No PSNs for PNN: T1_ES_PIC_MSS

in the testbed workqueue and I was wondering whether we should filter out such PNNs in the code to avoid flooding logs of warnings. @ticoann what do you think?

**Comment by ticoann** [comment]
We can make in the log in debug level. The only thing I worried is whether there is missing PNN and PSN mapping and we wouldn't find out.

**Comment by ticoann** [comment]
Sorry, I misunderstood. So there is no PSN for _Buffer and _MSSS, right?
we can only filter _MSS _Buffer mapping case.
