### ISSUE TITLE
ReqMgr2 -> request info without ProcessingString or Processing version

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#6384]
@ticoann @amaltaro 
When an acdc is created, the information provided in this API:
https://cmsweb.cern.ch/reqmgr2/data/request?name=jbadillo_ACDC_Run2015BHINPFJet100-16Oct2015_7414_151106_101855_6024
Comes without ProcessingString or ProcessingVersion.
In contrast with the old API:
https://cmsweb.cern.ch/reqmgr/reqMgr/request?requestName=jbadillo_ACDC_Run2015BHINPFJet100-16Oct2015_7414_151106_101855_6024

**Comment by ticoann** [comment]
Hi Julian, this only happens when ACDC is created but not original workflows?

**Comment by julianbadillo** [comment]
Also on original workflows:
https://cmsweb.cern.ch/reqmgr2/data/request?name=jbadillo_Summer11_151204_142108_8096
vs
https://cmsweb.cern.ch/reqmgr/reqMgr/request?requestName=jbadillo_Summer11_151204_142108_8096

**Comment by ticoann** [comment]
Thanks Julian, ProcessingVersion, ProcessingString is set only in assignment status in reqmgr2. (ReqMgr might have default value is set in creation) Workflow above seemed never reach to assignment state. Should we add default value for those in creation time as well?

**Comment by julianbadillo** [comment]
@ticoann Yes, we should.
