### ISSUE TITLE
Create the patches for 1.0.11_wmagent branch

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6396]
#6385
#6387
#6392 
#6394
#6401

**Comment by amaltaro** [comment]
retesting all together in a clean agent. However, maybe we could simply go for 1.0.12, since there were not many changes, to see...

**Comment by amaltaro** [comment]
Seangchan, I'm closing this issue since we upgraded the agents in the current cycle (1.0.12), which contains these patches already.
