### ISSUE TITLE
Write unit tests for SimpleCondorPlugin

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6400]
It's completely broken (maybe since ever). And add tests for allowOpportunistic.

If it's simple, then also fix the CondorPlugin, though we are about to get rid of that plugin...

**Comment by ticoann** [comment]
Alan, this test needs special set up (have to have condor schedd installed with actual job submission capability) Are you running it on that environment?

**Comment by amaltaro** [comment]
Nope :( But it at least some of the tests we could get running if we setup the proper database and schema. I spent 2 minutes with CondorPlugin and by adding a setUp and tearDown methods we can already get a couple of success tests. 

Anyways, it's more like a reminder since I didn't add any tests with the #6397 PR

**Comment by amaltaro** [comment]
Won't be done. But we could use some of the PyCondor test code to start writing SimpleCondorPlugin tests

**Comment by amaltaro** [comment]
Since PyCondorPlugin is basically dead, I'm renaming this issue for SimpleCondor one.
