### ISSUE TITLE
Enable CondorStatusService

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6405]
CondorStatusService is a scalable service for providing runtime updates from CMSSW to HTCondor.  It only activates when it's run under HTCondor of an appropriate version.

@hufnagel tested this out at the T0.  For his test, the change was simple:

https://github.com/hufnagel/WMCore/commit/5c50ab1918e4f749ee931452d1659d8a1e33aca2

However, that test "cheated" - the service is only in 7_6 and later, so he was able to skip runtime version detection.

Can we do a tweak of that patch to include the runtime version detection?

**Comment by bbockelm** [comment]
@mmascher - I think we discussed this previously too for CRAB3.

**Comment by ericvaandering** [comment]
Can you remind me of the purpose of having CMSSW communicate with condor and what you want to accomplish with this?

**Comment by bbockelm** [comment]
It does a few things:
- Includes basic IO statistics in the HTCondor classad, which a few projects (particularly from FKW) are picking up.
- Informs HTCondor of percent completion of the CMSSW job, making this information remotely available in the case of an operator debugging jobs.
  - At least HTCondor-CE sites will be able to see this information from their CE.
- Provides deadlock detection for operators.

**Comment by mmascher** [comment]
FYI, I am cherry-picking this to the WMCore used by CRAB3 and it did not create any problem. I will continue to do it. But honestly I have never checked if it works :)

Brian, do you know the name of the classad used to set the percentage of completion of the CMSSW job?

**Comment by ticoann** [comment]
Added in 1.0.13.pre6
