### ISSUE TITLE
Propagate request priority changes everywhere

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6407]
When someone changes a request priority in reqmgr(2), this info should get propagated to the following parts:
 1. GQ docs (and by replication to the LQ docs). Patch #6404 should fix this issue
 2. WMBS database (wmbs_workflow)
 3. jobs cached in the agent (in the JobSubmitter queue)
 4. jobs in condor (both pending and running).

1. is under testing and 3. still needs to be fixed. In addition to that, some rework is needed in JobUpdater.

**Comment by amaltaro** [comment]
Adding it to my todo list for December.

**Comment by ticoann** [comment]
Hi Alan, Alex, I switch this it to Alex. Since Alex is bored. :smile:  Thanks Alex.

**Comment by amaltaro** [comment]
LoL. Ok, 1 is done, tested and deployed in testbed.
Alex, please x-check 2., I believe it updates wmbs but I did not check.
3. for sure needs fix

**Comment by alexanderrichards** [comment]
> Since Alex is bored.

:smile: just thankful to have finally finished the PNN stuff

**Comment by alexanderrichards** [comment]
> Alex, please x-check 2.,

Hi Alan, this looks good to me, I see the WMBS update code in the JobUpdater [here](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobUpdater/JobUpdaterPoller.py#L154). I will submit a workflow and actually check this works

**Comment by alexanderrichards** [comment]
>`3. `jobs cached in the agent (in the JobSubmitter queue)

@amaltaro looking at the JobSubmitter. It looks like jobs are submitted from the queue using the priority not from the cached job but from the `workflowPrios` dict (see [here](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L697)) which is refreshed from WMBS [here](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L252).

To me this looks like as long as the WMBS priority is updated then the jobs cached in JobSubmitter queue will also be updated. Am I misreading this?

**Comment by amaltaro** [comment]
You're right Alex. JobUpdater updates WMBS (and it seems to be updating workqueue elements, maybe that's not really necessary, but that's another issue).

And JobSubmitter, first loads jobs into the cache (using the wmbs priority, as you pointed out) and then submits jobs from the cache. In addition to that, it seems to me cache is also updated for each JobSumitter cycle.

In summary, it seems we're good with priorities on the agent side and there is nothing to fix. But I appreciate if you can make sure that's the case :-) (you could play with agent 1.0.12.patch2)

**Comment by alexanderrichards** [comment]
> But I appreciate if you can make sure that's the case :-) (you could play with agent 1.0.12.patch2)

will do :wink:

**Comment by amaltaro** [comment]
Getting back to it, I'm checking one workflow in the new agent + reqmgr (1.0.5.pre2):
 1. Priority updated in the workload_cache doc --> OK
 2. Priority updated in the GQ WQE --> OK
 3. Priority updated in the LQ WQE --> OK
 4. Priority updated in the wmbs_workflow table --> OK
 5. Priority updated in the condor jobs --> BAD 

I suspect it may be with PyCondor plugin. I'm investigating it.

**Comment by amaltaro** [comment]
Problem with PyCondorPlugin was fixed long ago, so closing this issue.
