### ISSUE TITLE
Create the reqmgr page to change properties without status change

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6411]
First we only need priority change

**Comment by ticoann** [comment]
@vkuznet, Valentin, we need a page on reqmgr2 which we can change the properties or the request after request is created but which doesn't require status change.
Currently we only allow priority field to be changed but it might be extended to other properties.

**Comment by vkuznet** [comment]
Seangchan,
I need more info. Can you make a sketch? First, I need to understand if it's
going to be a separate page like (Approve) or it should be linked to request
name. Should be a separate page or an overlay on existing page. It would be
nice if you'll outline each step, e.g. click on Create menu, modify attributes,
click on Create button and land to another page where we need bla-bla-bla.
Or, go to Approve, find your request, click on it and land to another page
bla-bla-bla. Something like that will help me to understand the logic.

**Comment by ticoann** [comment]
Hi Valentin, Initially we just need to provide the page which has workflow information and update (only) priority field. I am not completely sure whether we can add the link to that page. I am thinking add to the request summary page. (I think it would be easier if we can chat through skype - I will send separate email to you)

**Comment by vkuznet** [comment]
@ticoann, Seangchan, could you please deploy #6422 and #6425 to your
reqmgr2-dev node that I can perform integration tests with new changes.

**Comment by ticoann** [comment]
Hi Valentin, I am running some test in reqmgr2-dev but I will set up the new vm for your test.

**Comment by ticoann** [comment]
couch-dev1.cern.ch is set with two patches. Let me know if you have trouble accessing it.

**Comment by vkuznet** [comment]
Thanks, I can access the node. Can I restart services on it if I need to tweak
code?

**Comment by vkuznet** [comment]
@ticoann, Seangchan, I fixed couple of things on web UI and want to try some
request, but I don't know parameters to create a request. Could you please
either let me know template/parameters to create new request or create a few by
yourself that I can test against them new code.

**Comment by ticoann** [comment]
> Thanks, I can access the node. Can I restart services on it if I need to tweak code?

Hi Valentin, the vm is all yours, do whatever you need to do.
I created a couple of request on that machine. I will send you the instruction how to create and assign the new request there in separate email.

**Comment by vkuznet** [comment]
@ticoann , Seangchan, where do we stand on this issue, there were lots of changes on web UI and I don't know if we covered this issue or not. Please advise.
