### ISSUE TITLE
add api to post the fwjr to WMAchive database

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6415]
initially API will talk to mongo db but will change to proper proxy.
WMAgent also need to handle network failure to connecting proxy.

**Comment by amaltaro** [comment]
I think this is what we're talking about:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/WMArchive.py#L8
isn't it? Then the component can handle post failures and retry it later.

If I'm wrong, please reopen.
