### ISSUE TITLE
TotalInputLumis for taskchain with input and lumilist

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6418]
Hi
note  

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_SUS-RunIISpring15FSPremix-00155__v1_T_151121_074246_8778

"LumiList":{"1":[[10001,15000],[22501,25000],[27501,30000],[50001,52500],[57501,60000],[65001,72500],[85001,87500],[92501,97500],[100001,102500],[147501,150000]]}

=> 35k lumisections, while 

"TotalInputLumis":6000

 is in the workload cache

**Comment by vlimant** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/9572/1/1/1.html

**Comment by amaltaro** [comment]
@ticoann haven't you fixed this issue?
