### ISSUE TITLE
wrong exit codes in WMSpec/Steps/Executors/CMSSW.py

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#6426]
that file produces some wrong exit code like 60515 [*]  see  thread in
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1163/2/1/1/1.html

Also 60513 and 60514 are present.
Those exit codes not only do not exits in the twiki, but are wrong since 60xxx is reserved for stageout issues.

We also do not want to be that fine grained in exit codes, and something which indicates
generic failure with SCRAM will do. We may want to take this chance to cleanup the list of codes for
Failures related to the environment setup - range 10000-19999. 

[*]
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L206

**Comment by ericvaandering** [comment]
I'll take a look at this if you want, @ticoann . You can assign it to me unless you've already fixed it.

**Comment by ticoann** [comment]
No I haven't done that. Thanks Eric, :smile:

**Comment by ericvaandering** [comment]
I'm not sure there will be a conflict. Really we just have to have the code under discussion report the correct exit codes.

**Comment by belforte** [comment]
yeah, hopefully we do not try to add more codes. Already Justas may have defined too many in #6427, but that's a different story.

**Comment by juztas** [comment]
I started going one by one and grep through WMCore/CRAB3 code and check which are used...

**Comment by belforte** [comment]
@juztas I am referring to the new one added for stageout 60321-60323 are those in use already ? Anyhow on second thought those may help. foreget my note.
