### ISSUE TITLE
Workqueue pulling only on subscription?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6431]
Dima noticed a workflow has a bunch of jobs running at FNAL, though it does not have trustiSitelists enabled. Maybe it's looking for blocks subscribed only, instead of blocks subscribed AND completed, from the phedex datasvc api, e.g.:
<block bytes="115112721870" files="30" name="/DoubleEG/Run2015D-v1/RAW#11764440-66ec-11e5-804b-001e67ac06a0" is_open="n" id="5530950">
<replica bytes="0" files="0" node="T1_US_FNAL_Disk" time_create="1448986423" time_update="1448986423" group="DataOps" se="cmssrmdisk.fnal.gov" custodial="n" node_id="1781" subscribed="y" complete="n"/>

I cannot investigate this issue now, so keeping the record here for Monday.

**Comment by ticoann** [comment]
@amaltaro, do you know which workflow is that?

**Comment by amaltaro** [comment]
fabozzi_Run2015D-DoubleEG-03Dec2015_7415p1_151203_165123_4976

all blocks were subscribed to FNAL but were 0% complete when I looked at it, the agent was reporting 6k jobs running there.

**Comment by amaltaro** [comment]
Fixed by #6807
