### ISSUE TITLE
need to rework the AllowOpportunistic support and also add a ForceAWS field

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#6445]
Reviewing the code for AllowOpportunistic, it seems to be implemented for the whole workflow, ie. if the request contains AllowOpportunistic, _ALL_ the jobs for that workflow have that flag set.

That's actually not what we want here. We only need/want this flag to be set for the top level task in the workflow. Possible implementation could follow what was done for the site lists and trustsitelist parameters, passing them on to the top level setupProcessingTask job splitter and then into the jobs.

@ticoann , @amaltaro , opinions ? First off, do you agree that the current flag is active for all jobs in a workflow (including merges, log collect, cleanup etc) ?

**Comment by hufnagel** [comment]
Oh, and we also want a ForceAWS field.

**Comment by amaltaro** [comment]
From the implementation side, I think it does set it to all jobs in the workflow (including merge and etc), setting it to Production/Processing only would be better (maybe...). About the top level only, I'm not really sure, we want any jobs of a workflow to be able to be overflown to other resources.

About ForceAWS, I don't agree introducing another flag yet (the more code, the more bug, the more maintanance, etc). And I think when we discussed it in https://github.com/dmwm/WMCore/issues/5994 and the final agreement was to create AllowOpportunistic flag only, that should give a hint to any site admin whether jobs can go to cloud/whatever resources they have or not.

**Comment by hufnagel** [comment]
If you think about how we handle sitelists in general and forcing workflows to run at certain sites, that only ever applies to the top level processing task in a workflow. Doesn't matter if the workflow is a TaskChain with multiple processing tasks, it still only matters for the first one. There are very good reasons for that which also apply just the same for the use of the AllowOpportunistic flag.

As such I am not in favor of limiting it to job type. If you imagine a TaskChain workflow with secondary a processing task, we want to run that where the data goes, not somewhere else. If we want it to run on AWS (or the opportunistic resource in general) we should make sure to stage out there.

We in any case don't have many TaskChain workflows and the ones we have are not really suited to opportunistic resources. Staging the data from the opportunistic site back to a CMS site just to submit another job later that reads it back from the CMS site to the opportunistic site is not an efficient way to work. That was the whole reason we wanted a StepChain type workflow where we can collapse everything into a single task with multiple steps.

The initial requirement was to have ForceAWS to be able to force a workflow onto AWS (instead of just allowing it to overflow there). OTOH, this was supposed to be used for testing only and so far we made do with implementing this in the condor side (ie. if you have no local resources to whatever you submit to, AllowOpportunistic effectively becomes ForceAWS). So let me talk through this here first before we renew the request for this feature.

**Comment by ericvaandering** [comment]
Yes, we had exactly the discussion in the last paragraph and the request was made *not* to have this last bit, or Tony said we did not need it, something like that. As you saw it was in the original request.

**Comment by amaltaro** [comment]
Since this feature was never really used in WMAgent, shall we close this issue?

**Comment by amaltaro** [comment]
Almost 2 years has passed, this feature has never been used in production and apparently it isn't really an issue, thus I'm closing it.
If someone has a strong argument to keep it open and to get something fixed, please make it and reopen the issue.
