### ISSUE TITLE
we should switch the PhEDExInjector to use a single worker thread instead of two

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#6451]
At the moment the PhEDExInjector runs two worker threads. One deals with file injections and block closing, the other deals with subscriptions and block deletions. As far as I can tell, we don't really need two threads here, they would be able to run sequentially.

These worker threads run on a different polling cycle, but this could be implemented within one cycle by just doing part of the work every Nth cycle.

Reason I am pushing for this now is that we have big problems in the Tier0 with garbage response to all kind of PhEDEx data service calls and we can't seem to figure out where they come from. And these problem only appear when the PhEDExInjector is running two worker threads, not when it runs just one of them (either of them).

There is another advantage to switching to a single thread. With two threads sometimes log output from them are overlapping which makes debugging from the logs difficult. Also, if one of the threads dies, the other keeps writing logs, which makes finding the relevant failure messages in the logs difficult.

**Comment by hufnagel** [comment]
@amaltaro , @ticoann , @ericvaandering , opinions ?

**Comment by amaltaro** [comment]
I'm all in favor of simplifying things, making it more stable, less bug prone and easier to debug.
If one thread can handle the load (I think it can), then I see no reason to have two (of course, unless the code is already there and stable :)).

**Comment by ericvaandering** [comment]
I have no opinions on threading issues. Something I have to educate myself on.

**Comment by ticoann** [comment]
Dirk, as we discussed earlier, I don't have any objection for this. Go for it. :smile:

**Comment by bbockelm** [comment]
When looking at #6461, I did notice that the Request objects are not thread safe -- I particularly observed pycurl errors from unprotected access to the same object from multiple threads.

So, it's probably true PhEDEx injector would benefit from moving to single thread.

**Comment by hufnagel** [comment]
Next on my todo list now that I am almost done with making the group for WMAgent PhEDEx subscriptions configurable...
