### ISSUE TITLE
Unit test for LFN<->PFN consistency

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6476]
Split off from #6437 from @mmascher 

"I have a general comment. We all know that we have two implementations of the LFN<=>PFN conversion in CMS: one that is in Perl in phedex (lfn2pfn API), and one in python here in WMCore. Unfortunately we do not have anything that checks that the two are the same, and I know for sure that on some particular iinput the two were not returning the same result.

I think it would be nice to have a unit test that takes some lfn that are used in WMCore and CRAB3, all the sites, and checks that the phedex lfn2pfn API, and the WMCore API return the same information."

Maybe when we get around to mocking PhEDEx we can add this.

**Comment by mmascher** [comment]
The other option is an `integration` test. On a first iteration it calls `lfn2pfn`, on another one it fetches the TFC from the phedex database and do the conversion using the WMCore implementation.
