### ISSUE TITLE
Tweak PostJobPrio strategy

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6490]
Watching the interaction between WMAgent schedds and the negotiator, I think we need to tweak the PostJobPrio strategy

We should set:

```
PostJobPrio1 = - $(workflow id)
PostJobPrio2 =  -(MaxWallTimeMins*100) - (RequestDisk/1000000)
```

The first can be done by the agent (the workflow ID is currently put into `PostJobPrio2`).  However, `PostJobPrio2` should be left unset by the agent -- the schedd can fill it in.

Why change?

Basically, we sometimes get a job groups of 100 jobs along the line of:

```
Job 1: MaxWallTimeMins = 200
Job 2: MaxWallTimeMins = 300
Job 3: MaxWallTimeMins = 200
Job 4: MaxWallTimeMins = 300
....
```

So, even though there are really two different types of jobs - those which need 200 minutes and those which need 300 minutes - the current ordering causes the negotiator to consider all 100 jobs individually.

The changed ordering would sort the shortest jobs first (within the same workflow and priority) in order to get them in larger groups.

**Comment by bbockelm** [comment]
The reason why this is biting us more than before is the current combination of lots of workflows _plus_ the re-reco.  It's been just enough to push over threshold.

The re-reco is mostly to blame here: the GEN-SIM jobs produce a constant number of events per lumi, meaning almost all jobs in a workflow have an identical `MaxWallTimeMins` estimate.  The re-reco is producing lots of variation in estimated runtimes at the individual job level

**Comment by ericvaandering** [comment]
So currently post priority 1 is how many sites the job can run at and 2 is (as you say) the taskID. I imagine the 2nd one is monotonically increasing per agent, but meaningless between agents. So really this is just about getting things grouped together, not really prioritizing them?

Maybe we should consider making the run times discreet along some logarithmic type scale since I gather this suggestion is just nibbling around the edges of the real problem.

**Comment by bbockelm** [comment]
Indeed, this is for sorting within a schedd.  If the schedd can sort jobs into identical groups, it can present the job group as a single entity to the negotiator.

The schedd does discretize the runtimes - however, the problem is jobs in the same group having different runtimes.  So it's a bit of a separate problem.  This:

```
Job 1: MaxWallTimeMins = 100
Job 2: MaxWallTimeMins = 1000
Job 3: MaxWallTimeMins = 100
Job 4: MaxWallTimeMins = 1000
```

is twice as much work as this:

```
Job 1: MaxWallTimeMins = 100
Job 2: MaxWallTimeMins = 100
Job 3: MaxWallTimeMins = 1000
Job 4: MaxWallTimeMins = 1000
```


NOTE: I have long-term dreams of encoding a consistent taskID into the `JobPrio` attribute -- that would allow us to process the workflows in FIFO order within the same priority level.  We'll need some work on the HTCondor side to improve negotiation speed first.

**Comment by ericvaandering** [comment]
Original discussion is in #5688 where @bbockelm suggested the current post-prio1. I'm inclined to more or less keep that since it's worked so far. Maybe -len(sites)*taskID for PP1 and Brian's suggestion for PP2?

**Comment by bbockelm** [comment]
Looking at the current set of task IDs, how about something like:

```
PostJobPrio1 = -len(sites)*1000000 - taskID
```

That basically keeps the current scheme plus improves the grouping.
