### ISSUE TITLE
Upload to dashboard an URL that points to the logArchive of a job

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6532]
As discussed in the compOps HN:
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2742.html

we could implement the same mechanism present in CRAB, which uploads an URL to the logArchive located at the site where the job was running. This way, site admins could investigate failures in dashboard and easily identify which and where the log could be found.

Sharing here additional information I discussed with Brian yesterday, the URL would be like:
root://cms-xrd-global.cern.ch//$LFN

this is the dashboard key CRAB uses to set the log name:
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L90

**Comment by belforte** [comment]
how would the LFN change when the log is transferred to CERN EOS ?

**Comment by amaltaro** [comment]
It changes quite a bit, since logs transferred to CERN come by via logCollect jobs, which creates a big tarball with <=500 logArchives and place them at both EOS and Castor. This would be an example:
/store/logs/prod/2015/06/WMAgent/amaltaro_ReDigi_cmsRun2_LumiMask_Agent107_Validation_DeterPU_v1_150618_165637_255/amaltaro_ReDigi_cmsRun2_LumiMask_Agent107_Validation_DeterPU_v1_150618_165637_255-StepOneProcDQMoutputMergeLogCollect-b668477557-1-logs.tar

**Comment by belforte** [comment]
I see. And IIUC it is not definied how long log sits at local site, so easy access to the tarball may also help.
It is possible to send the two links to dashboard, send one first, and send both when the tarball name is available. Could set names like "temp log","log tarball". Better xcheck with Pablo/Eddie (dashboard developers) anyhow, in case they have some ad hoc code which understands crab log names.

**Comment by amaltaro** [comment]
I'd start implementing first the local logArchiver tarball URL.

The second one will be trickier, since the logCollect job would need to carry the jobId (or whatever is uploaded to dashboard) of all the logs it's collecting, update this info while the job runs - we do not fail a logCollect in case it cannot collect one or some of the logs - and upload each of those job information in dashboard.

**Comment by ericvaandering** [comment]
BTW, it is in the mandate of the WMArchive project to solve this problem for good. Eventually to provide a service which will figure out where the log file is and retrieve it for you, even if on Castor.

The time scale of that may not match immediate needs, it is true.

**Comment by bbockelm** [comment]
@amaltaro - isn't the job ID in the log archive itself?  Could we use that from the merge job?

Regardless, having these easily accessible for only 24 hours is much better than the current 0 hours!

**Comment by amaltaro** [comment]
This subject just came up again in the CompOps HN. Pointing it here because it has some useful information:
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3207.html
