### ISSUE TITLE
Remove JSON wrappers

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6534]
We have two wrappers used to wrap multiple JSON implementations that should no longer be needed. Have to check that no other projects uses them (CRAB/DBS/DAS)

**Comment by ericvaandering** [comment]
DAS does something similar but with its own code. The only references I found were in StageManager (PR made for completeness) and some references from old code repos owned by @PerilousApricot

**Comment by PerilousApricot** [comment]
Which repos?

**Comment by ericvaandering** [comment]
Copies of the old WMCore and CRAB2
