### ISSUE TITLE
Add retry to our python distribution

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6539]
https://pypi.python.org/pypi/retry/0.9.1

#6538 would benefit as would plenty of other stuff we do.

**Comment by ericvaandering** [comment]
While you're doing this, please add "pep8" to the devtools RPM.

Can you give me an ETA for these?

**Comment by ticoann** [comment]
Sorry Eric for the late reply. I have initial patch but still need to test. I will finish some time next week.

https://github.com/cms-sw/cmsdist/commit/3801ce40a1643f73785180daefc14e6907462c55

**Comment by ticoann** [comment]
@ericvaandering, Patch is created. (Tested in my vm) If you want to test there is rpm in my repository. comp.sryu (1.0.13)
https://github.com/cms-sw/cmsdist/pull/2133

**Comment by ticoann** [comment]
For other application I will add when we request the new rpm. (reqmgr, reqmgr2, etc)

**Comment by ericvaandering** [comment]
Great. I'll wait for your RPM though.

**Comment by amaltaro** [comment]
It was done long ago:
https://github.com/cms-sw/cmsdist/blob/comp_gcc493/wmcore-devtools.spec#L4

Closing
