### ISSUE TITLE
update slqclachemy and cx_oracle for new architecture

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#6540]
When we switch to comp_gcc493 we should update sqlalchemy to 0.9.10 and cx_oracle to 5.2.1. I am already testing them for Tier0 replays, no issue so far (only change needed was bumping the version number in the spec file).

Any objections ?

**Comment by hufnagel** [comment]
@ticoann , how do I do this best ? Just make a pull request to the comp_gcc493 branch for cmsdist ?

**Comment by amaltaro** [comment]
Can you first share your specs (and/or RPMs), such that we can test it with MariaDB before making a PR to comp_gcc493?

**Comment by hufnagel** [comment]
As I said, the spec changes are trivial, you just change the versions to 0.9.10 and 5.2.1 respectively.

**Comment by hufnagel** [comment]
You can use my rpms as well, I build comp with wmagent 1.0.13.pre8 against the head of the comp_gcc493 branch last week. Repo is comp.hufnagel

**Comment by hufnagel** [comment]
Btw, do we want to update MariaDB too ? At least to the last patch level in the release cycle we already use (which is what I did for sqlalchemy, I didn't jump major versions there).

**Comment by hufnagel** [comment]
I would say updating versions like this if we jump architecture anyways makes sense.

**Comment by amaltaro** [comment]
It would be great to update mariadb as well, though I'm probably over-committed in February already :(
What's the last patch level release we have for mariadb? The current one is 10.0.20

**Comment by hufnagel** [comment]
MariaDB 10.0.23, so likely an easy upgrade, but also won't gain us much. Updating to the 10.1 series would get us to the current release series, but could also cause problems. Might be better to postpone this for now and tackle it another time.

**Comment by hufnagel** [comment]
I mean postpone the MariaDB upgrade, we should still update the other two :-)

**Comment by hufnagel** [comment]
The upgrades for cx_oracle and sqlalchemy are going into the cmsweb deployment today, what about MariaDB, did we make any progress in testing the new version for that ?

**Comment by amaltaro** [comment]
Not yet, though I should be able to get that tested this week

**Comment by hufnagel** [comment]
We don't expect any problems really, so you could maybe combine it with something else you need to test (on a MariaDB WMAgent).

**Comment by amaltaro** [comment]
BTW, only cx-oracle spec was updated.  sqlalchemy remains unchanged since 2014.

**Comment by hufnagel** [comment]
Ah, yes, we held off on that too pending the tests with MariaDB. Definitely use sqlalchemy 0.9.6 in your tests though. Tier0 is already using it.

**Comment by hufnagel** [comment]
Ok, I am closing this since both cx_oracle and sqlalchemy were updated.
