### ISSUE TITLE
fwjr has repeated PFN 

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMCore#6541]
The sample fwjr we got from WMAgent has the same PFN repeated twice for the same key/value pair. See https://github.com/dmwm/WMArchive/blob/master/test/data/fwjr_processing.json#L32 .

Example:
 "pfn": "root://cmseos.fnal.gov//lustre/unmerged/logs/prod/2015/10/22/fabozzi_Run2015BCharmonium-16Oct2015_7414_151016_150741_9653/DataProcessing/0000/0/37d35a6a-78c1-11e5-9155-a0369f23cf8a-0-0-logArchive.tar.gz<root://cmseos.fnal.gov/lustre/unmerged/logs/prod/2015/10/22/fabozzi_Run2015BCharmonium-16Oct2015_7414_151016_150741_9653/DataProcessing/0000/0/37d35a6a-78c1-11e5-9155-a0369f23cf8a-0-0-logArchive.tar.gz>",

Please fix it.

**Comment by ticoann** [comment]
done
