### ISSUE TITLE
byprepid view not returning all data

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6561]
while 

 jen_a_recovery-0-fabozzi_Run2015A-Jet-boff-27Jan2016_763p2__160203_193932_3291.request.schema.PrepID = 'ReReco-Run2015A-boff-27Jan2016-0007'

 it does not show up in 

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/_design/ReqMgr/_view/byprepid?key="ReReco-Run2015A-boff-27Jan2016-0007"

is there a better recommended api like https://cmsweb.cern.ch/reqmgr2/data/request?prepid=...

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, you can use following.
https://cmsweb.cern.ch/reqmgr2/data/request?prep_id=ReReco-Run2015A-boff-27Jan2016-0007

If that is OK, please close the issue, otherwise, I will add function you want to use. Thanks,

**Comment by vlimant** [comment]
Hi Seangchan,

 jen_a_recovery-0-fabozzi_Run2015A-Jet-boff-27Jan2016_763p2__160203_193932_3291 


*should* be in the result, but it is *not*. Thanks for the new api, but it does not return the correct information. This is subject of this issue.

**Comment by ticoann** [comment]
Hi Jean-Roch,
Sorry I misunderstood the problem. Yes you are right that doesn't include the PrepID
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/jen_a_recovery-0-fabozzi_Run2015A-Jet-boff-27Jan2016_763p2__160203_193932_3291

However, if acdc is created by web interface that shouldn't happen. It should take from original workflow PrepID.
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/fabozzi_Run2015A-Jet-boff-27Jan2016_763p2_160128_142039_5968

I checked a few acdc requests but those seems to be fine. (Not checked all the data though)
I will check with Jen how that acdc is created.  
For this case, I updated the PrepID manually, you should see the workflow now.
But I am not sure how this happened. If you have any other case you find, please let me know.
Thanks,

**Comment by vlimant** [comment]
thanks for the manual intervention. I think I have spotted a few other cases where the spec has the correct prepid, that is not showing up in the https://cmsweb.cern.ch/reqmgr2/data/request?prep_id=whatever api
the acdc was created properly, with the correct prepid, but that value did not make it properly to the workload cache. rather bizarre IMO

**Comment by vlimant** [comment]
Never has happened ever since.
