### ISSUE TITLE
Replace inner try/except by decorator

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6562]
once retry package is included in our stack, see #6539

**Comment by ericvaandering** [comment]
In which code?

**Comment by amaltaro** [comment]
Hmm, I was almost sure I've seen that code in one not old PR, but I failed to find it. I thought it was with the stage out, but there we have try/except inside a loop (according to the job retry settings of the agent).

I'm closing this issue, sorry for the noise.

**Comment by ericvaandering** [comment]
There was the code I flagged from Dirk. We should think about simplifying some code if we can.

**Comment by amaltaro** [comment]
I'm all for simplifying! ;)

**Comment by hufnagel** [comment]
Separate issue though, I am not going to touch the PhEDExInjector refactoring PR.
