### ISSUE TITLE
Stage-out into S3 

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/WMCore#6591]
S3 does not support adler32 checksum and so the stage-out into the data bridge for CMS@home is failing. As far as I can see, the checksum check is hardcoded in the gfal plugin (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Plugins/GFAL2Impl.py#L44). 

Does it make sense to enable adler32 checksum based on the protocol? for e.g if it s3, disable the check.

**Comment by HassenRiahi** [comment]
@hufnagel as discussed today pls find below a diff of the patch:

-bash-4.1$ diff sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMCore/Storage/Plugins/GFAL2Impl.py sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMCore/Storage/Plugins/GFAL2Impl_orig.py 
44c44
<         transferCommand = "env -i X509_USER_PROXY=$X509_USER_PROXY gfal-copy -t 2400 -T 2400 -p -vvv %s %s %s " %\
\---
\>         transferCommand = "env -i X509_USER_PROXY=$X509_USER_PROXY gfal-copy -t 2400 -T 2400 -p -K adler32 -vvv %s %s %s " %\

**Comment by hufnagel** [comment]
@ticoann , since this is site specific, the easiest would be to implement an option like "skip_checksum" or something like this that can be set in the site-local-config and then triggers this change in the calling of the gfal2-copy. What do you think

**Comment by hufnagel** [comment]
Btw, the priority on this recently changed since we want to start some full chain tests with cms@home and the agent submitting to cms@home currently doesn't work without this manual patch.

**Comment by ticoann** [comment]
@hufnagel, Dirk, is this (supporting for adler32) depends on the gfal2 version or external package (alder32) has to be installed in the site?
I was wondering whether we can check whether alder32 is available in general by running simple command and set the option according to that. That way, it could be more general and doesn't have to change site-local-config.

**Comment by amaltaro** [comment]
WMAgent does not use the Plugins (v2) implementations, instead it uses this one
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/GFAL2Impl.py#L88

which has the checksum configurable from the stage out call
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/StageOutImpl.py#L168

which seems to default to None.

We should first get that agent upgraded (it's super old) and then we see what needs to be done to it.

**Comment by ticoann** [comment]
Sorry I didn't even see which code it was using. Please ignore my previous message.

**Comment by juztas** [comment]
Even if its default None, production specifies this argument, and in this case it uses checksum. Looking through code, I don't see an easy way to disable this for production. For analysis, it worked, as it is not using checksum. Specifying through site-local-config sounds good idea.

**Comment by hufnagel** [comment]
To follow up on this, who can actually make the change ? I am off until Tuesday and swamped with a gazillion other things, so if you wait for me it'll take some time. Anyone else want to give it a shot ?

Basically need two pieces:

- adding a skip-checksum option

- actually using that option to turn off using checksums in the gfal2 call

**Comment by hufnagel** [comment]
@HassenRiahi , there is a pull request with the fix for this problem.
