### ISSUE TITLE
Create the workload config page.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6599]
Basically the same page as following

workload config page (not editable - doesn't need to do any specific format - will send the string just change "\n" -> "
")
https://cmsweb-testbed.cern.ch/reqmgr/view/showWorkload?requestName=amaltaro_TaskChain_MC_PhEDExSingleThread_v1_160209_165949_6091

The api need to be called to get the data is  (GET request)

https://reqmgr2-dev.cern.ch/reqmgr2/data/workload_config/sryu_MonteCarlo_eff_wq_testt_160217_212435_2532

link can be provide from initial page.

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_MonteCarlo_eff_wq_testt_160217_212435_2532

**Comment by vkuznet** [comment]
Seangchan, please review this PR: https://github.com/dmwm/WMCore/pull/6605 I added config button, along with API in ReqMgr2.
