### ISSUE TITLE
Remove WMBSService from WMAgent component

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6612]
This component provide the REST service on wmbs and agent status. But it is causing security problem on FNAL agent since the port is open to public. Since this service is not used by anyone as far as I know, we should delete the component. 
However configuration of this component used by other components AgentStatusWatcher, Tier0 as well as passed by secrete file. Need a careful test when it gets removed

**Comment by amaltaro** [comment]
And Seangchan has already removed it (starting at least in 1.1.2.x)
