### ISSUE TITLE
reqmgr2 splitting issue

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6619]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=sryu_ReDigi_LumiMask_reqmgr2_test_160223_223012_9725

Following workflow is in assign-approved status but not able to change splitting parameter.

**Comment by vkuznet** [comment]
Here we go: https://github.com/dmwm/WMCore/pull/6620 I misspelled the status.

**Comment by vkuznet** [comment]
Seangchan, let me know which exact statuses we should cover for making splitting parameter editable.

**Comment by amaltaro** [comment]
Valentin, "assignment-approved" is the only status that we should make the splitting editable.

**Comment by vkuznet** [comment]
Then, take the PR and close the issue :)
