### ISSUE TITLE
WmAgentScripts/assignWorkflow

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#6625]
```
python assignWorkflow.py sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339 --testbed -t testbed-vocms009
```

```
 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>404 Not Found</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>404 Not Found</h2>
        <p>Given requestName not found</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>

**Comment by ticoann** [comment]
@jenimal Jen could you test this again? This should be fixed with following patch

https://github.com/CMSCompOps/WmAgentScripts/pull/129

**Comment by jenimal** [comment]
Yeah Worked!
 python assignWorkflow.py sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012 --testbed -t testbed-vocms009
cmsweb-testbed.cern.ch
[{u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012': {u'InputDataset': u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN', u'ReqMgr2Only': True, u'Group': u'DATAOPS', u'OpenRunningTimeout': 1800, u'Comments': u'MCFromGEN LumiBased splitting with 1l per job. Half an hour opened', u'Requestor': u'sryu', u'ProcessingString': u'START53_V7C', u'ScramArch': u'slc6_amd64_gcc472', u'SizePerEvent': 1154, u'ConfigCacheID': u'1ad063a0d73c1d81143b4182cbf84793', u'Memory': 2300, u'RunBlacklist': [], u'PrepID': u'B2G-Summer12-00736', u'BlockWhitelist': [], u'RequestType': u'MonteCarloFromGEN', u'timeStamp': 1456430697, u'MergedLFNBase': u'/store/data', u'TimePerEvent': 16.870000000000001, u'InputDatasetTypes': {}, u'OutputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v2/GEN-SIM', u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v3/GEN-SIM', u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v4/GEN-SIM'], u'LumisPerJob': 300, u'RequestDate': [2016, 2, 25, 19, 33, 37], u'AcquisitionEra': u'Summer12', u'PrimaryDataset': u'QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph', u'CouchDBName': u'reqmgr_config_cache', u'CMSSWVersion': u'CMSSW_5_3_19', u'RequestSizeFiles': 0, u'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'RequestPriority': 90000, u'ProcessingVersion': 4, u'SplittingAlgo': u'LumiBased', u'RequestTransition': [{u'Status': u'new', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428817}, {u'Status': u'new', u'DN': None, u'UpdateTime': 1456853656}, {u'Status': u'assignment-approved', u'DN': None, u'UpdateTime': 1456853658}], u'RequestName': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012', u'RequestString': u'MonteCarloFromGEN_Jen_reqmgr2', u'InputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN'], u'CouchURL': u'https://cmsweb-testbed.cern.ch/couchdb', u'TotalTime': 28800, u'CouchWorkloadDBName': u'reqmgr_workload_cache', u'OriginalRequestName': u'jen_a_MonteCarloFromGEN_Jen_reqmgr2_160225_210455_4068', u'RequestWorkflow': u'https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012/spec', u'GlobalTag': u'START53_V7C::All', u'BlockBlacklist': [], u'RunWhitelist': [], u'FilterEfficiency': 1, u'DbsUrl': u'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader', u'SoftwareVersions': [u'CMSSW_5_3_19'], u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'_id': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012', u'RequestStatus': u'assignment-approved', u'Campaign': u'reqmgr2-validation', u'RequestNumEvents': 50000}}]
Assigned workflow: sryu_MonteCarloFromGEN_Jen_reqmgr2_160301_183412_7012 to site: ['T1_DE_KIT', 'T1_ES_PIC', 'T1_FR_CCIN2P3', 'T1_IT_CNAF', 'T1_RU_JINR', 'T1_UK_RAL', 'T1_US_FNAL', 'T2_CH_CERN', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_ES_CIEMAT', 'T2_FR_CCIN2P3', 'T2_FR_IPHC', 'T2_IT_Bari', 'T2_IT_Legnaro', 'T2_IT_Pisa', 'T2_IT_Rome', 'T2_UK_London_Brunel', 'T2_UK_London_IC', 'T2_US_Caltech', 'T2_US_Florida', 'T2_US_MIT', 'T2_US_Nebraska', 'T2_US_Purdue', 'T2_US_UCSD', 'T2_US_Wisconsin'] with processing version 4
