### ISSUE TITLE
WmAgentScripts/rejectAndClone.py

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#6626]
Error looks similar to the assign script issue, verified that the script works just fine for the non-test version.

```
jen_a@vocms049:~/WmAgentScripts_testbed $ python rejectAndClone.py  sryu_ReReco_Parents_reqmgr2_test_160223_223026_9979
```
```
Rejecting workflow: sryu_ReReco_Parents_reqmgr2_test_160223_223026_9979
Invalidating datasets
Traceback (most recent call last):
  File "rejectAndClone.py", line 83, in <module>
    main()
  File "rejectAndClone.py", line 73, in main
    datasets = reqMgrClient.outputdatasetsWorkflow(url, wf)
  File "/afs/cern.ch/user/j/jen_a/WmAgentScripts_testbed/reqMgrClient.py", line 477, in outputdatasetsWorkflow
    datasets = requestManagerGet(url,'/reqmgr/reqMgr/outputDatasetsByRequestName?requestName='+workflow)
  File "/afs/cern.ch/user/j/jen_a/WmAgentScripts_testbed/reqMgrClient.py", line 335, in requestManagerGet
    r1=conn.request("GET",request)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 931, in _send_request
    self.putrequest(method, url, **skips)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 847, in putrequest
    if url.startswith('http'):
AttributeError: 'dict' object has no attribute 'startswith'

```

**Comment by ticoann** [comment]
@jenimal, Jen, could you run this test again with updated patch.
https://github.com/CMSCompOps/WmAgentScripts/pull/129
I am getting some DBS permission error. I just want to check whether you are getting a same error.

```
/SMS-T2-4bd_mStop-250_mLSP-170to240_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/FAKE-MCRUN2_71_V1-v1/LHE
Traceback (most recent call last):
  File "rejectAndClone.py", line 82, in <module>
    main()
  File "rejectAndClone.py", line 75, in main
    dbs3.setDatasetStatus(ds, 'INVALID', files=True)
  File "/afs/cern.ch/user/s/sryu/WmAgentScripts/dbs3Client.py", line 162, in setDatasetStatus
    dbsapi.updateDatasetType(dataset=dataset, dataset_access_type=newStatus)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 1358, in updateDatasetType
    return self.__callServer("datasets", params=kwargs, callmethod='PUT')
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 403: You are not allowed to access this resource
```

**Comment by ticoann** [comment]
@jenimal  Hi Jen, it seem that error is due to pointing wrong url.
Could you uncomments following and run the test?

https://github.com/CMSCompOps/WmAgentScripts/blob/master/resubmit.py#L233

**Comment by jenimal** [comment]
jen_a@vocms049:~/WmAgentScript_testbed $ python rejectAndClone.py sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339
Rejecting workflow: sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339
sending reqmgr2 request
Invalidating datasets
[{u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339': {u'InputDataset': u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN', u'ReqMgr2Only': True, u'SoftTimeout': 159600, u'PrepID': u'B2G-Summer12-00736', u'MaxMergeEvents': 50000, u'CustodialSites': [], u'OpenRunningTimeout': 1800, u'Comments': u'MCFromGEN LumiBased splitting with 1l per job. Half an hour opened', u'MaxRSS': 4294967296, u'Requestor': u'sryu', u'ProcessingString': u'START53_V7C', u'ScramArch': u'slc6_amd64_gcc472', u'SizePerEvent': 1154, u'ConfigCacheID': u'1ad063a0d73c1d81143b4182cbf84793', u'Memory': 2300, u'RunBlacklist': [], u'Group': u'DATAOPS', u'MaxMergeSize': 4294967296, u'UnmergedLFNBase': u'/store/unmerged', u'BlockWhitelist': [], u'RequestType': u'MonteCarloFromGEN', u'MergedLFNBase': u'/store/backfill/1', u'TimePerEvent': 16.870000000000001, u'OutputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v2/GEN-SIM'], u'TotalInputEvents': 2500, u'RequestDate': [2016, 2, 25, 19, 33, 37], u'AcquisitionEra': u'Summer12', u'PrimaryDataset': u'QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph', u'CouchDBName': u'reqmgr_config_cache', u'CMSSWVersion': u'CMSSW_5_3_19', u'checkboxsryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339': u'checked', u'MinMergeSize': 2147483648, u'RequestPriority': 90000, u'SiteWhitelist': [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_CH_CERN', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_IT_Pisa', u'T2_IT_Rome', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_UCSD', u'T2_US_Wisconsin'], u'LumisPerJob': 1, u'ProcessingVersion': 2, u'Teams': [u'testbed-vocms009'], u'SplittingAlgo': u'LumiBased', u'TotalEstimatedJobs': 100, u'RequestTransition': [{u'Status': u'new', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428817}, {u'Status': u'assignment-approved', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428820}, {u'Status': u'assigned', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456552927}, {u'Status': u'acquired', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456553106}, {u'Status': u'running-open', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456813507}, {u'Status': u'running-closed', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456813515}, {u'Status': u'completed', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456823104}], u'RequestName': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339', u'RequestString': u'MonteCarloFromGEN_Jen_reqmgr2', u'InputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN'], u'CouchURL': u'https://cmsweb-testbed.cern.ch/couchdb', u'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'TotalTime': 28800, u'CouchWorkloadDBName': u'reqmgr_workload_cache', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'RequestWorkflow': u'https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339/spec', u'Teamtestbed-vocms009': u'checked', u'Campaign': u'reqmgr2-validation', u'BlockBlacklist': [], u'RunWhitelist': [], u'MaxVSize': 4294967296, u'FilterEfficiency': 1, u'GlobalTag': u'START53_V7C::All', u'DbsUrl': u'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader', u'TotalInputLumis': 100, u'SoftwareVersions': [u'CMSSW_5_3_19'], u'TotalInputFiles': 1, u'SiteBlacklist': [], u'action': u'Assign', u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'_id': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339', u'RequestStatus': u'completed', u'RequestNumEvents': 50000, u'Dashboard': u'reprocessing'}}]
/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v2/GEN-SIM
Files will be set to: 0 in DBS3
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339/spec
Traceback (most recent call last):
  File "rejectAndClone.py", line 83, in <module>
    main()
  File "rejectAndClone.py", line 79, in main
    clone = resubmit.cloneWorkflow(wf, user, group)
  File "/afs/cern.ch/user/j/jen_a/WmAgentScript_testbed/resubmit.py", line 177, in cloneWorkflow
    helper = reqMgrClient.retrieveSchema(workflow, reqmgrCouchURL)
  File "/afs/cern.ch/user/j/jen_a/WmAgentScript_testbed/reqMgrClient.py", line 746, in retrieveSchema
    helper.load(specURL)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.8.patch1/lib/python2.6/site-packages/WMCore/WMSpec/Persistency.py", line 75, in load
    data = request.makeRequest('', incoming_headers = {"Accept" : "*/*"})
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.8.patch1/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.8.patch1/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 275, in makeRequest_httplib
    raise e
httplib.HTTPException
jen_a@vocms049:~/WmAgentScript_testbed $

**Comment by jenimal** [comment]
needed to change url in the resubmit script and now it works
jen_a@vocms049:~/WmAgentScript_testbed $ python rejectAndClone.py sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339
Rejecting workflow: sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339
sending reqmgr2 request
Invalidating datasets
[{u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339': {u'InputDataset': u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN', u'ReqMgr2Only': True, u'SoftTimeout': 159600, u'PrepID': u'B2G-Summer12-00736', u'MaxMergeEvents': 50000, u'CustodialSites': [], u'OpenRunningTimeout': 1800, u'Comments': u'MCFromGEN LumiBased splitting with 1l per job. Half an hour opened', u'MaxRSS': 4294967296, u'Requestor': u'sryu', u'ProcessingString': u'START53_V7C', u'ScramArch': u'slc6_amd64_gcc472', u'SizePerEvent': 1154, u'ConfigCacheID': u'1ad063a0d73c1d81143b4182cbf84793', u'Memory': 2300, u'RunBlacklist': [], u'Group': u'DATAOPS', u'MaxMergeSize': 4294967296, u'UnmergedLFNBase': u'/store/unmerged', u'BlockWhitelist': [], u'RequestType': u'MonteCarloFromGEN', u'MergedLFNBase': u'/store/backfill/1', u'TimePerEvent': 16.870000000000001, u'OutputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v2/GEN-SIM'], u'TotalInputEvents': 2500, u'RequestDate': [2016, 2, 25, 19, 33, 37], u'AcquisitionEra': u'Summer12', u'PrimaryDataset': u'QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph', u'CouchDBName': u'reqmgr_config_cache', u'CMSSWVersion': u'CMSSW_5_3_19', u'checkboxsryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339': u'checked', u'MinMergeSize': 2147483648, u'RequestPriority': 90000, u'SiteWhitelist': [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_CH_CERN', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_IT_Pisa', u'T2_IT_Rome', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_UCSD', u'T2_US_Wisconsin'], u'LumisPerJob': 1, u'ProcessingVersion': 2, u'Teams': [u'testbed-vocms009'], u'SplittingAlgo': u'LumiBased', u'TotalEstimatedJobs': 100, u'RequestTransition': [{u'Status': u'new', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428817}, {u'Status': u'assignment-approved', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428820}, {u'Status': u'assigned', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456552927}, {u'Status': u'acquired', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456553106}, {u'Status': u'running-open', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456813507}, {u'Status': u'running-closed', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456813515}, {u'Status': u'completed', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'UpdateTime': 1456823104}], u'RequestName': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339', u'RequestString': u'MonteCarloFromGEN_Jen_reqmgr2', u'InputDatasets': [u'/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12pLHE-DMWM_Validation_DONOTDELETE_Alan_TEST-v1/GEN'], u'CouchURL': u'https://cmsweb-testbed.cern.ch/couchdb', u'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'TotalTime': 28800, u'CouchWorkloadDBName': u'reqmgr_workload_cache', u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch', u'RequestWorkflow': u'https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339/spec', u'Teamtestbed-vocms009': u'checked', u'Campaign': u'reqmgr2-validation', u'BlockBlacklist': [], u'RunWhitelist': [], u'MaxVSize': 4294967296, u'FilterEfficiency': 1, u'GlobalTag': u'START53_V7C::All', u'DbsUrl': u'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader', u'TotalInputLumis': 100, u'SoftwareVersions': [u'CMSSW_5_3_19'], u'TotalInputFiles': 1, u'SiteBlacklist': [], u'action': u'Assign', u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'_id': u'sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339', u'RequestStatus': u'completed', u'RequestNumEvents': 50000, u'Dashboard': u'reprocessing'}}]
/QDTojWinc_NC_M-1200_TuneZ2star_8TeV-madgraph/Summer12-START53_V7C-v2/GEN-SIM
Files will be set to: 0 in DBS3
https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/sryu_MonteCarloFromGEN_Jen_reqmgr2_160225_203337_2339/spec
Submitting workflow
Cloned workflow: jen_a_MonteCarloFromGEN_Jen_reqmgr2_160309_182401_5649
jen_a@vocms049:~/WmAgentScript_testbed $ vim resubmit.py

**Comment by vlimant** [comment]
Hi, I think that the clone was made in reqmgr1 and not reqmgr2 because reqMgrClient.submitWorkflow by default in the patch would submit to regmgr1
When switching to the regmgr2=True I get an error with the same interface.

**Comment by vlimant** [comment]
clearly https://cmsweb-testbed.cern.ch/reqmgr/view/details/jen_a_MonteCarloFromGEN_Jen_reqmgr2_160309_182401_5649 that issue has to be reopened
