### ISSUE TITLE
Need to add OriginalRequestName to the ReqMgr2 clone api

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6630]

**Comment by ticoann** [comment]
Alan, which call are you using to clone the request?

**Comment by amaltaro** [comment]
For reqmgr, we used to make a post to create/makeSchema and add the OriginalRequestName in the client/script side.
For reqmgr2, we could do the same for now. With my draft script, I was making a post to reqmgr2/data/request, so we could again have it on the client side until we validate and make sure the api does what it needs to do :-)

**Comment by amaltaro** [comment]
Closing it since it's no longer wanted, I guess :)
In summary, we add this key when the **clone** api is used
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L176

but later on we remove it such that it passes the factory validation:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Utils/Validation.py#L155

**Comment by vlimant** [comment]
OriginalRequestName does stay somewhere in the workflow cache or schema, right ? it is used to find out what is the parent request of a given acdc.

**Comment by amaltaro** [comment]
Yes for ACDC workflows. No for vanilla clone workflows.

**Comment by vlimant** [comment]
For clones, OriginalRequestName is used to fetch the original request and some of the parameters required for assignment. If that goes away, we would have to work something out, I don't see a reason to remove it as a decorator that can be absolutely practical

**Comment by amaltaro** [comment]
Which kind of parameters you fetch from the original that can't be fetched from the new request?

Maybe we can properly fix it without having the need for an additional parameter. How about this issue/question:
https://github.com/dmwm/WMCore/issues/7862
?
Perhaps that's exactly what you need

**Comment by vlimant** [comment]
TrustSitelists, TrustPUSitelists, ProcessingVersion, MergedLFNBaseand, SiteWhitelist (in some cases) those were not available in the schema of the clone, while present in the schema of the ancestor.

**Comment by vlimant** [comment]
also acquisitionera and processingstring I think

**Comment by amaltaro** [comment]
Seangchan and I had lots of discussion on this matter and - I think - I convinced him to treat clones just as a brand new request, meaning it has to have only *creation* arguments.

Said that, most of these parameters will be properly present in the clone, besides SiteWhitelist and the Trust flags. However, I understand unified has all these rules mapped somewhere and it knows where and how to assign these workflows, no?
