### ISSUE TITLE
ReqMgr2 states in the GUI

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6632]
Valentin, Seangchan, looking at the main remqgr2 page, I see it listing "negotiating" status. This is not a request valid status (only a WQE status, actually). How about we remove that?

Moreover, I also see "running" status, this is no longer a valid status (but it was < 2 years ago). How about we remove it as well from the reqmgr2 interface?

**Comment by ticoann** [comment]
Yes you are right. I will removed that. Reqmgr2 automatically generates the state transition from the api. So I don't think anything need to be done in GUI. I am supprised that negotiating state are propagated.

**Comment by amaltaro** [comment]
The only thing left to do here is the removal of the `running` state. I suggest we remove it once ReqMgr is dead.

**Comment by amaltaro** [comment]
Fixed by #7251 and another PR that I cannot find right now.
