### ISSUE TITLE
Need the team entry in assign page in reqmgr2

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6633]
First create the REST api to give the team list

**Comment by vkuznet** [comment]
Seangchan,
I need more info about what needs to be done. Assuming that api exists which
will return list of teams. What do you need to do on web UI?
Valentin.

**Comment by ticoann** [comment]
web UI need to list the teams in assignment page so user can select the team.
But I will have api ready (also need to make sure assignment won't go through without team) first.
When that is ready I will chat with you what exactly need to be done. Thanks

**Comment by vkuznet** [comment]
Seangchan, please check reqmgr-dev and let me know if this is what you wanted.
I added drop-down list of teams and so far put teams from static lists (will
replace it with API once its ready). The team value will be passed to
parameters as "team".

**Comment by ticoann** [comment]
Thanks Valentin, but I didn't mean that you should work on weekend. I don't think I can add api this weekend so please STOP WORKING. :smile:  I shouldn't marked as high priority
Anyway change looks good. but I was more thought about setting pages but front page would be fine too.
It just need to submit the team with other parameters.  (with the same put (or post) request).
Anyway, we can always submit teams in json format. so It is not that critical. I am also waiting for some more test be done (McM and Ops script) before create the new tag and make the pull request.
Thanks again for quick addition, but please enjoy your weekend. :smile:

**Comment by vkuznet** [comment]
Seangchan, I made initial changes and here is PR https://github.com/dmwm/WMCore/pull/6675 but I need an API from you to complete it.

**Comment by vkuznet** [comment]
The PR #6675 is closed now, what should we do with this issue?
