### ISSUE TITLE
Reqmgr2 return parameter

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#6636]
Hi,

could reqmgr2 api[*] of wf also return wf's original/first priority which it was submitted?

[*] https://cmsweb.cern.ch/reqmgr2/data/request?name=wf_id

**Comment by ticoann** [comment]
@anorkus, Hi Antans, Do you mean in case priority changed you want to have value of original priority?
Did that information available in reqmgr1?  Anyway, we can add that. Do you want to have the history of priority change?

FYI,  for the priority of the workflow we have "RequestPriority": 85000

**Comment by anorkus** [comment]
hi, yes you are correct. It was available in request schema(?). I would prefer just to have original priority workflow was submitted - no need to keep history as people are interested in current priority. Also string is easier to index than a list ;) Our services just want to "know" original submission priority.

Yeah, i know all the fields in dictionary :)

**Comment by amaltaro** [comment]
Seangchan, the issue here is when someone changes the request priority, that would update the RequestPriority value in the workload and with that the original prio is gone.
For reqmgr, I believe that information is in the workload webpage that people used to parse.

**Comment by ticoann** [comment]
Antanas,  Alan, thanks for the explanation, Is It OK if I just add InitialPriority field which keeps initial priority. #6639 (We can still get that information schema page (*) "request.priority" but I will deprecate that page all together). So it any code is parsing that page to get the information, please let me know which information is needed from that page. I will either create the new API or point the api which can get the same information. Thanks, 

(*)
https://cmsweb-testbed.cern.ch/reqmgr2/config?name=pdmvserv@vocms081.cern.ch_EXO-RunIISummer15GS-06013_00271_v1__160226_154130_8168
