### ISSUE TITLE
ReqMgr2 request name structure

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6637]
Antanas created a new reqmgr2 request today:
pdmvserv@vocms081.cern.ch_SUS-RunIIWinter15pLHE-00232_00146_v1__160226_103421_890

using this DN:
https://cmsweb.cern.ch/sitedb/prod/people/pdmvserv%40vocms081.cern.ch

Since we don't have the same username registration as we do for reqmg (oracle), I believe we are somehow getting the sitedb "username" or so, to prepend to the request name.

**Comment by amaltaro** [comment]
forgot to tag @anorkus

**Comment by ticoann** [comment]
So it seems this is nor in RequestSting. It is Requestor. 
We can have 2 choices
1. leave Requestor as it is but filter out @ from RequestName
2. filter out @ from both Requestor and RequestName.

I would do 1. But we can do 2 if you prefer.

**Comment by amaltaro** [comment]
I agree, Seangchan! I suggest we remove everything that comes after @ (inclusive) from the Requestor name.

**Comment by vlimant** [comment]
Hi guys, can we also take out everything after @inclusive away from inside the schema so that one can perform the proper search in the DB with a given user, without having to know where the user has injected the workflow from ?
