### ISSUE TITLE
Jen's Ops script tests 

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6640]
This will contain the list of the scripts tested/and need to be tested. 
1. whether the test is successful or not, 
2, exact command for the test.
3. If the test failed and error occurred, create the new issue with the error message.

**Comment by jenimal** [comment]
for directions on running: 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsWorkflowOperationsWMAgentScripts#assignWorkflow_py

Scripts that interact with the Request Manager

Tested - succeed parameters not checked
assignWorkflow.py - Done! https://github.com/dmwm/WMCore/issues/6625
rejectAndClone.py https://github.com/dmwm/WMCore/issues/6626
abortWorkflows.py https://github.com/dmwm/WMCore/issues/6687

Test Failed

Not tested
abortWorkflows.py
abortAndClone.py
rejectWorkflows.py
reqMgrClient.py
reqmgr.py
changeSplittingWorkflow.py
forceCompleteWorkflows.py
getInputLocation.py
dbsTest.py
phedexClient.py
phedexSubscriptionTest.py
closeOutWorkflows.py
resubmit.py
makeACDC.py
makeAllACDCs.py
extendWorkflow.py
recoverMissingLumis.py
resubmitUnprocessedBlocks.py
python stuckRequestDiagnosis.py
WFComplete_main.py
Priorities.py
listReqTapeFamilies.py
assignProdTaskChain.py
assignWorkflowsAuto.py
changePriorityWorkflow.py
mcassign.py
mctapefamilies.py
reqinfo.py
setrequeststatus.py

**Comment by ticoann** [comment]
@jenimal Jen, Jean-Roch found some problems.
I updated the patch
https://github.com/CMSCompOps/WmAgentScripts/pull/129, Please proceed the test with new patch

**Comment by vlimant** [comment]
https://github.com/vlimant/WmAgentScripts/tree/reqmgr2_migration is the branch with tested calls and back/forward compatibilities.
I am tempted to create a new script merging all that have to be merged ...

**Comment by prozober** [comment]
Test Failed
changePriorityWorkflow.py [#6704](https://github.com/dmwm/WMCore/issues/6704)

**Comment by vlimant** [comment]
I tried, with the patch and changing the urls properly and

python rejectAndClone.py sryu_ObjID2012DDoubleElectron_v4_v2_150126_223023_4994 
Rejecting workflow: sryu_ObjID2012DDoubleElectron_v4_v2_150126_223023_4994
Invalidating datasets
/DoubleElectron/None-v0/DQM
Files will be set to: 0 in DBS3
/DoubleElectron/None-v0/AOD
Files will be set to: 0 in DBS3
Submitting workflow
Cloned workflow: vlimant_ObjID2012DDoubleElectron_v4_v2_160315_190726_2738


but vlimant_ObjID2012DDoubleElectron_v4_v2_160315_190726_2738 is in reqmgr1 . So there is something needed on the ops script side for testing ; is there anything already started @ticoann @jenimal @prozober ? something clear and very puzzling is 

m = re.search("details\/(.*)\'", response)
in resubmit.py which just cannot work as is for reqmgr2 as the return value is much different

**Comment by jenimal** [comment]
It was requested that I sort the scripts by how often they get used:
In the main directory:
Dialy/Weekly:
assignProdTaskChain.py
assignWorkflow.py
duplicateEvents.py
findOrphanACDCs.py
makeACDC.py
makeAllACDCs.py
rejectAndClone.py
rejectWorkflows.py
resubmit.py
stuckRequestDiagnosis.py
WorkflowPercentage.py
recover/recoverMissingLumis.py
recover/recover.py
www/summary-mcclosedout.py
www/summary-mcrunning.py


Things that get used every once in awhile 
changePriorityWorkflow.py
changeSplittingWorkflow.py
DBS3SetDatasetStatus.py
extendWorkflow.py
forceCompleteWorkflows.py
getDatasetStatus.py
getInputLocation.py
StoreResults/createStoreResults.py
StoreResults/MigrationToGlobal.py
StoreResults/RequestQuery.py
StoreResults/StoreResultsAddCMSSWReleases.py
StoreResults/transferFiles_FNAL.py

very occasionally : 
condor_global_overview.py
condor_overview.py
The closeoutWorkflows* scripts we thought were depreciated, but needed again for a bit when unified wasn't picking up ReReco, or other workflows
Has unified picked up below functionality?
resubmitUnprocessedBlocks.py
resubmitWithBlockBlacklist.py

announceWorkflows.py
checkACDCCollections.py
closeOutWorkflowsFiltered.py
closeOutWorkflowsManual.py
closeOutWorkflows.py
closeOutWorkflowsWeb.py
createSitesBackfill.py
dataLock.py
dbs3Client.py
deleteInvalidOutput.py
findWorkflows.py
fix_merge_acdc.py
fixPhEDEx.py
setCascadeStatus.py
setDatasetStatusDBS3.py

__init__.py
jenreqMgrClient.py
killWorkflowAgent.py
lastWeekProcessing.py
listWorkflows.py
McMClient.py
notCustodialDatasets.py
phedexClient.py
pledged.py
processingCampaignOverview.py
reqMgrClient.py
reqmgr.py
site_view.py
unprocessedBlocks.py
utils.py
WorkflowJobInfo.py
WorkflowSummary.py

**Comment by vlimant** [comment]
can someone please try to make acdc to vlimant_Run2015A-HcalHPDNoise-boff-15Mar2016_763p2_160330_105901_3863 in the testbed using https://github.com/CMSCompOps/WmAgentScripts/tree/merging_unified_testbed_reqmgr2

**Comment by amaltaro** [comment]
Shall we close this issue?

**Comment by jenimal** [comment]
This has largely been taken over By Ali, @areinsvo

**Comment by vlimant** [comment]
please close
