### ISSUE TITLE
Unified tests

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6641]
This will contain the list of the scripts tested/and need to be tested. 
1. whether the test is successful or not, 
2, exact command for the test.
3. If the test failed and error occurred, create the new issue with the error message.

**Comment by mcremone** [comment]
testing **injector.py**, first issue:

considering sryu_B2G-Summer12-00736_v4_v2_150126_222415_9465
log: AVNayKojQnkjuy5tB7cz was created
considering sryu_B2G-Summer12DR53X-00743_v4_v2_150126_223017_1156
log: AVNayZpcQnkjuy5tB7c0 was created
considering sryu_BPH-Spring14miniaod-00004_v4_v2_150126_222422_4212
log: AVNayi1uQnkjuy5tB7c2 was created
Traceback (most recent call last):
  File "Unified/injector.py", line 157, in <module>
    injector(url,options,spec)
  File "Unified/injector.py", line 34, in injector
    familly = session.query(Workflow).filter(Workflow.name.contains(wfi.request['PrepID'])).all()
KeyError: 'PrepID'

**Comment by amaltaro** [comment]
Matteo, I checked this request and it does have the PrepID key. Did your get request schema call worked? Can you print wfi.request to make sure you got any content there?

**Comment by mcremone** [comment]
actually the crash is not referring to sryu_BPH-Spring14miniaod-00004_v4_v2_150126_222422_4212 that was succesfully injected. It is referring to the following one, whose schema is the following:

 {u'InputDataset': u'/MinimumBias/CMSSW_7_3_1_patch1-GR_R_73_V0A_RelVal_run2010A-v1/DQMIO', u'ReqMgr2Only': True, u'Group': u'DATAOPS', u'_rev': u'3-2c3a7db157f8756b4007f3cf09d4bc3d', u'RequestString': u'DQMHarvesting_Jen_reqmgr2', u'Comments': u'DQMHarvest spec with multiRun DQMHarvestUnit', u'Requestor': u'sryu', u'ProcessingString': u'GR_R_73_V0A_TEST_RelVal_jetHT2012c', u'ScramArch': u'slc6_amd64_gcc491', u'SizePerEvent': 1234, u'Memory': 2200, u'DQMUploadUrl': u'https://cmsweb-testbed.cern.ch/dqm/dev', u'RequestType': u'DQMHarvest', u'TimePerEvent': 2, u'OutputDatasets': [], u'RequestDate': [2016, 2, 25, 19, 33, 23], u'AcquisitionEra': u'CMSSW_7_3_1_patch1', u'CouchDBName': u'reqmgr_config_cache', u'CMSSWVersion': u'CMSSW_7_3_1_patch1', u'unmergedLFNBase': u'/store/unmerged', u'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'RequestPriority': 140000, u'mergedLFNBase': u'/store/relval', u'ProcessingVersion': 1, u'RequestTransition': [{u'Status': u'new', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428803}, {u'Status': u'assignment-approved', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'UpdateTime': 1456428805}], u'DQMConfigCacheID': u'e554f238a2ee8bb969248a343f6195d1', u'DQMHarvestUnit': u'multiRun', u'InputDatasets': [u'/MinimumBias/CMSSW_7_3_1_patch1-GR_R_73_V0A_RelVal_run2010A-v1/DQMIO'], u'CouchURL': u'https://cmsweb-testbed.cern.ch/couchdb', u'CouchWorkloadDBName': u'reqmgr_workload_cache', u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu', u'RequestWorkflow': u'https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/sryu_DQMHarvesting_Jen_reqmgr2_160225_203323_5549/spec', u'GlobalTag': u'GR_R_73_V0A', u'BlockBlacklist': [], u'RunWhitelist': [138937, 138934, 138924, 138923, 139790, 139789, 139788, 139787, 144086, 144085, 144084, 144083, 144011], u'_attachments': {u'spec': {u'stub': True, u'length': 26662, u'digest': u'md5-GVGZBGaNewXHtSqSObFJuw==', u'revpos': 2, u'content_type': u'application/json'}}, u'DbsUrl': u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', u'SoftwareVersions': [u'CMSSW_7_3_1_patch1'], u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'_id': u'sryu_DQMHarvesting_Jen_reqmgr2_160225_203323_5549', u'RequestStatus': u'assignment-approved', u'Campaign': u'reqmgr2-validation', u'RequestName': u'sryu_DQMHarvesting_Jen_reqmgr2_160225_203323_5549'}

**Comment by amaltaro** [comment]
This DQMHarvest template seems not to have PrepID key, and that's why it fails the assignment.
Can you slightly change the assignment script to first check whether 'PrepID' key is in the request? If not, just move on and assign the workflow.

I shall update all these templates this week or in the next one and, I will consider a PrepID for all of them.

**Comment by mcremone** [comment]
Ok injector looks working now. Go ahead testing the other modules.

**Comment by vlimant** [comment]
DQMHarvest are not meant to be going through injector, so let's not have a bypass for missing prepid field

**Comment by mcremone** [comment]
Sure, but we still need to avoid getting them. The bypass was meant just to go ahead with the test. But I can get workflows through injector in another way.

**Comment by vlimant** [comment]
to perform a descent test for unified, we need the backfill to have the expected characterisitcs, one of which is the prepid, to be set "uniquely" ; we should just clone one wfs of each type from what is currently on-going. that means also reading data from prod dbs, and probably writting there two, if we want to run things through unified end-to-end

**Comment by vlimant** [comment]
can one please add me in testbed in dataops group so that I can clone things

**Comment by vlimant** [comment]
the assignement team is testbed-vocms009, correct ? what happens if we assign to "production" team ?

**Comment by vlimant** [comment]
what is the substitute for https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=wfname

**Comment by vlimant** [comment]
what is the substitute for https://cmsweb.cern.ch/reqmgr/view/splitting/pdmvserv_EXO-RunIIWinter15GS-04525_00190_v0__160309_030202_9347 . I found the way to edit the splitting, but the interface is non-use friendly

**Comment by mcremone** [comment]
Do you mean in testbed? In that case is:

 https://cmsweb-testbed.cern.ch/reqmgr/view/showWorkload?requestName=wfname
<https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=wfname>
otherwise if you meant reqmgr2 it should be

 https://cmsweb.cern.ch/reqmgr2/view/showWorkload?requestName=wfname
<https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=wfname>


2016-03-09 23:44 GMT+01:00 vlimant <notifications@github.com>:

**Comment by vlimant** [comment]
cloning works fine (vlimant_B2G-Summer12-00736_v4_v2_160309_233152_2345 group ppd) 
assignment works fine
rejecting works fine
no big surprises

**Comment by ticoann** [comment]
> what is the substitute for https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=wfname

https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_EXO-RunIISpring15DR74-04305_00566_v0__160310_051458_3111

We added this link in reqmgr2 only because some of the code is parsing that web page to extract information. However, I would like to make the api and return the json file for the necessary information.

If this page is not for human checking the information, could you specify the information need to be extracted? We will provide the api for that information.

**Comment by ticoann** [comment]
> what is the substitute for https://cmsweb.cern.ch/reqmgr/view/splitting/pdmvserv_EXO-RunIIWinter15GS-04525_00190_v0__160309_030202_9347 . I found the way to edit the splitting, but the interface is non-use friendly

Is this for the human interaction, (updating the record for the web page?) In that case we will update the interface. Do you prefer the current reqmgr interface? Any better suggestions.

If this is used for extracting information and updating using script. 
Here is get call and you can use put call for updating using the same url
https://cmsweb-testbed.cern.ch/reqmgr2/data/splitting/pdmvserv_task_B2G-RunIIWinter15wmLHE-00831__v1_T_160308_114325_5262

**Comment by ticoann** [comment]
> the assignement team is testbed-vocms009, correct ? what happens if we assign to "production" team ?

Request won't pulled to agent since there is no testbed agent with production team.

**Comment by ticoann** [comment]
> can one please add me in testbed in dataops group so that I can clone things

I added you in dataops group.  Are you cloning to reqmgr1? reqmgr2 doesn't have group concept. (It just uses sitedb role for different action)

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/config?name= this is only for eye only. Whatever is parsing it should indeed be removed ; you also mentioned something about something accessing the request.schema. can you please suggest an alternative if that should be done differently.

https://cmsweb-testbed.cern.ch/reqmgr2/data/splitting/ for eyes only indeed. the old interface wasn't so bad.

team for testbed : testbed-vocms009 does not seem to run the workflow for real. is this going to happen, or no running is involved ?

group : when I tried to clone with group=DATAOPS user=vlimant it failed on saying the group was wrong. I changed the clone to group=ppd and it succeeded. so it looks like group does matter

**Comment by ticoann** [comment]
> you also mentioned something about something accessing the request.schema. can you please suggest an alternative if that should be done differently

The information which can get from schema also can get from following api. I think we should change to get information from following but please don't work on it yet. We would discuss what script can be moved to reqmgr2 first. 
```
https://cmsweb.cern.ch/reqmgr2
/data/request?name=
```

> team for testbed : testbed-vocms009 does not seem to run the workflow for real. is this going to happen, or no running is involved ?

Hmm, that is weird vocms009 is connected to global pool it should run jobs, I will check.

> group : when I tried to clone with group=DATAOPS user=vlimant it failed on saying the group was wrong. I changed the clone to group=ppd and it succeeded. so it looks like group does matter

Could you give me the workflow which is cloned? Is it reqmgr2 request? Group only matters when you creates the reqmgr1 workflow.

**Comment by vlimant** [comment]
with regards to group, I was trying to put a schema in reqmgr indeed.
now that I swtich reqmgr=2 in reqMgrClient.submitWorkflow I get a failure.
Would be great to have an exact error message coming back with 406. poking around.

**Comment by ticoann** [comment]
@vlimant, @mcremone, Thanks to Jean-Roch, there were some bugs found and fixed.

submitWorkflow wasn't working with reqmgr2 Flag =True
status change wasn't happening for rejected and assignment-approved.

Please let me know if you find other problems.

I updated the patch.
https://github.com/CMSCompOps/WmAgentScripts/pull/129

**Comment by vlimant** [comment]
while creating an ACDC 
{
  "InitialTaskPath": "/vlimant_B2G-Summer12-00736_v4_v2_160309_233152_2345/MonteCarloFromGEN", 
  "OriginalRequestName": "vlimant_B2G-Summer12-00736_v4_v2_160309_233152_2345", 
  "ACDCServer": "https://cmsweb-testbed.cern.ch/couchdb", 
  "RequestType": "Resubmission", 
  "TimePerEvent": 168.78999999999999, 
  "ACDCDatabase": "acdcserver", 
  "RequestString": "ACDC_B2G-Summer12-00736_v4_v2", 
  "Requestor": "vlimant", 
  "SizePerEvent": 1154, 
  "Memory": 2300, 
  "Group": "ppd", 
  "RequestPriority": 900000, 
  "PrepID": "B2G-Summer12-00736"
}

I got         <p>Invalid spec parameter value: 'CMSSWVersion'</p>
Had to add the CMSSWVersion in the schema of the ACDC ; @amaltaro tells me it should not be needed

**Comment by vlimant** [comment]
@dabercro for reference

**Comment by vlimant** [comment]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=sryu_BPH-Spring14miniaod-00004_v4_v2_150126_222422_4212 does not have ProcessingString, not even a None like the AcquisitionEra

**Comment by vlimant** [comment]
regarding ProcessingString : is it not defaulting to anything anymore

**Comment by vlimant** [comment]
looking into changing splitting issue, the apis are very different and I have the feeling that it is the way it in reqmgr1 because of the easy web interface that allows one to change the splitting algo without having to know the underlying schema. implementing the splitting web-interface in reqmgr2 might very well lead to the same change splitting api ; so I'd rather seat on any change for splitting until this is settled.

**Comment by ticoann** [comment]
Thanks Jean-Roch for testing. Would you mind adding the exact calls and errors you are getting as well.
That will be great help since I can run the test the same way. 

1. How were you creating ACDC, using web interface (wmstats) or is there a script?
2. Do you want to add the default ProcessingString when workflow is created? (To what?) Or it is not updating the ProcessingString.

**Comment by ticoann** [comment]
Hi Jean-Roch. About the splitting as we chat in today, there is not much changes (There is no schema change) The only change is that reqmgr2 allows multiple task settings at one time but reqmgr1 is not.
Due to that nature there are 2 parameters need to be embedded in the reqmgr call 'splitAlog' and 'taskName'. Any I updated the patch https://github.com/CMSCompOps/WmAgentScripts/pull/129 it should work now. If you send reqmgr1 request with the same param it will automatically update reqmgr2 request if request is reqmgr2 request. Let me know if you still have problem.

**Comment by vlimant** [comment]
there has been a schema change in what to pass to /reqmgr2/data/splitting/ (otherwise there would be no conversion needed). Any comments, thoughts on the splitting web-interface ?

is there a typo in the new patch (newParams = {"RequestStatus": "closed-out", "cascade": params["cascade"]} in announce call for example), or is announcing under the same call as closeout ?


about processingstring, do you confirm that there has been a change i.e. ProcessingString is not always present in the workflow cache dictionnary.

can we do the exercise of having that interface reqmgr2 oriented rather than reqmgr1 so that we do the migration right away rather than postponing and making this a rather tedious task later ?

**Comment by ticoann** [comment]
> there has been a schema change in what to pass to /reqmgr2/data/splitting/ (otherwise there would be no conversion needed). Any comments, thoughts on the splitting web-interface ?

Under lining schema didn't changed only reqmgr1 send the splitting change by task.
ie.  in reqmgr1 param
```
"{\"splittingAlgo\": \"LumiBased\", \"halt_job_on_file_boundaries\": true, \"requestName\": \"vlimant_BPH-Spring14miniaod-00004_v4_v2_160314_163422_2591\", \"splittingTask\": \"/vlimant_BPH-Spring14miniaod-00004_v4_v2_160314_163422_2591/StepOneProc\", \"lumis_per_job\": \"1\"}"
```
splittingAlgo,  splittingTask, requestName is not in the schema.
Those are reqmgrq1 specific parameters to pass which request, task and algorithm to to update.

Since reqmgr2 update multiple tasks and algos at one call, we need to specify those in the parameter (actual schema). Actual schema name for those are splitAlgo, taskName   and RequestName which we passed as url.

So here is conversion
https://github.com/CMSCompOps/WmAgentScripts/pull/129/files#diff-3fc98fbeeaadf6df0cfbc50d59551ffeR375

> 
> is there a typo in the new patch (newParams = {"RequestStatus": "closed-out", "cascade": params["cascade"]} in announce call for example), or is announcing under the same call as closeout ?
> 

Thanks I fixed that. Those are not tested. I just found the call by searching the all the Post call, we will need to test those.

> about processingstring, do you confirm that there has been a change i.e. ProcessingString is not always present in the workflow cache dictionnary.

 ProcessingString  is mandatory now but only in assign status. I am not sure whether we need to add default value when request is created.
 
> can we do the exercise of having that interface reqmgr2 oriented rather than reqmgr1 so that we do the migration right away rather than postponing and making this a rather tedious task later ?

As I said there are > 100 of calls /reqmgr/... hard coded for url in the WmAgentScript. Are you proposing to change those now? Or am I misunderstanding something. I think we need to first test all the script is working correctly first to make sure we can switch the default to reqmgr2.

FYI, as you suggested, I updated the patch to check whether it is request manager2 request or not before we make the Post and Put call instead of relying on 404 status return. I still have some trouble updating the Priority alone.  using changePriorityWorkflow()

```
Validation failed: AcquisitionEra is mandatory
```

didn't you have the same error before?

**Comment by amaltaro** [comment]
Seangchan, changing priority is not working in testbed. If you set your VM, then push this patch in to make it work:
https://github.com/dmwm/WMCore/pull/6686

**Comment by ticoann** [comment]
Thanks Alan, I thought somehow that patch got in the production. My bad.

**Comment by vlimant** [comment]
thanks for clarifying the changed api calls for splitting, that confirms what I understood from adjusting in my area. comments on the web interface for splitting ?


"> 100 of calls /reqmgr/" I am talking about the <20 calls within reqMgrClient.py ; the rest can only be read, or should migrate to using reqMgrClient.py. If we can have a patch that assumes calls are made reqmgr2 rather than reqmgr1


"I am not sure whether we need to add default value when request is created" that changes the behavior from reqmgr1, so we just need to define what to expect. AcquisitionEra seems to default to None, right ? let's just have a coherent behavior. I vote for having it always present in the workflow cache, regardless it's value.

**Comment by ticoann** [comment]
> thanks for clarifying the changed api calls for splitting, that confirms what I understood from adjusting in my area. comments on the web interface for splitting ?

I thought we wanted to have the same interface as current reqmgr1. Right? we will update that in next release.

> let's just have a coherent behavior. I vote for having it always present in the workflow cache, regardless it's value.

That will be fine with me. We just make sure it won't allow None or empty string after it gets assigned.

> "> 100 of calls /reqmgr/" I am talking about the <20 calls within reqMgrClient.py ; the rest can only be read, or should migrate to using reqMgrClient.py. If we can have a patch that assumes calls are made reqmgr2 rather than reqmgr1


I think that is more manageable. However the implication of doing that is we are creating the reqmgr2 request by default.  The reason we are calling reqmgr1 request first for PUT and POST is that reqmgr2 call will always successful even against reqmgr1 request. The difference is basically, reqmgr1 call updates both Oracle and CouchDB and reqmgr2 call updates only CouchDB.
With the current setting I don't think the code will fail when we completely drop the reqmgr code especially adding your suggestion of checking the request (whether it is reqmgr2 request). I think we have to wait for converting and clean up until we create the reqmgr2 request by default from McM.  

The initial step what I was thinking was.
1. Modify reqMgrClient.py library in a way other part of script doesn't need to change to make the call to reqmgr2 or reqmgr1 without specifying which call to make from the caller (unified or other script using reqMgrClient.py.) 
There might be the case other scripts need to be changed other than reqMgrClient.py but try to minimize it or move the function to reqMgrClient

2. We run the test and identifying the script we are not using and clean up.

3. After we are satisfied with test, we started to put reqmgr2 request in production (initially just few in different request type then make it default).

4. We clean  up ops script to use reqmgr2 request only.

5. When the all the production active workflow (not archived workflows) are only reqmgr2 workflows (and no more problems related to reqmgr1/reqmg2), we drop the Oracle db and reqmgr code.

**Comment by vlimant** [comment]
we are talking about different things apparently. I'll find a way to make it clear to you

**Comment by vlimant** [comment]
is there any reason to support submitting workflow to reqmgr1 ?

**Comment by ticoann** [comment]
> is there any reason to support submitting workflow to reqmgr1 ?

There is no reason if everything works fine with reqmgr2.  I am just saying we need to first pass all the test including ops/unified/McM tests before we convert reqmgr2 and maybe still run the production with caution. There could be always unforeseen problems.

**Comment by vlimant** [comment]
can we have an unmutable team name for running in the testbed ? like testbed-production or whatever

**Comment by amaltaro** [comment]
the team name is "testbed-vocms009", we shouldn't redeploy this agent in a month or two.

**Comment by vlimant** [comment]
while closing out
cmsweb-testbed.cern.ch /reqmgr2/data/request/vlimant_Run2015D-HcalNZS_0T-boff-15Mar2016_763p2_160330_105926_8025 {'cascade': True, 'RequestStatus': 'closed-out'} {'Content-type': 'application/json', 'Accept': 'application/json'}

I get

<body>
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: Validation failed: AcquisitionEra is mandatory {'attr': 'acquisitionEra', 'default': 'FAKE', 'assign_optional': False, 'optional': True, 'validate': &lt;function acqname at 0x7fa4e80391b8&gt;, 'null': False, 'type': &lt;type 'str'&gt;}</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>

**Comment by amaltaro** [comment]
Jean-Roch, the status change with cascade has been fixed and deployed to testbed today. Give it another try please.

**Comment by vlimant** [comment]
looks fixed since it did toggle to closedout this time.

**Comment by vlimant** [comment]
Noticing this, trying to figure out whether this is expected 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_BPH-Summer12-00220_00255_v0__160531_133446_683

(was injected by mistake) 

noticed   "MCPileup": null,  (which was failing Unified). When not provided, in comparison https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_FSQ-RunIISummer15GS-00057_00340_v0_castor_160523_134337_4337 MCPileup is just absent, not set to null/None.
I am patching Unified just in case, but that might break things somewhere else we have to think about. Maybe better to keep nackward compatibility and not having it present if not set.

**Comment by vlimant** [comment]
please close.
