### ISSUE TITLE
reqmgr2 TaskChain injection

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#6645]
Hi,

injecting TaskChain dict:
http://pastebin.com/ZxpDLu6F

fails with this error:
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: No module named "TaskChain"</p>

seems there is a parameter missing in sanity checks of dictionary received?
tried to inject this to testbed on Monday, February 29, 2016 11:28 AM

**Comment by ticoann** [comment]
Thanks Antanas for the report, could you also point the script you are using and exact command. That will be a big help for debugging. I can try it to test it myself.

**Comment by anorkus** [comment]
the command is this one:
cd /afs/cern.ch/cms/PPD/PdmV/work/McM/dev-submit/ 
source  /afs/cern.ch/cms/cmsset_default.sh
export SCRAM_ARCH=slc6_amd64_gcc493
if [ -r CMSSW_7_6_1/src ] ; then 
 echo release CMSSW_7_6_1 already exists
else
scram p CMSSW CMSSW_7_6_1
fi
cd CMSSW_7_6_1/src
eval `scram runtime -sh`
export X509_USER_PROXY=/afs/cern.ch/user/a/anorkus/.globus/voms_proxy.cert
export PATH=/afs/cern.ch/cms/PPD/PdmV/tools/wmcontrol_testful:${PATH}
wmcontrol.py --url-dict https://cms-pdmv-dev.cern.ch/mcm//public/restapi/chained_requests/get_dict/EXO-RunIIFall15DR7
6-03799 --wmtest --wmtesturl cmsweb-testbed.cern.ch

wmcontrol is a wrapper which makes a POST to reqmgr2. It POSTs the dictionary which i sent with pastebin. Redoing that POST (even with curl) should be enough to reproduce the error ;)

**Comment by ticoann** [comment]
Thank you very much Antanas, I also want to know how McM script is executed as well.
Anyway, you are right it give the 400 error when I just use the post call.

The reason is default config cache url is set to cmsweb and it seems that config cache id (61778aff073bf2507ec558760d0ad333) is only exist in cmsweb-testbed. 

Could you add following in your json document (on the top level would be fine not under Task[])?

"ConfigCacheUrl": "https://cmsweb-testbed.cern.ch/couchdb",

Thank you very much for the testing.

**Comment by anorkus** [comment]
but in the dict i've pasted you can see: 'ConfigCacheURL': 'https://cmsweb-testbed.cern.ch/couchdb',

**Comment by ticoann** [comment]
Ah, I was running the test over the link you in the command example below. So that I will run over initial json.

https://cms-pdmv-dev.cern.ch/mcm//public/restapi/chained_requests/get_dict/EXO-RunIIFall15DR76-03799

**Comment by anorkus** [comment]
well as i told wmcontrol is wrapper, it adds those global variables with url etc. The mcm url contructs dictionary from request specific things and knows nothing about rqmgr{1;2}

**Comment by ticoann** [comment]
Hi Antanas, I was able to create the request with http://pastebin.com/ZxpDLu6F (just using post call)

https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/sryu_McMTaskChain2_wmagent_14_160301_162925_1654

The only thing I had to change is 

ConfigCache**URL** -> ConfigCache**Url **

I think URL make more sense but as far as I remember, it was Url before so we couldn't change to upper case letter.

looking at wmcontrol code. following might caused the problem but I was wondering there was a no problem before?
https://github.com/ticoann/wmcontrol/blob/master/wmcontrol.py#L808

One other thing is I didn't get the same error you reported initially

```
Invalid spec parameter value: No module named "TaskChain"
```

I will try to run exactly the same command to see I can duplicate the error.

```
wmcontrol.py --url-dict https://cms-pdmv-dev.cern.ch/mcm//public/restapi/chained_requests/get_dict/EXO-RunIIFall15DR7
6-03799 --wmtest --wmtesturl cmsweb-testbed.cern.ch
```

Thanks for testing.

**Comment by ticoann** [comment]
Hi Antanas
When I ran
```
wmcontrol.py --url-dict https://cms-pdmv-dev.cern.ch/mcm//public/restapi/chained_requests/get_dict/EXO-RunIIFall15DR76-03799 --wmtest --wmtesturl cmsweb-testbed.cern.ch
```
I am getting following error which is related to Accept header on request. (I was wondering whether I am using the wrong version of wmcontrol.py. should I use master branch or some other branch for the test?

```
It seemslike the name of the GT '76X_mcRun2_asymptotic_v12' has a typo in it, missing the final ::All which will crash your job. If insted you're using CondDBv2, you're fine.
Re-encoding for nested dicts
....
Status: 406 Reason: Not Acceptable
Explanation:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>406 Not Acceptable</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>406 Not Acceptable</h2>
        <p>Not acceptable</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

**Comment by anorkus** [comment]
you shouldn't care about injection through wmcontrol. As you dont even need to clone it. You should use the install in afs which can be sourced.

Anycase the bug was on wmcontrol side:
https://github.com/cms-PdmV/wmcontrol/blob/master/modules/wma.py#L206

seems reqmgr1 needed the params to be encoded. This i didn't change and it worked fine for **non TaskChains** request. Which i would suggest to create another issue to parse the Content-Type of data received (if reqmgr2 receives only json)

When injecting TaskChain dict with "Content-type": "application/x-www-form-urlencoded" header it would fail with strange errors like:
`Invalid spec parameter value: No module named ******`

other notice:
ConfigCacheURL is fine, and seems everything got processed. I will change this to *Url in any case.

**Comment by ticoann** [comment]
Yes, in reqmgr when data is pass as request.body it assumes to be json. We could check the content type and convert correctly. I will create the issue.
