### ISSUE TITLE
Jobs running in resources not available in resource control

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6659]
We had a few cases where jobs ran at T0_CH_CERN - which is not in the resource control - and that causes the workflow to get stuck, since sequential/utilitarian jobs cannot be created when the location is "unknown". 

This leaves files available (wmbs_sub_files_available) and which then leaves a wmbs subscription unfinished as well.

The right behavior here would be:
 a) fail to create jobs for those files 
 b) report createfailed to wmstats
 c) and move on

**Comment by hufnagel** [comment]
Why isn't T0_CH_CERN in the resource control ? We want to run a lot of production there once a few small technical issues are resolved. And how did the jobs ran there if the site isn't in resource control ?

**Comment by amaltaro** [comment]
> We want to run a lot of production there once a few small technical issues are resolved.

Well... that's exactly my point! It needs to be commissioned for central production first and fix/adjust all the small issues.

Brian and Jean-Roch have a go_condor script that changes the DESIRED_Sites of jobs (overflow), that's how.

**Comment by hufnagel** [comment]
It is commissioned, we run the Tier0 there and the Tier0 is a WMAgent under the hood. Otherwise it works, you just need to whitelist it and get cracking :-). The small technical problem is related to mixing multi-core and single-core jobs in long lived pilots.

**Comment by hufnagel** [comment]
And I thought we stopped doing overflow and T0_CH_CERN was enabled as a normal site in Unified ?

**Comment by amaltaro** [comment]
First, it's not just. Second, Tier0 is a WMAgent under the hood but has a different setup, including how it handles resources coming from SSB.
We all agree that we want to use those resources, I'm just saying that some planing is needed and we need to have all pieces in order to make it work.

**Comment by amaltaro** [comment]
Fixed by #6785
