### ISSUE TITLE
closeOutWorkflowCascade does not seem to function

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6664]
Unified is setting closed-out workflows using https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py   closeOutWorkflowCascade but we are left with many ACDC in completed

**Comment by ticoann** [comment]
This is the reqmgr2 requests right? Thanks for the report. I will patch and request for new testbed upgrade.

**Comment by vlimant** [comment]
Hi, no, it is not reqmgr2. worth checking that the reqmgr2 implementation is different than the reqmgr one, to see if it's already broken in the egg

**Comment by ticoann** [comment]
Was this working before? Or always broken?

**Comment by ticoann** [comment]
I just looked at the code but that hasn't changed wrong time.Do you get any error message?

**Comment by amaltaro** [comment]
Cascade closed-out and announced only works if all the children are in the same status (all in completed when moved to closed-out, etc).

**Comment by vlimant** [comment]
that might be the reason then, since I am only finding cases where acdc are all messed up.
could this be changed to jump over the one with a different status ? or is it made as a recurrent call and de-facto cannot be done so ?

**Comment by ticoann** [comment]
It can be done but not so simple. Basically state transition has certain flow to follow and it can't jump to other state than next possible state. (We can jump the state by adding next possible state but I think we need to justify and make sure it is safe to do that).
Is there a case why workflow need to close-out if some of the children workflows (ACDC) is not completed.

**Comment by vlimant** [comment]
to be clear, I am not asking to jump transition.
the use case is
main workflow is completed
acdc1 is completed
acdc2 is rejected
acdc3 is completed

when cascade closeout on main workflow, all completed should go to closed-out. acdc2 stays rejected of course

**Comment by ticoann** [comment]
I see. That is legit case.  I am assuming acdc could be aborted as well. I will try to implement that.

**Comment by vlimant** [comment]
Have you also fix the cascade for announced ?

**Comment by jenimal** [comment]
acdc2 may  have been rejected because it was made in error, to get it "out of the way" so that it doesn't accidently get assigned.  If you make an ACDC by accident you go from new or assignment-approved -> rejected because it was never assigned.

Most of when I end up cleaning up when I clean up orphaned ACDC's are ones that were still running when the parent workflow moves to closed-out -> announced because we will close out announce workflows while the ACDC is still running cleanup/log collect jobs.

**Comment by vlimant** [comment]
> Most of when I end up cleaning up when I clean up orphaned ACDC's are ones that were still > running when the parent workflow moves to closed-out -> announced because we will close > out announce workflows while the ACDC is still running cleanup/log collect jobs.

workflows are not announced while relatives are still in "running*". they do run log/clean jobs, but they are in their proper status when the cascade is supposed to operate.
The most recent orphans are from https://github.com/CMSCompOps/WmAgentScripts/pull/160, the rest is from aborted/rejected in the middle of the chain.
