### ISSUE TITLE
output.keep has the wrong value

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6669]
You can see here

https://cmsweb.cern.ch/reqmgr/view/showWorkload?requestName=bsutar_PR_reference_RelVal_259685_160301_154613_3816

these two lines

bsutar_PR_reference_RelVal_259685_160301_154613_3816.tasks.Task1.steps.cmsRun1.output.keep = True
bsutar_PR_reference_RelVal_259685_160301_154613_3816.request.schema.Task1 = {'InputDataset': '/HLTPhysics/Run2015D-v1/RAW', 'KeepOutput': False, 'GlobalTag': '80X_dataRun2_Prompt_v1', 'SplittingArguments': {'lumis_per_job': 8}, 'SplittingAlgorithm': 'LumiBased', 'ConfigCacheID': '8bda8291183b7e65f9ed09b584d033cb', 'TaskName': 'Task1', 'RunWhitelist': [259685]}

which are inconsistent with each other.

**Comment by amaltaro** [comment]
it seems this spec forces the last step to keep the output (we just implemented the same in StepChain).
There are basically two issues here:
 1. the requestor should NEVER say that he does NOT want to keep the output of the last step, makes no sense at all.
 2. we should fail request injection for this case and make the requestor fix it on his side

**Comment by AndrewLevin** [comment]
No it can be a task chain workflow.

**Comment by amaltaro** [comment]
I know Andrew. I'm just saying that this specific request had a single task and the requestor set KeepOutput to False, which doesn't make sense.
I was saying that for StepChain requests, the last step output will *always* be saved as well.

**Comment by AndrewLevin** [comment]
I see. I think you should just make sure to use what is set in the schema, even if it is stupid.
