### ISSUE TITLE
Create a flag to bypass the input dataset and another for the PU

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6683]
And ... probably TrustSitelists should be kept as it is, just bypassing both input dataset and pileup dataset.

**Comment by vlimant** [comment]
a suggestion, add TrustSiteListsSecondary that defaults to false OR the value of TrustSitelists.
if set to True it ignore the location of the secondary input. otherwise does the current default matching.

**Comment by vlimant** [comment]
premix workflows will therefore be assigned with TrustSitelists = False TrustSiteListsSecondary = True
so that primary location is matched properly and secondary just ignored all together
