### ISSUE TITLE
ReqMgr2: add an empty field to the status drop-down menu

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6684]
Otherwise, when you go to the Gui, it shows you the first option, e.g.:
current in 'running-closed', would appear 'force-complete'
provided in the drop-down menu, which may be misleading.

So the idea would be to add an empty selection (or "--select--" ), as we
have in reqmgr.

**Comment by amaltaro** [comment]
BTW, the idea of having an empty field here is needed for request priority changes, otherwise it cannot be done via Gui.

**Comment by amaltaro** [comment]
@vkuznet if not asking too much, this one would be interesting to have as well :)

**Comment by vkuznet** [comment]
Alan, please provide concrete URL with example (please use testbed URLs). For instance, https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=request-amaltaro_TaskChain_MC_Agent1017_Validation_T2_160609_131119_2199
shows status running-close and drop down also starts with the same value. Do you really need another empty selection? I need to see on concrete example what do you want.

**Comment by amaltaro** [comment]
I just discussed this issue with Valentin and there was another fix put in place in the last month, which is also Ok. The drop-down menu will always have selected the same state that the workflow is, such that any workflow update would not take into account the state (to/from the same state).
Closing the issue.
