### ISSUE TITLE
ReqMgr2: OutputDatasets is not updated during assignment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6702]
in the reqmgr_workload_cache doc. It seems to keep the same OutputDatasets built during request creation and that's it. See example:
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_HIG-RunIISummer15GS-01331_00274_v2__160308_111346_296

**Comment by ticoann** [comment]
Does more output dataset is created after initial creation of request (i.e. When workflow is assigned)? 
Could you point the code if you know on top of your head?

**Comment by amaltaro** [comment]
The output datasets are really defined when we assign a workflow, though we could predict the output dataset names during request creation (in case we have enough information or default cases).

However, this info *must* be updated during assignment, so it should be around this method:
https://github.com/dmwm/WMCore/blob/a95a5667070358ec5fd54804d52a987fc4235a4e/src/python/WMCore/ReqMgr/Service/Request.py#L389
