### ISSUE TITLE
ReqMgr2: ACDC creation via webpage - naming needs to be fixed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6703]
If you don't change the request name during ACDC creation, it offers the same original request name without the timestamp part, such that ACDCing
pdmvserv_EXO-RunIISummer15GS-05060_00274_v2__160308_110629_7026

creates:
amaltaro_pdmvserv_EXO-RunIISummer15GS-05060_00274_v2__160315_102225_1898

so, just prepending the user name and appending the timestamp.

My suggestion is to keep the same behaviour as in reqmgr, so replacing the user name by "ACDC" and removing the timestamp part, such that it creates:
amaltaro_ACDC_EXO-RunIISummer15GS-05060_00274_v2__160315_102225_1898

**Comment by ticoann** [comment]
@amaltaro, Alan, you can assignall reqmgr2 problems to me. :smile:

**Comment by ticoann** [comment]
How did you create ACDC, using Web interface or some script?

**Comment by amaltaro** [comment]
Don't worry, you can have them all :-D
Yes, I created it via web page (wmstats).

**Comment by ticoann** [comment]
Hi Alan, this is due to its requestor's name is different from the prepended string. There is no difference between the reqmgr and reqmgr2.
requestor: pdmvserv@vocms081.cern.ch
string appended: pdmvserv
Anyway, I will update the patch handle this case.
