### ISSUE TITLE
Change reqmgr2 splitting page same as reqmgr interface

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6720]
current template
https://github.com/dmwm/WMCore/blob/master/src/templates/WMCore/WebTools/RequestManager/Splitting.tmpl

Basically
organize parameter by task name. 
With <input>

Allow parameter update by task as well as all the task.

**Comment by vkuznet** [comment]
$ticoann, Seangchan I need more input on that. Do you expect me to visualize
the page from the Javascript code?

- Please provide example of web page how it was done on reqmgr interface.
- Please be specific about splitting page. Do you refer to splitting tab from
  assign page or something else. If former, you explicitly asked to put a full
  JSON in splitting pop-up window. If latter, I have no idea what you're
  talking about.
- Which parameter update are you taking about, need example (again, it would be
  nice if you'll point me to existing web page or make a sketch/photo).

**Comment by ticoann** [comment]
@vkuznet, Hi Valentin,
Here is how it is done in reqmgr1
https://cmsweb-testbed.cern.ch/reqmgr/view/splitting/sryu_TaskChain_Multicore_wmagent_14_160223_225215_4928

splitting page is what we have how the pop up window.  (Yes which I asked to have json page, initially)
Corresponding JSON pop up is here (when click the Splitting tab) as well as in assignment page. (It is using the same code right?)
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=sryu_TaskChain_Multicore_wmagent_14_160223_225215_4928

I don't think the interface should be exactly same. (reqmgr1 allows the algorithm change)

Here is the detail.
1. Organize the splitting parameter by task name. (The older of task name goes to shorter to longer. not by length but by section i.e /a/bcd goes ahead than /a/b/c.) Secondary order can be by task type (Processing/Merge/Harvest/Skim/LogCollect/Cleanup) but I won't bother it to implement that now. Task type can be added later

2. Only need to display split parameter section from json (make algorithm and type not editable.
```
"splitParams": {
      "min_merge_size": 2147483648, 
      "algorithm": "ParentlessMergeBySize", 
      "initial_lfn_counter": 0, 
      "max_merge_size": 4294967296, 
      "max_merge_events": 400000, 
      "max_wait_time": 86400, 
      "trustSitelists": false, 
      "type": "Merge"
    },
```

So  interface is something like this.

```
/sryu_TaskChain_Multicore_wmagent_14_160223_225215_4928/HLTD/HLTDMergeRAWoutput/RECODreHLT/RECODreHLTMergeALCARECOStreamTkAlMinBias

algorithm: ParentlessMergeBySize
type: Merge
max_merge_size:  4294967296 (make this editable text box)
....

submit button
```

Each task contains submit button which only sends the given task changes. and there is overall submit button which sends all the task changes.

If you have time, we can chat briefly with skype. I am connected now. Thanks

**Comment by amaltaro** [comment]
Just a correction, algorithm must be editable for at lest Production and Processing task types (EventBased, LumiBased, etc).

**Comment by ticoann** [comment]
Hi Alan, so initial algorithm set for workflow is arbitrary. (Just takes the default)? Or there is case need to change algorithm on the fly after request is created?

**Comment by amaltaro** [comment]
McM provides only the TimePerEvent parameter, in this case the splitting algo is defined inside ReqMgr depending on whether a) there is input dataset (EventAwareLumiBased) or b) there is NO input dataset (EventBased).

However, one could change the default EventAwareLumiBased algo (when there is input) to a simple LumiBased algo, after the workflow is created and *before* it gets assigned.

**Comment by ticoann** [comment]
Thanks Alan, 
Valentin, in that case, I will create list of algorithms available for each type including split parameters as well as REST api for that. (i.e. reqmgr2/data/splitting/algorithms)
and return following format. Is that OK? or do you want to some different format?

```
[ {"taskType": "Processing",
   "splitParamlist": [{
      "runBlacklist": [], 
      "algorithm": "EventAwareLumiBased", 
      "runWhitelist": [], 
      "max_events_per_lumi": 20000, 
      "deterministicPileup": false, 
      "events_per_job": 822, 
      "trustSitelists": false, 
      "lheInputFiles": false, 
      },
      ...],
     {"taskType": "Production",
   "splitParamlist": [{
      "runBlacklist": [], 
      "algorithm": "FileBased", 
      "runWhitelist": [], 
      "max_events_per_lumi": 20000, 
      "deterministicPileup": false, 
      "events_per_job": 822, 
      "trustSitelists": false, 
      "lheInputFiles": false, 
      },
      ...]
```

**Comment by vkuznet** [comment]
@ticoann , @amaltaro , please have a look at this prototype (bare html, no styles), do you want to have editable json, or should I convert it into input fields?
![screen shot 2016-03-21 at mar 21 2 22 01 pm](https://cloud.githubusercontent.com/assets/125138/13929490/c375652e-ef70-11e5-9145-eca9d548c5ba.png)

**Comment by ticoann** [comment]
Thanks, Valentin,
I think it will be batter to switch to input filed. And For algorithm it could be drop down menu (I will add api I mentioned above, the default should what initially returned not the one from new api (and replace the section from the new api.) There is duplicate info, so we need only display values of split params key.

**Comment by vkuznet** [comment]
Yes, I'll need this API and proposed format is fine. Since I don't want to put
any attribute specific logic in javascript code I suggest that API should
return only parameters which will appear on web UI.

**Comment by vkuznet** [comment]
@ticoann @amaltaro , how about this:
![screen shot 2016-03-22 at mar 22 10 32 46 am](https://cloud.githubusercontent.com/assets/125138/13955070/b5bacd44-f019-11e5-9de1-b8d90fa30b36.png)

**Comment by vkuznet** [comment]
I'll wrap it into spitting page in pop-up window. So far I only concentrate on functionality and outlook. Please provide comment before I'll go to next step.

**Comment by amaltaro** [comment]
Valentin, based on your template:
 1. algorithm should be a drop down menu showing only the allowed algos
 2. lumis__per_job is ok and the input type must be integer
 3. ALL the other parameters have to be taken out. They don't belong to the splitting page.

As a general comment - not only for this page - I think there is way too much spacing between each of these fields. In the main page, where we have ~ 30 parameters, you have to scroll during your whole life to hit the bottom of the page :)

**Comment by ticoann** [comment]
Hi Valentin, I create the sending list of algorithms by task type. I think we can use that to filter out which params are displayed, It seems there are only few params need to be edited. If you have time, we can chat a little after WMArchive meeting. Thanks,
Here is the api.

https://reqmgr2-dev.cern.ch/reqmgr2/data/splitalgo

**Comment by vkuznet** [comment]
@ticoann @amaltaro please review https://www.dropbox.com/s/8h655wv6xs3dwp1/ReqMgrSplitInterface.mov?dl=0

Let me know if UI looks as you want it to be (style adjustments, shown vars can be adjusted later). For this screencast I used splitalgo output and put data directly into HTML file I developed. Later I'll replace data with call to the API.

**Comment by ticoann** [comment]
Thanks Valentin, GUI looks good. There is only couple of things I want to change.

1. algorithm can be removed from input text since it is in the drop down menu.
2. if input box value is false or true. we can make either drop down or radio button

**Comment by vkuznet** [comment]
Your appetite only grow, I knew it :)

**Comment by ticoann** [comment]
You shouldn't have asked feed back. :smile: 

Here is the format for this. I added taskName.  As we discussed all the filtering and overwriting default value happens in serverside.

https://reqmgr2-dev.cern.ch/reqmgr2/data/splitting/web_form/sryu_TaskChain_Task_Multicore_Sryu_reqmgr2_160318_050229_8964

**Comment by vkuznet** [comment]
@ticoann @amaltaro please review one more time
https://www.dropbox.com/s/8h655wv6xs3dwp1/ReqMgrSplitInterface.mov?dl=0
This is based on all your comments and I'll only need to test it with final reqmgr2 apis. Seangchan, which api I should use /reqmgr2/data/splitting or /reqmgr2/data/splitting/web_form. Also please remind me which API I'll need to use when I'll send data. Which POST parameters I'll need to send, I'll capture specific algorithm params, should I make a dict of them along with task name?

**Comment by vkuznet** [comment]
Here is PR https://github.com/dmwm/WMCore/pull/6734
It is untested since I need to deploy it first to reqmgr2 to test all APIs. Seangchan, please let me know if I can use reqmgr2-dev. I can apply this PR manually and test/tweak code, but I need some data in reqmgr2 to play with, please arrange.

**Comment by vkuznet** [comment]
Seangchan,
this API is not allowed
> https://reqmgr2-dev.cern.ch/reqmgr2/data/splitalgo
I get this
        <h2>405 Method Not Allowed</h2>
        <p>API not supported for this request method</p>

**Comment by ticoann** [comment]
Hi Valentin,

The new api is following. (As we discussed, you don't have to call 2 apis). You can call below to get the masked result.

https://reqmgr2-dev.cern.ch/reqmgr2/data/splitting/web_form/sryu_TaskChain_Task_Multicore_Sryu_reqmgr2_160318_050229_8964

Yes, you can update reqmgr2-dev. If you want I can update your patch there too.

Thanks,
