### ISSUE TITLE
ceToCMSName

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#6722]
Hello,

I have a SiteName I would like to map to a CE, but I have noticed `_siteresources()` doesn't have the CE types anymore. So `getAllCENames` is an empty list and [cmsNametoCE](https://github.com/dmwm/WMCore/blob/8d324f4973bdf2a1b5eab2337b7938502107112c/src/python/WMCore/Services/SiteDB/SiteDB.py#L140) just throws an exception. 
However, [ceToCMSName](https://github.com/dmwm/WMCore/blob/8d324f4973bdf2a1b5eab2337b7938502107112c/src/python/WMCore/Services/SiteDB/SiteDB.py#L216-L229) seems to do the same as [seToCMSName](https://github.com/dmwm/WMCore/blob/8d324f4973bdf2a1b5eab2337b7938502107112c/src/python/WMCore/Services/SiteDB/SiteDB.py#L231-L244) as they both just compare the fqdn without verifying the type (so, it's just compared against the SE FQDN since there are not CE FQDN types anymore). Is this a bug, am I miss-interpreting something or are SE/CE FQDNs the same on most CMS Sites? Any alternative to map a SiteName to a CE from WMCore without using `condor_status`?

**Comment by hufnagel** [comment]
As far as I remember we wanted to remove dealing with CE from all WMCore code and also want to remove CE from SiteDB. The only system that should care about CE is glideInWMS. As such it'll be

a) hard to find anyone that knows or cares about this code

b) dangerous to rely on this code to do anything in the long run (it could be removed)

**Comment by ericvaandering** [comment]
This isn't going to help you, but basically we no longer use CE names except in GlideinWMS when it's deciding which queues to send pilots too. The code you point to is unused in WMAgent and presumably elsewhere. 

Ah, I see Dirk has said much the same thing.

**Comment by khurtado** [comment]
Ah! Thank you. I won't use that code then...
