### ISSUE TITLE
Tag chirp updates from CMSSW

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6739]
The `CondorStatusService` can add a tag to all of its update attributes (i.e., `ChirpCMSSWMaxEvents` becomes `ChirpCMSSWDIGIMaxEvents`).  This can be used to allow HTCondor to record statistics for each step in a stepchain separately.  This is enabled by setting the `tag` to an appropriate untracked string (see https://github.com/cms-sw/cmssw/blob/7e2655ffaf3e2a7fa9ab823e788d5059c4e2353d/FWCore/Services/plugins/CondorStatusUpdater.cc#L422).

Without this, only the last step in a stepchain is recorded.

**Comment by bbockelm** [comment]
@hufnagel - you might be interested in this one.

**Comment by hufnagel** [comment]
I don't know what you want us to do here. Modify the following line ? How ?

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L615

**Comment by bbockelm** [comment]
Yeah - `cms.Service("CondorStatusService")` should become something like `cms.Service("CondorStatusService", tag=cms.untracked.string("DIGI"))`

**Comment by hufnagel** [comment]
Something like ? Where is that string supposed to come from ? I doubt we have access to DIGI, that's way too high level for this code. I can see jobType easily being available, I can also see maybe stepName (like cmsRun1, cmsRun2 etc).

**Comment by hufnagel** [comment]
production_cmsRun1, merge_cmsRun1, processing_cmsRun1, processing_cmsRun2

That's what we can easily do here. Not sure about DIGI.

**Comment by bbockelm** [comment]
Yeah - I think we could work with the step name (`cmsRun1`).

To the best of my telling, WMAgent doesn't have human-readable step names like "DIGI".  I usually have to label those per-campaign in the monitoring.

**Comment by hufnagel** [comment]
Step name should be easy to do. If all you want to be able to do is to have separate info for the different steps that will do it.

**Comment by hufnagel** [comment]
----- Begin Fatal Exception 24-Mar-2016 14:58:42 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of service of type CondorStatusService
Exception Message:
Illegal parameter found in configuration.  The parameter is named:
 'tag'
You could be trying to use a parameter name that is not
allowed for this plugin or it could be misspelled.
----- End Fatal Exception -------------------------------------------------

Which CMSSW version actually support the tag parameter ?

**Comment by bbockelm** [comment]
@hufnagel - this requires at least 7_6_0 -- but I can't see any release where `CondorStatusService` existed without this parameter.  What version were you using?

**Comment by hufnagel** [comment]
I think I used CMSSW_7_5_8. CondorStatusService exists in CMSSW_7_5_X where X>=1 and even CMSSW_7_4_X where X >= 7. I can change things so CondorStatusService requires 76X or higher.

**Comment by bbockelm** [comment]
Ah - yes, you'll need 7_6_X for this.  Doing a little test locally it seems to work.

**Comment by bbockelm** [comment]
Here's what I'm doing locally:
```
process.CondorStatusService = cms.Service("CondorStatusService", tag=cms.untracked.string("DIGI"), debug=cms.untracked.bool(True))
```
From the debug output, the `condor_chirp` lines are:
```
condor_chirp set_job_attr_delayed ChirpCMSSWDIGILastUpdate 1459804663
```
It might be best to do tags like `_FOO_` just to visually break things up...
