### ISSUE TITLE
jobtype reported to dashboard Processing and processing

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6743]
it looks like both Processing and processing jobtype are reported to the dashboard.

**Comment by vlimant** [comment]
where is the capitalization coming from and can we get rid of it ?

**Comment by amaltaro** [comment]
I had a look at it a couple of weeks ago and I could not spot any place changing it.
I'll come back to it once higher priority issues are sorted out.

**Comment by vlimant** [comment]
maybe the capitalization is in dashboard itself

**Comment by ticoann** [comment]
@vlimant, is this still the problem, if not could you close the issue?

**Comment by vlimant** [comment]
to my knowledge there is still a difference in capitalization. but who cares
