### ISSUE TITLE
Remove any reference to httplib2 when pycurl is used

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#6744]
Spawn from https://github.com/dmwm/WMCore/pull/6742

This is a requirement for having a crabclient that cleanly works in the CMSSW environment without creating conflicts.

Basically Service.py and Requests.py imports `httplib2`, but the package is not needed if you configure the packages to work with pycurl.

**Comment by mmascher** [comment]
As discussed in the PR mentioned above, in the context of the "pycurl defaultization" (https://github.com/dmwm/WMCore/pull/6360/files) we should try to get rid of the unrecommended `import httplib2` inside a function, or even get rid of httplib2 completely

**Comment by ticoann** [comment]
duplicate  issue
