### ISSUE TITLE
Merging can skip files that cannot be opened

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6782]
Chris and I just found this:
https://github.com/dmwm/WMCore/blob/9d7117909f7c3e536fc32806db7419632fc03f7f/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L585

Anyone know why this is here? I can do some bit blame and try to figure it out.

**Comment by amaltaro** [comment]
I thought it was related to the robust merge, but looking at the CMSSW class, I'm not sure anymore...

**Comment by ericvaandering** [comment]
Jean-Roc mentioned that term too, but I'm not familiar with it.

**Comment by amaltaro** [comment]
Robust merge is the ability to drop a "sick" file from the merge job. 
For instance, the job runs and failed to read/open file number 4. Then this job goes back to the agent in cooloff, the agent retries this job BUT that "sick" file will NOT be in the list of files to be merged. This behaviour can happen maxRetry times in a job lifetime.

**Comment by amaltaro** [comment]
Overseeded by #4851
