### ISSUE TITLE
reqmgr2 api returning info for a wrong workflow

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6783]
Andrew Levin reported this issue today, he queries 
cmsweb.cern.ch/reqmgr2/data/request?name=WORKFLOW_A

and the response is
{u'WORKFLOW_B': {u'Group': u...

it happens once a couple of hours (maybe once for each 2k queries)?

**Comment by ticoann** [comment]
I could reproduce the error yesterday with request list Andrew provide. However I am not sure what cause the problem. As Andrew observed, it is likely server side problem. I am not sure whether it is our application level (reqmgr2) or upper level (apache).
The only thing I found so far is calls made at almost the same time. which give the long result.
So far I only have one case found. I am trying to run more test and see there is any pattern.

heli_RVCMSSW_7_5_0TTbar_13_150715_150516_775 : [u'pdmvserv_HIN-pp502Fall15-00070_00016_v0__160401_121608_682’]

```
vocms0165/reqmgr2/reqmgr2-20160406.log:[06/Apr/2016:17:41:40] vocms0165.cern.ch 136.145.214.11 "GET /reqmgr2/data/request?name=heli_RVCMSSW_7_5_0TTbar_13_150715_150516_775 HTTP/1.1" 200 OK [data: 4025 in 3387 out 331486 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sryu/CN=676041/CN=Seang Chan Ryu" "" ] [ref: "" "” ]

vocms0165/reqmgr2/reqmgr2-20160406.log:[06/Apr/2016:17:41:41] vocms0165.cern.ch 131.225.205.32 "GET /reqmgr2/data/request?name=pdmvserv_HIN-pp502Fall15-00070_00016_v0__160401_121608_682 HTTP/1.1" 200 OK [data: 3102 in 3871 out 427156 us ] [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=Services/CN=wmagent/cmsgwms-submit1.fnal.gov" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
```

**Comment by amaltaro** [comment]
@AndrewLevin this issue should have been fixed with Seangchan's fix #https://github.com/dmwm/WMCore/pull/7002

Please reopen if you see new cases like this.
