### ISSUE TITLE
Change abort workflow to complete ALL subscriptions

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6789]
and kill ALL jobs. It's only a source of confusion having an aborted workflows (or in this specific case, aborted-archived) still with jobs in the system, see:
https://cms-logbook.cern.ch/elog/Workflow+processing/23773

IMO, we let the sites clean after themselves.

**Comment by ticoann** [comment]
#6572 will address this issue. So you want to even kill the clean up jobs?

**Comment by amaltaro** [comment]
Yes, sites have their own unmerged area cleanup anyways.

**Comment by ticoann** [comment]
@amaltaro, This is fixed with the periodic cleaning and complete transition change. Can we close this?

**Comment by amaltaro** [comment]
Sure, let's do it! Closing
