### ISSUE TITLE
Aborted workflows acquiring WQE and creating/submitting jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6791]
Second time I see the same behavior within a week or two. An aborted workflow still creating jobs, acquiring work from GQ, etc.
- Workflow: amaltaro_MonteCarlo_Ext_TEST_T0_Defragmentation_ALAN_160407_101739_1810
- was aborted at Fri Apr  8 12:34:06 CEST 2016
- acquiriging work in vocms0309 at
  2016-04-08 13:02:53,135:140489453991680:INFO:WorkQueue:Adding WMBS subscription for amaltaro_MonteCarlo_Ext_TEST_T0_Defragmentation_ALAN_160407_101739_1810
- all production jobs
- WQE canceled in GQ
- WQE canceled in LQ

Really don't know what happened, I just know it cannot!

**Comment by vlimant** [comment]
Giving water to this mill https://cmsweb.cern.ch/reqmgr/view/details/vlimant_BPH-RunIISummer15GS-Backfill-00030_00212_v0__160906_122234_1944 has been creating jobs even after everything had been killed and reached nothing pending ; though those are logcollect and cleanup.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr/view/details/vlimant_HIG-RunIISpring16DR80-Backfill-01830_00657_v0__160909_134934_1661 is gracefully submitting jobs over and over @ticoann

**Comment by amaltaro** [comment]
I had to kill this workflow from inside the agents (vocms03{03,04,10,11}) using Seangchan's magical script.

I forgot to keep note, but I think GQE were marked as CancelRequested, though I could not find any signs of this request being canceled in GQ...

We need to review how work gets aborted, since from time to time we have a workflow falling through the cracks. I don't know exactly how it works, but a possible solution would be:
1. GQ marks all GQE as CancelRequested and the request is moved to "aborted"
2. Agent updates the LQE (by replication) and then, kill all the jobs, mark all its LQE (and workqueue db) as Canceled AND update WMBS db.
3. Once ALL the agents have marked their LQE as Canceled (meaning ALL GQE are Canceled as well - by replication), then GQ would switch it to "aborted-complete".
4. Finally, this work can be archived (which is another discussion).

@ticoann what do you think?

**Comment by vlimant** [comment]
http://cms-gwmsmon.cern.ch/prodview/pdmvserv_BPH-Summer12-00228_00270_v0__160926_121558_7218 trying to take it down running 7k jobs after it was aborted and down to ~zero.

**Comment by amaltaro** [comment]
This one was taken care and updated on the wrong GH issue (already closed) #7214

**Comment by vlimant** [comment]
@ticoann please fix this. http://cms-gwmsmon.cern.ch/prodview/pdmvserv_HIG-RunIISummer15wmLHEGS-00691_00241_v0__161118_162113_5732 is aborted and running 20k jobs !

**Comment by amaltaro** [comment]
@vlimant this workflow was taken care on all the agents. It had quite a lot of jobs (15k-20k) in several agents. It should be completely gone of the system now (besides cleanup jobs).

I was discussing this same issue with Seangchan a few days ago and he may have a "half fix" for it :)

**Comment by vlimant** [comment]
guys http://cms-gwmsmon.cern.ch/prodview/pdmvserv_HIG-RunIISummer15wmLHEGS-00690_00241_v0__161118_162058_7421 from vocms0130.cern.ch and vocms0309.cern.ch

**Comment by amaltaro** [comment]
sorry about that. wf taken care in both nodes.

**Comment by vlimant** [comment]
adding this one https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_BPH-RunIISummer15GS-00111__v1_T_161207_120035_5549 in 308, 310 and 130

**Comment by amaltaro** [comment]
All those 3 agents had jobs in the queue for this workflow
pdmvserv_task_BPH-RunIISummer15GS-00111__v1_T_161207_120035_5549
I've just force-killed it on those agents.

**Comment by vlimant** [comment]
thx

**Comment by vlimant** [comment]
https://cms-gwmsmon.cern.ch/prodview/pdmvserv_BPH-RunIIWinter15GS-00045_00195_v0__161129_001501_4393 is a zombie

what's the ETA on a fix for this ?

**Comment by amaltaro** [comment]
And 
pdmvserv_BPH-RunIIWinter15GS-00045_00195_v0__161129_001501_4393
was also force-killed in all the agents (most of the agents still had jobs and wqes, this time).

A fix for it may be deployed this month in the newest release, still to be finalized and tested though.

**Comment by amaltaro** [comment]
Fixed by #7442
