### ISSUE TITLE
ReqMgr2: fix Unmergedlfnbase in Gui

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6794]
It's a drop down menu showing only '/store/data' and '/store/temp'.
I think we could make it static at '/store/unmerged'

**Comment by amaltaro** [comment]
@vkuznet if you have time, can you try to fix it for the next cycle please?
The behavior/content should be the same as we have for reqmgr right now.
Or just make as I suggested, static to '/store/unmerged'

**Comment by vkuznet** [comment]
Please take this PR with the fix: https://github.com/dmwm/WMCore/pull/6920
