### ISSUE TITLE
ReqMgr2: list of Cmssw releases incomplete (Gui)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6795]
That list is outdated, for example the list in the drop down menu ends with 7_3_1, we are already in 8_0 (maybe 8_1 ?).

**Comment by amaltaro** [comment]
the same for the ScramArch lists (Cmssw architectures)

**Comment by ericvaandering** [comment]
Could be related. Newer releases are on newer arch.

**Comment by ticoann** [comment]
I am not sure this is still problem, the list is updated from the following link.
https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML (it that is updated we will get the updated result) @amaltaro, Alan can we close this one?

**Comment by amaltaro** [comment]
I thought it was Ok, but having a look at:
https://cmsweb-testbed.cern.ch/reqmgr2/create

it seems both the scram arch and the cmssw lists are incomplete. e.g. `slc6_amd64_gcc493` is not in testbed right now.
I'll try to have a look at it tomorrow.

**Comment by ticoann** [comment]
https://cmsweb.cern.ch/reqmgr2/create. it seems it is OK in production as well as my vm.
I think it is cache update problem. patch is created #7239
