### ISSUE TITLE
Solve issue in CRAB for untar (Mainly solve env issues)

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#6804]
I am just creating an issue here to remember what we did to solve for now for older cmssw releases in CRAB3. So either the same untar goes to main WMCore branch, or CRAB3 solves python problems... I think better to solve python problems ;)

@belforte @mmascher

Some discussions are here:
https://github.com/dmwm/WMCore/pull/6799
https://github.com/dmwm/WMCore/pull/6779
https://github.com/dmwm/WMCore/pull/6798

**Comment by amaltaro** [comment]
@juztas , didn't you make a PR fixing this issue?

**Comment by juztas** [comment]
See your own comment, also Erics comment...
https://github.com/dmwm/WMCore/pull/6779#issuecomment-208316484
CRAB3 failed validation, because new tag which is created does not have this patch (https://github.com/dmwm/WMCore/pull/6897) included. This is needed for CRAB so it has to be in master branch and for sure we do not need only CRAB3 branch in WMCore. 
Also see here: https://github.com/dmwm/CRABServer/issues/5229#issuecomment-221919980 and here https://github.com/dmwm/CRABServer/issues/5229#issuecomment-222081897

**Comment by amaltaro** [comment]
Thanks, the ball is on my court. I'll validate #6897 and merge it to master if everything is Ok
