### ISSUE TITLE
GQ acquiring data for blocks not complete at destination

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6806]
@vlimant just reported an issue where the input dataset is being transferred from tape to a few sites (block distribution), and the GQ acquired those blocks and found their location where the block is not completed yet.

For this workflow: pdmvserv_task_BTV-RunIISpring16DR80-00007__v1_T_160403_120412_8028
that was assigned to Purdue, CERN and FNAL.

One GQE example is
```
{"_id":"28783e809e4847c8206a6393cdc0a4c4","_rev":"6-3224d07a3ac67f5e4f4cd17d34e1cc91","updatetime":1460717844.1380000114,"WMCore.WorkQueue.DataStructs.WorkQueueElement.WorkQueueElement":{"ParentQueueId":"pdmvserv_task_BTV-RunIISpring16DR80-00007__v1_T_160403_120412_8028","NumberOfEvents":1368,"StartPolicy":"Block","CreationTime":1460715950.7999999523,"NumOfFilesAdded":0,"Priority":95000,"ParentData":{},"PileupData":{"/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIISummer15GS-MCRUN2_71_V1-v2/GEN-SIM":["T1_IT_CNAF","T1_ES_PIC","T2_AT_Vienna","T2_GR_Ioannina","T2_UA_KIPT","T2_PK_NCP","T2_US_Purdue","T2_FI_HIP","T2_UK_SGrid_RALPP","T2_FR_GRIF_LLR","T2_BE_UCL","T2_ES_IFCA","T2_DE_RWTH","T2_PT_NCG_Lisbon","T2_KR_KNU","T2_DE_DESY","T1_UK_RAL","T1_US_FNAL","T2_IT_Legnaro","T2_US_Caltech","T2_UK_London_Brunel","T2_RU_JINR","T2_IT_Pisa","T2_US_Vanderbilt","T2_EE_Estonia","T1_DE_KIT","T2_IT_Rome","T2_RU_IHEP","T1_FR_CCIN2P3","T2_US_Florida","T2_TH_CUNSTDA","T2_FR_GRIF_IRFU","T0_CH_CERN","T2_UK_London_IC","T2_IT_Bari","T2_US_Nebraska","T2_CH_CSCS","T2_FR_CCIN2P3","T2_US_UCSD","T2_CH_CERN_HLT","T2_ES_CIEMAT","T1_RU_JINR","T2_US_Wisconsin","T2_HU_Budapest","T2_CN_Beijing","T2_US_MIT","T2_BE_IIHE","T2_RU_INR","T2_CH_CERN","T2_PL_Swierk","T2_FR_IPHC","T2_BR_SPRACE"]},"RejectedInputs":[],"ParentFlag":false,"TaskName":"BTV-RunIISpring16DR80-00007_0","Status":"Acquired","Inputs":{"/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/RunIISummer15GS-MCRUN2_71_V1-v1/GEN-SIM#f51ff370-7a3e-11e5-96da-a0369f23d05a":["T2_CH_CERN_HLT","T2_CH_CERN","T1_US_FNAL"]},"NumberOfLumis":8,"Jobs":2,"ParentQueueUrl":"https://cmsweb.cern.ch/couchdb/workqueue","ChildQueueUrl":"http://cmsgwms-submit1.fnal.gov:5984","PercentSuccess":0,"PercentComplete":0,"WMBSUrl":"http://cmsgwms-submit1.fnal.gov:9999/wmbsservice/wmbs","OpenForNewData":false,"EndPolicy":{"policyName":"SingleShot"},"FilesProcessed":0,"SiteWhitelist":["T2_US_Purdue","T1_US_FNAL","T2_CH_CERN"],"ACDC":{},"NumberOfFiles":1,"TeamName":"production","NoPileupUpdate":false,"RequestName":"pdmvserv_task_BTV-RunIISpring16DR80-00007__v1_T_160403_120412_8028","SubscriptionId":null,"NoInputUpdate":false,"TimestampFoundNewData":0,"ProcessedInputs":[],"SiteBlacklist":[],"Mask":null,"Dbs":"https://cmsweb.cern.ch/dbs/prod/global/DBSReader/","EventsWritten":0},"timestamp":1460715950.7999999523,"thunker_encoded_json":true,"type":"WMCore.WorkQueue.DataStructs.WorkQueueElement.WorkQueueElement"}
```

notice the location of the block: ["T2_CH_CERN_HLT","T2_CH_CERN","T1_US_FNAL"] 

and querying phedex blockreplicas for this gives me the following output atm:
<phedex request_version="2.3.21-comp3" request_timestamp="1460723739.15932" request_call="blockreplicas" instance="prod" request_date="2016-04-15 12:35:39 UTC" request_url="http://cmsweb.cern.ch:7001/phedex/datasvc/xml/prod/blockreplicas">
<block bytes="1630776753" files="1" name="/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/RunIISummer15GS-MCRUN2_71_V1-v1/GEN-SIM#f51ff370-7a3e-11e5-96da-a0369f23d05a" is_open="n" id="5630193">
<replica bytes="0" files="0" node="T2_CH_CERN" time_create="1460043883" time_update="1460045071.67333" group="DataOps" se="srm-eoscms.cern.ch" custodial="n" node_id="1561" subscribed="y" complete="n"/>
<replica bytes="0" files="0" node="T1_US_FNAL_Disk" time_create="1460043791" time_update="1460045071.67333" group="DataOps" se="cmssrmdisk.fnal.gov" custodial="n" node_id="1781" subscribed="y" complete="n"/>
<replica bytes="1630776753" files="1" node="T0_CH_CERN_Export" time_create="1446131528" time_update="1460045071.67333" group="" se="" custodial="n" node_id="1" subscribed="n" complete="y"/>
<replica bytes="1630776753" files="1" node="T0_CH_CERN_MSS" time_create="1446122607" time_update="1460045071.67333" group="DataOps" se="srm-cms.cern.ch" custodial="y" node_id="2" subscribed="y" complete="y"/>
</block>
</phedex>
```

So this block is only available at T0_MSS, for real.

This is the code dealing with the data location:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/DataLocationMapper.py#L109

**Comment by amaltaro** [comment]
BTW, 'incompleteBlocks' is False, meaning 'complete' args is set to 'y'. I just checked the phedex api and it returns the correct result, so must be something within our wmcore code. 
I'm investigating this issue.

**Comment by ticoann** [comment]
@amaltaro, Alan, I will take care of this. (I kind of know where the problem is) Don't work Friday night. :smile:

**Comment by amaltaro** [comment]
I'm not gonna fight for this issue :-) Ok, let me know if I can help you
