### ISSUE TITLE
inclued future package when python library is send to  in the workernode.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6817]
In related to the change in here. https://github.com/dmwm/WMCore/pull/6420

The problem occurs since the code including (builtin, past, etc)  is running in worker node. If the code is run agent there is no problem, since agent rpm has dependency on future package. But it doesn't seem that package is ported to worker node. Anyway, I will create a new issue for that.

**Comment by ticoann** [comment]
@amaltaro, @juztas, Alan, Justas, do you know where we can control this.
Doesn't CRAB have problem with this? It is preferable to add the future package in the library we send WN. Otherwise we have to remove this import (builtins, etc) at least temporary.

**Comment by juztas** [comment]
hey, let me tackle this down tomorrow as high prio ;)

**Comment by amaltaro** [comment]
Well, seems to have been fixed. So closing
