### ISSUE TITLE
minwalltimesecs logic

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6827]
Hi,

The logic here

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobCreator/JobCreatorPoller.py#L102-L115

makes no sense to me. Why do you not do this:

j['estimatedJobTime'] = max(min(j['estimatedJobTime'], constraints['MaxWallTimeSecs']),constraints['MinWallTimeSecs'])

?

Andrew

**Comment by ticoann** [comment]
Hi Andrew, 
What would be the correct logic?
1. estimatedJobTime < MinWallTimeSecs -> change to MinWallTimeSecs
2. estimatedJobTime > MaxWallTimeSecs -> change to MaxWallTimeSecs
3. MinWallTimeSecs < estimatedJobTime < MaxWallTimeSecs  -> keep estimatedJobTime

?

**Comment by AndrewLevin** [comment]
yes

**Comment by amaltaro** [comment]
Which is exactly what is coded...

**Comment by amaltaro** [comment]
```
if not j['estimatedJobTime'] or j['estimatedJobTime'] < constraints['MinWallTimeSecs']:
                j['estimatedJobTime'] = constraints['MinWallTimeSecs']
j['estimatedJobTime'] = min(j['estimatedJobTime'], constraints['MaxWallTimeSecs'])
```

**Comment by AndrewLevin** [comment]
no, it is overwritten later:

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobCreator/JobCreatorPoller.py#L107-L115

**Comment by amaltaro** [comment]
That's part of the logic, I suggest you to grab a pencil and make a few tests to see that it works as expected :)
