### ISSUE TITLE
Differentiate error code for time out.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6830]
There are 3 cases WMAgent kills the job when timeout occurs. current code is 71304
Andrew, pointed that it would  be helpful for debugging to have different error code for each cases (Error, Running, Pending)
Is there any rules for setting the error code.
I could set 
71304 - Running
71305 - Pending
71306 - Error

@amaltaro, @ericvaandering, any comments?

**Comment by amaltaro** [comment]
We have the error message saying what was the latest known condor status, though I agree that having only a different error code may be handy.
I think we only have to "respect" the error code ranges/types, that's all.

**Comment by ticoann** [comment]
Thanks Alan, I will create the patch then.
