### ISSUE TITLE
condor_chirp/crab3 and add stageout reports

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#6855]
Hey,
From crab jobs I see interesting numbers for stageout related failures (local, fallback, direct), but would be better to keep the track of each stageout separate and see the percentage also for prod and crab together,separate.  which now we can't filter easily and it is not possible.

So I have few questions:
Can we move https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executor.py#L164-L184 to better place, something like src/python/WMCore/Services/Condor/Condor.py ? Maybe in the future, crab would use the same python function to do chirp for other things or prod.
With one of previous pull requests Stageout module already prepares a stageoutPolicyReport with all tried stageouts and can we do condor_chirp, something like this?

```
for itemNum in range(len(stageoutPolicyReport)):
    stageOutRow = stageoutPolicyReport[itemNum]
    for reportType in ['PNN', 'Command', 'ExitCode']:
        if reportType in stageOutRow and stageOutRow[reportType] is not None:
            key = Chirp_Stageout_%s_%s_%s" % (stageoutType, itemNum, reportType)
            self.setCondorChirpAttrDelayed(key, stageOutRow[reportType])
```

@bbockelm is there any penalty for a job on schedd or anything else of doing more condor_chirp commands?

**Comment by bbockelm** [comment]
There is effectively no penalty here - there is a limit of 50 attributes that a job can send.  The updates are batched together into a single interaction with the schedd.

**Comment by juztas** [comment]
Just for my knowledge, what happens after 50? which ones will be skipped? Just randomly I have chosen one job, and it reported already 37. So if report also local, fallback info it will be +6. For analysis  +9, but analysis reports less on CMSSW. So it will be near the max limit. 

[1]
```
$ condor_history 169794.5 -l | grep Chirp
ChirpCMSSWReadVOps = 0
ChirpCMSSWMaxEvents = -1
Chirp_WMCore_cmsRun_ExitCode = 0
ChirpCMSSW_cmsRun2_ReadSegments = 1
ChirpCMSSWLumis = 0
ChirpCMSSW_cmsRun2_ReadBytes = 1442319268
ChirpCMSSW_cmsRun1_WriteTimeMsecs = 3097
ChirpCMSSWReadOps = 0
ChirpCMSSW_cmsRun1_EventRate = 0.0499193
ChirpCMSSWFiles = 0
ChirpCMSSW_cmsRun1_Done = true
ChirpCMSSW_cmsRun1_ReadTimeMsecs = 7611868
ChirpCMSSW_cmsRun1_Lumis = 9
ChirpCMSSW_cmsRun1_Events = 1091
ChirpCMSSWWriteTimeMsecs = 0
ChirpCMSSW_cmsRun2_Events = 1091
ChirpCMSSW_cmsRun2_ReadVOps = 0
ChirpCMSSW_cmsRun1_Files = 1
ChirpCMSSW_cmsRun2_ReadTimeMsecs = 893
ChirpCMSSW_cmsRun1_ReadBytes = 64134233643
Chirp_WMCore_cmsRun1_ExitCode = 0
ChirpCMSSW_cmsRun1_ReadOps = 810374
ChirpCMSSW_cmsRun2_ReadOps = 38091
ChirpCMSSW_cmsRun2_Lumis = 9
ChirpCMSSWRuns = 0
ChirpCMSSW_cmsRun1_MaxLumis = 4
ChirpCMSSW_cmsRun2_Files = 1
ChirpCMSSWReadTimeMsecs = 0
ChirpCMSSW_cmsRun2_Runs = 1
ChirpCMSSW_cmsRun1_MaxFiles = 1
ChirpCMSSW_cmsRun1_WriteBytes = 2036886779
ChirpCMSSWMaxLumis = -1
ChirpCMSSW_cmsRun1_LastUpdate = 1462896708
ChirpCMSSWMaxFiles = -1
ChirpCMSSW_cmsRun2_WriteBytes = 1003465926
ChirpCMSSWEvents = 0
ChirpCMSSWElapsed = 0
```

**Comment by bbockelm** [comment]
Looking at the HTCondor code, there is a hardcoded limit of 50 attributes.  After 50, new attributes will be ignored and a message logged to the StarterLog.  I guess we should bug the HTCondor team to make this configurable and to raise the default.

From your example, I don't think WMCore will advertise the attributes prefixed `ChirpCMSSW_cmsRun*_` for analysis.

Could we put this info in the stageout plugin architecture?

**Comment by bbockelm** [comment]
Another trick would be to encode the information to use less attributes and perhaps utilize a sub-classad?  Note that some versions of HTCondor have had issues with using `condor_chirp` with values > =1024 characters; don't know if this has been solved.

**Comment by juztas** [comment]
not only chirp, i think. we had 1024 chars* issue in CRAB with long list of lumis... I could add this into stageout plugin arch... any disagreement ?

**Comment by bbockelm** [comment]
Nope, sounds good!

**Comment by hufnagel** [comment]
@juztas , why do you want to move the setCondorChirpAttrDelayed method from where it is now ? This can only be called from within a running job and all the runtime code inherits from the class where the method is implemented now. Doesn't make much sense to have this code in Services, it's runtime code.

Do CRAB3 jobs use a different runtime code model ?

**Comment by bbockelm** [comment]
@hufnagel - any chance you could take a look at this?  I think it'd be useful to have systematic statistics about stageout performance at NERSC.

**Comment by amaltaro** [comment]
Given that this issue lacks activity for more than 3 years, shall we close it?
