### ISSUE TITLE
prevent small lumisection in EventBased job splitting

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6857]
provided eventsperjob and eventsperlumi, the current schema of splitting allows for the last lumi of a job to have a number of events smaller than eventsperlumi. This has an impact on multi-thread processing down the line of such production.

the proposal is to change so that the actual eventsperjob is made an exact multiple of eventsperlumi so that no smaller lumisection  is created

@bendavid

**Comment by bendavid** [comment]
Even better would be to stop using maxEvents.input to control job splitting entirely, and just switch to using maxLuminosityBlocks.input directly.

**Comment by amaltaro** [comment]
Since it's not a simple change, why the last lumi section cannot be smaller? How does it affect multi-threading processing? In the worst case, it would be a single job...

**Comment by ericvaandering** [comment]
I guess this is for MC production? 

It affects multi-threaded processing because the framework has to synchronize everything on lumi boundaries. So short lumis are inefficient to process.

**Comment by vlimant** [comment]
yes, exactly. sorry for not giving more info.

**Comment by amaltaro** [comment]
ok, then the issue is not about having lumi sections in different sizes, but instead having lumi sections too small? I'm just wondering how important it is, since it will be a single job per workflow

**Comment by bendavid** [comment]
No, it's not a single job per workflow.

Imagine the following:

GEN-SIM workflow with 200 events per lumi, 1007 events per job, and 100,000 events in total.

There will be 99 jobs with 1007 events each which produce 5 lumi sections of 200 events, plus 1 lumi section of 7 events.

Then the last job will have I guess 307 events, producing one lumi section of 200 events, and one lumi section of 107 events.

So then there will be 496 lumi sections of 200 events (good), 99 lumi sections of 7 events (bad!) and 1 lumi section of 107 events.  (not good, but not catastrophic on its own)

**Comment by amaltaro** [comment]
Thanks, Josh. Nothing as a good example :)

**Comment by vlimant** [comment]
is this something I should implement on unified side, or that should go in wmcore ?
@ticoann @amaltaro due to the expected deterioration of cpu efficiency because of this, this is now high priority.

**Comment by amaltaro** [comment]
> the proposal is to change so that the actual eventsperjob is made an exact multiple of eventsperlumi so that no smaller lumisection is created

Should we a) round down, b) round up or c) round to the closest multiple? Needless to say, such jobs will no longer target 8h length, but some more (or less).

However, IF `EventsPerJob` is provided during request creation, then I assume we don't do anything with that, right?

**Comment by ticoann** [comment]
What splitting algo we are talking about here? EventBased, right? Doesn't EventAwareLumiBased do this already?

**Comment by amaltaro** [comment]
It's only EventBased, the others *LumiBased are in the end splitted by lumis. I can take this issue Seangchan, especially because the fix is simple ;)

**Comment by vlimant** [comment]
"not simple" in 2016, "simple" in 2018 ;-)

**Comment by amaltaro** [comment]
Code is much easier now than it was in the beginning of 2016 :-)
BTW, I'll seek this approach: c) round to the closest multiple

**Comment by vlimant** [comment]
I think we need some elasticity in both events_per_job and events_per_lumi, i.e adjust either one of them depending on how much you have to change them.
see the attached python

**Comment by vlimant** [comment]
[l.py.txt](https://github.com/dmwm/WMCore/files/1812224/l.py.txt)

**Comment by amaltaro** [comment]
Patch was created based on the initial discussion. Is there any strong reason to have this elasticity? Your snippet mentions number of jobs, this part of the code has no clue of jobs (it's all one job).

**Comment by vlimant** [comment]
typo indeed, the njobs is nlumisinthejob.
the elasticity makes it that we do not have to worry about whether EpL and EpJ are multiple of each other or equal, and rely on the submission side to behave. conceptually, this should be the production system that makes sure no tiny lumis are created, not the requester that does not care the last bit about lumisize in MC.
the patch is good, we'll just have to make sure to handshake with ppd and push the responsibility of the lumisection size onto them ; @bbockelm OK?
if the responsibility falls onto Ops, then we need a simple api that reads .../do_splitting_right?request=<wf name>

**Comment by vlimant** [comment]
I am overly confused about how things are going. We discussed this, and decided that we would keep the EpJ as a suggestion, and enforce no small lumi here, since there is no use case for ever wanting to have a "small lumi at the end".
