### ISSUE TITLE
JobSubmitter cache update

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6864]
minimize the cache size but also avoid lower priority job gets first submitted.
Some discussion found #6856 

From Dirk's comment

If you set some sort of threshold and don't add jobs into the cache, you by design don't consider certain jobs for running. In such a system lower priority jobs in the cache can drown out higher priority jobs that are stuck in the db and not in the cache.

If you just add high priority jobs from the db to the cache, you will consider them for running preferentially, but at the expense of possible lower priority jobs that might have been able to run at sites where the higher priority jobs can't run.

But we are discussing here what to do in an overload situation. You pick your poison and I'd rather have looked at the high priority jobs and decided they can't run because of site restrictions than not to have looked at all and just ran FIFO.

Anyways, if you think it's too much for this PR please open another issue. But any kind of hard cutoff without taking into account priorities will inevitably result in some sort of complaint from Ops at some point: Why are all these low priority jobs being submitted if we have high priority work in the system ?

**Comment by amaltaro** [comment]
Fixed by #6856
