### ISSUE TITLE
Exit Code 134 $HOME/.root.mimes

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6894]
the frequent error code 134 seems to be related to  $HOME/.root.mimes

does wmcore make reference to this file, how does this get accessed by the job ?

https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3654.html

this is causing major failures and inefficiencies in production.

**Comment by hufnagel** [comment]
From the error message this is completely within CMSSW, has nothing to do with WMCore.

**Comment by vlimant** [comment]
is it CMSSW that sets the environment variables : like $HOME ? I don't think so

**Comment by hufnagel** [comment]
$HOME is set by the system and is the home directory of the current user

**Comment by vlimant** [comment]
so in case of wmagent, what is the user on the worker node ?

**Comment by hufnagel** [comment]
For production it should be whatever account the pilot runs under or whatever account the pilot executes the payload under (they can differ). This can be site dependent, for Tier0 jobs we have

HOME=/mnt/glidein_pilot/glide_EJeKvh/execute/dir_28739

so this is a dynamically created directory which won't have any init files in $HOME (never had).

Anyways, this whole discussion is a bit pointless IMO, this has nothing to do with WMCore. It's a framework bug or more correctly a bug in the ROOT version in CMSSW.

**Comment by hufnagel** [comment]
Or maybe (speculating here) a problem with configuration in that it enables loading this library from ROOT.

Without knowing more about what triggers the errors (specific/new CMSSW versions, specific type of workflows ?) it's all speculation.

**Comment by vlimant** [comment]
to make it less pointless. can the snipet of error returned from executing cmsRun be actually returned by the job, all the way to wmstats ?
i.e
    CMSSWStepFailure (Exit Code: 134)

         Adding last ten lines of CMSSW stdout:
        WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
        WARNING: There already exists /home/glidein_pilot/dir_820906/job/WMTaskSpace/cmsRun1/CMSSW_8_0_5_patch1 area for SCRAM_ARCH slc6_amd64_gcc530.
        /home/glidein_pilot/dir_820906/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh: line 62: 821618 Aborted                 $EXECUTABLE -j $JOB_REPORT $CONFIGURATION 2>&1
        CmsRunFailure
        Message: Error running cmsRun
        {'arguments': ['/bin/bash', '/home/glidein_pilot/dir_820906/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc530', 'scramv1', 'CMSSW', 'CMSSW_8_0_5_patch1', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
        Return code: 134

        	ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
        	MethodName : __init__
        	ClassInstance : None
        	FileName : /home/glidein_pilot/dir_820906/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
        	ClassName : None
        	LineNumber : 18
        	ErrorNr : 134

        Traceback: 

does not say anything, while
cmsRun  -j FrameworkJobReport.xml PSet.py
terminate called after throwing an instance of 'edm::Exception'
   what():  An exception of category 'FatalRootError' occurred.
    Additional Info:
       [a] Fatal Root Error: @SUB=TSystem::ExpandFileName
input: $HOME/.root.mimes, output: $HOME/.root.mimes

Complete
process id is 716062 status is 134

is more instructive
