### ISSUE TITLE
workloadcache has RequestNumEvents=0

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6902]
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_SUS-RunIISpring16DR80-00043__v1_T_160403_123457_1776

"RequestNumEvents":0

and 

"Task1":{"InputDataset":"/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer15GS-MCRUN2_71_V1-v2/GEN-SIM","PrepID":"SUS-RunIISpring16DR80-00043","ProcessingString":"PUSpring16_80X_mcRun2_asymptotic_2016_v3","ScramArch":"slc6_amd64_gcc530","SizePerEvent":3500,"ConfigCacheID":"d237254b3baa7b83f2d514956f5119ea","Memory":1980,"MCPileup":"/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIISummer15GS-MCRUN2_71_V1-v2/GEN-SIM","TimePerEvent":35,"AcquisitionEra":"RunIISpring16DR80","PrimaryDataset":"QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8","CMSSWVersion":"CMSSW_8_0_3_patch1","ProcessingVersion":1,"SplittingAlgo":"EventAwareLumiBased","TaskName":"SUS-RunIISpring16DR80-00043_0","KeepOutput":false,"GlobalTag":"80X_mcRun2_asymptotic_2016_v3","FilterEfficiency":1,"Multicore":1,"RequestNumEvents":18874815

maybe the first one should not be present if not initially specified in the request (not present in injected schema)

**Comment by amaltaro** [comment]
This has been recently fixed. It must be > 0 for production workflows or not present for processing.
