### ISSUE TITLE
Upload new values to Multicore, Memory and Performance params to workload doc

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6906]
This actually needs to be discussed whether we can completely overwrite the original values or whether we should somehow provide an API containing the exact parameters provided during request creation.

**Comment by vlimant** [comment]
Can this have more meat so that one understand what is the impact on operation of workflows ? Is this a monitoring feature or an actual feature that impacts wf behavior ?

**Comment by amaltaro** [comment]
This is mostly to investigate issues and check what were the original parameters and etc. The document I'm talking about is:
https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/amaltaro_TaskChain_RelVal_Multicore_HG1608_Validation_160809_232142_450

where the Memory/Multicore parameters could get overwritten and then by looking at this document you don't know anymore what was the original value.

**Comment by amaltaro** [comment]
This is actually overwritten for ReqMgr2 requests. So my question remains, is it Ok if we overwrite the original values with those values provided by Unified during assignment? My main concern is with future clones of the original request, since it would clone the values provided during the request assignment instead of the original one submitted by McM.

Please assume the structure of this document cannot change (so, no special key for `assign_param` and whatnot), so no third option in your answer :)

PS.: The same applies to AcqEra/ProcStr/ProcVer that I asked you in another issue...

**Comment by amaltaro** [comment]
Fixed in the last month by a couple of PRs
