### ISSUE TITLE
Report more information about the failure for exit code 134

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6919]
related to #6894 #6904 , we would need more information be reported back to wmstats. the python stack trace of wmcore is not really informative, while bits of logs on the worker node is

**Comment by vlimant** [comment]
Digging through error reports, it looks like 

https://github.com/dmwm/WMCore/blob/0.9.95b_plus_patches/src/python/WMCore/WMSpec/Steps/Diagnostics/CMSSW.py#L118

is wrong and should have outLog in it to fulfil its destiny ! @amaltaro @ticoann could this be added along

**Comment by vlimant** [comment]
add https://github.com/dmwm/WMCore/blob/7cda7bc5c76158790bf8e3912c5ec4332da52541/src/python/WMCore/WMSpec/Steps/Diagnostics/CMSSW.py#L238

**Comment by ticoann** [comment]
Surprised that bug wasn't found for many years. Thank Jean-Roch.
