### ISSUE TITLE
Cleanup StringIO/cStringIO

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6935]
There is no need for try/except around this anymore, I think. cStringIO is in all python versions we've used for years. Python3 makes cStringIO the default and it's called io.StringIO. 

We should just use `import cStringIO as StringIO` everywhere in preparation for the transition

**Comment by ericvaandering** [comment]
Turns out we had an issue for this already.

**Comment by amaltaro** [comment]
This should have been closed with #8733
