### ISSUE TITLE
Chirp exception message

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6939]
We've had sites who want to explore the ClassAd archive based on a full text search of exception messages.

As part of the WMCore wrapper that currently parses & chirps back the FJR, we should also include the exception message for jobs that fail.

However, with the exception messages, we are likely to hit the 1024 character limit on values passed via Chirp.  Hence, we should extract the exception message, compress it and base64-encode it.  If the encoded version is still greater than 1024 character, then we should recursively repeat the procedure until the encoded text is below the 1024 character threshold.  ElasticSearch can decode things appropriately on the other side.

**Comment by bbockelm** [comment]
(Filed this ticket after discussing this with @juztas and @hufnagel informally a few times.)

**Comment by ticoann** [comment]
Hi Kenyi,
Here is the code setting the condor_chirp parameters in WMCore.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L239

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executor.py#L165

**Comment by khurtado** [comment]
```
we should extract the exception message, compress it and base64-encode it. If the encoded version is still greater than 1024 character, then we should recursively repeat the procedure until the encoded text is below the 1024 character threshold
```
Are we talking about zlib/lzma compression here? Can multiple compressions really reduce the number of characters in the encoded version? Wouldn't that be equivalent or larger (due to overhead) to compressing once at the maximum level compression, or am I missing something in the logic?

**Comment by bbockelm** [comment]
Hi Kenyi,

I didn’t mean compressing twice - but rather only compress if the simple base64 encoding is still too large.

Because yes, you’re not going to benefit from multiple compressions!

Brian

**Comment by khurtado** [comment]
@bbockelm Okay, I got confused by the recursive part. So it's only checking for length, compress and encode... if the length is still too large, should the exception message just be trimmed?

**Comment by bbockelm** [comment]
Yeah - however, if it was trimmed, please at least note it was trimmed!
