### ISSUE TITLE
AcquisitionEra/ProcessingString for TaskChain Merge ACDC

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6941]
it is mandatory right now to drop AcquisitionEra and ProcessingString in assigning merge acdc of taskchain wf, while it has to be passed for all other acdc.
We should either
    * not have to pass any of those for ACDC : which would make sense because recovery should recover on the original dataset
    * not make an exception for taskchain-merge-ACDC

bonus : make also the ProcessingVersion a useless parameter in assignment so that it cannot be set to anything different than the original wf version.

**Comment by amaltaro** [comment]
@vlimant just a heads up, a fix for this issue is supposed to get into testbed today. Still need to be validated though, but in summary it means you should assign these ACDCs as any other (meaning, providing all the mandatory arguments/AcqEra/etc).

**Comment by amaltaro** [comment]
This is already in production and workflow assignment is uniform again (all those parameters must be provided during assignment - AcqEra/ProcStr/ProcVer/etc)
