### ISSUE TITLE
ReqMgr2: status update via  web UI is broken

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6956]
It returns a status Ok, however no changes were made to the request itself. The reason seems to be coming from the fact that you always _update_ the request priority as well, this is what is sent downstream from web interactions:
`{"RequestStatus":"aborted","RequestPriority":"250000"}`

which then does not end in an statusUpdate in Request.py, e.g.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L508

I'm still checking on how to fix it.

**Comment by amaltaro** [comment]
We actually should split it in two parts:
 1) via web UI, if the priority is not changed, then it should be removed from the parameters passed to ReqMgr2
 2) ReqMgr2 validation has to properly handle and update those 2 parameters when both are changed.

@vkuznet can you take care of 1) please? It would be very similar to the change you made for RequestStatus, when it does not change, then remove it from the parameters passed upstream.

I'm taking care of 2)

**Comment by vkuznet** [comment]
Alan, could you please point me to VM with concrete workflow. In order to see which part of code to change I need to see which web UI part you're talking about.

**Comment by amaltaro** [comment]
Sure, you can try moving this workflow
https://alan-cloud2.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_Data_HG1607_Validation_160627_235214_1091

to aborted status (don't change anything else). It will give you a thumbs up (Ok) but nothing really changed.

**Comment by vkuznet** [comment]
Alan, ok I modified a code but I need to test it. To do so we usually used reqmgr2-dev Seangchan's node and he put there some requests that I can play with via web interface. Can you do that for me? or tell me how to create few requests. I may several iteration since I'll debug web interface and see how requests will flow from web UI to the server. The code on reqmgr2-dev is modified already and ready for a test. If you can't do it on reqmgr2-dev may be you can give me access to your VM where I change the code and we can test it.

**Comment by amaltaro** [comment]
Giving it a second thought, case 2) does not seem to be needed. I cannot think of any real use case.
That means we only need the UI fix that you are working on (though I made a few improvements in another PR).

Seangchan's VM seems to be broken, I get a couch unauthorized when injecting a new request.
Anyways, I gave you access to alan-cloud2.cern.ch, just try not to break it (badly), since I have some tests on going there. You can pick a couple of workflows that are running and play with them. Otherwise let me know and I can inject more.

**Comment by vkuznet** [comment]
Alan, please take this PR: https://github.com/dmwm/WMCore/pull/6959
Per discussion in this issue it fixed the problem with RequestPriority parameter (as any other as well) if they're not changed they're removed from passed JSON. The code on your VM contains this fix, I changed the code manually, so please go ahead and test it with few workflows.
