### ISSUE TITLE
ReqMgr2: browsing through Home menu and status does not load any requests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6957]
If you browse through this web interface
https://alan-cloud2.cern.ch/reqmgr2/home

and then select a status, nothing is listed. E.g.:
https://alan-cloud2.cern.ch/reqmgr2/requests?status=acquired

It should fetch all requests under that status.

**Comment by amaltaro** [comment]
of course you can still find these workflows coming from WMStats, for instance
https://alan-cloud2.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_Data_HG1607_Validation_160627_235214_1091

**Comment by amaltaro** [comment]
@vkuznet perhaps you can help us with this UI problem as well? :-) I don't really know this code and I've never played with Cheetah, so it should be much easier for you.

I did a few tests in my VM and I noticed we fetch the correct data up to this point:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L464

here you can see a couple of logging lines from my VM
```
AMR kwds {'status': u'assignment-approved'}
AMR docs  [{'RequestDate': '2016-06-27 10:12:45 GMT', 'Requestor': u'pdmvserv', 'Group': u'ppd', 'RequestName': u'pdmvserv_task_B2G-RunIISpring16reHLT80-00970__v1_T_160627_131245_7164', 'RequestStatus': u
'assignment-approved'}]
```

maybe you can use this `docs` content to do further tests and check where the problem is coming from?

**Comment by vkuznet** [comment]
Well,
I think the problem is that the docs you get are NOT in JSON format they're
python dicts, but not JSON's, i.e. single quotes, the u'', etc. But in web UI
we need JSON not python dicts, so whoever send these docs to web UI does not
do json.dumps(doc) and just send doc. This is the problem.

The strange part though since production code does not seems to have this
problem, at least I/Seangchan never saw this. So it seems something were
introduced in between.

V.

**Comment by amaltaro** [comment]
I'll verify the json comment tomorrow morning then.

About your second comment, yes, you're right. Current testbed does not present this issue:
https://cmsweb-testbed.cern.ch/reqmgr2/requests?status=completed

**Comment by amaltaro** [comment]
Ahaa! You're right, it works if we convert docs to json format. It may be that something sniped in in the last json cleanup campaign. I'm checking how we can make a general fix now.

**Comment by vkuznet** [comment]
ok, now we know who screwed things :) yes, it seems like the jsonwrapper clean-up and migration to use plain json had side effect. It would be nice to find a place where exactly conversion to json format fails now.

**Comment by amaltaro** [comment]
So, investigating it a bit further is only becoming even weird for me...
In the end, all those reqmgr2 pages use this templatepage() method:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/tools.py#L90

The funny part is the following, when a go to the "Home" menu, it retrieves all the possible states and their transitions and pass it as a `requests` keyword argument to templatepage(), as a python *list*, e.g.:
```
[{'base': '/reqmgr2'}, {'requests': ['new', 'assignment-approved', 'assigned', 'acquired', 'running', 'running-open', 'running-closed', 'failed', 'force-complete', 'completed', 'closed-out', 'announced', 'aborted', 'aborted-completed', 'rejected'], 'rdict': {'aborted-archived': [], 'failed': ['rejected', 'assigned'], 'acquired': ['running-open', 'completed', 'acquired', 'aborted'], 'closed-out': ['announced', 'rejected'], 'completed': ['completed', 'closed-out', 'rejected'], 'rejected': ['rejected-archived'], 'rejected-archived': [], 'assigned': ['acquired', 'aborted', 'failed'], 'runni ... etc etc etc
```
which *works* just fine.

However!! if I make that list of states into a json format, then it breaks the template page (each char becomes a status).

Last but not least, the funniest part is that it works the other way around for "give me requests in status XXX", meaning, if `requests` keyword value are in json format, it populates the table, otherwise the page gets empty.

Valentin, could it be that templates are handling the same data in different ways?

Maybe we could investigate it together today, in case you have some free time.

**Comment by vkuznet** [comment]
Alan,
I see, it is slightly different problem. The python dict may contain either
string or unicode, e.g.

{'foo':1} vs {u'foo':1}

So I was wrong about json.dumps, since it convert python dict into string
representation. So what we need is to pass dicts with string keys/values rather
the unicode keys/values.

Are you in your office? I don't see you in gtalk.
Valentin.

**Comment by amaltaro** [comment]
Valentin, I updated the PR to cast unicode into string ascii. Have a look at #6960 please.

**Comment by vkuznet** [comment]
ok, my understanding that this works now and you can close the ticket.
