### ISSUE TITLE
ReqMgr2: splitting window does not close

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6966]
It seems to work fine for workflows in 'assignment-approved', however trying that out for running or completed workflows, e.g.:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=request-amaltaro_DQMHarvesting_LumiMask_HG1607_ReqMgr2_Validation_160706_101902_8279

does not. Once you click in the top `Splitting` button, it opens a window that cannot be closed, neither via escape nor via `Close` button.

**Comment by amaltaro** [comment]
@vkuznet you may want to have a look at this one :-)

**Comment by vkuznet** [comment]
Alan, could you please apply this PR: https://github.com/dmwm/WMCore/pull/6968 to fix the problem. Seems like simple bug in JavaScript call.

**Comment by vkuznet** [comment]
@amaltaro , does the provided solution work? if so, can you close the ticket.

**Comment by amaltaro** [comment]
Yes, it does! The ticket will be closed once the PR is merged, don't worry.
