### ISSUE TITLE
Set Dataset BlockName in the initial job attributes (where relevant)

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6972]
apologies if that is a duplicate, I could not find an original one.
it would be very beneficial for job re-routing to have the CMS_DesiredBlock set to the dataset block that is being read in primary input.

**Comment by ticoann** [comment]
are you talking about in JDL?

**Comment by vlimant** [comment]
I meant that it should be added to the classads passed to condor, best would be the exact list of files, or a hashed version of it so that we can tell what jobs runs on what, from the classads

**Comment by vlimant** [comment]
Could this be considered even with low prority ? adding the classad would greatly help further production tuning.

**Comment by vlimant** [comment]
In the context of very long data processing requests, and being able to move work around more efficiently, overflow and the like, that feature would be greatly appreciated. for now we can survive.

**Comment by vlimant** [comment]
@bbockelm we were discussing about this earlier today

**Comment by bbockelm** [comment]
Hi,

I believe this one is mis-prioritized: it's probably much higher priority in terms of processing tails.

The tails of the current re-RECO are going to overlap with the DIGI-RECO because we can't quickly rebalance data.

Brian

**Comment by hufnagel** [comment]
List of files is not doable in general, we have jobs with too many input files. Would it be enough to have the first input file ? We don't schedule across site boundaries (all of our job splitting algorithms are location aware and location specific), so the location of the first file will be the location for all other files.

Implementing this should be trivial.  In comparison putting the block into the classad is way more work AFAIK since I don't think we pass that information along at the moment.

**Comment by hufnagel** [comment]
One complication: If you process across block boundaries (one job reads files from multiple blocks), which I don't think we do (but should confirm), then you don't have a guarantee that all locations that have that first input file will have all the input files.

**Comment by vlimant** [comment]
I'd rather have the block name in the classad, not file list.

**Comment by bbockelm** [comment]
Indeed: file list is not particularly useful, blocks are.

I'm fairly sure that jobs don't cross block boundaries (if they did, I'd still rather take just the first block name).

**Comment by hufnagel** [comment]
Ok, the problem I see with this is that when the workqueue feeds blocks into the system, we loose the mapping of files to blocks. WMBS deals with files and filesets internally, not blocks.

@amaltaro @ticoann , do we keep the block to file mapping for input data somewhere ? I don't think so and worse, I wouldn't even know where we could keep store it if we wanted to...

**Comment by bbockelm** [comment]
What about mapping back from (single file) -> block?

**Comment by hufnagel** [comment]
You could always ask DAS or DBS :-), but that approach has obvious scaling problems...

**Comment by hufnagel** [comment]
For this lookup to be fast and scalable, you need the mapping inside the agent database.

**Comment by hufnagel** [comment]
Of the top of my hat, the least invasive solution I can think off is a table with fileset_id and block_name that is FK tied to the fileset and optionally created when the workqueue creates input filesets for top level tasks. The job splitting algorithm would then get that information via the fileset assoc and embed it into the job baggage. We can then extract this from the job baggage in the condor plugins and add the block name as a classad.

This would mean that only jobs for top level tasks would have that information but IMO this is fine. Only top level task jobs are relocatable in WMAgent anyways, all other lower level jobs have only one location they can run at.

**Comment by vlimant** [comment]
I think that internally, you have the wmbs jobid, and there must be a way to link this to the wqe, that knows what block it is processing.

**Comment by ericvaandering** [comment]
WQ blocks are aligned on DBS Blocks, so I don't think its possible to have jobs running files from different blocks.

**Comment by hufnagel** [comment]
Took a peek through the code again. Block name is not kept, at least not in the agent database. Two options giving the current code:

1) extract block name from couch (not sure what records we keep in couch)
2) extract block name from input fileset name (as it is part of the naming convention)

I really don't like 1 as it would introduce a dependency between the JobSubmitter plugin code and couch. Option 2 is a dirty hack, but as we are only talking about including an extra string in the jdl, might be acceptable.

Opinions @amaltaro @ticoann ?

**Comment by hufnagel** [comment]
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WMBSHelper.py#L225

**Comment by amaltaro** [comment]
Taking it from wmbs_fileset sounds better IMO, though it will probably not work for ACDCs and of course it only works for top level task. In this case we better keep a cache around for an hour or two as well.

**Comment by amaltaro** [comment]
I meant, 2) sounds better if those are the only possibilities to make it working. I didn't investigate the code myself to see what is and what is not possible.

**Comment by hufnagel** [comment]
We can always change the schema and add the missing information, but I didn't investigate that. AFAICT given the current code and information we store, these are the two options.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set Dataset BlockName in the initial job attributes (where relevant)](https://trello.com/c/O9lP2DJB/5-set-dataset-blockname-in-the-initial-job-attributes-where-relevant)
