### ISSUE TITLE
add t0_request_local compact cronjob in wmagent_couchapp_init for T0 deployment

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6982]

**Comment by hufnagel** [comment]
Is this the right place ? Are we setting up t0_request_local in the wmagent_couchapp_init. Don't remember if we have a T0 specific couchapp init or rely on the wmagent one.

**Comment by ticoann** [comment]
It seemed T0 is using wmagent-couchapp-init. 
https://github.com/dmwm/deployment/blob/master/tier0/manage#L363
But if not, could you point me the code?

**Comment by hufnagel** [comment]
No, you are right, we are using the wmagent-couchapp-init verbatim. Reason was that when we started Tier0 had no special couch db.

**Comment by hufnagel** [comment]
I guess the cronjob should be added wherever t0_request_local is initialized. If that is wmagent-couchapp-init, then that is the right place.
