### ISSUE TITLE
Stop using EOSCMS SRM for LogCollect stageout

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6989]
I've been talking with the EOSCMS team about working to eliminate the SRM endpoint.  (They'd like to get rid of SRM and OSG would like to retire support for bestman2).

In the agent, we currently hardcode the stageout to EOSCMS SRM.  We should remove this.  The two obvious options are:
1.  Switch to `gfal2` and `gsiftp://` stageout.
2.  Switch to `xrdcp` stageout for LogCollect.

I think Dirk is considering (2), but I wanted to record this as a ticket.

@amaltaro @hufnagel

**Comment by hufnagel** [comment]
Had to write a new xrdcp stageout plugin for this (we didn't have one). Implemented option 2, also because I am not sure if the gfal2 xrdcp plugin supports writing to castor (this needs some legacy command line options which set stager host and service class).

**Comment by hufnagel** [comment]
The old xrdcp stageout plugin was completely non-functional and no one used it. One greek site had it in it's site-local-conf, but that only worked because they also had a fallback rule. Site support contacted them and they elevated their fallback to be the default stageout rule.

**Comment by bbockelm** [comment]
Changes look good to me.  Thanks!
