### ISSUE TITLE
SubmitFailed should report the site it would like to run at

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7018]
just to make sure this does not get lost (could not find a GH issue about it ; please mark duplicate if relevant).
Errors:

    JobSubmit
        SubmitFailed (Exit Code: 71101)

            No sites are available to submit the job because the location of its input(s) do not pass the site whitelist/blacklist restrictions (WMAgent).

needs to be upgraded to "I would like to run at X,Y,Z, but that cannot work right now". so that we know better what is going on at first glance.

**Comment by ticoann** [comment]
Actually, it reports if the possible sites are exists.

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L449

error code 71101 means submit failed due to there is no matching sites.

**Comment by prozober** [comment]
I think this was the first discussion #6868.

**Comment by ticoann** [comment]
Thanks Paola, closing this and we can continue in #6868

**Comment by ticoann** [comment]
duplicate
