### ISSUE TITLE
JobGroup in the agent couchdb

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7021]
if one could sporadically do a search of what corresponds to a certain JobGroup, that would help greatly our understanding. Can we please deploy such a view ?

**Comment by ticoann** [comment]
Think about this again, it might not be that useful to have the view. To access the view you have to login to local agent as well as change the couch config if you want to use browser.
If this is solely debugging purpose, we can use simple db query to get the corresponding workflow name. Would that be sufficient?

```
select cache_dir from wmbs_job where jobgroup=1234;
```
cache_dir contains workflow name

**Comment by vlimant** [comment]
I think that the view has added value. login or tunneling is not a big deal and I'd rather have something I can put in a simple script.

**Comment by ticoann** [comment]
If you want to create the script which needs to be run in local agent,  there is no advantage having a view over querying db directly. The reason I am reluctant to create the view is that there is side effect of the view although it is simple to create the view. It affects the performance and disk size. View can take quite a big space especially if it is againtst the job information.

**Comment by ticoann** [comment]
If you could have the requirement what script would do, maybe I can construct the query for your needs. If it is hard to get from wmbs db, of course we can create the view but I would like to avoid create the new couch view if necessary.

**Comment by amaltaro** [comment]
That's a 2 years old issue, thus I'd assume it's not that important and/or not the best way to have this info. Closing it.
