### ISSUE TITLE
problem with workflow sandbox tarball being zero size

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#7025]
We observed a problem in the Tier0 with the workflow sandbox tarball being zero size. We looked at both the Tier0Feeder logs (since we call wmbsHelper.createSubscription() there) and the JobCreator logs and didn't see anything out of the ordinary.

Any idea what could have happened here ?

**Comment by ticoann** [comment]
which version of agent are you using? Is this first  time observing the problem?

**Comment by hufnagel** [comment]
Tier0 production deployment, so WMCore version is 1.0.17.pre2. I think this is the first time we have seen this, but @ebohorqu might want to clarify.

**Comment by amaltaro** [comment]
Perhaps you should start considering to follow the same path we do for central production, which is only using "production ready" releases. Cycle 1.0.17 production release would be at least *.pre6, that would certainly save you from some headaches.

**Comment by hufnagel** [comment]
You really think that is the problem here ?! Workflow sandbox creation code hasn't been touched in ages AFAIK.

**Comment by amaltaro** [comment]
Nope, I just made a general comment that sooner or later will hit T0 :)

**Comment by amaltaro** [comment]
BTW, is it a very recent workflow? Or it was created more or less in parallel with the disk space issues the T0 agent was facing a week or so ago?

**Comment by hufnagel** [comment]
Could be related to the disk space issues, in fact, that's the most likely explaination. Still a problem though since it means the workflow sandbox creation ignores an error in creating the tarball.

**Comment by amaltaro** [comment]
Fixed by #7151
