### ISSUE TITLE
Convert commands and popen2 to subprocess

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#7070]
I think most of all of this could be done as part of #7067. However, subprocess changed in python 3.5 to include a run() method that replaces almost everything. I'd suggest converting now to subprocess.call() or whatever is needed but put a comment in the code about the suggested subprocess.run() syntax so we can fully modernize down the road.

**Comment by hufnagel** [comment]
We should push to deprecate the former, since FNAL should be able to switch to the Xrdcp plugin.

**Comment by khurtado** [comment]
Looking into this, is there anything else left to do besides eventually replacing `subprocess.call` in this ticket? commands/popen2 were ported already. Should I just make a function in e.g.: Utils/Utilities that use either `subprocess.call()` or `subprocess.run().returncode` depending on the python version?

**Comment by amaltaro** [comment]
Kenyi, you're correct. The work has already been done and the only thing left is the python2 cleanup, once we hit python3 in production.
I think we can close this issue and open a new one for the python2 cleanup in the next year or so.
