### ISSUE TITLE
Remove try/except import cPickle

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#7110]
This is after we have comfortably migrated to python3. cPickle will no longer exist and there is no need to try to import it before falling back to pickle.

**Comment by amaltaro** [comment]
As quickly discussed this morning with Dario and Todor, we decided to postpone it to after we have python3-based services running in production.

**Comment by amaltaro** [comment]
@mapellidario I'm moving it to Q4 (it should actually go to 2022). I think we should keep importing cPickle as long as WMCore supports python2.
