### ISSUE TITLE
ExecutableNotFound not really informative

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7114]
When getting error code 127, propagated at ExecutableNotFound, there is no mention of what is "not found" making difficult to know at which level the problem occured

**Comment by ticoann** [comment]
@vlimant  Would it be enough information by adding which command is not found? I am not sure whether we can get any other information for this case. (Not sure error log is created)

**Comment by amaltaro** [comment]
Seangchan, any chance to get the hostname and add to the same error basket?

**Comment by ticoann** [comment]
Hi Alan I think it is easy to add host name. but not site name directly unless there is easy way to get the site name. I will add host name.

**Comment by vlimant** [comment]
The site name is provided at a higher level, it's fine
Having what command was not found should give a goo hint on how/where to fix
