### ISSUE TITLE
Files are not injected to PhEDEx but DBS is updated.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7115]
1. Although the files found in wmbs marked as PhEDEx injected but those are not in PhEDEx
   need to check the logic for the validation on PhEDEx inject status. 
2. Data is all deleted although it shouldn't have. (If the problem in the 1. case, drain status checking might get the wrong information from dbsbuffer_file table (in_phedex).
   need to review the drain status check script.
   Also it might be the case that dbsbuffer_file table gets deleted prematurely (although we don't clean up the table automatically,  - need to check the drain status.  

problem was reported initially #7107

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Files are not injected to PhEDEx but DBS is updated](https://trello.com/c/HVhiQhU3/2-files-are-not-injected-to-phedex-but-dbs-is-updated)

**Comment by ticoann** [comment]
closing it. There is patch updated although it is not 100% sure this is fixed.
