### ISSUE TITLE
WQE created with wrong priority

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7126]
https://cmsweb.cern.ch/reqmgr/view/details/prozober_ACDC_ACDC_recovery-0-fabozzi_HIRun2015-HIForward-02May2016_758p4__160830_112011_5843

priority is 900k, 

 has one WQE

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC_ACDC_recovery-0-fabozzi_HIRun2015-HIForward-02May2016_758p4__160830_112011_5843

 priority was 85k.
Had to change the priority of the wf to 900k to get the wqe aligned.

**Comment by ticoann** [comment]
Does this happen only ACDC? Could you tell me the steps  to reproduce the problem?

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=jen_a_recovery-6-fabozzi_Run2016B-2-SingleElectron-01Jul2016_8013p1__160812_182758_1667

another one. Not an ACDC. No clear way to reproduce.

**Comment by vlimant** [comment]
N.B.

jen_a_recovery-7-fabozzi_Run2016B-2-SingleElectron-01Jul2016_8013p1__160812_182816_2206.request.priority = 87000

jen_a_recovery-7-fabozzi_Run2016B-2-SingleElectron-01Jul2016_8013p1__160812_182816_2206.request.schema.RequestPriority = 900000.0

**Comment by amaltaro** [comment]
How were these workflows created? Can you point which script you are using?

**Comment by amaltaro** [comment]
Are they assigned within Unified or also standalone scripts? If the latter, please point us to the code.

**Comment by ticoann** [comment]
Especially please provide which script creates this workflow.  (I looked at the code for generating reqmgr1 workflow but I couldn't find specific place yet)

jen_a_recovery-7-fabozzi_Run2016B-2-SingleElectron-01Jul2016_8013p1__160812_182816_2206

**Comment by vlimant** [comment]
not by unified. Looks like it was assigned by hand, created from makeACDC and recoveryMissingLumis.py @prozober @jenimal

**Comment by jenimal** [comment]
any workflow with "recovery" in it's name was created by the recoveryMissingLumis.py script and assigned by hand, using the web interface.  The acdc's of the recovery were most likely made, and assigned via the web interface as well.  Jen

**Comment by ticoann** [comment]
@jenimal, Jen can you show me or point me the exact procedure? I would like to reproduce on vm or at least on the testbed.

**Comment by jenimal** [comment]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/RecoveringWorkflows

Enjoy

**Comment by ticoann** [comment]
FYI

I am trying to create the recovery workflow in testbed. (modify the script to point to testbed)

python WmAgentScripts/recover/recoverMissingLumis.py -q sryu -g DATAOPS -r amaltaro_ReReco_Parents_Integ_Test_Sept2016_Patches_160914_104332_3349

Not related to this problem, but one thing I notice is that following block name comes back with se names. which shouldn't. 
Blockname: /Cosmics/Commissioning2015-PromptReco-v1/RECO#77f9d258-b5d6-11e4-8732-02163e00d625	Locations: set([u'srm-eoscms.cern.ch', u'eoscmsftp.cern.ch', u'cmsdcatape01.fnal.gov', u'cmsdcadisk01.fnal.gov'])

Although I am not sure where this list comes from.
Calling directly dbs gives me PhEDEx node name

https://cmsweb.cern.ch/dbs/prod/global/DBSReader/blockorigin?block_name=/Cosmics/Commissioning2015-PromptReco-v1/RECO%2377f9d258-b5d6-11e4-8732-02163e00d625

[{"create_by": "tier0@vocms15.cern.ch", "creation_date": 1424108239, "open_for_writing": 0, "last_modified_by": "tier0@vocms15.cern.ch", "dataset": "/Cosmics/Commissioning2015-PromptReco-v1/RECO", "block_name": "/Cosmics/Commissioning2015-PromptReco-v1/RECO#77f9d258-b5d6-11e4-8732-02163e00d625", "file_count": 89, "origin_site_name": "T2_CH_CERN", "last_modification_date": 1424108239, "block_size": 347495323824}]

**Comment by amaltaro** [comment]
Fixed by #7228
