### ISSUE TITLE
Make a list of accepted parameters for creation and another for assignment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7133]
and enforce this list. Otherwise we end up with key/values in the schema (from creation time) that don't really set all the need properties (or for all the tasks). Then, if you don't provide them during assignment, it would default to the default values instead of those injected during creation.

In the end it brings us to a messy environment :(

**Comment by ticoann** [comment]
@amaltaro, Alan if you could create the list, I can add in the validation.
Basically it is controlled by
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L882
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L884

**Comment by vlimant** [comment]
+1
