### ISSUE TITLE
Create a new api which give statistics for by each exit code

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7134]
Need a statistics for each error code not just first step of the error code.
i.e
number of failed jobs  by workflow, task, exitCode, site, agent 

Dan, How many include sample reports per each case? (If we organize this way not all the samples might not be the same) sample means whole reports contains all the exitCodes and details with in a job.

**Comment by dabercro** [comment]
I think having up to five unique reports per error code should be enough to determine if the exits are done for the same reason. Hopefully that many don't usually get filled.

**Comment by juztas** [comment]
Hey,
Maybe this requires a different issue, but still good to mention. CRAB or Prod job is using condor_chirp if available and report the exitCode. CRAB is doing post processing analysis on the exitCode, and reports really wide range of exitCodes, Production sadly not. Maybe improve condor_chirp report and report better exitCode through condor and leave Wmagent for real work? For example for the last 24h CRAB3 exit codes:
![image](https://cloud.githubusercontent.com/assets/646582/18167233/b4f11358-704f-11e6-9f55-03b747569c4f.png)
And here production for the last month:
![image](https://cloud.githubusercontent.com/assets/646582/18167249/d5f53a3e-704f-11e6-82af-3dcdeb0ace56.png)

-1 means not reported anything.
This would not make load on Couch or WMAgent, also all of this data is kept under Brian's ES and also under cms-gwmsmon. cms-gwmsmon already provides API for unified for memory/walltime tuning, depending on exitCode. Same it also gives an overview of exitCodes and more info about each site.

Now if I understand what Dan wants, some parts are already available through cms-gwmsmon and it is missing only per agent (Straight forward to add, all information is already available). Per site API is not exposed, but it is only 1 line change.

I hope someday to make stageout report through chirp, which is also interesting to see site stageout failures/fallbacks. So this also could be one of indicators for site being bad...

**Comment by dabercro** [comment]
This could be useful. In particular, we don't actually know the number of successes at each site (though I guess some still eventually fail). Also, I can also compare the exit code yields here to the WMAgent exit codes. Let me know if you expose the per site API.

**Comment by ticoann** [comment]
@dabercro, Dan, is this still relevant?

You can control sample size on the REST parameter.

https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/prozober_ACDC1_task_EXO-PhaseIFall16wmLHEGS-00014__v1_T_170217_094501_9422?sample_size=5

**Comment by dabercro** [comment]
@ticoann thanks. You can close this issue too, I think.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a new api which give statistics for by each exit code](https://trello.com/c/UdTeLAMM/20-create-a-new-api-which-give-statistics-for-by-each-exit-code)

**Comment by amaltaro** [comment]
Closing it due to lack of activity.
