### ISSUE TITLE
replication down on submit2

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7135]
I noticed that replication is down on submit2.  Can you please give it a kick?

Jen

**Comment by amaltaro** [comment]
Either someone did something or the agent is back to normal.
Next time, please restart couch yourself, it should only require dev attention it it happens too often

**Comment by ticoann** [comment]
It should recover automatically in case replication stop.
To manually restart, restart couch and then AgentStatusWatcher.

**Comment by jenimal** [comment]
I will add those instructions to the shifter duties.  Thanks guys

Jen
