### ISSUE TITLE
High piority WQE Staying in Available

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7137]
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22fabozzi_HIRun2015-HIHardProbes-02May2016_758p4_160621_231330_3074_15baa5c8-6f79-11e6-bde9-02163e00f196%22&include_docs=true&reduce=false

 was sitting there since yesterday and more in Available, eventhough all matches and Vanderbilt is not overwhelmed with pending jobs at 900k priority.
I raised to 1M priority "just to see" and it got it moving.

right this moment, Vanderbilt is pending 0 jobs at 900k priority and a couple of thousands at 85k priority.

Can you please trace why that happened so that we do not have workflow stuck in acquired for no good reason, especially at 900k priority.

**Comment by amaltaro** [comment]
Can you please provide full details when reporting these issues? What's the workflow name that was stuck?

**Comment by amaltaro** [comment]
Each agent has 420 pending thresholds for Vanderbilt, as you can see, during the last 48h we had pending jobs maxxed out among all the 5 agents:
http://dashb-cms-prod.cern.ch/dashboard/request.py/condorjobnumbers_individual?sites=T2_US_Vanderbilt&sitesSort=2&jobTypes=&start=null&end=null&timeRange=last48&granularity=Hourly&cores=&sortBy=0&series=All&type=p

Likely there was some kind of problem with the priorities. Is it the same workflow that you reported having 900k prio but wqe with 83k or so?

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr/view/details/prozober_recovery-0-fabozzi_HIRun2015-HIHardProbes-02May2016_758p4__160831_144841_2581 
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_recovery-0-fabozzi_HIRun2015-HIHardProbes-02May2016_758p4__160831_144841_2581
are the link I meant to put.
The WQE was priority 900k.

**Comment by vlimant** [comment]
not the same wf as in #7126

**Comment by vlimant** [comment]
assuming this was just a delay for getting things under control on the agent, regardless of the very high priority of the wqe
