### ISSUE TITLE
TrusPUSiteList=True not functionning in ACDC assignment

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7138]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC_EXO-RunIISpring16DR80-03702_00622_v0__160901_084155_3027

 was assigned with TrustPUSitelist=True and yet the WQE has "NoPileupUpdate":false and does not want to move on to acquired because of the PU location.

 no DR80 ACDC is getting to run now because of this.

**Comment by amaltaro** [comment]
We definitely need to improve these issues reports if you want us to work efficiently on them...
1. how was the acdc created? which script?
2. how was it assigned? which script? any chances you still have the command line in your terminal?

**Comment by vlimant** [comment]
1. makeACDC as usual
2. assign.py --secondary_xrootd

 both used to function but as you can see, despite the spec having the correct values, the WQE does not.

**Comment by vlimant** [comment]
@prozober please create the ACDC for pdmvserv_EXO-RunIISpring16DR80-04266_00626_v0__160826_164045_3022 and assign with assign.py using the --secondary_xrootd option as usual

**Comment by amaltaro** [comment]
Use `--verbose` please and report it back here the output of:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/assign.py#L91

**Comment by vlimant** [comment]
﻿﻿https://github.com/CMSCompOps/WmAgentScripts/blob/master/resubmit.py you have blacklisted the TrustPUSitelists and https://github.com/CMSCompOps/WmAgentScripts/blob/master/assign.py sets it alright

**Comment by prozober** [comment]
Alan, I am attaching the output of the assignment process.
[output.txt](https://github.com/dmwm/WMCore/files/449723/output.txt)

**Comment by vlimant** [comment]
yup https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/b90d2fc74a48d0181e255dd8f811be6c 
"NoPileupUpdate":false

**Comment by vlimant** [comment]
one more piece of info : existing ACDC that made it through all seem to have an intersection with the PU location, so the issue might have been there since day one.

**Comment by amaltaro** [comment]
BTW, does it happen only for ACDCs?
I'll investigate it in the coming days.

**Comment by vlimant** [comment]
Only ACDC as far I can tell, as all premix backfill tests were assigned this way.

**Comment by vlimant** [comment]
N.B. this is a show-stopper to making recoveries on the on-going DR80 campaign with premix.

**Comment by amaltaro** [comment]
Then I'm working on it. Thanks!

**Comment by amaltaro** [comment]
Fix will be available only in the next production deployment (Sept 13th)

**Comment by vlimant** [comment]
We'll clone DR80 instead of ACDC untill then
