### ISSUE TITLE
Add more performance information to the FJR.xml

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7140]
and push it all the way up to WMArchive as well. It seems this is where we set the CMSSW FJR sections that we want to keep:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L506

From @yuyiguo , we need to collect at least "WMAgents needs to add EventThroughput and TotalLoopCPU." And maybe some multicore (or numberOfThreads or so), which is available in releases > 80x, right?

**Comment by yuyiguo** [comment]
Yes. We need to add EventThroughput and TotalLoopCPU to WMAgent's fwjr,  and remove *EventCPU from WMAgent FWJR.  But these changes are  only shown up at cmssw version 7_4_0 or later.  

CMSSW does not know info of multicore. So the new matrix in the agent's FWJR are: 
MinEventTime,
MaxEventTime,
AvgEventTime,
EventThroughput,
TotalJobTime,
TotalJobCPU,
TotalLoopCPU.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/8195
Feel free to reopen if something is missing.
