### ISSUE TITLE
reqmgr2 GUI improvement

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7146]
From Paola's report

1. a drop-down list for the fields Team, MergedLFNBase and UnmergedLFNBase. We need to avoid any possible mistake.
2. It would be possible to have a drop-down list with multiple selection? That for SiteWhitelist ,SiteBlacklist, CustodialSites, NonCustodialSites.
3. TrustSitelists and TrustPUSitelists, need to be false or true always, a drop-down list would be necessary. 
4. SubscriptionPriority needs to be a drop-down list with the values, Low, Normal, and High.
5. Custodial/Noncustodial Subscription Type need to be a drop-down list with the values, Replica and Move
6. I've never touched the Dashboard field.
7. All fields in the form would be first fill with values by default? I mean, when I am going to assign an ACDC in the current web interface the following fields are set by default:
    - AcquisitionEra 
    - ProcessingString
    - ProcessingVersion
    - MergedLFNBase
    - UnmergedLFNBase
    - SubscriptionPriority

**Comment by amaltaro** [comment]
@SaltumDis seems to have some spare cycles and she just told me she is pretty good at this thing :-)
@ticoann @ericvaandering unless you already have something else for her?

**Comment by amaltaro** [comment]
example:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_Data_HG1609_ReqMgr2_Validation_160906_130238_3451

**Comment by ticoann** [comment]
If Adelina has spare time. She is more than welcome to improve GUI. Unless Eric has something else in mind. (Storage backend test code is done, right?)

**Comment by SaltumDis** [comment]
@ticoann They are done. #7160

**Comment by ticoann** [comment]
Eric approved we can use Adelina for reqmgr GUI part. First, I think she need to be able to set up the testbed if she didn't have it yet. Alan, could you help her to set it up (Of course after your vacation)?

**Comment by amaltaro** [comment]
Just completing some information as discussed with Adelina today:
* Do not set any default unless it's written in the lines below (meaning it should be None)
* `Team`should default to ... `None` I guess. Then we have to validate where the team name was provided during assignment (but this is on us, not on Adelina)
* Any `Site`blah parameters should default to an empty list.
* `UnmergedLFNBase` should default to `/store/unmerged`
* The `Trust...` flags should default to `False`
* `Dashboard` should contain the following fields: test, reprocessing, production and integration

Then we have some tricky parameters (just input text box):
* `AcquisitionEra`, `ProcessingString`, `ProcessingVersion` should be a text box and default to the original value, if available.
* `MaxRSS` should default to `Memory` value * 1024
* `MaxVSize` should default to `20294967`
and these default values
```
              "BlockCloseMaxWaitTime" : 86400,
              "BlockCloseMaxFiles" : 500,
              "BlockCloseMaxEvents" : 20000000,
              "BlockCloseMaxSize" : 5000000000000,
              "SoftTimeout" : 129600,
              "GracePeriod" : 1000
```

**Comment by amaltaro** [comment]
And you can find some of these apis here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Tools/cms.py#L95

**Comment by amaltaro** [comment]
Basically the same as #6932 and fixed as well.
