### ISSUE TITLE
Assigning StepChain with dictionnary AcquisitionEra

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7155]
I assigned 

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/vlimant_task_BPH-RunIIFall15DR76-00057__v1_T_160905_213311_4199

with

{
  "SoftTimeout": 159600,
  "MaxVSize": 4394967000,
  "BlockCloseMaxEvents": 2000000,
  "MinMergeSize": 2147483648,
  "CustodialSites": [],
  "MaxMergeSize": 4294967296,
  "NonCustodialSites": [
    "T1_FR_CCIN2P3_Disk"
  ],
  "ProcessingVersion": 1,
  "MaxRSS": 2027520,
  "ProcessingString": {
    "BPH-RunIIFall15MiniAODv2-00057_0": "PU25nsData2015v1_76X_mcRun2_asymptotic_v12",
    "BPH-RunIIFall15DR76-00057_1": "PU25nsData2015v1_76X_mcRun2_asymptotic_v12",
    "BPH-RunIIFall15DR76-00057_0": "PU25nsData2015v1_76X_mcRun2_asymptotic_v12"
  },
  "Teamproduction": "checked",
  "Dashboard": "reprocessing",
  "SiteWhitelist": [
    "T1_FR_CCIN2P3",
    "T2_US_MIT"
  ],
  "TrustSitelists": false,
  "AutoApproveSubscriptionSites": [
    "T1_FR_CCIN2P3_Disk"
  ],
  "UnmergedLFNBase": "/store/unmerged",
  "CustodialSubType": "Replica",
  "TrustPUSitelists": false,
  "GracePeriod": 300,
  "MergedLFNBase": "/store/mc",
  "MaxMergeEvents": 200000,
  "checkboxvlimant_task_BPH-RunIIFall15DR76-00057__v1_T_160905_213311_4199": "checked",
  "SiteBlacklist": [],
  "action": "Assign",
  "AcquisitionEra": {
    "BPH-RunIIFall15MiniAODv2-00057_0": "RunIIFall15MiniAODv2",
    "BPH-RunIIFall15DR76-00057_1": "RunIIFall15DR76",
    "BPH-RunIIFall15DR76-00057_0": "RunIIFall15DR76"
  },
  "NonCustodialSubType": "Replica"
}

and 

"OutputDatasets":[
"/BdToKK_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/AODSIM",
"/BdToKK_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/DQMIO",
"/BdToKK_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM"

they all have the same acquisitionera despite the chain-specific setting.
Is there anything special needed to assign StepChain ?

**Comment by amaltaro** [comment]
Hmm, StepChain requests have only one production/processing task, that means we have a single AcquisitionEra for the whole workflow. My final answer would be that WMCore does not support output dataset definition by *step*.

About the assignment with dictionary, this is a validation that we can improve and enforce (actually allow) it only for TaskChain requests. So you have to assign StepChain requests just as any non-TaskChain requests.

**Comment by amaltaro** [comment]
You can have a look at this template:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/StepChain_MC.json

that's how StepChain requests should be built.

**Comment by vlimant** [comment]
@amaltaro thanks for the schema, I had seen it and used to make the conversion. era was ambiguous but now https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/TaskChain_MC.json I get it.
I think this is a show-stopper to using StepChain in replacement of TaskChain as requester expect the Campaign/Era + ProcessingString to be multiple

**Comment by amaltaro** [comment]
On the other hand, since StepChain is supposed to process all the chain until the end, why can't we change this CMS pattern and make it a single Campaing/Era + ProcessingString?

Is there any good reason to have BlahGS for GEN-SIM tiers and BlahDR for GEN-SIM-DIGI/RECO tier?

**Comment by vlimant** [comment]
I have doubts that this can be changed for many operational and book-keeping reasons, way beyond your and my responsibility.

How hard is it to have StepChain look like TaskChain in this respect ?

**Comment by amaltaro** [comment]
I have to "study" the code, but it's likely not possible since StepChain uses a completely different spec layout.

**Comment by drkovalskyi** [comment]
If we want StepChain to be used it has to be fixed. The main use case is that different steps of processing can be submitted as a chain, but each step is an independent entry in PPD database and accounted separately. They won't ever have a single campaign that would do everything from scratch till final user output. It's also very important that they can chain different number of steps, i.e. in some cases they start from existing GenSim in other GenSim is generated and store on the fly.

**Comment by amaltaro** [comment]
Dima, I'm not following you.
This issue is only related to the naming of the output datasets, nothing else.
PPD can create as many steps as they want in a StepChain request (shouldn't matter how many PPD requests it is), either completely from scratch or not.

My question was about the output dataset names. We have redundant information on the dataset names since day 0. I wonder if we must keep these redundancy or whether it's just convenience?
Depending on the answer, feel free to give it a priority and I can start looking at how hard is it to make this change .

**Comment by bbockelm** [comment]
Hi,

I was asked earlier why we were running task chains and not step chains; seems this ticket is the blocker?

Any progress since the discussion in September?

Thanks,

Brian

**Comment by amaltaro** [comment]
Yes, it seems to be the blocker. This issue also affects stepchain: https://github.com/dmwm/WMCore/issues/6787

I had a quick look at it this week and I don't expect it to be simple. WMStep/ConfigSection object doesn't really support dataset naming args (it's up to WMTask), so it's going to be a significant change. Still on my list though

**Comment by bbockelm** [comment]
Great, thanks for the update!  The github thread had gone cold, so it was difficult to determine if anyone was still actively thinking about the subject.

**Comment by amaltaro** [comment]
This issue was fixed and it's now in testbed. If everything is fine, it will be deployed in production next Tuesday.
