### ISSUE TITLE
Update code using optparse to argparse

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7158]
optparse is deprecated since py2.7. At least the reqmgr client scripts use it.

**Comment by amaltaro** [comment]
I'll take care of it after the current validation, unless @prozober jumps in before me :-D

**Comment by amaltaro** [comment]
@alexanderrichards , how about this one? If it's only used in test/*/reqmgr.py, then I think we can simply delete that client and close this issue.

**Comment by alexanderrichards** [comment]
ok, I'll take a look, thanks

**Comment by amaltaro** [comment]
@alexanderrichards can you remind me whether it has been fixed already?
