### ISSUE TITLE
Expose sites threshold and status to the external world

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7170]
the agents are dealing with various metrics from SSB and might override the status (columnid=237) and we end up assigning work to sites the agent cannot work with.
The example is T2_RU_JINR at the moment.
If you can expose the sites thresholds as seen by the agent, Unified can use this as "up" metric and we avoid assigning work that get stuck:

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_EXO-RunIISpring16MiniAODv2-05018_00517_v0__160907_095033_199

It has nothing to do with the clone, or assigning by hand. Operation needs to know what are the sites the agents can work with unambiguously.

@prozober

**Comment by amaltaro** [comment]
This is part of the agent monitoring. The information is already available in the agent, but not exposed yet.
BTW, how will you handle different information among different agents (drain/normal agents)?
Lowering this to medium prio as well.

**Comment by vlimant** [comment]
https://ggus.eu/index.php?mode=ticket_info&ticket_id=123784

**Comment by vlimant** [comment]
I had to manually set T2_RU_JINR up in the agent to get the workflow through.

**Comment by vlimant** [comment]
I have seen such information reported to wmstats, so maybe this issue should be updated ?

**Comment by amaltaro** [comment]
That's right! Thanks, closing the issue
