### ISSUE TITLE
Need to clean up workflows in status archived

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7173]
there are currently 
2185 Workflows in status announced, that have not been archived that are no longer associated with an agent, so they will never be archived.  They need to be cleared out of the system so central couch databases can get cleaned up.

there are also 	655 announced workflows on 053, but that is the relval agent, so I am guessing that is ligit.

Jen

**Comment by ticoann** [comment]
It is cleanup now. I am closing this issue.  I will investigate what caused this case. I am assuming draining check doesn't check for the archived status before wipe out the agent. But there might be an other bug.

**Comment by amaltaro** [comment]
No, we don't and we cannot :) Agents are redeployed kind of "on the fly", we cannot wait for all workflows to get archived for that, otherwise agent redeployment will take months instead of a week or two.

**Comment by jenimal** [comment]
Is there anyway of forcing the archive?  otherwise workflows get stuck in the agent forever until somebody manually moves them causing more work for the agent to track dead workflows.
