### ISSUE TITLE
Need to cleanup aborted workflows

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7176]
I'm busy cleaning the agent, and notice that we have 50 workflows in abort or abort-completed, they should be moved to abort-archived, but that should all happen automatically so I'll post the list here, and leave it to the experts to find out why they haven't moved.  If you want I can move them by hand, but always best to find out why things aren't moving on their own.

```
vlimant_ACDC_EXO-RunIISpring16DR80-04070_00649_v0__160902_025340_7855   aborted Resubmission    700000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
```

prozober_ACDC_EXO-RunIISpring16MiniAODv2-04535_00485_v0__160831_105226_3686 aborted Resubmission    70000   100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
diego_Run2016B-1-Backfill-SingleMuon-01Jul2016_8013p1_160831_093906_751 aborted ReReco  87000   100.0%  100.0%  4.0%    8.3%    23.9%   0 h 0 m 0
pdmvserv_BPH-RunIISpring16DR80-00040_00606_v0__160819_164019_9653   aborted ReDigi  90000   100.0%  100.0%  9.2%    9.7%    0.0%    0 h 0 m 0
jen_a_ACDC_HIG-RunIISpring16DR80-01778_00601_v0__160818_110237_9792 aborted Resubmission    90000   100.0%  100.0%  0.0%    0.0%    100.0%  0 h 0 m 0
jen_a_recovery-7-fabozzi_Run2016B-2-ZeroBias-01Jul2016_8013p1__160815_161228_2508   aborted Resubmission    900000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_SUS-RunIIFall15MiniAODv2-00158_00286_v0__160804_094343_5914   aborted Resubmission    85000   100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_task_EXO-RunIISpring16DR80-03464__v1_T_160725_174306_2970 aborted Resubmission    110000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_task_EXO-RunIISpring16DR80-03560__v1_T_160725_174251_3034 aborted Resubmission    110000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_task_EXO-RunIISpring16DR80-03473__v1_T_160725_174236_2120 aborted Resubmission    110000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_task_EXO-RunIISpring16DR80-03473__v1_T_160725_174229_3843 aborted Resubmission    110000  100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
prozober_ACDC_task_EXO-RunIISpring16DR80-03478__v1_T_160725_174150_9280 aborted Resubmission    110000  100.0%  100.0%  0.0%    0.0%    100.0%  0 h 0 m 0
jen_a_ACDC_Run2016B-AlCaLumiPixels3-07Jul2016_8014_160722_221559_2110   aborted Resubmission    85000   100.0%  100.0%  0.0%    0.0%    0.0%    0 h 0 m 0
jen_a_ACDC_EXO-RunIISpring16MiniAODv2-01297_00162_v0__160609_215009_7492    aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_EXO-RunIISpring16MiniAODv2-01296_00162_v0__160609_214915_540 aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-02073__v1_T_160609_042119_8150  aborted-completed   TaskChain   80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_task_EXO-RunIIWinter15wmLHE-03007__v1_T_160608_215400_2907   aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-02117__v1_T_160608_202430_1608  aborted-completed   TaskChain   85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-02107__v1_T_160608_202116_3845  aborted-completed   TaskChain   85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_HIG-RunIISpring16MiniAODv2-00675_00185_v0__160608_183818_3344  aborted-completed   ReDigi  85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_HIG-RunIISpring16MiniAODv2-00665_00185_v0__160608_183551_2079  aborted-completed   ReDigi  85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_HIG-RunIISpring16MiniAODv2-00644_00184_v0__160608_182952_1492  aborted-completed   ReDigi  85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_HIG-RunIISpring16DR80-00418__v1_T_160608_175408_7069 aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-02011__v1_T_160608_121912_6298  aborted-completed   TaskChain   80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_HIG-RunIISpring16DR80-00072__v1_T_160607_210239_7412 aborted-completed   Resubmission    90000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_TOP-RunIISpring16DR80-00027__v1_T_160607_205230_8464 aborted-completed   Resubmission    95000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_HIG-RunIISpring16DR80-00182__v1_T_160607_204759_7869 aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_HIG-RunIISpring16DR80-00182__v1_T_160607_204744_7373 aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-01995__v1_T_160607_203817_5433  aborted-completed   TaskChain   80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-01873__v1_T_160607_203428_9450  aborted-completed   TaskChain   80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_EXO-RunIISpring16DR80-01856__v1_T_160607_203405_6369  aborted-completed   TaskChain   80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_SUS-RunIIFall15DR76-00109__v1_T_160607_165803_1455   aborted-completed   Resubmission    70000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_SUS-RunIIFall15DR76-00109__v1_T_160607_165756_2349   aborted-completed   Resubmission    70000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_SUS-RunIIFall15DR76-00109__v1_T_160607_165750_969    aborted-completed   Resubmission    70000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_SUS-RunIIFall15DR76-00109__v1_T_160607_165744_404    aborted-completed   Resubmission    70000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_ACDC_task_SUS-RunIIFall15DR76-00109__v1_T_160607_165737_6716   aborted-completed   Resubmission    70000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
vlimant_BPH-Summer12-00220_00255_v0__160531_215750_8215 aborted-completed   MonteCarlo  85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_task_SUS-RunIISpring16DR80-00077__v1_T_160524_231704_1995    aborted-completed   Resubmission    90000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_task_SUS-RunIIWinter15pLHE-00346__v1_T_160517_231741_7262    aborted-completed   Resubmission    110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
prozober_SUS-RunIISummer15GS-00145_00284_v0__160603_142813_6145 aborted-completed   MonteCarloFromGEN   85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_task_B2G-RunIISpring16DR80-00254__v1_T_160531_203735_6766 aborted-completed   TaskChain   85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_task_HIG-RunIISpring16DR80-00036__v1_T_160422_232851_9669    aborted-completed   Resubmission    85000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_task_SMP-RunIIFall15DR76-00087__v1_T_160421_180345_654   aborted-completed   Resubmission    700000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
vlimant_FSQ-RunIISpring16FSPremix-00001_00001_v0_forPremixMB_160417_212807_4165 aborted-completed   MonteCarlo  110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_SMP-RunIISummer15wmLHEGS-00007_00004_v0__160415_124401_3730    aborted-completed   MonteCarlo  90000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_SUS-RunIIWinter15pLHE-00345__v1_T_160415_085721_7184  aborted-completed   TaskChain   110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_SUS-RunIIWinter15pLHE-00347__v1_T_160415_085717_1899  aborted-completed   TaskChain   110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
pdmvserv_task_SUS-RunIIWinter15pLHE-00346__v1_T_160415_085706_2349  aborted-completed   TaskChain   110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_ACDC_SUS-RunIIWinter15pLHE-00354_00157_v0__160413_204518_2656    aborted-completed   Resubmission    110000  0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0
jen_a_ACDC_TOP-pp502Fall15wmLHEGS-00006_00004_v0__160411_174046_8994    aborted-completed   Resubmission    80000   0.0%    0.0%    0.0%    0.0%    0.0%    N/A 0

**Comment by ticoann** [comment]
There are 13 aborted workflow which agent still need to update the workload summary. For other 37 aborted-completed workflows are moved to aborted-archived now. 
@jenimal, Jen, can you check and if this is fixed please closed the issue.

**Comment by ticoann** [comment]
Generally, it takes time to clean up and put workload summary report, Do you have any particular workflow you are suspecting to be stuck?

**Comment by amaltaro** [comment]
BTW, which agent is it?

**Comment by vlimant** [comment]
@ticoann what is the actual fix that was applied ? How do we not get there again ? anything specific for the agent doc @scarletnorberg .

**Comment by vlimant** [comment]
Can the label "Urgent OPS" please be removed and reserved for things preventing operation.

**Comment by ticoann** [comment]
This is fixed.
