### ISSUE TITLE
FWJR performance parameters for CPU  

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMCore#7177]
CMSSW added two new  performance parameters "EventThroughput" and "TotalLoopCPU", and removed "AvgEventCPU",  "MaxEventCPU", "MinEventCPU" and "TotalEventCPU".  This change happened at CMSSW_7_4_0. We have some agents already using this version of CMSSW, however we did not get a single   "EventThroughput" or  "TotalLoopCPU" in the data until 9/12/2016.

@amaltaro ,  @ticoann please take a look.

**Comment by yuyiguo** [comment]
@vkuznet @ticoann @amaltaro 
Look below fwjr that I got from testbed MongoDB , the "EventThroughput" and  "TotalLoopCPU"  were already there. This db was created using couchDB Seangchan copied for me a month ago.

In case you want to look the db yourself, here is the search query:
 db.realData.findOne({"task":{$regex:/^\/pdmvserv_task_SMP-RunIIFall15DR76-00083__v1_T_160313_135718_7429\//}})

 "meta_data" : {
                "jobstate" : "success",
                "ts" : 1458618418,
                "fwjr_id" : "1-0",
                "host" : "vocms013.cern.ch",
                "agent_ver" : "test-1",
                "jobtype" : "Processing"
        },
"task" : "/pdmvserv_task_SMP-RunIIFall15DR76-00083__v1_T_160313_135718_7429/SMP-RunIIFall15DR76-00083_0"


 "performance" : {
                                "multicore" : {

                                },
                                "storage" : {
                                        "writeTotalMB" : 879.899,
                                        "readPercentageOps" : 1.00023019375,
                                        "readAveragekB" : 76.3955819928,
                                        "readTotalMB" : 29175.428,
                                        "readNumOps" : 390975,
                                        "readCachePercentageOps" : 0,
                                        "readMBSec" : 0.00329168492533,
                                        "readMaxMSec" : 3257.19,
                                        "readTotalSecs" : 0,
                                        "writeTotalSecs" : 14585200
                                },
                                "cpu" : {
                                        "TotalJobCPU" : 11389.6,
                                        "EventThroughput" : 0.040756,
                                        "AvgEventTime" : 24.423,
                                        "MaxEventTime" : 83.938,
                                        "TotalJobTime" : 20125.1,
                                        "TotalLoopCPU" : 11385.9,
                                        "MinEventTime" : 8.87594
                                },
                                "memory" : {
                                        "PeakValueRss" : 1391.86,
                                        "PeakValueVsize" : 1901.52
                                }
                        },

**Comment by vkuznet** [comment]
Yuyi, I don't see these metrics in FWJRs in MongoDB on production node, e.g.
```
"task" : "/vlimant_BPH-RunIISummer15GS-Backfill-00030_00212_v0__160907_112626_808/Production",
"meta_data" : { "jobstate" : "success", "ts" : 1473746269, "fwjr_id" : "926261-0", "host" : "vocms0304.cern.ch", "agent_ver" : "1.0.19.patch1", "jobtype" : "Production" },
...
"cpu" : { "TotalJobCPU" : 27190.5, "AvgEventCPU" : 0.0626165, "MaxEventTime" : 66.3392, "AvgEventTime" : 0.0645586, "MinEventCPU" : 0.002999, "TotalEventCPU" : 26594.2, "TotalJobTime" : 27419, "MinEventTime" : 0.00281405, "MaxEventCPU" : 65.3591 }
...
}
```

So it means that documents we received don't have it somehow. Looking further, I see that our schema
https://github.com/dmwm/WMArchive/blob/master/src/python/WMArchive/Schemas/FWJRProduction.py#L94
also don't have them. So, I would suggest that you or @ticoann will first fix the schema, then verify on agent side that agents provide this info in FWJR docs.

**Comment by amaltaro** [comment]
And at which level is this schema used? The FWJR built by WMCore should have these fields, as we can see in the mapping schema:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L37

When the agent uploads these docs to WMArchive, is there any validation and further manipulation of these docs?

**Comment by vkuznet** [comment]
Alan,
the schema is required to convert JSON into AVRO. Only fields in schema will be
used during conversion, all other will simply discarded.

But the schema is used only when we transform data from MongoDB to HDFS. And, I
wrote that I don't see these metrics in MongoDB yet, so it seems to me that
agents don't write this info yet.

Valentin.

**Comment by yuyiguo** [comment]
@vkuznet, @amaltaro  When I load my test MongoDB , I used the same filter that @ticoann used to load production MongoDB. I have these new parameters in my MongoDB, so I believe it is your JSON to Avro convert removed these new parameters. You need to add these new parameters into the JSON to Avro  schema. 

You did not see this in production MongoDB may be because the Production only keeps data for one day, the new parameters are only available for cmssw_7_4_0 or later and the agents use more than one cmssw version. So it could be the data you looked at did not have them. But the integrated data from Niles should have them if not removed.

**Comment by yuyiguo** [comment]
@vkuznet , You use below schema to convert JSON to AVRO, right ?https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L37 

We have mixed data because the versions of CMSSW used. The *EventCPU are no longer have meaning because of using multicore. So they need to be removed for the newer CMSSW versions' document and  the EventThoughPut and TotalLoopCPU are only to the newer CMSSW version. Can the convertor of JSON to AVRO handle mixed docs?

**Comment by vkuznet** [comment]
Yuyi,
we may extend schema to include both attributes. The AVRO conversion will use
skip attribute(s) which are not present present in JSON, but schema must list
all attributes. That's why I said that we need to update the schema.
Valentin.

**Comment by vkuznet** [comment]
On  0, Yuyi Guo <notifications@github.com> wrote:
> @vkuznet, @amaltaro  When I load my test MongoDB , I used the same filter that @ticoann used to load production MongoDB. I have these new parameters in my MongoDB, so I believe it is your JSON to Avro convert removed these new parameters. You need to add these new parameters into the JSON to Avro  schema. 

Yuyi, the Mongo takes docs as is, no conversion is done at its level. But AVRO
conversion will not take attributes which are not listed in AVRO schema. This
means that we should see them in Mongo, but so far we'll not see them
on HDFS since there is no entry in AVRO schema.

> 
> You did not see this in production MongoDB may be because the Production only keeps data for one day, the new parameters are only available for cmssw_7_4_0 or later and the agents use more than one cmssw version. So it could be the data you looked at did not have them. But the integrated data from Niles should have them if not removed.

this may explain why I didn't see docs with these attributes.

**Comment by yuyiguo** [comment]
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L37
all ready have the new metrics. What are needed to have them in HDFS?

**Comment by vkuznet** [comment]
I updated the FWJR schema with this PR: https://github.com/dmwm/WMArchive/pull/227
next step would be to put this schema on production server and verify that data will be written correctly.

**Comment by amaltaro** [comment]
Well, I'd say the next step is to put it in testbed and make sure it works Ok before pushing it to production :)

**Comment by vkuznet** [comment]
Alan, of course, I updated preproduction node and if we still have test
agent pushing to cmsweb-testbed then in a day I should see correct data.

**Comment by yuyiguo** [comment]
My question is that if  WMArchive/src/python/WMArchive/Schemas/FWJRProduction.py can be generated from WMCore/src/python/WMCore/Services/WMArchive/DataMap.py? The the two new CPU parameters had been in DataMap.py for a while, but the schema was not updated accordingly. There are so many steps in between, it will help in long run if we can automate some of them.

**Comment by vkuznet** [comment]
Yuyi,
somebody needs to write such piece of code. Feel free to take this task.
Valentin.

**Comment by yuyiguo** [comment]
OK, I take it as long as we agree automating it is better.

**Comment by amaltaro** [comment]
@yuyiguo @vkuznet was it ever fixed? Is it in production now?

**Comment by vkuznet** [comment]
yes, and, you can check yourself any part of written docs, e.g.

```
ssh vocms071

# check which schema WMArchive use
cat /data/srv/current/config/wmarchive/wmarch_config.py  | grep long_storage_uri
data.long_storage_uri = 'hdfs:///cms/wmarchive/avro/schema.avsc'

# get Kerberos ticket to access HDFS
kinit

# scan the schema and check your favorite attibute
hadoop fs -cat hdfs:///cms/wmarchive/avro/schema.avsc | egrep "TotalLoopCPU|EventThroughput"
     "name": "EventThroughput"
     "name": "TotalLoopCPU"
```

**Comment by amaltaro** [comment]
In production since long ago.
