### ISSUE TITLE
Storage performance metrics writeTotalSecs

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMCore#7185]
The value of writeTotalSecs is somthing like 14585200 seconds that is 4051 hours. The number did not make any sense. @amaltaro, @ticoann  can you take a look below code?
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L448

**Comment by juztas** [comment]
Just to add also what I have encountered checking all these values from WMAgent and local couch.
Should be divided ```writeTime   = storageValues.get("Timing-tstoragefile-write-totalMsecs", 0) * 1000```
Same here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L436
Same here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L446
Now this also not correct currently as it is not MBSec: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L453
Also one thing might not be related, but in the agent couchdb I saw that TotalJobTime is lower than TotalJobCPU. This isn't right. 
Also in local couch `readTotalSecs` is always 0...

**Comment by yuyiguo** [comment]
As discussed in the meeting, it should deveided by 1000 to get second.
