### ISSUE TITLE
Instabilities in central workqueue

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7202]
And @geneguvo (thanks a lot!!) found the culprit:
```
$ egrep ' /couchdb/' /build/srv-logs/vocms0160/frontend/access_log_20160920.txt |  awk '{ print $10,$N}'|sort -n -r | head -n20
675236164 [20/Sep/2016:14:33:48 +0200] cmsweb.cern.ch 128.142.35.227 "POST /couchdb/workloadsummary/_bulk_docs/ HTTP/1.1" 502 [data: 675236164 in 20055 out 478 body 335295575 us ] [auth: BLAH ] [ref: "" "WMCore.Services.Requests/v001" ]
request de 675Mb!!!
```
that comes from vocms0303.

After locally changing the code of `CleanCouchPoller.py`, this is the problematic request
```
2016-09-20 19:45:09,805:140469167052544:INFO:CleanCouchPoller:About to commit 1048 bytes (674039780 bytes) of data for workflow summary for prozober_HIG-RunIISpring16MiniAODv2-02871_00462_v0_VBFPostMGFilter_160905_094321_573
```

Which this agent fails to post it to workloadSummary db in vocms0140.

I'm preparing a patch that will check the amount of data that has to be uploaded, and if it's bigger than X MB (maybe 20?), then we either
a) skip the doc upload at all
b) or upload just the doc schema

@ticoann any suggestions? You may want to have a look at the wmstats docs as well, some of those jobs have several errors.

**Comment by amaltaro** [comment]
BTW, I didn't fix it yet because we may want to have a look at what happened before we clear this up. Though we should definitely get it back stable today.
@BrunoCoimbra FYI

**Comment by ticoann** [comment]
Do you know what make the workload summary data so big? Is it the file names or lumi sections?

**Comment by ticoann** [comment]
@geneguvo, Thanks a lot Diego.

**Comment by amaltaro** [comment]
It was the lumi list length for the errors, which may be fixed now (well, shouldn't bug couch anymore).

I basically got the runsAndLumis list (list of lumis) for each error in the summary and make it a compactList (list of lists - lumi ranges). The original summary that was around 670MB, went down to 18MB
```
2016-09-20 22:47:38,556:140649266112256:INFO:CleanCouchPoller:About to commit 18479559 bytes of data for workflow summary for prozober_HIG-RunIISpring16MiniAODv2-02871_00462_v0_VBFPostMGFilter_160905_094321_573
```

the fix is not clean, but there isn't much that we can do in this case besides cap the number of lumis or "aggregate" them. I'll make a PR tomorrow.

Just in case, you can find 2 files in the current dir in vocms0303
workload_summary_new.json (dump of the summary with my patch)
workload_summary_ori.json (dump of the summary as it was before)

**Comment by amaltaro** [comment]
BTW, I'm not sure why, but I still cannot find the workload summary doc for this workflow
https://cmsweb.cern.ch/couchdb/_utils/document.html?workloadsummary/prozober_HIG-RunIISpring16MiniAODv2-02871_00462_v0_VBFPostMGFilter_160905_094321_573

the logs look Ok, no errors.

**Comment by ticoann** [comment]
Thanks a lot Alan, Yes, I thing we should change to range instead of lumi list. 
There could be sparse case but I am not sure there is better compression algorithm which is not very complicated.

**Comment by vlimant** [comment]
good progress ! bravo. is couch now stable-ish ? https://github.com/dmwm/WMCore/issues/7199 https://github.com/dmwm/WMCore/issues/7194 agents components are down

**Comment by amaltaro** [comment]
Yes, couch should be stable. I restarted those components that were down. From now on, I leave it to the WF team again.
