### ISSUE TITLE
Exit code 99303 to be more informative

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7203]
Looks to me that the error message could be more informative of the location of the error.
Looks like the job exited properly in condor, but the agent is enable to complete the post-processing : getting the JobReport.*.pkl which might have failed to transfer back due to routing issue. 
It looks as if we should be able to get more informative information. Like "job succeeded but I cannot get the pkl file" or "job status was X, and no pkl file"

**Comment by ticoann** [comment]
This is how condor status is mapped to Agent job status.
If Complete mean Success we can add that information. (Basically all 99303(4) means successful jobs but no fwjr - still we need to fail this job since we don't have fwjr) 
But I am not sure whether Complete means success. or it could be success or fail.

{'New': 'Pending',
 'Idle': 'Pending',
 'Running': 'Running',
 'Removed': 'Running',
 'Complete': 'Complete',
 'Held': 'Error',
 'Error': 'Error',
 'Timeout': 'Error',
 'Unknown': 'Error'}

**Comment by vlimant** [comment]
is it possible to print the actual job directory in the schedd/agent, a condor job id, anything that can help

**Comment by amaltaro** [comment]
As I told you over gtalk, this is the current procedure for any job debugging:
1. look at wmstats
2. look at the logArchive
3. look at the condor logs in the agent (either under JobCreator or JobArchiver, depending on the job status)
 3.a. you need the `wmbs_id` and the `agent` name from the wmstats job log, with that, you can find the condor logs.
4. condor_ssh_to_job and watch the logs in live jobs

**Comment by vlimant** [comment]
thx for the procedure. can 1.2.3.4 be exposed in wmstats error report

**Comment by jenimal** [comment]
If what I'm seeing Alan saying is correct, we need to catch it in a job that is still running "watch the logs in live jobs" not in jobs that have already exited out with exit code 99303

So For this particular batch, we are just going to let them run and see what we get out?

Jen

**Comment by vlimant** [comment]
So far, the agent job directory contains the pkl that is said to not exists : puzzle 1 for developpers
(likely it came after the agent tried to do something about it)
What wmstats reports in terms of site is just funky and unreliable : that need to be fixed somehow by updating the jobs before trying to complete it (60 secs cycle that Alan mentioned in HN)

It all traces back so far to IRFU taking jobs and failing them within seconds, and this get reported to any site in the whitelist ; so everywhere, even though it's really only IRFU : @prozober took IRFU to drain already.

**Comment by jenimal** [comment]
So how did you determine that the site that was failing was IRFU?  They aren't even showing up on dashboard.

**Comment by jenimal** [comment]
IRFU is in drain, but no ticket was opened.  Gaston has contacted their site support directly, but a ticket should really be opened so we have a way of tracking this issue, and a summary of what is going on should be posted to elog so the people who are supporting the system know it's already been adressed and can use their time and efforts looking at other things.  If we don't communicate to the entire group we end up with people trying to solve the same problem, that was already looked at on the next shift.

**Comment by ticoann** [comment]
FYI, Jean-Roch point out some weird case (Just for debugging purpose I am adding comments here)

wmstats has follwing job with exit code 99033

https://cmsweb.cern.ch/couchdb/_utils/document.html?wmstats/169818b4-7d6f-11e6-ab5c-002590494c06-737

```
 "_id": "169818b4-7d6f-11e6-ab5c-002590494c06-737",
   "_rev": "12-9cb52af92b58332241dcbf2bd9364bf3",
   "agent_name": "vocms0303.cern.ch",
   "site": "T2_CH_CERN",
   "cms_location": {
   },
   "outputdataset": null,
   "inputfiles": [
   ],
   "errors": {
       "NoJobReport": [
           {
               "details": "Could not find jobReport\nAdding end of condor.log to error message:\n<c>\n\n    <a n=\"MyType\"><s>SubmitEvent</s></a>\n\n    <a n=\"SubmitHost\"><s>&lt;128.142.35.227:4080?addrs=128.142.35.227-4080+[--1]-4080&amp;noUDP&amp;sock=9131_f0fa_15&gt;</s></a>\n\n    <a n=\"Proc\"><i>1</i></a>\n\n    <a n=\"Cluster\"><i>29355</i></a>\n\n    <a n=\"EventTime\"><s>2016-09-20T08:35:11</s></a>\n\n    <a n=\"Subproc\"><i>0</i></a>\n\n    <a n=\"EventTypeNumber\"><i>0</i></a>\n\n</c>\n\n<c>\n\n    <a n=\"Proc\"><i>1</i></a>\n\n    <a n=\"TriggerEventTypeName\"><s>ULOG_SUBMIT</s></a>\n\n    <a n=\"EventTime\"><s>2016-09-20T08:35:11</s></a>\n\n    <a n=\"EnteredCurrentStatus\"><i>1474353311</i></a>\n\n    <a n=\"ExtDESIRED_Sites\"><s>T2_CH_CERN</s></a>\n\n    <a n=\"SubmitHost\"><s>&lt;128.142.35.227:4080?addrs=128.142.35.227-4080+[--1]-4080&amp;noUDP&amp;sock=9131_f0fa_15&gt;</s></a>\n\n    <a n=\"QDate\"><i>1474353311</i></a>\n\n    <a n=\"TriggerEventTypeNumber\"><i>0</i></a>\n\n    <a n=\"WMAgent_JobID\"><i>1103592</i></a>\n\n    <a n=\"MyType\"><s>JobAdInformationEvent</s></a>\n\n    <a n=\"Cluster\"><i>29355</i></a>\n\n    <a n=\"JobStatus\"><i>1</i></a>\n\n    <a n=\"Subproc\"><i>0</i></a>\n\n    <a n=\"EventTypeNumber\"><i>28</i></a>\n\n    <a n=\"DESIRED_Sites\"><s>T2_CH_CERN</s></a>\n\n</c>\n",
               "type": "NoJobReport",
               "exitCode": 99303
           }
       ]
   },
   "state": "jobfailed",
   "exitcode": 99303,
   "acdc_url": "https://cmsweb.cern.ch/couchdb/acdcserver",
   "type": "jobsummary",
   "workflow": "pdmvserv_PPD-RunIISpring15PrePremix-00002_00011_v0_PUMoriond17_160914_201757_9380",
   "timestamp": 1474394738,
   "lumis": [
   ],
   "wmbsid": 1103592,
   "retrycount": 3,
   "task": "/pdmvserv_PPD-RunIISpring15PrePremix-00002_00011_v0_PUMoriond17_160914_201757_9380/Production",
   "output": [
   ],
   "jobtype": "Production",
   "state_history": [
       {
           "newstate": "jobcooloff",
           "oldstate": "jobfailed",
           "location": "T2_US_Wisconsin",
           "timestamp": 1474185707
       },
       {
           "newstate": "jobcooloff",
           "oldstate": "jobfailed",
           "location": "T2_US_Wisconsin",
           "timestamp": 1474190033
       },
       {
           "newstate": "jobcooloff",
           "oldstate": "jobfailed",
           "location": "T1_RU_JINR",
           "timestamp": 1474330556
       },
       {
           "oldstate": "jobfailed",
           "newstate": "jobfailed",
           "location": "T2_CH_CERN",
           "timestamp": 1474394738
       }
   ]
}

```

But actual fwjr contains exitcode
http://vocms0303.cern.ch:5984/_utils/document.html?wmagent_jobdump%2Ffwjrs/1103592-2

```
"cmsRun1": {
               "status": 1,
               "logs": {
               },
               "stop": null,
               "site": "T2_US_Wisconsin",
               "input": {
               },
               "errors": [
                   {
                       "details": "\n Adding last ten lines of CMSSW stdout:\nWARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.\nWARNING: There already exists /var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMTaskSpace/cmsRun1/CMSSW_8_0_20 area for SCRAM_ARCH slc6_amd64_gcc530.\n/var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh: line 78: 3110746 Aborted                 $EXECUTABLE -j $JOB_REPORT $CONFIGURATION 2>&1\nCmsRunFailure\nMessage: Error running cmsRun\n{'arguments': ['/bin/bash', '/var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc530', 'scramv1', 'CMSSW', 'CMSSW_8_0_20', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}\nReturn code: 134\n\n\tModuleName : WMCore.WMSpec.Steps.WMExecutionFailure\n\tMethodName : __init__\n\tClassInstance : None\n\tFileName : /var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py\n\tClassName : None\n\tLineNumber : 18\n\tErrorNr : 134\n\nTraceback: \n\n",
                       "type": "CMSSWStepFailure",
                       "exitCode": 134
                   },
                   {
                       "details": "Error reading XML job report file, possibly corrupt XML File:\nDetails: no element found: line 1, column 0",
                       "type": "BadFWJRXML",
                       "exitCode": 50115
                   },
                   {
                       "details": "Adding extra error in order to hold error report\n\nAdding last ten lines of CMSSW stderr:\nWARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.\nWARNING: There already exists /var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMTaskSpace/cmsRun1/CMSSW_8_0_20 area for SCRAM_ARCH slc6_amd64_gcc530.\n/var/condor/execute/dir_3364649/glide_5NqmPN/execute/dir_3109906/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh: line 78: 3110746 Aborted                 $EXECUTABLE -j $JOB_REPORT $CONFIGURATION 2>&1\n",
                       "type": "ErrorLoggingAddition",
                       "exitCode": 99999
                   }
               ],
```

**Comment by ticoann** [comment]
One thing I am wondering is whether there is race condition between Complete job status and fwjr creation. 
Here is my theory.

1. JobTracker tracks jobs using condor query. If Job is in Complete status it try to read the fwjr. If fwjr report doesn't exist it fails the job with 99303(4) error (also checks condor log) and create fwjr with agent message
2. But it seems fwjr comes back later overwrites fwjr report agent generates.

I need to check whether WMStats report and fwjr upload to couch happens in different time.
But briefly looking at it seems it happens at the same time.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L430

**Comment by vlimant** [comment]
@jenimal I told Poala to drain IRFU and https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3214/1/1/1/2/1/1.html because it's highly likely to be workflow related, there isn't reason to bug sites.
Paola is aware and that's all matters since she is the WTC.
Use your time and effort to what we asked you to do.
Gaston et al can follow up on site-support GGUS tickets already opened for real issues.

**Comment by ticoann** [comment]
@vlimant, Jean-Roch do you have more example with  exit code 99033 but actually fwjr exist?

**Comment by jenimal** [comment]
@vlimant  just trying to improve proceedures.  If we want OS and CSP to notice and report site issues we need to know how people are spotting more obscure cases like this, where it was really one site reporting everywhere as failing.  And Site Support can't follow up on issues if we put sites in drain and doing open tickets.  I know Gaston spent some time, and went up and looked with Stephon as well trying to find out who./why the site was put into drain.  With the amount of email and ticketing systems we have we have to make sure proceedures are written so that things are properly reported and people don't need to hunt down why a site was put into drain.

**Comment by vlimant** [comment]
improving procedure,  that's the spirit !

**Comment by vlimant** [comment]
@amaltaro @ticoann the amount of error 99303 is very high and will make the recovery process very complicated. you may raise this GH to "Urgent Ops".

The combination of
https://cmst2.web.cern.ch/cmst2/unified/report/pdmvserv_TOP-RunIISummer15wmLHEGS-00049_00159_v0__160919_161931_3234
and
http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=&submissiontool=&application=&activity=&status=&check=submitted&tier=&date1=2016-08-26+11%3A28&date2=2016-09-25+12%3A28&sortby=appexitcode&scale=linear&bars=20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=wmagent_pdmvserv_TOP-RunIISummer15wmLHEGS-00049_00159_v0__160919_161931_3234&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

 shows that 8001 does not get reported all the way to the agent (while it used to be). So something must be very wrong and we cannot look at wmstats reliably anymore.

**Comment by amaltaro** [comment]
99303 is `NoJobReport`, that makes me think there shouldn't be any other error reported. Do you have any case with 8001 exit code right now?

Seangchan and I are planning to rework these errors reported and possible show only one exit code/error. Though this will likely be done for November cycle, at best.

**Comment by ticoann** [comment]
Hi Jean-Roch, I see 2 different problems here.
1.  dashboard and wmstats showing different error code. Even though there are actually the same error. (I think it is due to that errors wrapped different error while it bubbles up. - maybe I am wrong we will look more detail.)
2.  WMStats job error report is different from fwjr in agent. - This is puzzled me more and I have no explanation. I thought there could be uuid collision but I check all the agent and wasn't the case.  Do you notice any other case than your first example for this?

FYI. 99303 - NoJobReport would still have job report which created by agent including only 99303 error message.
However with 99303 there shouldn't be condor.log reported. Do you know any other cases with error code 99303 but condor.log exits?  I think that was the case first example you gave me.

**Comment by bbockelm** [comment]
Hi,

Looking at the code and the output from the condor log above -

Seems that the submit event was the last one recorded by condor - note that there is no actual execute, complete, or remove event.

Is it possible that the agent thought it was removed but HTCondor was never actually told to remove it?  The agent then generated a 99303, but HTCondor continued on anyway?

Looking in Kibana, I have the job recorded as finishing CMSSW about 3 hours after WMAgent recorded it as failed:

http://hcc-metrics.unl.edu/app/kibana?#/doc/cms-*/cms-2016-09-20/job?id=vocms0303.cern.ch%2329355.1%231474353311&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))

Then,  the job went on hold with the following:

```
	Error from slot1@glidein_12166_768054896@b65fa51b3b.cern.ch: STARTER at 188.184.144.247 failed to send file(s) to <128.142.35.227:4080>; SHADOW at 128.142.35.227 failed to write to file /data/srv/wmagent/v1.0.19.patch1/install/wmagent/JobCreator/JobCache/pdmvserv_PPD-RunIISpring15PrePremix-00002_00011_v0_PUMoriond17_160914_201757_9380/Production/JobCollection_123727_0/job_1103592/condor.29355.1.err: (errno 2) No such file or directory
```

Which makes sense - the agent cleaned up the output directory hours earlier, so HTCondor couldn't write its outputs.

So - if you want to clear this up, I would start looking at the job removal code paths.

Brian

**Comment by bbockelm** [comment]
@ticoann - I can confirm that the FJR you quote above belongs to a previous run of the same WMAgent job (but different HTCondor ID), from a few days earlier than the one that got 99303:

http://hcc-metrics.unl.edu/app/kibana?#/doc/cms-*/cms-2016-09-18/job?id=vocms0303.cern.ch%2327054.65%231474195296&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))

**Comment by bbockelm** [comment]
Looking further, it might not actually be _removing_ jobs but some other mechanism for the agent to lose track.

Looking at the code, `MATCH_EXP_JOBGLIDEIN_CMSSite` is required for `readCondorLog` (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L1028) to work.  This is very unreliable:
* `MATCH_EXP_JOBGLIDEIN_CMSSite` is only available for running or terminated jobs.  Removed, held, and idle jobs may not get this information.
* I'm tracking down a condor job that causes `MATCH_EXP_JOBGLIDEIN_CMSSite` to be missing for around half of jobs anyway.

**Comment by amaltaro** [comment]
Thanks for looking at it, Brian.

About `readCondorLog`, we're actually removing it completely since we manage to retrieve info from the logs for less than 10% of the jobs, see:
https://github.com/dmwm/WMCore/pull/7210

> I'm tracking down a condor job that causes MATCH_EXP_JOBGLIDEIN_CMSSite to be missing for around half of jobs anyway.

I didn't get your point. Did you mean "tracking down a condor bug that causes..."? For half of the running job lifetime?

**Comment by bbockelm** [comment]
Poking through the condor code and doing some test examples -

`MATCH_EXP_JOBGLIDEIN_CMSSite` is never sent to the running shadow.  It's persisted in the schedd ad, but only the `JOBGLIDEIN_CMSSite` portion goes to the shadow - meaning this attribute will never be recorded in the user log _unless_ the job has been already retried once.  In that case, the job will get the value from the _previous_ job run.

So, at least in the current HTCondor code, `readCondorLog` is going to be missing in most cases and, when it is present, it's usually going to be incorrect (unless the job executed multiple times at the same site).

**Comment by bbockelm** [comment]
Ok, I think I figured this out.

Here's the culprit:

https://github.com/dmwm/WMCore/blob/b06fea845524a910522a077dc46d0d312d6b31e7/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L1007

Despite the comment there, it's actually perfectly normal for a job to be in `Running` state without `JobStartDate` set.  This simply means that the job has been recently matched to a startd, but we haven't heard a message back from the startd that the process has actually been launched.  The more work there is for the schedd - such as lots of short jobs, what `0303` is seeing currently - the more likely you'll see this occurring.  Just doing the appropriate query by hand, I can easily catch jobs in this state.

Anyhow, if the JobStatusLite component catch the jobs in this state, then it will fall back to the condor job log mechanism.  As discussed in #7210, it's extremely unlikely the condor job log mechanism will work.  Hence, the job gets marked as complete https://github.com/dmwm/WMCore/blob/b06fea845524a910522a077dc46d0d312d6b31e7/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L1111

However, the job still lives in HTCondor and continues to execute.

The fact that the sample log from @ticoann indicates the job had been submitted - but not executed - is further evidence that the job was in this state.

**Comment by vlimant** [comment]
great stuff !

**Comment by ticoann** [comment]
@bbockelm, Thank you very much Brian for investigating the problem.
@amaltaro, Alan There is still second problem. (now wmstats document seems to be deleted)

> 2. WMStats job error report is different from fwjr in agent. - This is puzzled me more and I have no explanation. I thought there could be uuid collision but I check all the agent and wasn't the case. Do you notice any other case than your first example for this?

These are the places updates fwjr in agent and job summary report in wmstats respectfully.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L343

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L426

It uses the same fwjr so it should have at least the same content but that wasn't the case.

**Comment by bbockelm** [comment]
Hi @ticoann -

Obviously the FJR is from the prior run of the same job at Wisconsin - job details and timestamps line up.

Is it possible that there was a transient failure in uploading the new document?   I recall network issues that day.

Brian

**Comment by ticoann** [comment]
Thank you very much Brian for investigating, I think that could happen (transient failure), however it seems it commits job reports to fwjr db first then to wmstats db. So it would make more sense if fwjr db has the latest data.

**Comment by bbockelm** [comment]
Yes - that is indeed mysterious.

However, since I'm not very familiar with this part of the system, I'm afraid I can't really do more than speculate :/

**Comment by vlimant** [comment]
when can we have something over in production ? 
there are plenty of errors which do not get reported correctly (there should not be error in the first place, that we agree ...) and makes it hard to trace things down

**Comment by ticoann** [comment]
Alan just finished the test. We will patch production agent tomorrow.

**Comment by amaltaro** [comment]
Production agents were patched yesterday afternoon with #7225 If these failures are still happening with timestamp starting from yesterday evening, then it's likely that there is another issue.

**Comment by vlimant** [comment]
Hi Guys, we are having a lot of 99303 on newly running workflows
https://cmsweb.cern.ch/reqmgr/view/details/pdmvserv_BPH-RunIISummer15GS-00086_00434_v0__160930_155823_6867
acquired on Sept 30.
Do we have to clone all workflow acquired prior to the patch ?

**Comment by jenimal** [comment]
FYI - we had a spike in 99303's over the weekend:
https://cmsweb-testbed.cern.ch/wmarchive/web/performance?metrics[]=jobstate&axes[]=host&axes[]=jobstate&axes[]=site&axes[]=exitCode&axes[]=workflow&start_date=20170126&end_date=20170201&exitCode=99303

Seems to have gone away again.  Paola says she can recover with plain ACDC, but something to keep an eye on.
