### ISSUE TITLE
Data location inconsistency between job logs and wmstats

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7217]
@vlimant was asking me about a very weird case where wmstats reports that a job was running at T2_US_Nebraska (failed job) while the condor logs in the agent vocms0303 reports that this job ran at T1_US_FNAL (notice it's the first attemp, so retry 0).

I forgot to add a link to a wmstats screenshot and a tarball of this job, from the JobCreator:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7217/

@ticoann do you have any idea of what can have happened?

**Comment by vlimant** [comment]
you're going to need to put more information ;-)

**Comment by amaltaro** [comment]
Daahh, I've just updated the description with logs/links

**Comment by ticoann** [comment]
wmstats document has different location than

https://cmsweb.cern.ch/couchdb/_utils/document.html?wmstats/07519492-8103-11e6-939f-002590494c06-689

wmagent document
http://vocms0303.cern.ch:5984/_utils/document.html?wmagent_jobdump%2Ffwjrs/1440091-0

I suspect that Nebraska was the originally picked by the agent when it gets to submitted and if failed fast so job tracker misses the location update or there could be the race condition between job tracker and error handler.

Created the patch #7218, please review.

**Comment by amaltaro** [comment]
I'm not sure that is the real problem. This job seems to have run for almost 2h.

**Comment by ticoann** [comment]
Where can I find the job running time. Is that from Running status to Complete/Removed status in condor. 
If you compare the document between wmstats and wmagent only difference is the site. although even in wmstats doc has correct site in cms_location property which gets directly from fwjr

**Comment by amaltaro** [comment]
Stop asking questions, it's Friday evening :) I don't think the "length" of the job is correct in the bossair db, instead I took a look at the condor log, e.g.:
```
WMAgent bootstrap : Fri Sep 23 05:29:51 UTC 2016 : WMAgent is now running the job...
...
WMAgent bootstrap : Fri Sep 23 07:03:01 UTC 2016 : WMAgent is finished. The job had an exit code of 0 
```

**Comment by ticoann** [comment]
You need to stop anwsering. :smile: And I don't expect to get this reply until next week. :-)
What really matters is the time between bossAir Running status and Complete status. that is the window of time whether it defined where we can miss jobs or track jobs. If it recorded in running status close to when it finished we still might miss the the status change although if it is 1 1/2 hours it is unlikely to do that considering JobTracking polling cycle. 
One other weird thing is why it says exit code 0, this job was failed isn't it?
