### ISSUE TITLE
add Campaign in fwjr - for wmarchive update.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7219]
@amaltaro, Alan is there any other information would be needed (PrepID, etc)

**Comment by amaltaro** [comment]
PrepID and Campaign, for sure. Nothing else comes to my mind at the moment.

**Comment by ticoann** [comment]
The place we can stick this in is within this loop. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L304

Since we don't keep the campaign/prepid in db, following options we can consider.

1. create the new wmbs table and insert that information in when wmbs_workflow table is popluated in wq then retrieve thought the db call
2. querey reqmgr2 and get the campaign, etc information
3. load spec information from wmbs_workflow table which contains spec file location.
   since we know the task as well as workflow name the query will be 
   ```
    select spec from wmbs_workflow where task=blah
    or
   select spec from wmbs_workflow where name=blah  
   ```

for 2, 3, we have to keep the memory cache so we don't call this for all the jobs.
(I don't know how many workflows will be handled within the life cycle of the agent but we limit the cache size  ~3000.
For me, option 3 is preferable since we don't need schema change or worry about the network glitch although it might be slow to load pickle file but using cache will reduce that problem.

What do you think?

**Comment by amaltaro** [comment]
I think 3 is the best choice, it's a bit expensive for too many jobs but still better than 2.
3000 workflows in the cache would be likely enough. How would it look like?
{workflow1: {task1: {campaing: X, prepid: Y}, task2: {etc}}, workflow2:...}

**Comment by amaltaro** [comment]
Another option would be using `dbsbuffer_dataset` table. It already has the `prep_id` column, we would have to add `campaign` though. It would be faster, but it's not clear how we would query it in this case, we'd likely have to convert the LFNs inside the FJR to a dataset and then perform the lookup.

**Comment by ticoann** [comment]
> I think 3 is the best choice, it's a bit expensive for too many jobs but still better than 2.
> 3000 workflows in the cache would be likely enough. How would it look like?
> {workflow1: {task1: {campaing: X, prepid: Y}, task2: {etc}}, workflow2:...}

Could each task can have different campaign or prepid? I thought one campaign per one workflow.

**Comment by amaltaro** [comment]
`Campaign` is a single parameter for the whole workflow. However, TaskChain accepts different `PrepID` for different tasks:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L309

**Comment by alexanderrichards** [comment]
I'll user the cache that @ticoann provides at:

[WMCore.Cache.GenericDataCache.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Cache/GenericDataCache.py)

**Comment by ticoann** [comment]
test this please
