### ISSUE TITLE
Access to condor logs

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7224]
As we discussed with @juztas @vlimant and this hypernews [https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3207.html], this requires wider communication and this can be reported on Monday meeting and discussed. Here are the steps which needs to be done if people agree. Also, this is just my suggestion, please feel free to accept it, ignore, modify...

Cheers,
Justas

[1]
a) Modify JobArchiver that whenever it tarballs condor*{err,out,log} files, it does not remove them, but moves to new location, which is defined in WMAgent configuration. Keep directory structure the same as JobCache, which would allow easily to map on Brian's ES, WMStats, Dashboard.
b) For wmagent puppet configuration reuse CRAB code for HTTP and cleanup script. Cleanup script is just simple cronjob with controlled date. Lets say keep last 30days in beginning and lare can be modified depending on the usage.
c) Get additional 1TB mounted for each schedd. Just to make sure that in case there are huge IO read for logs, it does not interfere with mounted volume where WMAgent or Schedd is running.
d) Rewrite rules in cmsweb, that it allows to access it from outside CERN. This will make sure that all users are authenticated and have certificate available. Now URL could be for example: https://cmsweb.cern.ch/prodlogs/vocms0303/taskname.../.../../../
e) Report to dashboard for each job a location to log file.
f) Start to improve the logging and what information it keeps.

P.S. Problem which I foresee is FNAL schedds, but this also could be solved, but would require FNAL people to open a port 80 to all cmsweb machines.

If an agreement is found, I volunteer myself for a and e, if you need help. For b, c, d there are a lot of people in CatA's office who know all details and can make it good and f is just longer term and would improve in time.

**Comment by juztas** [comment]
@amaltaro @ticoann comments?

**Comment by amaltaro** [comment]
We discussed this issue in the last WMAgent meeting and we'd like to explore an approach like what we have in CrabCache (something like a dropbox).

The idea would be to upload the wrapper logs to this area in cmsweb and report the url for these logs in wmstats and dashboard. 

Of course we cannot upload every single log to cmsweb, so the initial idea would be to upload a few logs (5?) for `cooloff` or `failed` jobs only, for each set of `workflow` + `agent` + `task` + `site` + `exitcode`.

**Comment by amaltaro** [comment]
@ticoann @vkuznet after our discussion on this topic  - in the WMAgent meeting yesterday - I talked to Todor and he confirmed these logs are accessible from anywhere (including outside cern).

I then asked Daniel to set this up in vocms0230, such that we can have a feeling on how it will work (Justas' approach) and if we're happy with that, we push it to the other agents.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Access to condor logs](https://trello.com/c/uqtVwMKI/19-access-to-condor-logs)

**Comment by thongonary** [comment]
FYI @ticoann

**Comment by ticoann** [comment]
superseed by #8442
