### ISSUE TITLE
Input files in wmstats report

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7243]
Hi guys,
We need the agents to report what input file was read and include that information in the wmstats report. That way we can make the whole list errors and decide what to do.
Thanks.

**Comment by juztas** [comment]
Just to add, as we talked with @vlimant also would be good to add this into job classads:
```
INPUT_FILES = "/store/data/Run2016B/DisplacedJet/RAW/v2/000/274/157/00000/DE308367-FE24-E611-A134-02163E011A12.root,N+1, N+2, N..."
INPUT_EVENTS = "6479,N+1,N+2, N..."
INPUT_FirstEvent = "0,N+1,N+2, N..."
INPUT_LastEvent = "0,N+1,N+2, N..."
INPUT_LumiCount = "10,N+1,N+2, N..."
INPUT_Sizes = "4270814155,N+1,N+2, N...
```
And also the block name, which job is analyzing.

**Comment by amaltaro** [comment]
@juztas please don't mix different features/requirements.

@prozober reporting the list of input files to wmstats is going to make it 10x slower. Since the list of files can be very very big for some job types. Can you please provide your use case in details?

**Comment by ticoann** [comment]
closing it now unless there is a specific use case.
