### ISSUE TITLE
MergedLFNBase not in wf cache

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7245]
while https://cmsweb.cern.ch/reqmgr/reqMgr/request?requestName=prozober_ACDC_Run2016B-v2-DoubleEG-23Sep2016_8020_160930_083057_1518 has it
but
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/prozober_ACDC_Run2016B-v2-DoubleEG-23Sep2016_8020_160930_083057_1518 does not
neither does
https://cmsweb.cern.ch/reqmgr2/data/request?name=prozober_ACDC_Run2016B-v2-DoubleEG-23Sep2016_8020_160930_083057_1518
#6602 ?

we need that value, passed from the original request to the clone and acdc at assignment time.
I'll see if I can find something.

**Comment by amaltaro** [comment]
fixed by #7329
