### ISSUE TITLE
Set T0 workflows activity to "t0"

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7256]
As mentioned here #7253
Several dashboard activities are mapped to `t0`. So we should update it from `tier0` to `t0` in the T0 specs here and in the T0 repository as well. No hurry though

**Comment by hufnagel** [comment]
@amaltaro , can you suggest where exactly in the Tier0 specs this should be changed ?

**Comment by amaltaro** [comment]
First change (replace tier0 by t0 activity) should be in the setDashboardActivity call, thus:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/PromptReco.py#L34

same for Express and Repack.

Second change is, if Tier0Feeder is now calling this workload method (as we discussed a week or two ago, which basically updates the workload object and calls a bunch of setter methods - used for wf assignment):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1633

then you need to pass the t0 value for `Dashboard` key.
