### ISSUE TITLE
Update unittest deployment procedure

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7261]
As discussed with @ericvaandering , there is a problem with the last pkgtools transition and the unittest deployment needs to be updated. Basically to find the latest RPM in cmsrep.

I already talked to @BrunoCoimbra  and he'll have a look at it.

**Comment by ericvaandering** [comment]
Assuming you pointed Bruno at the script we discussed?

**Comment by amaltaro** [comment]
Yep, here it goes again:
https://github.com/dmwm/WMCore/blob/master/test/deploy/deploy_unittest.sh#L16

**Comment by BrunoCoimbra** [comment]
Hey guys, I've just created a PR with a proposed solution.

**Comment by amaltaro** [comment]
Fixed, thus closing it
