### ISSUE TITLE
ACDC stuck in acquired

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7277]
Hey guys,
This ACDC seems to be stuck in acquired https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC_Run2016C-v2-FSQJets-23Sep2016_8020_161005_103019_6519
The input and site whitelist match. The workflow hasn't reached any agent.
Could you please help us to figure out what is going on?
Thanks.

**Comment by vlimant** [comment]
@prozober given that Florida is the only site it can run at and it's packed already with higher-older priority work. It has reached vocms0311.cern.ch
IMO we should be doing ACDC/recovery at x10 priority

**Comment by vlimant** [comment]
I raised the priority to 900k and if it does not get submitted we will have a problem.

**Comment by ticoann** [comment]
Hi Paola, you can use the script to check the status. (Although it will show only one agent status) (I ran this before Jean-Roch increase the priority) which tells you there is no slot left in Florida)

cmst1@vocms0303:/data/srv/wmagent/current $ $manage execute-agent check-request-wq-status -s Acquired -r prozober_ACDC_Run2016C-v2-FSQJets-23Sep2016_8020_161005_103019_6519
```
### summary for prozober_ACDC_Run2016C-v2-FSQJets-23Sep2016_8020_161005_103019_6519 ###
  Prioty: 90000, available elements: 1 
  Possble sites to run: [u'T2_US_Florida']
  Higher priority elements: 0, total available jobs: 0
Possible sites for the request prozober_ACDC_Run2016C-v2-FSQJets-23Sep2016_8020_161005_103019_6519
T2_US_Florida: {'priority': {85000: 1199, 90000: 824}, 'total jobs created': 2023, 'slots': 820.0}
Get available work from LQ for job creation
Resource is full no jobs will be created by this WMAgent
```

Anyway, it seems jobs are running now.

**Comment by ticoann** [comment]
I am closing the issue. You can reopen it if you still have problems.

**Comment by prozober** [comment]
Thanks Seangchan!
