### ISSUE TITLE
Inconsistencies for Rerecos

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7280]
Hi guys,
We are seeing some inconsistencies with the WMStats' report for Rerecos.
1. e.g. this Rereco request had some failures. This is the report we get from WMStats https://cmst2.web.cern.ch/cmst2/unified/report/cerminar_Run2016D-v2-MET-23Sep2016_8020_160926_170045_4728.
2. The workflow had errors in the DataProcessing task. We expected to see some missing lumis for all output datasets.
3. Instead, there are only missing lumis for MINIAOD, https://cmst2.web.cern.ch/cmst2/unified/datalumi/lumi.ReReco-Run2016D-23Sep2016-0010.html.

Is this coherent?
Thanks for your help.

**Comment by vlimant** [comment]
wmstats table itself does not show any error on dataprocessing.
However 
http://cmsweb.cern.ch/wmstatsserver/data/jobdetail/cerminar_Run2016D-v2-MET-23Sep2016_8020_160926_170045_4728

does 
"""
    "/cerminar_Run2016D-v2-MET-23Sep2016_8020_160926_170045_4728/DataProcessing": {
      "jobfailed": {
        "71304": {
          "T2_DE_RWTH": {
            "errorCount": 1, 
            "samples": [
              {
                "agent_name": "vocms0310.cern.ch", 
                "inputfiles": [], 
                "errors": {
"""

so the matter is to have data/jobdetail report the right thing

**Comment by amaltaro** [comment]
Hi Paola,
> 1. e.g. this Rereco request had some failures. This is the report we get from WMStats https://cmst2.web.cern.ch/cmst2/unified/report/cerminar_Run2016D-v2-MET-23Sep2016_8020_160926_170045_4728.

no longer available.

> 2. The workflow had errors in the DataProcessing task. We expected to see some missing lumis for all output datasets.
3. Instead, there are only missing lumis for MINIAOD, https://cmst2.web.cern.ch/cmst2/unified/datalumi/lumi.ReReco-Run2016D-23Sep2016-0010.html.

That's not true, there are missing lumi sections in all datatiers. As I'd bet, if there is a DataProcessing failure, then you miss those lumi sections for all output datatiers.

The real cause for the missing MergeMINIAOD is the robust merge that was triggered for those 2 jobs (honestly I didn't look at the logs, but I'm sure that was the reason).

I'm not sure these jobs are supposed to show up in the jobdetail api though.

The next WMA will report a summary of what was skipped, when robust merge is triggered.

Can we close this issue?

**Comment by vlimant** [comment]
[error.pdf](https://github.com/dmwm/WMCore/files/529678/error.pdf)

**Comment by amaltaro** [comment]
Closing it for being inactive for longer than 2 years. If the issue reappears, we can reopen and follow it up.
