### ISSUE TITLE
Incorrect Memory value inherited for ACDC (TaskChain)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7285]
It requires further investigation, however running a ACDC for
amaltaro_TaskChain_RelVal_Multicore_Agent1021_Validation_161007_234412_2447

in testbed, for the second task (RECODreHLT). I see it has memoryRequirements 4000 instead of 8000. 

It's likely inheriting the value from the main dict instead of the task one...

**Comment by vlimant** [comment]
#7132 ?

**Comment by amaltaro** [comment]
That's override. This issue is about inheritance.

**Comment by prozober** [comment]
Related to https://its.cern.ch/jira/browse/CMSCOMPPR-429, we rejected and cloned this taskchain https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer16DR80-00028__v1_T_170123_105858_4269 , but memory values are different for every task.
Could this be related to this issue?

**Comment by amaltaro** [comment]
Paola, this case is different. You're cloning a request and (trying) to override the Memory value in your clone. The problem is, you write the new value only to the top level dict, the task dict always has precedence over the top one, thus jobs are created with the memory defined in each task.
