### ISSUE TITLE
WMStats not reporting failures

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7291]
Hi guys, 
I have seen for some MonteCarlo workflows (in completed), WMStats did not report any failures.
e.g. https://cmst2.web.cern.ch/cmst2/unified/report/pdmvserv_HIG-RunIISummer15wmLHEGS-00473_00179_v0__161004_161815_8368
no errors but still 
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_HIG-RunIISummer15wmLHEGS-00473_00179_v0__161004_161815_8368%22&include_docs=true&reduce=false
The workflow ran in vocms0308. Could be related to the JobAccountant going down in this agent?
Thanks.

**Comment by amaltaro** [comment]
It seems this is being caused by the last changes to read the condor.out and condor.err (instead of log). It's getting some data that cannot be decoded with utf8... Still investigating though..

**Comment by ticoann** [comment]
Actually, as Alan found out #7295, It is due to the error message containing non json decodable string. It is not directly due to the patch but since we are retrieving more information from the log. I think it is more visible now.
Production agents are patched with temporary fix. So it should report to wmstats from now on.
FYI,  @prozobe, @vlimant

**Comment by amaltaro** [comment]
Paola, can you check whether wmstats is reporting the failures now? If so, then please close this issue.

As mentioned yesterday, what was not uploaded to wmstats is lost now, but any failures that happened from last Saturday on should get reported in wmstats.

**Comment by prozober** [comment]
Probably this Rereco fits here https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016G-23Sep2016-0001.
No failures reported for DataProcessingMergeMINIAODoutput task, but https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22cerminar_Run2016G-v1-MuonEG-23Sep2016_8020_160926_173545_5210%22&include_docs=true&reduce=false

**Comment by amaltaro** [comment]
This workflow completed a day after the agents were patched, so very likely this job ran before that time.

**Comment by ticoann** [comment]
@prozober, can we close this one?

**Comment by prozober** [comment]
Hi Alan, I think I've found a workflow not reporting failures in WMstats https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=SMP-RunIISummer15wmLHEGS-00035.
- WMStats reports failures only for Production and ProductionMergeLHEoutput tasks.
- However, there are failures for ProductionMergeRAWSIMoutput https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_SMP-RunIISummer15wmLHEGS-00035_00197_v0__161018_201807_4660%22&include_docs=true&reduce=false

**Comment by amaltaro** [comment]
It was robust merge, they are not reported.

You'll get these reported from the new agents, the `L` grey button in wmstats will get red and it will provide a summary of files/lumis skipped. I think that will get propagated also in the jobDetail API

**Comment by prozober** [comment]
Thanks Alan. I think we can close this issue.
