### ISSUE TITLE
Log Collect jobs showing as "failed" with exit code 0

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7308]
In the past we have largely ignored log collect jobs that failed.  But lately we've had a lot of workflows that are showing 100% failure for LogCollect, both in Dashboard and in WmStats, but they have the exit code of "0".  Site support has pointed out it's likely caused by a delay in reporting from the batch system, but it makes for lots of false leads on failing work when attempting to debug running workflows.

Here is an example workflow:
vlimant_BPH-Summer12-00228_00270_v0__161005_224414_1220

There are on the order of 2000 failed log collect's reported in WmStats.  But if you look there are 80 submit failures, and the rest all have a return exit code of 0.

Jen

**Comment by hufnagel** [comment]
@amaltaro , isn't that just the known LogCollect stageout problem ?

**Comment by amaltaro** [comment]
Yes, of course a failed job with exit code 0 is another problem. But honestly, since it's fixed in the new agent that should start rolling in in the next week, I'd rather not invest time to fix this issue.

**Comment by jenimal** [comment]
Will it clear the issue for both Dashboard and WmStats?  If so I will patiently wait and for now just continue to tell OS and CSP to  ignore LogCollect Failures.

**Comment by amaltaro** [comment]
Yes, it should.

**Comment by amaltaro** [comment]
All the old agents have 0 jobs and this issue shouldn't have cleared out by now. Notice you can still find some of these cases in wmstats, for old workflows.

**Comment by amaltaro** [comment]
Seeing this issue again for T2_CH_CERN and also in testbed for T3_CH_Volunteer site.

**Comment by hufnagel** [comment]
Are you complaining that LogCollect jobs fail or that they report code 0 ?

For the former, LogCollect have been failing the beginning of every month for the last 8 months or so. It's the beginning of February, since the latest castor/xrootd patch hasn't been applied yet I would image we again can't stageout LogCollect to castor.

**Comment by hufnagel** [comment]
I'll follow-up in the ticket to get the February directories fixed...

**Comment by amaltaro** [comment]
Both, that they fail and to make things worse, report exit code 0 :-)
Thanks!

**Comment by hufnagel** [comment]
Ok, the LogCollect stageout failures should not happen anymore. I looked at the code again, the current code really should throw an exception for Castor stageout failure. So that doesn't match with the exit code 0 statement.

Do we have logs from a recent "failed with exit code 0" LogCollect job ? Because if these really exist and they were created/run in a recent agent, I doubt this is related to stageout problems.

**Comment by jenimal** [comment]
Here is one that is still in the system:
pdmvserv_task_SMP-RunIISummer15wmLHEGS-00089__v1_T_170118_205100_5940


  * *Job Name:*02d937c0-e4b4-11e6-bc72-02163e0184a6-6
  * *WMBS job id:*1875693
  * *Workflow:*pdmvserv_task_SMP-RunIISummer15wmLHEGS-00089__v1_T_170118_205100_5940
  * *Task:*/pdmvserv_task_SMP-RunIISummer15wmLHEGS-00089__v1_T_170118_205100_5940/SMP-RunIISummer15wmLHEGS-00089_0/LogCollectForSMP-RunIISummer15wmLHEGS-00089_0
  * *Status:*jobfailed
  * *Input dataset:*
  * *Site:*T0_CH_CERN
  * *Agent:*vocms0126.cern.ch
  * *ACDC URL:*https://cmsweb.cern.ch/couchdb/acdcserver
  * *State Transition*
  * *Exit code:*0
  * *Retry count:*1
  * *Errors:*
      o *logCollect1*
  * *Input files:*
  * *Lumis:*
  * *Output:*
  * *log archive:*

*Jen*

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Log Collect jobs showing as "failed" with exit code 0](https://trello.com/c/LNniYyys/35-log-collect-jobs-showing-as-failed-with-exit-code-0)

**Comment by jenimal** [comment]
Seeing this again:
Job Name: 0108a57e-3677-11e7-b2c6-a0369f23d01e-6
WMBS job id: 3684019
Workflow: pdmvserv_task_SMP-RunIISummer16DR80Premix-00199__v1_T_170405_163606_2357
Task: /pdmvserv_task_SMP-RunIISummer16DR80Premix-00199__v1_T_170405_163606_2357/SMP-RunIISummer16DR80Premix-00199_0/LogCollectForSMP-RunIISummer16DR80Premix-00199_0
Status: jobfailed
Input dataset: /WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer15GS-MCRUN2_71_V1_ext2-v1/GEN-SIM
Site: T2_FR_CCIN2P3
Agent: cmsgwms-submit1.fnal.gov
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
jobfailed: 2017/5/11 (Thu) 18:49:31 UTC, T2_FR_CCIN2P3
Exit code: 0
Retry count: 0
Errors:
logCollect1
Input files:
Lumis:
Output:
log archive:

**Comment by jenimal** [comment]
https://cms-logbook.cern.ch/elog/Workflow+processing/26489

**Comment by amaltaro** [comment]
Fixed by #8424 (possibly)
