### ISSUE TITLE
Block missing from phedex

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7309]
There are couple of stuck transfers because of blocks present in DBS, but not in Phedex.

/SinglePhoton/Run2016B-23Sep2016-v2/DQMIO#643da8c0-83bb-11e6-a887-001e67abef8c

bugging transfer team so that they know. But it's likely it was not injected by the agent.
There are several potentially several other transfers
 affected as such.

@sidnarayanan 
@areinsvo @mcremone @scarletnorberg

**Comment by amaltaro** [comment]
Hmmmmm...
according to the agent (vocms0311), this block was injected into DBS and it's closed (dbsbuffer_block):
`25308	1423	/SinglePhoton/Run2016B-23Sep2016-v2/DQMIO#643da8c0-83bb-11e6-a887-001e67abef8c	25	1474875155	Closed	0`

and all its files (only 1) were also injected in DBS and PhEDEx (dbsbuffer_file):
`327703	/store/data/Run2016B/SinglePhoton/DQMIO/23Sep2016-v2/80000/12F3D199-B983-E611-B92B-34E6D7E05F0E.root	62131052	0		1305	InDBS	1	25308	2067	`

though I cannot find it in phedex datasvc, nor the block.

I'm going to flip a couple of flags to get it into PhEDEx (it will try to inject again in DBS as well, but I believe it's smart enough to just reject dups...)

**Comment by sidnarayanan** [comment]
@amaltaro does this mean no action is needed from the transfer team? I was going to manually inject the missing file today.

**Comment by vlimant** [comment]
thx @amaltaro please keep us posted, so far it has made it's way to phedex

**Comment by amaltaro** [comment]
Block `/SinglePhoton/Run2016B-23Sep2016-v2/DQMIO#643da8c0-83bb-11e6-a887-001e67abef8c` is now injected and closed into PhEDEx as well.

In case I need to do the same in the future, I had to:
* mark the block as `status=InDBS` in dbsbuffer_block
* mark its files as `in_phedex=0` in dbsbuffer_file

I took advantage of this issue and also improved the logging of the phedex component #7314, though it still needs to be tested.

I'm closing this issue, feel free to reopen if something is wrong with that block/dataset

**Comment by vlimant** [comment]
We have the same issue other blocks

/SinglePhoton/Run2016B-23Sep2016-v2/DQMIO#643da8c0-83bb-11e6-a887-001e67abef8c
/JetHT/Run2016B-23Sep2016-v2/DQMIO#5cb3e1e2-82ca-11e6-a104-002590494c06
/DoubleEG/Run2016B-23Sep2016-v1/DQMIO#45db00d8-82be-11e6-9f91-001e67abefa8
/SingleMuon/Run2016B-23Sep2016-v2/DQMIO#d75f5b08-839f-11e6-9f91-001e67abefa8
/BTagMu/Run2016E-23Sep2016-v1/DQMIO#357a9a04-95f2-11e6-975d-001e67abf518
/DoubleMuonLowMass/Run2016D-23Sep2016-v1/DQMIO#550ded2c-8fbb-11e6-a325-001e67abef8c

and that's for DQMIO dataset only. There must be several others dataset under the same problem.

@sidnarayanan how is this taken care of on the TT side ? i.e. a block in DBS that does not exist in Phedex.

**Comment by sidnarayanan** [comment]
We have to manually compare between DBS and TMDB what is missing, get the filenames/size/checksum from DBS, and inject into TMDB. Could write a tool to do all these steps automatically, but it won't be available today.

**Comment by vlimant** [comment]
@amaltaro I think we either need this GH to stay open, or create another one to trace and fix this issue on the agent side. We cannot really have data that do not get injected and goes missing.

**Comment by amaltaro** [comment]
Yes, I was not sure whether it was an issue with WMAgent or somewhere between the agent and TMDB, but since we have other cases like that, it's likely to be a problem in the agent code (there is one suspicious place ...).

I'll get back to it a bit later.

**Comment by vlimant** [comment]
I triple checking on how I reported these blocks, they are either not in phedex or marked as complete='n' in phedex.
Some of these would fall into the @sidnarayanan "incomplete transfer" in this case.

**Comment by vlimant** [comment]
/SinglePhoton/Run2016B-23Sep2016-v2/DQMIO#643da8c0-83bb-11e6-a887-001e67abef8c 

 was missing in phedex (injected by Alan)

/JetHT/Run2016B-23Sep2016-v2/DQMIO#5cb3e1e2-82ca-11e6-a104-002590494c06

 is missing in phedex

/DoubleEG/Run2016B-23Sep2016-v1/DQMIO#45db00d8-82be-11e6-9f91-001e67abefa8

 is missing in phedex

/SingleMuon/Run2016B-23Sep2016-v2/DQMIO#d75f5b08-839f-11e6-9f91-001e67abefa8

 is just incomplete transfer

/BTagMu/Run2016E-23Sep2016-v1/DQMIO#357a9a04-95f2-11e6-975d-001e67abf518

 is just incomplete transfer

/DoubleMuonLowMass/Run2016D-23Sep2016-v1/DQMIO#550ded2c-8fbb-11e6-a325-001e67abef8c

 is just incomplete transfer

**Comment by amaltaro** [comment]
And to summarize, None of them are important because those that are NOT in PhEDEx, they belong to workflows that are `rejected-archived`. So no blocks for WMCore folks to look at.

**Comment by vlimant** [comment]
suspicion now is that files were removed from TMDB after having been injected properly.

**Comment by vlimant** [comment]
This now turns into files were injected but did not really exists.
We will have to chase these kinds of ghost files and catch the failing stageout.

**Comment by vlimant** [comment]
would /BTagCSV/Run2016F-23Sep2016-v1/DQMIO be in the same situation ?

**Comment by amaltaro** [comment]
was it sorted out with the transfer team?

**Comment by sidnarayanan** [comment]
Yes. Block was missing because it contained no valid files. That is intentional.

**Comment by amaltaro** [comment]
This issue is so confusing. The summary I get from all the discussions we had about missing files here and there are:
a) inconsistency between DBS and PhEDEX coming from workflows force-completed that kept injecting jobs
b) files invalidation - triggered by site admins, Ops, transfer team - and some times not a consistent invalidation.

If there is any other case, can people be specific and clear? Thanks

**Comment by vlimant** [comment]
Yes, because we have had suspicion of file injection issues this was opened there. The reports are clear. But tracing what happened is confusing indeed, clearly we need to get this straighten with TT, and it looks like file injection is not the issue ; we will keep that in mind

**Comment by amaltaro** [comment]
Closing this one also in favor of #7115
