### ISSUE TITLE
WMStats reports PNN instead of PSN in the job report

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7313]
In the detailed view in wmstats (where you can create ACDCs from), I noticed the `site` column is reporting the PNN instead of the PSN. E.g. in testbed:
amaltaro_TaskChainZTT_PU_Agent1021_Validation_161019_134727_5053

**Comment by amaltaro** [comment]
And this is why we report the PNN:
https://gitlab.cern.ch/SITECONF/T1_US_FNAL_Disk/blob/master/JobConfig/site-local-config.xml#L2

@ticoann we need to talk to Dave M. or Gaston to fix this line.

**Comment by hufnagel** [comment]
You can't get the PSN from site-local-config. You would need to get it from HTCondor.

**Comment by hufnagel** [comment]
Ah, sorry, you refer to the site line. FNAL is a special case, this is by design. It's the only T1 that created two different sites for implementing the tape/disk separation. So this line can't be fixed, it is by design.

Now, they really should get rid of the T0_US_FNAL_Disk site and roll everything into a single T1_US_FNAL site... But that's a larger change.

**Comment by hufnagel** [comment]
https://cmsweb.cern.ch/sitedb/prod/sites/T1_US_FNAL_Disk

**Comment by amaltaro** [comment]
We get the correct PSN for every other T1 site. Why it cannot be updated for FNAL is unclear to me. What's the consequences if that line gets updated?

**Comment by hufnagel** [comment]
Every other T1 site the site name is the same as the PSN. For Fermilab it's not. Changing that line for Fermilab and leaving the site definitions as they are is a hack. Not sure if that hack will work or will even have other consequences though.

**Comment by hufnagel** [comment]
Btw, according to the naming conventions in site-local-config and the code in

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/SiteLocalConfig.py

this is all working correctly. The site name IS T1_US_FNAL_Disk and that is what is reported. If you want the PSN then the conventions and code should be changed to actually specify PSN.

Site != PSN. We have been historically extremely sloppy about being precise about this though and that is what is biting us here.

**Comment by amaltaro** [comment]
Then it's already inconsistent. Because the `psn_name` mapped to T1_US_FNAL_Disk is T1_US_FNAL:
https://cmsweb.cern.ch/sitedb/data/prod/data-processing

which is where the jobs are sent.

**Comment by hufnagel** [comment]
Why is that inconsistent ? It's correct. There just is no PSN in site-local-conf, there is a site name. You just report it as PSN, which is the wrong part.

**Comment by amaltaro** [comment]
Ok, and you are saying that the site name is T1_US_FNAL_Disk? That looks at least, weird!

What would be the impact in changing the site name in the site local config from *_Disk to T1_US_FNAL only?

**Comment by hufnagel** [comment]
Apart from piling another hack on top of our current hack to report the site name as PSN ? It would likely work, I just scanned through the WMCore SiteLocalConfig class. *IF* we do this I would also suggest we also do two other things:

1) ask FNAL to get rid of their two sites, there really is no reason for that, no other T1 has it
2) change the WMCore code and the site-local-conf to report PSN (and make that clear with the variable names and xml field names) if this is indeed supposed to be a PSN

**Comment by amaltaro** [comment]
Getting rid of the two FNAL sites is something that would take quite a while, I think.

UK_RAL and RU_JINR seem to have two sites as well, though I cannot find their site-local-config under the *_Disk entry in sitedb.

Besides the weirdness on this, it doesn't really affect me or CompOps, they just need to get used of this specifics related to FNAL.

Dirk, if you want to orchestrate the proper setup at FNAL, then please go ahead. Otherwise I'd close this issue as it's not a WMCore issue.

**Comment by hufnagel** [comment]
If this is really just about reporting in WMStats I would close as well. We report the correct site as defined in SiteDB and site-local-config. Will push for this change at FNAL, but likely only next year when I am actually there.

**Comment by amaltaro** [comment]
Ok, thanks Dirk!
@prozober FYI, read above please. Summary, not a WMCore issue, not a site issue (just a feature :D)
