### ISSUE TITLE
Jobs for site in drain not getting removed

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7315]
spotted this, while trying to get jobs removed for T2_FR_IPHC

```
2016-10-20 13:06:35,544:140117853804288:INFO:ResourceControlUpdater:Changing T2_FR_IPHC state from Normal to Draining
2016-10-20 13:06:45,590:140117853804288:INFO:PyCondorPlugin:Retrieved 43451 classAds
2016-10-20 13:08:27,735:140117864294144:INFO:AgentStatusPoller:Getting agent info ...
2016-10-20 13:08:46,611:140117864294144:INFO:AgentStatusPoller:CouchDB is running with 10 processes
2016-10-20 13:08:46,611:140117864294144:INFO:AgentStatusPoller:Getting wmbs job info ...
2016-10-20 13:08:49,077:140117864294144:INFO:AgentStatusPoller:finished collecting agent/wmbs info
2016-10-20 13:12:14,664:140117853804288:ERROR:BossAirAPI:Unhandled exception while calling update method for plugin PyCondorPl
ugin
Unable to edit jobs matching constraint
2016-10-20 13:12:14,721:140117853804288:ERROR:ResourceControlUpdater:Failed to update T2_FR_IPHC state to Draining:
2016-10-20 13:12:14,722:140117853804288:ERROR:ResourceControlUpdater:BossAirException
Message: Unhandled exception while calling update method for plugin PyCondorPlugin
Unable to edit jobs matching constraint
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : updateSiteInformation
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages
/WMCore/BossAir/BossAirAPI.py
        ClassName : None
        LineNumber : 786
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/BossAirAPI.py", line 777, in updateSiteInformation
    tempjoblist = pluginInst.updateSiteInformation(jobs, siteName, excludeSite)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/Plugins/PyCondorPlugin.py", line 687, in updateSiteInformation
    sd.edit('WMAgent_JobID == %i' % jobID, "DESIRED_Sites", classad.ExprTree('"%s"' % desiredSites))


2016-10-20 13:12:14,723:140117853804288:ERROR:ResourceControlUpdater:Traceback: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponen
t/AgentStatusWatcher/ResourceControlUpdater.py", line 344, in updateSiteState
    self.resourceControl.changeSiteState(siteName, state)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Res
ourceControl/ResourceControl.py", line 66, in changeSiteState
    jobtokill = bossAir.updateSiteInformation(jobInfo, siteName, state in ("Aborted","Draining","Down"))
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Bos
sAir/BossAirAPI.py", line 786, in updateSiteInformation
    raise BossAirException(msg)
BossAirException: BossAirException
Message: Unhandled exception while calling update method for plugin PyCondorPlugin
Unable to edit jobs matching constraint
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : updateSiteInformation
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages
/WMCore/BossAir/BossAirAPI.py
        ClassName : None
        LineNumber : 786
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py", line 777, in updateSiteInformation
    tempjoblist = pluginInst.updateSiteInformation(jobs, siteName, excludeSite)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/PyCondorPlugin.py", line 687, in updateSiteInformation
```

**Comment by vlimant** [comment]
This is holding several workflows that we would like to have closing.
So consider this urgent ops. I'd rather not have to kill the jobs by hand.

**Comment by amaltaro** [comment]
I *nicely* attempted to update/kill those jobs again in vocms0303, and it failed again after a few minutes of processing.

This issue lies either on the load of this condor schedd or on not a very good work made by the python bindings. The load of this node - condor job wise - right now is:
39741 jobs; 0 completed, 1 removed, 24162 idle, 15578 running, 0 held, 0 suspended

**Comment by amaltaro** [comment]
@bbockelm just in case you wanna skim this issue

**Comment by vlimant** [comment]
T2_FI_HIP is having the same issue of jobs not edited properly even though the site is in drain. regardless of back-and-forth status flipping that might have occured.

**Comment by vlimant** [comment]
on a side note, we have to find a better way to do the job editing, or job matching banning to avoid taking 3-4 days to have a site with no jobs pending, and failing jobs in the meantime.

**Comment by bbockelm** [comment]
I see a few things to fix up:

1.  https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L667 The construct of `classad.ExprTree('"%s"' % desiredSites)` is not the best.  You want to replace this with `classad.quote(desiredSites)` to avoid potential quoting issues.
2.  HTCondor considers an `edit` command that has no matching jobs as an error and hence throws an exception.  You probably want to catch the `RuntimeError` and move on.  It's likely that the job just finished but hasn't been noticed by the agent.
3.  Doing this job-by-job is horribly inefficient.  You want to replace this with a series of bulk updates.

An algorithm for the bulk updates would likely be something like this:
```
unique_site_lists = set()
dead_jobs = set()
for job in sd.xquery(projection=["DESIRED_Sites", "WMAgent_JobID"]):
  desired = job.get("DESIRED_Sites")
  id = job.get("WMAgent_JobID")
  if desired:
    if (desired == siteName) and id:
      dead_jobs.add(id)
    else:
      unique_site_lists.add(job['DESIRED_Sites'])
with sd.transaction() as txn:
  for orig_site_list in unique_site_lists:
    site_list = [i.strip() for i in orig_site_list.split(",")]
    site_list.remove(siteName)
    if not site_list: continue
    site_list = ",".join(site_list)
    try:
      sd.edit('DESIRED_Sites=?=%s' % classad.quote(orig_site_list), "DESIRED_Sites", classad.quote(site_list)
    except RuntimeError:
      pass
return [job for job in jobs if job['id'] in dead_jobs]
```

**Comment by bbockelm** [comment]
Note that my algorithm above would require two interactions with the schedd (one query, one edit transaction).  The existing algorithm requires about 4200 interactions with the schedd (with the current set of jobs).

**Comment by amaltaro** [comment]
I had the impression we had tried bulk condor edit in the past and it having issues (maybe timeout..). Ok, I'll try it again, but likely to the new agent only. @hufnagel you'll probably have to add it to SimpleCondor as well, if it turns to work fine. More news in the coming adys.

@vlimant where do you see jobs taking 3 to 4 days to be editted or removed from condor queue? Have you seen this happening in the past? Once we fix it, then all the jobs will be taken care within 15min or so. BTW, HIP was enabled until later yesterday afternoon.

**Comment by amaltaro** [comment]
Ok, I should have a code ready to be tested https://github.com/amaltaro/WMCore/commit/0a472fde9ae7128cc043613ea6c9c4f1eea931fa , however... it seems Schedd edit method does not support multiple attributes, does it?

If not, then it's going to be tricky because we'd have to update one list, then fetch the classAds again (not sure if there is a minimum amount of time to get the new attributes synced everywhere it needs to..) and then update the second list with new constraints.

**Comment by bbockelm** [comment]
Everything is in a single transaction.  So, if you do two Schedd.edit calls, they will be visible atomically.

It is a bummer that the schedd will have to apply the constraint twice server-side.  Not much we can do about that.  Could you file a condor bug?

**Comment by amaltaro** [comment]
Apparently I'm not able to file an issue at https://github.com/htcondor/htcondor, I don't even see the `Issues` button.
Thanks for the hints, I'll later give it a try.

**Comment by vlimant** [comment]
adding http://cms-gwmsmon.cern.ch/prodview/pdmvserv_BPH-RunIISummer15GS-00080_00448_v0__161019_161345_989 pending jobs at CSCS, which was set in drain.
This is creating tails, as previously reported

**Comment by amaltaro** [comment]
A fix for this issue was just pushed into the production agents.
However, it was tested only at a very small scale, so please report again if you still see wandering when they shouldn't.
