### ISSUE TITLE
ACDC creation reqmgr1 vs reqmgr2

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7325]
Trying to create a reqmgr2 ACDC for a worfklow in reqmgr1.
pdmvserv_EXO-RunIISpring16DR80-04597_00669_v0__160930_150303_8913
Using the same schema at injection
{
  "InitialTaskPath": "/pdmvserv_EXO-RunIISpring16DR80-04597_00669_v0__160930_150303_8913/StepOneProc", 
  "OriginalRequestName": "pdmvserv_EXO-RunIISpring16DR80-04597_00669_v0__160930_150303_8913", 
  "ACDCServer": "https://cmsweb.cern.ch/couchdb", 
  "Group": "ppd", 
  "RequestPriority": 70000, 
  "TimePerEvent": 3, 
  "ACDCDatabase": "acdcserver", 
  "RequestType": "Resubmission", 
  "SizePerEvent": 2500, 
  "Memory": 8192, 
  "RequestString": "ACDC_EXO-RunIISpring16DR80-04597_00669_v0_", 
  "PrepID": "EXO-RunIISpring16DR80-04597"
}

One ended up being 
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/vlimant_ACDC_EXO-RunIISpring16DR80-04597_00669_v0__161025_154757_6084 (reqmgr2)
the other one
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/vlimant_ACDC_EXO-RunIISpring16DR80-04597_00669_v0__161025_162428_4125 (reqmgr1)

so far so good. At assignment time, we try to get processingstring from the workload cache, and it is not present in the reqmgr2 case.

**Comment by vlimant** [comment]
N.B.
vlimant_ACDC_EXO-RunIISpring16DR80-04597_00669_v0__161025_154757_6084.request.schema.ProcessingString = 'premix_withHLT_80X_mcRun2_asymptotic_v14'

vlimant_ACDC_EXO-RunIISpring16DR80-04597_00669_v0__161025_162428_4125.request.schema.ProcessingString = 'premix_withHLT_80X_mcRun2_asymptotic_v14'

**Comment by amaltaro** [comment]
We'll likely have to make a patch for the client side. Can you point me the script you used please?

We'll try to get a proper fix for the server into testbed this week.

**Comment by vlimant** [comment]
reqmgr1 injected with https://github.com/CMSCompOps/WmAgentScripts/blob/master/makeACDC.py#L57

reqmgr2 https://github.com/CMSCompOps/WmAgentScripts/blob/updated_make_acdc/makeACDC.py#L43

the dictionary that was send is strictly identical

**Comment by vlimant** [comment]
side note : the reqmgr2 workflow does not show up in wmstats

**Comment by amaltaro** [comment]
It actually is there, but without `Campaign`... I'm pretty sure I tested it in my latest changes in the last month.

For now, can you read `Campaign` (I think you're already reading all the params) from the original workflow and put it in the json to be injected for the Resubmission workflow?

**Comment by vlimant** [comment]
we can change the way the recoveries/acdc were made indeed. unless you want to support the same behaviour as before.

**Comment by ticoann** [comment]
Hi Jean-Roch,

We will change to the same behavior. Basically for clone, and resubmission.  we will automatically retrieve original workflow and append those value to the new workflow unless it need to be overwritten, (This is the behavior you want, correct?) 

Meanwhile if you can add the parameters you want to inherit from original workflow,  please add it here (Campaign, ProcessString, etc)
https://github.com/CMSCompOps/WmAgentScripts/blob/updated_make_acdc/Unified/recoveror.py#L22

Sorry for the inconvenience.

**Comment by vlimant** [comment]
Hi,

 it's OK, no pb, I knew we'd come to chasing issues on ACDC. I could be wondering why this basic behavior is broken, but I won't.

 We will go on with ACDC in reqmgr1 for the moment, until you warn us back on this GH that things are fixed on server side.
 I'd rather not change the acdc scripts with putting extra members that I am not sure will be handled nicely downstream. AcquisitionEra for taskchain ACDC and the like.

 I repeat : this is not a show-stopper for operation, so let's just have the fix on the server side at next deployment.

**Comment by vlimant** [comment]
Hi guys, I think we have seen this exact same issue a while back for trying to get workload cache instead of /reqmgr/reqMgr/request?requestName= api and get the propers value for assigning them, even workflow in request manager.
I will try to trace that back to whatever issue was raised. But ...

**Comment by ticoann** [comment]
TaskChain workflow didn't work with reqmgr1 GUI assignment, It seems it is treated differently from other workflow in reqmgr1 as well. I didn't know you have to use reqmgr1 request to get the correct information for the task chain.

@vlimant, Question: For ACDC for a task chain workflow? do you need to modify the Task information for acdc compare to original workflow?

**Comment by vlimant** [comment]
usually the task information should not change, unless we have a timeperevent, memory and all per task. but let's not think about this now.

**Comment by ticoann** [comment]
Thanks Jean-Roch in that case, #7329 should fix the problem. It seem when it changes OpsScript overwrites. I was just afraid whether some of the field need to be removed from original config (spec)
