### ISSUE TITLE
Changing priority brings error message

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7327]
From https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_EXO-RunIIWinter15wmLHE-02696_00437_v0__161019_163322_2708 changing the priority brought up

"""
Server error message
Invalid spec parameter value: 'RequestStatus' 
"""
error window, but the priority is updated.

**Comment by vlimant** [comment]
am I trying to change a reqmgr1 request from reqmgr2 ? yes

**Comment by ticoann** [comment]
Yes that is not supported. :smile:

**Comment by vlimant** [comment]
shame :-(

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC0_Run2016G-v1-Tau-23Sep2016_8020_161029_103625_5054
is in request manager2 only (https://cmsweb.cern.ch/reqmgr/view/details/vlimant_ACDC0_Run2016G-v1-Tau-23Sep2016_8020_161029_103625_5054 fails), and changing the priority gives 
"""
Server error message
Invalid spec parameter value: 'RequestStatus' 
"""
and de-facto the priority does not change.

**Comment by ticoann** [comment]
Hi Jean-Roch, Sorry it seems this bug was introduced in last deployment. Patch is created. #7341

**Comment by vlimant** [comment]
Hi guys, is this in production already ?

**Comment by ticoann** [comment]
Hi Jean-Roch This will be updated tomorrow. Production upgrade is postponed to tomorrow.
