### ISSUE TITLE
non-reqmgr1 equivalent of reqmgr/reqMgr/request?requestName=

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7333]
assign.py is used to pick things up from

https://cmsweb.cern.ch/reqmgr/reqMgr/request?requestName=prozober_ACDC_task_EXO-RunIIFall15DR76-02586__v1_T_161026_164622_6741

where one can read the Task1, Task2, ...

https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC_task_EXO-RunIIFall15DR76-02586__v1_T_161026_164622_6741

does not hold the same level of information.

I think we have faced the same issue when we had this unfortunate move and bad acdc and all. So I'd hope we have this fixed somehow by now.

@prozober please hold on to assigning anything until we get this under control

**Comment by vlimant** [comment]
couchdb/reqmgr_workload_cache/ does not have that information either.

**Comment by ticoann** [comment]
This will be fixed with #7329. Also, for the get call script should use this.

https://cmsweb.cern.ch/reqmgr2/data/request/prozober_ACDC_task_EXO-RunIIFall15DR76-02586__v1_T_161026_164622_6741

**Comment by amaltaro** [comment]
Fix should already be available in production, so closing this issue.
