### ISSUE TITLE
Clean up Teams from the system

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7355]
As discussed with Seangchan yesterday (and initially fixed in #7353), we're no longer supporting a workflow assigned to more than one team name. 

In addition to that, we'll also remove the support of multiple team names defined in the agent configuration. It just causes confusion about `Team` x `Teams` and nobody has used this feature during the last couple of years.

**Comment by DAMason** [comment]
This makes me sad.

**Comment by amaltaro** [comment]
I'm actually keeping it open because the final clean up still has to happen (probably to HG1710 deployment)
