### ISSUE TITLE
Replacement of couchdb/reqmgr_workload_cache/<wfname>/spec

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7357]
Looks like https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_EXO-RunIIFall15DR76-04677__v1_T_161019_035339_1562/spec is the only place to retrieve the actual list of tasks that are created for a given workflow.
In a view to remove direct calls to couch, we would need a replacement place to retrieve that information.

**Comment by ticoann** [comment]
Jean-Roch, could you specify  information is needed? Names of all the tasks? Could you point me the code where the information is used?

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3896
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L3630

 requires a bit of code digging.

**Comment by ticoann** [comment]
Thanks Jean-Roch, So it seems the information needed is the splitting parameters for each task, is that correct?

**Comment by amaltaro** [comment]
@vlimant is this api what you were looking for? If so, then close the issue please
