### ISSUE TITLE
Upload of MC ACDC docs broken

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7377]
I've just found a MC workflow with 1 out of 20 jobs failed. The ACDC workflow produced exactly the same lumi + number of events. The problem lies on the jobfailed information uploaded to couchdb acdcserver:
https://cmsweb-testbed.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22amaltaro_MonteCarlo_PhEDEx_HG1611_Validation_pre6_161105_103000_3637%22&include_docs=true&reduce=false

where one can see the list of lumis correspond to ALL the lumis this workflow is supposed to create.
The same applies to the file nunmber of events (10k, so total number of events), though it's known and expected already..

Needs to be investigated further, on the agent side.

**Comment by ticoann** [comment]
HI Alan, 
I check the MC-Fake file created by this workflow and it seems there is only one file in wmbs. 
It seems that input file is used for multiple jobs but when it fails it didn't get to mask correctly on updated ACDC.  I haven't found exact code doing that.  One weird thing is there is no fileset name in wmbs_fileset table. /amaltaro_MonteCarlo_PhEDEx_HG1611_Validation_pre6_161105_103000_3637/Production

**Comment by amaltaro** [comment]
Thanks, Seangchan. About the single file in wmbs, that's is normal for MonteCarlo workflows, it basically creates one fake file per workqueue element (1000 jobs).

About the fileset, it seems the top level fileset name doesn't start with a `/`, you can find it
`amaltaro_MonteCarlo_PhEDEx_HG1611_Validation_pre6_161105_103000_3637-Production-0031b50ba950a6458506041ae7485674`.

The mask for this job must be wrong. I'll have a look at that table.

**Comment by amaltaro** [comment]
This job `12352` failed for `amaltaro_MonteCarlo_PhEDEx_HG1611_Validation_pre6_161105_103000_3637`.

It was supposed to create 5 lumi sections, but according to the acdc doc, it was handling 100(?)

Then looking at wmbs for the job mask, we actually have no entry for this job:
`select * from wmbs_job_mask where job=12352;`

then I unpickled the `job.pkl` and we can correctly see the job mask inside the job:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7377/job_12352

I thought we were supposed to create a job_mask entry per job, maybe there is an exception for MonteCarlo... but investigating.

**Comment by amaltaro** [comment]
I injected new test workflows into vocms0125 and vocms0230 (they have different db backends).
In vocms0125
```
MariaDB [wmagent]> select * from wmbs_job_mask where job=40;
+-----+------------+-----------+-----------+----------+----------+---------+---------------+
| job | FirstEvent | LastEvent | FirstLumi | LastLumi | FirstRun | LastRun | inclusivemask |
+-----+------------+-----------+-----------+----------+----------+---------+---------------+
|  40 |       9501 |     10001 |        96 |      101 |        1 |       1 |             1 |
+-----+------------+-----------+-----------+----------+----------+---------+---------------+
1 row in set (0.00 sec)
```

and then in vocms0230:
```
SQL> select * from wmbs_job_mask where job=17752;

no rows selected
```

now it should be easier to find the culprit.

**Comment by amaltaro** [comment]
and here is the place we create these job masks:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/Subscription.py#L656

I still don't know where the problem lies, but I noticed this call
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/Oracle/Masks/Save.py#L59

returns a ResultSet object when there is only one entry to insert.
`2016-11-09 18:06:26,053:140129367480064:INFO:Save:AMR result [<WMCore.Database.ResultSet.ResultSet instance at 0x7f726877d2d8>]`

contrary to when there are several entries to insert, which returns a sqlalchemy object
`2016-11-09 17:46:18,253:140129367480064:INFO:Save:AMR result [<sqlalchemy.engine.result.ResultProxy object at 0x7f7268212510>]`

I'm wondering if this ResultProxy could be closed before the transaction is committed or so(?)
I also don't get why the same DBAPI call would return different result objects.

**Comment by amaltaro** [comment]
Since @yuyiguo is sitting next to me :), I'm bugging her to see if there is any problem that I cannot really see now.
