### ISSUE TITLE
Request details in reqmgr broken

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7381]
Browsing through wmstats and then trying to open a reqmgr request:
https://cmsweb-testbed.cern.ch/reqmgr/view/details/amaltaro_ReDigi_HG1610_Validation_161007_120528_2120

raises an Internal Server Error.

The problem in the logs is the following [1].

However, one can still retrieve the workload_cache through
https://cmsweb-testbed.cern.ch/reqmgr2/data/request?name=amaltaro_ReDigi_HG1610_Validation_161007_120528_2120

or even check the whole spec via
https://cmsweb-testbed.cern.ch/reqmgr2/config?name=amaltaro_ReDigi_HG1610_Validation_161007_120528_2120

I was going to ask the HTTP group to abort today's upgrade, but I don't think anyone would need to open that `details` view in reqmgr anymore... well, I hope.

[1]
INFO:cherrypy.access:[10/Nov/2016:08:20:38] vocms0131.cern.ch 127.0.0.1 "GET /reqmgr/ HTTP/1.1" 200 OK [data: - in 1631 out 324 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
ERROR:root:Could not check workload for amaltaro_ReDigi_HG1610_Validation_161007_120528_2120, reason: WMWorkloadHelper instance has no attribute 'acquisitionEra'
ERROR:cherrypy.error:[10/Nov/2016:08:20:43] HTTP 
Traceback (most recent call last):
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/external/cherrypy/5.4.0/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/external/cherrypy/5.4.0/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/external/cherrypy/5.4.0/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrBrowser.py", line 210, in details
    request = Utilities.requestDetails(requestName)
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 478, in requestDetails
    schema['AcquisitionEra']  = str(helper.getAcquisitionEra())
  File "/data/srv/beHG1611n-comp/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 752, in getAcquisitionEra
    return self.acquisitionEra
AttributeError: WMWorkloadHelper instance has no attribute 'acquisitionEra'
INFO:cherrypy.access:[10/Nov/2016:08:20:43] vocms0131.cern.ch 2001:1458:202:48::101:970e "GET /reqmgr/view/details/amaltaro_ReDigi_HG1610_Validation_161007_120528_2120 HTTP/1.1" 500 Internal Server Error [data: - in 825 out 752663 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues" "" ] [ref: "https://cmsweb-testbed.cern.ch/wmstats/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0" ]

**Comment by ticoann** [comment]
Hi, Alan, what do you mean by aborting the upgrade today? Is there many workflows created by reqmgr1 in production. What we can do is instead of fixing reqmgr1 we can also change all the link to reqmgr2. I will check how many requests are in reqmgr1 request in production.

**Comment by amaltaro** [comment]
The cmsweb upgrade. But after a bit of thinking, I conclude the problem was not that bad.

**Comment by ticoann** [comment]
That's good. Thanks Alan. In fact, there is no reqmgr1 requests in production system.
https://cmsweb.cern.ch/reqmgr2/data/request?status=ACTIVE&mask=ReqMgr2Only

I think we can just close this issue and start to thinking about removing the reqmgr completely.

**Comment by amaltaro** [comment]
I think I have to agree with you then :-) Anyways, I still think we can leave this around until the beginning of the next week, just in case we hear complaints :)

**Comment by amaltaro** [comment]
No more ReqMgr, so no more problems with ReqMgr :)
