### ISSUE TITLE
Failed assignment with ImportError: No module named ReqMgr.Tools.cms

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7383]
{
  "SoftTimeout": 159600, 
  "BlockCloseMaxEvents": 2000000, 
  "MaxMergeEvents": 200000, 
  "CustodialSites": [], 
  "MaxRSS": 6041600, 
  "ProcessingString": "FlatPU28to62HcalNZSRAWAODSIM_80X_mcRun2_asymptotic_2016_TrancheIV_v6", 
  "Teamproduction": "checked", 
  "TrustSitelists": false, 
  "UnmergedLFNBase": "/store/unmerged", 
  "CustodialSubType": "Replica", 
  "TrustPUSitelists": false, 
  "GracePeriod": 300, 
  "MergedLFNBase": "/store/mc", 
  "SiteWhitelist": [
    "T2_US_Caltech"
  ], 
  "AcquisitionEra": "RunIISummer16DR80", 
  "checkboxvlimant_HIG-RunIISummer16DR80-00012_00032_v1__161108_193859_7396": "checked", 
  "NonCustodialSubType": "Replica", 
  "NonCustodialSites": [
    "T2_US_Caltech"
  ], 
  "MinMergeSize": 2147483648, 
  "BlockCloseMaxWaitTime": 172800, 
  "MaxMergeSize": 4294967296, 
  "ProcessingVersion": 2, 
  "Dashboard": "reprocessing", 
  "AutoApproveSubscriptionSites": [
    "T2_US_Caltech"
  ], 
  "MaxVSize": 4394967000, 
  "SiteBlacklist": [], 
  "action": "Assign"
}
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>400 Bad Request</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Unhandled error: Traceback (most recent call last):
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/HTTPFrontEnd/RequestManager/Assign.py", line 315, in assignWorkload
    helper.validateArgumentForAssignment(kwargs)
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1657, in validateArgumentForAssignment
    specClass = loadSpecClassByType(self.requestType())
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 331, in loadSpecClassByType
    globals(), locals(), [factoryName])
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/ReDigi.py", line 10, in &lt;module&gt;
    from WMCore.WMSpec.StdSpecs.DataProcessing import DataProcessing
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/DataProcessing.py", line 9, in &lt;module&gt;
    from WMCore.WMSpec.StdSpecs.StdBase import StdBase
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/reqmgr/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 18, in &lt;module&gt;
    from WMCore.ReqMgr.Tools.cms import releases, architectures
ImportError: No module named ReqMgr.Tools.cms
</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>

error in assigning vlimant_HIG-RunIISummer16DR80-00012_00032_v1__161108_193859_7396

**Comment by amaltaro** [comment]
I thought we had completely moved to ReqMgr2 by now(?) This is a ReqMgr (one) request and this issue sniped in in the latest cmsweb upgrade (we didn't really validate ReqMgr in the latest cycle).

Can you move it to ReqMgr2 please.

**Comment by vlimant** [comment]
We are in the transition period, and the phasing out deadline has not been reached.
I'll take this one back into reqmgr2, but we might be facing serious trouble without a fully functional and legacy reqmgr until the complete phase out.

**Comment by vlimant** [comment]
FYI @mcremone

**Comment by amaltaro** [comment]
Seems to be no longer an  issue, ReqMgr is deprecated \o/
Closing
