### ISSUE TITLE
JobStatusLite/CondorPlugin running timeout evaluated for lifetime of job

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#7385]
Was trying to understand why hepcloud jobs that have sat idle for a few days suddenly get killed by the agent when they run -- looks like the default running timeout of ~48 hours kills  it off based on the time it switches to running - when submitted.  To mitigate have extended the timeouts to something like proxy lifetime - 24 hours (though does it even need to be that?) but this should probably be something like current time - last state change...    I assume the point is kill off jobs that have been running more than 48 hours (which actually will happen anyway with pilot lifetimes that long)

**Comment by DAMason** [comment]
FWIW finding I need to do something like:

config.JobStatusLite.stateTimeouts = {'Running': 400000, 'Pending': 432000, 'Error': 300}

where normally it was

config.JobStatusLite.stateTimeouts = {'Running': 169200, 'Pending': 432000, 'Error': 300}

**Comment by amaltaro** [comment]
Dave, are you saying the agent is killing jobs after 169200 secs, regardless of its state? I'm pretty sure it uses the last state change timestamp from the BossAir table. To be clear, it will only kill jobs that are in the running state for 169200 secs, or in pending for 5 days (432000), and so on.

The main idea behind this component timeout is that we get a proper error code in case it's triggered. If the batch system (or the pilot) kills it, then we have no clue of what happened.

**Comment by DAMason** [comment]
Whats happening is its sitting idle, and while idle happily living under the much longer idle timeout, but after sitting idle for > the running timeout, as soon as the job flips to running status it kills the job.  The running timeout I think is being evaluated against the current time - the submit time, when I think its supposed to be current time - state flip time.  Right now I’m working around by just setting the running timeout also really long.  

> On Nov 13, 2016, at 3:53 PM, Alan Malta Rodrigues <notifications@github.com> wrote:
> 
> Dave, are you saying the agent is killing jobs after 169200 secs, regardless of its state? I'm pretty sure it uses the last state change timestamp from the BossAir table. To be clear, it will only kill jobs that are in the running state for 169200 secs, or in pending for 5 days (432000), and so on.

Nope — whats happening now is if the job exists for more than 169200 seconds and flips to running it kills it.

**Comment by DAMason** [comment]
BUT -- the job we looked at had NumJobStarts=4 -- could it be that in this case it takes the start time of the first time it ran (which might have been 2 days ago) rather than the most recent time?

Added the condor_history dump for the job the agent killed.

[addump.txt](https://github.com/dmwm/WMCore/files/588264/addump.txt)

**Comment by amaltaro** [comment]
Hmm, that's weird. The only possible problem I could see is when not all the classAds are returned from condor:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L1048
in this case we would set the `status_time` to 0. However, if this was the case your jobs would still be getting killed, no matter how many days the timeout is. (It should get updated in the next cycle)

These are the 3 classAds we use for updating `status_time` in the bossAir table:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L995

Is it possible condor is not switching the JobStatus for these jobs automatically restarted by it?

Can you point me to a workflow where you see these problems?

**Comment by amaltaro** [comment]
Dave, allow me to close this issue due to lack of activity. If someone spots this problem again, please reopen this issue.
