### ISSUE TITLE
multicore workflows with singlecore steps

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7393]
In this useful page https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752 that we have to keep around for this exact purpose (PLEASE DO NOT DEPRECATE AND REMOVE IT).
One can see
pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752.tasks.StepOneProc.steps.cmsRun1.application.multicore.numberOfCores = 4
pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752.tasks.StepOneProc.steps.cmsRun1.tree.children.cmsRun2.application.multicore.numberOfCores = 1
which means there is a problem somewhere.
thx @bbockelm for noticing.

I have not looked for an equivalent workflow in reqmgr (this one above is reqmgr2) to check whether the issue is "new"

**Comment by amaltaro** [comment]
Jeeez, really?!?! We don't run such a test during the validation/integration phase, that's why this issue sneaked in. I'll work on unit tests to catch such failures in the future.

For Ops, the immediate fix will be sending `"Multicore": 4` or so during assignment. Unified already reads the whole schema, so this is going to be faster and better for all of us, I hope. If you don't want to mess with TaskChains, just skip the override for it.

**Comment by bbockelm** [comment]
FYI - I'm not sure if it's the same or a separate issue, but I think the splitting for these workflows are incorrect by about 4x (jobs are too short).

**Comment by vlimant** [comment]
@amaltaro hacked in unified https://github.com/CMSCompOps/WmAgentScripts/commit/f72fbacf337880efe483c4f6bde201625bd7a93e
@bbockelm we have to figure out how this changed recently in how things are injected. I see StepTwoTimePerEvent and StepThreeTimePerEvent set in recent schema
https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597
not sure if those are injected or default parameters' value.
Let's deal with that splitting somewhere else.

**Comment by amaltaro** [comment]
BTW, this workflow
pdmvserv_TSG-RunIISummer16DR80Premix-00001_00015_v0__161106_205613_7752
was injected before the latest cmsweb upgrade. Meaning it's not a new issue.

**Comment by vlimant** [comment]
is the same issue present in reqmgr or new in reqmgr2 ?

**Comment by amaltaro** [comment]
Yes, the workload construction base code is the same.

**Comment by vlimant** [comment]
vlimant_B2G-RunIISummer16DR80Premix-00028_00018_v0__161116_181817_433.tasks.StepOneProc.steps.cmsRun1.tree.children.cmsRun2.application.multicore.numberOfCores = 4
with setting Multicore=4 at assignment

**Comment by amaltaro** [comment]
Yep, I confirm it works. I tested it this afternoon.
