### ISSUE TITLE
StepNTimePerEvent in the schema

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7394]
looking at injection tools @anorkus, it does not look like 

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.StepTwoTimePerEvent = 1.0

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.StepThreeTimePerEvent = 1.0

 were actually not injected as such. Please confirm.

Furthermore @amaltaro @ticoann they are not considered at all in splitting it seems, given, I assume, the presence of 

pdmvserv_B2G-RunIISummer16DR80Premix-00064_00024_v0__161108_101824_7597.request.schema.TimePerEvent = 35.0

This is somehow related to https://github.com/cms-PdmV/cmsPdmV/issues/789 @bbockelm

**Comment by amaltaro** [comment]
I wasn't very lucky setting these defaults to 1:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/ReDigi.py#L311

About the job splitting, I see this workflow is using 822 events per job, which is around the 35secs provided. So from the ReqMgr point of view, it's correct.

**Comment by bbockelm** [comment]
822 events / job @ 35 seconds-per-event = ~8 CPU hours.

At 4 cores, this is 2 wall-time hours.

Hence, 4x too short.

**Comment by amaltaro** [comment]
Well, we already had this long discussion in the past and I don't think we concluded anything.
Anyways I made this PR:
https://github.com/dmwm/WMCore/pull/6597/files

but before it got merged the issue seemed to have cleared out.

I'm happy to implement what's needed in WMCore, we just need to have a general agreement on this matter.
