### ISSUE TITLE
reqmgr2 to show which keys failed the input validation

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#7398]
Hi,

i noticed this return:
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: %d format: a number is required, not NoneType</p>
        <pre id="traceback"></pre>

is correct when a certain value is missing, but it's not clear for which key its missing/wrong. The message would be unclear if the input dictionary had multiple fields with 'None' value.

Could the message also return which key failed the value check?

**Comment by amaltaro** [comment]
Antanas, can you provide:
* timestamp for this request
* your dict/json input data
* the api used
Thanks

**Comment by anorkus** [comment]
arround Thursday, November 17, 2016 4:28 PM
the dict: http://pastebin.com/raw/F6RfpB5g
how many API's reqmgr2 has? Anycase we only do a POST request to cmsweb.cern.ch/reqmgr2/data/request

**Comment by amaltaro** [comment]
The error message above cannot be for this json you shared. Besides one problem in your json `ConfigCacheURL` should be `ConfigCacheUrl`, I'm able to inject it without any issues.

BTW, you probably do **not** want to set `ProcessingVersion=0`. Actually, if you never need this info, then don't provide `ProcessingVersion` at all. It will default to 1.

Can you try again the same json (with the two fixes I suggested)? If that works, please close this issue.

**Comment by anorkus** [comment]
any case the request was reinjected successfully later on. Also this is not bug or urgent request to be developed. 
For me the error message was puzzling as all the parameters were set. Just a low priority feature could be to display also the key which failed validation.

**Comment by amaltaro** [comment]
We do show the key for such validation failures, that's why I got puzzled it was not reported.

**Comment by anorkus** [comment]
hmmm, maybe it went to some generic error output. I was even more puzzled that it succeeded to inject on 2nd try.
