### ISSUE TITLE
ACDC stuck in Running?

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7415]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC2_EXO-RunIISummer15GS-07240_00440_v0__161109_102435_9874
According WMStats, this ACDC has one job that has been running for about 10 days.
I've been searching for logs in vocms0310 (agent that acquired the WQE), and I haven't found anything.

Could you please help us to understand what is going on?

**Comment by amaltaro** [comment]
Sorry for the delay. It's not stuck, there is a job executing in vocms0310
```
cmst1@vocms0310:/data/srv/wmagent/current $ condorq -const 'WMAgent_RequestName == "prozober_ACDC2_EXO-RunIISummer15GS-07240_00440_v0__161109_102435_9874"'
22735.10  2  108686 /data/srv/wmagent/v1.0.21.patch2/install/wmagent/JobCreator/JobCache/prozober_ACDC2_EXO-RunIISummer15GS-07240_00440_v0__161109_102435_9874/MonteCarloFromGEN/JobCollection_87170_0/job_947432/condor.22735.10.log T2_IT_Legnaro,T2_CH_CERN,T1_RU_JINR
```

If you see another issue with this request, then please reopen the ticket.
