### ISSUE TITLE
Adjustment of the splitting interface

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7419]
In the previous splitting interface, we had two parameters for the eventAwareLumiBased splitting, Optimal events per job and max events in a single lumi. (e.g. https://twiki.cern.ch/twiki/bin/view/CMSPublic/AssigningWorkflows#Assigning_TaskChains).
Now we only have one parameter, max_events_per_lumi. Why do we only have this one? Could we add the "Optimal events"parameter?

@vlimant

**Comment by amaltaro** [comment]
Thanks, Paola. A fix for this issue will be pushed to testbed in the next week.
