### ISSUE TITLE
priority search in reqmgr2

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7422]
what is the syntax to /reqmgr2/data/request? for searching by priority ?
what are all accepted search field, maybe there is a wiki I missed.

**Comment by amaltaro** [comment]
I don't think you can have a priority query, at least I couldn't find it in the code.
Have a look at this wiki: https://github.com/dmwm/WMCore/wiki/reqmgr2-apis

**Comment by amaltaro** [comment]
Better later than never:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L275:L294
