### ISSUE TITLE
AcquisitionEra mandatory in DQMHarvest

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7424]
was posting 

{
  "InputDataset": "/HLTPhysicsBunchTrains/Run2016H-09Nov2016-v3/DQMIO",
  "Group": "DATAOPS",
  "OpenRunningTimeout": 0,
  "Requestor": "vlimant",
  "ProcessingString": "09Nov2016",
  "ScramArch": "slc6_amd64_gcc530",
  "inputMode": "couchDB",
  "Memory": 7000,
  "PrepID": "Harvest-ReReco-Run2016H-evtSplitSkimP3-09Nov2016-v1-09Nov2016-0001",
  "DQMUploadUrl": "https://cmsweb.cern.ch/dqm/offline",
  "RequestType": "DQMHarvest",
  "TimePerEvent": 1,
  "DQMHarvestUnit": "byRun",
  "CouchDBName": "reqmgr_config_cache",
  "CMSSWVersion": "CMSSW_8_0_23",
  "RequestPriority": 900000,
  "DQMConfigCacheID": "947d11a5076ed983a3f9aaafd7a2b04c",
  "ConfigCacheUrl": "https://cmsweb.cern.ch/couchdb",
  "RequestString": "HARVEST-Run2016H-evtSplitSkimP3-09Nov2016-v1-HLTPhysicsBunchTrains-0",
  "CouchURL": "https://cmsweb.cern.ch/couchdb",
  "CouchWorkloadDBName": "reqmgr_workload_cache",
  "Campaign": "Run2016H",
  "GlobalTag": "80X_dataRun2_SPECIALHIGHPUFILL_v0",
  "DbsUrl": "https://cmsweb.cern.ch/dbs/prod/global/DBSReader",
  "SizePerEvent": 1500
}

and this failed with

<p>Invalid spec parameter value: Argument AcquisitionEra can't be None</p>

so I added it in Unified.
This is new and I am not sure the parameter is really necessary in itself in this type of request. Please advise

**Comment by amaltaro** [comment]
Hi Jean-Roch, AcquisitionEra/ProcessingString and ProcessingVersion should have no effect - as of now - for DQMHarvest, since it uses the dataset name for the output root file (DQMSaver).

If it's very unlikely that we'll ever want to change the root file AND you prefer it not to be mandatory here, then It should be simple to remove it for DQMHarvest only (or set a fake/whatever value). (?)

**Comment by amaltaro** [comment]
Actually, I take my question back. As we agreed a month ago, we would be enforcing AcqEra/ProcStr for all requests. It looks cleaner and more consistent.

**Comment by amaltaro** [comment]
There is nothing to change and injection was corrected in Unified. Closing

**Comment by vlimant** [comment]
Yes I changed the assignment to add that useless parameter, if that's what you call corrected. Making a useless parameter mandatory is not a good strategy IMO. But hey ...

**Comment by amaltaro** [comment]
It may become useful in a near future :)
