### ISSUE TITLE
TaskChain colliding output

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7431]
pdmvserv_task_MUO-RunIISummer16DR80Premix-00002__v1_T_161115_214602_1201
pdmvserv_task_MUO-RunIISummer16DR80Premix-00003__v1_T_161115_214616_3756

have finished with 200% completions.
no acdc, no other requests writing in it, the parent gen-sim is sane (as it produced other DR without duplicates).

both task of the chain write in the same dataset. Maybe we could have a protection for such case.

@mcremone @prozober FYI

**Comment by amaltaro** [comment]
Fixed by #7682
