### ISSUE TITLE
Set Watchdog MaxRSS in TaksChain

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7432]
please advise on how one can set the watchdog maxrss specific for each task of a chain.
It'd be great if this absence of assignment parameter for it would let it configure to maxrss+10MB.

**Comment by amaltaro** [comment]
The same way you set AcqEra/ProcStr. Thus you can provide a dictionary keyed by the task name.
E.g.: https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/Integration/TaskChainPyquenZeemumuJets_PU.json#L81

I'm closing this issue. Feel free to reopen it if you need more assistance or so.
