### ISSUE TITLE
Overflow errors?  exit code 73

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7434]
Over the last few days we have seen several workflows with exit code 73 - which has been tracked back to overflow errors in the past - sample list from today:
pdmvserv_task_BTV-RunIISummer15GS-00072__v1_T_161125_213611_6014 
pdmvserv_task_BTV-RunIISummer15GS-00073__v1_T_161125_213646_6031
pdmvserv_task_SUS-RunIISummer15GS-00196__v1_T_161125_233700_7116

error message is:
 Adding last 25 lines of CMSSW stdout:
Beginning CMSSW wrapper script
 slc6_amd64_gcc530 scramv1 CMSSW
Performing SCRAM setup...
Completed SCRAM setup
Retrieving SCRAM project...
Completed SCRAM project
Executing CMSSW
cmsRun  -j FrameworkJobReport.xml PSet.py
%MSG-i ThreadSetup:  (NoModuleName) 28-Nov-2016 03:45:45 EST pre-events
setting # threads 1
%MSG
28-Nov-2016 03:46:05 EST  Initiating request to open file /mnt/hadoop/store/mc/RunIISummer15GS/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/backup_MCRUN2_71_V1-v1/80000/287BC495-32B5-E611-ABD4-5065F381A2E1.root
28-Nov-2016 03:46:06 EST  Successfully opened file /mnt/hadoop/store/mc/RunIISummer15GS/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/backup_MCRUN2_71_V1-v1/80000/287BC495-32B5-E611-ABD4-5065F381A2E1.root
28-Nov-2016 03:46:07 EST  Closed file /mnt/hadoop/store/mc/RunIISummer15GS/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/backup_MCRUN2_71_V1-v1/80000/287BC495-32B5-E611-ABD4-5065F381A2E1.root
----- Begin Fatal Exception 28-Nov-2016 03:46:07 EST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=DataMixingModule label='mixData'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
Complete
process id is 18950 status is 73
CmsRunFailure
Message: Error running cmsRun
{'arguments': ['/bin/bash', '/tmp/glide_epFl6d/execute/dir_18299/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc530', 'scramv1', 'CMSSW', 'CMSSW_8_0_21', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Return code: 73

	ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
	MethodName : __init__
	ClassInstance : None
	FileName : /tmp/glide_epFl6d/execute/dir_18299/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
	ClassName : None
	LineNumber : 18
	ErrorNr : 73

Traceback:

**Comment by amaltaro** [comment]
Jen, if you don't mind I'll close this ticket because Jean-Roch created this one over the weekend:
https://github.com/dmwm/WMCore/issues/7428

and it's basically under control by now. A fix for this issue is going to be deployed in the next cmsweb upgrade.

**Comment by jenimal** [comment]
Didn't see the other ticket.  Thanks
