### ISSUE TITLE
reqmgr2 fetch MCPileup not functionning

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7435]
https://cmsweb.cern.ch/reqmgr2/data/request?status=acquired&mask=OutputDatasets&mask=InputDatasets&mask=MCPileup

sends me a 500 error. Can this please be fixed ?
Can MCPileup and InputDatasets also dives in the Task of the TaskChain/StepChain.

**Comment by ticoann** [comment]
That must be some glitch. The link works now.  Currently it only supports Workflow level filter (mask). I will add the test level filter as well.

**Comment by amaltaro** [comment]
It worked several during the day for me. However, it returns 500 with this example:
https://cmsweb.cern.ch/reqmgr2/data/request?request_type=TaskChain&status=announced&mask=MCPileup

**Comment by amaltaro** [comment]
Should be fixed now. Please reopen the issue if it pops up again.
