### ISSUE TITLE
Files missing in DBS and PhEDEx

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7439]
While proceeding with the draining of vocms0116, I noticed there are 41 files not uploaded to DBS and TMDB [1], where 4 files belong to the DQMIO tier.

Checking DBS and PhEDEx, the DQMIO dataset cannot be found. The other one has consistently 50 files.

I think these files were no injected because they don't have a valid `block_id` in the dbsbuffer_file. I'll have to investigate exactly where a dbsbuffer block is created and try to nail it down.

Should we trigger the data injection at this point? @vlimant 

BTW, this is the workflow normally completed and normal-archived
https://cmsweb.cern.ch/reqmgr2/data/request?outputdataset=/BdToKstarMuMu_BFilter_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISpring16DR80-PU2016_Classic_withHLT_80X_mcRun2_asymptotic_v14-v2/DQMIO

[1]
set(['/BdToKstarMuMu_BFilter_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISpring16DR80-PU2016_Classic_withHLT_80X_mcRun2_asymptotic_v14-v2/DQMIO',
     '/BdToKstarMuMu_BFilter_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISpring16DR80-PU2016_Classic_withHLT_80X_mcRun2_asymptotic_v14-v2/GEN-SIM-RAW'])

**Comment by vlimant** [comment]
for files belonging to a wf that is normal-archived, just trash the files please.

**Comment by amaltaro** [comment]
Thanks! I'm removing the agent code/data in order to make room for a new one, once we need it.
The code issue is still there to be fixed though

**Comment by amaltaro** [comment]
Also related to #7115, but keeping this one open for a bit longer.

**Comment by vlimant** [comment]
from #7610 if the transition to "completed" does not come with the certainty that all files were flushed from the agent in phedex and dbs it will be complicated to operate since either we put a timeout (completed+1 day) on checking request that are completed (and loose a day for all) or we need a new status that says completed-filesinjected to be able to tell.

**Comment by amaltaro** [comment]
There was a recent case reported in #8971. I'll close that one.

**Comment by amaltaro** [comment]
Due to the lack of activity and/or prioritization of this issue, I consider it no longer relevant and we shall close it.
There is a similar issue #8148 which should solve this problem, so I'm closing this one. Thanks!
