### ISSUE TITLE
Add changing default PhEDEx group in assignment gui

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#7440]
Having had DDM charge off and delete important data living in the default DataOps PhEDEx group, it would be useful to be able to change this when assigning workflows via the reqmgr2 gui.  Keep the default as dataops, but be able to change that to "local" or any of the other PhEDEx groups through a pickbox to be able to avoid DDM wiping away the results of tests, etc.  

Believe the attribute you'd change is this:

  "NonCustodialGroup": "DataOps", 

Maybe this is a pickbox along with each of the PhEDEx subscription options, though I'm not sure you'd want to mess with CustodialGroup

At minimum this is needed to circumvent overzealous DDM deletions of any kind of test.

**Comment by amaltaro** [comment]
Indeed we don't have these settings in the GUI. We can likely put it in place for January's cmsweb upgrade.

For now, you can have a look at this template and use the reqmgr2.py client for assigning your test workflows:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/MonteCarlo_PhEDEx.json#L65-L66

since you mostly use one kind of workflow, just adapt the template to your needs and use always the same.

**Comment by DAMason** [comment]
Actually that might be worse -- in my testing right now I'm setting the NonCustodialGroup to "local" and not doing anything with the CustodialGroup.  Next week though I'm going to talk to Natalia about creating a few more groups -- maybe something like "InProduction" and "Integration" or "Opportunistic".  "AnalysisOps" will have the same problem or worse since its also a group DDM knows about.   Also worry about abusing FacOps, since thats where the SAM test datasets live.

**Comment by hufnagel** [comment]
Tier0 uses AnalysisOps. IMO the default for non-custodial subscriptions should be AnalysisOps since if you subscribe a sample to a site from within the workflow, you by default want it in AnalysisOps (to not have DDM delete it out from under you).

**Comment by amaltaro** [comment]
Given the lack of activity in this ticket, I'm closing it.
