### ISSUE TITLE
high prio accounting group for condor

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7444]
There is this high priority accounting group feature in ITB (for emergency and very high priority workflows).

And we need to change the following classAd 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py#L239

to signalize those jobs are ultra important. So `acctGroup` value should be `highprio` instead of `production`.

Then we have to create a mechanism (aka another flag) that can be set during assignment and passed all the way down until the job submitter plugins. Maybe a boolean `HighPrio` attribute. 

How does it sound @ericvaandering @ticoann @vlimant
FYI @Farrukh-Aftab

**Comment by vlimant** [comment]
looks OK to me to have an assignment level parameter. we can also override in jobrouting.

**Comment by amaltaro** [comment]
Do you actually foresee using this assignment parameter? If not (only via jobRouter), then we should just make the simple changes at plugin level.

**Comment by Farrukh-Aftab** [comment]
IMO please do add a flag for assignment as well. This is supposed to be used after obtaining the green light from L1s/XEB. We can certainly do the modification with the job router as well, but it would be good to have that as a secondary options than the primary one.

**Comment by amaltaro** [comment]
That's my opinion as well, Farrukh. However, if people will mostly use it at JobRouter level (as it actually happens to tons of other job tweaks), then I'd rather invest time on something more fruitful.

**Comment by ericvaandering** [comment]
Seems to me we should aim to make the system functional without the mandatory interference of JobRouter. So I'd add it.

**Comment by amaltaro** [comment]
For reference:
https://cms-logbook.cern.ch/elog/GlideInWMS/4771

I'll try to get it done this week.

**Comment by amaltaro** [comment]
As just discussed with Seangchan, this change is much more complicated then just setting a different accounting group when someone instructs WMAgent to do so. Besides the RequestPriority, we would need to handle this different acctGroup differently since global workqueue, meaning:
 *) we must make sure these blocks always get replicated first (even if the RequestPriority=1 ...). Or make sure the highest priority inside each of these groups is replicated first
 *) job submitter would have to load ALL the jobs, then first sort by group, then within each group sort by job priority and only then submit.

In summary, we'd have to create another queue inside the agent to make sure it has higher priority, instead of simply using the RequestPriority (or the JobPrio for job submission).

Thus, to avoid having different queues in the agent and use one single parameter for defining what should go first or not, how about we define a RequestPriority range that would imply a `highprio` accounting group? Let's say the supported RequestPriority is between 0 and 100, and we call anything greater or equal to 91 as `highprio`.

Of course this needs a handshake among several groups, but it would certainly be the least error prone implementation.

**Comment by ericvaandering** [comment]
Per discussion just with Alan and me... I agree completely with @amaltaro above. :-)

**Comment by Farrukh-Aftab** [comment]
This would mean that jobs with >=91 won't be the norm right? I am assuming you meant 91k+ in HTCondor. Highprio accounting is only supposed to be used with explicit permission of XEB/L1s.

**Comment by ericvaandering** [comment]
Right. I think the real level we might use is 120K or even higher. 110K jobs we already have and as Alan pointed out we may have to adjust the priority used by RelVal down under the threshold. Following this proposal means changing "Highprio accounting is only supposed to be used with explicit permission of XEB/L1s." to "Submission of workflows with priority over XXX is only supposed to be used with explicit permission of XEB/L1s."

**Comment by Farrukh-Aftab** [comment]
Thanks for the clarification! That works perfectly!

**Comment by vlimant** [comment]
I am not too much in favor or mapping a priority range to this high priority (also would it work if priority is changed on the fly?)
The issue of having work going through all queues faster is not a pb imo, we have observed that this works well and fast enough (unless you have indication otherwise).
Only in htcondor people would like to have the jobs not wait in line.
How about tying this parameter to the highprio team ? i.e only workflow in that team get the flag. 
And we allow ourselves to jobroute it further.

**Comment by amaltaro** [comment]
> I am not too much in favor or mapping a priority range to this high priority (also would it work if priority is changed on the fly?)

It would actually be a threshold, anything above that priority maps to highprio group. The priority change on the fly would be an extra, it shouldn't be that complicate to implement it.

>  Only in htcondor people would like to have the jobs not wait in line.

This was my initial understanding. However, if we want to make it right (i.e., not delay such requests in WMAgent), we need to *guarantee* they will carry the highest priorities in the system.
IF we agree on this, then we can add another argument to the request spec that is set during assignment and gets propagated down to the submission plugins (when the highprio group is set).

>  How about tying this parameter to the highprio team ? i.e only workflow in that team get the flag.

I don't think it's a good idea. Eventually it will become a nightmare to manage these agents and how much highprio slots are needed.

**Comment by amaltaro** [comment]
FYI @ddavila
