### ISSUE TITLE
OpenRunningTimeout default value for resubmission

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7460]
as far as I can tell, in "Recovery", that parameter is not passed along in making the schema and yet

https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_recovery-4-cerminar_Run2016D-v2-SingleElectron-23Sep2016_8020_161209_121038_4682

  "OpenRunningTimeout": 43200

there are several of them <12h old all with no more work, staying in running-open.
Should we set that parameter to 0 in recovery, or omitting will default to 0 ?

**Comment by amaltaro** [comment]
Recovery is an ACDC, thus it inherits all information from the parent/original workflow.
Can you please try setting it to 0 during injection time (not assignment)?
I'm not sure this overwrite will work since not all arguments can be overwritten for Resubmission spec.

**Comment by vlimant** [comment]
let's try that an see.

**Comment by vlimant** [comment]
Did you really assign this to me ? ;-)
I think closing is fine.

**Comment by amaltaro** [comment]
Given the "let's try that an see.", I thought it was reasonable to wait for your feedback :)
Ok, closing it then. Thanks!
