### ISSUE TITLE
Multicore at assignment time for ACDC

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7463]
I thought Multicore could be set during assignment and we went ahead like this for 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161211_012840_7645

but it did not work. This was assigned with 

{'AcquisitionEra': u'Run2016H',
 'CustodialSites': [],
 'Dashboard': 'reprocessing',
 'MaxMergeEvents': 50000,
 'MaxMergeSize': 4294967296,
 'MaxVSize': 4294967296,
 'Memory': 50000,
 'MergedLFNBase': u'/store/data',
 'MinMergeSize': 2147483648,
 'Multicore': 24,
 'ProcessingString': u'09Nov2016',
 'ProcessingVersion': 1,
 'SiteBlacklist': [],
 'SiteWhitelist': ['T2_US_Nebraska'],
 'SoftTimeout': 159600,
 'Teamproduction': 'checked',
 'TrustSitelists': True,
 'UnmergedLFNBase': '/store/unmerged',
 'action': 'Assign',
 'checkboxmcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161211_012840_7645': 'checked',
 'execute': True}

so, is this supposed to work ?
FYI @mcremone

**Comment by vlimant** [comment]
#7285 related ?
#7393 indicated we should be able to overide that value.

**Comment by amaltaro** [comment]
Something is not right here. The workflow you pointed out was not assigned with Multicore: 24, but with 4 cores only.

Perhaps you're mixing it up with 
vlimant_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161211_100827_7812

which was properly assigned with Multicore: 24 and so is its task.

**Comment by vlimant** [comment]
I can ensure you that the dictionnary that was passed at assignment stated Multicore: 24 for mcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161211_012840_7645

the second one, we edited the json of recovery by hand to make it work.

hence the GH issue of not being able to overwrite Multicore for Resubmission.

**Comment by amaltaro** [comment]
Indeed it sets the new value only for the top level. Checking...
