### ISSUE TITLE
Missing file in Phedex - vocms0309

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7464]
We have a problem with https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_SUS-RunIISummer16DR80-00001_00029_v1__161128_135931_9429 at vocms0309.

The file /store/mc/RunIISummer16DR80/QCD_Pt-20to30_EMEnriched_TuneCUETP8M1_13TeV_pythia8/GEN-SIM-RAW/FlatPU28to62HcalNZSRAW_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/60000/16A3DAD9-A3B5-E611-9FB0-001E674DA347.root
is missing in Phedex.
As we saw in the agent's logs, there are 141 records of files injected in Phedex (block /QCD_Pt-20to30_EMEnriched_TuneCUETP8M1_13TeV_pythia8/RunIISummer16DR80-FlatPU28to62HcalNZSRAW_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/GEN-SIM-RAW#bfdf9cbc-b587-11e6-b8e0-001e67abf094), but in DBS are 142 files for that block.

Could you please help us to figure out what happened?
Thanks.

**Comment by amaltaro** [comment]
According to dbsbuffer_block and dbsbuffer_file, all 142 files were injected in both DBS and TMDB.

Investigating the PhEDExInjector logs, I counted exactly 142 files as well:
```
cmst1@vocms0309:/data/srv/wmagent/current $ FILES=0; grep -r 'GEN-SIM-RAW#bfdf9cbc-b587-11e6-b8e0-001e67abf094' install/wmagent/PhEDExInjector/ComponentLog | grep 'About to inject' | awk '{FILES+=$5}END{printf("total files: %d\n",FILES)}'
total files: 142
```

Could it be someone else (site admin, etc) asked the transfer team to invalidate this file?

**Comment by vlimant** [comment]
when I did that count a couple of days ago, it came out to 141 ... I am extremely puzzled.

**Comment by vlimant** [comment]
could the log specify the file name in the future, so that we have an exact listing of the files ?

**Comment by amaltaro** [comment]
It could, but since LFNs are quite big, it's very likely these logs will become very hard to look/parse for heavy agents. Without mentioning very very large lines.

**Comment by vlimant** [comment]
how do we know then that a file was not injected twice ?

**Comment by amaltaro** [comment]
We have unique LFNs in the database and there is a transaction for the file injection. There can't be double injection for the same file (and I'd expect PhEDEx to return 4xx or 5xx for that).

So the file was invalidated but nobody knew until yesterday. That's where the "file missing" comes from. I'm closing this issue, reopen if needed.
