### ISSUE TITLE
Handling Blocks with only Invalid Files

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7466]
maybe related to #7448 , sorry for the duplication if already adresse somewhere else

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_BTV-RunIISummer16DR80Premix-00044__v1_T_161202_192530_174

 is there waiting for /QCD_Pt_3200toInf_TuneCUETP8M1_13TeV_pythia8/RunIISummer15GS-MCRUN2_71_V1-v1/GEN-SIM#50dd62ca-79b7-11e5-9a2d-a0369f23d050 which has only invalid files that were removed from TMDB (phedex does not know about the block anymore).

I am going to force complete it, but we need a way to update the GQ to push the WQE to Done (or whatever) if it has no more existence in phedex.

A complication @sidnarayanan is if the files/block disappear from TMDB after the workflow is assigned (assignment with partial data on disk), which I think is the case here, how does this work and how do we get the workflow to naturally move forward (i.e. not having me make a unified check to force-complete it)

**Comment by amaltaro** [comment]
Closing it as dup of #7441 , where we already started discussing this issue. Please reply over there.
