### ISSUE TITLE
Merge jobs skipping ALL input files - exit code 60450

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7467]
As reported by @prozober in this Jira: https://its.cern.ch/jira/browse/CMSCOMPPR-328

merge jobs are failing quite often in T2_AT_Vienna with exit code 60450, which basically means there was no output files in the report file (besides logArch). Taking a look at the condor logs, not all of them have errors, so these jobs should succeed. However, you can see there were no files merged and no merged file stage out (only the logArch).

I managed to find the following log in vocms0130
install/wmagent/JobArchiver/logDir/p/pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902/JobCluster_4127/Job_4127624.tar.bz2

which was not copied over here:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7467/

I also unpickled the job config (job.pkl) and one of the reports (Report.3.pkl).

Looking at the job configuration, we can see the list of `input_files`, though I don't know if the structure/values are correct (especially the `'merged': True,`).

Then looking at the report file, we can see that all the unmerged files were skipped ?!?

**Comment by amaltaro** [comment]
And just in case, a snapshot of what we have in wmstats for this job:
```
Job Name: f0a1cde0-bcec-11e6-92fb-02163e01820e-0
WMBS job id: 4127624
Workflow: pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902
Task: /pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902/Production/ProductionMergeRAWSIMoutput
Status: jobfailed
Input dataset: undefined
Site: T2_AT_Vienna
Agent: vocms0130.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
jobcooloff: 2016/12/8 (Thu) 03:08:04 UTC, T2_AT_Vienna
jobcooloff: 2016/12/8 (Thu) 03:48:25 UTC, T2_AT_Vienna
jobcooloff: 2016/12/8 (Thu) 05:42:01 UTC, T2_AT_Vienna
jobcooloff: 2016/12/8 (Thu) 12:17:59 UTC, T2_AT_Vienna
jobfailed: 2016/12/9 (Fri) 01:28:18 UTC, T2_AT_Vienna
Exit code: 60450
Retry count: 4
Errors:
logArch1
cmsRun1
NoOutput (Exit Code: 60450)
No output files present in the report
stageOut1
ReportManipulatingError (Exit Code: 99999)
Could not find report file for step stageOut1!
Input files:
Lumis:
Output:
logArchive
lfn: /store/unmerged/logs/prod/2016/12/9/pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902/Production/ProductionMergeRAWSIMoutput/0000/4/f0a1cde0-bcec-11e6-92fb-02163e01820e-0-4-logArchive.tar.gz
location: null
pfn:
checksums: adler32: b7e9ec99
size: 0
log archive
root://castorcms.cern.ch//castor/cern.ch/cms/store/logs/prod/2016/12/WMAgent/pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902/pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902-ProductionRAWSIMoutputMergeLogCollect-r4b1d-8-logs.tar
```

**Comment by vlimant** [comment]
found on eos
/store/logs/prod/2016/12/WMAgent/pdmvserv_EXO-RunIISummer15wmLHEGS-01962_00249_v0__161123_003115_4307/pdmvserv_EXO-RunIISummer15wmLHEGS-01962_00249_v0__161123_003115_4307-ProductionLHEoutputMergeLogCollect-r4b18-7-logs.tar

where all input files are indeed skipped, and no root file can be created because not a single file is opened.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge jobs skipping ALL input files - exit code 60450](https://trello.com/c/AZUeFZD7/4-merge-jobs-skipping-all-input-files-exit-code-60450)
