### ISSUE TITLE
WMWorkload helper can't be used for "some" requests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7468]
Maybe it will never be fixed ... but CompOps use this class in some of their scripts (like resubmit.py) and they noticed calls like `helper.getAcquisitionEra()` started failing for some requests, e.g.:
```
>>> workflowName = "pdmvserv_EXO-RunIISummer15wmLHEGS-01970_00249_v0__161123_003233_2902"
>>> helper.getProcessingString()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.0.23/sw.sryu/slc6_amd64_gcc493/cms/wmagent/1.0.23/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 790, in getProcessingString
    return self.data.properties.processingString
AttributeError: 'ConfigSection' object has no attribute 'processingString'
```

Apparently it fails because this request was created/assigned before we put this PR in place https://github.com/dmwm/WMCore/pull/7400

It also fails if I try to retrieve this attr from the previous object/node
```
>>> helper.acquisitionEra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: WMWorkloadHelper instance has no attribute 'acquisitionEra'
```

It seems these attr would be set only in the tasks section of the workload object.

@ticoann I remember you telling me something like reqmgr1 was not using this class to set some of those properties (or something like that). Maybe you still remember that.

@vlimant @prozober I suggest you start moving away of WMCore code (use apis instead) to avoid such problems. 

BTW, this issue doesn't seem to hit production. I'm running a 2 months old workflow and jobs are also succeeding.

**Comment by ticoann** [comment]
@vlimant @prozober, could you send me the requests which failing with this error? Are these request created relatively long time ago.

In general, 
_helper.getProcessingString(), helper.getAcquisitionEra()_ should work but not _helper.processingString, helper.acquisitionEra_

**Comment by amaltaro** [comment]
Seangchan, one of them was created on Nov 23 (see workflow name above).

The previous code had `self.acquisitionEra = blah` in the setter method. That's why I tried to get that attr with `helper.acquisitionEra`

**Comment by amaltaro** [comment]
So the resubmit code was updated to use the request dictionary (reqmgr2 api) instead of the workload object. As discussed with Seangchan, there is nothing to be updated in the code, thus I'm closing this issue.
