### ISSUE TITLE
when agent is set to drain, automatically pick up the config change

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7494]

**Comment by amaltaro** [comment]
Which config change are you talking about? The speed draining tweaks?

**Comment by ticoann** [comment]
I am talking about WMAgentConfig.py (config.py) when we change the config to drain. We have to restart the component. I am thinking about that the component automatically picking up the config changes. 

However, I think it might be better to have this control in central location (db). So ops can set it without logging into the machine. We can discuss further.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [when agent is set to drain, automatically pick up the config change](https://trello.com/c/27dlKX3o/34-when-agent-is-set-to-drain-automatically-pick-up-the-config-change)

**Comment by amaltaro** [comment]
I think we can close this issue, can't we? I tested updating `UserDrainMode` flag in aux db and both components (AgentStatusWatcher and WorkQueueManager) picked up that config and stopped pulling work.

Haven't checked the `AgentDrainMode` mode though.
