### ISSUE TITLE
Flag to enable agent speedy draining

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7495]
FYI speeding up drain section in
https://twiki.cern.ch/twiki/bin/view/CMSPublic/AgentDraining#Starting_to_drain
And Alan's script
https://github.com/amaltaro/ProductionTools/blob/master/drainAgent.py

@amaltaro, Alan could you add more information on this ticket. what need to be done and what script is available.

Updating this first comment to have all the proposed changes here:
Just to summarize what we discussed during the meeting:
* maxRetries configuration goes to the auxiliar db (thus no component restart will be needed)
* change the DrainStatusPoller polling cycle to 2h instead of 12h.
* we add a SpeedyDrainConfig to the auxiliar db with something like
`SpeedyDrainConfig = {'retryThreshold': 500, 'siteThreshold': 200, 'pendingThreshold': 300}`

such that the agent can perform the automatic tweak based on those thresholds. Their meaning is:
* retryThreshold: once the agent has less than X jobs running+pending in condor, the agent sets maxRetries to 0.
* siteThreshold:once the agent has less than Y jobs running+pending in condor, the agent disables AgentStatusWatcher and enables all sites and bump thresholds, see  https://github.com/dmwm/WMCore/wiki/Draining-Steps#enabling-all-sites
* pendingThreshold: once the agent has less than Z jobs pending in condor, the agent changes their priority to 888888.

**Comment by amaltaro** [comment]
@ticoann @goughes I've just updated this twiki documentation for speed draining an agent:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/AgentDraining#Speeding_Up_Draining

I suggest we start implement the first 2 sections only. The third may not be needed and the 4th should be done by operators only.

About identifying stuck workflows, there are several different cases. The first and easiest case is when we have workflows in a final (*-archived) or semi-final state (aborted, closed-out, announced, rejected) and still not completed in the agent. For most of those cases, we can use the same logic as in https://github.com/dmwm/WMCore/blob/master/bin/kill-workflow-in-agent , since the workflows were aborted or already announced.

**Comment by ticoann** [comment]
@goughes, @amaltaro Thanks Alan, I also created document https://github.com/dmwm/WMCore/wiki/Draining-Steps.

For that particular  stuck workflow case, it should be taken care now with the periodic killing job patch applied in production agents.

**Comment by amaltaro** [comment]
Finally getting back to it. The latest draining campaign went much more smoothly and the only issues we had was related to this issue https://github.com/dmwm/WMCore/issues/8334 (which I still don't know what happen).

Nonetheless, I wrote a "Speedy draining" section to the WMCore/wiki that Seangchan created and I think that would be interesting to have in the agent.

**Comment by goughes** [comment]
Alan, I looked at your speedy draining section and I'm working on the implementation in the agent and had a couple questions.

1. Should the setting max retries to 0 part of speedy draining be an option that can be set (maybe in aux db) or happen automatically at the 500 job threshold?
2. Same for enabling all sites, should it be automatic at 100 jobs?

I'm thinking the agent could drain normally by setting DrainMode to true and speed drain if another option like SpeedDrain is also true.  Let me know your thoughts.

**Comment by amaltaro** [comment]
Hey Erik,
> I'm thinking the agent could drain normally by setting DrainMode to true and speed drain if another option like SpeedDrain is also true.

this sounds like a great idea. I agree, we only enable speedy draining if someone sets it (SpeedDrain parameter or so) to true in the WMAGENT_CONFIG auxiliar doc.

**Comment by amaltaro** [comment]
Just to summarize what we discussed during the meeting:
* maxRetries configuration goes to the auxiliar db (thus no component restart will be needed)
* we add a SpeedyDrainConfig to the auxiliar db with something like
`SpeedyDrainConfig = {'retryThreshold': 500, 'siteThreshold': 200}`

such that we perform the automatic tweak based on those thresholds (below 500 jobs, or below 200 jobs for site, etc)

**Comment by amaltaro** [comment]
@goughes @ticoann I updated the title and description of this issue at the very top. Let me know your thoughts

**Comment by goughes** [comment]
Alan and I discussed details of the speed drain.  Here is the current plan:

- Update drain thread polling from 12 hours to 1 hour
- Don't have a speed drain flag, just go into speed drain mode at the thresholds defined by 'SpeedyDrainConfig' dictionary. 
- Criteria for updating any agent configuration: if drain mode and a valid speed drain config
- Rename key name in dictionary so they are more meaningful
- Add 3rd "priority" threshold, if below a number of jobs (500), bump all jobs' condor prio to 999999

Will make new Issue/PR for reverting the speed drain changes if someone takes an agent out of drain mode.

**Comment by amaltaro** [comment]
@goughes Erik, about the job priority bump, we might do something equivalent to:
`condor_qedit -const 'JobStatus=?=1 && (CMS_JobType =?= "Production" || CMS_JobType =?= "Processing")' JobPrio 999999`

the other job types already have a very high JobPrio.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/8555

Just a few remarks worth mentioning:
*) `SpeedDrainMode` is meant to be used by the agent only, when it matches the other constraints.
*) Ops can change the thresholds in `SpeedDrainConfig`, but not the status, which is also going to be automatically updated by the agent 
*) in order to disable that feature, one can set the thresholds to 0
