### ISSUE TITLE
Submit failed to site that are not in drain

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7503]
I was looking at https://cmst2.web.cern.ch/cmst2/unified/report/vlimant_task_JME-RunIISummer16DR80-00006__v1_T_170103_111641_3417 that failed submit from agent 303 and some of the sites are/were not in drain at any point other the past few days.

Could not trace anything in 303 logs, so there is something very fishy.

https://its.cern.ch/jira/browse/CMSCOMPPR-369

**Comment by ticoann** [comment]
It seems the jobs overflow to the sites which is not in the site white list.
I didn't check all the failed jobs but it seems the site it ran was T1_UK_RAL, T2_US_Purdue, etc
Although they are proper location but not in the site white list.  

"SiteWhitelist":["T1_DE_KIT","T1_RU_JINR","T1_FR_CCIN2P3","T1_US_FNAL","T2_US_MIT","T2_US_Nebraska"]

@amaltaro, Are we supposed to handle this cases? I am not sure why it is only happening in only vocms0303 (Is this only agent doing overflow by unified?)

**Comment by vlimant** [comment]
this is very common use case that has been supported for a long time. The overflow is regular and indeed can end up outside of the site whitelist, so can it happen with stageout fallback.
It should be fine and has been fine all along, unless there is something new.

**Comment by vlimant** [comment]
please look at this one
https://cmst2.web.cern.ch/cmst2/unified/report/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500
failed over the last couple of day, at RAL within the whitelist and not in drain. in agent 311, there isn't anything indicating RAL was in seen in drain.

**Comment by ticoann** [comment]
Hi Jean-Roch, I looked at the link above and check one of the submit failed job. 

````
Job Name: 059ecd2a-d259-11e6-a223-001e67abef8c-0
WMBS job id: 4031039
Workflow: vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500
Task: /vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500/B2G-RunIISummer16DR80Premix-00939_0/B2G-RunIISummer16DR80Premix-00939_1
Status: jobfailed
Input dataset: /Graviton2PBToWW_width0p1_M-750_13TeV-JHUgenV7-pythi8/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM
Site: Unknown
Agent: vocms0311.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
Exit code: 71101
Retry count: 3
Errors:
JobSubmit
SubmitFailed (Exit Code: 71101)
No sites are available to submit the job because the location of its input(s) do not pass the site whitelist/blacklist restrictions (WMAgent).: Job is created before this patch. Please check this input for the jobs: [] 
Input files:
Lumis:
Output:
log archive:
```

In the job report it says site whitelist is [u'T0_CH_CERN'] and input file is at  ['T1_UK_RAL']

```
{'agentNumber': 8,
 'allowOpportunistic': False,
 'attachments': {},
 'cache_dir': u'/data/srv/wmagent/v1.0.21.patch3/install/wmagent/JobCreator/JobCache/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500/B2G-RunIISummer16DR80Premix-00939_0/B2G-RunIISummer16DR80Premix-00939_1/JobCollection_613440_0/job_4031039',
 'couch_record': None,
 'counter': 64,
 'custom': {},
 'estimatedDiskUsage': 2856000.0,
 'estimatedJobTime': 8925.0,
 'estimatedMemoryUsage': 5900.0,
 'fileLocations': set(['T1_UK_RAL']),
 'fwjr': None,
 'fwjr_path': None,
 'id': 4031039,
 'inputDataset': None,
 'inputDatasetLocations': ['T1_UK_RAL'],
 'input_files': [{'avgEvtsPerLumi': 136.0,
                  'checksums': {},
                  'events': 816,
                  'first_event': 0,
                  'id': 8604472,
                  'last_event': 0,
                  'lfn': '/store/unmerged/RunIISummer16DR80Premix/Graviton2PBToWW_width0p1_M-750_13TeV-JHUgenV7-pythi8/GEN-SIM-RAW/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/80000/5EA7EB2B-50D2-E611-A4A3-0025901D4AFE.root',
                  'locations': set([]),
                  'lowestRun': <WMCore.DataStructs.Run.Run object at 0x7f0740d93f90>,
                  'lumiCount': 6,
                  'merged': True,
                  'minrun': 1,
                  'newlocations': set(['T1_UK_RAL_Disk']),
                  'parents': set([]),
                  'runs': [<WMCore.DataStructs.Run.Run object at 0x7f0740d93f90>],
                  'size': 1378462070}],
 'jobType': 'Processing',
 'jobgroup': 613440,
 'location': None,
 'mask': {'FirstEvent': None,
          'FirstLumi': None,
          'FirstRun': None,
          'LastEvent': None,
          'LastLumi': None,
          'LastRun': None,
          'inclusivemask': True,
          'runAndLumis': {1: [[127, 129], [163, 165]]}},
 'name': '059ecd2a-d259-11e6-a223-001e67abef8c-0',
 'numberOfCores': 4,
 'outcome': 'failure',
 'owner': 'vlimant',
 'ownerGroup': 'unknown',
 'ownerRole': 'unknown',
 'possiblePSN': set([]),
 'retry_count': 0,
 'sandbox': '/data/srv/wmagent/v1.0.21.patch3/install/wmagent/WorkQueueManager/cache/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500-Sandbox.tar.bz2',
 'scramArch': 'slc6_amd64_gcc530',
 'siteBlacklist': [],
 'siteWhitelist': [u'T0_CH_CERN'],
 'spec': '/data/srv/wmagent/v1.0.21.patch3/install/wmagent/WorkQueueManager/cache/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500/WMSandbox/WMWorkload.pkl',
 'state': 'new',
 'state_time': 1483519046,
 'swVersion': 'CMSSW_8_0_21',
 'task': '/vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500/B2G-RunIISummer16DR80Premix-00939_0/B2G-RunIISummer16DR80Premix-00939_1',
 'taskType': 'reprocessing',
 'workflow': 'vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500'}
```

The weird thing is, if you look at the spec file, top level site white list is set to  ['T1_UK_RAL'] but 
the task level is set to  [u'T0_CH_CERN']

https://cmsweb.cern.ch/reqmgr2/config?name=vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500


```
vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500.tasks.B2G-RunIISummer16DR80Premix-00939_0.constraints.sites.whitelist = [u'T1_UK_RAL']


vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500.tasks.B2G-RunIISummer16DR80Premix-00939_0.tree.children.B2G-RunIISummer16DR80Premix-00939_1.constraints.sites.whitelist = [u'T0_CH_CERN']
```

**Comment by ticoann** [comment]
> this is very common use case that has been supported for a long time. The overflow is regular and indeed can end up outside of the site whitelist, so can it happen with stageout fallback.
> It should be fine and has been fine all along, unless there is something new.

Hmm, this is weird. Looking at the code if overflow falls to outside site white list, it doesn't work. And I don't think that part of code changed recently. (When it is outside the site white list, It only works if out put of job is not used as input of of other jobs or trusted site list is set to True). I will try to investigate more.

**Comment by vlimant** [comment]
vlimant_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170103_150334_5500 was cloned from pdmvserv_task_B2G-RunIISummer16DR80Premix-00939__v1_T_161205_010249_7838 which initially was assigned to T0_CH_CERN. It looks like something was left other from the cloning and not overiden in assignment.

**Comment by vlimant** [comment]
same for 

vlimant_task_JME-RunIISummer16DR80-00006__v1_T_170103_111641_3417.tasks.JME-RunIISummer16DR80-00006_0.tree.children.JME-RunIISummer16DR80-00006_1.constraints.sites.whitelist = [u'T1_DE_KIT', u'T1_RU_JINR', u'T1_FR_CCIN2P3', u'T1_US_FNAL', u'T2_US_MIT', u'T2_IT_Legnaro', u'T2_US_Nebraska', u'T2_IT_Pisa']

very interesting ...

**Comment by vlimant** [comment]
I put 10CHF on Alan telling me to get rid of

vlimant_task_JME-RunIISummer16DR80-00006__v1_T_170103_111641_3417.request.schema.SiteWhitelist = [u'T1_DE_KIT', u'T1_RU_JINR', u'T1_FR_CCIN2P3', u'T1_US_FNAL', u'T2_US_MIT', u'T2_US_Nebraska']

**Comment by ticoann** [comment]
Ah, so original workflow has site white list (T0_CH_CERN) and it wasn't cleaned up. That explains. what can we by with 10CHF? 😄

Anyway, looking at the code again, I am doubtful  it worked before when overflow is outside the site white list and output of that job is used for other jobs input. However if that is case to handle we can change the code. (Need to think about whether there is other side effect doing that).

**Comment by hufnagel** [comment]
Why wouldn't it work ? Site whitelist should only be relevant for top level tasks, they should not be considered at all for other tasks. They are definitely not considered for merges.

**Comment by vlimant** [comment]
I am pretty sure that overflowing outside of the original sitewhitelist has functioned very well, not sure how to present you with a current example. I have removed SiteWhitelist in cloning for unified, up to you to decide whether this has to be fixed on handling new requests too.

**Comment by ticoann** [comment]
I might be wrong but here is the reason I thought it is not working.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/JobFactory.py#L192

**Comment by ticoann** [comment]
A fix is created #7507

**Comment by vlimant** [comment]
Further on this issue, looks like the ACDC are created with the wrong data locations.

Two cases:
 a) https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIISummer16DR80Premix-00939 failed at RAL (because internal whitelist was T0) the ACDC was assigned to RAL, but then again 

vlimant_ACDC0_task_B2G-RunIISummer16DR80Premix-00939__v1_T_170105_134942_6929.tasks.B2G-RunIISummer16DR80Premix-00939_1.tree.children.B2G-RunIISummer16DR80Premix-00939_1MergeAODSIMoutput.tree.children.B2G-RunIISummer16MiniAODv2-00230_0.constraints.sites.whitelist = [u'T0_CH_CERN']
 and failed.

 b) https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIISummer16DR80Premix-01642 failed a bit everywhere because it was overflown (and internal whitelist was T0) the ACDC was assigned to 
"SiteWhitelist": [
    "T2_US_UCSD", 
    "T2_US_Wisconsin", 
    "T2_US_Florida", 
    "T2_US_MIT", 
    "T2_US_Caltech", 
    "T1_US_FNAL", 
    "T2_US_Purdue", 
    "T2_US_Nebraska", 
    "T2_CH_CERN"
  ], 
because this is the data location in the ACDC doc

https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22vlimant_task_EXO-RunIISummer16DR80Premix-01642__v1_T_170103_151558_8891%22&include_docs=true&reduce=false

while the data are not there for sure. So it looks like the ACDC doc was created wrong.

the assign.py goes an fetch the sites from the acdc doc for assignment, and therefore it has been assigned to the wrong sites, is this expected ? 

FYI @prozober

**Comment by vlimant** [comment]
for b), sorry for being sloppy, those are unmerged files with indeed the proper locations.

**Comment by vlimant** [comment]
and 
vlimant_ACDC0_task_EXO-RunIISummer16DR80Premix-01642__v1_T_170105_134533_2639.tasks.EXO-RunIISummer16DR80Premix-01642_1.tree.children.EXO-RunIISummer16DR80Premix-01642_1MergeAODSIMoutput.tree.children.EXO-RunIISummer16MiniAODv2-02272_0.constraints.sites.whitelist = [u'T0_CH_CERN']

**Comment by ticoann** [comment]
For a)
Actually, Alan pointed me out that site white list is set only top level.  So child task shouldn't set the site white list at all. I am not sure how the child task site white list is set in these workflows.
But we will add protection so site list won't be set for child tasks.

For b) so there is no problem of ACDC location, right?

**Comment by vlimant** [comment]
b) yes, false alarm.
a) yes, cloning with SiteWhitelist is what caused the issue. 10CHF for me !

**Comment by amaltaro** [comment]
SiteWhitelist is no longer supported at request Creation, and I saw Seangchan made a fix at some point. Closing this one, please reopen if there are still issues to be solved.
