### ISSUE TITLE
Support SLC7 workflows in WMAgent

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7512]
As discussed during the WMAgent meeting, we should start having CMSSW releases built in SLC7 (EL7?) within a few weeks/month.

Thus we have to make sure WMAgent will set the proper `REQUIRED_OS` in the job jdl. Right now it either supports `rhel6` or `any` (meaning whatever the resource OS is, accept it).

We still need to figure out which convention to use for these SLC7 workflows ... asking in CompOps.

**Comment by ericvaandering** [comment]
From discussion with Farrukh and co:

Eric:  there is a bit of a hitch (not for GlideinWMS). We have releases that will have an EL6 flavor and an EL7 flavor. Jobs in a workflow should be able to run on either flavor or machine, but we need to detect in the runtime which we landed on and adjust accordingly. Is the info we get from the request and our interaction with the tag collector robust enough to handle multiple arches in a workflow for a single release string? If so, we configure the JDL to run on either and then detect in WMRuntime.

Farrukh: the corresponding matching value for some OSG sites is: GLIDEIN_REQUIRED_OS = rhel7
I think the factory ops are going to use the same convention for CMS resources too. I have added Jeff to CC so he may confirm. The corresponding job class is "REQUIRED_OS". If you put 'any', you can match any resource irrespective of the OS. If you specify an OS, we match to 'GLIDEIN_REQUIRED_OS' advertised by the factory per the directives of the site admins.

**Comment by hufnagel** [comment]
We don't want to match to any. We want to match to rhel6 or rhel7. There could be other architectures out there, any will literally match to anything, which is not what we want.

@ericvaandering , so this will be set in the workflow that we can use two different scram arch, we ask for "rhel6 OR rhel7" in GLIDEIN_REQUIRED_OS and the runtime code figures out what GLIDEIN_REQUIRED_OS matched on ? Or will the runtime code figure out SL6 or SL7 based on something else ?

**Comment by ericvaandering** [comment]
I guess we will have to see. We could either determine what it matched on or what the OS itself tells us. Maybe class ad is the easiest, especially since the same runtime code is already (now) looking at nCores. :-)

**Comment by ericvaandering** [comment]
Ok, so how do we go about this intelligent switch where we can run the same workflow under multiple architectures? 

It looks to me like the detection of which OS we landed on can be done in src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py

Should the request have 
```"ScramArch": "slc6_amd64_gcc530", ```
turned into having the possibility of a list of strings? How does ScramArch get converted into the GLIDEIN_REQUIRED_OS?

**Comment by amaltaro** [comment]
Fixed by #7527, #7586, #7579 and #7584
Please reopen if you think it should remain opened.
