### ISSUE TITLE
Add support to CMSSW number of streams 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7515]
It should have exactly the same behaviour as Multicore arg, thus:
*) can be set during request creation (defaults to 0)
*) can be overriden during request assignment
*) can have different values for different tasks in the same request

Disclaimer: It would be trick to handle it in resizable jobs, so we decided to set `numberOfStreams` to the same value as `numberOfThreads`, at least to begin with.

@ericvaandering @ticoann please correct/complement if I missed something.

**Comment by hufnagel** [comment]
I don't understand the disclaimer. So this will only be usable for non-resizable jobs then ?

**Comment by amaltaro** [comment]
Yes. Meaning Unified needs to know what can be resizable or not.
We cannot really block it from WMCore because the condor ad can be enable at any point (so blocking during submission is useless).

**Comment by hufnagel** [comment]
Lets say we have N streams and M threads. M is the usual Multicore setting and defaults to 1. N shouldn't default to 1, it should default to 0 or M (which is the same thing for the framework).

If N is not equal M that just means the job is not resizable and Unified needs to honor that. Do we need any more than that ?

**Comment by hufnagel** [comment]
This assumes we have few enough of these that the jobs not being resizable is ok. Otherwise we might have to come up with a scheme to resize them in a "smart" way by changing both N and M, but that will be difficult, especially in how it affects memory use of the job...

**Comment by ericvaandering** [comment]
Yeah, # of streams in the framework of 0 (perhaps -1, Iforget which at the moment) tells it to use the same # of streams as threads.

When Alan is talking about resizable he means the dynamically resizable thing from "JDL Magic" But be construction that works on cores and reducing a core from a job does not reduce the memory unless the nStreams decreases too. And adding a core without adding a stream may harm your CPU efficiency. I think the only sane option for now is for the agent to run these jobs exactly as told by MCM or Unified.

**Comment by amaltaro** [comment]
Thanks, I have just updated my first message in this issue. The correct default value is going to be 0 then, as:
https://github.com/hufnagel/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L666

**Comment by amaltaro** [comment]
@ericvaandering as we discussed, these would be the possible places we'd need to update in order to get configurable numberOfStreams in a *step* basis:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L999
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1702
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMTask.py#L1328
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMStep.py#L47
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Templates/CMSSW.py#L357
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L658

**Comment by ericvaandering** [comment]
and https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1792 is the start of that chain?

So our proposal to McM will be to add numberOfThreads as an request-level parameter and an optional step-level parameter, right?

If it is never specified, it defaults to numberOfCores for all steps. If it is specified on the request, it is set to min(nThreads, nStepCores) for each step. And if it is set on step, it is set to min(nStepThreads, nStepCores).

**Comment by amaltaro** [comment]
This is the start point:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L999

McM sets `Multicore` in a request/task (and step for StepChain) basis.
Thus, they would need to set a `Streams` (or whatever you prefer to call it` argument, with an integer value, in order to get it propagated to the jobs.

BTW, the default value is going to be 0, right? Meaning, use the same as `numberOfThreads`.

**Comment by hufnagel** [comment]
I don't like Streams. Can we maybe call it MultiEvent ? Since that is what it is, number of parallel events we are processing, isn't it ?

@ericvaandering , numberOfThreads already is MultiCore, nothing is changing there. What's new is the ability to tell the framework not to process the same number of events in parallel, but less (and therefore have more than one thread it can use to process a single event.

**Comment by ericvaandering** [comment]
I called it streams because that's what the framework calls it. Why should we have our own terminology? We can say eventStreams so it's clear. 

@hufnagel correct, nothing on MultiCore. Sorry, I mis-spoke above. Should have said streams instead of cores.  If we were doing this from the start, we would have not called it MultiCore anyhow. We just overloaded an old setting from the forking days. 

So should we have them set two variables, Multicore and EventStreams?

**Comment by hufnagel** [comment]
Internally we can call it streams, I am just questioning what we should call it in the interface we expose to the user, ie. the request parameter. I am fine with EventStreams, just not sure if it might confuse people. But I guess the people that will change the defaults should know what it means.

PS: EventStreams is better than Streams :-)

**Comment by ericvaandering** [comment]
Ok, we'll go with EventStreams. I will write up the changes for this and for the EL7 stuff and send it around to both McM and Unified people for comment.

**Comment by ericvaandering** [comment]
@amaltaro as we do this, please use variable and dictionary keys that are eventStreams or EventStreams as appropriate. 

The behavior should be that this is optional at the request, task, and step level. If it is left off at one of those levels, use the value from the higher level. Possible values are (not set, 0, N != 0) For the zero case, we pass that down and set the CMSSW application appropriately so that nStream = nThread

**Comment by amaltaro** [comment]
> Possible values are (not set, 0, N != 0) For the zero case, we pass that down and set the CMSSW application appropriately so that nStream = 0 (which internally in CMSSW will do nStream = nThread).

Since we already set it (at SetupCMSSW level) to 0 for all CMSSW jobs, how about we make it two possible values, either 0 or >0? Then we default it to 0 for workload level and tasks/steps inherit it from workload if not provided. I think it will be easier and more clear than keeping None around. Any thoughts @ericvaandering ?

**Comment by ericvaandering** [comment]
The case I want to handle correctly is:
workload cores=4, workload streams= 3
 step cores = 8 or step cores =4

What should the streams be in those two cases? I would say in both cases they should be 3 inheriting from the workfload, not 8 and 4 respectively since its not set.

**Comment by amaltaro** [comment]
Yes, that's what I have in mind as well. Ok, I guess I have all the questions sorted out now, thanks!
