### ISSUE TITLE
Monitor problematic workflows (warning page, api)

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7517]
Condition need to be defined.
i.e workflows with more than 50% of failure.

current alert condition is specified here. (I think it was Julian's request before)
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStats/_attachments/js/DataStruct/T1/WMStats.RequestSummary.js#L57

1. if all the jobs failed mark as config error
2. if more than 85% jobs are failed mark as site error

https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStats/_attachments/js/DataStruct/T1/WMStats.RequestSummary.js#L94
1. after assigned if is not acquired in 2 hours - display warning
2. if status is not process in 2 day - mark as stuck.

We can add different conditions - I think we start with strict conditions so not too many warnings are triggered. (We can also add sending email or provide api as well)

The information available is number of jobs per sites and its status. One thing it is hard to check it time dependent data. wmstats doesn't keep the history of progress, only the snap shot. 
If we nee the data over time we have to create the new db and keep the snapshots over time (WMDatamining does similar statistics) - If we don't have to keep more than a couple of data, it is feasible. However, if it needs long term data, WMArchive is the right place to implement this.

**Comment by ticoann** [comment]
FYI @vlimant, @jenimal

**Comment by jenimal** [comment]
This is a great!  we are already pulling the warnings.  Problem right now is that if it is a site issue we have a hard time getting to the logs, to be able to pull logs for the sites.  
the agent wasn't complaining about sites yesterday, but is today, let me focus on those for the next week or two and see if they give us the results we want

**Comment by jenimal** [comment]
How hard would it be to have the workflows sorted by failure code?  It would make it much faster when there is a long list to figure out what the most pressing problems are.  I started with the current list, but have to go play taxi driver for my kids right now:
https://cms-logbook.cern.ch/elog/Workflow+processing/26067

the 99303 - is the schedd issue we were discussing yesterday.  Need to figure out how we can fix it on the fly
file read issues would point toward site problems
performance failures, generally we can't do anything about on the fly
Submit/Creation failures good to know about, verify the site is down and why, does it have to be down or can we be doing something there... 

Note most the workflows listed are complete ACDC's are getting going on them

**Comment by vlimant** [comment]
@ticoann how does one get that list of warning from wmstats api ? I fear that this is not a "view" but rather something computed on top in javascript. api is better are we want to wire some automatic procedure to this in the medium-long run.

**Comment by ticoann** [comment]
@vlimant, yes your right. What I meant was we could provide API as well if at the condition is defined.

**Comment by vlimant** [comment]
for Unified consumption, I would need an API, **or** wmstats creates the report unfied-like

**Comment by ticoann** [comment]
closing this and make general proposal for wmstats upgrade
