### ISSUE TITLE
add time.asctime in request transition

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7522]
would it be possible to have the actual date and time directly in the json

{
      "Status": "completed", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch", 
      "UpdateTime": 1483924107
}

adding 

"UpdateDate" : time.asctime( time.gmtime(1483924107))

**Comment by ticoann** [comment]
@vlimant, Yes, but may I ask why this formatted date is needed in db. client can always convert if this is for the display.  I am not sure whether it is good idea to save the same information in different format in db. (Although we already have a lot of duplicate information. 😄

**Comment by vlimant** [comment]
this or #6840, but at least a place where I can read of the date without opening python. If #6840 then this is not visible once the request is archived, hence this GH, so that one can read it off https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_HIG-RunIIWinter15pLHE-00329_00250_v0__161216_132345_5499

**Comment by vlimant** [comment]
an  extra tab in https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC2_task_PPD-PhaseIIFall16GS82-00006__v1_T_170109_212702_4754 ?

**Comment by ticoann** [comment]
I see, I will do  #6840. It will be updated in next deployment. I am closing this issue and keep  #6840

**Comment by amaltaro** [comment]
Hmm, I'd be in favor of adding a new key for that, e.g. `UpdateTimeStr` or so...
This way one can look at the reqmgr_workload_cache doc only and figure all the transitions right away.

**Comment by ticoann** [comment]
Hi Alan, Actually, I think it is better to avoid the need to check couch doc directly especially human readable data. If necessary information is not displayed in monitoring we can add that. I think it is better for Ops to get the necessary information in one place. Anyway, we can discuss tomorrow since you are mostly right with the reason I didn't foresee. :smile:

**Comment by ticoann** [comment]
Closing and will fix #6840
