### ISSUE TITLE
stuck in force-complete

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7529]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_HIG-RunIISummer16DR80Premix-00486_00055_v0__161109_122431_5636

was force-complete on Jan 5 and has not made it further.

**Comment by amaltaro** [comment]
@ticoann all the elements are marked as Done in central workqueue.
Can you check whether that script you've set to move work to complete is still up and running? The agents are not going to move it to completed since they were patched with https://github.com/dmwm/WMCore/pull/7472

**Comment by ticoann** [comment]
Cronjob is still running. The reason it is not moving is that inbox element status is still CancelRequested status. So cronjob is not picking that up. 

https://cmsweb.cern.ch/couchdb/workqueue_inbox/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_HIG-RunIISummer16DR80Premix-00486_00055_v0__161109_122431_5636

Workqueue should move that to Canceled status first but I am not sure what happens. I will investigate more and move the status.

**Comment by ticoann** [comment]
It seem there is a edge case workqueue_inbox element is not moved to canceled when force complete and abort happens.

If all the elements happened to be in Done states when force-complete and aborted happens. It doesn't seem to make inbox to Canceled. 
I moved the inbox status to Canceled manually. I will check whether it would catch up and make the request status to completed.

New refactoring work queue patch should handle this case.

**Comment by ticoann** [comment]
It seems it picked up and moved to completed now.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer16DR80Premix-01335__v1_T_161209_071150_9553

is also not going anywhere since quite some time. 
Please re-open, and confirm a fix

**Comment by ticoann** [comment]
It seems to be the same case as above. I manually change the inbox status to Canceled. It should pick up and move to completed shortly. 
The fix for this problem is now in testbed and will be update production in Feb. Until then we have to do this manually. I will leave this issue open until the production cmsweb is upgraded.

**Comment by vlimant** [comment]
great ! thanks for confirming

**Comment by amaltaro** [comment]
If you guys don't mind, I'm closing this one in favor of #7445
