### ISSUE TITLE
workflow long assigned

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7534]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_task_EXO-RunIISummer16DR80Premix-01801__v1_T_170105_224426_9870 is sitting in assigned for no apparent reason since 15 days

**Comment by amaltaro** [comment]
This is failing exactly in the same code as the issue #7441, though the reason is different.

It's failing to acquire one block that is not completed anywhere yet:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/AxialMonoW_Mphi-1500_Mchi-1_gSM-0p25_gDM-1p0_v2_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM%234c5a8e68-8fb3-11e6-8d67-001e67abefa8

since it has no location, it fails in this line (that is fixed in master):
https://github.com/dmwm/WMCore/blob/1.0.23.pre3/src/python/WMCore/Services/DBS/DBS3Reader.py#L666

**Comment by vlimant** [comment]
sorry for the duplicate then. looked like a different reason will pass on to TT @sidnarayanan

**Comment by amaltaro** [comment]
I don't know why it hasn't been registered into LogDB though:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1126

the fact that the database is completely empty looks suspicious as well...

**Comment by sebastianpulido** [comment]
Hi all,
1 file has been invalidated [1]. I was not receiving github notifications. I just subscribed.

Let me know,
Sebastian.
[1] /store/mc/RunIISummer15wmLHEGS/AxialMonoW_Mphi-1500_Mchi-1_gSM-0p25_gDM-1p0_v2_13TeV-madgraph/GEN-SIM/MCRUN2_71_V1-v1/70000/BE186F53-7590-E611-9181-0242AC130004.root

**Comment by vlimant** [comment]
@sebastianpulido, no worries, I send this by email to TT

**Comment by vlimant** [comment]
Please re-open for

prozober_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170120_180043_4823
pdmvserv_task_BPH-RunIISummer16DR80Premix-00010__v1_T_170112_142010_6077
pdmvserv_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170105_140314_3378

**Comment by amaltaro** [comment]
> prozober_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170120_180043_4823

Block not complete anywhere:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/TTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM%23b1026b82-91f8-11e6-8fc0-001e67abf518

> pdmvserv_task_BPH-RunIISummer16DR80Premix-00010__v1_T_170112_142010_6077

same:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/BuToKstarJpsi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISummer15GS-MCRUN2_71_V1-v1/GEN-SIM%2389263f0c-8a2e-11e6-b48c-002590494fb0

>  pdmvserv_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170105_140314_3378

same:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/TTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM%23b1026b82-91f8-11e6-8fc0-001e67abf518

@sebastianpulido I think these 3 are up to you

**Comment by sebastianpulido** [comment]
Hi all, I believe 1 block is reported twice? I invalidated 2 files. 
Thanks for reporting it Alan!

**Comment by vlimant** [comment]
@prozober can you please clone with black list, until we have the fix deployed and until such blocks are properly handled in invalidation by tt
@mcremone FYI

**Comment by sebastianpulido** [comment]
Hi all, I missed 1 file, no more missing files for datasets
https://cmsweb.cern.ch/phedex/datasvc/perl/prod/missingfiles?block=/TTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM%23*

https://cmsweb.cern.ch/phedex/datasvc/perl/prod/missingfiles?block=/BuToKstarJpsi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISummer15GS-MCRUN2_71_V1-v1/GEN-SIM%23*

Sebastian.

**Comment by vlimant** [comment]
@sebastianpulido can you please summarize what are the blocks left with no files (those that we should blacklist) if any ?

**Comment by amaltaro** [comment]
There is no need to cancel/blacklist any of these 3 workflows. Those blocks have > 1 files and they completed at their destination. All 3 workflows were already acquired by GQ.
