### ISSUE TITLE
Make SiteWhitelist mandatory during assignment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7535]
and it cannot be an empty list

**Comment by amaltaro** [comment]
BTW, I wouldn't mind getting rid of wildcards in the sitewhitelists as well. Nobody has ever used that since WMAgent day 1 and I'm not sure it would work throughout the whole system... Any thoughts @ticoann @hufnagel

**Comment by hufnagel** [comment]
Is this an operational change in that we no longer want to support empty (== all sites) site whitelists ?

As far as wildcards, I am surprised there is any code in for that. I can't see that working (reliably) at all.

**Comment by ticoann** [comment]
Hi Dirk,
For site white list, it was supported but it seem Ops never used it. So we want to remove it for more consistent with how we handle the site white list.

For wild cards I think we only supports whether it is T1*, T2*, etc. (I have to check the code.)

Anyway, Alan, I agree with you to get rid of it.

**Comment by hufnagel** [comment]
Even restricting it to T1*, T2* etc I don't see as being that useful anymore. With unified in place this is simply not something we need or which Ops would ever use. Agree to remove it.
