### ISSUE TITLE
is this a syntax error in LumiList ?

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#7537]
with ref. to
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/DataStructs/LumiList.py#L142
I do not understand what the repeated '<=' means, maybe my Python ignorance, maybe a typo ?
I went there because had got this [1] odd error with interactive python after I typed
```
from WMCore.DataStructs.LumiList import LumiList
fpub='/afs/cern.ch/user/b/belforte/public/outputDatasetsLumis.json'
lpu=LumiList(filename=fpub)
```
that json file was produced  by crab report and looks OK  to me, it parses in json validator.

[1]
```
----> 1 LumiList(filename=fpub)
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/lib/python2.7/site-packages/WMCore/DataStructs/LumiList.pyc in __init__(self, filename, lumis, runsAndLumis, runs, compactList, url, wmagentFormat)
    140             for lumi in sorted(self.compactList[run]):
    141                 # If the next lumi starts inside or just after the last just change the endpoint of the first
--> 142                 if newLumis and newLumis[-1][0] <= lumi[0] <= newLumis[-1][1] + 1:
    143                     newLumis[-1][1] = max(newLumis[-1][1], lumi[1])
    144                 else:

TypeError: coercing to Unicode: need string or buffer, int found
```

**Comment by belforte** [comment]
I try to  attach the json file
[outputDatasetsLumis.json.txt](https://github.com/dmwm/WMCore/files/723623/outputDatasetsLumis.json.txt)

**Comment by amaltaro** [comment]
The TypeError exception is because your json is not in any of the formats accepted by LumiList, it has a dataset name in there.

Taking just a part of that works:
```
>>> myLumi = {"283834": [[1, 67], [69, 82]], "281726": [[1, 288]], "281727": [[1, 1611]], "283308": [[1, 895], [897, 972]]}
>>> a = LumiList(compactList=myLumi)
>>> a.getCompactList()
{'281726': [[1, 288]], '281727': [[1, 1611]], '283834': [[1, 67], [69, 82]], '283308': [[1, 895], [897, 972]]}
```

Now coming back to the problem. Yes, AFAIK you cannot make triple comparisons in python, though the interpreter doesn't complain about such syntax.

Are you creating a fix for it or should I go ahead?

**Comment by belforte** [comment]
I thought about the dataset name of course, but it is always there in crab report outputs and usually it works. E.g. in this case another file was created for the input dataset, name in the beginning, and it works OK. Of course it would be better if CRAB and LumiList developers talked to each other and fixed either the code or the documentation of accepted format or both. Maybe @ericvaandering wants to follow up ?
I was not planning to debug this to figure out why exactly it fails only on this file and what it should be doing instead. I was hopin the original author could do it faster and more reliably :-)

**Comment by ericvaandering** [comment]
You absolutely can make triple comparisons unlike most languages:
```
Nakuru:LRWork ewv$ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 3<5<7
True
>>> 3<9<6
False
>>> 
```

And yes, that file is not a lumi list.

No, nothing to change here. Issue should be closed, IMO.

**Comment by belforte** [comment]
I see. And I have to correct my statement that crab report on this task produced other files in same format. It created 3 lumi summary files, only one with the dataset name.
Let's handle this like a CRAB bug then.

**Comment by amaltaro** [comment]
Indeed it's supported! I don't know what happened in the past that I was sure it was not allowed :-(
Thanks!
