### ISSUE TITLE
latest JobSubmitter broken for Tier0 use

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#7551]
Putting a check for ReqMgr2 into the JobSubmitter broke that component for Tier0 use.

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L109

When you put any referral back to ReqMgr2 into deeper agent code it's a) quite bad design-wise and b) without some provisions for it to be optional it'll break the Tier0.

**Comment by ticoann** [comment]
Sorry Dirk, I always forget about Tier0 cases.  Does tier0 ever abort the work? Or will that status ever needed?

**Comment by ticoann** [comment]
I created the patch assuming there is no aborted or force-complete status in tier0

**Comment by hufnagel** [comment]
There isn't, so this is ok.
