### ISSUE TITLE
problems starting WMBSService

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#7552]
Latest WMCore version I get this trying to start the WMBSService:

Starting : WMBSService
Starting WMBSService as a daemon
Log will be in /data/tier0/srv/wmagent/2.0.6/install/tier0/WMBSService
Waiting 1 seconds, to ensure daemon file is created

started with pid 273647
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method TempDirectory.__del__ of <WMCore.Services.Requests.TempDirectory object at 0x7fd4e6e62250>> ignored

**Comment by ticoann** [comment]
Hmm that is weird. are you using 1.1.0.pre6? In which machine are you deploying the agent?

**Comment by hufnagel** [comment]
Yes, using 1.1.0.pre6. Deployment is on vocms001, feel free to explore there.

**Comment by ticoann** [comment]
Dirk, did you deploy agent eventually? I checked vocms001. It seems all the components are running now.

cmst1@vocms001:/data/tier0/srv/wmagent/current $ $manage status
+ Couch Status:
++ Couch running with process: 273334
++ {"couchdb":"Welcome","uuid":"7ba48b9307c5fd7725b5418b68ebcc17","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
Status of Tier0:
Checking default database connection... ok.
Status components: ['DBS3Upload', 'PhEDExInjector', 'JobAccountant', 'JobCreator', 'JobSubmitter', 'JobTracker', 'JobStatusLite', 'ErrorHandler', 'RetryManager', 'JobArchiver', 'TaskArchiver', 'AlertProcessor', 'AlertGenerator', 'AnalyticsDataCollector', 'AgentStatusWatcher', 'Tier0Feeder', 'WMBSService']
Component:DBS3Upload Running:273370
Component:PhEDExInjector Running:273385
Component:JobAccountant Running:273394
Component:JobCreator Running:273421
Component:JobSubmitter Running:273428
Component:JobTracker Running:273461
Component:JobStatusLite Running:273493
Component:ErrorHandler Running:273527
Component:RetryManager Running:273532
Component:JobArchiver Running:273539
Component:TaskArchiver Running:273547
Component:AlertProcessor Running:273553
Component:AlertGenerator Running:273562
Component:AnalyticsDataCollector Running:273595
Component:AgentStatusWatcher Running:273602
Component:Tier0Feeder Running:273642
Component:WMBSService Running:273647

**Comment by hufnagel** [comment]
I didn't fix this, seems the component starts somehow even though it prints the error. Feel free to stop and start the component again to check it.

**Comment by hufnagel** [comment]
I am not trusting it's doing the right thing though with this error...

**Comment by ticoann** [comment]
I am not sure where the error coming from, However I don't think it is related WMBSService component.

When I used the 00_start_agent.sh script there were errors 
```
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method TempDirectory.__del__ of <WMCore.Services.Requests.TempDirectory object at 0x7f96872ef250>> ignored
```
But when I restarted only that component there was no errors. 

```
cmst1@vocms001:/data/tier0 $ $manage execute-agent wmcoreD --restart --component=WMBSService
Executing wmcoreD --restart --component=WMBSService ...
Components List Specified:
[WMBSService]
Checking default database connection... ok.
Stopping components: ['WMBSService']
Stopping: WMBSService
Starting components: ['WMBSService']
Starting : WMBSService
Starting WMBSService as a daemon 
Log will be in /data/tier0/srv/wmagent/2.0.6/install/tier0/WMBSService 
Waiting 1 seconds, to ensure daemon file is created
```
I will check again tomorrow.

**Comment by amaltaro** [comment]
This #7596 should fix this issue. There is another issue for the code cleanup.
