### ISSUE TITLE
Remove unused component.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7566]
AlertGenerator, AlertProcessor. - replaced by LogDB
WorkflowManager - never been used
WMBSService,  - HTTPFrontEnd/ - not used by anyone anymore

**Comment by ticoann** [comment]
@amaltaro, Alan, could you check whether we have to keep any of these components?

**Comment by amaltaro** [comment]
WorkflowManager is completely new for me :-)
WMBSService is in our list to be removed for quite some time.
About these Alert components, are they only used for the alert system (which triggers email and etc)?

When we remove them, we better make different PR for each of them

**Comment by hufnagel** [comment]
When we remove the alert components we should also remove the (remaining) alerts issued elsewhere.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove unused component](https://trello.com/c/Skg7mrKs/33-remove-unused-component)
