### ISSUE TITLE
Fail request acquisition in GQ if there are way too many lumis

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7575]
As a follow up of https://github.com/dmwm/WMCore/issues/7560 and private discussions.
There may be cases where we have gazillions of lumis in the same WQE (or file), e.g.
 pdmvserv_task_BPH-PhaseIIFall16GS82-00010__v1_T_170124_203731_9213

with 23M lumis per file (since it's MC). This just makes this workqueue thread `WorkQueueManagerWMBSFileFeeder` to get kind of stuck when inserting run/lumi into the local SQL database.

My idea is to use the ratio of `TotalInputLumis / TotalEstimatedJobs` and fail the work creation in global workqueue if beyond a specific threshold (200k lumis?) Ideally we should make it configurable.

**Comment by ticoann** [comment]
@amaltaro, Threshold is per WQ elements, right? Not total for whole workflow, right?

**Comment by ticoann** [comment]
Actually it should be per job, now I understand what you meant. I am not sure we can use TotalLumis/TotalJobs. We have to catch this before WQE is pulled down to LQ ideally.

**Comment by amaltaro** [comment]
I forgot to mention, we should implement this protection only for MonteCarlo start policy.

So if a WQE has more than 200k lumi sections, we fail its creation and throw a terminal exception for that request. I think we have access of NumberOfLumis before we create the element.
