### ISSUE TITLE
Automatically set the agent to Drain when diskUseThreshold is reached

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7577]
AnalyticsDataCollector has this configuration:
config.AnalyticsDataCollector.diskUseThreshold = 85

which is used to trigger a warning in wmstats when the disk usage is >= than that value.

The idea is to use this value in order to automatically set the agent into Drain. Once that is done, these 3 components should be restarted to see these changes:
WorkQueueManager,AnalyticsDataCollector,AgentStatusWatcher

**Comment by alexanderrichards** [comment]
@amaltaro is the following sufficient to set the agent to drain?
```diff
diff --git a/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py b/src/python/WMComponent/AgentStatusWatcher/
index 465905c..d85fe3a 100644
--- a/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
+++ b/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
@@ -168,7 +168,7 @@ class AgentStatusPoller(BaseWorkerThread):
             if float(disk['percent'].strip('%')) >= diskUseThreshold and \
                             disk['mounted'] not in self.config.AnalyticsDataCollector.ignoreDisk:
                 agentInfo['disk_warning'].append(disk)
-
+                agentInfo['drain_mode'] = True
         # Couch process warning
         couchProc = numberCouchProcess()
         logging.info("CouchDB is running with %d processes", couchProc)
```

**Comment by amaltaro** [comment]
Alex, as we quickly discussed in the meeting. These changes would simply report to wmstats saying that the agent is in drain mode (but actually it's not).

These are the changes you'd need:
1. you could update the agent config and add a new key/value (`'DrainMode': False`) to `queueParams`
https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L143
2. then, when the agent must go into drain, you switch if to True
3. finally, you'd have to restart three components. This is how we restart the components using the bash manage script
`$manage execute-agent wmcoreD --restart --components=WorkQueueManager,AnalyticsDataCollector,AgentStatusWatcher`

so you may want to have a look at
https://github.com/dmwm/WMCore/blob/master/bin/wmcoreD#L334

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automatically set the agent to Drain when diskUseThreshold is reached](https://trello.com/c/sTlZb4ry/15-automatically-set-the-agent-to-drain-when-diskusethreshold-is-reached)

**Comment by alexanderrichards** [comment]
> Automatically set the agent to Drain when diskUseThreshold is reached

@amaltaro  I cant see this link

**Comment by amaltaro** [comment]
Don't worry Alex. We were going to track some of these issues in trello but we gave up on that.

**Comment by amaltaro** [comment]
@alexanderrichards can you remind me what's the status of this issue? I have the impression it has been implemented already, no?

**Comment by ticoann** [comment]
Yes it is implemented
