### ISSUE TITLE
WMStats not loading "L" view

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7594]
Since the cmsweb upgrade this morning, when I click on the "L" view for a workflow, it just sits and spins instead of going to the "L" view.  

Jen

**Comment by jenimal** [comment]
@amaltaro @Seangchan

**Comment by amaltaro** [comment]
Jen, check again please. If the problem is solved, please close this ticket.

**Comment by jenimal** [comment]
It's working!  Thanks Guys!
