### ISSUE TITLE
Jobs Held in the Agent (in drain ?)

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7595]
I was looking at what just happened to 309

![daily309](https://cloud.githubusercontent.com/assets/4989875/22708170/aa4b294a-ed75-11e6-9733-67c5eca5c90c.png)

and https://cms-gwmsmon.cern.ch/prodview/pdmvserv_EXO-RunIISummer15wmLHEGS-03059_00290_v0__161226_203812_6453

![daily_03059](https://cloud.githubusercontent.com/assets/4989875/22708171/aa4d2eb6-ed75-11e6-9481-f5d6f40f3dd6.png)

this workflow was dormant in 309 it seems, with no jobs being created until now and that will probably get the workflow to complete.

what mechanism has been holding the job back in the agent for so long ?

**Comment by vlimant** [comment]
FYI @scarletnorberg

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_EXO-RunIISummer15wmLHEGS-03059_00290_v0__161226_203812_6453

@amaltaro @ticoann the workflow is in aborted-archived ... crazy !

**Comment by ticoann** [comment]
It seems this was aborted, aborted-completed and aborted-archvied by Matteo.
Was this workflow stuck? Is that the reason it transition happened manually?
aborted-completed, aborted-archived? Once it is moved to aborted-completed the killing job won't be triggered.  aborted-completed status transition  supposed to happen automatically.

 {
      "Status": "aborted", 
      "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mcremone/CN=761206/CN=Matteo Cremonesi", 
      "UpdateTime": 1482927085
    }, 
    {
      "Status": "aborted-completed", 
      "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mcremone/CN=761206/CN=Matteo Cremonesi", 
      "UpdateTime": 1486470936
    }, 
    {
      "Status": "aborted-archived", 
      "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mcremone/CN=761206/CN=Matteo Cremonesi", 
      "UpdateTime": 1486474723
    }

**Comment by vlimant** [comment]
I doubt @mcremone has toggle it by hand to archived.
Thing is, it had been aborted long time ago and resurrected yesterday

**Comment by mcremone** [comment]
I confirm I did not act manually on that workflow.

**Comment by ticoann** [comment]
Hmm, Matteo,  is there any script using your cert? How about in vocms049 or some agent?

Normally, aborted and aborted-archived should done by agent. Something like below.

{
      "Status": "aborted", 
      "DN": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal", 
      "UpdateTime": 1486112854
    }, 
    {
      "Status": "aborted-completed", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch", 
      "UpdateTime": 1486113997
    }, 
    {
      "Status": "aborted-archived", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch", 
      "UpdateTime": 1486115446
    }

I will investigate and report back.

**Comment by vlimant** [comment]
no script under Unified is setting workflows to aborted-completed or aborted-archived

**Comment by ticoann** [comment]
Not in Unified. I added the cronjob in vocms049 a month ago due the problem that abort is not completing it in specific case. I am suspecting if vocms049 uses Matteo's proxy this explains.
But still I don't understand why jobs are created and submitted.

**Comment by vlimant** [comment]
I would not know about that, @mcremone ?

**Comment by ticoann** [comment]
I looked at the db and code. I am not sure how this happen.
1. As I said, the aborted-completed, aborted-archived state transition should happens by agent.
   Not sure how Matteo's DN is recorded.
2.It sounds like it jobs were reappearing on Feb 7 before jobs weren't submitted, correct?

Here is the time line
aborted - Wed Dec 28 2016 06:11:25 GMT-0600 (CST)
aborted-completed -Tue Feb 07 2017 06:35:36 GMT-0600 (CST)
aborted-archived - Tue Feb 07 2017 07:38:43 GMT-0600 (CST)

It looks like after aborted WQ elements are all deleted  so it wasn't moving the state. 
After production upgrade (which has the fix on this case), it moves the status. 
However, it should be GQ dn which should be recorded.

Thanks,
