### ISSUE TITLE
Investigate memory leak in WMDataMining

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7599]
Seen in production once HG1702 was pushed in. Resident memory consumption goes as high as ~3.7GB, when the service becomes unresponsive (swap at 2GB).

**Comment by ericvaandering** [comment]
We could shut this down. I don't think anyone is using it. I can revisit later if anyone is. And I think it hasn't talked to McM in ages.

**Comment by ticoann** [comment]
Thanks Eric, we could shut it down then. 
I looked at the code briefly the memory usage depends mostly the job documents in wmstats. (failing document). There are around 200K. Even though we count one documents as 10K it should be only 20M.  Something is fish here.
