### ISSUE TITLE
GQ addWork() way too slow

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7607]
It seems the reqmgrInteraction workqueue thread is spending too long on the running-open requests. It usually takes between 20 and 30secs per request, so 100 requests opened would cause it to spend between 30 and 50min before acquiring anything new, which explains why this request
prozober_ACDC0_SUS-RunIISpring16FSPremix-00083_00047_v0__170210_085036_9266

hasn't been acquired yet.

This fix is not in production:
https://github.com/dmwm/WMCore/pull/7587

but anyways it doesn't solve the problem, since addWork always set continuous to True.

**Comment by ticoann** [comment]
It should solve the problem somewhat. Since continuous is always True. It won't evaluate next expression. That is the main reason the patch is created. #7587
If continuous is False it won't matter but if it is True it will help.

``
work = not continuous and self.backend.getElementsForParent(inbound)
```

If this is a big problem we can ask for the emergency deployment in production

**Comment by ticoann** [comment]
@amaltaro, Alan, do you see any improvement in production?

**Comment by amaltaro** [comment]
It looked Ok when I had a look this afternoon, but it could just be the lack of work as well :-)
I'll check it again tomorrow.

**Comment by ticoann** [comment]
Can we close this one, Alan?

**Comment by amaltaro** [comment]
There is not enough work in the system to check, but we can assume it's solved and if not, we just reopen it :-)

**Comment by ticoann** [comment]
Good policy. :-)
