### ISSUE TITLE
Retire oracle ReqMgr accounts

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7609]
Seangchan, I can talk to Kate about the procedure to return all those reqmgr oracle accounts (I have 6 of them).
However, before that, do we need to do anything else with that data?

**Comment by ticoann** [comment]
Hi Alan, I don't think we need anything from the db.

**Comment by amaltaro** [comment]
Then I'm going to delete it tomorrow morning, Ok? I already talked to Kate and she told me it's just a matter of going to the resources whatever CERN page and deleting it. Do I have your green light, @ticoann ?

**Comment by ticoann** [comment]
Yes go ahead, please.

**Comment by amaltaro** [comment]
I've deleted all the accounts I had under my ownership.
Seangchan, I listed them in the private email, subject: "Oracle accounts for ReqMgr"
Closing this issue.
