### ISSUE TITLE
stuck in acquired with all wqe done

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7611]
https://cmsweb.cern.ch/reqmgr2/data/request?name=fabozzi_Run2016B-23Sep2016-v2-HighMultiplicity85EOF-03Feb2017_ver1_8026p1_170203_185211_6837

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=fabozzi_Run2016B-23Sep2016-v2-HighMultiplicity85EOF-03Feb2017_ver1_8026p1_170203_185211_6837

 there was no jobs in the wqe, which is "expected", can I move manually to completed ?

**Comment by amaltaro** [comment]
This and #7445 are affected by the same issue. Can we close this one and follow up on the other issue?

**Comment by ticoann** [comment]
I am sorry that I didn't know there is legit case that Jobs are 0. I though all the WE should contain at least one Job. I am just wondering in what cases estimate Jobs are 0 in WQE?

**Comment by ticoann** [comment]
I moved the status manually by changing Jobs = 1.  StateTransition thread picked up and moved the status to completed for following. 

fabozzi_Run2016B-23Sep2016-v2-HighMultiplicity85EOF-03Feb2017_ver1_8026p1_170203_185211_6837
fabozzi_Run2016C-23Sep2016-v1-FSQJets-03Feb2017_8026p1_170203_160332_4166

I am closing this and leave it open #7445. Alan already created the fix but I would like to understand what is the case for Jobs = 0.
