### ISSUE TITLE
secondary jobs with large walltime requirements

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7629]
https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_HIG-RunIISummer15wmLHEGS-00915__v1_T_170120_082113_870

has job for the HIG-RunIISummer16DR80Premix-01934_1 task with a walltime requirement of 1800. This was not edited over the jobrouter.

**Comment by vlimant** [comment]
looking into this again, with several workflows stuck because of this
https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_BPH-RunIISummer15GS-00095__v1_T_170218_001123_7733

1800 min requirement means about 3k events / lumi on the input.
The filter efficiency seems to ~accurate and should have made 200 events/lumi on the /pdmvserv_task_BPH-RunIISummer15GS-00095__v1_T_170218_001123_7733/BPH-RunIISummer15GS-00095_0 task.

There were 780k jobs for that task, and the dataset /BsToMuMuPhi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISummer15GS-MCRUN2_71_V1_ext1-v1/GEN-SIM has a min-max events/lumis of 107-132 so it does not seem possible that there are lumisections with 3k events in this dataset, leading to 1800 in the BPH-RunIISummer16DR80Premix-00025_0 task.

regardless of whether the jobs should actually be ran at the site (sigh), knowing how it came to be submitted with 1800 is necessary

**Comment by vlimant** [comment]
I qedited some jobs down to 500 to get them going

**Comment by vlimant** [comment]
could this be resizable jobs @bbockelm ?

**Comment by bbockelm** [comment]
These are DR, right?  In that case, yes, they can be resized.

**Comment by ticoann** [comment]
FYI. This is what agent set for OriginalMaxWallTimeMin.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L543

I am closing the issue with Jean-Roch's permission for now. 😄
