### ISSUE TITLE
Dead Harvesting

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7630]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_HARVEST-Run2016B-v2-ZeroBias2-17Jan2017_8020_170125_064007_1366
and 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_HARVEST-Run2016B-v2-ZeroBias3-17Jan2017_8020_170125_001614_5508

don't look super healthy.
FYI @mcremone

**Comment by amaltaro** [comment]
transferring the input dataset to the sitewhitelist would help.
Not a WMCore issue, closing.

**Comment by vlimant** [comment]
alright, that's a lock/harvesting race condition. it was on disk just enough to get the wqe through to acquired, and now the agent does not find it anymore, right ?

**Comment by amaltaro** [comment]
Yes, that's right. The agent managed to pull down that WQE but before it was injected into WMBS, a data location updated kicked out and updated the element locally.

I'm planning to expose the WQE ids (for stuck in local workqueue database) to wmstats as well, it should be done in a week or two.
