### ISSUE TITLE
quantize MaxWallTimeMins

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#7631]
I noticed on cms-gwmsmon, that some of new jobs which come with expression:
```
MaxWallTimeMins = WMCore_ResizeJob ? ( EstimatedSingleCoreMins / RequestCpus + 15 ) : OriginalMaxWallTimeMins
```
are not quantized by htcondor and this makes a lot of autoclusters. I might be wrong, but matching looks at MaxWallTimeMins and this makes too many different autoclusters. Maybe quantize to nearest 100?

@bbockelm @vlimant

**Comment by bbockelm** [comment]
Good idea!

Should be able to wrap that to a call to quantize.  I think it's like:

quantize( ...., 180)

[seems that nearest 3 hours should be sufficient, no?]

**Comment by ericvaandering** [comment]
Would it make more sense to move all this quantize stuff into WMCore?

**Comment by bbockelm** [comment]
?

This is the WMCore issue tracker, so I hope that was implied...

**Comment by ericvaandering** [comment]
Well, we don't have a function quantize in WMCore and as far as I know, things like CPU time and memory are quantized in HTCondor, right?

**Comment by bbockelm** [comment]
ah - now I understand your comment.  I thought you meant that the code that produced the `quantize` call in HTCondor should be part of WMCore.   I see you mean that WMCore should do the quantization.

I'm not sure we can quantize within WMCore because the CPU time and memory are a function of the number of CPUs allocated (a runtime decision).

**Comment by ericvaandering** [comment]
OK. We also don't have any references to the HTCondor function named quantize, but I agree that's the thing to do here. @bbockelm you want to make the PR?

**Comment by ticoann** [comment]
> but I agree that's the thing to do here

Sorry I might misunderstood. If quantize is not the simple mod function, all there required parameters accessible  in WMAgent before job submission?

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/8429
