### ISSUE TITLE
Move WMWorkloadTools util functions to Utils

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7633]
Functions like these: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkloadTools.py#L18

I'll make these changes as soon as https://github.com/dmwm/WMCore/pull/7623 gets merged

**Comment by ericvaandering** [comment]
If you move this https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkloadTools.py#L54 I think you technically  want to do is False not == False
