### ISSUE TITLE
List of protected paths

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7645]
it might be simpler to expose the list of protected base lfn as made by
https://github.com/CMSCompOps/WmAgentScripts/blob/master/listProtectedLFN.py
directly from reqmgr so that we do not rely on some synchronization, sso, afs, ...
for the moment, it is 
https://cmst2.web.cern.ch/cmst2/unified/listProtectedLFN.txt
https://vocms049.cern.ch/unified/listProtectedLFN.txt

**Comment by ticoann** [comment]
@vlimant, Is the list changing over time? If that is the case how often does it change?

**Comment by vlimant** [comment]
the script looks at all workflow in acquired,running, completed and creates the lfn as we expect it to be, so it's very dynamic, and right now unified updates it not often enough anyways.
Having a specific view would be best and most appropriate IMO

**Comment by ticoann** [comment]
Sorry I look at the script link before (only the txt file).  We can provide the API which returns the same result with the same format.

**Comment by ticoann** [comment]
I have a couple of questions.
1. Where this list is used? Is this list used for not creating the same lfn path?
2. Why request for assignment-approved and announced status is not retrieve.

**Comment by vlimant** [comment]
We want to protect the unmerged area of things that are ongoing therefore announced and assignment-approved is not needed.
The list might be queried by admin to black directories while doing regular cleaning

**Comment by ticoann** [comment]
@vlimant, API is created, it that is not what you want, please reopen the issue.
https://cmsweb-testbed.cern.ch/wmstatsserver/data/protectedlfns

**Comment by vlimant** [comment]
looks alright to me

**Comment by vlimant** [comment]
@ticoann  are you using all outputs, even intermediate, or only the persisted ones ?
I realized that the intermediates are also written to unmerged and not in unified list. so better have it right in this implementation

**Comment by ticoann** [comment]
If unified doesn't include intermediate output, this won't either. It uses the exactly the same logic as unified. (I copied over).  Could you give me the example (intermediate output) what I am missing?

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_task_B2G-RunIISummer16DR80Premix-01472__v1_T_170120_005831_9210


pdmvserv_task_B2G-RunIISummer16DR80Premix-01472__v1_T_170120_005831_9210.tasks.B2G-RunIISummer16DR80Premix-01472_0.steps.cmsRun1.output.modules.PREMIXRAWoutput.lfnBase = '/store/unmerged/RunIISummer16DR80Premix/TprimeTToTZ_M-1400_Width-10p_RH_TuneCUETP8M2T4_13TeV-madgraph-pythia8/GEN-SIM-RAW/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1'

for example.
Is there a simple way to navigate all such lfnBase from a WMCore.WMSpec.WMWorkload.WMWorkload object ? or a dictionary of some sort

**Comment by amaltaro** [comment]
Seangchan, I just chatted with Jean-Roch. These intermediate samples/LFNs that he is concerned about are `transient` or `'keepOutput:False` data. 

The output of `OutputDatasets` correctly drop them from the list, I guess we'll need another handle to have those in this list. Or Jean-Roch adds that to Unified and we change it for the next cmsweb cycle, since this one is very close to the validation phase.

**Comment by ticoann** [comment]
Thanks Alan, let me look at the code. If it is simple to add, we can add it since we have to have another pull request. If not, we have to add for next deployment.

**Comment by amaltaro** [comment]
If we leave it for a future deployment, I think it would be a good idea to actually add something like `TemporaryDatasets` containing a list of dropped samples, to the workload/json request.

**Comment by vlimant** [comment]
for ref
WMCore.WMSpec.WMWorkload import WMWorkloadHelper
help = WMWorkloadHelper( wfi.full_spec )

for task in help.getAllTasks():
    for step in task.listAllStepNames():
        o = task.getOutputModulesForStep( step )
        for name,module in o.dictionary_().items():
            if hasattr(module, "lfnBase"):
                base = getattr(module,"lfnBase")
                if 'unmerged' in base:
                    print base

which is freaking slow

**Comment by vlimant** [comment]
I stand corrected :-(

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/1f868075f1ead622b062bbeebf044c17dae29032 for Unified
