### ISSUE TITLE
Package WMCore into pypi

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#7647]
I was wanting to float the idea of pushing WMCore into pypi so it can be easily be pulled into other projects. Setuptools already handles it via `python setup.py upload`, but that requires credentials, whch kinda makes `bin/buildrelease.sh` not the right place to put it, since whoever built a release would need to have PyPi credentials.

The other option is to add the hooks into the rpm bot or Jenkins to publish new releases. That's a bit easier since those hosts are secured and could keep the credentials secret.

Anyway, it'd be useful to have WMCore (well, a lot of DMWM's code, honestly) in pypi. If there's no objection, I'd like to put the hooks in to get it pushed up automagically

**Comment by ericvaandering** [comment]
I don't know what's involved here because I've studiously stayed away from anything that remotely smelled like packaging, but go ahead. We have no reason to keep things secret or to not try to improve our installation procedure.

**Comment by PerilousApricot** [comment]
Cheers, @ericvaandering. I need to sign up for a pypi account, which I think should use a "real" dmwm email and not my personal mail. Is there an email I should use for that?

**Comment by ericvaandering** [comment]
I think I set up an e-mail for you to use.

**Comment by PerilousApricot** [comment]
Erm, in the past or just now?

**Comment by PerilousApricot** [comment]
Ah, got it. Thanks.

**Comment by PerilousApricot** [comment]
The changes to setup.py were really minor, and I tested that I can upload to the pypi test server:

```
$ python setup.py register -r https://testpypi.python.org/pypi
running register
running check
Registering wmcore to https://testpypi.python.org/pypi
Server response (200): OK
```

https://testpypi.python.org/pypi/wmcore/1.1.1.pre4

I'll work on a jenkins job on my jenkins instance that will watch the repo and hit the upload command when new tags are made

**Comment by ericvaandering** [comment]
Once you have such a job, please share it so we can put it on the CMS Jenkins instance.

**Comment by PerilousApricot** [comment]
Of course. I'm just using my personal instance since I don't have permission to CMS'.

**Comment by PerilousApricot** [comment]
Wrote and tested a jenkins job that successfully saw a new tag in my personal repo and uploaded to the test pypi: https://jenkins.accre.vanderbilt.edu/job/DMWM-Push-PYPI/78 .

I'm going to change it over so it watches the main WMCore repo and uploads to the real pypi server. I'd like to run it on my personal instance for a couple of tags to make sure it works before I ship it off to be included in the CMS jenkins instance.

**Comment by ericvaandering** [comment]
Sounds good. Then hopefully I can adapt it easily to CMS.

**Comment by PerilousApricot** [comment]
I can dump the .xml for the job and email it to you. The Jenkins admin can use that to import the job directly.

**Comment by ericvaandering** [comment]
Ok. I'm an admin. Should be fine unless you use different plugins

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Feb 23, 2017, at 16:54, Andrew Melo <notifications@github.com<mailto:notifications@github.com>> wrote:


I can dump the .xml for the job and email it to you. The Jenkins admin can use that to import the job directly.

**Comment by goughes** [comment]
Looks like I'll be working on this issue and the other pypi packaging ones.  @PerilousApricot Can you tell me the email for the pypi account?  Is it associated with this user? https://pypi.org/user/cms-oc-dmwm/
