### ISSUE TITLE
RequestTransition records the wrong DN

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7648]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_task_EXO-RunIISummer16DR80Premix-07611__v1_T_170220_173516_7037

unless really mistake @prozober has not toggled the status into acquired, running, ...

**Comment by ticoann** [comment]
Yes, it looks like there is some problem.

**Comment by ticoann** [comment]
Sorry, there was a new bug introduce when I refactor the WQ and move the state transition to ReqMgr for February deployment.
Fix is created #7657
