### ISSUE TITLE
Changes in the submitter plugin for CMS@Home (x509 proxy)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7649]
Agents submitting jobs to T3_CH_Volunteer resources (CMS@Home AFAIK) should not carry the x509 user proxy. So we need to make it configurable such that we can disable it during deployment.
For the record, these were the local changes I made in vocms0159:
```
cmst1@vocms0159:/data/srv/wmagent/current $ diff -rup sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py{.ori,} | colordiff
--- sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py.ori	2017-02-21 11:24:24.295401859 +0100
+++ sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py	2017-02-21 11:24:50.446201566 +0100
@@ -462,8 +462,8 @@ class SimpleCondorPlugin(BasePlugin):
         # Customized classAds for this plugin
         ad['DESIRED_Archs'] = "INTEL,X86_64"
 
-        ad['x509userproxy'] = self.x509userproxy
-        ad['x509userproxysubject'] = self.x509userproxysubject
+        #ad['x509userproxy'] = self.x509userproxy
+        #ad['x509userproxysubject'] = self.x509userproxysubject
 
         ad['Rank'] = 0.0
         ad['TransferIn'] = False
```

**Comment by hufnagel** [comment]
Who asked for this ? This should not be in the agent since in the long run we want to be able to submit to CMS@Home and other resources from the same agents. I thought the approach we took (and which works for now) is to strip out the proxy after the agent submits the job (somewhere on the HTCondor side).

**Comment by amaltaro** [comment]
Nobody, I've just thought we could make it configurable on the agent side. But if Laurence can tweak
the schedd to not use those ads (or to not add them), then it's even better and we can close this issue. I'm waiting for his reply.

**Comment by hufnagel** [comment]
If you want to make it configurable on the agent side, we could do that. I don't think it would be a lot of work. It might even be useful for now to have an extra insurance against exposing production proxies to cms@home users while we figure out how to do this (reliably) on the HTCondor side.

Wait for Laurences reply and see if we can skip this or might need it for now. In the long run it would leave use with dedicated agents just for cms@home though, which is not really what we want.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/8615
