### ISSUE TITLE
Losing tracks of the condor job.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7670]
Some of the jobs in bl_runjob table sched_status is null.

i.e. There are 97 of them in vocms0116 and 90 of them in vocms0130. Other agents has no such a case.

```
select count(*) from bl_runjob where sched_status is null;

```
This causes following query not to return records in this cases.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/MySQL/LoadRunning.py#L24

That seems to be the reason those jobs can't be completed.

I am not completely sure whether this is SimpleCondor plugin related or previously could happen. (Although it seems only new agent have this problem, I couldn't find anything wrong in SimpleCondor plugin).

Here is the place sched_status should be set

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/BossAirAPI.py#L167

and

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L189

But both cases it should be set at least "New" and "Unknown", it can't be setting something not known to db.

1	Unknown
2	Completed
3	Running
4	Held
5	Idle
6	TransferOutput
7	Suspended
8	New
9	Removed

**Comment by ticoann** [comment]
FYI. @hufnagel, @amaltaro

**Comment by amaltaro** [comment]
I say the same thing I said the last time I looked at this code, job tracking needs some serious refactoring. The problem is that the validation is not going to be simple and all of it should take a couple of weeks :( I may look at it in the next month or so...

Now onto the problem, I've just found these lines in the JobStatusLite:
```
2017-02-19 15:12:34,728:139799868892928:INFO:StatusPoller:Killing job 366901 because it has exceeded timeout for status 'Running'
2017-02-19 15:12:34,840:139799868892928:ERROR:BossAirAPI:Mismatch in WMBS load: Some requested jobs not found!
...
2017-02-19 15:12:34,840:139799868892928:ERROR:BossAirAPI:Could not retrieve job with WMBS ID 366901 from BossAir database
2017-02-19 15:12:34,840:139799868892928:ERROR:BossAirAPI:Could not load all jobs in BossAir for WMBS input
...
```

that means:
a) this job timed-out in Running status because it already had a NULL `sched_status`
b) the `Timeout` status set here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/StatusPoller.py#L120 is the troublemaker (though I already made this BIG mistake in the past by removing this Timeout from here and it was a catastrophe)

I'm following the track b), something tells me this is the problem.

**Comment by amaltaro** [comment]
it cannot be b) because this call https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/BossAirAPI.py#L728 didn't return that job (when it was supposed to be killed), since it couldn't find that wmbs id in runjob. Investigating all the other cases that can set a sched_status then

**Comment by amaltaro** [comment]
Seangchan, I confirm your statement above, the plugin cannot return a state that is not known by the database.

There are basically 3 DAOs touching that column:
*) NewJobs : which should be *always* `New`
*) SetStatus : which is not used anywhere in the code.
*) UpdateJobs : which only updates what comes back from the plugin (localChanges here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/BossAirAPI.py#L508)

I couldn't spot any flaw on that code. 
Anyways, a database/table fix was done here, including a x-check against the states known by the plugin and some better logging:
https://github.com/amaltaro/WMCore/commit/9610669a9fbe984d0e813f73593b081306727a77

If we cannot find the problem, we may apply it to one or two nodes and see if we can get additional clues.

**Comment by hufnagel** [comment]
Hm, but then you seem to rule out b). Still, calling an update with a non-valid status IMO is the best guess as to how this could have been set to null.

I would actually suggest to add a not-null constraints on at least one of the agents where this problem occurred. If it happens again the component will crash with the query/update call that caused the problem and we will see what it was trying to do.

**Comment by ticoann** [comment]
@amaltaro, Alan I think actually you found the problem. (I think Timeout status is the case).

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/BossAirAPI.py#L728

This could return that Job.

**Comment by ticoann** [comment]
After discussing with Alan, I create the temporary patch for current production agent.

https://github.com/dmwm/WMCore/pull/7672

1. I will apply this patch in production
2. Then restart either one of (JobSubmitter, JobTracker, JobUpdater) - This should add the Timeout in db
3. manually update sched_status with corresponding number.

Hopefully this will pick out the jobs and fail them. 

@amaltaro, Alan is this OK?

**Comment by amaltaro** [comment]
Thanks, Seangchan. Sounds like a plan! Let me know if you need me ;)
