### ISSUE TITLE
links to ConfigCache

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7681]
It would be extremely useful to have links to taskname : configcacheid from 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_9_0_0_pre4BeamHalo_13__testUnif_170227_132846_7713

so as to be able to quickly navigate to them, by task

**Comment by ticoann** [comment]
@vkuznet, Hi Valentin, could you take this issue as well. I looked at the code little bit but you would fix it much faster than me. 

In the above link (in the table page), we can add a area which displays ConfigCacheID (by Tasks/Steps if necessary) and link to actual record.

URL link will be ("doc"  is json request document - which request page already contains)

url = "%s/reqmgr_config_cache/%s/configFile" % (doc["ConfigCacheURL"], doc["ConfigCacheID"])

There are multiple ConfigCacheID with slightly different name so we have to display all of them.
So it needs to search for string which contains ConfigCacheID as post fix.

**Comment by vkuznet** [comment]
Seangchan, here is a PR: https://github.com/dmwm/WMCore/pull/7729
Few questions though:
- what if ConfigCacheURL is null? The document JR provided has null value for ConfigCacheURL.
- I added a Config Files list of links under the table, but may be you want a different layout, e.g. to show them separate (new button)
Anyhow please deploy first this PR and we can have a look and iterate.

**Comment by vlimant** [comment]
@vkuznet there is ConfigCacheURL and ConfigCacheUrl, the first is valid, the second is null

**Comment by amaltaro** [comment]
Just a correction, it's actually the other way around:
`ConfigCacheUrl` is correct
`ConfigCacheURL` is wrong

see https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1125

**Comment by vkuznet** [comment]
@vlimant, I changed code to use ConfigCacheURL, will iterate with Seangchan.

@ticoann, Seangchan, why on earth you have these two in a document?

**Comment by vkuznet** [comment]
Well, in a document JR pointed out the
"ConfigCacheUrl": null, 
"ConfigCacheURL": "https://cmsweb.cern.ch/couchdb",

My question remains, why two? Get rid of one to avoid confusion.

**Comment by amaltaro** [comment]
There is some legacy code that was just left behind :-) For the case you see `ConfigCacheUrl` null, you probably see `CouchURL` with a valid url, no?
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1121

ReqMgr does enforce the arguments and their values. However, if the argument name (key) is NOT known by ReqMgr, then there is no sanitization (meaning the user can inject whatever he wants in the request json). We already have an issue opened to improve these arguments in case you wonder.

**Comment by amaltaro** [comment]
Which means, requests don't have two, but they may have 3 parameters for the same thing :P

**Comment by vkuznet** [comment]
I want to get Seangchan word about which parameter to use ConfigCacheURL,
ConfigCacheUrl, configCacheUrl, CongiccacheURL, etc.

I think it is waste of developer time to constantly tweak code of dynamically
changing data. Let's fix the data first, make a schema and stick to it.

**Comment by ticoann** [comment]
Sorry Valentin, Alan is right it is ConfigCacheUrl is the correct one. I am not sure how recent workflow has valid value on ConfigCacheURL.

Could you use ConfigCacheUrl but have the default value set as "https://cmsweb.cern.ch/couchdb" if it is null, We will enforce this param in spec level.

**Comment by vkuznet** [comment]
Done, feel free to deploy and let's iterate.
