### ISSUE TITLE
Dynamic-adapting the agent-site threshold to site behavior

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7686]
noticed https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_TOP-RunIISummer16DR80Premix-00130__v1_T_170208_203239_6372 that is well behaved, but KIT does not have over too many pending jobs, and therefore the site threshold in agent 0126 could deserve to be increased to a) put pressure on the site b) get the jobs out at this point in time where they should be out

**Comment by ericvaandering** [comment]
Interesting. No idea it would post here too. I'm going to use it to put together the dependency chart for the DBS schema update and only used this issue as a place keeper.
