### ISSUE TITLE
Set status for a whole bunch of requests at a time

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7687]
@ticoann can you please guide us on how to set assignment-approved multiple requests at the same time. Looking at https://cmsweb.cern.ch/reqmgr2/approve I assume this is possible.
FYI @anorkus

**Comment by anorkus** [comment]
well from the interface i see that you can approve all. Also search was non intuitive, is it searching by workflow name only? How to specify multiple workflows? Or could load workflows from specific campaign - in this case the approve-all button would make sense.

An input field to specify comma separated list to search workflows would be a clear solution.

**Comment by ticoann** [comment]
Search is string matching on request name, it will return all the requests which name contains that string. Then you can click "approve all" button to approve all the request which is filtered or click individual button to hand pick the approval.
Since request name contains the campaign name, if you want to search for specific campaign you can use that for the search.

If there is any suggestion for improve interface we can update that. Please create the issue for those suggestions and use cases.

**Comment by vlimant** [comment]
@ticoann is there a way to set the stauts of multiple requests in one and only one call ?

**Comment by ticoann** [comment]
@vlimant, Are you talking about the (REAST)APIs or WebInterface. 
We don't have currently a call  which can update the status in bulk. Only request by request. (Couch doesn't allow bulk update it has to be client side API or ReqMgr server API which wraps the call and update couch one by one).

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/ReqMgr/ReqMgr.py#L159

Could you give me the specific use case.  i.e. McM need to update to approved status given Campaign, given creation date, etc? We can create REST api or Client api or Web interface.

**Comment by anorkus** [comment]
Hi,
well both options would be best, but main need is for the web interface. Couch has bulk update feature ;) (but you do not need it, as the action would be done on the server looping over the wofklow ids given)

This feature is mostly not for the McM, but for RelVal and other workflows, where they would be approved immediately after innjection. Example are submitted relvals for campaign/batch/whatever (e.g. CMSSW_9_2_0_pre1-someStrangeName) and the submitted wants to approve those in one go. Clearly a more 'loose' search has to be implemented, or a input_area field where user can specify bunch of workflows and approve them.

**Comment by ticoann** [comment]
Hi Atanas, you are right. Couch has bulk update call. It doesn't have bulk _update handler call. I was confused with that. 

For the use case you describe. What would be the approval procedure?
1.  Do RelVal usually validate the parameters before workflow approved?
2. Is the same group  creates the request and approve?
3. What make the two step processing (new -> assignment-approved) If it needs to be approved immediately?

> Clearly a more 'loose' search has to be implemented,

What do you mean by loose search? Could you give me the example of that (what will be the search categories)?

**Comment by anorkus** [comment]
Hi,
everything needed is due to the migration from relval batch_manager to unified.
1) no 2)yes 3)to be same procedures between MC workflows and relvals and rereco.

procedure is easy: 
1. user injects relvals, has list of workflows (all in status new). he can inject workflows in batches: data relvals, fast sim etc.
2. then going to reqmgr2 page and approving the selected batch (or list of workflows).

more loose, means less strict: now it searches only workflow_name while matching the input. There are no wildcard search. Also not possible to search by other parameter(-s) like Campaign: to displays all wf's of this campaign in status new.

**Comment by ticoann** [comment]
> user injects relvals, has list of workflows (all in status new). he can inject workflows in batches: data relvals, fast sim etc.
> then going to reqmgr2 page and approving the selected batch (or list of workflows).

Is the injected batch different from approve batch? If not they can inject and approve consequently without going to reqmgr2. - Not saying that we won't do improve reqmgr2 GUI, I am trying to understand procedure.

> more loose, means less strict: 
I wasn't asking definition of word.  I am asking what search option do you need. It is not clear when you said "more loose". That is not a clear requirement we can implement.

>now it searches only workflow_name while matching the input. There are no wildcard search. Also not possible to search by other parameter(-s) like Campaign: to displays all wf's of this campaign in status new.

Are these only option needed for search,  Campaign, and wildcards?  There are many parameters which can searched by. Depending on how many what you need the interface will change.

**Comment by anorkus** [comment]
doesn't differ. @vlimant could explain more why he wants the requests to be injected, and announced later on.
Those are few options i could think now. Other people @franzoni @fabozzi could suggest other search options.

**Comment by vlimant** [comment]
@ticoann what is needed is an API where one can provide a list of workflows and the statuses of all of them are changed at the same time. If that is not possible, then we can close this issue IMO. 
Unless requesters want specific search capability in the /approve page (a search by Campaign would be sufficient). My 2 cents is that the transition to assignment-approve can be done by script otherwise.

**Comment by fabozzi** [comment]
Hello, sorry to jump on this conversation only now. I think Antanas has explained what is our procedure of relval submission. Basically: we submit a batch of workflows which are identified by the batch name + time stamp strings (contained in the Campaign name). We would like to approve/reject all workflows in a batch after injection. Is it possible right now? I mean, can I make a test of injection and then rejection, to check how it works right now?

**Comment by amaltaro** [comment]
I'm very late to this as well, but may I ask why this bulk update is wanted? Is it because McM (or RelVals?) is going to change how requests are created and approved? Or is it just for a matter of - possible - performance improvement?

**Comment by fabozzi** [comment]
Hi, the reason behind the change is the following:
- We have asked to remove the 4h grace period in Unified, in order to make relvals to be assigned as soon as possible.
- However, at the same time we want to approve or reject explicitly the relvals after injection. This is useful in the typical examples below:
1) We inject a batch of relvals and soon we realize we forgot to add a label useful to prevent dataset collision
2) We inject a batch of relvals and because of a glitch we have submission errors: you will see in reqmgr that a subset of the workflows have been actually injected. So we want to delete them and re-submit (if you have a look in reqmgr you will notice lots of relval workflows that are remnants of these fake submissions)

**Comment by ticoann** [comment]
@fabozzi, Current search is only on request name. But I think Campaign name is enbeded in request name in most cases, correct (as RequestString)?  
In that case you can bulk approve on following page, https://cmsweb.cern.ch/reqmgr2/approve 
(By searching the specific name)
I can add the field for campaign search in next deployment and select box as well (if that is needed).

But I was wondering if the created request is immediately updated to approved, why not add the update call right after creation of the request in whatever script you are using?

You can use the put rest api 
i.e. PUT /reqmgr2/data/request/[request_name]?RequestStatus=assignment-approved

https://github.com/dmwm/WMCore/wiki/reqmgr2-apis

**Comment by fabozzi** [comment]
@ticoann 
the string identifying the batch are embedded in the prepID of the request, not in the RequestString.
So introducing search by prepID could work as well as by campaign (not sure if this is more manageable for you).

**Comment by ticoann** [comment]
Hello 
> We inject a batch of relvals and soon we realize we forgot to add a label useful to prevent dataset collision

This sounds like  some automatic validation is needed. I am not whether this requires human eyes to check in that case support for web interface is sounds right.

> We inject a batch of relvals and because of a glitch we have submission errors: you will see in reqmgr that a subset of the workflows have been actually injected. So we want to delete them and re-submit (if you have a look in reqmgr you will notice lots of relval workflows that are remnants of these fake submissions)

I am just curious.
How do you submit  the workflows and delete them? Are you using reqmgr2 apis or directly couch call? (I don't think we ever provide deleting request call for reqmgr2 api)

**Comment by ticoann** [comment]
> the string identifying the batch are embedded in the prepID of the request, not in the RequestString.
I see.

> So introducing search by prepID could work as well as by campaign (not sure if this is more manageable for you).

We can do both or whatever you prefer.

**Comment by fabozzi** [comment]
@ticoann 
> I am just curious.
> How do you submit the workflows and delete them? Are you using reqmgr2 apis or directly couch > call? (I don't think we ever provide deleting request call for reqmgr2 api)

We submit the workflows using a script... not sure which kind of call is used there.
Our L3 manager are not experts so they do not know anything about reqmgr, etc.
Therefore, they simply resubmit the workflows, and leave the fake ones in the limbo by not putting them in the batchmanager (in the present system we have a batch manager: after injecting the workflows, we use the batchmanager interface to trigger assignement).

In my case, to reject the fake workflows I have used in the past the reqmgr2 web interface 
by clicking on them one-by-one. 
As you can imagine, this is quite painful, when you have to reject tens of workflows...

**Comment by fabozzi** [comment]
@ticoann 
> This sounds like some automatic validation is needed. I am not whether this requires human e
> yes to check in that case support for web interface is sounds right.

the land of mistakes is larger. Other examples that come to my mind: you wanted to submit multicore and you forgot to specify in the command...; or a batch of workflows need higher memory requirement and you forgot to specify in the command. Things that happens when people work under pressure or late in the night... :)

**Comment by ticoann** [comment]
@fabozzi, Thanks for the explanation. So you are the True users of reqmgr2 web interface. I thought no one is using it. :-) I created the issue.

https://github.com/dmwm/WMCore/issues/7704

Please clarify whether that is enough or if you have more specific idea we can follow in that issue.

> the land of mistakes is larger. Other examples that come to my mind: you wanted to submit multicore and you forgot to specify in the command...; or a batch of workflows need higher memory requirement and you forgot to specify in the command. Things that happens when people work under pressure or late in the night... :)

But how do you find out someone made a mistake? If you are using reqmgr2 interface, is there anyway we can make spot them easily? We like to improve our interface so it can be more useful.

**Comment by ticoann** [comment]
Closing this one. replaced by #7692 #7704

**Comment by fabozzi** [comment]
@ticoann 
Hi, I revamp this thread to ask updates on this feature and
what is the plan for the batch approval/reject to enter in production.
Thanks!

**Comment by ticoann** [comment]
@fabozzi, Hi Francesco, Actually I sent email a week ago (March 24th)  about the upgrade and asking for feedback. Subject field was "updated new features on ops requests for April production upgrade" I hope I had a right email address. (sent to CERN email). I am sorry if it didn't get delivered. 

The feature is on the testbed. (adding Campaign), you can check here.
https://cmsweb-testbed.cern.ch/reqmgr2/approve

Production upgrade is today. (I think it is already updated. https://cmsweb.cern.ch/reqmgr2/approve). Please let us know if you find any problem or anything need to be improved.

**Comment by fabozzi** [comment]
Hi, thank you. I would like to search the workflows of a current batch in production, for instance the batch:
CMSSW_9_1_0_pre2__fullsimPU_2017-1491253360

However, if I put that name in the filter, it does not display any workflows.
Am I doing something wrong?

**Comment by fabozzi** [comment]
Maybe only the batches that are in a certain state can be displayed? The workflows of the batch that I was referring are in "running-closed" state.

**Comment by ticoann** [comment]
Sorry that was our mistake. (We shouldn't have add campaign filters for other pages)

Bulk approve/reject only works with when requests are not yet approved.
So only through this link.  
https://cmsweb.cern.ch/reqmgr2/approve

If you want to just check which workflows are in that campaign.
https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?Campaign=CMSSW_9_1_0_pre2__fullsimPU_2017-1491253360&mask=RequestStatus

We can either remove campaign filters from other pages or if that is useful we can fix the other pages for the filter. (I won't have bulk status change capability though, unless you also need those for that - only for abort or reject in that case).

Sorry for the trouble, please let me know what would you prefer. I will create the new issue. Thanks

**Comment by fabozzi** [comment]
OK, thank you. Yes, I agree it is better to remove the campaign filtering from other pages. I am not sure if there is use case for bulk reject/abort. Therefore for the moment bulk approval/reject is sufficient.
