### ISSUE TITLE
Values inheritance for chained requests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7692]
@ticoann Seangchan, and there is yet another case that we didn't foresee :( Taking this request as example:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_MC_HG1703_Validation_170301_142616_3204

its ProcessingString was overwritten during assignment (that's why we have it in the top level dict as a dict object). The inner ProcessingString values are not overwritten in the couch workload doc though, see for more details: https://github.com/dmwm/WMCore/issues/6881

Then the problem is, the values - correctly - inherited are from the inner dicts instead of the dict at the top level.

I don't think it will be a real problem for Production, since the output dataset name  is defined at creation time by McM, so there shouldn't be any change between the values set by McM (at creation) and Unified (at assignment).
For the next cmsweb cycle, I suggest we simply clone the original request into a Resubmission spec and get over all this painful inheritance business.

**Comment by ticoann** [comment]
The rule is  that what ever defined inside (Task/Step) has higher order. So if the parameter is defined outside and has conflict information, parameters are set what is defined inside the Task/Step. I am not sure whether that is the behavior implemented for ACDC and clone, though.

Anyway, I agree that all the replacing should happen in server side.
So for ACDC/clone, client just specify what need to be overwritten and all other parameters should be inherited from original workflow.

**Comment by ticoann** [comment]
Actually the problem is not just ACDC or Clone. It seems it is generic problem for task chain and step chain as long as we allow dict format of params for those types.
ACDC and Clone is affected since it inherits the value and it is initially set vs new workflow won't have initial value for these. patch is created #7744
