### ISSUE TITLE
wrong state transition schema in remqgr2

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#7708]
FYI:
https://github.com/dmwm/WMCore/wiki/request-status

doesn't show that normal-archived can go to rejected-archived. example:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_EXO-RunIIWinter15wmLHE-01948__v1_T_151030_212148_5095
and
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_TRK-TTI2023Upg14GS-00008__v1_T_161103_201557_7993

could the documentation changed? And i would like to know the correct status when workflow succeeds.

**Comment by ticoann** [comment]
Sorry document wasn't updated. announced -> rejected-archived, normal-archived->rejected-archived transition was added last May.
https://github.com/dmwm/WMCore/issues/5944
I will update the diagram.

Meanwhile, here is the allowed state transition.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py#L8

**Comment by ticoann** [comment]
Document is updated. https://github.com/dmwm/WMCore/wiki/request-status
@anorkus, Antanas, Is there anything else need to be done? If not, could you close this issue?
