### ISSUE TITLE
add events number on filerun_lumi table and modify DAO

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7712]
1. add a num_events field for both wmbs
Both  wmbs, dbsbuffer table. Table should accept None in events field for the data which doesn't have record or no record in CMSSW fwjr 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/CreateWMBSBase.py#L97

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/MySQL/Create.py#L118

2. Change DAO to insert event number in that table.

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/MySQL/DBSBufferFiles/AddRunLumi.py

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/MySQL/DBSBufferFiles/GetRunLumiFile.py

3. Change DBS Api to upload event information.

4. Populate the wmbs_file_runlumi_wmbs in when we get the file information from DBS in WMBSFileFeeder

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update WMBS to match DBS](https://trello.com/c/KGgOOFbP/4-update-wmbs-to-match-dbs)

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update WMBS to match DBS](https://trello.com/c/KGgOOFbP/4-update-wmbs-to-match-dbs)

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Insert WMAgent information into DBS](https://trello.com/c/08vMUaOf/5-insert-wmagent-information-into-dbs)

**Comment by amaltaro** [comment]
Is it normal that I get a "Card not found" when I click on these links?

**Comment by ticoann** [comment]
Alan, I think Eric @ericvaandering need to invite you then you can log in.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add events number on filerun_lumi table and modify DAO](https://trello.com/c/wcFBcaRi/9-add-events-number-on-filerun-lumi-table-and-modify-dao)
