### ISSUE TITLE
Very large merge job

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7715]
https://cms-gwmsmon.cern.ch/prodview/fabozzi_RVCMSSW_9_0_0_pre6QCD_Pt_80_120_13_HI__testUnif_170309_154634_5251

 has ended up with jobs like

QCD_Pt_80_120_13_HIMergeFEVTDEBUGoutput	Dashboard link
Hide Debug Information
WallTime	Memory	Cpus	Running	Idle	Scheduler	Desired Sites	Warnings
2200	1000	1	0	4	vocms053.cern.ch	1	

LogCollectForQCD_Pt_80_120_13_HI	Dashboard link
Hide Debug Information
WallTime	Memory	Cpus	Running	Idle	Scheduler	Desired Sites	Warnings
2200	1000	1	0	1	vocms053.cern.ch	1	

both merge and logcollect are requesting to run for 2200.
those tasks are not touched by job routing, which is anyway off on the relval agent.

**Comment by amaltaro** [comment]
Without giving that much thought to it, it must be how cms-gwmsmon evaluates the memory expression, e.g.:
```
OriginalMemory = 1000
ExtraMemory = 500
RequestMemory = OriginalMemory + ExtraMemory * ( WMCore_ResizeJob ? ( RequestCpus - OriginalCpus ) : 0 )
```

so these jobs are actually requesting 1GB. I also checked the workload config and it's correct.

**Comment by juztas** [comment]
one is about walltime, another about memory... cms-gwmsmon allows this to evaluate for htcondor and it does not do any evaluation by itself.

**Comment by amaltaro** [comment]
Daaaah, sorry. Ok, here is the deal then. For some reason (I believe the lack of a decent TpE/SpE values), Andrew requested to have different requirement limits for the Relval agent, which are:
config.JobCreator.GlideInRestriction = {'MaxRequestDiskKB': 20971520, 'MinWallTimeSecs': 132000, 'MaxWallTimeSecs': 132000, 'MinRequestDiskKB': 1048576}

which maps to 2200min. 

Please x-check this tweak with @AndrewLevin and let us know if we should update the deployment of the relval agent to use the default settings.

**Comment by vlimant** [comment]
how did these merge jobs ended up requesting 2200 = max value ? too many events in the merge ?
@AndrewLevin please indeed remind us of the reason behind this

**Comment by AndrewLevin** [comment]
We wanted to make sure that the jobs are not hard killed by the site, which makes it difficult to track down why they were killed, so we set the maxwalltime to be larger than the wmagent soft kill.

**Comment by vlimant** [comment]
@amaltaro how is the merge/log job length estimated ? why is it set to the max allowed value and not something intermediate ?
@AndrewLevin have you had issues with job pending forever because they request for too long of a runtime ? KIT does not seem to like 2200, unless there is something else

**Comment by amaltaro** [comment]
Because there is no intermediate value :-) , see my previous reply and the config snippet.

The agent doesn't really calculate merge job length (actually, I think it's unrealistic to try to figure that out), thus it uses the minimum limit as defined in the config.

**Comment by vlimant** [comment]
Oh ! so all jobs will come out with 2200, no matter what ! It's a bit rough IMO, especially for merge jobs. But if there were no matching issues previously, then we go down the same path until we get proper request values and go with more regular job requirements.

**Comment by AndrewLevin** [comment]
Hi,

I haven't noticed jobs pending forever because they request too long of a runtime. Are you sure they are pending forever, or just a really long time? I have not used KIT recently, maybe it is specific to KIT.

Andrew

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 1](https://trello.com/c/HDmjZb2G/1-issue-1)

**Comment by aperezca** [comment]
Hi Andrew, 

As long as you run on the grid, not on specialized resources, be it at KIT or anywhere else, we are bound by the VO card (*), which specifies 48h maximum walltime . As we also reserve time for pilot draining, it basically mean that such long jobs could only potentially match recently started pilots, not all of them, hence the potential matching issues leading to jobs "pending forever" that Jean-Roch commented.

Antonio.
(*) https://operations-portal.egi.eu/vo/view/voname/cms

**Comment by vlimant** [comment]
de facto those jobs have ~0 chance to run at KIT. they have been pending for more than a day at priority 50,500,000 and 30,500,000. qedited away. we ought to understand what is the actual timelimit that can be requested

**Comment by vlimant** [comment]
@AndrewLevin I think we have been too permissive with long running jobs that would have lead to setting very high max. It turns out that the requested time is only used for matching and the job would live longer than that. The watchdog is set to 44H in unified as a legacy, regardless of how much time is requested in condor.
I just noticed that TimePerEvent is set to 0.1 in the request, which drives under-estimate of the requested time for "regular" steps (i.e. not log/merge/clean). So we end up with request for short jobs for processing which will go over time, and request for long jobs which will run for a minute (if ever matching). We need to review this and get some more reasonable values all around

**Comment by AndrewLevin** [comment]
Hi Jean-Roch,

It is a huge nightmare to deal with situations where jobs are either not matching or they are getting killed by the site. As you have already found out with KIT. So, I just used a constant maxwalltimemin which made the problem go away (although apparently only for FNAL and CCIN2P3). There is a price we pay in terms of slots available that have that much wall time left. However, it seems we can afford to pay that price and I was just very happy to not have to worry about time per event settings. If you want to try to get the relval requesters to set reasonable time per events, good luck with that.

Relval workflows are time-critical, so 44H is probably too long -- I have been using 36 hours for the wmagent soft kill.

Keep in mind that you can only set a single soft kill timeout per workflow.

I am not sure I understand why the merge job was not matching at KIT. Presumably the merge job is only run if there are unmerged files. But all of the jobs that produce the unmerged files would have run with exactly the same wall time request. 

Andrew
