### ISSUE TITLE
Usage of reqmgr_auxiliary couch db and docs in there

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7759]
While scanning couch.log in my personal VM, I noticed several "Not found" while accessing a doc in reqmgr_auxiliary couch db
`[Thu, 30 Mar 2017 13:12:36 GMT] [info] [<0.7813.0>] 128.142.153.212 - - GET /reqmgr_auxiliary/PERMISSION_BY_REQUEST_TYPE 404`

It's not critical because we then use it from the cache (right, Seangchan?).

**Comment by ticoann** [comment]
Yes, currently it is just using the hardcoded default value. So it shouldn't be a problem. I will fix this along with software.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Usage of reqmgr_auxiliary couch db and docs in there](https://trello.com/c/Gkv0lWXr/10-usage-of-reqmgr-auxiliary-couch-db-and-docs-in-there)
