### ISSUE TITLE
Job left over from aborted workflow

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7762]
I noticed 
https://cms-gwmsmon.cern.ch/prodview/fabozzi_RVCMSSW_9_0_0GluGluHToZZTo4L_M125_Pow_py8_Evt_13__PU25_reHLTcc7_170327_230233_6021

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_9_0_0GluGluHToZZTo4L_M125_Pow_py8_Evt_13__PU25_reHLTcc7_170327_230233_6021

which is aborted-archived. From the relval agent. Is that agent fully up to date on the release version ?

**Comment by ticoann** [comment]
Agent is upto date but transition between aborted and aborted-completed happened too fast (faster than the polling cycle). agent misses the update.

I will create the patch for handling this cases.

```
aborted: Wed Mar 29 2017 02:42:36 GMT-0500 (CDT)
aborted-completed: Wed Mar 29 2017 02:43:56 GMT-0500 (CDT)
 {
      "Status": "aborted", 
      "UpdateTime": 1490773356
    }, 

    {
      "Status": "aborted-completed", 
      "UpdateTime": 1490773436
    }, 
```

**Comment by ticoann** [comment]
I will kill those jobs manually. If that is OK with you.

**Comment by ticoann** [comment]
I kill those jobs without permission. 😄

**Comment by vlimant** [comment]
I just condor_rm all jobs from 

https://cms-gwmsmon.cern.ch/prodview/prozober_ACDC0_task_HCA-PhaseIFall16GS-00007__v1_T_170331_105036_8804

we ought to get aborted workflows fully under control.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_9_0_0ZEE_13__reHLTcc7_170327_174211_5619
https://cms-gwmsmon.cern.ch/prodview/fabozzi_RVCMSSW_9_0_0QCD_Pt_3000_3500_13__reHLTcc7_170327_174200_6576
https://cms-gwmsmon.cern.ch/prodview/fabozzi_RVCMSSW_9_0_0TTbar_13__reHLTcc7_170327_174237_7732
and many others from the relval agent

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_JME-PhaseIFall16GS-00006__v1_T_170309_141735_7301 has spewed thousands of jobs while it has been aborted for 15 days.
https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_JME-PhaseIFall16GS-00006__v1_T_170309_141735_7301

**Comment by amaltaro** [comment]
These are the moment I'm totally against of having more agents than needed in production.
gwmsmon doesn't give me the agents running these jobs (and it's archived, so no longer in wmstats), so there we go in agent by agent to locally abort it.

**Comment by amaltaro** [comment]
Hmm, I found only 4 jobs on vocms0311, though gwmsmon says PIC has almost 2k jobs pending?!?

**Comment by vlimant** [comment]
I did condor_rm emergency those from 311 because I am baby sitting PIC in running through a backlog.
I hope that there will be no more jobs fro aborted at next agent release, so that noone has to go through the pain full process.
gwmsmon does tell the agent, when clicking on "show debug information"

**Comment by ticoann** [comment]
Sorry, Jean-Roch. The patch is ready. We can patch the current production agents.

**Comment by ticoann** [comment]
@vlimant All the production agents are patched. Please let me know if this happens again.

**Comment by amaltaro** [comment]
Seangchan, have you patched only agents up and running? Or you also pushed it into draining and sleeping/ready agents? According to the twiki, some agents are missing it.

**Comment by ticoann** [comment]
I added only active agents (meaning) where I can see in wmstats including draining agent. For the complete list, twiki page is updated.
