### ISSUE TITLE
Too many DNS queries for cmsweb.cern.ch

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7765]
I've just received an email from cern it complaining about too many DNS queries for cmsweb.cern.ch. The worst offenders are:
```
vocms0314.cern.ch :
                         cmsweb.cern.ch    5202  queries in the last 2 hours (0.7 per sec)
 
vocms053.cern.ch :
                         cmsweb.cern.ch    7323  queries in the last 2 hours (1.0 per sec)
```

besides a bunch of crab3 nodes.

I'll look at it tomorrow.

**Comment by amaltaro** [comment]
and some documentation they have provided:
http://service-dns.web.cern.ch/service-dns/faq.asp

**Comment by ticoann** [comment]
what do you mean by DNS query? Is that the query try to resolve DNS names? Which DNS is it try to resolve?

**Comment by amaltaro** [comment]
I still didn't manage to look at the IT documentation, but what I understood is the following case for instance:
```
>>> import socket
>>> socket.gethostbyname('cmsweb.cern.ch')
'188.184.65.109'
```

so we're resolving cmsweb.cern.ch name way too often. Unless I misunderstood it :-)

**Comment by PerilousApricot** [comment]
The easy fix is to install dnsmasq on the affected host(s), which will cache DNS queries

**Comment by amaltaro** [comment]
CERN IT said we need to run nscd daemon on those hosts. I've contacted the VOC (who is/was on vacation) and he should follow up on it. Thus, I'm closing this ticket
