### ISSUE TITLE
remove campaign filter from other than approve pages in reqmgr2

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7768]
Or fix the filter.

**Comment by ticoann** [comment]
@vkuznet, Valentin, could you take a look at this?

i.e. Campaign filter doesn't work.
https://cmsweb.cern.ch/reqmgr2/requests?status=running-open

on approve page it works.
https://cmsweb.cern.ch/reqmgr2/approve

**Comment by vkuznet** [comment]
Seangchan, try this PR: https://github.com/dmwm/WMCore/pull/7778
I think I missed to show campaign on a page and it cause the behavior.
It would be nice if you'll add it to your VM and add few requests with
different campaigns to test it.
