### ISSUE TITLE
Inconsistent status WQE/reqmgr

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7770]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_HIRun2015-HIMinimumBias1-02May2016_758p4_170331_112803_4571

looks to be in an odd situation.
Or is it just waiting for T0 to be up ?
@prozober that might have to be redone

**Comment by amaltaro** [comment]
It's not inconsistent. ReqMgr status will be `running-open` while there is at least 1 WQE in `Acquired` status. Haven't we circulated these definitions when this transition was made (maybe it was sent to the wf-team egroup)?

**Comment by vlimant** [comment]
ok. I suspected something like that too. 

what is in the way of the jobs to be made then

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_ACDC0_HIRun2015-HIMinimumBias1-02May2016_758p4_170331_112803_4571

is this because of T0 holding part of the required input ?
