### ISSUE TITLE
Retrieve assignment default arguments for assignment via web UI

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7840]
Since we separated the creation from assignment arguments, the ReqMgr2 assignment form no longer shows the default assignment values for some of those arguments (merge and block args in general).

We should change it such that:
1) it retrieves the assignment arguments definition, as in:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1042
2) it retrieves the request dictionary (it already does)
3) then it overrides the default arguments by the request one
4) fill in the form with the pre-selected values.

**Comment by amaltaro** [comment]
@vkuznet would you have some time in the next week to work on this ReqMgr2 issue?
If so, let me know how I can be of assistance. :-)

**Comment by vkuznet** [comment]
Alan, please be specific and provide screen shot where changes should go and/or point to the code which needs to be changed.

**Comment by amaltaro** [comment]
Valentin, I'm talking about the "Assign" page, for example this workflow is GOOD and it has all the default values already set in the web form (because their json has ALL key/value args since its creation):
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ReDigi_BadTier_HG1704_Validation_170327_150804_7008

on the other hand, this workflow Assign page is BAD, as you can see there are lots of unfilled fields (because we still don't have several key args in the request json):
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_EpL_HG1705_Validation_170426_211542_1394

Hmm, we already have these args hard-coded here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L394

why they don't show up in the web form then?
Besides that, my initial suggestion is to get rid of these args and fetch them from StdBase specification (my first comment here), and cache it in memory, since it only changes during cmsweb deployments.

**Comment by vkuznet** [comment]
Alan,

> Valentin, I'm talking about the "Assign" page, for example this workflow is GOOD and it has all the default values already set in the web form (because their json has ALL key/value args since its creation):
> https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ReDigi_BadTier_HG1704_Validation_170327_150804_7008
> 
> on the other hand, this workflow Assign page is BAD, as you can see there are lots of unfilled fields (because we still don't have several key args in the request json):
> https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_EpL_HG1705_Validation_170426_211542_1394
> 
> Hmm, we already have these args hard-coded here:
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L394
> 
> why they don't show up in the web form then?

because both workflow you shown above comes from "fetch" method not from assign
one, i.e.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L560
that's why both URLS have:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=<request_id>

The assign code you pointed out is invoked when you call
https://cmsweb-testbed.cern.ch/reqmgr2/assign

(click on Settings button to see arguments you mentioned on line L394).

I think what you want is to apply similar logic (line 394) in fetch method.

> Besides that, my initial suggestion is to get rid of these args and fetch them from StdBase specification (my first comment here), and cache it in memory, since it only changes during cmsweb deployments.

That's fine by me, please take this PR: https://github.com/dmwm/WMCore/pull/7843
and apply it to your testbed and we can see if it will provide what you want.

Best,
Valentin.

**Comment by vkuznet** [comment]
Alan,
did you review/deploy my changes for this issue?
Thanks,
Valentin.

**Comment by amaltaro** [comment]
Not yet. I was busy with some critical stuff. I'll look at it tomorrow.
