### ISSUE TITLE
Is StepChain able to process a "tree" of tasks

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7841]
Is the StepChain fully linear task1->task2->task3, or can it allow task1->task2 task1->task3, which is possible with TaskChain
Example https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HCA-PhaseISpring17GS-00001__v1_T_170502_201648_8745

**Comment by amaltaro** [comment]
Yes, but if step2 and step3 have the same output module, it will not pass the validation during creation time. See issue: https://github.com/dmwm/WMCore/issues/6787

**Comment by amaltaro** [comment]
And I guess I can close it... reopen/rename if needed please.
