### ISSUE TITLE
Review data structs for agent/services metrics

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7847]
These are the metrics we upload to wmstats (agentInfo), here:
https://cmsweb.cern.ch/couchdb/_utils/database.html?wmstats/_design/WMStatsErl/_view/agentInfo

Benjamin discussed with Alberto (CERN IT) and we have to improve some of these metrics in order to have an easier data lookup and aggregation. 

BTW, dots '.' are not allowed in key names. @stiegerb can you please:
*) find out which regex is used to validate these key names
*) and comment here on a few cases - with examples - that should be changed from/to
?

As we discussed, I'm assigning this issue to you :) but if it becomes urgent and you don't manage to check it, we can always reassign it.

**Comment by amaltaro** [comment]
This is one (big) api used to collect global workqueue information:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1153

and then some of these APIs are again used on the agent side:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py#L133

**Comment by stiegerb** [comment]
About allowed key names, it seems only dots are a problem.

One example is the `workByAgentAndPriority` for the global_workqueue agent, where we use the agent hostname as field names:

```
  "workByAgentAndPriority": {
       "http://vocms0130.cern.ch:5984": {
           "900000": {
               "count": 7,
               "min": 1,
               "max": 112,
               "sum": 169,
               "sumsqr": 13387
           }
       }, ...
```

This falls under the restructuring anyway, so we should fix both in one go.

One other thing, we have a top level `type` field, which is always `agent_info`. Shall we change that to something else for the `reqmgr` and `global_workqueue` documents?
