### ISSUE TITLE
Jobs completed in BossAir but still in condor pool

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7849]
While draining the 1.1.0 agent, I've seen two major issues related to the job tracking:
1) pending condor jobs still being tracked by JobStatusLite even after the Timeout has exceeded (they were pending for more than 1M secs). The reason seems to be from the fact that they don't have `status_time` in the `bl_runjob` table.
2) held condor jobs not being tracked anymore, but still in condor for several days. Apparently because their `status` in `bl_runjob` is 0, meaning the job is considered completed and there is no more tracking.

This happened in several agents! I'll resume working on it soon before it causes more damage...

**Comment by hufnagel** [comment]
Keep in mind that jobs dropping out of tracking but still in Condor are not considered a problem with the SimpleCondor plugin. Being able to make a best effort to kill a job in HTCondor job but ultimately not caring if it really is killed in HTCondor is a feature of the SimpleCondor plugin, not a bug. We track by HTCondor job id, so multiple versions of the same job alive in HTCondor don't matter, only the one current version is going to be tracked by the agent. So I would say 2 isn't a problem (or only a problem if we never bothered to call a kill on them before we abandoned them).

1 is a problem though.

**Comment by amaltaro** [comment]
I still think held jobs should get removed from htcondor. I have to check whether we actually try removing them after the `Error` timeout. Otherwise having jobs in condor for a workflow that is already completed may just cause confusion, and I think it also counts to the MAX_JOBS_RUNNING limit.

For possible future reference, I've got 5 held jobs in my dev machine and this is the status of bl_runjob and wmbs_job for them:
```
MariaDB [wmagent]> SELECT rj.id, rj.wmbs_id, rj.grid_id, rj.status, rj.sched_status, rj.status_time,
    ->   wmbs.state AS wmbs_state, wmbs.state_time AS wmbs_state_time, wmbs.outcome AS wmbs_outcome, wmbs.cache_dir
    ->   FROM bl_runjob rj INNER JOIN wmbs_job wmbs ON rj.wmbs_id = wmbs.id
    ->   WHERE sched_status = 5;
+-----+---------+----------+--------+--------------+-------------+------------+-----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id  | wmbs_id | grid_id  | status | sched_status | status_time | wmbs_state | wmbs_state_time | wmbs_outcome | cache_dir                                                                                                                                                            |
+-----+---------+----------+--------+--------------+-------------+------------+-----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 652 |     728 | 2848.179 | 0      |            5 |  1495120697 |          4 |      1495120949 |            0 | /data/srv/wmagent/v1.1.2.patch4/install/wmagent/JobCreator/JobCache/amaltaro_ReDigi_cmsRun2_May_Validation_170518_095954_8928/StepOneProc/JobCollection_30_0/job_728 |
| 657 |     733 | 2848.184 | 0      |            5 |  1495120998 |          4 |      1495121189 |            0 | /data/srv/wmagent/v1.1.2.patch4/install/wmagent/JobCreator/JobCache/amaltaro_ReDigi_cmsRun2_May_Validation_170518_095954_8928/StepOneProc/JobCollection_30_0/job_733 |
| 668 |     744 | 2848.195 | 0      |            5 |  1495120998 |          4 |      1495121189 |            0 | /data/srv/wmagent/v1.1.2.patch4/install/wmagent/JobCreator/JobCache/amaltaro_ReDigi_cmsRun2_May_Validation_170518_095954_8928/StepOneProc/JobCollection_30_0/job_744 |
| 672 |     748 | 2848.199 | 0      |            5 |  1495120576 |          4 |      1495120709 |            0 | /data/srv/wmagent/v1.1.2.patch4/install/wmagent/JobCreator/JobCache/amaltaro_ReDigi_cmsRun2_May_Validation_170518_095954_8928/StepOneProc/JobCollection_30_0/job_748 |
| 680 |     756 | 2849.7   | 0      |            5 |  1495120817 |          4 |      1495120949 |            0 | /data/srv/wmagent/v1.1.2.patch4/install/wmagent/JobCreator/JobCache/amaltaro_ReDigi_cmsRun2_May_Validation_170518_095954_8928/StepOneProc/JobCollection_30_0/job_756 |
+-----+---------+----------+--------+--------------+-------------+------------+-----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
5 rows in set (0.00 sec)
```

where `status=0` is completed and `status=1` means the job is active.
And `outcome=1` is success and 0 for failure.

**Comment by hufnagel** [comment]
Confusion for who ? An operator ? Maybe. For the system no. If the rest of the code is done correctly these extra jobs will just be ignored. And yes, we should certainly try to kill them. Sometimes they cannot be killed though an everything should still work correctly in that case.

**Comment by hufnagel** [comment]
Same thing for MAX_JOBS_RUNNING, if these jobs count then the code that counts them is buggy. Jobs that drop out of tracking shouldn't be counted for anything.

**Comment by amaltaro** [comment]
For the held jobs:
https://cms-logbook.cern.ch/elog/GlideInWMS/5393

if we have a hook on the condor_schedd side, then it's much better.
