### ISSUE TITLE
Agent Manager System

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7851]
Putting this in writting, as discussed a couple of times.
In order to not have too many agents in production at the same time, I think we need an agent-manager component that would bring in-or-out agents based on specific operation rules (like boot an agent in the production team if all agents are running to their maximum amount of jobs).
Doing it manually is bringing delays and there is no real reason to have a person doing this ; which operation should do in the meantime.

**Comment by amaltaro** [comment]
For the record, Unified is doing most of this already:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L5528
