### ISSUE TITLE
Remove RFIO plugins

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#7854]
The way I read https://github.com/cms-sw/cmssw/issues/17375#issuecomment-300428060 there is no longer any reason to support RFIO stageout . Comments, @hufnagel ?

**Comment by hufnagel** [comment]
While I agree with removing old crap code, there is this:

[hufnagel@lxplus028 SITECONF]$ grep rfcp */JobConfig/site-local-config.xml
T2_FR_IPHC/JobConfig/site-local-config.xml:      <command value="rfcp"/>
T2_FR_IPHC/JobConfig/site-local-config.xml:      <catalog url="trivialcatalog_file:/opt/exp_soft/cms/SITECONF/local/PhEDEx/storage.xml?protocol=rfcp"/>
T2_MY_UPM_BIRUNI/JobConfig/site-local-config.xml:     <command value="rfcp-2"/>
T2_MY_UPM_BIRUNI/JobConfig/site-local-config.xml:     <catalog url="trivialcatalog_file:/opt/exp_soft/shared_soft/cms/SITECONF/local/PhEDEx/storage.xml?protocol=rfcp"/>
T2_TH_CUNSTDA/JobConfig/site-local-config.xml:     <command value="rfcp"/>
T3_TH_CHULA/JobConfig/site-local-config.xml:     <command value="rfcp"/>

Should work through SiteSupport and have them suggest that these should be changed. In fact, I would suggest if you are serious about cleaning up the stageout plugins, that SiteSupport suggests to all sites to either switch to the xrdcp plugin or the gfal2 one. IMHO these are the only ones we really need at this stage.
