### ISSUE TITLE
Limit of MC GQ work (lumi sections)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7855]
As discussed in this issue: https://github.com/dmwm/WMCore/issues/7575

In short, there is a limitation in the GWQ -> LWQ data acquisition of MonteCarlo (MCFakeFile) where each WQE is mapped to a file in the SQL local database. This file has a mapping of run/lumis where each lumi corresponds to a row in the table. Thus, we of course have to avoid injecting 1M rows for one single file (that's why the job splitting makes a difference here).

The current limitation - to fail request acquisition by GWQ - is set to 200k lumis per WQE. Forgetting about a code refactoring/redesign, we could try either:
a) bumping this limit to ??? in global workqueue, maybe 400k lumis and see how the agent deals with this load
b) decrease the number of jobs created for each MonteCarlo WQE. It used to be 250 in the past, but it was creating many thousands WQE per workflow. Then we bumped it to 1000, which makes 4 x less WQE but then creates much more lumis on the agent database. Maybe we could again decrease it to 500 (or 750)/
c) Unified has to take this limit into account and set the job splitting accordingly.

Matteo, Paola, can you please point me to the workflow assigned that went through with a smaller job splitting. I'd like to check how long `WorkQueueManagerWMBSFileFeeder` took to inject those X lumis per file.

**Comment by vlimant** [comment]
FYI @prozober @mcremone 
@amaltaro  can the amount of work put in a single wqe be defined in term of # of lumis ?

**Comment by prozober** [comment]
Alan, here is the workflow https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=prozober_HIN-pPb816Spring16GS-00048_00011_v0_pPbBst_GENonly_170517_183430_6353

**Comment by amaltaro** [comment]
With some extra effort, yes, we could use # of lumis instead. However, I think this will simply move the problem down in the chain while balancing WQE among several agents. It may be that the WQE becomes 10 jobs only, or maybe 10k jobs, etc. A mix of both would be much better, but I'm not sure how much work that's going to take.

Paola, are you sure that's the workflow? It created a single job, 1000 events...

**Comment by prozober** [comment]
Yes, 100% sure. Only thing I changed was "events_per_job": 20000.

**Comment by vlimant** [comment]
the cloning must have gone astray indeed :   "RequestNumEvents": 1000 is in the schema

**Comment by prozober** [comment]
I used https://github.com/CMSCompOps/WmAgentScripts/pull/221
`python reject.py -i -c pdmvserv_HIN-pPb816Spring16GS-00048_00011_v0_pPbBst_GENonly_170420_201218_4615`

**Comment by mcremone** [comment]
@amaltaro do you have any other suggestion? Is there anything else we can try or shall we reject it?

**Comment by amaltaro** [comment]
@mcremone I've just updated my initial comment in this ticket. If that doesn't answer your question, then please elaborate.

**Comment by thongonary** [comment]
We might want to start with increasing the limit to 400k lumis per WQE. @amaltaro steps we should follow for this?

FYI @vlimant @prozober

**Comment by amaltaro** [comment]
Ok, I'll talk to Lina (HTTP team) on Monday and then we can increase it to 400k and watch how the agents are going to respond to that. I'll update here once that is done.

**Comment by amaltaro** [comment]
Lina has updated the global workqueue settings and it should now be limiting it to 400k lumis per MC WQE. Are you guys going to assign any workflow that's known to overcome that limit? If so, please provide the request name once it gets assigned such that I can watch an agent or two.

**Comment by amaltaro** [comment]
It turns out this # of lumis check is also performed on the agent side when writing docs to the local `workqueue` db, see Jean-Roch's issue here (my last comment): https://github.com/dmwm/WMCore/issues/7910

**Comment by amaltaro** [comment]
It turns out this # of lumis check is also performed on the agent side when writing docs to the local `workqueue` db, see Jean-Roch's issue here (my last comment): https://github.com/dmwm/WMCore/issues/7910

**Comment by thongonary** [comment]
@amaltaro What's the status of the agent now? Do we have a patch for the agent so that it won't perform the number of lumis check?

**Comment by amaltaro** [comment]
Yes, all the agents have been patched and the # of lumis check should be performed by global workqueue only. Patch was applied yesterday afternoon.

**Comment by amaltaro** [comment]
Fixed by #8077
