### ISSUE TITLE
Investigate job splitting  on file boundaries

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7860]
we were looking at https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2016D-v2-DoubleEG-18Apr2017_8028_170519_180444_7852 that created DataProcessing jobs of 50-150 min walltime, while it should be creating jobs with a requested walltime of about 8h
@amaltaro would be be related to the "halt on file boundary" ?
FYI @bbockelm

**Comment by bbockelm** [comment]
Doesn't look that bad to me:  https://es-cms.cern.ch/goto/11d20073462d64cdcb9c40649f30bf0e

**Comment by amaltaro** [comment]
Looking at the workflow configuration:
  "TimePerEvent": 4, 
      "events_per_job": 7200, 

so the job splitting settings are Ok.
Now whether those jobs processed much less events, that could be and it could be coming from the fact that files are splitted between files, as you mentioned and as discussed (hmm, I thought we had a GH for that...).

Let me rename this issue.

**Comment by amaltaro** [comment]
As discussed in a private thread, ReqMgr is setting the correct job splitting value (targetting 8h jobs), but the job splitter algo may stop assigning work to a job if it goes beyond one single file (even whole files).

Possible impacts are
a) related to merging scrambled lumi sections
b) file parentage (?) But we can have one file being processed by different jobs, then different merge jobs processing these children... I cannot say what problem would that cause (@hufnagel ?)

**Comment by vlimant** [comment]
@bbockelm looking at https://cms-gwmsmon.cern.ch/prodview/fabozzi_Run2016D-v2-DoubleEG-18Apr2017_8028_170519_180444_7852 I see requested walltime in the range 100-150 min. 
Maybe the jobs are running for 8h : fine with me, and good even. But the job are requesting 4x less. Could this be a /mcore in the condor plugin ?

**Comment by amaltaro** [comment]
Cannot see any logic flaw here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L546-L552

the plugin should be asking for 480min in this case.

**Comment by vlimant** [comment]
for the record, neither resizing nor performance tuning is enabled for that campaign, so Unified is not tampering with those numbers. Is there anything that could play weird with the condor expression for the requested wall time @bbockelm  ?

**Comment by bbockelm** [comment]
@amaltaro - is it possible the units here are wrong:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L547 ?

`estimatedJobTime` is treated as if it were estimated *wall time*; if it was actually *core time*, then it might explain the difference.

**Comment by amaltaro** [comment]
The unit is correct. The real problem (which in this case I consider to be the right thing actually) is coming from the splitter algo:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L215

since it doesn't add 7200 events for each job, the requested wall time floats according to the number of events to be processed by each job. So sorting out what's mentioned in this subject, should also fix this problem.

**Comment by vlimant** [comment]
was trying to make sense of estimatedMinsSingleCore and estimatedMins and I am lost in what they actually min

**Comment by amaltaro** [comment]
I discussed this matter with Eric yesterday and the plan is the following:
1. run the integration workflows in testbed with that flag off
2. if everything goes fine, then we patch the production agents setting that to false
3. last but not least, we make that parameter configurable at workflow assignment (if really ever needed?)

IMO, checking the consistency/correctness of the data produced is going to be a challenge. I'll check only the output in terms of lumis/completion, dbs and phedex registration. However, if there is a problem, I think it would be spotted only when analysing and/or processing the data produced.
So... if someone wants to have a look at some data to make sure it's Ok before it goes to production, that would be great.

**Comment by amaltaro** [comment]
And for the point 3., issue created: https://github.com/dmwm/WMCore/issues/7864

**Comment by vlimant** [comment]
@amaltaro, any update on the test in testbed ?

**Comment by amaltaro** [comment]
We ran a bunch of workflows in testbed and I haven't seen any operational issues. I also picked one output dataset and it has the parent files in dbs. Of course I didn't investigate what a processing -> a merge job executed and what are the children and parents. I'll try checking that later today/tomorrow.

**Comment by vlimant** [comment]
does this mean we could move the default to false at the next deployment ?
