### ISSUE TITLE
Automatically increment ProcVer on clones ?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7862]
Hey @vlimant @prozober @mcremone
does it make sense to automatically bump the ProcessingVersion on clone requests (when using the clone API)? 

That would be either 0 or 1, which means, either we **always** bump it to all ProcessingVersion key/values present in the request, or we do not! Not something that the user can pass a flag and ask or not for the bump.

**Comment by vlimant** [comment]
yes. The version can always be re-changed back at assignment

**Comment by amaltaro** [comment]
Awesome. I'll make sure to add it in the current testbed.
