### ISSUE TITLE
Make halt_job_on_file_boundaries configurable at assignment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7864]
@ericvaandering @vlimant do we really need it? If the multi-files job works just fine, we probably have no reason to ever turn that off, do we? If so, then we better not code something that is not going to be useful IMO.

**Comment by ericvaandering** [comment]
Well, I come at this from exposing all the parameters of the job splitting to the request. Otherwise why have a parameter? But if agree that changing the default is enough, OK with me.

**Comment by amaltaro** [comment]
I'd say some of those are just internal splitter parameters with a sensible default value that should never change. Otherwise we need to expose all of these:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L42-L54

We can likely get rid of of some, but it's always good to keep it there in case you see you messed something up years later.

**Comment by amaltaro** [comment]
Nothing has happened in the last 2 years. If we have the need to have it configurable, then we can come back to this issue. Closing it now though.
