### ISSUE TITLE
Implement PeriodicRemove expression for held jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7881]
It could either be set in the condor_schedd configuration or be added to the job classads.
We better ad it to every job such that we control the exact expression.

According to Stefano, it's just a matter of defining that expression:
https://cms-logbook.cern.ch/elog/GlideInWMS/5393

no further ads are needed.
For reference, this is how it's done for CRAB:
https://github.com/dmwm/CRABServer/blob/f8770011dcd03febc7218ecbc49e3b4b9b0c7684/src/python/TaskWorker/Actions/DagmanSubmitter.py#L488

though in our case I think it should be (plain english) `job is on Hold && currentStatusTime > 10minutes` or so.

**Comment by vlimant** [comment]
do you know what are the reasons a job would go in held status ? and how would they end up being treated in the agent ? is there a specific error code ? is this counting as a retry ?

**Comment by amaltaro** [comment]
AFAIK it usually happens with a site-specific problems. However, if I'm not wrong I've also seen it happening with unhandled mistakes/exceptions in the WMCore code.

They are completed in the agent and they go to jobcooloff status (or failure).
About the specific code, yes it should be exit code 71306. but wait... there is something fishy here...

**Comment by amaltaro** [comment]
@hufnagel @ticoann we do kill (well, we should) jobs that go into held status, see:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/StatusPoller.py#L109

however, the problem is that this job is no longer active in BossAir since the plugin says it's completed:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L235

which is never returned to StatusPoller (in order to kill and tag it)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/BossAirAPI.py#L474

Shouldn't we instead leave this held job in active and let StatusPoller (JobStatusLite) kill it based on the Error mapped state and its timeout? Of course, if we do so then we have to distinguish Error(Removed) from Error(Held):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L44

**Comment by amaltaro** [comment]
BTW, I assume Held jobs don't return the agent FJR, meaning the agent has no clue of what happened to this job thus flagging those jobs with that 99xxx exit code (no job report)
