### ISSUE TITLE
Task ProcessingVersion default value shouldn't be 0

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7891]
That change was made by me and there was a good reason to keep that set to 0 (I think to fallback to the workload level arg in case that was eval to false).

However, if one creates a TaskChain request with ProcessingVersion arg only at the top level, the task dict will override that to 0, thus the output dataset for that task will be `v0`.

We either set the inner task default to 1 or we don't set a default there, such that the top level (workload) is used instead. I think latter option is better and less error prone.

**Comment by amaltaro** [comment]
example to reproduce that:
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/Integration/RelVal_Premix.json

**Comment by ticoann** [comment]
I agree the latter (we don't set a default there) is better. So the version start from 0 not 1?

**Comment by amaltaro** [comment]
For this case it starts from 0, but that's wrong and it should always start from 1.
