### ISSUE TITLE
Merge not ran with the proper CMSSW version of the previous step

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7900]
from https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_task_EXO-RunIISummer15GS-10533__v1_T_170602_203815_9168 having a lot of merge issues

pdmvserv_task_EXO-RunIISummer15GS-10533__v1_T_170602_203815_9168.tasks.EXO-RunIISummer15GS-10533_0.tree.children.EXO-RunIISummer15GS-10533_0MergeRAWSIMoutput.tree.children.EXO-RunIISummer16DR80Premix-09475_0.tree.children.EXO-RunIISummer16DR80Premix-09475_1.tree.children.EXO-RunIISummer16DR80Premix-09475_1MergeAODSIMoutput.steps.cmsRun1.application.setup.cmsswVersion = 'CMSSW_7_1_26'

while 

pdmvserv_task_EXO-RunIISummer15GS-10533__v1_T_170602_203815_9168.tasks.EXO-RunIISummer15GS-10533_0.tree.children.EXO-RunIISummer15GS-10533_0MergeRAWSIMoutput.tree.children.EXO-RunIISummer16DR80Premix-09475_0.tree.children.EXO-RunIISummer16DR80Premix-09475_1.steps.cmsRun1.application.setup.cmsswVersion = 'CMSSW_8_0_21'

and 

"Task4": {
    "KeepOutput": true, 
    "PrepID": "EXO-RunIISummer16MiniAODv2-09410", 
    "InputFromOutputModule": "AODSIMoutput", 
    "GlobalTag": "80X_mcRun2_asymptotic_2016_TrancheIV_v6", 
    "TimePerEvent": 0.4, 
    "FilterEfficiency": 1, 
    "SplittingAlgo": "EventAwareLumiBased", 
    "ProcessingString": "PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6", 
    "ScramArch": [
      "slc6_amd64_gcc530"
    ], 
    "SizePerEvent": 60, 
    "ConfigCacheID": "b6dbf93947e795314241186527e3202d", 
    "Memory": 5900, 
    "Multicore": 4, 
    "TaskName": "EXO-RunIISummer16MiniAODv2-09410_0", 
    "AcquisitionEra": "RunIISummer16MiniAODv2", 
    "PrimaryDataset": "DarkSUSY_mH_125_mN1_30_mGammaD_5_cT_50_13TeV_pythia8", 
    "Campaign": "RunIISummer16MiniAODv2", 
    "InputTask": "EXO-RunIISummer16DR80Premix-09475_1", 
    "CMSSWVersion": "CMSSW_8_0_21"
  }, 

I am pretty sure we have had this issue in the past and I have recollection that this was fixed. If not, now is a very good time.

FYI @prozober

**Comment by vlimant** [comment]
https://github.com/dmwm/WMCore/issues/7012

**Comment by vlimant** [comment]
this had not been fixed back in the day. @ticoann are you available to look into this ?

**Comment by amaltaro** [comment]
not good... I'm looking into this problem

**Comment by amaltaro** [comment]
puzzled! We have a template exercising the same cmssw behaviour and all tasks/cmssw release are correct. I cloned this workflow twice into testbed and again I see the correct releases for all those tasks
https://cmsweb-testbed.cern.ch/reqmgr2/config?name=amaltaro_task_EXO-RunIISummer15GS-10533__v1_T_170607_132706_7769
https://cmsweb-testbed.cern.ch/reqmgr2/config?name=amaltaro_task_EXO-RunIISummer15GS-10533__v1_T_170607_131143_3971

I also took a look at the code and merge + logcollect should always be using the same cmssw/Scram as the parent task (production/processing task). 

It's still not clear to me how it could happen... I want to start writing more unit tests for all these specs and all possible cases that come to my mind. I'll try to get that done this week and maybe that will expose an issue that I failed to see here.

**Comment by vlimant** [comment]
can you try to clone it a thousand times and check if ever that happens ?
are any of these operations done in parallel and some corruption would happen through shared memory ?

only solution for now is cloning, I suppose.

**Comment by ticoann** [comment]
Looking at the code, I can't see why it is not setting up the CMSSW correctly for the merge.
The private variable  self.frameworkVersion is responsible for setting the CMSSW version correctly.
The thing it can go wrong is that self.frameworkVersion is workload variable and not thread safe.
However I don't think it is using multi thread when it creates the spec object.
Maybe I don't quite understand the code either - too fancy. :-)

FYI. @amaltaro, Alan it seems the following code is actually used to set the CMSSWVersion

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L120
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L167

I was wondering do we need to update parameters here

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L345

Shouldn't it be updated already
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L343

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, 

1. when you clone the request everything is set correctly?
2. Is it consistently happening only for the merge task?

**Comment by vlimant** [comment]
Only for the merge task has this been observed. And cloning seems to work.
N.B. the injection from McM is done in parallel if I remember correctly (@anorkus).

There seem to be quite some of those at the moment, under RunIISummer15GS.
@ticoann  can you think of the way to identify those by script so that @prozober can grab them all and clone ?

**Comment by vlimant** [comment]
#7467

**Comment by ticoann** [comment]
I created the script to identify the case. However I have to add some method on WMCore to make this work and script is not robust. ( I will try to refine the script and update WMCore code to support that).
However, still debugging what could cause this.

@prozober - Below are active requests which has different cmssw version between merge job and parent task.

(request name, task name,  original cmssw version, (set of both merge version and task version))  

```
pdmvserv_task_EXO-RunIISummer15GS-09419__v1_T_170522_162023_7144 EXO-RunIISummer16MiniAODv2-07873_0 CMSSW_8_0_21 set(['CMSSW_7_1_25_patch3', 'CMSSW_8_0_21'])
pdmvserv_task_EXO-RunIISummer15GS-09409__v1_T_170522_161820_9646 EXO-RunIISummer16MiniAODv2-07863_0 CMSSW_8_0_21 set(['CMSSW_7_1_25_patch3', 'CMSSW_8_0_21'])
pdmvserv_task_EXO-RunIISummer15GS-10521__v1_T_170602_203533_2356 EXO-RunIISummer15GS-10521_0 CMSSW_7_1_26 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10507__v1_T_170602_203214_2449 EXO-RunIISummer15GS-10507_0 CMSSW_7_1_26 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-09435__v1_T_170522_162428_820 EXO-RunIISummer16MiniAODv2-07889_0 CMSSW_8_0_21 set(['CMSSW_7_1_25_patch3', 'CMSSW_8_0_21'])
pdmvserv_task_EXO-RunIISummer15GS-10480__v1_T_170602_202603_4357 EXO-RunIISummer16DR80Premix-09422_1 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10480__v1_T_170602_202603_4357 EXO-RunIISummer16MiniAODv2-09357_0 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10534__v1_T_170602_203817_6714 EXO-RunIISummer15GS-10534_0 CMSSW_7_1_26 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10528__v1_T_170602_203653_7181 EXO-RunIISummer16DR80Premix-09470_1 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10528__v1_T_170602_203653_7181 EXO-RunIISummer16MiniAODv2-09405_0 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10533__v1_T_170602_203815_9168 EXO-RunIISummer16DR80Premix-09475_1 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10533__v1_T_170602_203815_9168 EXO-RunIISummer16MiniAODv2-09410_0 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10522__v1_T_170602_203532_8549 EXO-RunIISummer16DR80Premix-09464_1 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10522__v1_T_170602_203532_8549 EXO-RunIISummer16MiniAODv2-09399_0 CMSSW_8_0_21 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
pdmvserv_task_EXO-RunIISummer15GS-10527__v1_T_170602_203653_8600 EXO-RunIISummer15GS-10527_0 CMSSW_7_1_26 set(['CMSSW_8_0_21', 'CMSSW_7_1_26'])
```

**Comment by vlimant** [comment]
you could try to create the same type of workflow in 10-20 simultaneous threads so that the same code gets called at the same time. That's what is happening on submission side of these workflows.
