### ISSUE TITLE
No retries on error code 87

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7901]
this kind of error is clearly not recoverable by a retry, so we should not even try.

**Comment by amaltaro** [comment]
For bookkeeping, can you please post here the error message for this exit code?

**Comment by vlimant** [comment]
Fatal Exception (Exit code: 8026)
An exception of category 'NotFound' occurred while

**Comment by vlimant** [comment]
Fatal Exception (Exit code: 8023)
An exception of category 'MismatchedInputFiles' occurred while
[0] Calling InputSource::readFile_
Exception Message:
RootPrimaryFileSequence::nextFile() Branch 'GlobalObjectMapRecord_hltGtStage2ObjectMap__HLT.' is in file 'root://ccmsdlf.ads.rl.ac.uk//castor/ads.rl.ac.uk/prod/cms/store/unmerged/Run2016B/NoBPTX/RECO/18Apr2017_ver1-v1/10004/1086F426-9B47-E711-8D27-0242AC110004.root'
but not in previous files.

CMSSWStepFailure (Exit code: 87)

**Comment by amaltaro** [comment]
Instead of failing jobs on exit code 87 (which I haven't found anywhere a description for it), shouldn't we fail jobs with 'MismatchedInputFiles' (8023)?

**Comment by vlimant** [comment]
here goes the confusion of the many exit codes exposed in wmstats.
whichever is the error code that is being seen by the agent, this should not be retried. I'd say add 87 and 8023

**Comment by amaltaro** [comment]
Calling it 8023 then.
