### ISSUE TITLE
fix condor log being displayed in single column text

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7904]
for example

NoJobReport

    NoJobReport (Exit Code: 99303)

        Could not find jobReport
        Adding end of condor.13468.0.log to error message:
        <
        /
        c
        >

        <
        c
        >

         
         
         
         
        <
        a
         
        n
        =
        "
        P

is just unreadable in wmstats

**Comment by amaltaro** [comment]
dup of #7798 :) closing
