### ISSUE TITLE
Special Error for SYSTEM_PERIODIC_REMOVE

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7906]
@thongonary and I were looking at 

https://cmst2.web.cern.ch/cmst2/unified//condorlogs/pdmvserv_task_HIN-pPb816Spring16GS-00049__v1_T_170601_155641_5744/99303/HIN-pPb816Spring16GS-00049_0/1047/vocms0304_1047339/Job_1047339/condor.12807.0.log

and the error code in wmstats is 99303, while 

    <a n="MachineAttrGLIDEIN_CMSSite0"><s>T2_CH_CERN</s></a>
    <a n="Proc"><i>0</i></a>
    <a n="TriggerEventTypeName"><s>ULOG_JOB_ABORTED</s></a>
    <a n="EventTime"><s>2017-06-03T01:38:56</s></a>
    <a n="EnteredCurrentStatus"><i>1496446736</i></a>
    <a n="ExtDESIRED_Sites"><s>T1_DE_KIT,T1_ES_PIC,T1_FR_CCIN2P3,T1_RU_JINR,T1_UK_RAL,T2_AT_Vienna,T2_BE_IIHE,T2_BE_UCL,T2_BR_SPRACE,T2_CH_CERN,T2_CH_CERN_HLT,T2_CH_CSCS,T2_CN_Beijing,T2_DE_DESY,T2_DE_RWTH,T2_ES_CIEMAT,T2_ES_IFCA,T2_FR_CCIN2P3,T2_FR_GRIF_IRFU,T2_FR_GRIF_LLR,T2_FR_IPHC,T2_GR_Ioannina,T2_HU_Budapest,T2_IT_Bari,T2_IT_Legnaro,T2_IT_Rome,T2_KR_KNU,T2_PL_Swierk,T2_PT_NCG_Lisbon,T2_RU_JINR,T2_TR_METU,T2_TW_NCHC,T2_UK_London_Brunel,T2_UK_London_IC,T2_UK_SGrid_Bristol,T2_UK_SGrid_RALPP,T2_US_MIT,T3_IN_TIFRCloud</s></a>
    <a n="QDate"><i>1496410842</i></a>
    <a n="TriggerEventTypeNumber"><i>9</i></a>
    <a n="WMAgent_JobID"><i>1047339</i></a>
    <a n="MyType"><s>JobAdInformationEvent</s></a>
    <a n="Cluster"><i>12807</i></a>
    <a n="JobStatus"><i>3</i></a>
    <a n="Reason"><s>The system macro SYSTEM_PERIODIC_REMOVE expression '( ( NumJobStarts &gt; 9 ) || ( NumShadowStarts &gt; 19 ) || ( DiskUsage &gt; 27000000 ) )' evaluated to TRUE</s></a>

is there a way to not have 99303, but something that has more meaning ?

**Comment by vlimant** [comment]
@amaltaro @ticoann

**Comment by amaltaro** [comment]
I think this `Reason` from the condor.log file is the same as the `RemoveReason` present in the job classad once it gets removed by condor.

As already discussed with Brian and the CRAB team, checking the job history classAds is **not** the proper way to do post-mortem handling, thus what we can do is to check this condor.log file and basically publish the reason content (which is not that clear by itself, since it tells the expression is True, but not which part of it).

Unless it's too convoluted, we should be able to have this for the next WMAgent release in August.

**Comment by vlimant** [comment]
I really wish we can have a separate error code for jobs ending up in SYSTEM_PERIODIC_REMOVE, is this the plan ? it is seriously impacting operation

**Comment by ticoann** [comment]
That wasn't the plan. :-) I was going to get the specific message with the same excode. but We can add the new exit Code. Could you give me the exitCode for this?

There is no range for GlideIn particularly.
https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes

So you want me to define something in (90000-99999)?
