### ISSUE TITLE
Job pending at site set in Drain, and status Drain in the agent

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7916]
despite being in drain, there are many jobs still pending at

https://cms-gwmsmon.cern.ch/prodview/T2_UK_London_IC

and in particular some merge jobs (which are not jobrouted) which I was expecting to be removed

**Comment by amaltaro** [comment]
I browsed through a few requests in gwmsmon and they mostly have merge/logcollect jobs, which is allowed by the system (including harvesting and cleanup):
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L323

However, this request seems to have processing/production jobs running there:
https://cms-gwmsmon.cern.ch/prodview/prozober_ACDC0_task_SMP-RunIISummer16DR80Premix-00199__v1_T_170608_111442_3606#

but connecting to the agent and listing what that site has running/pending, I get only those merge/utilitarian jobs.
