### ISSUE TITLE
CC7: AgentStatusWatcher fails to get proxy information (symbol lookup error)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7936]
I finally managed to deploy wmagent on the CC7 nodes, after manually installing the following packages (I still have to ask Daniel to puppetize them):
`yum -y install libXft-devel libXpm-devel libXext-devel mesa-libGLU-devel perl-Switch perl-Env perl-Thread-Queue`

and services/components run without any apparent issues.

However, looking at the AgentStatusWatcher logs, I see it's failing to retrieve the timeleft for the user proxy (debug):
```
2017-06-15 14:11:55,225:140049327441664:DEBUG:Proxy:Executing : 
 command : voms-proxy-info -file PROXYFILE -timeleft
 output : 
 error: voms-proxy-info: symbol lookup error: voms-proxy-info: undefined symbol: _ZN8vomsdataC1ESsSs

 retcode : 127
2017-06-15 14:11:55,225:140049327441664:ERROR:Proxy:Error while checking proxy timeleft for PROXYFILE
```

the interesting part is that it works just fine if the agent environment is not sourced.

Google suggests checking the shared libraries linked from voms-proxy-info with 
```
ldd `which voms-proxy-info`
```

which then shows several libraries being used from cms comp stack

**Comment by amaltaro** [comment]
And I forgot to mention that I don't know even from where to start debugging this issue :(

**Comment by davidlt** [comment]
I guess you are using `voms-clients-cpp` and something is wrong. lxplus7.cern.ch uses `voms-clients-java`, you cold try using it.

**Comment by davidlt** [comment]
Correction boths are installed on lxplus7.cern.ch, but JAVA clients are used (in my case).

**Comment by amaltaro** [comment]
The executable is the same
`/bin/voms-proxy-info`

how do I check whether it uses cpp or java?

then the libraries being used by the standard `voms-proxy-info` are:
```
cmst1@vocms0192:/afs/cern.ch/user/a/amaltaro $ ldd `which voms-proxy-info`
	linux-vdso.so.1 =>  (0x00007ffd921e6000)
	libvomsapi.so.1 => /lib64/libvomsapi.so.1 (0x00007fe505061000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007fe504df3000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fe504a08000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fe5047de000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe5044d5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe5041d2000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe503fbc000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe503bfb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe5039de000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fe503790000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fe5034a9000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fe5032a4000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fe503072000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe502e6e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe502c57000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe5054ec000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fe502a48000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fe502843000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe502629000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe502401000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fe5021a0000)
```

while the one with the agent environment (cms comp packages) are (with 2 additional libraries):
```
cmst1@vocms0192:/afs/cern.ch/user/a/amaltaro $ ldd `which voms-proxy-info`
	linux-vdso.so.1 =>  (0x00007fffe196d000)
	libvomsapi.so.1 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/condor/8.5.7-comp/lib/condor/libvomsapi.so.1 (0x00007f659147c000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f6591201000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f6590e17000)
	libexpat.so.1 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/expat/2.0.1/lib/libexpat.so.1 (0x00007f6590deb000)
	libstdc++.so.6 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6 (0x00007f6590c68000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6590966000)
	libgcc_s.so.1 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libgcc_s.so.1 (0x00007f659094e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f659058c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6590370000)
	libssl.so.1.0.0 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/openssl/1.0.1r/lib/libssl.so.1.0.0 (0x00007f6590300000)
	libcrypto.so.1.0.0 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/openssl/1.0.1r/lib/libcrypto.so.1.0.0 (0x00007f6590136000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f658fee8000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f658fc01000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f658f9fc000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f658f7ca000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f658f5c6000)
	libz.so.1 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/zlib/1.2.8/lib/libz.so.1 (0x00007f658f5aa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f659172a000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f658f39b000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f658f196000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f658ef7c000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f658ed54000)
	libpcre.so.1 => /data/srv/wmagent/v1.1.4.pre8/sw/slc7_amd64_gcc630/external/pcre/8.37/lib/libpcre.so.1 (0x00007f658ed0f000)
```

**Comment by davidlt** [comment]
If you would use Java clients then `voms-proxy-info` would be a symlink to a bash script which calls Java client.

So you ship your own `libvomsapi.so.1` thus this sounds like API (maybe also ABI) breakage . Especially if you by accident call `voms-proxy-info` from the system.

**Comment by amaltaro** [comment]
Thanks to @davidlt for passing by and helping me to understand this issue (I hope).

There are several problems, but in summary it's the classic mix between comp and system libraries.
As we can see from the comments above, condor ships the vomsapi library but not the voms-client, which is then incompatible since condor is built with gcc630 (and the new c++11 ABI).

There are several ways to fix it, two that I considered are:
1) does htcondor need to build/enable the vomsapi library @bbockelm ? If not, you may just disable it in the spec and build new RPMs (in addition to that, we could bump the version to 8.6.3 as used in production right now).
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condor.spec#L48
2) if it does need the vomsapi, then we should consider building our own voms client package and stop using the system one.

David, feel free to correct me or complement anything important that is missing on this summary.

**Comment by davidlt** [comment]
Sounds correct. The original commit 4 years ago does provide information on why voms was enabled in htcondor. If it's definitely needed then you have multiple directions you can go to resolve it.

**Comment by bbockelm** [comment]
I can confirm that the VOMS library is necessary.

That said, as part of the HTCondor build, it should have downloaded and compiled VOMS also.  It's possible that either there's a problematic path or the library isn't getting packaged.

**Comment by davidlt** [comment]
That's exactly the problem. HTCondor builds voms library 2.0.13 IIRC, but it doesn't provide voms-clients. voms-clients (2.0.14) are being used from system, but in comp environment it picks the library from HTCondor. The one provided by HTCondor (which overrides default) is not compatible with what's on the system.

**Comment by bbockelm** [comment]
HTCondor libraries should be staged such that they are not put into `$LD_LIBRARY_PATH` (unless maybe we muck with the generated `$RPATH` for the condor libraries?)

**Comment by davidlt** [comment]
Correct. I would suggest to make sure that voms library (bundled within HTCondor) is built in static way. That would solve the issue.

**Comment by amaltaro** [comment]
Just for the record, we've just hit the same issue on a SL6 node at FNAL which apparently upgraded the voms-client to 2.0.14. WMAgent comp package was built using the current production scram (slc6_amd64_gcc493).
I'm going to ask Krista not to upgrade it on the production nodes because I won't be looking at this issue in the coming days/week, at least.

**Comment by amaltaro** [comment]
One more update on it, I've just noticed we run v3 on our slc6 nodes, which uses the java api:
```
cmst1@vocms0125:/data/srv/wmagent/current $ voms-proxy-info --version
voms-proxy-info v. 3.0.7 (voms-api-java/3.0.6 canl/1.3.3)
cmst1@vocms0125:/data/srv/wmagent/current $ rpm -qa  | grep voms
voms-api-java3-3.0.6-1.el6.noarch
voms-2.0.14-1.el6.i686
voms-2.0.14-1.el6.x86_64
voms-clients-cpp-2.0.14-1.el6.x86_64
voms-clients3-3.0.7-1.el6.noarch
```

while the CC7 node has an upgraded version - which is v2 ... ?!? - and there is no voms-client3 package available for it
```
cmst1@vocms0192:/data/srv/wmagent/current $ voms-proxy-info --version
voms-proxy-info
Version: 2.0.14
Compiled: Sep 11 2016 05:41:34
cmst1@vocms0192:/data/srv/wmagent/current $ rpm -qa | grep voms
voms-clients-cpp-2.0.14-1.el7.x86_64
voms-2.0.14-1.el7.x86_64
```

I've built the same condor version RPM but enabling static voms library (I think), I'm going to test it soon. In case any of you want to x-check the build log, see it here (PS.: this one was for slc6):
http://amaltaro.web.cern.ch/amaltaro/forAlan/condor-static-build-log

**Comment by bbockelm** [comment]
My (admittedly vague) understanding is that voms-clients3 was a rewrite of the command-line clients into Java -- and this approach is no longer being pursued.

VOMS3 was a pure-Java effort; the only branch with C / C++ support is VOMS2.  Hence, the supported line of clients is VOMS2.

Again, only a vague understanding, but that seems to match what you see in practice?

**Comment by amaltaro** [comment]
Apparently yes. Having a look at their github repo should answer this question.

About this problem, I have this PR which is - possibly - addressing this issue.
https://github.com/cms-sw/cmsdist/pull/3323

voms-proxy-info no longer links to the condor shared library, though I see a couple of extra libraries regarding one of my first comments here. Just in case, here is the output of ldd after I rebuilt WMAgent+condor RPMs with the patch in that PR:
```
cmst1@vocms0192:/data/srv/wmagent/current $ ldd `which voms-proxy-info`
	linux-vdso.so.1 =>  (0x00007ffe309a1000)
	libvomsapi.so.1 => /lib64/libvomsapi.so.1 (0x00007f61db263000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f61daff4000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f61dac0a000)
	libexpat.so.1 => /data/srv/wmagent/v1.1.6.pre3/sw.amaltaro/slc7_amd64_gcc630/external/expat/2.0.1/lib/libexpat.so.1 (0x00007f61dabde000)
	libstdc++.so.6 => /data/srv/wmagent/v1.1.6.pre3/sw.amaltaro/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libstdc++.so.6 (0x00007f61daa5b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f61da759000)
	libgcc_s.so.1 => /data/srv/wmagent/v1.1.6.pre3/sw.amaltaro/slc7_amd64_gcc630/external/gcc/6.3.0/lib64/libgcc_s.so.1 (0x00007f61da741000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f61da37f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f61da163000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f61d9f15000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f61d9c2d000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f61d9a29000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f61d97f7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f61d95f2000)
	libz.so.1 => /data/srv/wmagent/v1.1.6.pre3/sw.amaltaro/slc7_amd64_gcc630/external/zlib/1.2.8/lib/libz.so.1 (0x00007f61d95d7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f61db6f0000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f61d93c7000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f61d91c3000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f61d8fa9000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f61d8d81000)
	libpcre.so.1 => /data/srv/wmagent/v1.1.6.pre3/sw.amaltaro/slc7_amd64_gcc630/external/pcre/8.37/lib/libpcre.so.1 (0x00007f61d8d3c000)
cmst1@vocms0192:/data/srv/wmagent/current $
```

Last but not least, voms commands are functional again. I'm going to run a couple of workflows just to make sure condor/python bindings are working as expected.

**Comment by amaltaro** [comment]
Yep, voms3 clients are only available in java, indeed. Even though you find some references to c/c++ apis, it's all java.
