### ISSUE TITLE
Failed workflow

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7939]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=rverma_PR_reference_RelVal_296967_170616_175347_6854

is failed. What is the reason and where can we see the reason for that failure ?

**Comment by amaltaro** [comment]
There seems to be lack of input work. Apparently some of those lumis listed are not present in the dataset.

This is the message from global_workqueue logs:
```
2017-06-16 20:00:08,931:ERROR:WorkQueue:Failing workflow "rverma_PR_reference_RelVal_296967_170616_175347_6854": No work in spec: 'rverma_PR_reference_RelVal_296967_170616_175347_6854' Check inputs: Failed to add work. Input data: ["input.section_('WMBS')", 'input.sandbox = None', "input.section_('splitting')", 'input.splitting.runs = [296967]', "input.splitting.algorithm = 'LumiBased'", "input.splitting.lumis = ['1,200']", 'input.splitting.deterministicPileup = False', 'input.splitting.lumis_per_job = 1', "input.splitting.section_('performance')", 'input.splitting.performance.sizePerEvent = 2000.0', 'input.splitting.performance.memoryRequirement = 8000.0', 'input.splitting.performance.timePerEvent = 10.0', "input.section_('dataset')", "input.dataset.section_('runs')", 'input.dataset.runs.blacklist = []', 'input.dataset.runs.whitelist = []', "input.dataset.section_('blocks')", 'input.dataset.blocks.blacklist = []', 'input.dataset.blocks.whitelist = []', "input.dataset.name = '/HLTPhysics/Run2017A-v1/RAW'", "input.dataset.primary = 'HLTPhysics'", "input.dataset.dbsurl = 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader'", "input.dataset.processed = 'Run2017A-v1'", "input.dataset.tier = 'RAW'"], mask: None.
```

**Comment by vlimant** [comment]
ok, thanks.

**Comment by vlimant** [comment]
how do we expose this out to operation ?

**Comment by amaltaro** [comment]
I'll discuss this issue with Seangchan today, but I created this ticket the last time it happened:
https://github.com/dmwm/WMCore/issues/7808

**Comment by vlimant** [comment]
There is at least

that file 

https://cmsweb.cern.ch/das/request?input=lumi%20file%3D/store/data/Run2017A/HLTPhysics/RAW/v1/000/296/967/00000/2EAA18F4-9D52-E711-BE81-02163E0142A6.root&instance=prod/global&idx=0&limit=10

 to be processed. Please check the code for possible interference when LumiList is bigger than the list of lumis in the file.

 This needs to be understood quite fast @amaltaro @ticoann

**Comment by franzoni** [comment]
Hello Jean-Roch, Alan,

thanks for the feedback.

That PD has lumi sections [1,22]. 
https://cmswbm.cern.ch/cmsdb/servlet/DatasetSummary?RUN=296967
https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fdata%2FRun2017A%2FHLTPhysics%2FRAW%2Fv1%2F000%2F296%2F967%2F00000%2F2EAA18F4-9D52-E711-BE81-02163E0142A6.root&instance=prod%2Fglobal 

The wf's asks for [1,200] - while that's not ideal,
one would expect that  that the [1,22] be picked up. Or does requesting lumi section number 23, which is not present, invalidates the workflow altogether ?

Ravindra, Bajarang,
we'll need to resubmit this, please contact us for details.

Cheers,
Arun and Giovanni for AlCa/Db

**Comment by amaltaro** [comment]
A quick scan at the code tells me that range of lumi sections should have worked. I couldn't spot a place rejecting this workflow if some of the lumis are not in the block:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L83

Anyways, I always thought this LumiList feature was something along the golden json files we use to use for real data, meaning requestor should provide THE runs and lumis he/she wants to have processed, not "give me whatever you can in this range".

**Comment by franzoni** [comment]
hi @amaltaro 

> LumiList feature was something along the golden json

it's said in the email that requesting more LS's than the existing ones was not a good choice.

If that's not the reason why the workflow failed,
can we try to find it, so we ensure that future workflows won't hit the same ?

**Comment by vlimant** [comment]
@amaltaro as you said, the code should support [1,200] while the data has only [1,28]. Why did it fail then ?
Could it be that the file was not yet in DBS at the time of submitting the workflow ?

    "modification_time": "2017-06-16 19:33:35" is for the file 

and 

    new: 2017-06-16 15:53:47 UTC
    assignment-approved: 2017-06-16 15:53:53 UTC
    assigned: 2017-06-16 17:55:47 UTC
    failed: 2017-06-16 18:00:11 UTC

is for the workflow.

sounds reasonable indeed.
@franzoni resubmittion is the way to go

**Comment by amaltaro** [comment]
Makes a lot of sense. Are you cloning it or resubmitting with a proper lumi list? I'm interested to see a clone of it, otherwise I'll clone it tomorrow myself.

**Comment by ravindkv** [comment]
Hi All, 

We have already resubmitted the WFs, this time with another run number and lumi range. Here are the campaign IDs:
HLT+RECO
CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_13_50
Unfortunately, there is a failure again with HLTPhysics datasets. And for other two datasets, the status is "running-closed" (https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_13_50)

PR
CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_14_02
Similar status (https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_14_02)

Thanks a lot.

**Comment by bajarang** [comment]
Hello @vlimant @amaltaro @franzoni @ravindkv @arunhep

I want to mention two things, in regard to the two campaigns which Ravindra mentioned just above.

Not to confuse things, I will first mention the workflows ([A] below) which we would need your help in tracking the bugs 
[A] **Please track following workflows** : 
For HLT+RECO in https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_13_50
(i) verma_HLT_newco_RelVal_297050_170619_135328_5533
(ii) rverma_HLT_newco_RelVal_297050_170619_135340_8581
(iii) rverma_HLT_refer_RelVal_297050_170619_135252_224
(iv) rverma_HLT_refer_RelVal_297050_170619_135309_2515
For PROMPT in https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_9_2_3_patch2__ALCARELVAL-2017_06_19_14_02
(i) rverma_PR_reference_RelVal_297050_170619_140317_6177
(ii) rverma_PR_reference_RelVal_297050_170619_140325_7167
The above workflows are for datasets SigleElectron and JetHT, and they are all in running-closed state with error "Files in no block". Would you suggest for such type of errors to resubmit from scratch checking the availability of files on the DAS?

Next I will mention below the workflows which we should be discarding as we noticed some problem with them.
[B] **Please neglect the workflows below** : 
For HLT+RECO 
(i) rverma_HLT_newco_RelVal_297050_170619_135319_2764
(ii) rverma_HLT_refer_RelVal_297050_170619_135242_6494
For PROMPT 
(i) rverma_PR_reference_RelVal_297050_170619_140309_4713
Please neglect these workflows which are for HLTPhysics dataset. As we accidentally chose the wrong dataset name for these, thats why they are in forget/failed state.

Apologies for the clutter. I will report back the correct HLTPhysics workflows here in some time.

Regards,
Bajrang
