### ISSUE TITLE
Deprecating stage out plugins

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7940]
I just talked to @stlammel and @roksys to see if the SS team can start pushing sites away of (almost) deprecated transfer tools. I'm posting here a summary of what I found in SITECONF repo,  feel free to x-check these numbers.

**local stage out for T0/T1/T2 sites** see command used to grep here [1]
```
      2 cp
     17 gfal2
      1 rfcp
      1 rfcp-2
      5 srmv2
     31 srmv2-lcg
      2 stageout-xrdcp-fnal
      1 vandy
      5 xrdcp
```

**fallback stage out for T0/T1/T2 sites**
```
     14 gfal2
      1 rfcp
      2 srm
      5 srmv2
     15 srmv2-lcg
```

As you can see, I discarded T3s configuration since we mostly don't use them.

I believe the goal is to keep only 3 implementations around (well, 4 with vandy). So gfal2, xrdcp and cp (+ vandy). Correct?

In a short term, I think we can deprecate only rfcp* and srmv2. By the way, is there any difference between `srmv2` and `srmv2-lcg`?

[1]
grep -A5 -r '<local-stage-out>' /cvmfs/cms.cern.ch/SITECONF/T{0,1,2}*/JobConfig/site-local-config.xml | grep 'command value' | awk -F'=' '{print $2}' | awk -F'"' '{print $2}' | sort | uniq -c

**Comment by ticoann** [comment]
Thanks Alan for doing that. It seems even with this list, we can remove half of the plugins in the code.

**Comment by hufnagel** [comment]
As a proposal how to move forward, how about we remove what we obviously can. Then instead of fighting to have sites change to change their stageout so we can remove more, we look at a very limit list of plugins that we want to support in the next version of the stageout code. Then when that code is ready the argument to get sites to switch will be stronger.

I assume here that even if we rework that v2 stageout code significantly, we'll keep the possibility to define what stageout code version we want to use in the stageout section in site-local-config. That way we can gradually change sites over.

**Comment by hufnagel** [comment]
Of course, all sites currently using something obviously deprecated (lcg-cp, ahem) we should more or less force / strongly suggest to that they switch to gfal. And if a site is the only user of another plugin, we might have site support ask what's so special they need their own plugin.

My argument is more from the development angle, if we are serious about switching to new stageout code, any cleanup more than the obvious in the current plugins is somewhat wasted effort.

**Comment by ticoann** [comment]
I agree with Dirk. I will first clean up the not used ones on the list. Then we can discuss further.

**Comment by stlammel** [comment]
Removing plugins not on the list may cause problems as Alan's list
excludes Tier-3s.
I don't know the history of having so many plugins but agree to
reduce them to just one (or a few) well supported ones.
                                                   cheers,  Stephan

**Comment by gastonlp** [comment]
Hi Everyone, 

Here's a list including T3 sites for local stage out:

Plugin, # of sites
cp,  13
gfal2 , 23
rfcp, 2
rfcp-2,  1
srmv2, 18
srmv2-lcg, 58
stageout-xrdcp-fnal,  6
vandy, 1
xrdcp, 9

For the fallback

 cp, 4
 gfal2,22
 rfcp,1
 srm,4
 srmv2,32
 srmv2-lcg,54
 stageout-xrdcp-fnal,6
 xrdcp,8

I would like to ask what is the timeline for removing srmv2, as currently 76 sites use a variation of it for local stage out. I'll open tickets to all the sites, but I feel that setting and exact date for deprecation, not too long in the future, would push sites towards executing the change quickly.

Cheers, 
Gaston

**Comment by stlammel** [comment]
Thanks Gaston! The srmv2* we'll keep for right now. srmv2-lcg will
be phased out with SL 6.
                             cheers,  Stephan

**Comment by gastonlp** [comment]
Dear All, 

The rfcp and rfcp-2 plugins have been removed from all the active T2 sites. Currently the only active site using it is T3_TH_CHULA, which has an open ticket requesting its removal.
I believe it can be safely removed. 


Regards, 
Gaston Lyons

**Comment by ticoann** [comment]
Thanks Gaston!

**Comment by amaltaro** [comment]
Thank you very much, Stephan and Gaston! First round of removals is here: #8012

The next - easier one - might be `srm`, only 2 T2s with this fallback and 4 sites in total.

**Comment by gastonlp** [comment]
Hi Alan, 

'srm' is currently being used in only three sites: T3_US_Cornell, which doesn't have a CE on the VO feed  ,T2_MY_UPM_BIRUNI , a morgue site that has been disabled for a long time, and T3_US_UCR which is currently working on the removal [1].

It should be removable very quickly.

Cheers, 
Gaston.

[1] https://ggus.eu/?mode=ticket_info&ticket_id=129189

**Comment by amaltaro** [comment]
Gaston, since none of these sites are used by production and - apparently - that T3 site has made the necessary changes, I'm removing the srm plugin from WMCore. Anyways these changes won't be in production before August.

**Comment by stlammel** [comment]
Yes, thanks Alan! The remaining site is broken anyhow, no reason
to wait for them.
                    - Stephan

**Comment by ericvaandering** [comment]
Is this issue still open? Are there more plugins to remove?

**Comment by ticoann** [comment]
closing it

**Comment by stlammel** [comment]
We are working on phasing out Posix/cp now, ahead of the Singularity.
                                                             - Stephan

**Comment by stlammel** [comment]
The last site replaced cp with gfal2, so the Posix/cp stage-out plugin can/should be phased out. (It will not work with Singularity and the new SAM tests.) Thanks,
- Stephan
