### ISSUE TITLE
WMRuntime code incompatible with python2.6

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7944]
As surfaced in this PR #7937, there can be a specific setup that causes all jobs to fail when executing the WMAgent runtime code with features that are only available from python 2.7 on, for instance a dictionary comprehension. Of course the workflow needs to be using an old'ish release that uses python 2.6 instead (e.g. 537_patch5).

Apparently we do execute SetupCMSSW code with the COMP python2.7 (scramPreScripts attr is an empty list btw, so I don't know how this block gets executed...):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L191

but then the python version can be overwritten in the Scram library:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Tools/Scram.py#L311

We can discuss here how to properly handle these case and make sure wmruntime code is always compatible with the interpreter being used.

**Comment by ticoann** [comment]
@amaltaro, Alan this is fixed with your recent patch, isn't it?

**Comment by amaltaro** [comment]
AFAIK the scram command is still executed with COMP python, so it should have been python2.7.
I'm not sure it was fixed (or actually there was anything to fix), but I'll just close it and assume we won't be running python2.6 CMSSW anymore :)
