### ISSUE TITLE
Mapping OutputDataset to TaskName

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7968]
in case of step/task chain, what is the best way to get 
{
"Task1": ["output1"],
"Task2":[].
...
}

type of dictionnary ?

**Comment by ticoann** [comment]
It seems we don't store OutputDataset by Task in reqmgr couch db. Only the list of Outdatasets for the whole workflow. Is there any correlation between task name and output datasets?

You can query like following to get the list separately.  (real task name, not Task1, etc)

https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?RequestStatus=running-closed&RequestType=TaskChain&mask=OutputDatasets&mask=TaskName

**Comment by vlimant** [comment]
is there a way to get this from the "spec" https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_task_BPH-PhaseIISpring17GS-00004__v1_T_170621_142219_4260 ?

**Comment by amaltaro** [comment]
This information is not stored anywhere but in the internals (object wise) of the workload. Each request has a list of output datasets. Said that, the only way to figure that out is coding against the WMCore libraries (and I'd rather keep it like that unless there is a very good reasoning behind it).

**Comment by vlimant** [comment]
is there a chance to have this as an api ? or have it in the workload cache ?
For several operational things, it is mandatory to be able to do the mapping task/step <=> output.

**Comment by amaltaro** [comment]
Jean-Roch, can you please list and explain what are those use cases? Maybe we can accomplish what you need with existent apis/tools.

**Comment by vlimant** [comment]
in essence I want to know the campaign of the task per output dataset.

**Comment by vlimant** [comment]
I was able to do this going through the spec 

https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_task_HIG-RunIISummer15wmLHEGS-01262__v1_T_170906_162107_4411

and the subscriptions attributes

pdmvserv_task_HIG-RunIISummer15wmLHEGS-01262__v1_T_170906_162107_4411.tasks.HIG-RunIISummer15wmLHEGS-01262_0.subscriptions.RAWSIMoutput.dataset = '/ChargedHiggs_HplusTB_HplusToTauNu_IntermediateMassNoNeutral_M-200_13TeV_amcatnlo_pythia8/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM'

for example.

**Comment by ticoann** [comment]
Alan is working on the StepChain mapping, https://github.com/dmwm/WMCore/pull/8697
We will try to do the same way for TaskChain.
