### ISSUE TITLE
JobSplitting not matching the 8h target

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7988]
Looking at 

https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00237__v1_T_170701_124014_5751
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_TOP-RunIISummer15wmLHEGS-00237__v1_T_170701_124014_5751

the miniaodsim jobs do not seem to be coming out as expected.

{
    "splitAlgo": "EventAwareLumiBased", 
    "splitParams": {
      "trustPUSitelists": true, 
      "algorithm": "EventAwareLumiBased", 
      "max_events_per_lumi": 20000, 
      "deterministicPileup": false, 
      "lheInputFiles": false, 
      "trustSitelists": false, 
      "events_per_job": 28800, 
      "type": "Processing"
    }, 
    "taskName": "/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00237__v1_T_170701_124014_5751/TOP-RunIISummer15wmLHEGS-00237_0/TOP-RunIISummer16DR80Premix-00266_0/TOP-RunIISummer16DR80Premix-00266_1/TOP-RunIISummer16MiniAODv2-00263_0", 
    "taskType": "Processing"
  }, 

is the splitting for the task

"Task4": {
    "KeepOutput": true, 
    "PrepID": "TOP-RunIISummer16MiniAODv2-00263", 
    "InputFromOutputModule": "AODSIMoutput", 
    "GlobalTag": "80X_mcRun2_asymptotic_2016_TrancheIV_v6", 
    "TimePerEvent": 1, 
    "FilterEfficiency": 1, 
    "SplittingAlgo": "EventAwareLumiBased", 
    "ProcessingString": "PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6", 
    "ScramArch": [
      "slc6_amd64_gcc530"
    ], 
    "SizePerEvent": 60, 
    "ConfigCacheID": "86329c92d317a6deffea363c322483d1", 
    "Memory": 5900, 
    "Multicore": 4, 
    "TaskName": "TOP-RunIISummer16MiniAODv2-00263_0", 
    "AcquisitionEra": "RunIISummer16MiniAODv2", 
    "PrimaryDataset": "TGJets_lept_4f_ckm_NLO_13TeV_amcatnlo_madspin_Herwigpp", 
    "Campaign": "RunIISummer16MiniAODv2", 
    "InputTask": "TOP-RunIISummer16DR80Premix-00266_1", 
    "CMSSWVersion": "CMSSW_8_0_21"
  },

which means 28800/60.=480 min of walltime desired.

This could be coming from the fact that jobs are made as soon as there are a couple or one file available in input, and therefore not accumulate enough number of input files to make a long enough job.

**Comment by vlimant** [comment]
@ericvaandering is this worth looking into or we drop the ball on TaskChain and just deprecate it as soon as StepChain can support all usecases (which will not work for taskchain that start from pLHE files ... another long standing never solved topic ... )

**Comment by ericvaandering** [comment]
What is SizePerEvent?

I don't know enough from the links you sent to understand how long the jobs are actually estimated to be.

**Comment by vlimant** [comment]
SizePerEvent is barely used in this context, it's an estimation of the output size per event.

the debug table on gwmsmon for that task says 

WallTime	Memory	Cpus	Running	Idle	Scheduler	Desired Sites	Warnings
25	5900	4	0	10	vocms0308.cern.ch	1	
20	5900	4	0	14	vocms0308.cern.ch	1	
32	5900	4	0	2	vocms0308.cern.ch	1	

20 to 32 min requested walltime, while it should be about 480 if there was enough work added to each job.

**Comment by amaltaro** [comment]
According to oracle database:
```
SELECT wmbs_job.id, wmbs_job_mask.firstlumi, wmbs_job_mask.lastlumi, count(wmbs_job_assoc.fileid) AS num_files, wmbs_job.cache_dir
  FROM wmbs_job INNER JOIN wmbs_job_mask ON wmbs_job.id=wmbs_job_mask.job
  INNER JOIN wmbs_job_assoc ON wmbs_job.id=wmbs_job_assoc.job 
  WHERE cache_dir like '%TOP-RunIISummer16DR80Premix-00266_1/TOP-RunIISummer16MiniAODv2-00263_0/JobCollection%'
  GROUP BY wmbs_job.id, wmbs_job_mask.firstlumi, wmbs_job_mask.lastlumi, wmbs_job.cache_dir
  ORDER BY num_files DESC;
```

just by a glance, it seems the Task4 jobs are getting created with an average of 6 lumis (thus ~1200 evts instead of 28800). There are some jobs that have only 1 lumi section though.

Regarding the number of files associated to each job, we can see that there are jobs "processing" part of a total of 5 or 4 files. The weird thing are those jobs processing only 1 lumi section but still having > 1 file associated (?)

A few lines of the query above can be seen here:
```
id	firstlumi	lastlumi	num_files
537722	11705	11711	5
537722	15856	15862	5
537722	7330	7336	5
537722	11992	11998	5
537722	7288	7294	5
542283	3781	3794	4
580761	9824	9828	4
538184	23728	23728	4
538184	7260	7263	4
538184	27504	27510	4
538184	23507	23513	4
540161	3533	3533	4
540161	4978	4984	4
```

Unless people say otherwise, I'm setting it to high prio for August.

**Comment by amaltaro** [comment]
Wait, I got something wrong from that table... let me update my previous comment.

**Comment by vlimant** [comment]
with regards to #8080 : If the extra mile of making it better ( remove the "+ 10% of another job") is too hard to walk right away, I think we should see how much further on better job splitting does this brings us
