### ISSUE TITLE
Stageout executor handles exit codes wrong

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#7990]
Hi,

I was tracking down some false positives at Vanderbilt (where stageouts were thought to have succeeded but they actually failed) and found a painful WMCore bug. See the following snippet, which is a simplified version of the actual code (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Execute.py#L77)

```python
Python 2.7.13 (default, Dec 17 2016, 23:03:43) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import subprocess
>>> child = subprocess.Popen("exit 127", shell=True)
>>> err = child.wait()
>>> print err
127
>>> os.WIFEXITED(err)
False
>>> os.WIFSIGNALED(err)
False
>>> os.WIFSTOPPED(err)
True
>>> os.WSTOPSIG(err)
0
```

The code actually returns `0` to its caller, instead instead of `127`! This isn't good! In particular, that's the exit code that bash uses if it can't find a script. I'm going to add a separate PR to fix the vandy specific stuff to test for this, but otherwise that code probably needs to be fixed up.

**Comment by ticoann** [comment]
Thanks Andrew for reporting a problem.

**Comment by vlimant** [comment]
@ticoann @amaltaro is there a patch lining up for this issue ?
@PerilousApricot is there any issue with the rolling back to srm https://ggus.eu/index.php?mode=ticket_info&ticket_id=128809#update#17 
I am assuming that other sites could be affected and this might have serious consequence on storage consistency.
Jean-Roch (CRC)

**Comment by ticoann** [comment]
@vlimant, There is no patch yet but I will investigate. I am not quite understand how this code works. Did you observe the same problem for any other sites? It seems that part of code was there since the beginning. I would suspect we would have a lot more cases like this before.

**Comment by PerilousApricot** [comment]
@vlimant Ugh, my laptop is in the shop, so I'm temporarily using another machine that doesn't have my grid cert, so I can't see the GGUS ticket. If it's the "lost files" ticket, then I think moving to gfal fixes it.

To prevent from having to update WMCore each time we want to change our local stageout scripts, we store them in GPFS. What I think happened is that either a) GPFS wasn't properly mounted on a WN or b) some jobs landed in singularity, which doesn't have GPFS bind-mounted. When that happened, WMCore tried to run an unexistent script, and bash uses `127` for that exit code:

```
[root@foreman ~]# /bin/sh -c "nonexistent" ; echo $?
/bin/sh: nonexistent: command not found
127
```

But, WMCore does a weird thing and tries to return the signal number instead of the exit code, and 127 gets parsed/converted into `0`
```python
    elif os.WIFSTOPPED(err):
        return os.WSTOPSIG(err)
```
To your point, @vlimant -- this could happen anytime a stageout plugin returns `127`. I don't see any need for any of the if statements between the `err = wait()` and the `return err`. Spot-checking a couple plugins, it doesn't seem like anyone depends on that behavior.

**Comment by bbockelm** [comment]
The problem commit is this one: https://github.com/dmwm/WMCore/commit/175338d0b0a87111d8fdd2f3aad00d5699797e52

It assumes that the integer returned by `popen2.Popen3.wait` has the same semantics as the integer returned by `subprocess.Popen.wait`.

`popen2` returns the status code from, basically, `os.wait`, which is compatible with the `os.WIF*` functions and does the right thing.

`subprocess` returns a bitshifted status that doesn't seem to have any particular semantics aligned with POSIX and is incompatible with the `os.WIF*` functions.  It causes this code to translate exit status 127 (which is impossible to return from POSIX's `wait`) into 0.  Garbage in, garbage out.

**Comment by ticoann** [comment]
Thank you very much, Brian, I didn't know (I wouldn't have known that). I will create the patch for this.
