### ISSUE TITLE
Can we enable lazy download when LheInputFiles is true

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7997]
It looks like the lhe eos space is exported via xrootd, and therefore we should be able to run pLHE type of workflows at other place than CERN, but having the lazy download should be enabled so as to limit the read.
How does one change that ?

**Comment by bbockelm** [comment]
@vlimant - is this one still relevant at all?  If so, maybe it's something @khurtado could do.

**Comment by vlimant** [comment]
it relevant for the pLHE workflows

**Comment by amaltaro** [comment]
Yes, I suggest we first try running a remote workflow just to check whether LHE files can really be accessed from outside CERN (I see no reason why not though).

If it works fine, we need then to instrument EventBased algo to add a baggage to the job flagging it reads LHE files. 

Reopening and assigning it to @khurtado for April. Kenyi, please ping me when you start working on this and I can give you further directions.

**Comment by amaltaro** [comment]
As discussed in the CompOps meeting, this feature will be important for some requests/campaigns that will hit the production system at any time. 
Given that Kenyi is busy with the condor stuff, and other things, let me take this one.
