### ISSUE TITLE
Disable local WQ monitoring for T0 agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8020]
This code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py#L117-L120

cannot run for Tier0 agents, since they don't install/run WorkQueueManager and they don't use global workqueue.

**Comment by amaltaro** [comment]
I see someone is stealing my issues :-P Seangchan, I can fix it later today or tomorrow, unless you're reallly willing to fix it yourself ?

**Comment by ticoann** [comment]
I am only stealing easy ones. and pay back with harder ones. :-)
