### ISSUE TITLE
Workflow not moving from "assigned"

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#8035]
Something weird is happening, I created this ACDC two days ago
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC1_task_HGC-PhaseIITDRSpring17DR-00023__v1_T_170802_143815_4017

it is sitting in "assigned", but, when I go through WMStats it says the workflow has already run some jobs.
The only WorkQueue element seems to be done
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=vlimant_ACDC1_task_HGC-PhaseIITDRSpring17DR-00023__v1_T_170802_143815_4017

Could you please help us to take a look?

**Comment by ticoann** [comment]
Hi Paola, it seems workqueue (GQ) thread are silently  crashed in cmsweb. I will ask Lina to restart workqueue. If it is urgent, I can manually move the status to completed

**Comment by ticoann** [comment]
Actually there is problem on Job counting, and this seems to be causing the error. I am not sure why job counting is 0.  I manually change the job counting and it moved to completed status now.

"NumberOfLumis": 940,
"Jobs": 0,

I am suspecting it failed initially updating the job counting after dry job splitting ran. but element is created.

**Comment by prozober** [comment]
Thanks for your help! Will your fix prevent this from happening?

**Comment by amaltaro** [comment]
Yes, but only in September, after the cmsweb upgrade.

**Comment by prozober** [comment]
Guys, could you please help me with this one? It is facing the same issue.
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_ACDC2_task_HGC-PhaseIITDRSpring17DR-00023__v1_T_170807_231902_7000
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=mcremone_ACDC2_task_HGC-PhaseIITDRSpring17DR-00023__v1_T_170807_231902_7000

**Comment by amaltaro** [comment]
Paola, I did the same as Seangchan. Switched the number of Jobs from 0 to 1 in that workqueue element and I see it's now in running-* state. A new issue has been created to address it.

**Comment by prozober** [comment]
All ACDCs for the request https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HGC-PhaseIITDRSpring17DR-00023 are being affected.

Could you please help me with this ACDC?
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_ACDC3_task_HGC-PhaseIITDRSpring17DR-00023__v1_T_170810_185950_9155

**Comment by ticoann** [comment]
Hi Paola, I change the Job number for that workflow. It should be propagating state soon.
I check whether there is other case for this, but couldn't find it now. Let me know if you find any. Newly created ACDC might have the same problem.
