### ISSUE TITLE
Cheerypy threads log rotation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8038]
From this HN discussion:
https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1555.html

the way we use and rotate the log files is not ideal. A thread keeps writing to the same file as of
when it was started, and the log rotation happens at midnight (I suppose) by appending the date to the log file, which is then also transferred to vocms022.

I guess we cannot use the logrotate for several of these WMCore services, since most of them spawn several threads, though I don't know exactly how that works :) Ideally our logs should follow the same behaviour as the mongdb service, for instance.

**Comment by ericvaandering** [comment]
@amaltaro in the patch you provided for this on line 80 of WMLogging is a reference to codecs which does not exist anywhere. I'm reopening this for you to fix. :-)

**Comment by ticoann** [comment]
Thanks Eric, my mistake too. I miss that.

**Comment by amaltaro** [comment]
It wasn't me :P Thanks again!
