### ISSUE TITLE
workload summary not created (or lacking info) in > 1.1.6.pre3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8039]
Just started investigating what is happening, but I've seen two cases so far:
* workload summary is created but it's missing tons of information, including the output datasets and stats
* workload summary isn't created at all "Error: unknown workflow name"

**Comment by amaltaro** [comment]
Sigh, I must have done something bad with all the thousands of rebase I had to do on PR 7998.
Problem is that only the unmerged filesets are getting created (and top level).

Unless tag pre2 is fine, then it means another PR screwed that up.

**Comment by amaltaro** [comment]
My tests are still running, but everything seems to be fine when running on private central services and new agent.

There is still a problem though, that stepchain fix is not backwards compatible (there were a few fixes to the spec files), the agent then counts on some of those information in order to properly create the filesets. As we can see, there is a problem running "old" workflows (created on reqmgr 1.1.4 or 1.1.5) on the new agent. We have to discuss on how to proceed in the next upgrade.

I still have to test what happens when we run new requests (new reqmgr) on old agent (1.1.4), I believe it will work without any issues.

**Comment by amaltaro** [comment]
That's it. Master works fine but it doesn't if we use the current production reqmgr (1.1.5.pre5).
I'm closing this issue now. We still have to discuss on how to proceed with these breaking changes during production deployment.

**Comment by ticoann** [comment]
> I still have to test what happens when we run new requests (new reqmgr) on old agent (1.1.4), I believe it will work without any issues.

If that is the case we can  update cmsweb first and and deploy new agents after that.
