### ISSUE TITLE
request doesn't move to completed status

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8044]
I think the problem is following query returns empty list.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Subscriptions/MarkNewFinishedSubscriptions.py

I am not sure what caused this. I will investigate further.

**Comment by amaltaro** [comment]
It appears that:
* workflows are not marked as injected in wmbs_workflow
* filesets are not closed (open=1)
* subscriptions are not finished

I'm pretty sure it all comes from the first bullet. Checking...

**Comment by ticoann** [comment]
Thanks Alan for fixing my mess.

**Comment by amaltaro** [comment]
Glad to help, especially on the easy ones ;)

**Comment by ticoann** [comment]
It wasn't easy for me. :-) I didn't check the JobArchiverLog. I wonder whether we should crash the component for mistake like this.
