### ISSUE TITLE
Jobs on T3_US_OSG 

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8062]
@ticoann @amaltaro 

Looking at the errors from 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_PPD-PhaseIITDRSpring17GS-00004__v1_T_170814_041459_4250

several jobs are reported in error from T3_US_OSG

Job Name: 00357d66-810e-11e7-b4db-02163e0184a6-4
WMBS job id: 2091063
Workflow: pdmvserv_task_PPD-PhaseIITDRSpring17GS-00004__v1_T_170814_041459_4250
Task: /pdmvserv_task_PPD-PhaseIITDRSpring17GS-00004__v1_T_170814_041459_4250/PPD-PhaseIITDRSpring17GS-00004_0/PPD-PhaseIITDRSpring17GS-00004_0MergeRAWSIMoutput/PPD-PhaseIITDRSpring17DR-00006_0/PPD-PhaseIITDRSpring17DR-00006_1
Status: jobfailed
Input dataset:
Site: T3_US_OSG
Agent: vocms0126.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition

    jobcooloff: 2017/8/15 (Tue) 21:57:12 UTC, T3_US_OSG
    jobcooloff: 2017/8/16 (Wed) 01:00:16 UTC, T3_US_OSG
    jobcooloff: 2017/8/16 (Wed) 07:03:19 UTC, T3_US_OSG
    jobfailed: 2017/8/16 (Wed) 14:00:31 UTC, T2_US_Wisconsin

Exit code: 8002
Retry count: 3

I tripled checked the overflow mechanism and all logs (since aug 3) for that workflow and OSG was not added.
Is there something in the agent (vocms0126.cern.ch was handling that wf) that would let jobs be submitted to OSG 

fyi @thongonary @mcremone

**Comment by amaltaro** [comment]
Then I suggest you checking once again :)

There is no way the agent could have submitted jobs to T3_US_OSG, reasons are:
* this resource does not exist in vocms0126 database
```
SQL> select * from wmbs_location where site_name like '%OSG%';
no rows selected
```
* and you reported a non top level task, which means it's data driven and OSG does not have a PNN.

Closing this issue. Let us know (reopen) if you still think there is something wrong in the agent.

**Comment by vlimant** [comment]
I should have mentioned that looking at https://cms-gwmsmon.cern.ch/prodview/T3_US_OSG there were no jobs running on T3_US_OSG for the time window in question. I triple checked the logs and I have every single version of the overflow mapping there is, and OSG is no-where as a destination.
Perhaps T3_US_OSG is reported as the site with a failure while it is not actually the site the job failed at ?

There are numerous on-going such errors and there is no over-flow, nor jobs running on OSG : so what is happening in wmstats report ?

**Comment by amaltaro** [comment]
Apparently those jobs were redirected by Wisconsin CE to a cluster that had a wrong setup/siteconf, according to Ajit. Rokas is discussing it within the site support team and @prozober is in the loop.

Please close the issue once that's crystal clear.

**Comment by vlimant** [comment]
alright, is this visible in the condor logs or what ?

**Comment by amaltaro** [comment]
You can see which SITECONF the job loaded, but I don't think we print its content.
If you want to dig it deeper, please get in touch with the site support team and/or Ajit.
Closing this issue.
