### ISSUE TITLE
adjust the number of pending jobs to number of agents in the a team

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8087]
I think I saw a mechanism to adjust the number of pending jobs to the number of active agents. How does that work ?

**Comment by ticoann** [comment]
We check the active agent (none draining agent)
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L116

Then  divided pending slots by num of agent. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L251

There is also configurable pendingSlotsTaskPercent which can control the threshold manually (90% is set)

https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py

Is there a problem? Is pending job is set to high? In that case it can be controlled by pendingSlotsTaskPercent

We can put that parameter in aux db  - which you can change through REST API.

**Comment by vlimant** [comment]
what I have been thinking is that the number of pending core/jobs should be a global parameter that all agents "share" equally. It looks like when an agent is added to the production team, there is a significant jump in number of pending instead of remaining ~constant. what is the value of agentsCount, in which range of number of agents in production would the number of pending be constant when adding a new agent ?

**Comment by ticoann** [comment]
Current scheme is basically that. We have a constant number of pending which divided by number of agent.  There is a case if we have a lot of drained agent and they are put back one by one. That could increase the total pending job drastically. However we have default number for agent (5 at the moment). We are assuming at least 5 agents will be running together. We can adjust that value if the simultaneous running agents are surely more/less than that.

**Comment by amaltaro** [comment]
Without mentioning that an agent does not condor_rm jobs if the pending thresholds is lowered.

**Comment by vlimant** [comment]
ok, so, only with >5 agents in production does the number of pending stays ~constant when adding a new agent. I think that "5" should be lower to 3, if not 2 or 1, so that we really rely on the number of active agents, and hence have a more stable value of pending. It's OK to not have condor_rm.

what's the prospect of turning all these in "number of cores" instead of "number of jobs" ?

**Comment by amaltaro** [comment]
Soo, it should be using 5 only as a default value in case it fails to get that info from couch
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L128

however, there seems to be a bug in L139 and it's always considering 5 agents on the same team (just confirmed by comparing the relval and production thresholds.

> what's the prospect of turning all these in "number of cores" instead of "number of jobs" ?

not sure we'll ever have it, especially with resizable slots and job_router in place.
