### ISSUE TITLE
Remove the need for setting MaxRSS at assignment time

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8091]
There is too much confusion and complications in having both "Memory" and "MaxRSS" in the schema. I cannot think of a reason we should not have only one of the two, and the other one handled purely internally

**Comment by hufnagel** [comment]
If this is maxRSS for the runtime kill code, all Tier0 workflows use this rule

maxRSS = 1024 * specArguments['Memory'] + 10

works well for us there.

**Comment by vlimant** [comment]
exactly. there is no need for having to specify this explicitely, it should be all take care off internally, especially in the case of Task and Step chains, ACDC of such (which T0 does not have to deal with)
