### ISSUE TITLE
agent need to acquire in their team

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8095]
related to #8074 I do not understand the reason for having team="" go to *any* team. This is highly un-desirable IMO and WQE should just get in nowhere land. Better the request should not be able to assign if Team="" is the one that is decided.

I don't know why this is happening more frequently now, but this is happening and impacting urgent requests

**Comment by ticoann** [comment]
We have to get rid of Teams and just keep Team if workflow is only assigned in one team. If not we have to keep Teams not Team. Anyway, for now I added the temporary fix which we can deploy next cmsweb. #8098

**Comment by DAMason** [comment]
Appears we had another workflow get sucked down by the hepcloud agent like this:
vlimant_task_HIG-PhaseIITDRSpring17DR-00034__v1_T_170826_004446_7421

At the moment looks like the majority of it got pulled into production agents, but a good fraction is lost in the active hepcloud agent.

**Comment by vlimant** [comment]
@amaltaro @ticoann

**Comment by ticoann** [comment]
temp fix is created #8106 and updated to hepcloud and relval agent (cmssrv237, vocms053)
So those agent shouldn't pull down empty team. The real fix should be removing the teams and make sure team is not empty. (That will be updated next deployment)

**Comment by vlimant** [comment]
thanks. can we please also patch the relval agent so that it does not pick up production work ?

**Comment by ticoann** [comment]
I did both hepcloud and relval. :smile:

**Comment by vlimant** [comment]
great. need to read more :-(

**Comment by DAMason** [comment]
So have been waiting for cmssrv237 to make jobs out of wmagent_dmason_NERSCTEST_170829_201133_755 for about an hour and a half -- see it pulled down the work, but nothing beyond that for the last hour and a half or so.  Impatient, or patch broke something?

**Comment by ticoann** [comment]
Sorry patch broke something. New patch is updated (relval agent as well). Let me know if you still have problem.

**Comment by DAMason** [comment]
I see jobs now -- so far so good!  Will pay attention to next workflow we throw in (likely tomorrow)
