### ISSUE TITLE
JobAccountant vocms0126.cern.ch

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#8112]
I assume it needs the patch on it now.

Here is the error log:

2017-08-30 23:21:09,364:139664035522304:INFO:Harness:>>>Terminating worker threads
2017-08-30 23:21:09,375:139664035522304:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.JobAccountant.JobAccountantPoller.JobAccountantPoller instance at 0x7f0619526e18> <@========== WMException Start ==========@>
Exception Class: AccountantWorkerException
Message: Error while adding files to WMBS!
(IntegrityError) ORA-00001: unique constraint (CMS_WMBS_PROD11.WMBS_FILDETAILS_UNIQUE) violated
 'INSERT INTO wmbs_file_details (id, lfn, filesize, events,\n                                            first_event, merged)\n             VALUES (wmbs_file_details_SEQ.nextval, :lfn, :filesize, :events,\n                     :first_event, :merged)' [{'first_event': 51830923, 'lfn': '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/947B8340-608D-E711-B42A-0CC47A6C1038.root', 'filesize': 2309339425, 'merged': 0, 'events': 2049}, {'first_event': 51830923, 'lfn': '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-443-0-logArchive.tar.gz', 'filesize': 0, 'merged': 0, 'events': 0}, {'first_event': 55082587, 'lfn': '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/50B10B18-648D-E711-9AE0-001E67DFFB86.root', 'filesize': 2308154982, 'merged': 0, 'events': 2051}, {'first_event': 55082587, 'lfn': '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-659-0-logArchive.tar.gz', 'filesize': 0, 'merged': 0, 'events': 0}, {'first_event': 55127749, 'lfn': '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/08B9202A-648D-E711-9077-C4346BC78D10.root', 'filesize': 2231042421, 'merged': 0, 'events': 1969}, {'first_event': 55127749, 'lfn': '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-662-0-logArchive.tar.gz', 'filesize': 0, 'merged': 0, 'events': 0}, {'first_event': 55443883, 'lfn': '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/3A5F1D4F-6A8D-E711-A57E-008CFAF35826.root', 'filesize': 2292134513, 'merged': 0, 'events': 2041}, {'first_event': 55443883, 'lfn': '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-683-0-logArchive.tar.gz', 'filesize': 0, 'merged': 0, 'events': 0}  ... displaying 10 of 197 total bound parameter sets ...  {'first_event': 52658893, 'lfn': '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/B6561BD9-648D-E711-8DC6-C4346BBCB6A8.root', 'filesize': 2358679228, 'merged': 0, 'events': 2095}, {'first_event': 52658893, 'lfn': '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-498-0-logArchive.tar.gz', 'filesize': 0, 'merged': 0, 'events': 0}]
	ModuleName : WMComponent.JobAccountant.AccountantWorker
	MethodName : handleWMBSFiles
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py
	ClassName : None
	LineNumber : 863
	ErrorNr : 0

Traceback:
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 835, in handleWMBSFiles
    transaction = self.existingTransaction())

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/WMBS/MySQL/Files/Add.py", line 40, in execute
    conn = conn, transaction = transaction)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 924, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp4/lib/python2.7/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 916, in do_executemany
    cursor.executemany(statement, parameters)

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 205, in __call__
    raise ex

2017-08-30 23:21:09,375:139664035522304:INFO:BaseWorkerThread:Worker thread <WMComponent.JobAccountant.JobAccountantPoller.JobAccountantPoller instance at 0x7f0619526e18> terminated

**Comment by ticoann** [comment]
I am not completely sure whether this is issue is that duplicate uuid which happens once in a year. 
I restarted the JobAccountant, I will check whether it crashes again.

**Comment by amaltaro** [comment]
Hi Scarlet, Seangchan is correct, two jobs from the same workflow and task have created the same file. I've removed one (meaning it will be marked as failed) of them and restarted the component.
This problem happens a couple of times per year, since the unique UID algorithm don't guarantee 100% uniqueness :)

Just in case, log of the script I ran and the output:
```
cmst1@vocms0126:/data/srv/wmagent/current $ python removeDupJobAccountant.py 
Found 437 pickle files to open
with a total of 202 output files
Retrieved 2669956 lfns from wmbs_file_details

Found 2 duplicate files: ['/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/0003/0/91c23fe2-8d0e-11e7-b4db-02163e0184a6-864-0-logArchive.tar.gz', '/store/unmerged/logs/prod/2017/8/30/pdmvserv_task_BTV-RunIISummer17GS-00018__v1_T_170829_204108_6698/BTV-RunIISummer17GS-00018_0/0004/0/74d38710-8d0e-11e7-b4db-02163e0184a6-687-0-logArchive.tar.gz']
The bad pkl files are:
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/JobCollection_553949_0/job_3030619/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00018__v1_T_170829_204108_6698/BTV-RunIISummer17GS-00018_0/JobCollection_553947_0/job_3029439/Report.0.pkl
Remove them, restart the component and be happy!
cmst1@vocms0126:/data/srv/wmagent/current $ ls
alandir  apps  apps.sw  auth  bin  config  install  removeDupJobAccountant.py  sw
cmst1@vocms0126:/data/srv/wmagent/current $ mv /data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00018__v1_T_170829_204108_6698/BTV-RunIISummer17GS-00018_0/JobCollection_553947_0/job_3029439/Report.0.pkl alandir/
```

**Comment by amaltaro** [comment]
The component crashed again with more duplicates, suspicious... I'm removing these files too

```
Found 3 duplicate files: ['/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/0010/0/8db9233e-8dae-11e7-b4db-02163e0184a6-989-0-logArchive.tar.gz', '/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/0009/0/8db9233e-8dae-11e7-b4db-02163e0184a6-233-0-logArchive.tar.gz', '/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/BTV-RunIISummer17wmLHEGS-00009_0MergeRAWSIMoutput/BTV-RunIISummer17DRPremix-00035_0/0000/0/8deef944-8d47-11e7-b4db-02163e0184a6-14-0-logArchive.tar.gz']
The bad pkl files are:
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/JobCollection_559748_0/job_3060569/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/JobCollection_559748_0/job_3059813/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/BTV-RunIISummer17wmLHEGS-00009_0MergeRAWSIMoutput/BTV-RunIISummer17DRPremix-00035_0/JobCollection_555686_0/job_3043136/Report.0.pkl
Remove them, restart the component and be happy!
```

**Comment by amaltaro** [comment]
And it happened once again. I noticed it's always logArchive files.. maybe we should remove (or rename) it on the FJR instead of fail the job. LogArchive job would skip it instead of failing then.

```
Found 2 duplicate files: ['/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/0011/0/dbdc57b6-8de0-11e7-b4db-02163e0184a6-95-0-logArchive.tar.gz', '/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/0007/0/edba341e-8d8e-11e7-b4db-02163e0184a6-901-0-logArchive.tar.gz']
The bad pkl files are:
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/JobCollection_558208_0/job_3067401/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17wmLHEGS-00009__v1_T_170829_204515_7939/BTV-RunIISummer17wmLHEGS-00009_0/JobCollection_558431_0/job_3054337/Report.0.pkl
Remove them, restart the component and be happy!
```

We can also look into a better way to define these names, I _just_ need to learn where that happens :)

**Comment by amaltaro** [comment]
And there were more cases later today. I did some improvements to that script such that we can have a better idea of the status of those jobs (most of them had failed). 

4 jobs were failed again, log below
```
Found 4 duplicate files:
['/store/unmerged/logs/prod/2017/8/31/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeLHEoutput/0000/1/e0164c06-8dc2-11e7-b4db-02163e0184a6-4-1-logArchive.tar.gz',
 '/store/unmerged/RunIISummer17GS/QCD_Pt-600to800_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/GEN-SIM/92X_upgrade2017_realistic_v10-v1/110003/5E272D8F-6A8D-E711-AF7A-0025904B9B3E.root',
 '/store/unmerged/logs/prod/2017/8/31/pdmvserv_task_BTV-RunIISummer17GS-00031__v1_T_170829_204405_3076/BTV-RunIISummer17GS-00031_0/0000/0/c6a58104-8d3d-11e7-b4db-02163e0184a6-525-0-logArchive.tar.gz',
 '/store/unmerged/logs/prod/2017/8/31/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeRAWSIMoutput/0000/1/e5dc5e00-8dc2-11e7-b4db-02163e0184a6-1-1-logArchive.tar.gz']
Corresponding to 4 bad pkl files, they are:
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/JobCollection_553949_0/job_3030665/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00031__v1_T_170829_204405_3076/BTV-RunIISummer17GS-00031_0/JobCollection_555536_0/job_3042420/Report.0.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeLHEoutput/JobCollection_559645_0/job_3062390/Report.1.pkl
/data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeRAWSIMoutput/JobCollection_559647_0/job_3062395/Report.1.pkl

Parsing /data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00026__v1_T_170829_204253_3975/BTV-RunIISummer17GS-00026_0/JobCollection_553949_0/job_3030665/Report.0.pkl ...
  Successful job: True
  Job exit codes are: set([])
Parsing /data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/pdmvserv_task_BTV-RunIISummer17GS-00031__v1_T_170829_204405_3076/BTV-RunIISummer17GS-00031_0/JobCollection_555536_0/job_3042420/Report.0.pkl ...
  Successful job: False
  Job exit codes are: set([139, 50115, 99999])
Parsing /data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeLHEoutput/JobCollection_559645_0/job_3062390/Report.1.pkl ...
  Successful job: False
  Job exit codes are: set([60450, 99999])
Parsing /data/srv/wmagent/v1.1.4.patch2/install/wmagent/JobCreator/JobCache/vlimant_task_HIG-RunIISummer15wmLHEGS-01679__v1_T_170829_172935_2614/HIG-RunIISummer15wmLHEGS-01679_0/HIG-RunIISummer15wmLHEGS-01679_0MergeRAWSIMoutput/JobCollection_559647_0/job_3062395/Report.1.pkl ...
  Successful job: False
  Job exit codes are: set([60450, 99999])
```

**Comment by amaltaro** [comment]
Proper issue created in #8333
