### ISSUE TITLE
Silent failures of harvesting jobs

### ISSUE THREAD

**Issue by fabozzi** [dmwm/WMCore#8118]
Dear all,
sometimes we experience failures of harvesting  without any error message.
We discover these failures afterwards when validators look at DQM GUI and do not find the sample, or they do find the sample but DQM plots fewer entries than expected.

This happened in the past for this wf, where we saw small statistics in DQM plots:
fabozzi_RVCMSSW_9_0_0RunSingleEl2016E__cc7_RelVal_sigEl2016E_170421_144836_8005
Resubmitting the workflow fixed indeed the issue.

Recently we have seen that for the following workflow no file was uploaded in DQM GUI:
zhenhu_RVCMSSW_9_2_8VBFHToBB_M125_Pow_py8_Evt_13UP17__HS_170809_220847_85

[There are a few additional workflows which are still under investigation, so I will update here if we can confirm their issue is related to harvesting].

**Comment by amaltaro** [comment]
Hi Francesco,

> This happened in the past for this wf, where we saw small statistics in DQM plots:
fabozzi_RVCMSSW_9_0_0RunSingleEl2016E__cc7_RelVal_sigEl2016E_170421_144836_8005
Resubmitting the workflow fixed indeed the issue.

harvesting is supposed to run at a single place which is also supposed to contain the whole dataset. Apparently this example you provided us created 2 DQMIO blocks, one with origin_site_name as Nebraska and the other with Purdue (maybe fallback stage out kicked in). The workflow is archived, but it likely created two harvesting job, where the second root file overwrites the former when it hits the DQM Gui (just confirmed but looking up the root file version).

For the second case, where no root file is in the server. AFAIK, the DQMGui server can accept the http post call (to upload the file) and later on the dataset could fail some internal validation/regex before being finally persisted.

Can you provide more examples, please? Especially useful it the workflow is not archived yet.

**Comment by fabozzi** [comment]
Hi Alan,
thank you for your feedbacks. I am happy that there is an understanding of the 2 cases I cited.

Unfortunately I do not have other past examples to my memory. And for the otehr recent workflows that we were still investigating, we finally understood that there was no harvesting issue.
So the good thing is that these failures appears still limited.

For the future, we will continue to notify as soon as we see another verified harvesting issue.

@GurpreetSinghChahal, @prebello

**Comment by amaltaro** [comment]
Thanks, Francesco. Let's keep this issue open for a couple of months then. Please update us whenever you see these issues (the sooner the better, to avoid getting those wfs archived).

**Comment by fabozzi** [comment]
Hi @amaltaro , 
a few relval workflows injected recently seem to be affected by harvesting failures:
zhenhu_RVCMSSW_9_4_0_pre1WM_13_170918_185347_6807
zhenhu_RVCMSSW_9_4_0_pre1TTbarLepton_13_170918_183831_6405
zhenhu_RVCMSSW_9_4_0_pre1ZpTT_1500_13_170918_191608_7019

Actually no issue was reported in the announcement hypernews and we realized this problem only when we saw no ROOT file available in DQM GUI. 

By inspecting the logs, we do see error messages:

https://vocms049.cern.ch/unified/report/zhenhu_RVCMSSW_9_4_0_pre1WM_13_170918_185347_6807

https://vocms049.cern.ch/unified/report/zhenhu_RVCMSSW_9_4_0_pre1TTbarLepton_13_170918_183831_6405

https://vocms049.cern.ch/unified/report/zhenhu_RVCMSSW_9_4_0_pre1ZpTT_1500_13_170918_191608_7019

We have also reported the issue on the hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/relval/8561/1.html

Can you have a look?

**Comment by amaltaro** [comment]
Francesco, given the harvesting job is properly reported in WMStats (and Unified), can you please follow this up with the P&R team on why the failure was not reported in the announcement? 

This GH issue is meant to report/address WMCore/WMAgent silent issues with harvesting, which is not the case reported. 
Let us know if you see harvesting failures unreported in *wmstats* and we'll take it from there. WMAgent only talks to WMStats (and dashboard), all the other monitoring tools are secondary and not directly used by WMAgent.

**Comment by amaltaro** [comment]
@fabozzi Francesco, from my last comment, it wasn't really a WMCore/WMAgent issue. Given no issues were found in the last ~6 months, I wonder whether we could close this issue?

**Comment by fabozzi** [comment]
Hi, I agree with you. I can close the issue

**Comment by amaltaro** [comment]
Thanks!
