### ISSUE TITLE
Create the Api to get information to determine the condition for dataset transfer.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8133]
@vlimant, @amaltaro, Jean-Roch which condition is required (per request)

1. Number of jobs
2. Duration of jobs
3. CPU requirement
4. SiteWhite list

**Comment by vlimant** [comment]
?

**Comment by amaltaro** [comment]
As the subject says, we'd like to know what are the conditions and logic for transferring input dataset (blocks), pileup dataset and parent dataset if needed. Which properties are considered and what's the algorithm for chunking data and selecting the PNNs to host data.

**Comment by vlimant** [comment]
is this https://github.com/dmwm/WMCore/issues/8324  ?

**Comment by amaltaro** [comment]
Not really. That issue simply says that block replication is driven by the SiteWhitelist used during workflow assignment.

The next step is to transfer data, how then?

**Comment by vlimant** [comment]
I am confused about this, and how much repetition we have to go through on this

**Comment by amaltaro** [comment]
You're right. Logic is already in place somehow - likely a copy/pasting from the Unified repo though -
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py
