### ISSUE TITLE
Input data rule removal on a block-basis

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8134]
[editing the first comment in this issue]

As mentioned in the transition to Rucio doc:
"""
Initial input data to a workflow will be held on disk by Unified with block-by-block rules before the workflow is assigned. There will be a handover to the WMAgent, which can then remove the relevant rules block by block when it is finished processing it. We do not want to have to keep whole datasets pinned to disk for the duration of workflows.
"""

so we need to check the T0 mechanism/logic which deletes input block (Rucio datasets) and adapt/adopt it for central production activities as well.

Related to: https://its.cern.ch/jira/browse/CMSRUCIO-97
and 
https://its.cern.ch/jira/browse/CMSRUCIO-37

**Comment by amaltaro** [comment]
Wondering if it's still relevant with the transition to Rucio...(?) @ericvaandering @vlimant @bbockelm

**Comment by vlimant** [comment]
good question indeed.  I am ignorant of how this is going to be handled in Rucio

related to #8384 #8332 #7651

**Comment by ericvaandering** [comment]
I tried to describe some of that in https://indico.cern.ch/event/741043/sessions/280860/attachments/1684511/2712623/Transition_plan.pdf 

Can you read there and see what needs to be clarified (for sure this is 6 months old at this point).

What I have in mind using our current tools and terminology is that Unified will make a "rule" to keep some input data in place and will make one rule per workflow or WQ element (which as long as the requirements are the same will not create extra copies of data). The the agent or ReqMgr will know when that workflow (or WQ element) is complete and can remove the rule. When all the rules for a chunk of data are removed, only then will Rucio try to delete the data.

**Comment by amaltaro** [comment]
I have created a specific issue for the block deletion logic used by the T0 WMAgent:
https://github.com/dmwm/WMCore/issues/9623

while this issue can be used to discuss data usage and cleanup in the overall WM system.
We might as well start with a fresh issue, given that this one is now almost 3 years old...

**Comment by amaltaro** [comment]
Given that this issue dates back to 2017, I decided to replace it by a fresh new issue:
https://github.com/dmwm/WMCore/issues/11409

to evaluate a better input data placement mechanism. I am closing this one out. Thanks everyone!
