### ISSUE TITLE
failing assignment

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8160]
we are getting 

400 Bad Request

Invalid spec parameter value: 'ConfigSection' object has no attribute 'outputSubs'

http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=ReReco-Run2016D-DoubleMuonLowMass-07Aug17-0006
while assigning https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170831_195141_4272

any clue what can be going on ?

**Comment by amaltaro** [comment]
This change should have been transparent :( Can you please clone and assign this request?
It _should_ work, otherwise we'll need to make a hot fix in cmsweb.

**Comment by amaltaro** [comment]
It seems we have between 10 and 15 workflows waiting to be assigned, besides some very old workflows that can be probably rejected:
https://its.cern.ch/jira/browse/CMSCOMPPR-1288

Do you want me to reject/clone all those requests?

**Comment by vlimant** [comment]
FYI @prozober @areinsvo

**Comment by areinsvo** [comment]
Here's one workflow if you want to test that cloning fixes the problem:
 fabozzi_Run2016G-v1-MuOnia-07Aug17_8029_170831_185944_1726

I'll go through Unified and make a list of the rest facing this issue.

**Comment by amaltaro** [comment]
Thanks, Allie. There you go:
amaltaro_Run2016G-v1-MuOnia-07Aug17_8029_170914_161656_5235

**Comment by areinsvo** [comment]
Full list of affected workflows according to Unified (plus the one you just cloned):
pdmvserv_task_BTV-RunIISummer17DRPremix-00039__v1_T_170908_134925_3732
pdmvserv_task_BTV-RunIISummer17GS-00049__v1_T_170913_095113_7524
pdmvserv_task_BTV-RunIISummer17DRPremix-00043__v1_T_170908_134909_9797
fabozzi_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170831_195141_4272
pdmvserv_task_BTV-RunIISummer17DRPremix-00045__v1_T_170908_135540_7719

**Comment by amaltaro** [comment]
@areinsvo the workflow I cloned is still sitting in assignment-approved. Let me know when I should clone the others. Or just go ahead if you will.

**Comment by areinsvo** [comment]
@amaltaro the workflow is now running, so your fix seems to have worked (unless @vlimant you took any manual action on amaltaro_Run2016G-v1-MuOnia-07Aug17_8029_170914_161656_5235?) 

I think you can go ahead and clone the other 5. Thanks!

**Comment by amaltaro** [comment]
@areinsvo there you go:
amaltaro_task_BTV-RunIISummer17DRPremix-00039__v1_T_170915_163213_593
amaltaro_task_BTV-RunIISummer17GS-00049__v1_T_170915_163223_7938
amaltaro_task_BTV-RunIISummer17DRPremix-00043__v1_T_170915_163241_4077
amaltaro_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170915_163250_8451
amaltaro_task_BTV-RunIISummer17DRPremix-00045__v1_T_170915_163255_3714

Thank you very much.

**Comment by amaltaro** [comment]
And I have just rejected the original ones. I think this "solves" this incompatibility problem.
If there are no others in the same situation, please close this issue.

**Comment by areinsvo** [comment]
It looks like there are two others that just showed up with the same issue:
prebello_Run2016B-v2-SingleElectron-07Aug17_ver2_8029_170818_042306_8526 *
pdmvserv_task_BTV-RunIISummer17DRPremix-00046__v1_T_170908_135549_5687
@amaltaro can you please clone these as well?
* This is also being followed in the JIRA ticket https://its.cern.ch/jira/browse/CMSCOMPPR-1241

**Comment by amaltaro** [comment]
The new workflows are:
amaltaro_Run2016B-v2-SingleElectron-07Aug17_ver2_8029_170917_073230_9580
amaltaro_task_BTV-RunIISummer17DRPremix-00046__v1_T_170917_073245_8251

I'm rejecting the original ones.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=amaltaro_task_BTV-RunIISummer17DRPremix-00046__v1_T_170917_073245_8251 was left "new"

**Comment by areinsvo** [comment]
Some of the clones aren't showing up for me either in Unified or on Dima's pages. 
For instance, fabozzi_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170831_195141_4272
 should have been  replaced with amaltaro_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170915_163250_8451
But I don't see the clone either place:
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016D-DoubleMuonLowMass-07Aug17-0006 or http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=ReReco-Run2016D-DoubleMuonLowMass-07Aug17-0006

Did we miss something?

Assignment-approved:
amaltaro_Run2016B-v2-SingleElectron-07Aug17_ver2_8029_170917_073230_9580
amaltaro_task_BTV-RunIISummer17DRPremix-00046__v1_T_170917_073245_8251

Running:
amaltaro_Run2016G-v1-MuOnia-07Aug17_8029_170914_161656_5235

In trouble (Unified hasn't found the clone):
fabozzi_Run2016D-v2-DoubleMuonLowMass-07Aug17_8029_170831_195141_4272
pdmvserv_task_BTV-RunIISummer17DRPremix-00039__v1_T_170908_134925_3732
pdmvserv_task_BTV-RunIISummer17DRPremix-00045__v1_T_170908_135540_7719
pdmvserv_task_BTV-RunIISummer17DRPremix-00043__v1_T_170908_134909_9797
pdmvserv_task_BTV-RunIISummer17GS-00049__v1_T_170913_095113_7524

**Comment by amaltaro** [comment]
Sorry, my clone script simply clones a workflow. I forgot swapping those to "assignment-approved".
Just did so and they should be seen by Unified now

**Comment by vlimant** [comment]
the issue with pdmvserv_task_BTV-RunIISummer17GS-00049__v1_T_170913_095113_7524 was actually elsewhere ; it creates duplicates outputs :-(

**Comment by areinsvo** [comment]
There is one more today with the same error message.
fabozzi_Run2016B-v2-DoubleEG-07Aug17_ver2_8029_170831_201509_3552

**Comment by amaltaro** [comment]
Allie, here is a clone:
amaltaro_Run2016B-v2-DoubleEG-07Aug17_ver2_8029_170920_092605_5698

I'm rejecting the original one (*_3552)

**Comment by areinsvo** [comment]
One more: pdmvserv_task_BTV-RunIISummer17DRPremix-00041__v1_T_170908_134941_8561

@amaltaro is there a way to check which workflows will have this issue while they are still in staging, instead of waiting for them to try and fail to be assigned?

Also, I switched amaltaro_Run2016B-v2-DoubleEG-07Aug17_ver2_8029_170920_092605_5698 to "assignment-approved" via request manager.

**Comment by amaltaro** [comment]
Here is a clone
amaltaro_task_BTV-RunIISummer17DRPremix-00041__v1_T_170920_161243_3072

already in assignment-approved, I keep forgetting it. Old workflow was rejected.

Yes, there is, one can look for any workflows in assignment-approved dating before Sept 12, around noon time at CERN. which gives me the following requests:
fabozzi_HARVEST-RelValVBFHToBB_M125-28Aug2017_928_170901_105532_1029
pdmvserv_EXO-RunIISpring16MiniAODv2-05080_00564_v0__161015_161420_2415
prozober_EXO-RunIISummer15GS-07899_00471_v0__161213_144423_8577
prozober_EXO-RunIISummer15wmLHEGS-01952_00249_v0__161213_144704_656

which one should I clone?

**Comment by amaltaro** [comment]
I assume we're fine now. @areinsvo please reopen this issue if there is anything else left to do. Sorry for the extra work once again.
