### ISSUE TITLE
OriginalMaxWallTimeMins and EstimatedSingleCoreMins should be quantized

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8174]
Is there any major drawback in having these parameters quantized (say 30 min) ?

**Comment by amaltaro** [comment]
The question is, is there any drawback in keeping the correctly calculated value? Is auto-cluster creation depending on any of these condor ads?

**Comment by vlimant** [comment]
I think that

ad['MaxWallTimeMins'] = classad.ExprTree('WMCore_ResizeJob ? (EstimatedSingleCoreMins/RequestCpus + 15) : OriginalMaxWallTimeMins')

is making MaxWallTimeMins too granular ?

**Comment by juztas** [comment]
See here: https://github.com/dmwm/WMCore/issues/7631

**Comment by vlimant** [comment]
that closes the loop indeed

**Comment by vlimant** [comment]
how do we go about and start quantizing those values so that we stop shooting the global pool with hundreds of time and disk requirements

**Comment by ticoann** [comment]
How do we quantize?  Just added to expression?

Something like below?
```
ad['MaxWallTimeMins'] = classad.ExprTree('quantize(WMCore_ResizeJob ? (EstimatedSingleCoreMins/RequestCpus + 15) : OriginalMaxWallTimeMins', 180))
```

**Comment by bbockelm** [comment]
Hi,

You need to apply the rounding to `EstimatedSingleCoreMins` (or other attributes) prior to submission.

HTCondor has its own internal rounding mechanisms, but they've worked very poorly for CMS -- they have fairly funky rules that cause fairly gross under-estimates or over-estimates.

Brian

**Comment by amaltaro** [comment]
You're too late Seangchan LoL

**Comment by ticoann** [comment]
You shouldn't work that late. :-)
