### ISSUE TITLE
adding error code 8001 to the failing list

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8188]
these are standard framework exceptions that should not be retried.
there is an on-going abuse of the retry for the wmlhe requests, and we should circumvent it.
can this maybe be made agent-configurable somehow ?

**Comment by ticoann** [comment]
It is configurable. For current production agent (1.1.4), we can manually change the config and restart ErrorHandler.

https://github.com/dmwm/WMCore/blob/1.1.4_wmagent/etc/WMAgentConfig.py#L245

New agent (we will deploy next week) will work a little differently, we kept the config in aux db and we can just change the entry there (NoRetryExitCodes), and Agent will pick up without restarting the component. (See below for the samples)


https://cmsweb-testbed.cern.ch/couchdb/_utils/document.html?reqmgr_auxiliary/WMAGENT_CONFIG_cmsgwms-submit3.fnal.gov

I will add the 8001 exit code in default config as well.
