### ISSUE TITLE
Add TotalInitTime from FWJR

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#8192]
@Dr15Jones tells me that TotalInitTime is set in more recent cmsRun executions in the same place as TotalJobTime which tracks the time during the initialization phase. Also need to get this into WMArchive

**Comment by ericvaandering** [comment]
Also TotalInitCPU

**Comment by ericvaandering** [comment]
Crap. As found by @vkuznet we also don't have ‘NumberOfThreads’ and ‘NumberOfStreams’ in the same section copied into our FWJR. We're about a year behind.

**Comment by vkuznet** [comment]
Eric, probably it would be worth to add schema validation to WMCore/WMAgent release. Without properly checking docs of what it reads and writes out we'll be in a dark for long time. It can be done by using existing schema (https://github.com/dmwm/WMArchive/blob/master/src/python/WMArchive/Schemas/FWJRProduction.py) and checking that WMCore/WMAgent components satisfies it (i.e. write docs with all appropriate key-values).

**Comment by ticoann** [comment]
@Dr15Jones, TotalInitTime, TotalInitCPU, are both CPU performance, correct?
@ericvaandering, Eric it seem we automatically gets those if they are CPU performance,

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L354

Of course we still need to update schema for WMArchive update.

Eric, For NumberOfThread (Stream), we need to get 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L718
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L719

not
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMStep.py#L46
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMStep.py#L57

correct?

Or does cms fwjr contains that information?

**Comment by vkuznet** [comment]
Seangchan, I would suggest that you correct WMArchive schema first since it
needs to be propagated to HDFS to handle new docs. Then you can collect metrics
from various places and create new WMAgent release with them. Since it takes
time we'll be able to propagate WMArchive schema and it will be in place once
new WMAgent release will be ready.
Best,
Valentin.

**Comment by ericvaandering** [comment]
@ticoann the thread and stream values should be in the XML FWJR in the same place as all the other CPU stuff, so in that case they should be in the agent job report already.

**Comment by Dr15Jones** [comment]
> Eric, For NumberOfThread (Stream), we need to get ...
Or does cms fwjr contains that information?

That information is available in the CMSSW FWJR.

**Comment by ticoann** [comment]
Thanks Eric, Chris, that makes things simple.  I will create the patch.
