### ISSUE TITLE
ACDC with too many parents

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8196]
Currently following workflows are skipped in vocms0308 and vocms0310 due to too many parents files need to be retrieved. (60K) Which takes up all the processing in WorkQueueMananger
We need to check whether parentage is needed or make more effient.

```
"mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053538_530", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053544_9947", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053551_9974", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053600_3305", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053608_5854", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053617_8169", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053625_8322", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053632_9709", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053641_9747", "mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053649_646"
```

**Comment by vlimant** [comment]
from the chat, it seems mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053600_3305 (affecting 310) and mcremone_ACDC0_task_EGM-RunIISummer17GS-00002__v1_T_170924_053538_530 (affecting 308) were the main source of issue
