### ISSUE TITLE
CreationFailure, but nothing missing

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8219]
the error report for     prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719 indicates
    Job Name: 7ed914fa-a389-11e7-8368-a0369f23cf8a-25
    WMBS job id: 2626151
    Workflow: prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719
    Task: /prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719/DataProcessing
    Status: jobfailed
    Input dataset: /FSQJets/Run2016H-v1/RAW
    Site: N/A
    Agent: cmsgwms-submit2.fnal.gov
    ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
    State Transition
    Exit code: 99305
    Retry count: 0
    Errors:
        CreationFailure
            CreationFailure (Exit Code: 99305)

                File /store/data/Run2016H/FSQJets/RAW/v1/000/283/685/00000/B03C5047-F499-E611-A34F-02163E0135CC.root has too many events (42271) in 1 lumi(s)

    Input files:
    Lumis:
    Output:
    log archive:

and 

    Job Name: 7ed914fa-a389-11e7-8368-a0369f23cf8a-26
    WMBS job id: 2626152
    Workflow: prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719
    Task: /prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719/DataProcessing
    Status: jobfailed
    Input dataset: /FSQJets/Run2016H-v1/RAW
    Site: N/A
    Agent: cmsgwms-submit2.fnal.gov
    ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
    State Transition
    Exit code: 99305
    Retry count: 0
    Errors:
        CreationFailure
            CreationFailure (Exit Code: 99305)

                File /store/data/Run2016H/FSQJets/RAW/v1/000/283/685/00000/5AC1C84F-F499-E611-BD43-02163E01355B.root has too many events (42023) in 1 lumi(s)

    Input files:
    Lumis:
    Output:
    log archive:

but there is nothing missing in the expected output.
I am wondering whether the creation failure happens before the RunWhitelist or LumiWhitelist is applied. i.e. that big lumi/run is not in the RunWhitelist in the first place.

**Comment by vlimant** [comment]
for accounting what is going on with the current workflows we need a proper reporting of error and reporting in the ACDC documents

**Comment by amaltaro** [comment]
This is actually a dup of #7260
