### ISSUE TITLE
Unreported missing lumisections

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8220]
I was looking at the 2 missing lumisection from 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016H-FSQJets-07Aug17-0008
and the fact that only the DQMIO is missing something, while all seem to have succeeded on ACDC (there's a second order mystery on why     prozober_ACDC0_Run2016H-v1-FSQJets-07Aug17_8029_170927_144054_8719 has failures, but nothing missing in the output #8219)

Tracking this in the logs, the two lumisections were actually merged in AOD from the output of the original workflow, but cannot be found to be merge in DQMIO. Neither can they be found in the ACDC document of the original workflow (hence not in any ACDC).

The lumisection was processed (see all logs below) 1004fc1c-9eaa-11e7-a550-001e67abf518-512-1-logArchive.tar.gz and reported in the FrameworkJobReport.xml

I could not make sense of the content of stageOut1/Report.pkl to check the output file names in the storage and whatnot, so I cannot tell whether the file was stage-out properly and never used subsequently in a merge job, or if the stage-out failed but did not get reported as missing.

With Ops spending time and effort chasing last lumisections, and things getting delayed, I think it is important to track down, understand how the accounting went astray and fix it.

all logs from eos are in
vlimant@vocms049.cern.ch >ls /tmp/vlimant/fabozzi_Run2016H-v1-FSQJets-07Aug17_8029_170831_183904_6546_ALLLOGS

N.B. dqmio files are reported with 0 events in the FrameworkJobReport
1004fc1c-9eaa-11e7-a550-001e67abf518-512-1-logArchive.tar.gz_dir/cmsRun1/FrameworkJobReport.xml:<Run ID="282663">
1004fc1c-9eaa-11e7-a550-001e67abf518-512-1-logArchive.tar.gz_dir/cmsRun1/FrameworkJobReport.xml-   <LumiSection ID="742" NEvents="0"/>
and that is expected, since these are histogram files.

**Comment by vlimant** [comment]
looking at https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=ReReco-Run2016B-SinglePhoton-07Aug17_ver2-0024 it is very likely the same issue, but on AOD and other data tiers.
i.e. no failures, and still missing data.

**Comment by vlimant** [comment]
related to #7280 maybe ?

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22fabozzi_Run2016B-v2-SinglePhoton-07Aug17_ver2_8029_170831_201611_4366%22&include_docs=true&reduce=false
 
vlimant_ACDC0_Run2016B-v2-SinglePhoton-07Aug17_ver2_8029_170927_141623_7634 should have processed it
 
what I can see is
{"_id":"0e40480d53cf5bea43bb4f525dc3a1af","_rev":"1-644277b933c6a626ab579677de5c7394","files":{"/store/data/Run2016B/SinglePhoton/RAW/v2/000/274/161/00000/A0718CCD-2725-E611-80AB-02163E013807.root":{"lfn":"/store/data/Run2016B/SinglePhoton/RAW/v2/000/274/161/00000/A0718CCD-2725-E611-80AB-02163E013807.root","locations":["T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8997693,"size":4284489070,"runs":[{"run_number":274161,"lumis":[55,56]}],"last_event":0,"parents":[],"events":7319,"merged":"1"},"/store/data/Run2016B/SinglePhoton/RAW/v2/000/274/161/00000/983925ED-2725-E611-9D94-02163E01434D.root":{"lfn":"/store/data/Run2016B/SinglePhoton/RAW/v2/000/274/161/00000/983925ED-2725-E611-9D94-02163E01434D.root","locations":["T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8997694,"size":3650653826,"runs":[{"run_number":274161,"lumis":[57,58,59,60]}],"last_event":0,"parents":[],"events":6240,"merged":"1"}},"collection_name":"fabozzi_Run2016B-v2-SinglePhoton-07Aug17_ver2_8029_170831_201611_4366","collection_type":"ACDC.CollectionTypes.DataCollection","fileset_name":"/fabozzi_Run2016B-v2-SinglePhoton-07Aug17_ver2_8029_170831_201611_4366/DataProcessing","timestamp":1505807967.5606310368}}
 
there are 2 keys in the files directory, and while 274161,"lumis":[57,58,59,60] are not missing, 274161,"lumis":[55,56] are. So it looks like the acdc is running only on one of the two
https://its.cern.ch/jira/browse/CMSCOMPPR-1382

**Comment by vlimant** [comment]
another case 
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22fabozzi_Run2016C-v2-MET-07Aug17_8029_170831_200631_3696%22&include_docs=true&reduce=false

where 276242:39 and 276242:87 (among others) are missing from the final output, while it is in the ACDC doc and the ACDC had no failure.

fabozzi_Run2016C-v2-MET-07Aug17_8029_170831_200631_3696
vlimant_ACDC0_Run2016C-v2-MET-07Aug17_8029_170928_141233_6261

could it be a a missing handling of not being able to read the file ?
is it because the file /store/data/Run2016C/MET/RAW/v2/000/276/242/00000/2C84FA3B-9640-E611-BA89-02163E012336.root appears twice in the ACDC doc ? (no because /store/data/Run2016C/MET/RAW/v2/000/276/242/00000/BC75385C-9840-E611-ADD8-02163E0144C8.root appears once and 276242:125 is also missing ?)

**Comment by amaltaro** [comment]
Sorry for the delay. I'm having a look at this last example now.

**Comment by amaltaro** [comment]
Getting an overview of
fabozzi_Run2016C-v2-MET-07Aug17_8029_170831_200631_3696

it's supposed to process 'TotalInputLumis': 18810, while ALL the output files have 18797 at the moment (so 13 lumis missing). Among the missing lumis, those 3 that you mentioned above
276242:39, 276242:87 and 276242:125

First weird thing is, original workflow had 27 DataProcessing failures, while the ACDC ran 40 processing jobs (same job splitting).

The ACDC workflow was acquired by vocms0308 (still in completed status) and, checking the wmbs tables shows why we don't see those lumi sections in the output:
```
SELECT rlm.fileid, rlm.run, rlm.lumi, wfd.lfn FROM wmbs_file_details wfd
INNER JOIN wmbs_file_runlumi_map rlm ON rlm.FILEID=wfd.ID
WHERE lfn IN ('/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/4040565E-9840-E611-872E-02163E0139DC.root',
'/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/2C84FA3B-9640-E611-BA89-02163E012336.root',
'/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/B682D12F-9840-E611-85F9-02163E01413A.root');

11406344	276242	86	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/2C84FA3B-9640-E611-BA89-02163E012336.root
11406344	276242	88	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/2C84FA3B-9640-E611-BA89-02163E012336.root
11406354	276242	38	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/4040565E-9840-E611-872E-02163E0139DC.root
11406354	276242	40	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/4040565E-9840-E611-872E-02163E0139DC.root
11406376	276242	123	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/B682D12F-9840-E611-85F9-02163E01413A.root
11406376	276242	124	/store/data/Run2016C/MET/RAW/v2/000/276/242/00000/B682D12F-9840-E611-85F9-02163E01413A.root
```

so those lumis were NOT inserted into the database. Now checking why it happened.

**Comment by vlimant** [comment]
great stuff. please keep us posted

**Comment by amaltaro** [comment]
Sigh, I can't find any flaws on that code. Every single lumi section + run should have been inserted in WMBS:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/File.py#L558

and I checked the whole code twice, dumped a few pickled files along the way such that we don't lose the acdc data.

I wanted to check WorkQueueManager logs to see if there was any error/problem when acquiring that, but it has been rotated already and log is gone.

**Comment by amaltaro** [comment]
@vlimant if you need to announce these wfs, please go ahead. I won't manage to look at it again before Monday.

**Comment by amaltaro** [comment]
The previous workflow is gone, so I started looking at:
https://its.cern.ch/jira/browse/CMSCOMPPR-1422

and my initial findings are....
Randomly picking run/lumi:
```
file dataset=/Charmonium/Run2016G-v1/RAW run=278875 lumi=149
lumi file=/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root
Lumi: [149, 152]
Run number: 278875
```

The original workflow ran at a few different agents and I do see all 4 lumis in wmbs:
```
workflow: fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157
agent url: vocms0308.cern.ch,cmsgwms-submit2.fnal.gov,vocms0310.cern.ch,vocms0126.cern.ch,vocms0304.cern.ch

Input available in vocms0310
select * from wmbs_file_runlumi_map where FILEID=(select id from wmbs_file_details where LFN='/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root');
```

while the first ACDC has only one lumi section in the wmbs table
```
workflow: vlimant_ACDC0_Run2016G-v1-Charmonium-07Aug17_8029_170929_073824_5097
agent url: vocms0308.cern.ch

Input available in vocms0308
select * from wmbs_file_runlumi_map where FILEID=(select id from wmbs_file_details where LFN='/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root');
11463810	278875	152	
```

and these are the important ACDC entries for the original workflow
```
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157%22&include_docs=true&reduce=false

{"id":"4f5d7574067444c4d7776c59047a599f","key":"fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157","value":{"_rev":"1-91c7fac1cbd85b78c0a14587944b39af","_id":"4f5d7574067444c4d7776c59047a599f"},"doc":{"_id":"4f5d7574067444c4d7776c59047a599f","_rev":"1-91c7fac1cbd85b78c0a14587944b39af","files":{"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root":{"lfn":"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root","locations":["T1_FR_CCIN2P3_Disk","T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8935422,"size":3621324290,"runs":[{"run_number":278875,"lumis":[149,150,151]}],"last_event":0,"parents":[],"events":5393,"merged":"1"},"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/2A46E653-7363-E611-9C8F-FA163E625666.root":{"lfn":"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/2A46E653-7363-E611-9C8F-FA163E625666.root","locations":["T1_FR_CCIN2P3_Disk","T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8935418,"size":3639886281,"runs":[{"run_number":278875,"lumis":[153,154]}],"last_event":0,"parents":[],"events":5416,"merged":"1"}},"collection_name":"fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157","collection_type":"ACDC.CollectionTypes.DataCollection","fileset_name":"/fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157/DataProcessing","timestamp":1505840064.0781030655}},
{"id":"0e40480d53cf5bea43bb4f525dca367c","key":"fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157","value":{"_rev":"1-511b106e3b6eed214ba61ebe00c16fb4","_id":"0e40480d53cf5bea43bb4f525dca367c"},"doc":{"_id":"0e40480d53cf5bea43bb4f525dca367c","_rev":"1-511b106e3b6eed214ba61ebe00c16fb4","files":{"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root":{"lfn":"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/92E93157-7363-E611-AFF0-02163E011CC8.root","locations":["T1_FR_CCIN2P3_Disk","T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8935422,"size":3621324290,"runs":[{"run_number":278875,"lumis":[152]}],"last_event":0,"parents":[],"events":5393,"merged":"1"},"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/3CAD3B7F-6F63-E611-AD6F-FA163E1B7D49.root":{"lfn":"/store/data/Run2016G/Charmonium/RAW/v1/000/278/875/00000/3CAD3B7F-6F63-E611-AD6F-FA163E1B7D49.root","locations":["T1_FR_CCIN2P3_Disk","T3_US_FNALLPC","T1_US_FNAL_Disk"],"first_event":0,"checksums":{},"id":8935414,"size":3757300289,"runs":[{"run_number":278875,"lumis":[145,146,147,148]}],"last_event":0,"parents":[],"events":5591,"merged":"1"}},"collection_name":"fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157","collection_type":"ACDC.CollectionTypes.DataCollection","fileset_name":"/fabozzi_Run2016G-v1-Charmonium-07Aug17_8029_170831_190446_6157/DataProcessing","timestamp":1505808228.1856780052}},
```

there must be a problem somewhere where one entry of that file gets lost. Unfortunately I could not find any flaw in the code. That leaves me only one option, which is to try to reproduce this problem in testbed.

**Comment by ticoann** [comment]
Thank you very much Alan for the investigation. I think there is problem when the same file has 2 or more entries. But this seems the bug we always had. I am not sure why this happens now.
I created the patch #8241. @amaltaro, Alan could you review.

**Comment by vlimant** [comment]
maybe only now does someone cares to understand why there is something missing while nothing is reported missing ;-)
I hope that patch gets us through.
Another case https://its.cern.ch/jira/browse/CMSCOMPPR-1552 if more material is needed

**Comment by amaltaro** [comment]
It might be caused by the same root cause than this one, nonetheless, it's a different issue and I created a different ticket to address it: https://github.com/dmwm/WMCore/issues/8258

**Comment by amaltaro** [comment]
Provided that we cannot replicate it in our testbed setup nor find any flaws in the code, I was going to say it could have been that the ACDC workflow was assigned while not all the documents were available in the ACDCServer... but looking at the previous example, there is 1.5d offset between the original wf completion and the ACDC assignment. Moreover, I think a workflow doesn't go to complete if ErrorHandler still has jobs to process, right?

@ticoann perhaps we should validate your fix and push it to the agents. Even if that doesn't solve the issue, we'll at least have a better db performance.

**Comment by amaltaro** [comment]
Given the previous comments, I'm demoting this issue and pushing it to end'ish of this year...
