### ISSUE TITLE
Remove MaxVSize code

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8221]
Since we don't use it, we better get it out of the code.

**Comment by amaltaro** [comment]
@hufnagel @bbockelm any reason not to remove it?

**Comment by hufnagel** [comment]
Practical difference between removing it and setting it to 1TB is kind of irrelevant. But if you really are finally too bothered by it, sure, why not ;-).

**Comment by amaltaro** [comment]
I always heard we should not kill jobs based on vsize, that's why I used 1TB as default value :) Just wanted to hear any good arguments for doing or not something. 
The more code, the more maintenance, that's the mean reason behind removing it if unused/useless.

**Comment by hufnagel** [comment]
I cannot foresee any scenario where we would ever go back and want to actually kill on VSize. So in that sense removing it should be fine (and make the code a bit easier to maintain in the long run as you said).

**Comment by bbockelm** [comment]
I would prefer to remove it.  We have `git history` if this turns out to be the wrong decision.
