### ISSUE TITLE
MaxRSS at assignment web ui

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8236]
With the latest developments related to memory <--> maxrss (where maxRSS gets set according to the Memory requirements), the tasks configuration have the proper settings during the request creation.
Problem is, the form given via assignment web page contains default values and that value comes from the request.schema definitions (which contains the workload default values, not the ones provided within the tasks/steps).

There are at least two ways to fix it:
1. properly build the Memory/MaxRSS value (from the tasks/steps if it's a chained request) and set it at workload (and schema level), during creation
2. remove MaxRSS field from the assignment web ui. Memory isn't there anyways...

I'm in favor of 2 because it's much easier and easier to maintain at a long run.
@ticoann any thoughts?

**Comment by amaltaro** [comment]
In addition to that, I'd remove a few other settings from the web ui assignment page and leave only what's is _normally_ touched by Ops. Leaving the fields rarely changed to the rest api only.

**Comment by ticoann** [comment]
@amaltaro, Alan, so even if MaxRSS is defined in the request, it gets overwritten when Memory value is set, is that correct?

**Comment by amaltaro** [comment]
MaxRSS can't be (manually) set during request creation, it is an assignment argument. Well, scratch that, actually it can:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1054

If user explicitly sets it, then the expected behaviour is to use the user input (though I'm not sure it corresponds to reality :) Still, I don't think P&R team sets it during creation, only assignment.

**Comment by amaltaro** [comment]
Seangchan, I think I just figured what the problem is. I'll have a look at it soon and - if needed- you can follow it up on your timezone :)

**Comment by amaltaro** [comment]
Honestly, I think we should just "get rid of" this MaxRss and hard couple it to the Memory requirements, in a completely transparent way to the end users/P&R.

**Comment by ticoann** [comment]
I completely agree if users are not going to set it in different value than memory. I can update the patch

**Comment by ticoann** [comment]
However, looking at WmAgentScript code. It seems it is explicitly set the MaxRSS
https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py#L790
is MaxRSS has different unit than Memory?

**Comment by amaltaro** [comment]
They used to have, Memory is/was in MB and MaxRSS was in KB. We changed MaxRSS half an year ago to MB too, but we had to support KB too
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L201

we should be able to replace that by now, I hope. I'm asking them in this issue:
https://github.com/CMSCompOps/WmAgentScripts/issues/248
