### ISSUE TITLE
Merge task incompatibility between new agent and old workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8237]
Reposting it from JIRA:
https://its.cern.ch/jira/browse/CMSCOMPPR-1441

In summary, old workflows - created before the HG1709 cmsweb upgrade - don't carry the `input.dataTier` attribute for the merge tasks.
When the new agent (>= 1.1.6) acquires this workflow and starts creating entries in wmbs, it might not create a merge task in wmbs_workflow, which is supposed to be associated to a subscription and a fileset:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WMBSHelper.py#L330

**Comment by vlimant** [comment]
is that guy badly affected ? https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_Run2016G-v1-SingleMuon-07Aug17_8029_171003_152214_9971
if so we need to know urgently since everyone is watching it

**Comment by amaltaro** [comment]
Sorry to say, but yes. Those files aren't making anywhere. I suggest we/you abort it and clone/assign to the highprio team.

**Comment by amaltaro** [comment]
We updated the spec of all old workflows (and new recoveries for old workflows). All the details were discussed with Seanghan (subject: "Merge problem") and with the P&R team (subject: "Sever situation with the agents").

I'll keep this issue opened until tomorrow morning.

**Comment by amaltaro** [comment]
Things look stable now. No code changes required, only workload spec updates.
Closing it and hopefully we won't need to reopen it.
