### ISSUE TITLE
Wrong site reported in wmstats

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8240]
I thought it had been fixed, but looking at one case today I see it's not.
More details here:
https://cms-logbook.cern.ch/elog/GlideInWMS/5691

**Comment by ticoann** [comment]
One weird thing is these jobs seems to be held states according to condor log, not the Running state. and removed from the the pool.  Job sites gets updated when state is change to Running state. So this might be the cause of the problem. I will take a look and decide update the locations in jobs in Held state.

**Comment by ticoann** [comment]
FYI this is the line from condor log
<a n="MachineAttrGLIDEIN_CMSSite0"><s>T2_US_Florida</s></a>

**Comment by amaltaro** [comment]
I might be wrong, but I think not even our job wrapper has started on those worker nodes (since it was a singularity setup/bootstrap issue). Thus there is no code trapping the exit code and wait a minimum time (5min) before exiting the worker node.

As we can see in the condor logs, that information is reachable there, the problem though is when that information is safely available on the schedd... same issue as for condor_rm.

Maybe we could look for a specific information in the log, and in case it's not there we skip it up to X times (5?), when we give up on that option and simply use whatever we have to report.

**Comment by vlimant** [comment]
a "NoSiteToReport" could be better than a random site name IMO.
"a wrong report is worse than no report" they say.
