### ISSUE TITLE
Dashboard and WMStats reporting different error codes

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#8264]
SeangChan asked me to open an example of when Dashboard and WMStats are reporting different error codes.
Here is one good example that is showing right now:
pdmvserv_task_HIG-RunIISummer15wmLHEGS-01737__v1_T_171012_121755_352
Dashboard is showing 40's, when I look at WMStats I see:
PerformanceError
PerformanceKill (Exit Code: 50660)
Error in CMSSW step cmsRun1
Job has exceeded maxRSS: 3225600
Job has RSS: 3320520
cmsRun1
CMSSWStepFailure (Exit Code: 40)
 Adding last 25 lines of CMSSW stdout:
 2274 XrdAdaptorInternal   pre-events       pre-events       pre-events
 2275 FailedPropagation    1/25179792                        
 2276 FailedPropagation    1/171323814      1/171324455      
 2277 FailedPropagation    1/171323814                       
 2278 GsfMultiStateUpdator 1/13445307       1/13445307       1/171325765
 2279 GsfMultiStateUpdator 1/171323935                       
 2280 InvalidState         1/13445307       1/13445307       1/171325765
 2281 InvalidState         1/171323935                       
 2282 PosteriorWeightsCalculator 1/13445307       1/13445307       1/171325765
 2283 PosteriorWeightsCalculator 1/171323935                       
 2284 TimeReport           PostEndRun                        
 2285 MemoryReport         PostEndRun                        
 2286 fileAction           1/13444075       1/13444069       1/13444071
 2287 fileAction           pre-events       pre-events       pre-events
 2288 fileAction           PostEndRun       PostEndRun       PostEndRun
 2289 fileAction           PostProcessEvent PostProcessEvent PostEndRun
 2290 fileAction           pre-events       pre-events       PostProcessEvent

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning             54384               54384
Error                  20                  20
System                 48                  48
Complete
process id is 85483 status is 40
<@========== WMException Start ==========@>
Exception Class: CmsRunFailure
Message: Error running cmsRun
{'arguments': ['/bin/bash', '/home/tmp/87318762.pbs04.pic.es/glide_7j74mW/execute/dir_85133/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc530', 'scramv1', 'CMSSW', 'CMSSW_8_0_21', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Return code: 40

	ModuleName : None
	MethodName : __init__
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/WMSpec/Steps/WMExecutionFailure.py
	ClassName : None
	LineNumber : 18
	ErrorNr : 40

Traceback: 

<@---------- WMException End ----------@>
ErrorLoggingAddition (Exit Code: 99999)
Adding extra error in order to hold error report

Adding last ten lines of CMSSW stderr:
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
WARNING: There already exists /home/tmp/87318762.pbs04.pic.es/glide_7j74mW/execute/dir_85133/job/WMTaskSpace/cmsRun1/CMSSW_8_0_21 area for SCRAM_ARCH slc6_amd64_gcc530.
logArch1
stageOut1

**Comment by ticoann** [comment]
Job Name: 994adf84-b366-11e7-bce9-02163e01877e-8
WMBS job id: 870441
Workflow: pdmvserv_task_HIG-RunIISummer15wmLHEGS-01737__v1_T_171012_121755_352
Task: /pdmvserv_task_HIG-RunIISummer15wmLHEGS-01737__v1_T_171012_121755_352/HIG-RunIISummer15wmLHEGS-01737_0/HIG-RunIISummer16DR80Premix-03845_0
Status: jobfailed
Input dataset:
Site: T1_ES_PIC
Agent: vocms0250.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition

**Comment by amaltaro** [comment]
Also merging it into a single issue
