### ISSUE TITLE
Where is the local stage out log???

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8270]
If one look at the tarball attached to this ggus:
https://ggus.eu/index.php?mode=ticket_info&ticket_id=131288

I can't really make sense of that stage out logging and I can't find the error for the local stage out neither.

**Comment by vlimant** [comment]
on a similar note, I was wondering about the content of the Report.pkl which I was unable to make sense of just yet.

**Comment by amaltaro** [comment]
on a similar note, but totally different :)
Report.pkl is a ConfigSection object AFAIR, thus it has a well defined structure.

**Comment by vlimant** [comment]
does it contain any "report" information ?

**Comment by vlimant** [comment]
I mean  the one in stageOut1/ directory of course, which is the only thing that I can find in logarchive

**Comment by amaltaro** [comment]
Log has been reworked and it will get copied back to the agent and it will also be available in the job logArchive tarball (which ends up in the logCollect tarball). More info on https://github.com/dmwm/WMCore/pull/8425
