### ISSUE TITLE
PerformanceKill report : include the core count

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8271]
in message like this one 

PerformanceKill (Exit code: 50660)
Error in CMSSW step cmsRun1
Job has exceeded maxRSS: 3749888
Job has RSS: 4980436

would it be possible to add a line that says how many thread the job was ran on. since resizing is more democratized already, this would help understanding things upfront.
same comment stand for the time out performance kill.

**Comment by ticoann** [comment]
Yes, Is number of threads enough? or number of streams as well?
