### ISSUE TITLE
Merge for NANOAOD processing

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8273]
Distilling the information in many threads of information, @amaltaro converged on the following requirements to be able to merge the nanoaod non-edm files.

The regular merge step creation taken from DataProcessing needs to be passed a new argument (I vote for mergeNANO), which needs to be set to true if the declared datatier is NANOAOD or NANOAODSIM.

I'll take care of the DataProcessing configuration change to swap the outputmodule to NanoAODOutputModule type, using that mergeNANO=True parameter.

**Comment by vlimant** [comment]
https://github.com/cms-sw/cmssw/pull/21013 implements the mergeNANO switch, will probably make it in 9.4 pre4

**Comment by hufnagel** [comment]
Are we planning to produce NANOAOD from the Tier0 ? If so, I probably should make a new Tier0 release quickly once this functionality is in a WMCore release...

**Comment by vlimant** [comment]
I am not aware the plan on this end
