### ISSUE TITLE
PU json containing location of incomplete blocks

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8275]
for pdmvserv_task_SMP-PhaseIITDRFall17DR-00007__v1_T_171006_181121_5757 for example, from the json T2_IT_Legnaro and T2_IT_Bari seem to be holding the PU in full, while it is not the case.
The dataset is being transferred and not yet there in full.

Feature or bug ?

**Comment by amaltaro** [comment]
We only add blocks that are complete at a destination:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py#L73

so if T2_IT_Legnaro and T2_IT_Bari are set for a block that is not completed yet, it means some data/file got deleted/locally invalidated or something like that, after the json was built.
