### ISSUE TITLE
Published NANOAOD NANOAODSIM files type

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8276]
related to #8273 
and /RelValTTbar_13/CMSSW_9_4_0_pre3-94X_mc2017_realistic_v4_RelVal_nanoaod94X-v2/NANOAODSIM test dataset

The format declared in dbs should be something different than EDM, for consistency.
Not so sure what other type is possible : @yuyiguo ?

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, this is not an issue any more, right?

**Comment by vlimant** [comment]
NANOAODSIM is not of EDM type, and will never be. If we care about the declared type in dbs, we need to declare the correct type. if we don't care about the declared type in dbs, we can drop this.

hence the question : what are the allowed types in dbs @yuyiguo and do we have the handle in the agent to inject a file type different than "edm"

**Comment by ticoann** [comment]
These are the current types dbs has

EDM
LUMI
LUMI-SA
LUMI-VDM
PIXDMP
STREAMER

**Comment by vlimant** [comment]
the NANOAOD, NANOAODSIM can exist in both edm (PoolOutput module) or non-edm (NanoAODOutputModule). The most usual case is non-edm (see above).
I would not be sure how to name the new type in DBS, and whether we need a new type ; will come back to this after consulting the nanoaod commissioning group

**Comment by amaltaro** [comment]
@vlimant did you manage to get any updates on this front?

**Comment by amaltaro** [comment]
If we decide it's important to have it in the agent, please reopen.
