### ISSUE TITLE
Ban NANOAOD{SIM} files from going straight to merge

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8278]
Otherwise we could end up with some EDM and non-EDM files under the same dataset. The idea is to never have NANOADO EDM format registered in DBS.

This hook can be added either with:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Templates/StageOut.py#L51

or checking the datatier here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/StageOut.py#L151

@hufnagel you use these mechanism in T0, let me know if there is a better place for adding this tweak.

**Comment by hufnagel** [comment]
Tier0 does it differently, we use the forceMerged and forceUnmerged options in spec methods when we setup the workflow (which eventually ends up calling your first code segment). I think this would be total overkill here when we know that we never want to use elevation to merged output for this data tier.

My vote is for an early conditional in front of the second code section, doing a data tier comparison and skipping all the checks if we have NANOAOD(SIM). That assumes you have the data tier information available at that point ?
