### ISSUE TITLE
Add worker node hostname in fwjr for WMArchive.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8279]
In meta_data field.
meta_data["wn"] or meta_data["worker_node"]

**Comment by ticoann** [comment]
FYI @vkuznet, @amaltaro 

Will this be only information from worker node, or some more information.

**Comment by vkuznet** [comment]
Seangchan, I would be explicit, so please use meta_data["worker_node"].
Hepix people asked also the following:
- $MACHINEFEATURES/hs06: HS06 score of the host
- $MACHINEFEATURES/total_cpu: number of configured job slots
- $JOBFEATURES/hs06_job: HS06 score available to your job
- $JOBFEATURES/allocated_cpu: number of allocated slots (=8 in case of a multicore job)
(see https://github.com/HEP-SF/documents/raw/master/HSF-TN/2016-02/HSF-TN-2016-02.pdf for a full description.

**Comment by ericvaandering** [comment]
Do we know if these machine and job features are really the machine or the pilot? In other words, lets say its a 4 core job running in an 8 core pilot in a 32 core physical machine (or VM). 

Is MACHINEFEATURES/total_cpu 8 or 32?
Is JOBFEATURES/allocated_cpu 4 or 8?

**Comment by vkuznet** [comment]
I think it is only one way to check it, just get some node spec by logging directly to such node. Alan @amaltaro may help with that.
