### ISSUE TITLE
Changing Multicore and Memory on a TaskChain ACDC

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8283]
related to https://its.cern.ch/jira/browse/CMSCOMPPR-1571 we seem to be needing to increase the core count on the phaseII digi because the gen-sim lumis are too big.
making and acdc with edited schema https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC0_task_HGC-PhaseIITDRFall17DR-00010__v1_T_171027_155235_4595 failed to get the jobs submitted with 16 cores and 29G as specified.

Can this be only achieved by changing the values at assignment time ?
I put urgent-ops since the ACDC for many of the "everybody's watching" PhaseII requests are held on this

**Comment by amaltaro** [comment]
Please assign the workflow with the settings you want. Multicore changes are not supported during Resubmission creation.

That's why we allow their update during assignment, to avoid mucking with the request creation parameters.

**Comment by vlimant** [comment]
thanks for the confirmation.
So it works for changing memory, but not for Multicore, right ?
While indeed that gives ops the possibility to assign these, that leaves open issues with having to change the splitting also by hand prior to assignment, maybe #7767 in the future

**Comment by amaltaro** [comment]
Yes, though there is this detail about TaskChain ACDCs:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/Resubmission.py#L44

so, if you want to update Memory settings, you need to pass a dict of taskname:value for all tasks

**Comment by amaltaro** [comment]
Please confirm the assignment works as expected and close this issue.

**Comment by vlimant** [comment]
@areinsvo : note that your recent change for setting memory in ACDC (https://github.com/CMSCompOps/WmAgentScripts/commit/55f90e9cdf66505b94b3c8cce6b70189246a0a1f) seems to be plain wrong the way it's described here. I am close to say "abandon ship" ...

**Comment by vlimant** [comment]
@amaltaro can you please make a GH issue so that we get rid of everything in submitted ACDC schema that is not doing anything. like any TaskN, TaskChain and anything else i.e. tighten the ACDC request validation.

I would vote for having 
        if arguments['OriginalRequestType'] != 'TaskChain' or isinstance(arguments['Multicode'], dict):
helper.setMulticore(arguments['Multicore'])

so that ACDC can be created with a different core count and different time/event, and therefore be completely self-consistent.
This way, when it comes to assigning, there is no need for having to remember to change the splitting or whatnot. 

Alternatively, have the time/event be changeable during assignment and modify the full splitting : #7767 and we get rid of line 42-47 you pointed out which at this point does not make 

I think all these inconsistencies arise from the mis-interpretation of Time/Event being 1/Throughput instead of the time/event per thread.

**Comment by amaltaro** [comment]
A couple of issues were created WmAgentScripts.

I think it would be fine to add Multicore to the creation arguments, for ACDC. However, I'd like to avoid having the same functionality supported in different ways.

I'm also removing the urgent ops label.
