### ISSUE TITLE
Preventing Schedd to run at their limit (Bis)

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8285]
following from #7559 the throttling should be done earlier then reaching the schedd limit, and either include a hard timeout for getting back to business to avoid see-sawing at the limit.

**Comment by amaltaro** [comment]
We have decreased the schedd limits and also put in place some mechanism to avoid fetching data from GQ when the agent is heavily loaded. Still, it can happen and as discussed with SI, there isn't much to be done at that stage. I'm closing this one.
