### ISSUE TITLE
avoid infinite loop in EventBased splitting

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#8289]
see https://github.com/dmwm/CRABServer/issues/5599
this loop in EventBased.py will go into infinte loop if eventsPerJob is not strictly positive.
We will put a check in CRAB client, but it may be a good idea to protect the code here as well.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L148-L183

**Comment by amaltaro** [comment]
I think such protection should be placed way up in the code, such that a "sick" workflow never gets to the job splitting.
In central production services, we already have this validation in place:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1201

Of course nothing refrain us from adding another check here... but if CRAB can have such validation during request creation, that's the cleaner option IMO.

**Comment by belforte** [comment]
I have put a protection in CRAB code (see the issue mentioned initially).
I surely agree that bad inputs should not be discovered so late in the processing. Whether an inner call should go into infinite loop or raise exception in case of problems is maybe a matter of tastel. In general sanitizing inputs is a good practice since there can be simply good honest (new) bugs upstream and the easier we make spotting them, the better for us. Of course there's a judgement call to make as to what is good protection and what's useless paranoia. This repository developers are surely more qualified than me to make that call.
And thinking about it, maybe we should put a second check in CRAB sort of mid-way.

**Comment by amaltaro** [comment]
Stefano, since we only call the job splitting algorithms when there is actual work to be splitted, I think it's Ok to add another check at that layer. PR 8290 was created and should go in in 1.1.8.pre5 tag
