### ISSUE TITLE
Don't create nor submit jobs for force-completed/aborted workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8300]
Besides cleanup/logcollect. This problem still happens from time to time when a workflows moves to completed too quickly (or to aborted-completed).

We need to revisit these two fixes https://github.com/dmwm/WMCore/pull/7763 and https://github.com/dmwm/WMCore/pull/7442

**Comment by ticoann** [comment]
duplicate with #8252
