### ISSUE TITLE
False heartbeat alarms in components on T0

### ISSUE THREAD

**Issue by vytjan** [dmwm/WMCore#8305]
As discussed with @amaltaro yesterday, time after time we're having false alarms of components at T0.

Some recent WMStats agent info messages:

    agent: vocms014.cern.ch (1.1.6.patch5)
    agent last updated: 2017/11/6 (Mon) 11:41:02 UTC : 0 h 1 m
    data last updated: N/A
    status: Components or Thread down;
    team: tier0production
    component errors for: JobSubmitterJobSubmitter
        worker thread: JobSubmitterPoller
        status: Timeout
        last updated: 2017/11/6 (Mon) 10:51:16 UTC
        pid: 2016612
        *error message:*Last worker thread heartbeat was 49 min ago

    agent: vocms014.cern.ch (1.1.6.patch5)
    agent last updated: 2017/11/6 (Mon) 16:12:31 UTC : 0 h 1 m
    data last updated: N/A
    status: Components or Thread down;
    team: tier0production
    component errors for: TaskArchiverTaskArchiver
        worker thread: CleanCouchPoller
        status: Timeout
        last updated: 2017/11/6 (Mon) 15:36:02 UTC
        pid: 208216
        *error message:*Last worker thread heartbeat was 36 min ago

    agent: vocms014.cern.ch (1.1.6.patch5)
    agent last updated: 2017/11/2 (Thu) 17:42:23 UTC : 0 h 5 m
    data last updated: N/A
    status: Components or Thread down;
    team: tier0production
    component errors for: TaskArchiver TaskArchiver
        worker thread: CleanCouchPoller
        status: Timeout
        last updated: 2017/11/2 (Thu) 17:04:17 UTC
        pid: 208216
        *error message:*Last worker thread heartbeat was 38 min ago

False alarms happen more often, these are only some cases reported by CPS shifters and therefore recorded.

**Comment by amaltaro** [comment]
Thanks Vytas! All of those were false alarms? the component was properly running and records were being written to the ComponentLog file (and were there errors in the logs? it might be an external service is not responsive ...)? Make sure to provide this info, such that we can distinguish real false alarms from real ones.

**Comment by vytjan** [comment]
I have rechecked the component logs. In all these cases, the components were running properly with records being written to the ComponentLog file - there aren't any errors around the "last updated" timestamps.
Therefore, I assume these were false alarms.

Let me know if you need any additional information.

**Comment by cronot99** [comment]
About the first error (JobSubmitter), it was not a false alarm, but the component crashed with no log entries. We are not sure if it is related to Tier0Feeder that crashed almost at the same time due to database connection errors.

On the other hand, yesterday afternoon (FNAL time) WMStats showed alarms of down components for TaskArchiver and PhEDEx injector, but the components were up and running. I didn't saved the "heartbeat" message, but I will if I saw it again

**Comment by cronot99** [comment]
We just had on WMStats a false alarm on component DBS3Upload:

agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/7 (Tue) 20:48:45 UTC : 0 h 1 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/7 (Tue) 20:18:32 UTC
pid: 2179175
error message:
Last worker thread heartbeat was 30 min ago

**Comment by vytjan** [comment]
Not sure if it is a separate issue or the same one, but DBS3Upload component is crashing without any error messages in the ComponentLog file (and then starts working again after some time):

    agent: vocms014.cern.ch (1.1.6.patch5)
    agent last updated: 2017/11/8 (Wed) 09:38:14 UTC : 0 h 3 m
    data last updated: N/A
    status: Components or Thread down;
    team: tier0production
    component errors for: DBS3Upload
    DBS3Upload
        worker thread: DBSUploadPoller
        status: Timeout
        last updated: 2017/11/8 (Wed) 08:55:10 UTC
        pid: 61404
        error message:
        Last worker thread heartbeat was 42 min ago

In addition to this, there are no log records for these ~45 min:
```
...
2017-11-08 09:58:24,439:140420646622976:INFO:DBSUploadPoller:Have 346 files for block /ParkingHT/Run2017F-v1/RAW#ac4e1ee2-c3b1-11e7-be6a-02163e018d62
2017-11-08 10:43:23,692:140420646622976:INFO:DBSUploadPoller:About to insert block /MET/Run2017F-LogError-PromptReco-v1/RAW-RECO#d36e2012-c42e-11e7-be6a-02163e018d62
...
```

**Comment by cronot99** [comment]
At this moment WMStats is reporting TaskArchiver as down, but it is currently running normally and writing on his log file without error messages

vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 14:46:26 UTC : 0 h 4 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: TaskArchiver
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 13:30:36 UTC
pid: 208216
error message:
Last worker thread heartbeat was 75 min ago

**Comment by cronot99** [comment]
We are receiving the same alarm on WMStast reporting TaskArchiver down. Again, the is working normally without error messages.

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 15:58:16 UTC : 0 h 0 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: TaskArchiver
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 15:07:49 UTC
pid: 208216
error message:
Last worker thread heartbeat was 50 min ago
```

**Comment by cronot99** [comment]
We just received an alarm of several components down on multiple agents, but all the components are up and running.

```
agent: vocms013.cern.ch (1.1.4.patch3)
agent last updated: 2017/11/8 (Wed) 17:45:05 UTC : 0 h 38 m
data last updated: N/A
status: Data is not updated: AnalyticsDataCollector Down;
team: tier0production
```

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 18:11:45 UTC : 0 h 14 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload,TaskArchiver
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:29:48 UTC
pid: 443593
error message:
Last worker thread heartbeat was 41 min ago
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:37:54 UTC
pid: 208216
error message:
Last worker thread heartbeat was 33 min ago```

**Comment by cronot99** [comment]
We just received an alarm of several components down on multiple agents, but all the components are up and running.

```
agent: vocms013.cern.ch (1.1.4.patch3)
agent last updated: 2017/11/8 (Wed) 17:45:05 UTC : 0 h 38 m
data last updated: N/A
status: Data is not updated: AnalyticsDataCollector Down;
team: tier0production
```

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 18:11:45 UTC : 0 h 14 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload,TaskArchiver
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:29:48 UTC
pid: 443593
error message:
Last worker thread heartbeat was 41 min ago
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:37:54 UTC
pid: 208216
error message:
Last worker thread heartbeat was 33 min ago```

**Comment by cronot99** [comment]
We just received an alarm of several components down on multiple agents, but all the components are up and running.

```
agent: vocms013.cern.ch (1.1.4.patch3)
agent last updated: 2017/11/8 (Wed) 17:45:05 UTC : 0 h 38 m
data last updated: N/A
status: Data is not updated: AnalyticsDataCollector Down;
team: tier0production
```

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 18:11:45 UTC : 0 h 14 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload,TaskArchiver
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:29:48 UTC
pid: 443593
error message:
Last worker thread heartbeat was 41 min ago
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:37:54 UTC
pid: 208216
error message:
Last worker thread heartbeat was 33 min ago```

**Comment by cronot99** [comment]
We just received an alarm of several components down on multiple agents, but all the components are up and running.

```
agent: vocms013.cern.ch (1.1.4.patch3)
agent last updated: 2017/11/8 (Wed) 17:45:05 UTC : 0 h 38 m
data last updated: N/A
status: Data is not updated: AnalyticsDataCollector Down;
team: tier0production
```

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 18:11:45 UTC : 0 h 14 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload,TaskArchiver
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:29:48 UTC
pid: 443593
error message:
Last worker thread heartbeat was 41 min ago
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:37:54 UTC
pid: 208216
error message:
Last worker thread heartbeat was 33 min ago```

**Comment by cronot99** [comment]
We just received an alarm of several components down on multiple agents, but all the components are up and running.

```
agent: vocms013.cern.ch (1.1.4.patch3)
agent last updated: 2017/11/8 (Wed) 17:45:05 UTC : 0 h 38 m
data last updated: N/A
status: Data is not updated: AnalyticsDataCollector Down;
team: tier0production
```

```
agent: vocms014.cern.ch (1.1.6.patch5)
agent last updated: 2017/11/8 (Wed) 18:11:45 UTC : 0 h 14 m
data last updated: N/A
status: Components or Thread down;
team: tier0production
component errors for: DBS3Upload,TaskArchiver
DBS3Upload
worker thread: DBSUploadPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:29:48 UTC
pid: 443593
error message:
Last worker thread heartbeat was 41 min ago
TaskArchiver
worker thread: CleanCouchPoller
status: Timeout
last updated: 2017/11/8 (Wed) 17:37:54 UTC
pid: 208216
error message:
Last worker thread heartbeat was 33 min ago
```

**Comment by amaltaro** [comment]
@vytjan has it improved after T0 migrated to newer WMCore releases (> 1.1.12)? If so, how about we close it?

**Comment by amaltaro** [comment]
@vytjan are you still seeing false heartbeats alarms for the T0 agents? Is it happening to the same two components you initially reported? It would be useful if you had data for the previous 3 months or so (even though we sort of know what are the slow components in the system).

**Comment by vytjan** [comment]
@amaltaro there were no false heartbeat alarms on Tier0 recently. 
 We can close this issue and re-open it if something similar happens in the future.

**Comment by amaltaro** [comment]
Perfect! closing.
