### ISSUE TITLE
Add number of cores monitoring

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8322]
Fetch amount of work - in terms of number of cores - that are either running and pending in condor and push it to WMStats and MonIT.
We could also fetch this information for work in the local agent queue (created), but I don't think we have the _expected_ number of cores in the database, but only in the job pkl file...

**Comment by amaltaro** [comment]
@khurtado if you're short on tickets, would you like to take a look at this one?

**Comment by khurtado** [comment]
Sure!

**Comment by khurtado** [comment]
@amaltaro Just to be sure I understand, is this basically adding "Running/Pending Cores" in the WMStats "[filtered stats view](https://github.com/dmwm/WMCore/blob/0615bd977edd4ad103db7ea24f461aa794c9a104/src/couchapps/WMStats/_attachments/js/Views/HTMLList/T1/WMStats.RequestSummaryList.js#L7-L19)" and adding `Running/Pending Cores per Agent` plots  in Grafana's Agent overview?

**Comment by amaltaro** [comment]
Erik, as we discussed over slack in the past week, I don't think we need to work on this issue anymore.

We can use the official CMS Job Monitoring to get this information, from this link:
https://monit-grafana.cern.ch/d/000000628/cms-job-monitoring?refresh=15m&orgId=11&var-group_by=ScheddName&var-Tier=All&var-Site=All&var-Type=production&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-binning=1h&var-measurement=condor_1h&var-retention_policy=long&from=now-2d&to=now-15m
