### ISSUE TITLE
Transferor MS module has to subscribe data according to the SiteWhitelist

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8324]
As discussed in a private thread, there are basically 2 options for the transferor module, but Jean-Roch has already confirmed how it works (or how it's supposed to work). Snippets of a private email:
"""
How is the transferor supposed to work
in the new schema. Is it:
1. transferor module will distribute the input data among sites - which fulfil the data
placement requirements - and *only then* Unified assigns that workflow. Thus, based
on where data is available or heading to.
OR
2. Unified first decides which sites the workflow has to run (one could read the workflow
is assigned) and *only then* the transferor module starts making phedex subscriptions
to places already decided by assignor/unified
"""

and this was @vlimant  answer:
"
 I think 2. But then we need a handle (setting back from staging to assignment-approved ?) when the destination is set drain afterwards, so as to re-route transfers."

This means transferor module has to query reqmgr2 for "acquired" workflows and then fetch all those blocks from Global workqueue and create phedex subscriptions.
This schema has to be changed as well: https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-APIs

@vkuznet FYI

**Comment by amaltaro** [comment]
This is apparently how the Transferor microservice has been implemented, but we can review and make sure it's doing the right thing.

**Comment by amaltaro** [comment]
@vlimant Jean-Roch, just to make sure we're still on the same page. Data placement is based on the rules defined within each Campaign, right?
The MicroService has a reference to a unified configuration json
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Common.py#L37

I guess that used to be the file with all the campaign configuration, correct?

**Comment by vlimant** [comment]
there are both a campaign level and general level configurations. I am not sure which one is the one @vkuznet implemented in UnifiedConfiguration

**Comment by vkuznet** [comment]
According to
https://github.com/CMSCompOps/WmAgentScripts
there are two files:
unifiedConfiguration.json
campaigns.json
(there were third file campains.relval.json but it is gone now).

The former is loaded in utils.py module, and later is not used anywhere.

In MicroService code I used unifiedConfiguration.json since it was used in
utils.py module. And I have a env variable to read campaigns.json but where
to use (or should it be used) should come from JR.

**Comment by vlimant** [comment]
campaigns.json used to be loaded by campaignInfo and used through that interface ; the json file is a sync in GH of the content of campaign configuration in mongodb

**Comment by vkuznet** [comment]
Are you saying that current 74KB campaign.json is what you have/had in MongoDB?
Why in this case you need MongoDB? Does MongoDB contains campaign configuration
or any other information? Can we migrate MongoDB under DMWM and put all docs
into CouchDB (I'm not against MongoDB per-se, but since DMWM depends on CouchDB
we should probably use it).

**Comment by vlimant** [comment]
the unified mongodb has much more than that.
yes to any other db (as I think I commented somewhere) as long as there is a trivial interface to it.

**Comment by vkuznet** [comment]
If you can give us MongoDB files I can organize the transfer. Since both MongoDB
and CouchDB stores json docs the migration should be trivial.

**Comment by amaltaro** [comment]
Valentin, I suggest we discuss a possible migration from Mongo to Couch in a different thread to avoid mixing things up here.

Jean-Roch, can you share this general configuration and go through what are the parameters that matter to data placement? If you can explain how it's suppose to change as well (how often, based on what, etc), that would be helpful to properly plan the next steps.

I chatted with Sharad today and he said the Pileup data placement (secondary input) is based on the campaign configuration, which contains a list of sites where the PU sample *must* be 100% available.
Thus, I assume the general configuration is only used for the primary input dataset (and maybe parent dataset?)?

Please shed some lighs on these details before we implement again something that doesn't match with reality.

**Comment by vlimant** [comment]
a migration to couchdb can come with its own issues https://github.com/CMSCompOps/WmAgentScripts/issues/403

**Comment by vlimant** [comment]
the two files are 
https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json
https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json

**Comment by amaltaro** [comment]
I just had a chat with Jean-Roch and he says the
* unifiedConfiguration is only available in GH (not persisted in mongo) and it should be up-to-date. We need to check what parameters matter to the Transferor module though, likely `sites_banned`, `sites_auto_approve`, `sites_with_goodIO`, etc
* the campaigns configuration is also persisted in mongodb (every campaign dict is broken down into a mongodb doc).

Thus, if we don't want to add another dependency in WMCore (pymongo), we'll need to update Unified and have it pushing docs to central couch as well.

**Comment by amaltaro** [comment]
Fixed by #9330
