### ISSUE TITLE
Automate site issue warning

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8328]
@mapsacosta

**Comment by ticoann** [comment]
1. condition for initial alert
2. exit code need to be looked at

**Comment by mapsacosta** [comment]
http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/

**Comment by amaltaro** [comment]
@mapsacosta Is it still relevant? If so, can you please clarify what you wanted to accomplish with this issue and what's the expected behaviour?

**Comment by amaltaro** [comment]
Thanks, Maria.
