### ISSUE TITLE
New API to get full list of workflows/dataset/blocks

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#8332]
I just spoke with Yutaro in a context of Dynamo taking charge of auto-deleting data when ReqMgr2 is no longer using them. He said that Dynamo team needs an API to get list of current workflows/dataset/blocks which current ReqMgr2/WQ are working with. Based on this list they can schedule deletion. I'm putting this into a ticket. @yiiyama Yutaro please confirm.

**Comment by yiiyama** [comment]
@vkuznet Thank you for the summary. Indeed, we threw around some ideas within the Dynamo team, and came to a conclusion that a full list (basically what Unified makes now) is the most efficient for both sides. Without this list, because of the way Dynamo deletions work, we will be querying `https://cmsweb.cern.ch/reqmgr2/data/request?inputdataset=XYZ` and `outputdataset=XYZ` a large number of times.

**Comment by ticoann** [comment]
@yiiyama, Yutaro, what exact information you are extracting and what API are you plan to use?

**Comment by yiiyama** [comment]
@ticoann What I had in mind is a query that will list all active workflows. But then I realized that I could query `https://cmsweb.cern.ch/reqmgr2/data/request?status=XYZ` where XYZ=new,assignment-approved, ... (i.e. all request statuses except for normal-archived, rejected-archived, and aborted-archived) and find the list of datasets that are involved. That will be a limited number of queries to make, so I believe we won't be causing heavy loads to anyone.
@vlimant Is this actually how you create the current lock file?

**Comment by ticoann** [comment]
@yiiyama, Hi Yutaro, sorry for the late reply.
If you are querying active workflows (not archived one following API will be better it uses server side cash so it will be fast and light).
https://github.com/dmwm/WMCore/wiki/wmstatsserver-api

i.e.

https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?mask=InputDataset&mask=OutputDataset&mask=MCPileup&mask=DataPileup&mask=RequestStatus

It only returns non archived requests.

**Comment by yiiyama** [comment]
Thank you @ticoann. It looks like reqmgr2 has some more information about the workflows than wmstatsserver. For example in the wmstatsserver link you have above, there is
`{
  "InputDataset": "/BTagCSV/Run2017B-v1/RAW", 
  "MCPileup": null, 
  "OutputDataset": null, 
  "RequestName": "fabozzi_Run2017B-v1-BTagCSV-17Nov2017_940_171208_171010_9362", 
  "RequestStatus": "running-open", 
  "DataPileup": null
}`
while in reqmgr2 for the same request (https://cmsweb.cern.ch/reqmgr2/data/request?name=fabozzi_Run2017B-v1-BTagCSV-17Nov2017_940_171208_171010_9362) we get
`    "OutputDatasets": [
      "/BTagCSV/Run2017B-17Nov2017-v1/DQMIO", 
      "/BTagCSV/Run2017B-17Nov2017-v1/MINIAOD", 
      "/BTagCSV/Run2017B-17Nov2017-v1/AOD"
    ], `

But I don't think it's a show stopper - I can probably combine two calls and that will still be a limited number of queries to make.

**Comment by amaltaro** [comment]
Closing this one in favor of https://github.com/dmwm/WMCore/issues/8134
