### ISSUE TITLE
Automatically fix JobAccountant unique lfn id

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8333]
The usual uuid collision, we should either:
a) fix it for good
b) make the component resilient to these problems and just fail the bad job/fwjr

Reported here https://its.cern.ch/jira/browse/CMSCOMPPR-1717

**Comment by ticoann** [comment]
I would vote for b) Unless we can find a solution quickly and not very intrusive.

**Comment by amaltaro** [comment]
:-) I guess that's what has to be done too. With some improvements, the code might not get that ugly :-)

**Comment by amaltaro** [comment]
Just for the record, it happened again on vocms0255 this time. There were 44 files duplicated among the pickle job reports that the component was processing (none of them were already in the database).

Those files were removed and the component restarted. It has accumulated 127k jobs to process within these 12h of outage.

**Comment by vlimant** [comment]
how do we get this not silently shooting us in the foot ?

**Comment by amaltaro** [comment]
It's going to be fixed by #8487 , we hope! Closing it for now
