### ISSUE TITLE
JobCreator not creating final jobs for a specific workflow

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8334]
This workflow
vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170926_193056_9589

is facing the same issues on both vocms0310 and vocms0303 (and maybe submit2).
These agents are being drained for a couple of weeks now, they have 0 jobs queued and/or in the global pool, however, there are still some subscriptions not finished and files available for further processing.

I've put vocms0310 JobCreator component into debug mode, but I can't see anything weird (besides a few things that I still don't know how it works...).

**Comment by amaltaro** [comment]
Jean-Roch noticed something weird going on with vocms0254, regarding this request:
pdmvserv_task_EXO-RunIISummer16NanoAOD-01867__v1_T_180210_152217_1516

it has only two WQE, both in Running state on vocms0254. One of them is completed, the other is `Running` in the agent. The wf_id `16179` and sub_id `34350` is still not finished, see 
```
SELECT wmbs_workflow.id AS wf_id, wmbs_subscription.id AS sub_id, wmbs_workflow.task, wmbs_subscription.finished
       FROM wmbs_workflow INNER JOIN wmbs_subscription 
       ON wmbs_workflow.id=wmbs_subscription.workflow
       WHERE wmbs_workflow.name='pdmvserv_task_EXO-RunIISummer16NanoAOD-01867__v1_T_180210_152217_1516';
```

both Processing filesets are no longer `open`, but only one of them has the subscription finished.

Poking around the wmbs tables, we can see that subscription still has THAT file available for job creation, the fileset has the correct fileid associated to it, AND it has valid locations, see
```
select * from wmbs_sub_files_available where subscription in (34350, 34394);
select * from wmbs_fileset_files where FILESET=197956;
select * from wmbs_file_location where fileid=4968732;
```

Now I'm going to add some debugging statements to the JobCreator code to see why it doesn't create a job/jobgroup for that available file
```
...
2018-02-28 10:54:02,205:140288507098880:INFO:JobCreatorPoller:Retrieved 0 jobGroups from jobSplitter
2018-02-28 10:54:02,206:140288507098880:INFO:JobCreatorPoller:Found end in iteration over subscription 34350
```

**Comment by amaltaro** [comment]
I found the problem, but I don't know how it happened!

The file available for job splitting does NOT have any run/lumi map information:
```
select * from wmbs_file_runlumi_map where FILEID=(select id from wmbs_file_details where lfn='/store/mc/RunIISummer16MiniAODv2/ADDGravToGG_MS-8000_NED-4_KK-1_M-500To1000_13TeV-sherpa/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/100000/9EA30DC4-82EF-E611-A0B7-7845C4F92EC7.root');
```

which makes this file not to have any Run object inside the job splitting algo, which causes no job to be created:
https://github.com/dmwm/WMCore/blob/1.1.8_wmagent/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L120

The component responsible for creating these wmbs information is WorkQueueManager (WorkQueueManagerWMBSFileFeeder thread), which according to the logs (and thankfully some debugging added on that branch) everything went smooth (including a graceful cycle completion):
```
...
2018-02-14 14:39:57,097:140288919463680:INFO:WMBSHelper:"pdmvserv_task_EXO-RunIISummer16NanoAOD-01867__v1_T_180210_152217_1516" Injecting block /ADDGravToGG_MS-8000_NED-4_KK-1_M-500To1000_13TeV-sherpa/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM#da7ed1b0-ef88-11e6-93bf-002590494c06 (1 files) into wmbs
2018-02-14 14:39:57,182:140288919463680:INFO:WMBSHelper:WMBS File: /store/mc/RunIISummer16MiniAODv2/ADDGravToGG_MS-8000_NED-4_KK-1_M-500To1000_13TeV-sherpa/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/100000/9EA30DC4-82EF-E611-A0B7-7845C4F92EC7.root
 on Location: set([u'T1_US_FNAL_MSS', u'T2_IN_TIFR', u'T2_US_UCSD', u'T1_US_FNAL_Buffer'])
2018-02-14 14:39:57,384:140288919463680:INFO:File:AMR about to add 1 non-unique files for fileset 197956
2018-02-14 14:39:57,395:140288919463680:INFO:File:AMR run and # of lumis to be recovered: {1: 4}
2018-02-14 14:39:57,398:140288919463680:INFO:AddRunLumi:AMR received 1 file entries
2018-02-14 14:39:57,399:140288919463680:INFO:AddRunLumi:AMR inserting 4 lumis from sliceBinds
2018-02-14 14:39:57,531:140288919463680:INFO:WorkQueue:Created top level subscription 34350 for pdmvserv_task_EXO-RunIISummer16NanoAOD-01867__v1_T_180210_152217_1516 with 1 files
...
2018-02-14 14:41:15,939:140288919463680:INFO:WorkQueueManagerWMBSFileFeeder:53 of units of work acquired for file creation
2018-02-14 14:41:15,941:140288919463680:INFO:BaseWorkerThread:WorkQueueManagerWMBSFileFeeder took 154.646 secs to execute
```

this is where the run/lumi information is added to the database (see log above):
https://github.com/dmwm/WMCore/blob/1.1.8_wmagent/src/python/WMCore/WMBS/File.py#L617

this is the DAO adding it (see log above, no problems!!!!):
https://github.com/dmwm/WMCore/blob/1.1.8_wmagent/src/python/WMCore/WMBS/MySQL/Files/AddRunLumi.py

this is the higher level code that starts all these insertions, where we can see that top level subscription was successfully created (thus the db transaction had been committed!!!):
https://github.com/dmwm/WMCore/blob/1.1.8_wmagent/src/python/WMCore/WorkQueue/WorkQueue.py#L449

@ticoann can you please take some time and have a look at this issue and my findings? I'm happy to know that I'm wrong and I missed a subtle detail, unfortunately I cannot see anything wrong in the code nor in the logs.

Then we can see how to manually fix this (these?) cases.

**Comment by amaltaro** [comment]
And I have a conceptual comment, even though code-wise it seems to be correct.

I can't make much sense of this code
https://github.com/dmwm/WMCore/blob/1.1.8_wmagent/src/python/WMCore/WorkQueue/WMBSHelper.py#L438

haven't we started a new transaction object a few lines above? Thus, I'd expect `existingTransaction` to be True, (problem is that it would not commit anything in that case).

It seems this code should instead be
```
        existingTransaction = self.beginTransaction()
...
        self.commitTransaction(existingTransaction)
```

however, if there is a transaction on going (e.g. myThread.transaction.transaction != None), `existingTransaction` would be True and again, a commit would be triggered only by the highest level class which initiated this `beginTransaction()`, IF called from there.

Am I missing anything?

**Comment by ticoann** [comment]
>      existingTransaction = self.beginTransaction()
> ...
>       self.commitTransaction(existingTransaction)

Alan, you are right. The code should be above.  I think it was mistake. 
But since this should be (is) a top level function, maybe someone want to make sure it commits.
I would change the code for clarity.

**Comment by vlimant** [comment]
what can we do in the short term to release the missing jobs ?

**Comment by hufnagel** [comment]
Retrieve the run/lumi for the affected files from DBS, then insert the missing run/lumi database records in WMBS. Next job splitter data discovery should find it. @amaltaro , do you agree ?

**Comment by amaltaro** [comment]
Yes, I'll try this procedure for that one file/workflow. If things go well, then we'll have to see how many we're missing and automatically fetch/insert the missing info.
Sorry, I had the pleasure to be stuck in the car for the whole morning...

**Comment by amaltaro** [comment]
@vlimant the agent had only that file without the run/lumi map. I manually inserted it, the job was created and that workflow is now announced.

**Comment by vlimant** [comment]
is there a way to detect other such cases ?
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_B2G-RunIISummer16NanoAOD-01730__v1_T_180228_041828_870
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_B2G-RunIISummer16NanoAOD-01233__v1_T_180227_201834_636
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_B2G-RunIISummer16NanoAOD-01180__v1_T_180228_001820_2891
look stalled

**Comment by vlimant** [comment]
there are several others with same stalling apparent behavior that can be spotted visually, let me know if you find a way to track them all down

**Comment by ticoann** [comment]
It seem above workflows are stuck with different reason than Alan described.

It merge task create the job but not yet submitted. (Not sure why)
/pdmvserv_task_B2G-RunIISummer16NanoAOD-01730__v1_T_180228_041828_870/B2G-RunIISummer16NanoAOD-01730_0/B2G-RunIISummer16NanoAOD-01730_0MergeNANOEDMAODSIMoutput


http://vocms0253.cern.ch:5984/wmagent_jobdump%2Fjobs/_design/JobDump/_show/jobSummary/500188


Task: /pdmvserv_task_B2G-RunIISummer16NanoAOD-01730__v1_T_180228_041828_870/B2G-RunIISummer16NanoAOD-01730_0/LogCollectForB2G-RunIISummer16NanoAOD-01730_0

http://vocms0253.cern.ch:5984/wmagent_jobdump%2Fjobs/_design/JobDump/_show/jobSummary/486630

I will investigate

**Comment by amaltaro** [comment]
Seangchan, for the case you looked up, that processing job ran at T1_US_FNAL, so the merge and logCollect jobs are waiting to run there. Problem is that FNAL has more jobs pending than the number of slots
```
cmst1@vocms0253:/data/srv/wmagent/current $ $manage execute-agent wmagent-resource-control --site-name=T1_US_FNAL -p
T1_US_FNAL - 1843 running, 5012 pending, 18836 running slots total, 3531 pending slots total, Site is Normal:
...
```

that's why even these very high priority jobs haven't been submitted to condor yet.

Question is, why we have exceeded the site pending slots? Possible because the agent pulled higher priority work. I'm not sure whether late binding can contribute to it as well.

Coming back to the question whether we can track these no run/lumi information. I cooked this query and ran it on vocms0253, unless I made a mistake in the query, there are NO problematic files (missing the run/lumi map).
```
SQL> SELECT DISTINCT avail.fileid
FROM wmbs_sub_files_available avail
  INNER JOIN wmbs_file_details details
    ON avail.fileid = details.id 
  LEFT JOIN wmbs_file_runlumi_map map
    ON avail.fileid = map.fileid
WHERE
  map.fileid IS NULL AND
  details.lfn not like '%logArchive.tar.gz%';  2    3    4    5    6    7    8    9  

no rows selected
```

**Comment by amaltaro** [comment]
BTW, I've just checked all the other agents in drain and there are no cases of files without run/lumi map. Which makes it very unlikely to be a bug in the WMCore code btw...

**Comment by vlimant** [comment]
apologies for dumping an unrelated set of workflow in the issue. good if no other such cases are in no other agents (did you check also the running ones?)

**Comment by amaltaro** [comment]
Yep, it's all good!

**Comment by ticoann** [comment]
Thanks Alan for checking this one but don't work while you are on vacation.

**Comment by ticoann** [comment]
> that's why even these very high priority jobs haven't been submitted to condor yet.
> 
> Question is, why we have exceeded the site pending slots? Possible because the agent pulled higher priority work. I'm not sure whether late binding can contribute to it as well.

It seems there are a lot of higher priority jobs running on FNAL but I haven't specifically checked for the merge job. Anyway, if it is the real problem, I will create the separate issue.
