### ISSUE TITLE
Still running jobs at a site that has been in the waiting room for 2 wks

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#8336]
T2_RU_INR  has been in the waiting room for ~2wks, yet we are still running jobs for 
vlimant_task_MUO-RunIIFall17GS-00013__v1_T_171030_094645_4523
there that are failing.  If a site is in the waiting room we should not be attempting to run jobs there, there are other sites in the whitelist that we could be using.

Jen

**Comment by amaltaro** [comment]
From the AgentStatusWatcher logs (vocms0254), this site went into drain mode on:
`2017-11-02 06:11:12,365:140634461931264:INFO:ResourceControlUpdater:Changing T2_RU_INR state from Normal to Draining`

and it was set back to normal today
`2017-11-16 06:15:58,137:139796979365632:INFO:ResourceControlUpdater:Changing T2_RU_INR state from Draining to Normal`

dashboard metrics also confirm this site is production enabled:
http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=237&batch=1&lastdata=1

Jen, please follow this up with the SS team. The agent is doing what it's supposed to do, closing it ;)

**Comment by jenimal** [comment]
We had jobs running during the time that the site was in the waiting room:
https://cmsweb.cern.ch/wmarchive/web/performance?metrics[]=jobstate&axes[]=host&axes[]=jobstate&axes[]=site&start_date=20171109&end_date=20171114&aggDB=aggregated&aggCol=day&site=T2_RU_INR

@mapsacosta@gmail.com

**Comment by mapsacosta** [comment]
Hi Alan,

As an example, this query [1] from dashboard from 11/13 to 11/15 (Timeframe in which the site was still in the WR) has lots of aborted/failed production jobs.

[1] http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=T2_RU_INR&submissiontool=&application=&activity=&status=&check=submitted&tier=&date1=2017-11-13+18%3A05&date2=2017-11-15+12%3A05&sortby=activity&scale=linear&bars=20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

**Comment by amaltaro** [comment]
I see some jobs submitted from vocms0252, though I'm not sure whether those were Production/Processing jobs or merge/logcollect/cleanup.

Mind that the following job types can still be submitted to a site in drain:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L340

**Comment by jenimal** [comment]
OK we are seeing this again, with the following workflow:
vlimant_task_BPH-Summer12-00255__v1_T_171102_104929_2376
This is a low priority workflow: 63000 
That was submitted in 171102, before CNAF had it's meltdown.  Now CNAF has been down for a LONG time: 
http://cmssst.web.cern.ch/cmssst/siteStatus/detail.html?site=T1_IT_CNAF
but now we are submitting jobs to them and of course they are failing miserably, 92, file read errors.  
How do we shut off the site so that the jobs get retried at other sites and can succeed before Paola has a big mess to clean up?

**Comment by amaltaro** [comment]
Jen, CNAF was a problem with Unified/JobRouter. Jean-Roch found the problem a day or two ago and fixed it.

**Comment by jenimal** [comment]
So we are filtering through all the jobs that are were submitted 2 days ago?  We are still seeing active errors.

**Comment by amaltaro** [comment]
Perhaps because jobs took a long time in the pending queue? You better check with the P&R team and also with Jean-Roch to see if anything was done. It wasn't the agent submitting them, so nothing we can do :)

**Comment by mapsacosta** [comment]
Thanks for the acclaration Alan.. but I still have a question.. at [1] I see 14K aborted, 3K running all of them **submitted** today Feb 7th. 

One of those jobs, for example, tried to run 3 times at CNAF without succeeding 

jobcooloff: 2018/2/7 (Wed) 09:50:48 UTC, T1_IT_CNAF
jobcooloff: 2018/2/7 (Wed) 11:11:16 UTC, T1_IT_CNAF
jobcooloff: 2018/2/7 (Wed) 14:20:48 UTC, T1_IT_CNAF

So are these "leftovers" from the Unified/JobRouter issue? or is it still happening? @vlimant  

[1] http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=T1_IT_CNAF&submissiontool=&application=&activity=&status=&check=submitted&tier=&date1=2018-02-07+10%3A40&date2=2018-02-07+16%3A38&sortby=activity&scale=linear&bars=20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

**Comment by vlimant** [comment]
@mapsacosta several things were there. the jobrouting code was not updating to the right gh repo on the fnal agents ; fixed by Farrukh. the rules were using the extended list of sites, as per Brian implmentation and indeed used sites in drain ; fixed https://github.com/CMSCompOps/WmAgentScripts/pull/259
