### ISSUE TITLE
Fix unified transferor unstable unit tests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8346]
WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t.TransferorTest:testRequestManager changed from success to error
WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t.TransferorTest:testRequestManagerAutomation changed from success to failure

**Comment by vkuznet** [comment]
Can you put pointer to the actual log. The test relies on phedex data-service, so it may be fragile depending on data availability. I need to see the actual log with failure to understand the reason.

**Comment by amaltaro** [comment]
Valentin, I'm getting these failures in an opportunistic mode, since it fails from time to time. I've just found logs for `testRequestManager` test, this was the error:
```
Error Message

{'datasets': [u'/QCD_HT500to700_BGenFilter_TuneCP5_13TeV-madgraph-pythia8/RunIIF [truncated]... != {}
+ {}
- {'datasets': [u'/QCD_HT500to700_BGenFilter_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17wmLHEGS-93X_mc2017_realistic_v3-v1/GEN-SIM'],
-  'name': 'req1',
-  'sites': [u'T1_US_FNAL_Disk']}
```

in case you want to see full logs, have a look at:
https://cmssdt.cern.ch/jenkins/view/DMWM/job/DMWM-WMCore-PR-test/lastCompletedBuild/testReport/WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t/TransferorTest/testRequestManager/

though it will vanish some time in the coming days/weeks.

**Comment by amaltaro** [comment]
Log for the second test failure:
https://cmssdt.cern.ch/jenkins/job/DMWM-WMCore-PR-test/6551/testReport/junit/WMCore_t.Services_t.MicroService_t.Unified_t.Transferor_t/TransferorTest/testRequestManagerAutomation/

also to be deleted anytime in the comind days/weeks.

**Comment by vkuznet** [comment]
Alan, Seangchan,
could you please tell me if jenkins node provides X509 environment setup?
By inspecting the log I see that
```
requests': {'key': None, 'endpoint':
'https://cmsweb.cern.ch/phedex/datasvc/json/prod/', 'timeout': 300,
'req_cache_path': '/tmp/.wmcore_cache_nFGG8D/cmsweb.cern.ch/.cache',
'cachepath': '/tmp/.wmcore_cache_nFGG8D/cmsweb.cern.ch', 'cert': None,
'cacheduration': 0, 'host': 'https://cmsweb.cern.ch/phedex/datasvc/json/prod/',
'capath': None, ...
```
so the both key and cert are set to None. It means that http calls will fail
to PhEDEx data-service since it requires certificates. But it is unclear
to me if this is the case since tests fails time to time. I also see cachepath
which may cause it. So my question is how jenkins setup cachepath and x509?
Can we run test without cachepath?

Best,
Valentin.

**Comment by amaltaro** [comment]
We should mock all those phedex calls not to have unit tests calling the real data-services.
Valentin, I think it's going to be easier if Seangchan or I fix it (eventually)...

**Comment by vkuznet** [comment]
I totally agree, do you have mock class for PhEDEx?
Basically I need subscriptions API.

**Comment by vkuznet** [comment]
Alan, Seangchan,
I made a PhEDExMock class to imitate PhEDEx subscription by using actual phedex
data. Please have a look into https://github.com/dmwm/WMCore/pull/8359
It should fix the unit test problem here.
Best,
Valentin.

**Comment by vkuznet** [comment]
Well, the class didn't support the group parameter which I used in my unit tests.
Therefore, I modified MockPhEDExApi code to provide this functionality and then I was able to
use it. Please review https://github.com/dmwm/WMCore/pull/8359
and let me know if you want to proceed with it.

**Comment by ticoann** [comment]
I see now. One thing is that you don't have to explicitly pass the mock PhEDEx. I will comments directly on the #8359

**Comment by vkuznet** [comment]
Seangchan, 
just a reminder that you need to provide feedback directly in #8359.

**Comment by ticoann** [comment]
Closing it
