### ISSUE TITLE
dashboard report CE need to be fixed - wmagent reporting site name as CE

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8355]
Stephen requested

**Comment by amaltaro** [comment]
@vytjan Vytas is willing to have a look at this issue :)

**Comment by roksys** [comment]
Hi,

We found some WNs reported as CE, probably it is related issue.

http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=unknown&submissiontool=&application=&activity=reprocessing&status=&check=submitted&tier=&date1=2018-05-28+09%3A11&date2=2018-05-30+09%3A11&sortby=ce&scale=linear&bars=20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

**Comment by amaltaro** [comment]
@vytjan Vytas, if you're too busy with T0 developments, I can either assign it to someone else or move it to a later milestone. Please let me know what you prefer.

**Comment by amaltaro** [comment]
The CE information is likely useful not only for the dashboard monitoring, but for the current MonIT/grafana/kibana too. So I think we should fix and keep that functionality around.

@goughes given that you have access to the worker nodes and whatnot, it looks a good candidate for you.

**Comment by khurtado** [comment]
Just to paste what we discussed during today's meeting regarding the CE.

The classad: `GLIDEIN_Gatekeeper` has the CE name for a site. This is available in the machine classads of the pilots.

If we want to send the CE with the job ads in Kibana, then adding that attribute here:
https://github.com/dmwm/WMCore/blob/38b41a51be0ac5d22ff6f867bddca5371b4f462e/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L536

Should pass the Gatekeeper that into the job classads (with the name: `MachineAttrGLIDEIN_Gatekeeper0`), which should be populated by ElasticSearch/Kibana then.

**Comment by goughes** [comment]
@khurtado Let me know if #9352 looks right to you. Do I need to do anything with the `JobAdInformationAttrs` on lines 537 and 538? https://github.com/dmwm/WMCore/blob/38b41a51be0ac5d22ff6f867bddca5371b4f462e/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L537

**Comment by khurtado** [comment]
@goughes It looks good to me in terms of code. Testing would be necessary to double check ES  indeed starts storing that attribute. `JobAdInformationAttrs` is related to attributes written the job event logfile in condor if I recall, so nothing related to ES.
