### ISSUE TITLE
need to setup valid certificate for microservice

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#8370]
The newly deployed microservice is responding on cmsweb-testbed, e.g.
```
scurl https://cmsweb-testbed.cern.ch/microservice/data/status
{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}
```
but I can't place post request to query WQ, e.g.
```
scurl -X POST -H "Content-type: application/json" -d '{"request":{"process":"assignment-approved"}}'
https://cmsweb-testbed.cern.ch/microservice/data
```
produces the following traceback
```
[29/Nov/2017:13:30:42] vocms0131.cern.ch 128.142.137.213 "POST /microservice/data HTTP/1.1" 200 OK [data: 4299 in
42 out 392722 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y
Kuznetsov" "" ] [ref: "" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18
libssh2/1.4.2" ]
Traceback (most recent call last):
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/MicroSe
rvice/Unified/TaskManager.py", line 130, in run
    func(*args, **kwargs)
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/MicroSe
rvice/Unified/Transferor.py", line 216, in process
    requests = requestsInfo(state)
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/MicroSe
rvice/Unified/RequestInfo.py", line 385, in requestsInfo
    requestJobs = workqueueRequests(state)
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/MicroSe
rvice/Unified/RequestInfo.py", line 372, in workqueueRequests
    data = mgr.getdata(url, params=params, headers=headers, cert=cert(), ckey=ckey())
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/pycurl_
manager.py", line 262, in getdata
    verbose=verbose, ckey=ckey, cert=cert, doseq=doseq, cookie=cookie)
  File
"/data/srv/beHG1712b/sw/slc6_amd64_gcc493/cms/reqmgr2ms/0.0.2/lib/python2.7/site-packages/WMCore/Services/pycurl_
manager.py", line 252, in request
    raise exc
HTTPException:
url=https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_view/jobsByRequest?group=true&reduce=true,
code=403, reason=Forbidden, headers={'Date': 'Wed, 29 Nov 2017 12:30:42 GMT', 'Transfer-Encoding': 'chunked',
'Content-Type': 'text/html', 'CMS-Server-Time': 'D=3028 t=1511958642511950', 'Server': 'Apache'
```

So, my question is how do we need to configure microservice that it will be
allowed to query WQ and ReqMgr2? My understanding that we need a valid proxy or
host certificate but it looks like it is not the case on microservice backend
(vocms0131).

**Comment by h4d4** [comment]
Checking the services that use dmwm-service-key.pem and dmwm-service-cert.pem

`cfg]$ grep -rn dmwm-service- ./* | grep manage`
/acdcserver/acdcserver_manage:45:  if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then 
./acdcserver/acdcserver_manage:46:    export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem 
./acdcserver/acdcserver_manage:47:    export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./crabcache/manage:39:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./crabcache/manage:40:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./crabcache/manage:41:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./crabserver/manage:39:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./crabserver/manage:40:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./crabserver/manage:41:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./reqmgr/manage:48:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./reqmgr/manage:49:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./reqmgr/manage:50:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./reqmgr2/manage:50:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./reqmgr2/manage:51:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./reqmgr2/manage:52:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./reqmgr2ms/manage:50:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./reqmgr2ms/manage:51:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./reqmgr2ms/manage:52:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./reqmon/manage:48:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./reqmon/manage:49:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./reqmon/manage:50:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./t0_reqmon/manage:48:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./t0_reqmon/manage:49:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./t0_reqmon/manage:50:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
./workqueue/manage:51:if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
./workqueue/manage:52:  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
./workqueue/manage:53:  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem

I found that excepting reqmgr2ms all services have those certificates copied in its 
/data/srv/current/auth/ directory

`ls -l /data/srv/current/auth/`
total 84
drwxr-x---. 2 cmsweb _acdcserver   4096 Dec  9  2016 acdcserver
drwxr-x---. 2 cmsweb _bigcouch     4096 Dec  9  2016 bigcouch
drwxr-x---. 2 cmsweb _confdb       4096 Dec  9  2016 confdb
drwxr-x---. 2 cmsweb _couchdb      4096 Dec  9  2016 couchdb
drwxr-x---. 2 cmsweb _crabserver   4096 Dec  9  2016 crabserver
drwxr-x---. 2 cmsweb _dbs          4096 Dec  9  2016 dbs
drwxr-x---. 2 cmsweb _dbsmigration 4096 Dec  9  2016 dbsmigration
drwxr-x---. 2 cmsweb _dmwmmon      4096 Dec  9  2016 dmwmmon
drwxr-x---. 2 cmsweb _dqmgui       4096 Dec  9  2016 dqmgui
drwxr-x---. 2 cmsweb _phedex       4096 Dec  9  2016 phedex
drwxr-x---. 2 cmsweb _popdbweb     4096 Dec  9  2016 popdbweb
drwxrwx---. 2 cmsweb _config       4096 Nov 29 18:03 proxy
drwxr-x---. 2 cmsweb _reqmgr       4096 Dec  9  2016 reqmgr
drwxr-x---. 2 cmsweb _reqmgr2      4096 Dec  9  2016 reqmgr2
drwxr-x---. 2 cmsweb _reqmon       4096 Dec  9  2016 reqmon
drwxr-x---. 2 cmsweb _sitedb       4096 Mar 17  2017 sitedb
drwxr-x---. 2 cmsweb _t0_reqmon    4096 Dec  9  2016 t0_reqmon
drwxr-x---. 2 cmsweb _t0wmadatasvc 4096 Feb 13  2017 t0wmadatasvc
drwxr-x---. 2 cmsweb _victorweb    4096 Dec  9  2016 victorweb
drwxr-x---. 2 cmsweb _config       4096 Dec  9  2016 wmcore-auth
drwxr-x---. 2 cmsweb _workqueue    4096 Dec  9  2016 workqueue

Additionally, even when /data/cfg/reqmgr2ms/manage points to the 
AUTHDIR=$TOP/current/auth/reqmgr2 when the certificates are, 
I saw that the owner and group of /data/srv/current/auth/reqmgr2 are cmsweb and _reqmgr2.

`drwxr-x---. 2 cmsweb _reqmgr2      4096 Dec  9  2016 reqmgr2`

And _reqmgr2ms are not into the reqmgr2 group.
`cat /etc/group | grep reqmgr2
_reqmgr2:x:100048:cmsweb
`

So, this could be affecting the access to dmwcore certificates.

I also, checked that reqmgr2ms user are into the group _config.
`cat /etc/group | grep config
_config:x:100000:_confdb,_couchdb,_empty,_bigcouch,_auth,_config,_phedex,_sitedb,_dqmgui,_gitweb,_reqmon,_mongodb,_dmwmmon,_das,_dbs,_workqueue,_t0_reqmon,_popdbweb,_sw,_crabserver,_reqmgr,_t0wmadatasvc,_frontend,_crabcache,_overview,_reqmgr2,_acdcserver,_dbsmigration,_victorweb,cmsweb,_admin,_reqmgr2ms
`

Then, I think that we can try creating the certificate directory for 
reqmgr2ms into /data/srv/current/auth/ and copied wmcore certificates there.

**Comment by vkuznet** [comment]
@h4d4 Lina, could you then change manually the following
- create reqmgr2ms area in /data/srv/current/auth/ with proper permissions
- copy certs over there
- assign reqmgr2ms group to this area
- change reqmgr2ms manage script to set AUTHDIR=$TOP/current/auth/reqmgr2ms
- then restart the service and let us know
Then I can try to test if requests are coming through.
Thanks,
Valentin.

**Comment by h4d4** [comment]
@vkuznet I did the changes, please test and let me know how it's going.
Thnaks, Lina.

**Comment by vkuznet** [comment]
Lina,
something is not right. I still get the same error. Could you please list
/data/srv/current/auth/reqmgr2ms area since I don't have permission. Also let me know
if you restarted the service? And, it would be easier to debug if you'll
just add printouts to reqmgr2ms/manage script, e.g.
echo "$X509_USER_KEY"
echo "$X509_USER_CERT"
after they're setup (after if block where they set).
Please report here.

Best,
Valentin.

**Comment by amaltaro** [comment]
Valentin, I think we should test it ourselves and only ask Lina if we really cannot catch these problems in dev.

**Comment by vkuznet** [comment]
Alan,
I'll be happy to do it if I either get spare VM or somebody give me proper
certificates, on my VM I have:

```
sudo -H -u _reqmgr2ms bashs -l -c "curl --cert /data/srv/current/auth/reqmgr2ms/dmwm-service-cert.pem --key /data/srv/current/auth/reqmgr2ms/dmwm-service-key.pem https://cmsweb.cern.ch/sitedb"
curl: (58) unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)
```

**Comment by amaltaro** [comment]
If you need more developments VM in your openstack personal project, then you should contact Daniel (VOC) and ask for it. Since you work on several different projects, I don't think they would deny your request :)

About these pem files. Are you using a real service certificate (or your proxy file)? Or is it just a fake file created during the deployment? Or is it in the cmsweb-testbed backend (needless to say, that is NOT the purpose of cmsweb-testbed...)?

**Comment by h4d4** [comment]
@vkuznet 
In case that this can help:

Below the current status of /data/srv/current/auth/reqmgr2ms

`ls -lash /data/srv/current/auth/ | grep reqmgr2ms`
4.0K drwxr-x---.  2 cmsweb _reqmgr2ms    4.0K Nov 30 11:32 reqmgr2ms

`ls -lash /data/srv/current/auth/reqmgr2ms`
total 16K
4.0K drwxr-x---.  2 cmsweb _reqmgr2ms 4.0K Nov 30 11:32 .
4.0K drwxr-x---. 24 cmsweb _config    4.0K Nov 30 11:25 ..
4.0K -r--r-----.  1 cmsweb _reqmgr2ms 3.0K Nov 30 11:32 dmwm-service-cert.pem
4.0K -r--r-----.  1 cmsweb _reqmgr2ms 1.7K Nov 30 11:32 dmwm-service-key.pem

And below the value for the variables $AUTHDIR, $X509_USER_KEY, $X509_USER_CERT, set into /data/srv/current/config/reqmgr2ms/manage
`[cmsweb@vocms0131 auth]$ less /data/srv/current/config/reqmgr2ms/manage | grep  AUTHDIR`
AUTHDIR=$TOP/current/auth/reqmgr2ms

`[cmsweb@vocms0131 auth]$ less /data/srv/current/config/reqmgr2ms/manage | grep X509_USER_KEY`
export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem

`[cmsweb@vocms0131 auth]$ less /data/srv/current/config/reqmgr2ms/manage | grep X509_USER_CERT
`
[cmsweb@vocms0131 auth]$ less /data/srv/current/config/reqmgr2ms/manage | grep X509_USER_CERT

I also restarted the service.

Best Regards, Lina.

**Comment by vkuznet** [comment]
ok, I tested service in my VM using my personal certificates which I placed
in /data/srv/current/auth/reqmgr2ms/ area as
```
/data/srv/current/auth/reqmgr2ms/dmwm-service-key.pem
/data/srv/current/auth/reqmgr2ms/dmwm-service-cert.pem
```
With this setup everything works. Here is PR for manage script changes
which I requested Lina to already apply for cmsweb-testbed:
https://github.com/dmwm/deployment/pull/566
With this change everything works in my VM (!!!).

Now, on cmsweb-testbed there is somewhere misconfiguration since now I even
can't access the service. The following call
```
scurl https://cmsweb-testbed.cern.ch/microservice/data/status
```
worked (here scurl is an alias to curl --key mykey --cert mycert)
and now it stopped working. The original output was
```
{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}
```
and now I'm getting
```
The site you requested is not available.</p><p>CMS <a href='https://twiki.cern.ch/twiki/bin/view/CMS/ScheduledInterventions'>scheduled interventions page</a> lists planned CMS and CERN service downtimes and known site-wide computing system incidents. Planned updates are notified on the <a href='https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce.html'>CERN computing announcements</a> forum.</p><p>Would you please be so kind and <a href='https://ggus.eu/?mode=ticket_cms'>create a ticket</a> to"CMS Web Tools" support unit</a> if this interruption was unexpected?</p>
```

It is obvious misbehavior of cmsweb-testbed frontend. But I can't check it since
I don't have permission to cmsweb-testebed frontend nodes (vocms0134|vocms0135).

@h4d4, Lina, sorry but your help to resolve this issue is required.

Either provide me access to cmsweb-testbed frontends that I can see why requests
are failing or do it yourself via
```
curl -k --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem https://cmsweb-testbed.cern.ch/microservice/data/status
```
call which should work since service is running on backend.

**Comment by ticoann** [comment]
Lina, For the initial permission problem, what is the cert DN reqmgr2ms is using? If it is the same as other services in cmsweb it should have following group and role in sitedb. 
"facops", "web-service"

https://github.com/dmwm/WMCore/blob/master/src/couchapps/WorkQueue/validate_doc_update.js#L18

**Comment by h4d4** [comment]
@vkuznet I've given you access to vocms0134 and vocms0135 the testbed fronted machines

**Comment by vkuznet** [comment]
Lina,
here is the issue:
- the frontend yields 503 (HTTP Service unavailable) error
[30/Nov/2017:16:21:55 +0100] cmsweb-testbed.cern.ch 128.142.137.213 "GET /microservice/data/status HTTP/1.1" 503 [data: 5919 in 18003 out 1359 body 21556 us ] [auth: TLSv1.2 DHE-RSA-AES128-GCM-SHA256 "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov" "-" ] [ref: "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2" ]
- the backend complains about authz that front-end not present proper headers
[30/Nov/2017:18:19:13]  ERROR: authz denied, front-end headers not present
- and the backend allows monitoring call
[30/Nov/2017:18:19:28] vocms0131.cern.ch 127.0.0.1 "GET /microservice/data/status HTTP/1.1" 200 OK [data: 344 in 104 out 956 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
- but it does not allow my local curl call
[30/Nov/2017:18:19:13] vocms0131.cern.ch 127.0.0.1 "GET /microservice/data/status HTTP/1.1" 403 Forbidden [data: 191 in 751 out 684 us ] [auth: - "" "" ] [ref: "" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2" ]
Please note that the last two are identical in terms of calls the only
difference is that one comes from a monitoring daemon and another from my curl
call.

I think it is permission problem somewhere on backend.

Can we restart the service again. I want to see if local curl call will pass
through after fresh restart.

Thanks,
Valentin.

**Comment by h4d4** [comment]
@vkuznet Hello Valentin I've just restart the service.
Best regards, Lina.

**Comment by vkuznet** [comment]
Lina,
I doubt that you restarted proper one.
According to vocms0131:/data/srv/logs/reqmgr2ms/reqmgr2ms-20171130.log
the reqmgr2ms data-service last time was restarted at 30/Nov/2017:14:35:54

So, I don't know what you restarted but certainly it is not what I'm looking for.

Please provide details and check that you indeed restart reqmgr2ms on vocms0131.
Thanks,
Valentin.

**Comment by vkuznet** [comment]
Now I think I understand what's going on. It seems to me we had two instances running on vocms0131. One feed /data/srv/logs/reqmgr2ms/reqmgr2ms-20171130.log log and it ended at 30/Nov/2017:19:38:10 and another feed /data/srv/logs/reqmgr2ms/reqmgr2-20171130.log which still runs. According to first log it was killed, then the second instance was allowed to run. Even though I don't know how in this case the ports were handled. 

I think that's it's partially my fault since I asked Lina to manually change things and at the end we end-up with different logs and messy situation. Sorry for that.

Anyhow, I created PR: https://github.com/dmwm/deployment/pull/566 which I suggest Lina will merge and deploy again the service with it. It addresses missing Unified config files and contains proper log names, X509 settings, etc.

Lina, can you do that? It would be nice to remove logs from /data/srv/logs/reqmgr2ms/ to avoid further confusion.

Let me know.

**Comment by h4d4** [comment]
@vkuznet 
Hello Valentin,
for now I deleted the reqmgr2ms logs, let me review the changes to redeploy it.
I'll keep you posted.
Best Regards, Lina.

**Comment by vkuznet** [comment]
@h4d4 Lina, did you get chance to work on reqmgr2ms issue. I tried again and I can't pass the frontend. Here is frontend entry for this call `https://cmsweb-testbed.cern.ch/microservice/data/status`
```
[07/Dec/2017:16:29:49 +0100] cmsweb-testbed.cern.ch 2001:1458:201:a4::100:17a "GET /microservice/data/status HTTP/1.1" 503 [data: 5919 in 18002 out 1359 body 7010 us ] [auth: TLSv1.2 DHE-RSA-AES128-GCM-SHA256 "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov" "-" ] [ref: "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2" ]
```
and here is what back end says:
```
[07/Dec/2017:16:30:42]  ERROR: authz denied, front-end headers not present
[07/Dec/2017:16:30:42] vocms0131.cern.ch 127.0.0.1 "GET /microservice/data/status HTTP/1.1" 403 Forbidden [data: 191 in 751 out 23522 us ] [auth: - "" "" ] [ref: "" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2" ]
```

To me it is issue with frontend configuration.

**Comment by ticoann** [comment]
@h4d4  LIna, did you fix anything?
It seems it is working for me.

https://cmsweb-testbed.cern.ch/microservice/data/status

{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}

https://cmsweb-testbed.cern.ch/microservice/data

{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}

@vkuznet, Valentin, Are they (2 REST apis above) supposed to give the same result?

One weird thing is initially it gave me Service unavailable but by resending it I can get the reply.

**Comment by vkuznet** [comment]
Hi,
yes service is working, but I think it is configured to talk to 2 backends
as reqmgr2 and only one backend has it. Therefore time to time due to round
robin we hit a backend which does not have it.

But I did checked that when I hit proper backend I got correct behavior:
### getWorkflows: 49.6 sec
### dbsInfo: 22.5 sec
### phedexInfo: 11.0 sec
### eventsLumisInfo: 13.7 sec

So this is correct response on backend.

I think we agreed that it will only run on single backend and therefore
we'll need to adjust frontend rules correctly only to forward request to
specific backend.

Best,
Valentin.

**Comment by h4d4** [comment]
@vkuznet @ticoann 
Hello, 

Regarding to those Valentin's suggestions[1].
I merged the PR #566 that Valentin did, and deleted the reqmgr2ms logs as he proposed, but I not redeployed on testbed yet. Last Thursday was the Production upgrade, so I decide to wait for this redeploy in testbed. 
Then, I'll do it the next Monday. I'll let you know once the deployment is done.
Best Regards, Lina.

[1]
Anyhow, I created PR: dmwm/deployment#566 which I suggest Lina will merge and deploy again the service with it. It addresses missing Unified config files and contains proper log names, X509 settings, etc.
Lina, can you do that? It would be nice to remove logs from /data/srv/logs/reqmgr2ms/ to avoid further confusion.

**Comment by h4d4** [comment]
@vkuznet  

Hello Valentin,

I've re-deployed on testbed including the PR #566.
I've also create reqmgr2ms area in /data/srv/current/auth/ with proper permissions, including the dmwm certificates.

This is the part of the output when reqmgr2ms starts[1]

When I do:
https://cmsweb-testbed.cern.ch/microservice/data/status
I got:
{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}

When I do 
https://cmsweb-testbed.cern.ch/microservice/data:

I got:
{"result": [
 {"microservice": "UnifiedTransferorManager", "request": {}, "results": {"status": {}}}
]}

Please, test it and let me know how it's going.

Best Regards, Lina.

[1]
starting reqmgr2ms
X509_USER_CERT=/data/srv/current/auth/reqmgr2ms/dmwm-service-cert.pem
X509_USER_KEY=/data/srv/current/auth/reqmgr2ms/dmwm-service-key.pem

**Comment by vkuznet** [comment]
Lina,
thanks, now as far as I can tell everything work as expected. I was able to
query the service via GET request as you shown and also placed a POST request.
We can close the ticket.
Thanks again for your help.
Best,
Valentin.
