### ISSUE TITLE
Lock on secondary / query not functioning

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8384]
neither https://cmsweb.cern.ch/reqmgr2/data/request?mask=RequestDate&mask=MCPileup&status=normal-archived&detail=false nor https://cmsweb.cern.ch/reqmgr2/data/request?mask=RequestDate&mask=MCPileup&status=normal-archived works, I need to know what/when the secondary were used.
Is there a way to get directly a dictionnary of the form 
{ <Dataset name> : <date of creation of the last workflow that had it in any MCPileup> }

**Comment by ticoann** [comment]
Hi Jean-Roch,  reqmgr2 API doesn't allow get whole archived data and mask against that.  (There are simply too much data and not feasible to handle that).
Do you have any other parameters known other then status, i.e. campaign, input dataset, etc)

https://github.com/dmwm/WMCore/wiki/reqmgr2-apis

If you are searching none archive data wmstaserver api is faster, but in this case it seems you are looking for the archived data.
https://github.com/dmwm/WMCore/wiki/wmstatsserver-api

We cannot add api retrieving all archived data but If it is desired we can add date range, probably you have to query by month. Let us know what alternative API you need for this case.

**Comment by vlimant** [comment]
if one could add  

since=30

and get the data since 30 days, this would probably be enough.
or https://github.com/dmwm/WMCore/issues/7651 could be complete, or @yiiyama confirms we do not need the locks be made through unified. Either of the three would work for me.

at the moment, secondary inputs are not fully protected because of this

**Comment by ticoann** [comment]
we can add "since" query with archived status and limit 60 days at a time.
I was just curious what is the logic behind 1 or 2 month checking workflows for secondary dataset (Pileup)?

**Comment by vlimant** [comment]
@ticoann we want to lock the secondary input of any workflow that is less than 1 month old, as a way to keep that secondary on disk for at least 1 month after the last actual use

**Comment by vlimant** [comment]
found a work around to lock secondary, using Unified configuration. not good in the long run.

**Comment by amaltaro** [comment]
Closing this issue in favor of an API for locking data (or in favor of developments along the Rucio transition).
