### ISSUE TITLE
Multicore in assigning ACDC of ACDC

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8392]
looking at 
https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_task_SMP-PhaseIITDRFall17wmLHEGS-00030__v1_T_171103_204004_8254
https://cmsweb.cern.ch/reqmgr2/config?name=mcremone_ACDC0_task_SMP-PhaseIITDRFall17wmLHEGS-00030__v1_T_171116_004028_825
https://cmsweb.cern.ch/reqmgr2/config?name=vlimant_ACDC1_task_SMP-PhaseIITDRFall17wmLHEGS-00030__v1_T_171122_180054_1020
https://cmsweb.cern.ch/reqmgr2/config?name=mcremone_ACDC2_task_SMP-PhaseIITDRFall17wmLHEGS-00030__v1_T_171213_210739_3479

it looks like ACDC0 maintained the numberOfCores = 8 in the spec, while the other ones switched to numberOfCores = 1

I cannot find any flaw in how things are assigned. From the logs of where the assignement was done, no Multicore parameter was passed on to the assign api, and yet numberOfCores = 1 even for the tasks that specify Multicore=8

somehow @ticoann @amaltaro the base directory value (set to 1 by default) is taken as the value that needs to go everywhere for ACDC of ACDC.

N.B. this is a showstopper for still cursed upgrade requests of highest priority.

FYI @prozober

**Comment by vlimant** [comment]
I allow myself to put urgent ops until I figure out a way to circumvent the problem and be able to make the last acdc for >10 upgrade requests of top priority

**Comment by ticoann** [comment]
Hmm, this should have been fixed by

https://github.com/dmwm/WMCore/pull/8286

Could you point me the script where the actual assignment is done. That will be helpful for debugging the issue.

**Comment by ticoann** [comment]
Actually, now I see what is wrong. I can create the patch but this will require cmsweb update. Meanwhile I maybe find the temporary solution on this. How is ACDC of ACDC is created and assigned?
@prozober, Paola are you using wmstats/reqmgr2 web interface or some script from WmAgentScript?

**Comment by prozober** [comment]
Hi @ticoann, actually we are creating ACDCs using Unified scripts. 
I think @areinsvo could please help us to provide the info we need, that is where the ACDCs are created and assigned.

**Comment by vlimant** [comment]
my 2 cents is that we should not touch actor to patch for this and run second++ ACDC by hand and assign with the multicore option of assign.py until the fix propagates to reqmgr.

**Comment by ticoann** [comment]
I think assign with mutilcore option would be fine. Any minimal changes will be preferred for temporary solution. We will fix the update in next reqmgr release.
