### ISSUE TITLE
Please add evironment variable in CMS jobs for frontier debugging

### ISSUE THREAD

**Issue by DrDaveD** [dmwm/WMCore#8399]
At at least one point in the past I am quite sure WMAgent used to do this, but I just looked at some job logs where it is clearly not set.  Please set and export the environment variable FRONTIER_LOG_LEVEL=warning for CMS jobs in a future release of WMAgent.

**Comment by ticoann** [comment]
@DrDaveD, I don't recall we have this environment variable set before. Anyway, we can add that. But I was wondering what is accessing this variable?

**Comment by ericvaandering** [comment]
Must be Frontier being run inside CMSSW

**Comment by ticoann** [comment]
In this case shouldn't CMSSW or Frontier set this then (which one is setting default value)? Or is it (warning level) only for the jobs run by Agents?

**Comment by DrDaveD** [comment]
Yes it is the frontier client running inside CMSSW.  We don't want these messages to show up when people run cmsRun interactively, but they are helpful for debugging job failures.  There's a current issue that it would have helped with debugging, and the messages have helped with debugging many problems in the past.
