### ISSUE TITLE
when CRAB ASO timeouts should return exit code 60317

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#8405]
see
https://github.com/dmwm/CRABServer/issues/5364
current code in 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py#L263-L265
returns 60321 which indicates site problem, while ASO timeout can be for other reasons as well. Should use the ad-hoc, already existing 60317

**Comment by belforte** [comment]
I will make a PR for this, but can't assign it

**Comment by ticoann** [comment]
Thanks Stefano

**Comment by amaltaro** [comment]
@belforte I see you fixed it in your private branch. Are you going to make a WMCore PR?

**Comment by belforte** [comment]
haven't got the chance to test that yet. Eventually I will make a PR
