### ISSUE TITLE
requested walltime is much less than 8h

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8411]
people from the cpu-eff task force were looking at inefficiencies from 

https://cms-gwmsmon.cern.ch/prodview/fabozzi_Run2017F-v1-BTagCSV-17Nov2017_940_171218_171845_1070

coming from too short jobs. The requested walltime is ranging 20-75 minutes.

cmst1@vocms0250:/afs/cern.ch/user/v/vlimant $ condor_q -const 'WMAgent_RequestName =="fabozzi_Run2017F-v1-BTagCSV-17Nov2017_940_171218_171845_1070"' -af  EstimatedSingleCoreMins OriginalMaxWallTimeMins MaxWallTimeMins  RequestCpus WMCore_ResizeJob | sort | uniq
175 20 20 8 false
300 37 37 8 false
325 40 40 8 false
350 42 42 8 false
350 45 45 8 false
400 50 50 8 false
425 75 75 8 false
450 75 75 8 false
475 75 75 8 false
500 75 75 8 false
750 75 75 8 false

even if time/event is wrongly estimated, the target requested walltime should be more in the 8h region than 1h.
What is the limiting factor for creating/requesting longer running jobs ?

BTW https://cms-gwmsmon.cern.ch/prodview/pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404 MC seems to have the same issue too.

**Comment by vlimant** [comment]
@ticoann @amaltaro this is very high on the list of things for management. so please help me understand what we are doing wrong here

**Comment by amaltaro** [comment]
Hmm, checking the job splitting settings for 
pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404 

I can't really see anything wrong, even though vocms0252 has two different job lengths for the first task:
```
cmst1@vocms0252:/data/srv/wmagent/current $ condor_q -const 'WMAgent_RequestName =="pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404"' -af WMAgent_SubTaskName EstimatedSingleCoreMins OriginalMaxWallTimeMins MaxWallTimeMins RequestCpus WMCore_ResizeJob | sort | uniq -c
  27130 /pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404/HIG-RunIIFall17wmLHEGS-00048_0 350 87 87 4 false
  46474 /pdmvserv_task_HIG-RunIIFall17wmLHEGS-00048__v1_T_180110_201332_6404/HIG-RunIIFall17wmLHEGS-00048_0 750 150 150 4 false
cmst1@vocms0252:/data/srv/wmagent/current $
```

the single core estimated time sounds reasonable (350 or 750min), but the final `MaxWallTimeMins` is set to 1 or 2.5h only. I suspect there is a logic problem in here, but how come we didn't spot it with the latest changes and tests done in the last round (a few months ago)..

**Comment by vlimant** [comment]
@amaltaro can you please check on the data reprocessing one ?

singlecoreestimate of 350-750 is not reasonable, because it is the range of 8h, but the job will run with 8 cores and therefore will run 8 times shorter. the logic in the condor plugin is to have MaxWallTimeMins be EstimatedSingleCoreMins /Requestcpus ; hence 350=>87=350/8

**Comment by vlimant** [comment]
question is : how is singlecoreestimate estimated ?

**Comment by vlimant** [comment]
BTW : the two different values 350 and 750 is because of unified tuning the value based on observation of successful jobs. all in all, not enough work is put in the jobs.
time/event underestimate is bad, of course, but regardless, the initial MaxWallTimeMins submitted by wmagent should be ~8h, *not* 1-2.5 h.

**Comment by amaltaro** [comment]
Before I proceed debugging the condor classads and the time set by the agent, how is unified tweaking these jobs? All via JobRouter (thus when it's submitted to condor)?
Is there any flag that I can see to figure out whether unified changed the original values or not? Having a pointer to the unified code would be a plus too.

**Comment by amaltaro** [comment]
and what is the original value? 750 or 350?

**Comment by vlimant** [comment]
the jobrouter rules are created via https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/go_condor.py running on the schedd, and feeding from https://vocms049.cern.ch/unified/public/equalizor.json 
the original value between 350 and 750 must be 350, as the rule always tries to set the requested walltime to higher value (to avoid jobs going over pilot boundary)

**Comment by vlimant** [comment]
nope, the condition is 
(target.HasBeenTimingTuned =!= true) || (target.EstimatedSingleCoreMins <= %d)
so either never tuned, or to be tuned to a bigger value

**Comment by amaltaro** [comment]
Ok, I think I found the problem, which is 
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobCreator/JobCreatorPoller.py#L116

Before doing anything, we need to work - once again - on the TimePerEvent definition. E.g. for 8 cores and TimePerEvent=5secs. Is TimePerEvent:
a) the time 8 cores "would take" to process 1 event? Thus in 5 secs we get 1 event, in 50 secs we get 10 events.
OR
b) the time 1 core would take to process 1 event? Thus, in 5 secs we get 8 events, in 50 secs we get 80 events.

??? @bbockelm @vlimant @ericvaandering 

Depending on the answer, it might be about time to resume the work done on this PR:
https://github.com/dmwm/WMCore/pull/6597/files or fix the JobCreatorPoller line.

**Comment by vlimant** [comment]
The convention in reqmgr is (a) timeperevent = (number of events processed) / (walltime of the job)
convention that is correct in the splitting, but indeed inconsistent in  

j['estimatedJobTime'] = min(j['estimatedJobTime']/(nCores * 0.8), constraints['MaxWallTimeSecs'])

**Comment by vlimant** [comment]
for example "events_per_job": 4800, is derived from "TimePerEvent": 6, in https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2017F-v1-BTagCSV-17Nov2017_940_171218_171845_1070 for example.
>>> (8*60*60) / 6
4800

**Comment by amaltaro** [comment]
FYI: https://github.com/dmwm/WMCore/wiki/TimePerEvent-convention

**Comment by vlimant** [comment]
How soon can we have #8415 in ? Looks like an agent component, so in theory we could have a patch, right ?

**Comment by amaltaro** [comment]
tomorrow
