### ISSUE TITLE
 WMAgent wrapper script exits non-zero if the last step in the job fails

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8422]
That is, exit non-zero in the case where the last CMSSW fails (but stageout succeeds) or stageout of non-logfile job outputs fails (and CMSSW succeeds).
 Effectively, anything that would trigger a retry in the agent.

**Comment by ticoann** [comment]
I am not sure whether this is still true. I will investigate

**Comment by bbockelm** [comment]
Thanks for opening this @ticoann !

Chris Jones reported finding such an example within the last week, so I suspect there are still corner cases out there.

One potential place to start (beyond reviewing the bash code!) is to look at condor_history and see if there's any cases where we exit code 0 but use condor_chirp to report a non-zero code from the FJR.  That might be one error path already closed, however...

**Comment by ticoann** [comment]
@Dr15Jones, Chris, do you still have example of this. I looked through the WMAgent code but I couldn't find the apparent place for this to happen. It will be helpful which exitCode and where the error occurred which end up reporting exitCode 0. Thanks.

**Comment by Dr15Jones** [comment]
I no longer have access to the example. I believe in the case I was looking at the framework job report from the framework was unparsable because the cmsRun job crashed before closing out the xml file.

**Comment by ticoann** [comment]
Hmm, that is weird it should set different exitCode than 0 when FWJR is available.
Chris, Thank you for the info. If you find another case please let me know.

**Comment by amaltaro** [comment]
While looking for something else in the steps classes, I think this is the place we'd have to propagate the exit code from to the job wrapper (of course, still running logArch step):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L236

**Comment by bbockelm** [comment]
Hi Alan -

Indeed, let's handle this one with a higher priority.  A lot of external systems look at the HTCondor exit code; it would be useful to make sure they are synchronized.

Brian

**Comment by bbockelm** [comment]
@amaltaro / @ticoann - this one remains high priority.  Is it being actively worked on?

**Comment by ticoann** [comment]
It is not actively worked on since last findings by Alan (20 days ago). I will look at the code Alan pointed.

**Comment by ticoann** [comment]
Unfortunately, I don't think below code is the problem.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L236

It seems it is correctly passed to here

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L251

And this is recorded in step error and reported to wmstats.

**Comment by amaltaro** [comment]
While reading this issue again, this is somehow tricky. WMAgent/WMStats checks the exit code of all the steps inside a job, and in case one of those has an exit code != 0, then the job gets that exit code assigned and it's marked as failed (unless it's a passable error/step).

On the other hand, HTCondor uses the chirped exit code from every step. How does it define whether a job with multiple steps has succeeded or not?

Seangchan, this is how the whole job gets ran from the very top level (wrapper):
https://github.com/dmwm/WMCore/blob/master/etc/submit.sh#L171

and it uses the return code from that call. That means we should be also returning the exit code here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Startup.py#L40

and then exiting this Startup script with something like `sys.exit(rc)`, such that the wrapper can also see it.
