### ISSUE TITLE
adding error code 8501 to the failing list

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8430]
since #8188 the special error code is 8501 and should not be retried

**Comment by amaltaro** [comment]
Jean-Roch, since you're seeing these errors, can you post the error message here, just for the record. Thanks

**Comment by ticoann** [comment]
@amaltaro, Alan, did you already update aux db for this, it seems it contains 8051.

**Comment by ticoann** [comment]
default value is updated in #8435
