### ISSUE TITLE
add a "held" status

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8431]
to get people to start thinking about this, medium-low priority, even though there is a way to hold workflows via jobrouter and unified, I think we should have this directly in reqmgr/agent.
a workflow in held should have no more job submitted. 
the pending jobs should either be edited with "something" that makes them unmatchable, or removed (condor_rm) from the queue.
the running jobs, we might decide to have them killed, and put back for resubmission.

an "unheld" status would be used later on transiently, and the status would go back to running/acquired/...

The goal is to be able to put a workflow "on hold" upon too many failures, then resume or reject (i.e. not reject right away, and give a chance to fix something)

**Comment by ticoann** [comment]
Is this the same issue as #8378?  If it is the same issue we can discuss it further there.

**Comment by ticoann** [comment]
duplicate
