### ISSUE TITLE
Publish ReqMgr stats to CERN MONIT

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8443]
We could start with:
* for workflows in assignment-approved
  * their priority
  * their RequestNumEvents (if starting from scratch)
  * maybe, amount of requests in each campaign (tricky for TaskChains)

**Comment by ticoann** [comment]
Hi Alan,
This information is in wmstats, exactly what statistics  need to be displayed and what is the advantage of putting is CERN Monit?

**Comment by amaltaro** [comment]
Indeed they are :) I usually don't pay attention to that stats box. Still, one has to apply some filters and aggregation by priority is not supported (it is for campaign), and the output isn't very user friendly (either a row or a table).
Having this info in Monit would allow to make a fancy graph :) and have that visualization in a dashboard, together with other overview graphs of central production.
