### ISSUE TITLE
Constrain on request name length

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8449]
we have had this issue recently

Exception Class: WMSpecFactoryException
Message: 'vlimant_r-0-prebello_Run2016B-03Feb2017_ver2-v2-SingleMuon-05Feb2018_ver2_944_180207_191812_393_180212_154306_1681' does not match regular expression [a-zA-Z0-9\s\.\-_]{1,100}$

however what we input is requestor, request string and that's it, then a series of characters are added of variable size, hence we cannot control exactly what should be the maximum length or the input.
can the regexp be applied somehow at the requeststring level, or else. so that one can add deterministic checks

**Comment by amaltaro** [comment]
This was limited when we had ReqMgr1, which used oracle as a backend database. Couch is more relaxed, maybe we can apply the lexicon/regex on the requestor + request string, leaving the final date + random number off (which is completely predictable).
