### ISSUE TITLE
Merge job requirements

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8451]
maybe a GH with a couple of items. There is a new issue popping up because of the merging of nanoaod. 
a) we need to be able to change that requirement one way or the other. short term if it turns out that the nano merging does need more memory because it goes through many many events, long term so that we have the flexibility.
b) I noted that the watch dog is set to 2.3G-ish, but the jobs are made in condor with requesting 1000MB of memory, which is not consistent

**Comment by amaltaro** [comment]
dup #8331
