### ISSUE TITLE
Splitting API removing attr not provided when posting new splitting

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8453]
@ticoann I might have got something wrong, so please correct me if something is wrong.

While testing the `splitting` rest api, it looks like one has to provide all (existent) allowed splitting attributes, otherwise it just gets removed when new settings are posted.

For example, if I post this content:
```
[{u'splitAlgo': u'EventAwareLumiBased',
  u'splitParams': {'job_time_limit': 20000},
  u'taskName': u'/amaltaro_MonteCarloFromGEN_Agent1110_Validation_180213_114610_1192/MonteCarloFromGEN',
  u'taskType': u'Processing'}]
```
the `events_per_job` attribute is gone. I'd expect the update function to update only those attributes provided (maybe it doesn't work for nested dicts though).

The correct content to post would be
```
[{'splitAlgo': u'EventAwareLumiBased',
  'splitParams': {u'events_per_job': 507, 'job_time_limit': 20000},
  'taskName': u'/amaltaro_MonteCarloFromGEN_Agent1110_Validation_180213_131827_7141/MonteCarloFromGEN',
  'taskType': u'Processing'}]
```
which does the correct splitting update.

**Comment by amaltaro** [comment]
@ticoann since you're going to look into this splitting API, can you also have a look at this issue?

**Comment by ticoann** [comment]
It seems it should set up (update) correctly. But only top level task doesn't set up correctly in the workQueue splitting parameter. Does that wha you observed?

**Comment by amaltaro** [comment]
I didn't even assign those tests because I'm pretty sure it will break JobCreator (maybe even Global WorkQueue), since the splitting attribute is removed.

You can try the example I mentioned above, but before changing the splitting, have a look at the workload spec (not the json) and locate the `splitting` section. After you update the job splitting with partial parameters, you'll see that some attributes are gone from that task splitting section

**Comment by ticoann** [comment]
Are you calling REST api something like below?
```
curl --cert $X509_USER_CERT --key $X509_USER_KEY -X POST -H "Content-type: application/json"  -H "Accept: application/json"  https://reqmgr2-dev.cern.ch/reqmgr2/data/splitting/sryu_StepChain_MCStatic_sryu_180308_052522_5675 -d '[{"splitAlgo": "EventBased",
  "splitParams": {"job_time_limit": 20000},
  "taskName": "/sryu_StepChain_MCStatic_sryu_180308_052522_5675/GENSIM",
  "taskType": "Production"}]'
```

**Comment by ticoann** [comment]
Never mind Alan, I can reproduce the problem thanks.
