### ISSUE TITLE
allow to ignore lumilists when using FileBased splitting

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#8467]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3554/2/1/1/1/2/2/1/2/2/1/1/1/1/1/1/1/1/1.html

this is needed by
https://github.com/dmwm/CRABServer/issues/5645

@ticoann @amaltaro @hufnagel let's use this to converge on the new signature for the SplitterFactory
so that I can make the proper changes to CRAB in
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Splitter.py

**Comment by amaltaro** [comment]
I might still be missing something, however, this is how (check the else below too) we load the list of files:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/JobFactory.py#L237
when sortByLocation() is called. It doesn't do any lumi/run check, it simply loads what's already in the agent/database. (I'm not sure how CRAB uses this though).

Then there are a few checks in the FileBased that disregard run/lumi info:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/FileBased.py#L48

keeping the file for further job splitting.

Where is the problem coming from? What's the use case? What are the input parameters?

**Comment by belforte** [comment]
thanks @amaltaro . I will check the JobFactory.py and the CRAB code and dig for the analysis that was done when we had to set the limit. The problem only appeared in CRAB because we run 10 processes on the same machine, when a few of them load the super-large lumilists the host runs out of memory.
If we can solve by simply not passing the lumilist to the splitter factory, and no change to WMCore, so much the better.
Ball in my park now.

**Comment by amaltaro** [comment]
Ah-ha, now I finally see the problem, thanks! Ok, let us know your findings.

**Comment by hufnagel** [comment]
Technical comment, if the splitting doesn't need the run/lumi information and that information is massive, not fetching it from the database in the first place likely improves the splitting performance quite a bit.

So even if the reason for the crash isn't precisely in the data retrieval in the FileBased splitting algo, but more in what CRAB does with this information, you might still want to not retrieve it when it is not needed.

Just saying.

**Comment by hufnagel** [comment]
Ah, re-reading your comment, CRAB might not even use this data discovery though but have it's own. And NANOAOD will never be processed by production workflows. Ignore (for the most part) my comment then.

**Comment by belforte** [comment]
@hufnagel I fully agree with your comment. Simply have not the code in my mind and can't say where to touch it yet. Definitely will want to do make things as lean as possible

**Comment by belforte** [comment]
@ticoann feel free to assing to me. I will either close if fix is all in crab land, or come back with request for WMCore and you can review then.

**Comment by belforte** [comment]
after reviewin CRAB code, I believe that the simplest solution for us is via a small upgrade in WMCore as indicated here
https://github.com/dmwm/CRABServer/issues/5645#issuecomment-387550233
feel free to reply here or there... if you agree it may be better to have an ad hoc issue about the additional functionality in Services/DBS
