### ISSUE TITLE
Error Codes reporting 0 to Dashboard but 50660 to Archive and WMStats

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#8473]
SeangChan was looking for instances of misreporting error codes to Dashboard.  Here is a prime example

pdmvserv_task_HIG-RunIIFall17wmLHEGS-00630__v1_T_180216_120647_5907

Looking at Dashboard:
http://dashb-cms-job.cern.ch/dashboard/templates/web-
job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&usr=&site=&submissiontool=wmagent&application=&activit
y=reprocessing&status=&check=submitted&tier=&date1=2018-02-20+12%3A28&date2=2018-02-
20+16%3A28&sortby=appexitcode&scale=linear&bars=20&ce=&rb=&grid=&jobtype=Processing&submissionui=&dataset=&submi
ssiontype=&task=wmagent_pdmvserv_task_HIG-RunIIFall17wmLHEGS-
00630__v1_T_180216_120647_5907&subtoolver=&genactivity=&outputse=&appexitcode=&accesstype=&inputse=&cores=

there is a high instance of failures with exit code 0 and N/A
I was trying to figure out what that translates to in WMStats, went over to WMArchive:
https://cmsweb.cern.ch/wmarchive/web/performance?
metrics[]=jobstate&axes[]=host&axes[]=jobstate&axes[]=site&axes[]=exitCode&start_date=20180220&end_date=20180220&agg
DB=aggregated&aggCol=hour&workflow=pdmvserv_task_HIG-RunIIFall17wmLHEGS-00630__v1_T_180216_120647_5907

And see that they are 
50660
Application terminated by wrapper because using too much RAM (RSS).
and
99303

I know that these are relatively new exit codes, how do we get Dashboard to map them properly?

**Comment by amaltaro** [comment]
Merging it into another issue regarding diff exit codes in diff tools
