### ISSUE TITLE
WorkQueueManagerCleaner is very slow

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8477]
And so it raises a heartbeat alarm.
I don't know exactly what it's doing to be honest, but I see it taking a few hours per cycle, on vocms0250
```
2018-02-21 01:18:34,045:140688431773440:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 12439.739 secs to execute
2018-02-21 04:47:52,849:140688431773440:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 12377.496 secs to execute
2018-02-21 07:00:58,592:140688431773440:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 7805.157 secs to execute
etc etc
```

probably there is some room for improvements here. Or we slice the amount of work it has to do. Or ...

**Comment by amaltaro** [comment]
Bumping it to Medium. Still present in 1.1.14.patch4. submit4 is raising the heartbeat timeout very very often.

**Comment by amaltaro** [comment]
This one is always raising heartbeat issues, I'd suggest to work first on this one instead of https://github.com/dmwm/WMCore/issues/8253

**Comment by amaltaro** [comment]
Just so it doesn't go into oblivion, this is how bad this thread is doing in the 1.4.5 series (submit3):
```
2021-04-20 16:42:03,550:140233874929408:INFO:WorkQueueManagerCleaner:Start updating & cleaning...
...
2021-04-20 21:31:12,511:140233874929408:INFO:WorkQueueManagerCleaner:Killing 0 requests in WMBS ...
2021-04-20 21:31:12,511:140233874929408:INFO:WorkQueueManagerCleaner:Finished updating & cleaning.
2021-04-20 21:31:12,512:140233874929408:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 17348.962 secs to execute
```

yes, basically 5 hours to complete a cycle!

**Comment by amaltaro** [comment]
As I debug another problem with this very same thread, just another update to this GH issue (based on WMAgent 1.4.7). The heavy processing of this thread happens on the `performSyncAndCancelAction` method, here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L969

that code is a bit tricky because it gets executed both by local and global workqueue, but by a quick look, I'm not sure all that code is actually required to be executed (e.g. why executing `addNewFilesToOpenSubscriptions`???)

That method deserves attention and performance enhancements must be made.

**Comment by amaltaro** [comment]
And a new record with FNAL agents running 1.4.7:
```
2021-07-24 23:14:03,429:140386018113280:INFO:BaseWorkerThread:WorkQueueManagerCleaner took 207003.664 secs to execute
```

It's sort of expected to have a slower process on the FNAL agents, since those agents pull 50% more work than the CERN ones. However, I did not expect this thread to take **days** to complete... 

Trying an agent restart to see whether things improve, if not, we might have to add this issue to our Q3 list and bring it up to the top of the priority list.

**Comment by amaltaro** [comment]
Given the current (almost) critical situation with the unmerged area, and the slow response from the agents, let me try to make some safe and quick improvements here.

**Comment by haozturk** [comment]
Thanks Alan. Let me provide some statistics: As of now, there are 666 workflows in `running-closed` w/ 100% complete output. (Some waiting for 4-5 days). Also we have ~330 workflows waiting for `force-completed` to `completed` transition. So, in total this slowness affect ~1k workflows. From by perspective, this is the highest priority issue, right now. Please let me know if I'm missing something.

**Comment by amaltaro** [comment]
Thanks for this information, Hasan. I have something already cooked, but this code is complex and it takes some debugging and learning as I go through the code :-D
