### ISSUE TITLE
delayed release of work 

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8492]
was discussing with @amaltaro what could be the origin of the burst on submit4

![daily](https://user-images.githubusercontent.com/4989875/36780523-88bd6120-1c73-11e8-9fac-a202f1cba7aa.png)

the agent is in drain, and it is holding work for ~10h.
Given that this impacts draining time and delivery of the samples, I would like that we get an understanding.
Given this

![daily-cpu](https://user-images.githubusercontent.com/4989875/36780668-ea49de14-1c73-11e8-9f73-d7e19a607aa1.png)

the jobs get running when they are released, meaning that they are in top priority.

This is a secondary effect, that you can put low priority. Just recording here the observation and giving my opinion on the the impact of this

**Comment by amaltaro** [comment]
For the record while I have some investigation still fresh in my mind.
As we chatted, it could be pretty much anything, it could be LQE having a valid location, sites going in/out of drain, priority x resources, components misbehaving (not the case here), workflows being force-completed/aborted, etc.

Can you provide the same plots but for a longer period of time (at least > 3days). Just to see where this behavior stands or whether it's something that happened in the last 24h only.

**Comment by amaltaro** [comment]
Thanks!
