### ISSUE TITLE
JobSubmitter memory hungry

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8493]
As reported by Diego in this elog
https://cms-logbook.cern.ch/elog/GlideInWMS/6087

there is a wmagent process that is consuming around 18GB of RSS memory on vocms0253. Having a look at the agent, that's JobSubmitter:
```
cmst1@vocms0253:/data/srv/wmagent/current $ grep -r 1352320 install/wmagent/*/Daemon.xml
install/wmagent/JobSubmitter/Daemon.xml:	<ProcessID Value="1352320"/>
cmst1@vocms0253:/data/srv/wmagent/current $ 
cmst1@vocms0253:/data/srv/wmagent/current $ ps -p 1352320 -o pid,ppid,rss,vsize,pcpu,pmem,cmd -ww | grep 1352320
1352320       1 18152828 18588968 3.0 30.1 python /data/srv/wmagent/v1.1.10.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch4/bin/wmcoreD --start --config=/data/srv/wmagent/v1.1.10.patch4/config/wmagent/config.py
cmst1@vocms0253:/data/srv/wmagent/current $ 
```

This must be the reason why that process sometimes silently dies (or it gets somehow stuck, I don't remember right now) and causes it to be automatically restarted.

For the record, this is the load of that agent right now
```
2018-02-28 21:52:27,445:139740511799040:INFO:JobSubmitterPoller:Found 8795 new jobs to be submitted.

cmst1@vocms0253:/data/srv/wmagent/current $ condor_status --schedd vocms0253.cern.ch
Name              Machine           RunningJobs   IdleJobs   HeldJobs
vocms0253.cern.ch vocms0253.cern.ch       14482      50249          0
                      TotalRunningJobs      TotalIdleJobs      TotalHeldJobs
               Total             14482              50249                  0
```

**Comment by ticoann** [comment]
We can control the memory usage (in some degree) by setting below value lower.
config.JobSubmitter.cacheRefreshSize = 30000
Currently it gets holds 30000 record in the cache, which shouldn't be 18GB. I will restart JobSubmitter whether memory usage goes up again. We might have some memory leak.

**Comment by ticoann** [comment]
After JobAccountant restarted memory usage is around 400MB. So it doesn't seem to be due a cache size. (cache was reduced only 33%). I will monitor for a few more days.

**Comment by amaltaro** [comment]
Haaa, the memory leak comes from the htcondor python bindings, more precisely from `submitMany` API.

I created this script 
https://github.com/amaltaro/ProductionTools/blob/master/testCondorSubmission.py#L275
mimic'ing the same `submit` method from SimpleCondorPlugin module.

If you comment out submitMany line and don't really submit jobs to condor, the memory footprint is negligible. On the other hand, the memory grows very quickly if we keep submitting jobs to condor.

This is one method memory profiling for job data structure creation but no submission (50 cycles creating 1k jobs each):
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_8493/noSubmit_50_1k.log

while this one is actually submitting jobs to local condor queue:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_8493/submit_10_1k.log (10 cycles creating 1k jobs each)

Right now we build condor 8.5.7, I might try building a new condor RPM on 8.6.8, which is the same condor version we run in production.

@bbockelm I guess we should make it an issue for the htcondor, right? Can you please remind me what's their ticketing system?

**Comment by ticoann** [comment]
Nice! Alan. :-)

**Comment by bbockelm** [comment]
Yup, that's about what I expected.  Try the latest condor version in the stable series (8.6.11); I see at least one commit about python bindings memory leaks.

**Comment by amaltaro** [comment]
Ok, I haven't managed to build the latest condor yet. I had to update both patches and then it started failing to includ an openssl header, which should have been fixed when I removed that option from the condor spec.

Now it fails when building the boost external with a cryptic error, not to say there is basically no error message :( I'll keep trying, maybe I can bug Shahzad to give me some help here.

In case anyone wants to have a look, these are my current changes (branch condor-upgrade):
https://github.com/amaltaro/cmsdist/commit/eb97a5810162a340e4c7e5b57b321867c4c211e5

**Comment by amaltaro** [comment]
I updated the standalone script such that anyone can reproduce the issue with no need to any of the WMCore libraries. I sent all the recipes to Diego D. to follow up with htcondor developers. Now it's time to explore a temporary solution for this issue...

**Comment by johnkn** [comment]
I did some investigation, it's leaking the classAds that are returned by submitMany via the 4th argument.  But only if you *don't* supply the 4th argument.  Not really sure why this is so, but you can easily work around the bug just by calling submitMany with 4 arguments like this:

     schedd.submitMany(clusterAd, procAds, 0, [])

**Comment by ticoann** [comment]
@johnkn, That is great and simple workaround. 😄 Thank you very much John. We will test.

**Comment by johnkn** [comment]
actually

  schedd.submitMany(clusterAd, procAds, 0, None)

Is better, because None causes the creation of the result_ads to be skipped entirely.  This is what the 2 argument version of submitMany was intended to do.

**Comment by amaltaro** [comment]
Thanks, John. It works like a charm!

**Comment by johnkn** [comment]
Good.  I have put in a fix for the underlying bug.  for now, I recommending passing None as the last argument if you don’t actually want to get the ads returned.  I tested it and that works and is a bit cheaper than passing an empty list.

-tj
