### ISSUE TITLE
clone API doesn't work (400 error)

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8495]
It seem it need to filter out RequestName)

Following API gives  400 error.

cmst2@vocms049:/data/cmst2 $ curl --cert $X509_USER_CERT --key $X509_USER_KEY -X PUT -H "Content-type: application/json"  -d '{"RequestNumEvents": 4000}' https://cmsweb.cern.ch/reqmgr2/data/request/clone/wmagent_dmason_NERSCTEST_171102_171002_8020

**Comment by amaltaro** [comment]
@ticoann I guess we're missing some details with this curl call, because using python https works just fine:
```
amaltaro@vocms0192:/data/amaltaro/ReqMgr2_scripts $ python clone.py wmagent_dmason_NERSCTEST_171102_171002_8020
Cloning request 'wmagent_dmason_NERSCTEST_171102_171002_8020' with the following override settings: {}
Clone: amaltaro_dmason_NERSCTEST_180302_204317_5883
```

You can see this script here:
https://github.com/amaltaro/scripts/blob/master/ReqMgr2/clone.py#L22

**Comment by amaltaro** [comment]
and voila:
```
amaltaro@vocms0192:/data/amaltaro/ReqMgr2_scripts $ python clone.py wmagent_dmason_NERSCTEST_171102_171002_8020 '{"Step1": {"RequestNumEvents": 4000}}'
Cloning request 'wmagent_dmason_NERSCTEST_171102_171002_8020' with the following override settings: {u'Step1': {u'RequestNumEvents': 4000}}
Clone: amaltaro_dmason_NERSCTEST_180302_205137_9024
```

**Comment by ticoann** [comment]
Thanks Alan, I used PUT instead of POST. That is why I got the error. (following works)

curl --cert $X509_USER_CERT --key $X509_USER_KEY -X POST -H "Content-type: application/json"  -H "Accept: application/json"  -d '{"Step1":{"RequestNumEvents": 4000}}' https://cmsweb.cern.ch/reqmgr2/data/request/clone/wmagent_dmason_NERSCTEST_171102_171002_8020
