### ISSUE TITLE
reqmgr priority update using curl

### ISSUE THREAD

**Issue by dlont** [dmwm/WMCore#8496]
I copy the issue from JIRA https://its.cern.ch/jira/browse/CMSCOMPPR-2448

I tried using REST API, as you suggested, but I cannot even GET the dictionary, i.e.

curl --cert myusercert.pem --key myuserkey.pem -X GET https://cmsweb.cern.ch/reqmgr2/data/request/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00284__v1_T_180227_092148_7752

throws an error:

curl: (58) Unable to load client key -8178.

It is not the certificate problem, because I can successfully read using wget

wget --certificate myusercert.pem --private-key myuserkey.pem  https://cmsweb.cern.ch/reqmgr2/data/request/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00284__v1_T_180227_092148_7752

Answering Seang's questions
 > Is the link works in the browser?
yes

> Is your key PKCS#8 key or RSA key?
I have PKCS#12 key that I use for grid. It works when I use wget, but not with curl. Unfortunately, wget does not support PUT method, as far as I understand. Otherwise it would solve the issue.

**Comment by ticoann** [comment]
@dlont, Hi Denys,
Are you using curl and openssl? 
You can create RSA key and try with that

openssl pkcs8 -in path/to/your/pkcs8/key -out path/to/rsa/key
Here is more of the same problem you are having.
https://stackoverflow.com/questions/20969241/curl-58-unable-to-load-client-key-8178

Anyway, web ui for changing priority is fixed and will be deployed next week. 
If you could tell me the requests and priority value you need to change. I can change it for you until production reqmgr is updated.

**Comment by dlont** [comment]
It is the workflow specified in the original message

**Comment by ticoann** [comment]
Hi Denys, Priority is updated to 82K. Since the issue (curl failure) itself doesn't seem to be WMCore issues. If you agree, could you close the issue?

**Comment by dlont** [comment]
Yes, I agree, but I need to move a couple of wfs to 89k, please.

https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_TOP-RunIISummer15wmLHEGS-00285__v1_T_180301_042036_331

https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_TOP-RunIISummer15wmLHEGS-00286__v1_T_180301_041930_4968

**Comment by amaltaro** [comment]
Hi Denys, as requested, I've updated the priority of these 2 workflows above to 89k.
As Seangchan already mentioned, the web UI will get fixed during tomorrow's CMSWEB upgrade.
I'm closing this issue
