### ISSUE TITLE
Monitor memory utilization based on PSS instead of RSS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8498]
Some interesting explanation here: https://elinux.org/Android_Memory_Usage

In short, RSS considers all pages of shared libraries (so there is always an overcounting), while PSS (Proportional) divide that size among all the processes sharing it.

**Comment by bbockelm** [comment]
This is relevant because `cmsRun` will `fork` / `exec` in order to startup `condor_chirp` for statistics gathering.

If the watchdog triggers after the `fork` but before the `exec`, it will currently see the memory usage as doubling, even though the RAM usage is approximately the same.  Since this phase is quite short, it will just cause infrequent "mystery memory usage" that looks as if it doubled in a short amount of time.

Unfortunately, if the memory usage is greater than 50% of the max RSS parameter, then the watchdog may decide to shoot the process.

**Comment by amaltaro** [comment]
BTW, I thought ps would have the `pss` argument, but it doesn't! It looks like we have to look at `/proc/$pid/smaps` instead (does the pilot/payload have access to it?).

Here's a suggestion on how to monitor PSS memory usage (mind that the first answer is wrong, we have to actually sum all those entries up):
https://superuser.com/questions/102005/how-can-i-display-the-memory-usage-of-each-process-if-i-do-a-ps-ef

**Comment by amaltaro** [comment]
@goughes Erik, how about you take over this issue? :)

**Comment by goughes** [comment]
I'm grabbing totals for RSS, PSS and VSize from `/proc/<pid>/smaps` with this command:

`awk '/^Rss/ {rss += $2} /^Pss/ {pss += $2} /^Size/ {vsize += $2} END {print rss, pss, vsize}' /proc/%i/smaps`

My testing shows the RSS/VSize numbers jive with what is found via the command used now in PerformanceMonitor.py. https://github.com/dmwm/WMCore/blob/ff3ef25f1058b303aa489844adbe9191b9dfb9cd/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L62

%CPU and %MEM is also returned by the ps command and is logged here:

https://github.com/dmwm/WMCore/blob/ff3ef25f1058b303aa489844adbe9191b9dfb9cd/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L202

That is the only place the %CPU and %MEM is values are used.  Are they worth logging?

If so, I can run both commands to get the desired statistics.  If not, I will just switch the command to read from smaps.

**Comment by goughes** [comment]
Just synced my fork and it looks like the vsize stuff has been removed so you can ignore my comments about that.

**Comment by amaltaro** [comment]
@goughes Erik, in my opinion we can keep fetching those stats: rss, pcpu, pmem and add the PSS on top of it., logging something like:
```
logging.info("PSS: %s, RSS: %s; PCPU: %s; PMEM: %s", ...
```

and the line above it ("Retrieved following...") can probably go away.
How does it sound?
