### ISSUE TITLE
Provide get call for splitting only returns updatable parameters.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8499]
Add options on following api which returns only valid parameters for update.
/reqmgr2/data/splitting/

**Comment by amaltaro** [comment]
For this specific case, I think we should GET all splitting parameters but when one POSTs it, we should update only what's allowed.
For the record, another issue created on the same subject a week ago: https://github.com/dmwm/WMCore/issues/8453

**Comment by ticoann** [comment]
I have a little different approach to that. Since we are getting strict about validation. I think we shouldn't ignore the some parameters blindly. If we want to be more flexible, we should at least report back which parameters won't be updated. But also, user shouldn't try to modify some parameters which is allowed to be changed.

**Comment by amaltaro** [comment]
> I have a little different approach to that. Since we are getting strict about validation. I think we shouldn't ignore the some parameters blindly.

I completely agree! However, in this case we'd need to return only changeable parameters with the GET api, which might not be optimal if someone wants to check all job splitting parameters.

**Comment by ticoann** [comment]
> I completely agree! However, in this case we'd need to return only changeable parameters with the GET api, which might not be optimal if someone wants to check all job splitting parameters.

Oh, I meant add "option" to retrieve only updatable parameters. So we can add query string ?only_updatable=true. Than, returns the list of values which can be updated. Without that option behavior of get will be the same.

**Comment by amaltaro** [comment]
Approved!!! :)

**Comment by ticoann** [comment]
Thank you, Sir. 😄
