### ISSUE TITLE
None values in reqmgr2 injection, while input dictionary has zero None values

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#8517]
Last week we noticed a masive (few hundred requests) were failing injection to reqmgr2 with this error:
          <p>Invalid spec parameter value: int() argument must be a string or a number, not 'NoneType'</p>

example dictionary we tried to inject is here: https://pastebin.com/raw/gAC4TEzW

We are not sending any null values in dictionary. So it seems it's missing a variable, but... I retried injection today and only difference is configCacheID (which we upload during injection time) it works - no other parameters changed.

Can it be that during injection time reqmgr was putting some default parameters as None?  Would it be possible in the error message to show which variable has wrong/missing value?

Also another injection failure happened on  March 14, 2018 9:35 AM. prepid: task_B2G-RunIIFall17wmLHEGS-00175. Immediate retry succeeded - only configCacheId changed.

**Comment by amaltaro** [comment]
Yes, printing the parameter name in the error message makes a lot of sense, unfortunately it doesn't seem to be the case for data type check, we'll fix it.

> Also another injection failure happened on March 14, 2018 9:35 AM. prepid: task_B2G-RunIIFall17wmLHEGS-00175. Immediate retry succeeded - only configCacheId changed.

This is still fresh and we have a timestamp. I'll check the reqmgr2 logs tomorrow to see if I can get any useful info from it.

**Comment by anorkus** [comment]
the most strangest error (maybe related to None values) was on March 14, 2018 10:21 AM sending this dictionary: https://pastebin.com/raw/vkGT39CM

Exception Class: WMSpecFactoryException
Message: Argument 'Task1' cannot be None
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : _validateArgumentDict
        ClassInstance : None
        FileName : /data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.11.pre3/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py
        ClassName : None
        LineNumber : 74

for sure Task1 is not None...

**Comment by amaltaro** [comment]
>  Message: Argument 'Task1' cannot be None

I also hit this issue yesterday. It comes from the slightly complex validation of dict arguments.

For the first issue, I think it comes from here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L482

I'll investigate it for the next week testbed deployment.

**Comment by amaltaro** [comment]
Fixes by #8585
