### ISSUE TITLE
Cleanup/alarm for logs in /store/logs/prod/recent/ 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8522]
Follow up of #8456
It's not a WMCore issue, but I think it's worthy having a ticket here and discuss how we're going to handle that log storage space. The allocation is 30TB and a maximum of 50M files, which can be seen with
```
amaltaro@aiadm61:~ $ eoscms quota /eos/cms/store/logs/prod/recent

By group:
┏━> Quota Node: /eos/cms/store/logs/prod/recent/
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│group     │used bytes│logi bytes│used files│aval bytes│aval logib│aval files│ filled[%]│vol-status│ino-status│
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
 zh           21.24 GB   10.62 GB     7.91 K   60.00 TB   30.00 TB    50.00 M     0.04 %         ok         ok 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

According to dashboard, we're running between 500 and 600k jobs a day (based on the last week resource utilization). From Seangchan's recent tests, the tarballs are around 5MB each (though it can vary by quite a bit depending on the workflow and job configuration - and site stage out commands). In summary:
* that gives us around 100 days worth of files
* 10 to 12 days worth of storage space (6M tarballs only!)

Thus, I'd suggest
* we need to get more space for these logs. In avg, we need 100TB of _usable space_ in order to keep 1 month worth of logs. (So I'd say we need 200TB of usable space) 
* for the cleanup, I think we can contact the transfer team and ask if they can setup some cleanup script. I know Sid is working on a script to perform the /store/unmerged cleanup
* then for monitoring the quota and making sure we never reach the limit (including the limit of files!), we can ask the VOC to setup an alarm once we reach 80%(?) of the total space.

Any thoughts?

**Comment by bbockelm** [comment]
@vlimant - who in operations would be in the best position to do this?

It's "just a cronjob", but getting it known to operations (documented, finding a responsible team, etc) is probably more effort than writing the cronjob itself.

**Comment by vlimant** [comment]
the availability of reports/logs from unified is set to "keep everything you have for workflows that have not been announced more than 2 weeks ago".
the cron is already set, I would just need to add /eos/cms/store/logs/prod/recent to the paths to clean and be given delete permission in it.

**Comment by amaltaro** [comment]
For the record, Daniel provided this grafana link to monitor that EOS space:
https://monit-grafana.cern.ch/dashboard/db/vocms-eos-quotas?orgId=6&refresh=15m&var-fulltotalquotas=All&var-quotas=All&var-totalquotas=All

and he's also set an alarm (runs every 10min) with a 90% thresholds, Seangchan and I are supposed to get it, initially.

**Comment by amaltaro** [comment]
Cleanup has also been addressed by the data transfer team (Sid). In short, any directory last-modified > 60 days ago will be deleted. This means a workflow might have some task directories but not others, in case nothing has been written in there for 60 days or more.

Further details can be found in the thread "CERN EOS logs cleanup" with data-transfer and oc-dmwm egroups.
