### ISSUE TITLE
ReqMgr2 request API with pileup query strings

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8544]
While looking at ReqMgr2 APIs to list requests using a given pileup dataset, I noticed that the `mc_pileup` query string
https://cmsweb.cern.ch/reqmgr2/data/request?mc_pileup=/Neutrino_E-10_gun/RunIISummer17PrePremix-MC_v2_94X_mc2017_realistic_v9-v1/GEN-SIM-DIGI-RAW&detail=false&status=ACTIVE

returns a different result than `mc_pileup` + `data_pileup` query
https://cmsweb.cern.ch/reqmgr2/data/request?data_pileup=/Neutrino_E-10_gun/RunIISummer17PrePremix-MC_v2_94X_mc2017_realistic_v9-v1/GEN-SIM-DIGI-RAW&mc_pileup=/Neutrino_E-10_gun/RunIISummer17PrePremix-MC_v2_94X_mc2017_realistic_v9-v1/GEN-SIM-DIGI-RAW&detail=false&status=ACTIVE

which seems to be just an OR of those parameters.

I looked at the views and they are just the same.

Seangchan, am I missing something here?

**Comment by ticoann** [comment]
If you specifies multiple parameters. It considers as AND operation. (I am not sure that is standard interpretation, though) But I think mostly we assume it is "AND" operator. 

https://www.ibm.com/support/knowledgecenter/en/SS6KJL_8.6.4/FEB/ref_data_rest_api_list_filter.html

Is this causing any problem, should we support OR operator?

**Comment by amaltaro** [comment]
Ohhh, I missed this line
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L338

sorry for the noise, Seangchan. Closing it
