### ISSUE TITLE
Stepchain Parentage handling

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8556]
1. provide DBS api for setting the dataset parentage with out inserting the file first. (and more)
       - https://github.com/dmwm/DBS/issues/570
       - https://github.com/dmwm/DBS/issues/569
       - https://github.com/dmwm/DBS/issues/566
2. provide api find a file parentage by given dataset/block/file. - This will be expensive check for dataset)
3. provide api insert parentage (WMCore API)
4. change the Agent code to remove wrong parentage relation in StepChain case

Along with this, we need to gather the statistics whether it is worth to put the parentage in DBS once it is resolved or just calculate on the fly

**Comment by vlimant** [comment]
the way I see it, and that I am not sure it's what I understand from your description above, and with a further suggestion from Liz today.

 * we need the piece of code that does the file based parentage (based on lumisection) provided either a block parentage (where can we get this from?), or a dataset parentage (this is contained in the request schema)
 * we need to run this at workflow close-out (even better reqmgr toggles completed) systematically, provided it does not take hours per dataset (we need an estimate on how long it takes per dataset) and push the information in dbs where it belongs already.

this "make the parentage at close-out" can be either run by reqmgr or unified (I vote reqmgr, but I don't really care)

the only important item, IMO is to have that piece of code that reconstruct the file parentage under a provided dataset parentage, regardless where we end up running it.

@bbockelm

**Comment by ticoann** [comment]
Added in HG1809
