### ISSUE TITLE
Need Dockerfile and image for kubernetes

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#8564]
Could you please create Dockerfile and image for current cmsweb server (e.g. ReqMgr2, etc) that we can use to deploy it to kubernetes. Follow up github.com/vkuznet/CMSKubernetes for instructions, in particular look-up dbs2go folder which contains Dockerfile for dbs2go. We need similar for all WMCore based servers we use on cmsweb.

**Comment by amaltaro** [comment]
You have already provided all of those under:
https://github.com/dmwm/CMSKubernetes/tree/master/docker

so I'm closing this issue. Thanks
