### ISSUE TITLE
Create new API which retrieves parent files by lumi section

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8590]
Precondition is at least dataset parentage needs be know.  

1. provide file parentage by given file and parent dataset
2. provide file parentage by given block and parent dataset
3. provide file parentage by given dataset and parent dataset

Option 3 will take big performance hit.

**Comment by vlimant** [comment]
@ticoann @yuyiguo I don't think there is a label higher than higher priority.
can we please have an update on this.
