### ISSUE TITLE
Is there anyone using UserFileCache?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8608]
This module
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/UserFileCache/UserFileCache.py

seems not to be used within WMCore. Check whether it's used by any other external service, if not, delete it.

**Comment by ticoann** [comment]
I think crab uses this

**Comment by bbockelm** [comment]
Correct, this is used heavily by CRAB3.  Closing ticket.
