### ISSUE TITLE
Is there anyone using SAM?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8609]
This module
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/SAM/SAM.py

seems not to be used within WMCore. If external services are not using it either, then let's delete it.

**Comment by ticoann** [comment]
I am not sure but not in us. (WMAgent)

**Comment by bbockelm** [comment]
Delete it.  The SAM test it references is no longer in use.

@PerilousApricot heads-up.  You touched the file last.

**Comment by ticoann** [comment]
Thanks, I added in #8607
