### ISSUE TITLE
Make a different dir structure for T0 prod/recent logs (?)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8634]
Since T0 process much more workflows than central production (and workflows usually behave), I think we could isolate Tier0 logs from central production ones.

Default URL is 
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/

how about we make it
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/Express

and so on, such that we create an additional directory based on the request spec name?

Since I think it's a great idea, I'll go ahead and make the necessary changes and request Lina to push it into testbed today.

@hufnagel @drkovalskyi @vytjan let me know if you disagree by this Wednesday such that I can roll it back.

**Comment by drkovalskyi** [comment]
Why Express instead of Tier0 or something more representative. Is it really only for Express? If not we need a better name.

**Comment by amaltaro** [comment]
Express for Express, Repack for Repack etc. Check out the proposed fix in 8635
Anyways, I don't think I can change anything before Dirk gets back from vacations, since there are some details that I need his feedback.

**Comment by drkovalskyi** [comment]
Sounds good to me
