### ISSUE TITLE
Decrease EventsPerLumi when it's bigger than the calculated EventsPerJob

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8639]
From this discussion
https://its.cern.ch/jira/browse/CMSCOMPPR-2861

**Comment by vlimant** [comment]
listing here all the wf severely (>factor 2) affected
pdmvserv_task_SUS-RunIIFall17wmLHEGS-00026__v1_T_180501_163815_1272
pdmvserv_task_HIG-RunIIFall17wmLHEGS-01113__v1_T_180415_203614_875
pdmvserv_task_SUS-RunIIFall17wmLHEGS-00018__v1_T_180415_204125_5254
pdmvserv_task_EGM-RunIISummer18GS-00005__v1_T_180521_224529_6986
@prozober
