### ISSUE TITLE
Log original request parameters before ReqMgr default values are added

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8644]
We should keep a record of every POST (and PUT) ReqMgr2 request before we apply the default parameters/values to the user request, in addition to what we have already.

**Comment by ticoann** [comment]
@amaltaro, Alan where would you keep this and what will be the usage?

**Comment by amaltaro** [comment]
Darn it! We should get this in for August deployment. I think we can simply log the user input in the usual reqmgr2 log.

The use case is debugging workflows and making sure that what the user claims to have posted to reqmgr2 is actually what he really posted. Example are the EventsPerJob and EventsPerLumi, that we're rounding now in ReqMgr2.

I'm working on it today.

**Comment by amaltaro** [comment]
Fixed by #8691
