### ISSUE TITLE
Make ACDC creation to recover all tasks/failures

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8645]
Hi @thongonary @mcremone @vlimant 
Seangchan and I were discussing whether it would be helpful if we changed the behavior of ACDC creation.
The current behavior is that one needs to create an ACDC workflow for every single task that we want to recover. So it offers a good flexibility on what exactly to recover, but it might spans several additional wfs.
The proposed behavior would be that a single ACDC wf would be needed in order to recover failures from different tasks (aka. all failures in the ACDC server). Seangchan mentioned this is how ACDCs used to work a few years back...

If you think this change can add a substantial improvement to P&R Ops, then let us know and we can define a milestone for it.

**Comment by thongonary** [comment]
@prozober may have some opinion on which ACDC behavior she prefers.

**Comment by amaltaro** [comment]
One use case would be whether Ops decides to recover the merge jobs only (since that would yield enough stats) and forget any other production/processing task failures. If you try to recover everything, it might just delay the announcement of such samples.

Thus it's more like a tradeoff question, is it worth it to have a better traceability of work and sometimes add a delay to a request here and there? or we rather recover only - and only - what we want, even though it might mean 10 ACDCs for one single request?

You might discuss it in today's P&R meeting, unfortunately neither me or Seangchan will be connected. But please let us know what you decided or more concerns.

**Comment by thongonary** [comment]
Thanks! Now I remember we had quite frequent encounter with similar situations in the past where 1 task has fatal exception (mostly due to misconfiguration) and we only ACDC the other tasks to recover what's possible.
So my answer from me would be no, we like to keep it that way. I will confirm after the discussion at the group meeting.

**Comment by thongonary** [comment]
The conclusion from our meeting was that we would like to keep it the current way.

**Comment by amaltaro** [comment]
Ok, thanks Thong. Closing the issue.
