### ISSUE TITLE
Create a map for Step and OutputDataset including child dataset information

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8681]
Create a map between step and output dataset after assigning the workflow.
1. when workflow is assigned, figure out  mapping between step and output dataset
2. Also parentage between output datasets,  (Using StepName, InputStep, KeepOut parameter)
3. Create the map  [{StepName:  "SomeStep", "OutputDatasets": [], "ParentDataset": parentDataset}, ... ] - this is just sample  data structure. It can be changed.
4. Update the map to spec in couchdb

This will be used by Agent #8676

**Comment by ticoann** [comment]
@amaltaro, Alan, I summarized what we discussed. If I misunderstand something, please feel free to modify the condition.

**Comment by amaltaro** [comment]
Thanks for the summary, Seangchan. While investigating something else, I just noticed `dbsbuffer_dataset` has the parent column that we could use for this purpose. Haven't looked any further though.
