### ISSUE TITLE
Provide the view and property to check the parentage relations to StepChain.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8705]
related to #8701 
1. we can add flag in StepChain spec. - ParentageResolved.
2. provide the reqmgr view to check that with status.

That way we have option to manually fix parentage and test after cmsweb deployment

**Comment by ticoann** [comment]
@amaltaro, Alan what do you think. If you agree. I can create the patch tomorrow and test.

**Comment by amaltaro** [comment]
We only have test stepchains in the system, so I wouldn't worry too much for now.
I believe O&C are aware of the StepChain limitations and they will only resume StepChain injections after they have the green light that we have it all fixed.

My suggestion is not to patch any agents, if needed we can cut a new release in September again.

**Comment by ticoann** [comment]
Added in HG1809
