### ISSUE TITLE
Filter by "input dataset" in wmstats does not work

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8721]
Or maybe it doesn't work for TaskChain workflows only...
Example in production is this input dataset
/ttH_M125_mtop1735_TuneCP5_13TeV-powheg-pythia8/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM

which belongs to this workflow (which is active)
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIIFall17MiniAODv2-01000__v1_T_180414_215925_7580

**Comment by amaltaro** [comment]
no query, just wmstats web ui

**Comment by ticoann** [comment]
Actually that never worked for TaskChain or StepChain. Filter only looks for the top level properties not in Task/Step level properties.
