### ISSUE TITLE
WMAgent runtime memory kill should send SIGTERM instead of SIGUSR2

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8727]
The WMAgent runtime code that kills on RSS and VSize limits sends a SIGUSR2 to the cmsRun process.

CMSSW doesn't actually terminate on this, it just shuts down gracefully at the next event boundary.

Arguably this is not what we want in a production environment when we decide to kill a job.

We should send SIGTERM instead.

**Comment by amaltaro** [comment]
Dup of #8345
