### ISSUE TITLE
WorkQueueManagerWMBSFileFeeder slowly adding data to dbsbuffer tables

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8740]
Related to https://github.com/dmwm/WMCore/issues/8528

I've seen WorkQueueManagerWMBSFileFeeder heartbeat alarms since the past weekend, which is hitting us in at least a couple of agents (vocms0252, vocms0254).

Checking the logs on vocms0252...
```
2018-08-12 15:19:52,946:140043577100032:INFO:WorkQueue:Adding WMBS subscription for vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01118__v1_T_180808_124312_4167
... almost 2 days later ...
2018-08-14 13:11:00,644:140043577100032:INFO:WMBSHelper:Inserting in bulk all the file info into WMBS for vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01118__v1_T_180808_124312_4167
2018-08-14 13:25:55,078:140043577100032:INFO:WMBSHelper:Inserting all the file info into DBSBuffer for vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01118__v1_T_180808_124312_4167
... and now slowly going through these dbsbuffer insertions...
```

and vocms0254 seems to be stuck processing this ACDC
```
2018-08-13 16:30:33,521:139965766612736:INFO:WorkQueue:Adding WMBS subscription for vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01122__v1_T_180808_130708_5376
```

**Comment by amaltaro** [comment]
Given the amount of data objects created, it doesn't surprise me that the memory footprint goes up to 5GB (at least for this specific workflow in vocms0254). I'm working on a debug patch to try to pin point the expensive code sections.

**Comment by amaltaro** [comment]
Sigh... it took me 450 secs to get all that _wmbsPreparation execution for
vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01122__v1_T_180808_130708_5376

in a testbed+mariadb agent.

**Comment by ticoann** [comment]
@amaltaro, Alan it seems it is slow due to the workflow contain so many files in one block

I see in vocms0254 following workflow has 62536 files in one block

Adding ACDC files into WMBS for vlimant_ACDC1_task_HIG-RunIIFall17wmLHEGS114__v1_T_180815_170325_4076: files: 62536

and vocms0252 below workflow has 223K files in one block

Adding ACDC files into WMBS for vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01118__v1_T_180808_124312_4167: files: 223343

And it take long time to check ~0.5 sec 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WMBSHelper.py#L610

**Comment by ticoann** [comment]
I created the patch to improve the performance.

**Comment by ticoann** [comment]
One other question I have is whether we need to add unmerged ACDC files in DBSBuffer.
I guess if we have parents files we need to add it to tract it but in case we don't have parents we might not need this. (In that case, I can create another patch to skip that)

**Comment by amaltaro** [comment]
Good catch, Seangchan! I think we quickly discussed those `exists()` the last time we were investigating this issue.

About unmerged files in DBSBuffer, I can't think of anything else. So I think you're right and we could skip *unmerged* insertion into DBSBuffer, unless those files contain parents.
