### ISSUE TITLE
WMStats reports for some ACDCs are empty

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#8749]
WMStats reports for some ACDCs are empty.

Workflows -

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01415

https://its.cern.ch/jira/browse/CMSCOMPPR-3297
https://its.cern.ch/jira/browse/CMSCOMPPR-3387

Please have a look.

**Comment by amaltaro** [comment]
Same comment as I made in the other issue you opened:
https://github.com/CMSCompOps/WmAgentScripts/issues/301

please provide more info.

**Comment by prozober** [comment]
Hi guys, regarding https://its.cern.ch/jira/browse/CMSCOMPPR-3297, we had a couple of ACDCs with this kind of error report:
https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01415__v1_T_180706_152554_7772
https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/vlimant_ACDC0_task_HIG-RunIIFall17wmLHEGS-01415__v1_T_180706_002140_9878

In those cases, we had one some jobs failing for task RunIIFall17DRPremix with an unknown exit code, from an unknown site.

**Comment by amaltaro** [comment]
This has been fixed with the WMStats changes made in the last couple of months (caused by agent rotation).
