### ISSUE TITLE
No DN recorded for priority change from new to new status

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8778]
Via web UI, without any state change. If the request is in New state, then the box with Priority Transition will not fetch the correct DN, see request (prio 220k)
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ACDC_StepChain_ReDigi3_HG1809_Validation_180901_234933_6208

**Comment by vlimant** [comment]
related to #8916
