### ISSUE TITLE
Log for the ReqMgr2 parentageFixTask thread

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8780]
Looking at the logs on the backend, I see it uses the date from when the process was started, e.g.
vocms0132/reqmgr2/parentageFixTask-20180831.log 

and it never rotates and/or create a new log file when it gets into a new day. Even more interesting, looking at this file now, I can see entries only for today (e.g. 2018-09-03 ...), while the rest is gone.
If one look at vocms055, the file name is the same but the content is from "2018-08-31"...

Weird thing is, it uses the same base class as statusChangeTasks or auxCacheUpdateTasks, and those are rotating just fine (see vocms0731)...

**Comment by ticoann** [comment]
Alan, I don't have problem with this. Do you still have problem?

parentageFixTask-20180912.log     parentageFixTask-20180913.log   parentageFixTask-20180914.log

**Comment by amaltaro** [comment]
Looking at the testbed nodes, I do see different log file names created for it (and other threads).
However, reqmgr2 is missing logs since it was restarted yet, I think we'll need to roll these PR back
https://github.com/dmwm/deployment/pull/664/files

for now, it's better to have dups than no logs at all :(

**Comment by amaltaro** [comment]
I was ready to close it, but I just found the same problem with another reqmgr2 thread. Check this output from a testbed node:
```
[cmsweb@vocms0132 current]$ cat ../logs/reqmgr2/couchCleanup-20180926.log 
2018-09-27 03:02:51,651:INFO:CouchDBCleanup:total 0 requests deleted
2018-09-27 07:02:56,932:INFO:CouchDBCleanup:total 0 requests deleted
[cmsweb@vocms0132 current]$ ls ../logs/reqmgr2/couchCleanup-20180927.log 
ls: cannot access ../logs/reqmgr2/couchCleanup-20180927.log: No such file or directory
[cmsweb@vocms0132 current]$ date
Thu Sep 27 07:11:35 CEST 2018
```

so log from 27Sept written to 26Sept file.
