### ISSUE TITLE
SiteDB API's used by CRAB

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#8783]
as requested by @amaltaro I list all SiteDB API's used by CRAB.
This should be useful also to @lecriste with reference to https://github.com/dmwm/CRABServer/issues/5705

CRAB always does:
```
from WMCore.Services.SiteDB.SiteDB import SiteDBJSON
```
and  from there it uses:

https://github.com/dmwm/WMCore/blob/6686ebd5fa728839f228575dc08de2d7b385bc2c/src/python/WMCore/Services/SiteDB/SiteDB.py#L107
https://github.com/dmwm/WMCore/blob/6686ebd5fa728839f228575dc08de2d7b385bc2c/src/python/WMCore/Services/SiteDB/SiteDB.py#L118
https://github.com/dmwm/WMCore/blob/6686ebd5fa728839f228575dc08de2d7b385bc2c/src/python/WMCore/Services/SiteDB/SiteDB.py#L178

the above list includes client and server.

Finally CRAB client also makes a direct call to
https://cmsweb.cern.ch/sitedb/data/prod/whoami
which I am going to replace with a call to CRIC  (maybe start with CRIC as fallback)

In the client we decided to use the direct curl to sitedb so that we have a shell command which user can see in the log and try themselves interactively to help them understand what is a CRAB problem and what is not.

Let me know if you need more.

**Comment by amaltaro** [comment]
Thanks, Stefano! I'm about to leave on vacation for a week, but I might get a first version of it by tomorrow.

**Comment by belforte** [comment]
ooppps. I pasted the same link twice (and missed one API). will edit previous comment

**Comment by belforte** [comment]
hmm... maybe this is where CRAB server gets the username
which is then stored in the CRAB Task DB and used as needed.
https://github.com/dmwm/CRABServer/blob/e255988da28fe754245e4eb31959b65ccc333964/src/python/CRABInterface/RESTUserWorkflow.py#L622

**Comment by belforte** [comment]
reference to dnUserName is in CRAB Client code, but is never used. 
I am going to remove the reference.
Do not worry about Publisher/utils I do not see whey we need such a reverse lookup. This is the new standalone Publisher which we still need to polish and deploy, I assume we will get rid of that in the process.

**Comment by belforte** [comment]
shall I edit the initial comment to remove the unused API dnUserName ?

**Comment by amaltaro** [comment]
That will be more clear. Yes, please edit the initial description.

**Comment by belforte** [comment]
done. reference to dnUserName will be gone from CRAB Client in next tag.
It may be useful to have such a call in WMCore, for convenience in case of need, but surely no hurry.

**Comment by ticoann** [comment]
Just for the record, Adding Stefano's comments here.

```
About PNN/PSN conversion but there is no constraint of unique mapping, differently from what the comments in the source say.

It is likely that those list conversion are buggy for SiteDB Service already. Is someone using them ?

I think we need to review the signature and semantyc of those functions before we can use them to replace existing code. Or maybe we stay with the simple one-name->a-list-of-names mapping.
```

**Comment by belforte** [comment]
thanks. In other words: either return a list of lists or only implement the lookup for a single name returning one list. The latter is sufficient for CRAB. And yes, we can remave getallcmsnames to getAllPSNs or something
similarly more appropriate, now that it is clear that CMS Name is a not well defined concept.

**Comment by amaltaro** [comment]
I guess this can be closed now. So be it
