### ISSUE TITLE
Create a Service class for Rucio with data discovery APIs

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8796]
https://github.com/dmwm/WMCore/wiki/PhEDEx-to-Rucio-Transition

Related to: https://its.cern.ch/jira/browse/CMSRUCIO-97
and
https://its.cern.ch/jira/browse/CMSRUCIO-37

**Comment by ticoann** [comment]
JIRA ticket. https://its.cern.ch/jira/browse/CMSRUCIO-37

**Comment by amaltaro** [comment]
After #8966
