### ISSUE TITLE
Rotate global workqueue database and recreate views

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8798]
Production global workqueue database is reasonably sized, however it's views have grown beyond the limits and they are almost 50x bigger than the database itself. From CMSWEB's report:
```
TOTAL SIZE(MB)       HOST                   DB NAME    DB SIZE(MB)    VIEWS SIZE(MB)         DOCS      DELETED
-------------------------------------------------------------------------------------------------------
      61814.10  vocms0740                 workqueue        1448.26          60365.84        29618       863516
```

besides that, most of the documents are now deleted.

For further reference, we need to save the permanent docs (non-deleted) into a new database and swap them during the intervetion. I have started this investigation a couple of weeks ago, but I faced several couch crashes and instabilities.

I'll create a wiki page with all the instructions and then we can discuss the final bits, @ticoann

**Comment by amaltaro** [comment]
Production workqueue database was rotated today. It had around 1400 valid docs, 930k deleted docs and it was taking 1.4GB of disk space. Views were contributing to 70GB!!!

New database with the valid docs only has ~20MB and views are around 15MB.
Closing

**Comment by ticoann** [comment]
Wonderful, Thanks Alan, Lina. @amaltaro, @h4d4
