### ISSUE TITLE
ScramArch not in job classads ?

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8820]
Tried to look at what scram archs we use for CMSSW_7_X production jobs (related to #8788) and couldn't find any information about that in ElasticSearch. Isn't this recorded ?

**Comment by amaltaro** [comment]
There is no job classad for it. Instead, we actually map the scramArch to a list of REQUIRED_OS, which goes into the job requirements. I'd say we can probably use that, we mostly care about the OS only in the end (for now):
https://github.com/dmwm/WMCore/blob/a7fcf041cde69c9b55a7f63100a72f1cda2a3578/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L647

**Comment by hufnagel** [comment]
Ok, so we only support rhel5, rhel6 and rhel7 in production right now. That helps. Thanks
