### ISSUE TITLE
Fix Services/PhEDEx/PhEDEx unit tests (currently marked integration)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8826]
I've got 3 out of 5 errors in my VM openstack setup, those are mostly legit errors and need to be fixed.

On the docker setup, I see 4 out of 5 errors and all of them point to "Could not find a valid CA path".

With all these data management discussions going on, we should fix those and re=enable it for jenkins

**Comment by ticoann** [comment]
I will take this Alan.

**Comment by amaltaro** [comment]
This won't be done. Closing
