### ISSUE TITLE
AgentJobInfo not in wmstats info for completed workflow (When Agent is drained)

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8827]
unified used to get AgentJobInfo from https://cmsweb.cern.ch/wmstatsserver/data/request/pdmvserv_task_HIG-RunIIFall17DRPremix-00809__v1_T_180513_171003_961 , but it is not there anymore for some reason. glitch on that one, or a recent change ?

**Comment by amaltaro** [comment]
If there is no AgentJobInfo information in wmstats, that's because the workflow ran in an agent(s) that has been already shutdown/redeployed. Given that wmstats doesn't keep data for more than ... 0.25 days AFAIR, and the agent that handled it is gone from the system, we do not have this information anymore.

**Comment by vlimant** [comment]
BTW https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/pdmvserv_task_HIG-RunIIFall17DRPremix-00809__v1_T_180513_171003_961 seem to still have lots of useful information as can be seen below

![screenshot from 2018-09-26 15-23-21](https://user-images.githubusercontent.com/4989875/46083167-15891180-c1a1-11e8-9c87-d56a21ac4e29.png)

**Comment by amaltaro** [comment]
Just to make sure everyone is aware of it. This is a BIG!!! problem for agent recycling and deployments. In practice - with the current behavior of workflows and P&R Ops - it means it will take half a year to manage to get an agent redeployed. Which will cause all sort of other issues as data volume, agent maintenance, patching, etc etc etc...

This means we need to work on wmstats and increase the data retention for a reasonable amount of time (days? weeks?) and assume that P&R will take the necessary actions within that time window.

PS.: It has data now because I restarted submit4 (which is completely drained but not wiped out yet), which was handling this workflow.

**Comment by amaltaro** [comment]
BTW, that workflow has been sitting in completed for 37 days without any action. We cannot keep data forever.

**Comment by ticoann** [comment]
> config.TaskArchiver.DataKeepDays = 0.125

This is duration for keeping old job summary doc (which is the same as AgentJobInfo). Job Summary information is updated every 10 min, so it keeps the 3 hour history. 

Job record from given given workflow won't be deleted until workflow is archived. That is why you can recover when you revive the agent.

What we probably could do is changing the deleting algorithm. (Keep the summary record for completed workflow even though it is more than 3 hours passed). I will look at the code what need to be done to keep this when agent is drained.

**Comment by ticoann** [comment]
And this is the one, related to cleaning up this information in wmstats (currently set to 3 hours)

https://github.com/dmwm/deployment/blob/master/reqmon/config.py#L109

**Comment by ticoann** [comment]
One other option we can do is instead of creating the new document each summary just update summary document. (I think this would be better option although this won't be a simple change)

**Comment by amaltaro** [comment]
> This is duration for keeping old job summary doc (which is the same as AgentJobInfo). Job Summary information is updated every 10 min, so it keeps the 3 hour history.

just to make sure I understood it. The decision on what is deleted or not is completely on the wmstats side with that config line that you pointed out, right? There is a continuous replication set from local agent/wmagent_summary to cmsweb/wmstats, but I guess we don't replicated docs deleted on the agent (such that it gets deleted in wmstats as well), do we?

Are multiple job summary docs merged together on the wmstats side? Or it takes one doc per agent and uses only the latest one?

I'm trying to figure out whether setting that value to 7 days on the wmstats side would be enough to keep AgentJobInfo around for 7 days, even when we have agents going out of the system.

**Comment by ticoann** [comment]
> The decision on what is deleted or not is completely on the wmstats side with that config line that you pointed out, right? 

Yes

> There is a continuous replication set from local agent/wmagent_summary to cmsweb/wmstats, but I guess we don't replicated docs deleted on the agent (such that it gets deleted in wmstats as well), do we?

No we don't replicate deleted document


> Are multiple job summary docs merged together on the wmstats side? Or it takes one doc per agent and uses only the latest one?

We use only the latest one. The reason we did this way was initially we wanted to keep time series record, but if we keep the data for a week the size was too big and couch is not really handles that well. I think we need to either have different clean up policy or just send one document per agent with the same name (but I think this one won't protect from this case) We can discuss tomorrow.

**Comment by amaltaro** [comment]
Fixed by #8836 , now onto the next problem though #8851 ...
