### ISSUE TITLE
workflow in failed status : need something for ops

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8833]
there's usually no way to tell why a workflow went in to failed status. 
where can the information be extracted from, and exposed ?

**Comment by amaltaro** [comment]
It should have been addressed in this issue https://github.com/dmwm/WMCore/issues/7808
such that that information is available via wmstats logdb records.
I agree it's a PITA to have to look at the cmsweb logs everytime we have a problem like that. I reopened that issue and will close this one.
