### ISSUE TITLE
getDBSSummaryInfo should not raise an exception for blocks with only INVALID files

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8846]
As discussed in a private thread "Error in DBSReader.listDatasetSummary" with Yuyi and CRAB folks, when we call this WMCore/DBSReader `getDBSSummaryInfo`
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L377

passing a block (dataset would be the same) which only contains invalid files, DBSServer returns an empty list as result. However, our code raises a `DBSReaderError` exception in L395.

It seems to be necessary by the GQ start policies, to make sure that this block is skipped all the way up in the chain.

I need to investigate to see what are the required changes if we stop raising this exception.

**Comment by amaltaro** [comment]
FYI: https://its.cern.ch/jira/browse/CMSCOMPPR-3822

possible worth bumping this issue priority.

**Comment by vlimant** [comment]
+1 on increasing the priority. 
we should be able to cope transparently with a dataset that contains a completely empty block. 
maybe by not creating the WQE in GQ?
