### ISSUE TITLE
how to make CRIC use pycurl ?

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#8847]
New Service.CRIC module defaults to httplib2.
But I need to use pycurl which is more available, e.g. on schedd's, we
had gone through a small campaign in past years to make CRAB use only pycurl,
but this is not now not the case and odd errors are popping up.
How can I CRIC to use pycurl,  in lack of an explicit argument like SiteDB API had ?

see old usage:
https://github.com/dmwm/CRABServer/blob/1243414ef7b120699cf7f769570309b3fb09bdbf/src/python/TaskWorker/Actions/DagmanCreator.py#L831

**Comment by belforte** [comment]
basaically SiteDB API allowed to pass a dictionary to the Service init, setting all possible options
https://github.com/dmwm/WMCore/blob/c0f47718d8033fe947798fcc2f659b11e60641c8/src/python/WMCore/Services/SiteDB/SiteDBAPI.py#L34
but CRIC does not accept that dictionary anymore

**Comment by amaltaro** [comment]
I missed this detail. See fix in 8848
