### ISSUE TITLE
Recent workflow missing agent data in wmstats

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8851]
Probably related to this patch #8840

Sharad reported these three prep_ids:
task_EXO-RunIISummer16MiniAODv3-04050
task_EXO-RunIISummer16MiniAODv3-10105
task_EXO-RunIISummer16MiniAODv3-10890

that have data missing in wmstats. I had a look at the first one and its status transition are very recent
```
acquired: 2018-10-13 17:43:09 UTC DN: /DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch
running-open: 2018-10-13 17:53:29 UTC DN: /DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch
running-closed: 2018-10-13 17:53:30 UTC DN: /DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch
completed: 2018-10-14 13:21:44 UTC DN: /DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch
```

it was processed by vocms0280, which was patched and is apparently working without any issues.
I'm investigating why this document hasn't been uploaded to wmstats...

**Comment by amaltaro** [comment]
After looking into vocms0280, I don't really know what the problem is. I added some logging to
sw/slc7_amd64_gcc630/cms/wmagent/1.1.15.patch4/lib/python2.7/site-packages/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py.bkp

and restarted AnalyticsDataCollector and we can see the data gets correctly uploaded/updated to the local couch wmagent_summary db. Which we can double check by checking the document itself in the db
```
cmst1@vocms0280:/data/srv/wmagent/current $ curl -ks -X GET http://BLAH:BLAH@localhost:5984/wmagent_summary/vocms0280.cern.ch-pdmvserv_task_EXO-RunIISummer16MiniAODv3-04050__v1_T_180920_032811_6935
{"_id":"vocms0280.cern.ch-pdmvserv_task_EXO-RunIISummer16MiniAODv3-04050__v1_T_180920_032811_6935",...
```

and the document should show up in wmstats in the following url:
https://cmsweb.cern.ch/couchdb/_utils/document.html?wmstats/vocms0280.cern.ch-pdmvserv_task_EXO-RunIISummer16MiniAODv3-04050__v1_T_180920_032811_6935

via couchdb replication from wmagent_summary to wmstats. Checking the replication status
```
cmst1@vocms0280:/data/srv/wmagent/current $ curl -ks -X GET http://BLAH:BLAH@localhost:5984/_active_tasks
[{"pid":"<0.157.0>","checkpoint_interval":600000,"checkpointed_source_seq":7609806,"continuous":true,"doc_id":"8260bd513361512483388d1a4fd6f3e9","doc_write_failures":0,"docs_read":0,"docs_written":0,"missing_revisions_found":0,"progress":100,"replication_id":"b3f6e9925e98955f5afc2ce0430e6e36+continuous","revisions_checked":10,"source":"https://cmsweb.cern.ch/couchdb/workqueue/","source_seq":7609834,"started_on":1539690025,"target":"http://cmst1:*****@localhost:5984/workqueue_inbox/","type":"replication","updated_on":1539693175},{"pid":"<0.201.0>","checkpoint_interval":600000,"checkpointed_source_seq":38211,"continuous":true,"doc_id":"8260bd513361512483388d1a4fd73775","doc_write_failures":0,"docs_read":10,"docs_written":10,"missing_revisions_found":10,"progress":100,"replication_id":"336419e461dfbe4156057ad9d42367bb+continuous","revisions_checked":10,"source":"http://localhost:5984/workqueue_inbox/","source_seq":38214,"started_on":1539690025,"target":"https://cmsweb.cern.ch/couchdb/workqueue/","type":"replication","updated_on":1539693174}]
```

and voila, the replication to wmstats is NOT there (even though it was a bit earlier). I guess it's automatically restarted in case it fails, because the replication doc has been pushed again to the replicator db.

The replication seems to be crashing and there are messages like
```
[Tue, 16 Oct 2018 12:44:52 GMT] [error] [<0.3583.4>] ChangesReader process died with reason: {function_clause,
...
```
in the couch.log. vocms0281 seems to have the same problem actually.

**Comment by amaltaro** [comment]
Ok, back to it investigating this issue on submit6. I think I found the problem, but still don't know how to solve it.

Looking at the couch log, I see records like:
```
[Wed, 17 Oct 2018 06:37:31 GMT] [info] [<0.19441.703>] 127.0.0.1 - - GET /wmagent_summary/_changes?filter=WMStatsAgent%2Frepfilter&feed=continuous&style=all_docs&since=5772161&heartbeat=10000 500
...
```
just before the replication to wmstats dying. Running the same query with curl, we can see it returns all the revisions for a specific non-deleted doc (style=all_docs). Which is probably where the replication is timing out.

From the couchdb documentation:
http://docs.couchdb.org/en/1.6.1/api/database/changes.html

we should be using the default value `style=main_only` instead of `all_docs`.

I'm now trying to figure out where it's defined and called, however I can't find anything but
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/CMSCouch.py#L468

which turns not to be used anywhere in WMCore (besides a bin script...).

**Comment by amaltaro** [comment]
Those query parameters are internal to the couch database replication and it seems we can't really change them.
I temporarily set couch log level to debug in submit6 and it almost blew up my terminal with very very long lines, no way to parse or even look at that.

Checking the replication algorithm in 
http://docs.couchdb.org/en/1.6.1/replication/protocol.html#algorithm

the changes feed yields pairs of id/rev, which are then passed to the filter function (which in our case should be returning false for all deleted docs - thus all docs but the latest revision). From step 6 in the wiki, it does a bulk update of all non-deleted docs into the target db (and that new_edit:false is something I didn't understand). In summary, I don't see why it would start failing...

**Comment by amaltaro** [comment]
And setting debug mode in vocms0262 (testbed node), I see something _weird_ which might be causing problems (too?).
From the logs, it seems it gets ALL revisions of a document and check for changes in all those revisions compared to the latest one, e.g.:
```
[Tue, 16 Oct 2018 14:38:58 GMT] [info] [<0.5366.0>] 127.0.0.1 - - GET /wmagent_summary/vocms0262.cern.ch-amaltaro_TaskChain_ProdMinBias_Oct2018_Validation_181016_162334_5396?revs=true&open_revs=%5B%221-123456789%22%5D&latest=true 200
[Tue, 16 Oct 2018 14:49:00 GMT] [info] [<0.7364.0>] 127.0.0.1 - - GET /wmagent_summary/vocms0262.cern.ch-amaltaro_TaskChain_ProdMinBias_Oct2018_Validation_181016_162334_5396?atts_since=%5B%221-123456789%22%5D&revs=true&open_revs=%5B%222-123456789%22%5D&latest=true 200
[Tue, 16 Oct 2018 14:59:01 GMT] [info] [<0.9954.0>] 127.0.0.1 - - GET /wmagent_summary/vocms0262.cern.ch-amaltaro_TaskChain_ProdMinBias_Oct2018_Validation_181016_162334_5396?atts_since=%5B%221-123456789%22%2C%222-123456789%22%5D&revs=true&open_revs=%5B%223-123456789%22%5D&latest=true 200
[Tue, 16 Oct 2018 15:09:02 GMT] [info] [<0.12084.0>] 127.0.0.1 - - GET /wmagent_summary/vocms0262.cern.ch-amaltaro_TaskChain_ProdMinBias_Oct2018_Validation_181016_162334_5396?atts_since=%5B%221-123456789%22%2C%222-123456789%22%2C%223-123456789%22%5D&revs=true&open_revs=%5B%224-123456789%22%5D&latest=true 200
[Tue, 16 Oct 2018 15:17:42 GMT] [info] [<0.422.0>] 127.0.0.1 - - GET /wmagent_summary/vocms0262.cern.ch-amaltaro_TaskChain_ProdMinBias_Oct2018_Validation_181016_162334_5396?atts_since=%5B%221-123456789%22%2C%222-123456789%22%2C%223-123456789%22%2C%224-123456789%22%5D&revs=true&open_revs=%5B%225-123456789%22%5D&latest=true 200
```

so a workflow that remains in the system for a longer time will eventually cause problems, since couch has to go through all previous revisions to see what are the changes.

Given that the agent handles <2k requests at a given time, we might have to consider getting rid of this replication and instead POST those directly to cmsweb wmstats.
@ticoann I'll let you digest all this information and point mistakes on my interpretation, then we can discuss a possible solution.

**Comment by ticoann** [comment]
Thank you very much for all the investigation, I remember we set the check point which uses _changes.
It is checked for only revisions in 10 min instead of all the revisions. I wonder whether the interval unit is not correct. (in the document it says millisecond), could we reduce to 1 min and whether it improves ?

```
; checkpoint setup: 10 minutes interval
use_checkpoints = true
checkpoint_interval = 600000
```

Anyway, as you suggested not using the replication for summary doc would be good thing. Since all the summary doc is temporary document we don't care we loses some revisions? I can create the patch for that and see how that goes. 

Thanks a lot, Alan.
