### ISSUE TITLE
submitfailed only for sites in draining for > 24h

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8858]
As just discussed with Sharad @sharad1126, in order to decrease the burden on operations in terms of recovering work from sites that go into drain mode (which triggers submitfailed for some specific cases), we should make it a bit smarter and give jobs a grace period before marking them as failed.

Rough logic is:
* when update the site cache in JobSubmitterPoller, set also a timestamp for that status
* if the site is in drain for less than 24h, then just skip that job from the submitter cycle and move to the next one
* else, if the site is in drain for more than 24h and the job can only run there (no IObound jobs), then mark it as submitfailed.

**Comment by amaltaro** [comment]
@sharad1126 feel free to complement it if I missed anything.

**Comment by sharad1126** [comment]
@amaltaro I don't think you missed anything. Implementing this may decrease failing of workflows due to site being in drain.

**Comment by amaltaro** [comment]
fresh from the meeting, let's set a configurable grace period of 1 month for this. Before that, jobs should just sit in the internal queue waiting for the site to come back to "normal" or moved to "down", which would trigger job removal and ACDC documents creation.

**Comment by vlimant** [comment]
one month is way to large IMO ; one month means essentially that the drain status means absolutely nothing. 2 days is more reasonable as this would allow to really drain bad sites automatically, and prevent submitfail from a ssb metric glitch

**Comment by jenimal** [comment]
The ideal, is if a site goes to drain, and there are any other sites in the whitelist the jobs automatically default over to those sites.  Even if it's a "final round" failure over, give it a try at a site not in drain.

**Comment by amaltaro** [comment]
What you describe is the current behavior, Jen.
Yes, Jean-Roch, I actually agree that 1 month is too much. Unless the first goal is to reduce recoveries, no matter whether that increases tails by a lot, then 1 month makes sense.

**Comment by jenimal** [comment]
This is showing all re-tries were at FNAL

Job Name: 0d27bd43-8e6f-4105-988d-99e642eaa359-0
WMBS job id: 3419724
Workflow: pdmvserv_task_HIG-RunIIFall17MiniAODv2-01428__v1_T_181010_095527_487
Task: /pdmvserv_task_HIG-RunIIFall17MiniAODv2-01428__v1_T_181010_095527_487/HIG-RunIIFall17MiniAODv2-01428_0
Status: jobfailed
Input dataset: /QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM
Site: Unknown
Agent: cmsgwms-submit4.fnal.gov
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
jobcooloff: 2019/1/24 (Thu) 09:49:13 UTC, T1_US_FNAL
jobcooloff: 2019/1/25 (Fri) 05:39:42 UTC, T1_US_FNAL
jobfailed: 2019/1/25 (Fri) 12:46:36 UTC, T1_US_FNAL
Exit code: 71104
Retry count: 3
Errors:
JobSubmit
SubmitFailed (Exit Code: 71104)
The job can run only at a site that is currently in Draining state (WMAgent).T1_US_FNAL

**Comment by vlimant** [comment]
@amaltaro please go ahead with implementing the "N seconds grace period", then we can debate and set it to 2 days.

**Comment by drkovalskyi** [comment]
2 days is too small. While it's probably Ok in practice, it's too short to consider it fixed. We need a reasonably large number just to catch potential problems in setting site in drain. So it should be at least a week.

**Comment by drkovalskyi** [comment]
I had a chat with Jean-Roch about this issue and he pointed out that the larger is the "grace period" the longer it will take to train a site when we do mean that. In this case I agree, 2 days should be a reasonable compromise to avoid failing workflows due to short term state changes and making it hard to use drain status to gracefully shutdown a site.
