### ISSUE TITLE
Add search by secondary input in WmStats

### ISSUE THREAD

**Issue by thongonary** [dmwm/WMCore#8862]
Currently the search box in WmStats only allows search by (primary) input dataset, along with output dataset/prep ID/request name/data range. Could it be possible to add an option to search by secondary input, or allow the input dataset query to search for both primary and secondary input?

**Comment by ticoann** [comment]
@thongonary, Thong, secondary means PileUp dataset, right?

**Comment by amaltaro** [comment]
Yes, either MCPileup and DataPileup
