### ISSUE TITLE
Expose login info outside CherryPy

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#8864]
Hi,

After a discussion with @belforte, we think that all of CRAB's direct usage of CherryPy looks like this:

https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/UserFileCache/RESTExtensions.py#L38

That is, we look at the thread-local request variable to retrieve the `user` member set here:

https://github.com/dmwm/WMCore/blob/0615bd977edd4ad103db7ea24f461aa794c9a104/src/python/WMCore/REST/Auth.py#L108

Could we add a method to `WMCore.REST.Auth` that is basically:

```
def get_user_info():
    return cherrypy.request.user
```

?

With this, we can remove the direct CherryPy usage from CRABServer and make any transition / upgrade simpler.

Brian

**Comment by belforte** [comment]
I was actually thinking this to happen as part of moving from cmsweb FE to
a (THE ?) new authz. via tokens. So introducing a hook to a WMCore method
sounds great. And also the time to go from group/role to a leaner scheme.

**Comment by vkuznet** [comment]
+1

**Comment by belforte** [comment]
would this be a good time to document what cherrypy.request.user is, beside "a dictionary" ? so that we define what user/group/role means and are led to define how to do authz w/o roles ?

**Comment by vkuznet** [comment]
Well, there is no cherrypy.request.user it is us (CMS) who append user to cherrypy.request. This is done in Auth.py module
https://github.com/dmwm/WMCore/blob/0615bd977edd4ad103db7ea24f461aa794c9a104/src/python/WMCore/REST/Auth.py#L108
which use user_info_from_headers function defined here
https://github.com/dmwm/WMCore/blob/0615bd977edd4ad103db7ea24f461aa794c9a104/src/python/WMCore/REST/Auth.py#L3
which by itself defines the dictionary
```
user = { 'dn': None, 'method': None, 'login': None, 'name': None, 'roles': {} }
```

**Comment by belforte** [comment]
I did not say cherrypy defines this. I am asking CMS to be clear,
if you look more in the code there are places where `'group` key is added, and  where it is used e.g. in CRAB REST side. And while good written source can serve as good documentation at times, it is not IMHO a good reason to avoid properly document things in some less hidden place as well.
I guess all I wanted to say that in view of moving to tokes later on it would be good to define an implementation independent protocol and strat using it. Then at some point simply change import from WMCore.REST.auth to WMCore.scitoken.auth or whatever.
Anyhow.. you surely know better, Just tell me what to change in CRAB, or make a PR !

**Comment by vkuznet** [comment]
Ok, I created two PRs, one for WMCore (https://github.com/dmwm/WMCore/pull/8868) and one for CRABServer (https://github.com/dmwm/CRABServer/pull/5758) to fix this issue.
