### ISSUE TITLE
reduce the revision limit on wmstats and change the deployment script accordingly

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8886]
WMStats db size in couch is over 100GB. I am suspecting it is due to the revision limit is set 1000 (default value)

I ran the test on my vm which has 21 documents and takes 54 MB
I reduce the revision limit to 10  (and it reduces the size to half 27MB

We should apply to production agent.
$ curl http://localhost:5984/wmstats/_revs_limit
1000

$ curl -X PUT -d "10" http://localhost:5984/wmstats/_revs_limit
{"ok":true}

$ curl -X POST -H "Content-Type: application/json" http://localhost:5984/wmstats/_compact
{"ok":true}

**Comment by ticoann** [comment]
@amaltaro Alan, I don't think this change will affect production in harms way as we discussed.
We can try on testbed and it if works apply to production (and added to deployment script)
What do you think?

**Comment by amaltaro** [comment]
Situation is becoming critical then, I just checked and wmstats db is taking 149GB at this very moment :(

Looking at the reference you sent via email a couple of days ago:
https://eclipsesource.com/blogs/2012/07/11/reducing-couchdb-disk-space-consumption/#comment-16725

it looks like the difference between 10 and 100 revisions is almost none. In order to go safer and avoid any future possible issues with replication, I'd set it to 100. Then we need to trigger compaction to get rid of some of the old data.
I'm contacting Lina right away.

**Comment by amaltaro** [comment]
Apparently we gained only 300MB by setting wmstats rev_limit from 1000 to 100 in testbed. DB size was 7.3GB before compaction and 6.9GB after it (and all this gain might not have come from the revision changes only...).

We're going to set it to 10 now and run it once again.

**Comment by ticoann** [comment]
Hi Alan, testbed won't be affected since there is no new agent attached it. It only will take effect if the documents has a lot of revisions. The reduced sized is probably due to the deleted document.
i would go with 50 revisions in production just for the safe side.

**Comment by amaltaro** [comment]
Compaction finished and the final database has 6.9GB with 10 revs_limit. As we chatted, there are only a few requests with tons of revisions, so testbed doesn't reflect much what we have in production.
However, if it really made difference, I'd expect to see different numbers between 10 and 100.

Seangchan, we can keep discussing it via Slack, it seems to require further investigation before we push it in prod.

**Comment by ticoann** [comment]
Difference would be really small. since there are only 11 documents (total 8100 document), I would expect reduce the size < 5 MB between 100 and 10 revision.

**Comment by amaltaro** [comment]
Thanks to Lina @h4d4 , this has been applied to both testbed and production wmstats nodes.
Reference for her gitlab ticket is: https://gitlab.cern.ch/cms-http-group/doc/issues/130

and as we discussed on Friday, we set it to 50 revisions.
Compaction is running now, original db size is 160GB.

**Comment by ticoann** [comment]
Thanks Alan, Lina. Is compaction still running?

**Comment by h4d4** [comment]
@ticoann 
Seangchan, there is a new compaction, please see below:

Apache CouchDB is running as process 3862, time to relax.
[{"pid":"<0.604.2475>","changes_done":1357,"database":"wmstats","progress":35,"retry":true,"started_on":1541414193,"total_changes":3773,"type":"database_compaction","updated_on":1541430250}]
Best Regards, Lina.

**Comment by amaltaro** [comment]
Apparently the compaction went through over the last night and the current database size is 126GB.
That means we need to go with the plan B, which is patching the agents and dumping central wmstats tomorrow or so.

**Comment by amaltaro** [comment]
To summarize:
* both testbed and production wmstats database were changed to 50 _revs_limit (this change is database specific, not couch-wide)
* wmstats db size is ~3.5GB only. Thus we should be back a stable situation now.

Thank you very much for sorting all these issues out, Seangchan! I'm closing this ticket, feel free to reopen if there is anything left to follow up.
