### ISSUE TITLE
Remove legacy crab config from wmagent-mod-config

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8926]
@belforte @lecriste can you please confirm whether we can safely remove these sections from this code:
https://github.com/dmwm/WMCore/blob/master/bin/wmagent-mod-config#L158-L189

and a few other like `CRABInterface` and etc? I guess it's no longer used by CRAB, is it?

**Comment by lecriste** [comment]
@dciangot is working on a new ASO version and may comment more.

**Comment by amaltaro** [comment]
I was going to ssay that I couldn't find where or how it's actually used, but I do see some sections in the code like this
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/CleanerDaemon.py#L90

but then looking into the ASO deployment code, there we go:
https://github.com/dmwm/deployment/blob/master/asyncstageout/manage#L246

so we cannot delete those (and I was actually removing that `amq_auth_file` in another PR, so let me get that back into the module).

**Comment by belforte** [comment]
thanks Alan. Sorry for the trouble. We will try to get rid of this stuff asap.

**Comment by amaltaro** [comment]
No worries, I don't want to remove code in use. However, it makes me really happy to wipe out all the garbage that is not needed by anyone or not used. Thanks, Stefano. I'm closing this issue.
