### ISSUE TITLE
1.1.19.pre5 wmagent deploy script overcounts leftover processes

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#8942]
The following line counts for leftover WMAgent processes before moving forward:
https://github.com/dmwm/WMCore/blob/1.1.19.pre5/deploy/deploy-wmagent.sh#L150

The problem is, this will always produce a result greater than 1 in my tests, because it's grepping for wmagent(matching the deploy-wmagent.sh script itself, and the grep command being executed with the script):

``` 
cmst1    3027742  0.0  0.0 113288  1608 pts/0    S+   22:31   0:00 sh deploy-wmagent.sh -w 1.1.19.pre5 -d HG1811a -t testbed-dev -r comp=comp -c kwmcore.cern.ch
cmst1    3027757  0.0  0.0 112708   960 pts/0    S+   22:31   0:00 grep -E couch|wmcore|mysql|beam
```

For now, I'm using
output=`ps aux | egrep 'couch|wmcore|mysql|beam' |  grep -v deploy-wmagent.sh | wc -l`
instead. Does that look good?

**Comment by khurtado** [comment]
That’s fine with me :). However, there should probably be some warning in
the documentation if the deployment scripts are going to have that
restriction, I think it’s not so obvious  you should expect your agent
deployment to fail if your host name ever contains any of the strings :
beam, couch, mysql or wmcore in it

**Comment by ticoann** [comment]
I think might be more robust to filtering out "deploy-wmagent.sh" since it doesn't force the vm name to not contain any specific words. Although, for production agent names are pretty standard for individual vm names are not. If Kenyi or anyone want to name his/her vm, let them do it. :-)

**Comment by amaltaro** [comment]
@khurtado thinking about this issue once again. How about we stick to your suggestion and filter out `deploy-wmagent.sh` from the grep command? Can you take care of it?
