### ISSUE TITLE
T0 paused jobs not showing up in tier0_wmstats

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8960]
They do show up in the lower table, with job details, however the upper table with tasks/jobs overview has 0 paused jobs for every single task. A screenshot can be seen here:
https://www.dropbox.com/s/8vwlvoqi02mcmwj/T0_paused_Issue8960.png?dl=0

I also checked that job (938077) in the agent (vocms0313) and I confirm it's in the jobpaused status, which can be confirmed from this link as well:
https://cmsweb.cern.ch/t0_reqmon/data/jobdetail/PromptReco_Run326790_HIHardProbes

While the requestcache API
https://cmsweb.cern.ch/t0_reqmon/data/requestcache

doesn't list those jobpaused under the `AgentJobInfo`
```
    "AgentJobInfo": {
      "vocms0313.cern.ch": {
        "status": {
          "queued": {
            "retry": 1, 
            "first": 270
          }, 
          "success": 720
        }, 
        "agent_team": "REPLACE_TEAM_NAME", 
        "workflow": "PromptReco_Run326790_HIHardProbes", 
        "timestamp": 1546862386, 
        "_rev": "1-32387e3fc3cf0c6b3d1923ece9931a03", 
        "sites": {
          "T2_CH_CERN": {
            "queued": {
              "retry": 1
            }, 
            "success": 720
          }
        }, 
        "agent": "WMAgentCommissioning", 
        "skipped": false, 
        "tasks": {
          "/PromptReco_Run326790_HIHardProbes/Reco/AlcaSkim": {
            "status": {
              "queued": {
                "first": 270
              }, 
              "success": 1
            }, 
            "sites": {
              "T2_CH_CERN_HLT": {
                "inputEvents": 27678, 
                "cmsRunCPUPerformance": {
                  "totalJobCPU": 7912.017999999999, 
                  "totalJobTime": 10019.858999999999, 
                  "totalEventCPU": 7599.829
                }, 
                "wrappedTotalJobTime": 11179, 
                "dataset": {}
              }, 
              "T2_CH_CERN": {
                "inputEvents": 1605, 
                "cmsRunCPUPerformance": {
                  "totalJobCPU": 532.359, 
                  "totalJobTime": 674.0709999999999, 
                  "totalEventCPU": 508.74600000000004
                }, 
                "wrappedTotalJobTime": 733, 
                "success": 1, 
                "dataset": {}
              }
            }, 
            "jobtype": "Processing", 
            "subscription_status": {
              "updated": 1542537008, 
              "total": 1, 
              "open": 1, 
              "finished": 0
            }
          },
... 
```

**Comment by andresfelquintero** [comment]
Apparently the problem is when the data goes from couchdb to wmstats. Can I have access to the API code? or is it not available??

**Comment by amaltaro** [comment]
It turns out the actual problem was with a broken couchdb view. I had to delete the view file for:
wmagent_jobdump/jobs

including an old .compact leftover file, restarted the agent and couch and waited for almost 2h to get the view re-created. The file size is now only 3.1GB, against the 60GB that it was before.

The overview table (upper one) seems to be up-to-date again and I can see failures and etc for the workflow mentioned above: PromptReco_Run326790_HIHardProbes

Let me close this issue.
