### ISSUE TITLE
Grace period on site going in Drain

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8961]
site going in drain for couple of hours / day : i.e. a very limited amount of time may cause havoc in operation. 
is there a mechanism that can be implemented for waiting N-hours (N=24?) from the time a site appears in drain and the time it takes effect to have jobs removed ?

should there be an other ssb/cric status like "transitionally bad" instead ?
this would also serve as a "pause" state (preventing submission to that site, but not fail the jobs with submit failures)

**Comment by vlimant** [comment]
#8858 indeed

**Comment by amaltaro** [comment]
Closing as dup of #8858
