### ISSUE TITLE
Workflow without reqmgr_workload spec file in couchdb

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8978]
@vlimant reported failures in one of the unified modules and the apparent problem is that the workflow was created, with the proper reqmgr_workload_cache request doc in the database (couchdb)
https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_task_SUS-RunIISummer16NanoAODv4-00040__v1_T_190124_181348_3206

but somehow the spec file for the same workflow is missing:
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_SUS-RunIISummer16NanoAODv4-00040__v1_T_190124_181348_3206/spec

The request status is New, and since it's related to couch, we can't have an atomic operation. However, we should likely invert the order in which these documents get persisted into the database. Having a spec file in there doesn't hurt, but the inverse does.

One more thing, the fetch API fails to find this same workload_cache because it tries to load the spec file for the splitting view
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_SUS-RunIISummer16NanoAODv4-00040__v1_T_190124_181348_3206

To be investigated whether the same happened with workflows in other status...

**Comment by vlimant** [comment]
so the issue is present for all wf in "new" ? looks like indeed
