### ISSUE TITLE
Is there a way to catch unsuccessful uploads to DQMGUI?

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/WMCore#8986]
Can a flag be created on the DQMUpload code that is set when a DQMIO file is harvested and uploaded correctly to the DQMGUI, but the file is empty and shows no results?  The DQM team wants to be aware of these kind of problems and they are requesting a flag or something that shows when an empty file gets uploaded to the DQMGUI. Also they want to keep (in EOS probably) the file that is produced after the harvesting for some time instead of deleting it right away after it is uploaded. If they keep the file for some time it will allow us to reupload it if something goes wrong. Is it possible to allocate some space for this topic?

**Comment by amaltaro** [comment]
Andres, we might be able to flag a job in the JobFactory/JobCreator in case the sum of files to be harvested don't have any lumi section, such that we could for instance skip this job and/or mark as createfailed or so.

Finding this information during runtime is going to be a bit trickier, we do not check the root file produced out of the harvesting job. The root file is also not staged anywhere, it's simply uploaded to the DQMGUI and that's it, so once the job exists the worker node, that root file is lost.

What's the impact on having an "empty file" in the DQM Gui?

**Comment by andresfelquintero** [comment]
DQM people told me that if they have empty files on DQMGUI they won't be able to notice an issue after some time has passed, and it will prevent them from harvesting the job again due to the input files being erased faster than they could check some of the uploads. They are looking at that flag as a way to notice it sooner and be able to reharvest it.

**Comment by vytjan** [comment]
Alan, the impact is that if the upload fails, then they cannot certify the failed upload PD for that run (or whatever certification is done).

The discussion about handling DQM Harvesting job output is in progress on JIRA:
https://its.cern.ch/jira/projects/CMSTZ/issues/CMSTZ-753
And there is no clear decision yet on how we want to avoid these upload failures.

**Comment by amaltaro** [comment]
Then I suggest we just follow it there to avoid x-discussion in these two issues.

Failing to upload is one thing, uploading a valid root file with no content is something completely different (and considered as a successful jobs). We need to get these basics straight first.

I'll join that discussion once I have a free slot, and we can come back here once we have the final requirements and wanted behaviour.

**Comment by andresfelquintero** [comment]
This was solved and needs to be tested on Run 3 but there should not be any problem with it.
