### ISSUE TITLE
Possible misconfiguration with the secondary input

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8997]
Also related to https://github.com/dmwm/WMCore/issues/8983
and initially reported and discussed over this JIRA ticket: https://its.cern.ch/jira/browse/CMSCOMPPR-4523

I'm still debugging it, but I have strong suspicious on a badly configured pileup task. More news this afternoon.

**Comment by sharad1126** [comment]
Looking forward for more info and solution. Thanks Alan.

**Comment by amaltaro** [comment]
After running further tests, I can confirm that the problem comes from the PSet configuration.
In terms of WMCore execution during runtime, this is the line
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L460

that returns None (so the mixing module is missing both the "input" and the "secsource" attributes).

Here is a recipe on how to reproduce this problem (as it's executed by SetupCMSSWPSet during runtime) for this request:
sagarwal_task_EXO-RunIIFall18wmLHEGS-00129__v1_T_190202_174312_198

First create a CMSSW project area/environment (the same as used by Task2/EXO-RunIIAutumn18DRPremix-00492_0):
```
cd workarea/WMCore_8997/
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc6_amd64_gcc700
scram project CMSSW_10_2_5
cd CMSSW_10_2_5/src
cmsenv
```

Either copy the PSet.* files reported by Unified in the failed jobs, or copy the original PSet uploaded with the request (I'll take the original one):
```
voms-proxy-init -rfc -voms cms -valid 1:00
export X509_USER_PROXY=/tmp/x509up_u5514
wget -nv --certificate=$X509_USER_PROXY --private-key=$X509_USER_PROXY --ca-certificate=$X509_USER_PROXY https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/4c4ea798b91f11a4e308766bde52b153/configFile
```

Now we import this PSet and run the same manipulation as done by WMCore on the worker node, basically:
```
python  # run the python interpreter

processMod = __import__("PSet", globals(), locals(), ["process"], -1)
process = processMod.process
mixModules, dataMixModules = [], []

prodsAndFilters = {}
prodsAndFilters.update(process.producers)
prodsAndFilters.update(process.filters)
for key, value in prodsAndFilters.items():
  if value.type_() in ["MixingModule", "DataMixingModule"]:
    mixModules.append(value)
  if value.type_() == "DataMixingModule":
    dataMixModules.append(value)

len(mixModules)
len(dataMixModules)

for m in mixModules:
  print "module type %s" % type(m)
  for pileupType in ['mc']:
    print "pileupType %s" % pileupType
    inputTypeAttrib = getattr(m, "input", None) or getattr(m, "secsource", None)
    print "inputTypeAttrib %s" % inputTypeAttrib
```

which should print `inputTypeAttrib None`. And voilà, that's why the PSet ran on the worker nodes don't have a SINGLE file in the secondary list, because a) the original configuration doesn't and b) the PSet tweak does not add a single file to that list either.


To make sure I did not make any mistake, I did the same checks for this Fall17 request:
pdmvserv_task_EXO-RunIIFall17wmLHEGS-00597__v1_T_190126_120534_1013

which does NOT have a list of secondary files in the original PSet. I managed to list a secsource attribute under the mixModules, something like:
```
... 
module type <class 'FWCore.ParameterSet.Modules.EDProducer'>
pileupType mc
inputTypeAttrib None
module type <class 'FWCore.ParameterSet.Modules.EDProducer'>
pileupType mc
inputTypeAttrib cms.SecSource("EmbeddedRootSource",
...
```

explaining why the request has succeeded.

**Comment by amaltaro** [comment]
Question now is, should we **always** overwrite the original list of secondary files? If so, then this is something we have to fix in WMCore. @vlimant

**Comment by vlimant** [comment]
this https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/4c4ea798b91f11a4e308766bde52b153/configFile is the configuration of https://cmsweb.cern.ch/reqmgr2/fetch?rid=sagarwal_task_EXO-RunIIFall18wmLHEGS-00129__v1_T_190202_174312_198 and has 

process.mixData.input.fileNames = cms.untracked.vstring([]) 

indeed, but this means that mixData does have the "input" attribute ...

can you add a print for the module name in your test ?

**Comment by vlimant** [comment]
from that configuration 

>>> process.mixData.type_()
'PreMixingModule'

**Comment by vlimant** [comment]
please go ahead with changing 

> if value.type_() in ["MixingModule", "DataMixingModule"]:

to 

> if value.type_() in ["MixingModule", "DataMixingModule", "PreMixingModule"]:
