### ISSUE TITLE
Provide the full CMSSW exit code from the job report (if possible)

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#9006]
We currently use `condor_chirp` to report the Linux-provided exit code from CMSSW:

https://github.com/dmwm/WMCore/blob/0615bd977edd4ad103db7ea24f461aa794c9a104/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L236

However, this is an 8-bit exit code: CMSSW's framework job report provides a more detailed exit code.

If the exit code is non-zero, the framework job report exists and is parseable, we should provide the error code from CMSSW instead of the one from Linux.

**Comment by bbockelm** [comment]
Note that if we have a non-zero exit code and the framework job report parsing throws an exception, then we should suppress the exception and utilize the Linux exit code instead when constructing the `CmsRunFailure` WMExecutionFailure.

**Comment by belforte** [comment]
++1 for suppressing that exception which always makes it look WMCore failed when it was simply the user application which did it !
