### ISSUE TITLE
Decrease MaxWallTimeSecs limit in the agents config to 2750min (instead of 2760)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9028]
In order to avoid the 25% rounding that would bring this up to 3000mins, thus making it impossible to run in many sites.

**Comment by vlimant** [comment]
please ping so that we roll back https://github.com/CMSCompOps/WmAgentScripts/commit/ddfda82367fece660bada6bf8e905000addcfeae

**Comment by amaltaro** [comment]
@vlimant fix is now in place in all the agents. Thanks
