### ISSUE TITLE
Block still opened in Phedex

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#9031]
from time to time there are blocks that end up still opened 

https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?dataset=/TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM&complete=n

what is the simplest phedex api call that one can do to set is_open="n" ?
can the block-closing part of the agent be made more resilient, or does it nothing to do with agents ?

**Comment by amaltaro** [comment]
I don't see any block opened on the dataset you mentioned above.
Isn't it the same issue as this:
https://github.com/dmwm/WMCore/issues/8148
?

If so, please close this one.

**Comment by vlimant** [comment]
that block was closed with https://github.com/CMSCompOps/WmAgentScripts/pull/387 already

**Comment by vlimant** [comment]
not related to #8148 as far I can tell, it happens when workflows arrive for assignment, and not all blocks are closed in phedex (protection in unified, that would now close all such block)

**Comment by amaltaro** [comment]
Please provide block name(s) for the next time this issue happen. Best would be not to close them in Unified such that we can reliably debug this issue.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?dataset=/EGamma/Run2018D-v1/RAW&complete=n

<phedex request_version="2.5.0pre1-comp" request_timestamp="1550654586.3116" request_call="blockreplicas" instance="prod" request_date="2019-02-20 09:23:06 UTC" request_url="http://cmsweb.cern.ch:7001/phedex/datasvc/xml/prod/blockreplicas"><block bytes="3622223990638" files="500" name="/EGamma/Run2018D-v1/RAW#b802605b-c501-4640-8b2c-4101a48cfefa" is_open="y" id="10196171"><replica bytes="3622223990638" files="500" node="T1_IT_CNAF_MSS" time_create="1536066151" time_update="1541503977" group="DataOps" se="TAPE.cr.cnaf.infn.it" custodial="y" node_id="8" subscribed="y" complete="n"/><replica bytes="3622223990638" files="500" node="T0_CH_CERN_Export" time_create="1536067503" time_update="1541501879" group="" se="" custodial="n" node_id="1" subscribed="n" complete="n"/><replica bytes="3622223990638" files="500" node="T1_IT_CNAF_Disk" time_create="1536066151" time_update="1541502771" group="AnalysisOps" se="storm-fe-cms.cr.cnaf.infn.it" custodial="n" node_id="661" subscribed="y" complete="n"/><replica bytes="3622223990638" files="500" node="T1_IT_CNAF_Buffer" time_create="1536815666" time_update="1541502480" group="" se="TAPE.cr.cnaf.infn.it" custodial="n" node_id="7" subscribed="n" complete="n"/><replica bytes="3622223990638" files="500" node="T0_CH_CERN_MSS" time_create="1536066151" time_update="1541501809" group="DataOps" se="srm-cms.cern.ch" custodial="y" node_id="2" subscribed="y" complete="n"/></block></phedex>

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?dataset=/TprimeBToTZ_M-1800_LH_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM&complete=n

<phedex request_version="2.5.0pre1-comp" request_timestamp="1550654631.48823" request_call="blockreplicas" instance="prod" request_date="2019-02-20 09:23:51 UTC" request_url="http://cmsweb.cern.ch:7001/phedex/datasvc/xml/prod/blockreplicas"><block bytes="16650316081" files="6" name="/TprimeBToTZ_M-1800_LH_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM#fc60df3d-dc21-44d4-b36e-cc9b1d4ca9ba" is_open="y" id="9688021"><replica bytes="16650316081" files="6" node="T1_US_FNAL_Disk" time_create="1526083562" time_update="1526579448" group="AnalysisOps" se="cmsdcadisk01.fnal.gov" custodial="n" node_id="1781" subscribed="y" complete="n"/><replica bytes="16650316081" files="6" node="T0_CH_CERN_Export" time_create="1526678006" time_update="1526685856" group="" se="" custodial="n" node_id="1" subscribed="n" complete="n"/><replica bytes="16650316081" files="6" node="T1_UK_RAL_Disk" time_create="1540802211" time_update="1540889028" group="AnalysisOps" se="gridftp.echo.stfc.ac.uk" custodial="n" node_id="2301" subscribed="y" complete="n"/><replica bytes="16650316081" files="6" node="T0_CH_CERN_MSS" time_create="1526677101" time_update="1526695338" group="DataOps" se="srm-cms.cern.ch" custodial="y" node_id="2" subscribed="y" complete="n"/><replica bytes="16650316081" files="6" node="T2_UK_London_IC" time_create="1545889568" time_update="1545900833" group="AnalysisOps" se="gfe02.grid.hep.ph.ic.ac.uk" custodial="n" node_id="47" subscribed="y" complete="n"/></block></phedex>

**Comment by vlimant** [comment]
since we have a hack-around in unified, let's forget about this

**Comment by amaltaro** [comment]
Clarifying - as per our last discussion on this subject - that the workaround implemented in Unified is only meant to be applied to blocks that are not under production by any agent/workflow, otherwise we might hit unexpected issues with PhEDEx/DBS registration.
