### ISSUE TITLE
Set create_by and creation_date for blocks uploaded to DBS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9042]
Not sure whether the agent already does that or not, but looking at one block that was produced in production, I see Null for both of those fields at file level, e.g.:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?block_name=/WminusH_HToZZTo4L_M190_13TeV_powheg2-minlo-HWJ_JHUGenV7011_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM%239fef307a-6fe4-4dce-9df1-ca700e5dc7a9&detail=true

**Comment by amaltaro** [comment]
DBS issue created to track it on the server side as well: https://github.com/dmwm/DBS/issues/615

**Comment by goughes** [comment]
Closing this as it is not necessary. More info here: https://github.com/dmwm/DBS/issues/615
