### ISSUE TITLE
SubmitFailed not reporting site in wmstats

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#9047]
for pdmvserv_task_HIG-RunIIFall18wmLHEGS-00388__v1_T_181126_083424_8286 for example, job failed with SubmitFailed but the site is not reported in wmstat (while it should to my understanding, @amaltaro ?)

**Comment by amaltaro** [comment]
Actually the site is reported under job detail info (when you expand one of the jobs), e.g.:
```
Errors:
    JobSubmit
        SubmitFailed (Exit Code: 71104)
            The job can run only at a site that is currently in Draining state (WMAgent).T2_UK_London_Brunel
```

but I agree that it should be also reported under the `site` column in the lower/job table.

**Comment by vlimant** [comment]
#6868 #7018

**Comment by vlimant** [comment]
given the wish to run more automated operation, it is crucial to have the site properly reported programmatically (i.e. not only "readable" in the error text)

**Comment by bbockelm** [comment]
@amaltaro - is this something that @khurtado can work on?

**Comment by amaltaro** [comment]
Sure, I see no reason why not. Assigning it to Kenyi
