### ISSUE TITLE
Use bypassVersionCheck in merging step

### ISSUE THREAD

**Issue by srimanob** [dmwm/WMCore#9054]
Following the discussion in 
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4413.html

we would like to have
process.source.bypassVersionCheck = cms.untracked.bool(True)
in the merge process. This is needed urgently, to allow validation for MC trigger menu happen. The plan is to try to read RAW from 10_6, and run HLT step on original release then write the new RAW out to pass to RECO step.

**Comment by vlimant** [comment]
@amaltaro I cannot think of drawbacks in doing this for any merge step (i.e. not a configurable feature). do I remember right that this goes in https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/python/Merge.py which means we do not have to change anything on wmcore ?

**Comment by amaltaro** [comment]
Yes, that's how merge process is created:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L204

the only possible drawback might be in the case we screw up something in WMCore, then we no longer have the mechanism to spot such incompatibilities between processing and merge (as we did a couple of years ago when StepChain was being commissioned).

**Comment by srimanob** [comment]
Should we look for possibility to add more option on Merge.py to bypassversion only by intension, then this option need to pass somehow with the workflow?

I am looking around, and try to see example how we merge DQMIO, or NanoAOD in
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L613-L722

**Comment by vlimant** [comment]
@amaltaro would you prefer to have a configurable switch ? looks heavy to me, and the use case you point out can be seen otherwise ; your call.
the default value

bypassVersionCheck  = True

can be set either in mcm, wmcontrol, or wmcore.

**Comment by srimanob** [comment]
@vlimant Not sure I understand, how we can set it in McM, WMControl to touch merge step without updating CMSSW? Do I miss some keypoint?

In case we need to update the Merge in CMSSW, I prepare the PR
https://github.com/cms-sw/cmssw/pull/26030

**Comment by amaltaro** [comment]
I think we set it to True in the Merge.py and be done with it. 
The drawback aforementioned isn't enough to make it configurable in a workflow basis.

@srimanob that means you'd have to update your patch from
`bypassVersionCheck = options.get("bypassVersionCheck",False)`
to
`bypassVersionCheck = options.get("bypassVersionCheck", True)`

**Comment by vlimant** [comment]
ok. good !
