### ISSUE TITLE
problems with setSchema in unit tests

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#9062]
Initializing the schema in Tier0 unit tests doesn't work anymore. It seems at some we introduced a dependency between the DBSBuffer and WMCore schema that forces us now to initialize the DBSBuffer schema first (which is why such dependencies are a bad idea in general) and only then add the WMCore schema. If I am trying to extend this to include the T0 schema I get problems

        logging.getLogger().setLevel(logging.DEBUG)
        self.testInit.setSchema(customModules = ["WMComponent.DBS3Buffer",
                                                 "WMCore.WMBS",
                                                 "T0.WMBS"],
                                useDefault=False)

and I run the unit test and it only prints out this

DEBUG:root:Tables for WMCore.WMBS created
DEBUG:root:Problem creating database table

ALTER TABLE dataset_locked
                 ADD CONSTRAINT dat_loc
                 FOREIGN KEY (dataset_id)
                 REFERENCES dbsbuffer_dataset(id)
                 ON DELETE CASCADE

(DatabaseError) ORA-00942: table or view does not exist

which is as expected since initializing the WMCore first doesn't work due to the dependency. Problem is, I called it with the DBSBuffer schema first, so why is it trying to initialize the WMCore schema first?

@andresfelquintero should be following up on this with @amaltaro

**Comment by amaltaro** [comment]
How about adding instructions on how to setup T0 unit tests and also which unit test fails here?

**Comment by andresfelquintero** [comment]
Hello Alan. I am going to add here the procedure but we will create a twiki on this later on. 
So first of all we need to run this shell script on a virtual machine, we are currently using vocms015. The shell script is:

BASE_DIR=/data/tier0
DEPLOY_DIR=$BASE_DIR/srv/wmagent

# Necessary variables
export WMAGENT_SECRETS_LOCATION=$BASE_DIR/admin/WMAgent.secrets
export X509_USER_CERT=$BASE_DIR/certs/servicecert-vocms001.pem
export X509_USER_KEY=$BASE_DIR/certs/servicekey-vocms001.pem
#export X509_HOST_CERT=$BASE_DIR/certs/hostcert.pem
#export X509_HOST_KEY=$BASE_DIR/certs/hostkey.pem

#Very convenient variables
export install=$DEPLOY_DIR/current/install/tier0
export config=$DEPLOY_DIR/current/config/tier0
export manage=$config/manage

#export STAGE_SVCCLASS=t0export
#export current=$DEPLOY_DIR/current
#export WMAGENT_SITE_CONFIG_OVERRIDE=/afs/cern.ch/cms/SITECONF/T0_CH_CERN/JobConfig/site-local-config.xml

# special Tier0 variables
export DATABASE=oracle://CMS_T0AST_REPLAY4:NotAPassword@INT2R
export COUCHURL=http://admin:couch@localhost:5984
export WMAGENT_CONFIG=$DEPLOY_DIR/current/config/tier0/config.py

source $DEPLOY_DIR/current/apps/t0/etc/profile.d/init.sh

export PYTHONPATH=$BASE_DIR/admin/nose-1.1.2/build/lib:$PYTHONPATH

After it was run, then the virtual machine's database should be wiped by using /data/tier0/00_wipe_t0ast.sh .

Then we run python /data/tier0/T0/test/python/T0_t/WMBS_t/RunConfig_t/RunConfig_t.py where this error appear. This is the code for RunConfig_t.py https://github.com/dmwm/T0/blob/master/test/python/T0_t/WMBS_t/RunConfig_t/RunConfig_t.py

**Comment by andresfelquintero** [comment]
This summarizes the process until now. https://github.com/dmwm/T0/wiki/Running-a-Unit-test-on-Tier0

**Comment by hufnagel** [comment]
I found the problem

https://github.com/dmwm/WMCore/blob/master/src/python/WMQuality/TestInit.py#L188

reorders the list if schemas to initialize in unpredictable ways since a dict in python doesn't have a predictable order. The order you get keys out of a dict is not necessarily the order you add elements to the dict. Which is what happens here (confirmed with print statements).
