### ISSUE TITLE
Repurpose PhEDExInjector towards the Rucio service

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9065]
Or we create a brand new RucioInjector component inheriting some of the PhEDExInjector functionality. Internal logic might change quite a bit, so we might write a new component from scratch and have a switch to either use RucioInjector or PhEDExInjector.

**Comment by ericvaandering** [comment]
Tracked by Rucio project in https://its.cern.ch/jira/browse/CMSRUCIO-49

**Comment by amaltaro** [comment]
From the PhEDExInjector docstring, it's basically making 4 operations:
```
 - injecting files
 - closing blocks
 - making subscriptions (if requested to)
 - deleting blocks (for copy+delete subscriptions - used only by T0 at the moment)
```

and those map to the following Rucio operations:
```
First, let's start saying that a phedex data injection corresponds to adding a replica in a given scope+rse in Rucio. Here is the flow of actions to inject data into Rucio
  * a rule needs to be created beforehand in order to protect your replica (NOTE: scope needs to be defined for any of those data types)
  * then we create a rucio container (if it already exists, just use it)
  * then we create a rucio dataset (those should be unique)
  * next, we need to attach that rucio dataset to a container
  * then we add replicas to the RSE (and scope)
  * last but not least, we attach_dids (new replicas) to the rucio dataset
NOTE: look into add_files_to_dataset API (DID Client), we might be wrapping a bunch of these operations into the same API.
```

About closing CMS blocks, we can look into the `close` method which is meant to close either rucio datasets or containers.

@ericvaandering please let me know if I misunderstood anything here

**Comment by ericvaandering** [comment]
Well, the rule creation has to come after container or dataset creation depending on what the rule covers.

**Comment by amaltaro** [comment]
Thanks, Eric. I've updated my comment above.

In addition to that, there was a discussion on how we can handle output dataset subscription as well. We can probably keep the same logic we have at the moment, which means we create rucio rules for the output datasets to be kept and transferred around. To be investigated possible multiple rucio rules to make sure intermediate blocks/files remain available until further tasks are done with them.

About rucio subscriptions, they are like rules generator, where we'll likely use it in the future for campaigns or larger data placement. It can take a regular expression as one of the arguments and any data (according to the `did_type`) matching the regex would get evaluated and maybe a rule created for it. 

A location needs to be provided to the subscription as well, and location can mean many things here. It could either be an RSE, or a country, or a region, and so on.
