### ISSUE TITLE
Duplicate lumi section in ACDC for MCFakeFile

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9074]
@vlimant was asking me about duplicate lumi sections that are lately showing up too often in production.
This is the JIRA ticket for that prepID:
https://its.cern.ch/jira/browse/CMSCOMPPR-4903

and here is the Unified report (search for duplicate):
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_SUS-RunIIFall18wmLHEGS-00025&module=checkor&limit=5000

Jean-Roch also provided me with the lumi number and files that have duplicates, e.g.:
```
(1, 252052) [u’/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/8D858631-45A0-4D40-A880-F5298F195329.root’, u’/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/B417C89D-5345-AA4B-BA2B-29E4F154AB6E.root’]

(1, 240646) [u’/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/78504BE6-7D0C-504D-AC33-4633FB046646.root’, u’/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/99D23191-62CC-8A4B-8DDF-175BB2786FFC.root’]
```

Investigating the lumi `240646` and making sure those 2 last files really contain the same lumi number:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?logical_file_name=/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/78504BE6-7D0C-504D-AC33-4633FB046646.root&run_num=1&lumi_list=[240646]
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?logical_file_name=/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/99D23191-62CC-8A4B-8DDF-175BB2786FFC.root&run_num=1&lumi_list=[240646]

and the answer is yes, they both have lumi 240646 (second one is invalid already). They belong to the following blocks:
```
/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM#db434bf2-1827-484d-93b6-2317a2a9d422
/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM#6070c12c-9db4-4a2e-bc06-31210e06d6dc
```

Mapping these files to blocks and then investigating which agents produced those output datasets, I found that vocms0257 is where this workflow ran
vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481

Given the file names, this is the query to find which workflow produced those files:
```
SELECT dbsbuffer_block.id AS blockid, dbsbuffer_block.blockname AS blockname,
 dbsbuffer_file.id AS fileid, dbsbuffer_file.lfn AS lfn,
 dbsbuffer_workflow.id AS wfid, dbsbuffer_workflow.name AS name FROM dbsbuffer_block
 INNER JOIN dbsbuffer_file ON dbsbuffer_block.id = dbsbuffer_file.block_id
 INNER JOIN dbsbuffer_workflow ON dbsbuffer_file.workflow = dbsbuffer_workflow.id
 WHERE dbsbuffer_file.lfn
 IN ('/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/78504BE6-7D0C-504D-AC33-4633FB046646.root',
 '/store/mc/RunIIAutumn18MiniAOD/TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/70000/99D23191-62CC-8A4B-8DDF-175BB2786FFC.root');
``` 

After that, I wrote a script to fetch data from the ACDCServer and print files with those duplicate lumi sections:
```
cmst1@vocms0257:/data/srv/wmagent/current $ python getACDCChunkFiles.py 
Splitted block name: {'SpecName': 'vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481', 'TaskName': '/pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222/SUS-RunIIFall18wmLHEGS-00025_0', 'NumOfFiles': 31055, 'Offset': 0}
Retrieved 156 unique files from the ACDCServer
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-46f9bc176a3d2f7e0ecaaa75cd99cf87 with events: 528768, contains these lumis: set([240646])
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-fcadce0757360738dec334f0c2abb6a8 with events: 566304, contains these lumis: set([252052])
Spent 77.5486171246 secs running so far
```

and as we can see, there are no dups in the ACDCServer. So something must have happened in the agent.

I also compared the job splitting between the original and the ACDC and they are the same, so there should really be no issue with that. Next steps is to investigate the jobs that produced those files (and possible the jobs that produced the respective unmerged files...)

**Comment by amaltaro** [comment]
It helps if you find/run the correct SQL query. I can confirm it's a problem in the agent assigning the same lumi mask to > 1 jobs.

For the record, this is how I tracked this down. Given the duplicate lumi section number, we need to find out which input contains it (done by parsing the ACDCServer data). Once we have these two values - and we know which agent to look at - we run this query to find the job numbers that dealt with that lumi + fileid:
```
select wfd.id as fileid,wfd.events, wjm.* from wmbs_file_details wfd
 inner join wmbs_job_assoc wja ON wja.fileid = wfd.id
 inner join wmbs_job_mask wjm ON wjm.job = wja.job
 where wfd.lfn = 'MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-46f9bc176a3d2f7e0ecaaa75cd99cf87'
 and (wjm.firstlumi<=240646 and wjm.lastlumi>=240646);
fileid	events	job		firstevent	lastevent	firstl	lastl	run	run	inclusive
3070	528768	80054	98182753	98184385	240645	240649	1	1	T
3070	528768	80325	98182753	98184385	240645	240649	1	1	T
```

2 jobs with exactly the same job mask!!!!
With the job ids in hand, we can look for the logArchive tarball in the agent, look into the `wmagentJob.log` to confirm the job mask and also fetch the LFN for the prod/recent tarball.
For job `80054`:
```
find install/wmagent/JobArchiver/logDir/v/vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481/ -name \*80054\*
mask': {'LastRun': 1, 'LastLumi': 240649, 'FirstRun': 1, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 98184385, 'FirstEvent': 98182753, 'jobID': 80054, 'FirstLumi': 240645}
root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481/SUS-RunIIFall18wmLHEGS-00025_0/vocms0257.cern.ch-80054-0-log.tar.gz
``` 

For job `80325`:
```
find install/wmagent/JobArchiver/logDir/v/vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481/ -name \*80325\*
mask': {'LastRun': 1, 'LastLumi': 240649, 'FirstRun': 1, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': 98184385, 'FirstEvent': 98182753, 'jobID': 80325, 'FirstLumi': 240645}
root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/vlimant_ACDC0_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_190218_145226_481/SUS-RunIIFall18wmLHEGS-00025_0/vocms0257.cern.ch-80325-0-log.tar.gz
```

Finally we build a CMSSW area and unpickle the PSet.pkl files inside those tarballs.
```
vocms0257.cern.ch-80054-0-log.tar.gz
process.source = cms.Source("EmptySource",
    firstEvent = cms.untracked.uint32(98182753),
    firstLuminosityBlock = cms.untracked.uint32(240645),
    firstRun = cms.untracked.uint32(1),
    numberEventsInLuminosityBlock = cms.untracked.uint32(408)
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(1632)
)
```

and
```
vocms0257.cern.ch-80325-0-log.tar.gz .
process.source = cms.Source("EmptySource",
    firstEvent = cms.untracked.uint32(98182753),
    firstLuminosityBlock = cms.untracked.uint32(240645),
    firstRun = cms.untracked.uint32(1),
    numberEventsInLuminosityBlock = cms.untracked.uint32(408)
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(1632)
)
```

Those 2 jobs belong to the same jobgroup and the same subscription:
```
select wj.id as jobid, wj.jobgroup, wjg.subscription from wmbs_job wj
 inner join wmbs_jobgroup wjg ON wj.jobgroup = wjg.id
 where wj.id IN (80054, 80325);
jobid        jobgroup   subs
80054	295	132
80325	295	132
```

Last but not least - besides being almost useless - I see nothing fishy in the JobCreator logs, all those jobs were created in one shot by the component.
```
2019-02-18 15:13:15,776:140122241484544:INFO:JobCreatorPoller:Found end in iteration over subscription 21
2019-02-18 15:13:15,837:140122241484544:INFO:EventBased:Creating jobs for ACDC fileset /pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222/SUS-RunIIFall18wmLHEGS-00025_0
2019-02-18 15:15:13,531:140122241484544:INFO:JobCreatorPoller:Retrieved 1 jobGroups from jobSplitter
2019-02-18 15:18:15,003:140122241484544:INFO:DashboardReporter:Handling 31055 created jobs
2019-02-18 15:18:38,307:140122241484544:INFO:JobCreatorPoller:JobCreator has finished creating jobGroup 295.

2019-02-18 15:18:38,328:140122241484544:INFO:EventBased:Creating jobs for ACDC fileset /pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222/SUS-RunIIFall18wmLHEGS-00025_0
2019-02-18 15:19:15,892:140122241484544:INFO:JobFactory:No additional files found; Ending.
2019-02-18 15:19:16,092:140122241484544:INFO:JobCreatorPoller:Retrieved 0 jobGroups from jobSplitter
2019-02-18 15:19:16,098:140122241484544:INFO:JobCreatorPoller:Found end in iteration over subscription 132
```

Now we need to investigate what happened in the `EventBased` algo

**Comment by amaltaro** [comment]
And the root cause for all these duplicates is that we cannot guarantee that a job failure information will be uploaded only once to CouchDB. There is no rollback mechanism, and if something bad happens in the line next to the doc upload to couch, the whole process fails but the document is already stored in Couch.

This can be seen with this simple script I ran, which mimics the `DataCollectionService.getProductionACDCInfo` call done in the EventBased algo:
```
cmst1@vocms0257:/data/srv/wmagent/current $ python getACDCProduction.py 
Retrieved 31055 files from the ACDCServer
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-46f9bc176a3d2f7e0ecaaa75cd99cf87 with events: 1632, contains these lumis: [240645, 240646, 240647, 240648, 240649]
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-46f9bc176a3d2f7e0ecaaa75cd99cf87 with events: 1632, contains these lumis: [240645, 240646, 240647, 240648, 240649]
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-fcadce0757360738dec334f0c2abb6a8 with events: 1632, contains these lumis: [252049, 252050, 252051, 252052, 252053]
File: MCFakeFile-pdmvserv_task_SUS-RunIIFall18wmLHEGS-00025__v1_T_181211_005112_2222-SUS-RunIIFall18wmLHEGS-00025_0-fcadce0757360738dec334f0c2abb6a8 with events: 1632, contains these lumis: [252049, 252050, 252051, 252052, 252053]
Total amount of lumis: 155244, where unique are: 142382
```

so there are two rows/docs for each of those jobs (lumi sections). And a bunch more, as can be seen in the last line.

**Comment by vlimant** [comment]
@amaltaro interesting findings.
is there a "cleanup" that can be ran on the ACDC server when a wf reaches "completed", to get rid of all possible document duplicates ?
fixing when the ACDC does get started is nice, but the information in the ACDC database is also used for figuring out how much is there to recover (by unified), and that information should be as accurate as possible

**Comment by amaltaro** [comment]
I agree fixing it in the source would be better. However, it would require more effort to make the right thing and make sure there are no race conditions between the ACDC data and an ACDC workflow getting assigned. Plus the protection on the agent side has to be there anyways, as a protection :)

One possibility would be to update WMAgent on the nodes running Unified and let Unified use the same mechanism as the agents, just to get the correct accounting.

**Comment by vlimant** [comment]
can we get the mechanism in the couchdb view directly ?

https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=<>&include_docs=true&reduce=false
