### ISSUE TITLE
Need a configuration option to enable pycurl for ReqMgr2 requests

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9102]
While testing k8s setup I found that I don't have pycurl option in external configuration which can be passed to ReqMgr2 manager. The later initialize CouchServer which by itself uses JSONRequests objects. The later can be initialized with pycurl, see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/CMSCouch.py#L912

But I can't find anywhere how I can configure ReqMgr2 to enable pycurl which can be used in underlying code.

This issue is part of
https://github.com/dmwm/WMCore/pull/9101

**Comment by amaltaro** [comment]
The whole WMCore eco-system now relies on pycurl. So I'm closing this issue.
