### ISSUE TITLE
problems with scram()

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#9113]
HI @amaltaro 
did you push some backward non-compatible changes to scram() ? Which I did not pay attention to and hence did not protect against ?
I just build a new TW instance with WMCore 1.2.0
and got this:

```
  File "CMSRunAnalysis.py", line 644, in getOutputModules
    ret = scram("python -c '%s'" % pythonScript, logName=subprocess.PIPE, runtimeDir=os.getcwd())
TypeError: __call__() got an unexpected keyword argument 'logName'

```

**Comment by amaltaro** [comment]
Yes, Stefano. I got rid of the `logName` and the `scramOutput.log` file in this PR:
https://github.com/dmwm/WMCore/pull/8989

and made you aware of those changes; I knew it would have some side effect somewhere...

I believe I wrote a decent description of the changes. However, please let me know if you have questions or if we need to put some changes back in WMCore.

**Comment by belforte** [comment]
I vaguely remembered, which indeed why I wrote. I think that I looked at that at the time and judge it to be safe. sounds that I missed something !
Need to push some urgent fix to CRAB TaskWorker now, so am switching back to wmcore 1.1.20.
Will need ad ad hoc issue about porting to 1.2.0+  will come back to tthings in there.

**Comment by lecriste** [comment]
@amaltaro I noticed a different behaviour with the current scram:
with the `logName` paramter, `scram.stdout` used to return `[]`; without that parameter it returns `None`.

Is it intended?
CRAB code is raising an exception [here](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L650) because of this difference.

**Comment by amaltaro** [comment]
Scram call is supposed to return the exit code from the scram subprocess, see:
https://github.com/amaltaro/WMCore/blob/23a51aacbdc08b9956ac974e2a76f704511d1cee/src/python/WMCore/WMRuntime/Tools/Scram.py#L330

Looking at my changes, I don't think I touched that part in my PR.

**Comment by belforte** [comment]
Alan, the question is not about the return value of scram() call.
I must say that I am puzzled by `scram.stdout` call in CRAB code, there seems
to be no explicit `stdout` methos in Scram.py. Is this an attempt to access internal
object structure from the outside ? brrrrr....
That said, from the code you pointed to still looks like CRAB should find the stdout of the executed command, not None, nor [].
Leo is that from a successful call, or a failed one ?

**Comment by lecriste** [comment]
It is from a successful call. For example, [this](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L644) scram call:
`scram("python -c '%s'" % pythonScript, logName=subprocess.PIPE, runtimeDir=os.getcwd())`

makes `scram.stdout` to return `[]` [here](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L650).

By removing the logName parameter from the `scram` call, as in the new WMCore 1.2.0, that `scram.stdout` returns `None` (and `literal_eval(None)` raises an exception)

**Comment by belforte** [comment]
I could not reproduce that. We are following up in CRAB land. Let's leave this issue close unless we have clear evidence of a bug.
