### ISSUE TITLE
Create a new request state called "staging"

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9134]
This status will be used to report that ALL input data of a specific workflow has already been handled by ReqMgr2MS and PhEDEx/Rucio subscriptions have been already made.

From
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py#L20

new request status transition would be:
```
"assigned": ["staging",
                     "aborted",
                     "failed"],
"staging": ["staged",
                     "aborted"],
```

The transition from `assigned` to `failed` is still not totally clear whether it can happen or not.
Perhaps in cases where there is no input data (DBS) matching the user provided values/whitelist/blacklist... The best would be to let this check happen at GQ level, as it already does, but then we just delay the failure by hours/days/weeks.

**Comment by vkuznet** [comment]
Alan,
the status can be updated in MS via PUT request, e.g.
```
curl -X PUT -H "Content-Type: application/json" -d '{"RequestStatus":"staging", "RequestName":"valya_TaskChain_MC_Agent105_CDB16_forceComplete_190408_094630_5751"}' https://vk-reqmgr.cern.ch/reqmgr2/data/request
```
But of course there wrappers in WMCore to do that. For instance [ReqMgrAux ](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py) class has method [updateRecords](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L77) which I can use to update request status in ReqMgr2 from `acquired` to `staging`. I already tested direct curl call and adding code to MS.

**Comment by amaltaro** [comment]
Valentin, please don't spend your time on these MS issues assigned to me. I've been working on other issues hitting us in production and still didn't manage to work on MS, please be patient.

**Comment by amaltaro** [comment]
Just chatted with Jean-Roch and there were concerns about the request status `staging` and how it can be misleading. Honestly speaking, if we want to:
* tackle one MS at a time
* not monitor/track subscription requests and their status (not at this stage)
then I'm afraid we cannot have another status flagging that data has been completely transferred to where they were expected.

In short, `staging` can mean:
* data is moving towards their destination, but nothing is available
* data is moving towards their destination, but some of them are available
* data is already completely available

Just like `acquired`, which can have many meanings as well:
* acquired by GQ only, data not available yet
* acquired by GQ only, some data available yet
* acquired by GQ only, data fully
* acquired by the agents

Question is, does it make more sense to:
a) mark a workflow as `staging` while MS doesn't transfer its input data; then set to `acquired` once transfers are put in place
b) mark a workflow as `acquired` while MS doesn't transfer its input data; then set to `staging` once transfers are put in place

@vlimant @vkuznet @bbockelm any thoughts?

**Comment by vkuznet** [comment]
Alan, I'm not sure it is my call to decide or give you input on that. But MS architecture allows to start from one state and move it to another one, i.e. it will work with either of your proposal.
