### ISSUE TITLE
Review POST microservice API and persist data if needed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9135]
I still don't know all the details and information returned by the `/microservice/data/` POST API.

Depending on what the use case will be, e.g.:
* given a workflow name, return all its blocks and locations where data was subscribed, etc

we might have to persist data somewhere (central CouchDB is a good call) such that we don't need to query the data-service every time the Microservice has to handle the same query.

Thus we need to review that code and also document what it supports and what it's supposed to do.
Documentation can be written here:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Transferor

**Comment by amaltaro** [comment]
Just an update to this ticket.

The REST APIs had a few changes and we support the following APIs for both GET and POST calls:
https://alancc7-cloud1.cern.ch/ms-transferor/data/status
https://alancc7-cloud1.cern.ch/ms-transferor/data/info

e.g.:
```
$ curl --cert $X509_USER_CERT --key $X509_USER_KEY -X POST -H "Content-type: application/json"  -H "Accept: application/json"  -d '{"request":"amaltaro_StepChain_DupOutMod_HG2004_Val_200331_104220_690"}' https://alancc7-cloud1.cern.ch/ms-transferor/data/info
{"result": [
 {"request": "amaltaro_StepChain_DupOutMod_HG2004_Val_200331_104220_690", "transferDoc": {"ConfigType": "TRANSFER", "lastUpdate": 1585644764, "workflowName": "amaltaro_StepChain_DupOutMod_HG2004_Val_200331_104220_690", "transfers": []}}
]}
```
we could actually support PUT method such that we can update some information in the transfer documents. One of the items that would be useful to update is the list of transfer requests.

**Comment by vkuznet** [comment]
@amaltaro , can we close this issue?

**Comment by amaltaro** [comment]
It's more than 2 years old and there is specific issue for MSTransferor. Yes, let's close this one out as well. Thanks Valentin.
