### ISSUE TITLE
Enable ReqMgr2MS Transferor module in read-only mode

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9136]
The idea is to keep running this daemon in a dry-run mode such that we can check whether it's coming up with reasonable data-placement results. We also have to x-check the MicroService output with what is done by Unified.

**Comment by amaltaro** [comment]
@vlimant is Unified logging how data gets placed? Is the data-placement done in a campaign or request-basis? If you can give us some pointers, we'll definitely need those for the consistency checks here.

**Comment by vlimant** [comment]
There are logs in transferor and trace in phedex of what block went where.
Given that there is a random choice it’s going to be hard to make a one to one comparison

**Comment by vkuznet** [comment]
For the purpose of this issue title it is implemented already and we can close it. The readOnly mode is configuration parameter now and MSTransferor and MSTransferorMonit classes perform the status transition.

**Comment by amaltaro** [comment]
Title is ambiguous! How about we close it once we have reqmgr2ms running in read-only mode in cmsweb production?

**Comment by vkuznet** [comment]
ok

**Comment by amaltaro** [comment]
Service is now in production, with the status transition enabled, but data transfer disabled. As supported by the configuration file:
https://github.com/dmwm/deployment/blob/master/reqmgr2ms/config-transferor.py#L70-L71

I'm closing this ticket.
