### ISSUE TITLE
Provide APIs to be used within MS Transferor module

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9142]
Alan, please provide full set of APIs for every individual step.

**Comment by amaltaro** [comment]
Valentin, most of the snippets that I'll point out here are from this cherrypy thread:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py

For ReqMgr2 interaction, either fetching workflows in a specific status OR updating a workflow to another status, you can use:
```
from WMCore.Services.ReqMgr.ReqMgr import ReqMgr
reqmgrSvc = ReqMgr(config.reqmgr2_url, logger=self.logger)
reqmgrSvc.getRequestByStatus([status], detail=False)
reqmgrSvc.updateRequestStatus(wf, stateFromGQ)
```

For Global WorkQueue interaction, fetching elements and updating them, you can use :
```
from WMCore.Services.WorkQueue.WorkQueue import WorkQueue
gqService = WorkQueue(config.workqueue_url)
gqService.getAvailableWorkflows()  # FIXME: I'll have to create another method for this
gqService.updateElements(elements, params)
```

We should also integrate LogDB to the MS such that we can expose temporary/permanent errors, otherwise we only have the service logs to find issues. See:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/CherryPyPeriodicTask.py#L34

I believe the PhEDEx APIs are already in place, right? If these pointers answer your questions, please close this issue.

**Comment by vkuznet** [comment]
Alan,
thanks for pointers. While awaiting your reply I modified code to use ReqMgrAux
```
from WMCore.Services.ReqMgrAux import ReqMgrAux
reqmgr = ReqMgrAux(reqmgr_url, logger)
reqmgr.updateRecords(callname, data)
```
etc.

Should I switch to `WMCore.Services.ReqMgr` instead? I don't mind but I want to know why do you have `ReqMgrAux` and `ReqMgr` which covers identical APIs.

**Comment by vkuznet** [comment]
If you look at ReqMgrAux it covers the following APIs:
```
    def getCMSSWVersion(self):
    def updateRecords(self, callname, kwparams):
    def populateCMSSWVersion(self, tc_url, **kwargs):
    def getWMAgentConfig(self, agentName):
    def postWMAgentConfig(self, agentName, agentConfig):
    def deleteWMAgentConfig(self, agentName):
    def updateAgentConfig(self, agentName, key, value):
    def getCampaignConfig(self, campaignName):
    def postCampaignConfig(self, campaignName, campaignConfig):
    def updateCampaignConfig(self, campaignName, propDict)
```

while ReqMgr covers these APIs:
```
    def getRequestByNames(self, names):
    def getRequestByStatus(self, statusList, detail=True):
    def getRequestTasks(self, name):
    def getConfig(self, name):
    def insertRequests(self, requestDict):
    def updateRequestStatus(self, request, status):
    def updateRequestStats(self, request, stats):
    def updateRequestProperty(self, request, propDict):
    def getAbortedAndForceCompleteRequestsFromMemoryCache(self, expire=0):
    def getRequestByStatusFromMemoryCache(self, statusList, expire=0):
    def cloneRequest(self, requestName, overwrittenParams=None):
    def getGenericRequestInfo(self, queryDict):
```
So the former is about configuration of requests, while later is about request properties. Since I need to deal with configuration I think I should use the former, but may be both can be merged into single class. It is just confusing and duplication of each other (as other parts of WMCore).

**Comment by amaltaro** [comment]
ReqMgrAux is supposed to be used for auxiliary things; as you listed it above, it is meant to deal with CMSSW releases, agent config, campaigns.
ReqMgr is *the* request manager module to work with requests in general.

Thus, you need to use ReqMgr and not ReqMgrAux.

**Comment by vkuznet** [comment]
That's fine, but you still didn't provide into where should I get campaigns
configs?

**Comment by amaltaro** [comment]
For campaigns, I believe we need to use the ReqMgrAux Service class. However, I don't know how complete is that implementation. I'll check that on Monday.

**Comment by vkuznet** [comment]
Alan, that's my original point. Having two classes seems an overkill when they provide basic HTTP access to the same server. Anyway, have a look, and let me know.

I prefer to use a single class since I'm passing its instance around in different functions.

And, the main question is where campaings configuration, you kind of avoiding this question :)

**Comment by amaltaro** [comment]
HTTP access is just the lower layer, those classes still provide different functionality and serve different purposes.

About campaigns question, I said I'd check it on Monday, but to avoid getting the same question a couple times more over the weekend :), here is a snippet:
```
>>> from WMCore.Services.ReqMgrAux.ReqMgrAux import ReqMgrAux
>>> reqMgrAux = ReqMgrAux('https://alancc7-cloud1.cern.ch/reqmgr2')
>>> res = reqMgrAux.postCampaignConfig("CampaignTest1", {"CampaignName1": {"Key1": "Value1"}})
>>> res
[{u'ok': True, u'rev': u'1-7e1f07d01e47ecf17dd83f28f2887424', u'id': u'WMAGENT_CONFIG_CampaignTest1'}]
>>> reqMgrAux.getCampaignConfig("CampaignTest1")
[{u'ConfigType': u'WMAGENT_CONFIG', u'CampaignName1': {u'Key1': u'Value1'}}]
```

After you post that document, here is where you can find it:
https://alancc7-cloud1.cern.ch/couchdb/_utils/document.html?reqmgr_auxiliary/WMAGENT_CONFIG_CampaignTest1

so the implementation seems to be completed. I found a bug though, the document `ConfigType` isn't correct though.

**Comment by vkuznet** [comment]
Alan,
I already told you that I used reqMgrAux.getCampaignConfig API but it does not
find any configs and it throw HTTP exceptions. My question is how campaign
configs appear in CouchDB? Who is injecting them and can we test them with
unified transferor/MS setup?

For completeness here is how getCampaignConfig fails in my VM. Here the message comes
from reqMgrAux which first query local cache file and then tries reqmgr2 URL
```
The cachefile /data/srv/state/reqmgr2ms/.wmcore_cache_1000058/requests/vk-reqmgr
.cern.ch/15744094587142094_GET_campaignconfig_Agent105_Validation does not exist and the service at https://vk-reqmgr.cern.
ch/reqmgr2/data/campaignconfig/Agent105_Validation is unavailable - it returned 404 because Not Found with result: <!DOCTYP
E html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>404 Not Found</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>404 Not Found</h2>
        <p>No such instance</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>
ERROR:root:Traceback (most recent call last):
  File "/data/srv/HG1904a/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.0.9.pre2/lib/python2.7/site-packages/WMCore/Cache/GenericDataCache.py", line 37, in getData
    self.data = self.func(**self.kwargs)
  File "/data/srv/HG1904a/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.0.9.pre2/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 49, in _getResult
    verb=verb, contentType=contentType)
  File "/data/srv/HG1904a/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.0.9.pre2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 205, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/HG1904a/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.0.9.pre2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 320, in getData
    raise he
HTTPException
```

Please note that I do have reqmgr_auxilary DB:
```
https://vk-reqmgr.cern.ch/couchdb/_utils/database.html?reqmgr_auxiliary
```
but it does not have any campaign configs.

**Comment by amaltaro** [comment]
We don't have any campaign documents yet, that's why you cannot get them.
Unified is suppose to inject, eventually. So you can either create a couple of fake campaigns, or get the json Jean-Roch provided and inject that in your test VM.

**Comment by amaltaro** [comment]
@vkuznet , this is a too generic issue, and most of it has been clarified already. 
I'm closing it and then we can discuss any API needs on the many other GH issues that we have opened for this sub-project.
