### ISSUE TITLE
need for cp stageout plugin

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#9144]
For HPC that do not provide internet access to the worker node, stageout has to happen to the internal file system, which is mounted on the worker nodes.

The CP plugin was retired, so I see two options here. I could write a new CP plugin. Alternatively, the XRDCP plugin understands local file paths for input and output, but it misses the automatic output directory creation. I could add the latter based on parsing the output PFN (only do it if stageout is to a local file system path).

@amaltaro , what do you prefer? Or do you see another option?

**Comment by amaltaro** [comment]
I vote for reviving the CPImpl we used to have (and check if the implementation needs any update).
Having an XRDCP plugin that can actually do xrootd and cp depending on the case would be confusing IMO.

**Comment by amaltaro** [comment]
Look at what I found:
https://github.com/dmwm/WMCore/pull/8287

Can you take care of this issue?

**Comment by hufnagel** [comment]
Sure, I can do this. Do you want to me just add a CPImpl or also change the test back to use it?

**Comment by amaltaro** [comment]
We better keep the tests around too. Thanks!

**Comment by hufnagel** [comment]
My main concern with the tests is what to do (if anything) with LogArch_t.py, DeleteFiles_t.py, FileManager_t.py ?

I will need to add back the main unit test CPImpl_t.py, just haven't gotten to that yet.
