### ISSUE TITLE
Upgrade SQLAlchemy to >= 1.3.0

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9153]
There are two security vulnerabilities in the SQLAlchemy version we use in COMP (both versions actually), as one can see here:
https://github.com/dmwm/WMCore/network/alert/requirements.txt/SQLAlchemy/open

I'm trying to build sqlalchemy on 1.3.3 and I'll link it here once I have the cmsdist PR.

**Comment by hufnagel** [comment]
I assume you want to upgrade everyone then and get rid of the two older versions?
