### ISSUE TITLE
Replace WMCore StompAMQ with CMSMonitoring one

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9185]
Per our discussion on CMS Monitoring meeting we need to converge on one common layer to send docs to MONIT. The proposal is to use https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/StompAMQ.py

It provides `validation_schema` input parameter for `StompAMQ` class which can be set to `None` to avoid validation.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/9292
