### ISSUE TITLE
Review MS Transferor and adapt it according to the new architecture

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9195]
As per the second proposal on this wiki (picture still to be updated):
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Transferor#relying-on-reqmgr2-second-proposal

we should review the Transferor/Unified code already available in WMCore and follow the new Transferor design.

In short, the Transferor module is responsible for:
* fetching workflows from ReqMgr2 in the status `assigned`, including their json description
  * make a list of unique campaigns in those requests
* fetch campaign configuration from CouchDB (given a unique list of campaigns)
* fetch the unified configuration from CouchDB
* parse the request json and find out which blocks need to be transferred (using DBS)
* run the Transferor algorithm to decide which data go where (following the SiteWhitelist - SiteBlacklist)
* create all phedex subscriptions - or rucio rules
* classify subscriptions IDs by dataset (inside the same workflow) and persist it in Couchdb
* IF ALL these steps succeeded, update the request status to `staging`
* ELSE, record the error in Couch LogDB and restart from scratch in the next cycle

**Comment by vkuznet** [comment]
I think this is mostly done. With #9216 and #9225 we cover new proposal specs and can work now on API implementations.
