### ISSUE TITLE
Create a new MS TransferMonit application

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9196]
As discussed in this second proposal for the MS Transferor architecture:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Transferor#relying-on-reqmgr2-second-proposal

we have the need for another application that can monitor data placement subscriptions and advance requests to the next status.

In short, this MS would be in charge of:
* fetching workflows from ReqMgr2 that are in the `staging` status
* fetch the map of workflow / dataset / list of transfer IDs from Couchdb
  * respecting workflows with a timestamp greater than X hours (6h?)
* IF the workflow has no input data at all, simply update its status to `staged`, otherwise, continue the bullets below...
* fetch the unified configuration (or the campaign configuration, whatever we need to use in order to read the Pileup transfer acceptance)
* call PhEDEx/Rucio subscriptions
  * IF all calls for a given workflow succeeded, update its timestamp in the couch map document
  * ELSE, don't update anything and just retry in the next cycle (or update LogDB with the call that failed and the reason...)
* IF pileup is above the completion acceptance in the campaign/unified configuration, then update the request status to `staged`

**Comment by vkuznet** [comment]
So far code is part of https://github.com/dmwm/WMCore/pull/9140

**Comment by vkuznet** [comment]
I think this is done now with #9140 , #9216 and #9225

**Comment by amaltaro** [comment]
That's the problem when you create a broad issue... the application has been created, but it's still missing the most important logic in my POV. Which is the data transfer monitoring, evaluation, and update of the request status if it's all good.
