### ISSUE TITLE
Add CMS_Type job classad

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9252]
One of the monitoring items described in this issue: https://github.com/dmwm/WMCore/issues/8958

but since it's becoming more urgent and there are changes upstream to stop setting a default value for it, see: https://github.com/dmwm/cms-htcondor-es/pull/129

we need to push these changes ASAP.

`CMS_Type`: likely the same as the dashboard activity used to be. One of the following values are allowed: `(Production, Test, Tier0)`.

PS.: do they have the first capital letter? or is it all lower case?

**Comment by cronosnull** [comment]
We are using lowercase names in the type variable, but CRAB is sending "Analysis" in CMS_Type, so, I think we can use here the first Capital letter (the spider script will change it to lowercase before store it in the Type attribute).

**Comment by aperezca** [comment]
Hi Alan, 

Just to remind that the importance of this attribute is not only for monitoring purposes, but also eventually for matchmaking. So the principle guiding the categories should not only be "classify for monitoring", but by groups we may want to differentiate and select at negotiation time. We have discussed use cases for this specially when facing non-grid or non-standard resources.

(I leave to you and WM to decide on the actual groupings, of course).

Antonio.

**Comment by vkuznet** [comment]
It is yet another reason to enforce the schema validation of documents.

**Comment by amaltaro** [comment]
Hi everyone,

this has been fixed and just pushed to all the production/hepcloud/relval agents. There are likely a few testing/development agents connected to ITB which still don't have it though.

These changes will only affect new jobs getting submitted to condor; meaning that everything that was already in the condor pool before the patch got applied, won't have the `CMS_Type` job ad. 
I foresee 5 days until every single job in the pool gets updated with the new ad, so next Thursday June 28, should be fine to get the Job Monitoring changes in production.
