### ISSUE TITLE
REST.Auth

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMCore#9263]
@amaltaro 
I got below errors [1] when I was running DBS with WMCore 1.2.3. The build was successful, but when I started DBS server, I got these errors. The Auth was introduced last month. I did not get why the building did not bring REST into the rpm. Please take a look. I will need this for the HG1907 release.
Thanks,
Yuyi

[1] Traceback (most recent call last):
  File "/data/srv/HG1906f/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.10.0/lib/python2.7/site-packages/WMCore/WebTools/Root.py", line 35, in <module>
    from WMCore.WebTools.FrontEndAuth import FrontEndAuth, NullAuth
  File "/data/srv/HG1906f/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.10.0/lib/python2.7/site-packages/WMCore/WebTools/FrontEndAuth.py", line 8, in <module>
    from WMCore.REST.Auth import get_user_info
ImportError: No module named REST.Auth
~

**Comment by amaltaro** [comment]
Problem seem to have been inserted with these changes:
https://github.com/dmwm/WMCore/pull/8871

which made the WebTools package to depend on a function in the REST one.

They are not set to depend on each other and, DBS is using the `wmc-web` setup:
https://github.com/dmwm/WMCore/blob/master/setup_dependencies.py#L44

which is isolated from the REST one.

I have a fix for it and I'll tag you in the PR.

**Comment by yuyiguo** [comment]
@amaltaro 
Will you create a branch from 1.2.3 and apply your fix there?  Please add [9258](https://github.com/dmwm/WMCore/pull/9258) to the branch too. I need this one to get DBS server doc correct. 9258 adds  only some doc strings.

**Comment by amaltaro** [comment]
@yuyiguo I'd rather not merge anything that is not tested. Please have a look at both PRs comments, I need your input there.
