### ISSUE TITLE
Evaluate WMAgent on an ipv6 host

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9286]
Besides the natural migration and support to ipv6, it's also needed in order to migrate StompAMQ usage to the CMSMonitoring project (even though Valentin might find an ipv4 only solution).

AFAICS, it's disabled on both CERN and FNAL nodes. So we better check whether WMAgent behaves on both protocols.

Reference to get it enabled is here:
https://cern.service-now.com/service-portal/view-request.do?n=RQF1349880

**Comment by amaltaro** [comment]
My understanding is that we have been running on nodes with dual stack (ipv4 and ipv6). In addition, there are no known issues with ipv6, including monitoring and StompAMQ.

@khurtado and/or @todor-ivanov , do you think there is anything left for us to do in this 4 year old issue? Or should we just go ahead and close this out?

**Comment by todor-ivanov** [comment]
Hi @amaltaro I agree we can close this issue.
