### ISSUE TITLE
CMSSW seg fault showing up as BadFWJRXML error in WMStats

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9289]
Provided that jobs can pile many different exceptions and exit codes within the same step, I'd expect the very first exception to be reported in WMStats.

Which is not the case for (in testbed)
amaltaro_TaskChain_NanoAOD_Agent124_Val_190706_191332_1418

there is a job that seg faulted with an exit code 139, followed then by a failure to read the XML job report with an exit code 50115 (of course, the report wasn't completely created). What is getting reported in the WMStats table is actually the 50115 first, followed by the other 2 exit codes added to the job.
```
Job Name: 304435bf-e897-410b-bc6e-a8a7e6771653-0
WMBS job id: 39
Workflow: amaltaro_TaskChain_NanoAOD_Agent124_Val_190706_191332_1418
Task: /amaltaro_TaskChain_NanoAOD_Agent124_Val_190706_191332_1418/RunIIFall17NanoAOD
Status: jobfailed
Input dataset: /WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM
Site: T2_CH_CERN
Agent: vocms0193.cern.ch
ACDC URL: https://cmsweb-testbed.cern.ch/couchdb/acdcserver
State Transition
Exit code: 50115
Retry count: 0
Errors:

    logArch1

    cmsRun1
        BadFWJRXML (Exit Code: 50115)

            Error reading XML job report file, possibly corrupt XML File:
            Details: no element found: line 1, column 0

        CMSSWStepFailure (Exit Code: 139)

             Adding last 25 lines of CMSSW stdout:
            #3  <signal handler called>
```

Given that 139 was the first error, it should be the first error to be added to that step. As well as the first error to get reported in the WMStats table.

So we need to investigate:
* whether the order of errors are correct in the job report
* and why wmstats is changing that order (or which order/logic it's using).

Job log can be found here: http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_9289/

**Comment by thongonary** [comment]
Has this been fixed? It's showing up in https://its.cern.ch/jira/browse/CMSCOMPPR-8785

**Comment by amaltaro** [comment]
It's under development
