### ISSUE TITLE
Keep campaign configuration in Couch synchronized with MongoDB

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9310]
Now that https://github.com/dmwm/WMCore/issues/9228 has been taken care and we're ready to do a one time injection into central CouchDB; we should plan on how to keep the campaign configuration consistent between the two different database backends.

I see two possibilities:
a) check with Ops which script they use to create/write campaign records into MongoDB; then we can adapt the same script to write to both backends; this would also allow them to delete campaigns from central couch;
b) extend one of the ReqMgr2 CP-threads to fetch campaign records from MongoDB, and update campaigns in central couch in a polling cycle manner (every X hours).

Both options have pros and cons, but I think option a) would be the best.

Regardless of which option we choose, we need to use this script to make the conversion from Unified to WMCore campaign schema:
https://github.com/dmwm/WMCore/blob/master/bin/adhoc-scripts/parseUnifiedCampaigns.py

@vkuznet @sharad1126 and @thongonary any thoughts here?

**Comment by vkuznet** [comment]
If possible I also in favor of option A. Now we have a schema and should adapt existing scripts to use the schema and push docs into appropriate destinations.

**Comment by amaltaro** [comment]
@thongonary and @sharad1126 how would you prefer to handle this case? What I had in mind was to extend your script:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaignsConfiguration.py
to first inject campaigns into MongoDB, then inject the same campaign (with a different format) into central couchdb. This has two problems though:
*) we need to update the WMAgent version deployed on the unified nodes (or on the node creating/inserting campaigns)
*) if the couchdb campaign injection fails, we need to make sure it gets retried until it succeeds.

Another option would be to keep two different scripts:
*) the one which is already in use, without any modifications
*) then a second script, which reads all the campaigns from mongodb (or a list of campaign names), parse and inject them into couchdb.

Please let me know your thoughts.

**Comment by sharad1126** [comment]
Hi @amaltaro , I think this is the same about which we had a small discussion last week. I'll suggest to go ahead and use our script and extend it as from operations side, we won't like to run two scripts separately. It just increases the manual work for the operations. @thongonary what do you think?

**Comment by amaltaro** [comment]
This Ops/WmAgentScripts PR fixes this issue: https://github.com/CMSCompOps/WmAgentScripts/pull/466

Which has been merged 5min ago and it's now live. Every campaign Unified has is also available in central CouchDB (production CMSWEB), even though we're not using those yet.
