### ISSUE TITLE
Stop using ApMon in WMAgent jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9434]
**Impact of the bug**
WMAgent

**Describe the bug**
Service has been retired, even though we still try to send job information (via ApMon) to `cms-jobmon.cern.ch`. Error in the condor.out log is something like:
```
======== WMAgent Run the job starting at Sat Nov  2 11:39:54 GMT 2019 ========
Sat Nov  2 11:39:55 2019: ApMon[ERROR]: Error resolving cms-jobmon.cern.ch: [Errno -2] Name or service not known
Sat Nov  2 11:39:55 2019: ApMon[WARNING]: Not sending parameters since no destination is defined.
Sat Nov  2 11:39:55 2019: ApMon[DEBUG]: Closing UDP socket on ApMon object destroy.
Sat Nov  2 11:39:55 2019: ApMon[ERROR]: Error resolving cms-jobmon.cern.ch: [Errno -2] Name or service not known
....
```

**How to reproduce it**
none

**Expected behavior**
If we want to keep using this implementation, we might just pass/skip any job update.
 
**Additional context and error message**
AFAIK the service has been retired in October 2019.

**Comment by andresfelquintero** [comment]
Do you need any help on this issue? We have seen this issue when we resume paused jobs. I don't know where are we supposed to send the job information instead of ApMon.

**Comment by amaltaro** [comment]
I think the initial idea is to keep that code around. However, it would be better to just skip any of those job updates in my opinion. Anyways, whatever we decide to do, that will require changes to the source code. 
If you feel like making those changes, please go ahead and make a pull request!

**Comment by amaltaro** [comment]
Starting with ReqMgr2 HG2002 (1.3.0.pre6), the PerformanceMonitor plugin has been disabled, so production jobs will no longer report to the old dashboard, see:
https://github.com/dmwm/WMCore/pull/9510

**Comment by amaltaro** [comment]
New issue created: https://github.com/dmwm/WMCore/issues/9536
closing this one
