### ISSUE TITLE
Create Rucio APIs for MicroServices with multi pycurl

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9461]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
The MS Transferor implementation is not yet fully supporting Rucio. One of the reasons is because we still have to find out what are the exact APIs that best suit our needs.

**Describe the solution you'd like**
Implement the Common wrapper APIs for Rucio requests, using the concurrent pycurl `getdata`
function such that we can speed up any REST API requests.
If there are no Rucio APIs providing the information that is needed, e.g.: given a dataset, return its size, we might have to fallback to DBS (likely meaning a slower response too).
 
**Describe alternatives you've considered**
We could use the Services/Rucio module, but then we cannot take advantage of the concurrent requests. In the future we can reorganize those functions under the `Common.py` module and make it at least more clear and reuse as much code as we can.

**Additional context**
This issue is meant to address what didn't get implemented in this PR: https://github.com/dmwm/WMCore/pull/9457

**Comment by amaltaro** [comment]
@ericvaandering Eric, I'm planning to use the Rucio REST APIs because then we can profit of the concurrency offered by the WMCore/pycurl module. However, we have the extra complexity in the sense that we need to manage the token, and make sure that we use a valid token; and handle requests that failed due to its "unexpected" expiration.

If I'm not wrong, I think I heard you saying in one of these meetings that a "special setup" has been provided to DAS, to avoid this extra burden with the token(?) Perhaps we could look into the same thing for these CMSWEB services?

**Comment by ericvaandering** [comment]
No, there is not a special setup. The issue we had to solve with DAS was allowing DAS to be able to omit the Rucio account name, but that doesn’t help you.

It’s going to be a pain this way. :-)

**Comment by vkuznet** [comment]
@amaltaro , if you need to understand REST Rucio APIs you may use dasgoclient with proper site query and use `-verbose 3` option which will print all HTTP request info such that you may understand all REST calls DAS is doing behind the scene.

**Comment by amaltaro** [comment]
Thanks Eric, Valentin. I have a prototype using Rucio REST APIs, so the basics should all be clear by now. It's just the extra burden of renewing/verifying the token, but it's required to have a good throughput of rucio calls.
