### ISSUE TITLE
Remove reportWorkflowToDashboard for the March release

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9513]
**Impact of the new feature**
 ReqMgr2

**Is your feature request related to a problem? Please describe.**
Just a reminder to complete the removal of some code for the March 2020 release. This is a followup from here:

https://github.com/dmwm/WMCore/pull/9510

**Describe the solution you'd like**
Remove the referred piece of code. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by amaltaro** [comment]
Easily done, so we better get it out of our place asap ;)

**Comment by amaltaro** [comment]
Because I like easy issues, I'm stealing this one to myself.
