### ISSUE TITLE
Create CouchDB view for transfer documents from reqmgr_aux db

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9518]
**Impact of the new feature**
ReqMgr2/CouchDB

**Is your feature request related to a problem? Please describe.**
Now that we are about to push ReqMgr2MS into production, we could have a couchdb view to monitor transfer requests that haven't moved for X hours/days.

**Describe the solution you'd like**
It's a couchdb view to be deployed on the ReqMgrAux couchapp. It should fetch documents of type: TRANSFER and go through their `completion` field. The completion field is a list of float, where this real number represents the completion of a transfer (0 to 1).

Thus my suggestion would be to go through this list and check whether the last 4 elements (4 x 6h = 24h) in that list has the same value, meaning that that transfer request hasn't moved for 24h and is likely stuck for some reason. We can get back to this value once we start working on this.

**Describe alternatives you've considered**
Don't monitor anything and rely on the data management tools/team.

**Additional context**
none

**Comment by amaltaro** [comment]
@sharad1126 I knew I already had an issue for what we discussed in the past week.
This is the feature I said in that meeting that would be easy to be implemented.

Please let me know if you have anything to add here.

**Comment by sharad1126** [comment]
@amaltaro I think this is something different and will help the DM team to catch stuck transfers. What we need for PnR Ops is basically the `dataset name` which you are transferring, with the `phedex request id` and the `percentage completion` of that particular `request` infront of it. Also, what we would like to see is that this thing appears for every workflow and not like a centralised space. eg. you can push this info to our elastic search instance: https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_EXO-RunIIFall17MiniAOD-00764 and this goes to every workflow, so it's easy to check it. else you can make something of your own and we can ask Dima to integrate it in his page - https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIIFall17MiniAOD-00764 like we have transferor api link right now under the workflow name.

**Comment by amaltaro** [comment]
@sharad1126 as we discussed in the past week, please make a new GH feature ticket providing the exact requirements. Thanks

**Comment by amaltaro** [comment]
Nick confirmed (as privately discussed with a few peeps from the CompOps group, in the past week) that these rules - which belong to a single rucio account - should be fairly easy to monitor and act when needed, thus making it likely no longer needed to be (re)implemented by the WM group.

Given that it hasn't been implemented yet, and we are for a couple of months now fully in Rucio mode, I'm just going to close it. If needed, we can always reopen and/or create a new issue...
