### ISSUE TITLE
Validate WMStatsServer WMCore service in kubernetes

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9526]
**Impact of the new feature**
The whole WMCore eco-system, including CouchDB

**Is your feature request related to a problem? Please describe.**
In order to prepare for the upcoming infrastructure migration (from VMs to kubernetes/containers), we should fully validate all the services that we run in CMSWEB and make sure they behave well in the kubernetes infrastructure.

Other questions that we should address are related to the auto-scale of each of our services (some need to run in a single instance, others can have multiple instances).

Last but not least, we also need to decide how we are going to proceed with CouchDB. Apparently the k8s setup does not support the load we currently have in production. So we might have to keep CouchDB deployed in the standard VM backends in production CMSWEB.

**Describe the solution you'd like**
There is no real solution, but many questions need to be answered before we can enable that infrastructure in production in a seamlessly fashion.

No development is expected within the WMCore context. However, it's good to keep track of this activity here, which might be quite time consuming.

**Describe alternatives you've considered**
none

**Additional context**
The cluster to be used is: https://cmsweb-k8s-testbed.cern.ch

and this is the ticket to provide feedback (where some problems have already been fixed, like the service certificate used within the cluster): https://gitlab.cern.ch/cms-http-group/doc/issues/199

**Comment by amaltaro** [comment]
@khurtado feel free to also provide some feedback here (those that might matter for WMCore activities).

**Comment by amaltaro** [comment]
Status update, most of the services have been validated in k8s by HG2007a (thanks to Kenyi!).
Apparently, we still have to fix MongoDB usage within MicroServices though (only use if for MSOutput), meant to go in in HG2007b

**Comment by amaltaro** [comment]
As discussed in the meeting, this is only about `reqmon` and `reqmon-tasks`

**Comment by goughes** [comment]
reqmon and reqmon-tasks are runnign fine in k8s production for a couple days. Closing this issue.
