### ISSUE TITLE
Disable input data placement in Unified

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9527]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
Not really a WMCore development, but something that will be required to switch MicroServices on in production. There will be a moment that MicroServices will be fully enabled in central production, at the same time we need to make sure that Unified stops making the data placement, keeping all the rest of its functionality intact.

**Describe the solution you'd like**
We need to make the necessary changes to disable input data placement in Unified, somewhere here:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/transferor.py

Even better if we can start by making this configurable.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by amaltaro** [comment]
I'm not sure I'll be able to get it done by the next Thursday.... If I fail, I'll re-assign it to someone else ;)

**Comment by todor-ivanov** [comment]
@amaltaro What is the status of this one? Do we need to organize a last minute chat with you where you can give more details?

**Comment by amaltaro** [comment]
I didn't manage to get this one started. I'll get this one done in the coming week or two. I might need your help though to get the tests performed with Sharad.

**Comment by vlimant** [comment]
let me put here the note that if you want to disable transferor (which is the right way to go) you have to make sure eveything is tight about the lock and I do not see a dynamo GH issue linked here #7651

**Comment by todor-ivanov** [comment]
Hi Jean-Roch @vlimant. Thanks for this guidelines. One question here. Is it enough that only the transferor.py module from unified [1] to be disabled? And moreover, is it the whole thing that should be stopped, like just stopping its execution from the acrontab [2], or cutting that high could cause some other issues? Also should we consider disabling the stagor.py too? 
Regards
Todor

[1]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/transferor.py

[2]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/acrontab.list#L18
https://github.com/CMSCompOps/WmAgentScripts/blob/master/precycle.sh

**Comment by amaltaro** [comment]
About data locking, @goughes is on top of those things and we might even get the data locking in place before the input data placement. We're following data locking discussions on:
https://github.com/dmwm/WMCore/issues/7651

**Comment by amaltaro** [comment]
Initial proposal implemented here: https://github.com/CMSCompOps/WmAgentScripts/pull/519

I underestimated the amount of work that had to go in, especially because the assignor.py module has tons of data management logic.
