### ISSUE TITLE
Assess/monitor production MicroServices during February

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9528]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
Not related to any problem. However, now that we have microservices deployed to production CMSWEB (in dry-run mode). We should evaluate how well the service is performing, such that we can make some final adjustments - if needed - before switching data placement on in the beginning of March.
 
**Describe the solution you'd like**
MicroServices do not know anything about the data placement performed by Unified, so this is one comparison that we can't perform.

What I have in mind here is some basic status check of the services, using the following REST APIs (service polling cycle is set to 10min):
https://cmsweb.cern.ch/ms-transferor/data/status
https://cmsweb.cern.ch/ms-monitor/data/status
where we could fetch information like (for ms-transferor):
* `execution_time`: this is how long the service took executing its last cycle
* `num_datasets_subscribed`: amount of datasets subscribed in the last cycle (actually it's currently disabled!)
* `num_blocks_subscribed`: amount of blocks subscribed in the last cycle (actually it's currently disabled!)
* `error`: shows a major error found in the last cycle
* `total_num_requests`: number of requests processed in the last cycle

and for ms-monitor:
* `execution_time`: this is how long the service took executing its last cycle
* `request_status_updated`: amount of requests that went through a status transition
* `failed_transfer_doc_update`: amount of transfer couch documents that failed to get updated in the database
* `success_transfer_doc_update`: amount of transfer couch documents that succeeded to get updated in the database
* `filtered_transfer_docs`: amount of transfer couch documents that were meant to be updated in the last cycle

I was expecting to be able to run a cross-check between the service logs and global workqueue elements, but it looks like we don't log what would be the blocks that would actually get transferred.

**Describe alternatives you've considered**
Feel free to propose other items/metrics that we should monitor as well.

**Additional context**
none

**Comment by amaltaro** [comment]
I'll likely not be able to work on this one by the next week, I thought you could put something in place @goughes and get some plots done (a week of data should be more than enough).

**Comment by goughes** [comment]
I'm grabbing statistics every 10 mins for these two APIs on my test VM.

**Comment by amaltaro** [comment]
@goughes we can likely update this issue by the end of this week with whatever information we have collected so far.

Just in case, one can also scan the transferor logs for the `DRY-RUN` string. It should contain the data and location that a phedex subscription would get created to. However, given that Unified is still responsible for pre-staging data, we are likely not to find any such lines.
