### ISSUE TITLE
Build full dependency tree for WMCore services/packages and WMAgent

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9539]
**Impact of the new feature**
None will be affected. The proposed feature is about to collect data regarding the build process of all the above mentioned systems.

**Is your feature request related to a problem? Please describe.**
This is a solution proposed following a request from the FNAL security team, regarding what are the external dependencies of all the services we run on the WMAgent machines. It was suggested and agreed that we can build such a list of dependencies for all our services and this list should be consulted on a regular basis from the security team.  

**Describe the solution you'd like**

The best solution foreseen is to fetch those dependencies with `pkgtools`. Argumentation:
   - It will allow to do it with the minimal amount of coding. The list is already prepared during the process of building the packages with `cmsBuild`. Here [1] is where we should dump it to a place of our desire.
   - This method will provide the ability to rebuild the dependency tree with any change of versions or packages that is triggered upon every push to the [cmsdist](https://github.com/cms-sw/cmsdist) repository.     

The disadvantage of this approach is that we need to make PR to to the `pkgtools` repository in order  to ask for our feature to be implemented.
 
[1]
https://github.com/cms-sw/pkgtools/blob/V00-32-XX/cmsBuild#L3601

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:

An alternative to the above approach, should be a standalone script which is possible to run on demand. This script should be able to: 
 - go through the [cmsdist](https://github.com/cms-sw/cmsdist) repository, 
 - read all the spec files,
 - build the dependency tree, 
 - resolve any loops or version mismatch, 
 - print the final list.

Which is quite much more work to do than the solution already suggested. 

**Additional context**

**Comment by amaltaro** [comment]
@todor-ivanov given that we are converging into PyPi packages and soon'ish moving away from RPMs, could you please clarify/update this GH issue with anything relevant still left to be done? I'm inclined to think that this could be closed out, but maybe there are still outstanding items to be worked on here.

**Comment by todor-ivanov** [comment]
Hi @amaltaro
Agreed. Closing it now.
