### ISSUE TITLE
simplify myproxy credential name

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#9544]
**Impact of the new feature**
only affects CRAB.

**Is your feature request related to a problem? Please describe.**
currently submission from client  needs to go through same REST host as indicated in TaskWorker config. With multiple REST hosts and TW's in docker/k8s era this is not working. Also the numerical hash of the DN makes it always difficult to tell what's happening w/o adding a real extrasecurity value.

**Describe the solution you'd like**
credentail in myproxy should have a simple username, e.g. we can pass
to the WMCore Credential service a string like "CRAB" and credential name will be
CRAB_belforte etc. 

**Describe alternatives you've considered**
no other way is possible

**Additional context**

**Comment by belforte** [comment]
I will provide a tested PR.
This requires coordinated changes in CRAB TaskWorker, see 
https://github.com/dmwm/CRABServer/issues/6018
https://github.com/dmwm/CRABClient/issues/4817

For what concerns WMCore, the changes are only in
https://github.com/dmwm/WMCore/blob/059258c5c9d9d309c6d1283be0484634adf88073/src/python/WMCore/Credential/Proxy.py#L360
https://github.com/dmwm/WMCore/blob/059258c5c9d9d309c6d1283be0484634adf88073/src/python/WMCore/Credential/Proxy.py#L393
https://github.com/dmwm/WMCore/blob/059258c5c9d9d309c6d1283be0484634adf88073/src/python/WMCore/Credential/Proxy.py#L555

CHanges may also be required to:
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/Credential_t/MyProxy_t.py
to be verified

**Comment by belforte** [comment]
thanks @todor-ivanov

**Comment by belforte** [comment]
rats! I also need to modify the method which executes myproxy-logon on TW
https://github.com/dmwm/WMCore/blob/e394466b52d0f1e51c48ad2ef6e9daa23c4c0a96/src/python/WMCore/Credential/Proxy.py#L563

**Comment by belforte** [comment]
on the good side the PR which was merged has been tested in CrabClient and works as expected. Also CrabServer and TW are working with WMcore 1.3.1.pre2

**Comment by belforte** [comment]
Note that
https://github.com/dmwm/WMCore/blob/e394466b52d0f1e51c48ad2ef6e9daa23c4c0a96/src/python/WMCore/Credential/Proxy.py#L563
is only used in CRAB and unit tests. So I will not affect anything in WMCore

**Comment by todor-ivanov** [comment]
Hi Stefano @belforte, Sorry for not coming back to it immediately. We were in a row of issues following one after another lately. Do you already have the PR fixing this?

**Comment by belforte** [comment]
no worry @todor-ivanov I have not started working on this yet. Will let you know when I have something tested. I've been in my own stream of issues as well :-)
