### ISSUE TITLE
Move parent dataset lock list to reqmgr aux db

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#9561]
**Impact of the new feature**
ReqMgr2, WMStats

**Is your feature request related to a problem? Please describe.**
To build a list of parent datasets to lock, we are running a parent lock cherrypy thread on multiple backend servers. Some failure scenarios (mainly with DBS queries) could create cases where the parent locks are different across each backend. 

**Describe the solution you'd like**
Move the cherrypy thread to a single backend. The thread will update and store a parent lock list in the reqmgr auxiliary database. The WMStats `parentlocks` API will query the single copy that exists in aux db.

**Describe alternatives you've considered**
We considered some, but this is the best option.

Need to revert this deployment change: https://github.com/dmwm/deployment/pull/867

**Comment by amaltaro** [comment]
@goughes Erik, while we discuss how to best address this input parent dataset locking mechanism, let me make some modifications to this issue and the expected solution.

First, we can use this PR to retrieve workflows requiring parent dataset:
https://github.com/dmwm/WMCore/pull/9571

it should be much lighter than any other approach we have thought so far. The way to query it is similar to:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/CherryPyThreads/CouchDBCleanup.py#L39

Then we need to move the `BuildParentLock` from WMStats to ReqMgr (and modify deployment accordingly). Still, to be performed by a single backend.

I also suggest to keep a local in-memory cache in the cherrypy thread, something like:
```
dsetToParent = {"input_dataset_A": "parent_dset_AA", ...}
```
and only update the document in reqmgr_aux DB if there is content change.

Last but not least, keep the `parentlocks` API in the ReqMgr2 service (thus you can keep some of those changes in your PR).

What do you think? If anything is not clear (and before you start deleting changes that you have already made), please ping me on slack.
