### ISSUE TITLE
MS: subscribe blocks being produced under DataOps PhEDEx group

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9604]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

One of the Ops/Unified use case is that, output data of active workflows (running-*) has to be accounted against one of the PhEDEx group, otherwise data remains only *injected* into the storage, taking up space, but not really accounting that space against any group.
 
**Describe the solution you'd like**
Output blocks should get subscribed against their origin location, with the following parameters:
* location: where the block has been produced (where it is present)
* priority: does not matter (normal will be fine, after all, no transfers will be triggered)
* group: DataOps
* no notification/email

Expanding on the implementation details. I think we can use the `dbsbuffer_block` table and start using a new status for subscribed blocks, called `Subscribed`. Once blocks get closed in PhEDEx `Closed`, we can then trigger the block subscription.
AFAIK, these are the current possible statuses:
```
Pending
Closed
Open
InDBS
```

**Describe alternatives you've considered**
Another option would be to add a database schema change here, with a new column for the `dbsbuffer_block`. It might be useful to trigger block level rules in Rucio...

**Additional context**
@hufnagel would these subscriptions make sense for T0 data?
@ericvaandering @nsmith- do you think this feature would be also useful in the Rucio era?

Grepping the code, these DAOs will deserve special attention - at least -:
```
src/python/WMComponent/PhEDExInjector/Database/MySQL/GetDeletableBlocks.py:             AND dbsbuffer_block.status = 'Closed'
src/python/WMComponent/PhEDExInjector/Database/MySQL/MarkBlocksDeleted.py:    sql = """UPDATE dbsbuffer_block
src/python/WMComponent/PhEDExInjector/Database/MySQL/MarkBlocksDeleted.py:             SET dbsbuffer_block.deleted = :DELETED
src/python/WMComponent/PhEDExInjector/Database/MySQL/GetMigratedBlocks.py:             WHERE dbsbuffer_block.status = 'InDBS'
src/python/WMComponent/DBS3Buffer/MySQL/GetOpenBlocks.py:             WHERE dbsbuffer_block.status = 'Open' OR dbsbuffer_block.status = 'Pending' AND
src/python/WMComponent/DBS3Buffer/MySQL/CountOpenBlocks.py:             FROM dbsbuffer_block
src/python/WMComponent/DBS3Buffer/MySQL/UpdateBlocks.py:    sql  = """UPDATE dbsbuffer_block SET status = :status, create_time = :time, location =
src/python/WMComponent/DBS3Buffer/MySQL/LoadBlocksByDAS.py:                FROM dbsbuffer_block dbb
src/python/WMComponent/DBS3Buffer/MySQL/SetBlockClosed.py:        sql = """UPDATE dbsbuffer_block
```

**Comment by ericvaandering** [comment]
Actually @ncsmith and I had discussed this and we think that replicas with no rules don't get deleted if they are the final replicas. However.... The accounting issue is a good one and searching by rules for Ops is a good way to do that.

We might actually want to use a different Ops account for this activity rather than for the requested transfers so that we can find things easily.

**Comment by nsmith-** [comment]
:+1: to using many different accounts. Alternatively, the production-generated rules could be made with some metadata that describes their purpose, not sure what is better. I suspect rucio is better-optimized to query by account than by some likely unindexed metadata field.

**Comment by amaltaro** [comment]
Thanks for your comments.
Given that this change would not be useful only for PhEDEx, I think that creating a new column in the `dbsbuffer_block` table would be cleaner and more robust. Here's the table schema:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/MySQL/Create.py#L130-L139

so something like:
```
                 subscribed      INTEGER      DEFAULT 0,
```
would do.
Anything else that we're still missing or could be better here?
