### ISSUE TITLE
MS: Extend reqmgr2ms spec to also depend on mongodb and pymongo

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9605]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

As discussed this week, we have decided to use the MongoDB technology on this new microservice, instead of coupling yet another service to CouchDB.

**Describe the solution you'd like**
We should update the deployment scripts AND the reqmgr2ms cmsdist spec such that it brings the MongoDB and pymongo client. Once that's done, we should update the requirements.txt list as well.

**Describe alternatives you've considered**
CouchDB would be a natural alternative here, especially because the team already has enough expertise on the product.
Regarding the microservices itself, `reqmgr2ms` is also used for the MSTransferor and MSMonitor, where both depend on CouchDB. So another possibility would be to create a new service/package for this microservice, but that would imply changes to the WMCore setup script, new deployment scripts, new service commissioning, new spec file...

**Additional context**
none

**Comment by amaltaro** [comment]
Initial changes made against the cmsdist and deployment repositories.

I have also built reqmgr2ms depending on mongo/pymongo, package is in my private  repo `comp.amaltaro`, tag to be used is: `HG2004f-comp`

**Comment by amaltaro** [comment]
cmsdist and deployment changes have been merged and it can now be found in the official comp repo starting in `HG2005a`. Closing this issue as fixed

**Comment by todor-ivanov** [comment]
@amaltaro, Great! Thanks! 
Does it mean that starting from this tag onward we will deploy MongoDB in central services machines by default whenever we deploy ReqMgrms or you created it as a separate service to be installed?

**Comment by amaltaro** [comment]
Yes, it will come as a dependency of reqmgr2ms, so it will get deployed to our VMs as well (mind the non-standard port though).
