### ISSUE TITLE
MS: Create a new microservice MSOutput (simple functionality)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9606]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

There is the need for a new microservice to handle output data placement, which will initially work with PhEDEx and DDM, and in a late stage with Rucio.

**Describe the solution you'd like**
Re-use the MicroService architecture and add a new microservice to the MSManager module (and MicroService package).
It should have the very basic functionality, read the service configuration from the deploy configuration file, serve any kind of content through the info/status REST APIs. The skeleton has to consider different data management technologies.

Besides changes in the WMCore repo, we should also implement the necessary changes to the deployment repo (reqmgr2ms configuration).

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by todor-ivanov** [comment]
@amaltaro just to clarify. Here 
> The skeleton has to consider different data management technologies.
By 'data management technologies' you mean: Phedex, DDM and Rucio, right ?

**Comment by amaltaro** [comment]
That's correct!
