### ISSUE TITLE
MS: create a Services wrapper module for DDM

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9607]
**Impact of the new feature**
ReqMgr2MS (and anything else using the Services package)

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

Unified talks to two different data management technologies for the output data placement. PhEDEx for relval output and DDM for standard production samples (because DDM does an intelligent data placement)

**Describe the solution you'd like**
Given that we will have to use DDM REST APIs for a few months, we should implement a wrapper around those APIs in order to make its usage cleaner and straight forward.

One API that we definitely need to use is `/registry/request/copy`. No need to implement anything else, unless we find it to be important for this migration.

I have already asked Benedikt for further information. I'll update this description once I have further documentation on that API.

**Describe alternatives you've considered**
or create a wrapper around all the 3 data management tools: DDM, PhEDEx and Rucio

**Additional context**
Unified has this logic implemented in `_pass_to_dynamo`, here:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L511

**Comment by todor-ivanov** [comment]
@amaltaro, could we make it to be a general wrapper to all three of them - DDM, Rucio, Phedex and implement a decent switch in the call to the module?

**Comment by amaltaro** [comment]
That's another option Todor, I added to the alternatives.
However, I tend to believe that such wrapper would rest in our base code for the rest of the days (just as it happened for the DBS2/DBS3 wrapper...). With different modules, we can easily remove a module (and possible replace an os environment and/or if-else and be done with the final migration/cleanup).

I'm happy to be proven wrong though ;)
