### ISSUE TITLE
Disable NANOAOD/NANOAODSIM output data placement in Unified

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9634]
**Impact of the new feature**
Unified

**Is your feature request related to a problem? Please describe.**
It's not really a WMCore issue, but given that Unified has closer to 0 dev manpower now. I thought we could make this change for them, we have anyways investigated that code already.

**Describe the solution you'd like**
We should implement a configurable parameter for the Unified setup, such that we can skip any output data placements for a set of datatiers. Logging the datasets being skipped from the data placement.

Reason for that is, that it will be taken care of by the Rucio/DM team.

**Describe alternatives you've considered**
An alternative would be to hard-code those datatiers in the code... However, this functionality will likely be needed for other use cases, so having it configurable is likely a better idea.

**Additional context**
none

**Comment by todor-ivanov** [comment]
Here are the relevant, Issue and PR in the WmAgentScripts repository:

https://github.com/CMSCompOps/WmAgentScripts/issues/530
https://github.com/CMSCompOps/WmAgentScripts/pull/531

**Comment by amaltaro** [comment]
There was this additional PR as well:
https://github.com/CMSCompOps/WmAgentScripts/pull/561

they have been merged and Unified will no longer subscribe those data tiers for RelVal workflows.

Next week we should disable those tiers for standard workflows as well, when Unified needs to update their config to:
```
"tiers_to_rucio_nonrelval": ["NANOAOD", "NANOAODSIM"]
```

Given that all pieces are now in place, I'm closing this issue.
