### ISSUE TITLE
RucioInjector fails to create rules against MSS endpoints

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9638]
**Impact of the bug**
WMAgent

**Describe the bug**
I'm actually not sure whether it's a bug, or whether there is no such RSE. However, while running some tests, I noticed that the RucioInjector component fails to create a container rule against a MSS endpoint.

**How to reproduce it**
Create a rule against `T1_US_FNAL_MSS`

**Expected behavior**
There are actually two issues to be tackled here.
1. is `T1_US_FNAL_MSS` a valid RSE? Is our WMAgent rucio accounts allowed to create such rules?
2. ReqMgr2 supports workflow parameters for custodial and non-custodial sites (in addition to priority, phedex group, etc). Rucio does not have such concept, so once we start migrating to RucioInjector, it could be that the component will try to make 2 container rules for the same dataset (1 custodial, 1 non-custodial). I think we will have to drop/skip the custodial data placement and only proceed with the non-custodial.

As mentioned in my comment below, we also want to have the possibilty to change container rule creation to `ask_approval=True`, in case the False option fails.

**Additional context and error message**
From RucioInjector in vocms0193:
```
2020-04-15 10:08:27,589:140658649351936:INFO:RucioInjectorPoller:Creating container rule for /RelValH125GGgluonfusion_14/Integ_Test-SC_LumiMask_PhEDEx_Agent133_Val_Alanv11-v11/NANOAODSIM against RSE T1_US_FNAL_Disk
2020-04-15 10:08:29,295:140658649351936:INFO:RucioInjectorPoller:Container rule created for /RelValH125GGgluonfusion_14/Integ_Test-SC_LumiMask_PhEDEx_Agent133_Val_Alanv11-v11/NANOAODSIM under rule id: [u'814097ee9ee740eba048c15ac1a92c55']
2020-04-15 10:08:29,295:140658649351936:INFO:RucioInjectorPoller:Creating container rule for /RelValH125GGgluonfusion_14/Integ_Test-SC_LumiMask_PhEDEx_Agent133_Val_Alanv11-v11/NANOAODSIM against RSE T1_US_FNAL_MSS
2020-04-15 10:08:30,719:140658649351936:ERROR:Rucio:Exception creating rule replica for data: ['/RelValH125GGgluonfusion_14/Integ_Test-SC_LumiMask_PhEDEx_Agent133_Val_Alanv11-v11/NANOAODSIM']. Error: Provided RSE expression is considered invalid.
Details: RSE Expression resulted in an empty set.
```

**Comment by amaltaro** [comment]
@ericvaandering @nsmith- can you please help me understand this MSS failure?

**Comment by nsmith-** [comment]
It's `*_Tape` these days (as all mass storage systems in use by CMS are tape)
You can see RSEs via `rucio list-rses`.
Worth keeping in mind, some tape RSEs will only allow rules created with `ask_approval=True` (I am not sure if that is automatically set for those or not, Eric might)

**Comment by nsmith-** [comment]
Really, though, we need to abandon `CustodialSites` and `NonCustodialSites` in favor of a structure like
```
rules: [{'rse_expression': '...', 'copies': 1}, ...]
```
for defining the container rules placed on workflow outputs

**Comment by nsmith-** [comment]
In the interim the same can be accomplished entirely within rucio via subscription mechanism, which matches DIDs to regular expression on injection and creates rules. We can even use this for now and figure out what to do about final output placement later.

**Comment by amaltaro** [comment]
AFAICS, Unified does not use the `CustodialSites` configuration, so it's very unlikely that WMAgent will have to create data placement against _Tape RSEs (maybe T0 only). Which means, at least during this migration, we could perhaps skip the CustodialSites data placement and only perform the non-custodial one.

As for those workflow parameters, I have made another GH issue:
https://github.com/dmwm/WMCore/issues/9639
such that we don't forget to make those changes when PhEDEx gets out of the picture.

**Comment by ericvaandering** [comment]
_MSS is not a valid RSE. They are called _Tape in Rucio. However, we've also got agreement that under Rucio we will hold off on writing NanoAOD to tape for a bit.

I thought these subscriptions would be put in place by Unified, not the agent. 

For the short term no one will make the tape request. For catchup, Ops will have to do it, maybe with subscriptions. Long term, do we want to do it with subscriptions still or have the agent start doing it?

**Comment by ericvaandering** [comment]
I see Nick has largely said the same thing while I was being interrupted with something else. :-)

**Comment by nsmith-** [comment]
Sounds good. It might be worth understanding why unified does the custodial copy itself rather than setting CustodialSites. (e.g. https://cmsweb.cern.ch/phedex/prod/Request::View?request=2177988 )

**Comment by amaltaro** [comment]
Another requirement from the Rucio migration discussion we had today.
Besides the mapping from _MSS to _Tape, we should implement the following logic for tape (custodial) requests:
1) first we create a standard rule request, thus leaving `ask_approval=False`. Some sites might forbid it, which means the rule creation will fail. If it does, then
2) create the same rule request, but this time explicitly set `ask_approval=True`. This time it should go through.

**Comment by amaltaro** [comment]
@nsmith- can you please confirm whether the comment/description above is still correct?

**Comment by nsmith-** [comment]
Yes that description is correct. I looked into the type of exception and one would expect an `rucio.common.exception.AccessDenied` exception for a site that requires approval. That exception could be due to other access denial reasons, but at least it is much less likely to stem from some validation error or otherwise.
