### ISSUE TITLE
Properly query schedds that flock to another collector 

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#9650]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
HEPCloud schedds are configured in such a way the local schedds can't be found in the collector host, but rather in the flock collector. We rely on finding the local schedd in the regular collector here:

https://github.com/dmwm/WMCore/blob/506cfd515cb2f4590c54d29d3bbb571381e187a7/src/python/WMCore/Services/PyCondor/PyCondorAPI.py#L81-L84 

So, we can't query attributes like the `CurbMatchMaking` for those schedds.

```
$ condor_config_val -expand COLLECTOR_HOST FLOCK_COLLECTOR_HOSTS
vocms0809.cern.ch:9618,cmssrv283.fnal.gov:9618
cmssrv268.fnal.gov:9620, cmssrv605.fnal.gov:9620
[cmsdataops@cmssrv217 ~]$ condor_status -schedd -constraint 'Machine == "cmssrv217.fnal.gov"'
# Nothing here
[cmsdataops@cmssrv217 ~]$ condor_status -pool cmssrv268.fnal.gov -schedd -constraint 'Machine == "cmssrv217.fnal.gov"'
Name               Machine            RunningJobs   IdleJobs   HeldJobs

cmssrv217.fnal.gov cmssrv217.fnal.gov           0         34         25

                TotalRunningJobs      TotalIdleJobs      TotalHeldJobs

              
         Total                 0                 34                 25
``` 

https://cms-logbook.cern.ch/elog/GlideInWMS/7356

**Describe the solution you'd like**
I think we should make the code smarter and search for the local schedd in  `COLLECTOR_HOST` and then `FLOCK_COLLECTOR_HOST` (if not present in the former).

**Describe alternatives you've considered**
None so far.

**Comment by amaltaro** [comment]
@khurtado just for future usage, you created this issue with the "new feature" template instead of the bug one, so some fields are slightly different.

About the issue, I just notice that WorkQueueManager is failing in testbed agent vocms0290 (apparently connected to the global pool). Error from the WorkQueueManager is:
```
2020-05-05 11:49:20,844:140187051910912:INFO:PyCondorAPI:Recreating Collector instance due to query error...
2020-05-05 11:49:21,065:140187051910912:ERROR:PyCondorAPI:Condor failed to fetch schedd attributes.Error message: list index out of range
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.3.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.3.3.patch3/lib/python2.7/site-packages/WMCore/Services/PyCondor/PyCondorAPI.py", line 93, in isScheddOverloaded
    projection=['CurbMatchmaking'])[0]
IndexError: list index out of range
2020-05-05 11:49:21,065:140187051910912:WARNING:WorkQueueManagerWorkPoller:No work will be pulled: schedd is overloaded
```

From what I had understood, this issue should only hit us in schedds configuration that cannot be found in the collector (other collector setup).

Can you please have a look at this issue this week? We better have a fix for it before we get ourselves into problems with the production agents as well.

**Comment by khurtado** [comment]
Hi @amaltaro,
The issue with `0291` is an ITB issue. We have 2 collectors, the one at CERN has HTCondor 8.9.6, while the one at FNAL still has 8.9.2. There is a compatibility bug between 8.9.2 and schedds that are 8.9.4+, as in this case

``
[khurtado@vocms0291 ~]$ condor_status -pool cmssrv283.fnal.gov:9618 -collector -af Machine CondorVersion | sort | uniq -c
      1 cmssrv283.fnal.gov $CondorVersion: 8.9.2 Jun 04 2019 BuildID: 471265 PackageID: 8.9.2-1 $
[khurtado@vocms0291 ~]$ condor_status -pool vocms0809.cern.ch:9618 -collector -af Machine CondorVersion | sort | uniq -c
    102 vocms0809.cern.ch $CondorVersion: 8.9.6 Mar 22 2020 BuildID: 498526 PackageID: 8.9.6-1 $
      1 vocms0816.cern.ch $CondorVersion: 8.9.6 Mar 22 2020 BuildID: 498526 PackageID: 8.9.6-1 $
```

So, if you try to query the `CurbMatchmaking` attribute with CERN, you get the value. If you query the FNAL collector, you get an empty result, hence the `out of range` in python.

```
[khurtado@vocms0291 ~]$ condor_status -pool cmssrv283.fnal.gov:9618 -schedd vocms0291.cern.ch -af:h CurbMatchmaking
CurbMatchmaking
[khurtado@vocms0291 ~]$ condor_status -pool vocms0809.cern.ch:9618 -schedd vocms0291.cern.ch -af:h CurbMatchmaking
CurbMatchmaking
false
[khurtado@vocms0291 ~]$
```
So, I will ask when this collector is going to be updated. As for how we can improve this, I was thinking the following:

Right now, we just use `htcondor.Collector()` to get one collector from the configuration. Condor will pick one randomly from the list, either CERN or FNAL. If the query fails, it fails. No further information regarding what collector was used. Instead, we could do:

1. Get list of collectors from `htcondor.param['COLLECTOR_HOST']` and/or `htcondor.param['FLOCK_COLLECTOR_HOST]`
2. Pick one randomly, similar to what HTCondor does
3. Do the query with that collector, if it fails, throw the exception message, but print the collector that was used for it.

This goes along with the main issue in this thread, because we could first see if we can find the local schedd in the list of schedds in `htcondor.param['COLLECTOR_HOST']`, or look in `htcondor.param['FLOCK_COLLECTOR_HOST]` otherwise (or fail if it can't be found in any of them).  What do you think?

**Comment by khurtado** [comment]
@amaltaro So, it turns out the problem with `vocms0291` and `vocms0290` comes from the fact these schedds had authorization issues with the FNAL ITB and Production collectors. Maria from FNAL is working on adding them to the mapfile configuration.

**Comment by amaltaro** [comment]
Just an update on this issue. I have deployed the latest stable release (1.4.3.patch2) on one of the hepcloud agents (cmssrv217) and this same issue pops up.
Since this agent is only meant to run tests, I have hacked that method in place (PyCondorAPI.py).

**Comment by amaltaro** [comment]
Possibly related with this very same problem.
Checking one of the HEPCloud testbed agents (cmssrv271), I see that WorkQueueManager fails to execute the thread cycle due to:
```
2021-10-06 03:22:15,979:139839699715840:INFO:WorkQueueManagerWorkPoller:Pulling work from https://cmsweb-testbed.cern.ch/couchdb/workqueue
2021-10-06 03:22:16,670:139839699715840:INFO:PyCondorAPI:Recreating Collector instance due to query error...
2021-10-06 03:22:16,677:139839699715840:ERROR:PyCondorAPI:Condor failed to fetch schedd attributes.Error message: list index out of range
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2/lib/python3.8/site-packages/WMCore/Services/PyCondor/PyCondorAPI.py", line 123, in isScheddOverloaded
    q = self.coll.query(htcondor.AdTypes.Schedd, 'Name == "%s"' % scheddAd['Name'],
IndexError: list index out of range
2021-10-06 03:22:16,678:139839699715840:WARNING:WorkQueueManagerWorkPoller:No work will be pulled, reason: schedd is overloaded
```

From the log snippet, one can see it's affecting our latest WMAgent stable release (Py3 1.5.2).

@hufnagel @khurtado if you have any suggestion on how we should deal with this case, please let me know. Dirk, if you feel like proposing a fix for this, it would be even better ;)

**Comment by khurtado** [comment]
While testing #11307, I realized the HEPCloud schedds can now be located from the local collector and do not need to query the flock collector for the schedd information anymore.

```
[cmsdataops@cmssrv217 PyCondor]$ condor_status -schedd -constraint 'Machine == "cmssrv217.fnal.gov"'
Name               Machine            RunningJobs   IdleJobs   HeldJobs

cmssrv217.fnal.gov cmssrv217.fnal.gov           0          0          0

                TotalRunningJobs      TotalIdleJobs      TotalHeldJobs


         Total                 0                  0                  0
[cmsdataops@cmssrv620 current]$  condor_status -schedd -constraint 'Machine == "cmssrv620.fnal.gov"'
Name               Machine            RunningJobs   IdleJobs   HeldJobs

cmssrv620.fnal.gov cmssrv620.fnal.gov           0          0          0

                TotalRunningJobs      TotalIdleJobs      TotalHeldJobs


         Total                 0                  0                  0
```

Interactive usage of the current PyCondorAPI works at present without the PR (see below). 
Hence, I will close my PR and close this issue as well.

```
>>> api = PyCondorAPI.PyCondorAPI()
>>> import htcondor
>>> scheddAd = api.coll.locate(htcondor.DaemonTypes.Schedd)
>>> scheddAd['Name']
'cmssrv620.fnal.gov'
>>> scheddAd
[ CondorPlatform = "$CondorPlatform: X86_64-CentOS_5.11 $"; CondorVersion = "$CondorVersion: 8.9.7 May 20 2020 BuildID: UW_Python_Wheel_Build $"; Machine = "cmssrv620.fnal.gov"; MyType = "Scheduler"; Name = "cmssrv620.fnal.gov"; MyAddress = "<131.225.188.61:9615?addrs=131.225.188.61-9615&alias=cmssrv620.fnal.gov&noUDP&sock=schedd_2710_69be>" ]
>>> q = api.coll.query(htcondor.AdTypes.Schedd, 'Name == "%s"' % scheddAd['Name'], projection=['CurbMatchmaking'])[0]
>>> q
[ CurbMatchmaking = (ShadowsRunning > 9.700000000000000E-01 * 20000) || (RecentDaemonCoreDutyCycle > 9.800000000000000E-01); RecentDaemonCoreDutyCycle = 2.156176985096403E-04; ShadowsRunning = 0 ]
```
