### ISSUE TITLE
Create DID metadata to distinguish RelVal data from the others

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9655]
**Impact of the new feature**
WMAgent (and like MicroServices - MSOutput)

**Is your feature request related to a problem? Please describe.**
As discussed in today's Rucio migration meeting, we need to have a way to distinguish RelVal from any other data injected into Rucio. This will be needed for the very first phase of NANOAOD injection, so we can likely create something not too convoluted here.

**Describe the solution you'd like**
Create a meta-data key/value pair and feed it into Rucio when creating a DID. DID here needs to be clarified whether it's a a) replica, b) a block or c) a container.
This meta-data key needs to be agreed upon with the Rucio team before hand, because it needs to be created in the Rucio database.

Perhaps we could use this meta-data to identify the data source, something like:
* `relval` data
* `production` data
* `tier0` data
* `test` data
sort of the same classification we have for CMS jobs. The metadata key could be `dataType`, but it might be misleading in terms of EDM and etc. So perhaps it could be named `dataSource`? Or anything else that is meaningful and not anbiguous.

UPDATE (after discussions below):
We decided to use a metadata key named `project` (for blocks and containers), the allowed values are:
* `Production`: for central production activities/workflows
* `RelVal`: for Release Validation activities/workflows
* `Tier0`: for Tier0 production activities/workflows
* `Test`: for any test/dev/replay activities/workflows
* `User`: for user/crab activities

**Describe alternatives you've considered**
My initial suggestion was to use the same PhEDEx group logic, thus `RelVal` for release validation data; `DataOps` for anything else.

**Additional context**
none

**Comment by todor-ivanov** [comment]
Hi @amaltaro @nsmith- My two cents here is ... for me those both and `dataType` and `dataSource` are kind of...equally misleading. What sounds the most descriptive to me is actually `dataStream`. Even though here we should be careful not to clash terminology with T0.

**Comment by nsmith-** [comment]
I suppose if we rewind this topic, the intention was to assist rucio in identifying the appropriate output data placement policy, so maybe we call it `placement_policy`?
RelVal NanoAOD has sort-of forced us to consider the output placement mechanism, even in this case where rucio does most of the work

**Comment by todor-ivanov** [comment]
Hi @nsmith- From the example you chose (RealVal NanoAOD),  would I make a wrong reading/conclusion/suggestion if I read it like: We can also widen the inital set of categories and make it a super set including two classification types  - one is the workflow type, producing the data (`relval`, `production` ... etc) and the other to be the data Tier (`AOD`, `NANOAOD`, ... etc.)?

**Comment by nsmith-** [comment]
One could split things like that. Certainly the data tier can be surmised from the container DID name. Perhaps then `workflow_type` could be the name of this extra field.

**Comment by amaltaro** [comment]
`workflow_type`, in the context of WMCore, means: TaskChain, StepChain, ReReco, Repack, etc
So another overloaded and misleading name :)

How about `workActivity`? Or `workflowActivity`? 
Note: If we want to keep consistency with the current metadata, then it needs to follow the camelCase convention

**Comment by nsmith-** [comment]
`workflowActivity` sounds good. Can change later in principle. I just added it to cmsrucio-int. Due to https://github.com/rucio/rucio/issues/3512 it will be unvalidated for now.
I made this a collection metadata, i.e. container or dataset but not file DID.

**Comment by nsmith-** [comment]
Explicitly, the allowed metadata at this point is:

| Applicable DID type | Key | Value |
| --- | --- | --- |
| DATASET | `workflowActivity` | `RelVal` |
| DATASET | `workflowActivity` | `Production` |
| CONTAINER | `workflowActivity` | `RelVal` |
| CONTAINER | `workflowActivity` | `Production` |

Sound good?

**Comment by amaltaro** [comment]
Should we extend those values to: `Tier0` and `Test` as well?

**Comment by nsmith-** [comment]
I would prefer not setting a key for such until we know what the intention is on the rucio subscription side. For RelVal and Production NanoAOD I know what to do, but I am not sure what to do with Tier0 or Test.

**Comment by nsmith-** [comment]
But if you already have such established activities I am ok including it.

**Comment by amaltaro** [comment]
We have already started running test workflows that make it to the Rucio database. So, if you think it makes sense to tag those DIDs with `Test`, either now or in a few months from now, I'd rather have it implemented this week then.

Otherwise, I can make changes only for those two workflow activities and the rest remains without that DID metadata (basically any agent running dev/testbed/replays/tier0 workflows).

From my side, I'd be inclined to always label those data.

**Comment by nsmith-** [comment]
Ok then let's label the data. Sorry for the flip-flop.

**Comment by amaltaro** [comment]
No worries! Thank you for your input!
