### ISSUE TITLE
Fix StepChain parentage for workflows in closed-out as well

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9656]
**Impact of the new feature**
WMAgent & Unified

**Is your feature request related to a problem? Please describe.**
Given the asynchronous nature of merge execution in StepChain workflows, it could be that its output datasets get announced before all the parentage information has been updated.
The Parentage dependency is resolved through a ReqMgr2 cherrypy thread, which queries DBS, asking for every block in a dataset with no Parent block : [1]. Those are extremely heavy queries to the DBS database and sometimes due to external pressure to the system can lead to delays. When those delays exceed the 5 min timeout (configured in the cmsweb Frontend) the current query is dropped and the Parentage resolution of the current block is retried during the next cycle. This by its own means  can delay the process even further, while in the meantime Unified can see that  the needed statistics for a workflow is reached and announce the data. 
There is already a flag in the request description `ParentageResolved` which is used to sign StepChains with complete parentage information.
We need to fix parentage before it gets announced (closed-out status in ReqMgr2). Set that flag to `True`, and then propagated and take it into account by Unified. 

[1]
1. Given a dataset, find its parent datasets
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L870

2. Find all the blocks in the dataset that do not have a parent block:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L968

3. Given a block name, list files parents by lumi:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L953

[2]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_SC_LumiMask_PhEDEx_HG2004_Val_200330_093128_1213

**Describe the solution you'd like**
We should enable the `closed-out` status in the `StepChainParentageFixTask` cherrypy thread, such that Unified can check the `ParentageResolved` value before announcing StepChain workflows.
 
**Describe alternatives you've considered**
Other alternatives  are to  have WMAgent to only publish full information to DBS - this requiters long term development plans and redesign of portions of the WMAgent

**Additional context**
There is a related issue in Unified:
https://github.com/CMSCompOps/WmAgentScripts/issues/545

**Comment by amaltaro** [comment]
Reopening it because PR #9657 does not really fix this issue, it will only mitigate the impact of having datasets with incomplete parentage information getting announced.

**Comment by amaltaro** [comment]
Actually, this issue has been fixed. We can follow the real issue here: https://github.com/dmwm/WMCore/issues/9537
