### ISSUE TITLE
Top level task must consider pileup location of subsequent tasks

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9658]
**Impact of the bug**
WMAgent

**Describe the bug**
I still cannot believe this is the current buggy behaviour...
Apparently, when the agent acquires a TaskChain WQE without any input dataset, it creates the top level jobs against all the sites in the SiteWhitelist, even if the subsequent tasks require a pileup dataset.

**How to reproduce it**
Injecting a TaskChain workflow, without any input dataset and a pileup dataset in the Task2.
Assign it to a site containing the pileup and another without it.

**Expected behavior**
Top level jobs should be created against the intersection(SiteWhitelist - SiteBlacklist, PileupLocation). 

**Additional context and error message**
Problem reported in this issue: https://its.cern.ch/jira/browse/CMSCOMPPR-12155
Error message in WMStats is:
```
    Fatal Exception (Exit Code: 8029)

        An exception of category 'NoSecondaryFiles' occurred while
           [0] Constructing the EventProcessor
           [1] Constructing module: class=MixingModule label='mix'
        Exception Message:
        RootEmbeddedFileSequence no input files specified for secondary input source.
```

**Comment by hufnagel** [comment]
Why is this a bug? Is that top level job (which usually doesn't need pileup) site whitelist reused for the later step that does need pileup? I thought the later steps are based on input data location (where the input data from the previous jobs has been written) modulo pileup location?

**Comment by hufnagel** [comment]
Example: GenSimDigiReco TaskChain

Why should you care about pileup location for the GenSim?

**Comment by amaltaro** [comment]
Because if the GenSim runs in a location that does not host the pileup data. Digi would be created against the site holding the GenSim output. Which then breaks during runtime, given that there are no secondary files at that location.

**Comment by hufnagel** [comment]
Ok, yes, thought of that as well.

Problem is, pileup is not widely distributed. Basically to first order most pileup is read via AAA. So even if you make this change, it can't actually work this way, you would have to rely on Unified to work around your restrictive site white list to get any actual work through the system.

**Comment by hufnagel** [comment]
In light of the desire to move Unified functionality into the agent, I would think a bit of what you are trying to achieve here. If you make this change as simply "fix this bug", you'll be relying more on Unified, not less.

**Comment by vlimant** [comment]
Unified was taking care of limiting the sitewhitelist to site holding the secondary ; now this is gone apparently, revealing the bug
