### ISSUE TITLE
MSOutput REST interface is not working

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9661]
**Impact of the bug**
MicroServices

**Describe the bug**
MSOutput REST interface is not working. The following link is broken:
https://cmsweb-testbed.cern.ch/ms-output/data/status

**How to reproduce it**
Just browse the broken link.

**Expected behavior**
It should return the service status. similar to:
https://cmsweb-testbed.cern.ch/ms-transferor/data/status 

**Additional context and error message**

**Comment by todor-ivanov** [comment]
@amaltaro This bug will be resolved once this one [1] is merged. I tested it on my machine and the fix is working.  We can close the issue on our end either immediately or wait for the next deployment in testbed. 

[1]
https://github.com/dmwm/deployment/pull/892

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/deployment/pull/892
