### ISSUE TITLE
Unable to start agent in Docker container

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#9675]
**Impact of the bug**
WMAgent Container:
 - WMA_TAG=1.2.8
 - DEPLOY_TAG=HG1909e

**Describe the bug**
run.sh script fails to perform agent initialization actions. The script exits with apparent success. After that, it is not possible to start the agent inside the container.

**How to reproduce it**
I'm currently trying to run wmagent from a container in a Tier0 machine. In order to achieve that, I followed [this guide](https://github.com/dmwm/WMCore/wiki/WMAgent-in-Docker). I changed folder bidings to fit T0 machines folder structure. 

**Expected behavior**
I should be able to start agent after running run.sh. Also, said script should properly report errors.

**Additional context and error message**

Output of run.sh show issues while initializing the agent. Most of them referring to "unknown action"  
```
*** Activating the agent ***
+ cd /data/srv/wmagent/current/config/tier0/
+ ./manage activate-agent
./manage: unknown action 'activate-agent', please try './manage help' or documentation.
+ echo 'Done!'
Done!
```
```
+ echo '*** Initializing the agent ***'
*** Initializing the agent ***
+ ./manage init-agent
./manage: unknown action 'init-agent', please try './manage help' or documentation.
+ echo 'Done!'
Done!
```
The script is also unable to use wmagent-resource-control. 
```
Adding ALL sites to resource-control...
+ ./manage execute-agent wmagent-resource-control --add-all-sites --plugin=SimpleCondorPlugin --pending-slots=50 --running-slots=50 --down
wmagent-resource-control is not a binary in WMCore/bin
+ echo 'Done!'
Done!
```
After running run.sh, calling  `$manage start-agent` will fail with the following output:
```
Starting WMAgent...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/bin/wmcoreD", line 152, in <module>
    cfgObject = loadConfigurationFile(config)
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMCore/Configuration.py", line 597, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/data/srv/wmagent/v1.2.8/config/wmagent/config.py
Due to error:
name 'config' is not definedTraceback (most recent call last):
  File "/data/srv/wmagent/v1.2.8/sw/slc7_amd64_gcc630/cms/wmagent/1.2.8/lib/python2.7/site-packages/WMCore/Configuration.py", line 590, in loadConfigurationFile
    modPath[1], modPath[2])
  File "/data/srv/wmagent/v1.2.8/config/wmagent/config.py", line 1, in <module>
    config.RetryManager.PauseAlgo.default.coolOffTime = {'create': 10, 'job': 10, 'submit': 10}
NameError: name 'config' is not defined
```
I've checked existance and permissions to both config.py and wmagent-resource-control and did not find any problems.

**Comment by amaltaro** [comment]
@germanfgv German, we will probably get back to this issue only in the next week. We are having quite some problems with central production these days.

**Comment by goughes** [comment]
German and I got this worked out over Slack. First two errors were due to using the T0 manage script instead of the standard WMAgent script. Third error was related to the new deployment procedure for WMCore 1.3.3.patch2. Sounds like it is almost working, but we could definitely make the container more T0 friendly after all the bugs are worked out.

**Comment by germanfgv** [comment]
The agent is now successfully running inside the container. As Eric said, the errors where solved by pointing to the correct manage script and by fixing the host agent configuration.

I'll go ahead and close this issue, and If something else shows up I'll create another issue. Thank you for your help.

**Comment by amaltaro** [comment]
Thank you very much, @germanfgv and @goughes . I'm closing this issue then.
