### ISSUE TITLE
ReqMgr2 web UI responding very slowly (fetch API)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9678]
**Impact of the bug**
ReqMgr2 (web UI, REST APIs are not affected)

**Describe the bug**
While browsing through a few workflows in the ReqMgr2 UI, I see some of those query strings are taking many minutes to respond, e.g.:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_EXO-RunIISummer16NanoAODv6-08201__v1_T_200325_092206_950
which took 4.5min to get served.

while this:
https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_task_EXO-RunIISummer16NanoAODv6-08201__v1_T_200325_092206_950

responds in less than a second.
Thus, there is some extra information coming from the `fetch` API that is slowing the whole thing.

**How to reproduce it**
Just open the fetch link above

**Expected behavior**
First we need to identify what is causing the slowness in this response (I've seen cases where cmssdt affects it, for instance). Then we need to evaluate whether we need such information.
Finally, this API should respond very quickly (<1sec), given that it's specific to one single workflow.

**Additional context and error message**
none

**Comment by goughes** [comment]
The slowness on the UI comes from calling `getTeams()` here:
https://github.com/dmwm/WMCore/blob/d2fb9d89341c515319062d07703a212a638c4adf/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L586

The method queries the reqmon API `https://cmsweb.cern.ch/wmstatsserver/data/teams` 

ReqMgr logs show that accessing the web UI takes just over 270 secs (the pycurl timeout value). 
```
"GET /reqmgr2/fetch?rid=cmsunified_task_HIG-RunIIFall17pLHE-00006__v1_T_200326_054925_8778 HTTP/1.1" 200 OK [data: 3187 in 25003 out 270640886 us ]
```
So likely this API call times out and the team info is then read from the cache.
https://github.com/dmwm/WMCore/blob/d2fb9d89341c515319062d07703a212a638c4adf/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L389

I cannot get a response from this API to determine what is returned. ResourceContolUpdater also gets team information for agents, but logs show that thread isn't timing out. That thread has its own instance of WMStatsReader. Further investigation is needed.

**Comment by amaltaro** [comment]
Haaa, it makes a lot of sense! That API returns a simple list of agent names, e.g.:
https://cmsweb-testbed.cern.ch/wmstatsserver/data/teams

which - internally - uses the wmstats `requestcache` content, which has been broken for the last many days.
So, I'd suggest to actually cache the content of that getTeams API. Given that it does not change that often, we can certainly have an hour or two of cache lifetime.

**Comment by goughes** [comment]
Another thing to note, the team info is pulled every time fetch is called, but the only time the team information is used is when a request is in assignment-approved status. We could eliminate many unnecessary calls to wmstatsserver by only pulling the team info if a request has that status.
