### ISSUE TITLE
Deprecate ReqMgr2 WMDataMining thread

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9701]
**Impact of the new feature**
Deprecation of a cherrypy thread not used for the last 2 or 3 years.

**Is your feature request related to a problem? Please describe.**
Not a problem, just code cleanup, given that that functionality is no longer needed.

**Describe the solution you'd like**
Deprecate this package:
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/WMDataMining

and completely delete the cherrypy extension here:
https://github.com/dmwm/deployment/blob/master/reqmgr2/config.py#L127

Note: there might be further reference to the WMDataMining functionality.

**Describe alternatives you've considered**
keep code around and cherrypy thread commented out :D

**Additional context**
none

**Comment by amaltaro** [comment]
Unless @ericvaandering Eric has any reasonable argument against it ;)

**Comment by ericvaandering** [comment]
Not if no one is using it. This was an attempt to help Maria understand where the bottlenecks were in moving workflows along.
