### ISSUE TITLE
Create proper destination output map for nonRelval workflows based on the campaign configuration

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9756]
**Impact of the new feature**
MicroServices, Rucio

**Is your feature request related to a problem? Please describe.**
When we  started re implementing the basic logic for the MSOutput module for MicroServices we repeated what was already done in Unified. Shortly speaking, it is a separation of how the data placement submissions are treated based on type of workflows (Relval, NonRelval). 
   * For `RelVal` requests there is a well defined destination map based on the data tiers. 
   * For `NonRelVal` requests all values are left by default to be decided by DDM like :
      - number of copies
      - destination is a wildcard list ['T1_', 'T2_*'] etc.
 
Once we start moving to Rucio all those parameters need to be defined on our side. The strategy we  opted for so far is to create a proper `destinationOutputMap` for all the workflows - 
   * For `RelVal` based on the data tier schema we already have [1]
   * For `NonRelval`  based on the campaign configuration, which typically looks something like [2]

Different output datasets from one and the same workflow may fall under different campaigns.
From the Workflow configuration we build a full `cmpaignOutputMap` which looks like [3]. So for the moment, a typical destination map looks like [4]. Unfortunately the cmpaign configuration provides mostly information needed for starting the workflow and little to nothing related to the final data destination. Another interesting question is how to obtain the number of copies too. So before we continue with any actual implementation a discussion needs to happen, for which I am tagging few people here who might be able to help:

@ericvaandering 
@nsmith-
@klannon 
@amaltaro 

[1]
https://github.com/dmwm/WMCore/blob/033f7e31e8d7ab9df67956698b0d29b09c2f5a4d/src/python/WMCore/MicroService/Unified/MSOutput.py#L704-L716

[2]
```
...
  u'HG2006_Val': {u'CampaignName': u'HG2006_Val',
                 u'ConfigType': u'CAMPAIGN_CONFIG',
                 u'MaxCopies': 1,
                 u'PartialCopy': 1,
                 u'PrimaryAAA': False,
                 u'Secondaries': {},
                 u'SecondaryAAA': False,
                 u'SecondaryLocation': [u'T1_US_FNAL', u'T2_CH_CERN'],
                 u'SiteBlackList': [],
                 u'SiteWhiteList': [u'T1_US_FNAL',
                                    u'T2_CH_CERN',
                                    u'T2_US_MIT',
                                    u'T2_IT_Legnaro',
                                    u'T2_US_Nebraska'],
                 u'_id': u'CAMPAIGN_CONFIG_HG2006_Val'},
...
 u'HINPbPbAutumn18DR': {u'CampaignName': u'HINPbPbAutumn18DR',
                        u'ConfigType': u'CAMPAIGN_CONFIG',
                        u'MaxCopies': 1,
                        u'PartialCopy': 1,
                        u'PrimaryAAA': False,
                        u'Secondaries': {u'/MinBias_Hydjet_Drum5F_2018_5p02TeV/HINPbPbAutumn18GS-103X_upgrade2018_realistic_HI_v11-v1/GEN-SIM': [u'T1_RU_JINR',
                                                                                                                                                 u'T1_FR_CCIN2P3']},
                        u'SecondaryAAA': False,
                        u'SecondaryLocation': [],
                        u'SiteBlackList': [u'T1_US_FNAL',
                                           u'T2_US_Purdue',
                                           u'T2_US_Caltech',
                                           u'T2_US_Florida',
                                           u'T2_US_Nebraska',
                                           u'T2_US_UCSD',
                                           u'T2_US_Wisconsin',
                                           u'T2_CH_CERN',
                                           u'T2_CH_CERN_HLT'],
                        u'SiteWhiteList': [u'T1_RU_JINR', u'T1_FR_CCIN2P3'],
                        u'_id': u'CAMPAIGN_CONFIG_HINPbPbAutumn18DR'},
...
```
[3]
```
u'campaignOutputMap': [{u'campaignName': u'RunIISummer19UL17MiniAOD',
                         u'datasets': [u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17MiniAOD-106X_mc2017_realistic_v6-v1/MINIAODSIM']},
                        {u'campaignName': u'RunIISummer19UL17wmLHEGEN',
                         u'datasets': [u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17wmLHEGEN-106X_mc2017_realistic_v6-v1/GEN',
                                       u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17wmLHEGEN-106X_mc2017_realistic_v6-v1/LHE']},
                        {u'campaignName': u'RunIISummer19UL17RECO',
                         u'datasets': [u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17RECO-106X_mc2017_realistic_v6-v1/AODSIM']}],
```
[4]
```
 u'destinationOutputMap': [{u'datasets': [u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17wmLHEGEN-106X_mc2017_realistic_v6-v1/LHE',
                                          u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17MiniAOD-106X_mc2017_realistic_v6-v1/MINIAODSIM',
                                          u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17RECO-106X_mc2017_realistic_v6-v1/AODSIM',
                                          u'/GluGluToBulkGravitonToHH_HToVhadVhad_M-3000_narrow_WZHtag_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer19UL17wmLHEGEN-106X_mc2017_realistic_v6-v1/GEN'],
                            u'destination': [u'T2_*', u'T1_*']}],

```

**Describe the solution you'd like**
Output dataset non-custodial/disk destination - for standard workflows - needs to be decided based on two possible configuration parameters:
* from the Unified configuration: using the parameters `tiers_no_DDM` and `tiers_to_DDM `, see:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/unifiedConfiguration.json#L226-L232
* and from the campaign level configuration: using the parameter `TiersToDM`.

Note that the campaign-level configuration has precedence over the Unified configuration.

In addition to that, the number of copies is meant to be assigned from the campaign configuration value `MaxCopies`.

Last but not least, we need to update this utilitarian script:
https://github.com/dmwm/WMCore/blob/master/bin/adhoc-scripts/parseUnifiedCampaigns.py
which takes campaign configuration from Unified MongoDB, apply the WMCore campaign schema, and inject the correspondent campaign configuration into central CouchDB.

**Describe alternatives you've considered**
Eventually stop using the Unified-based campaigns and provide all the APIs and validation for others to update campaign in central couchDB.

**Additional context**
none

**Comment by nsmith-** [comment]
This relates to #9639 
If I understand this right, this is a significant departure from having a `CustodialSites` and `NonCustodialSites` field per workflow. I am not against it, just trying to understand.

I would advocate that any destination specifier is written as an [RSE Expression](https://rucio.readthedocs.io/en/latest/rse_expressions.html) rather than lists, lists with wildcards, etc.

**Comment by todor-ivanov** [comment]
Hi @nsmith- thanks for commenting on this. The comment you make here is quite meaningful and very helpful. I think it was not given a significant thought in that direction, though. We haven't discussed any adaption of the `[Non]CustodialSites` workflow parameters so far. If it could be the most reliable source of information about data destination we could easily preserve those in the current implementation too. From my understanding they can give us a 'workflow level' granularity when it comes to defining where the output data should go. While using the campaign map - we can benefit from a finer 'dataset level' granularity for the same purpose (every Output dataset of one and the same workflow can be associated with different a campaign). It is only, that the information we get from the campaign configuration so far, has nothing to do with data placement. The 'SiteWhiteList' and 'SiteBlacklist' from the campaign configuration are more like run destinations for the workflow and give no information about the final data placement.  So even though we build correctly the campaign based output dataset map we cannot benefit much from the campaign configuration itself to create the next step - which should be the destination map. If there is any way to enlarge the cmapaign configuration and put that information there in advance, that would give us quite good flexibility. And would basically solve all our problems. 

As of the RSE format of the destination map, the conversion to it should be straight forward.

**Comment by amaltaro** [comment]
@todor-ivanov @nsmith- my suggestion is to start - once output data placement goes to Rucio - with a generic RSE expression, which would cover any T1 or T2 disk endpoints. Such that Rucio can decide what the best location for the data is.

About custodial location, we could also provide a generic expression like `Tape` and let Rucio decide where to put data.

I still think keeping the Campaign logic around will be useful for the long run. I foresee a case where we want to ensure that HI data only gets archived at a given place, and that it's made available at Vanderbilt storage, and so on. I guess that can be discussed later this year though.

**Comment by todor-ivanov** [comment]
Hi @nsmith-  I am working on this, but I experience some doubts about if I am building the best `RSE Expressions`. Here [1] is a simple example when it comes to a single geographical region (taken just for brevity). All looks fine at a first glance, but actually in this list there are both `T1_US_FNAL_Disk` and `T1_US_FNAL_Type`, which doesn't sound correct to me. And I do not see a way to restrict only to `Disk`, because:

   * I cannot distinguish between them both based on any RSE parameter besides the Name itself [2]
   * There is no way for me to put a regular expression or a wildcard regarding any parameter in the `RSE Expression`.  So name parsing is not an option regardless if we are talking about the `RSE name` itself or `site pnn`

Any advice here would be helpful. Thanks in advance!



[1]
```
In [35]: for i in rcl.list_rses(rse_expression='(tier=2|tier=1)&cms_type=real&country=US'):
    ...:     pprint(i)

{u'rse': u'T2_US_Purdue'}
{u'rse': u'T1_US_FNAL_Disk'}
{u'rse': u'T2_US_Florida'}
{u'rse': u'T2_US_Nebraska'}
{u'rse': u'T2_US_Caltech'}
{u'rse': u'T1_US_FNAL_Tape'}
{u'rse': u'T2_US_Wisconsin'}
{u'rse': u'T2_US_UCSD'}
{u'rse': u'T2_US_Vanderbilt'}
{u'rse': u'T2_US_MIT'}
```

[2]
```
In [36]: rcl.list_rse_attributes(rse='T1_US_FNAL_Disk')
Out[36]: 
{u'T1_US_FNAL_Disk': True,
 u'cms_type': u'real',
 u'country': u'US',
 u'fts': u'https://fts3.cern.ch:8446',
 u'lfn2pfn_algorithm': u'cmstfc',
 u'pnn': u'T1_US_FNAL_Disk',
 u'quota_approvers': u'holzman,huangch,gutsche,dmason',
 u'rule_approvers': u'holzman,huangch,gutsche,dmason',
 u'tier': u'1'}

In [37]: rcl.list_rse_attributes(rse='T1_US_FNAL_Tape')
Out[37]: 
{u'T1_US_FNAL_Tape': True,
 u'cms_type': u'real',
 u'country': u'US',
 u'fts': u'https://fts3.cern.ch:8446',
 u'lfn2pfn_algorithm': u'cmstfc',
 u'pnn': u'T1_US_FNAL_Buffer',
 u'quota_approvers': u'holzman,huangch,gutsche,dmason',
 u'rule_approvers': u'holzman,huangch,gutsche,dmason',
 u'tier': u'1'}
```

**Comment by nsmith-** [comment]
You can use `rse_type=DISK` in the expression to remove tape, and `rse_type=TAPE` for the converse.

**Comment by todor-ivanov** [comment]
Thanks @nsmith-  It odes the trick [1]. I obviously missed to find that option myself, because it is somehow not listed among the list of `rse_attributes`.  Is that intended, or it just falls under a different category in general? Thanks for the hint once again! 


[1]
In [124]: for i in rcl.list_rses(rse_expression='(tier=1|tier=2)&cms_type=real&rse_type=DISK&country=US'):
     ...:     pprint(i)

{u'rse': u'T2_US_Purdue'}
{u'rse': u'T1_US_FNAL_Disk'}
{u'rse': u'T2_US_Florida'}
{u'rse': u'T2_US_Nebraska'}
{u'rse': u'T2_US_Caltech'}
{u'rse': u'T2_US_Wisconsin'}
{u'rse': u'T2_US_UCSD'}
{u'rse': u'T2_US_Vanderbilt'}
{u'rse': u'T2_US_MIT'}

**Comment by amaltaro** [comment]
For the record, the initial description with the solution we want/need has been updated.
