### ISSUE TITLE
MSoutput: Work only on worflows in status ['closed-out', 'announced']

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9757]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
We need to exclude `completed` status from the list of statuses to be considered by the MSOutPut module for  MicroServices. The list [`closed-out`, `announced`] will be pretty much sufficient.    

**Describe the solution you'd like**
remove `completed` from the list of workflow statuses.

**Describe alternatives you've considered**
N/A

**Additional context**
No

**Comment by amaltaro** [comment]
Todor, the actual status is `completed`. Please update the description

**Comment by todor-ivanov** [comment]
Thanks Alan. I updated the description.
