### ISSUE TITLE
Rucio wrapper API has a deprecated client API: get_account_usage

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9786]
**Impact of the bug**
WMCore in general

**Describe the bug**
While working on the MSTransferor code to support Rucio APIs, I noticed that our code to fetch account usage:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py#L135

no longer works and it now raises an exception (traceback below).

Investigating the Rucio repository, I found this PR which actually replaces that API by a few others:
https://github.com/rucio/rucio/pull/2797

With this, we should learn that CI tests for Rucio APIs is a must in WMCore.

**How to reproduce it**
Create a rucio client object and call:
```
>>> res = client.get_account_usage("wma_test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Client' object has no attribute 'get_account_usage'
```

**Expected behavior**
We need to find the proper python client API to be used. This API has to provide us with the following information:
```
{'quota': item['bytes_limit'],
 'bytes_limit': item['bytes_limit'],
 'bytes': item['bytes'],
 'bytes_remaining': item['bytes_remaining']})
```
such that our input data placement logic can respect storage limitations.

**Additional context and error message**
```
Traceback (most recent call last):
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre4/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSTransferor.py", line 175, in execute
    self.updateCaches()
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/external/py2-retry/0.9.1-comp5/lib/python2.7/site-packages/retry/compat.py", line 16, in wrapper
    return caller(f, *args, **kwargs)
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/external/py2-retry/0.9.1-comp5/lib/python2.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/external/py2-retry/0.9.1-comp5/lib/python2.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre4/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSTransferor.py", line 128, in updateCaches
    self.rseQuotas.fetchStorageUsage(getattr(self, "rucio", self.phedex))
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre4/lib/python2.7/site-packages/WMCore/MicroService/Unified/RSEQuotas.py", line 150, in fetchStorageUsage
    for item in dataSvcObj.getAccountUsage(self.dataAcct):
  File "/data/srv/HG2007f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 146, in getAccountUsage
    res = list(self.cli.get_account_usage(acct, rse=rse))
AttributeError: 'Client' object has no attribute 'get_account_usage'
```

**Comment by amaltaro** [comment]
I had a look at all the python client APIs available, and the only one that returns a somehow meaningful content is:
```
>>> res = client.get_local_account_usage("wma_test")
>>> list(res)
[{u'files': 327, u'rse': u'T2_CH_CERN_Test', u'bytes': 859054118298, u'bytes_remaining': -859054118298, u'rse_id': u'2c053ee8a43c4b48a5a8dfbe627a0e93', u'bytes_limit': 0}, {u'files': 287, u'rse': u'T1_US_FNAL_Disk', u'bytes': 1122049837430, u'bytes_remaining': -1122049837430, u'rse_id': u'6ea57b6942c64301b15d15c744ad761d', u'bytes_limit': 0}, {u'files': 2, u'rse': u'T1_US_FNAL_Tape_Test', u'bytes': 10002544, u'bytes_remaining': -10002544, u'rse_id': u'7d278590db4f4d29b13414c14366ef6c', u'bytes_limit': 0}, {u'files': 52, u'rse': u'T1_US_FNAL_Disk_Test', u'bytes': 43857805876, u'bytes_remaining': -43857805876, u'rse_id': u'c9c0b79e9d55433e8d506ae91a0d2151', u'bytes_limit': 0}, {u'files': 5214, u'rse': u'T2_CH_CERN', u'bytes': 13703055768287, u'bytes_remaining': -13703055768287, u'rse_id': u'f7d61f9d3a6e48159421a20a1a17389d', u'bytes_limit': 0}, {u'files': 1, u'rse': u'T1_US_FNAL_Tape', u'bytes': 4992972, u'bytes_remaining': -4992972, u'rse_id': u'fab02327b7f7424abb04549e7a1736f7', u'bytes_limit': 0}]
```

I'm not sure what the difference is between local and global account, but the global APIs always return an empty content as response.

In addition to that, as one can see in the output, this `get_local_account_usage` API seems to be listing information only for sites that the rucio account has actually created data rules. Also, `bytes_limit` seems to be always 0 (I saw the same for wma_prod).

@ericvaandering @nsmith- would you have any advice on how we can accomplish it after these changes on the Rucio side?

**Comment by ericvaandering** [comment]
Right, all the old account usages are now "local" 

Global is the ability to assign quotas based on globally or RSE expressions, which probably has no use for production

**Comment by ericvaandering** [comment]
I think the issue is that we didn't give wma_test a quota. The quotas are set for transfer_ops

**Comment by amaltaro** [comment]
@ericvaandering  Eric, and do we have RSE quotas defined for the "wma_prod" account? 

I see - at least - two use cases for the MSTransferor (input data placement):
1. given a large set of RSEs, and some input blocks to be distributed, we need to make sure that blocks only go to places with quota available (and that they get evenly distributed on those (best would be to let Rucio normalize it, but that will have to wait for the future)
2. given a large'ish set of RSEs, and multiple input data (like primary/parent and pileup), we need to force a minimum single RSE intersection of those RSEs holding these data. So, we need to know before hand where data will get placed.

Managing these quotas from within MSTransferor isn't that great, so if you have another suggestion here, I'm all ears.

**Comment by nsmith-** [comment]
Regardless of what we set, the `wma_prod` account is an administrator account and the quotas are just "for show" and do not prevent rules from creating.
Based on your use cases, in fact global quotas seem to be the better solution: we can set a quota on a RSE expression such as `tier=2&type=disk` or similar and then all input transfers for a certain class of workflows would make rules on their input with that expression. Then rucio is responsible for distributing as appropriate. After the rule is complete (something MSTransferor can monitor), then it can query what sites ended up being selected and using that to assign the allow-list for the jobs.

**Comment by amaltaro** [comment]
I'm not sure making a data placement and waiting for the transfer to complete to only then proceed with the workflow (and workflow SiteWhitelist) is our best option. Eventually we will want to have agents to start working on a workflow as soon as a few of the input blocks were made available.

Also changing the SiteWhitelist only when the data placement is done by Rucio, would require a bunch of logical and design changes, meaning a longer ETA.

Perhaps another option - for the moment - would be to replicate the Detox quotas (DataOps and others) somewhere else, and keep using those until we can completely delegate input data placement to Rucio, reducing all the unneeded complexity in MSTransferor.

**Comment by nsmith-** [comment]
Well for the case where you can process single blocks, you can make a rule per block and then just have to wait for the rule applying to that block to complete to read its location and start work, rather than making a rule for all blocks at once.
I'm not sure what the issue is with waiting on the SiteWhitelist, don't you have to modify it in MSTransferor anyway?

**Comment by amaltaro** [comment]
Nope. Unified assigns workflows based on many metrics, plus on the planned locations for the pileup dataset(s).
MSTransferor carries out the input data placement based on the SiteWhitelist of the workflow, on the Campaign configuration, and on the pileup configuration within the Campaign. But yes, eventually we want to get the data transfer done, and then we can update the workflow SiteWhitelist once again.

I'm afraid your comment above does not support our use case number 2.

**Comment by nsmith-** [comment]
Sure, I was mostly speaking to case 1. I think case 2 is the less frequent one, right?
Would having a quota and then checking if there is available space at an RSE selected by MSTransferor work for case 2? We can certainly make a quota, even for a different account. One thing I want to point out, is in general we can have as many `wma_*` accounts as we like, each with different quotas, if it helps at all. On our side, it makes some book-keeping easier in fact, since per-account usage is aggregated.

**Comment by amaltaro** [comment]
> Sure, I was mostly speaking to case 1. I think case 2 is the less frequent one, right?

I do not have numbers. But I would say half of the workflows we get in production require some sort of pileup dataset.

> Would having a quota and then checking if there is available space at an RSE selected by MSTransferor work for case 2?

Exactly! This is basically the problem I've been trying to solve.

I'll try to test this local API in the coming hours, but if you have any other idea, please just let me know.

**Comment by nsmith-** [comment]
> I do not have numbers. But I would say half of the workflows we get in production require some sort of pileup dataset.

Uh but case 2 is specifically when there is classical mixing pileup right? Otherwise for premix pileup it does not matter where the secondary is located, it will be read via AAA.

**Comment by amaltaro** [comment]
Yes, that applies mostly for classical pileup. But it could apply for premix pileup as well if they are not assigned with TrustPUSitelists = True.

So, trying to summarize the issue here. If I call:
```
>>> res = client.get_local_account_usage("wma_test")
```
it returns data for only a handful of sites, here is the full output:
```
>>> list(res)
[{u'files': 327, u'rse': u'T2_CH_CERN_Test', u'bytes': 859054118298, u'bytes_remaining': -859054118298, u'rse_id': u'2c053ee8a43c4b48a5a8dfbe627a0e93', u'bytes_limit': 0}, {u'files': 290, u'rse': u'T1_US_FNAL_Disk', u'bytes': 1122073832305, u'bytes_remaining': -1122073832305, u'rse_id': u'6ea57b6942c64301b15d15c744ad761d', u'bytes_limit': 0}, {u'files': 2, u'rse': u'T1_US_FNAL_Tape_Test', u'bytes': 10002544, u'bytes_remaining': -10002544, u'rse_id': u'7d278590db4f4d29b13414c14366ef6c', u'bytes_limit': 0}, {u'files': 52, u'rse': u'T1_US_FNAL_Disk_Test', u'bytes': 43857805876, u'bytes_remaining': -43857805876, u'rse_id': u'c9c0b79e9d55433e8d506ae91a0d2151', u'bytes_limit': 0}, {u'files': 5250, u'rse': u'T2_CH_CERN', u'bytes': 13773732395083, u'bytes_remaining': -13773732395083, u'rse_id': u'f7d61f9d3a6e48159421a20a1a17389d', u'bytes_limit': 0}, {u'files': 1, u'rse': u'T1_US_FNAL_Tape', u'bytes': 4992972, u'bytes_remaining': -4992972, u'rse_id': u'fab02327b7f7424abb04549e7a1736f7', u'bytes_limit': 0}]
```

while the production rucio account:
```
>>> res = client.get_local_account_usage("wma_prod")
```
returns - apparently - data for all the T1 and T2 RSEs. However, they are set with `bytes_limit=0`, which means, `bytes_remaining` is always negative, e.g.:
```
>>> pprint(list(res))
[{u'bytes': 30855143179,
  u'bytes_limit': 0,
  u'bytes_remaining': -30855143179,
  u'files': 88,
  u'rse': u'T2_AT_Vienna',
  u'rse_id': u'0465a108757a4acb8f2f18085b8e25f7'},
 {u'bytes': 1648526431185,
  u'bytes_limit': 0,
  u'bytes_remaining': -1648526431185,
  u'files': 3326,
  u'rse': u'T1_US_FNAL_Disk',
  u'rse_id': u'087ee3383b9d45f6b31814af07b2c56d'},
...
```

this Friday I'm leaving on vacation for 3 weeks. Is there anything that we can do still today (otherwise I'm afraid I won't manage to get this sorted before I leave)? 

Should we use the Detox quota until the beginning of September? Should we make input data placement without bothering about the storage quota?

@ericvaandering @nsmith- if you prefer to have a quick chat over zoom, just ping me on slack and we can make it before I stop working today.

**Comment by nsmith-** [comment]
I updated all `wma_test` quotas on integration instance.

**Comment by amaltaro** [comment]
@nsmith- Nick, is there any reason I only see quota for a handful of sites:
```
>>> list(client.get_local_account_usage("wma_test", rse=None))
[{u'files': 327, u'rse': u'T2_CH_CERN_Test', u'bytes': 859054118298, u'bytes_remaining': -859054118298, u'rse_id': u'2c053ee8a43c4b48a5a8dfbe627a0e93', u'bytes_limit': 0}, {u'files': 292, u'rse': u'T1_US_FNAL_Disk', u'bytes': 1122093834615, u'bytes_remaining': 6246877906165385, u'rse_id': u'6ea57b6942c64301b15d15c744ad761d', u'bytes_limit': 6248000000000000}, {u'files': 2, u'rse': u'T1_US_FNAL_Tape_Test', u'bytes': 10002544, u'bytes_remaining': -10002544, u'rse_id': u'7d278590db4f4d29b13414c14366ef6c', u'bytes_limit': 0}, {u'files': 52, u'rse': u'T1_US_FNAL_Disk_Test', u'bytes': 43857805876, u'bytes_remaining': -43857805876, u'rse_id': u'c9c0b79e9d55433e8d506ae91a0d2151', u'bytes_limit': 0}, {u'files': 5260, u'rse': u'T2_CH_CERN', u'bytes': 13791475274971, u'bytes_remaining': 4709208524725029, u'rse_id': u'f7d61f9d3a6e48159421a20a1a17389d', u'bytes_limit': 4723000000000000}, {u'files': 1, u'rse': u'T1_US_FNAL_Tape', u'bytes': 4992972, u'bytes_remaining': -4992972, u'rse_id': u'fab02327b7f7424abb04549e7a1736f7', u'bytes_limit': 0}]
```
?

**Comment by nsmith-** [comment]
It only returns sites where usage > 0. If you want the full list of sites where you have quota you could use `client.get_local_account_limits(account)`

**Comment by amaltaro** [comment]
Awesome!
```
>>> res = client.get_local_account_limits("wma_test")
>>> pprint(res)
{u'T1_DE_KIT_Disk': 2676000000000000,
 u'T1_ES_PIC_Disk': 833000000000000,
 u'T1_FR_CCIN2P3_Disk': 1174000000000000,
```
