### ISSUE TITLE
Create unit tests for MSOutputTemplate

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9790]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
This is a followup from this PR https://github.com/dmwm/WMCore/pull/9772#pullrequestreview-441492839
We need to create unit tests for MSOutputTemplate. The tests should be addressing mostly input vs. output Documents, which may be simulated in the test directly. But similarly to https://github.com/dmwm/WMCore/issues/9789 we may need to have a MongoDB instance for real. 

**Describe the solution you'd like**
Crate unit tests for MSOutputTemplate.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No

**Comment by amaltaro** [comment]
Done in: https://github.com/dmwm/WMCore/pull/9901
