### ISSUE TITLE
Gather list of PSet tweaks applied by WMAgent during job runtime

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9808]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Yes, it's related to the tightly coupling of WMCore, WMControl and CMSSW, and the complications affecting the support of multiple python versions (in CMSSW and WMCore) and job configuration (Pset) tweaks applied during runtime.

**Describe the solution you'd like**
This issue is meant to be an investigation of what exactly is tweaked by WMAgent - during the job runtime; what the source of the information is (things from the workflow description? things from the WMAgent job description? things based on the site and/or storage? things related to the data to be accessed? etc)

I think the result of this issue should be something like:
* CMSSW/PSet parameter tweaked:
* data format
* data source

Once we have an (almost) exhaustive list, we can then have further discussions and see whether this PSet tweaking would be better maintained in a different place (like in the CMSSW itself), such that the agent would only need to call that script, passing all the arguments to it, and be done.

**Describe alternatives you've considered**
The other alternative is what we have right now, which is an auto-discover of the CMSSW latest python version, and then executing the PSetTweak script to perform all the tweaks with the own CMSSW python version.

**Additional context**
This is likely a good start for this: https://github.com/dmwm/WMCore/blob/master/src/python/PSetTweaks/WMTweak.py#L22
another place is: 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py

**Comment by khurtado** [comment]
Here is some initial logic:

1) The CMSSW executor runs a pre-script called: [SetupCMSSWPset](https://github.com/dmwm/WMCore/blob/8864d49526fa57466f3d6cd2d1a2546d38d12dd6/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L86) 
2) The SetupCMSSWPset will modify a Pset 3 times at the worker level:
- At the [task level](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L774-L776)
Where the input is: `self.process`, which is a stepSection of a [FwjReport](https://github.com/dmwm/WMCore/blob/189a3aa4e6460085b44eb7cfd61ac32b61424575/src/python/WMCore/FwkJobReport/Report.py)
- At the [job level](https://github.com/dmwm/WMCore/blob/e0741bf0f2ffb19e44aba1ce93c5dfb68e48f570/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L785-L786)
Where the input is: A WMBS Job object
- At the job level again, for [each output module](https://github.com/dmwm/WMCore/blob/e0741bf0f2ffb19e44aba1ce93c5dfb68e48f570/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L797-L798)

The [script command](https://github.com/dmwm/WMCore/blob/8864d49526fa57466f3d6cd2d1a2546d38d12dd6/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L220-L223) is called looks like this:

```
2020-07-15 00:03:37,065:INFO:Scram:    Invoking command: /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_0/external/slc6_amd64_gcc491/bin/python2.7 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset
```

**Comment by khurtado** [comment]
Closing this issue wih #10179

**Comment by amaltaro** [comment]
@khurtado just for completeness. Did you manage to compile that list in a single place? Or was it sort of on the fly as you found new tweaks to be applied? If it's all in one place, then could you please share it in this issue.

**Comment by khurtado** [comment]
Methods are in:
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime#methods-in-setupcmssw-that-require-scram
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime#methods-in-setupcmssw-that-require-reading-from-the-pset-besides-the-one-above

and the external scripts that handle them are in:
https://github.com/cms-sw/cmssw-wm-tools/tree/master/bin
