### ISSUE TITLE
US opportunistic sites need to be kept down in CERN agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9814]
**Impact of the bug**
WMAgent

**Describe the bug**
With the production running activity going down, I noticed that T3_US_SDSC is actually enabled in the CERN agents:
```
cmst1@vocms0252:/data/srv/wmagent/current $ $manage execute-agent wmagent-resource-control --site-name=T3_US_SDSC -p
Executing wmagent-resource-control --site-name=T3_US_SDSC -p ...
Thresholds and current status for all sites:

T3_US_SDSC - 0 running, 350 pending, 2000 running slots total, 375 pending slots total, Site is Normal:
...
```

as we know, CERN schedds are not - yet - able to run payload in the US Opportunistic resources, e.g.: 
T3_US_SDSC, T3_US_NERSC, T3_US_OSG, T3_US_TACC and T3_US_PSC (so far).

Which usually is not a big deal, because those sites are not mapped in the CRIC `data-processing` API:
http://cms-cric.cern.ch/api/cms/site/query/?json&preset=data-processing

so they don't even get inserted into the agent's resource-control.
However, I do see `T3_US_SDSC` being returned from that API, which means that there is a PNN defined for `T3_US_SDSC`, which makes it to be automatically inserted into the agent's local database.

**How to reproduce it**
add T3 sites in a CERN agent.

**Expected behavior**
We need to make sure CERN agents won't pick work for those sites, because otherwise, they will simply take up job slots and will never managed to run. The deployment script has this hook, so the change is super simple:
https://github.com/dmwm/WMCore/blob/master/deploy/deploy-wmagent.sh#L214

**Additional context and error message**
vocms0250, vocms0251 and vocms0252 configuration file have been changed and AgentStatusWatcher restarted.

**Comment by amaltaro** [comment]
@hufnagel is it expected to have a PNN defined in CRIC for `T3_US_SDSC`?

**Comment by hufnagel** [comment]
Probably related to T3_US_SDSC being right next to T2_US_UCSD and the latter having storage. Are you currently tying CERN resource control solely to the absence/presence of a mapped PNN? Not sure that's a good idea long term for multiple reasons. First, SDSC does have local storage access at UCSD. Secondly there might be similar T3 in Europe inside the Global Pool later. Also, the next HEPCloud T3 (Theta) will definitely have Rucio managed storage.

Can't we just add a black-list feature (i.e. don't add these sites to resource control) and configure this for the CERN agents? Or vice-versa a white list feature for the FNAL agents? Or do you want to avoid having differences in agent deployments/configurations?

**Comment by aperezca** [comment]
Isn't this precisely what solves the issue of having to route jobs from CERN to FNAL schedds?

Not that it's a feature we wouldn't like to have, of course, but still, e.g. removing NERSC from CERN agents/schedds would solve the issue... And we would save further discussions on e.g. how many jobs to route, whether or not they should remain visible to the global pool, etc.

**Comment by hufnagel** [comment]
It alone doesn't solve the issue completely, since Unified overflow right now completely ignores the agents configured sites and overflows based on it's own internal list. But that's arguably also something that should be changed.

**Comment by hufnagel** [comment]
That being said, overflow isn't an immediate problem, since all these jobs still have some sites in their white list that are reachable by that agents/schedd. Directly assigned workflows OTOH might now.

Alan, is this actually a concern here, did the CERN agents pull work for the current HEPCloud workflow and now can't run it because they can't reach HEPCloud resources?

**Comment by amaltaro** [comment]
@hufnagel if you check the CRIC link above, you will see that:
PSN: T3_US_SDSC
PNN: T3_US_SDSC
so it looks like it has its own storage endpoint.

> Are you currently tying CERN resource control solely to the absence/presence of a mapped PNN?

Yes, this is the script executed during the WMAgent deployment:
https://github.com/dmwm/WMCore/blob/master/bin/wmagent-resource-control#L99-L110
which is responsible for adding resources to the local agent database (as you can see, it relies on the data-processing API, which only returns entries that have a PSN <--> PNN mapping. This is what I've been planning to change to support any kind of PSN from the CRIC catalog (no matter whether there is a PNN or not).

> Can't we just add a black-list feature (i.e. don't add these sites to resource control) and configure this for the CERN agents?

Yes, that's what we have in the agent configuration, see:
https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L350

the only difference is that we actually add those resources to the database, even though they are *always* kept down/disabled.

**Comment by hufnagel** [comment]
I think we should remove the T3_US_SDSC PNN from CRIC since SDSC doesn't have it's own storage. There is a read rule for MINIAOD from the UCSD cache in it's SITECONF, but other than that everything is AAA (like the other sites). And even the MINIAOD is not really for production, but for (local) analysis.

**Comment by hufnagel** [comment]
I'll contact Stephan and ask him how to do this. Is there anything else for me to do here? Seems to me we have a plan for the rest, right?

**Comment by hufnagel** [comment]
Ok, I disabled the T3_US_SDSC PNN (on advice from Stephan, seems there is no way to remove a PNN from a site).

Alan, can you check if thar fixes the problem?

**Comment by hufnagel** [comment]
Ok, seems I can also remove the PNN, did that as well.

**Comment by todor-ivanov** [comment]
Hi @hufnagel , I just checked in vocms0252, and the site seems to appear  as Down in the schedd tight now: [1].  @amaltaro do we have a full list of opportunistic T3_US sites and in this situation do we still want to explicitly add them to [2].




[1]
```
cmst1@vocms0252:/data/srv/wmagent/current $ $manage execute-agent wmagent-resource-control --site-name=T3_US_SDSC -p
Executing wmagent-resource-control --site-name=T3_US_SDSC -p ...
Thresholds and current status for all sites:

T3_US_SDSC - 0 running, 0 pending, 2000 running slots total, 375 pending slots total, Site is Down:
```


[2]
https://github.com/dmwm/WMCore/blob/a09e2aefe700fb9b0d12b9f7089b21bde5a5bd62/etc/WMAgentConfig.py#L350

**Comment by amaltaro** [comment]
Todor, the list has been provided in the initial description:
 T3_US_SDSC, T3_US_NERSC, T3_US_OSG, T3_US_TACC and T3_US_PSC (so far).

but I think Dirk is about to commission some other resources as well?

**Comment by hufnagel** [comment]
T3_US_OSG is no longer in the list (the only resources in it are accessible normally through the global pool now). The new site we are commissioning is T3_US_ANL, but we expect it'll take some time before we are ready to use it. You might as well include it in a list of HEPCloud resources already though.

**Comment by hufnagel** [comment]
About T3_US_SDSC, is the 'Down' status expected? In CRIC the site shows up as 'production', with no storage associated with it.

https://test-cmssst.web.cern.ch/cgi-bin/set/ProdStatus/T3_US_SDSC

also shows it as production enabled.
