### ISSUE TITLE
Create an organized structure for PyPI packaging 

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#9822]
**Impact of the new feature**
This will help arrange the PyPI components of WMCore, allowing us to build the required packages without making a mess of the repo with multiple requirements files and setup.py scripts.

**Is your feature request related to a problem? Please describe.**
We need to package at least 6-7 things, which could lead to lots of duplication of files. Let's make sure we do this in a sane way.
Currently there are two setup scripts for wmcore and wmagent, which have the same content except for one line. 

**Describe the solution you'd like**
Be able to build and upload all the required packages to PyPI with a minimal footprint in the WMCore repo.

**Comment by amaltaro** [comment]
Closed by https://github.com/dmwm/WMCore/pull/9874
Erik, please reopen this issue if I'm wrong.
