### ISSUE TITLE
Customize pylintrc file for CRAB testing

### ISSUE THREAD

**Issue by ddaina** [dmwm/WMCore#9826]
**Impact of the new feature**
CRABServer, CRABClient

**Is your feature request related to a problem? Please describe.**
Not a problem at a moment, but we are starting to work on CRAB testing and that could possibly mean that some of the things which are currently defined in a same way for both WMCore and CRAB might needs to be changed.   

**Describe the solution you'd like**
For CRABServer, CRABClient we would like to customize [pylintrc](https://github.com/dmwm/WMCore/blob/master/standards/.pylintrc) file. For instance, we would like to disable following messages:

- C0103: Invalid %s name "%s"
- W0703: Catching too general exception %s
- R0912: Too many branches (%s/%s)
- R0914: Too many local variables (%s/%s)
- R0915: Too many statements (%s/%s)

More changes in the near future may follow. Therefore, the purpose of this issue is to discuss what could be the best way to customize this file for CRAB without affecting current testing behavior of WMCore.

**Describe alternatives you've considered**

1. Simply keep it as it is and ignore those messages in the pylint report (short term solution taking into account that other changes might be needed (?) );
2. Have a separate pylintrc for CRAB testing (over the time could possibly lead to two completely different standards used for WMCore and CRAB even though projects are coupled);
3. Agree on a way how to edit current code so that above described changes are applied only to CRAB testing, but not WMCore.

**Additional context**
None

FYI @belforte

**Comment by amaltaro** [comment]
@ddaina Hi Daina, I know you did some work here. I wonder if this issue is still relevant for you?

**Comment by ddaina** [comment]
Hi, Alan, 

No, sorry. I believe we discussed it and agreed on actions. I am closing it. 

Thanks.

**Comment by amaltaro** [comment]
Thanks Daina!
