### ISSUE TITLE
Temporarily increase memory requirements for a Harvest task

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9829]
**Impact of the new feature**
ReqMgr2 / WMAgent

**Is your feature request related to a problem? Please describe.**
Problem was reported in this JIRA ticket: https://its.cern.ch/jira/browse/CMSCOMPPR-16306

which turns out to be a problem with the latest version of ROOT.
Nonetheless, we need to find a quick workaround such that Release Validation activities can proceed. It looks like T0 is also affected by this problem, so we could provide a temporary patch for both the T0 and the RelVal agent.

**Describe the solution you'd like**
Hardcode memory requirements (and maxPSS in the watchdog) to a large enough number, maybe 5GB.
This change is supposed to be applied in ReqMgr2 (because the watchdog is configured during the workflow creation). However, the desire is to be able to edit the workflow once it comes to the RelVal agent, thus not requiring a hotfix for ReqMgr2 in cmsweb.

**Describe alternatives you've considered**
Do nothing and wait for the ROOT team to fix the problem.

**Additional context**
none

**Comment by amaltaro** [comment]
Apparently there is a workaround already in place for the RelVal case, more info here:
https://its.cern.ch/jira/browse/CMSCOMPPR-16306?focusedCommentId=3282070&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3282070

@germanfgv do you need these changes to be implemented for the T0 machinery?

**Comment by drkovalskyi** [comment]
We need it for Tier0 as well. It's better to have it and not to use it than hit a problem during data taking that cannot be easily fixed.

**Comment by germanfgv** [comment]
I agree with @drkovalskyi . This could be very useful for us.

**Comment by amaltaro** [comment]
@germanfgv @drkovalskyi  Are you having memory issues with the latest T0 replays? Do you need it for the upcoming MWGR? Just to know how the priority has to be set here.

**Comment by germanfgv** [comment]
Yes Alan. We are having memory issues in the current replay and we will need a workaround for the incoming MWGR. FYI, our current memory issue is with a RecoMergewrite_DQMIO task, not a Harvest task.

**Comment by amaltaro** [comment]
Patch has been made available and applied to the relval agent only (vocms0259).

**Comment by amaltaro** [comment]
Discussion on this topic is going to happen in January 2021. Further information in the non-HN thread "Plan for high memory relvals with CMSSW_11_1_0_patch3"

**Comment by amaltaro** [comment]
The workaround created in #9840 seems to be no longer necessary. This wasn't a WMCore issue either and RelVals seem to be stable with the standard agent configuration/code. Closing this issue.
