### ISSUE TITLE
Use setuptools instead of distutils for PyPI builds

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#9849]
**Impact of the new feature**
We use distutils to build pypi things currently. Setuptools is a more current approach for this.
Python packaging guide recommends setuptools: https://packaging.python.org/guides/tool-recommendations/

**Is your feature request related to a problem? Please describe.**
No problem, but we should base our pypi things off of the current accepted standard for packaging.
Distutils will go away at some point: https://bugs.python.org/issue41282

**Describe the solution you'd like**
Update all setup scripts to use setuptools instead of distutils.

**Describe alternatives you've considered**
None

**Comment by amaltaro** [comment]
Closed by https://github.com/dmwm/WMCore/pull/9874
Erik, please reopen it if I'm wrong.
