### ISSUE TITLE
Remove PhEDEx dependency from DBS3Reader

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9869]
**Impact of the new feature**
WMAgent, Global WorkQueue and one of the CRAB services (TaskWorker?)

**Is your feature request related to a problem? Please describe.**
It's a step required to migrate from PhEDEx to Rucio.

**Describe the solution you'd like**
The DBS3Reader services module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py

initializes a PhEDEx client instance during its initializing, thus having a hard dependency on the PhEDEx service (in order to provide a transparent data location either through DBS or PhEDEx).

This is confusing and I'd suggest to completely remove it (instead of replacing it by the Rucio module). So, once we make this change, we need to make sure that services calling:
```
def listFileBlockLocation(self, fileBlockNames, dbsOnly=False):
def listDatasetLocation(self, datasetName, dbsOnly=False):
```

without `dbsOnly=True`, will need to be updated as well and possibly have their own instance of the Rucio client/wrapper, using the Rucio object to figure out the data location (instead of relying on DBS3Reader).

**Describe alternatives you've considered**
Replace the PhEDEx functionality within DBS3Reader by Rucio...

**Additional context**
none

**Comment by belforte** [comment]
Do we want to start by calling PhEDEx in those two methods, so that we can put this in quickly ? E.g. in CRAB we already have code which calls Rucio data location directly bypassing `listFileBlockLocation`, At this point I am only worried about making the transition as transparent as possible, not about resurrecting older code.

**Comment by amaltaro** [comment]
I guess you meant Rucio(?)
Yes, that's the alternative I have mentioned. But I would only chase that option if we see that the needed changes are too much, otherwise I'm afraid we might leave with Rucio client within DBS for another 10 years...

**Comment by belforte** [comment]
I fully agree on not having Rucio client withing DBS client !!!!  We may simply be trying to say same things in different ways. I think I misunderstood what you wrote initially. Sorry.  Again, goal is clear, is only a matter of details in how to deal with the transition.
One way is:
* at some point, after all data locations are solidly in Rucio's side, there will be a new version of DBS3Reader w/o PhEDEX and we rebuild with it, deploy new services in production and then turn off PhEDEx.,
I was wandering if we can have code which works even if PhEDEx is down as long as it does not use it. That's all.

**Comment by amaltaro** [comment]
Changes are deeper than what I expected and we have only two options here:
1) remove completely remove the PhEDEx-related code from DBS3Reader; and deal with those outside of this module on the client side
2) replace PhEDEx-related code by Rucio.

I'm working on option 1, but it affects a few other DBS3Reader APIs and our code (WMCore/CRAB) will need to be carefully verified to make sure we have the expected data structure.

@belforte let me know if you have any concerns. I should have a first PR ready by tonight.

**Comment by belforte** [comment]
I am happy with 1. I believe CRAB code is ready for that. But of course will test.
