### ISSUE TITLE
Integrate LFN2PFN for Rucio

### ISSUE THREAD

**Issue by dciangot** [dmwm/WMCore#9873]
**Impact of the new feature**
At least CRAB

**Describe the solution you'd like**
Integrate  https://rucio.readthedocs.io/en/latest/api/rse.html#rucio.client.rseclient.RSEClient.lfns2pfns into Rucio WMCore class

**Additional context**
CRAB ticket: https://github.com/dmwm/CRABServer/issues/6102

**Comment by dciangot** [comment]
We might have a problem for this integration.

I did some tests, and, in particular for some CRAB code part, we need a complete 1:1 substitution, meaning that the lfn format is like: `/store/user/dciangot/....` without any notion of Rucio "scope".

Instead I see in Rucio code that the scope has to be always specified https://github.com/rucio/rucio/blob/bfa9af321b29a8843e75edd40e7b86183a1fbd7c/lib/rucio/web/rest/webpy/v1/rse.py#L434

@amaltaro am I missing something here?

To reproduce the problem one can use this(*) with this wmcore branch (**)
(*)
https://gist.github.com/dciangot/acc816f29ba714a840d8b4852698e7fa
(**)
https://github.com/dciangot/WMCore/tree/lfn2pfn

**Comment by amaltaro** [comment]
@dciangot sorry for the delay Diego. I'm afraid I'm not the best person to answer your question, it goes into the internals of Rucio and from the API signatures, I don't see scope anywhere.

**Comment by klannon** [comment]
Is this a question for @ericvaandering or @nsmith-?

**Comment by dciangot** [comment]
Yeah, I think it is RUCIO internal too... I'm trying to go ahead specifing scope everywhere. So far looks like a minor problem, with minor changes needed on CRAB side. 
I'll  keep you posted after some tries.

**Comment by nsmith-** [comment]
Yeah this is unavoidable: rucio considers a DID as the tuple `scope, name` whereas CMS has considered a LFN just a path. To bridge the gap, there are essentially to classes of LFNs: centrally produced LFNs, which always have scope `cms`, and user-produced LFNs, which *must* have a path matching `/store/user/rucio/{name}/...` and corresponding scope `user.{name}`, enforced [here](https://github.com/ericvaandering/rucio/blob/cms_nano2/lib/rucio/common/schema/cms.py#L480). You could bridge the gap by parsing the LFN for this, if you are sure it is a Rucio-cataloged LFN, and it should be robust.

**Comment by nsmith-** [comment]
For legacy data, since you know it falls under the traditional TFC, you can just set the scope to `cms`, although if it ever passes through [this validation](https://github.com/ericvaandering/rucio/blob/cms_nano2/lib/rucio/common/schema/cms.py#L493) it will fail. Perhaps we can change it to `lfn.startswith('/store/user/rucio')` @ericvaandering ?

**Comment by ericvaandering** [comment]
Well I'd rather not. /store/user/dciangot is NOT a valid rucio DID regardless of the scope. If Diego knows he's dealing with something outside of Rucio I'd rather he figures out what the PFN for /store/user/rucio/dciangot is and removes the /rucio/ with a substitution.

**Comment by dciangot** [comment]
wait, maybe my message was misleading.. I of course meant to translate a valid Rucio DID so /store/user/rucio/dciangot, but without knowing necessary which user scope to use.

If I understand the solution proposed by Nick, a solution would be to use the cms scope, but that validation would make it unusable for whatever lfns starts with `/store/user/` 

In other words, while before I could ask Phedex to apply TFC to an lfn without knowing a scope, this would not be the case anymore, if I understand correctly

**Comment by nsmith-** [comment]
In your example, it was `/store/user/dciangot/...` which is not valid in Rucio. If you meant to have an example LFN like `/store/user/rucio/dciangot/...` then you can parse this string to extract the username and fill the scope as `user.{name}`.

**Comment by dciangot** [comment]
yeah, in fact is not a major problem so far, my question was if one can avoid this `user.{name}` thing, but the answer is no if I got it right.. 
We should be fine but I just wanted to be sure that the "apply the TFC to whatever lfn I pass" is not available in anyway other than extracting the username somehow.

**Comment by amaltaro** [comment]
@dciangot Diego, I might have lost track of this. Are you still working on this issue?

**Comment by dciangot** [comment]
@amaltaro no, you did not lost anything. Just resumed it yestarday and tested the PR on my dev crab instance.

I think that it still need some review though, so I opened a draft PR.

**Comment by amaltaro** [comment]
Thanks for the update, Diego.
