### ISSUE TITLE
Clean up SetupCMSSWSetup step from unused applyPSetTweak method and check were tweak from ConfigCache is used at otherwise

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#9878]
**Impact of the new feature**
[CMSSWStepSetup](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L770-L772) tries to apply an inexistent method when psetTweak is `not None` in the configuration.

This `psetTweak` parameter is not set anywhere and is always `None` though, which is why we never get an exception message here at present.
This is the file that CMSSWFetcher fetches from ConfigCache [HERE](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/CMSSWFetcher.py#L57) though, meaning we are apparently not using the psetTweak file created by TweakMaker and written in ConfigCache at least in this runtime script. Rather, we the script uses the WMLoad and  WMBS Job objects to create the tweaks that are applied at runtime.

**Is your feature request related to a problem? Please describe.**
This is related to #9808.

**Describe the solution you'd like**
We should make 100% sure this isn't used neither here nor in the T0 and simply get rid of this part. Where is the [pset tweak from ConfigCache](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/CMSSWFetcher.py#L57) used? Do we still need this? Can we get rid of it?

**Describe alternatives you've considered**
Alternative is leaving this code as is, which is the current situation

**Additional context**
You can find some notes here:
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime#notes-on-the-code

**Comment by amaltaro** [comment]
Kenyi, please go ahead and create a PR removing it. If code doesn't crash, it means we never call that, so it should be safe to delete that TweakAPI.
