### ISSUE TITLE
MSOutput/MSRuleCleaner: Delete general NonCustodial (Disk) rules once the Custodial (Tape) rule is created. 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9880]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
The Rucio Rules  generated by the WMAgents related to NonCustodial data placement should be deleted at some point. The suggestion made during the Rucio Transition meeting was to have this done by means of some of the Micro services. Currently the one we can use as a first stage implementation should be MSOutput. But since this way we start putting too much actions in one micro service we may end up with a `mini` instead of a `micro` service, so we decided to separate the tasks conceptually and on a later stage whatever was developed in MSOutput related to data placement to stay in MSOutput, and whatever is developed related to rule deletion (eventually also including block level deletions) to go into a separate new service called MSRuleCleaner.

**Describe the solution you'd like**

The currently discussed strategy was  to have the General NonCustodial (disk) rules created by WMagent  to be deleted as soon as  the Custodial (Tape) rule is created. The Rucio internal mechanism to protect from data loss  can be relied on and to make the request for rule deletion as soon as the Tape rule is created and not caring at all about rule satisfaction (this  should be Rucio's business), or we can double protect ourselves and use the child rule mechanism, i.e. using the following logic:
   * For every each DID that  we  are about to crate the Custodial rule we find (eventually query Rucio for that) the relevant Noncustodial rule created 
   * Create the Custodial Rule  as a child rule to the NonCustodial one, so that Rucio should consider keeping both copies of the dataset (Rucio  container) from this rule until the child rule is  satisfied (Tape transfer completed) and only then deleting the parent Rule

Given that the Tape data placement happens when the workflow is in the `closed-out` state, it means that the disk container rule shall be deleted in the same `closed-out` state. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by amaltaro** [comment]
Another alternative to deal with these block-based rucio rules (created by WMAgent, against the origin site), would be to implement this logic in the CherryPy thread archiving workflows (such that we do not leave any data behind), something like:
1. find all the block-level rules that match
```
u'did_type': u'DATASET',
u'account': u'wma_prod',
where the did name would have a wildcard to match all the blocks (how can we do so???)
```
2. delete all those rules if workflow is going to `aborted-archived | rejected-archived`
3. if workflow is going to `normal-archived`, then we need to make sure that MSOutput has properly created all the container-level rules. For that, proceed as:
  * query MSOutput (once it gets implemented) and fetch the mongodb record for the workflow
  * evaluate whether the `transferStatus=done`, if so, delete all the block-level rules; else, keep this workflow not-archived and retry in the next cycle.

I believe I saw a way to fetch all the rules provided a did_name with regex, just need to find what that is and how to use.

**Comment by todor-ivanov** [comment]
I am still more in favor of creating it as a separate Micro Service. And following our short chat with @amaltaro a minute ago, I would formulate a short step by step description of the actions the component would need to perform so based on that we can discuss the the technical details. Here it follows:
   * Start a separate MS thread and let it be managed by MSManager as for the rest of the Micro Services
   * Start querying Reqmgr for all the workflows in the given statuses `['announced', 'aborted-completed', 'rejected']` and create 2 different paths for those:
      * The ones that are about to be `archived` from status `announced`, they have already been processed by MSOutput and we have records about the container level rules in the MSOutput database. So for them we may decide either to query MongoDB directly (in case the MSOutput and MSRuleCleanup services live in the same VM or container instance - because MongoDB is still local but not centralized), or to use the MSOutput Rest Info interface, and parse the output. 
      * The ones that are about to be `archived` from status `aborted` or `rejected`, we  must query Rucio with the regexp Alan is talking about, so we can fetch the list of exiting block level rules related to a given DID.
   * Once we have a properly created list of block level rules delete those from Rucio
   * Move the workflow status to the proper `archived-*` state - will need a change in the CherryPy thread currently dealing with that [1]


[1]
https://github.com/dmwm/WMCore/blob/5961d2229b1e548e58259c06af154f33bce36c68/src/python/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py#L101

**Comment by todor-ivanov** [comment]
@amaltaro we should think over how to deal with the fact that `MSOutput` is also considering workflows in status `['announced']` too. So we should  try to somehow avoid the inevitable race condition here.

**Comment by amaltaro** [comment]
Thanks Todor. And here is the algorithm we have just discussed:
1. get workflows in `announced` status
2. skip Resubmission workflows, i.e., move them straight to `normal-archived` (because rule deletion will be done on the parent/original workflow). 
3. for those workflows in announced, fetch their mongo output record via REST calls
4. IF the mongodb record does not exist, or it's in `transferStatus: pending` , skip this workflow until the next cycle and move to the next workflow
5. IF mongodb record exists and it’s in `done` transfer status, proceed with the next steps like...
6. loop through all the output datasets, fetching block-level rules against `wma_prod` rucio acct
7. delete all those block rules (continuing with deletions even if some deletion requests fail). IF any deletion failed, keep this workflow in the same status. ELSE - if every single rule deletion call succeeded - then move this workflow status to `normal-archived`

For workflows in `rejected`, those can likely go straight to `rejected-archived`.
For workflows in `aborted-completed`, those can likely go straight to `aborted-archived`.
We could add a grace time here such that we keep such workflows in that status for a bit longer, especially those in `aborted-completed`, but this might be a complication that does not pay off...

**Comment by klannon** [comment]
Sorry if I'm cluttering this issue up, but I don't see any mention of cleaning up the rules on the input.  Does that happen in another MS?

**Comment by todor-ivanov** [comment]
Hi @klannon , yes indeed they are not mentioned in the current construction of this MS. I am pretty sure we can include whatever cleanup we need in this service and I agree this is the right place to do so, but for the rules from MSTransferor I am not sure if  we had a firm decision if they should be purged from here.

**Comment by klannon** [comment]
OK.  I'm fine if we focus on the output rules first and then evaluate the input rules.  I just wanted to make sure it wasn't forgotten.  It sounds like it wasn't.  Thanks!
