### ISSUE TITLE
Perform clean-up of WMCore dependencies after WMArchive migration

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9887]
**Impact of the new feature**
Clean-up WMCore dependency

**Is your feature request related to a problem? Please describe.**
Not really, but it would be nice to clean-up WMCore once we migrate WMArchive.

**Describe the solution you'd like**
provide a fix to
https://github.com/dmwm/WMCore/blob/master/setup_dependencies.py#L14

**Describe alternatives you've considered**

**Additional context**

**Comment by amaltaro** [comment]
Thanks for creating this issue, Valentin.
