### ISSUE TITLE
make 1.3.6.crab branch py 2.6 compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#9896]
@mapellidario @amaltaro  can you please port this
https://github.com/dmwm/WMCore/commit/4ec90a8d7f2e1902e37003f9391252cab43f08bc#diff-35b2d48eaf9f595cbd8b5a31931cb2cf
(and possibly other related fixes)
to the 1.3.6.crab branch and create a new tag ?

We have users who use CRAB to run old SL5 CMSSW versions on SL6 containers and they have python 2.6, see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5786/1/2.html

thanks. @ddaina when this is done we'll need to rebuild TaskWorker with the new tag

**Comment by amaltaro** [comment]
@mapellidario Dario, could you please check that crab branch (1.3.6_crab) and find all the places evaluating the python version in a non py26/py27/py3 compatible way? Once you have those, please create a PR for the 1.3.6_crab branch.

@belforte I'm afraid we will have to have a wider discussion on this topic in the coming weeks. WMCore is moving towards the decoupling of CMSSW environment and WMCore stack. That will give us freedom to drop support to python2 in 2021 (provided that all the external services like DBS/T0/WMArchive/CRAB/etc are python3 compatible). Perhaps it could be a topic to be discussed in the CMS Week.

**Comment by belforte** [comment]
@amaltaro in a way such a decoupling is a dream coming true. I guess that we will simply need to do the same in CRAB. In the end the job wrapper uses WMCore methods exactly to deal with scram and CMSW env. The worst it can happen is that there has to be a proper version on python on CVMFS. Surely would have been easier years ago when there was much more (expert) manpower available for CRAB. With me doing the coding.. well.. will have to see.

**Comment by mapellidario** [comment]
Dear Alan and Stefano, I looked how we check for the version of python interpreter in WMCore in `1.3.6_crab` branch.

#### Not py2.6 compatible

There is only one use that is not py2.6 compatible and is the usual one, as suggested by Stefano.

`src/python/WMCore/Configuration.py`
```python
PY3 = sys.version_info.major == 3
```

As requested, I opened #9902 to address this issue.

#### py2.6 compatible

Then I collected the following **py2.6 safe** checks

`bin/adhoc-scripts/workflowCompletion.py`
```python
sys.version_info[:2]
```

`src/python/WMCore/Database/ipy_profile_couch.py`
```python
pyver = sys.version.split('\n')[0]
```

`src/python/WMCore/Services/pycurl_manager.py`
```python
sys.version.startswith('3.')
```

`src/python/WMCore/Services/Requests.py`
```python
sys.version.startswith('3.')
```

`src/python/WMCore/WMSpec/Steps/Executors/DQMUpload.py`
```python
sys.version_info[:3]
```

`src/python/WMCore/Wrappers/JsonWrapper/JSONThunker.py`
```python
sys.version.startswith('3.')
```

`test/data/ReqMgr/validate-test-wfs.py`
```python
 sys.version_info[:2]
```

**Comment by belforte** [comment]
thanks Dario

**Comment by belforte** [comment]
this was fixed and new tag for crab created by Alan : https://github.com/dmwm/WMCore/pull/9902#issuecomment-689808933
@amaltaro you can close
@ddaina please rebuild current TW version with WMCore  1.3.6.crab2 and deploy in production. No need to go through testbed for this.

**Comment by belforte** [comment]
@ddaina when new TW is active, please send a mail to the users of old data, to make them happier
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5786/1/2.html

**Comment by amaltaro** [comment]
Thanks, I'm closing this issue then.
