### ISSUE TITLE
Provide proper metrics for web based services

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9939]
**Impact of the new feature**
Based on recent incident [INC2542764](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2542764) with low service performance of Python based services on k8s it would be extremely helpful to provide proper set of metrics from service stack. Since all cmsweb Python based services (DBS, ReqMgr2, CRAB etc.) are based on WMCore codebase it is natural to implement service metrics in WMCore rather in upstream services. This will allow proper monitoring of web services.

**Describe the solution you'd like**
Extend [ProcessStats.py](https://github.com/dmwm/WMCore/blob/master/src/python/Utils/ProcessStats.py) metrics to include the following
- number of requests
- status code stats
- response time of request
- number of connections
- number of open file descriptors
- if DB is in use DB related stats

**Is your feature request related to a problem? Please describe.**
Please see this incident discusssions [INC2542764](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2542764)

**Describe alternatives you've considered**
None, currently we run our services without proper knowledge how they behave, what is their throughput and how the perform under production load

**Additional context**
Once metrics are added to [ProcessStats.py](https://github.com/dmwm/WMCore/blob/master/src/python/Utils/ProcessStats.py) we need to modify WMCore WebTools and REST interface to add `/metrics` or `/status` end-points and enable this by default that it would not be required in upstream code to change anything in order to have them. Once they are available we can setup proper exporter (code should be developed in CMS Monitoring group) and integrate it into Prometheus metrics for each individual service.

**Comment by amaltaro** [comment]
Valentin, sometime ago we have implemented the CherryPy based statistics through:
https://cmsweb.cern.ch/reqmgr2/data/stats

looking at the output, I see lots of potential on the type of data that can be provided, but - apparently - most of them are either empty or reporting a default value.

**Comment by vkuznet** [comment]
yes, this can be good candidate too, please put the pointer to the code as well here that we can refer and look at. I don't mind where/how it will be reported but we do need this for every service, e.g. CRAB, DBS, etc.

**Comment by vkuznet** [comment]
one problem which I immediately see with this output is set of dynamic keys (usual issue with Python dev), while for metrics to be integrated with exporter/Prometheus it is not acceptable. The keys of all keys should be static, i.e. we need a fixed schema. For example, key "Cheroot HTTPServer 139744287237712" or "CP Server Thread-10" are not good. The schema should not rely on dynamic keys which may change from app to app, from one config to another. Instead we need a static schema which will be independent from underlying app and service configuration.

**Comment by amaltaro** [comment]
Valentin, here are the pointers to the code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Server.py#L700
and 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WebTools/Welcome.py#L55

the latter is on the Welcome module, so I think it's of no use to DBS/CRAB services at the moment.

About the data structure, note that we simply return the output of the native cherrypy API. Of course, nothing stops us from applying a data schema on top of that. Only problem is that it can break in future releases (if they change that format).

**Comment by vkuznet** [comment]
@todor-ivanov please review this feature request too which should be fixed by #9940 PR I requested you to review too.

**Comment by vkuznet** [comment]
@amaltaro , please review and decide if we need to proceed or close it. The correspoding PR #9961 and #9940 are still open for 2 years.
